### ISSUE TITLE
Create tree view like structure for docs

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [dotnet/orleans#1000]
Currently if someone wants to find a page in docs, It's not easy and new readers don't know how much they can expect from a page. 
I propose that we link to all sub pages in the index pages. As an example, streaming page in Orleans has a couple of sub pages which readers can access by using the next page links in the pages, It would be much better if they all were visible from the index page.

Everything doesn't have to be in main index however due to lack of a real tree view control here, we can just list level one child pages in each index.

I'm willing to make it happen if everyone agrees.

**Comment by sergeybykov** [comment]
I think this is a very good suggestion. Navigating our doc pages is not intuitive indeed.

**Comment by jthelin** [comment]
**DocToc** is a nice little tool for creating Table of Contents (TOC) jump list for a single document page.
https://github.com/thlorenz/doctoc

I wonder if their is anything similar for building a meta-index of all pages, or if DocToc could be extended in that direction some how?

**Comment by jthelin** [comment]
History in the making:
https://twitter.com/JorgenThelin/status/663452140187201536

**Comment by ashkan-saeedi-mazdeh** [comment]
@jthelin  
DocToc is nice. For the first part in #1054 I did it manually. I wasn't sure if DocToc will mess up with our TOC or not. Should check it out however.

**Comment by sergeybykov** [comment]
I believe this is already covered with the transition to DocFx.
