### ISSUE TITLE
Enable Orleans nuget packages debugging with GitLink

### ISSUE THREAD

**Issue by kowalot** [dotnet/orleans#1001]
As Orleans user I would like to have ability to debug Orleans nuget packages in easy way without too much configuring which should help me understand better how Orleans works and find easier issues in Orleans or in my own code.

Advantages of GitLink over Symbolsource,  are nicely summarized by Oren Novotny on his blog.

https://oren.codes/2015/09/23/enabling-source-code-debugging-for-your-nuget-packages-with-gitlink/

https://github.com/GitTools/GitLink

**Comment by sergeybykov** [comment]
@kowalot Thank you for your suggestion. I tried to publish symbols packages for 1.1.0-beta1 and that was failing with a cryptic error. We'll investigate if GitLink is a better option.

**Comment by kowalot** [comment]
Thanks!

btw. I investigated it a bit more and executed gitlink in Orleans repo directory 

``` sql
gitlink . -d Binaries\Release  -f src\Orleans.sln
```
which can be added to CreateOrleansNugetPackages.bat

and seems that .pdb files are ok.
``` sql

GitLink v2.2.0.0
================

Arguments: . -d Binaries\Release -f src\Orleans.sln -skipverify

No target url was specified, trying to determine the target url automatically
Automatically determine target url 'https://github.com/kowalot/orleans'
Extracting embedded pdbstr.exe
Using provider 'GitHubProvider'
Checking if commit with sha hash 'af29514ec8d1fdbcebbdf03aa4d465c4451ce62c' exists on the repository
Using commit sha 'af29514ec8d1fdbcebbdf03aa4d465c4451ce62c' as version stamp
Found '17' project(s)

Handling project 'ClientGenerator'

Handling project 'Orleans'

Handling project 'OrleansRuntime'

Handling project 'OrleansHost'

Handling project 'OrleansManager'

Handling project 'OrleansProviders'

Handling project 'TestGrainInterfaces'

Handling project 'TestGrains'

Handling project 'Tester'

Handling project 'OrleansAzureUtils'

Handling project 'TesterInternal'

Handling project 'OrleansTestingHost'

Handling project 'OrleansZooKeeperUtils'

Handling project 'OrleansCounterControl'

Handling project 'OrleansEventSourcing'

Handling project 'OrleansSqlUtils'

Handling project 'OrleansCodeGenerator'

All projects are done. 17 of 17 succeeded

Completed in '00:00:01.0119204'

```

**Comment by amamh** [comment]
@kowalot 

That's a great suggestion, I hate having to build Orleans myself and reference its DLL's instead of using NuGet in order to be able to debug the source. I've never heard of gitlink before, it looks like exactly what I want, I will try what you suggested.

It seems like you had to create your own repository for Orleans to be able to use gitlink?

**Comment by kowalot** [comment]
I just forked Orleans repo and generated my own nugets packages for test purposes. It can be done in similar way in main repository.

**Comment by amamh** [comment]
@kowalot then how do you debug the source?

**Comment by sergeybykov** [comment]
@kowalot I'll try run GitLink next time we publish NuGets.

I think it doesn't make much sense to run it on every build as we have dozens of them daily. We have to codesign binaries before publishing. Because of that, the build on the build machine is a preliminary one - it produces unsigned binaries. Then once they are signed, we rebuild the NuGets, but that happens on a dev machine by simply rerunning CreateOrleansNugetPackages.bat. So I think it makes sense for us to run GitLink at that point.

**Comment by sergeybykov** [comment]
BTW, I just successfully published symbols packages for 1.1.0-beta1 to SymbolSource.org. Looks like their infrastructure got fixed.

**Comment by kowalot** [comment]
@sergeybykov I didn't manage to load symbols via symbolssource.org for beta1. Are you sure that everything went well?
I see only something for 1.0.10
https://www.symbolsource.org/Public/Metadata/NuGet/Project/Microsoft.Orleans.Server

Anyone can confirm it works now from symbolssource.org ?

**Comment by amamh** [comment]
@kowalot 
Couldn't get it to work either.

**Comment by sergeybykov** [comment]
That's what it is I think. We didn't update file versions to 1.1.0 in the -beta1 build.

**Comment by veikkoeeva** [comment]
Might be of general interest here: [GitLink is a port of SourceLink](http://blog.ctaggart.com/2014/11/gitlink-port-of-sourcelink-with-command.html). [SourceLink](http://ctaggart.github.io/SourceLink/) is written in F# and hence is .NET and I think more or less cross-platform already (it'd be great to have more F# folks involved in Orleans). :)

I remember chatting with @richorama about his great [Nugot](http://nugot.net/) initiative to provide a trace which files were used to translate which package, to ease auditing and SourceLink made an appearance in the discussion. I can't remember the purpose though.

**Comment by amamh** [comment]
@kowalot 

Did you manage to get it working with 1.0.10?

**Comment by kowalot** [comment]
@amamh Nope I am waiting for valid 1.1.0 version.
@veikkoeeva I would love to see any alternative method which makes things simpler ;) no matter if it's gitlink or any other promissing tool.

**Comment by sergeybykov** [comment]
@kowalot I ran GitLink against the 1.1.0-beta2 binaries. How do I verify that everything worked fine? That command seems to have succeeded.

**Comment by kowalot** [comment]
@sergeybykov I can't see .pdb files in .nupkg. I checked 1.1.0 and 1.1.0-beta2
The .pdb file has inside searchable string like SRCSRVTRG=https://raw.github.com 

Good example of gitlink integration is *Nest* nuget package ( .NET client for Elasticsearch).
.PDB is inside with mentioned link to commit of the build.
Having such package you have an instant config to step into the nuget package source code hosted on github

**Comment by sergeybykov** [comment]
Pdbs are in the *.symbols.nupkg packages that went to symbolsource.org. Where does GitLink expect them?

I just published 1.1.0 final packages and was about to run GitLink against that build. Am I doing it wrong?

**Comment by kowalot** [comment]
@sergeybykov  I am not expert in Gitlink. As far as I understand, seems that people configure .nuspec with corresponding .pdb files which are modified by gitlink

https://github.com/elastic/elasticsearch-net/blob/develop/build/Elasticsearch.Net.nuspec
https://github.com/xunit/xunit/blob/master/src/xunit.runner.utility.nuspec

and part of msbuild (https://github.com/xunit/xunit/blob/master/xunit.msbuild)
``` xml
 <Target Name='GitLink'>
    <Warning Condition=" '$(CommitHash)' == '' "
        Text="Skipping GitLink because CommitHash was not specified." />
    <Exec Condition=" '$(CommitHash)' != '' "
        Command='packages\gitlink\lib\net45\GitLink.exe $(MSBuildThisFileDirectory) -f $(SolutionName) -u https://github.com/xunit/xunit -s $(CommitHash)' IgnoreExitCode='true' />
  </Target>
```

Bringing [Oren's blog](https://oren.codes/2015/09/23/enabling-source-code-debugging-for-your-nuget-packages-with-gitlink/):

"After running GitLink, just include the PDB files in your nuspec/main nupkg alongside your dll files and you’re done. Upload that whole package to NuGet (and don’t use the -symbols parameter with nuget pack). This also means that users don’t need to configure a symbol server as the source-indexed PDB’s will be alongside the dll — the location VS will auto-load them from."



but having these files in main .nuspec might not be something what you or some users want to have.

Moreover, when I enabled following symbol source to VS
    http://srv.symbolsource.org/pdb/Public
IDE downloaded .pdb for Orleans.dll v1.1.0 (Timestamp: 2015-12-11 00:48)
i:\SymbolCache\Orleans.pdb\0D1508608F4F4530B762EB39589C5D521\Orleans.pdb 

but the pdb inside has following parameters

SRCSRV: ini ------------------------------------------------
VERSION=2
INDEXVERSION=2
VERCTRL=http
SRCSRV: variables ------------------------------------------
SRCSRVTRG=https://nuget.smbsrc.net/src/%fnfile%(%var1%)/%var2%/%fnfile%(%var1%)
SRCSRVCMD=
SRCSRVVERCTRL=http
SRCSRV: source files ---------------------------------------
SRCSRV: end ------------------------------------------------

And no luck in stepping into Orleans code but in the same program was able to debug elasticsearch lib.

**Comment by attilah** [comment]
Now as we've 1.1.0 released, what do we plan to do with this issue?

**Comment by kowalot** [comment]
I am still trying figure out what's going on in symbolssource deployment.
What for sure worked out that symbolssource returned .pdb.
I see one detail which might be important. Documentation (https://docs.nuget.org/create/creating-and-publishing-a-symbol-package) says:

*"Source files are placed in a separate special folder - src. This folder needs to follow the relative structure of your source repository, because PDBs contain absolute paths to source files used to compile a matching DLL"*

When I build sources tagged 1.1.0   , Microsoft.Orleans.Core.1.1.0.symbols.nupkg has following source  file paths 
src\AssemblyLoader\...
...

whereas solution path is
src\Orleans\AssemblyLoader\...
Considering that .pdb has absolute paths to sources it may generate a problem with locating files in IDE.
WDYT?

**Comment by sergeybykov** [comment]
We switched to publishing symbols to the official Microsoft symbols servers because symbolsource.org has been behaving unpredictably. Looks like there is no need to use GitLink for us anymore.
