### ISSUE TITLE
The Reminders Protocol and ReminderException 

### ISSUE THREAD

**Issue by shayhatsor** [dotnet/orleans#1009]
When someone implements a grain with reminders, they're definitely not expecting a  `ReminderException` which they can't do anything about but wait for a random amount of time for the local cache to refresh itself from the global reminders store. 

Currently,  `ReminderException`  is thrown:
1) [here](https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/ReminderService/LocalReminderService.cs#L162) - saying that reminder upsert failed because of a bug in the underlying reminders provider that hasn't implemented upsert atomically. In this situation, throwing a `ReminderException` can mislead the user into thinking it's part of the correct reminders protocol.
2) [here](https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/ReminderService/LocalReminderService.cs#L204) - when there's a duplicate activation of a grain, this is supposed to prevent one of the activations from deleting a reminder that the other has just changed. I'm not sure it does, because a grain which is not the "owner" might still delete the reminder if its local reminders cache was just updated

I believe that we should do one of the following:
 1) Check ETag on every action. Then when a reminders race condition surfaces in a silo, it should commit suicide. Maybe throw a `DuplicateActivationException` ? definitely not a `ReminderException`
 2) Don't check ETag on deletes. a grain that must be sure it doesn't have a duplicate activation will handle it itself, with whatever mechanism it desires. This is a well known limitation in Orleans.

This issue is about providing a grain using reminders an expected well defined behavior. It can be configurable per grain.

**Comment by gabikliot** [comment]
Here are the explanations of the current semantics and the rational behind them:
https://github.com/dotnet/orleans/issues/637#issuecomment-12415240
https://github.com/dotnet/orleans/pull/985#issuecomment-154920416
