### ISSUE TITLE
Bug when subscribing to stream from timer callback

### ISSUE THREAD

**Issue by yoniabrahamy** [dotnet/orleans#1010]
Hello everyone,
I'm having an exotic issue in Orleans.
I have a grain that has a timer, and on the timer callback function the grain subscribes to a stream.
When I subscribe with a an older token (that is in the QueueCache), I expect the grain to start consuming the messages immediately (this happens when I subscribe to a stream regularly). However, when the subscription happens inside the timer callback, the consuming does not start immediately, but only after another message enters the stream (another message has been produced).

Currently I have a workaround for this problem: In the timer callback, I call `GrainFactory.GetGrain(this.GetPrimaryKey()` (Basically calling to myself) and then with the grain i received I call the function that subscribes to the stream.

Unfortunately, I do not have enough time to look deeper into the problem (hence the workaround), but I would love to get some input if anyone has an idea why this happens.

Cheers.

**Comment by jason-bragg** [comment]
This is happening because the timer calls are not subject to message interleaving semantics, which allows for a race condition wherein stream infrastructure calls can sneak in before the grain is ready.
From: http://dotnet.github.io/orleans/Advanced-Concepts/Timers-and-Reminders.
>"Each invocation of asyncCallback is delivered to an activation on a separate turn and will never run concurrently with other turns on the same activation. Note however, asyncCallback invocations are not delivered as messages and are thus not subject to message interleaving semantics. This means that invocations of asyncCallback should be considered to behave as if running on a reentrant grain with respect to other messages to that grain."

**Comment by gabikliot** [comment]
Jason, do you understand the concrete race condition that causes that?
Do you think that the call sneaks in here: https://github.com/dotnet/orleans/blob/master/src/Orleans/Streams/Internal/StreamConsumer.cs#L92, between `pubSub.RegisterConsumer` and `myExtension.SetObserver`?

If this is indeed the race, then it is not specific to timers. The same will happen in reentrant grains, and the fix is not to change timers reentrancy, but rather make these two lines atomic (there are multiple techniques to do that, does not really need a lock or synchronization primitive). If this is indeed the race, it should be easy to fix. I would love to see repro first.

**Comment by jason-bragg** [comment]
>"If this is indeed the race"

I've not identified the race condition, nor am I convinced there is only one.  My initial investigation suggested the IStreamConsumerExtension.GetSequenceToken call.

>"is not specific to timers"

I am of the opinion this is an issue with timers and reentrant grains.

>"I would love to see repro first."

Agreed.

**Comment by gabikliot** [comment]
>My initial investigation suggested the IStreamConsumerExtension.GetSequenceToken call.

Can you elaborate?

**Comment by jason-bragg** [comment]
@gabikliot 
?"I would love to see repro first."

More broadly, we're lacking testing around streaming using reentrant grains.

**Comment by jason-bragg** [comment]
@gabikliot 
>Can you elaborate?

The subscription process generates an IStreamConsumerExtension.GetSequenceToken call to the grain.  When following normal message interleaving semantics, this call will not be processed until the current grain call (and the subscription process) is complete.  I believe this call is sneaking in before the subscription process is complete.  It may be sneaking in at the place you pointed out, but I've not dug that deep.

**Comment by gabikliot** [comment]
@yoniabrahamy , we belie we solved this issue via #1261.
Can you please try the original scenario now, with latest master?

**Comment by yoniabrahamy** [comment]
@randa1 passing the torch to you on that subject.

**Comment by gabikliot** [comment]
I will close this issue for now, as we believe we fixed it in #1261. Feel free to re-open is you find otherwise.
