### ISSUE TITLE
Orleans is not regenerating orleans.codegen.cs

### ISSUE THREAD

**Issue by juancumba** [dotnet/orleans#1011]
I have a grain Interface like this:

    public interface ITitulo : IGrainWithStringKey
    {
    Task<TituloOrleans> GetTitulo();
    Task NuevaCotizacion(DateTime fechaHora);
    Task<CotizacionOrleans> GetCotizacionRealTime();
    }

and I changed one of the methods to:

    Task NuevaCotizacion(CotizacionOrleans nuevaCotizacion);

but the auto-generated code its not recompiling and when I try to build the proyect says:
> 'TituloFactory.TituloReference' does not implement interface member 'ITitulo.NuevaCotizacion(CotizacionOrleans)'

What I need to to for regenerate the orleans.codegen.cs??

**Comment by sergeybykov** [comment]
What version are you running? Try deleting the content of `orleans.codegen.cs` and recompile.

**Comment by juancumba** [comment]
Im running Microsoft.Orleans.Core and Interfaces version 1.0.10 under a .net project with framework 4.5.2.

I tried deleting both, the file and the content, and never the code is regenerated. I tried too cleaning the solution, rebuilding and other things and nothing happened.

**Comment by sergeybykov** [comment]
If you delete the content of the file, you don't get the "'TituloFactory.TituloReference' does not implement interface member 'ITitulo.NuevaCotizacion(CotizacionOrleans)'" error, do you? Do you get anything generated there?

Also, look at the Output window. It may provide more clues.

**Comment by juancumba** [comment]
Yes, when I delete the content of the file the project compile OK but then when I try to use the silo it says:

> Excepción no controlada: System.InvalidOperationException: Cannot find generated
 factory type for interface 'IOL.IOrleansGrains.Titulos.ITitulo'
>   en Orleans.GrainFactory.MakeFactoryDelegate(Type interfaceType, String method
Name, Type delegateType)
>   en Orleans.GrainFactory.MakeCaster(Type interfaceType)
>   en System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Fu
nc`2 valueFactory)
>   en Orleans.GrainFactory.Cast[TGrainInterface](IAddressable grain)
>   en Orleans.GrainFactory.GetGrain[TGrainInterface](String primaryKey, String g
rainClassNamePrefix)

And output windows doesn't say nothing interesting:
> 1>------ Build started: Project: IOL.LogicTier, Configuration: Debug Any CPU ------
> 1>  IOL.LogicTier -> C:\Git\corenet\IOL.LogicTier\bin\Debug\IOL.LogicTier.dll
> 2>------ Build started: Project: IOrleansGrains, Configuration: Debug Any CPU ------
> 2>  IOrleansGrains -> C:\Git\corenet\IOL.Framework\Orleans\IOrleansGrains\IOrleansGrains\bin\Debug\IOrleansGrains.dll
> ========== Build: 2 succeeded, 0 failed, 4 up-to-date, 0 skipped ==========

**Comment by sergeybykov** [comment]
>Yes, when I delete the content of the file the project compile OK 

Do you see generated code in `orleans.codegen.cs` after compilation?

**Comment by juancumba** [comment]
No... still empty. I believe this is problem... It never regenerate the code. Someway to force this regeneration?

**Comment by sergeybykov** [comment]
Did you add https://www.nuget.org/packages/Microsoft.Orleans.Templates.Interfaces/1.0.10 to the project?

**Comment by juancumba** [comment]
I uninstalled the library and installed again and it started working again :S

I don't know what can happened but thanks a lot for your help Sergey!

**Comment by sergeybykov** [comment]
You are welcome, Juan!
