### ISSUE TITLE
Orleans.Streams.QueueCacheMissException: Item not found in cache

### ISSUE THREAD

**Issue by andycwk** [dotnet/orleans#1012]
Hi,

I've added streams into my solution and keep receiving the following exception, this was happening a lot in dev - but updating to 1.1.0-beta1 seemed to have resolved the issue.

I've now deployed into QA and the issue has reappeared!

The big issue for me is that once this exception occurs, the stream agent appears to stop pushing any more events out to the stream consumers!

Any thoughts on how I can debug this further, or even how I can detect the issue and restart processing?

```xml

    <Message>EventName=&quot;MessageEvent&quot; Message=&quot;[2015-11-10 21:23:38.558 GMT    15	ERROR  	0	WorkspaceHistoryNotificationsBuilder *grn/6A8E938A/425f28bdbc14b4aa9ba56e004541769d030000006a8e938a-0x3C5E6574	]	!!!!!!!!!! Item not found in cache.  Requested: [EventSequenceToken: SeqNum=35, EventIndex=0], Low: [EventSequenceToken: SeqNum=37, EventIndex=0], High: [EventSequenceToken: SeqNum=37, EventIndex=0]	
Exc level 0: Orleans.Streams.QueueCacheMissException: Item not found in cache.  Requested: [EventSequenceToken: SeqNum=35, EventIndex=0], Low: [EventSequenceToken: SeqNum=37, EventIndex=0], High: [EventSequenceToken: SeqNum=37, EventIndex=0]
   at Orleans.Providers.Streams.Common.SimpleQueueCache.InitializeCursor(SimpleQueueCacheCursor cursor, StreamSequenceToken sequenceToken, Boolean enforceSequenceToken)
   at Orleans.Providers.Streams.Common.SimpleQueueCache.GetCacheCursor(Guid streamGuid, String streamNamespace, StreamSequenceToken token)
   at Orleans.Streams.PersistentStreamPullingAgent.&lt;DoHandshakeWithConsumer&gt;d__1e.MoveNext()&quot; TraceSource=&quot;WaWorkerHost.exe&quot;</Message>

```

**Comment by jason-bragg** [comment]
What stream provider are you using?  AzureQueueStreamProvider?  A PersistentStreamProvider with a custom adapter? ...
Are you using implicit or explicit subscriptions?

This looks like it is occurring during stream subscription.  The expected behavior in this case is for the consumer to be notified of the failure via the OnErrorAsync.  This indicates that the subscription failed to rewind to the requested sequence token.  After notifying the consumer, unless the consumer takes some action (unsubscribe, resume subscription using a newer token, ..), the subscription will be brought current so that any new events generated on the stream will be received by the consumer.  Is your consumer not seeing any events even when new events are being generated on the stream?

**Comment by andycwk** [comment]
Hi,

Sorry should have included that info I'm using the AzureQueueStreamProvided as is out of the box with implicit subscriptions.

The grain basically collects a batch of notifications and then pushes them into Azure storage in a batch.

As you can see, I'm not actually passing a token during initialisation - should I be?

Nothing is being logged via the OnErrorAsync event either, and once the exception is raised I see not more events for the grain - I have the stream keyed to the user performing activities that generate the notifications :(

```c#
 [ ImplicitStreamSubscription( "WorksopaceHistoryNotifications" ) ]
  public class WorkspaceHistoryNotificationsBuilder : BaseIndexingGrain<...>,
    IWorkspaceHistoryNotificationsBuilder, IAsyncObserver< WorkspaceEvent >
```

```c#
    public override async Task OnActivateAsync()
    {
      logger = base.GetLogger( string.Format( "{0} {1}", GetType().Name, base.IdentityString ) );
      logger.Info( "OnActivateAsync" );

      var streamProvider = GetStreamProvider( StreamProvider.AzureQueueProvider );

      var handler = streamProvider.GetStream< WorkspaceEvent >( this.GetPrimaryKey(), StreamNamespaces.WorksopaceHistoryNotifications );

      await handler.SubscribeAsync( this );

      await base.OnActivateAsync();
    }
```

```c#
    public async Task OnNextAsync( WorkspaceEvent detail, StreamSequenceToken token = null )
    {
      var historyDetail = await new WorkspaceHistoryDetail().BuiltFrom( detail, GrainFactory );

      await Add( new IndexJob< WorkspaceHistoryDetail, object >( historyDetail, null ) );
    }

    public Task OnCompletedAsync()
    {
      return TaskDone.Done;
    }

    public Task OnErrorAsync( Exception ex )
    {
      logger.Error(0,ex.Message, ex);
      return TaskDone.Done;
    }
```

**Comment by jason-bragg** [comment]
Peculiar, this looks fine.

More questions:
May I see your stream provider configuration (minus DataConnectionString of course)?
>The grain basically collects a batch of notifications and then pushes them into Azure storage in a batch.

How are you writing these batches?

**Comment by andycwk** [comment]
Sure :)

I stream registration is in code so I can grab the connection string from the Role Environment...

```c#
      config.Globals.RegisterStreamProvider<SimpleMessageStreamProvider>("SMSProvider");
      config.Globals.RegisterStreamProvider<AzureQueueStreamProvider>("AzureQueueProvider", new Dictionary<string, string> {
        {"DataConnectionString", connectionString},
        {"DeploymentId", "streams"}
      });
```

The heavy lifting is done in the base grain..
I basically add the entry into a list in state and then set up a timer (and reminder to bring the grain back on line in failure) and then leave!

```c#
    protected async Task Add( IndexJob< TDetails, TExtra > indexJob )
    {
      State.PendingIndexJobs.Add( indexJob );

      if( timer == null )
        timer = RegisterTimer( BatchIndexTrigger, null, TimeSpan.FromSeconds( 1 ), TimeSpan.FromSeconds( 1 ) );

      if( reminder == null && ( await GetReminders() ).Count == 0 )
        reminder = await RegisterOrUpdateReminder( reminderKey, TimeSpan.FromMinutes( 10 ), TimeSpan.FromMinutes( 10 ) );
    }
```

Later the BatchIndexTrigger is fired that builds the batch up and fires it off to Azure Storage with the following..

```c#
    var result = await searchServiceClient
        .Indexes.GetClient( indexName )
        .Documents.IndexAsync( new IndexBatch< TIndexDocument >( indexBatch ) );
```

**Comment by andycwk** [comment]
I suposse to build up a complete picture.. on the producer side..

```c#
    private IAsyncStream< WorkspaceEvent > GetHistoryStreamFor( Guid userId )
    {
      return streamProvider.GetStream< WorkspaceEvent >( userId, StreamNamespaces.WorksopaceHistoryNotifications );
    }

...
 await GetHistoryStreamFor( userId ).OnNextAsync( new WorkspaceEvent {
            WorkspaceId = details.WorkspaceId,
            EntryId = details.EntryId,
            VersionId = details.VersionId,
            UserId = userId,
            Event = WorkspaceHistoryEvents.NavigatedToFolder,
            TimestampUtc = DateTime.UtcNow,
            FullPaths = new List< string > {"home"}
          } );
...
```

**Comment by jason-bragg** [comment]
>"set up a timer" 

Timers can be an issue in streams.  Not saying it is, as I've not seen how you're using it.  Please see #1010 for more info. 

>"and reminder to bring the grain back on line in failure"

This should not be necessary with implicit subscription, as any event delivery on an implicit subscription will wake the grain up.

>await new WorkspaceHistoryDetail().BuiltFrom( detail, GrainFactory )

What is the grain factory used for here?  If a grain is making grain calls to itself in a grain call, that would be bad.

Even with those nuances, this looks like a bug, but can you try something for me before I start digging into building a repro.

Please test again with this setting added to the azure queue stream provider configuration property bag:
{PersistentStreamProviderConfig.STREAM_PUBSUB_TYPE,  StreamPubSubType.ImplicitOnly}

**Comment by gabikliot** [comment]
I also noticed that the call ` await handler.SubscribeAsync( this );` and the grain implements directly `IAsyncObserver< WorkspaceEvent >`.

**Comment by andycwk** [comment]
Thanks for the continued help guys!

jason-bragg: Will do thought it may be a while as I'm away from the computer for a good few hours. - The reminder is just there to wake the grain to finish processing any outstanding Index Jobs waiting to to Azure - I can't guarantee when a user will next perform an action that will wake the grain via the stream subscriptions :(

gabikliot: It was my understanding from http://dotnet.github.io/orleans/Orleans-Streams/Streams-Programming-APIs that I can implement from IAsyncObserver<> but Orleans still needs a helping hand with handler.SubscribeAsync(...)

**Comment by andycwk** [comment]
The GrainFactory passed into the Built From function is used to call out to entry grains to get additional details used to populate search - no calls to self -- that would defo be bad :)

I suppose a timer could be causing the a double subscription (by running through onActivateAsync again) -wonder if that's where the issue is :|

I might drop a guard clause in to bypass the subscription logic if the grain already has it's handler field populated!

**Comment by jason-bragg** [comment]
@andycwk
>"The reminder is just there to wake the grain to finish processing any outstanding Index Jobs waiting to Azure"

If the grain dies, the outstanding jobs will be lost, right?  If so, there is no point in waking back up until there is more data on the stream.

**Comment by andycwk** [comment]
Ah yes, normally I would agree and also point out that it's a wast of resources!
However, I've got some retry logic buried into the indexing routine that helps with any potential transient errors originating from the search service.

Within the index routine (shown below) that is normally triggered by the timer I first save the grains current state and then proceed to send the index jobs in a batch to the search service.

On return each job can pass/fail - I remove any passing ones and increment a retry counter for the failed ones..

... Excuse the amount of code in the method - I still need to re -factor this bit of code for readability :)

````C#
    private async Task IndexPendingJobs()
    {
      if( State.PendingIndexJobs.Any() == false )
      {
        if( timer == null ) return;

        timer.Dispose();
        timer = null;

        if( reminder == null ) return;

        await UnregisterReminder( reminder );
        reminder = null;

        return;
      }


      var indexBatch = new List< IndexAction< TIndexDocument > >();

      var pendingIndexJobs = State.PendingIndexJobs.ToArray();
      foreach( var indexJob in pendingIndexJobs.Take( 1000 ) )
      {
        if( indexJob.ShouldRemove )
        {
          indexBatch.Add( new IndexAction< TIndexDocument > {
            ActionType = IndexActionType.Delete,
            Document = BuildDeleteDocumentFor( indexJob )
          } );
        }
        else
        {
          indexBatch.Add( new IndexAction< TIndexDocument > {
            ActionType = IndexActionType.Upload,
            Document = await BuildSearchDocumentFor( indexJob )
          } );
        }
      }
      await WriteStateAsync();

      var result = await searchServiceClient
        .Indexes.GetClient( indexName )
        .Documents.IndexAsync( new IndexBatch< TIndexDocument >( indexBatch ) )
        .OnException( builder => builder.AddObject( indexBatch ) );

      foreach( var source in result.Results.Where( x => x.Succeeded ) )
      {
        State.PendingIndexJobs.Remove( State.PendingIndexJobs.FirstOrDefault( x => x.Key == source.Key ) );
      }

      foreach( var source in result.Results.Where( x => x.Succeeded == false ) )
      {
        var job = State.PendingIndexJobs.FirstOrDefault( x => x.Key == source.Key );

        if( job == null )
          continue;

        job.IndexAttemp++;
        if( ++job.IndexAttemp > 5 )
          ExceptionlessClient.Default
            .CreateLog( GetType().FullName, "Index job not making it into search index" )
            .AddObject( job )
            .AddObject( source )
            .AddRecentTraceLogEntries()
            .Submit();
      }

      await WriteStateAsync();

      await TaskDone.Done;
    }

````

**Comment by jason-bragg** [comment]
@andycwk
Clearly more to it than I'd expected. :)  I just wanted to make sure you weren't doing it for streaming reasons and understood that streams would wake the grain for you.  Sounds like you're on top of it!

**Comment by andycwk** [comment]
Hi Guys,

I've added in the extra configuration switch and I have been hammering the solution locally on my dev machine for the last couple of days - I'm going to deploy to QA today and see how it goes once in the Azure infrastructure!

Thanks for the great help so far with this issue!

**Comment by andycwk** [comment]
Hay gys,

It's been a while - I've had our QA team hammering this stuff and the exception keeps reappearing - each time killing the processing of the stream queues :(

![image](https://cloud.githubusercontent.com/assets/2248787/11270881/5d1e7b42-8eba-11e5-843c-85ce077feb60.png)

**Comment by andycwk** [comment]
Not sure if it's linked - but I'm also getting watchdog failure messages along the lines of 'Watchdog had 2 Health Check Failure(s) out of 2 Health Check Participants.' not ure what the watchdog is watching but though I would mention!

**Comment by gabikliot** [comment]
Can you please provide the full silo log. Need to get more details about watchdog failures.

**Comment by andycwk** [comment]
hmm... Just popped over to the worker role to grab those logs and it appears that the default trace config I have in place has not created any logs :|

I'll tweak and redeploy - I'll send the logs next time I see the watchdog message - but out of interest is there any article that discusses the watchdog?

**Comment by gabikliot** [comment]
There is no article about watchdog.
Watchdog is an internal component that checks the health of other internal runtime components inside the silo and warns when something is wrong. Things like frozen timers, inconsistency in some internal data structures. The log should have details of the individual component that failed the check.

https://github.com/dotnet/orleans/blob/fc0af9079413505de6c5dad928a266fccda74d68/src/OrleansRuntime/Silo/Watchdog.cs

Please produce logs at Info level.

**Comment by andycwk** [comment]
Hi, I've tried to create the logs at info level but when I RDP into the worker role they are not in bin folder where I expected them to be - any suggestions?

Cheers!
