### ISSUE TITLE
Custom LogConsumer doesn't receive any calls

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#1014]
Stumbled over some strange situation with logging.I want to disable Trace and file logging and call my own consumer only.
Initialization code is the following, being called in bootstrap provider
```
	var cfg = new NodeConfiguration { TraceFilePattern = null, TraceToConsole = false };
			TraceLogger.Initialize(cfg);
			TraceLogger.LogConsumers.Add(new DrawboardLogger());
```
Can see that I have 3 log Consumers in collection, got none messages from Orleans into my logs =(
Am I doing something wrong or it's a bug?

**Comment by gabikliot** [comment]
I don't think you need the first 2 lines. Just try the last line alone.

**Comment by centur** [comment]
Umm found that my log error level was overridden by Orleans config settings this why in normal case I got no messages - as there were no errors to log. Now it's sorted
