### ISSUE TITLE
Orleans Namespace Convention

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#1025]
It's not so obvious for most of us what is the rationale behind Orleans namespace structure.

For example the file `Orleans\Logging\ILogConsumer.cs` is under namespace `Orleans.Runtime`...

Is that any reason for it? Its a bit confusing for newcomers to get handy on Orleans code since VS automatically creates namespaces based on directories under the project and following the Default Namespace setting on project properties.

So, should we normalize all the projects in order to follow VS conventions or should be just follow as is?

Thanks

**Comment by gabikliot** [comment]
Yes, there was a reasoning behind that.
Basically, the thinking was: put most useful APIs in the one root namespace, `Orleans`. Keep it slim and only for the core programming abstractions, so the new user can  see only what is really required and not all the advanced stuff.
The rest, more advanced stuff, put in derived namespaces. 
Also, don't have to follow Java practice of matching folders to packages. Again, the goal is to make it easier for the user of Orleans: simple stuff is in one namespace `Orleans`, more advanced stuff is in a couple (and not 25) namespaces.

Clearly, this is quite subjective and can be reviewed and changed.

**Comment by galvesribeiro** [comment]
Ok no problem. Lets close this issue and move forward.

Thanks
