### ISSUE TITLE
Coreclr compatibility: Core CLR PerformaneCounters

### ISSUE THREAD

**Issue by KodrAus** [dotnet/orleans#1040]
In relation to #368 , we need an alternative to using ManagementObject to get total physical memory on the machine a Silo is running on.

So far I'm investigating the following ideas:
- Find a cross-platform alternative to the win api queries. A PerformanceCounter in CoreFX, like mono's would be nice.
- Rework the stats so that they're wrapped in a stat class like option types in other languages, so consumers of the stats can deal with the case where the stat isn't available.

In pseudo code the stat class might look something like this:

```
class Statistic<T> {
    Some(T),
    None
}

Some + Some = Some
Some + None = None
None + None = None
```

The stat class could act as a polyfill until .NET Core support catches up if necessary so you get graceful degradation

Any thoughts?

**Comment by gabikliot** [comment]
Just an FYI, we don't really use that physical memory value anywhere in the runtime. We just log in the log, for troubleshooting (mostly to troubleshoot cases when we are under GC pressure). So an easy way to "solve" the problem is just ifndef it all together in CORECLR build.

**Comment by tsibelman** [comment]
I saw that clr-core have PerformanceCounter class do they plan to support this cross platform ?

**Comment by KodrAus** [comment]
@gabikliot Sounds good to me. I'll #ifdef my way to glory and if other machine-specific cross-plat things pop up then it might be worth revisiting.

@tsibelman I asked about it on the CoreFX repo, since mono PerformanceCounters are cross platform so we'll see. I'm sure they will though.

**Comment by sergeybykov** [comment]
I think regardless, we can load a perf counters specific assembly dynamically. Will be very natural when https://github.com/dotnet/orleans/pull/1026 is done.

**Comment by tsibelman** [comment]
Yes but what whould you use in clrcore ?

**Comment by sergeybykov** [comment]
Nothing for now - it won't load, and we'll ignore it.

**Comment by tsibelman** [comment]
It fine for this case but what about all the custom counters you expose right now ?

**Comment by sergeybykov** [comment]
I think one of the ideas in https://github.com/dotnet/orleans/pull/1026 is to make perf counters just one of the optional consumers of the telemetry data, along with statistics tables and various APM solutions.

**Comment by tsibelman** [comment]
Yes I understend that it configurable, I was asking what would be a Orleans default imlementation.

**Comment by sergeybykov** [comment]
On CoreCLR? By default we'll write them to the statistics tables and to the log.

**Comment by galvesribeiro** [comment]
@tsibelman There will be an `OrleansTelemetry.PerformanceCounters` library which will encapsulate the implementation of PerfCounters using the new API. This will be optional to have. For now, we will leave it with only the .Net 4.5.x implementation so people who already use it can keep using. 

The native/default Orleans KPIs (which also contains the old Performance Counters) will be pushing data now to any the `IMetricTelemetryConsumer` that is registered at silo startup time and that includes the PerfCounters as well.

As I've mentioned on other issues, I'm still investigating what would be the best performance counter-like api/daemon on Linux/OSX so I can put it together on the new PerfCounter assembly. So far, I've just found `logd` to write logs/traces. If you or @KodrAus has any suggestion I would be glad to add it.

As @sergeybykov  mentioned, the statistics will be dump to the default `ITelemetryProviders`(file, console, Trace) but you can write it anywhere you want. #1026 gives you power to create your own provider and consume all telemetry data with it.

**Comment by KodrAus** [comment]
Depending on what Core CLR support is going to be for all the machine-level metrics we're interesting in gathering, an option might be to create a cross-platform `OrleansTelemetry.Native` package that bundles up some native code. It's a bit of a sledgehammer solution, but if it's the only way to gather some detailed, OS specific metrics then it might be worth coming up with a tidy, cross-platform solution to getting that data.

**Comment by galvesribeiro** [comment]
@KodrAus Exactly. I want to do that outside Orleans core. That will be at the provider level. The main idea on the APM APIs is completely isolate any implementation details.

**Comment by KodrAus** [comment]
@galvesribeiro I'm out of my depth with interopping native code with .NET, but I have a hunch that if you'd wanted the native bits to be compiled on the client machine with the rest of the dependent packages, then the new project format with its flexible compilation api might make it easier.

I'd be very interested to see what kinds of things are possible here.

**Comment by galvesribeiro** [comment]
I'm talking a lot with CoreCLR team and also I'm getting the next efforts to finish the port of Orleans to it (in fact I'm doing it now :smile: ) and coreCLR is build on differently than "old" .net. The native layer was created as small Shims which is exactly what you suggested. Small pieces of native code that entails the platform details for that specific functionality. What I'll probably do with APM related to the PerfCounters, is either implement a native shim on the provider end, ousite Orleans core, or if possible, to keep things "managed" as much as possible, will use P/Invoke to call native APIs to report progress. I did a research on Linux side for something built-in similar to perfcounters and the only thing closer that I found is PAPI (http://icl.cs.utk.edu/papi/faq/index.html) and it is just for Hardware counters not for application ones besides it is an external library, not bundled on any common linux distros. The logger/trace for example, I've already found and tested the usage of `logd` which is bundled with any common linux distro today.

I'll continue my quest looking for it and if you find something, please let me know.

**Comment by KodrAus** [comment]
Interesting stuff, I'll have to dig through what you come out with because I'd like to understand myself how it can be done effectively. Anything that could potentially just be pulled off nuget.org/github and built on any 'normal' machine or Microsoft .NET container would be slick.

**Comment by ReubenBond** [comment]
I believe this issue is no longer relevant. There are yet more telemetry APIs coming (System.Diagnostics.Metrics) and CoreCLR ended up exposing `EventCounter` and `EventPipe` as ways to collect & expose metrics to external applications.
