### ISSUE TITLE
Updating templates according to the roslyn based codegen feature

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [dotnet/orleans#1042]
After the addition of the new Roslyn based codegen feature by @ReubenBond  we need to update Visual Studio templates.
Please provide feedback on what additional templates are required and what we should probably remove.

**Comment by ashkan-saeedi-mazdeh** [comment]
As a first step I'll try to remove codegen for F# and VB templates.

**Comment by ashkan-saeedi-mazdeh** [comment]
@sergeybykov  Should I edit template's .csproj and .vbproj and .. by hand or there is something somewhere in code/UI which I'm missing.

Also what do you think of adding a template for standalone silo project?

And a solution template maybe?

**Comment by ReubenBond** [comment]
@ashkan-saeedi-mazdeh manual editing is the way, I believe.

A standalone "quick start" silo project would be good. We need to improve the out of the box experience for new users.

**Comment by ashkan-saeedi-mazdeh** [comment]
@ReubenBond  I agree.

@jthelin  It seems as @sergeybykov  said you have more info on this.
I have the sdk installed. 

When I try to build the current project it fails because it can not sign the built packages?

**Comment by jthelin** [comment]
@ashkan-saeedi-mazdeh - Could you stash the build log output file somewhere so we can see exactly what is going wrong.

**Comment by ashkan-saeedi-mazdeh** [comment]
@jthelin  This is the error

```
Error	1	Cryptographic failure while signing assembly 'd:\unity projects\Orleans\Orleans\src\OrleansVSTools\OrleansVSTools\obj\Release\OrleansVSTools.dll' -- 'Error reading key file 'd:\unity projects\Orleans\Orleans\src\Orleans.snk' -- The system cannot find the file specified. '	D:\unity projects\Orleans\Orleans\src\OrleansVSTools\OrleansVSTools\CSC	OrleansVSTools

```

**Comment by ashkan-saeedi-mazdeh** [comment]
@jthelin  Am I right that in order to remove NuGet packages I should modify .vbproj files to not include them? Where does NuGet references are stored other than there?
I want to remove references to Orleans.Template packages to use codegen.

**Comment by jthelin** [comment]
NuGet packages are listed in the .*proj files (as a library Reference) and in the packages.config file in that project directory as well. Should remove from both places.

**Comment by jthelin** [comment]
@ashkan-saeedi-mazdeh  - The build problem you mention above is because the OrleansVSTools project is still trying to do code signing. The code signing and the signing key file was removed from the main code base in PR #910.

Here's a patch that should turn off the code signing steps in VSTools project. 
You can hand edit the files in notepad, or save this text in a `patch.diff` text file and use "Apply Patch" in your Git tool.

```
From d7ff9d1067943feb0f9f74497c631dc89b7d2b61 Mon Sep 17 00:00:00 2001
From: Jorgen Thelin <jthelin@microsoft.com>
Date: Wed, 25 Nov 2015 06:57:37 -0800
Subject: [PATCH] Remove code signing in VSTools project.

---
 src/OrleansVSTools/OrleansVSTools/OrleansVSTools.csproj | 5 -----
 1 file changed, 5 deletions(-)

diff --git a/src/OrleansVSTools/OrleansVSTools/OrleansVSTools.csproj b/src/OrleansVSTools/OrleansVSTools/OrleansVSTools.csproj
index 53332b0..55130c1 100644
--- a/src/OrleansVSTools/OrleansVSTools/OrleansVSTools.csproj
+++ b/src/OrleansVSTools/OrleansVSTools/OrleansVSTools.csproj
@@ -16,8 +16,6 @@
     <AppDesignerFolder>Properties</AppDesignerFolder>
     <RootNamespace>OrleansVSTools</RootNamespace>
     <AssemblyName>OrleansVSTools</AssemblyName>
-    <SignAssembly>True</SignAssembly>
-    <AssemblyOriginatorKeyFile>..\..\Orleans.snk</AssemblyOriginatorKeyFile>
     <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
   </PropertyGroup>
   <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
@@ -133,9 +131,6 @@
     </EmbeddedResource>
   </ItemGroup>
   <ItemGroup>
-    <None Include="..\..\Orleans.snk">
-      <Link>Orleans.snk</Link>
-    </None>
     <None Include="source.extension.vsixmanifest">
       <SubType>Designer</SubType>
     </None>
-- 
1.9.5.msysgit.0
```

**Comment by ashkan-saeedi-mazdeh** [comment]
@jthelin  Thanks for the patch.
About the packages.config, C# has them but not VB

**Comment by sergeybykov** [comment]
@ashkan-saeedi-mazdeh Where are you at with this? Are you stuck with those questions? I don't have all the answers yet. First checking in case you already figured them out.

**Comment by ashkan-saeedi-mazdeh** [comment]
@sergeybykov  I know the answer to most of them. NuGet packages should be in csproj and vbproj files but I have another question.
Should I reference Orleans core instead of the template for the interface and collection to compile? I think the answer is yes because I removed the templates and naturally I get compile errors, did not have the time to test, hopefully will do today.

**Comment by ashkan-saeedi-mazdeh** [comment]
@sergeybykov  I'm stock now. I am new to creating project templates like this so stock on a prev question.
How to add NuGet packages to VB projects? I never used VB.NET in my life and thre seem to be no packages.json 
I even did not have it installed at first :) 

Used VB6 in one of the old classes at high school a little so not too unfamiliar :D

**Comment by sergeybykov** [comment]
@ashkan-saeedi-mazdeh https://github.com/dotnet/orleans/pull/1127 by @attilah is close to be merged and it touches the code. Let's reassess what's left after we merge it.

**Comment by sergeybykov** [comment]
Resolved by https://github.com/dotnet/orleans/pull/1127.
