### ISSUE TITLE
Adding a member function that returns other than Task or Task<> shows an not helpful error message.

### ISSUE THREAD

**Issue by shanegrueling** [dotnet/orleans#1044]
Hey,

adding a member function that returns something else than Task or Task<> stops codegen. So far so good. Unfortunately the error message is not helpful.
@sergeybykov told me that there was a better one at some point in time.

I think it would be nice to have a good error message so beginner know what they did wrong.

```
The command ""PATH_TO_PROJECT\packages\Microsoft.Orleans.Templates.Interfaces.1.1.0-beta1\build\..\tools\ClientGenerator.exe" "@obj\Release\Overflow.GrainInterfaces.codegen.args.txt"" exited with code 3.
```

**Comment by gabikliot** [comment]
Fixed via #1045.
