### ISSUE TITLE
IGrainObserver not useable in with VB (CodeGen Issue)

### ISSUE THREAD

**Issue by BenjaminGibbs** [dotnet/orleans#105]
I have come across another small bug in the CodeGen which prevents using IGrainObserver in being used with VB

Adding the following interface to the GrainInterfaces project creates a compile error.
```vbnet
Public Interface IMyObserver
        Inherits IGrainObserver

End Interface
```
The code generated that is invalid is

```vbnet
Public Shared Sub DeleteObjectReference(reference As onShowcase.Distributed.GrainInterfaces.ApplicationData.IMyObserver) As System.Threading.Tasks.Task
            Return Global.Orleans.Runtime.GrainReference.DeleteObjectReference(reference)
End Sub
```
It is declaring a sub/void but then trying to return a task.

It is caused by https://github.com/dotnet/orleans/blob/622d724b43d06aa483c236c23dbbe049fe2dd81d/src/ClientGenerator/VBCodeGenerator.cs#L174

**Comment by gabikliot** [comment]
Closed via #115 .
