### ISSUE TITLE
Using Immutable<string>

### ISSUE THREAD

**Issue by Astorlights** [dotnet/orleans#1050]
Since strings are immutable, does using Immutable\<string> optimize anything ? 

public async Task MyGrainMethod(Immutable\<string> name, Immutable\<int> value...) 

How about primitive types, should we use Immutable\<int> or is it overkill ?

Thanks!

**Comment by sergeybykov** [comment]
I `Immutable<string>` doesn't make much sense.

**Comment by gabikliot** [comment]
strings, as well as all primitives and structs (whose all fields are also recursively value types) are treated as immutable, no need to wrap them.
https://github.com/dotnet/orleans/blob/master/src/Orleans/Serialization/TypeUtilities.cs#L65
