### ISSUE TITLE
Can't use Null Propagation Operator (?.)

### ISSUE THREAD

**Issue by luisrudge** [dotnet/orleans#1053]
`var myObject = State.MyObjects?.FirstOrDefault(i => i.Id == e.Id);`
![image](https://cloud.githubusercontent.com/assets/941075/11315478/997fba54-8fd9-11e5-8d9e-8f16d598b024.png)

**Comment by ashkan-saeedi-mazdeh** [comment]
For this to work you should use the beta and the new codegen created by @ReubenBond  
A new beta should be released soon with fixes as well.

**Comment by amamh** [comment]
I don't get it, are you trying to use null propagation in Orleans source itself or in your own project using Orleans?

**Comment by luisrudge** [comment]
On my own project

**Comment by amamh** [comment]
@luisrudge 

Wouldn't that be a VS problem? I'm using C# 6.0 just fine in my custom stream providers.

**Comment by luisrudge** [comment]
hmm.. why @ashkan-saeedi-mazdeh mentioned a new codegen then?

**Comment by amamh** [comment]
that's why I'm confused

**Comment by ReubenBond** [comment]
Orleans used to generate code and compile it during build using csc.exe. The new codegen compiles that code using MSBuild, using your current C# version.

**Comment by luisrudge** [comment]
so.. Any clues on why I'm seeing such an error?

**Comment by ReubenBond** [comment]
Are you using the new beta? The reason you're seeing a problem is that directly invoking csc.exe as in the current stable (1.0.10) will compile for C# 5, not C# 6.

The new beta will compile using whatever the rest of your project is set to use.

**Comment by luisrudge** [comment]
Ahhh, yeah.. that makes sense.. I'm not using the beta yet. Any ETA on the RTM?

**Comment by ReubenBond** [comment]
We will roll out a second beta with some important fixes to serialization generation (plus others), determine the stability, and then possibly RTM.
Is this issue resolved?

**Comment by luisrudge** [comment]
Yeha, thanks!
