### ISSUE TITLE
Serialization fails when grain methods use abstract types from external libraries

### ISSUE THREAD

**Issue by randa1** [dotnet/orleans#1064]
Hello all,

We have a grain which accepts a parameter with an abstract type, which is loaded from an external library which is Orleans agnostic (a nuget used by several systems in our deployment). Until lately, everything worked fine. When we got the latest master branch the behavior broke and we can no longer invoke this method.

I've created a test for it (on the Orleans solution) here: https://github.com/randa1/orleans/commit/13750fae5e6748aa132a74a58f47b6c99f489f24

I've investigated and it seems that a change in assembly loading is causing it. In previous versions, all types of each loaded assembly would be registered in the `SerializationManager`:
``` c#
        private static void OnAssemblyLoad(object sender, AssemblyLoadEventArgs args)
        {
            // Old code. All loaded assemblies would get here and all types will be registered
            FindSerializationInfo(args.LoadedAssembly);
        }
```

In the new code, which is the current master branch, this has changed and the `AssemblyProcessor` class was added to handle the callback:
``` c#
        private static void ProcessAssembly(Assembly assembly)
        {
            // If the assembly is loaded for reflection only or it does not reference Orleans, avoid processing it.
            if (assembly.ReflectionOnly || !TypeUtils.IsOrleansOrReferencesOrleans(assembly))
            {
                return;
            }
            // rest of code...
        }
```

Since our external library assembly is loaded with `ReflectionOnly` set to `true` and does not reference orleans, the types are not registered.

From what I've seen it only happens for abstract types, since for concrete types the codegen creates a serializer, which is registered to the `SerializationManager` by some other code path.

Paging @ReubenBond too as the `AssemblyProcessor` changes were made by him :)

Thanks,
Ran

**Comment by gabikliot** [comment]
Can try adding [Serializable] attribute to this abstract type? I think it might solve the problem.

**Comment by randa1** [comment]
Today we've seen this in another service, this time with an `enum`. We have a class which has an `enum` property:

```
public class MyClass
{
    public MyEnum Foo { get; set; }
}
```

And this class is the return value of a grain interface method. When invoking the method we get the exact same error as in the issue above (that the type cannot be resolved).

**Comment by ReubenBond** [comment]
@randa1 could you please submit a repro PR for both of these issues (enum & abstract class)? That will likely require creating a separate project for the types which does not reference `Orleans.dll`.

**Comment by randa1** [comment]
@ReubenBond I would gladly, I've already created a repro on my fork (link in original post).. I can create a PR but that would mean pushing a test that currently fails into Orleans.. Should I still do it?

**Comment by gabikliot** [comment]
Yes, and you can mark this failing test as [Ignore].

**Comment by randa1** [comment]
As #1095 fixed this, closing the issue.
