### ISSUE TITLE
Error on Silo Startup when SQL Server is the System Store

### ISSUE THREAD

**Issue by percyabrown** [dotnet/orleans#1065]
I am getting the start up errors in this log: https://gist.github.com/percyabrown/a6a8c1934326e717ff83 . I ran this script to set up the tables in a database named Orleans: https://gist.github.com/percyabrown/94db8cbf9a93654c90dd . The login in the connection string is an administrator. I am able to connect to the database outside of the Orleans Deployment using the same connection string. Do you have any idea what could be causing the errors?

**Comment by percyabrown** [comment]
Here is my

**Comment by percyabrown** [comment]
Here is the OrleansCofiguration.xml for my local deployment:

https://gist.github.com//percyabrownfad3ed37a768976cc024 .

I could not connect as localhost on my laptop.

**Comment by percyabrown** [comment]
Here is the log file from when I tried to start the silo using the OrleansConfig.xml above: https://gist.github.com/percyabrown/2ef6d77228fffc822053

**Comment by veikkoeeva** [comment]
@percyabrown It looks like the new script does not work, but the [previous one](https://github.com/dotnet/orleans/commit/6e8c79925d890ac8601c5cc1854796973963b95e) does. You had a good point [in Gitter](https://gitter.im/dotnet/orleans?at=5654900ef59a8f0758a67550). It looks like this is a regression introduced in https://github.com/dotnet/orleans/pull/1008, but the tests do not catch it.

**Comment by shayhatsor** [comment]
@veikkoeeva and @percyabrown, surely I'm missing something here. AFAIK, the membership table version must be updated upon every write to the table [atomically](https://github.com/dotnet/orleans/blob/master/src/Orleans/SystemTargetInterfaces/IMembershipTable.cs#L89). so there might be another thing at play here.

**Comment by veikkoeeva** [comment]
@shayhatsor You could be right. I just too a previous version of the script, applied and re-run HelloWorld. I did not look any deeper, I just wanted to narrow down the problem so that I can sleep better. :).

I would try to look into it I hadn't so much to do in IRL at the moment (I still need to arrange some furniture, drilling etc.). I look also into this tomorrow if nothing comes up, like working in shifts. :D

**Comment by shayhatsor** [comment]
ok, It's not a bug. just remove:
```xml
<SeedNode Port="11111" Address="10.0.0.109"/>
```
You can't have a seed node (=Primary node) when you're not running the `MembershipTableGrain` liveness. Which is a configuration that's used for [Local Development and Unreliable Deployment on a Cluster of Dedicated Servers](http://dotnet.github.io/orleans/Orleans-Configuration-Guide/Typical-Configurations). It's easy to miss and there should be a better indication for the user. It happened to me once :)

**Comment by percyabrown** [comment]
That worked on my local drive.

**Comment by gabikliot** [comment]
Was that solved? Can now be closed?

**Comment by veikkoeeva** [comment]
@shayhatsor, @percyabrown That is an interesting find. I took HelloWorld, tried the newest script and it hanged like @percyabrown described -- it had `SeedNode` defined still. Then I recreated the database with the one revision older script and it worked. I would like to understand what would be the reason for this.

**Comment by percyabrown** [comment]
@shayhatsor, @veikkoeeva after making the change to the configuration file the silo did not crash but it is only writing to the OrleansMembershipVersion table and not writing to the OrleansMembership table. Is this the expected behavior?

**Comment by shayhatsor** [comment]
no, I'm checking it out.

**Comment by percyabrown** [comment]
@shayhatsor, @veikkoeeva  I may not have run the right script for the tables. Can you email me the script you used to set up the tables?

**Comment by veikkoeeva** [comment]
@percyabrown The [current master version](https://raw.githubusercontent.com/dotnet/orleans/master/src/OrleansSQLUtils/CreateOrleansTables_SqlServer.sql), the [previous version](https://raw.githubusercontent.com/dotnet/orleans/6e8c79925d890ac8601c5cc1854796973963b95e/src/OrleansSQLUtils/CreateOrleansTables_SqlServer.sql). I'm on a phone now. :)

**Comment by shayhatsor** [comment]
this is with your configuration (only changed to reference my localhost)
![capture](https://cloud.githubusercontent.com/assets/12084632/11399590/0db85eb6-9391-11e5-94ed-63e190c23d98.PNG)

**Comment by percyabrown** [comment]
Thanks!

**Comment by percyabrown** [comment]
Then it must be the script I ran. I just got the script from Veikko. Let me
recreate the database and try again.

**Comment by percyabrown** [comment]
@shayhatsor , @veikkoeeva It loaded on my laptop when I ran the old script to create the tables and wrote to both tables. I will move to network and try. This looks promising.

**Comment by percyabrown** [comment]
@veikkoeeva , @shayhatsor I worked on the network, so I am closing this issue.

**Comment by percyabrown** [comment]
Using the script you sent and the configuration change, 2 silos started on
our network servers so I closed issue. Thank you very much for your help!

**Comment by percyabrown** [comment]
Using the script Veikko sent and the configuration change you suggested, 2
reliable silos started on our network servers using SQL Server, so I closed
issue. Thank you very much for your help!

**Comment by veikkoeeva** [comment]
@percyabrown Which one of the two scripts? :) But I'm glad it helped.

**Comment by percyabrown** [comment]
The "old" script.

**Comment by percyabrown** [comment]
@veikkoeeva <https://github.com/veikkoeeva> the "old" script.

**Comment by shayhatsor** [comment]
@veikkoeeva the change that was made in the current script was in the following commit: https://github.com/dotnet/orleans/commit/35211ce6e03500765e376c2bf559bff6b2c4ae01. on my end it seems to be working properly, so i have no idea why the 'old' script works and the 'new' doesn't for @percyabrown. @percyabrown what's the sql server version you're using ?

**Comment by veikkoeeva** [comment]
@shayhatsor This is strange indeed.

`SELECT * FROM OrleansDatabaseInfo;` gives me

| Id               | Value           | Description                         |
|------------------|-----------------|-------------------------------------|
| ProductName      | SQL Server 2014 | The database product name.          |
| Database version | 12.0.4100.1     | The version number of the database. |
|                  |                 |                                     |

I'll try to give this a quick look later today.

**Comment by percyabrown** [comment]
@shayhatsor <https://github.com/shayhatsor> and @veikkoeeva
<https://github.com/veikkoeeva>I am running the exact same version Product
SQL Server 2014 and database version 12.0.4100.1

**Comment by percyabrown** [comment]
@shayhatsor ,@veikkoeeva  I now have 3 silos running. Oddly enough. With the old script I was able to leave the <SeedNode> element, which seems to designate one of the silos as Primary. Without the <SeedNode> element all silos came up as secondary.

**Comment by gabikliot** [comment]
@percyabrown , when using SQL for system store, you SHOULD NOT (better say: must not) specify Primary. All silos will be secondaries, and this is how it should be. Primary is only used in Test setup with in memory system store.

**Comment by percyabrown** [comment]
Got it. Thank you!

**Comment by shayhatsor** [comment]
ok, i think i know what happened here. @percyabrown, you're probably using the public released nugets of orleans... which aren't updated to support the 'new' script... use the 'old' script till next release.

**Comment by percyabrown** [comment]
That is correct.
