### ISSUE TITLE
Grain key type isn't saved with the key

### ISSUE THREAD

**Issue by shayhatsor** [dotnet/orleans#1068]
this is an issue to continue discussing #1043. Currently, it seems to me that the only clean solution would involve a breaking change.

**Comment by sergeybykov** [comment]
Moving this to Backlog alone with #1123.

**Comment by jason-bragg** [comment]
Add issue for new Grain ID system linked to this issue and other grain ID issues.

**Comment by ReubenBond** [comment]
The new GrainId and InterfaceType types resolve this, which was indeed a breaking change.
