### ISSUE TITLE
CodeGen: fix serialization of types in assemblies which do not reference Orleans

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#1072]
Currently the code generator only considers assemblies which [directly reference `Orleans.dll`](https://github.com/dotnet/orleans/blob/3d9fdde7a3a1183c6fb94fa87289889b9e66dad7/src/OrleansCodeGenerator/RoslynCodeGenerator.cs#L116]). This is done to improve silo start times.

Unfortunately, this has lead to problems where types which are specified in assemblies which do not directly reference `Orleans.dll` will not have serializers generated for them. See #1064 and #1056 for example.

I want input on how to solve this.

One possible solution is to create a `[KnownType]` attribute which can exist on the assembly level, grain interface level, grain class level, or grain method level which refers to external types which will require serialization generation. We would use that hint to pick up the entire assembly of the referenced type and generate serializers for all types which we can generate serializers for.

Another tweak is to consider all assemblies for all types which are referenced from a grain interface. That way, if a grain references an abstract type in a foreign assembly, we will generate serializers for all types in that assembly.

Your feedback is greatly appreciated :)

**Comment by gabikliot** [comment]
A question: even if we don't generate serializers for the, the code should have worked, with fallback Binary Serializer. Correct?
If yes, then I wonder if the problem described in #1056 is this or maybe something else?

**Comment by randa1** [comment]
I think the latter is the way to go (all assemblies referenced from a grain interface). Requiring to explicitly state all these types/assemblies which are already in the interface is quite redundant.

**Comment by ReubenBond** [comment]
> Requiring to explicitly state all these types/assemblies which are already in the interface is quite redundant.

The problem is that is not true, we cannot expect developers to comply:
```C#
public interface IBadInterface : IGrainWithStringKey
{
  Task<object> BadToTheBone(object input);
}
```

That's not to mention that an abstract type may be declared in assembly A and have a concrete implementation in assembly B, which would break my suggested enhancement.

**Comment by gabikliot** [comment]
But Reuben, I thought we generate serializers via this rule (at least that what we used to do prio to the new code gen (I think)):

http://dotnet.github.io/orleans/Advanced-Concepts/Serialization

1) Go over all grain interface and grain class implementation assemblies (these are the assemblies that have the code gen step defined on them via referencing Orleans templates nuget).

2) Out of those assemblies: generate serializers for types that are directly referenced in grain interfaces method signatures or state class signature OR for any type that is marked with [Serializable] attribute.

**Comment by ReubenBond** [comment]
> 2) Out of those assemblies: generate serializers for types that are directly referenced in grain interfaces method signatures or state class signature OR for any type that is marked with [Serializable] attribute.

The OR bit was never true, unless I missed an important detail (eg, because I looked for `SerializableAttribute` in code instead of `IsSerializable`).

Even if it is, this is Runtime code gen: should we be scanning every type in every assembly? Why do we care what's marked as `[Serializable]`, is that for startup performance? We will only ever generate serializers where possible.

**Comment by gabikliot** [comment]
I am pretty sure that was the old logic. @sergeybykov will know for sure.
It was indeed a Runtime code gen. Yes, every type in every assembly we successfully loaded. I think so. Done to basically support the case when you pass lets say a `List<object>` and the `object` can be anything.

CC: @alan-geller. Alan, do you remember?

**Comment by sergeybykov** [comment]
>It was indeed a Runtime code gen.

We only had compile time codegen before Reuben's codegen PR. We did not generate any serializers upon load.

We looked for `[Serializabe]` at compile time because the attribute was considered a hint that the type might be sent over the wire. We would try to generate a serializer for it hoping to do better than the fallback .NET one. This logic also allowed developers to use `[Serializabe]` to trigger compile time generation of serializers for their types that weren't explicitly used in a grain interface.

**Comment by ReubenBond** [comment]
I can certainly scan all assemblies to find types marked `[Serializable]`, it's as easy as removing the code which *avoids* that wide search. If we want that, I'm happy to comply :)

**Comment by sergeybykov** [comment]
I think it's the right thing to do that at compile time. Probably not at run time though.

**Comment by gabikliot** [comment]
Sure, compile time, my bad. I think lets do the same now as well.

**Comment by sergeybykov** [comment]
Is the issue here that for F# and VB we cannot do compile time codegen? Then maybe we could make the run time full scan option off by default but configurable, so that F#/VB folks could turn it on as the cost of longer silo startup time?
