### ISSUE TITLE
Documentation for OnActivateAsync?

### ISSUE THREAD

**Issue by svick** [dotnet/orleans#1079]
When looking into answering [a question on SO](http://stackoverflow.com/q/33920495/41071) I found some mentions of the `OnActivateAsync()` method, but pretty much the only documentation about it I could find is [a short mention in a tutorial](http://dotnet.github.io/orleans/Step-by-step-Tutorials/A-Service-is-a-Collection-of-Communicating-Actors#the-life-of-an-actor) and [few mentions in passing in another tutorial](http://dotnet.github.io/orleans/Getting-Started-With-Orleans/Developing-a-Grain).

Is there some documentation about this method that I'm overlooking? If not, shouldn't there be more of it? Maybe a detailed explanation of the lifecycle of a grain?

**Comment by sergeybykov** [comment]
I think this is a valid point. We don't seem to have a doc section clearly describing the lifecycle of a grain. Do you feel like contributing one?

**Comment by svick** [comment]
I don't feel like I know Orleans enough to write it, so no, sorry.

**Comment by sergeybykov** [comment]
That's fine. :-)

**Comment by amamh** [comment]
@svick 

Doesn't seem like there's anything complicated about it.

Constructor -> ReadStateAsync -> OnActivateAsync

This will only happen if the grain is not already active. Note that being subscribed to a stream keeps the grain active.

**Comment by ashkan-saeedi-mazdeh** [comment]
@amamh  @sergeybykov 
I can write it but is really `OnReadStateAsync` called on activation?

**Comment by amamh** [comment]
Well, I believe that's the whole point of a state. It's going to be read before the grain is activated i.e. restore its previous state. The idea is that a grain/actor conceptually always exists with no lifecycle and that's done by persisting its state, so it can die/wake up without the knowledge of the users. Clients see actors as always "there", that's the point of "virtual" actors.

**Comment by sergeybykov** [comment]
@amamh You are right. One small correction - it is `ReadStateAsync`. It is called on the storage provider if the grain class extends `Grain<T>`.

@ashkan-saeedi-mazdeh Your help will be very much appreciated!

**Comment by ashkan-saeedi-mazdeh** [comment]
@sergeybykov  my pleasure.
@amamh  yeah , OnReadAsync confused me, I thought there is a virtual method which I didn't know about.

**Comment by jason-bragg** [comment]
>I can write it..

@ashkan-saeedi-mazdeh :+1: 
Thanks!

**Comment by miker1423** [comment]
Hello, are this docs ready or someone is writing them? I'm glad to help if needed. 😄

**Comment by sergeybykov** [comment]
Unless @ashkan-saeedi-mazdeh suddenly got back to it now, I don't think anybody is.

**Comment by ashkan-saeedi-mazdeh** [comment]
@miker1423  @sergeybykov  not unfortunately , I got myself too busy. :) Getting free again soon. I would be happy to help reviewing it and ... however.

**Comment by sergeybykov** [comment]
Resolved via #2478.
