### ISSUE TITLE
Dnx Console Host

### ISSUE THREAD

**Issue by elmortega** [dotnet/orleans#1083]
Orleans version 1.1.0-beta1

I'm trying to host the silo in a Dnx Console App this way:    

```
    AppDomain hostDomain = AppDomain.CreateDomain("OrleansHost", null,
                 new AppDomainSetup()
                 {
                     AppDomainInitializer = InitSilo
                 });
```

But I get a System.IO.FileNotFoundException.

If a I run it in a normal console app works fine

**Comment by sergeybykov** [comment]
I suspect you need to add pre-released `Microsoft.Framework.DependencyInjection` and `Microsoft.Framework.DependencyInjection.Abstractions` nugets to the project. We fixed that for -beta2. Which file does the `FileNotFoundException` complain about?

**Comment by elmortega** [comment]
'OMS.ConsoleHost' is the Console project name

No se puede cargar el archivo o ensamblado 'OMS.ConsoleHost, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ni una de sus dependencias. El sistema no puede encontrar el archivo especificado.

**Comment by KodrAus** [comment]
I had this issue running in DNX too. You won't be able to run Orleans in DNX just yet (unless it's changed in the last few days), it's an active work in progress.

Have a look at #368 or #912

**Comment by elmortega** [comment]
Just installed the Orleans version 1.1.0-beta2, doesn't work either

**Comment by jdom** [comment]
yeah, as @KodrAus mentioned, Orleans is not supported on DNX just yet. BTW, are you targeting CoreCLR or full .NET?

**Comment by elmortega** [comment]
@jdom full .NET

**Comment by elmortega** [comment]
So that means that I can´t use orleans with Asp.Net 5 ?

**Comment by sergeybykov** [comment]
@elmortega You should be able to use Orleans so long as you target full .NET I think. Try the final v1.1.0 we just published.

**Comment by elmortega** [comment]
in my project.json:

"frameworks": {
    "dnx451": {
      "dependencies": {
        "Microsoft.Orleans.OrleansRuntime": "1.1.0"
      }
    }

**Comment by elmortega** [comment]
I´m trying to initialize the GrainClient in a Asp.Net 5 app

            var clientconfig = new Orleans.Runtime.Configuration.ClientConfiguration();
            clientconfig.Gateways.Add(new IPEndPoint(IPAddress.Loopback, 30000));
            GrainClient.Initialize(clientconfig);

but I get...

An exception of type 'System.AggregateException' occurred in mscorlib.dll but was not handled in user code

{"Método no encontrado: 'Void Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions..ctor(Microsoft.CodeAnalysis.OutputKind, System.String, System.String, System.String, System.Collections.Generic.IEnumerable`1<System.String>, Microsoft.CodeAnalysis.OptimizationLevel, Boolean, Boolean, System.String, System.String, System.Collections.Immutable.ImmutableArray`1<Byte>, System.Nullable`1<Boolean>, Microsoft.CodeAnalysis.Platform, Microsoft.CodeAnalysis.ReportDiagnostic, Int32, System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,Microsoft.CodeAnalysis.ReportDiagnostic>>, Boolean, Microsoft.CodeAnalysis.XmlReferenceResolver, Microsoft.CodeAnalysis.SourceReferenceResolver, Microsoft.CodeAnalysis.MetadataReferenceResolver, Microsoft.CodeAnalysis.AssemblyIdentityComparer, Microsoft.CodeAnalysis.StrongNameProvider)'."}

StackTrace

   en System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   en System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   en System.Threading.Tasks.Task`1.get_Result()
   en Orleans.GrainClient.InternalInitialize(ClientConfiguration config, OutsideRuntimeClient runtimeClient)
   en Orleans.GrainClient.Initialize(ClientConfiguration config)

**Comment by GeroL** [comment]
I have a working one with DNX RC1. RC2 does not work because the CompilationServices system was changed to much.
I will try to create a branch and a pull request.
Basically what I did with Orleans:

* Include all dependent NuGet packages. 
* Added a property to RoslynCompiler class to pass external MetadataReference.

What I had to do on the project side:

* Get MetadataReference from DNX Assemblies.

Orleans filters out assemblies without location. DNX assemblies do not have one.

See : https://github.com/aspnet/dnx/issues/3248

**Comment by GeroL** [comment]
I tested Orleans with dotnet cli nightlies and it works good.
So as DNX is deprecated and dotnet cli works with orleans out of the box is this task still needed?

**Comment by pshirshov** [comment]
@GeroL: could you create a minimal demo of orleans running on top of dotnet cli?

**Comment by TsengSR** [comment]
@pshirshov: A few days I ported the Orleans Adventure sample to .NET Core running against the full .NET Framework (4.5.2, Orleans doesn't work with 4.6 or netcoreapp yet), while tracking down some issues I had with implementation of my application. 

https://github.com/TsengSR/OrleansAdventure

I too think this issue is obsolete, unless it's meant to be re-interpreted as `netcoreapp1.0`. But DNX is a bit different than netcoreapp

**Comment by sergeybykov** [comment]
@TsengSR Would you submit a PR with your version of the Adventure sample?

Looks like this issue can be closed now.

**Comment by pshirshov** [comment]
I think it's not good idea to close until Orleans starts working on .net core runtime not 4.6 one.

**Comment by TsengSR** [comment]
One of the main tasks of DNX was loading the runtime libraries into the application. 

With dotnet-cli all the runtime libraries are either downloaded via nuget and shipped with the application (self-sustained applicatoin) or by providing a reference point in portable apps, both which happens via `Microsoft.NETCore.App` for applications and `NETStandard.Library` for class libraries. 

The other one was to provide an application entry point (in dnx applications there wasn't a need for a `Main` method), as dnx would provide this entry point. With the new dotnet-cli tooling applications have to provide an entry point.

DNX by itself wasn't related to .NET Core/CoreCLR support. It supported both CoreCLR and the full .NET framework.

**Comment by sergeybykov** [comment]
With 2.0 Tech Preview running on .NET Core I think this can be closed now.
