### ISSUE TITLE
Doesn't work NuGet import MSBuild targets and props files into project 

### ISSUE THREAD

**Issue by vadimzozulya** [dotnet/orleans#109]
targets and props files are not included to the project after installing 
<i>Microsoft.Orleans.Templates.Interfaces</i> or <i>Microsoft.Orleans.Templates.Grains</i> packags.

Based on NuGet documentation(http://docs.nuget.org/create/creating-and-publishing-a-package#import-msbuild-targets-and-props-files-into-project), </i>.target</i> and <i>.props</i> files should be named  as <b>{packageid}.targets</b> and <b>{packageid}.props</b> accordingly.

**Comment by jthelin-microsoft** [comment]
Fixed by PR #111
