### ISSUE TITLE
Ensuring data consistency when a transaction spans state in two Grains

### ISSUE THREAD

**Issue by saeedakhter** [dotnet/orleans#1090]
I'm working on a game that has in-game currency.  I need to make reasonable guarantees that if a Orleans silo crashes mid-transaction that the state of the game can be restored to a consistent state.

My understanding is that persisting state for single grain instance is an atomic operation (since writing an entry to Azure Table is an atomic operation).  So in cases where a transaction modifies two properties of the same grain (player trades currency for goods), there is no concern.  The player is always left in a consistent state because the entire transaction either succeeds or fails atomically.

The problem occurs when a currency transaction spans two grain instances.  If a currency transaction involves multiple grain instances, all instances would need to be persisted as one atomic operation.  Azure Table does support Entity Group Transactions(https://azure.microsoft.com/en-us/documentation/articles/storage-table-design-guide/), but in order to use this feature all entities involved must have the same partition key (with different row keys). It appears the Orleans AzureTableStorage Provider uses unique PartitionKeys for each Grain which maximizes scalability but means that no atomic transactions can be used to maintain strong consistency of the data.  This design choice makes a lot of sense, so I still need another solution.

Instead, I'm proposing a commit or rollback pattern that would make certain guarantees.  For the purpose of this example, let's assume GrainSender is trading currency for goods with GrainReceiver.  All of these statements should be true regardless if the silo hosting GrainSender crashes or the silo hosting GrainReceiver crashes mid-transaction.
	1) The operation can be safely retried from the front end regardless of whether it completed or not.
	2) GrainSender would retry and complete the operation before allowing use of it's Currency or Goods.
	3) If GrainReceiver does not have the necessary goods for the transaction, the transaction is rolled back. 

I've implemented this and uploaded to GitHub:
https://github.com/saeedakhter/OrleansStrongConsistency

My question is, is there a generalization that makes sense to integrate into Orleans itself?  I'm offering to do the work and submit a pull request, but I need some guidance.  I really don't want to re-implement this logic whenever two Grains need to exchange property values in a way that guarantees data consistency.  I'm thinking of creating some base classes similar to Grain and GrainState that a developer would extend from if they would like to perform transactions between Grains.  The alternate new base GrainState would keep track whether the state is in a 'locked/pending' state because it needs to communicate with another grain to complete a transaction and a short history of executed transactions to enable idempotent (safely retry-able) transactions.  The developer extending from the alternate Grain would need to implement the abstract functions to Send and Receive a delta to the current state…  I haven't planned it out completely, but this is the rough outline that I am proposing:

    public abstract class GrainConsistent<TGrainState> : Grain
       where TGrainState : GrainStateConsistent
    {
        /// <summary>
        /// Implement this function to deduct properties such as Currency, Goods, and any other delta to your current state
        /// this is called when there is an outgoing Transfer
        /// </summary>
        protected abstract Task<bool> Send(TGrainState deltaState);

        /// <summary>
        /// Implement this function to receive properties such as Currency, Goods, and any other delta to your current state
        /// this is called when there is an incoming Transfer, or when an outgoing transfer fails that needs to be rolled back 
        /// </summary>
        protected abstract Task<bool> Receive(TGrainState deltaState);

        protected virtual Task<TGrainState> GetState()
        {
            // completes any pending transaction before returning base.GrainState
            // otherwise you might be working with inconsistent data after a silo crash that occurred mid-transaction
        }

        protected virtual Task<bool> Transfer(double Timestamp, GrainConsistent target, TGrainState delta)
        {
            // implements the same logic inside https://github.com/saeedakhter/OrleansStrongConsistency/blob/master/GrainCollection/Employee.cs
        }

        protected virtual Task<bool> Receive(double Timestamp, TGrainState delta)
        {
            // implements the same logic inside https://github.com/saeedakhter/OrleansStrongConsistency/blob/master/GrainCollection/Employee.cs
        }
    }

Thoughts?  Is there an alternate way of achieving this in Orleans that I'm not thinking of?

**Comment by gabikliot** [comment]
CC @philbe.

**Comment by sergeybykov** [comment]
My impression is that an approach like this may work in a limited case, even though I still have questions about who would initiate retries/rollbacks in various failure cases, considering that grains are reactive by nature, and only get activated when there are external messages to them. Also, it's not clear to me if/how this approach would scale beyond two-grain transactions.

@philbe has been working on a project of adding general purpose ACID cross-grain transactions, and even for Phil it wasn't straightforward.

Your approach, if it works, can probably be implemented in the form of a base class that multiple grain classes could inherit the functionality from. https://github.com/OrleansContrib/ would be a good place where to share such code with others. I don't quite see it in the core Orleans codebase, at least not yet.

**Comment by philbe** [comment]
@saeedakhter, I read your implementation. It’s elegant. The basic idea is sound, though I’m not sure the current code handles all concurrency and failure cases. E.g., suppose client C starts a transfer from employee E to employee F by updating E, and before C can update F, client D starts a transfer from F to E and updates F. Doesn’t this deadlock? Maybe that’s what you were getting at in your last paragraph.

I can see why the approach would be quite useful in your scenario. But I agree with @sergeybykov that it seems insufficiently general to add to the core Orleans codebase. In addition to the two-grain limitation, you’ve combined the idempotence of transaction requests with the ACID properties of transactions. That’s fine when designing it for a particular app, as you did. However, in general-purpose transaction systems, those abstractions are componentized separately, with idempotence handled by a persistent queuing system.

We have an implementation of general-purpose ACID transactions for Orleans that allows any number of grains and grain calls to participate. The API is very similar to .NET transactions. No firm plan on when we’ll make it public, but soon I hope.

**Comment by saeedakhter** [comment]
@philbe @sergeybykov Thanks for your feedback. I got busy with other things for a bit, but I recently updated my implementation at https://github.com/saeedakhter/OrleansStrongConsistency with your feedback and it would be great to see it get into https://github.com/OrleansContrib/ as you suggested.

Here are the improvements:
	1) It is now implemented as a base class that is easy to extend to get transaction support
	2) It can now handle transactions with an arbitrary number of grains involved in the transaction
	3) I believe it is now ACID-compliant:  Atomic because a commit by TransactionStatusPool is the single truth a transaction completed otherwise it will roll back.  Consistent and Durable because a silo can crash mid-transaction, and grains will automatically rollback (or remain in the transaction complete state if a commit by TransactionStatusPool did occur). Isolated because grains are single threaded and the callstack must unwind before another transaction can complete with the same grains.
	4) Retries now must be attempted by the client if it does not receive confirmation that the transaction completed, but rollbacks are handled automatically through the base class implementation  (OnActivateAsync logic to confirm or rollback a transaction in flight and one Reminder per Grain actively involved in transactions).
	5) I separated out the notion of being "idempotent" from the base class.  The transaction base class no longer keeps track of previous transaction IDs.  Instead, a transaction builder helper class assists the developer to ensure transactions are retried properly by checking transaction status to avoid the same transaction inadvertently being executed twice.
	6) I solved the deadlocks problem @philbe pointed out by growing locked grains in the deterministic order of lowest to highest Grain GUID.  Now multiple transactions can be in flight and will not hang each other.

If you have further feedback or would like me to issue a pull request for OrleansContrib, please let me know.

**Comment by gabikliot** [comment]
My initial feedback is to the README.

You explain how using Entity Group Transactions is not possible since AzureTableStorage Provider uses unique PartitionKeys for each Grain. This is of course not the right reason.  AzureTableStorage provider is just A ONE provider, in fact it is even just a sample. One can trivially write a different storage provider identical to that one, and map grains to Azure Table rows/partitions in any way he wishes. So the fact that this particular storage provided picked to map data this way can not be used as a general argument. 

Instead, you might want to explain why using a storage provider that does map all grains into one partitions will still not work. This is since you still need too make all writes from one place in one write batch, and for that you need to collect all tx results and coordinate their write together, which is what your solution is essentially doing via `TransactionStatusPool`.

**Comment by philippecp** [comment]
@philbe Is there any update on making API public? I also need transactions and will soon have to make a decision to either roll my own transaction system, wait for your API or use something other than orleans.
