### ISSUE TITLE
Recoverable Event Hub Persistent Stream Provider

### ISSUE THREAD

**Issue by jason-bragg** [dotnet/orleans#1096]
Much of Orleans streaming infrastructure was designed to support the following requirements:
* Ordered streams, with data duplication allowed – Events must be delivered to consumers in order.  Duplicate events are allowed.  For instance, a stream of events e1, e2, e3, e4, e5 can be delivered to a consumer ordered as e1, e2, e3, e4, e1, e2, e5, but can’t be delivered in the order e1, e4, e5, e2, e3, e4, e5.
* Recoverable/Rewindable – Consumers can recover from transient errors in stream processing by resuming stream consumption from the sequence token of the last successfully processed event.  Since this is intended only to compensate for transient stream processing errors, only 30 minutes of recoverable stream data is required.
* Persistent streams – Events must be persisted upon generation.  Processing of the event can be delayed, but persistence of the event must be immediate.
* Performant – Must support stream delivery of 2000+ events per second per silo with below 40% CPU utilization.

These requirements came from [343 Industries](https://www.halowaypoint.com/en-us), an early adopter and co-developer of Orleans streaming technology.  [343 Industries](https://www.halowaypoint.com/en-us) developed a recoverable stream provider using EventHub.  This EventHub Stream Provider is being contributed to the Orleans open source project.  During the process of porting this technology to Orleans, the stream provider will be refactored and reorganized to conform to Orleans open source conventions, but the core architecture and requirements must be preserved.

This stream provider will be introduced in the following stages (plan subject to change):

1. Minimal non-recoverable EventHub stream provider
   * Introduction of a new ServiceBus specific project.  OrleansServiceBus.  This will be comparable to the azure specific project OrleansAzureUtils.
   * Development of EventHubQueueAdapter comparable to AzureQueueAdapter, with similar limitations.
      1. Non-rewindable
      2. Will use simple queue cache.
   * Define an EventHubStreamProvider that is a persistent stream provider that uses the EventHubAdapter.
   * Add test coverage for EventHubStreamProvider comparable to that of AzureQueueStreamProvider.

2. Introduce PooledQueueCache (open to better name).  This will be an implementation of the IQueueCache interface which can cache up to 30 minutes of data while minimizing impact to garbage collection.
   * This implementation will cache raw serialized events in pooled blocks of memory that are reused and never collected by garbage collection system.
   * Add PooledQueueCache BVT tests.

3. Add recoverable stream tests using the test stream provider GeneratorStreamProvider with a PooledQueueCache.

4. Update EventHubStreamProvider to be recoverable.
   * Update EventHubQueueAdapter to use PooledQueueCache.
   * EventHubQueueAdapter to persist state that tracks offset into EventHub partition.
   * Add recoverable stream tests comparable to those built against GeneratorStreamProvider.

**Comment by gabikliot** [comment]
Great initiative! Very happy that is happening!

One question: do we have to introduce  a new ServiceBus specific project? Can we keep it inside AzureUtils?

The arguments against a new project are:
1) more projects to maintain.
2) it may not be obvious to user that Event Hub relies on ServiceBus, and they will forget to reference that nuget and you will be answering tons of question on GH about it.
3) I would speculate that the vast majority of user who will use EH stream provider will run in Azure and use Azure Table system store, so they will any way depends on Azure Utils nuget.
4) for users that run in Azure and not use EH this will bring an extra dependant (ServiceBus) dll. So what?

**Comment by jason-bragg** [comment]
@gabikliot 
I am not strongly opposed to adding ServiceBus to the azure utilities.  My main reason for doing so was to limit dependencies and allow independent versioning of core dependencies.  While ServiceBus is part of azure, it is it's own product, with it's own release cycle, and it's own set of capabilities which are not insignificant.  Bundling it with azure storage seemed like it would eventually lead to a large and complex assembly with difficult to resolve dependency versioning problems.

1) - Agreed
2) - I don't see how, but maybe I'm missing something.  The event hub stream provider will be in the OrleansServiceBus assembly.  They can't reference it if they don't include the assembly.  This is no different than the AzureQueueStreamProvider.
3) - Agreed, but I suspect that they will want to update these dependencies independently.  My suspicion is that putting both of these (significant) dependencies in the same project will introduce dependency version management issues.
4) - No opinion.  I personally don't see much of an issue with an extraneous assembly or two, but it's hard to say because we don't know what additional dependencies Azure Storage or ServiceBus will include.

**Comment by gabikliot** [comment]
I also don't strongly oppose, just something to consider.
Re point 2: I think you missed my intention. User code (grain code) does NOT directly reference EHStrreamProvider, as it does not directly reference AzureQueueStreamProvider. It references the IStreamProvider. The only place that references AzureQueueStreamProvider is the config, which may be in XML. So the solution will compile fine and fail at runtime, if the user did not specify the correct stream provider assembly or forgot to deploy this assembly. And since the name of this assembly is ServiceBuss, it may not be trivial to see that this assembly is required for EH. 
Indeed same applies for AzureQueue, except that AQ is part of Azure utils

**Comment by jason-bragg** [comment]
@gabikliot 
We ( @sergeybykov, @jdom, and I ) went over the pros/cons of adding a new ServiceBus assembly vs. using AzureUtils for the EventHub façade, and the consensus was that placing this logic in a ServiceBus assembly is probably a safer approach.  No one had a strong opinion on this, but placing the ServiceBus dependency in it's own assembly avoids pushing new dependencies onto our azure storage customers.

**Comment by jason-bragg** [comment]
I obtained clearance to identify the "Customer" contributing the EventHubStreamProvider.  Description updated to credit 343 Industries.

**Comment by gabikliot** [comment]
OK, its your call on ServiceBus assembly.

Looking forward to Event Hub Stream Provider OSS!

**Comment by jason-bragg** [comment]
Work complete.
See for next set of related work see "Recoverable Event Hub Persistent Stream Provider - Part 2  #1454"
