### ISSUE TITLE
Configuration files from the NuGet packages are not copied to a project.

### ISSUE THREAD

**Issue by vadimzozulya** [dotnet/orleans#110]
After installing <i>Microsoft.Orleans.Client</i> or <i>Microsoft.Orleans.Server</i> NuGet packages configuration files is not appeared in project folder.

It seems they are in not appropriate folder (<i>lib\net45</i> instead of <i>content</i>).

**Comment by jthelin-microsoft** [comment]
Fixed by PR #111
