### ISSUE TITLE
GrainState : ETag value not set

### ISSUE THREAD

**Issue by angshuman-agarwal** [dotnet/orleans#1129]
Hi
I am using the latest stable _v1.0.10_ and trying to write a simple program to **save the state in a file** on the disk. I am able to persist. But, when I stop the SILO and start it again, I do not see anything in _ETag_. **Is it not supposed to implicitly set and show when was the state last saved ?** I tried explicitly setting like this **too** - 
```
this.State.Etag = DateTime.Now.ToString(); 
```
Still it is always null. Must be I am missing something silly.

![grainstate](https://cloud.githubusercontent.com/assets/1796126/11725987/6489b1f6-9f74-11e5-92f3-8e1c07a37d2d.png)

**Comment by sergeybykov** [comment]
ETag is set by the persistence provider (if it supports such functionality). What provider are you using?

**Comment by angshuman-agarwal** [comment]
Hi,
I wrote my own _FileStorage Provider_ which persists the state on disk in JSON format

regards
Angshuman

**Comment by sergeybykov** [comment]
Then it's your provider's responsibility to generate ETags, for example based on tick count. Or you can keep them as `null`s, but then you won't be able to detect write conflicts.

**Comment by angshuman-agarwal** [comment]
I explicitly do this 

`this.State.Etag = DateTime.Now.ToString();`

**Comment by gabikliot** [comment]
If you share your whole storage provider code we may be able to help.

**Comment by gabikliot** [comment]
Looks like we can close that issue, right?
