### ISSUE TITLE
Make PersistentStreamProvider interfaces more consistent and asynchronous

### ISSUE THREAD

**Issue by amamh** [dotnet/orleans#1130]
As discussed [here](https://github.com/dotnet/orleans/issues/1046#issuecomment-163728530)

I think the following should be changed to make it easier to implement a custom PersistentStreamProvider:

In `IQueueAdapterFactory`:

- Method `IQueueAdapterCache GetQueueAdapterCache()` should be asynchronous like method `Task<IQueueAdapter> CreateAdapter();`

For example, in my [custom provider](https://github.com/amamh/orleans-PipeStreamProvider) I'm using Redis for the cache, and I want to initialise the connection without making a blocking call.

If this is intended to be a getter method rather than a creation one (hence "Get" instead of "Create"), so it should just return an already setup `IQueueAdapterCache` then there should be some other async method in `IQueueAdapterFactory` where the adapter cache can be created asynchronously.

In `IQueueAdapter`:

- There should be an async Init method the same as `IQueueAdapterReceiver`:
  - `Task Initialize(TimeSpan timeout)`

Thank you,
Space Monkey

**Comment by amamh** [comment]
According to @gabikliot [here](https://github.com/dotnet/orleans/issues/1132) I shouldn't be needing to do any blocking calls in the cache in the first place. If that's correct, then the first point should be ignored. That is, Method `IQueueAdapterCache GetQueueAdapterCache()` should stay synchronous.

**Comment by jason-bragg** [comment]
to reinforce @gabikliot's point:

>Orleans IQueueCache is exactly for caching in silo (server) memory.

The cache was intended to be a local in-memory cache.  Changing this is not as simple as updating the calls to be asynchronous (returning a Task) due to the reentrant nature of the pulling agent (a system target).  Unfortunately, the adapter pattern does not (nor, in my view, should it) support what you're trying to do with it. :/

**Comment by amamh** [comment]
Hey, thanks for the reply. I get the first point.

> the adapter pattern does not (nor, in my view, should it) support what you're trying to do with it.

Which part are you referring to? the suggestion about the async init method for the adapter? or are you referring to me trying to cache everything?

**Comment by jason-bragg** [comment]
@amemh, I apologize for being unclear.  I was referring to the use of a remote (or more generally, asynchronous) cache.  In the current adapter pattern, the cache is primarily intended to:
* Support independent event delivery.  Consumers that take longer processing an event should not hinder consumers with faster processing.
* Short term error recovery.  If there are processing errors, consumers can re-subscribe to an earlier point in the stream and reprocess the events.

To achieve these goals, a local in-memory message cache was introduced.  Using something like redis for the cache does not fit this pattern.
