### ISSUE TITLE
PersistentStreamProvider: How to avoid blocking calls in the cache?

### ISSUE THREAD

**Issue by amamh** [dotnet/orleans#1132]
Maybe this is not a very conventional thing to do, but in my [custom provider](https://github.com/amamh/orleans-PipeStreamProvider) I'm using Redis for caching.

However, IQueueCache and IQueueCacheCursor interfaces don't have async methods, so I'm stuck with using the synchronous API which works fine but isn't a great idea.

Is there a way to achieve this or am I not supposed to do this?

---

This could be related to https://github.com/dotnet/orleans/issues/1130

**Comment by gabikliot** [comment]
You are not supposed to do this.

The cache itself is supposed to be in memory data structure with fast retrieval. So it was deliberately modeled with sync API. The cache should not be doing async calls outside the server.
If you find yourself needing to do async calls from within the cache, you probably modeled your data and queue provider wrongly.

**Comment by amamh** [comment]
Even though I'm using a Redis server running on the same machine? I mean, that's supposed to be a fast setup, I just want to avoid caching a lot of data in memory. The reason I want to cache a lot of data is to be able to replay everything again for clients who want that.

**Comment by gabikliot** [comment]
Orleans IQueueCache is exactly for caching in silo (server) memory.
If you want to cache inside Redis (which is what Redis is of course), you should do it in Redis and from Orleans's perspective it is an external queue provider.

**Comment by amamh** [comment]
@gabikliot 

I have a two more questions, please:

- If we make the assumption that Redis is always going to be running on the same machine (so, there is only one server), why would that be worse than using a memory structure? Of course, it won't be as fast as accessing the process memory because of the serialisation/etc overhead when calling Redis, but could it ever be "fast enough"?

- What do you mean by:

> If you want to cache inside Redis (which is what Redis is of course), you should do it in Redis and from Orleans's perspective it is an external queue provider.

Maybe I'm just getting confused, are you simply repeating that I shouldn't use Redis in the provider cache and keep it as an external component that has to be accessed asynchronously?

**Comment by gabikliot** [comment]
>are you simply repeating that I shouldn't use Redis in the provider cache and keep it as an external component that has to be accessed asynchronously?

Yes, exactly.
