### ISSUE TITLE
Silo configuration not honoring <Networking Subnet=x />

### ISSUE THREAD

**Issue by amccool** [dotnet/orleans#1135]
ProxyingGateway seems to use the subnet, but the interconnect is not.

using OrleansConfiguration.xml

```
<Defaults>
  <Networking Subnet="192" Port="11111"  Address="" />
  <ProxyingGateway  Subnet="192" Port="30000" Address="" />

<SystemStore SystemStoreType ="SqlServer"
```

results in
172.18.4.153:11111
192.168.2.102:30000

21:02:36Z [1] Information R5Ent.OrleansSiloHostService.exe 0: [2015-12-11 21:02:36.536 GMT     1        INFO    100403  Silo    172.18.4.153:11111]     -------------- Initializing Secondary silo on host doink MachineName DOINK at 172.18.4.153:11111, gen 187563756 --------------

Silo configuration:
   Silo Name: empty silo
   Generation: 187563756
   Host Name or IP Address:
   DNS Host Name: doink
   Port: 11111
   Subnet:
   Preferred Address Family: InterNetwork
   Proxy Gateway: 192.168.2.102:30000
   IsPrimaryNode: False

**Comment by jason-bragg** [comment]
In 2.0 configuration is more explicit, allowing users to do this as they like.
