### ISSUE TITLE
Converge Templates NuGet packages

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#1145]
Currently, we have two packages which will introduce compile-time code generation into a consumer's project:
* Microsoft.Orleans.Templates.Interfaces
* Microsoft.Orleans.Templates.Grains

Code generation now functions identically for all project types. Therefore, these packages are now functionally equivalent and can be converged into one package to avoid potential confusion.

**Comment by attilah** [comment]
What is the proposed name? 

Microsoft.Orleans.CodeGeneration
or
Microsoft.Orleans.Roslyn

for me Microsoft.Orleans.Templates does not makes too much sense ;-)

**Comment by ReubenBond** [comment]
Agree that Microsoft.Orleans.Templates doesn't make much sense - I didn't know what it was until Sergey or Gabi told me.

I prefer the first name, Microsoft.Orleans.CodeGeneration, but it's still inaccurate because that's for compile-time / build time code gen only.

`Microsoft.Orelans.CodeGeneration.Build`?

**Comment by lexia** [comment]
```
Microsoft.Orelans.CodeGeneration.Build
```

Yep, seems fairly self-explanatory !

**Comment by jdom** [comment]
`Microsoft.Orleans.CodeGeneration.Build` sounds good. Also, currently the Templates packages that we are about to collapse into CodeGeneration.Build are also adding a nuget dependency to `Microsoft.Orleans.CodeGeneration` (used for runtime) which is wrong and should be removed.
