### ISSUE TITLE
Microsoft.Orleans.OrleansRuntime nuget package dependency for DI packages missing.

### ISSUE THREAD

**Issue by attilah** [dotnet/orleans#1150]
the nuspec file for Microsoft.Orleans.OrleansRuntime is missing the DI package dependency definitions:
Microsoft.Extensions.DependencyInjection
Microsoft.Extensions.DependencyInjection.Abstractions

**Comment by amamh** [comment]
Could it be because it's a pre-release package?

**Comment by sergeybykov** [comment]
Yes, that's the reason. When the DI packages are released as a stable version, we need to add them to OrleansRuntime, and remove the OrleansDependencyInjection workaround for this.

**Comment by sergeybykov** [comment]
Resolved via https://github.com/dotnet/orleans/pull/1878.
