### ISSUE TITLE
Problem running Orleans Client on IISExpress

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#1156]
After the introduction of Telemetry APIs the TraceLogger class is unable to open/write the trace file while running the Orleans Client on an IISExpress development server.

The error happens on `Line 271 in TranceLogger.cs`

```
Trace.TraceError("Error opening trace file {0} -- Using DefaultTraceListener instead -- Exception={1}", exc);
```

The problem is that the log file is being written on the IISExpress.exe directory on Program Files which is protected by UAC.

The problem was also reported by @attilah on Gitter:

![image](https://cloud.githubusercontent.com/assets/4714040/11830322/e78bd024-a38a-11e5-960b-7ed94183fdf0.png)

[**Workaround**] run Visual Studio as Administrator while I fix this bug.

Thanks

**Comment by centur** [comment]
I hit similar problem, but not with IIS but with Azure SDK emulator and 2 concurrent access attempts to the same logfile. It's not the same problem but it shows that current choice of default behaviour is not good. I think the default behaviour for telemetry must be - write to mock TelemetryConsumer which should do nothing (discard the data), and only if user wants to collect it and explicitly adds particular provider in code or config - it must push data to the configured collector.

**Comment by galvesribeiro** [comment]
Does the problem still happen? There were several changes and fixes at the consumers. Otherwise we should close it.

**Comment by galvesribeiro** [comment]
Closing it as the problem don't happen on 2.0.
