### ISSUE TITLE
Who's using Orleans in Production?

### ISSUE THREAD

**Issue by ghuntley** [dotnet/orleans#1184]
This is somewhat related to #1171 - branding and marketing.

![marketing](https://cloud.githubusercontent.com/assets/127353/11921017/53774052-a7d2-11e5-9a70-3144a8777822.png)

Orleans has had some really fantastic success stories but they just haven't been publicly shared in a easy to consume/centralised location. Use this issue to share companies/projects who are using the Orleans Framework in production and how the framework is being used. 
- Company Name or Project
- What business outcome is being solved with the framework.
- Why the framework was chosen.
- Technical details (FSharp, Azure, NServiceBus) etc.
- Any marketing materials, such as presentations/talks or videos.

**Comment by sergeybykov** [comment]
Please also don't forget to add your company to http://dotnet.github.io/orleans/Who-Is-Using-Orleans.

**Comment by jthelin** [comment]
Original tweet is here:
https://twitter.com/gregyoung/status/678612900878131202
