### ISSUE TITLE
Guid is not properly deserialized in Json serializer.

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#1187]
Seems that ##752 is back again.

When turning on ```UseJsonFormat="true"``` in config - first silo start is working fine, data is nicely saved in json format and all looks good. On consequent runs  - Silo throws Deserialization exception on first encountered stateful grain (in my case it's current UserGrain to check permissions):

```
  "ClassName": "Orleans.Runtime.OrleansException",
    "Message": "Forwarding failed: tried to forward message NewPlacement Request S127.255.0.0:11111:188375097*grn/A5831D15/00000000@4eb809a6->S127.255.0.0:11111:188375097*grn/20286B2F/00000000+095b3cc6f368a382cee5e48bedeff6c7cacd4f30bce8e3d98612e1534363202a@a5c2b583 #47[ForwardCount=2]: global::DBCloud.ActorInterfaces.Users.IUserGrain:GetState() for 2 times after Failed SetupActivationState to invalid activation. Rejecting now. System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Orleans.Storage.AzureTableStorage.ConvertFromStorageFormat(GrainState grainState, GrainStateEntity entity)\r\n   at Orleans.Storage.AzureTableStorage.<ReadStateAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClassa.<<QueueTask>b__8>d__c.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Orleans.Runtime.Catalog.<SetupActivationState>d__35.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Orleans.Runtime.Catalog.<InitActivation>d__2b.MoveNext()",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": null,
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2146233088,
    "Source": null,
    "WatsonBuckets": null
```

**Comment by centur** [comment]
I can recall I saw similar issue in 1.0.9 too, but by that time I was messing with the silo setup and discounted this exception on my messed up configuration

**Comment by gabikliot** [comment]
But this call does  not seem to be related to Streaming: `DBCloud.ActorInterfaces.Users.IUserGrain:GetState()`
#752 was about streaming: it failed to json-deserialzie Orleans internal class `PubSubGrainState`.

If this is your own state, then Orleans has nothing to do with how you serialize your state to Json.

**Comment by centur** [comment]
umm,I think it's serializer failure. Isn't UseJsonFormat="true" suppose to switch serializer from binary to json fir entire provider?

**Comment by gabikliot** [comment]
Yes, it does. And Newtonsoft json serializer fails on that type.
The class has to be Json Serializable. Not every C# will correctly serialize in Json (as opposite to the binary .NET serialization and Orleans's binary serializer). It has to follow certain rules. It's actually a bit tricky to get it always right. And sometimes it will serialize without any error indication but then won't deserialize.

**Comment by centur** [comment]
Is there a reason why this class won't be serialized and deserialized properly ?
```
[Serializable]
	public class UserState: BaseGrainState
	{
		public string Id { get; set; }
		public string FirstName { get; set; }
		public string LastName { get; set; }
		public string UserAlias { get; set; }
		public string CompanyName { get; set; }
		public string Position { get; set; }
		public string Phone { get; set; }
		public string LoginAccountName { get; set; }
		public string LoginPasswordHash { get; set; }
		public string LoginPasswordSalt { get; set; }
		public Guid ActivationId { get; set; }
		public bool IsOptInForCommunication { get; set; }
		public NotificationSettings NotificationSettings { get; set; }
		public string AssignedSubscription { get; set; }
		public List<string> ManagedSubscriptions { get; set; }
		public List<string> Projects { get; set; }
	}
```
NotificationSettings type has 4 booleans and serialized deserialized without any issues.
I'm 99% sure that Json.NET can serialize\deserialize this class without any problems

**Comment by gabikliot** [comment]
Looks OK I think.
Maybe `BaseGrainState`?
Try serializing and deserializing it in isolation, with just a unit test.

**Comment by centur** [comment]
Ok I did some addition manual testing (don't have a handy sample to run full blown silo, we are testing against in-memory providers). And I think I found the problem:
Deeper exception says 
```
System.ArgumentException occurred
  HResult=-2147024809
  Message=Object of type 'System.String' cannot be converted to type 'System.Guid'.
  Source=mscorlib
  StackTrace:
       at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
  InnerException: 
```
and happens in this method: 
```
AzureTableStorage.cs; Line: 297
internal void ConvertFromStorageFormat(GrainState grainState, AzureTableStorage.GrainStateEntity entity)
{
...
dictionary = JsonConvert.DeserializeObject<Dictionary<string, object>>(entity.StringData, this.jsonSettings);
...
}
```

The JSON that's being fed into it is :
```
{
  "$type": "System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[System.Object, mscorlib]], mscorlib",
  "ActivationId": "4dfbaa4c-c401-4905-b554-56eb7867e1a9",
  "AssignedSubscription": null,
  "CompanyName": null,
  "FirstName": "Alex",
  "Id": "095b3cc6f368a382cee5e48bedeff6c7cacd4f30bce8e3d98612e1534363202a",
  "IsOptInForCommunication": true,
  "LastName": "Annotations",
  "LoginAccountName": "bullcliptest+alex@drawboard.com",
  "LoginPasswordHash": "wi0DbMovXxZmzQCPTndVZlQjJtYhO6gYn1hG3K/KOzcovoewAK4W4Ad5fFmiiqx44dBS4LWQhis8nJfDGmFcAQ==",
  "LoginPasswordSalt": "jH2NETmIovRgMYiPlfm+JjVhk9SMyBldg+KlqKDCT7tUg6jHjpDEbWTk+A3vy1/6Cr8CMu8yqloegminN61S6w==",
  "ManagedSubscriptions": {
    "$type": "System.Collections.Generic.List`1[[System.String, mscorlib]], mscorlib",
    "$values": []
  },
  "NotificationSettings": {
    "$type": "DBCloud.ActorInterfaces.Notifications.Model.NotificationSettings, DBCloud.ActorInterfaces",
    "EnableGlobalAnnouncements": false,
    "EnableProject": false,
    "EnableDocument": false,
    "EnablePersonal": false
  },
  "Phone": null,
  "Position": null,
  "Projects": {
    "$type": "System.Collections.Generic.List`1[[System.String, mscorlib]], mscorlib",
    "$values": []
  },
  "UserAlias": "bullcliptest+alex@drawboard.com"
}
```

**Comment by gabikliot** [comment]
So Guid does not deserialize back from string? Could be.  Weird.

So how json should be configured to deserialzie guid?
You can experiment with it locally, without Orleans at all, and once you figure that out you can submit a test with Guid json deserialization into: https://github.com/dotnet/orleans/blob/master/src/Tester/SerializationTests/SerializationTests.JsonTypes.cs
and also suggest a change into https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs#L107. 
Maybe we need to add a converter for Guid?

Or maybe this is related:
http://stackoverflow.com/questions/9117182/incorrect-serialization-in-c-sharp-using-json-net
http://stackoverflow.com/questions/11991577/missing-guid-when-deserializing-object-using-json-and-c-sharp
http://tinymission.com/post/custom-serialization-for-json-properties-in-web-api

Referring back to my previous comment: https://github.com/dotnet/orleans/issues/1187#issuecomment-166229928 " Not every C# object will correctly serialize in Json"

**Comment by centur** [comment]
yes, working on this now :) - trying to verify that Serialization settings Orleans is using with Json.NET are actually causing this issue. Struggling a bit with a nested class in linqpad

**Comment by centur** [comment]
I think the pain point here is that the data is being Deserialized to Dictionary<string,object> and some type information is being lost. When I deserialized the json above and printed each value type - I got this

>ActivationId - System.String

which is not really a correct result. But Json.NET doesn't have this problem when it works directly with objects - see attached DeserializationBug.zip - it has LINQPad sample which performs (de)serialization to an object directly - Guid is a known type for Json and it doesn't preserve $type information for it when serializing (which may be wrong and it's a bug in Json.NET)

[DeserializationBug.zip](https://github.com/dotnet/orleans/files/70341/DeserializationBug.zip)

Is there a way to introduce converters like when we know that property is Guid and we got "string" back in the deserialized Dictionary<string,object> - we need to perform a call to configurable ```Func<string,Guid>``` ?

**Comment by gabikliot** [comment]
How about: submit a PR reproducing a bug and I will look into it?

**Comment by centur** [comment]
:+1:

**Comment by ReubenBond** [comment]
For the record, I also experience this bug - I never looked into it, but it's a crippling issue with that provider.

**Comment by gabikliot** [comment]
The provider was never meant to be a full proof provider. It was meant to be a sample.
Anyway, will fix all this. Just submit repros.

I will also make it possible to configure Json settings on this provider and in Orleans's Json serializer.
I really want to take us out of the business of configuring Json serializers.

**Comment by centur** [comment]
After a bit more digging in - I've submitted an [issue #762](https://github.com/JamesNK/Newtonsoft.Json/issues/762)  to Json.NET.

It's actually a bug in Json.NET, but I think there is some space for Orleans deserializer to be a bit more robust for such issues. One can't expect serializers are perfect.

**Comment by gabikliot** [comment]
Great!
It would still be nice if you also submitted a repro to Orleans (Test case) and I will see how I can fix it in Orleans (probably writing a special Guid converter), regardless of the Json.NET fix (or maybe it is considered a feature there).

**Comment by ReubenBond** [comment]
> The provider was never meant to be a full proof provider. It was meant to be a sample.

For clarity, this provider is intended for production use now, correct?

**Comment by gabikliot** [comment]
Yes, it is.

**Comment by centur** [comment]
Thanks for the clarification :+1:

**Comment by gabikliot** [comment]
I think this happens since Guid does not have an empty constructor, but I am not sure. Would be interesting to get their answer.

**Comment by gabikliot** [comment]
Looks like it is a "feature" of Json.Net serializer: https://github.com/JamesNK/Newtonsoft.Json/issues/728
For some reason, "GUID is like string" similarly to how "int is like long", and "double is like decimal". Intriguing.

**Comment by centur** [comment]
This is a bit strange "feature" which may break many things - I care less about other dependant libraries ( still it's good to know about such defaults) but assuming that fallback serializer in Orleans is exactly Json.NET - such mis-conversions can break many other edge cases for state serialization \ deserialization.

**Comment by gabikliot** [comment]
So we got no official answer from Json.Net?
Maybe you want to ping them directly again? Otherwise, we are in a full agreement that "This is a bit strange "feature" which may break many things", and not just in Orleans but everywhere Json.Net is used.

**Comment by gabikliot** [comment]
I figured out how to do that: #1249.
http://stackoverflow.com/questions/21908262/newtonsoft-json-deserializeobject-emtpy-guid-field

      public override bool CanConvert(Type objectType)
     {
          return objectType.IsAssignableFrom(typeof(Guid));
     }

and not `return (objectType == typeof(Guid));`

But the support on https://github.com/JamesNK/Newtonsoft.Json is really "outstanding".

**Comment by centur** [comment]
Great work, 
btw Reuben's snippet also solves potential issue with Nullable<Guid>
