### ISSUE TITLE
Asp.net 5 - Cannot find an implementation class for grain interface

### ISSUE THREAD

**Issue by elmortega** [dotnet/orleans#1189]
I´m getting this exception:

An unhandled exception occurred while processing the request.

ArgumentException: Cannot find an implementation class for grain interface: OrleansWebAppTest.Models.IHello. Make sure the grain assembly was correctly deployed and loaded in the silo. Loaded grain assemblies: file:///C:/Users/byrmanager/Documents/Visual Studio 2015/Projects/TemporalProjects/orleans/src/OrleansConsoleHost/bin/Debug/OrleansRuntime.DLL
en Orleans.Runtime.TypeCodeMapper.GetImplementation(Type interfaceType, String grainClassNamePrefix) en C:\Users\byrmanager\Documents\Visual Studio 2015\Projects\TemporalProjects\orleans\src\Orleans\IDs\TypeCodeMapper.cs:línea 17

The public bool TryGetGrainClassData method in the GrainInterfaceMap.cs returns false as it doesn´t seem to be able to get an implementation for the provided interface as the this.typeToInterfaceData.TryGetValue(GetTypeKey(interfaceType, false), out interfaceData) method returns false

In my project.json:

"frameworks": {
    "dnx451": {
      "dependencies": {
        "Orleans": "1.0.0-*",
        "OrleansProviders": "1.0.0-*"
      }
    }
  },

**Comment by richorama** [comment]
Does the silo successfully load your assembly? You should it scan for assemblies at startup, it tells you if it found anything in each of the DLLs it looked in...

**Comment by elmortega** [comment]
How can I make sure the grain assembly was correctly deployed and loaded in the silo?

**Comment by richorama** [comment]
Orleans searches the directory where the host application is located, as well as the `Applications` sub-directory, and all directories under it.

**Comment by elmortega** [comment]
I thought I could just put my grain interfaces and implementation code in the webapp's model folder. but I guess that way the silo host wouldn't be able to load my grain classes, right?

**Comment by elmortega** [comment]
loadedAssemblies contains only one, the OrleansRuntime.DLL

**Comment by richorama** [comment]
How are you hosting the Orleans silos?

**Comment by elmortega** [comment]
Console Application http://dotnet.github.io/orleans/Step-by-step-Tutorials/Minimal-Orleans-Application

**Comment by richorama** [comment]
Are your grain assemblies in the `bin\debug` directory of the console application? 

An convenient way of doing that is to add them as references and set them to copy locally.

**Comment by richorama** [comment]
did that fix the problem?

**Comment by elmortega** [comment]
It was solved when using the v1.1.0-VSIX project templates

**Comment by asifshiraz** [comment]
I'm facing the same problem. In my case, I'm initializing the TestCluster from inside a unit test's constructor. The Grain and GrainInterface projects are referenced by the Unit Tests and are available in the bin/x64/Debug folder of the Unit Tests project. Still, the Silo complains of not having the assembly loaded.

**Comment by sergeybykov** [comment]
@asifshiraz Can you open a separate issue with information about which version you are running. Are you grain classes public, BTW?

**Comment by jamescarter-le** [comment]
Be aware that if you have your grains in an *.exe file and include this as a reference in your UnitTest project Orleans will not scan this assembly for Grains, they must be in a *.dll file instead.

**Comment by philrowan-mtb** [comment]
I just came across this and found out my grain class was not inheriting `Orleans.Grain` and was only implementing my grain interface. Adding `Orleans.Grain` fixed it for me.

**Comment by sergeybykov** [comment]
A code analyzer could potentially help find such issues and produce warnings.

**Comment by sq735** [comment]
> I just came across this and found out my grain class was not inheriting Orleans.Grain and was only implementing my grain interface. Adding Orleans.Grain fixed it for me.

Thanks a lot

**Comment by sergeybykov** [comment]
> I finally solved it by adding a reference to the nuget package: Microsoft.Orleans.OrleansCodeGenerator.Build in the silo, grains, and grain interfaces projects.

There's no need to add it to the silo project.

**Comment by fadingdust** [comment]
Note: `Microsoft.Orleans.CodeGenerator.MSBuild` is a viable alternative to `Microsoft.Orleans.OrleansCodeGenerator.Build`
