### ISSUE TITLE
SerializationException when running nUnit tests - "Not allowed member of type ""Orleans.Runtime.Silo+SiloType,OrleansRuntime...

### ISSUE THREAD

**Issue by KazAlx** [dotnet/orleans#1208]
Taking "HelloWorld" sample (using Orleans 1.1.0), add nUnit Nuget packages and make HelloWorldSiloTests changes to enable test runner to properly locate config files
 (please see attached files, renamed to .txt)
[packages.config.txt](https://github.com/dotnet/orleans/files/73213/packages.config.txt)
[HelloWorldSiloTests.cs.txt](https://github.com/dotnet/orleans/files/73212/HelloWorldSiloTests.cs.txt)
 
the test runs fine when using MSTest. However when switched to nUnit, there is an exception

Exception during test initialization: 
Exc level 0: System.Runtime.Serialization.SerializationException: Not permitted member type "Orleans.Runtime.Silo+SiloType,OrleansRuntime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null".
   in System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   in Orleans.TestingHost.TestingSiloHost.LoadSiloInNewAppDomain(String siloName, SiloType type, ClusterConfiguration config, AppDomain& appDomain)
   in Orleans.TestingHost.TestingSiloHost.StartOrleansSilo(SiloType type, TestingSiloOptions options, Int32 instanceCount, AppDomain shared)
   in Orleans.TestingHost.TestingSiloHost.<InitializeAsync>d__16.MoveNext()

**Comment by sergeybykov** [comment]
This is strange. The code seems to create an instance of `CodeGeneratorOptimizer` which extends `MarshalByRefObject`. Is it possible that assemblies form different versions are mixed up somehow?

Also, @jthelin has played with nUnit, and I think he was more successful than that.

**Comment by KazAlx** [comment]
No modifications to original HelloWorld's references to Orleans have been made; only nUnit references added... I can provide the entire solution archive if it helps

**Comment by jthelin** [comment]
Apart from using the nunit test runner, the only other thing i needed to do was to turn off the shadow-copy option. 

I haven't tried NUnit recently with Orleans unfortunately though, so something may have gotten broken with some recent change?

**Comment by jthelin** [comment]
There were some other weird problems running tests on the Jenkins build servers with NUnit though so the original change had to be put on hold.
https://github.com/dotnet/orleans/pull/575

xUnit seems to be generally preferred testing framework for DotNet OSS projects now.

**Comment by kobynet** [comment]
This happens to me as well, using HelloWorld project, easy to reproduce by adding Nunit3 nuget and replacing the attributes 
[TestClass] -> [TestFixture]
[ClassCleanup] -> [TearDown]
[TestMethod] -> [Test]

Either install [Nunit3 test adapter tool for vs](https://visualstudiogallery.msdn.microsoft.com/0da0f6bd-9bb6-4ae3-87a8-537788622f2d) and then run from Test Explorer window or run test using the nunit3 cli tool.

It just might be related to [NUnit3 Assembly Isolation](https://github.com/nunit/nunit/wiki/Assembly-Isolation) but that is just a hunch.

**Comment by sergeybykov** [comment]
We switched to xUnit awhile ago.
