### ISSUE TITLE
Forwarding failed exceptions

### ISSUE THREAD

**Issue by k1918u42** [dotnet/orleans#1209]
We have about 12 Orleans silos (azure worker roles) supporting around 100 web roles.  Every couple weeks some of the Orleans silos start throwing forwarding failed exceptions:

    Forwarding failed: tried to forward message Request S[ip]:11111:188604562*cli/5bebe9bf@7d8cfb97->S[ip]:11111:186066337*grn/7A74AB6F/45a25a8d@12e5569b #116808238[ForwardCount=2]: [GrainType + Method] for 2 times after Non-existent activation to invalid activation. Rejecting now.

Through analyzing the ip addresses in the exception and correlating to the SiloInstances table we're able to determine which roles are generating the error.  Restarting the role fixes the issue temporarily (usually for a week or two).

Searching the existing issues I see this error can occur when the Global Grain GC limit is less than 1 minute (issue #271).  We haven't set this value though and the default limit of 2 hours should apply.

Have you encountered this issue before and if so what was the resolution?

**Comment by sergeybykov** [comment]
@k1918u42 What version of Orleans is this with? What you described sounds similar to the issue fixed by https://github.com/dotnet/orleans/pull/955.

**Comment by k1918u42** [comment]
We're running 1.0.5.  If #955 is in 1.1.0 we'll try upgrading and see if that fixes.

**Comment by gabikliot** [comment]
Also, just in case it does keep happening, try to check if this happens always to the same grain (same grain type and same grain id), or different grains of the same type or different grain types.

`[ip]:11111:186066337*grn/7A74AB6F/45a25a8d@12e5569b`
Hash of the grain type: 7A74AB6F
Hash of the grain id: 45a25a8d
Activation ID: 12e5569b

**Comment by k1918u42** [comment]
Will do, thanks!

**Comment by sergeybykov** [comment]
@k1918u42 Please update us if the upgrade will resolve the issue.

**Comment by k1918u42** [comment]
Ok, it may be a couple months before the update reaches our production environment but I'll try to remember to let you know.

**Comment by gabikliot** [comment]
Ye, we are used to this "suspend and resume 3 month later" process. The context is fully re-loadable into the fast cache from a reliable persistent disk.

**Comment by sigmadon** [comment]
I know this was a long time ago, but was there any progress/feedback on this? We're seeing the same thing but running on a later version (1.4.1)

**Comment by sergeybykov** [comment]
@sigmadon There are multiple potential reasons for something to manifest as this error. For example, failing to load grain's state or grain code blocking threads. Do you see any other warning/errors in the logs? Can you share the logs?
