### ISSUE TITLE
Orleans Stream - CEP

### ISSUE THREAD

**Issue by angshuman-agarwal** [dotnet/orleans#1214]
Hi,
Sorry - this is not an issue but rather a generic question - Is it possible to _do_ or **extend** the current stream implementation to do _complex event processing_ like filtering, adding custom user functions, joining 2 streams, aggregating on the stream. (_in real-time_) ?

```
priceStream.Select(price=>price.Symbol).SlidingWindow(price, 1s).Where(price=>price.UpdateTime > DateTime.Now.AddSeconds(-2)) ; 

```
Something on [these lines](http://esper.sourceforge.net/esper-0.7.5/doc/reference/en/html/EQL.html) 

Thanks

**Comment by dVakulen** [comment]
Extending of the current implementation is definitely possible, and there is suggestion to do it at http://dotnet.github.io/orleans/Student-Projects:
 > Declarative dataflow language over streams. Define and build a Trident-Storm like declarative language over Orleans streams. Develop an optimizer that configures the stream processing to minimize overall cost.

**Comment by angshuman-agarwal** [comment]
ah..thanks :smile: Then may be I can build a Rx wrapper on client side for now and try to work that way. Something like - 

```
return Observable.Defer(() => client.GetStream())
                .Select(factory.Create)                
                .Catch<Price>(Observable.Empty<Price>())
                .Repeat()
                .Publish()
                .RefCount();
```
where,
GetStream() internally will be - (Client can subscribe to this)

```
        public IObservable<Price> GetPriceStream()
        {
            return subject.AsObservable();
        }
```
where, subject  -

```

/// IAsyncObserver<IPrice>
public Task OnNextAsync(IPrice item, StreamSequenceToken token = null) 
        {
            subject.OnNext(priceObj);            
            return TaskDone.Done;
        }

```

**Comment by gabikliot** [comment]
You can definitely build Rx wrapper on the client, like you wrote. That should be easy.
On the server, inside grains, you need to be careful about `SynchronizationContext` in Rx. It is possible to do correctly, as discussed here: https://github.com/dotnet/orleans/issues/315

**Comment by angshuman-agarwal** [comment]
@gabikliot - Thanks ! That helps.
