### ISSUE TITLE
Possible serialization issue when using different Orleans versions

### ISSUE THREAD

**Issue by randa1** [dotnet/orleans#1219]
I'm not sure this is actually a problem, I'll explain our workflow and would like to hear your opinion.

We're currently working on an application that uses our Kafka stream provider as an external library (via NuGet). As of now, both our application and the stream provider assembly reference Orleans 1.1.0.

We also have an internal Orleans build in our company, that uses the Orleans master. This build is pushed to an internal NuGet server with an internal minor version - e.g. 1.1.0.1, 1.1.0.2, etc.

This creates an inconvenience because of an implementation detail of the Orleans assembly loading:
Currently in `AssemblyProcessor`, assemblies are loaded only if they reference Orleans. This check considers the reference only if the assemblies' full name match, meaning - including exact version. It means that when upgrading the Orleans version in my application (even if it's a minor version), I must also upgrade the Orleans version in the provider project, publish a new NuGet, etc. If I don't, the types from the stream provider are not loaded by the serializer, and I get a serialization exception when the stream provider is used.

The inconvenience here is pretty clear - I must update Orleans in ALL dependencies before updating it in my application, even if the change has nothing to do with codegen or serializations.

This is the relevant code:
**AssemblyProcessor:**
```c#
// If the assembly does not reference Orleans, avoid generating code for it.
if (TypeUtils.IsOrleansOrReferencesOrleans(assembly))
{
      // Code generation occurs in a self-contained assembly, so invoke it separately.
      CodeGeneratorManager.GenerateAndCacheCodeForAssembly(assembly);
}
```

**TypeUtils:**
```c#
internal static bool IsOrleansOrReferencesOrleans(Assembly assembly)
{
      return DoReferencesContain(assembly.GetReferencedAssemblies(), OrleansCoreAssembly)
            || string.Equals(assembly.FullName, OrleansCoreAssembly, StringComparison.Ordinal);
}
```

Is this by design? If so, maybe we should consider changing it, seeing as it will become a major burden in large projects and it will become larger as Orleans releases become more frequent.

**Comment by gabikliot** [comment]
Looks like `IsOrleansOrReferencesOrleans` is only used in this context and it should be no harm to change the comparison to `assembly.GetName().Name` instead of `FullName`.
That should fix it, right?

**Comment by randa1** [comment]
Yes, I think so. I wanted to understand whether it's intentional though.

**Comment by gabikliot** [comment]
I don't see a reason why not to allow a more flexible versioning in this particular case. But maybe @sergeybykov or @reubenbond think otherwise?

**Comment by jthelin** [comment]
Yes, it makes sense to either remove version numbers from the check, or else only compare the first two Major.Minor part of the version numbers.

Semantic versioning principles say that there should be no breaking API changes in the Patch or Build parts of version numbers.

XRef: Major.Minor.Patch.Build
http://semver.org

**Comment by randa1** [comment]
Thanks @jthelin. Makes sense.

**Comment by sergeybykov** [comment]
I don't see a problem with this either approach (using `Name` or a portion of assembly version).
