### ISSUE TITLE
 Hosting AzureSilo and Web layer on the same worker role

### ISSUE THREAD

**Issue by loneshark99** [dotnet/orleans#1220]
This is a question . In Azure, can a same worker role be a Client (http but selfhosted webapi)  as well as host the Orleans Silo.  As per the examples I have seen they are separate roles.

**Comment by gabikliot** [comment]
They can. But yay need to host the client in a separate app domain. There are some examples in samples and unit tests.

**Comment by loneshark99** [comment]
@gabikliot thank you, worked perfectly.

**Comment by gabikliot** [comment]
Great.
