### ISSUE TITLE
sqlServer dataBase migration

### ISSUE THREAD

**Issue by El-amine** [dotnet/orleans#1227]
Hi, i have designed an application with sqlserver 2014 like database. Now i must deploy it on some computers that have sql server 2008.
How can i do the database migration ? 
thanks for your help
best regards

**Comment by veikkoeeva** [comment]
@El-amine Hi! If you mean how to create Orleans specific tables for SQL Server 2008, running the script ([here](https://github.com/dotnet/orleans/blob/master/src/OrleansSQLUtils/CreateOrleansTables_SqlServer.sql)) should just work. You shouldn't have data migration problems either, I remember the only difference on data structures is between SQL Server 2000 and newer (2008 and newer have some performance tuning tweaks).
