### ISSUE TITLE
client choses loopback adapter when not specificed

### ISSUE THREAD

**Issue by amccool** [dotnet/orleans#1243]
I'm troubleshooting why some of my clients register themselves with a IP of 127.0.0.1 (no networking is defined in clientconfiguration.xml
gatewayprovider=SqlServer)
this line:
             bool isLoopbackInterface = (i == NetworkInterface.LoopbackInterfaceIndex);

in ClusterConfiguration.cs
is deciding that my Hyper-V Virtual Ethernet Adapter #3 is a loopback adapter

that particular adapter is what should be getting used for the client, but instead the real loopback is chosen in
         if (candidates.Count > 0) return PickIPAddress(candidates);

because the real loopback wasn't filtered out correctly as NetworkInterface.LoopbackInterfaceIndex is incorrectly reporting the adapter index

I'm running both ipv4 and ipv6

perhaps this is due to hyper-v virtual switches on my clients?

I see that netInterfaces[X].NetworkInterfaceType has a better indicator
Ethernet or Loopback

perhaps this instead?

             bool isLoopbackInterface = (netInterface.NetworkInterfaceType == NetworkInterfaceType.Loopback);

**Comment by gabikliot** [comment]
@amccool , do you think https://github.com/dotnet/orleans/issues/1136 and https://github.com/dotnet/orleans/issues/1135 are related to this ?

**Comment by gabikliot** [comment]
Fixed via #1244.

**Comment by amccool** [comment]
#1136 is not related, different storage issue
not positive on #1135, I will have a look
