### ISSUE TITLE
How do I plug: orleans.serialization.json into my grains?

### ISSUE THREAD

**Issue by ukluk** [dotnet/orleans#1257]
Please share a sample on how to consume and register the Orleans Json Serializer (or any custom serializer) , I want to use the default TableStorage State Provider, but would like to serialize as Json.

**Comment by gabikliot** [comment]
Pass  UseJsonFormat="true" to AzureTableStorage in config.
See example here: https://github.com/dotnet/orleans/blob/master/src/TesterInternal/Config_StreamProviders.xml#L10
