### ISSUE TITLE
Do not deactivate System grains

### ISSUE THREAD

**Issue by gabikliot** [dotnet/orleans#126]
In dev settings, when using Reminder table grain, if Activation GC is set to a small time, the Reminder table grain will be deactivated.
This is described here:
https://orleans.codeplex.com/discussions/580531

Change Activation GC to never deactivate ReminderTableGrain grain (MembershipTableGrain is already handled correctly and is never deactivated).

**Comment by yevhen** [comment]
That probably should be considered a bug rather than an "enhancement" :)

**Comment by weitaolee** [comment]
oh. very good

**Comment by jthelin-microsoft** [comment]
Fixed in PR #129
