### ISSUE TITLE
TODO: Turn on Code Analysis for the Orleans.dll developer API assembly.

### ISSUE THREAD

**Issue by jthelin** [dotnet/orleans#1263]
Recording this work item as a relatively easy Up-For-Grabs issue that anyone wanting to get more involved with Orleans project could take on.

TODO: Turn on Code Analysis to run automatically during build of the main developer API in `Orleans.dll` assembly by ticking the "Enable Code Analysis on Build" checkbox in project properties.

Then need to make minor code changes to fix any issues identuified by Code Analysis -- mostly missing IDisposable functions on some classes that use other IDisposable resources.

The main goal is to get a clean pass (zero CA warnings) from "_MIcrosoft Minimal Recommended Ruleset_" when running Build.cmd of Visual Studio build.

A stretch goal would be to use "_MIcrosoft Managed Recommended Ruleset_", but that is a significantly more onerous task requiring more code fixes.

Extra credit: 
`OrleansAzureUtils.dll` is the other "developer facing" assembly containing often use public Orleans APIs. Would be good to turn on Code Analysis for that assembly too, either as separate PR or combined with this one.

**Comment by leonpw** [comment]
I will look into this

**Comment by sergeybykov** [comment]
Resolved via #2335.
