### ISSUE TITLE
Questions about on-premise Orleans deployment

### ISSUE THREAD

**Issue by angshuman-agarwal** [dotnet/orleans#1268]
Hi,
In the [UnitTesting](http://dotnet.github.io/orleans/Step-by-step-Tutorials/Unit-Testing-Grains) page, the 4th bullet point mentions this - 

> In production there is no primary and secondary silos: all silos are equal and behave in a peer-to-peer fashion.

Does it mean that if I am running self-hosted Orleans SILO **(not using MS Azure)**, I can only host one SILO per server (which is Primary) ? Can someone please suggest on how to set up the SILO cluster in Production with a sample config (preferably)? Are there any limitations ? I followed this [article](https://coderead.wordpress.com/2014/08/29/overrides-in-orleans-configuration/) to create a cluster.

So with above approach I can set up multiple SILOs but need to tell Client only about one (Primary/Secondary) and Orleans will figure out the cluster members automatically.

**Comment by gabikliot** [comment]
>Does it mean that if I am running self-hosted Orleans SILO (not using MS Azure), I can only host one SILO per server (which is Primary) 

No.There are no Primary/Secondary, unless in testing, even on prem. All of them are Secondaries.

http://dotnet.github.io/orleans/Step-by-step-Tutorials/On-Premise-Deployment

>So with above approach I can set up multiple SILOs but need to tell Client only about one (Primary/Secondary) and Orleans will figure out the cluster members automatically.

No. There are no Primary/Secondary, unless in testing, even on prem.
You point clients to all of them, all of them are Secondaries.

**Comment by angshuman-agarwal** [comment]
Thanks @gabikliot  - will take a look and ask if any doubts.

**Comment by angshuman-agarwal** [comment]
@gabikliot 
How I monitor the Orleans (cluster) on-premise deployment ? 

As described here - http://dotnet.github.io/orleans/Advanced-Concepts/Runtime-Monitoring, 
_There are five ways Orleans deployment can be monitored by an external operator by utilizing the data that Orleans writes automatically to Azure storage._

Is it something we can do with On-Premise deployment too ? Is this suffice -https://github.com/dotnet/orleans/blob/master/misc/scripts/RemoteDeployment/MonitorOrleansSilos.ps1

**Comment by gabikliot** [comment]
You can definitely do all of those, except 4 (MDS , which is an internal Azure monitoring and alerting system). 
1) You can watch cluster membership in your system store, 
2+3) you can watch silo/client metric and statistics, depending on where you redirected them. If you don't want them to go to Azure Table, you can either configure them to got to SQL (we have SQL statistics provider now), or write your own provider for storing statistics elsewhere.
4) You can hook in your own Log Consumer and redirect all Orleans logs into where ever you want. Log statements come with semantic information, which includes error codes, so you can watch those in your favorite on prem monitoring and alerting system. 
5) Windows performance counters for sure.
6) MonitorOrleansSilos.ps1 will give you some basic info as well, but frankly we did not use it much recently, as I don't know how up to date this script is. 

You can **contribute to improve it**, or to any other tools that will make running Orleans on prem smoother.
For example, [those guys are using Consul to manage Orleans's based services](#1226), and [contributing Consul integration](#1267), which makes us super happy. And of course [Gigya contributed Zookeeper System](#493) store as well as [Kafka stream provider](#1205). Both those companies are using Orleans on prem.

**Comment by angshuman-agarwal** [comment]
Thanks @gabikliot 
I believe this is what you are referring to - http://dotnet.github.io/orleans/Advanced-Concepts/Configuring-SQL-Tables

The **CreateOrleansTables_*** link in the article is not working. But I found them - https://github.com/dotnet/orleans/tree/master/src/OrleansSQLUtils

Hope this is what you are collectively referring to. I will go through them.

**Comment by sergeybykov** [comment]
I fixed the *CreateOrleansTables_** link in the docs.
