### ISSUE TITLE
TestAll.cmd not passing on current master (c554be5)

### ISSUE THREAD

**Issue by sebastianburckhardt** [dotnet/orleans#1271]
I would like to run TestAll.cmd locally, routinely, to test my local changes (merges, branches, etc.) before submitting them to GitHub.

However, the tests are not passing right now, console output (somewhat abbreviated) is:

Starting test execution, please wait...
Skipped  Generic_OnAzureTableStorage_LongNamedGrain_EchoValue
Skipped  AQ_Filter_Basic
Skipped  AQ_Filter_EvenOdd
(...)
Passed   Silo_Config_MembershipGrain
Passed   Silo_Config_AzureTable
Passed   Liveness_Azure_1
Passed   Liveness_Azure_3_Restart_GW
Passed   Liveness_Azure_4_Restart_Silo_1
Failed   Silo_Config_SqlServer
Error Message:
   Test 'Silo_Config_SqlServer' exceeded execution timeout period.

Perhaps this is a configuration issue? I could not find any documentation on how one is supposed to run TestAll.cmd, other than some old issues mentioning that Storage Emulator must be running (which it is).

**Comment by sergeybykov** [comment]
There are still some issues with the tests that I'm trying to clear. I'm investigating them now that nearly all tests have been migrated.

**Comment by galvesribeiro** [comment]
@sebastianburckhardt for the failure on SQL connection it is probably either one of those reasons: 1. you don't have SQLExpress installed or 2. You don't have the LocalDb (which comes with VS!) installed or 3. something is blocking SQL connection. 

@veikkoeeva  can you add something here?

**Comment by veikkoeeva** [comment]
@galvesribeiro Missing any SQL Server is one plausible explanation or that firewall ports are blocked (see [script to open them](https://blog.brankovucinec.com/2015/12/04/scripts-to-open-windows-firewall-ports-for-sql-server/)). I ran `TestAll.cmd` for latest master and I got `Passed   Silo_Config_SqlServer`. I got plenty of other failures, which I suppose @sergeybykov is investigating currently. Places to download and install SQL Server versions can be found [here](http://stackoverflow.com/questions/23320013/how-to-install-localdb-separately) or [here](http://www.hanselman.com/blog/DownloadSQLServerExpress.aspx).

On a related note, it has been discussed to auto-detect if a relational database or some other piece is present and if not, mark those tests as skipped.

**Comment by sergeybykov** [comment]
@sebastianburckhardt, is this still an issue?

**Comment by sebastianburckhardt** [comment]
Tried it today. The console is full of error messages... 

but given that I see this line near the bottom
   Orleans.NonSiloTests  Total: 262, Errors: 0, Failed: 0, Skipped: 1, Time: 282.201s

I am going to optimistically assume everything is o.k. and close this issue.
