### ISSUE TITLE
VS 2015 C# Templates not Rendering Correctly

### ISSUE THREAD

**Issue by zeus82** [dotnet/orleans#1277]
With version 1.1.0 of the VS extension, when I try to create a new Orleans Grain Interface, the resulting C# is:

``` C#
using System.Threading.Tasks;
using Orleans;

namespace $safeprojectname$
{
    /// <summary>
    /// Grain interface IMyGrain1
    /// </summary>
    public interface IMyGrain1 : IGrainWithGuidKey
{

}
}

```

$safeprojectname$ should be the appropriate namespace, same thing happens when trying to create an Orleans Grain Class.

**Comment by sergeybykov** [comment]
What version of VS is this with? Have you tried uninstalling/reinstalling the VSIX?

**Comment by zeus82** [comment]
I have tried uninstalling and re-installing, still get the same problem.  I'm running VS 2015 Update 1 (Enterprise)

**Comment by sergeybykov** [comment]
@zeus82 I can't seem to repro this. VS 2015 Update 1 Enterprise. Maybe a VS corruption or something? Can you try on a different machine?

**Comment by angshuman-agarwal** [comment]
Even I got the same issue with VS 2015 Enterprise.

**Comment by zeus82** [comment]
I just tried it on my personal computer with VS 2015 Community with Update 1.  I installed Orleans 1.1.0 for the first time and I got the same problem.  I don't know if this helps, but the name of the project I created was "Test.Backend.Orleans" and so is the default namespace.  The project is a .NET 4.6.1 "Orleans Grain Interface Collection"

**Comment by sergeybykov** [comment]
I am still unable to reproduce this, even after I uninstalled and re-downloaded the VSIX, targeted 4.6.1 I specified "Test.Backend.Orleans" as the project name. There must be a missing repro step here I think but I can't think what it can be. Do you have system local set to a different language by chance?

**Comment by zeus82** [comment]
My Work machine is Windows 10 Enterprise (64 bit) and my Language is English (Canada).  I also have English (United States), but its second in the list, so I assume Canada is the default.  All formatting follows my language defaults.

I'm pretty stumped as well.  I poked around in the code, and it looks good!

**Comment by sergeybykov** [comment]
I tried on both Windows 8.1 and 10 with VS 2015.1, and was unable to reproduce the problem that you are seeing. I'm dumbfounded. I suspect this might be a VS bug, but without a stable repro it's impossible to say for sure.

**Comment by timfun** [comment]
I have the same issue here with the latest version of vs extension. I get the same outcome.

**Comment by jason-bragg** [comment]
on vs2017+ now
