### ISSUE TITLE
StorageProviders Usage in Production w.r.t. Streams : PubSubStore / MemoryStore

### ISSUE THREAD

**Issue by angshuman-agarwal** [dotnet/orleans#1282]
Hi,
I am little confused on the usage of the 2 stores and exactly when to configure what in the config XML when dealing with _Streams_ - 

```
<StorageProviders>
      <Provider Type="Orleans.Storage.MemoryStorage" Name="MemoryStore" NumStorageGrains="1"/>
      <Provider Type="Orleans.Storage.MemoryStorage" Name="PubSubStore" NumStorageGrains="1"/>
</StorageProviders>
```

The code comments [here](https://github.com/dotnet/orleans/blob/master/src/OrleansProviders/Storage/MemoryStorage.cs) says- 

>    /// <remarks>
    /// This storage provider is ONLY intended for simple in-memory Development / Unit Test scenarios.
    /// This class should NOT be used in Production environment, 
    ///  because [by-design] it does not provide any resilience 
    ///  or long-term persistence capabilities.
    /// </remarks>

And, the code [here](https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Streams/PubSub/PubSubRendezvousGrain.cs), uses the Store - What I understand is that we can store the **PubSubGrainState in the storage we intend to define in the config XML**

```
[Orleans.Providers.StorageProvider(ProviderName = "PubSubStore")]
internal class PubSubRendezvousGrain : Grain<PubSubGrainState>, IPubSubRendezvousGrain
```

Is this correct to state for any Stream PubSubState  persistence ?
```
<StorageProviders>
      <Provider Type="Namespace.MyStorage" Name="PubSubStore" NumStorageGrains="1"/>
</StorageProviders>
```

**Comment by angshuman-agarwal** [comment]
I think the above question is invalid. I was thinking and I kind of get it now after going through the [code](https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Streams/PubSub/PubSubRendezvousGrain.cs)

**Comment by gabikliot** [comment]
I am glad you figured that out.

Just for completeness, in case someone else will be looking here in the future, I will answer.

Storage provider has a name and type. The name is what ever you give it. The type is the concrete implementation. In the configuration, you specify the type of the provider (implementation class) and give an arbitrary name to it.

Our streaming infrastructure expects you to define `StorageProvider` with name "PubSubStore". It can be StorageProvider of any type.

Therefore, in testing you can define `<Provider Type="Namespace.MyStorage" Name="PubSubStore"/>` while in prod you can define 
`<Provider Type="Orleans.Storage.AzureTableStorage" Name="PubSubStore" />`
OR
`<Provider Type="Namespace.MyStorage" Name="PubSubStore" />`
