### ISSUE TITLE
CodeGen Serializer is generated for private nested class with enum

### ISSUE THREAD

**Issue by jason-bragg** [dotnet/orleans#1283]
CodeGen will try to generate a serializer for the private nested class B in the following code.

If A is not generic, everything is fine.
If B is public everything is fine.
If enum is in A (private or public) everything is fine.
If there is no enum in C, everything is find.
But put them all together, and Codegen thinks it should generate a serializer for the private nested class 
B.
No idea why :)
Very amusing though.

    public class A<T>
    {
        private class B
        {
            public enum C
            {
            }
        }
    }

**Comment by jason-bragg** [comment]
Tagging @ReubenBond as he may have an idea what this is.

As an FYI, this is not blocking me, I just moved the enum into A and made it private, which seems to work.

**Comment by ReubenBond** [comment]
Thanks for the heads up, I've submitted an attempt at a fix in #1284.
