### ISSUE TITLE
PersistentStreamProvider: How to come up with a unique queue name in Adapter that a receiver can know? 

### ISSUE THREAD

**Issue by amamh** [dotnet/orleans#1295]
This is a question not an issue:

Assume the following setup:
- Using Redis as a backend to carry the streams. Each physical queue is just a simple Redis list.
- Server
  - **Adapter 0 is created by the server along with corresponding receivers**
    - **Receivers need to know the Redis list name to read from.**
  - Server reads using the receivers, caches and waits for Client 2 to subscriber.
- Client 1 writes
  - **Adapter 1 is created by Client 1. Adapter 1 chooses a name for the Redis list**
- Client 2 reads
  - Client is receiving messages from the server, it doesn't need to know anything beyond which provider to use.

So, the problem is that you have 2 different threads that need to share the same data. It doesn't have to be Redis, if I'm using MQ then I need to choose queue ID/name.

Whatever name I use in the writing adapter in Client 1, the server adapter which reads needs to know that name.

For now what I'm doing is simply using a name that's based on the queue number and provider name "orleans-MyProviderName-<QueueId>"

The problem with that is if I create a new client which creates a new adapter, it will write to the same location and that will cause clashes if I also use the same stream GUID and namespace.

This seems like a common problem, there must be a simple way to solve this?

**Comment by gabikliot** [comment]
Why does it cause clashes?

**Comment by amamh** [comment]
@gabikliot 

Well, if you are using the same Redis server (or MQ or w/e else) and you use the same List names (or queues names, etc) from different writing adapters, wouldn't that be a problem?

**Comment by gabikliot** [comment]
I have no idea. Never used Redis.
 In azure Queue you can enqueue to the same Queue from different clients. In event hub you can produce to the same hub/topic from different clients.

**Comment by amamh** [comment]
@gabikliot 

I didn't expect you to know Redis. It's just a simple list used as a queue.

The problem can be generalised as: **"How do you give a unique ID to each independent cluster of Silos?"**. "Cluster" can be just one server.
In this particular situation, that's useful because then each cluster (and its connected clients) will differentiate between its own messages (and its clients' messages) and other messages that it shouldn't try to read/alter.


I thought maybe someone can point out an obvious way to solve this problem.

**Comment by jason-bragg** [comment]
@amamh 
As you're writing your own adapter, it seems to me that you can pass in whatever additional configuration information you need (like any Redis information) through the stream configuration, which will show up in the property bag in the IProviderConfiguration passed into the adapter factories Init call.

A second issue is consistently mapping QueueId's (the queue identifier used by the agent) to the adapter specific resource.  One way of doing this is by building a mapping from the QueueId to the Redis resource in the IStreamQueueMapper.  Take a look at how this is done in EventHubQueueMapper.

**Comment by amamh** [comment]
@jason-bragg 

I guess I could pass something like a GUID in the config that will be the same for the whole cluster and all its clients so that they all have a shared unique identifier that they use to know which Redis list (or w/e equivalent for other types of physical queues) is to be used by them.

For the QueueId => Redis resource, I just use the the ID itself in the name like this

`$"orleans-{providerName}-queue-{queueId}"`

Thanks for your help :)

**Comment by jason-bragg** [comment]
@amamh Glad that helped.

That naming convention, while functional, would make me nervous, as it appears to create a binding between the provider name and the resource.  My preference would be to have a well formed resource name, independent of the provider, then solve how to configure the provider to talk to the resource.

For instance.
Resource names:
"foogazy-news-feed/england"
"foogazy-news-feed/france"
"foogazy-news-feed/germany"

Then in stream provider config 
NewsPortal = "foogazy-news-feed"
NewsFeeds = "england, france, germany"

The adapter would register 3 queues, one for each feed, then map a queueId to each resource name.

This allows a well formed organization of the data independent of any stream providers that read it.
Not strictly necessary, but, imo, preferable to unnecessarily coupling the two.

**Comment by gabikliot** [comment]
Not sure why we need all that complications described above.

The question was very simple: "How do you give a unique ID to each independent cluster of Silos?".

The answer is trivial - lucky, we already have exactly THE right mechanism in place to do that: it is called **deployment id**. One needs to give a unique deployment id for every independent cluster of Silos. In Azure that is done automaticaly by Azure infra, on prem. you have to do it yourself. And f course, you need to include this deployment id as part of your persistent queue names. We do that exactly in Azure Queue Stream Provider.
Look how we do it here:
https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Providers/Streams/AzureQueue/AzureQueueAdapterReceiver.cs#L30. 
and here:

https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Storage/AzureQueueDataManager.cs#L88

**Comment by amamh** [comment]
@gabikliot 

yup, that's exactly what I wanted. So, it is like what Jason suggested, a config parameter that has to be shared with all servers/clients. I wonder if this could be supported by Orleans itself, something like `GrainClient.GetClusterID()`

Thanks everyone for your help

**Comment by amamh** [comment]
@jason-bragg 

Thanks for your suggestion, it's always good to know where I might have not followed a good approach. 

In this instance, I think it makes sense to use the provider name in the resource name because only this particular provider knows how to read/write to resources (Redis lists) used by it.

For example, there is a particular batch container type used by this provider, so you wouldn't be able to deserialise (read) anything from these resources if you don't know that type.
