### ISSUE TITLE
Enable installation as a service in OrleansHost.exe

### ISSUE THREAD

**Issue by creyke** [dotnet/orleans#1303]
This could simplify deployment of Orleans on premise, by providing a recommended version of the Orleans runtime host which can be installed as a Windows Service. In doing so, it could also pave the way for creation of container (Docker) system images for Orleans, which can be patched with application runtime binaries. It would also negate the need to have an additional project in an application solution; that being one that hand rolls a OrleansHost.exe variant which can be installed as a service.

**Comment by gabikliot** [comment]
+1 for smoother/out of the box script/special host to start Orleans as Windows service.

**Comment by veikkoeeva** [comment]
I wonder if this still needs refactoring. I remember @jdom did some work on providing a lighter weight style to start a silo, but I don't seem to find the code now.

Here is one idea, use [TopShelf](https://github.com/Topshelf/Topshelf) like [this](https://topshelf.readthedocs.org/en/latest/configuration/quickstart.html) to start a Windows server.  Essentially the refactoring @jdom did didn't differ that greately from [this](https://gist.github.com/veikkoeeva/4414609e828375c898f3) (don't look too much into the configuration part, just the wrapper around silo).

All in all, not many lines of code. If a command-line parser is needed, it can be added too.

**Comment by jdom** [comment]
Just as FYI. The changes I did were mostly to TestingSiloHost, where it's main use is in unit/functional testing, not really as a production deployment feature. It messes around with AppDomains and copying generated assemblies in and out of them, etc, which is not what we want in production.

Having said that, I totally agree with making it very simple to host in different environments with ease.

**Comment by ReubenBond** [comment]
Whatever we do, keep Linux/OS X in mind: that might mean creating a Windows-only `OrleansServiceHost` package rather that adding a platform-specific dependency to `OrleansHost`.
+1 for TopShelf, by the way.

**Comment by jdom** [comment]
yup, completely agree with that... not all of our binaries need to be platform agnostic...

**Comment by attilah** [comment]
I think that TopShelf can be a good xplatform way, since as I read thru they're doing xplat too (at least trying) ;-) and coreclr (sorry .Net Core 1.0) too.

**Comment by amccool** [comment]
What does this need for requirements in the configuration aspect?  Just standard support for the `OrleansConfiguration.xml`?  DI?

**Comment by galvesribeiro** [comment]
For those interested in Orleans+Docker check out #3004 and #3005
