### ISSUE TITLE
Special character like '/' in grain primary key failing reminder registration using azure table storage

### ISSUE THREAD

**Issue by somnathnitb** [dotnet/orleans#1309]
Hi Team,

We have a grain for which the primary key is like "tag:abcxyz123.com,2012:test/system#_68c362fd-6449-456b-928b-c57a17d586ed" with state stored in azure table storage. Grain activation without any reminder succeeds. But when we make this grain remindable and then grain activation is failing with Azure table storage bad request exception. From the source code I see that reminder table row key has direct mapping to Grian Primary key and what I believe is special characters are not allowed in table storage partition key and row key.
We are using orleans version 1.0.9 and not sure whether this has been fixed in later version or not.

Would really appreciate any help on this.

Error message:

EventName="MessageEvent" Message="[2016-01-21 02:58:21.999 GMT    21	ERROR  	100513	Catalog	100.105.68.47:11111]	!!!!!!!!!! Error calling grain's AsyncActivate method - Grain type = LCBS.Global.Gateway.Grains.GatewayGrain Activation = [Activation: S100.105.68.47:11111:191036279*grn/13519D0F/00000000+tag:abcxyz123.com,2012:test/system#_466bffd0-b041-47f5-a548-a7a026918f76Gateway@1a1563a4 #GrainType=LCBS.Global.Gateway.Grains.GatewayGrain State=Activating]	
Exc level 0: System.AggregateException: One or more errors occurred.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.GrainReference.<InvokeMethodAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LCBS.Global.Gateway.Grains.GatewayGrain.<RegisterReminder>d__4.MoveNext() in D:\builds\786433\LCBS-WEB-JOB1\src\LcbsWebApp\Production\Global\Gateway\LCBS.Global.Gateway\Grains\GatewayGrain.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LCBS.Global.Gateway.Grains.GatewayGrain.<OnActivateAsync>d__3.MoveNext() in D:\builds\786433\LCBS-WEB-JOB1\src\LcbsWebApp\Production\Global\Gateway\LCBS.Global.Gateway\Grains\GatewayGrain.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Catalog.<CallGrainActivate>d__6e.MoveNext()
Exc level 1: Microsoft.WindowsAzure.Storage.StorageException: Message = The remote server returned an error: (400) Bad Request., HttpStatusCode = 400, HttpStatusMessage = Bad Request, ExtendedErrorInformation.ErrorCode = InvalidInput, ExtendedErrorInformation.ErrorMessage = One of the request inputs is not valid.
RequestId:12abd0ad-0002-0109-41f7-53a6c5000000

Thanks,
Somnath

**Comment by gabikliot** [comment]
What lines 41 and 29 in the grain do? Do you have a stack trace for them, that include the reminder operation?

**Comment by somnathnitb** [comment]
Here is the code which is invoked in line 41(line 41 is await RegisterOrUpdateReminder(ReminderName,
                               reminderInvokePeriod, reminderInvokePeriod)):-

private const string ReminderName = "XyzReminder";

private async Task RegisterReminder()
        {
            var reminderInvokePeriod = TimeSpan.FromMinutes(10);
            await RegisterOrUpdateReminder(ReminderName,
                               reminderInvokePeriod, reminderInvokePeriod);
        }

**Comment by gabikliot** [comment]
This is weird.
We have the code to Sanitize the row/partition key. It is here: https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Storage/AzureStorageUtils.cs#L278
So somehow it is not doing the job.
Or maybe there are other characters that are not allowed that we are supposed to sanitize as well?

It would be very helpful if you could get to the bottom of what is not sanitized (maybe have a direct test where you use that key directly to Azure Table and see what needs to be sanitized).
Also please take into account that there are some differences between Storage Emulator and real service. Just something to be aware of in case you are using emulator.

**Comment by somnathnitb** [comment]
I would beg to differ on that. From Orleans source code of 1.0.9 looks like AzureStorageUtils is not used at all.
You can trace down from here https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/ReminderService/LocalReminderService.cs#L113

ReminderEntry object is created which has direct grain reference. Now if you go to https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Storage/AzureBasedReminderTable.cs#L157 you can easily figure out that it creates the row key based on grairef.ToKeyString() and then once table entity is constructed it directly goes and uses tabledatamanager to create the entry.

We are really blocked on this as we are not sure whether this can be pulled up as a bug or we need to go for some workaround.

PS: We did our testing on deployed instance directly using table storage.

**Comment by gabikliot** [comment]
If its a bu, we will definitely help to solve it asap.
But I fail to see the how we do not sanitize it.

[AzureBasedReminderTable.UpsertRow](
https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Storage/AzureBasedReminderTable.cs#L157) calls 
`ReminderTableEntry remTableEntry = ConvertToTableEntry(entry, remTableManager.ServiceId, remTableManager.DeploymentId);`

[ConvertToTableEntry](https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Storage/AzureBasedReminderTable.cs#L77) calls 
`string rowKey = ReminderTableEntry.ConstructRowKey(remEntry.GrainRef, remEntry.ReminderName);`

[ConstructRowKey](https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Storage/RemindersTableManager.cs#L29) calls 

`var key = String.Format("{0}-{1}", grainRef.ToKeyString(), reminderName); //grainRef.ToString(), reminderName);`
`return AzureStorageUtils.SanitizeTableProperty(key);`

[AzureStorageUtils.SanitizeTableProperty](https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Storage/AzureStorageUtils.cs#L274)

Therefore, the row key used for the table is sanitized, as far as I can tell.

**Comment by somnathnitb** [comment]
Thanks a lot for your input. That's the reason I have been pointing out that we are using 1.0.9. Below is the code in 1.0.9 version:-

public static string ConstructRowKey(GrainReference grainRef, string reminderName)
        {
            return String.Format("{0}-{1}", grainRef.ToKeyString(), reminderName); //grainRef.ToString(), reminderName);
        }

I think we have strong reason now to upgrade to latest version.

**Comment by gabikliot** [comment]
Yes, that was fixed in https://github.com/dotnet/orleans/pull/774/.

Isn't it nice to report a blocking bug and find out it was already fixed? Glad you are not blocked any more.

**Comment by somnathnitb** [comment]
It really is. :) Thanks a lot.

**Comment by sergeybykov** [comment]
:+1: Nice! Closing this then.

**Comment by gabikliot** [comment]
As was discovered by @centur and reported in https://github.com/dotnet/orleans/issues/1385, this function was not actually working correctly and sanitization not really happening.
Was foxed, for real now, in #1381.
