### ISSUE TITLE
Orleans.SqlUtils.StorageProvider.SqlStorageProvider

### ISSUE THREAD

**Issue by wxlTest** [dotnet/orleans#1315]
Hi,I am come from China.My english is poor.Who can teach me to use SqlStorageProvider.
This is my config:
 Provider Type="Orleans.SqlUtils.StorageProvider.SqlStorageProvider" Name="SqlUtilsStore" ConnectionString="Data Source=.;Initial Catalog=Orleans;Integrated Security=True;Pooling=False;Max Pool Size=200;Asynchronous Processing=True;MultipleActiveResultSets=True" 

Can someone tell me how to config MapName,ShardCredentials,StateMapFactoryType Property,or give me samples.

Thanks!

**Comment by sergeybykov** [comment]
Have you looked at https://github.com/dotnet/orleans/tree/master/src/TesterInternal/StorageTests/SQLAdapter? The tests should be a good starting point.

**Comment by amccool** [comment]
https://github.com/dotnet/orleans/pull/1321  will provide for creating a GrainStateMapFactory when using orleans via nugets.

there is some "hard" stuff to do in creating the database(s) correctly.   I'm hoping to have another PR to make it easier on the developer (and still work if the db work is done before hand)
namely this stuff:  https://azure.microsoft.com/en-us/documentation/articles/sql-database-elastic-scale-get-started/

**Comment by wxlTest** [comment]
Well,Thanks!
