### ISSUE TITLE
Need to try generate serializer for type arguments of IAsyncObserver<T>

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#1316]
From https://github.com/dotnet/orleans/issues/1286.

With `FireAndForgetDelivery=true` SMS streams silently lose events if those fail to serialize. While there is a design question of how surface such failures, a related mitigation is to include concrete type arguments of classes that implement `IAsyncObserver<T>` in the list of candidates for serializer generation.

If we find a class `Foo : IAsyncObserver<Bar>` we can try to generate a serializer for `Bar` to reduce the probability of the failure and to improve performance of passing event of that type.

**Comment by dVakulen** [comment]
Taking this one.

**Comment by gabikliot** [comment]
Closed via #1319.
