### ISSUE TITLE
Is "A Service is a Collection of Communicating Actors" tutorial page out of date?

### ISSUE THREAD

**Issue by apuchkov** [dotnet/orleans#1318]
I getting this error when I use code from [A Service is a Collection of Communicating Actors](http://dotnet.github.io/orleans/Step-by-step-Tutorials/A-Service-is-a-Collection-of-Communicating-Actors) Tutorial.

![image](https://cloud.githubusercontent.com/assets/150003/12517963/969f1126-c103-11e5-97b5-202d448b1d45.png)

```
Error	CS0311	The type 'GrainInterfaces1.IEmployee' cannot be used as type parameter 'TGrainInterface' in the generic type or method 'IGrainFactory.GetGrain<TGrainInterface>(Guid, string)'. There is no implicit reference conversion from 'GrainInterfaces1.IEmployee' to 'Orleans.IGrainWithGuidKey'.	Grains1	c:\Users\apuchkov\Documents\Visual Studio 2015\Projects\SiloHost1\Grains1\Manager.cs	12	Active
```

Also there some errors with code which goes to `Program.cs`
![image](https://cloud.githubusercontent.com/assets/150003/12520156/e4f84920-c110-11e5-9801-0a6ba898d2ad.png)

```
Error	CS1061	'IGrainFactory' does not contain a definition for 'GrainFactory' and no extension method 'GrainFactory' accepting a first argument of type 'IGrainFactory' could be found (are you missing a using directive or an assembly reference?)	SiloHost1	c:\Users\apuchkov\Documents\Visual Studio 2015\Projects\SiloHost1\SiloHost1\Program.cs	54	
```
```
Error	CS0311	The type 'GrainInterfaces1.IManager' cannot be used as type parameter 'TGrainInterface' in the generic type or method 'IGrainFactory.GetGrain<TGrainInterface>(Guid, string)'. There is no implicit reference conversion from 'GrainInterfaces1.IManager' to 'Orleans.IGrainWithGuidKey'.	SiloHost1	c:\Users\apuchkov\Documents\Visual Studio 2015\Projects\SiloHost1\SiloHost1\Program.cs	56	Active
```

It seems that `IEmployee` and `IManager` should implement `Orleans.IGrainWithGuidKey` instead of `Orleans.IGrain`.

**Comment by sergeybykov** [comment]
Yes, the tutorial is outdated (e.g. needs to use `IGrainWithGuidKey` instead of `IGrain`)  and appears to have bugs. I'll try to fix it ASAP.

Thanks for flagging it!

**Comment by sergeybykov** [comment]
I think I fixed it. Could you please double-check.

**Comment by apuchkov** [comment]
Looks good. Thank!

**Comment by zarda** [comment]
I tested. Might the "IGrainWithIntegerKey" be correct one.
