### ISSUE TITLE
Inconsistencies in "Concurrency" Tutorial

### ISSUE THREAD

**Issue by apuchkov** [dotnet/orleans#1320]
[Concurrency](http://dotnet.github.io/orleans/Step-by-step-Tutorials/Concurrency) tutorial has some inconsistencies, e.g. `GreetingData.From` property is declared as `long` and then used as `IEmployee`.

![image](https://cloud.githubusercontent.com/assets/150003/12521421/9a76e91c-c118-11e5-8991-3f12d2c1e4e6.png)

![image](https://cloud.githubusercontent.com/assets/150003/12521450/bd1768de-c118-11e5-8f76-975852da8a63.png)

**Comment by apuchkov** [comment]
Is documentation source hosted on a GitHub? I can't seem to find it.

**Comment by sergeybykov** [comment]
The documentation is in https://github.com/dotnet/orleans/tree/gh-pages.
