### ISSUE TITLE
Error Serializing classes that work in 1.1.0

### ISSUE THREAD

**Issue by bstead** [dotnet/orleans#1338]
Ive just updated from 1.1.0 to 1.1.2 and It appears that the serialization of many of my classes are no longer working.

Im getting a "No copier found for object of type Patient. Perhaps you need to mark it [Serializable] or define a custom serializer for it?" error when attempting to return an object that previously worked. 
Unfortunately, these classes are maintained by third parties, so I have limited control over them.

These classes do return false when running GetTypeInfo().IsSerializable(). I'll be able to dig in a bit more tomorrow to provide further details on this.

**Comment by sergeybykov** [comment]
What is 0.90.3 and 0.90.4? https://github.com/dotnet/orleans/releases/tag/v1.1.2 is the latest version we released.

**Comment by bstead** [comment]
@sergeybykov - Sorry about that, I crossed the wires a bit(Ive editted the issue)...we just updated from 1.1.0 to 1.1.2

**Comment by ReubenBond** [comment]
Could you please include a definition of your class and the project layout, @bstead? Also: does using `[assembly: KnownType(typeof(Patient))]` in an assembly which references Orleans fix it?

**Comment by bstead** [comment]
Hi Rueben, Thanks for the quick response. Adding the KnownType to the grainclass and interface did not help. Ill write up an example on the class layout.

**Comment by bstead** [comment]
Rueben,
Ive added a GIST here:
https://gist.github.com/bstead/73951672239d73005352

I haven't pinpointed the specific attribute/nesting etc. required to cause the error, but the shared example should be reproducible.

Thanks,
Ben

**Comment by ReubenBond** [comment]
@bstead thank you for that :) Could you please show me which NuGet packages each project has and also a representative sample of the Patient class?

Because your grain interface only returns a `Bundle` (which I assume contains a collection of `object`), we cannot tell that a `Patient` will ever be serialized at runtime, so the `KnownType` attribute is helpful.

**Comment by bstead** [comment]
@ReubenBond -
No problem- The nuget for the library containing the bundle is in the Gist readme.  Ive added the github repo link to the readme in the gist as well. I also added the Patient.cs file...hopefully this helps.

Thanks,
Ben

**Comment by bstead** [comment]
Let me know if there is anywhere else you would like to me to try applying knowntype

**Comment by bstead** [comment]
I created a stub method that explicitly returned a Patient Object in my grain interface which has me back up and running. 
Ive seen worse workarounds :)

**Comment by gabikliot** [comment]
@ReubenBond , could the problem be that @bstead  defined  `KnownType(typeof(Patient))` in the different assembly than the one that actually defines  `Patient`, and as a result we ignore the `KnownType` directive, since we expect it in the same assembly with the type?

**Comment by ReubenBond** [comment]
@gabikliot defining `KnownType` in another assembly ought to be fine - as long as that assembly is loaded by both client and silo.

@bstead I didn't find the `[KnownType(...)]` attribute in your gist.

**Comment by bstead** [comment]
@ReubenBond - I added the Assembly:KnownType for patient to the assembly info of graininterfaces, graincollection and silohost as well as the client. Unfortunately, no luck.

Its strange to me that this used to work at all. I see there was work done with nested object serialization, but prior to that I was retrieving the objects without a problem anyways.

**Comment by ReubenBond** [comment]
@bstead could you possibly upload a project which repro's the issue? Sorry for the hassle, it's hard for me to investigate otherwise
