### ISSUE TITLE
Etag is not set in OrleansMembershipTable for SQLServerMembership Provider

### ISSUE THREAD

**Issue by amccool** [dotnet/orleans#1341]
Trying to track down why my membership table always has 0x00000 for the Etag.

The VersionETag in OrleansMembershipVersionTable
is set correctly (e.g. not 0x000000)

Using the unit tests.   I removed the ETag column from the OrleansMembershipTable table

and removed it from these queries
MembershipReadRowKey
MembershipReadAllKey

Changed
RelationalOrleansQueries.CreateMembershipEntry
from
`etag = Convert.ToBase64String(record.GetValue<byte[]>("ETag"));`
to
`etag = Convert.ToBase64String(record.GetValue<byte[]>("VersionETag"));`

Now all the tests pass except
MembershipTable_SqlServer_UpdateRow

This test exposes that Etag is never matched in the where clause.   Apparently in the other tests the VersionEtag is being used

Should I create a PR to share code?

**Comment by amccool** [comment]
hopefully this is visible
https://github.com/dotnet/orleans/commit/bffa131489a8930d048707f7b6e00de2286b7e8c

**Comment by amccool** [comment]
@sergeybykov lets close this issue in favor of https://github.com/dotnet/orleans/pull/1360 being the fix

**Comment by sergeybykov** [comment]
Resolved via https://github.com/dotnet/orleans/pull/1360.
