### ISSUE TITLE
Namespaces do not match project settings

### ISSUE THREAD

**Issue by MovGP0** [dotnet/orleans#135]
Apparently the namespaces in the .cs files do not match the settings of the 'Default namespace' and the folder in which the files are located. 

Is it ok to make a pull request for just fixing namespaces?

**Comment by MovGP0** [comment]
I would put files who are in the right namespace but wrong folder into the correct folder. 

I um unsure how to handle files that are in the wrong namespace but correct folder. Moving public classes would be a breaking change and since it is in production now that might cause some unwanted issues. 

Would it be ok to move the internal classes and not the public ones?

**Comment by sergeybykov** [comment]
Could you clarify what definition of 'right' and 'wrong' you are applying here. Do you mean namespaces exactly matching the folder structure? The folder structure tries to organize the source files around related pieces of functionality. I'm not sure what we'll gain by blindly assigning namespaces to follow that structure or rearranging files according to the namespaces.

For example, we have a bunch of types in the Orleans.Runtime namespace that are spread across a number of folders. If we were to follow the rule and move, say, Catalog related types to Orleans.Runtime.Catalog and GrainTypeManager related types to Orleans.Runtime.GrainTypeManager, etc., would that be cleaner or just a bunch of extra namespaces with no added value?

Another example is the Orleans\IDs folder that holds types with some relation to identities from different parts of the runtime: QueueId and StreamId from Orleans.Streams and SiloAddress from Orleans.Runtime. With the proposal, would we have to move the source files to different folders to match their respective namespaces or to move them all to a single Orlean.IDs namespace?

**Comment by jthelin** [comment]
Merged PR #160 which is a partial solution to this question / issue.

Most of this is historic cruft based on the way the code evolved and restructured over time, so there may be other simple things that can be done to clean things up here without breaking changes to APIs.

If anyone spots any other major discrepancies, please flag them and/or submit small targeted pull requests.
