### ISSUE TITLE
Dependency on Azure assemblies

### ISSUE THREAD

**Issue by zdeneksejcek** [dotnet/orleans#136]
Hi,

is there a plan to remove Azure dependencies? I had a short look on source files and it seems like there are only few places that use Azure assemblies.

Thanks.

**Comment by sergeybykov** [comment]
Since Orleans can run with no actual dependency on Azure, removing the runtime assembly references and making them loadable based on config hasn't been a priority for us. A PR for it is more than welcome.

**Comment by veikkoeeva** [comment]
Has anyone thought about possible approaches? There are probably many ways to do this and one thing to notice is that, maybe, for example ``Microsoft.Data.*`` libraries wouldn't be required if Azure dependencies are removed from ``Orleans.csproj``. That is, framework and Nuget libraries the Azure libraries are dependent on.

**Comment by gabikliot** [comment]
One approach could be to move all Azure specific code into AzureUtils project, which we already have, and load it dynamically in other projects, where needed. The code is already factored out pretty well, everywhere we use Azure Storage there is always a factory class and everything is hidden behind interfaces. So I think the changes will be mostly local, inside those factory classes.
A PR for that would be very welcomed.

**Comment by gabikliot** [comment]
Now that #508 is merged this issue can be finally closed!
