### ISSUE TITLE
How to get all the activated GrainIds at any given point in time

### ISSUE THREAD

**Issue by loneshark99** [dotnet/orleans#1367]
This is a question.  Is there a way to get all the GrainIds that are currently active i.e those grain actually activated in the Silos.

The ManagementGrain Interface currently only returns, the count of grains per type.  Is this stored in one of the Azure Tables which orleans uses.

Thanks.

**Comment by gabikliot** [comment]
No, it is not stored in any table.
Every silo stores in memory the set of activations it currently hosts, an in addition there is a distributed directory that stores, also in memory the mapping from grain ID to the silo that currently has an activation for this silo.
It is possible to add methods to MgmtGrain to retrieve this information. As long is it is very clear that this should be used for management/troubleshooting only, and not as part of the programming model, it should be fine.

It should be also interesting to use Streams to stream back the (potentially large) list.
