### ISSUE TITLE
JSON Grains - Grain methods using JObject parameter types and/or return types.

### ISSUE THREAD

**Issue by jthelin** [dotnet/orleans#1368]
I created a minimal repro https://github.com/jthelin/orleans/pull/2 for what seems to be a bug with handling of grains using JSON parameters and/or return values of type `JObject`.

The code all builds ok, but the new test cases `JSON_GetGrain` and `JSON_EchoJson` both fail with exception:
`Cannot find an implementation class for grain interface: UnitTests.GrainInterfaces.IJsonEchoGrain`

I have traced through the GrainInterfaceMap code, and there is indeed no type mapping data present at runtime for IJsonEchoGrain

The "Loaded grain type summary" dump in the silo log does not list that grain either, but I can't see any errors in the silo log(s) about problems loading that grain type, or that it was skipped.
Build log and Silo log: https://gist.github.com/jthelin/1db4393ef330d451beaf

From the silo logs, the `TestGrains.dll` assembly which contains the JsonEchoGrain does get inspected and other grains in that assembly get loaded correctly.

There is already a test case for SerializationManager handling of `JObject` but not one for passing `JObject` values to/from grains.
https://github.com/gabikliot/orleans/commit/d957d272c77027df5d9cf7d897f74d1cb24cab40#diff-b2da0bfffa2a6b698e7d539d22c9889fR50

Any thought on how to narrow down why this grain type won't load correctly?

Test results:
https://ci.appveyor.com/project/jthelin/orleans/build/1.0.495/tests
```
[00:02:12] Failed   JSON_GetGrain
[00:02:12] 
[00:02:12] Error Message:
[00:02:12] 
[00:02:12]    Test method Tester.General.JsonGrainTests.JSON_GetGrain threw exception: 
[00:02:12] System.ArgumentException: 
Cannot find an implementation class for grain interface: UnitTests.GrainInterfaces.IJsonEchoGrain. 
Make sure the grain assembly was correctly deployed and loaded in the silo. 
Loaded grain assemblies:  
file:///C:/projects/orleans/TestResults/Deploy_appveyor 2016-02-03 19_59_10/Out/OrleansRuntime.DLL 
file:///C:/projects/orleans/TestResults/Deploy_appveyor 2016-02-03 19_59_10/Out/Tester.DLL 
file:///C:/projects/orleans/TestResults/Deploy_appveyor 2016-02-03 19_59_10/Out/TestInternalGrains.DLL 
file:///C:/projects/orleans/TestResults/Deploy_appveyor 2016-02-03 19_59_10/Out/TestGrains.DLL 
file:///C:/projects/orleans/TestResults/Deploy_appveyor 2016-02-03 19_59_10/Out/TestFSharp.DLL
[00:02:12] 
[00:02:12] Stack Trace:
[00:02:12] 
[00:02:12]    at Orleans.Runtime.TypeCodeMapper.GetImplementation(Type interfaceType, String grainClassNamePrefix) 
                 in c:\projects\orleans\src\Orleans\IDs\TypeCodeMapper.cs:line 17
[00:02:12]    at Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReference_FromType(Func`2 getGrainId, Type interfaceType, String grainClassNamePrefix) 
                 in c:\projects\orleans\src\Orleans\CodeGeneration\GrainFactoryBase.cs:line 25
[00:02:12]    at Orleans.GrainFactory.GetGrain[TGrainInterface](Int64 primaryKey, String grainClassNamePrefix) 
                 in c:\projects\orleans\src\Orleans\Core\GrainFactory.cs:line 87
[00:02:12]    at Tester.General.JsonGrainTests.<JSON_GetGrain>d__0.MoveNext() in c:\projects\orleans\src\Tester\General\JsonGrainTests.cs:line 20
[00:02:12] --- End of stack trace from previous location where exception was thrown ---
[00:02:12]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[00:02:12]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[00:02:12]    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

**Comment by gabikliot** [comment]
So you are saying its not that `JObject` is not serialized correctly, but even before that, the grain is not even loaded? That is very strange. 
And if you change the grain method `public Task<JObject> EchoJson(JObject data)` to get and return string instead of `JObject`  it suddenly all works? Very strange.

You should be able to debug that locally. Put a breakpoint in the place where assembly is loaded and look why we ignore that grain. You might find out that we have some complicated, potentially wrong, rule that prevents that grain from loading.

**Comment by gabikliot** [comment]
@jthelin, do you need more help investigating this?

**Comment by jthelin** [comment]
I figured out what the problem was, and it was our old friend bug in my code by forgetting to make my grain implementation class extend the `Grain` base class! :blush: 

We really do need to fix that "feature" because either server code-gen really should flag that as **error at build time**, anr/or silo assembly loader **should not silently** skip those classes that implement interface derived from `IGrain` but don't extend `Grain` or `Grain<T>`.
`TypeUtils.IsConcreteGrainClass(myGrain)` returns `false`

I seem to have a particular blind spot for repeating the Not-Extending-GrainBase bug in my code!

I am sending across my original PR to add JSON grain test case.

I have also been talking a look at how to fix the Not-Extending-GrainBase problem, but it is not easy with current AL code structure. I will log a separate issue to document this part of the problem.


Thanks for the offer of help @gabikliot
