### ISSUE TITLE
Lamport / vector clocks

### ISSUE THREAD

**Issue by jkonecki** [dotnet/orleans#1370]
Enhancement proposal: implement [Lamport clock](https://en.wikipedia.org/wiki/Lamport_timestamps) / [vector clock](https://en.wikipedia.org/wiki/Vector_clock).

The suggested implementation would require the runtime to maintain a clock for each thread and extend the `Grain` base class so it can access the clock.

The benefits include being able to apply partial ordering for events/updates raised by LogViewer (distributed grains / event-sourced grains).

**Comment by ReubenBond** [comment]
Closing this since we haven't gotten to it yet and do not have an application for them in the near future. We can consider them for specific application and include them in the design. Thank you for the suggestion, Jakub
