### ISSUE TITLE
Code generation causes project to be built twice

### ISSUE THREAD

**Issue by Liversage** [dotnet/orleans#1377]
I recently upgraded my project to 1.1.2. Unfortunately, I have run into an issue where my project is built twice by msbuild. I am using Octopus Deploy and part of the build on the build server is to create an Octopus Deploy nuget package that is then pushed to a repository. The problem I am facing is that this happens twice during build and the second push will then fail because the repository does not allow overwriting an existing package.

I have managed to reproduce the problem by creating a new Visual C# Class Library project and then compile it using the following commands:

    msbuild /t:Clean
    msbuild

The following targets will be built for the project:

    ValidateSolutionConfiguration
    GenerateTargetFrameworkMonikerAttribute
    CoreCompile
    CopyFilesToOutputDirectory

Now update the project by adding a reference to the `Microsoft.Orleans.Templates.Grains` nuget package. Building the project as described above will result in more targets being built:

    ValidateSolutionConfiguration
    OrleansCodeGeneration
    GenerateTargetFrameworkMonikerAttribute
    CoreCompile
    _CopyFilesMarkedCopyLocal
    CopyFilesToOutputDirectory
    OrleansCodeGeneration
    GenerateTargetFrameworkMonikerAttribute
    CoreCompile
    CopyFilesToOutputDirectory

As you can see `CoreCompile` and associated targets are built twice. In most cases this is benign but when using the `OctoPack` nuget package the target to create the Octopus Deploy package and push it is also built twice leading to a build failure.

I have not been able to figure out a way to fix this but any input is very welcome.

**Comment by sergeybykov** [comment]
I'm not familiar with Octopus. Is it possible to separate the package building piece into a separate project?

**Comment by jthelin** [comment]
The Octopus Deploy problem is maybe just a symptom rather than root-cause here, but here's more info on what it is @sergeybykov 
https://octopus.com/why

Just to clarify @Liversage -- does your project contain both grain interfaces and grain implementation classes in single project?

I am not that familiar with how code-gen works nowadays, but might it actually be two separate "builds" happening here - one for interface / client code-gen and one for server code-gen?

Would one possibility be to trigger the Octopus "Push" operation from the `AfterBuild` or `BeforePublish` steps instead?
https://msdn.microsoft.com/en-us/library/ms366724.aspx

/cc: @ReubenBond

**Comment by Liversage** [comment]
The issue here is that if you add a reference to the `Microsoft.Orleans.Templates.Grains` nuget package (and I believe also the `Microsoft.Orleans.Templates.Interfaces` nuget package) the project will start being built twice by msbuild.

Do not focus too much on my Octopus Deploy story. I just wanted to explain why building the same project twice is in fact a problem. My description on how to demonstrate the issue does not involve Octopus Deploy. It is very easy to repro so I thought it was easier to explain how to do that instead of providing a complete project.

That being said this may only be a problem for projects the does something that can only be done once and the only thing I can come up with is publishing a specific version of a nuget package to a feed that does not allow package versions to be overwritten. So perhaps this is a corner case problem. But it is unexpected that the project is built twice by msbuild and sooner or later someone else will be hit by this.

I will consider your suggestions on how to fix my specific Octopus Deploy problem. I have been so focused on understanding the problem that fresh input on how to work around it is appreciated.

To enable continuous deployment I simply need to add the `OctoPack` nuget package and my own nuget package for versioning plus add some properties to the msbuild command line and bam! my project is deployed after a build. Except it does not work when the project contains Orleans code generation. So I will probably have to hand edit some gnarly XML in my `.csproj` to enable this functionality.

**Comment by Liversage** [comment]
I have been unable to find a solution that fixes the root cause of the problem (that grain projects are being built twice by msbuild). However, I have been able to create a workaround for my specific Octopus Deploy problem that might be useful for someone else having a similar problem.

I have added the following to my `.csproj` file:

    <PropertyGroup>
      <OctoPackSentinelFile>$(MSBuildProjectDirectory)\.octopacked</OctoPackSentinelFile>
    </PropertyGroup>
    <Target Name="BeforeClean">
      <Delete Files="$(OctoPackSentinelFile)"/>
    </Target>
    <Target Name="AfterBuild">
      <CreateProperty Value="" Condition="Exists($(OctoPackSentinelFile))">
        <Output TaskParameter="Value" PropertyName="OctoPackPublishPackageToHttp"/>
      </CreateProperty>
    </Target>
    <Target Name="BeforeOctoPack" BeforeTargets="OctoPack">
      <WriteLinesToFile File="$(OctoPackSentinelFile)" Lines="octopacked"/>
    </Target>

When OctoPack is executed a sentinel file is created. The `AfterBuild` target (that executes after the normal build but before the `OctoPack` target) checks for the existence of this file. If it exists it clears the `OctoPackPublishPackageToHttp` property. When this property is empty the nuget package is not published to the nuget package feed. On the first build the file does not exist and the nuget package is published. On the second build the file exists and no conflicting nuget packaged is published.

It is a kludge but it works for me.

**Comment by sergeybykov** [comment]
@Liversage The double build process is by design today - we build the project without codegen, run reflection over the produce assembly to find artifacts to codegen, generate orleans.codegen.cs, and rebuild the assembly. We were told it would be possible to insert codegen into the Roslyn compilation pipeline, so that it would run inline as part of it, but I'm not sure if it's actually possible today.

A workaround like yours is the easiest solution I think.

**Comment by Liversage** [comment]
@sergeybykov Thanks for the update. Now I know that I need a workaround for the double build so I am closing the issue.
