### ISSUE TITLE
Use ReadTheDocs as a rendering frontend for documentation

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#1379]
There was a suggestion to consider migrating our docs to http://docs.readthedocs.org/en/latest/index.html. The concern about such a migration is maintaining code and docs in two different systems with different futures, economics, access control, etc.

The alternative option to explore is to leverage ReadTheDocs as a "frontend" for rendering the docs in gh-pages. If that can be reliably set up via post-built hooks, we may get better looking and versioned documentation without moving the doc "sources" away from our repo.

**Comment by richorama** [comment]
Here is the result of doing a naive import of the unmodified gh-pages branch directly into readthedocs:

http://ra-orleans.readthedocs.org/en/gh-pages/

**Comment by gabikliot** [comment]
I think its very convenient to have the docs in the sam repo with the sources. I will definitely favor that options, even if it means we can't move to ReadTheDocs at all. The frontend options sounds OK.

What about the style that dotnet core is using? http://dotnet.github.io/docs/
Can we have different frontend styles for the same docs repository?

**Comment by ghuntley** [comment]
Have lots of to contribute on this subject but I'm about to goto bed. Nerd snipe me if I forget to reply back to this topic. Short story is I've tried many different combinations for http://docs.reactiveui.net and ended up moving away from RTD to Gitbook which is so much better. 

Also "orleans.readthedocs.org" is attached to my account, can be xfered. :-)

**Comment by sergeybykov** [comment]
We switched to using DocFx.
