### ISSUE TITLE
PVS-Studio: OnDeliveryFailure and OnSubscriptionFailure have same body

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#1387]
OnDeliveryFailure and OnSubscriptionFailure have same body, but different expected semantic.

**V3013 It is odd that the body of 'OnDeliveryFailure' function is fully equivalent to the body of 'OnSubscriptionFailure' function (70, line 84). AzureTableStorageStreamFailureHandler.cs 70**

```
      public Task OnDeliveryFailure(GuidId subscriptionId, string streamProviderName, IStreamIdentity streamIdentity,
            StreamSequenceToken sequenceToken)
        {
            return OnFailure(subscriptionId, streamProviderName, streamIdentity, sequenceToken);
        }

        public Task OnSubscriptionFailure(GuidId subscriptionId, string streamProviderName, IStreamIdentity streamIdentity,
            StreamSequenceToken sequenceToken)
        {
            return OnFailure(subscriptionId, streamProviderName, streamIdentity, sequenceToken);
        }

```

**Comment by gabikliot** [comment]
I don't think it is a bug or there is anything "Odd" about having 2 functions having same body, when the functions implement an interface and are there to allow customization in general, but in this particular implementation of the interface the implementation is identical.

**Comment by sergeybykov** [comment]
By design.
