### ISSUE TITLE
PVS-Studio: excessive prefix check - StartsWith("boot") check also covers "bootstrap" cases

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#1389]
We can get rid of first check as second check covers all cases which first one does.

**V3053 An excessive expression. Examine the substrings '/bootstrap' and '/boot'. ClientGenerator.cs 310**

```
 else if (arg.StartsWith("/bootstrap") || arg.StartsWith("/boot"))
```

**Comment by ReubenBond** [comment]
This is very much benign, but we should get rid of one and probably be more strict in parsing codegen args.

**Comment by noamyogev84** [comment]
I think this issue no longer exits. :)

**Comment by ReubenBond** [comment]
Thanks, @noamyogev84!
