### ISSUE TITLE
PVS-Studio: same implementations for semantically different methods  in test and utility grains.

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#1391]
Set of warnings about  copy-pasted implementation of semantically different methods:
I've sorted them out by projects and put the runtime and utility ones on top. 
Many of these may be false positives but still worth to look through for "copy-paste" errors.

---

Orleans project:

**... 'OnDeliveryFailure' function is fully equivalent to the body of 'OnSubscriptionFailure' function (23, line 29). NoOpStreamFailureHandler.cs 23**

**... 'UnregisterProducer' function is fully equivalent to the body of 'UnregisterConsumer' function (36, line 50). ImplicitStreamPubSub.cs 36**

**... 'ProducerCount' function is fully equivalent to the body of 'ConsumerCount' function (55, line 60). ImplicitStreamPubSub.cs 55**

**... 'Start' function is fully equivalent to the body of 'Close' function (41, line 46). SimpleMessageStreamProvider.cs 41**

---

BondUtils project:

**... 'ReadUInt16' function is fully equivalent to the body of 'ReadVarUInt16' function (22, line 57). InputStream.cs 22**

**... 'ReadUInt32' function is fully equivalent to the body of 'ReadVarUInt32' function (27, line 62). InputStream.cs 27**

**... 'ReadUInt64' function is fully equivalent to the body of 'ReadVarUInt64' function (32, line 67). InputStream.cs 32**

---

TesterInternal project:

**...'StartTimer' function is fully equivalent to the body of 'StopTimer' function (183, line 188). TesterInternal TimerOrleansTest.cs 183**

**... 'SplitScript' function is fully equivalent to the body of 'ConvertToExecutableBatches' function (13, line 44). MySqlStorageForTesting.cs 13**

**... 'TestInitialize' function is fully equivalent to the body of 'TestCleanup' function (32, line 39). GatewaySelectionTest.cs 32**

**... 'TestInitialize' function is fully equivalent to the body of 'TestCleanup' function (44, line 52). ConfigTests.cs 44**

**... 'GrainReference_DotNet_Serialization' function is fully equivalent to the body of 'GrainReference_DotNet_Serialization_Unresolved' function. GrainReferenceTest.cs 53**

**... 'PredFunc' function is fully equivalent to the body of 'StaticPredFunc' function (806, line 811). BuiltInSerializerTests.cs 806**

**... 'Init' function is fully equivalent to the body of 'Close' function (76, line 82). MockStatsCollectors.cs 76**

**... 'Init' function is fully equivalent to the body of 'Close' function (129, line 135). MockStatsCollectors.cs 129**

**... 'ClassCleanup' function is fully equivalent to the body of 'TestInitialize' function (42, line 48). LocalStoreTests.cs 42**

**... 'Persistence_Grain_Write' function is fully equivalent to the body of 'Persistence_Write' function (210, line 318). PersistenceGrainTests.cs 210****

---

TestGrains project

**... 'OnCompletedAsync' function is fully equivalent to the body of 'OnErrorAsync' function (33, line 38). ConsumerEventCountingGrain.cs 33**

**... 'GetAxB_Async' function is fully equivalent to the body of 'GetAxB' function (24, line 57). PromiseForwardGrain.cs 24**

**... 'GetAxB_Async' function is fully equivalent to the body of 'GetAxB' function (28, line 61). PromiseForwardGrain.cs 28**

**... 'GetA_Async' function is fully equivalent to the body of 'GetA' function (44, line 69). PromiseForwardGrain.cs 44**

**... 'DoIt' function is fully equivalent to the body of 'DoMore' function (39, line 44). GrainInterfaceHierarchyGrains.cs 39**

**... 'DoIt' function is fully equivalent to the body of 'DoThat' function (72, line 77). GrainInterfaceHierarchyGrains.cs 72**

**... 'DoIt' function is fully equivalent to the body of 'DoMore' function (122, line 144). GrainInterfaceHierarchyGrains.cs 122**

**... 'SetState' function is fully equivalent to the body of 'SetStateData' function (20, line 37). ValueTypeTestGrain.cs 20**

---

TestInternalGrains project:

**... 'Ping' function is fully equivalent to the body of 'Send' function (81, line 91). StressTestGrain.cs 81**

**... 'OnActivateAsync' function is fully equivalent to the body of 'DoSomething' function (43, line 66). PersistenceTestGrains.cs 43**

**... 'ProduceSequentialSeries' function is fully equivalent to the body of 'ProduceParallelSeries' function (618, line 625). StreamingGrain.cs 618**

**Comment by ReubenBond** [comment]
I think we can close this and maybe run more static analysis soon.
