### ISSUE TITLE
PVS-Studio: Missing throw keyword in OrleansRuntime.MemoryStorageGrain

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#1396]
**V3006 The object was created but it is not being used. The 'throw' keyword could be missing: throw new InconsistentStateException(FOO). OrleansRuntime MemoryStorageGrain.cs 129**

```
                    if (currentETag != null)
                    {
...
                        new InconsistentStateException(error);
                    }
```

**Comment by gabikliot** [comment]
I can't believe compiler didn't give a warning.

**Comment by ReubenBond** [comment]
Some of these bugs really ought to be picked up by the compiler or at the very least, ReSharper.

**Comment by gabikliot** [comment]
I wonder if our compiler settings in VS projects should be set to be more strict.
