### ISSUE TITLE
PVS-Studio: Some TesterInternal warnings

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#1400]
Some medium severity warnings around the code in TesterInternal tests. 

**V3032 Waiting on this expression is unreliable, as compiler may optimize some of the variables. Use volatile variable(s) or synchronization primitives to avoid this. TesterInternal LoggerTest.cs 468**

**V3051 An excessive type check. The object is already of the 'Exception' type. TesterInternal PersistenceGrainTests.cs 178**

**Comment by ReubenBond** [comment]
I think we can close this and maybe run more static analysis soon. Thanks for reporting it, Alexey :)
