### ISSUE TITLE
PVS-Studio: Tests - TesterInternal RequestContextTest has some suspicious formatting

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#1402]
Some hard to read formatting that is error prone

**V3043 The code's operational logic does not correspond with its formatting. The statement is indented to the right, but it is always executed. It is possible that curly brackets are missing. TesterInternal RequestContextTest.cs 87**

**... TesterInternal RequestContextTest.cs 97**

**... TesterInternal RequestContextTest.cs 111**

**... TesterInternal RequestContextTest.cs 155**

**... TesterInternal RequestContextTest.cs 181**

All code is like this one: 

```
            if(msg.RequestContextData != null) foreach (var kvp in msg.RequestContextData)
            {
                headers.Add(kvp.Key, kvp.Value);
            };
```

**Comment by ReubenBond** [comment]
I think we can close this and maybe run more static analysis soon.
