### ISSUE TITLE
AzureTableDataManager inefficient use of query

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1409]
I looked at the code for AzureTableDataManager.ReadSingleTableEntryAsync, and saw it uses a query to retrieve an entity by partition key and row key. The CloudTableClient object has a method Retrieve to return a single entity by a partition key and row key which is probably more reliable and efficient then a general query with a filter placed. It would also make the code more readable to use it.

**Comment by gabikliot** [comment]
That is a good idea.
There are more potential improvement we could do, listed here: https://github.com/dotnet/orleans/issues/169 

Community PRs will be welcomed.

**Comment by gabikliot** [comment]
Fixed via #1483.
