### ISSUE TITLE
GrainFactory uses generated factories via Reflection

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#141]
It is currently impossible to get rid of generated per-interface grain factories because GrainFactory class underneath leverages the generated factory classes via Reflection.

**Comment by ReubenBond** [comment]
Should the generated factories either have an attribute [GrainFactory(typeof(TGrainInterface)] or perhaps implement an IGrainFactory<T> interface? Perhaps the first - attributes make more sense as markers, I believe.

**Comment by sergeybykov** [comment]
If we want to get rid of the generated factories altogether, Do we even need to think of the proper way of marking the factories? I agree, that an attribute is probably a better option of the two, but I am hoping we don't need either.

**Comment by MovGP0** [comment]
I'd prefer an ```IGrainFactory<T>``` solution. They would get found via reflection and registered within an dependency container once at startup. 

However, to find the best working approach, it is usually best to try 2 or 3 variants with a conceptual prototype.

**Comment by sergeybykov** [comment]
The point I'm trying to make is that if you look at the code of the generated factory classes, they are actually very thin wrappers that call XYZGrainReference.Cast() and GrainFactoryBase.MakeGrainReferenceInternal(). If the GrainFactory class itself did that directly for any grain interface passed to it as a type argument, then we wouldn't need to generate XYZGrainFactory classes at all. That would make the question of how to mark them moot.

**Comment by MovGP0** [comment]
well, we would still need an interface for DI. So basically 

    public interface IGrainFactory
    {
        TGrainInterface GetGrain<TGrainInterface>(Guid primaryKey, string grainClassNamePrefix)
            where TGrainInterface : IGrainWithGuidKey;
        
        TGrainInterface GetGrain<TGrainInterface>(long primaryKey, string grainClassNamePrefix)
            where TGrainInterface : IGrainWithIntegerKey;
        
        TGrainInterface GetGrain<TGrainInterface>(string primaryKey, string grainClassPrefixName)
            where TGrainInterface : IGrainWithStringKey;
        
        Task<TGrainObserverInterface> CreateObjectReference<TGrainObserverInterface>(IGrainObserver obj)
            where TGrainObserverInterface : IGrainObserver;
        
        Task DeleteObjectReference<TGrainObserverInterface>(IGrainObserver obj) 
            where TGrainObserverInterface : IGrainObserver;
    }
    
    public class GrainFactory : IGrainFactory
    {
         // ..
    }
