### ISSUE TITLE
How does a silo retrieve a grain?

### ISSUE THREAD

**Issue by andredublin** [dotnet/orleans#142]
I know that orleans is a distributed system.
But I am curious to know what communication protocol does a silo use retrieve a grain? (e.g. Gossip, Raft, Paxos).
If it doesn't use a protocol then is it activating the grain on the silo itself then setting its state from data retrieved from table storage?

Thanks!

**Comment by sergeybykov** [comment]
Usually, grain state is externalized in storage. It gets loaded into grain's memory upon activation, either via the declarative persistence mechanism or by grain code.

**Comment by alan-geller** [comment]
@andredublin: do you mean how does Orleans find an existing instance of a grain, or how does Orleans fetch the state of a grain when it needs to create a new instance?
Sergey answered the second. The answer to the first is that Orleans uses a distributed directory with consistent hashing to store a table of active grains and their locations. When you first try to send a message to a grain, the silo you're running on (or the client) will look in the directory to see if there is an existing activation, and (in most cases) will direct the message to the existing activation if there is one.

**Comment by andredublin** [comment]
@alan-geller @sergeybykov Both answers are acceptable.  I am interested in the process on how the hashing tables work.  If you could point me in the right direction to where the hashing tables take place that would be great!

**Comment by gabikliot** [comment]
You can find much more details here: http://research.microsoft.com/pubs/210931/Orleans-MSR-TR-2014-41.pdf
and here:
https://github.com/dotnet/orleans/tree/master/src/OrleansRuntime/GrainDirectory
LocalGrainDirectory.cs, RemoteGrainDirectory.cs, ...

**Comment by andredublin** [comment]
@gabikliot thank you

**Comment by andredublin** [comment]
@gabikliot Great paper by the way, would it be ok if I posted it at http://paperswelove.org ?
