### ISSUE TITLE
KnownAssemblyAttribute does not generate serializers at runtime

### ISSUE THREAD

**Issue by ca-ta** [dotnet/orleans#1424]
It also prevents serializers from being generated in any assemblies containing the attribute.

The issue seems to stem with the way the code generator [processes the attribute](https://github.com/dotnet/orleans/blob/master/src/OrleansCodeGenerator/RoslynCodeGenerator.cs#L310).

I've tried a naive fix - replacing `IntersectWith` with `UnionWith` but things crashed left and right. 
Repro coming soon.

**Comment by ca-ta** [comment]
Repro in #1425

**Comment by ca-ta** [comment]
@ReubenBond - an feedback on this?

**Comment by ReubenBond** [comment]
I'll get on this asap, @ca-ta - apologies for the delay

**Comment by ca-ta** [comment]
Thanks @ReubenBond!

**Comment by jdom** [comment]
Could this be related to #1469 ?

**Comment by ReubenBond** [comment]
Fixed by #1504
