### ISSUE TITLE
Page build warning

### ISSUE THREAD

**Issue by jthelin** [dotnet/orleans#1431]
Merging PR #1430 to the `gh-pages` branch caused GitHub to send me e-mail with the following "Page build warning" below.

I confess I don't really know enough about `gh-pages` and Jekyll to make an informed decision about what the right fix is, so I will leave it to others to comment on that.

/cc: @richorama 

> The page build completed successfully, but returned the following warning:

> You are attempting to use the `pygments` highlighter, which is currently unsupported on GitHub Pages. Your site will use `rouge` for highlighting instead. To suppress this warning, change the 'highlighter' value to `rouge` in your `_config.yml`. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.

> GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies: https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

> For information on troubleshooting Jekyll see: https://help.github.com/articles/using-jekyll-with-pages/#troubleshooting

**Comment by richorama** [comment]
GitHub has recently changed gh-pages, it looks like syntax highlighting has changed with it.

`rouge` seems to be doing a good job (if that's what the live site is currently using) so I suggest we follow the advice and switch to it.

I'm happy to create a PR for this (give me a day).

**Comment by jthelin** [comment]
Cool. Thanks. You have the comm @richorama

**Comment by richorama** [comment]
..and the yak shave begins :¬)

> The page build completed successfully, but returned the following warning:

> You are currently using the 'redcarpet' Markdown engine, which will not be supported on GitHub Pages after May 1st. At that time, your site will use 'kramdown' for markdown rendering instead. To suppress this warning, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.

> GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies:

>   https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

> For information on troubleshooting Jekyll see:

>  https://help.github.com/articles/using-jekyll-with-pages#troubleshooting

> If you have any questions you can contact us by replying to this email.
