### ISSUE TITLE
Exposing low-level abstractions to users to support advanced unexpected scenarios

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1435]
I've been learning and trying out Orleans in the past two weeks. I want to say I consider Orleans a great framework, since it provides great high-level abstractions: Grains, Reminders, Timers, State persistence, Streams, etc. I want Orleans to become an excellent framework by exposing from it some of its low-level abstractions: Consistent ring providers, silo status listeners, etc. By taking this approach Orleans provides simple high-level abstract solution to 80% of scenarios, while enabling the other 20% scenarios be implemented powers by Orleans run-time. Exposing low-level abstractions will enable users to implement higher-level abstractions on top of them, like Reminders, Grains  & Streams are based on consistent ring providers, and some of those high-level abstractions could be merged back into the framework, extending it without changing its internals. Client technologies are well known for this: jQuery has plugins, angular.js has decorators, etc. For Orleans, I suggest to start with the following low-level abstractions that are already pretty clean and would be simple to expose them in a read-only fashion that allows users to learn of cluster state and respond to changes:
1. `ISiloStatusOracle` + `ISiloStatusListener`: Orleans run-time monitors state of cluster and each silo has its view on the status of other silos and ability to react to changes in a silo's status abstracted by those interfaces. By exposing it users can implement notifications about changes in cluster state, or avoid querying `IManagementGrain` for silos status making him a bottleneck in case some advanced custom logic requires checking for (approximate) silos statuses every few seconds. Orleans run-time has knowledge on cluster state, available on every silo in-memory without need to query storage - let's give users access to this information, let's allow them to be reactive about status changes using status listeners. Note: `ISiloStatusOracle` has control methods and not just querying methods. To expose the querying methods alone, interface segregation principle should be applied.
2. `IConsistentRingProvider`: Orleans run-time monitors state of cluster and holds valuable knowledge of how work items can be uniformly distributed between active silos based on consistent hashing implementation, and all of that is nicely encapsulated in `IConsistentRingProvider`. By exposing it users can use Orleans run-time to schedule work items for silos in a way that isn't support by the higher-level Reminders/Streams. That way users can, for example, support a work distribution pattern that isn't limited to 5+ minutes intervals provided by distributed reminders, using following technique: 
   - Introduce a table of all work items to distribute 
   - Introduce a grain(s) that acts as read-write cache of that table, call it work items grain. Every addition/deletion of work item is done using this grain, so it's in memory state will never be stale.
   - Each active silo has a stateless worker that subscribes to changes in current silo consistent ring range, and on every ring change the stateless worker queries the work items grain for work items that are assigned to current silo based on the silo's consistent ring range, and then activate other stateless workers that handle the work items. 
   - Since changes to consistent ring hash ranges are infrequent for most users, the work items grain doesn't become a bottleneck, and it's caching might not even be needed.

For both of those abstractions, it's better to let users subscribe async listeners and not sync ones like current abstractions provide, so subscriptions could execute async I/O.

If we agree to expose above low-level abstractions and give users access to Orleans run-time valuable data about the cluster, the question is how should those abstractions be exposed? I see the following alternatives:
1. Expose from `Silo` - above low-level abstractions are about the silo, so it's natural to put it here, and it's simplest since it has data members for above. This is also discoverable to users by simple Intellisense over `Silo` class that is the entry point to Orleans.
2. Expose by grains methods wrapping `IGrainRuntime` - grains are the unit of processing in Orleans, so it it's more natural to expose low-level abstractions to grains and not to code that is aware of `Silo`. Stateless workers are most natural to access low-level abstractions about current silo since they are local to that silo, but I can imagine scenarios where a grain would want knowledge about its hosting silo without knowing which silo it is in advance. The 'IGrainsRuntime' approach is also discoverable and enables unit testing grains, and grain methods wrapping `IGrainRuntime` members make user code more cohesive and makes the low-level abstractions much more discoverable.
3. Expand on option 2 by allowing the grain to listen to silo status changes and silo hash ring range changes using dedicated interfaces similar in spirit to `IRemindable`. Using this option would enable reminder like semantics, where the status changes are passed on to the grain via standard grain messages, keeping the grain active as well as making sure the grain is responding to one status change at a time.

What do you think about my ideas? How would you choose to expose those low-level abstractions? I'd like to hear feedback before starting to work on a pull request.

**Comment by gabikliot** [comment]
The first point was already suggested in https://github.com/dotnet/orleans/issues/1323.

**Comment by ReubenBond** [comment]
Closing this for now since I believe we support the majority of the cases which have come up. We can have separate issues for individual abstractions which users wish to access, since each one needs its own treatment.
