### ISSUE TITLE
Call context between client and server?

### ISSUE THREAD

**Issue by jesuspsalas** [dotnet/orleans#145]
I’m wondering if there is a ‘call context’ that can be use to transport some collateral data 
between Orleans client and Orleans server when I’m invoking a method on a grain.

(For instance to transport the client identity)

**Comment by jesuspsalas** [comment]
Looking around I found Orleans.Runtime.RequestContext :+1: so I'll answer my one question. Yes, there is a Call Context that propagates additional information between client and grains

**Comment by gabikliot** [comment]
https://github.com/dotnet/orleans/wiki/Request-Context

**Comment by sergeybykov** [comment]
@jesuspsalas You reopened because RequestContext is not sufficient for what you are trying to do?
