### ISSUE TITLE
MQTT Broker as Orleans Grain

### ISSUE THREAD

**Issue by SteveOmondi** [dotnet/orleans#1453]
High Guys, 
I was wondering if anyone could help me with guidelines to building MQTT broker as an Orleans client. I am trying to implement a setup where the broker can be spread up as Grains for clients to subscribe. 
Each grain will be identified by the ID of the group/Organization(Primary Key).

Thanks in advance

**Comment by amamh** [comment]
Hey,

I think your question needs to be a bit more specific if you want people to help. Just a thought :)

**Comment by Ernesto99** [comment]
Hey Steve, sure you need to be more specific please. Please elaborate the context :-)
