### ISSUE TITLE
Recoverable Event Hub Persistent Stream Provider - Part 2

### ISSUE THREAD

**Issue by jason-bragg** [dotnet/orleans#1454]
This is a follow up to Recoverable Event Hub Persistent Stream Provider #1096 
Below is a list of remaining work related to the EventHubStreamProvider.

- Flow Control (formerly called Backpressure) - EventHub partitions can produce 30-40k events per second per silo. This is far faster than the 2k events per second per silo processing target rate of the EventHubStreamProvider. There is currently no mechanism for slowing down the EventHub partition read rate. The EventHub adapter will need some way of detecting that events are being read from EventHub faster than they are being processed, and reduce the read rate. Similarly, if events are being processed in a timely manner, and there is a backlog of events in the partition, the read rate should be increased. Figuring out how to accurately and efficiently regulate the read rate is an interesting problem space for those interested in difficult problems.

- Provider Ready influences Silo Ready – The EventHub stream provider supports a large cache of messages for recoverability.  At silo startup, this cache must be filled before the stream provider is considered ready for service.  This information should somehow feed into silo status.  The silo should not be considered ready for service unless all of the EventHub message caches are caught up.

- Modular Message format. – For the EventHubStreamProvider to process a wide range of messages from EventHub, the cache data adapter must be a pluggable component that application developers can provide.

- Perfcounters + Monitoring – The EventHubStreamProvider needs logging and perf counters.

- Developer mode – Individual Application developers using the EventHubStreamProvider should not be required to setup and manage their own hubs for standalone development and testing.

**Comment by jason-bragg** [comment]
Tagging some folks that might be interested:
@gabikliot @yoniabrahamy @richorama @randa1 @angshuman-agarwal @amamh  @centur @amccool, @undecided2013 @andycwk
Sorry if I missed anyone..

**Comment by sergeybykov** [comment]
@jason-bragg Isn't this all done now?

**Comment by jason-bragg** [comment]
All except "Provider Ready influences Silo Ready".  This feature has been postponed indefinitely.
