### ISSUE TITLE
MVC/Web Api as orleans client is unresponsive to requests.

### ISSUE THREAD

**Issue by andredublin** [dotnet/orleans#146]
Following your tutorial, when running an MVC/Web Api as a Web Role.
Any requests set to the app are not processed and they are stuck waiting for a response from the server.

Using your AzureWebSample project I am able to have a MVC/Web Api as a Web Role work only if the ASP.NET Web Pages application is running too.  Once I remove the ASP.NET Web Pages application I am back to my requests not being processed.

**Comment by gabikliot** [comment]
You should only use await inside the MVC code, never use blocking .Result or .Wait.
It is a known issue with TPL and synchronization context that is unrelated to Orleans.

http://www.tugberkugurlu.com/archive/the-perfect-recipe-to-shoot-yourself-in-the-foot-ending-up-with-a-deadlock-using-the-c-sharp-5-0-asynchronous-language-features

http://stackoverflow.com/questions/13489065/best-practice-to-call-configureawait-for-all-server-side-code

**Comment by richorama** [comment]
My guess is that the Orleans client isn't getting initialized. Are you able to provide an example solution?

-----Original Message-----

**Comment by andredublin** [comment]
@richorama So Global.asax.cs has these few lines of code in it.
```cs
if (!AzureClient.IsInitialized)
{
    AzureClient.Initialize(Server.MapPath("~/ClientConfiguration.xml"));
}
```

It is at the AzureClient.Initialize() method where the hang up occurs.
I've used all the same configuration settings from the AzureWebSample.
Other than that I am not doing anything special.

**Comment by richorama** [comment]
And you're running it in an azure webrole (in the emulator I assume)?

-----Original Message-----

**Comment by andredublin** [comment]
@richorama Yes I am.

**Comment by gabikliot** [comment]
@andredublin Can you share both your client config file as well as client log that Orleans client writes? You can finds it in the project, in one of the inner folders that are created when deployed to a local emulator.

**Comment by sergeybykov** [comment]
We've seen people having similar connectivity issues when they deployed frontends and silos with configs out of sync, e.g. silos using Azure Table for membership and frontends with config pointing to localhost mistakenly taken from a sample. Is that's the case, it should be fairly obvious from the logs - what addresses silos and frontends use.

Even if that's not the case here, I think we still have a burning need for https://github.com/dotnet/orleans/issues/36, to hopefully eliminate this whole class of initial bootstrap issues.

**Comment by andredublin** [comment]
Here is my ClientConfiguration.xml config
```xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- 
	This is a sample client configuration file for use by an Azure web role acting as an Orleans client. 
	The comments illustrate common customizations.
	Elements and attributes with no comments should not usually need to be modified.
	For a detailed reference, see "Orleans Configuration Reference.html".
-->
<ClientConfiguration xmlns="urn:orleans">
  <!-- 
	To turn tracing off, set DefaultTraceLevel="Off" and have no overrides. To see a minimum of messages, set DefaultTraceLevel="Error".
    For the trace log file name, {0} is the silo name and {1} is the current time. 
	Setting WriteTraces to true will cause detailed performance information to be collected and logged about the individual steps in the
	message lifecycle. This may be useful debugging performance issues.
	-->
  <Tracing DefaultTraceLevel="Info" TraceToConsole="true" TraceToFile="{0}-{1}.log" WriteTraces="false">
    <!--
		To get more detailed application logging, you can change the TraceLevel attribute value to "Verbose" or "Verbose2".
		Depending on the log levels you have used in your code, this will cause additional messages to be written to the log.
		-->
    <TraceLevelOverride LogPrefix="Application" TraceLevel="Info" />
  </Tracing>
</ClientConfiguration>
```

I'll get you a client dump once I test a dev/test silo project instead.

**Comment by jesuspsalas** [comment]
@Andredublin I had the same problem (I'm not used to TPL that much), so what I did to make it work (I'm not sure if this the right thing to do, @gabikliot will know better) is to enclose  all async calls into a 

 Task.Run(() =>
            {
                  GrainType xx = GrainXXXXFactory.CreateObjectReference(this).Result;
            }).Wait();

and this fixed the issue, other people with more TPL experience can explain probably what is the best approach to this.

**Comment by gabikliot** [comment]
@andredublin Can you try the same:
Task.Run(() =>
 {
          AzureClient.Initialize(Server.MapPath("~/ClientConfiguration.xml"));
 }).Wait();

**Comment by andredublin** [comment]
@jesuspsalas Thanks but its not the fetching of a grain that is causing me problems, as I was able to query a silo via a Web API project as a web role in their AzureWebSample project.  It is when I either create my own project and set it up according to their tutorial the AzureClient.Initialize call hangs.

As for your code what you are doing is running a task on a background thread, but you are blocking with the .Wait() call to get the result from that background task.  That's one way to go about it, but I think the consensus for "best practices" is to use async/await keywords where possible.

@gabikliot I will try that out.

**Comment by andredublin** [comment]
So I've had some success with a deploy cloud service silo + web api when I carefully reread the documentation to make sure I had everything set up correctly using the AzureWebSample Project without having to run a background task and block for the result.  So most likely it was my cloud service role configurations were incorrect somehow.

test url for a few hours:
http://95838d53485745a983e0b3ad81eb9ca0.cloudapp.net/api/hello?name=Andre

@sergeybykov A template would be ideal for initial setup.
@gabikliot, @richorama, @jesuspsalas Thank you for your help.
