### ISSUE TITLE
Shouldn't ReadOnlyAttribute be public?

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1460]
I've looked at GrainsAttributes.cs and saw this internal attribute:

`[AttributeUsage(AttributeTargets.Method)]
internal sealed class ReadOnlyAttribute : Attribute
{
}`

As well as this public attribute:

`[AttributeUsage(AttributeTargets.Method)]
public sealed class AlwaysInterleaveAttribute : Attribute
{
}`

Shouldn't they both be public? To my understanding they are part of the same single writer/multiple readers latest edition to Orleans

**Comment by gabikliot** [comment]
No, they are unrelated to single writer/multiple readers latest edition to Orleans.
First, single writer/multiple readers is not currently part of Orleans runtime. It is an application pattern someone implemented on top.
Second, we don't currently support `ReadOnlyAttribute`. We used to in the past, but there were both impl. complications and also a bit confusion in the programming model about some delicate points w.r.t. execution and interlieaving. Not saying we will never support them, but as of now, there is nothing in the runtime that implements that. The attribute has no backend implementation. Instead, there is all or nothing `Reentrant` attribute.

`AlwaysInterleave` is implemented, but we think it will be too confusing to expose it. Instead, again, there is all or nothing `Reentrant` attribute. See here for more details: https://github.com/dotnet/orleans/issues/447#issuecomment-118926817

**Comment by Eldar1205** [comment]
Thank you!
