### ISSUE TITLE
Usage of pragmatic general multicast for messaging

### ISSUE THREAD

**Issue by Carlm-MS** [dotnet/orleans#1466]
1) Should an option for simultaneous delivery using PGM be included in stream providers where all consumers receive messages at once?
2) Should PGM be an considered for grain and system target calls?
3) Could/should PGM with LVC (last value caching) be utilized for the silo membership table?

For reference, a C# library that provides this type of functionality: http://zguide.zeromq.org/php:chapter5.

**Comment by gabikliot** [comment]
What is PGM? Is it IP Multicast? Does Azure even support IP multicast? IP multicast is usually only supported on LAN and not on WAN. But I don't know what is PGM and who supports that. How PGM and caching are related to silo membership table?

-----------------

After reading zero MQ section I concluded the following:

1) PGM is just a regular IP multicast (please correct me if I am wrong). I actually have a lot of experience with IP multicast, worked in the past on Group Communication systems that utilize IP multicast. Before going into details of pros and cons, we should answer the basic question of whether Azure (and other providers) supports IP multicast. 
Azure: looks like NO: https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-faq/, which is not surprising, given all the disadvantages of IP multicast
AWS: might be possible, but sure not easy and not out of the box it looks: https://www.buckhill.co.uk/blog/how-to-enable-broadcast-and-multicast-on-amazon-aws-ec2/2#.VsQfAvIrLIU
GCP: No https://cloud.google.com/compute/docs/networking

2) silo membership protocol already does what they call last value caching. The table holds the last value and the newly added members catch up to it by a single read. So we have that, built in natively into the protocol.

**Comment by sergeybykov** [comment]
@gabikliot https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-faq/ is about VNets. It's unclear to me if the same applies to networks between role instance. Maybe, maybe not.

**Comment by Carlm-MS** [comment]
@gabikliot 
PGM is reliable multicast - multicast with loss detection/retransmits similar to TCP.  You're right, PGM doesn't work in azure.  I just tried a simple client/server app and it looks like a no go.

It looks like others have run into problems installing services that utilize multicast in any form (ElasticSearch, ZeroMQ, etc) https://feedback.azure.com/forums/217313-networking/suggestions/3741233-support-multicast-within-virtual-networks

This issue was open in 2013 and still 'under review', so it seems unlikely that it will ever be supported.

**Comment by sergeybykov** [comment]
@Carlm-MS Should we close this for now?

**Comment by Carlm-MS** [comment]
Sadly, yes :)

**Comment by gabikliot** [comment]
I doubt it will ever be implemented due to inherit scalability problem with basically any multicast routing protocol. The spanning tree of switches it has to build is simply too costly to build (its a Steiner spanning tree, NP hard) and to maintain. 

Instead, what we can (and should) do is implement multicast on Orleans level. If sending one streaming msg too 10 consumes all on the same silo, we should send one msg, and  not 10 like now. In a setup with lots of consumers you will get much more gain for your bucks this way. It won't be trivial to implement, but should be doable.
