### ISSUE TITLE
Suggestion/Question: Could a grain be partially Reentrant?

### ISSUE THREAD

**Issue by amamh** [dotnet/orleans#1468]
I have a grain that will be used heavily for querying (reading) and only a few times for writing. It would make a lot of sense if I could mark the methods that respond to querying as Reentrant. That is, the read only methods should be called by the runtime in ~~parallel~~ EDIT: will get a performance boost by allowing interleaving.

A simple example:

    Task Add(string key);

    Task Remove(string key);

    [Reentrant]
    Task<List<string>> GetAll();

    [Reentrant]
    Task<List<string>> Query(query params);

That way, when Add/Remove are called, the runtime will behave how it normally does. It will queue the operations and do them sequentially ~~not in parallel~~ EDIT: without interleaving. When GetAll/Query or any readonly method is called, the runtime will behave as if the whole grain is marked `Reentrant` EDIT: and allow interleaving to get a performance boost.

Obviously, it's easy for me to suggest something like, but I don't know how hard it is to implement that.

- Is that a good idea?
- Is it possible to add?
- Is there a way to do this currently?

---------
EDIT: I thought Reenterant means allowing parallel execution instead of interleaving execution, so I edited the question to correct that.

**Comment by angshuman-agarwal** [comment]
I guess _stateless_ workers will do fine in case of Editor views. Stateless worker mode is appropriate for grains that hold no local state, or grains whose local state is static, such as a grain that acts as a cache of persistent state. And in case of editors, its 99% that's the case.

**Comment by amamh** [comment]
There are Add/Remove methods in the grain, so it has a non-static local state.

**Comment by sergeybykov** [comment]
We used to have `[ReadOnly]` for that - to allow interleaving of methods marked with it with other `[ReadOnly]` methods, but then with one of the necessary refactoring of the scheduler we lost the ability to easily enforce the semantics, and we made the attribute internal. @gabikliot may remember better.

**Comment by amamh** [comment]
@sergeybykov 
Thanks for the reply!

I suspected you must have thought of this feature already. Is there a chance it's going to be added back in a future release?

**Comment by sergeybykov** [comment]
My recollection is that there were some challenges with figuring out whether outstanding Tasks of a grain activation belong to `[ReadOnly]` requests or regular ones. This is where I suspect @gabikliot has a more accurate recollection.

**Comment by angshuman-agarwal** [comment]
@amamh

You can use 2 grains i.e. for reading (normal grain) and writing grain (stateless worker). The read grain will delegate to the write grain which will do an async write (add/remove). Advantage will be that the write  grain will always be created in the local silo which removes the need for network hop to write to db. And if there are two concurrent writes, that will also get handled and subsequently the views will get the latest data always via the read grain stream.

Does this makes sense?

**Comment by gabikliot** [comment]
@sergeybykov is totally correct. There were complications in implementing it correctly. Its not trivial. Plus, there are some not trivial design choices, like can readers starve a writer or should writers get priority, etc...

For reference:
https://github.com/dotnet/orleans/issues/1460
https://github.com/dotnet/orleans/issues/447#issuecomment-118926817

There are 2 ways we can proceed:
1) Someone volunteers to implement it in the runtime. It is sure not trivial, but doable. If someone is seriously interested to put in some good time investment and to get back very deep and intimate knowledge and understanding of how messaging dispatch mechanism works in Orleans (basically, one  of the most critical parts of the runtime), I can guide him through.
2) Implement that in the application level, via helper/wrapper object, like `AsyncSerialExecutor`: https://github.com/dotnet/orleans/blob/master/src/Orleans/Async/AsyncSerialExecutor.cs
I think this is actually the better way to go. It is VERY easy to use this pattern or extend it with more custom interleaving execution semantics, you are in full control of how to do what. It is very easy to build those things with lambdas and async await.

**Comment by amamh** [comment]
@angshuman-agarwal 
I think we are talking about two different things. There are no editor views. The grain has a local state, so I can't use a Stateless grain.

@gabikliot 
I don't think I'm at a level where I can contribute now. I had some trouble before understanding how the PullingAgent class works for persistent streams. So, I'll go with option 2 :)

So, my understanding now is that:
I can mark a grain as Reentrant and using `AsyncSerialExecutor` I can force **parts of the grain code** to be non-interleaving i.e. as if the grain is not Reentrant.

I think one downside is that I don't see how I can return anything from a Task this way. The "AddNext" method returns a Task without a result e.g. Task\<int\>.

------

I also should point out that there was some misunderstanding on my part. I thought Reentrant means parallel execution is permitted, now I understand that it only means interleaving is permitted.

**Comment by gabikliot** [comment]
>I can mark a grain as Reentrant and using AsyncSerialExecutor I can force parts of the grain code to be non-interleaving i.e. as if the grain is not Reentrant.

Yes.

For other parts, the read parts, it depends: if you want to allow them to interleave with write parts, then `AsyncSerialExecutor`  will work as is for you and you don't need to change it. But if you want them to wait until all writes are done, then you will need too extend `AsyncSerialExecutor`  to support NonInterleaved and Interleaved, probably with 2 queues inside. Not hard to do, but will require a change in the AsyncSerialExecutor .

**Comment by centur** [comment]
I think  @angshuman-agarwal solution is valid - 
We had similar issue to what you described with our View grains - heavy write blocks all grain readers.
Solved it by moving out computational heavy logic to another grain similar to  what he suggested.

Effectively we have a very fast grain which just returns it current state and cached values, which is your stateful grain with queries, and add\remove methods which receives full pre-computed object  that needs to be added to state. This precomputed object is prepared by other stateless grain and pushed to the main View
So Add\Remove is very fast and won't block readers for a long period

**Comment by gabikliot** [comment]
Yep, @centur 's solution sounds good as well.

**Comment by amamh** [comment]
@centur 

I understand what you are saying, in your situation moving the computation part into a stateless grain makes sense.

The problem is that I thought "Reentrant" means allowing parallel execution so I thought by marking the readonly methods as "Reentrant" (i.e. "parallel" in my mind) I would **relieve the bottleneck by allowing multiple threads** on the grain instead of a single thread. However, the writing operations should still remain single threaded because they manipulate the state.

Since my understanding was incorrect anyway, I edited my question to make this issue thread about **allowing interleaving of some methods while disallowing others**. That is the correct effect of "Reentrant" and not parallel execution as I previously thought. In that corrected context, what @gabikliot  said about using `AsyncSerialExecutor` is the right answer until Orleans brings back the `Readonly` attribute.

**Comment by gabikliot** [comment]
Can we close that @amamh ?
