### ISSUE TITLE
Missing RemoteDeployment folder in v1.0 setup installer

### ISSUE THREAD

**Issue by jakupj** [dotnet/orleans#148]
Release 0.9 had a RemoteDeployment folder with powershell scripts. v1.0 is missing this folder and related scripts

**Comment by sergeybykov** [comment]
The scripts aren't very Orleans specific. We weren't sure how much value they added and how many people actually used them for private cluster deployments. So we took the "less is more" approach and didn't include them. The ones from 0.9 can still be used, and we haven't touched them  for quite some time. Did anybody here use the scripts?

**Comment by sergeybykov** [comment]
We can put them back into src\scripts\RemoteDeployment. Or maybe .\misc\scripts\RemoteDeployment?

**Comment by veikkoeeva** [comment]
``.\misc\scripts\RemoteDeployment`` feels better.

**Comment by sergeybykov** [comment]
I submitted a PR for this - https://github.com/dotnet/orleans/pull/156.

**Comment by gabikliot** [comment]
Closed via #156.
