### ISSUE TITLE
Azure persistence provider WriteRead_Json test is failing

### ISSUE THREAD

**Issue by dVakulen** [dotnet/orleans#1484]
At https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs#L277 while iterating through collection of custom converters this [check ](https://github.com/dotnet/orleans/blob/master/src/Orleans/Serialization/OrleansJsonSerializer.cs#L267)returns true when parameter ```objectType``` is ```System.Object```, thus making the Guid converter to be chosen for deserialization of completely different object.

**Comment by dVakulen** [comment]
For the context: #1187.

**Comment by gabikliot** [comment]
For more context: https://github.com/dotnet/orleans/issues/1269, @Allon-Guralnek explained it well.

**Comment by gabikliot** [comment]
Fixed via #1485.
