### ISSUE TITLE
Question: How to Resolve an hotspot

### ISSUE THREAD

**Issue by doron0220** [dotnet/orleans#1486]
Hello everyone,
We have in our system a grain which is called a lot of times and we suspect it'll become an hotspot.
In order to Resolve it we thought about duplicating this grain and get it by (its key+instance number). That way (and if we'll sync correctly state between all duplicated grains ) we can balance the load to a fixed number of grains having the same state.

The problem here is that my duplication of this grain is of fixed size and not dynamically by load, and my question is does anyone know how to duplicate grains dynamically by load?
Or does anyone know a better way to do it? 

The best way i can think of is in a stateless grain measure performance of my duplicated grains and if i  encounter a performance hit add more grains.

**Comment by sxam** [comment]
To add to the question - what about Revoking? I mean, if we have some statefull grain that is responsible for modifying the data and a "cache layer" of grains  that hold it for Get requests - how do I synchronize? The immediate solution is just expire the "cache" grains after some TTL, but that will bring us to an unhealthy situation where someone made Set and after that Get will bring them an older version.
So we have to have Revoking. For Revoking we had the following idea - "Cache layer" will be statefull Grains and on activation they will write themselves up in some DB. Whenever the main grains will receive a Set , he will get to DB and send a Revoke request to all the "cache layer" grains. (BTW, we will need "cache" grains to be Reentrant for that solution to avoid Deadlocks)..

So if anybody have some advice about revoking cache layers made of Grains, it will also be  most welcomed, in addition to previous question about dynamic activation of Cache grains depending on the load.

**Comment by sergeybykov** [comment]
This looks similar to what is being discussed in https://github.com/dotnet/orleans/issues/1490.

That being said, if you can prevent hotspots by a better partitioning of the data, that's always better. Not sure if it's possible in your case - not enough information.
