### ISSUE TITLE
C# Template doesn't run when activating AzureTable Storage

### ISSUE THREAD

**Issue by Gentlehag** [dotnet/orleans#1487]
I've created a solution with the three default projects.

I can run this solutions and every thing works as expected.

Now the DevTestServerConfiguraiton says that I can activate tablestorage with uncommenting one of the given lines.
  ```
      <Provider Type="Orleans.Storage.MemoryStorage" Name="MemoryStore" />
      <!-- To use Azure storage, uncomment one of the following lines: -->
      <Provider Type="Orleans.Storage.AzureTableStorage" Name="AzureStore" DataConnectionString="UseDevelopmentStorage=true" />
      <!--<Provider Type="Orleans.Storage.AzureTableStorage" Name="AzureStore" DataConnectionString="DefaultEndpointsProtocol=https;AccountName=MYACCOUNTNAME;AccountKey=MYACCOUNTKEY" />-->
```
But as Soon as I uncomment one i got an exception tellming  me that the type can't be resolved.
![image](https://cloud.githubusercontent.com/assets/4619513/13204799/0c05dab6-d8d9-11e5-923b-ac178c5c9d23.png)
What do I have to do further ? And I think it would be nice to have a comment for this in the config.

**Comment by gabikliot** [comment]
As the error msg says, please check that Orleans azure utils assembly is copied into bin folder. There is nuget for it.

**Comment by sergeybykov** [comment]
@Gentlehag Were you able to resolve this by making sure OrleansAzureUtils.dll is included in the cspkg?
