### ISSUE TITLE
Proper support for JSON serializer

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#1495]
This is to resurface the conclusion of the discussion in https://github.com/dotnet/orleans/pull/1485 and https://github.com/dotnet/orleans/issues/1484.

I see five areas where JSON serialization potentially applies.

A. Grain state objects.
B. Orleans public types that app code is expected to persist, such as  `GrainReference`  and its generated subclasses, implementations of  `IAsyncStream<T>` , etc.
C. Arguments and return values of app grain interfaces' methods.
D. Various runtime types that get sent over the wire.
E. Various runtime types that get persisted, e.g. membership and reminders data.

A is a no-brainer - app code needs to be able to define how app state gets serialized, with JSON or not, including all possible JSON serialization settings.
B is also obvious - app code needs to serialize those handful of types in various scenarios.

The case for C is that we cannot guarantee that there will be an Orleans generated serializer for sending all app types over the wire. Today we fall back to .NET binary serializer, and not all types are binary serializable. Plus .NET binary serializer that is going away in CoreCLR. 

D & E don't seem to have any clear benefits from using JSON instead of Orleans binary serializers. Considering the pitfalls of how JSON deals with common data structures and no obvious way to test all runtime types for correct JSON serialization, I see no reason to use JSON here. Today we only optionally use it for pub-sub grain state to make the data human readable for debugging, but because it is implemented as grain state, it falls under A.

So maybe the plan should be to: 
- [ ] 1) explicitly separate in the runtime code C from D, and make sure only Orleans binary serializer is always used for D. If we want to use JSON for some special cases in E, that should done with a separate instance of JSON serializer where app code cannot change settings configured by the runtime code;
- [ ] 2) Fill any gaps in B and cover each of the types with unit tests that would catch any future regressions.
- [ ] 3) Expose publicly settings of the JSON serializer used for A & C that app will have full control of. Via DI?
- [ ] 4) Because JSON serializer is particularly bad at preserving object types in loosely typed data structured, such as `Dictionary<string, object>` and `List<object>`, we cannot JSON-serialize such data structures, and instead have to serialize individual objects. An example of that in the persistence code where we put data into a dictionary, and then serialize the dictionary. 
- [ ] 5) Avoid wrapping application types that have to Json-serialize into any other type or put them into any dictionaries/lists. We need to pass application types (A and C) to Json serializer as is.

**Comment by RehanSaeed** [comment]
I believe that BinarySerializer is not going away in .NET Core. 

Also, given the major new work to add a fast JSON serializer in .NET Core are there any plans to move away from JSON.NET to the new aforementioned serializer? If so, would that be the recommended approach for Grain Storage?

**Comment by ReubenBond** [comment]
> I believe that BinarySerializer is not going away in .NET Core.

Yes, that's correct. At the time of writing the original issue, BinarySerializer was not going to be included in .NET Core/Standard.

> Are there any plans to move away from JSON.NET to the new aforementioned serializer?

We do not have plans to move from JSON.NET, but the intention is to make serialization more pluggable in future. Your input on what you'd like to see is appreciated.

Note that BinaryFormatter is not the main serializer used in Orleans, it's only a fallback - used as a last resort for when other serializers do not support a given type. For example, Exceptions may be serialized using BinaryFormatter.

**Comment by RehanSaeed** [comment]
Thanks for the update. In particular, I'm talking about the `UseJson` setting here:

```
    .AddAzureTableGrainStorageAsDefault(
        options =>
        {
            options.ConnectionString = "UseDevelopmentStorage=true";
            options.UseJson = true;
        })
```

I'm thinking this uses JSON.NET and could then be easily switched for the new .NET Core JSON serializer when it turns up for extra performance.

**Comment by ReubenBond** [comment]
@RehanSaeed the new JSON Serializer will not be completely compatible with JSON.NET, so I would be very wary of automatically switching users over to it. For example, if the user specifies some JSON.NET-specific attributes which the new serializer does not understand then behavior would differ.

I'd rather see a fairly generic serializer interface which users can customize on a per-provider basis using (for example) named DI registrations. So if you want to customize the the serializer for a given storage serializer then you register your serializer using the same name. Does that sound tenable?

**Comment by RehanSaeed** [comment]
Yes, the generic approach is the way to go.

**Comment by ReubenBond** [comment]
We support serializer pluggability in most or all cases now, and JSON is the default for grain storage, so I consider this complete.
