### ISSUE TITLE
ReflectionTypeLoadException in SiloAssemblyLoader

### ISSUE THREAD

**Issue by DixonD-git** [dotnet/orleans#1517]
First of all, I'm not really sure it is Orleans issue, I rather seeking a hint for a workaround here.

I get this exception on test/dev silo host start:
```
Exc level 0: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Orleans.Runtime.TypeUtils.GetTypes(Assembly assembly, Func`2 whereFunc) in D:\Projects\orleans\src\Orleans\CodeGeneration\TypeUtils.cs:line 452
   at Orleans.Runtime.TypeUtils.GetTypes(Func`2 whereFunc) in D:\Projects\orleans\src\Orleans\CodeGeneration\TypeUtils.cs:line 462
   at Orleans.Runtime.SiloAssemblyLoader.GetGrainClassTypes(Boolean strict) in D:\Projects\orleans\src\OrleansRuntime\GrainTypeManager\SiloAssemblyLoader.cs:line 62
   at Orleans.Runtime.GrainTypeManager.InitializeGrainClassData(SiloAssemblyLoader loader, Boolean strict) in D:\Projects\orleans\src\OrleansRuntime\GrainTypeManager\GrainTypeManager.cs:line 132
   at Orleans.Runtime.GrainTypeManager.Start(Boolean strict) in D:\Projects\orleans\src\OrleansRuntime\GrainTypeManager\GrainTypeManager.cs:line 57
   at Orleans.Runtime.Silo.DoStart() in D:\Projects\orleans\src\OrleansRuntime\Silo\Silo.cs:line 416
   at Orleans.Runtime.Silo.Start() in D:\Projects\orleans\src\OrleansRuntime\Silo\Silo.cs:line 393
   at Orleans.Runtime.Host.SiloHost.StartOrleansSilo() in D:\Projects\orleans\src\OrleansRuntime\Silo\SiloHost.cs:line 170
Exc level 1: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

I've debugged it with Orleans source, apparently it fails when loading assembly `"Microsoft.CodeAnalysis.Scripting, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"`. I'm running the project on .NET 4.6.1. I don't really understand what is `System.Runtime.Loader`, and why it is required by `Microsoft.CodeAnalysis.Scripting`, but the same code runs fine outside of Orleans.

Any idea what I can do with it?

**Comment by DixonD-git** [comment]
Reported the issue for the Roslyn team: https://github.com/dotnet/roslyn/issues/9417 as well. As for `SiloAssemblyLoader.GetGrainClassTypes`, I would like to able to exclude some assemblies from scanning explicitly, if I know that they do not contain grains.

**Comment by veikkoeeva** [comment]
@DixonD-git Looking at [SiloAssemblyLoader](https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/GrainTypeManager/SiloAssemblyLoader.cs#L26), not possible currently. There is a plan to move into a fully configurable loader, in conjunction with improved DI. One idea is that one could just give a list of types to be loaded, using whatever criteria needed. I don't remember if there's explicitly a recorded issue for this. I don't know whose time should I take and summon here to give an exact pointer on it, but if you look at [Orleans Meetups](https://github.com/OrleansContrib/meetups), one of them had this specifically discussed. Namely stealing/studying the system from Orleankka. :)

**Comment by DixonD-git** [comment]
@veikkoeeva Thanks, that idea should be definitely logged as an issue. As for the problem I have, could it be appropriate to allow the silo to run on the error while discovering grains from assemblies? We could simple log the error and continue discovery from other assemblies.

**Comment by ReubenBond** [comment]
Should assembly loading be all-or-nothing (fail if we cannot load all assemblies) or should it be best efforts (log and continue on exception).

The problem is sometimes DLLs are bad. For example, some Service Fabric dlls reference DLLs which are not publicly available. If there is a type initializer which fails (eg, by attempting to load a DLL which does not exist), then the silo will fail to start. That type might not be important, though.

In my opinion, we should adopt a best-efforts approach and shore up the safety of assembly loading/scanning.

**Comment by sergeybykov** [comment]
I'm not sure I understand. I thought we skip an assembly that fails to load for whatever reason and move on to the next one. What am I missing here?

**Comment by DixonD-git** [comment]
@sergeybykov I've tried to create a new Dev/Test silo host project and just to add the `Microsoft.CodeAnalysis.Scripting` package - in that case the assembly was indeed just ignored during the silo start. However, the test silo fails to start with the error I posted in the first comment in another solution. I cannot share the full solution unfortunately, but when I have a chance, I will try more for creating some project where this issue would reproducible.

**Comment by DixonD-git** [comment]
@sergeybykov I've managed to create a small Dev/Test host with minimum required to reproduce the issue. Once you have a chance, please, check `src/FailingSiloHost` project at https://github.com/DixonD-git/orleans/tree/failing-silo-host/

**Comment by sergeybykov** [comment]
@DixonD-git As I understand, the trick to repro the issue is this: `var t = typeof(CSharpScript);`, correct?

**Comment by DixonD-git** [comment]
@sergeybykov Yes, it just makes the respective assembly to be loaded into the application domain. This issue should be fixed by https://github.com/dotnet/orleans/pull/1534 , so I'm closing it now.

**Comment by sergeybykov** [comment]
:+1:
