### ISSUE TITLE
Adding Custom Header in the payload

### ISSUE THREAD

**Issue by raunakm** [dotnet/orleans#1528]
I have a requirement where I need to add a Custom Header at the Client and then read it on the server.
I looked through ** Orleans.Runtime.Message** class  and only properties I see that are getting serialized are headers and bodyObject.
Now headers is of type Dictionary<Header, object> where Header is enum type.
Is there any other way I can add a custom header which has to be key,value pair ?

**Comment by gabikliot** [comment]
Use RequestContext instead.

**Comment by gabikliot** [comment]
http://dotnet.github.io/orleans/Advanced-Concepts/Request-Context
