### ISSUE TITLE
Question: Returning grain state from grain's methods

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1531]
I have a grain contract `ICheckpointGrain` and I want it to have get/set methods for `Checkpoint` object that inherits `GrainState` and used as persistent state for `CheckpointGrain` implementing `ICheckpointGrain`. Should I separate between the object exposed in the grain's contract and the persistent state object, or there's no design/technical issue with exposing persistent state from grains?

**Comment by sergeybykov** [comment]
`GrainState` is going away. Any POCO class can represent grain's state now (as `T` in `Grain<T>`). There is nothing preventing exposing the same type as an argument/return value type for grain methods.
