### ISSUE TITLE
Question: calling DelayDeactivation() multiple times

### ISSUE THREAD

**Issue by shay1e** [dotnet/orleans#1541]
Hi,

We have a type of grain that call `DelayDeactivation()` immediately on `OnActivateAsync()`. Later on, each grain calculates a new value for delayed deactivation, less than the initial value (in terms of absolute time, not TimeSpan). 

The question is:
Consider this code:

            DelayDeactivation(TimeSpan.FromMinutes(60));
            DelayDeactivation(TimeSpan.FromMinutes(1));

Will the second command override the first one? If not, would this do the trick?

            DelayDeactivation(TimeSpan.FromMinutes(60));
            DelayDeactivation(TimeSpan.FromMinutes(-1));
            DelayDeactivation(TimeSpan.FromMinutes(1));

And if also not, is it possible to achieve such a behavior? It is important  since each of those grains can hold large objects in memory, and we wouldn't want them to be activated longer than they should.

Thanks :)

**Comment by sergeybykov** [comment]
Take a look at https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Catalog/ActivationData.cs#L624. I believe it behaves exactly like you want, and both versions of the code above should achieve the same result.

**Comment by shay1e** [comment]
Perfect!

Thanks a lot Sergey :)

**Comment by sergeybykov** [comment]
No problem.
