### ISSUE TITLE
Question: detecting if a grain message was received from another silo

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1542]
I'd like to have a grain with `[PreferLocal]` placement, and that grain will most of the time be activated by a reminder. Is it possible for the grain to detect if it was invoked from a reminder on a different silo, or more generally if the grain message is coming from another silo? This may happen since reminders are periodically re-balanced between silos which means after a grain was invoked on same silo as the reminder, later the reminder may move to another silo while the grain remains active on original silo.

**Comment by sergeybykov** [comment]
You can probably guess with pretty high accuracy if you have the grain record its activation time in `OnActivateAsync()`, and then compare it with current time at the beginning of the reminder callback. Unless the grain gets invoked with a normal method call and a reminder message within a very narrow time window. But then do you need to be 100% accurate?

**Comment by Eldar1205** [comment]
I don't need to be 100% accurate, but it's possible that the grain is
activated on one silo, and then another silo joins and takes ownership of
the reminder associated with the already active grain, and then no way to
tell if the message sent was from another silo or not. I'm considering a PR
with addition to reminder service of a new method `IsReminderLocal` to ask
whether a certain reminder is local to current silo, but I think a better
solution (which I'm not sure how to do) is to put this info on the
RequestContext. I saw the internal 'Message' object has info about sender,
and this data can be useful for app code as well.

2016-03-10 1:56 GMT+02:00 Sergey Bykov <notifications@github.com>:

**Comment by sergeybykov** [comment]
What bothers me is that one of the key points of the Orleans programming model is that the app code doesn't need to be concerned with knowing where it runs and where the messages are coming from. While many things are doable to expose the low level information to the app code, I'm concerned that following down this path may end up with a death of the simple programming model by a thousand cuts.

In general, we recommend benchmarking an app before going after optimizations. In this case it's not clear to me why a reminder message coming from another silo would be a performance concern, especially it only a small percentage of grains would be exposed to that.
