### ISSUE TITLE
Serializer issue for GrainInterfaceMap

### ISSUE THREAD

**Issue by ozang** [dotnet/orleans#1543]
Hi, 

I am trying to connect to an orleans silo but I got this error:

> {"Unsupported type 'Orleans.Runtime.GrainInterfaceMap' encountered. Perhaps you need to mark it [Serializable] or define a custom serializer for it?"}
> 
> 
>    at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, BinaryTokenStreamReader stream)
>    at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, BinaryTokenStreamReader stream)
>    at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, BinaryTokenStreamReader stream)
>    at Orleans.Serialization.SerializationManager.Deserialize(Type t, BinaryTokenStreamReader stream)
>    at Orleans.Serialization.SerializationManager.Deserialize(BinaryTokenStreamReader stream)
>    at Orleans.Runtime.Message.DeserializeBody(List`1 bytes)
>    at Orleans.Runtime.Message.get_BodyObject()
>    at Orleans.Runtime.GrainReference.ResponseCallback(Message message, TaskCompletionSource`1 context)

When I searched in object browser, I can see a class, possibly created to serialize this class : Orleans.Runtime.Configuration.OrleansCodeGenOrleans_Runtime_GrainInterfaceMapSerializer.OrleansCodeGenOrleans_Runtime_GrainInterfaceMapSerializer()

But somehow i got this error. I think there is configuration problem.. Do you have any idea about how I can solve this problem?

**Comment by ozang** [comment]
While searching for a solution, I found this link: 
 http://pastebin.com/nt9grH5H
It contains a autogenerated file, containing GrainInterfaceMapSerializer and also lots of serializers autogenerated by the framework but in my setup it is not generated.  Do you have any idea how to trigger this code gereneration process?

**Comment by sergeybykov** [comment]
Looks exactly like https://github.com/dotnet/orleans/issues/1522.

**Comment by gabikliot** [comment]
Another example of why it would be helpfull to add version check between client and silo,  as part of first connection handshake.

**Comment by ozang** [comment]
Thank you... I worked...
