### ISSUE TITLE
Runtime grain code generation

### ISSUE THREAD

**Issue by stgolem** [dotnet/orleans#1551]
Is there any reason why you should generate code on compile time? Isn't it much easy to do on Silo Host startup to generate all this Proxy classes?
With this we also can have an ability to codegen grain classes in runtime before Silo starts (for whatever reason we want that).

**Comment by sergeybykov** [comment]
Main reasons for compile time codegen are early error detection and better determinism about the generated code that can be saved for debugging or compliance.

You are free not to use compile time codgen, and run time codegen should happen automatically. I'm less sure about codegen'ing of grain classes that you mentioned. Today that would have to happen before a silo starts.

**Comment by stgolem** [comment]
Oh! That is a great news. We are currently use Nemerle as part of our domain model language. So all grains classes are created also at compile time. But no godegen happens on Silo start.
Is there any config or whatever else for this to happen?

**Comment by sergeybykov** [comment]
You shouldn't need anything.
