### ISSUE TITLE
Non-timeout Messaging Delivery Errors

### ISSUE THREAD

**Issue by Astorlights** [dotnet/orleans#1552]
Hello, I'd like to ask whether the deliverance status is unknown or known-not-delivered in a situation when some network-based exception (other than Timeout) error is thrown when calling await OtherGrain.MyFunction();

Thank you !
Abe

**Comment by gabikliot** [comment]
Are you asking what types of exceptions could be thrown from a grain call?

**Comment by gabikliot** [comment]
A grain call will succedd, or throw some exception, or if both didn't happen, timeout exception will be thrown. So the task returned from a grain call will never stay unresolved forever. It is guaranteed it will timeout after a configurable time.

**Comment by Astorlights** [comment]
So when an exception is thrown (immediately or some time before the timeout), is it guaranteed that the Tagret grain method was not invoked ?

**Comment by gabikliot** [comment]
No, that is not guaranteed. The target grain could have been invoked, but the reply didn't arrive.

**Comment by Astorlights** [comment]
When reply does not arrive, wouldn't that invoke the TimeoutException  ?

**Comment by Astorlights** [comment]
... after the timeout period ?

**Comment by Astorlights** [comment]
Simply put, I'm asking about the situation when the exception is thrown out of target grain method call, and it is _not_ TimeoutException, but it's some network-related exception like "Target network unreachable" or something like that, thrown by whatever layer below. In this situation, is it still possible that the target grain method was invoked and is "running", even though the caller got this such exception. Thanks again.

**Comment by gabikliot** [comment]
Yes, the situation you described is totally possible.
