### ISSUE TITLE
Questions on Azure Maintenance and on grains stuck on deactivating

### ISSUE THREAD

**Issue by SGI-Swong** [dotnet/orleans#1553]
Hello,

We are currently using Orleans 1.1.1.2 and are deployed as an Azure cloud service and we had a couple questions.

First, for Azure Maintenance Updates, are there any best practices for Orleans to ensure minimal impact to the users?  If we use update domains to spread out all the role instances, would grains that were on an instance that is being updated get relocated to a new instance, the next time the user logs in?  Is there anything in Orleans we can do to help with users disconnecting when an instance goes down for maintenance?

Second, we are seeing grains that stop responding and seem to be stuck in the deactivating state. Not sure if it is related to this issue : https://github.com/dotnet/orleans/issues/1383 where the grain is stuck forever awaiting a task that never completes.

Using OrleansManager tool to get a grain report on the stuck grains gives the following information.  NOTE: The reports below were taken on Mar 1.

**DetailedGrainReport for grain *grn/2B6C2053/00000000000000000000000000000000060000002b6c2053+XXXX-0x6EA11B69 from silo Squire.SiloWorkerRole_IN_3 SiloAddress=S10.10.0.57:11111:193958758**
   LocalCacheActivationAddresses=[]
   LocalDirectoryActivationAddresses=S10.10.0.36:11111:193958776
   PrimaryForGrain=*****
   GrainClassTypeName=[      [Activation: S10.10.0.57:11111:193958758_grn/2B6C2053/00000000000000000000000000000000060000002b6c2053+XXXX@c509cab7 #GrainType=_***\* Placement=RandomPlacement State=Deactivating NonReentrancyQueueSize=307 EnqueuedOnDispatcher=0 InFlightCount=0 NumRunning=0 IdlenessTimeSpan=**2.05:05:40.7903052**CollectionAgeLimit=00:10:00]]
   LocalActivations:
[].

**DetailedGrainReport for grain *grn/CC2963EA/0000000000000000000000000000000006ffffffcc2963ea+YYYY-0x8D84F9B9 from silo Squire.SiloWorkerRole_IN_3 SiloAddress=S10.10.0.57:11111:193958758**
   LocalCacheActivationAddresses=[]
   LocalDirectoryActivationAddresses=S10.10.0.43:11111:193958781
   PrimaryForGrain=*****
   GrainClassTypeName=[      [Activation: S10.10.0.57:11111:193958758_grn/CC2963EA/0000000000000000000000000000000006ffffffcc2963ea+YYYY-0x8D84F9B9@1e29458e #GrainType=_***\* Placement=RandomPlacement State=Deactivating NonReentrancyQueueSize=64 EnqueuedOnDispatcher=0 InFlightCount=0 NumRunning=0 IdlenessTimeSpan=**2.05:02:44.5471241** CollectionAgeLimit=00:05:00]]
   LocalActivations:
[].

**DetailedGrainReport for grain *grn/CC2963EA/0000000000000000000000000000000006ffffffcc2963ea+ZZZZ-0x71768536 from silo Squire.SiloWorkerRole_IN_3 SiloAddress=S10.10.0.57:11111:193958758
   LocalCacheActivationAddresses=[]
   LocalDirectoryActivationAddresses=S10.10.0.36:11111:193958776
   PrimaryForGrain=*****
   GrainClassTypeName=[      [Activation: S10.10.0.57:11111:193958758_grn/CC2963EA/0000000000000000000000000000000006ffffffcc2963ea+ZZZZ-0x71768536@11450790 #GrainType=_***\* Placement=RandomPlacement State=Deactivating NonReentrancyQueueSize=59 EnqueuedOnDispatcher=0 InFlightCount=0 NumRunning=0IdlenessTimeSpan=**2.06:08:21.3209408** CollectionAgeLimit=00:05:00]]
   LocalActivations:
[].

The grains all appear to be stuck in the Deactivating state and their IdlenessTimeSpan all are running for approximately the same time ~2 days 6 hours.  Tracing back the time for this, it appears to have been idle since approximately Sunday, February 28, 2016 at 4:51:00 AM PST time.  They also all appear to be living on the same silo: S10.10.0.57:11111:193958758.  

 Is there a way that a grain can get stuck in deactivating and never get destroyed?  I did see a  “Error calling grain’s OnDeactivateAsync” for a few Grains, but doing a detailed grain report on them did not turn up the same issue as above where the grain is stuck deactivating. 

 I noticed in OrleansManager there were a couple commands, “collect” and “unregister”.  Collect appears to force collection any activations older than a passed in age limit and Unregister will remove it from the RemoteGrainDirectory.  Collect sounds like it may trigger and destroy the above activations potentially fixing the issues on these grains , but I’m hesitant to run either of these commands until we get more information as to exactly the effects that they would cause.

Thanks!

Steve

**Comment by gabikliot** [comment]
I would like to focus first on the 2nd issue - stuck activation. You have provided a lot of very usefull information, thank you for that!
Still, I have a number of questions before diving in:

1) I can pretty clearly see that you have changed the grain reports and as a result, some fields got messed up. Can you please re-post the grain reports **as is**, without omitting any data. If you want to  anonimize anything, please do but without loosing any data and while maintaining mapping - map same grain types and keys to similar hashes.

2) Any chance you can share the full silo log? You can do it privately to me or @sergeybykov  via private gitter chat.

3) What your code in `OnDeactivateAsync` is doing?  Any chance is it making a blocking .Result/Wait call? Is it making another grain call? Could there be a cycle of grain calls in this case? Do you call into any storage library, which may never resolve a Task? I see there are 2 different grain types involved, so please answer for each.

.4) When the grain appears stuck, what do you see on the client? The calls just times out?

**Comment by gabikliot** [comment]
HI @SGI-Swong 

Do you have the extra information that I asked for?

**Comment by Plasma** [comment]
@gabikliot I'm not related to @SGI-Swong however testing Orleans on Azure worker roles here, I am noticing a potential similar issue.

When a grain activation is on RoleSiloRole_IN_0, if I reboot that role gracefully via the Azure portal (OnStop() should be called in my code, etc), then the grain is not moved to _IN_1 during the reboot.

Instead my code times out trying to send a message to the grain instance. It recovers when the role returns online.

In this case, would that be a cache issue on the client (web role) thinking it should still talk to the grain on _IN_0, or is it _IN_0's silo that failed to deactivate/mark itself as offline during the known reboot event?

I do see _orleansAzureSilo.Stop() called in OnStop() in the RoleEntryPoint.

**Comment by Plasma** [comment]
In particular, I see this during a reboot if I try and send a message:

```
System.AggregateException: One or more errors occurred. ---> System.TimeoutException: Response did not arrive on time in 00:00:30 for message: Request *cli/f35bcf87@6f8c52a7->S10.241.96.13:30000:197430782*grn/1A431302/5dfe04bb #83: global::TestGrain.IDemoGrain:GetDebugInfo(). Target History is: <S10.241.96.13:30000:197430782:*grn/1A431302/5dfe04bb:>
```

After the timeout occurs, if I re-send the command it seems to work. Is there a period where it will always timeout?

**Comment by gabikliot** [comment]
@Plasma , I don't think your case is related or similar to this issue. This issue is about activation remaining stuck forever in Deactivation.

In you case:
1) Make sure you Role OnStop code calls Silo.Stop. https://github.com/dotnet/orleans/blob/master/Samples/AzureWebSample/OrleansAzureSilos/WorkerRole.cs#L72

2) If you shutdown the silo gracefully, I believe you should not see even a single timeout. If you don't, or in case if failures, you will see some timeouts, for up to 30 sec (which is the default time to detect failures, configurable). After that, next calls will succeed.

**Comment by Plasma** [comment]
Thanks @gabikliot. I do call OnStop, I'll clarify a proper test case for you soon.

It seemed to be if I get a grain activated on instance 0, shut down the role instance at instance0, and immediately messaged the grain. If I waited a minute or so first before messaging after the shutdown it was fine.

**Comment by gabikliot** [comment]
Having a test demonstrating that would be great! Thank you @Plasma .

**Comment by sergeybykov** [comment]
Looks like this one got superseded by #4757. Closing in favor of it.
