### ISSUE TITLE
Policy for closing un-responsive isssues

### ISSUE THREAD

**Issue by gabikliot** [dotnet/orleans#1564]
This is a discussion issue regarding our policy for open un-responsive issues.

We see sometimes that people open issues, ask questions or request help, but then do not respond to your answers/requests for more data or suggestions for a solution.
I suggest to adopt a policy according to which we close those issues after some time. That time can be quite large, lets say a week or two, even a month may be OK, but lets not leave those open issues hang out for ever.
Examples are:
https://github.com/dotnet/orleans/issues/1275, https://github.com/dotnet/orleans/issues/1299, ...

What do people think?

**Comment by ReubenBond** [comment]
I'm for this, certainly for issues tagged `question` or `bug` or where there's an open question & no followup. 

What about issues which just aren't actively being worked on? For example, do we close the Service Fabric issue because I don't have the cycles to actively develop it? Maybe we do, I'm open to that.

**Comment by gabikliot** [comment]
I am OK with leaving the "Work in progress" issues open. They are in a different ball park in my view. They are something that we do want to work on, just did not get the time to yet. While the question/bug are just out there, with no visible way to make any progress.

**Comment by sergeybykov** [comment]
I think anything of value should stay open while dead issues like questions with no follow up we should close. I'd say after a week. In any case, it is easy to reopen an issue if the person who originally opened it comes back.

**Comment by gabikliot** [comment]
Agree.
