### ISSUE TITLE
using Azure Membership table with Public IP addresses

### ISSUE THREAD

**Issue by simonycs** [dotnet/orleans#1571]
Hi, 

We have been entertaining the idea of exposing Azure Membership table with Public Instance IP addresses. Basically since Azure support instance level Public IP capability, we could have a Orleans Client sitting anywhere that could hook up with Azure Orleans Services. We are not very concerned with Security right now since the data we hosting is not confidential and we could also add ACL in the Cloud Service. We could query Azure Management API to retrieve the Public IPs of each instance and replace the address in the SiloInstances table with Public one. it requires some change in the Orleans AzureUtil code but seems doable. We were wondering if anyone has successfully done that before and if you guys know if there is any other complications by doing so. 

Thanks,
Chunsheng

**Comment by sergeybykov** [comment]
Looks like nobody has tried to use such a setup.
