### ISSUE TITLE
Incomplete grainType when activating generic grains

### ISSUE THREAD

**Issue by jasonholloway** [dotnet/orleans#1579]
Hello,

It seems that generic grains can never have their state loaded properly on activation, as the various `PlacementDirectors` that produce the `grainType` string to be used in retrieving the grain from storage are all without generic type information for the grain in question, and therefore produce `grainTypes` with generic args missing.

This contrasts with explicitly calling `ReadStateAsync()` and `WriteStateAsync()` from the grain itself, which, via `GrainStateStorageBridge`, produces a fully-specified `grainType` each time.

The upshot is, state is written to one storage key, but loaded from another in the case of activation.

There's a simple enough workaround in calling `ReadStateAsync()` from each generic grain's `OnActivateAsync()` - but this isn't fantastic, obviously.

Does this sound right?

**Comment by sergeybykov** [comment]
Sounds like an embarrassing bug. Need to investigate. Thank you, @jasonholloway!

**Comment by jasonholloway** [comment]
Well, I'm hoping the embarrassing mistake's not mine! But it looks right...

**Comment by gabikliot** [comment]
Can you produce a test that reproduces that problem?

**Comment by jasonholloway** [comment]
Yep, here you go: a fork with an added test method [here](/jasonholloway/orleans/tree/generic-activation-test).

The test method is this: `UnitTests.StorageTests.PersistenceGrainTests_Local.Persistence_Grain_Activate_StoredValue_Generic()`.

**Comment by jasonholloway** [comment]
Just out of interest - would making a pull request with the above be the normal thing to do here?

**Comment by gabikliot** [comment]
Yes, pull request. If the test fails, mark it with skip attribute.

**Comment by Maarten88** [comment]
When testing with a custom storage provider, I see the value of the grainType parameter for a generic grain is different between the ReadStateAsync and the WriteStateAsync functions for the same grain:

    ReadState -> MyProject.Grains.GrainIndexGrain`1
    WriteState -> MyProject.Grains.GrainIndexGrain`1[[MyProject.GrainInterfaces.IApplicationGrain, MyProject.GrainInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]

I have not found where this problem originates, but I think the inconsistency of the grainType parameter is what causes this bug.

**Comment by sergeybykov** [comment]
Resolved via https://github.com/dotnet/orleans/pull/1897.
