### ISSUE TITLE
Question: What triggers Orleans to detect duplicate activation and de-activate one of them

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1588]
I know there are very rare situations where two silos may activate the same (not stateless worker) grain, and according to documentations Orleans will eventually find out about it and ask one of the silos to de-activate his grain instance. What causes this duplicate detection logic to kick in? Is it the client sending a grain message to gateway? Is it every grain message (e.g. including reminders/streams)? Is it based on some timer or other condition? 

Additionally, how long does it usually take until one of the grain instances is de-activated? Is it, let's say, up to 10 seconds? Can this time be controlled by configuration?

**Comment by gabikliot** [comment]
None of the above.
It is a Membership change notification: https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Catalog/Catalog.cs#L1284

Usually, it is very very fast - tens/hundreds of milliseconds: from the moment a silo was declared dead until all silos learn about it. This usually takes one message latency plus one membership table read. But in the worst case the msg may be lost, so it is bounded by the time membership table is read periodically. One minute by default, configurable. More on membership here: http://dotnet.github.io/orleans/Runtime-Implementation-Details/Cluster-Management
