### ISSUE TITLE
Consider renaming NuGet packages

### ISSUE THREAD

**Issue by jkonecki** [dotnet/orleans#16]
Current name of the NuGet packages is **ProjectOrleans.xxx**.

Consider renaming it to **Orleans.xxx** or **Microsoft.Orleans.xxx**.
The word *project* in the package name doesn't seem to add any value and won't help with powershell auto-completion (orl + TAB).

I'm happy to update all the nuspec files

**Comment by ReubenBond** [comment]
+1 for Microsoft.Orleans.XXX

**Comment by sergeybykov** [comment]
+1. I agree, "Project" doesn't add any extra value. Let's do it.

**Comment by jkonecki** [comment]
Sergey, so are we ok for Microsoft.Orleans.xxx or you need to fill in
gazillion approval forms to use this prefix ;-)?

**Comment by sergeybykov** [comment]
We are okay. No gazillion forms. New Microsoft. :-)

**Comment by jkonecki** [comment]
Cool ;-). I'll do the change today.

**Comment by sergeybykov** [comment]
Thank you!

**Comment by sergeybykov** [comment]
Merged. Thank you, Jakub!
