### ISSUE TITLE
The Unit-Testing-Grains.md file uses MSTest, and doesn't mention any other test framework.

### ISSUE THREAD

**Issue by moswald** [dotnet/orleans#1600]
While MSTest isn't _deprecated_, it's usage isn't exactly in vogue at this time. Most new code seems to be tested with xUnit 2.

A preferred step-by-step document would use xUnit in the example code, and it would at least mention that other frameworks such as NUnit are possible.

**Comment by sergeybykov** [comment]
@moswald Good point. Would you like to take a stab at updating https://github.com/dotnet/orleans/blob/gh-pages/Step-by-step-Tutorials/Unit-Testing-Grains.md?

**Comment by mikkelbu** [comment]
Shouldn't this issue be closed, since #2595 was merged?

**Comment by moswald** [comment]
Oh, yep. Jeez, I filed this awhile ago and then promptly forgot about following up. I have a private branch that I guess I don't need anymore. 😅
