### ISSUE TITLE
a possible bug in AzureGatewayListProvider.cs

### ISSUE THREAD

**Issue by shayhatsor** [dotnet/orleans#1601]
I was just browsing the code and saw [this](https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Storage/AzureGatewayListProvider.cs#L28). it doesn't lock anything, since we're returning a task. It should either be an async compatible lock or removed altogether.

**Comment by sergeybykov** [comment]
Indeed looks like a harmless bug - the lock doesn't protect anything.

**Comment by gabikliot** [comment]
Fixed via #1602.
