### ISSUE TITLE
Coreclr compatibility: re-enable F# projects/code

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#1606]
#1605 disabled F# projects in order to make initial progress. These must be re-enabled.

**Comment by veikkoeeva** [comment]
As relevant, I'll link [F# for CoreCLR Status](https://github.com/Microsoft/visualfsharp/wiki/F%23-for-CoreCLR---Status) and [How to help with building F# for the CoreCLR](https://github.com/Microsoft/visualfsharp/issues/688) as a top-level issue.

**Comment by veikkoeeva** [comment]
CoreCLR support merged to F# mainline: https://github.com/Microsoft/visualfsharp/pull/1006#event-620529144.

**Comment by ReubenBond** [comment]
This issue is not relevant to our current CoreCLR efforts. Each project is being moved to the new tooling piece by piece
