### ISSUE TITLE
Question: Do grains have to implement IGrainWithXXXKey?

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1627]
Is it possible to have a certain grain type implement IGrain without having a compile-time known primary key type? I ask because I want to test a system grain, called ConsumerGrain, by faking his input using another grain for test purposes, called ProducerGrain. I'd like the ProducerGrain to have the same primary key as ConsumerGrain, so in the test I can control which ConsumerGrain gets which data by invoking a ProducerGrain with matching id. Is this supported? If not, do you agree it should be supported?

**Comment by sergeybykov** [comment]
I'm not sure I fully follow the scenario. You would still need a key, and `IGrainWithXXXKey` merely specifies which type is used for the key. You can have two grain classes, in your case `ConsumerGrain` and `ProducerGrain`, implement the same grain interface `X`, and then easily choose which class to target at run time by passing the optional grain class name prefix to `GrainFacroty.GetGrain<X>(key, prefix)`. Would this not do what you need?

**Comment by Eldar1205** [comment]
This is not what I need, and in the end I realized I can't implement what I originally had in mind due to generic constraints and bad design, so I chose another design. However I believe there's still an interesting question whether it's possible to have a grain type without a compile-time-known key type?

**Comment by sergeybykov** [comment]
>However I believe there's still an interesting question whether it's possible to have a grain type without a compile-time-known key type?

I'm not sure how this could work. In most cases, a grain needs to know its identity - the key, hence the key type.

**Comment by Eldar1205** [comment]
Thanks. I'll close the issue, question answered.

2016-04-01 0:34 GMT+03:00 Sergey Bykov <notifications@github.com>:
