### ISSUE TITLE
Statistics exceed the column width

### ISSUE THREAD

**Issue by Astorlights** [dotnet/orleans#1628]
We're getting the exception _System.Data.SqlClient.SqlException: String or binary data would be truncated_. It's similar to issue [https://github.com/dotnet/orleans/issues/796](https://github.com/dotnet/orleans/issues/796), but this time it's the column Statistic in OrleansStatisticsTable being set up as NVARCHAR(250), while the value can be longer, in our case 265 characters : 
Grain.EImporterGrainCollection.Cache.CacheReplicaGrain`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[EImporterDomain.Database.ImportTableInfo, EImporterDomain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]

**Comment by veikkoeeva** [comment]
@Astorlights There shouldn't be now harm increasing the column width even in runtime as Orleans reads all there is. I remember there's some ADO.NET limit, which is quite, after which one needs to read in chunks. Care to do a PR which widens it by default?

A better fix would be to actually refactor the whole statistics part. I can help with ideas (if I didn't already write them somewhere) if you want to give it a shot. :)

**Comment by Astorlights** [comment]
I'm not sure about refactoring the whole stats, but I'll try do the PR for widening the column (to 512?).

**Comment by veikkoeeva** [comment]
@Astorlights I'm not sure. As you see from the issue you linked, it takes some work to actually see what would the upper bound be. If you don't see that long lines, it may be sufficient.

**Comment by gabikliot** [comment]
Fixed via #1635.
