### ISSUE TITLE
Xunit project exception

### ISSUE THREAD

**Issue by dsarfati** [dotnet/orleans#1636]
I'm having problems adding basic unit tests to our Orleans project. Orleans is unable to find the implementation for the grain interface. I created a very simple demo that recreates the same error we are getting on our larger project. Any help getting this single test running would be great!

**Sample:** https://github.com/dsarfati/orleans-xunit 

**Exception:**
`
Result Message:	System.ArgumentException : Cannot find an implementation class for grain interface: GrainInterfaces1.IGrain1. Make sure the grain assembly was correctly deployed and loaded in the silo. Loaded grain assemblies:  
`

**Comment by sergeybykov** [comment]
@dsarfati The link above points to Orleans docs. Did you mean to point to your repro project instead?

**Comment by dsarfati** [comment]
@sergeybykov oops. Updated the link

**Comment by dsarfati** [comment]
Looks like I figured out the issue. The published version of Orleans (1.1.3) doesn't look for grains in the startup directory. This was added in #1190, so I added the nightly build nuget packages (1.2.0) to our local Nexus and everything works exactly as expected.

**Comment by sergeybykov** [comment]
@dsarfati Great.
