### ISSUE TITLE
Remote Deployment Scripts: Get-Process

### ISSUE THREAD

**Issue by Kraegon** [dotnet/orleans#1644]
I've been trying to use the remote deployment powershell scripts, found in the /misc/scripts folder. When the scripts attempt to check whether or not the specified process is running on a remote machine, the Get-Process command fails because the operation is not permitted remotely. I was wondering if possibly Get-Process shouldn't be called as-is but using Invoke-command?
I don't have a lot of experience in Powershell, so I am wary of messing around too much.

**Comment by sergeybykov** [comment]
You need to configure WinRM and PowerShell on the target servers for the scripts to work. I uploaded the old doc we had for these scripts - https://github.com/dotnet/orleans/blob/master/misc/scripts/RemoteDeployment/Orleans-Remote-Deployment.docx. It has the necessary configuration steps.

**Comment by Kraegon** [comment]
Thank you very much for uploading the document. I've also used the similar instructions found here at https://dotnet.github.io/orleans/Step-by-step-Tutorials/On-Premise-Deployment
It seems that Get-Process cannot execute due to some infrastructure problems, using Invoke-Command seems to do the job as a workaround. The following case seems relevant:
https://stackoverflow.com/questions/22357063/get-process-to-remote-computer-doesnt-work-but-invoke-command-does
