### ISSUE TITLE
Question: Can Orleans grain Logger be used in multi-threaded scenario?

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1646]
I have a grain that does parallel async I/O operations, calls to other grains, and I want to run them with retries. If some tries fail, I'd like to use the grain's `Logger ` to log a warning. Since the grain requests run in parallel, and it's important that remains that way, the question is can the `Logger ` be used in that parallel context? 

I looked at `TrackTrace `method and other telemetry consumers delegation methods, and they are thread-safe (assuming the consumers are, which they should since they are practically singletons), while the `Log `method isn't (modifies a non-thread safe dictionary). Can I assume that the Logger is by-design thread-safe while using the `TrackXXX` APIs and telemetry consumers on the other end? If that's the case, is it officially documented as part of the framework behaviour the application can rely on?

**Comment by gabikliot** [comment]
Code in the grain never runs multi threaded. Single threaded execution is a basic and fundamental property of grain execution model.

**Comment by Eldar1205** [comment]
Just to make sure, even with following code the `consumerGrainsStartConsumingTasks `will never execute CPU-bound operations in parallel?

```
var consumerGrainsStartConsumingTasks = Array.ConvertAll(eventHubRuntimeInfo.PartitionIds, partitionId =>
                {
                    var eventHubPartitionKey = new EventHubPartitionKey(eventHubInfo.ServiceBusNamespace, eventHubInfo.EventHubName, partitionId);
                    var consumerGrain = GrainFactory.GetGrain<IManagedEventHubConsumerGrain>(eventHubPartitionKey.ToString());
                    return RetryUtils.RetryWithLinearPolicyAsync(
                        () => consumerGrain.StartPeriodicConsumption(eventHubInfo.SubscriptionId, eventHubInfo.RootPolicyName, eventHubInfo.RootPolicyKey, _cManagedEventHubConsumerGroup),
                        retriesCount: 3,
                        delayBetweenTries: TimeSpan.FromSeconds(5),
                        logger: _logger);
                });

            await Task.WhenAll(consumerGrainsStartConsumingTasks);
```

**Comment by Eldar1205** [comment]
I re-read carefully the grains turn based concurrency carefully and now understand that the awaited tasks running inside the `RetyWithLinearPolicyAsync` will be executed by Orleans task scheduler which ensures the single concurrency model. Thanks for your help :)
