### ISSUE TITLE
Add GrainClient managment to OrleansTestHost test framework

### ISSUE THREAD

**Issue by jason-bragg** [dotnet/orleans#1649]
I suggest we add to the OrleansTestHost test framework the ability to manage multiple GrainClients, each in its own app domain, similar to how Orleans Silos are managed.

OrleansTestHost allows test to configure and manage multiple Orleans silos in a cluster, with each silo in its own appdomain, but it does not support similar capabilities for GrainClients.  Currently the test itself acts as a (the only) grain client connecting to the cluster.  This makes it difficult to test multiple GrainClient and GrainClient failure scenarios.

**Comment by amccool** [comment]
+1

**Comment by gabikliot** [comment]
Good idea.

**Comment by benjaminpetit** [comment]
GrainClient is no longer static
