### ISSUE TITLE
Question: Why doesn't TraceLogger TrackTrace respect current severity level?

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1650]
I noticed the implementation of `TrackTrace`doesn't check if the message's severity level is equal/lower to current logger's severity level. That means that DefaultTraceLevel, TraceLevelOverride and runtime control using `ManagementGrain`don't apply when using `TrackTrace`, but apply when using Error/Warn/Info/etc. Is this like that by design? If so, will the `Error`/`Warn`/`Info`/etc. APIs remain for the long run? I'm asking since I was told the `ILogConsumer`will be deprecated in favor of the different `ITelemetryConsumer` interfaces, so maybe the original logging APIs are planned to be deprecated as well.

**Comment by sergeybykov** [comment]
Looks like a bug to me. We are keeping both `ILogConsumer` and `ITelemetryConsumer` until we are certain `ITelemetryConsumer` does everything that `ILogConsumer` does and correctly. After that we can deprecate `ILogConsumer`.

**Comment by ReubenBond** [comment]
Obviated by the move to `ILogger` in later Orleans releases
