### ISSUE TITLE
Question: Serializers for Orleans streams payload classes

### ISSUE THREAD

**Issue by dotanpatrich** [dotnet/orleans#1654]
I'm kind of new to Orleans and using it currently to process incoming events passes to grains using orleans streams. The Orleans client sends to the stream objects of type 'EventData', which are implemented in a separate nuget we consume. On the Orleans silo side, we have a grain with subscribes to this stream using ImplicitStreamSubscription. The grain interface does not uses the 'EventData', and actually the stream subscription is the main entry point for this grain.

The problem I encounter is when the client try to send the 'EventData' instances to the stream, I get back an exception on missing serializer for the 'EventData' class. Marking the 'EventData' class as [Serializable] solved this, but understand does not uses the built-in specialized serializer of Orleans.

How can I get Orleans to use the built-in generated serializers for the 'EventData'?

According to the documentation it seems to be a must to add the orleans templates nuget to the 'EventData' assembly project. Is it indeed? Since it is a nuget which is used in runtime environment other than Orleans, I would like to keep it without any reference to orleans.

**Comment by sergeybykov** [comment]
I updated https://github.com/dotnet/orleans/blob/gh-pages/Advanced-Concepts/Serialization.md with information about `[KnownType]` and `[KnownAssembly]` attributes as another way to trigger generation of Orleans serializers for additional types.

**Comment by Eldar1205** [comment]
`EventData `internal structure relies on a stream, usually a `MemoryStream `but not always. How will Orleans behave trying to serialize that? Streams are usually not serialization friendly as far as I know

**Comment by dotanpatrich** [comment]
Thanks for pointing out how to use the [KnownType] and [KnownAssembly] attributes.
I tried to follow the instructions you sent by adding 

I added the following attributes to the grain interface code:

```
[assembly: KnownType(typeof(EventData))]
[assembly: KnownAssembly(typeof(EventData))]
```


But keep on getting this exception when sending a message to the stream:

```
Exc level 0: System.ArgumentException: No serializer found for object of type EventData. Perhaps you need to mark it [Serializable] or define a custom serializer for it?
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, BinaryTokenStreamWriter stream, Type expected)
   at Orleans.Serialization.BuiltInTypes.SerializeImmutable[T](Object original, BinaryTokenStreamWriter stream, Type expected)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, BinaryTokenStreamWriter stream, Type expected)
   at Orleans.Serialization.BuiltInTypes.SerializeInvokeMethodRequest(Object obj, BinaryTokenStreamWriter stream, Type expected)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, BinaryTokenStreamWriter stream, Type expected)
   at Orleans.Serialization.SerializationManager.Serialize(Object raw, BinaryTokenStreamWriter stream)
   at Orleans.Runtime.Message.Serialize_Impl(Boolean batching, Int32& headerLengthOut, Int32& bodyLengthOut)
   at Orleans.Messaging.OutgoingMessageSender.Process(Message msg)
```

What am I missing here? Do I still need to mark the EventData class as [Serializable]?

**Comment by sergeybykov** [comment]
Issue with `[KnownType]` and `[KnownAssembly]` sometimes getting ignored have been reported. Try `[Serializable]` as a workaround.

**Comment by aprooks** [comment]
Found an error behavior, probably relevant to this one.

I have an external type marked with KnownAssembly.

Then I send it from client to grain A, and then from grain A to grain B.

This works fine with in-memory config (InMemory pub sub storage and simpleMessageStreamProvider). But once I switch to AzureTableStorage and AzureQueueStreamProvider, I start getting exception "Type not marked as serialized" during grain call from A to B, even though call from client to A is fine and all data is serialized and deserialized

**Comment by sergeybykov** [comment]
@aprooks Do you have `[KnownType]` for that type in an grain interface/implementation project? Do you see a serializer getting generated for the type in Properties\orleans.codegen.cs?

**Comment by aprooks** [comment]
@sergeybykov sorry did not mention - I'm using Orleankka, so it might be it's issue. I will try checking what it generates.

**Comment by sergeybykov** [comment]
@aprooks That shouldn't matter. I'd first check if codegen generates a serializer anyway.

**Comment by aprooks** [comment]
@sergeybykov I dug a bit more. First there is no code.cs, I have no idea how Orleankka generates interfaces, so probably it is time to check :)
Second, My initial description is was wrong. Grains are communicating properly, but in the second grain, event with same external object is being publish to stream provider and throws exception on publish. I could try recreating this behavior in Orleans if needed

**Comment by sergeybykov** [comment]
@aprooks No Properties\orleans.codegen.cs in the project?

A unit test reproducing the problem would really help.

**Comment by amccool** [comment]
I dont want to hijack this issue, but I believe I have a similar problem.

**Comment by sergeybykov** [comment]
https://github.com/dotnet/orleans/pull/1864 added an explicit `[GenerateSerializer]` attribute to instruct codegen to try to generate a serializer for a type. `[KnownType]` and `[KnownAssembly]` have the same effect *only* if the target type is marked as `[Serializable]`. This was confusing. We might deprecate `[KnownType]` altogether.

@amccool I suspect this issue is different from #1881.

**Comment by sergeybykov** [comment]
@dotanpatrich Can you check that `[GenerateSerializer]` solves the problem for you?
