### ISSUE TITLE
Casting from generic to non-generic interface fails with an obscure error message

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#1656]
After reverting #1604 `Generic_CastGenericInterfaceToNonGenericInterfaceBeforeActivation` fails with an obscure message:

> "Error finding invoker for interface ID: -154835372 (0xF6C56654). System.ArgumentNullException: Value cannot be null."

The cast should succeed.

**Comment by ReubenBond** [comment]
Fixed since at least #8705
