### ISSUE TITLE
Question: Grain context in Orleans

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1659]
In my Orleans based service, I use DI container and DI heavily. In some cases there's a singleton object in the grain's dependency graph, a.k.a object graph, usually a factory of some sort. I have a case where I want the factory to use the grain's `Logger` to log traces on behalf of the grain requesting something from the factory. With WebApi (for example) you have a static HttpContext you can access to get data on current request. With Orleans there's the RequestContext that serves a similar purpose - is there a problem with putting a reference to the grain itself in the RequestContext, as a way to achieve a so called "GrainContext"?

**Comment by sergeybykov** [comment]
I'm not sure I understand - do you want to put a reference to the grain activation object to `RequestContext`?

The main purpose of `RequestContext` is to facilitate passing additional environment information along the grain call chain, e.g. an auth token. Passing a reference to a local object obviously won't work. Did I misunderstand your question?

**Comment by Eldar1205** [comment]
You understood the question correctly, I ask about putting the grain reference, e.g. instance of class inheriting `Grain`, on the `RequestContext`. The motivation is having a `GrainContext.Current` similar to other request handling frameworks (WebApi, WCF, etc.). Given the current request is handled by a certain grain, I think it's a good idea to have access to current grain as well. I actually don't want the local grain reference to pass along grain call chain, since the next grain in the chain should put its own reference on the `RequestContext`. So question is will putting a local reference on `RequestContext` cause an exception or will Orleans won't pass such local references and work seamlessly?

**Comment by sergeybykov** [comment]
What code would access that variable? Since grains are reactive in nature, why can't grain explicitly pass `this` to that code instead of relying on the ambient state in `RequestContext`?

**Comment by Eldar1205** [comment]
Passing this isn't DI friendly and hinders loose coupling. The grain reference will have to be passed along the call stack until it reaches the destination somewhere in the object graph, along the way passing through business objects that shouldn't be aware of Orleans existence at all, hence hindering loose coupling. With ambient state, I can have any part of the grain object graph access the current grain, without other parts knowing about it.
