### ISSUE TITLE
Question: How to build Orleans and generate Nugets from source?

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1660]
I've downloaded Orleans solution from master branch and would like to build it from source (Release build) and generate the Nugets. I looked at the contribution guide and didn't see an instruction on how to do so, can someone please tell me?

**Comment by sergeybykov** [comment]
Run `src\Build.cmd`.

**Comment by jasonholloway** [comment]
And if you're tweaking your own version, make sure to change ``src\Build\Version.txt`` first to stop NuGet getting confused - stick your name on the end of it or something.
