### ISSUE TITLE
Extension methods on GrainReference

### ISSUE THREAD

**Issue by FenrisWolfAtMiddleEarth** [dotnet/orleans#1667]
There is a set of extension methods available for an IGrain implementation. They are useful for extracting a grains key.
Shouldn't they also be available for GrainReference, so they can be used in a StorageProvider?

**Comment by sergeybykov** [comment]
Those extension methods are defined for `IAddressable`, and since `GrainReference` implements `IAddressable`, they also work for grain references.

```csharp
ISimpleGrain grain = GrainFactory.GetGrain<ISimpleGrain>(12345);
var key = grain.GetPrimaryKeyLong();
```

**Comment by FenrisWolfAtMiddleEarth** [comment]
I almost agree :-)
The method which I need GetPrimaryKeyString seems to be implemented with IGrainWithStringKey. Or am I missing something?

        public static string GetPrimaryKeyString(this IGrainWithStringKey grain);

**Comment by sergeybykov** [comment]
That one works as well:

```csharp
var g = GrainFactory.GetGrain<IStringGrain>("foo");
string key = g.GetPrimaryKeyString();
```

**Comment by FenrisWolfAtMiddleEarth** [comment]
Thanks for your reponse, but you lost me entirely.
I would like to use GetPrimaryKeyString in a StorageProvider. In my understanding there is no way of doing that. In a StorageProvider, I only have a GrainReference.
In your snippet code, g is a of type IGrainWithStringKey, which matches nicely with the extension method GetPrimaryKeyString. So yes. That will work.
GetPrimaryKeyString is different from the other GetPrimaryKey, which all extend IAddressable. GetPrimaryKeyString is the only one of the methods which does not extend IAddressable.

        public static Guid GetPrimaryKey(this IAddressable grain);
        public static Guid GetPrimaryKey(this IGrain grain);
        public static Guid GetPrimaryKey(this IAddressable grain, out string keyExt);
        public static Guid GetPrimaryKey(this IGrain grain, out string keyExt);
        public static long GetPrimaryKeyLong(this IAddressable grain);
        public static long GetPrimaryKeyLong(this IGrain grain);
        public static long GetPrimaryKeyLong(this IAddressable grain, out string keyExt);
        public static long GetPrimaryKeyLong(this IGrain grain, out string keyExt);
        public static string GetPrimaryKeyString(this IGrainWithStringKey grain);

**Comment by sergeybykov** [comment]
Sorry, I indeed lost your point about storage provider along the way. I submitted https://github.com/dotnet/orleans/pull/1675 for the sake of API completion, but `Guid GetPrimaryKey(this IAddressable grain, out string keyExt)` actually already provides the same functionality because string keys internally are implemented as compound keys with an empty GUID.

**Comment by FenrisWolfAtMiddleEarth** [comment]
Thanks for your help

**Comment by sergeybykov** [comment]
@FenrisWolfAtMiddleEarth You are welcome.
