### ISSUE TITLE
Suggestion: Resolve bootstrap providers using the application supplied IServiceProvider

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1671]
Today Orleans creates application registered `IBootstrapProvider`implementations by invoking their constructor directly. I suggest that like with grains, Orleans will use the `IServiceProvider` supplied by the application to create the `IBootstrapProvider`. That way several things can be supported without Orleans direct support:
1. Unit-testing: When the provider receives its dependencies using constructor injection instead of  getting them from the `IServiceProvider`injected during `Init`, thus avoiding the [service locator anti-pattern](http://blog.ploeh.dk/2010/02/03/ServiceLocatorisanAnti-Pattern/) which hinders unit testing.
2. Interceptors: Most DI containers provide an option for nterceptors as a way to generically extend an interface implementation with extra capabilities. Because all bootsrap providers implement a single generic IBootstrapProvider interface, any interceptor support from a DI container can enable their extensibility. 

What do you think of my suggestion? I'm pretty new to Orleans source code so I may be missing some issues with my suggestion.

**Comment by benjaminpetit** [comment]
Implemented in 2.0
