### ISSUE TITLE
Question: Can Orleans be told not load certain assemblies?

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1676]
In my cloud service there's a worker role that runs as Orleans cluster, and that role has several native dlls used as part of his deployment. On silo startup, Orleans tries to load all dlls as .Net assemblies and submit error traces when it fails to load a dll for unexpected reason, which happens for the native dll case. Is there an option to tell Orleans to exclude certain dlls from its loading process? I think it's good idea for those traces to remain as errors for unexpected scenarios, but if the app knows those dlls aren't .Net can it tell that to Orleans?

**Comment by sergeybykov** [comment]
We discussed (although I can't find an issue for that) doing the opposite give silo an explicit list of assemblies to scan, so that it would ignore everything else. I think that's a better approach than adding a skip list.

**Comment by Eldar1205** [comment]
That'd be great too :)
