### ISSUE TITLE
Question: Can application rely on IGrainRuntime & IProviderRuntime to be silo-level singletons?

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1677]
Grains can be injected with `IGrainRuntime `and then expose it's functionality as grain methods. Bootstrap providers are injected with `IProviderRuntime `(method injection) which exposes similar API to `IGrainRuntime`, namely access to `IGrainFactory `and getting loggers. Both are singletons - the `IGrainRuntime `is (internally) a field of Silo, and `IProviderRuntime `is (internally) implemented by `SiloProviderRuntime.Instance`. If I want their APIs to be accessible to parts of the application that aren't grains or bootstrap providers and aren't directly invoked by grains/bootstrap providers, can I for example store the `IProviderRuntime `received in a bootstrap provider in some static member that other classes could use to get loggers for themselves? Is there a better suggested way to implement a logger factory that can be accessed anywhere to create Orleans loggers, or to call grains, like Orleans internally has `TraceLogger.GetLogger` and `RuntimeClient.Current.InternalGrainFactory` that can be accessed from any context?

**Comment by sergeybykov** [comment]
Orleans runtime doesn't prohibit using statics for sharing such things. The argument against such approach I think is reduced testability because those classes will rely on the ambient environment variables that. Since those other classes will end up executing within the context of a grain in the end anyway, it would be cleaner to pass `IGrainRuntime` to them explicitly. At the end of the day, it's your decision how "hacky" you want your code be. Orleans runtime is oblivious to that.

**Comment by Eldar1205** [comment]
Thanks for your comment. I use ambient scopes in testable ways. Assume there's a static `GrainFactory` like used to be, then I create an `IGrainFactory` interface implemented by `GrainFactoryWrapper` that delegates to static `GrainFactory`. My objects depend on `IGrainFactory` and are testable, and since my code owns that interface and the implementation it's also injectable using a DI container whenever necessary. Given an object-dependency-graph grain->A->B->C->D using Orleans DI integration I can have the grain and D depend on `IGrainFactory` without B and C knowing about it, which IMO is important that as an application developer this can be done. What do you think about Orleans supplying the silo-level singletons in the IServiceCollection provided to the application for DI integration? That way they could be registered to the DI container and referenced only where needed cleanly without ambient environment.
