### ISSUE TITLE
Question: are bootstrap providers guaranteed to be called before grains receive messages?

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1678]
As part of learning how to use Orleans from application perspective, I have several questions raised regarding Orleans guaranteed behavior & semantics, e.g. behavior that isn't by accident and application can safely rely on. Current question revolves around bootstrap providers and grains, the two places an application logic can run when hosted in Orleans cluster - bootstrap providers are documented to run at Silo startup, and by looking at Silo.DoStart I can see bootstrap providers come before the MessageCenter.StartGateway which to my understanding it what enables grain requests to be received from any source (GrainClient, other grain, reminder, implicit stream, etc.), so bootstrap providers are effectively initialized before any grain receives a request in the silo. Did I understand correctly current behavior? Can this behavior be relied upon by application?

**Comment by sergeybykov** [comment]
You are correct. That's the current behavior and it can be relied on. Unless for some reason it changes in the future.
