### ISSUE TITLE
Warnings from AssemblyLoader not finding Applications directory

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1686]
I found the following warning in traces when running Orleans on my cloud service, it wasn't there first time I ran that cloud service with Orleans. Can someone please tell me why Orleans is looking for that directory and what are my options to make the warning go away?

[2016-04-17 16:21:03.792 GMT     7	WARNING	101705	AssemblyLoader.Silo	100.106.4.23:30000]	Unable to find directory E:\approot\Applications; skipping.

**Comment by sergeybykov** [comment]
`Applications` is the hardcoded path where silo looks for app assemblies. The warning is harmless. If you create such a directory before starting a silo, the warning will go away.

**Comment by Eldar1205** [comment]
And if there won't be any assemblies in that directory, won't that cause issues for the silo?

**Comment by sergeybykov** [comment]
No issues. This warning probably should change to an info.

**Comment by Eldar1205** [comment]
Added code that creates the directory on startup and it worked, thanks
