### ISSUE TITLE
Unmanaged Memory Consumption

### ISSUE THREAD

**Issue by PBeckerr** [dotnet/orleans#1689]
I started 2 Silos locally, 1. as Primary Node and the other one as secondary.

The amount of unmanaged memory is constantly rising. (White Bar = unmanaged)
[Profiler](https://cloud.githubusercontent.com/assets/13576643/14633168/b260ae5c-061c-11e6-9c01-9aaff4303ec0.png)

Its enough to just start the silos and let them idle.
PS: Im using the OrleansHost.exe

Log from a second testrun:
`[2016-04-19 09:16:21.986 GMT    10	INFO   	100507	Catalog	127.0.0.1:22223]	Before collection#8: memory=139MB, #activations=0, collector=<#Activations=0, #Buckets=0, buckets=[]>.	
`
`[2016-04-19 09:16:21.999 GMT    10	INFO   	100508	Catalog	127.0.0.1:22223]	After collection#8: memory=139MB, #activations=0, collected 0 activations, collector=<#Activations=0, #Buckets=0, buckets=[]>, collection time=00:00:00.0123494.`
`[2016-04-19 09:17:22.002 GMT    14	INFO   	100507	Catalog	127.0.0.1:22223]	Before collection#9: memory=158MB, #activations=0, collector=<#Activations=0, #Buckets=0, buckets=[]>.`
`[2016-04-19 09:17:22.004 GMT    14	INFO   	100508	Catalog	127.0.0.1:22223]	After collection#9: memory=158MB, #activations=0, collected 0 activations, collector=<#Activations=0, #Buckets=0, buckets=[]>, collection time=00:00:00.0018114`

**Comment by gabikliot** [comment]
This looks like very short time span sample of the memory profile. You need to run it for much longer if you want a strong evidence of a problem. It may just be a gen one or gen two small amount of garbage that is not GCed since there is no real problem. We do not force GC.collect calls and instead rely on GC to collect when it thinks it should. And we do have some light timers kicking in periodically producing small amount of garbage.

**Comment by PBeckerr** [comment]
Here is the log. 
No grain created, No Client connected.
[EWS-1-2016-04-19-09.09.06.489Z.txt](https://github.com/dotnet/orleans/files/226012/EWS-1-2016-04-19-09.09.06.489Z.txt)

In case its working as intended, how much RAM is recommended for running a silo?
200mb for the runtime alone seems unreasonable to me, at least if there is 0 load and its keep rising.

I will retry with a larger time span and will update my issue tomorrow.

**Comment by gabikliot** [comment]
1) your log is too short to tell any trend. As I wrote before, you need to run it longer.
2) for some reason there are no GC related stats in the log. I wonder if someone broke it and we stopped printing them. They used to be logged as part of all other runtime stats, as part of this long stats list, under Runtime. GC.
3) 200 MB is definitely a size we consider very, very reasonable and small. Orleans is a full blown distributed runtime, it's not a tiny library. Only 200mb, in a world of 10-100 GB servers as a norm, is a drop in the sea. That said, probably with a medium size efforts even that number could be easily reduced by half probably. But i don't think it's worth the effort or time.

**Comment by PBeckerr** [comment]
Thanks for the explanation
