### ISSUE TITLE
Azure Table Storage performance enhancements

### ISSUE THREAD

**Issue by gabikliot** [dotnet/orleans#169]
We ported Azure Storage to version 4.2 in PR #163 and followed up with a number of improvements in PR #168.
This now concludes all the work we planned to do w.r.t. upgrading to Azure Storage to version 4.2.

There are still a number of improvements and enhancements that were suggested by @veikkoeeva , @ReubenBond and @pherbel in PR #100 and in issue #79. I have summarized those below. These are "nice to have" and we don't plan to do them ASAP. Community PRs will be welcomed.

1)  Consider using DynamicTableEntity instead of TableEntity for increased efficiency. 
a.  As @veikkoeeva wrote: “Now the entities are refactored to use TableEntity, which uses reflection. DynamicTableEntity would probably better and it looks like it's essential in case one wants to employ storage data type updates without incurring downtime. The old code looks like uses reflection too and as that wouldn't be just updating the libraries and strictly associated code, I left it for some other PR that does further refactoring and optimizations.“
b.  Also consider EntityResolver
c.  [Windows Azure Storage Client Library 2.0 Tables Deep Dive](http://blogs.msdn.com/b/windowsazurestorage/archive/2012/11/06/windows-azure-storage-client-library-2-0-tables-deep-dive.aspx)
d. [Jeffrey Richter's (ed. of Wintellect fame) Guide to Working with Azure Storage Tables](http://www.wintellect.com/download/index/azurestoragetables)
2)  Consider refactoring queries to  use TableQuery.GenerateFilterCondition instead of explicit LINC queries.
a.  Windows Azure Storage Client Library 2.0 Tables Deep Dive
3)  Another idea by @veikkoeeva “I think the bolder aim could be to provide a stream to storage, or two streams. One stream could save straight to storage, the other could batch messages and save (adaptively on load?) based either on some time interval or elements in the queue. This stream perhaps could have a configurable failover so that when, say, Azure Table Storage (ATS) goes offline, a secondary system would be attempted (a SQL Server, or another ATS storage (via connectionstring)). This system could be perhaps provide library components to a common pubsub functionality. This kind of batching doesn’t look like too complicated from an Rx perspective. As an example: http://blog.petegoo.com/2013/01/20/reactive-extensions-in-message-processing/ (though delay sensitive stream would be more complicated). These streams could, naturally, provide a place to intercept the messages.”

**Comment by DixonDs** [comment]
Switch to `DynamicTableEntity` was done in https://github.com/dotnet/orleans/pull/1587

**Comment by ReubenBond** [comment]
There have been probably 3 entirely new Azure Table Storage SDKs released since issue was created and I believe it's no longer relevant
