### ISSUE TITLE
Warning from WindowsPerfCountersStatistics about counters not found

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1690]
I found a warning in traces of my Orleans based cloud service regarding windows perf counters not found, and would like to know if Orleans expects me too run OrleansCounterControl.exe as startup task of my worker role, or is there something else that I can do to my worker role/cloud service in order to have the perf counters Orleans is looking for? Any help would be appreciated. The trace:

[2016-04-19 06:56:44.580 GMT     7	WARNING	100701	WindowsPerfCountersStatistics	100.108.102.18:30000]	Windows perf counters not found -- defaulting to in-memory counters. Run OrleansCounterControl.exe as Administrator to create perf counters for Orleans.

**Comment by sergeybykov** [comment]
Yes, you need to run `OrleansCounterControl.exe` as an elevated task before starting a silo, so that the perf counter categories are registered.

**Comment by Eldar1205** [comment]
Worked, thank you very much
