### ISSUE TITLE
Question: Long running grain task breaks promise

### ISSUE THREAD

**Issue by peter-perot** [dotnet/orleans#1693]
Please see the following scenario:

I have a stateless worker grain (also reentrant) which looks like that:

````csharp
[StatelessWorker, Reentrant]
public class MyWorkingHorseGrain : Grain, IMyWorkingHorseGrain
{
	public async Task<string> DoSomeReallyHardWork(string name)
	{
		var worker = Task.Delay(50000); // imagine some heavy DB stuff here

		// this loop is just to keep the logger busy ;-)
		while (true)
		{
			var heartbeat = Task.Delay(2000);
			var task = await Task.WhenAny(worker, heartbeat);

			if (worker.IsCompleted)
			{
				this.GetLogger().Info("----- Mission accomplished.");
				break;
			}

			if (worker.IsCanceled)
			{
				this.GetLogger().Warn(0, "----- Mission canceled.");
				break;
			}

			if (worker.IsFaulted)
			{
				this.GetLogger().Error(0, "----- Something went wrong.");
				break;
			}

			this.GetLogger().Info("----- Still working.");
		}

		return "Hello " + name + "!";
	}
}
````

My simple console application initializes the client as follows (setting timeout to 2 minutes):

````sharp
GrainClient.Initialize(configFilePath);
GrainClient.SetResponseTimeout(TimeSpan.FromMinutes(2));
````

However: When I'm calling the long running method I get a "Response did not arrive on time in 00:00:30 for message." logged and the task is aborted.

In the most cases my real world application method runs faster so that the 30sec limit is not broken.

But sometimes it takes slightly longer to complete (doing some **async** DB stuff to collect some records).

What am I missing here? If this is not a bug (I think it's not :wink:), what is the right way to accomplish this?

ANNOTATION: The "heartbeat" stuff is only to get something logged. It can be removed so the method looks like this:

````csharp
public async Task<string> DoSomeReallyHardWork(string name)
{
	await Task.Delay(50000); // imagine some heavy DB stuff here
	return "Hello " + name + "!";
}
````

**Comment by sergeybykov** [comment]
The code looks legit to me. Does the client call `DoSomeReallyHardWork()` directly with no intermediate grains in between?

**Comment by peter-perot** [comment]
Yes, the method is called directly in this case. But would it make a difference if the method was called from  another grain?

**Comment by sergeybykov** [comment]
Silos have their own response timeout settings. It shouldn't matter in this case, but I was still wondering about the exact setup. Can you easily turn this in to a repro unit test?

**Comment by peter-perot** [comment]
How can I define the timeout settings for silos? Does this mean that there is an "inter-grain" or "inter-silo" timeout which is independent from the response timeout for the client?

Is there any entry in the XML configuration file I missed?

However, I'll try to make a test repro tomorrow or next week.

**Comment by sergeybykov** [comment]
Yes, those are for grain-to-grain calls, reminders, etc. Though the client timeout should be respected and propagated.

`MessagingConfiguration.ResponseTimeout` is in https://github.com/dotnet/orleans/blob/master/src/Orleans/Configuration/OrleansConfiguration.xsd#L253 for both client and silo config.

**Comment by peter-perot** [comment]
Thanks.

> Though the client timeout should be respected and propagated.

Exactly. IMHO it wouldn't make sense if the silo timed out following its own "short period timeout" without taking the client timeout into account which wants to set a longer period for the request.

**Comment by gabikliot** [comment]
Try defining the new value via client config file. I wonder if something broke in this programmable setter.

**Comment by peter-perot** [comment]
Hi Guys, I don't know what kind of bad coffee I had that morning, but for some reason I had commented out the method `SetResponseTimeout`. Sorry.

The good part is:

I learned that **client timeout settings are obviously propagated to the service. Is it right that the longest timeout wins, so that the resulting timeout is `max(clientSideTimeout, serverSideTimeout)`?**

If this observation is not wrong, could you please put this information into the docs? (If I didn't overlook it.)

**Comment by peter-perot** [comment]
Just one more question concerning timouts: **If a Grain A calls a Grain B, and Grain A knows that its request could take some more time** (so it would break the timeout limit), could Grain A override the propagated timeout somehow?

**Comment by sergeybykov** [comment]
@peter-perot 
>I learned that client timeout settings are obviously propagated to the service. Is it right that the longest timeout wins, so that the resulting timeout is  max(clientSideTimeout, serverSideTimeout) ?

Not quite. When a message is sent, its expiration time is set according to the response timeout setting on the caller's side. It doesn't matter what the value is set on the receiving end. We recommend to set the timeout on the client and silo side to the same value only for consistency of experience, so that a call to a grain from a client times out after the same period of time as an analogous call to it from another grain.

>If a Grain A calls a Grain B, and Grain A knows that its request could take some more time (so it would break the timeout limit), could Grain A override the propagated timeout somehow?

The main purpose of the timeout is to unblock the caller. A timer gets started on the caller side to fault the returned `Task` with a `TimeoutException` unless a response arrives before then. Hence, there is no way to change the timeout on the callee's side.

In fact, we only include expiration time in a message header as an optimization - to avoid processing messages that the caller already gave up on. If we didn't pass expiration time with a message, timeouts would work exactly the same way.

**Comment by hahn-kev** [comment]
Seems like it would be better to just call the original grain back with a result once you're finished if it's a long running task, instead of returning the value via a Task. That way the requesting grain isn't waiting on the value, you avoid the timeout issue altogether. Maybe I'm not understanding something.

**Comment by peter-perot** [comment]
@sergeybykov: Thanks for the explanation; now I understand why there is a client and a server side timeout and how it works internally. I think it would be helpful when mentioned in the docs. Anyway – I think we can close this issue.

@hahn-kev: Basically this is a design decision I think. But you are right: Long running tasks are possibly a better candidate for a subscriber/publisher pattern.

**Comment by gabikliot** [comment]
If the long running task has valuable intermediate results, one can use a stream to stream periodic results back to the original submitter.

**Comment by sergeybykov** [comment]
@peter-perot Our docs have lots of gaps. If you have an idea where such information would fit based on your experience of reading them and figuring out how things work, that would help. If you can submit a PR against https://github.com/dotnet/orleans/tree/gh-pages, that would be even better.

**Comment by peter-perot** [comment]
@sergeybykov: Thank you for the link to the docs. I'll have a look at it and submit a PR later.
