### ISSUE TITLE
Running my Orleans Silos in Service Fabric

### ISSUE THREAD

**Issue by sirkirby** [dotnet/orleans#1695]
I've seen a few issues about deeper integration between Orleans and Service Fabric, and I'm looking forward to that. For the time being, looking for opinions on just using Stateless services within fabric to run my silo hosts. On paper, looks like a simple conversion from Cloud Services to Service Fabric. Are there any other considerations I should be making before I dive in?

**Comment by sergeybykov** [comment]
Have you found https://github.com/ReubenBond/OrleansFabricSilo? For basic integration one other thing I can think of is make sure that the firewall has the silo-to-silo and client gateway ports open for internal traffic.

**Comment by sirkirby** [comment]
Thank you @sergeybykov, that is just what I was looking for!

**Comment by sergeybykov** [comment]
With Service Fabric now generally available we plan to make such integration a first class citizen in the codebase.
