### ISSUE TITLE
When changing to SQL for membership silo fails

### ISSUE THREAD

**Issue by BlueTechHound** [dotnet/orleans#1699]
Followed the instructions here to create the tables and configuration
http://dotnet.github.io/orleans/Advanced-Concepts/Configuring-SQL-Tables

and I get the following error when starting:
Unhandled Exception: System.SystemException: Failed to start Orleans silo 'DESKTOP' as a Secondary node

My configuration file is below, also attaching the error log

<?xml version="1.0" encoding="utf-8"?>
<OrleansConfiguration xmlns="urn:orleans">
  <Globals>
    <SystemStore SystemStoreType ="SqlServer"
                 DeploymentId="OrleansTest"
                 DataConnectionString="Data Source=xxx;Initial Catalog=xxx;Integrated Security=false; User id=xxx;Password=xxx;Pooling=False;Max Pool Size=200;Asynchronous Processing=True;MultipleActiveResultSets=True" AdoInvariant="System.Data.SqlClient" />
    <StatisticsProviders>
      <Provider Type="Orleans.Providers.SqlServer.SqlStatisticsPublisher" Name="MySQLStatsProvider" ConnectionString="Data Source=xxx;Initial Catalog=xxx;Integrated Security=false; User id=xxx;Password=xxx;Pooling=False;Max Pool Size=200;Asynchronous Processing=True;MultipleActiveResultSets=True" />
    </StatisticsProviders>
  </Globals>
  <Defaults>
    <Statistics ProviderType="MySQLStatsProvider" WriteLogStatisticsToTable="true"/>
    <Networking Address="localhost" Port="11111" />
    <ProxyingGateway Address="localhost" Port="30000" />
  </Defaults>
</OrleansConfiguration>

[DESKTOP-O8G3K0T-StartupError-2016-04-19-23.38.31.091Z.txt](https://github.com/dotnet/orleans/files/230229/DESKTOP-O8G3K0T-StartupError-2016-04-19-23.38.31.091Z.txt)

**Comment by veikkoeeva** [comment]
@BlueTechHound I took a quick run on `HelloWorld` sample and it seemed to work, certainly not that error. I deployed the DB from the master and got an exception from a missing key. A question: Are you running [Microsoft.Orleans.OrleansSqlUtils 1.1.3](https://www.nuget.org/packages/Microsoft.Orleans.OrleansSqlUtils/)?

Even if this is not the problem (let's find out the reason if not), the error message could be clearer.

**Comment by BlueTechHound** [comment]
I am running Microsoft.Orleans.OrleansSqlUtils 1.13, just installed it this morning through NuGet when trying to get this converted to use SQL. I did not run in to any issues with the script at all, but I do agree that I wish there was more insight on the exception.

**Comment by BlueTechHound** [comment]
SQL Version:
Microsoft SQL Server 2014 - 12.0.4422.0 (X64) 
	Jul 27 2015 16:56:19 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)

**Comment by veikkoeeva** [comment]
@BlueTechHound If you use the same connection string as Orleans uses and run
`SELECT QueryKey FROM OrleansQuery;`, do you get 18 keys?

**Comment by BlueTechHound** [comment]
Using the same connection string, I get the following 18 keys

DeleteMembershipTableEntriesKey
DeleteReminderRowKey
DeleteReminderRowsKey
GatewaysQueryKey
InsertMembershipKey
InsertMembershipVersionKey
InsertOrleansStatisticsKey
MembershipReadAllKey
MembershipReadRowKey
ReadRangeRows1Key
ReadRangeRows2Key
ReadReminderRowKey
ReadReminderRowsKey
UpdateIAmAlivetimeKey
UpdateMembershipKey
UpsertReminderRowKey
UpsertReportClientMetricsKey
UpsertSiloMetricsKey

**Comment by veikkoeeva** [comment]
@BlueTechHound I think we're onto something here. In the [latest relational refactoring](https://github.com/dotnet/orleans/commit/2693e5e88afb98b6fb4e84a96c7afe9ffbb06f51#diff-08c9973f4fb0b007702763a9eece2b8dL540) there was a chance from `ActiveGatewaysQueryKey` to `GatewaysQueryKey` and this might be the culprit. It looks like you have the pre-release script deployed and if you Nugets are older, this will certainly fail with the given message.

**Comment by BlueTechHound** [comment]
So would it be safe to just update that one value or should I recreate the DB with the updated script?

**Comment by veikkoeeva** [comment]
@BlueTechHound Good point! There were definitely more changes than that one particular query change, you should redeploy the whole database (don't forget to remove the view too, otherwise the `ALTER DATABASE` call likely hangs). I'm not sure if updating just the SQLUtils Nuget package should work too, since the interface has remained the same (some internal changes and then added `async` definitions).

Sorry if I'm a bit abrupt currently, I'll push kids to bed and then I need to do some housework, but I'm around. :)

**Comment by BlueTechHound** [comment]
No worries, thank you for your time. That change you pointed me to has a ton of errors, will not execute

Msg 156, Level 15, State 1, Line 38
Incorrect syntax near the keyword 'ON'.
Msg 102, Level 15, State 1, Line 78
Incorrect syntax near 'AUTO_INCREMENT'.
Msg 156, Level 15, State 1, Line 95
Incorrect syntax near the keyword 'ON'.
Msg 156, Level 15, State 1, Line 113
Incorrect syntax near the keyword 'ON'.
Msg 102, Level 15, State 1, Line 180
Incorrect syntax near 'DELIMITER'.
Msg 156, Level 15, State 1, Line 183
Incorrect syntax near the keyword 'in'.
Msg 155, Level 15, State 2, Line 195
'INT' is not a recognized CURSOR option.
Msg 195, Level 15, State 10, Line 237
'ROW_COUNT' is not a recognized built-in function name.
Msg 156, Level 15, State 1, Line 242
Incorrect syntax near the keyword 'THEN'.
Msg 102, Level 15, State 1, Line 246
Incorrect syntax near ';'.
Msg 102, Level 15, State 1, Line 248
Incorrect syntax near 'END$$'.

**Comment by veikkoeeva** [comment]
@BlueTechHound From the looks of the keywords, it looks like you accidentally took the MySQL version.

**Comment by BlueTechHound** [comment]
Yep, that would do it. I made the mistake of taking the SQL on the top thinking it was a link to a file. Executed fine, same error


   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.SqlUtils.RelationalStorage.<ExecuteAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.SqlUtils.RelationalStorage.<ReadAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.SqlUtils.RelationalOrleansQueries.<CreateInstance>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.MembershipService.SqlMembershipTable.<InitializeMembershipTable>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClassa.<<QueueTask>b__8>d__c.MoveNext()

**Comment by BlueTechHound** [comment]
I do know that it is absolutely hitting the database, though :)

**Comment by veikkoeeva** [comment]
@BlueTechHound How do you know it hits the database? It's not easy to tell from that fragment what could the problem be. Can you attach a fuller log? If you care to check, you can do something like 

    SELECT * FROM OrleansMembershipVersionTable;
    SELECT * FROM OrleansMembershipTable;

to see if Orleans succeeded first retrieving the queries and then writing to the membership tables.

**Comment by BlueTechHound** [comment]
I know because when I ran it and forgot to create the tables in the database, it told me that the database table did not exist. Ran the script to create the tables, that error went away and got the error we see again. 

Running those select statements returns zero rows. I am attaching the logs that I have

[OrleansStartupError-2016-04-21-19.04.39.128Z.txt](https://github.com/dotnet/orleans/files/230558/OrleansStartupError-2016-04-21-19.04.39.128Z.txt)

**Comment by BlueTechHound** [comment]
The other log
[orleans.txt](https://github.com/dotnet/orleans/files/230563/orleans.txt)

**Comment by BlueTechHound** [comment]
And watching via SQL profiler, I can see the user execute the following statement before it fails. I was hoping to catch it doing a select on a specific key

SELECT QueryKey, QueryText FROM OrleansQuery;

**Comment by veikkoeeva** [comment]
@BlueTechHound From the error message, it looks like it can't find the key. Could there be again a mismatch between the database and code? Looking at https://twitter.com/projectorleans/status/722948734816890880, it also look version 1.2.0 is imminent, so one option could be that you update the Nuget packages and use also the latest script. That way you don't need to update SQL server later again.

**Comment by BlueTechHound** [comment]
It does seem that way, and not sure how that happened. I initially executed the Sql Server script in the master and used the latest version of Orleans from NuGet that is not pre-release (1.13) 

I tried again with a fresh database, executing the script from master (https://raw.githubusercontent.com/dotnet/orleans/master/src/OrleansSQLUtils/CreateOrleansTables_SqlServer.sql) with the same results. I was hoping the use of MS SQL was fairly straight forward. 

When I try to move to the 1.2.0 beta pre-release, a new error that seems unrelated.
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

**Comment by veikkoeeva** [comment]
@BlueTechHound This is just to synchronize minds before I go to bed. If you use the latest non-pre-release Nugets, the correct script is located at `packages\Microsoft.Orleans.OrleansSqlUtils.1.1.3\lib\net451\SQLServer`. This is the Nuget package of the binaries. I tested it by taking the HelloWord sample, modifying its configuration to use SQL Server and adding SQLUtils version 1.1.3 (I left the other packages to version 1.1.0 while I did the test, I see now). If you use the the script from the master and code from a previous version, there can be incompatibility issues.

As for the other error, you might need to open another issue or pop by to the channel to have a chat with someone. If you set `TraceLevel` to `Verbose3` in configuration, you should have information logged in great detail: warning and error messages and consequently information on what it was that couldn't be loaded.

**Comment by sergeybykov** [comment]
@BlueTechHound Were you able to sort this out after all?

**Comment by amccool** [comment]
looks like ActiveGatewaysQueryKey was removed in https://github.com/dotnet/orleans/commit/2693e5e88afb98b6fb4e84a96c7afe9ffbb06f51
from
src/OrleansSQLUtils/CreateOrleansTables_SqlServer.sql

Orleans.SqlUtils.RelationalOrleansQueries.OrleansQueries has 
public readonly string ActiveGatewaysQueryKey;

which is breaking on startup, as that query key no longer exists. 
```
Exc level 1: System.ArgumentException: Not all required queries found. Missing a
re: ActiveGatewaysQueryKey
   at OrleansSQLUtils.Storage.DbStoredQueries..ctor(Dictionary`2 queries)
   at Orleans.SqlUtils.RelationalOrleansQueries.<CreateInstance>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Orleans.Runtime.MembershipService.SqlMembershipTable.<InitializeMembership
Table>d__4.MoveNext()
```

```
            const string orleansQueriesSelectTemplate = "SELECT QueryKey, QueryText FROM OrleansQuery;";
            var orleansQueries = new OrleansQueries();
            var propertiesDictionary = typeof(OrleansQueries).GetFields().ToDictionary(p => p.Name, p => p);
            var populatedKeys = await storage.ReadAsync(orleansQueriesSelectTemplate, _ => { }, (selector, _) =>
            {
                var queryKey = selector.GetValue<string>("QueryKey");
                var queryText = selector.GetValue<string>("QueryText");
                propertiesDictionary[queryKey].SetValue(orleansQueries, queryText);
                return queryKey;
            }).ConfigureAwait(continueOnCapturedContext: false);

            //Check that all the required keys are loaded and throw an exception giving the keys expected but not loaded.
            var missingQueryKeys = populatedKeys.Except(propertiesDictionary.Keys);
            if (missingQueryKeys.Any())
            {
                throw new ArgumentException(string.Format("Not all required queries found when loading from the database. Missing are: {0}", string.Join(",", missingQueryKeys)));
            }
```
