### ISSUE TITLE
How to keep grain alive all the time?

### ISSUE THREAD

**Issue by liuchangtao** [dotnet/orleans#1709]
grain code like this:
class Mygrain : IMygrain,Grain
{
...
private int m_nCounter=0;
public Task< int > getCounter()
{
return Task.FromResult(m_nCounter++);
}
...
}

client code like this:
...
while(true)
{
Console.ReadLine();
var gr = GrainClient.GrainFactory.GetGrain< IMygrain >(0);
int n = gr.getCounter().Result();
Console.writeline("counter = "+n.ToString());
}
....

at first when I press 'Enter' key , it work ok,like follow:
counter = 0
counter= 1
counter= 2

but after a long time about 4 hours or more ,I press 'Enter' key, it restart from 0 not 3, like follow:
counter = 0
counter= 1
counter= 2

I guess the grain is Deactivate after a long time,is there some way to key my grain alway alive with out using GrainState,how about using a heartbeat ?

thank you very much!

**Comment by gabikliot** [comment]
http://dotnet.github.io/orleans/Advanced-Concepts/Activation-Garbage-Collection

**Comment by liuchangtao** [comment]
thank you,it's helpful ~~~

**Comment by gabikliot** [comment]
You are welcome.
