### ISSUE TITLE
Question/Suggestion: Knowing grain de-activation reason?

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1715]
Can a grain tell the reason for its de-activation, e.g. if it's because the silo is shutting down, because he reached age limit or because he asked to be de-activated on idle?

De-activation on idle is simple since the grain asks for it so he can remember a flag that can be inspected during de-activation, but differentiating between age limit and silo shut down is something the application can't tell on its own, correct? 

If I'm correct, what do you think about modifying `OnDeactivateAsync` to receive an enum `DeactivationReason`? I'm aware this is a breaking change, which can be avoided by adding a `DeactivationReason` property to `Grain` instead of passing it as parameter, but I think this is unclean and the breaking change can be very easily detected and fixed by inspecting the compilation error.

**Comment by gabikliot** [comment]
Can you please explain the scenario where this is needed?

**Comment by Eldar1205** [comment]
I have a grain that does periodic background processing that should always be active as long as the silo is active (using `DelayDeactivation` from timer tick), unless it receives a request that asks him to stop processing, which eventually result in de-activation since background processing has stopped. I'd like to tell on de-activation whether it happened because a silo was shutdown or because some bug in the "keep alive" logic that caused the grain to de-activate even though it should continue with the background processing. A de-activation reason that says "age limit" or "shutdown" would allow me to detect when de-activation due to "age limit" when it shouldn't happen and log a warning.

**Comment by ReubenBond** [comment]
Fixed: Orleans now lets you override a variant of `DeactivateOnIdle` which contains a `DeactivationReason` with a code, message, and optional exception describing the reason for deactivation: https://learn.microsoft.com/en-us/dotnet/api/orleans.igrainbase.ondeactivateasync?view=orleans-7.0&devlangs=csharp&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Orleans.IGrainBase.OnDeactivateAsync)%3Bk(SolutionItemsProject)%3Bk(DevLang-csharp)%26rd%3Dtrue
