### ISSUE TITLE
Orleans NuGet packages should no longer use Content Files

### ISSUE THREAD

**Issue by rrector** [dotnet/orleans#1718]
From http://docs.nuget.org/Create/Nuspec-Reference#content-files:

Caution:
 These instructions define a technique used in pre-3.0 versions of NuGet that include files in a package. Newer project systems will not add or manage these files in your project. NuGet recommends the newer contentFiles notation, described below. 

Currently, src\NuGet\Microsoft.Orleans.OrleansCodeGenerator.Build.nuspec uses a Content File to include the blank Properties\Orleans.codegen.cs file into the project. For this use, just setting up the msbuild Item in the custom .targets file should be sufficient.

**Comment by sergeybykov** [comment]
Resolved via https://github.com/dotnet/orleans/pull/1720.
