### ISSUE TITLE
Problem with ClusterConfiguration

### ISSUE THREAD

**Issue by FenrisWolfAtMiddleEarth** [dotnet/orleans#1722]
I am trying to start a silo with a cluster configuration. However it fails with an error I don't understand. Any pointer would be very much appreciated.

The code fails with the error:
{"Method not found: 'Orleans.Runtime.Configuration.NodeConfiguration Orleans.Runtime.Configuration.ClusterConfiguration.GetConfigurationForNode(System.String)'."}

The top of my stack trace is:
   at Orleans.Runtime.Host.SiloHost.SetSiloConfig(ClusterConfiguration config)
   at Orleans.Runtime.Host.SiloHost..ctor(String siloName, ClusterConfiguration config)

            var config = new ClusterConfiguration
            {
                Defaults =
                {
                    HostNameOrIPAddress = "localhost",
                    Port = 22222,
                    ProxyGatewayEndpoint = new IPEndPoint(IPAddress.Loopback, 40000),
                },
                Globals =
                {
                    LivenessType = GlobalConfiguration.LivenessProviderType.SqlServer,
                    DeploymentId = "MySilo",
                    DataConnectionString = "someconnectionstring",
        }
            };

            _siloHost = new SiloHost("MySilo", config);

**Comment by sergeybykov** [comment]
Seems like a version mismatch - assemblies from different versions of NuGet packages got mixed in.
Double-check that all Orleans NuGets are of the same version, clean and rebuild.
Starting with 1.2.0, we are changing assembly versions to make such mismatches more obvious.

**Comment by FenrisWolfAtMiddleEarth** [comment]
Thanks. You are correct. Updating nuget packages solved the problem.
I am puzlled why you need a persistent layer for the cluster configuration (i.e. azure, sql-server or zookeper). I have written a two cluster quorum's during my career. Both worked in memory only, which is a much simpler configuration.
If a persistent layer is needed, it would be helpfull if it could be just a fileshare. But I can see there is an option for custom. So I guess I could write my own.

**Comment by gabikliot** [comment]
You can indeed write your own. See more details of why here:
http://dotnet.github.io/orleans/Runtime-Implementation-Details/Cluster-Management

Shortly, in memory quorum will mean it can't withstand more than half quorum failures. Ours works even if all nodes failed. Plus it solves the initial discovery and obviates reconfiguration.

**Comment by FenrisWolfAtMiddleEarth** [comment]
Yes. You are correct. :-)
The quoroms I wrote will stop at half of the nodes being unavailable.
And they node needed knowledge of other available nodes through configuration.
I like the simpler approach with the simpler setup and configuration though.
Thanks for your explanation.

**Comment by sergeybykov** [comment]
@FenrisWolfAtMiddleEarth 👍
