### ISSUE TITLE
Configuring Reminders with the silo process

### ISSUE THREAD

**Issue by FenrisWolfAtMiddleEarth** [dotnet/orleans#1736]
We have implemented our silohost in a windows service. We have a number of grains, which should run "batch-like". Some with 2-hour interval, some with 24-hour interval and some with monthly interval. We thought a good implementation of that would be as reminders.

We need a place to configure these reminders in Orleans, and we thought a natural place for that is when starting the windows, service which holds the silo. Something like the below.

However, Orleans will not let use GrainClient to get a reference to a grain. And as I understand we need a grain to register a reminder. We get an error "You are running inside the provider code, on the silo. GrainClient.GrainFactory should only be used on the client side. Inside the provider code use GrainFactory that is passed via IProviderRuntime (use providerRuntime.GrainFactory)."

Is there any way to register a grain when starting the silo host process?

            _siloHost = new SiloHost("MySilo", ClusterConfiguration.LocalhostPrimarySilo());
            _siloHost.InitializeOrleansSilo();
            _siloHost.StartOrleansSilo();

            GrainClient.GrainFactory.GetGrain<IMyBatchGrain>("MyBatchGrain").Register();

**Comment by gabikliot** [comment]
You should write this code inside bootstrap provider.

Your other option is to create a grain client inside a separate app domain, or even process. But it cannot be in the same memory domain with the silo and not inside provider or grain.

**Comment by sergeybykov** [comment]
>We need a place to configure these reminders in Orleans, and we thought a natural place for that is when starting the windows, service which holds the silo. Something like the below.

If those reminders need to be registered once, then trying to do the same upon each restart of each node seems excessive to me. Reminders survive restarts and redeployments of a service. I think it would be more logical to execute an explicit 'configuration' task once right after a first deployment via a separate process or something, and not deal with that after.

**Comment by FenrisWolfAtMiddleEarth** [comment]
Thanks
Bootstrapprovider seems to do the job nicely for us.
We understand your suggestion about an explicit configuration task which just runs once. however that just complicates spinning up a fresh system on a phoenix server. (We do that for automated integration tests etc.)
Hopefully silo nodes are rarely restarted, so re-registering at those rare occasions should not be a problem.
