### ISSUE TITLE
Stack trace in exceptions

### ISSUE THREAD

**Issue by FenrisWolfAtMiddleEarth** [dotnet/orleans#1739]
One of the major advantages Orleans has over the Akka framework, is the propagation of exceptions through the Task object. It makes a huge difference when developers do not have to write extra code in every subgrain / subactor to pass exceptions back to a calling grain, And the calling grain / actor also needs code to test on any return-code / return-exception.
However, I just saw my first exception in a grain today. I may be doing something wrong, but in this exception, the original stack trace was not present. I had hoped it would be passed back as well. Perhaps through the Inner Exception object. It is not very helpful to just know that somewhere in what could be a deep hierarchy of grains, a null exception occurred.
Is there a recommended pattern for handling this?

**Comment by sergeybykov** [comment]
We should be serializing and passing the original exception intact. Can you create a simple repro unit test?

**Comment by FenrisWolfAtMiddleEarth** [comment]
That is good to hear. Then it is just me doing something wrong. In my project the exception logged has no information about RepositoryFailing:

    public class MasterGrain : Grain, IMasterGrain
    {
        public async Task DoWork()
        {
            try
            {
                var worker = GrainFactory.GetGrain<IRepositoryFailing>(0);
                var result = await worker.DoFail();
            }
            catch (Exception ex)
            {
                GetLogger().Error(0, "Error", ex);
            }
        }
    }

    public interface IMasterGrain : IGrainWithIntegerKey
    {
        Task DoWork();
    }
}

    public class RepositoryFailing : Grain, IRepositoryFailing
    {
        public Task<string> DoFail()
        {
            return Task.Run(() =>
            {
                var emptyList = new List<string>();
                return emptyList.Single();
            });
        }
    }

    public interface IRepositoryFailing : IGrainWithIntegerKey
    {
        Task<string> DoFail();
    }

**Comment by sergeybykov** [comment]
`Task.Run()` is likely the culprit. Take a look at http://dotnet.github.io/orleans/Advanced-Concepts/External-Tasks-and-Grains for details on how to use external tasks. It's unclear from the example why you needed `Task.Run()` in the first place. If you indeed do need to start a separate task, use `Task.Factory.StartNew()` instead.

**Comment by FenrisWolfAtMiddleEarth** [comment]
Thanks. I was not aware of the difference between Task.Run and Task.Factory.StartNew. But that is definiately something to consider. Hwoever the problem remains, even if I just use Task.FromResult like this:

    public class RepositoryFailing : Grain, IRepositoryFailing
    {
        public Task<string> DoFail()
        {
            var emptyList = new List<string>();
            return Task.FromResult(emptyList.Single());
        }
    }

    public interface IRepositoryFailing : IGrainWithIntegerKey
    {
        Task<string> DoFail();
    }

I still get a stacktrace like this:

Sequence contains no elements
Exception = System.InvalidOperationException: Sequence contains no elements
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.GrainReference.<InvokeMethodAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Db.Cards.IsicGrains.MasterGrain.<DoWork>d__0.MoveNext() in C:\TFS\CardSystems\Source\CoreFunctionality\CardsSilo\IsicGrains\MasterGrain.cs:line 14

**Comment by jdom** [comment]
Hi @FenrisWolfAtMiddleEarth. Unfortunately at some point when we improved exception propagation (#1378 and several others) to not mess with aggregate exceptions and so on, I think we broke propagating the original stacktrace.
I have a few ideas in mind on how to fix it (basically propagate an intact aggregate exception, and just unwrap it before throwing it for the caller to catch). If you want to give a shot at a PR to solve this, you are most welcome, otherwise I or someone in the community will pick it up. Hopefully it's not an urgent blocking issue, just makes troubleshooting a little bit harder.

**Comment by abatishchev** [comment]
@sergeybykov hi, actually other way around, one indeed should use Task.Run() over Task.Factory.StartNew(). See:
- http://blogs.msdn.com/b/pfxteam/archive/2011/10/24/10229468.aspx
- http://stackoverflow.com/a/29693430/41956
- http://blog.stephencleary.com/2013/08/startnew-is-dangerous.html

**Comment by jdom** [comment]
BTW, we merged a fix for the broken stack trace with #1808

**Comment by sergeybykov** [comment]
The fix is in the 1.2.2 NuGet release.

**Comment by FenrisWolfAtMiddleEarth** [comment]
Seems to work fine now.
Thanks

**Comment by FenrisWolfAtMiddleEarth** [comment]
It looks like this continues to be a problem. Also in version 1.2.2
I can reproduce with the very same repro-solution, which I sent you.

**Comment by jdom** [comment]
Yeah, unfortunately this preserved the stacktrace but as soon as you await the call (which rethrows the exception), the stacktrace is wiped. 
Fixed in #1879

**Comment by sergeybykov** [comment]
Fixed via https://github.com/dotnet/orleans/pull/1879.
