### ISSUE TITLE
Question: Delivery ordering of notification by using ClientObserver

### ISSUE THREAD

**Issue by leimou** [dotnet/orleans#1743]
Hello, 

I'm writing to ask whether notification is delivered in FIFO order by using ClientObserver. To be specific, we are using GameLobby (`IGameLobby)` grain to represent a single game lobby and ServerSession (`IServerSession`) grain to represent an available game session. When there are enough people are collected in a game lobby, we'll allocate a game session and prepare to start the game. The allocated game session needs to be initialized with several commands. The code looks like this:

```csharp
public async Task AllocateSession()
{
    if (m_serverSession == null && m_sessionData == null)
    {
         var sessionMgr = GrainFactory.GetGrain<ISessionManager>(0);
         m_serverSession = await sessionMgr.AllocateSession(this);
         m_sessionData = await m_serverSession.AssignGameLobby(this.GetPrimaryKeyLong());

         // Sending GameRule command
         var gameRuleMsg = MessageFactory.CreateGameRuleCmd(m_gameMode);
         PushServerSession(m_serverSession.GetPrimaryKeyLong(), gameRuleMsg);

         // Sending Map command
         var loadMapMsg = MessageFactory.CreateLoadMapCmd(m_mapVoted);
         PushServerSession(m_serverSession.GetPrimaryKeyLong(), loadMapMsg);
    }
}

private void PushServerSession(long sessionId, FP.Notification message)
{
    var sessionGrain = GrainFactory.GetGrain<IServerSession>(sessionId) as IAddressable;
    var observerRef = sessionGrain.AsReference<INotificationObserver>();
    observerRef.OnNotification(message);
}

public interface INotificationObserver : IGrainObserver
{
    void OnNotification(FP.Notification message);
}
```
We are expecting that "GameRule" command should arrive before "Map" command, for most cases, it is. However, there are cases that "Map" command arrive before "GameRule" command, which breaks our assumption and cause problems. 

So my questions are:

1. Is this the right way to use client observers?
2. Is notification guaranteed to be delivered and received in FIFO order? If not, what about streams?
3. As you may notice, we are using a single manager grain for managing a great number of session state, which should be avoided according to Orleans Best Practices. For this kind of management/aggregation tasks, what's the recommended approach in Orleans context?

Thanks in advance.
Lei Mou

**Comment by sergeybykov** [comment]
From the code, it looks like you are using an observer interface to notify a session grain. There is not need to use observers for that. You can instead add a `Task OnNotification(FP.Notification message);` to `IServerSession`, and await the call to guarantee FIFO ordering.

Client observers are for sending one-way, potentially unreliable, messages to clients, usually frontends.
>As you may notice, we are using a single manager grain for managing a great number of session state, which should be avoided according to Orleans Best Practices. For this kind of management/aggregation tasks, what's the recommended approach in Orleans context?

One popular pattern is to partition the single session manager grain into a larger number of such grains, e.g. 100, and pick one of them for each allocation request, randomly or in a round-robin fashion. Of course, this is easy to do if the manager grains don't require significant coordination between them.

**Comment by leimou** [comment]
> From the code, it looks like you are using an observer interface to notify a session grain. There is > not need to use observers for that. You can instead add a Task OnNotification(FP.Notification
> message); to IServerSession, and await the call to guarantee FIFO ordering.

> Client observers are for sending one-way, potentially unreliable, messages to clients, usually
> frontends.

Thanks, in this case it seems Client observers doesn't fit our needs, since `IServerSession` still needs to pass the issued commands in order, to frontends (and frontends will send the commands to actual game server process via TCP channel), and we don't want to miss any of them, or receive them in wrong order. In this case, shall we use Stream instead, for example, SMS stream?

I tried to find some clues in the code base, but I didn't succeed in finding out how exactly messages sent by client observer is dealt with (e.g, why we received commands in wrong order). Any pointer/hints are greatly appreciated.

> One popular pattern is to partition the single session manager grain into a larger number of such > grains, e.g. 100, and pick one of them for each allocation request, randomly or in a round-robin
> fashion. Of course, this is easy to do if the manager grains don't require significant coordination
> between them.

This would be a straight forward solution if there is no coordination. But what if we want to balance the number of sessions each manager grain manages? (Sessions needs to register themselves in session manager, and it will terminate and restart on demand) In this case, I don't have a better idea instead of introduce yet another "manager" grain, which manage the state of each SessionManager (How many sessions it manages), however it actually repeats the problem instead of solving it... Is there any suggestions regarding to this? 

Thanks!
Lei Mou

**Comment by sergeybykov** [comment]
>In this case, shall we use Stream instead, for example, SMS stream?

Yes, SMS streams are a reliable alternative where you can easily guarantee ordering by awating publishing of events.

>I tried to find some clues in the code base, but I didn't succeed in finding out how exactly messages sent by client observer is dealt with (e.g, why we received commands in wrong order). Any pointer/hints are greatly appreciated.

They are delivered like all other messages, only with a special one-way flag - https://github.com/dotnet/orleans/blob/master/src/Orleans/Messaging/Message.cs#L101.

>This would be a straight forward solution if there is no coordination. But what if we want to balance the number of sessions each manager grain manages? (Sessions needs to register themselves in session manager, and it will terminate and restart on demand) In this case, I don't have a better idea instead of introduce yet another "manager" grain, which manage the state of each SessionManager (How many sessions it manages), however it actually repeats the problem instead of solving it... Is there any suggestions regarding to this?

Hard to speak in general terms, but if you can decouple handling of hot paths from non-hot paths, you can still achieve better throughput and scalability. E.g., if each of the sessions manager grains syncs with the global coordinator only once every few seconds (by timer). Or if the global coordinator periodically balances some resources across session managers. Sessions managers would be on the hot path of allocating sessions, but the global coordinator wouldn't be. I'm hand-waving because I don't know the exact requirements.

**Comment by leimou** [comment]
@sergeybykov Thanks a lot for all these information, I'll try to do more experiments and testing and see the results. :-)
