### ISSUE TITLE
Deserialization of types defined in assemblies that aren't loaded by silo

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#1753]
https://github.com/dotnet/orleans/issues/1536 appear to point to a subtle issue with how we serialize types. We only include the type name but not the assembly name. When the target assembly is already loaded into the silo app domain, there is no problem. However, as @bwanner and I investigated in https://github.com/dotnet/orleans/issues/1536, if the assembly isn't yet loaded, resolution of the type fails during deserialization.

A straightforward solution would be to pass fully qualified names, including assembly name, of all types. That would make us send lots of extraneous data as most assemblies, system and app ones, will always be loaded. We could try to be starter, and dynamically decide, based on whether the type is defined in a system assembly or an assembly that references Orleans.dll, and only include assembly names for those that are neither. Seems doable but error prone to me.

`[KnownType]` and `[KnownAssembly]` are workarounds, but they are non-obvious for the cases that sometimes work and sometimes don't, like in https://github.com/dotnet/orleans/issues/1536. Unit testing with `[KnownType]` and `[KnownAssembly]` is also problematic because we start silos in app domain different from the unit test code.

**Comment by ReubenBond** [comment]
This is supported in Orleans 7.x to the degree that it is supported by modern .NET
