### ISSUE TITLE
internal OrleansJsonSerializer

### ISSUE THREAD

**Issue by dsarfati** [dotnet/orleans#1754]
[OrleansJsonSerializer](https://github.com/dotnet/orleans/blob/cc90465640710d82b2fc40bc9749af992faf41cf/src/Orleans/Serialization/OrleansJsonSerializer.cs)  is internal, is any reason not to expose this as public in case others need to use it as the default serializer?

**Comment by sergeybykov** [comment]
It's just a wrapper over Newtonsoft.Json with a set of converters. How would somebody use is as the default serializer? I'm not against exposing it as public, just not sure what you'd gain by that?

**Comment by dsarfati** [comment]
I had started down the path of building my own version of the Newtonsoft.Json wrapper as an alternative to other external serializes (protobuf...) and then stumbled across this. The Json converters for grain ids and such seem like they could be useful for others.

**Comment by sergeybykov** [comment]
Then I see no reason to keep it internal.

**Comment by gabikliot** [comment]
Hmmmmm, ..... hmmmm ....

https://github.com/dotnet/orleans/pull/1204

The need to make it public was raised in December in #1204. 
Of course, once you make it public, it **can** be mutated by the application (even if not supposed to), so the need to deal with that and how/if to make it settable is back as well, even if we tried to bury our head in the sand back then.

**Comment by sergeybykov** [comment]
@gabikliot I'm a bit confused. https://github.com/dotnet/orleans/pull/1204 was about making static `OrleansJsonSerializer.JsonSerializerSettings` public while here it's about `OrleansJsonSerializer` class. What am I not seeing?

**Comment by gabikliot** [comment]
Making `OrleansJsonSerializer` public will not be enough. For that particular ask for that particular  user maybe it will be, but someone else will not want to use our full `OrleansJsonSerializer` which is coupled with our `BinaryTokenStreamReader `, and will instead want to serialize by himself (for example, in persistent provider case).
What they both will need is to be able to Json-serialixe our **internal types**. For that that need access to converters. 

There are multiple ways to solve that whole "bag of issues related to Json" and I outlined some approaches in https://github.com/dotnet/orleans/pull/1485#issuecomment-186749232, later re-summarized in https://github.com/dotnet/orleans/issues/1495.

>What am I not seeing?

The bigger picture, unfortunately.

**Comment by ReubenBond** [comment]
OrleansJsonSerializer is no longer internal
