### ISSUE TITLE
Reminder is not being triggered

### ISSUE THREAD

**Issue by FenrisWolfAtMiddleEarth** [dotnet/orleans#1774]
For some reasone our reminder is not being triggered.
We are using SQL-server for storage, and I can see the reminder is in the table [OrleansRemindersTable], and if the period is in milleseconds, it should be fired every 10 minutes.

ServiceId: 00000000-0000-0000-0000-000000000000
GrainId: GrainReference=000000000000000000000000000000000600000061677e62+IsicExpiry
ReminderName: IsicExpiringCardsPoll
Period: 600000
GrainHash: 1760969935
Version: 68
StartTime: 2016-05-18 07:36:05.173

I have also attached the Orleans log, if that is any help.
[WX1601-2016-05-18-09.41.32.764Z.txt](https://github.com/dotnet/orleans/files/270265/WX1601-2016-05-18-09.41.32.764Z.txt)

**Comment by veikkoeeva** [comment]
@FenrisWolfAtMiddleEarth Which version of the code you are running? Latest master or some Nuget version? You might want to increase the tracing level to `Verbose3`. Maybe also mask the client name if it not otherwise public. :)

**Comment by FenrisWolfAtMiddleEarth** [comment]
Thanks for your suggestions.
I'm afraid I have to disappoint you though. We are just using "some" NuGet version. As you can see from the logs, we are using latest stable. 1.2.0

runtime Version='1.2.0.0 (Release)

I have tried increasing trace-leve to Verbose3 as you suggested. It revealed some loggings, which looks suspicous. At least with my untrained eye.
[Verbose3Log.txt](https://github.com/dotnet/orleans/files/271047/Verbose3Log.txt)

**Comment by FenrisWolfAtMiddleEarth** [comment]
Using the above verbos3 loggings, I found this issue.
I guess this fix is not included in latest stable nuget package (i.e. 1.2.0)
https://github.com/dotnet/orleans/issues/1746

**Comment by veikkoeeva** [comment]
@FenrisWolfAtMiddleEarth Does [this](https://gitter.im/dotnet/orleans?at=573cc1fd1effc6fe3f3fb7d7) help? It looks like the new Nugets are in. :)

**Comment by FenrisWolfAtMiddleEarth** [comment]
Yes, thank you for that.
I saw you released v1.2.1 this evening. After upgrading, I can confirm that the problem is solved.
:-)
