### ISSUE TITLE
Initialize GrainClient and Silo in the same process.

### ISSUE THREAD

**Issue by lyjdamzwf** [dotnet/orleans#1780]
Hi guys:
For some reasons, I need to get a Grain out of a Grain context but in the Silo process.
So I try to initialize a GrainClient, but it raised a exception below:

> 127.0.0.1:12111]        OutsideRuntimeClient.ConstructorReset(): client Id *cli/
> 74c55794
> Initialization failed. Calling SetUnobservedExceptionHandler the second time.

I tracked the code it caused of the Silo has invoked the SetUnobservedExceptionHandler so the initialization of GrainClient failed.

How can I fix the problem?

Plus, my requirement is when the process receives the shutdown signal, the silo process should notify all users (Grains) offline which are active, but I couldn't get a Grain/StreamProvider in the shutdown callback, so are there any other ways to solve the problem?

**Comment by sergeybykov** [comment]
`GrainClient` has to be in a separate app domain or process from a silo. Currently, they cannot coexist.

>Plus, my requirement is when the process receives the shutdown signal, the silo process should notify all users (Grains) offline which are active, but I couldn't get a Grain/StreamProvider in the shutdown callback, so are there any other ways to solve the problem?

Your process shutdown callback needs simply needs to call `Silo.Shutdown()`. This will trigger a graceful shutdown of the silo, as part of which each activated grain will get deactivated, and its `OnDeactivateAsync()` method will get called.

Do you need something different?

**Comment by lyjdamzwf** [comment]
@sergeybykov Actually, I want a proprocessing before Silo.Shutdown, like notify some messages to  All Grains (simply say is broadcasting in a normal method), and this broadcasting logic codes can't be put in the Grain.OnDeactivateAsync(), since the Silo is shuttting down, some other grains may be already OnDeactivateAsync so that I couldn't use it.

That's all, have I explained clearly? :)

**Comment by sergeybykov** [comment]
@lyjdamzwf Sorry about missing your comment. This isn't supported today. There is no way to send messages from the same app domain with a silo. As a workaround, you could initialize a client in a separate app domain, and signal it to send messages upon a shutdown.

**Comment by shlomiw** [comment]
I also have a scenario when I want to subscribe to events (Orleans Streams) in a common code for both Orleans Clients and Orleans Silos.

i.e. - I have a common Cache manager (not Grain), which is used in all my processes, both clients and silos. I'd like it to be able to subscribe to 'clear' event via Orleans Stream. 
If GrainClient could co-exist in the same process, it would simply solve my issue.

**Comment by DixonDs** [comment]
@shlomiw You can try to inject and use `Orleans.Streams.IStreamProviderManager` in your common code

**Comment by shlomiw** [comment]
@DixonDs - thanks for the quick reply! 
I'm reading now about Application Bootstrapping within a Silo (thanks to @richorama in gitter):
https://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Application-Bootstrap-within-a-Silo.html

Via the bootstrap I can inject it?

**Comment by DixonDs** [comment]
@shlomiw In `Init` method, you have `IProviderRuntime providerRuntime` so that you can use `providerRuntime.ServiceProvider` to get the service provider from which you can try to get `IStreamProviderManager`

**Comment by shlomiw** [comment]
Just found #2236 , looks the same as what I want :) Thanks, I'll try

**Comment by richorama** [comment]
@DixonDs I don't _think_ that will work. You'll need to use the provider runtime to activate a grain, and subscribe to a stream from there. A bootstrap provider is not addressable, and therefore can't be a streaming endpoint.

**Comment by shlomiw** [comment]
@DixonDs / @richorama - got the following exception inside the BootstrapProvider:

```
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Trying to get a Stream or send a stream message on a silo not from within grain and not from within system target (CurrentActivationData is null) RuntimeContext.Current=RuntimeContext: ActivationContext=[SystemTarget: S127.0.0.1:11111:230742630ProviderManagerSystemTarget@S00000013], Scheduler=ActivationTaskScheduler-13:Queued=0 TaskScheduler.Current=ActivationTaskScheduler-13:Queued=0
```

I'll try to create a kind of utility Grain and subscribe from there.
