### ISSUE TITLE
Get fault & upgrade domain from the management grain

### ISSUE THREAD

**Issue by richorama** [dotnet/orleans#1789]
Perhaps this is too much of an edge case, but I'd like to get the values  for `FaultZone` and `UpdateZone` on [`MembershipEntry`](https://github.com/dotnet/orleans/blob/82a1e9f7096950d462eb19ff226f128cd570e2c8/src/Orleans/SystemTargetInterfaces/IMembershipTable.cs#L235) for each silo (as well as `Status`). Preferably from the management grain.

This would allow some kind of [web based dashboard](https://github.com/orleanscontrib/orleansdashboard) to show a nice 'cluster map' of where each silo is located.
 
... a bit like service fabric does 

![](https://acom.azurecomcdn.net/80C57D/cdn/mediahandler/docarticles/dpsmedia-prod/azure.microsoft.com/en-us/documentation/articles/service-fabric-visualizing-your-cluster/20160415071221/sfxclustermap.png)

https://azure.microsoft.com/en-gb/documentation/articles/service-fabric-visualizing-your-cluster/

Happy to do the work...

**Comment by sergeybykov** [comment]
That would be neat.

**Comment by gabikliot** [comment]
@richorama , great idea!
Would it just be enough to add a call to `IManagementGrain`: `Task<List<MembershipEntry>> GetDetailedHosts()`?
`MembershipEntry` is already public.

**Comment by richorama** [comment]
@gabikliot I'll do that. Thanks.

**Comment by richorama** [comment]
closed by #1794
