### ISSUE TITLE
SqlException when attempting to insert row into membership table

### ISSUE THREAD

**Issue by Kwal** [dotnet/orleans#1798]
<img width="1320" alt="screen shot 2016-05-29 at 4 32 18 pm" src="https://cloud.githubusercontent.com/assets/600568/15636145/45b97b8a-25bb-11e6-9641-5656af45acfc.png">

I used the latest SQL script file within the OrleansSQLUtils project.

**Comment by gabikliot** [comment]
You need to run the script that matches the code. If you are using code from nuget, you should use the script from there as well. If latest code from master, then also latest script from master.

**Comment by Kwal** [comment]
![facepalm](https://cloud.githubusercontent.com/assets/600568/15638651/fa331540-25e7-11e6-9817-d65d10b91e9f.jpg)

Apologies - totally missed #1787 - thanks!
