### ISSUE TITLE
No gateways available

### ISSUE THREAD

**Issue by creatworld** [dotnet/orleans#1807]
After primary node restart，client will throw some exception like "No gateways available"，when call grain.

**Comment by gabikliot** [comment]
In dev setup you should not restart primary. It won't work.
In real prod setup there are no primaries, all silos are secondaries, andoof course restarting them (all at once or one by one) is 100% supported.

**Comment by gabikliot** [comment]
http://dotnet.github.io/orleans/Orleans-Configuration-Guide/Server-Configuration
