### ISSUE TITLE
Nugets place c# files in vb project.

### ISSUE THREAD

**Issue by BenjaminGibbs** [dotnet/orleans#181]
When adding a VS template nugets in to a VB project, it is adding the c# codegen file and not the VB one, when you compile it gives an error as the VB one does not exist..

Easy fix to work around just to add the file, but a bug none the less.

**Comment by ReubenBond** [comment]
I guess this is resolved by #528. VB Projects should not reference the Templates packages. Can we force them not to?

**Comment by sergeybykov** [comment]
So we need to change `OrleansVSTools` to remove VB and F# project templates?

**Comment by gabikliot** [comment]
@BenjaminGibbs , is this still an open issue?

**Comment by sergeybykov** [comment]
Resolved via https://github.com/dotnet/orleans/pull/1634.
