### ISSUE TITLE
Runtime-Tables.md is highly out of sync

### ISSUE THREAD

**Issue by shayhatsor** [dotnet/orleans#1810]
In reaction to #1740 and my continued work on improving the documentation (#1264) I've stumbled upon [Runtime-Tables.md](http://dotnet.github.io/orleans/Documentation/Runtime-Implementation-Details/Runtime-Tables.html) file.The entire file has broken links and is basically an old documentation of Azure runtime tables.
I'm not exactly sure what's the purpose of this help file, we can just move that documentation to the code (which already includes most of it).

**Comment by gabikliot** [comment]
I added this page by request from @veikkoeeva , when he just started looking at a SQL store, quite a long time ago.
I am totally fine with either removing it completely and leaving the code to speak for itself, or updating it to reflect the latest reality.

**Comment by veikkoeeva** [comment]
And it was a welcomed addition. :)

**Comment by shayhatsor** [comment]
@veikkoeeva, would you mind if I move this documentation to the code and link to it where needed ?

**Comment by veikkoeeva** [comment]
@shayhatsor Go ahead. I was wondering that I could move the SQL rationale explanations to some place if you something in your mind. I'm sure I can do that quickly as it looks like I've written it plenty of times already.

**Comment by shayhatsor** [comment]
@veikkoeeva, I didn't forget you 😉 If you can create a page explaining the design rationale, I'll link it in the advanced concepts section and also in other pages talking about relational storage. Like you said, you've already wrote it many times, we just need to revise and review.

**Comment by veikkoeeva** [comment]
@shayhatsor Sure, I will. :)

**Comment by sergeybykov** [comment]
@shayhatsor, do you think we still need to do something with this page? I fixed the link above.

**Comment by shayhatsor** [comment]
This article was supposed to be about providing a description of the Orlean runtime tables, which was right when there was only Azure in the membership mix. Now it doesn't reflect reality since concrete membership implementations differ from one another. I suggest that we rename this page to 'Azure Runtime Tables` for now. In the future, if some brave soul decides to generalize this page - that's better.

**Comment by sergeybykov** [comment]
Resolved via #2573.
