### ISSUE TITLE
Silo Proxy IP isn't communicated to clients

### ISSUE THREAD

**Issue by shayhatsor** [dotnet/orleans#1812]
this is a bug found in #1136. The bug occurs in all systems stores, I've opened this to close the other.

**Comment by gabikliot** [comment]
This is not a bug, but a limitation in the current implementation ("a feature"). We simply don't allow to specify different IP for inter-silo communication and silo to client communication.

**Comment by shayhatsor** [comment]
@gabikliot, i might be wrong, but doesn't [this](https://github.com/dotnet/orleans/blob/master/src/Orleans/Configuration/NodeConfiguration.cs#L408) allow the user to configure a separate IP for silo proxy?

**Comment by gabikliot** [comment]
You are right. It IS a bug. We do allow to specify IP but don't write it in the membership table.

**Comment by aprooks** [comment]
@sergeybykov I believe this one should be closed as fixed
