### ISSUE TITLE
Concept for long running grains

### ISSUE THREAD

**Issue by FenrisWolfAtMiddleEarth** [dotnet/orleans#1814]
What is the good design for a long running grain?
We need to have a thread permanently reading on a Websphere MessageQueue. It will read messages, which will then be passed on to business logic contained in grains.
Is there any good way to implement the read on Websphere MessageQueue as a grain?
Or should that be implemented outside of our silo as an Orleans Client?

**Comment by shayhatsor** [comment]
you may find this http://dotnet.github.io/orleans/Orleans-Streams/ helpful.

**Comment by FenrisWolfAtMiddleEarth** [comment]
Thanks Shay
Yes. I understand the concept of streams. My problem is that the "event" is on a Websphere MessageQueue. In order to read the "event" from Websphere MQ and add that as a stream or similiar in Orleans, I don't see any way around having a thread reading Websphere MQ constantly.
However I am unsure if there is any good way of implementing such a thread which never stops within the silo. Or should that be implemented outside of the silo as an Orleans client?

**Comment by RaringCoder** [comment]
@FenrisWolfAtMiddleEarth  Do you need something that long polls? Reminders might be useful for this.

**Comment by shayhatsor** [comment]
@FenrisWolfAtMiddleEarth, it's important to note that a grain method can run forever. The time limitation is only on the task that's waiting for the call to be completed. So let's say you have a grain that reads from the queue: `WebSphereQueueGrain`, and it has methods : `Task Init()` , `Task Start()` and `Task Stop()`. also it should have the `[Reentrant]` attribute, i'll explain later why.
Now, `Task Init()` has some code that connects to the queue and throws if it has failed.
your silo bootstrap code might be:
```csharp
var webSphereQueueGrain = providerRuntime.GrainFactory.GetGrain<<IWebSphereQueueGrain>(0);
await webSphereQueueGrain.Init();
webSphereQueueGrain.Start().Ignore();
```
and your silo shutdown code:
```csharp
var webSphereQueueGrain = providerRuntime.GrainFactory<IWebSphereQueueGrain>(0);
await webSphereQueueGrain.Stop(); //this is possible because the grain is reentrant
```
`Task Stop()` will be similar to:
```csharp
_stopped = true;
await DisconnectFromQueue();
```
and `Task Init()`:
```csharp
await ConnectToQueue();
_stopped = false;
```
`Task Start()` will be similar to:
```csharp
while(_stopped == false)
{
   var item = await Dequeue();
   GrainFactory.GetGrain<IProcessorGrain>().Process(item).Ignore();
}
```

**Comment by mtdaniels** [comment]
@shayhatsor - if no items are dequeued for a bit of time, what prevents the grain from being deactivated?

**Comment by shayhatsor** [comment]
@mtdaniels, it might get deactivated, but the task that's running the `Start()` method will continue running and reactivate the grain when needed.

**Comment by mtdaniels** [comment]
@shayhatsor - It seems like the goal is to start polling on the grain, and expect that it continues until it is explicitly stopped.  If that's the case, then my thinking is a Reminder would guarantee reactivation (until Stop is called, at which point you'd cancel the Reminder).

Is that reasonable?

**Comment by shayhatsor** [comment]
@mtdaniels and @FenrisWolfAtMiddleEarth, I've updated the [previous comment](https://github.com/dotnet/orleans/issues/1814#issuecomment-224292047).

**Comment by shayhatsor** [comment]
@mtdaniels, a reminder doesn't solve the problem of having some downtime till the queue wakes up again. In situations where the grain wishes to not be deactivated for a timespan, the grain can call `DelayDeactivation(timespan)`

**Comment by jason-bragg** [comment]
We have the same queue reading need in the streaming infrastructure.  The way we handled it there is very much like what @shayhatsor has suggested.

-Create reentrant grain, grain with Start and Stop calls.  I suggest reading up on reentrant grains to avoid bugs.
-On Start, call DelayDeactivation, and create a timer that calls a queue message read loop which reads+delivers messages until the grain is explicitly shutdown (via Stop()), or until there are no more messages to read.  The read loop is run again, by the timer the next timer tick.  This prevents free-spin when no data is available.  The read timer, in our case is set to something like 100ms, so the read loop will never shutdown on busy queue, but only checks for messages 10 times a second on idle queues.  -On Stop, break out of read loop, remove the timer, and call DeactivateOnIdle to trigger grain deactivation.

**Comment by gabikliot** [comment]
Alternatively, you can create a new Stream Provider, by writing a Queue Adapter for Websphere MessageQueue. That way all the polling from the queues will be done by the streaming infrastructure.

Do you expect to have a relatively small number of physical queues (10s-100s) which contain messages to a large (1000s up to millions) number of grains? If yes, then streaming might be a better solution.

**Comment by FenrisWolfAtMiddleEarth** [comment]
Thanks very much for everyone's input.
In my understanding Shay's suggestion makes perfect sense, and I cannot see why it should not work.

**Comment by FenrisWolfAtMiddleEarth** [comment]
And just as I wrote my closing comment, gabikliot wrote another suggestion.
Yes, writing a stream provider seems like a more correct usage. (And that was propably also Shay's original suggestion... Apologies for not fully understanding your reply Shay)
Thanks. We will definately be looking in to a stream provider.

**Comment by SidelnikovDmitriy** [comment]
Hi, @FenrisWolfAtMiddleEarth !
Could you solve this problem?
I have a similar task, have you found any ready-made solutions for streaming processing?
