### ISSUE TITLE
Is there any concept of Silo 'Roles'?

### ISSUE THREAD

**Issue by mtdaniels** [dotnet/orleans#1815]
Long story short, I'm researching distribution solutions to retrofit an existing project.  Akka.Net is predictably one of the other options.  Akka.Cluster offers the concept of a role, which allows separation of responsibilities among nodes in the cluster.  Is there anything comparable in Orleans?

My suspicion is that the answer is no, and the only way to achieve such separation is with multiple clusters.

**Comment by shayhatsor** [comment]
@mtdaniels, I've read a bit about Akka.Cluster roles. I believe Orleans can answer that requirement with a custom `PlacementStrategy`. this is being discussed in #1806.

**Comment by mtdaniels** [comment]
Fair enough.  Thanks!
