### ISSUE TITLE
Use Registered IO + IOCP

### ISSUE THREAD

**Issue by jthelin** [dotnet/orleans#1817]
Do any .NET / Windows networking experts have any opinions on whether this type of change would benefit Orleans too? 

https://github.com/Microsoft/Mobius/issues/456

The empirical test results in the above link look quite compelling:

> the speed of JVM receiver [using RIO] is about 4 times of the speed of .NET receiver.

**Comment by jthelin** [comment]
More background info (for reference)

http://www.serverframework.com/asynchronousevents/2011/10/windows-8-registered-io-networking-extensions.html

http://www.serverframework.com/asynchronousevents/2011/10/windows-8-registered-io-and-io-completion-ports.html

**Comment by veikkoeeva** [comment]
@jthelin I would say so, RIO and other things discussed quite extensively at https://github.com/dotnet/orleans/issues/307. I think Orleans is prototyping with [DotNetty](https://github.com/Azure/DotNetty) currently.

**Comment by ReubenBond** [comment]
I believe this is no longer as relevant, so I will close it. This may be more suitable to the dotnet/runtime repository, in the Socket stack, which is what Orleans uses for networking. Everyone is welcome to open a new issue, referencing this one, to start a new discussion if desired.
