### ISSUE TITLE
Orleans Code Generator NuGet

### ISSUE THREAD

**Issue by kaithao** [dotnet/orleans#183]
I'm working on converting our current Orleans project over to using all NuGet packages.  The one issue I'm running into is that my project is still pointing to OrleansSDK which is pointing to the SDK directory for which I've installed Orleans.

Should I continue working off of the SDK directory and not use the Code Generator NuGet package for this or is there a setup process that I should be following to get this working that I've missed?

**Comment by jthelin** [comment]
PR #124 should provide a helpful comparison for this type of project conversion to NuGet -- particularly the changes in HelloWorld-NuGet to HelloWorldInterfaces.csproj and HelloWorldGrains.csproj
https://github.com/jorvik/orleans/commit/35d2aea4914bc7cc4f73eef4a18d3e8adf094694

**Comment by jkamstra** [comment]
PR #124 would have been nice to have as a reference if someone was pursuing a Azure based CI/CD setup with VSO. Unless there is some way to get the Orleans SDK installed on Azure build systems.

**Comment by sergeybykov** [comment]
We do not want to require Orleans SDK installed on a build machine. Orleans-based projects need to build on a vanilla build machine/agent. I'm pretty sure of that having tried to build the VSIX as part of our TFS/VSO build recently. :-)

**Comment by sergeybykov** [comment]
This should be all fixed/Improved in https://github.com/dotnet/orleans/releases/tag/v1.0.5. Just add Microsoft.Orleans.Templates.Interfaces or Microsoft.Orleans.Templates.Grains to your grain interfaces or grain implementation project respectively. VSIX should do the same. No dependency on %OrleansSDK% anymore.

**Comment by sergeybykov** [comment]
I added a documentation page for NuGets - http://dotnet.github.io/orleans/NuGets.

**Comment by jkamstra** [comment]
Thanks everyone. Tried it out this afternoon. Works great!
