### ISSUE TITLE
Explain "Orleans deployments are currently limited to a single data center per deployment"

### ISSUE THREAD

**Issue by mtdaniels** [dotnet/orleans#1831]
I ran across that specified limitation here: http://dotnet.github.io/orleans/Frequently-Asked-Questions, and would like to fully explain what the actual limitation is and what the intent of that statement is.  Our current plan is to host a cluster on premise, running as a Windows Service; however, we do in fact have two data centers.  Ideally servers in both locations would be on the same cluster (using Sql Server for liveness).

**Comment by jdom** [comment]
A single Orleans cluster is not optimized for having silos talk to other silos where the latency is very high (for example placement is completely random, and this might not be a good idea if you have latencies that are orders of magnitude different whether the peer is in the same or a different datacenter).
We recently merged multi-cluster support for Orleans, where you can basically model more than one cluster and have them talk to each other. Nevertheless this is in `master` and wasn't released in any nuget package yet.
Also, there are no features that currently benefit from the multi-cluster support, although there's a few coming very soon (like #1800).
So depending on when you expect to deploy to production, full support for multi-cluster might already be in place.
