### ISSUE TITLE
Question: Can grain be deactivated during timer/reminder callback?

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1846]
Hi,

I was wondering if a grain can be deactivated and OnDeactivateAsync called while a timer/reminder callback is executed? If so, how would you recommend to make the deactivation wait for the timer/reminder callback finish execution?

**Comment by gabikliot** [comment]
You can call deactivate on idle . If the grain is not reentrant, deactivation will happen after this method is done. If it is reentrant, it depends if there are other currently queued operations. There is no mechanism  to wait for deactivation, but you can probably build something yourself with task completion source which you will resolve in on deactivate async.

**Comment by Eldar1205** [comment]
I think you answered the opposite question. I'm interested in delaying a
pending deactivation for a timer tick to finish. Timers don't keep the
grain alive so Orleans may decide to deactivate while the grain handles a
timer tick. Will Orleans wait for the tick to finish, and if not do you
suggest using tasks to make the deactivation wait for the timer to finish?
בתאריך 16 ביונ' 2016 5:29 PM,‏ "Gabriel Kliot" <notifications@github.com>
כתב:

**Comment by gabikliot** [comment]
> Orleans may decide to deactivate while the grain handles a timer tick.

No, it will not.

>Will Orleans wait for the tick to finish

Yes, of course it will. 
Orleans will NOT deactivate in the MIDDLE of the timer tick.
Not just that it will wait until the tick is over, it will wait until the task returned from the current tick is resolved (`ActivationData.WaitForAllTimersToFinish`).
