### ISSUE TITLE
Advice on using Orleans for an Instant Messaging application 

### ISSUE THREAD

**Issue by easysoft2k15** [dotnet/orleans#1851]
I'm working on a messaging application and would like to use Orleans as back-end.

**ARCHITECTURE**
Each client is a mobile phone.
Messages sent may be strings or files (in case of file they may be some MB in size).
Looking at the examples  seems like the architecture I need to use is the one implemented in "GPSTracking" example which means that the flow to send message from one client to the other is:

1. a clientA send the message to a front-end ASP.NET application via SignalR
2. the ASP.NET get the clientA GRAIN and call the SendMessage method
3. GRAIN of clientA send the message to GRAIN clientB
4. if clientB is NON online, GRAIN clientB keep the message until clientB become active (ASP.NET application call the GRAINS method IsOnline each time a client connect with signalR so each GRAIN has the notion of "Being Online or Offline")
5. if clientB is online, GRAIN use IPushNotifier (GPSTracker example) to send back the message to ASP.NET (using SignalR) which in turn send the message to clientB

**I have a few QUESTIONS:**

- [ ] a) Does it make sense to use Orleans in this scenario (compare to just let the ASP.NET application to manage the business logic of sending messages, store messages, retry logic, etc.)?

- [ ] b) suppose in point (5) clientB is still online but when the IPushNotifier try to send the message it become unavailable (clientB has gone offline in the meanwhile), ASP.NET can not deliver message so it should report back to GRAIN B that the message was not deliver. It seems to me that in this way part of the business logic is managed by the ASP.NET application. I feel that ASP.NET application should only forward commands in both direction without implementing any business logic that should be demanded to the GRAINS.

- [ ] c) My understanding is that there must be a front end (usually ASP.NET) for authentications purpose, etc. In this way I need to keep basically three "logical" communication channels open:
-  from clients to ASP.NET (SignalR)
-  from ASP.NET to GRAINS in silos (native Orleans client)
-  from GRAIN IPushNotifier to ASP.NET (SIgnalR)

Isn't it to much overhead?

**NOTES**
- I'm using Xamarin on the client side so I guess the only way to communicate with GRAINS would be using a front-end ASP.NET (while in the GPSTracker example vehicles use ORLEANS native interface to communicate directly with GRAIN).
- being able to establish a communication channel back to Mobile application directly from Orleans GRAIN after the initial connection was established via ASP.NET, seems like a reasonable think to do. I don't know if this is possible or even advisable

Any advise on how use the framework in this context would be much appreciated.
Thank You
Alessandro

**Comment by sergeybykov** [comment]
Such an application is a great fit for Orleans, as it would help easily scale out a large number of independent contexts (conversations).

I'm not too familiar with SignalR, but I suspect you probably don't need to use its hub functionality to push notifications to ASP.NET. GPSTracker sample does that to broadcast updates to all clients. In the chat case you only need to notify parties of the same conversation.

I think you need the clients to open a bi-directional connection with ASP.NET via SignalR, and have ASP.NET code communicate with grain via Orleans client library. Notifications back to ASP.NET can be delivered either via client observers or SMS streams.

>being able to establish a communication channel back to Mobile application directly from Orleans GRAIN after the initial connection was established via ASP.NET, seems like a reasonable think to do. I don't know if this is possible or even advisable

I don't believe this is easy to do as grain and silos don't normally open externally accessible ports. Neither do mobile clients. The general recommendation is to have clients only to the frontends (ASP.NET).

**Comment by sergeybykov** [comment]
Have you looked at the Chirper sample - https://github.com/dotnet/orleans/tree/master/Samples/Chirper?

**Comment by easysoft2k15** [comment]
Thank You for thefeedback!
I was thinking too about the Observer pattern in order to communicate back to ASP.NET from Orleans and I'm glad You confirmed this is the right way of using the framework.
I'm going to take a look at the Chirper sample as well.
Alessandro
