### ISSUE TITLE
Provide explicit list of assemblies in Configuration for the Silo/Client.

### ISSUE THREAD

**Issue by jamescarter-le** [dotnet/orleans#1852]
When booting a Silo or Client with a large number of managed and native assemblies in the Base Directory, Initialization takes a significant length of time.

As discussed in #1676, we should add a Configuration setting to explicitly specify assemblies to be loaded by Orleans to look for applicable Types.

**Comment by sergeybykov** [comment]
https://github.com/dotnet/orleans/issues/1840 already has concrete suggestions. Let's use it and consider this one a duplicate.
