### ISSUE TITLE
Error creating activation after implementing DI option

### ISSUE THREAD

**Issue by jeffas** [dotnet/orleans#1853]
I have an Orleans project that I have implemented Grain DI using the Startup class convention, implemented using AutoFac's pre-built _IServiceProvider_ package.
With the DI logic in place, trying to invoke the target method on the grain returned by _GrainClient.GrainFactory_ results in there error message 'Error creating activation'.

The included stack trace is as follows:
```Exc level 0: System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.Runtime.GrainCreator.CreateGrainInstance(Type grainType, IGrainIdentity identity)
   at Orleans.Runtime.Catalog.CreateGrainInstance(String grainTypeName, ActivationData data, String genericArguments)
   at Orleans.Runtime.Catalog.SetupActivationInstance(ActivationData result, String grainType, String genericInterface)
   at Orleans.Runtime.Catalog.GetOrCreateActivation(ActivationAddress address, Boolean newPlacement, String grainType, String genericArguments, Dictionary`2 requestContextData, Task& activatedPromise)
   at Orleans.Runtime.Dispatcher.ReceiveMessage(Message `message)```

Commenting the 'Startup' tag from the config file allows the project to start normally (i.e. without DI).    Under this condition, _GrainFactory_ is able to resolve working grains as long as there is a parameter-less constructor, per standard behavior.

**Comment by jeffas** [comment]
I worked out the issue, so I'll give an explanation of what I was running into.  Basically I had registered the grains keyed to their interfaces, which is a typical use case.  However I discovered that Orleans resolves the grain interfaces that you pass into _GrainClient.GrainFactory_ to the concrete type and was using that concrete type to request the grain from the service provider.

The AutoFac service provider was unable to find a registration against the concrete type, and returned _NULL_ instead of a description exception.  Since there isn't a null check against the returned grain instance in _GrainCreator.CreateGrainInstance_, it threw a _NullReferenceException_ when it tried to set grain properties.

Would a null check, after trying to resolve the grain, be useful if it raised a more informative exception?

**Comment by sergeybykov** [comment]
>Would a null check, after trying to resolve the grain, be useful if it raised a more informative exception?

I think so.

**Comment by jdom** [comment]
See #1841

**Comment by sergeybykov** [comment]
Should be fixed via https://github.com/dotnet/orleans/pull/1901.
