### ISSUE TITLE
 Cannot find generated GrainReference class for interface issue with 1.2.2 version

### ISSUE THREAD

**Issue by somnathnitb** [dotnet/orleans#1860]
Hi,

We upgraded from 1.0.9 to 1.2.2 and after the upgrade we are getting exception where it's unable to load a grainwithguidkey with below error:-
Error Details System.InvalidOperationException: Cannot find generated GrainReference class for interface 'Grains.Interfaces.User.IUserGrain'
   at Orleans.GrainFactory.MakeCaster(Type interfaceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Orleans.GrainFactory.Cast(IAddressable grain, Type interfaceType)
   at Orleans.GrainFactory.Cast[TGrainInterface](IAddressable grain)

Would really appreciate any quick help on this.

Thanks,
Somnath

**Comment by sergeybykov** [comment]
Take a look at Properties\orleans.codegen.cs of the project that defines `IUserGrain`. Do you see a grain reference class generated there at compile time?

**Comment by somnathnitb** [comment]
In the Interfaces project I can see reference to interface being created with GrainRefrenceAttribute. But nothing in actual class implementation project. There was never any code generated in the implementation project.

**Comment by sergeybykov** [comment]
One in the interfaces project is enough. Can you make sure you rebuilt all the binaries and deploy the right versions of them?

**Comment by somnathnitb** [comment]
Thanks for your quick responses. Actually we have a very good CI & CB infrastructure which takes care of version across all the binaries. Our build doesn't allow multiple packages as well. This started coming up only after migration to Orleans 1.2.2 from 1.0.9. Anything specific I need to handle post migration?

**Comment by sergeybykov** [comment]
In the grain interfaces assembly do you see a `OrleansCodeGenUserGrainGrainReference` class? Do you see it in Properties\orleans.codegen.cs?

**Comment by somnathnitb** [comment]
yes I can see this internal class OrleansCodeGenUserGrainReference : global::Orleans.Runtime.GrainReference, global::LCBS.Global.Grains.Interfaces.User.IUserGrain getting generated

**Comment by somnathnitb** [comment]
Another quick input it's failing only when a call to grain is made to get it's state using GrainClient. Like I said we migrated from 1.0.9 to 1.2.2 and still we have states inheriting from "GrainState". Anything I need to look for?

**Comment by sergeybykov** [comment]
This is very strange. Is there any way to get a condensed repro? The error says *"Cannot find generated GrainReference class for interface"*, which should happen only if the interface assembly is missing the generated grain reference class. Any chance you have a different version of the interface assembly on the client?

The interface assembly is obviously loaded because you are passing `IUserGrain` to `GetGrain`. Seems like something is missing in this picture, and I can't quite get what.

**Comment by Donjay2101** [comment]
Add Reference to OrleansCodeGenerator, In my project this was the issue I did not added "OrleansCodeGenerator" as reference.

**Comment by 2821840032** [comment]
yes！I also have this problem.
I want to use silo as client.
That's not going to work.
I don't know why this is the problem anyway.
Maybe there's something wrong with my usage?

services.AddScoped<IGrainFactory>(d=>host.Services.GetService<IGrainFactory>());

**Comment by 2821840032** [comment]
services.AddScoped<IGrainFactory>(d=>host.Services.GetService<IGrainFactory>());
Input error above

**Comment by 2821840032** [comment]
yes！I also have this problem.
I want to use silo as client.
That's not going to work.
I don't know why this is the problem anyway.
Maybe there's something wrong with my usage?

services.AddScoped《IGrainFactory》(d=>host.Services.GetService《IGrainFactory》());

**Comment by ReubenBond** [comment]
@2821840032 could you show more of your configuration code? It is possible that you do not have the `Microsoft.Orleans.CodeGenerator.MSBuild` package installed.

**Comment by rpanday** [comment]
Thanks @ReubenBond, adding reference to `Microsoft.Orleans.CodeGenerator.MSBuild` package worked for me.
