### ISSUE TITLE
Question: Does global server side interceptor execute before or after grain is activated?

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1870]
I haven't had a chance to play with version 1.2.x yet and have a question regarding the global server side interceptor feature that was added. Let's assume my grain with <type, id> = <Consumer, 15> is about to receive a message (from client/another grain/reminder/etc.) but it's not yet activated. Will the global server side interceptor intercept the message before the grain is activated or will the interceptor run only after `OnActivateAsync` was executed successfully?

**Comment by sergeybykov** [comment]
>Will the global server side interceptor intercept the message before the grain is activated or will the interceptor run only after  OnActivateAsync  was executed successfully? 

Global interceptor gets invoked for an already activated grain, after `OnActivateAsync()` successfully executed.
