### ISSUE TITLE
Ability to intercept OnActivateAsync for grain

### ISSUE THREAD

**Issue by Dewaldf** [dotnet/orleans#1871]
I would like to be able to intercept the OnActivateAsync & OnDeactivateAsync method for a grain using a global interceptor. 

Currently If I want to do something when a grain is activated, I need to do it on a per grain bases, the other option is to create a base grain and then inherit from it. This is not ideal, because that forces me to inherit a specific grain for functionality and might make things complicated.

**Comment by richorama** [comment]
This has also been asked for on the dashboard https://github.com/OrleansContrib/OrleansDashboard/issues/34

**Comment by shlomiw** [comment]
+1
Will help for metrics

**Comment by ReubenBond** [comment]
Closing in favor of #4519, which xref's this
