### ISSUE TITLE
Failure to read grain state after upgrading from version 1.1.3 to 1.2.2

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1872]
As part of the upgrade to version 1.2.2, I made my grain state class no longer inherit GrainState, as it is obsolete, but then I started noticing read state exceptions. I use the Azure Storage table provider, and grain state is serialized using default serializer. I tried reverting to keep using GrainState as base class for now, but it didn't help, still getting the exception. Please help me understand how should I make the upgrade. Here is an example trace with the exception:

"[2016-06-24 20:04:37.827 GMT    19 WARNING 101032  Dispatcher  100.107.176.34:30000]   Forwarding failed: tried to forward message NewPlacement Request S100.107.124.46:30000:204492685ReminderService@S00000010->S100.107.176.34:30000:204494632*grn/8E20F1E5/00000000+asec-7509b1da-fecc-4774-9b3c-dc4ae69803e8-ns::asec-4d43fdf3-2a96-4871-b107-9d3906d1d04c-eh::0@fb890ea5 #8896[ForwardCount=2]: global::Orleans.IRemindable:ReceiveReminder() for 2 times after Failed SetupActivationState to invalid activation. Rejecting now.  
Exc level 0: System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'Microsoft.Azure.Security.RomeDataStorage.Orleans.Server.ManagedEventHubs.ManagedEventHubConsumerState'.
   at Orleans.GrainState`1.Orleans.IGrainState.set_State(Object value)
   at Orleans.Storage.AzureTableStorage.<ReadStateAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass1_0.<<QueueTask>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Catalog.<SetupActivationState>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Catalog.<InitActivation>d__51.MoveNext()"

**Comment by Eldar1205** [comment]
I like to add that if I'm right about the cause of the issue, this is backward compatibility problem where with GrainState the state were serialized as properties bag (Dictionary<string, object>) that is different than the state class itself. To solve this, I suggest modifying the grain state handling code such that when **reading** the code will try to deserialize the persisted state as either the state class itself or as it used to deserialize GrainState, but when **writing** the code will only use the new serialization not based on GrainState. That way we have backwards compatibility and overtime all grain states will be persisted in new format and the backwards compatibility code can be removed, with the proper release note of course.

**Comment by Eldar1205** [comment]
I've manage to solve the issue by implementing an adapter around AzureTableStorage. Here's the code, I suggest to merge it into Orleans as bug fix, let me know what you think:

`/// <summary>
    /// An implementation of Orleans <see cref="IStorageProvider"/> that decorates an <see cref="AzureTableStorage"/>
    /// with read operations backwards compatibility support for the obsolete <see cref="GrainState"/> inherited classes.
    /// </summary>
    public class GrainStateBackwardsCompatibilityStorage : IStorageProvider
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GrainStateBackwardsCompatibilityStorage"/>
        /// </summary>
        public GrainStateBackwardsCompatibilityStorage()
        {
            _underlineStorage = new AzureTableStorage();
        }

        /// <inheritdoc />
        public string Name => _underlineStorage.Name;

        /// <inheritdoc />
        public Logger Log => _underlineStorage.Log;

        /// <inheritdoc />
        public Task Init(string name, IProviderRuntime providerRuntime, IProviderConfiguration config)
        {
            return _underlineStorage.Init(name, providerRuntime, config);
        }

        /// <inheritdoc />
        public Task Close()
        {
            return _underlineStorage.Close();
        }

        /// <inheritdoc />
        public async Task ReadStateAsync(string grainType, GrainReference grainReference, IGrainState grainState)
        {
            var asLegacyState = grainState.State as GrainState;

            // No need for backwards compatibility for type that isn't inherited from the legacy GrainState
            if (asLegacyState == null)
            {
                await _underlineStorage.ReadStateAsync(grainType, grainReference, grainState);
                return;
            }

            var proxyState = new WeaklyTypedGrainState { State = grainState.State, ETag = grainState.ETag };
            await _underlineStorage.ReadStateAsync(grainType, grainReference, proxyState);

            var stateAsPropertiesBag = proxyState.State as Dictionary<string, object>;

            if (stateAsPropertiesBag == null)
            {
                grainState.State = proxyState.State;
            }
            else 
            {
                Log.Info("Underline storage read state as properties bag, assuming it's legacy GrainState properties bag");

                asLegacyState.SetAll(stateAsPropertiesBag);
                grainState.State = asLegacyState;
            }

            grainState.ETag = proxyState.ETag;
        }

        /// <inheritdoc />
        public Task WriteStateAsync(string grainType, GrainReference grainReference, IGrainState grainState)
        {
            return _underlineStorage.WriteStateAsync(grainType, grainReference, grainState);
        }

        /// <inheritdoc />
        public Task ClearStateAsync(string grainType, GrainReference grainReference, IGrainState grainState)
        {
            return _underlineStorage.ClearStateAsync(grainType, grainReference, grainState);
        }

        private readonly AzureTableStorage _underlineStorage;

        private class WeaklyTypedGrainState : IGrainState
        {
            public object State { get; set; }

            public string ETag { get; set; }
        }
    }`

**Comment by shayhatsor** [comment]
@Eldar1205, thanks for taking the time to offer a solution. If you can provide a PR, that would be best. As it is a bug that blocks most upgrades, it must result in a new Orleans release. @sergeybykov, do you agree?

**Comment by Eldar1205** [comment]
Until a release is made this solution can be posted as an external
mitigation, only the type of underline storage provider needs to be
modified depending on kind of storage used by developers. Would be nice if
Orleans supported closed generic bootstrap providers registrations.

2016-06-25 15:18 GMT+03:00 Shay Hazor <notifications@github.com>:

**Comment by sergeybykov** [comment]
>@Eldar1205, thanks for taking the time to offer a solution. If you can provide a PR, that would be best. As it is a bug that blocks most upgrades, it must result in a new Orleans release. @sergeybykov, do you agree?

I think the fix would be worth a 1.2.3 release.

**Comment by philreindl** [comment]
Did this make it into 1.2.3?  If so, how do I use it?  I assume I need to change the Storage Provider attribute to something like  [StorageProvider(ProviderName = "GrainStateBackwardsCompatibilityStorage")]

Is that true?  Thanks

**Comment by sergeybykov** [comment]
Unless I'm missing something, there wasn't a PR for this.

**Comment by philreindl** [comment]
Ah ok. I was able to make it go by pasting in the above code as a new type and referencing as documented in the Custom Providers section of the docs.

Thanks!

**Comment by benjaminpetit** [comment]
Orleans backward compatibility work started in 2.0
