### ISSUE TITLE
ImplicitStreamSubscription doesn't activate a grain that implements IGrainWithIntegerKey

### ISSUE THREAD

**Issue by ghost** [dotnet/orleans#1882]
I am attempting to implement ImplicitStreamSubscriptions on grains that implement IGrainWithIntegerKey, however, the grain that gets activated is not an 'integer identified grain', e.g. this.GetPrimaryKeyLong() throws an exception in it's OnActivateAsync().

I modified the SampleStreamingTests by changing the IMultipleImplicitSubscriptionGrain to extend IGrainWithIntegerKey, and the test fails.  In order to create a Guid from a long (to pass into GetStream), I used the following code:

```
            long longId = 123;
            byte[] bytes = new byte[16];
            BitConverter.GetBytes(longId).CopyTo(bytes, 0);
            var streamId = new Guid(bytes); 
```

and modified GetGrain to use the long
`var grain = GrainClient.GrainFactory.GetGrain<IMultipleImplicitSubscriptionGrain>(longId);`

**Comment by sergeybykov** [comment]
Looks like a consequence of https://github.com/dotnet/orleans/issues/1121.

**Comment by d-loring** [comment]
Ah thanks, any estimate when this feature would be available?  It seems like there is some other interest in using implicits with other grain type on the other thread.

**Comment by sergeybykov** [comment]
No estimate yet. It's a non-trivial and likely breaking change because we'll have to change how stream identities are defines and handled. Contributions, of course, are more than welcome.

**Comment by ReubenBond** [comment]
This is not longer an issue in 7.x, since stream identities are now flexible and align with grain identities.
