### ISSUE TITLE
Release with Microsoft.Extensions.DependencyInjection updated to stable

### ISSUE THREAD

**Issue by dolly22** [dotnet/orleans#1890]
When is new orleans release containing #1878 scheduled? It's blocking us from upgrading to .NET Core 1.0 RTM.

**Comment by jdom** [comment]
That commit just updated the DI package reference, but Orleans still does not support .NET Core at all.  Or what is your goal with that commit?

**Comment by dolly22** [comment]
I'm using some Microsoft.Extensions.* libraries (Logging, Caching, Options, DependencyInjection) targeting net452. Now it's not possible to upgrade my code to reference 1.0.0 library version due to some changes in DependencyInjection package contracts. 

Current orleans 1.2.2 release uses ConfigureStartupBuilder from OrleansDependencyInjection that depends on outdated rc1 packages and uses no longer existing contract Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionExtensions (now renamed to [ServiceCollectionServiceExtensions](https://github.com/aspnet/DependencyInjection/commit/60ca512beec3fefb4cd377ede009ff96b4848456))

This is the exception i'm getting when initializing silo...

> Exc level 0: System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Orleans.Runtime.Startup.ConfigureStartupBuilder.RegisterSystemTypes()
   at Orleans.Runtime.Startup.ConfigureStartupBuilder.ConfigureStartup(String startupTypeName)
   at Orleans.Runtime.Silo..ctor(String name, SiloType siloType, ClusterConfiguration config, ILocalDataStore keyStore)
   at Orleans.Runtime.Silo..ctor(String name, SiloType siloType, ClusterConfiguration config)
   at Orleans.Runtime.Host.SiloHost.InitializeOrleansSilo()

**Comment by jdom** [comment]
I see, then we should consider this commit for a patch release (1.2.3), depending how far we are from 1.3.0
/cc @sergeybykov

**Comment by Lexelas** [comment]
@dolly22 

Current type for ServiceCollectionExtensions is actually ServiceCollectionContainerBuilderExtensions

See https://github.com/aspnet/DependencyInjection/issues/412

**Comment by sergeybykov** [comment]
We couldn't include this change in 1.2.3 because it's a change in dependencies, and hence is breaking. Will be included in 1.3.0.

**Comment by sergeybykov** [comment]
1.3.0 has been released.
