### ISSUE TITLE
CancellationToken feature failures

### ISSUE THREAD

**Issue by jdom** [dotnet/orleans#1891]
Hi, we are getting some random failures in our CI builds in relation to the new cancellation token feature.
I took a look at the tests, and they seem correct, so these might actually be uncovering some bugs.
Perhaps someone wants to take a look? @dVakulen ?

These are some of the failures we've seen in our private VSO from time to time, and sometimes the PR build in Jenkins (like [here](http://dotnet-ci.cloudapp.net/job/dotnet_orleans/job/innerloop_prtest/1527/) and [here](http://dotnet-ci.cloudapp.net/job/dotnet_orleans/job/innerloop_prtest/1508/))

This one is the one we get failing more often (with delay 0ms)

```
Test Name: UnitTests.CancellationTests.GrainCancellationTokenTests.MultipleGrainsTaskCancellation(delay: 0)
Duration: 0:00:10.025
Error message
Assert.Throws() Failure
Expected: typeof(System.Threading.Tasks.TaskCanceledException)
Actual: (No exception was thrown)

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
UnitTests.CancellationTests.GrainCancellationTokenTests.<MultipleGrainsTaskCancellation>d__2.MoveNext() in C:\Builds\5877\Orleans\Nightly-Func\src\test\Tester\CancellationTests\GrainCancellationTokenTests.cs: line 50
```

```
Test Name: UnitTests.CancellationTests.GrainCancellationTokenTests.MultipleGrainsTaskCancellation(delay: 10)
Duration: 0:00:10.207

Error message
Assert.Throws() Failure
Expected: typeof(System.Threading.Tasks.TaskCanceledException)
Actual: (No exception was thrown)

System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
UnitTests.CancellationTests.GrainCancellationTokenTests.<MultipleGrainsTaskCancellation>d__2.MoveNext() in C:\Builds\5877\Orleans\Nightly-Func\src\test\Tester\CancellationTests\GrainCancellationTokenTests.cs: line 50
```

```
Test Name: UnitTests.CancellationTests.GrainCancellationTokenTests.InterSiloClientCancellationTokenPassing(delay: 10)
Duration: 0:00:00.024
Error message
System.Exception : Could not make requested grains placement

UnitTests.CancellationTests.GrainCancellationTokenTests.<GetGrains>d__14`1.MoveNext() in C:\Builds\7001\Orleans\Nightly-Func\src\test\Tester\CancellationTests\GrainCancellationTokenTests.cs: line 196
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
UnitTests.CancellationTests.GrainCancellationTokenTests.<ClientGrainGrainTokenPassing>d__12.MoveNext() in C:\Builds\7001\Orleans\Nightly-Func\src\test\Tester\CancellationTests\GrainCancellationTokenTests.cs: line 162
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
UnitTests.CancellationTests.GrainCancellationTokenTests.<InterSiloClientCancellationTokenPassing>d__10.MoveNext() in C:\Builds\7001\Orleans\Nightly-Func\src\test\Tester\CancellationTests\GrainCancellationTokenTests.cs: line 148
```

```
Test Name: UnitTests.CancellationTests.GrainCancellationTokenTests.CancellationTokenCallbacksThrow_ExceptionShouldBePropagated
Duration: 0:00:00.126

Error message
No exception was thrown
Expected: True
Actual: False

UnitTests.CancellationTests.GrainCancellationTokenTests.<CancellationTokenCallbacksThrow_ExceptionShouldBePropagated>d__7.MoveNext() in C:\Builds\5879\Orleans\Nightly-Func\src\test\Tester\CancellationTests\GrainCancellationTokenTests.cs: line 119
```

Most of the times, the ones that fail is the ones that have a delay of 0ms or 10ms before canceling the token. I haven't seen the ones with a 300ms failing yet, so I assume it's something related to canceling the token fast after we were preparing to send it to the remote grain.

**Comment by gabikliot** [comment]
Yes, I even saw that sometimes happen on my laptop. This test is sensitive to timing. 
@dVakulen , do you think it is possible to change this test to still test what it tests now, but not be dependent on timing? Time dependence makes tests very fragile and extremely costly to everyone, as those tests keep failing occasionally. But of course we don't want to completely remove them, as they are valuable.

**Comment by jdom** [comment]
I also don't like tests that depend on waiting more time, but here it is actually the opposite, looks like if we don't wait enough it doesn't work correctly, so I wouldn't fix the test itself, I think it's uncovering an actual bug in the runtime that needs fixing. After that is fixed, we can think about what to do with the test

**Comment by gabikliot** [comment]
I will leave it to @dVakulen to take a look and if he can't figure it out, I will look into this.

**Comment by dVakulen** [comment]
The reason of this failures is collecting of the GCT in situation when the cancel request arrives before the original call with cancellation token, thus nothing keeps reference to the cancelled token besides interner in this period of time. As straightforward way of fixing it I'd use cache with small (< 1 min) time expiration for newly arrived tokens, but maybe there's better ideas one may come up with..

**Comment by dVakulen** [comment]
I've made this tests to depend on time in order to catch this kind of bugs.

**Comment by gabikliot** [comment]
Ohhh, this is a beautifull, beautifull bug!
Indeed, there is a race between the grain request and the later cancel request.
Usually, they arrive in order and all is fine.
Even if they arrive out of order (we don't provide 100% fifo order), our logic still should handle it correctly. We record the token that arrived via cancel request in the grain extension and when later on the original request arrives, we cancel it upon its arrival. This actually works. I was able to repro the out of order execution and saw its working.

BUT: the token is stored in the Interner. **We only keep weak reference to it**. The idea was that the extension code will keep a weak reference to the token and in the normal execution the original request token is passed to the grain and as long as the grain holds a strong reference to the token, it will be kept in the extension via the weak reference. If the grain drops the reference, it will be dropped automatically in the extension. If we held a strong ref in the extension, we would need to deal with manually GCing them. So it was a trick to avoid manual memory management.
But in the race case we put the token that came in the cancel request but of course we don't pass it to the grain, since the original grain call has not arrived yet. So now there is only a weak ref to this token and it is sometimes GCed before the later grain call arrives!

I need to think how to fix it in the best way. Ideas are welcomed!

**Comment by jdom** [comment]
Well, the question is whether it is worth trying to enforce the cancellation in this unlikely scenario, since calling Cancel doesn't mean that we guarantee that the request will be canceled (it could have finished already by the time the Cancel arrives, or not checked again), but if this is a VERY long running operation and the user took all the precautions to check for cancellation often, then silently failing to cancel might be a very good option.
So I agree that silently failing is not very good, but an approach we could take is that if the cancellation arrives prior to the request with the token, then we can throw an exception back to the caller of the Cancel method, and he can decide whether to retry the cancellation.
That scenario is not that different to the error handling needed if the Cancel request never reaches the silo due to some other transient failure...

**Comment by gabikliot** [comment]
I just saw that my explanation is exactly the same as the one @dVakulen gave.
I just failed to fully comprehend his explanation initially.

@jdom , throwing upon a cancel request that arrives and there is nothing to cancel is indeed one option. Not sure if it won't create other edge cases scenarios. Need tho think through carefully. 

Basically, the question is how "best effort" is the best effort cancellation. For example, messaging as a whole is best effort. Still, look at this issue: https://github.com/dotnet/orleans/issues/1775 - users are pretty upset when msgs don't arrive, even if strictly speaking it does not violate the semantics.

**Comment by jdom** [comment]
Hehe, I thought you read his reply and tried to expand on it, even if it was clear in the first place :P
Agree on the fact that best effort should be explicit or it can cause frustration. That's why I'm suggesting throwing an exception: "we did our best effort but it wasn't enough so I'm at least letting you know so you can handle it"

**Comment by sergeybykov** [comment]
Resolved via #1934.

**Comment by dVakulen** [comment]
@sergeybykov I don't think that this was ready to be closed, as https://github.com/dotnet/orleans/pull/1934 only disabled race condition under which the tests were failing.

**Comment by sergeybykov** [comment]
Sorry, I misunderstood.

**Comment by dVakulen** [comment]
So there's two ways of fixing this:
 1. cache with small time expiration for newly arrived tokens
 2. Exception throwing in case of race with  auto retry.

Which one should we take?

**Comment by gabikliot** [comment]
I will look again at it and will reply.

**Comment by jdom** [comment]
Disabling some more related tests via https://github.com/dotnet/orleans/pull/2219

**Comment by dVakulen** [comment]
@gabikliot Could you please share your thoughts on this?

**Comment by dVakulen** [comment]
Fixed via https://github.com/dotnet/orleans/issues/3168
