### ISSUE TITLE
'My First Orleans' documented example incorrect

### ISSUE THREAD

**Issue by GadgetGeekUK** [dotnet/orleans#1893]
For: http://dotnet.github.io/orleans/Step-by-step-Tutorials/Minimal-Orleans-Application

It states:

- Tested in both Visual Studio 2013 and 2015 using Orleans 1.0.9.

However, I'm working through the example withe Orleans 1.0.10.0 and the following line is definately not available until a later release, 'LocalhostSilo()':

`var config = Orleans.Runtime.Configuration.ClientConfiguration.LocalhostSilo(30000);`

If I replace this with the code used in 1.2.2:

`var config = new ClientConfiguration { GatewayProvider = ClientConfiguration.GatewayProviderType.Config };
config.Gateways.Add(new IPEndPoint(IPAddress.Loopback, 30000));`

The code runs but then fails at:
var friend = GrainClient.GrainFactory.GetGrain<IHello>(0);

Saying it can't find an instance of the IHello...

**Comment by sergeybykov** [comment]
Thanks. I updated "1.0.9" to "1.2.0".

>Saying it can't find an instance of the IHello...

Can you double-check to make sure all binaries are rebuilt and of matching versions?

**Comment by GadgetGeekUK** [comment]
Many thanks, did you alter the use of 'ClientConfiguration.LocalhostSIlo()' as this is not available in the earlier releases.

I checked all Orleans references are at 1.0.10.0, and am now trying on another PC to see if I get the same issue!!

**Comment by GadgetGeekUK** [comment]
1st: I had missed the adding of the Orleans.Templates.Interfaces to the Interfaces project.

2nd: Then the issue was with the generation of the grain factory class. Using VS2015/resharper, the following line in the 'HelloGrain':

`return Task.FromResult(string.Format("You said {0}, I say: Hello!", msg));`

had been changed to use C#6.0 string interpolation:

`return Task.FromResult($"You said {msg}, I say: Hello!");`

This then causes the codegen to fail, and you get no 'HelloFactory' generated.

**Comment by GadgetGeekUK** [comment]
Resolving both these issues, the 'Minimal' demo now works!

**Comment by sergeybykov** [comment]
>This then causes the codegen to fail, and you get no 'HelloFactory' generated.

This was enabled in 1.2.0.
