### ISSUE TITLE
Question: Orleans on Azure App Service

### ISSUE THREAD

**Issue by levidrain** [dotnet/orleans#1896]
I'm working on an app that currently has a very small user base.  I'm interesting in using Orleans to "future proof" it.  However, when hosting on Azure, a simple setup requires several resources (cloud service, app service, vnet setup, table storage, etc).  It quickly gets costly for so little load.

Is it possible to create a new AppDomain when the App Service starts up and host a local silo; and in the main AppDomain create the client?  I already need the app service to be always on for webjobs, so if I understand correctly, the silo wouldn't be shutdown when idle.

Is this possible? Is it a bad idea?  Again, I don't need a lot of the benefits of Orleans yet, it's more about being able to scale up later.

Thanks.

**Comment by sergeybykov** [comment]
I don't see why this approach wouldn't work. In your situation I'd give it a try.

**Comment by Maarten88** [comment]
You can also use Yams to serve small deployments: you can deploy a website and orleans silo to a single small instance cloudservice, with fast deployments. It works well for us. An advantage is you don't have to change things later, if you want to scale. You 'll need to make the website self hosted, so it deploys as an executable, but with asp.net core that's easy now.

**Comment by levidrain** [comment]
@Maarten88 interesting.  I wasn't familiar with Yams, I'll look into it.

**Comment by turowicz** [comment]
@sergeybykov having trouble setting this up. It works fine in a single-node cluster but as soon as you scale out to more VMs in the App Service the problems arise.

This is probably due to the Sandboxing feature of App Service
https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox

Has anyone tried working around it somehow?

**Comment by sergeybykov** [comment]
@turowicz Can you provide more details about your setup and configuration? What clustering options you are using, etc. Please open a new issue for that.

**Comment by turowicz** [comment]
@sergeybykov thanks I will open a new ticket
