### ISSUE TITLE
Application Bootstrap within a Silo

### ISSUE THREAD

**Issue by weitaolee** [dotnet/orleans#19]
please give a code  way to boostrap silo
```
 var BOOTSTARTP_PROVIDER_CONFIGS_NAME = "Bootstrap";
            ProviderCategoryConfiguration providerConfiguration;
            if (!siloHost.Config.Globals.ProviderConfigurations.TryGetValue(BOOTSTARTP_PROVIDER_CONFIGS_NAME, out providerConfiguration))
            {
                providerConfiguration = new ProviderCategoryConfiguration()
                {
                    Name = BOOTSTARTP_PROVIDER_CONFIGS_NAME,
                    Providers = new Dictionary<string, IProviderConfiguration>()
                };
            }

            var eventStoreProvider = new ProviderConfiguration(new Dictionary<string, string>(), typeof(EventStoreInitBootstrapProvider).FullName, "EventStoreInitBootstrapProvider");
            providerConfiguration.Providers.Add("EventStoreInitBootstrapProvider", eventStoreProvider);

            siloHost.Config.Globals.ProviderConfigurations[BOOTSTARTP_PROVIDER_CONFIGS_NAME] = providerConfiguration;
```
but failed. I read the source code ,find some class have method like AddProvider ,but internal

please give a way to give the Application Bootstrap by  code.

**Comment by yevhen** [comment]
If you need it now, you can get it with the following hack:

```cs
void RegisterBootstrapProviders(params[] Type bootstrapProviders)
{
    var category = Configuration.Globals.ProviderConfigurations.Find("Bootstrap");

    if (category == null)
    {
        category = new ProviderCategoryConfiguration
        {
            Name = "Bootstrap",
            Providers = new Dictionary<string, IProviderConfiguration>()
        };

        Configuration.Globals.ProviderConfigurations.Add("Bootstrap", category);
    }

    foreach (var bootstrapProvider in bootstrapProviders)
        Register(bootstrapProvider, category);
}

public void Register(Type bootstrapProvider, ProviderCategoryConfiguration category)
{
    var fullName = bootstrapProvider.FullName;
    var config = new ProviderConfiguration(properties, fullName, fullName);

    var peskyField1 = GetPrivateField("childConfigurations");
    var peskyField2 = GetPrivateField("childProviders");

    peskyField1.SetValue(config, new List<ProviderConfiguration>());
    peskyField2.SetValue(config, new List<IProvider>());

    category.Providers.Add(config.Name, config);
}

static FieldInfo GetPrivateField(string name)
{
    var field = typeof(ProviderConfiguration)
        .GetField(name, BindingFlags.Instance | BindingFlags.NonPublic);

    Debug.Assert(field != null);
    return field;
}
```
But I agree, that programmatic configuration is now really problematic.

**Comment by gabikliot** [comment]
What is problematic about it? We just need to change one method to be public.

**Comment by yevhen** [comment]
Which one?

**Comment by gabikliot** [comment]
There is a class ProviderConfiguration. In our usage we always used it via XML, so this was a non issue, and naturally we hided all methods as internal.
If someone wants to construct ProviderConfiguration programmatically, it is a very natural thing to ask, no objections what so ever, just make what ever methods need to be made public and that is all.

**Comment by weitaolee** [comment]
@gabikliot yes,I read the source code ,and I find the method is internal. 
so if change the method as public, maybe can give more freedom to developer

**Comment by gabikliot** [comment]
If you change it to public and submit a pull request, we will be glad to accept it.

**Comment by pherbel** [comment]
Expand the documentation also would be helpful ;-)

**Comment by gabikliot** [comment]
You mean beyond that: https://github.com/dotnet/orleans/wiki/Application-Bootstrap-within-a-Silo?

**Comment by pherbel** [comment]
I mean expand that page with just a short comment that you can configure the Bootstrap provider in the code as well and an example about it.

**Comment by gabikliot** [comment]
@weitaolee, I believe I fixed the issue via #170. Unless I misunderstood what the original problem was.
Please try it out. If it does not fix the problem, could you please provide more details on what is actually not working.

**Comment by weitaolee** [comment]
@gabikliot thanks for your job ,I will try it later.

**Comment by gabikliot** [comment]
I believe we can close this issue given @yevhen's https://github.com/dotnet/orleans/pull/205
