### ISSUE TITLE
GrainState generic type constraint

### ISSUE THREAD

**Issue by normanhh3** [dotnet/orleans#1906]
Is there any objection to adding appropriate type constraints to Grain<TGrainState> in src\Orleans\Core\Grain.cs to require that the T type is required to have a parameterless constructor via the [**new** constraint](https://msdn.microsoft.com/en-us/library/d5x73970(VS.80).aspx)?

Instead of 
`
public class Grain<TGrainState> : Grain, IStatefulGrain
`

`
public class Grain<TGrainState> : Grain, IStatefulGrain where TGrainState : class, new()
`

This would have saved me quite a few hours the other day with Orleans.  :-(

**Comment by sergeybykov** [comment]
I don't see why not.

**Comment by shayhatsor** [comment]
@normanhh3, you got an exception here: https://github.com/dotnet/orleans/blob/master/src/Orleans/Core/GrainStateStorageBridge.cs#L136
right ? thanks for suggesting the fix. I'm sure it'll save hours for other people too.

**Comment by normanhh3** [comment]
@shayhatsor I don't have the call stack from the actual error.  My issue was that I was using **System.String** for the grain state instead of a wrapper object that has a parameterless constructor.

My assessment is that the constraint might have saved me the trouble of having to debug to the Activator.CreateInstance line that was causing the issue. :-/

I'll get a PR in for this soon.

**Comment by normanhh3** [comment]
I was just checking the documentation pages to see if I needed to clarify anything there as well.

The documentation for [Grain Persistence](https://github.com/dotnet/orleans/blob/gh-pages/Getting-Started-With-Orleans/Grain-Persistence.md) says that `Grain<T>` expects the T type to inherit from GrainState.

Is the inheritance from GrainState a requirement any longer?

My current running code is NOT inheriting the from GrainState and seems to be working just fine (near as I can tell on a single development silo)

If this is a requirement still, then I propose changing TGrainState to be constrained specifically to the GrainState type as opposed to the more generic `new` and `class` constraints.

Thoughts?

**Comment by shayhatsor** [comment]
> The documentation for Grain Persistence says that  Grain<T>  expects the T type to inherit from GrainState.

That's not right anymore.

> Is the inheritance from GrainState a requirement any longer?

No, that's a deprecated requirement.

**Comment by normanhh3** [comment]
Also see comment thread on #1923 for more context.
