### ISSUE TITLE
Orleans in an Azure CI/CD setup?

### ISSUE THREAD

**Issue by jkamstra** [dotnet/orleans#192]
I have been trying to get Orleans to build successfully using 1.0.3 packages via a VSO TFS repository triggering an Azure hosted CI/CD setup to no avail. Has anyone had success here?

**Comment by veikkoeeva** [comment]
@jkamstra Do you mean you are trying to download the 1.0.3 packages as part of building your own application or building the Orleans project? Do you have available logs (under ``BUILD``)?

**Comment by jkamstra** [comment]
We are a startup and I was attempting to test drive the following workflow. 

Using the 1.0.3 SDK and the VS nuget tooling we wanted to build a solution that we could build locally, run/test locally, check into VSO hosted TFS store, and trigger a CI/CD build onto Azure from VSO build.

I was able to get it working, but it is a rather frustrating, time consuming process. It requires hand editing of the .csproj files (thanks to @jthelin for the tips in PR #124). Problem is each round trip runs between 15-18 minutes. It took me about 6 round trips to finally get it right partly due to some self inflicted pain, but mostly due to the manner that the nuget packages markup the .csproj build defs - which work fine locally with an Orleans SDK installed, but not so good in cloud builds.

I have not yet tried to pull Orleans dailys into the cloud for build. I'd guess we can checkin local nuget packages in the \packages folder? but I am not a nuget specialist by any means.

I can unravel my build logs and document the big pieces if needed, but the repo is fairly straightforward if this is a supported scenario.

**Comment by sergeybykov** [comment]
@jkamstra We definitely want this kind experience to be smooth and painless. Could you provide more details on what hoops you ended up jumping through. Did you set up any of the environment variables that Orleans.SDK.targets looks for to find ClientGenerator.exe?

**Comment by veikkoeeva** [comment]
@jkamstra Could you share what was problem with the "Nuget markup" of csproj files? Was it that the Nuget packages wouldn't be downloaded or that they had a wrong version number? Or even better, did you happen to compile any notes to share in the process?

I can feel your pain as someone who has setup a fairly large Project with automatic SQL Server testing. The first hurdle is trying to figure out, what exactly has been installed on the build agents. Luckily, there's a page for that: [TFS Service - Software on the hosted build server](http://listofsoftwareontfshostedbuildserver.azurewebsites.net/).

**Comment by jkamstra** [comment]
No @sergeybykov I did not set environment variables - not sure how I can do that on a hosted TFS build agent. 

Great link @veikkoeeva. Thank you. 

The problem I ran into is I had three interface and three grain projects which all needed to have references to $OrleansSDK removed and I had to fixup all local references to point to the "..\packages" path. 

I also noticed that adding Orleans nuget features like Orleans.Templates.Grains or Interfaces brought in a lot of other unneeded dependencies. I manually removed most of those.

Next I had to manually remove nuget error checking as that always failed on the cloud...
<Error Condition="!Exists('..\packages\Microsoft.Orleans.Templates.Grains.1.0.3\build\Microsoft.Orleans.Templates.Grains.props') ...

Followed by the all out removal of the Grains and Interfaces Target packages from the solutions - possibly just fear and frustration.

Removed ClientConfiguration.xml from all the grains and interface projects.

Then I finally got to a state where I could do real work and start tracking why my instances were cycling because of a bad storage account key in my silos project (preceded by a round trip to enable diagnostics). 

Followed by a final round trip because of a local Newtonsoft.Json package ref in my silos project .csproj.

So again, I can now run with public nuget 1.0.3 packages, but I am guessing if we want to test daily builds of Orleans moving ahead we would have to build locally and manually push binaries to Azure.

Summary: about 3 hours of time (a lot of which was just staring at TFS build and deploy progress) and about 120 minutes of VSO build time burn :-)

**Comment by veikkoeeva** [comment]
@jkamstra You can set environment variables in code like ``Environment.SetEnvironmentVariable("VisualStudioVersion", "12.0")``, or then also in the TFS build template. There is a very good article with simular issues over at SSDT blog [SQL Server Database Projects and Team Foundation Build](http://blogs.msdn.com/b/ssdt/archive/2014/07/24/sql-server-database-projects-and-team-foundation-build.aspx). With regard to Nuget, this just worked for just. As for general information: [Package Restore with Team Foundation Build](https://docs.nuget.org/consume/package-restore/team-build) and [http://blog.davidebbo.com/2014/01/the-right-way-to-restore-nuget-packages.html](http://blog.davidebbo.com/2014/01/the-right-way-to-restore-nuget-packages.html).

We went through this and other similar hassle to find out that we'd burn build minutes humongously every day, so we have the tickets in Online and the build server on-premises (which make dependencies management easier too). 

You may have read these, but I'll add as a general notes to anyone bumping here. I don't know, maybe [Build Futures](http://blogs.msdn.com/b/visualstudioalm/archive/2015/02/12/build-futures.aspx) bring some sanity -- and with regard to .NET in GitHub, I add, it looks like [Appveyor](http://www.appveyor.com/) and [Travis](https://travis-ci.org/recent) are very popular build systems.

**Comment by jthelin** [comment]
@jkamstra -- Thank you for your perseverance in dealing with the problems with switching to using Orleans NuGet packages. 

To make things a little easier for others that may encounter the same problems you did, I have posted some notes in the project wiki about how to convert legacy Orleans .csproj over to use the new Orleans NuGet packages.

https://github.com/dotnet/orleans/wiki/Convert-Orleans-v0.9-csproj-to-Use-v1.0-NuGet

We will also update the Orleans vsix templates to use NuGet packages going forward.

Regarding Hosted TFS build -- i think many people [me included] have had similar teething troubles with getting their build environment set up and working but after that initial time investment things usually run pretty smoothly [so far, for me at least]

**Comment by veikkoeeva** [comment]
:+1:

**Comment by jkamstra** [comment]
Thank you @jthelin and @veikkoeeva for the links. Should be helpful for the next team trying similar.

**Comment by gabikliot** [comment]
Can that issue be now closed and considered resolved, given the new [re-structured Orleans NuGets](http://dotnet.github.io/orleans/NuGets)?
