### ISSUE TITLE
Question: Can stateful grain with blob storage have its state represented as MemoryStream?

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1924]
I like to add a new grain to my service that acts as persistent buffer for data that should be sent to another service which expects blobs. For that end I like the grain to buffer data in a MemoryStream, which is an efficient representation of buffered data which can also be uploaded to blobs very easily (UploadFromStreamAsync). While I can have my grain be stateless grain that interacts with its blob on its own, I prefer to have it a stateful grain such that the grain state is of type MemoryStream. Will the blob storage be able to handle that correctly without serialization? If not, what do you think about adding support to that?

**Comment by ReubenBond** [comment]
This isn't supported by the in-built serializer, but storage providers are responsible for their own serialization, so you can write support for this kind of thing in your own storage provider (which we can host in `OrleansContrib` or even here if it's something others are interested in).

You could even make it 'smart' and support having streams mixed in with other properties, but you'd likely have to implement your own `Stream` sub-type which chained together the grain state's streams as well as serializing the other properties.

Other options:
* Write an application-specific storage provider for this one grain that avoids copying the stream's contents into a buffer on upload and instead directly calls `UploadFromStreamAsync`.
* Avoid storage providers and just read/write the blob as-needed either by overriding `ReadStateAsync`, `WriteStateAsync`, & `ClearStateAsync`, or by calling your own read/write methods directly.

Hope that helps :)

**Comment by AlgorithmsAreCool** [comment]
If you want to just store and load the blobs with the normal grain persistence semantics I think a simple custom storage provider is best. They are pretty easy to implement. But do you actually need the data cached in the grain's memory? How big are these MemoryStreams going to be?

**Comment by Eldar1205** [comment]
Not big. I got useful answers, closing the issue
בתאריך 10 ביול' 2016 10:57,‏ "AlgorithmsAreCool" <notifications@github.com>
כתב:

**Comment by veikkoeeva** [comment]
@Eldar1205 It might interest you that one of the ideas on adding `CancellationToken` in https://github.com/dotnet/orleans/issues/1516 (via the mighty work of @dVakulen) was streaming scenarios. For instance, streaming binary blobs to storage either via a custom provider or in some application specific way.

The public storage provider API does not support streams, but maybe it's worth discussing. The relational one in the makings (https://github.com/dotnet/orleans/pull/1682) internally could do streaming.
