### ISSUE TITLE
Simplify IAsyncObservable/IAsyncObserver API

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#1931]
As discussed in #1916 (Ad-hoc observable streams), there is a desire to simplify/evolve the API (primarily `IAsyncObservable<T>`/`IAsyncObserver<T>`) used for Virtual Streams producers/consumers.

Please read [Orleans Streams Programming APIs](https://dotnet.github.io/orleans/Orleans-Streams/Streams-Programming-APIs) & the relevant API code: 
- [`IAsyncObservable<T>`](https://github.com/dotnet/orleans/blob/master/src/Orleans/Streams/Core/IAsyncObservable.cs)
- [`IAsyncObserver<T>`](https://github.com/dotnet/orleans/blob/master/src/Orleans/Streams/Core/IAsyncObserver.cs)
- [`StreamSubscriptionHandle<T>`](https://github.com/dotnet/orleans/blob/master/src/Orleans/Streams/Core/StreamSubscriptionHandle.cs)
- [`StreamSequenceToken`](https://github.com/dotnet/orleans/blob/master/src/Orleans/Streams/Core/StreamSequenceToken.cs) (less relevant)

Here are my concerns about the current API as it applies to #940 / #1916 ([original comment](https://github.com/dotnet/orleans/pull/1916#issuecomment-231566598)):
- Operations like filtering, seeking, etc, should be provided before obtaining the observable rather than in the `SubscribeAsync` call. We cannot predict or cleanly specify the ways which users may want to query the underlying stream, and those query methods need to be discoverable. For example, maybe the stream doesn't support seeking (maybe it's hot), maybe it supports filtering by prefix, suffix, `string.Contains(x)`, or some complex query. Pushing these requirements to the point where the user obtains the stream allows for much more flexibility. Eventually, maybe we'll have `IAsyncQbservable<T>` and can support shifting expression trees to the most logical point in the cluster.
- `Subscribe` returns an `StreamSubscriptionHandle<T>` which is generic because it supports re-subscription via `ResumeAsync`. I believe resubscription should just be a `SubscribeAsync` call on the original observable. There is no `PauseAsync` method anyhow, only `UnsubscribeAsync`. For reference (as pointed out by @gabikliot), the difference between calling `StreamSubscriptionHandle<T>.ResumeAsync(...)` and calling `IAsyncObservable<T>.SubscribeAsync(...)` is that the former is used during failure recovery to continue an existing subscription.
- `Subscribe` takes a `StreamSequenceToken`, which is cardinal (can be compared with other `StreamSequenceToken`s to determine which one is newer). This doesn't fit for ad-hoc streams, since they may have been created only for that specific call and each one is necessarily unique.

@gabikliot [responded](https://github.com/dotnet/orleans/pull/1916#issuecomment-231569801), saying:

> I think all your concerns re `IAsyncObservable/IAsyncObserver` can/should be solvebale.
> The extra `Subsribe` method can be moved to a sub class: we can create a hierarchy of `IAsyncObservables` (plain, rewinbale, resumable, what ever).
> 
> The difference between resume and subscribe is described here: http://dotnet.github.io/orleans/Orleans-Streams/Streams-Programming-APIs. I think I can safely say that neither of us (me, @jason-bragg and @sergeybykov) like that extra API (Resume). We think its ugly, but it was the only way we could think of to solve the problems we had to solve.
> 
> The main point is (and I hope again that I am expressing everyone's opinion, please correct me if I am wrong): we all think the current streaming API is version 0.7 at best. The API should be improved. The internal implementation is rather robust I would say, but the API is ugly, and we need to improve it, and to support all these other scenarios.
> 
> At the base it is very simple: it is identical to System.Rx just async. So fundamentally I don't think we made a wrong decision . But coming up with one unified API for all the cases was very hard, and this is work in progress.
> 
> I am of a strong opinion that instead of coming up with yet another API (your grain observers) we should improve the current one. And this is where the help of the community, your help, @yevhen's help,  would be highly appropriated.
> 
> Another option is to give up completely on RX, both in virtual and ad-hoc streams and go with something else. I am not an expert on .NET Core but it seems like its new libraries are still immature as of now to be a strong candidate instead of Rx. On the other hand we were promised Rx 3.0, including async support, many years ago, and we are still waiting. So maybe its about time to give up ...
> 
> My suggestion is: lets look at how to evolve the current `IAsyncObservable/IAsyncObserver` to be more fluent, user friendly and support all the different cases. This way we can also maybe impact the future of `System.Rx`.

If we see some more details about Rx 3.0, then we could ensure that our API aligns as much as possible so that we can take full advantage of it. On the other hand, as @gabikliot pointed out, we haven't heard much from the Rx folks in a _long_ time - so we shouldn't hold our breath.

How should we take this forwards? Can we create an API which works nicely for both Virtual Streams & ad-hoc streams?

**Comment by ReubenBond** [comment]
I'll leave discussion to the WIP PR (#1916) for now, rather than forking it.

**Comment by gabikliot** [comment]
>the difference between calling StreamSubscriptionHandle<T>.ResumeAsync(...) and calling IAsyncObservable<T>.SubscribeAsync(...) is that the former is used during failure recovery to continue an existing subscription.

The main reason for Resume is not just for failure recovery but for re-activating the grain. Imagine the grain subscribed once, then it got deactivated and now reactivates. The grain wants to be subscribed, just as it was before, to continue processing events. In the ideal world the grain code should not do anything. Everything should be re-hooked automatically. However, since we support subscribing an arbitrary lambda, we could not persist it. Therefore, we did not know how to re-hook automatically (without limiting what you can subscribe with). The result: you need to provide the subscription function (lambda or what not) again. 
Now the question: why not call SubscribeAsync? Since we support what we call "subscription multiplicity": grain can subscribe multiple times and each one is a separate subscription (with potentiality different sequence token). We have to support multiplicity, otherwise important catch-up and recovery and other usage scenarios will not work. So if we used SubscribeAsync the grain will be subscribed twice, which is not what we want here.
The result is ResumeAsync.

Above is an explanation of how different constrains pushed us to this solution. Would love to see if someone can suggest how to break out from this circle of constrains and come up with a better overall API.

**Comment by ReubenBond** [comment]
@gabikliot I see where you're coming from, thanks for the explanation. I'm porting the PR to see if I can conform to the Virtual Streams API sensibly

**Comment by jason-bragg** [comment]
Picking back up from "WIP: Ad-hoc observables for grains #1916"

I am of the opinion that IAsyncObservable/IasyncObserver should mirror as closely what the RX team prototyped for these which are simply async versions of the observable/observer apis.  This means no filtering or recovery information in these interfaces, and subscribe calls return asynchronously disposable objects.

I also don’t think the IAsyncObservable/IasyncObserver stream processing api pattern should be limited to stream providers.  We should be able to get streams from providers or grains.

This means we’ve a number of issues we’d need to solve:
-	How does recovery work?  How do you ask for a data from a particular point in a stream and how do you know what point to ask for?
-	How does filtering work?

I favor the following patterns:
-	When one requests a stream one gets an asynchronous version of a connectable observable.  Any filtering must be passed in the request for the observable.  Any stream position information must also be passed in this request.
-	If a stream is recoverable, it must pass any recoverability information along with the event.

For instance, a non-recoverable stream from sms stream provider would look like this.

    IAsyncConnectableObservable<int> subscription = sms.GetStream<int>(streamId);
    IAsyncDisposable handlerDisposer = await subscription.SubscribeAsync(ProcessSomeStuff, HandleError, Done);
    IasyncDisposable SubscriptionDisposer await subscription.Conect();

Same pattern would exist for a grain.

Recoverable streams from something like EventHub stream provider would look something like:

    IAsyncConnectableObservable<Recoverable<int>> subscription = eh.GetStream<int>(streamId, token);
    IAsyncDisposable handlerDisposer = await subscription.SubscribeAsync(ProcessSomeStuff, HandleError, Done);
    IAsyncDisposable SubscriptionDisposer await subscription.Conect();
 
Where Recoverable is a class that contains a value and a recovery token.  The nice thing about this is that we can generalize or specialize the token, and support different GetStream calls for different grains and stream providers.
For instance, the event hub stream provider could support the IRecoverableStreamProvider interface, which supports the generic recoverable calls as well as the IStreamProvider interface, which supports the non-recoverable calls (see the sms example), but could also support its own EventHub specific calls that users ok with the event hub dependency could use.
For instance:

    IAsyncConnectableObservable<EHRecoverable<int>> subscription = eh.GetEventHubStream<int>(streamId, token);

Where EHRecoverable has a value and an EventHub specific recovery token that has hub and position data that applications can use.

And/Or

    IAsyncConnectableObservable<EventData> subscription = eh.GetEventHubStream (streamId, token);

This call delivers EventHubs actual EventData with no interpretation.

**Comment by ReubenBond** [comment]
Let's close this and take another look at these APIs as we consider evolving Streams
