### ISSUE TITLE
Where is Orleans SDK on the tutorial On Premise Deployment

### ISSUE THREAD

**Issue by welly87** [dotnet/orleans#1962]
Hi all i'm starting exploring orleans and stumble across this article for deploying on premise
http://dotnet.github.io/orleans/Step-by-step-Tutorials/On-Premise-Deployment

However i can't find Orleans SDK anywhere. Also the build seems didn't produce .\BInaries\OrleansServer

Am i missing something obvious here ?

Any help would be really appreciated. 

Cheers

**Comment by ashkan-saeedi-mazdeh** [comment]
There is no SDK anymore. The NuGet package Microsoft.Orleans.Host is used to get the server executable.  I'm not however sure where the powershell scripts are atm. but even without them, you can build a Orleans host application and just copy contents of the folder to target machine and run it.

**Comment by sergeybykov** [comment]
PowerShell scripts are in https://github.com/dotnet/orleans/tree/master/misc/scripts/RemoteDeployment.

**Comment by ashkan-saeedi-mazdeh** [comment]
@sergeybykov  Maybe we should make a NuGet package for them or add them to `Microsoft.Orleans.Host` ? After that I'll take care of the docs.

**Comment by sergeybykov** [comment]
I'm not sure about that. There's so many, and better, ways to deploy binaries to remote machines. This is just the one we used for running tests at some point. I don't think it deserves a special promotion.

**Comment by ashkan-saeedi-mazdeh** [comment]
So I'll update the docs and just mention some stuff exists there but recommended approach is that the developer finds the best deployment option. Good? @sergeybykov

**Comment by sergeybykov** [comment]
Good.

**Comment by welly87** [comment]
@ashkan-saeedi-mazdeh @sergeybykov 
Thanks a lot for the explanation. I will look forward on the updated docs. 

Cheers
