### ISSUE TITLE
v1.3.0 Release

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#1972]
For 1.3.0 we have the following out standing PR.

1. [x] Update to WindowsAzure.Storage 7.0.0 #1968 (testing)
2. [ ] GSI protocol for multi-clusters  #1800

The plan is to release 1.3.0-beta once #1968 is merged, and 1.3.0-beta2 or 1.3.0-rc after #1800 is in.

Up until 1.3.0-rc other PRs will be merged unless there's a serious reason to hold off.

**Comment by ashkan-saeedi-mazdeh** [comment]
Can we have @veikkoeeva's  relational storage in as well?

**Comment by jdom** [comment]
@ashkan-saeedi-mazdeh 
> Up until 1.3.0-rc other PRs will be merged unless there's a serious reason to hold off.

so certainly. I'm pretty sure it'll be merged before we release RTM (or RC)... I'm planning to create the beta release really soon, not sure if it will make it in time or not, I'm not that familiar with that PR, so it's not up to me.

**Comment by ashkan-saeedi-mazdeh** [comment]
Great then @jdom

**Comment by veikkoeeva** [comment]
@ashkan-saeedi-mazdeh Regarding https://github.com/dotnet/orleans/pull/1682, I'm quite pressed on time currently. I can't unfortunately work that many hours to ensure an actual setup and usage scenario function as intended in addition to tests (I've tried the storage provider when it was less complete, on the first weeks of June and it worked then). See discussion point at https://github.com/dotnet/orleans/pull/1682#issuecomment-235036195.

I'm not sure if having the tests pass is sufficient criteria to roll this in. This week I likely can fix little things such as misinforming comments and quickly see if I can overcome the dependency injection related problem on custom built Nugets and using them in the storage samples.

**Comment by ReubenBond** [comment]
Could we please include #1938, also? I assume we're cherry-picking commits rather than forking from current master.

**Comment by jdom** [comment]
We are not cherry picking anything ATM. It will be the current master. If we need to do an RC, then after that we'll cherry pick if needed before RTM, but I'm not sure we'll need that

**Comment by ashkan-saeedi-mazdeh** [comment]
@veikkoeeva  Don't push yourself man! That's not too urgent for me at all.

**Comment by veikkoeeva** [comment]
@sergeybykov, @jdom Should https://github.com/dotnet/orleans/issues/1998 be fixed first?

**Comment by jdom** [comment]
@veikkoeeva ideally, yes :)
It is not a *newly introduced* bug, though, so releasing without it would be unfortunate, but not blocking the release I assume.

**Comment by ashkan-saeedi-mazdeh** [comment]
<IMHO>  @veikkoeeva  As @jdom  mentioned, I guess since this was already the case, at least merging this is an improvement and based on the state of the previous SQLUtils, It's not that small improvement either so maybe it's good to merge this and we test it and then fix that issue as well. </IMHO>

**Comment by veikkoeeva** [comment]
@ashkan-saeedi-mazdeh Hmm, I got a bit delayed, but I think I can include in the provider something along the lines

    public static string ExtractBaseClass(string typeName)
        {
            var genericPosition = typeName.IndexOf("`", StringComparison.OrdinalIgnoreCase);
            if(genericPosition != -1)
            {
                var split = typeName.Split(new[] { '[', ']' }, StringSplitOptions.RemoveEmptyEntries);
                return split[0] + string.Join(",", split.Skip(1).Where(i => i.Length > 1).Select(i => string.Format($"[{i.Substring(0, i.IndexOf(',', i.IndexOf(',') + 1))}]")));
            }

            return typeName;
        }

to extract a consistent variable (untested code, not optimized). Hence averting a potential disaster. :)

**Comment by ashkan-saeedi-mazdeh** [comment]
@veikkoeeva  Nice! Great job!

**Comment by tsibelman** [comment]
@sergeybykov when do you think 1.3.0 release will be finished ?

**Comment by sergeybykov** [comment]
We are down to one last piece of feedback for https://github.com/dotnet/orleans/pull/1800. After that we'll run performance and reliability tests in order to release a Beta2 or maybe an RC of 1.3.0.

**Comment by veikkoeeva** [comment]
I'll add https://github.com/dotnet/orleans/pull/2113 too, which would be nice to get included. :)

**Comment by sergeybykov** [comment]
@2113 is already in.

**Comment by sergeybykov** [comment]
1.3.0 has been released.
