### ISSUE TITLE
Remote and Cluster Configuration

### ISSUE THREAD

**Issue by welly87** [dotnet/orleans#1979]
Hi all, 

Based on the tutorial and examples, seems that both guide only refer to localhost deployment where client and server in the same node. 

Is there any sample configuration for remote silo and also cluster setting ?

**Comment by ashkan-saeedi-mazdeh** [comment]
@welly87 
Aren't the ones linked here the ones you are looking for?
http://dotnet.github.io/orleans/Orleans-Configuration-Guide/

**Comment by welly87** [comment]
yes, i have already read that but still no luck . 

here's the configuration on the server

<?xml version="1.0" encoding="utf-8"?>
<OrleansConfiguration xmlns="urn:orleans">
  <Globals>
    <SeedNode Address="localhost" Port="11111" />
    <Liveness LivenessType ="MembershipTableGrain" />
  </Globals>
  <Defaults>
    <Networking Address="localhost" Port="11111" />
    <ProxyingGateway Address="localhost" Port="30000" />
  </Defaults>
</OrleansConfiguration>

and here's the configuration on the client. 

<ClientConfiguration xmlns="urn:orleans">
  <Gateway Address="192.168.1.6" Port="30000"/>
  
  <Tracing DefaultTraceLevel="Info" TraceToConsole="false" TraceToFile="{0}-{1}.log" BulkMessageLimit="1000">
    <TraceLevelOverride LogPrefix="Runtime" TraceLevel="Info" />
    <TraceLevelOverride LogPrefix="Application" TraceLevel="Info" />
    <TraceLevelOverride LogPrefix="AssemblyLoader" TraceLevel="Warning" />
  </Tracing>
  <Statistics MetricsTableWriteInterval="300s" PerfCounterWriteInterval="30s" LogWriteInterval="300s" WriteLogStatisticsToTable="true" StatisticsCollectionLevel="Info"/>
  <Messaging ResponseTimeout="30s" ClientSenderBuckets="8192" MaxResendCount="0"/>
</ClientConfiguration>

However the client throw exception 

An unhandled exception of type 'Orleans.Runtime.SiloUnavailableException' occurred in mscorlib.dll

Additional information: The target silo became unavailable for message: Request *cli/3ca1dcb3@d7b60f9a->S192.168.1.6:30000:0TypeManagerId@S00000011 #2: global::Orleans.Runtime.ITypeManager:GetTypeCodeMap(). Target History is: <S192.168.1.6:30000:0:TypeManagerId:@S00000011>. See https://aka.ms/orleans-troubleshooting for troubleshooting help.

Any ideas ?

**Comment by ashkan-saeedi-mazdeh** [comment]
Does the Silo start successfully?
Can you ping the IP you put in the client and is the port 30000 TCP is open in the firewarll of the server?

**Comment by welly87** [comment]
@ashkan-saeedi-mazdeh 

finally it connecting. Here's the blog post on the setup i have used. Is that the correct way ?

https://weltam.wordpress.com/2016/07/25/getting-started-with-microsoft-orleans/

**Comment by galvesribeiro** [comment]
@welly87 if you use any membership provider like Azure Table or SQL, you don't need a Seed silo. 
This is my Silo config for AzureTableStorage(replave with your connection strings):

```
<?xml version="1.0" encoding="utf-8"?>
<OrleansConfiguration xmlns="urn:orleans">
  <Globals>
    <BootstrapProviders>
      <Provider Type="OrleansDashboard.Dashboard" Name="Pay Insights - Cluster Health" Port="9696" Username="pi" Password="pimon" />
    </BootstrapProviders>
    <Liveness LivenessType="AzureTable" />
    <SystemStore SystemStoreType="AzureTable" DeploymentId="PI-Switch" DataConnectionString="YOUR_CONNECTION_STRING"/>
    <StorageProviders>
      <Provider Type="Orleans.Storage.AzureTableStorage" Name="AzureStore" DataConnectionString="YOUR_CONNECTION_STRING" />
    </StorageProviders>
    <Messaging ResponseTimeout="1m" />
    <Application>
      <Defaults>
        <Deactivation AgeLimit="60m"/>
      </Defaults>
    </Application>
  </Globals>
  <Defaults>
    <Networking Address="" Port="11111" />
    <ProxyingGateway Address="" Port="7777" />
    <Tracing DefaultTraceLevel="Info" TraceToConsole="true" TraceToFile="{0}-{1}.log">
      <TraceLevelOverride LogPrefix="Application" TraceLevel="Info" />
    </Tracing>
    <Statistics MetricsTableWriteInterval="30s" PerfCounterWriteInterval="30s" LogWriteInterval="300s" WriteLogStatisticsToTable="true"/>
  </Defaults>
</OrleansConfiguration>
```

**Comment by welly87** [comment]
@galvesribeiro 
thanks for this information. however we don't host our service on azure. we host orleans on premise. 

cheers

**Comment by ashkan-saeedi-mazdeh** [comment]
@welly87  Yes the configuration of Network interfaces in your config is correct.
As @galvesribeiro  mentioned, If you want to have a reliable Orleans cluster then the membership tables should be stored in reliable storage. If you use a silo as primary then if that specific silo fails, the whole cluster will be unavailable. 
If you host on Premise then you should install either install SQLServer and use that for membership or open an azure account to use Azure Table. The Azure option will be free as well since storage will not be much so the free 25$ free credit per month will be enough.
I guess SQLServer express is good enough too.

**Comment by galvesribeiro** [comment]
@welly87 it is just an example of configuration. You can change the "SystemStore" and "Liveness" to reflect your membership provider.

If you are on-premises, I would suggest the easy way which is SQL Server as @ashkan-saeedi-mazdeh  suggested. You have other options available like ZooKeeper, MySQL, etc, and you can even create your own MembershipProvider (if you do, please share on OrleansContrib :smile: ) as it is easy and well documented.

The point is, you must have a central place to keep you membership information (and your grain state if you have any).
