### ISSUE TITLE
OrleansAzureUtils has a static dependnecy on OrleansRuntime

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#198]
This brings OrleansRuntime to any client that uses AzureClient. There seem to be two options.
1. Split OrleansAzureUtils into OrleansClientAzureUtils & OrleansRuntimeAzureUtils.
2. Remove the static dependency and make OrleansAzureUtils dynamically load OrleansRuntime only when AzureSilo is instantiated.

**Comment by gabikliot** [comment]
Seems like given [the new re-structuring of Orleans NuGets](http://dotnet.github.io/orleans/NuGets) we should go with option 1. We already have a separate NuGet for client and server hosting, so if we split the OrleansAzureUtils.dll into OrleansClientAzureUtils.dll & OrleansRuntimeAzureUtils.dll and include the appropriate one in the appropriate NuGet package, we won't introduce any new complications or dependencies or NuGets for users, while avoiding the potential complications of dynamic loading of OrleansRuntime.

**Comment by gabikliot** [comment]
Why did u close that ? I thought it is still an open and valid concern?

**Comment by sergeybykov** [comment]
My mistake. Need more sleep.

**Comment by sergeybykov** [comment]
As we split AzureUtils into separate modules, this will get resolved.

**Comment by sergeybykov** [comment]
Resolved via #3833.
