### ISSUE TITLE
"Could not load type 'Orleans.PublicOrleansTaskExtentions'..." error

### ISSUE THREAD

**Issue by realrover** [dotnet/orleans#1983]
Hi guys,
I just started to explore Orleans and tried to run "Hello, world" sample when client and host are in separate executables. However, I'm getting an error on the client side when calling Console.WriteLine(hello.SayHello("First").Result);

Full error:
"Could not load type 'Orleans.PublicOrleansTaskExtentions' from assembly 'Orleans, Version=1.2.3.0, Culture=neutral, PublicKeyToken=null'.":"Orleans.PublicOrleansTaskExtentions"

I guess some runtime component maybe is missing, but what is this? Win 7, VS 2015.  Please help. Thanks.

**Comment by malavika1** [comment]
I also had this issue because my NuGet packages were not all the same version across the solution. Maybe try checking that.

**Comment by realrover** [comment]
Yup, it helped. Thanks!
