### ISSUE TITLE
Build.cmd fails to build pre-release nuget packages in diff OS locales

### ISSUE THREAD

**Issue by jdom** [dotnet/orleans#1984]
The reason is that [CreatePackages.bat line 47](https://github.com/dotnet/orleans/blob/81776b5a5a0d4a6306810671e71a753325adad88/src/NuGet/CreateOrleansPackages.bat#L47) uses the MS-DOS `date` and `time` commands to generate a dev string based on the current date and time (such as Microsoft.Orleans.Client.1.3.0-Dev201607221711.nupkg).
Nevertheless those commands are language and locale dependent.
In Windows using default en-US settings, date returns `Mon 07/25/2016` and time `09:56 AM`.

When @veikkoeeva tried to run this using fi-FI settings, he got `Dev0165.7.1934` generated, which is invalid according to SemVer (and as you can see it shares nothing of the intended approach in en-US).

Here's some suggestions for making it locale independent: http://stackoverflow.com/questions/203090/how-to-get-current-datetime-on-windows-command-line-in-a-suitable-format-for-us

**Comment by veikkoeeva** [comment]
@jdom Maybe an intermediary fix could be calling a PowerShell script to return the date?

A tip for a workaround suggested by @jdom at Gitter: hardcode the date to `201607221711` (or some other appropriate value) to get the packets build locally.
