### ISSUE TITLE
Exception when receiving stream message

### ISSUE THREAD

**Issue by TrexinanF14** [dotnet/orleans#1988]
I've got a class that is registered to receive messages from the simple messaging stream, but when the message gets passed to the receiver, I get this exception:

Orleans.Runtime.GrainExtensionNotInstalledException: Extension not installed on grain Server.Grains.Channel.ChannelAgent attempting to invoke type Orleans.Streams.OrleansCodeGenStreamConsumerExtensionMethodInvoker from invokable Orleans.Runtime.ActivationData

I didn't think that extension methods were even directly accessible from user code, and I know I'm not using them myself. I assume I have something misconfigured, but the error isn't particularly helpful. 

My project was previously using 1.2.1 and the stream was working correctly, but this showed up when I upgraded to 1.2.3.

**Comment by ReubenBond** [comment]
@TrexinanF14 in the consumer grain's `OnActivateAsync` method, are you calling either `ResumeAsync` or `SubscribeAsync`?

**Comment by TrexinanF14** [comment]
No, the ```SubscribeAsync``` happens in a method call. I didn't call ```ResumeAsync```, which appeared to be my problem. I realized after the fact that my testing hadn't involved passing a message via stream to a deactivated grain.

Thanks for your help @ReubenBond. Next time I'll try to RTFM properly. That said, could this error message be improved?
