### ISSUE TITLE
Data is potentially orphaned in storage providers, because Orleans passes the fully qualified type for generic grains

### ISSUE THREAD

**Issue by veikkoeeva** [dotnet/orleans#1998]
This bug make it easy to unadvertedly orphan potentially business critical data.

When grains are generic, Orleans passes a fully qualified grain type as a parameter to storage providers. 
An example from https://github.com/dotnet/orleans/pull/1682#issuecomment-235536652

> Test.Implementation.Person`1[[System.Double, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]

This creates a problem for every storage providers that relies on this information to find storage using the type given by Orleans. Using the given example, perhaps more sensible format would be 

> Test.Implementation.Person`1[[System.Double]]

**Comment by shayhatsor** [comment]
IMHO #1075 was a good solution for this issue. It wasn't approved.

**Comment by veikkoeeva** [comment]
This is currently remedied in #1682 with the following piece of code

```
/// <summary>
        /// Extracts a base class from a string that is either <see cref="Type.AssemblyQualifiedName"/> or
        /// <see cref="Type.FullName"/> or returns the one given as a parameter if no type is given.
        /// </summary>
        /// <param name="typeName">The base class name to give.</param>
        /// <returns>The extracted base class or the one given as a parameter if it didn't have a generic part.</returns>
        private static string ExtractBaseClass(string typeName)
        {
            var genericPosition = typeName.IndexOf("`", StringComparison.OrdinalIgnoreCase);
            if(genericPosition != -1)
            {
                //The following relies the generic argument list to be in form as described
                //at https://msdn.microsoft.com/en-us/library/w3f99sx1.aspx.
                var split = typeName.Split(BaseClassExtractionSplitDelimeters, StringSplitOptions.RemoveEmptyEntries);
                return split[0] + string.Format($"[{string.Join(",", split.Skip(1).Where(i => i.Length > 1 && i[0] != ',').Select(i => string.Format($"[{i.Substring(0, i.IndexOf(',', i.IndexOf(',') + 1))}]")))}]");
            }

            return typeName;
        }
```

**Comment by veikkoeeva** [comment]
On further note, having the version number likely helps writing migration logic. The persistence providers should deal with it, though.

**Comment by shayhatsor** [comment]
Does it include version information of non .net types? because if it doesn't, I don't see how it's usable.

**Comment by ElanHasson** [comment]
What would be n example of a "non .net type"?

**Comment by shayhatsor** [comment]
i meant that i wasn't sure that the full version is included in user defined types, but it is. so the version is usable and relevant, like @veikkoeeva mentioned.

**Comment by ReubenBond** [comment]
I'm not entirely sure what to do about this without orphaning existing data.

We introduced `RuntimeTypeNameFormatter` fairly recently. That can be used to get a non-version-dependent type string.

One option would be a setting to choose between `type.FullName` and `RuntimeTypeNameFormatter.Format(grainType)` where the default is to use the new behavior (orphaning existing data) but which allows assembly versions to vary.

Another alternative is to try to read the new key (no version) and fall back to the old key (with version). That adds latency and complexity, but at least no data is orphaned.

Thoughts?

**Comment by veikkoeeva** [comment]
@ReubenBond I think there is a change to consider the linked issues and others when solving this.

As a premise: assembly version data is potentially useful at least in scenarios where the system contains both new and old version of types and the old version needs transformation to a new type. This situation can occur when there are renames, bug fixes (e.g. a mistake in data shape, or this case here -- being defensive with data) or other backwards incompatible transformations that need temporary bridge code (to be removed in some later update). It would be useful to use the new function you mention that would give information for decision making without the user needing "to probe" (in custom code) this from the data.

But if one is already doing this, one case could be also changing the format in which data is stored. I could easily imagine a situation where cold data is in some other format than warm data or perhaps one wants to encrypt and decrypt data before going to the store. This hot-cold distinction means also picking some data separate from others based on some parameters.

I don't think every provider can or need to support these things. An option could be to introduce a new constructor that takes some constructs as injected from the DI container and potentially allow switching during application running. The [AdoNetStorageProvider](https://github.com/dotnet/orleans/blob/master/src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/AdoNetStorageProvider.cs#L145) would benefit from a possibility to have a constructor that could inject the things you see in the constructor. I.e. the functionality to choose (de)serializer based on grain state parameters and potentially whatever logic the user would want to ignore if the logic could be easily injected. The container, for example, could have a default implementation like now (see [StorageSerializationPicker](https://github.com/dotnet/orleans/blob/918b6c1b8ec8a944047ad767371e41c2e756bd5d/src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/StorageSerializationPicker.cs)), but it could be also user implemented and injected).

It looks to me one could inject defaults in the future and for now leave the current ones as-is when going the DI route.

**Comment by ReubenBond** [comment]
Thanks, @veikkoeeva :)

When you mention linked issues, are you primarily talking about #1075? 
@jason-bragg, do you think there's scope to update the interface for a modernized provider model to accept `Type grainType` instead of `string grainType`?

**Comment by jason-bragg** [comment]
@ReubenBond My preference for future storage features is to allow the application layer to have more control over the data identity rather than mapping it from the grain itself.  Data should, of course be able to be mapped to the grainId but it would not 'have' to be and how it's mapped should be modifiable by the application.  Debatable, I'm sure, but this is my current view. :)

**Comment by veikkoeeva** [comment]
@ReubenBond That is one way of passing more information to the state provider, but I mean this as something could handle migrations and other things too. The ADO.NET provider already tests for that by changing the (de)serializer (but it could do also other transformation, any transformation). It bothers me a bit there isn't a clear, general way to reshape data and storage specific things. This mightn't be such a thing for every provider, but maybe to some.

@jason-bragg It looks to me the problem is to know [which kind of a mapping one has](https://en.wikipedia.org/wiki/Bijection,_injection_and_surjection). I see it like `(format, otherThings) = SerializationParametersChoice(serviceId, storageProviderInstanceName, grainType, grainReference, grainState, params)`. One draft of it [here](https://github.com/dotnet/orleans/blob/master/src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/IStorageSerializationPicker.cs). Had to start somewhere and not make it too radical (and it'd be useful to discuss how to make this behave better with DI). In general the idea here is to choose things like (de)serializer and match it to DB capabilities (e.g. JSON is mapped to besponse JSON type or string, binary serializer go to binary blobs etc.). If I may, if there will be changes, it'd be interesting to discuss streaming (patching past the end) and sharding (vertical and horizontal) too and what kind of changes would be needed. I haven't done thinking in great depth in this space, but feels shouldn't take too much changes to the current model.
