### ISSUE TITLE
How to change the output format of Grain Logger

### ISSUE THREAD

**Issue by lyjdamzwf** [dotnet/orleans#1999]
I couldn't find a way to config the format of grain logger.
By default the grain logger uses UTC/GMT time zone and it's not what I want.
I knew orleans provides a ILogConsumer for customizing, but seems there will be two duplicate output if I do this (orleans log output and my implementation of ILogConsumer).

And currently, I just want to change the default timezone of grain logger for corresponding to the local time.

**Comment by jdom** [comment]
You can avoid the default logger and just have your custom one configured, if that helps.
