### ISSUE TITLE
Server unresponsive

### ISSUE THREAD

**Issue by mbernard** [dotnet/orleans#2004]
Hi,

I'm running an Orleans cluster on Azure cloud services. Everything works fine with my staging environment. But when I push in production, (where I have a much much bigger work load), my servers fall unresponsive after a few hours. I talked with Azure support, and it seems the issue is related Orleans taking all the memory at some point. 

Is this a know issue? Do you have any advice?

thanks

**Comment by jdom** [comment]
It's nothing inherent to Orleans itself that is taking a lot of memory, as this is running in various production environments that have a lot of load, as well as we do nightly load tests where we saturate the silos for a long time.
Nevertheless I'd recommend you take a memory dump of some of these silos and see what they are holding. A thing to keep in mind is that Orleans can have thousands/millions of active grains, so what kind of state they hold is important, as sometimes you might have unnecessary duplication of objects in them. At first glance it could be seen as "Orleans" is holding references to these, but I'm pretty sure you'll discover it is your own grains who reference these big chunks of memory.
Once you find exactly what is taking so much memory, then maybe we can suggest how to workaround them.

**Comment by shayhatsor** [comment]
Have you followed the docs about [Configuring-.NET-Garbage-Collection](http://dotnet.github.io/orleans/Advanced-Concepts/Configuring-.NET-Garbage-Collection)?
Do silos actually crash or just become very slow?
