### ISSUE TITLE
Port examples to use publicly available Nuget packages

### ISSUE THREAD

**Issue by veikkoeeva** [dotnet/orleans#203]
The examples doesn't seem to be using the publicly available Nuget 1.0.3 packages. I'll open an issue a submit something today. If it's all right, later some more.

**Comment by gabikliot** [comment]
@veikkoeeva ported the HellowWorld example, to use Nugets in #204.
https://github.com/dotnet/orleans/tree/master/Samples/HelloWorldNuget
