### ISSUE TITLE
'Response did not arrive on time in 00:00:30 for message ...' when using SQL Server cluster membership

### ISSUE THREAD

**Issue by d-loring** [dotnet/orleans#2033]
I have an orleans client and server (1.2.2) configured to use SQL Server for cluster membership.  When the pair are started in standalone mode, e.g. ClusterConfiguration.LocalhostPrimarySilo() / ClientConfiguration.LocalhostSilo() everything works fine.  However, when the pair are started with a configuration that uses SQL Server for membership data, **the following exception is thrown**:

Response did not arrive on time in 00:00:30 for message: Request S10.10.20.7:22222:208397610_grn/77FAD497/00000000@f22d7b82->S10.10.20.7:22222:208397610_grn/EB2C0203/00000000@c2d5e78e #130: global::Draco.VSMConnection.IS4586Observer:OnReceive(). Target History is: S10.10.20.7:22222:208397610:*grn/EB2C0203/00000000:@c2d5e78e
Exception = System.TimeoutException: Response did not arrive on time in 00:00:30 for message: Request S10.10.20.7:22222:208397610_grn/77FAD497/00000000@f22d7b82->S10.10.20.7:22222:208397610_grn/EB2C0203/00000000@c2d5e78e #130: global::Draco.VSMConnection.IS4586Observer:OnReceive(). Target History is: S10.10.20.7:22222:208397610:*grn/EB2C0203/00000000:@c2d5e78e
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Draco.VSMConnection.VSMEndpoint.<>c__DisplayClass7_0.<<RegisterReceiver>b__0>d.MoveNext() in C:\dev\dracosoft\draco\Plugins\VSMConnection\VSMEndpoint.cs:line 81

**The clustered server configuration is as follows:**

Configuration = new ClusterConfiguration()
            {
                Globals =
                {
                    ResponseTimeout = TimeSpan.FromSeconds(30),
                    LivenessType = GlobalConfiguration.LivenessProviderType.SqlServer,
                    ReminderServiceType = GlobalConfiguration.ReminderServiceProviderType.SqlServer,
                    DeploymentId = "DracoSilo",
                    DataConnectionString = "Data Source=dracodb;Initial Catalog=draco;User ID=sa;Password=*****",
                    AdoInvariant = "System.Data.SqlClient"
                }
            };
            Configuration.AddMemoryStorageProvider("PubSubStore");
            Configuration.Globals.RegisterStorageProvider<CassandraStorageProvider>("Default", new Dictionary<string, string>
                {
                    { "Database", "draco" },
                    { "ConnectionString", "dracodb" }
                });
            //Stream providers
            Configuration.AddSimpleMessageStreamProvider("Default");

```
        //Dependency injector
        Configuration.Defaults.StartupTypeName = typeof(DracoConfigureServices).AssemblyQualifiedName;

        Configuration.Defaults.Port = 22222;
        Configuration.Defaults.ProxyGatewayEndpoint = new IPEndPoint(IPAddress.Any, 30000);
```

**and the clustered client configuration is as follows:**

var config = new ClientConfiguration()
                {
                    ResponseTimeout = TimeSpan.FromSeconds(30),
                    GatewayProvider = ClientConfiguration.GatewayProviderType.SqlServer,
                    DeploymentId = "DracoSilo",
                    DataConnectionString = "Data Source=dracodb;Initial Catalog=draco;User ID=sa;Password=*****",
                };
                config.AddSimpleMessageStreamProvider("Default");

**Does anything look odd about this configuration?**

**Comment by veikkoeeva** [comment]
@d-loring Can you connect to the DB (using, e.g. VS or Management Studio) using the connection string Orleans uses also? There might be a case the ports between Orleans cluster or clients aren't open.

Also, latest stable is [version 1.2.3](https://www.nuget.org/packages/Microsoft.Orleans.OrleansRuntime/), you should definitely be using it.

**Comment by d-loring** [comment]
Yes, I can connect to the database from the orleans server.  When I set up multiple servers, they do share the load, so I know the connection is not the problem.  I believe it is related to streaming data; when no client connects, the servers stay alive, however, when a client connects and listens to the streams, the server throws the exception.

**Comment by veikkoeeva** [comment]
@d-loring The current relational DB functionality does not implement streaming and there isn't a link between relational and in-memory pubsub. It looks like `.LocalhostPrimarySilo()` sets up the systems in general so that your scenario works locally.

If I read your configuration correctly, you are trying to give to your in-memory storage provider the connection strings to your database. This won't work, since in-memory storage provider is an in-memory one and doesn't use any specific storage. I don't have the details at hand currently, but in-memory storage is configured differently. You could try to omit the streaming and the storge configuration and see if the configuration works then. 

From that strack trace I don't see anything specifically related to relational system nor can I see more than that observer couldn't read response in time. You could try to increase logging level to `Verbose3` and let's see if it reveals something.

**Comment by d-loring** [comment]
I omitted the configuration for the grain storage provider.  I am using a cassandra storage provider to persist grain state.  I see now that the in-memory storage provider is used for pubsub storage, which won't work in this configuration.  I'll try with the sql server connection instead.
