### ISSUE TITLE
Should the Installation section inside "README.md" file be updated?

### ISSUE THREAD

**Issue by fishjimi** [dotnet/orleans#2035]
In README.md :
> Installation is performed via NuGet. There are several packages, one for each different project type (interfaces, grains, silo, and client).
In the grain interfaces project:
PM> Install-Package Microsoft.Orleans.Templates.Interfaces
In the grain implementations project:
PM> Install-Package Microsoft.Orleans.Templates.Grains

In [Orleans NuGet Packages of Orleans Documentation
](http://dotnet.github.io/orleans/NuGets)

> There are 4 key NuGet packages you will need to use in most scenarios:
Microsoft.Orleans.OrleansCodeGenerator.Build
PM> Install-Package Microsoft.Orleans.OrleansCodeGenerator.Build 
Build support for grain interfaces and implementation projects. Add it to your grain interfaces and implementation projects to enable code generation of grain references and serializers. **Microsoft.Orleans.Templates.Interfaces** and **Microsoft.Orleans.Templates.Grains** packages are **obsolete** and provided only for backward compatibility and migration.

It let me confused....

**Comment by ashkan-saeedi-mazdeh** [comment]
@fishjimi  definitely it should, If you feel doing so, update the readme file based on the actual docs and submit a PR.

Thank you for bringing this into attention.

**Comment by fishjimi** [comment]
@ashkan-saeedi-mazdeh thanks for your suggestion ,I will help to update the docs.
