### ISSUE TITLE
GrainClient.Initialize fails due to UnobservedExceptionsHandlerClass.SetUnobservedExceptionHandler

### ISSUE THREAD

**Issue by danvanderboom** [dotnet/orleans#2036]
I'm being bit by UnobservedExceptionsHandlerClass.SetUnobservedExceptionHandler being static and rejecting second calls.

I have my test OrleansHost project calling GrainClient.Initialize once in the console client, and once within an ITelemetryConsumer implementation which is defined in the same console app test project. The second time I call GrainClient.Initialize, it's running within the context of the second AppDomain. Do static type elements bleed across AppDomains in .NET? (The answer I'm seeing is yes here.)

Or should I only be initializing GrainClient once across all AppDomains in an assembly?

When I initialize it only once, I get {"Runtime is not initialized. Call Client.Initialize method to initialize the runtime."} in OrleansHostWrapper (within 2nd AppDomain), even though I called Client.Initialize in my Program.cs (1st AppDomain)... to kick off some work in the cluster (starting a simulator to generate some activity).

When I call GrainClient.Initialize in both places (from both AppDomains), I get: {"Calling SetUnobservedExceptionHandler the second time."}

Does SetUnobservedExceptionHandler need to produce an exception, rather than silently disregarding the second attempt to add an error handler which is already in place, or logging a Verbose message about it?

Is there some other reason not to allow GrainClient to be initialized for different AppDomains or contexts within the same .NET program/assembly?

My telemetry consumer is attempting to publish to some virtual streams; and to get access to those, it needs to go through the GrainClient (right?).

I'm guessing I might be able to get around this by using the XML config files, separating the various GrainClient components into different assemblies. But now that I've learned Orleans is leaning toward the code-based config approach going forward, I don't want to have to mess with XML unless I have to. (Code-based config [with Intellisense] is so much more intuitive and discoverable.)

Any ideas on what my best approach might be? Recommended use of GrainClient in these scenarios? How best to package and include my ITelemetryConsumer implementation? How to reason about the context that extensions like Orleans consumers and providers run in?

**Comment by danvanderboom** [comment]
AppDomain.Current.FriendlyName shows "OrleansHost", the explicitly created AppDomain, based on the OrleansHost project template, when I attempt to initialize GrainClient a 2nd time. And yet, the static members must be shared across AppDomains because a conflict is experienced in UnobservedExceptionsHandlerClass. (Unless Orleans somehow marshals calls into a different AppDomain prior to calling SetUnobservedExceptionHandler. This seems unlikely.)

If rejecting subsequent calls to SetUnobservedExceptionHandler is necessary, should it be tracked by AppDomain instead of globally, such that the 1st call that comes from each AppDomain is allowed, and each can have their own exception handler? This would suggest a non-static implementation of these pieces.

This is also a big guess on my part. I'm more interested to hear from those with more knowledge of Orleans' inner workings than me.

**Comment by veikkoeeva** [comment]
@danvanderboom Not seeing your code, but would this help: [Static Fields in AppDomain](http://stackoverflow.com/questions/4298913/static-fields-in-appdomain) or [Static Variable Instances and AppDomains, what is happening?](http://stackoverflow.com/questions/9806372/static-variable-instances-and-appdomains-what-is-happening) (perhaps tangentially interesting [Don't lock on marshal-by-bleed objects](http://joeduffyblog.com/2006/08/21/dont-lock-on-marshalbybleed-objects/)).

**Comment by danvanderboom** [comment]
@veikkoeeva Very useful links, thank you. It seems AppDomains are actually broken in .NET, or at least designed poorly, in that one regard of allowing marshal-by-bleed objects. Seems like a great way to break the isolation AppDomains were supposed to provide.

The solutions all seem to involve changing the offending class with static members, making it inherit from MarshalByRefObject, adding instance methods to access the underlying static member, etc. There doesn't seem to be anything I can do from my calling code to get around this, at least not that I can think of yet.

I can separate OrleansHost from the client that calls into an Orleans grain to start up some activity there (put them in separate processes), but if I needed to get GrainClient access from two different Orleans extensions, I'm guessing I'd be right back in the same position where it will fail as long as they're loaded into the same process, even if they're defined in different assemblies and loaded into separate AppDomains.

Steps to reproduce:

1. Create new Orleans project using the VS template: grain interfaces project, grains project, and OrleansHost console project.
2. In the OrleansHost project, add two different ITelemetryConsumer implementations, and register both of them with Orleans' LogManager.TelemetryConsumers.
3. In both custom telemetry consumer implementations, initialize GrainClient. (This should fail.)
4. If the previous step doesn't fail: get a virtual stream provider, get a virtual stream reference, and publish a message to that virtual stream in both telemetry consumers. (Goal.)

A variation of this would be to try initializing and using GrainClient from both a custom telemetry consumer and a custom storage provider. Any scenario where 2+ extensions will be loaded into the same Orleans host process and need access to GrainClient could be a problem.

Orleans is moving toward supporting CoreCLR, DI, etc., and in this refactoring, some or all of these static classes and static members can go away, and we can achieve real isolation by avoiding statics. Until then, I need a temporary solution. 

If we can only have one functional GrainClient per process, I'm tempted to route all GrainClient calls through some kind of singleton proxy where only one GrainClient is setup and used to satisfy all requests coming from various consumers, providers, and other Orleans extensions.

**Comment by gabikliot** [comment]
The 2nd time you call `GrainClient.Initialize` (the one you make fro within ITelemetryConsumer implementation) must be done within a new app domain. You are simply creating both `GrainClient` inside the same app domain. App domains are not created automatically (except the 1st, default one, which is just inside your main). 
Create  a new app domain, INSIDE the code that runs INSIDE that app domain call `GrainClient.Initialize`.

**Comment by danvanderboom** [comment]
@gabikliot I am calling GrainClient.Initialize from two different AppDomains, but they are loaded in the same process, and static members "bleed" across AppDomains in the same process _unless they inherit from MarshalByRefObject_, as explained here:
http://stackoverflow.com/questions/4298913/static-fields-in-appdomain
http://joeduffyblog.com/2006/08/21/dont-lock-on-marshalbybleed-objects/

**Comment by danvanderboom** [comment]
@gabikliot The 2nd AppDomain being created was code written by the Orleans VS template for the OrleansHost project.

`AppDomain hostDomain = AppDomain.CreateDomain("OrleansHost", null, 
    new AppDomainSetup
    {
        AppDomainInitializer = InitSilo,
        AppDomainInitializerArguments = args,
    });`

That InitSilo runs in the new AppDomain, and that calls some other method where I inserted my 2nd call to GrainClient.Initialize().

I checked AppDomain.Current and it was indeed called from the new AppDomain, not the original one the program starts in. Yet I still got:
{"Calling SetUnobservedExceptionHandler the second time."}

**Comment by danvanderboom** [comment]
I've reproduced the problem with this code repo:
https://github.com/danvanderboom/OrleansAppDomainTest

**Comment by gabikliot** [comment]
OK, I will leave it to @jdom and @sergeybykov to look into that.

**Comment by jdom** [comment]
@danvanderboom this is not a problem of Marshal-by-bleed. This is just that an Orleans host and Orleans client cannot run within the same app domain. They both call into `UnobservedExceptionsHandlerClass.SetUnobservedExceptionHandler`, but this would not be the only thing that conflicts with them running together, so it's not just a matter of fixing this method. We would like to get rid of many of the statics we currently use, but it's not a trivial amount of work, and it could also result in some changes to the programming model. As it stands today, from within a Silo you should not use GrainClient. That means that your telemetry consumer implementation should probably get a different implementation of GrainFactory depending on which environment it is running on.

Running multiple clients within the same process, but in different AppDomains, is definitely supported. In fact, take a look at the tests tagged with "GeoCluster" that do this thing via a [Client wrapper in a separate AppDomain](https://github.com/dotnet/orleans/blob/master/test/TesterInternal/GeoClusterTests/TestingClusterHost.cs#L220)

**Comment by jdom** [comment]
and other that it would not be technically possible to run both client and host in the same appdomain, it would probably not be an OK solution to have a grain client running inside 1 silo host of the cluster that it wants to talk to, regardless of that limitation. It would be unnecessarily inefficient.

**Comment by danvanderboom** [comment]
@jdom I may have misdiagnosed the problem. But I do believe I am calling GrainClient.Initialize for the 2nd time from a 2nd AppDomain, as reproduced in my sample solution at:
https://github.com/danvanderboom/OrleansAppDomainTest

The AppDomain.Current.FriendlyName reports a different value at the time I call GrainClient.Initialize for the 2nd time.

From what you've said, and from what I'm getting from looking at the code and from chatting on Gitter, I think I have a work-around right now to satisfy my current requirements. I see the work that is happening with Orleans to get the .NET Core support further along, and the statics are definitely (in one way or another) causing some kind of problem that I wouldn't be running into if static types and methods weren't involved. So that's fine: I have a work-around plan, and will move forward with that right now.

"As it stands today, from within a Silo you should not use GrainClient. That means that your telemetry consumer implementation should probably get a different implementation of GrainFactory depending on which environment it is running on."

When you say "should probably get a different implementation", do you mean one that exists which I'm not aware of yet (and can start using today)? or one that doesn't exist, and for which the abstractions and interfaces to share across implementations might also not yet exist in Orleans?

What concerns do you have about the efficiency of this communication path, between consumers (as an Orleans client) and grains? And what ideas do you have about how a more custom Orleans-extension-to-grains communication mechanism might best function?

**Comment by jdom** [comment]
Well, there's already a different implementation of `IGrainFactory` for whether code is running inside the Silo or outside of it, you just need to get to it.
Most of the times, for code running inside the client you just get to the factory by getting `GrainClient.GrainFactory`, and when you are inside the silo you get it from within a grain by calling `base.GrainFactory` (or from within a provider from `IProviderRuntime.GrainFactory`). Nevertheless, I don't think there is a built-in way for doing this from within a telemetry consumer, so you might have to find a way to get it (I recall some conversations on Gitter for people trying to do something similar, not necesarilly a telemetry consumer, but a piece of code that ran in both client and silo, don't remember how they worked around it).
There are some plans of improving our DI and registering IGrainFactory in it (see https://github.com/dotnet/orleans/issues/988), but at this point they are just ideas that require several changes. I'm pretty sure that issue https://github.com/dotnet/orleans/issues/2030 would indeed require to improve the DI story.

**Comment by danvanderboom** [comment]
@jdom Thanks for the info and tips. I took your advice, and was successful in my TelemetryConsumer getting a grain reference and communicating with it. (At the end of the consumer's constructor, I believe, for that test.)

Then I tried to take it one step further. I started my SamplingTimer, trying both System.Timers.Timer and System.Threading.Timer. When the timer's tick event handler runs, it's in a different thread or synchronization context, and the method call on the grain reference fails.

The OrleansHost project is a console project, where SynchronizationContext.Current isn't set.
https://blogs.msdn.microsoft.com/pfxteam/2012/01/20/await-synchronizationcontext-and-console-apps/

And I've been unsuccessful so far in setting it myself and then posting a message to that saved context. It still fails. I wonder if the thread or context I should be targeting is something I can access from outside the Orleans assembly?

Any suggestion of where in the Orleans code I might start looking for my answers?

Thanks!

**Comment by jdom** [comment]
hey, just got back from a small break, were you able to resolve the issue?

**Comment by sergeybykov** [comment]
@danvanderboom, is this still an issue? Seems to overlap with #2041 to some degree.

**Comment by sergeybykov** [comment]
I'll close it. Feel free to reopen.
