### ISSUE TITLE
Should throw if GrainClient.Initialize(config); is called twice

### ISSUE THREAD

**Issue by sudsy** [dotnet/orleans#2041]
Very minor issue that I came across that took me a while to work out what was wrong. I could do a PR for this when I get a chance if you want to assign it to me.

I had originally configured my GrainClient using the guide [here](http://dotnet.github.io/orleans/Tutorials/Front-Ends-for-Orleans-Services.html). 

Later I wanted to implement streams and so I tried to configure the GrainClient within my api controller forgetting that it was already configured. 

My feeling is that running Initialize for the second time should have thrown, perhaps pointing the user to the update method instead.

**Comment by sergeybykov** [comment]
I think this should be true after we make `GrainClient` non-static in #467. Work in that direction is currently being done in #2345.

**Comment by sergeybykov** [comment]
Client is non-static since 1.5.0 as `ClusterClient`.
