### ISSUE TITLE
Orleans Protobuf serializer throw a exception

### ISSUE THREAD

**Issue by lilinghui** [dotnet/orleans#2049]
syntax = "proto3";
package game;

option csharp_namespace = "Game";

message NestData 
{
    string Data = 1;
}

message TestGrainState
{
    string Name = 1;
    //repeated NestData TestDatas = 2;    // AAA
}
one simple proto, my Grain code is (it just for test serializer)
        public Task<TestGrainState> Test()
        {
           TestGrainState state = new TestGrainState();
            state.Name = "test";

```
        NestData data = new NestData();
        //data.Data = "nest";  // BBB

        state.TestDatas.Add(data);

        return Task.FromResult(state);
    }
```

it work fine, but when uncomment AAA BBB then "setField1" throw a System.Security.VerificationException crashed.
internal class OrleansCodeGenGame_TestGrainStateSerializer
...
        public static global::System.Object DeepCopier(global::System.Object original)
        {
            global::Game.TestGrainState input = ((global::Game.TestGrainState)original);
            global::Game.TestGrainState result = new global::Game.TestGrainState();
            setField0(result, getField0(input));
           /// crash here  /////
            setField1(result, (global::Google.Protobuf.Collections.RepeatedFieldglobal::Game.NestData)global::Orleans.Serialization.SerializationManager.@DeepCopyInner(getField1(input)));
            global::Orleans.@Serialization.@SerializationContext.@Current.@RecordObject(original, result);
            return result;
        }

orlean ver is 1.2.3

**Comment by lilinghui** [comment]
I test with orlean 1.1.0 , it's ok

**Comment by gabikliot** [comment]
What? It works with Orleans 1.1.0 but not with 1.2.3?  And you are using `OrleansGoogleUtils` - the Orleans build it Google protobuf serializer, not the .NET protobuf, right?

**Comment by lilinghui** [comment]
my code is 
    public class HelloGrain : Orleans.Grain, HelloWorldInterfaces.IHello
    {

        Task<Game.TestGrainState> HelloWorldInterfaces.IHello.Test()
        {
            Game.TestGrainState state = new Game.TestGrainState();
            state.Name = "test";

            Game.NestData item = new Game.NestData();
            item.Data = "testnest";
            state.TestDatas.Add(item);
            return Task.FromResult(state);
        }
    }

client 
            var friend = GrainClient.GrainFactory.GetGrain<IHello>(0);
            var t = friend.Test().Result;

I used
<package id="Google.Protobuf" version="3.0.0" targetFramework="net451" />

whe it in Orleans 1.1.0 , it work fine.

**Comment by lilinghui** [comment]
Google.Protobuf is this
<package id="Google.Protobuf" version="3.0.0" targetFramework="net451" />

**Comment by lilinghui** [comment]
Google.Protobuf : package id="Google.Protobuf" version="3.0.0" targetFramework="net451"

**Comment by lilinghui** [comment]
test code is same , when orleans ver >= 1.2.0 , it throw System.Security.VerificationException

**Comment by gabikliot** [comment]
I am trying to reproduce, so far without success.
