### ISSUE TITLE
Remove strings from InBuiltTypes under serialization

### ISSUE THREAD

**Issue by Drawaes** [dotnet/orleans#2056]
There are a large number of method names that are currently linked by passing "MethodName". They should all be changed to nameof(MethodName) to allow compile time checking. I am happy to do the work if you think it is okay to change to this? I see no performance or functionality impact.

**Comment by jason-bragg** [comment]
I see no issue with this.. anyone else?

**Comment by veikkoeeva** [comment]
Feels like a sane move.

**Comment by jdom** [comment]
Resolved by #2067
