### ISSUE TITLE
Are Orleans project developers eligble for Open Source Development R# licences?

### ISSUE THREAD

**Issue by veikkoeeva** [dotnet/orleans#206]
It looks like the MS Orleans developers have R# licences, as probably many others. It doesn't hurt to add this here, I suppose: [ReSharper Free Open Source License](http://www.jetbrains.com/buy/opensource/?product=resharper). Maybe there should be a mention in the Wiki.

**Comment by ReubenBond** [comment]
That would be very helpful. I don't think many of us are eligible, though. Eg, I could not be considered a core committer at this stage, I think.

**Comment by sergeybykov** [comment]
Closing it for now because of the "You have to be projects lead or core committer" language.
