### ISSUE TITLE
How to use SystemStoreType ="PostgreSQL" in SystemStore

### ISSUE THREAD

**Issue by sundong1982** [dotnet/orleans#2079]
none?

**Comment by veikkoeeva** [comment]
@sundong1982 It is a regrettable naming problem. `SystemStore="SqlServer"` should really be `SystemStore="AdoNet"`. It will be likely changed in the 2.0 release when backwards incompatible changes are more OK.

In your example case the connection string would be `"DataConnectionString="Server=127.0.0.1;Port=5432;Database=myDataBase;Userid=myUsername;Password=myPassword;Protocol=3;Pooling=true;MinPoolSize=1;MaxPoolSize=20;ConnectionLifeTime=15; AdoInvariant="Npgsql" /"`

Take a note of th last *AdoInvariant="Npgsql"*. This tells Orleans which ADO.NET libraries to load and use. For more information at http://dotnet.github.io/orleans/Advanced-Concepts/Configuring-SQL-Tables.

Currently there is a database deployment script only for SQL Server and MySQL. If you have the time and inclination, take a look at https://github.com/dotnet/orleans/tree/master/src/OrleansSQLUtils. The scripts are there and you should get going by translating a PostgreSQL specific version of them. We have exhaustive tests and can help you checking progress incrementally if you wish work on this. You don't have to, but I mention just in case. Eventually someone gets there, I've thought about it myself too. :)

**Comment by ReubenBond** [comment]
We could add an alias between "adonet" and "sqlserver"

**Comment by veikkoeeva** [comment]
@ReubenBond That is a splendid idea. We could do that and add appropriate deprecation warning(s).

**Comment by xclayl** [comment]
I've been working on a Npgsql implementation.  This is where I'm at at the moment. (it seems to work for me)

[OrleansTables_postgres.txt](https://github.com/dotnet/orleans/files/446346/OrleansTables_postgres.txt)

**Comment by veikkoeeva** [comment]
This would be a great contribution. If you need help in plugging it in to the test framework, just open a new PR and ping me or @shayhatsor. We might be absent for a while, but appear eventually. :)

**Comment by sundong1982** [comment]
thx all :)

**Comment by sergeybykov** [comment]
I'll link https://github.com/dotnet/orleans/pull/2113 to this.

**Comment by sergeybykov** [comment]
Resolved via #2113.
