### ISSUE TITLE
IStreamProviderRuntime interface is not accessible to external Stream Providers 

### ISSUE THREAD

**Issue by ca-ta** [dotnet/orleans#208]
Currently, ```IStreamProviderRuntime ``` is an internal interface.
```IStreamProviderRuntime ``` and the family of related interfaces expose runtime features essential to implementing new stream providers that are not based on, say, the  ```IQueueAdapter```  interface (but which, naturally, still require runtime support).

However, making ```IStreamProviderRuntime ```  public would require making a significant number of other interfaces and classes public as well:
* ```StreamId```
* ```IConsistentRingProviderForGrains```
* ```IGrainRingRangeListener```
* ```IStreamConsumerExtension```
* ```IStreamProducerExtension```
* ```StreamDirectory```
* ```StreamQueueBalancerType```
* ```IStreamFilterPredicateWrapper```
* ```StreamPubSubType```
* ```IStreamPubSub```
* ```PubSubSubscriptionState```
* ```ISystemTarget```

I wonder if this is OK - while I think ```IStreamProviderRuntime ``` is similar in intent to ```IStorageProviderRuntime```, there is a stark contrast in the amount of internals exposed:  ```IStorageProviderRuntime``` is currently an empty interface. 

I understand that the Stream internals are currently being refactored. However, if you think it is acceptable to make IStreamProviderRuntime available to external stream providers in the current form in the meanwhile, I would be more than happy to create a PR with the required changes.
I could certainly use the runtime functionality exposed as a result.

Thanks for open sourcing Orleans - super cool stuff :+1:

**Comment by gabikliot** [comment]
I don't think we should make IStreamProviderRuntime public in its current form. It will force making all those other type public, and they definitely should not be public. ISystemTarget definitely should not be public.

The fundamental problem, which internally we thought a lot about, is that we have 2 audiences. The Orleans applications developers and runtime extensions developers. Orleans's primary goal is to simplify distributed app development. This is its **mission**. Therefore, anything that complicates that is an anti-thesis. An important part of simplifying the programming model is the public API surface. We want to keep it as small and intuitive as possible.

On the other hand we have a secondary goal of extensibility. In this light, we see writing new providers similar in spirit to writing Kernel drivers. There are a bunch of APIs in the OS (both Linux and Windows) to write drivers. It should be made very clear to the developers that those APIs apply to "device drivers implementers" and not to "applications developers". Until we have a way to make this distinction very clear, I think we should not complicate app developers life.

So I think we should do 2 things:
1)	Consider how we make this distinction very clear. Is just having a namespace enough? Orleans.Providers.Streams? Maybe in addition moving all extension APIs into a separate assembly? That way app an developer does not even have to link against “extensibility” dll? Community feedback would be great here.
2)	We, the Orleans team, need to refactor this API. This is unrelated and regardless of how we solve point 1. The current shape of IStreamProviderRuntime is simply unacceptable to be made public, even for “kernel” developers. We put all  the stream extensions API there IStreamProviderRuntime **temporarily**, just to keep track of it, WITHOUT an intention to make it public in its current form. We are on the path of this refactoring, but it will take time. We will first refactor queue adapters, as we think those have a wider usage and then refactor the IStreamProviderRuntime. For now, those who really need to write their own stream providers can do it by forking the code. Not ideal, but possible. That is the price we pay for deciding to open the whole stream functionality public. The application streaming APIs were ready for consumption and we did not want to delay their released until we polish the internal extension API.

**Comment by gabikliot** [comment]
I also have a question to @ca-ta. Can you please provide more details on the scenario where you need to write your own stream provider, which is not covered by queue adapters or SMS? For example, could your stream provider be implemented as an extension to SMS, when SMS provides more configuration options, so it can be customized for specific needs? I am merely gathering requirements and trying to understand usage patterns.

**Comment by ca-ta** [comment]
@gabikliot Thank you for the explanation. 

Regarding 1) - The namespace approach would work for me just fine. 
If insufficiently clear, the API can always be moved to a separate assembly, for the price of a few more ```InternalsVisibleTo```  attributes.

Regarding 2) - That one word ("temporary") explains a lot :-) It appears I've been trying to use the provider mechanism way too early in its development cycle and, as you know from the CodePlex thread, I've quickly ended up having problems.

It would be great if you could share a timeline for the Stream Provider infrastructure refactoring, as vague as it may be - I'm under some time pressure and I could use the info to help me decide on the magnitude of the hacking I will need to engage in :-)

**Comment by gabikliot** [comment]
Lets try to understand in the [codeplex thread] (https://orleans.codeplex.com/discussions/584910) what the gaps are. It may be not too hard to support your scenario. I don't have exact dates for this yet. Our first goal was to refactor queue adapters.

**Comment by ca-ta** [comment]
Thank you - I'll follow up on codeplex.
