### ISSUE TITLE
Make AWS tests SkippableFacts

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#2080]
The AWS tests added as part of #2007 and #2008 are failing in the absence of the AWS emulator. Is we turn them to SkippableFacts, we can skip them is the emulator isn't present.

**Comment by veikkoeeva** [comment]
@sergeybykov They shouldn't be skipped on just any error, but rather on errors failing to connect to the AWS emulator/storage. We could turn this into default functionality too in the future (I would hope without mangling it in class constructors, arguing that's not class but test invariants).

**Comment by MikeHardman** [comment]
This will be a consideration for the Kinesis simulator also so I'll need to
follow this pattern here, I'll need the DynamoDB storage emulator that
these tests depend on and an additional emulator for the streaming platform.

**Comment by galvesribeiro** [comment]
@MikeHardman sure, After the last 2 PRs get merged I'll make a cleanup and make the tests (1) isolated on its own projects as suggested by @jdom and (2) make them skippable.

**Comment by galvesribeiro** [comment]
I think we can close that after #2095
