### ISSUE TITLE
Performance of Serialization Manager and removal of locks for reading

### ISSUE THREAD

**Issue by Drawaes** [dotnet/orleans#2081]
As I understand it the Serialization Manager will mostly load the type -> Copier/Serializers and Desers at startup time. After that there should be minimal registration. It seems that this is a "hot path" for serialization and looking up the type to find the copier or serializer will be happening a lot. 

There is a lock around every read and while the operation in the lock is normally very quick it is a point of contention. I realize the penalties of immutable dictionaries and concurrent dictionaries have been discussed. I would propose instead the locks are removed for reading, and for writing a Clone and Swap with a lock approach is taken. This might increase the amount of GC, but it should only be up until a silo has seen all types it will need to serialize. 

I have done some testing and with 1 thread doing serialization on my crude test there is basically no difference (expected) but with two and three threads the difference ~17% for 4 threads and 6% for 2 threads (4 core Xeon laptop with 8 hyper threads). The test was just using the RoundTripSerializationForTesting method.

I am happy to make a PR if it is of interest.

**Comment by ReubenBond** [comment]
Fixed - the new serializer is very fast
