### ISSUE TITLE
Not all required queries found. Missing are: ClearStorageKey,ReadFromStorageKey,WriteToStorageKey

### ISSUE THREAD

**Issue by ZzzasdfghjklZzz** [dotnet/orleans#2091]
I try to configure SqlTable for my Orleans Server(1.2.3),I am using this sql script file to create my table:
[https://github.com/dotnet/orleans/blob/master/src/OrleansSQLUtils/CreateOrleansTables_SqlServer.sql](url)
this is my OrleansConfiguration.xml:
`<?xml version="1.0" encoding="utf-8"?>`
`<OrleansConfiguration xmlns="urn:orleans">`
`<Globals>`
`<SystemStore SystemStoreType ="SqlServer"
           DeploymentId="OrleansTest"
           DataConnectionString="Data Source=localhost;Initial Catalog=Orleans;Integrated Security=True;" />`
`</Globals>`
`<Defaults>`
`<Networking Address="localhost" Port="11111" />`
`<ProxyingGateway Address="localhost" Port="30000" />`
`</Defaults>`
`</OrleansConfiguration>`
however,it throw that exception:
Not all required queries found. Missing are: ClearStorageKey,ReadFromStorageKey,WriteToStorageKey
this is my OrleansQuery:
![image](https://cloud.githubusercontent.com/assets/21215924/17924671/30d8edae-6a1c-11e6-923f-d75d004fef11.png)

i am unfamiliar with the Orleans,may i miss any key points?

**Comment by sergeybykov** [comment]
You need to use the script matching the version of the binary - from https://www.nuget.org/packages/Microsoft.Orleans.OrleansSqlUtils/1.2.3.

**Comment by veikkoeeva** [comment]
@ZzzasdfghjklZzz That's true what @sergeybykov told. It's in the `packages/SqlUtils` directory. We should have better docs on it (just discussed a related thing in Gitter). We should also improve that particular check.

**Comment by ZzzasdfghjklZzz** [comment]
@sergeybykov @vadimzozulya thanks a lot,you guys are pretty good,It is of great use for my work.
