### ISSUE TITLE
Use Orleans for grid computing

### ISSUE THREAD

**Issue by menjiKu** [dotnet/orleans#2092]
Hey there

I'm about to start a new greenfield project and one of my tasks deals with a very frequent processing of a large amount of data.

A simplification of my task:
- I have a  large predefined, **static** list of strings
- Every half a second (approximately) a user sends me another string
- I check every string I have stored and if it's within a hamming distance of 1 from the user's input I return MY string to the user.

NOTE: The list of strings is kept unchanged between user inputs.

(in reality the check I run on every string is more complicated and guarantees I will not receive 2 positive results for the same query string)

I made sure checking all these strings synchronously takes too long and it did. Took a few minutes for a single query, in that time I'd have already gotten around 100 more to process.

I read some of the documentation of Orleans and from what I've got it Orleans is oriented to allows execution of a multiple instances of the same task on a different actors. Is that right?
Since what I need is to **split a single task** between **different actors** ( for example: tell one actor to check half of the string and a second actor to check the other half at the same time)
Is it possible?

**Comment by sergeybykov** [comment]
Orleans makes it relatively straightforward to partition your state and computations by encapsulating then in actors (grains). The first decision to consider is on the data partitioning into grains, so that requests could be routed to the right pieces of state instead of moving lots of data to computations.

With the partitioning in hand, one can fan out or serialized execution of requests against the data partitions (grains) to implement the desired algorithm. For example, you can fan out a check call to two (or more) grains holding different pieces of the static dataset to perform those checks in parallel.

With that, the system should automatically scale to the maximum parallelism (number of CPU cores) of the cluster.

**Comment by menjiKu** [comment]
I assumed I need to split the execution of my request between different grains but the thing that bothers me is the code that splits the request between different grains.
Should the user send his request to a single grain which "splits" the execution by calling a collection of other "secondary" grains which do the actual calculation?
If so, how can that first grain know how many cores I have in the cluster to split the request accordingly?

Further more, if I'm expecting my cluster to grow, how do I design those secondary grains which handle only part of the data? If I implement 2 grain classes where one reads a half the rows from a DB and the second reads the second half I won't be able to add more servers to the cluster and split my data to 3 or 4 for example without re-writing my grains and adding more grains implementaions which take a samller part of the entire collection.
How should I tackle this issue?

**Comment by sergeybykov** [comment]
Better late than never.

>Should the user send his request to a single grain which "splits" the execution by calling a collection of other "secondary" grains which do the actual computations ?

There are two popular patterns for this.

1. Use a large enough pool of "secondary" grains, e.g. 1000 of then, and spread the load across them by picking a grain ID for the target grain for each request from the pool. For example, you can pick an integer from 0 to 999 by round-robin, random or hash/mod based algorithm. This approach works when there is no affinity between requests and specific target "secondary" grains in the pool.

2. Use `StatelessWorker` "routers" grains (http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/StatelessWorker.html) that will execute any custom routing logic of picking the target "secondary" grain for each request. `StatelessWorker` grains automatically scale, and appear to the caller as a single grain. So this is similar to what you mentioned but without a single grain bottleneck.

>If I implement 2 grain classes where one reads a half of the rows from a DB and the second reads the second half I obviously won't be able to add more servers to the cluster and split my data to 3 or 4 grains at a time without re-writing my grains and adding more grains implementations which take a smaller part of the entire collection from the database.
How should I tackle this issue?

It's hard for me to tell for sure without understanding more details of the scenario, but it seems to me that 2 will allow to implement such an approach within the "router" grain logic.

**Comment by menjiKu** [comment]
Hey sergey
I guess my last message wasn't clear enough, The thing I'm trying to achieve is splitting a very long indipendent calculations between several grain, let's say 20.

What I'm trying to figure out is how a single string from a user could be checked against, let's say, 100 strings in my DB if I want  20 'secondary' grains to check 5 strings each.

If I understood your reply, using a simple router grain would allow me to check *different user's* strings concurrently but I want more than that - I want to check *each user's* string using several grains at the same time.

Do you mind reopening this thread for me? thank you!

**Comment by sergeybykov** [comment]
>If I understood your reply, using a simple router grain would allow me to check different user's strings concurrently but I want more than that - I want to check each user's string using several grains at the same time.

The router grain could make a fan-out call for each string to N grains in parallel, if that's what you need. The question is if those N grains can be arbitrary from a single pool or have to be from N different pools of grains, e.g. affinitized with different data sets. That part of the requirements isn't clear to me. But I should be able to implement either case I think.

**Comment by menjiKu** [comment]
>  The question is if those N grains can be arbitrary from a single pool or have to be from N different pools of grains

The implementation I had in mind includes a single database containing all the strings and each grain could query for every entry.
This way I could give the secondary grains a 'first index' and 'last index'  with the forwarded user input and they would query and check against all entries in the database within the range they received.
So I think there should be a single pool of secondary grains, since each grain can access all of the data.

**Comment by sergeybykov** [comment]
So the grain pool pattern for secondary grains will work for you, and there is no need for the router grains, since the client can fan-out to N secondary grains as easily?

**Comment by menjiKu** [comment]
> since the client can fan-out to N secondary grains as easily

I want to avoid having my client call N different grains for 2 reasons:
 1. It means my client need to know I have X entries in my server's database to actually give X/N entries to each grain.
 2. It would reduce the scalability of the client and the server since my client needs to know how many grains it could activate effectively. 
For example, I assume that if my silo has 4 CPUs available for grains to run on, the client would probably get the best results activating 4 grains.
This way the client needs to "know" 4 is the preferable number either by predefined configuration (meaning I need to update the client each time I have more/less CPUs available) or a message from my silo telling it how many is the "optimal" number of grains (Information I think doesn't need to concern the client at all).

I'm looking for a solution where the client does not need to know N different grains (or even N different threads) are processing its request. So a router grain does sound fitting here.
Further more I think the router grain needs to know how many secondary grains it could actiavate in the silo for optimal distribution (directly related to the time it takes to process the user's request).

**Comment by sergeybykov** [comment]
I agree - looks like `StatelessWorker` router grains is the better option.
>Further more I think the router grain needs to know how many secondary grains it could actiavate in the silo for optimal distribution (directly related to the time it takes to process the user's request).

I wouldn't stress too much about trying to get an optimal distribution. With large enough number of incoming requests statistics will take care of it for the most part.

**Comment by menjiKu** [comment]
> With large enough number of incoming requests statistics will take care of it for the most part.

Not sure I understood that part.
If I do use a stateless router grain which fans out the request to N different grains, how is the router grain going to adapt if more/less resources are available (like losing communication to some servers)?
Seems like I'd have to reconfigure the router grain and it won't scale by itself, which is not something anyone can maintain.

**Comment by sergeybykov** [comment]
Sorry, I wasn't clear. Let me try to explain the whole picture as I see it. Please correct me if I misunderstood something.

With `StatelessWorker` router grains, they will be naturally distributed across all of the silos and scaled out automatically. This part is simple.

For the secondary grains you need to choose the fan-out factor N for parallelizing the checking operation across N grains. You also need to choose the parallelism factor K of the total number of secondary grains in the cluster.

I'd say than N is primarily determined by your latency requirements - there is no benefit in making N much higher than L/l where L is the latency of executing a check sequentially
and l is the target latency budget with some reasonable margin. Picking N significantly higher will increase the messaging overhead for better latency that you don't need, because you are already within the budget of l.

If you pick K >> N, and make routers pick N secondary grains from the pool of K for each request randomly or via consistent hashing, with high enough K the load should get pretty evenly distributed across all nodes due to statistics. Note that K doesn't need to match the total number of core/threads C in the cluster. So long as K > C, you should get pretty good distribution across all cores/threads. Ideally, I think you want K to be significantly, by factors, higher than C, so that you can increase C over time if needed, and not worry about changing K.

Does this make sense or I went off the rails here?

**Comment by menjiKu** [comment]
That made perfect sense, thank you!

Just one more question for now - how could I limit the amount of secondary grains in the cluster (K)?

**Comment by sergeybykov** [comment]
>how could I limit the amount of secondary grains in the cluster (K)?

All such factors you control by simply picking the grain identity scheme. For example, to limit K to 1000, the simplest way is to use integers as the grain ID type, and pass a int between 0 and 999 as key to `GrainFactory.GetGraing<IMySecondaryGrain>(key)`.

To pick specific keys, you can either round-robin by incrementing a counter and mod'ing it with K or do `Random.Next(K)` or calculate a hash of some request data and mod it by K. Regardless of the exact method, the end result is the same - the grain IDs of secondary IDs will be between 0 and K-1 giving you K secondary grains processing all incoming requests in a balanced manner.
