### ISSUE TITLE
Bug Report: No physical ram installed on machine?

### ISSUE THREAD

**Issue by jamescarter-le** [dotnet/orleans#2094]
I have a RAMDisk on my machine for my Resharper cache, when running Orleans I get the following exception:

"No physical ram installed on machine?"

Not a big issue I can disable the disk, just thought I would mention it.

**Comment by ReubenBond** [comment]
Interesting. At least the silo should continue after that exception, so it's not a major blocker.

Seems the exception is from here: https://github.com/dotnet/orleans/blob/master/src/Orleans/Statistics/RuntimeStatisticsGroup.cs#L112

**Comment by jamescarter-le** [comment]
Yep seen that, strange WinRT is giving us 0 capacity when a RAM Disk in installed. Not an Orleans issue then, just thought I would report it.
