### ISSUE TITLE
Automate building docs with DocFX

### ISSUE THREAD

**Issue by jdom** [dotnet/orleans#2106]
Now that DocFX was integrated by #1970, it requires a few manual steps to build the HTML documentation from the markdown files. We should automate this process to reduce friction.
We can split the documentation source (markdown files) from the generated html into 2 different branches (and potentially even put both of them in a new orleans-docs repo, but we'd need to sort out the domain change issue in that case, so it's not a pre-req). Let's call them `docs` and `gh-pages` respectively for now.
The script can be triggered by Jenkins every time the `docs` branch changes, and should:
1. Pull the `gh-pages` branch into a clone in a working folder
2. Delete all the generated HTML from it
3. Run docfx so that it builds and puts the generated HTML on that `gh-pages` clone
4. Add all files and commit
5. Push to `gh-pages`

Sounds reasonable?

After we have this basic automation in-place, we can take a look at doing something with #88 to generate API docs from the XML comments too.

**Comment by jason-bragg** [comment]
All for auto-dox, though I'm concerned about updating the main doc repository to point to auto-generated dox from the latest code.  I think we'll need main docs to point to the generated docs of the latest released version (starting with 1.3).

I suggest keeping auto generated docs per release (again starting with 1.3) and a link to the unreleased latest docs that can be updated as described above.

**Comment by jdom** [comment]
Agreed, I envision this in a similar way that the script can fetch the changes from either `master` or some other branch or tag, so we can build docs whatever version of the API. Still, that's something we should discuss in #88 after we have this particular issue implemented, which is not for generating the API from code, but just the docs from the markdown files.

**Comment by erictuvesson** [comment]
@sergeybykov + @jason-bragg, what is the status on this and https://github.com/dotnet/orleans/issues/88?

Considering that there is a lot of documentation on the `docs` branch using Docfx.

**Comment by sergeybykov** [comment]
No progress on API docs. Any help would be much appreciated. 🙂

**Comment by ReubenBond** [comment]
Closing as duplicate (close enough) of #88. By the way, I took a stab at this and couldn't prevent DocFx from crashing. Here's the issue: https://github.com/dotnet/docfx/issues/4341
