### ISSUE TITLE
Persistence of Large amounts of data - Best Patterns?

### ISSUE THREAD

**Issue by falconmick** [dotnet/orleans#2107]
Hi guys,
I am just getting into Orleans as a way to learn about the Actor model.

From what I understand, whenever an actor is brought out of storage and into memeory, the state (if any) will be retrieved from the storage provider and placed into this.State.

The big issue I see with this is that After a while storing something like a game and it's statistics would take up allot of time to extract from the storage provider AND make the grains allot bigger.

Say I were to persist the game history to an external source (TSQL) if I want to then access this data, is it still right to use an actor to save and query this data? Or am I missing the point of actors and all data should be stored using State?

Any write ups about persisting large data within Orleans would be appreciated.

Cheers,
Michael.

**Comment by sergeybykov** [comment]
There are two related but different things here to consider: 1) management of state and 2) declarative persistence feature (`Grain<TState>`).

1) Grain code is free to manage its persistent state in any way it needs - loading all of it into memory upon activation, persisting a full snapshot or deltas or change log, lazily loading pieces of state on demand, etc.

2) Declarative persistence is an optional opt-in feature that covers a small subset of such operations that we deemed most typical. 

If 2) is sufficient for a particular grain type, it requires least amount of code but provided the limited subset of functionality.

Otherwise, 1) allows for pretty much any other way of handling of persistent state.

**Comment by falconmick** [comment]
So say for example you have an actor who accepts in readings of temperature every 10 seconds. One consumer of the application would like to just see the latest data every 10 seconds and therefore queries the api which talks to the grain and gets that value which is updated every 10 seconds.

Another consumer however wants to see how the temperature changed over the course of a day.
I can see two solutions, 
A) using an Orleans timed event, manually save a reading to a datetime in another DB storage device, the API then queries this table.
B) using an Orleans timed event, create a new actor (say LongTimeStorageSensor) and pass in a snapshot of the temperature. This new actor maintains it's history and automatically compresses data as it gets old (i.e. keep every 10 seconds for the past minute, every min for the day, every hour for the month and every day for the remainder)
C) Just have a list of readings that are stored inside of the this.State, after 1 year this list is then a behemoth.

From what I understand of your reply, my A) maps to your 1) and my C) maps to your 2).

For data which grows over time like this, is it recomended to go with a solution like A)? From my understanding of a talk Caitie McCaffrey made, Halo 4 stored Game data inside of long time storage (slow, but not accessed as often) and the user actors held aggregate and slimmed down game data.
But did they they then query the Map data via an actor? Or did they just use an API to talk to that persistant storage?

Sorry for the long and weird questions. I am just trying to see how the Actor system fits into a typical app. Like is it an acceptable design to have an actor who has no state or grain persistance and simply is used to call an external data store (like to retrieve game data)

Cheers.
Michael.

**Comment by falconmick** [comment]
I mean I understand I can probably do whatever I want, but I just don't want to violate the entire idea behind this programming model by doing Object Oriented coding. I want to code actors.

**Comment by sergeybykov** [comment]
>From what I understand of your reply, my A) maps to your 1) and my C) maps to your 2).

I think so too.

A) is the most universal option - you indeed can do whatever you want with it. I wouldn't go for B) with a separate actor type. Within the same actor type it pretty much becomes A).

There may also be a compromise middle ground there. For example, if temperature changes relatively infrequently, it may make sense to record only changes and their timestamps. If the historical data compresses very well, it may be fine to load it all if the whole history is a few kilobytes compressed. If that's the case, even C) may become a viable option.

**Comment by falconmick** [comment]
Thanks.
It's amazing that at 1am (or whatever time it is in USA, I assume) that the lead developer of a tool used in systems that cost hundreds of thousands of dollars to run can reply so quickly and usefully.

Thank you

**Comment by sergeybykov** [comment]
No problem. It's only 6pm here. :-)
