### ISSUE TITLE
how can i test my Grain which depends on another Grain?

### ISSUE THREAD

**Issue by egmkang** [dotnet/orleans#2112]
```
class GrainB : Grain, IGrainB
{
    public async override Task OnActivateAsync()
    {
        var grain = GrainFactory.GetGrain<IGrainA>(0);
        await grain.Register(this.GetPrimaryKeyString());
        await base.OnActivateAsync();
    }

}

class GrainA : Grain, IGrainA
{
    public Task Register(string grainKey);
    public Task UnRegister(string grainKey);
}
```

there is two Grain named GrainA and GrainB. GrainB depends on GrainA. I saw the Orleans's sample and the TestGrainFactory can create a local grain which I can test. when Grain is simple, it can be tested easily. but in my problem, GrainB depends on GrainA, how can I complete the test?

**Comment by sergeybykov** [comment]
You can run your test with GrainA and GrainB classes within a test silo. What I suspect you might need in addition is some test hooks (methods or interfaces) to query the state of the grains to verify that they did exactly what you intended them to do.

Unless I missed something, run time dependencies between grains shouldn't preclude you from do that.
