### ISSUE TITLE
Bug while searching in docs and broken links

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#2117]
With the new docfx based docs I found out that there is some bug when you search for something.

To give an example, open the main docs page and search for SQL. Click on the first link which should be http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Configuring-SQL-Tables.html?q=SQL

Note that docfx add `?q=SQL` query string parameter to the URL. The page is rendered however the code sections (like the XML config in this case) is empty. If you look at the source of the page, the HTML code is there for that section but it isn't rendered. Just remove the querystring parameter and it render properly.

![image](https://cloud.githubusercontent.com/assets/4714040/18257969/36ad36b4-73a3-11e6-83c0-6516270a59c4.png)

I wonder if it is a docfx bug or something with our pages.

Also, there are broken links that return a 404 like in this page http://dotnet.github.io/orleans/Documentation/Runtime-Implementation-Details/Relational-Storage.html on the first paragraph there is a `SQL Tables` link. I don't know if it was a mistake on the migration steps or something on our indexing.

**Note**: it happens on chrome and edge as well.

**Comment by richorama** [comment]
Issue raised with docfx: https://github.com/dotnet/docfx/issues/675

**Comment by sergeybykov** [comment]
Looks like this is fixed now in DocFx.
