### ISSUE TITLE
`AzureSilo.Start` should use `DeploymentId` and `ConnectionString` from passed `ClusterConfiguration`

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#2121]
Correct me if I am missing something. If I want to use custom `deploymentId` and `connectionString`, I need to specify them in two places for `AzureSilo.Start` - in `config.Globals` and as separate params to this method. It seems to me that these two optional params are redundant - they could be retrieved from `config.Globals` instead.

**Comment by sergeybykov** [comment]
With `AzureSilo` you don't need to specify deploymentId or connectionString at all. By default, it uses the cloud service deployment ID and reads connection string from its configuration. Take a look at https://github.com/dotnet/orleans/blob/master/Samples/AzureWebSample/OrleansAzureSilos/WorkerRole.cs for an example.

**Comment by DixonDs** [comment]
Yes, if I use default configuration. The problem is when I want to pass custom values there (why I want that is another matter)

**Comment by sergeybykov** [comment]
If you want to override the defaults, you can pass them to the overload of `Start` that takes the arguments. Is that not working for you?

**Comment by DixonDs** [comment]
I've got impression that in order to make that work, I need to pass Table Storage connection string in both `config.Globals.DataConnectionString` and `connectionString` params (similarly for deployment ID)

**Comment by sergeybykov** [comment]
@benjaminpetit is eliminating this confusion in https://github.com/dotnet/orleans/pull/2109. Essentially, `ClusterConfig` and `deploymentId`/`connectionString` should be mutually exclusive. He is adjusting the API to reflect that.

**Comment by sergeybykov** [comment]
Resolved via #2109.
