### ISSUE TITLE
Question: Can grain client interceptors be used to intercept grain-to-grain call?

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#2125]
In my service there are numerous grain to grain calls, and I like to implement general retry logic on the caller side and like to know whether Orleans interceptors could be used for it. Server-side interceptors don't seem to fit since AFAIK they run on the callee side, not the caller. Grain client interceptors doesn't seem to fit as well since grain to grain doesn't use the static GrainClient. Is there a built way to do what I want?

**Comment by ReubenBond** [comment]
@Eldar1205 what kind of errors are you planning on retrying on, just network errors or application errors, too? For the former, maybe you can enable message retries instead by setting `MaxResendCount` in config.

In response to the question in the title, yes, `GrainClient.ClientInvokeCallback` can be used to intercept grain-to-grain calls.

There is no way to set an outgoing call interceptor on a per-grain basis today.

**Comment by Eldar1205** [comment]
So to make sure, the GrainClient should be used inside a silo to intercept
outgoing grain request on the caller side? Thats unusual is it not?
בתאריך 8 בספט' 2016 3:03,‏ "Reuben Bond" <notifications@github.com> כתב:

**Comment by ReubenBond** [comment]
@Eldar1205 I'm not entirely certain what you mean. You get grain references just as you usually would, the only difference is that you set an interceptor using the static GrainClient.

**Comment by Eldar1205** [comment]
Now its clear to me. Thanks. I will close the issue soon
בתאריך 8 בספט' 2016 8:07,‏ "Reuben Bond" <notifications@github.com> כתב:

**Comment by Eldar1205** [comment]
Reopening the issue - I saw the `GrainClient.ClientInvokeCallback` can only intercept grain client requests before the message it sent, and can't be used to execute custom logic after the grain responds. In my scenario I wish to pass a logging correlation context from grain client to the grain itself. The correlation context is used to implement a logical call stack. For that purpose I want a client interceptor which puts the correlation context in Orleans `RequestContext`, acting as a stack push, and after the grain returns response to client I want to remove the correlation context from the `RequestContext` acting as a stack pop. However since the client interceptor doesn't allow post-message logic, I can't use it to perform the stack pop. Any suggestions?

**Comment by jdom** [comment]
What we do in 343 is to put a correlation ID in the frontend before doing a grain call from the client (basically each HTTP request will put in a new end to end correlation id), and this flows through to the grain call, and the nested calls that this grain does too. Otherwise if you just do a stack push before a call and stack pop after it, then it is not correlating a lot with regards to the end to end call.
Could this be a workable alternative for you?

**Comment by Eldar1205** [comment]
The correlation context, in short CC, that the logging infrastructure provides me is used to capture a hierarchy, which I'm complied to adhere to. For each logical flow, there is a root operation, with nested operation, with nested operation, etc. This forms a logical call stack. I wish to have such a call stack for any logical flow - handling a timer tick/a reminder/a grain request from a client/a grain request from a bootstrap provider. When I capture the CC, I capture the current logical stack frame, so it can be transferred across machine boundaries so the logical call stack resumes from same stack frame on the other machine. This is why an end to end correlation id isn't my model, since it doesn't represents a call stack. I wish for every grain invocation to be another stack frame, which is why I require the ability to pop the stack. I'm now thinking that when a grain receives a request with a captured CC in `RequestContext`, the grain could itself remove the CC from the context and perform the pop. Will this work as expected, or will the `RequestContext `on the message sender side not reflect the pop?
