### ISSUE TITLE
Cannot build grain interfaces project using NuGet's Microsoft.Orleans.Templates.Interfaces package

### ISSUE THREAD

**Issue by ksuszka** [dotnet/orleans#213]
I don't have OrleansSDK installed on my machine. I've created empty class library project, added Microsoft.Orleans.Templates.Interfaces NuGet 1.0.3 package, created empty interface inheriting from IGrain interface and it does not compile. It seems that path to ClientGenerator in Microsoft.Orleans.Templates.Interfaces.targets is wrong ("..\tools").

Second, smaller issue is the number of packages it appends to the project references. It is suppose to be a project only with interface definitions, but now i've got references to things like Microsoft.WindowsAzure.Storage or ClientGenerator.exe itself.

**Comment by sergeybykov** [comment]
Yes, the process of creating grain interfaces and classes without the SDK installed is broken right now. The Microsoft.Orleans.Templates.* are more like placeholders at the moment.

**Comment by jthelin** [comment]
I think this issue with Microsoft.Orleans.Templates.* packages should be fixed by PR #247 and #231.

Please build the 1.0.5 packages locally, put them in a local directory configured as package source and try again to see if you still hit this problem.

Thanks,

**Comment by jthelin** [comment]
Update: The 1.0.5 NuGet packages are now in the public repository so should auto-download as normal.

https://www.nuget.org/packages?q=orleans

**Comment by sergeybykov** [comment]
Please reopen if you find that 1.0.5 Microsoft.Orleans.Templates.* don't solve the problem for you. *"Works on my machine."* :-)
