### ISSUE TITLE
Expose caller information to silo interceptors: grain type, method name

### ISSUE THREAD

**Issue by danvanderboom** [dotnet/orleans#2139]
There's some nice data visualization work being done of Orleans clusters, silos, and grains, and some of the best ideas so far depend on knowing, from within a silo interceptor, the type and method name of the caller.

In grain-to-grain communications, the caller is a grain, the type is a grain type, and the calling method is itself a grain method. It'd be nice to know whether or not this is the case, if there's a possibility that the caller could be a non-grain object (such as an Orleans extension). This would help to determine if calls come in from an Orleans client (like the Internet through one protocol or another), or whether it's internal (grain-to-grain) communication.

Let's visualize some call graphs and streaming graph pipelines!

**Comment by creyke** [comment]
+1

**Comment by sergeybykov** [comment]
`Message` class exposes `SendingGrain` and `SendingActivation` properties that can provide enough information to interceptors. Some decoding, e.g. `TypeCode` -> grain class, may be needed.

**Comment by danvanderboom** [comment]
https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Core/InsideRuntimeClient.cs#L367
>resultObject = await InvokeWithInterceptors(target, request, invoker, message);

https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Core/InsideRuntimeClient.cs#L395
>private Task<object> InvokeWithInterceptors(IAddressable target, InvokeMethodRequest request, IGrainMethodInvoker invoker, Message message)

https://github.com/dotnet/orleans/blob/e2e0c5b2a12a7c831224f89a3c550e0d9c60a0d1/src/Orleans/CodeGeneration/IGrainMethodInvoker.cs#L21
>Task<object> IGrainMethodInvoker.Invoke(IAddressable grain, InvokeMethodRequest request, Message message);

https://github.com/dotnet/orleans/blob/afe355a0f3974b570b8cac19e71f8943378ddb16/src/Orleans/Core/InterceptedMethodInvoker.cs#L51
>public Task<object> Invoke(IAddressable grain, InvokeMethodRequest request, Message message)

Are these the right places to be looking at this? Or does the Message object need to be included within the InvokeMethodRequest?

**Comment by MikeHardman** [comment]
Obviously +1, the sooner we can get at caller information during the intercept the sooner I can get some better graphs rendered!

**Comment by sergeybykov** [comment]
I don't think passing `Message` to interceptors and invokers is a good approach. My feeling is that it'd be better to pass caller's info decoded from the message, and probably only if that is requested (via config or otherwise). The easiest, short of passing type code integer, would be to pass a strings of the class name. We could probably resolve it to a `TypeInfo` but it's not clear to me if that would be useful, maybe.

I'm less sure about passing caller's method info/name, as we don't track it calling methods today. Possible, of course, with some extra effort.

**Comment by Dewaldf** [comment]
Is anyone actively working on this ?

**Comment by sergeybykov** [comment]
@Dewaldf 
>Is anyone actively working on this ? If not, mind if I give it a go ?

I'm unaware of anybody working on this. Please do!
