### ISSUE TITLE
Allow grain states with private ctor

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#2141]
Grain states are created using `statefulGrain.GrainState.State = Activator.CreateInstance(stateType);` in `GrainCreator`. Is there any specific reason why private constructors are not allowed? Otherwise, we could use `Activator.CreateInstance(stateType, true)` to allow grain states with private ctors as well

**Comment by sergeybykov** [comment]
I don't believe there's a specific reason other than that invoking a private method in general goes against the implied intent that caused the author to make it private in the first place, and hence is somewhat hacky.

**Comment by DixonDs** [comment]
Another alternative could be to have some extension point that would allow to define custom default state creation logic, which would be used when the stateful grain is created, Grain<>.ClearStateAsync is called etc.

**Comment by sergeybykov** [comment]
I think that would be a cleaner approach than invoking somebody else's private constructors.

**Comment by ReubenBond** [comment]
Should this be the responsibility of DI?

eg: try to use DI to construct grain state, if the state type is not available, use Activator.

**Comment by ElanHasson** [comment]
I like the idea of using DI and falling back on Activator. Provides for more flexibility.
