### ISSUE TITLE
[WIP] Orleans 2.X

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#2143]
_This issue will be a "root" issue to track the progress on 2.0 milestone following the steps agreed at [Meetup 10](https://youtu.be/_SbIbYkY88o)._ 

The main target on this milestone is the port to [.Net Core](https://github.com/dotnet/coreclr) but other features like enhanced deployment & cluster management in multiple hosting environments, pervasive DI, new persistence layer, etc., but all them basically follow the major goal to be compatible with .Net Core. 

The initial strategy is to keep working on the port on `master` branch by having a separated and temporary solution where we will target `.Net Standard` while using new projects "linking" to the `.cs` files and following the guidelines [here](https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/target-dotnetcore-with-msbuild) (thanks to @jdom for this briliant idea). The reason for that strategy and not the current one (have a separated branch for that) is to reduce the merge complexity and be able to hotfix and add non-breaking changes to 1.3.x releases while we still working on .Net Core port. We will focus on have any breaking change on hold to 2.0 but that doesn't block us from having new features being released under 1.x.y tag.

The tasks will be distributed across multiple phases defined as **_CRAWL_**, **_WALK_** and **_RUN_**.  So, here is the list of macro-tasks that we should cover in this story and each one of them will be tracked by a separated issue and its sub-issues referenced here. 
- [x] **_CRAWL_**
  - [x] .Net Core Compatible Binaries - #2145
  - [x] Orleans 2.0 (beta is out)
- [ ] **_WALK_**
  - [x] Building on .Net Core 
  - [ ] Testing on .Net Core
  - [ ] Orleans 2.X
- [ ] **_RUN_**
  - [ ] Cross-platform testing
  - [ ] Orleans 2.Y

**Note**: #368 was tracking it before but since most of the issues there were already completed and we moved to a new strategy, from now on, lets keep the discussion about that here.

**Comment by jason-bragg** [comment]
As each of these stages (Crawl, Walk, Run) will include it's own discussions and a number of sub-tasks, would it make sense to open a similar issue for each stage as we enter it?  This is a good high level view, but if this ends up including all of the discussion and details of the full port it will get a bit unruly up in here :)

**Comment by galvesribeiro** [comment]
@jason-bragg yep! That is the idea as we agreed on the meetup. I'm writing the Crawl main issue right now and will refer it here. Gimme a few minutes.

**Comment by galvesribeiro** [comment]
BTW, anyone with write access please feel free to update/edit this or the related sub-issues with anything you feel necessary.

**Comment by Eldar1205** [comment]
Question - when you say port to .Net Core, do you mean only .Net Core will be supported, or the full .Net framework will still be supported? I think it's very important the full .Net framework is continued to be supported, as many other libraries do as of day.

**Comment by TrexinanF14** [comment]
@Eldar1205 See #2145 for more information, but the short answer is yes it will support full framework as well as core.

**Comment by galvesribeiro** [comment]
Yes, when we say "Target `netstandard15`" we mean cover both .Net Core as the full framework ([more here](https://docs.microsoft.com/en-us/dotnet/articles/standard/library)). Remember that the major internal customer like Halo uses the full framework.

**Comment by SebastianStehle** [comment]
Is there a timeline for 2.0?

**Comment by jdom** [comment]
We are about to publish a beta in nuget.org very soon, and hopefully if everything goes well, we can push the final release a month after that (not an unmovable commitment, but we are targeting that).
In the meantime I'm sure you are aware of preview releases to myget.
Hope it aligns with your needs

**Comment by SebastianStehle** [comment]
Yes, I am super exited to use in .NET Core :)

**Comment by mo-esmp** [comment]
We are going to evaluate orleans in upcoming .NET Core project. 
I'm wondering if v2.0 beta 1 is good enough for using in a project or not ?
How close are you to v2.0 release ?
Looking for recommendation on this case.

Thanks in advance.

**Comment by sergeybykov** [comment]
We just published 2.0.0-beta2 packages to NuGet.org. Is should be good for new projects. While there will still be some changes before final, they should not impact most applications.

We hope 2.0.0 final is only a few weeks away. Although with the end of the year holidays many people will be on vacation. You can join the upcoming meetup this Wednesday that will be focused on Orleans 2.0 - https://github.com/OrleansContrib/meetups#meetup-15-orleans-20-with-the-core-team.

**Comment by talarari** [comment]
Any update you can share ? 
Looking forward to upgrading to 2.0.

**Comment by sergeybykov** [comment]
We are hoping to publish 2.0.0-rc1 tomorrow. If all tests run fine.
