### ISSUE TITLE
Suggestion: uniform hash based grain placement policy

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#2167]
I’d like to add a new grain placement policy that places grains on silos based on their uniform hash, same way reminders are balanced. The placement policy should allow to specify per grain type whether to force grain activations re-balancing on silo join/leave or not, alternatively instead of re-balancing activations a simpler route could be taken to force deactivation of grains that should be re-balanced, and let them be re-activated by a message an the placement policy will put them in their new silo. 

The motivation for this is using Orleans reminders as a way to implement evenly distributed scheduled jobs executions, where grains are the job executors that are kept **always active** so state could be preserved between consequent job executions in memory, and if needed also persisted. Reminders are evenly distributed between silos based on associated grains uniform hash, but the grains they activate aren't necessarily on same silo and if the grains are always active then when new silos join they get their share of the reminders, but not their share of the grain activations doing the actual work. Having the grains forcibly balanced based on their uniform hash will achieve the necessary elasticity of jobs execution, and will also be more efficient since there's no TCP messaging between reminders and their grains - both are placed on silos based on the grain's uniform hash. I thought about using stateless workers with reminders for that purpose, but this has several disadvantages:
1. After reminders are re-balanced there'll be a time window where the stateless worker is activated on two silos (at least) - the old and new owners of the reminder. Depending on the job, this may be undesirable, and for the specific scenario I have it's highly undesirable.
2. Stateless workers can't leverage Orleans persistence ignorance for grains, which is amazingly useful.
3. Grains that aren't stateless workers could also receive messages from other grains, such as commands to change job execution parameters or stop job entirely. With stateless workers it won't work as expected if the message sender isn't on same silo as the stateless worker.

I like to have your assistance with the following:
1. Explanation on how to contribute to Orleans. I couldn’t infer a step-by-step process on how to start contributing, and I explored the Orleans contribution guide. I know my way around Git, but have never contributed to project on Github, so if there are links I should follow and/or some conventions/methodologies specific to Orleans, I’ll appreciate if you could share.
2. Suggestions on how to approach the implementation, in particular which existing classes/interfaces I should look at for reference since I'll need to use them or to get ideas on how implement the new policy.
3. Suggestions on how to test this contribution, in particular which existing tests I should look at for reference. 
4. Suggestions on how I should document the new placement policy's behaviour and usage scenarios.

For 2 & 3, note this placement policy differs from the existing one since in certain conditions is can force deactivation of grains, while existing placement policies only have to do with placing new activations.

Any feedback on the suggestion and/or assistance with 4 points above will be appreciated.

**Comment by ashkan-saeedi-mazdeh** [comment]
I can not answer many of the above but the right way that it should be done is to expose the Placement strategy directory using DI so users can register their own placement strategies. @ReubenBond  had an implementation of this somewhere IIRC. 

Adding all strategies possible to the main core probably is not a good idea. 

about the process, just fork the project and do your modifications on your version, get the latest changes from upstream once in a while to not have merging issues. at the end when you are done, merge with latest master and create a pull request. 

I'm not sure how much code you should add for rebalancing when cluster members are joining/leaving but I'm sure you can get notifications when they happen. Doing rebalancing might have performance implications so should not be taken lightly.

**Comment by ReubenBond** [comment]
@ashkan-saeedi-mazdeh is correct, there is an implementation of hash-based placement in #2070. 

> Adding all strategies possible to the main core probably is not a good idea.

Agreed, in #2070 I was using DI to inject the placement director. I think it could have been taken further.

I am continuing development on those pieces and pushing smaller PRs. I'm *really* hoping that we get proper DI support soon so that proving these customizations becomes much easier.

**Comment by Eldar1205** [comment]
1. Does the hash-based placement supports eager de-activation when cluster size changes?
2. Can the hash-based placement be merged into master separate from the Service Fabric PR so the new placement can be part of Orleans releases and the de-activation support could be added if needed?

**Comment by ReubenBond** [comment]
@Eldar1205 
It's quite specific to the needs, so it wont dynamically balance load, a grain with id X will always map to the primary silo for some partition Y. Merging that specific placement director into the core wouldn't help anyone. Hopefully we'll soon have a way to more easily create custom placement directors.

**Comment by Eldar1205** [comment]
Why are you saying it won't help anyone? I have a use for it after some enhancements.

**Comment by ReubenBond** [comment]
@Eldar1205 what I mean is that my Service Fabric-specific implementation will not be useful for non-Service Fabric scenarios. The implementation uses SF bits.

**Comment by ReubenBond** [comment]
@Eldar1205 on the other hand, the implementation also included a generic `[ConsistentHashPlacement]` attribute, and allowed using dependency injection to inject an `IPlacementDirector<ConsistentHashPlacement>` - I'll try to get that into master.

**Comment by ashkan-saeedi-mazdeh** [comment]
@ReubenBond  Actually I only meant the injection part, I did not know you created a PR with your SF support stuff. The last time we talked, you didn't do it yet and then I went offline to just work and work. It would be good to have the injection of the placement director in the master to be able to add one's own strategies.
