### ISSUE TITLE
Orleans NuGet 1.0.3 packages copy OrleansConfiguration.xsd into each project, stopping Intellisense

### ISSUE THREAD

**Issue by ToddShelton** [dotnet/orleans#218]
The 1.0.3. NuGets copy OrleansCOnfiration.xsd into each project folder.  Visual Studio appears to use all the XSDs in the solution for Intellisense, but when more than one is present, Intellisense breaks: 

![orleans-xsd-intellisense-error](https://cloud.githubusercontent.com/assets/10549630/6608437/29972076-c804-11e4-9c4f-1f7e4a2992cf.png)

If you installed the Orleans XSD in your VS installation, Intellisense stops the first time you install a NuGet.  Otherwise it stops the second time.  

Not sure what the answer is here--I delete them from the project files.  The latest XSD in a prominent place on the project home page is not a bad idea.

**Comment by sergeybykov** [comment]
I was thinking - should we remove the xsd along with the client and silo config files from the NuGet packages altogether?

**Comment by ToddShelton** [comment]
I think leave them.  

An OrleansConfiguration.readme describing the configuration files in detail, packed with the NuGet, would be pretty handy.   It would include mention of the XSD and instructions on how to add it to your VS, also recommendation to delete the XSD after installing in VS and why.  

Before we start, a lot of us like to study the configuration settings to learn what something can do.  It's a surprisingly effective way to get people thinking about what's possible and trigger questions.  So I think it's worth doing.

**Comment by gabikliot** [comment]
The file is located [here](https://github.com/dotnet/orleans/blob/master/src/Orleans/Configuration/OrleansConfiguration.xsd).

Added a link to it from [here](http://dotnet.github.io/orleans/Orleans-Configuration-Guide/).

**Comment by sergeybykov** [comment]
This is fixed in 1.0.5 where only Microsoft.Orleans.Server nugget brings OrleansConfiration.xsd. Grain interfaces and implementation projects are supposed to only include the respective Microsoft.Orleans.Templates packages.
