### ISSUE TITLE
add "last edited" and "last reviewed" dates to each documentation page

### ISSUE THREAD

**Issue by danvanderboom** [dotnet/orleans#2180]
When documentation lags behind current versions of Orleans (or any open source project) and the recommended best practices in using it, it can be helpful for developers to know how old that documentation is, how long ago it's been reviewed for relevance and current recommended practices, etc., before one blindly adopts the code in documentation. It doesn't have to be displayed prominently at the top necessarily, just consistently placed in the same location on every page.

"Originally written" and "last edited" might work better, or maybe just the one "last edited" date.

There's likely some open source tool that could automate updating these dates in the docs.

**Comment by danvanderboom** [comment]
Not that anyone should blindly adopt code from any online documentation :) but you all know what I mean.

**Comment by ashkan-saeedi-mazdeh** [comment]
This is a very good suggestion.
MS has this alongside the name of the editor on its docs I guess, so we might be able to do it using whatever they use.?

Not that we can force people to adapt good practices, otherwise I would crash any computer which a developer copied code from the browser and is trying to paste in the IDE containing a project more than 3.14 hours old :)

**Comment by JillHeaden** [comment]
I like this idea! I am adding it to the pages as I edit them.

**Comment by sergeybykov** [comment]
Wait. If we have to add/update such timestamps manually, I'm afraid that's too much manual work. That should be automatable I hope.

**Comment by JillHeaden** [comment]
I hope so, too. I don't know how to do it yet, but I am looking into it.

**Comment by sergeybykov** [comment]
Let's not add those markers manually then, so that we don't end up with a partial mess.

**Comment by ReubenBond** [comment]
I'm closing this for now as it's not actionable, but the point is well noted. I believe that moving documentation to docs.microsoft.com would be the best solution, since that version of DocFx supports this.
