### ISSUE TITLE
Communication between Silos

### ISSUE THREAD

**Issue by mauriciomagni** [dotnet/orleans#2194]
I am thinking of using Orleans to create an application using micro-services.
My goal is to have different services that interact between them, let's say the application will have:
AuthenticationService, WarehouseService and InvoicingService.
Now I need to communicate each service, I expect to have inside WarehouseService.Grain1 something like this:
            GrainClient.Initialize(ClientConfiguration.LocalhostSilo(37888));
            bool orleansClientInitialized = GrainClient.IsInitialized;
            ISessionGrain grain = GrainClient.GrainFactory.GetGrain<Realm.ISessionGrain>(id);
But the first line (GrainClient.Initialize) raises an exception: "WaWorkerHost.exe Error: 0 : [2016-09-21 11:05:39.363 GMT     5	ERROR  	100319	OutsideRuntimeClient	127.0.0.1:37000]	!!!!!!!!!! OutsideRuntimeClient constructor failed."

This raises some questions:
1. Does it make sense to implement micro-services using Orleans?
2. What is the proper way to communicate grains in different services.

Thank you,
Mauricio

**Comment by sergeybykov** [comment]
From inside a grain there is no need to initialize client, the runtime environment is already set up within a silo. So you can simply call `this.GrainFactory.GetGrain<ISessionGrain>(id)`. Client needs to be explicitly initialized outside of silos, typically at the frontends.

I see two options here:
 1. Implement multiple logical services as different grain classes (or sets of classes) that will directly call each other within a single silo cluster.
 2. Implement true microservices with each being one individually deployable.

1 is simpler and more efficient with direct calls between grains belonging to different logical services, but bundles deployment and servicing of those services. 
2 requires each microservice to be deployed to a separate cluster of silos (but not necessarily to different servers). In this case calls between the services will have to be made via their respective frontends.

**Comment by mauriciomagni** [comment]
Hello Sergey

Thank you for your response. 
I am trying to achieve option 2; in that case, you mentioned "calls between the services will have to be made via their respective frontends". Taking the risk of asking a silly question... this front-ends should be WCF services or Web APIs? or there is a kind of Orleans Fron-end for these cases?

Thank you,
Mauricio

**Comment by sergeybykov** [comment]
The typical design includes one or more frontend web servers that receive HTTP/REST/WebSocket requests from clients and are responsible for authentication, authorization, admission control, DDoS protection, etc. Each of the web servers initializes (once) `OrleansClient` with configuration pointing to the backend silo cluster of the respective service.

**Comment by mauriciomagni** [comment]
Thank you for your response, I will keep working based on it.
