### ISSUE TITLE
Geo-distributed gossip channel implementation for current membership back-ends

### ISSUE THREAD

**Issue by veikkoeeva** [dotnet/orleans#2207]
[Referencing earlier discussion](https://github.com/dotnet/orleans/pull/1800#issuecomment-236635086) (quoted in full at the end) with @sebastianburckhardt  on geo-distributed gossip channel implementation on other membership providers, is there more circumstantial documentation on this feature? From the earlier discussion it looks like the implementation revolves around [MultiClusterData](https://github.com/dotnet/orleans/search?utf8=%E2%9C%93&q=MultiClusterData).

I wonder if the work should be split into sub-issues as per current membership back-ends? @sebastianburckhardt mentions explicitly _ZooKeeper_ and _Consul_, but it’d be useful to support _ADO.NET_ too, I believe.

The quote:

> @veikkoeeva and others: Currently, the geo-distribution support is designed to be fully independent of the membership providers. Clusters can continue to manage their membership as before. For example, you could join two clusters into a multi-cluster even if each is using a different membership provider.
> Multi-clusters exchange configuration information through gossip channels (any number of them can be configured). There is no persistence requirement for gossip channels. The reason is that all the configuration information is redundantly stored in all the silos of all clusters, and in all the gossip channels, so losing any one channel is harmless.
> Gossip channels can be implemented in multiple ways, even though our current PR only contains one such implementation which is Azure tables. We implemented Azure tables first because they are convenient to access globally (they have a stable address, and access is secure over https). 
> We hope to have alternative gossip channel implementations in the future, such as:
> - running a gossip channel as a simple service in memory. Basically requires writing a server frontend. This is quite easy to do in principle - except that exactly how to run a service is something everyone may want to do a bit differently.
> - implement gossip channel on top of existing configuration services, e.g. ZooKeeper or Consul. This would require representing the MultiClusterData structure in a way that makes sense (mapping independent pieces of data to independent keys), just like it is currently done for Azure Tables.
>   Anyone, feel free to start an issue to discuss a particular GossipChannel implementation (feature request or proposed contribution).

**Comment by sebastianburckhardt** [comment]
Documentation is lagging at this point... what we have so far is this [word document](https://github.com/sebastianburckhardt/orleans/blob/geo-samples/geo/docs/Design-Documentation.docx), which does not contain much detail and is a bit out of date. I am planning to get some markdown documentation written up next week. 

Writing a gossip channel for ADO.NET seems like a good place to start. 

Looks to me like we can probably mimic the way things work currently for liveness and reminder services, as far as packaging of code and dependencies concerned.
