### ISSUE TITLE
How To Use ServiceBusQueue

### ISSUE THREAD

**Issue by NigelYu** [dotnet/orleans#2217]
In my Grains.cs file ,I want to use“QueueClient.CreateFromConnectionString(queueName)”   to create QueueClient ,but it dose not response.who can help me to  solve.
This is Code snippet:

 public async static Task SendAsync(string queueName,object objectData)
        {
            string connectionString = "Endpoint=sb://test.servicebus.chinacloudapi.cn/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=";
            if (queueName.IsNullOrEmpty())
            {
                throw new ArgumentException(nameof(queueName));
            }
            NamespaceManager namespaceManager = NamespaceManager.CreateFromConnectionString(
              connectionString);
            if (!namespaceManager.QueueExists(queueName))
            {
                namespaceManager.CreateQueue(queueName);
            }
            if (queueClinet == null)
            {
                queueClinet = QueueClient.CreateFromConnectionString(connectionString, queueName);
            }
            BrokeredMessage message = new BrokeredMessage(objectData.ToJson());
            await queueClinet.SendAsync(message);
 }

**Comment by sergeybykov** [comment]
I'm not familiar with the API. Does `CreateFromConnectionString()` by chance perform a network operation, e.g. a DNS lookup in a blocking fashion? That would be a problem.
/cc @jason-bragg @jdom

**Comment by jason-bragg** [comment]
Generally speaking, I didn't think the service bus apis had blocking calls without async counterparts, so if there is no CreateFromConnectionStringAsync then CreateFromConnectionString should not be blocking.  Having said that, I've not worked with service bus queues as much as EventHub, so my knowledge in this area is limited.

The QueueExists check and create queue operation are more likely to block than the CreateFromConnectionString.
