### ISSUE TITLE
Usage of HttpListener and HttpClient in Orleans

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [dotnet/orleans#2225]
I have to questions regarding Http communication in Orleans
1- Should we create one and only one HttpClient in the whole Orleans app or at least per grain and use it to avoid closing and opening many as grains activate and deactivate, Is there in inherit issues I don't recall?

2- If I want to listen to some http callbacks for authentication of OAuth-2 services for an Orleans based service, Is it a good approach to start a listener in a bootstrap provider and use it or I should make a separate app to do this which connects to Orleans as a client? I wonder can it make issues perf-wise at least for Orleans if I do it inside the silo to avoid the deployment of multiple applications? The same can be asked about hosting owin based WebAPI in silos behind a load balancer which only have the webApi port open, in this way requests will usually go for less network hops but might interfere with Orleans ?

**Comment by veikkoeeva** [comment]
@ashkan-saeedi-mazdeh

1. Maybe only one per silo, but there [are caveats there](https://github.com/dotnet/corefx/issues/11224).
2. You probably know already I personally think exposing Orleans silos to Internet isn't a good idea. :)

**Comment by sergeybykov** [comment]
Silo doesn't prevent grains from sharing things like statics. In legitimate cases that's actually a good pattern. One client per silo or a `ThreadLocal` per grain thread or a pool of clients - all these cases are easy to implement.

HTTP listeners is another question. @richorama already did something like that - https://github.com/OrleansContrib/OrleansHttp. I was thinking about opening another issue for that.
