### ISSUE TITLE
Streams vs Observers, An improvement is needed

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [dotnet/orleans#2235]
I'm fairly new to streams so there are chances I'm wrong in one way or another but as I'm experiencing, the current situation is like this:
- Observers are RPCs but handling their subscriptions is hard, you can not easily invalidate client subscriptions and at best you can guess based on time and clean the saved subscribers once in a while and a set of other issues which are more solvable than this.
- Streams doesn't suffer from any of the issues of observers, have much more flexibility and have lots of additional features but are more suitable for , well streaming data.

Now if I have events which I would like to tell about them to clients and don't suffer from the issues of observers, I have to use one stream per event specially if i can not express my event using a single value (e.g. string/enum) and need additional data for the event. 

Take this as an example. I have a Challenge system in place, A player can invite another to a challenge, the other player can accept/deny the challenge. We assume that clients will handle timeouts themselves, otherwise a timeout event can happen too. The challenge is for playing a realtime game. 

Also after a player accepts a challenge, a game is created for them and a challenge started event should be sent to the involved parties. Now some of these events need player IDs which are strings in my system, some need game ID which is a GUID in my system and in effect I have to use streams like this
"ChallengeStartedEvents" "ChallengeRequestEvents" "ChallengeAcceptedEvents" ...
I use the GUID for multi-tenancy and as the key for each user application. 
Now if observers didn't have the issue they have, I would need to just subscribe to one observer containing all these methods, now I need to subscribe to multiple streams. 

Can we somehow fix this by any way other than making streams type unsafe? 
Am I missing something?

**Comment by sergeybykov** [comment]
I would look at implementing this with a single stream of T per challenge, where T is a base class for all supported events, e.g. `ChallengeEvent`, with the specific events either being subclasses of it (cleaner) or expressed within `ChallengeEvent` as an enum and a set of extra field. This way, all parties would only need to subscribe to a single stream per challenge, and receive all possible events related to it.
Only if you need to separate visibility of certain events for different parties I would add additional streams.

**Comment by ashkan-saeedi-mazdeh** [comment]
@sergeybykov  Actually I ended up doing like what you said, but still aren't RPCs cleaner than that, I have a ChallengeEventData type for that including a Type which is an enum and a set of fields.

Maybe it's just me and not being used to streaming APIs but to me it is like old fashion messaging which we tried to avoid in Orleans. I say this because in this case a normal method call makes more sense to me but that's how we did it in Erlang indeed. We had an atom (like enum kinda) which we were doing pattern matching on and interpret rest of the message based on that. To me still an observer like system with a stream like subscriptions is a pretty nice thing however low priority since current system works and we have more important stuff to do.

What do you think? Am I wrong in my judgement?

**Comment by sergeybykov** [comment]
I don't know. I think we have a reasonable, not perfect of course, combination of async RPC and async streaming. We want at some point to consider a simplified and improved streaming API, a.k.a. Streaming v2. Ideas for that are welcome.

**Comment by ashkan-saeedi-mazdeh** [comment]
I will give it a good thought and will share ideas when the time comes for streams 2.0
To me we need to support

- Fire and forget
- sending data types with different signatures (i.e. RPC like streams)
- and have the nice subscription logic which streams have and observers don't

If we have these we can remove observers, I guess this is better than adding subscription logic and automatic serialization of it to observers since they have more limitations too.

From other aspects which stream can be improved, I am not ready to list anything other than those mentioned in the manual itself and by others as well, atm.
