### ISSUE TITLE
Timeouts when refreshing gateway silos - purging of the OrleansSiloInstances table

### ISSUE THREAD

**Issue by fsimonazzi** [dotnet/orleans#2250]
We've been facing an issue where a grain client fails to refresh gateway silos due to timeouts. After a while all the entries become stale and the client fails to communicate until restarted.

`ERROR  100921    Messaging.GatewayManager                XXX.XXX.XXX.XXX:0]   !!!!!!!!!! Exception occurred during RefreshSnapshotLiveGateways_TimerCallback -> listProvider.GetGateways()                
Exc level 0: System.TimeoutException: Task<T>.WaitForResultWithThrow has timed out after 00:00:03.
   at Orleans.OrleansTaskExtentions.WaitForResultWithThrow[T](Task'1 task, TimeSpan timeout)
   at Orleans.AzureUtils.OrleansSiloInstanceManager.FindAllGatewaySilos()
   at Orleans.AzureUtils.OrleansSiloInstanceManager.FindAllGatewayProxyEndpoints()
   at Orleans.AzureUtils.AzureGatewayListProvider.GetGateways()
   at Orleans.Messaging.GatewayManager.RefreshSnapshotLiveGateways_TimerCallback(Object context)" `

While trying to diagnose this issue we found that the OrleansSiloInstances had about 2.5k entries, all with the same partition key. We're using in place upgrades for the cloud service hosting the silos and the Web API front end, so the deployment id doesn't change. Even though this not enough to cause the timeout, we did find it could be a contributing factor as the queries for live instances will require a partition scan.

Have you seen this issue? Will it make sense to purge entries from this table periodically to minimize the impact of this factor? If so, is there a recommended practice?

**Comment by sergeybykov** [comment]
I don't beleive we've ever heard of such a problem. It is a bit strange that 3 seconds aren't enough for reading even 2.5K entries from the table. 

It is okay to delete old entries from the table.

**Comment by fsimonazzi** [comment]
Thanks Sergey. I don't think it's the only factor here. It's good to know you haven't seen this issue. I'll close and reopen if we find something relevant.
