### ISSUE TITLE
Access to grains from WebJobs hosted on same worker role as orleans silo

### ISSUE THREAD

**Issue by Lexelas** [dotnet/orleans#2290]
Hello

I'm trying to access grains from web job (https://azure.microsoft.com/en-us/documentation/articles/websites-dotnet-webjobs-sdk/). Typical job that involves grains might look like that 

```
public async Task ProcessQueueMessage([ServiceBusTrigger("test")] string inputText, [Blob("log/zyz.txt")]TextWriter writer)
{
            //do something with grains
            var result = await Task.Factory.StartNew(async delegate
            { 
                var grain = OrleansRuntime.GrainFactory.GetGrain<ICountTotalGrain>("test");  
                await grain.SetDelta(1);
                return (await grain.GetTotal()).ToString();
            }, CancellationToken.None, TaskCreationOptions.None, OrleansTaskScheduler).Unwrap();

            //do something in webjob context
            writer.WriteLine(result);
}
```

as you can see my code assume we have access to grainfactory via orleans runtime (IProviderRuntime) since we can't use grainclient because web jobs sdk is on the same server as silo. I also need orleans task scheduler to not violate single thread execution rule in orleans grains.

It is possible to store refence to both orleans task scheduler and runtime in for example DI container and share it with WebJobs SDK or any other code that is running in same environment (cloud service worker role) but i doubt it would be a good idea. Any hints how to call grains method from code outside of silo yet in same worker role ?

**Comment by sergeybykov** [comment]
>as you can see my code assume we have access to grainfactory via orleans runtime (IProviderRuntime) since we can't use grainclient because web jobs sdk is on the same server as silo. I also need orleans task scheduler to not violate single thread execution rule in orleans grains.

You can use `GrainClient` on the same server as silo, just not from the same AppDomain. Are you starting a silo from within the web job process and AppDomain? Can't you start it as a separate process or AppDomain? That would allow you to use `GrainClient` for calling grains, which is the intended use case for such a scenario.

If you do this, you won't need to deal with scheduler contexts and other stuff, which shouldn't be necessary here I think.

**Comment by Lexelas** [comment]
Right now both WebJobs and Orleans silo is staring in same appdomain. Basically i start webjobs after silo.Start() but before silo.Run().

I don't have much experience with appdomains so it is hard for me to say right now if it will work or not. I guess i will have to try make it work first and then eventually add followup questions if i fail :-)

**Comment by sergeybykov** [comment]
See, for example, how we start a test silo in an app domain - https://github.com/dotnet/orleans/blob/master/src/OrleansTestingHost/AppDomainSiloHandle.cs#L65.
