### ISSUE TITLE
OrleansJsonSerializer marked as internal in 1.3.0 nuget

### ISSUE THREAD

**Issue by amccool** [dotnet/orleans#2301]
I'm having a problem using `OrleansJsonSerializer` via the 1.3.0 nuget. Its marked as internal in the nuget library. 

But yet in https://github.com/dotnet/orleans/blob/1.3.0/src/Orleans/Serialization/OrleansJsonSerializer.cs its marked as public.

**Comment by jdom** [comment]
It appears @amccool was getting a different version from somewhere. The problem when away when he explicitly downloaded the package from the official nuget feed. Closing

**Comment by amccool** [comment]
needed to perform

```
C:\Users\XXXX\Source\Repos\Orleans.StorageProviders.SimpleSQLServerStorage>C:\Users\XXXX\Downloads\nuget.commandline.3.4.3.nupkg\tools\nuget locals all -clear
Clearing NuGet HTTP cache: C:\Users\xxx\AppData\Local\NuGet\v3-cache
Clearing NuGet cache: C:\Users\xxx\AppData\Local\NuGet\Cache
Clearing NuGet global packages cache: C:\Users\xxx\.nuget\packages\
Local resources cleared
```.
