### ISSUE TITLE
Failsafe Exception Serialization

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#2310]
We currently rely on all serialized types to be present during deserialization. This means that the assembly for any type transferred over the wire must be present on the receiving end. This is fine for most cases, but can be tricky for 'unexpected' types, such as exceptions.

Users would like to be able to see basic information about which exceptions are being thrown and from where, even if they are unable to deserialize the concrete exception. We can accomplish this using the `ILBasedSerializer`, adopting a special scheme for serializing Exceptions whereby base class fields are serialized first, like so:
`<FullTypeName><Length><ExceptionBaseClassFields><RemainingFields>`

Using this scheme, we can fall back to deserializing into `Exception` or an `OrleansFallbackException` class and retain the original `Message` and `StackTrace` properties along with the name of the original exception type.

I've prototyped this and added a test case. I can make it PR ready.

Thoughts? Should I pursue this?

**Comment by jdom** [comment]
I think it's valuable. Main cases is when the client does not have all the types that the silos use, but also the upcoming heterogeneous deployments, where not all silos are equal.
Unofortunately this will only work when ILBasedSerializer is used as the fallback, and not when using Binary Formatter, but still, I think it's good.
BTW, if I would state a preference, I'd call it something like RemoteNonDeserializableException (or something as non-ambiguous of that sort) and not make it inherit from OrleansException, since these are typically related to protocol.

**Comment by gabikliot** [comment]
+1

**Comment by sergeybykov** [comment]
What about non-exception types? Do we throw a meaningful exception if, say, a `Task<object>` method tries to return an object of a type not present on the caller's side?

**Comment by ReubenBond** [comment]
> Unfortunately this will only work when ILBasedSerializer is used as the fallback, and not when using Binary Formatter, but still, I think it's good.

Maybe we should switch to ILBasedSerializer :) We could default to ILBasedSerializer for exceptions and keep using BinaryFormatter for other exotic types.

> I'd call it something like RemoteNonDeserializableException (or something as non-ambiguous of that sort) and not make it inherit from OrleansException

Noted, lgtm.

> What about non-exception types? Do we throw a meaningful exception if, say, a Task<object> method tries to return an object of a type not present on the caller's side?

At the moment, a `TypeLoadException` will be thrown from both `ILBasedSerializer` and `BinaryFormatterSerializer`. It should contain the original type name, like so:
![image](https://cloud.githubusercontent.com/assets/203839/19456895/6c11f28a-950f-11e6-8095-d81600e0cf1e.png)

**Comment by sergeybykov** [comment]
>At the moment, a TypeLoadException will be thrown from both ILBasedSerializer and BinaryFormatterSerializer.

Is that the exception that will break the caller's `Task`?

**Comment by ReubenBond** [comment]
> Is that the exception that will break the caller's `Task`?

Actually, it looks like `FileNotFoundException` for the relevant assembly is thrown.
```Could not load file or assembly 'RuntimeTypeCreator, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.```

Regarding exceptions, here's what I've got:
```C#
public class RemoteNonDeserializableException : Exception
{
    /// <summary>
    /// Gets the type name of the original <see cref="Exception"/> represented by this instance.
    /// </summary>
    public string OriginalTypeName { get; internal set; }

    /// <summary>
    /// Gets or sets the data from the original exception which was not consumed by this instance.
    /// </summary>
    /// <remarks>
    /// This includes any fields in the original instance which are not present on the base <see cref="Exception"/> type.
    /// </remarks>
    internal byte[] UnconsumedData { get; set; }
}
```

Using this class, we can deserialize into the `RemoteNonDeserializableException` type and maintain the original type name (via `OriginalTypeName` field) with `StackTrace` and `InnerException` intact. We can then send that exception back to the silo which will deserialize it back into the *original* type with full fidelity - no loss of type/data 😄

To test this, I'm generating a new exception type at runtime on the silo, throwing it to the client, checking that it has the right `OriginalTypeName`/message/data, then passing it back to the server & inspecting it has the correct concrete type, message and data.

**Comment by jdom** [comment]
Lol, nice. BTW, let's override the ToString method so that it uses the original type name, and basically prints similar to the real deal and not like this proxy exception

**Comment by ReubenBond** [comment]
@jdom good suggestion, I've added it. This produces the same output as the original `.ToString()` except that assembly-qualified names are used instead of shortened 'full' names:
```C#
public override string ToString()
{
    if (string.IsNullOrWhiteSpace(this.OriginalTypeName)) return base.ToString();

    var builder = new StringBuilder();
    builder.Append(this.OriginalTypeName);
    if (!string.IsNullOrWhiteSpace(this.Message))
    {
        builder.Append(": ").Append(this.Message);
    }

    if (this.InnerException != null)
    {
        builder.Append(" ---> ")
                .AppendLine(this.InnerException.ToString())
                .Append("   --- End of inner exception stack trace ---");
    }

    builder.AppendLine();
    builder.Append(this.StackTrace);
    return builder.ToString();
}
```

**Comment by jdom** [comment]
Just be careful that exceptions that go over the wire and are then rethrown do not rely on the stack trace property, but on the stacktracestring and remotestacktracestring fields (or something like that). You should probably disassemble exception to see what I mean. Maybe it might just be simpler to call base.ToString and then replace the start of the string with the correct type name.

**Comment by ReubenBond** [comment]
Using the `StackTrace` property should always be safe.

The round-tripping support is currently unsound even if the exception itself does not change, since references in the serializer are absolute (relative to the beginning of the call to `Serialize`/`Deserialize`, not `SerializeInner`).

**Comment by jdom** [comment]
You are right about the StackTrace property. Now with the code in front of me, I got confused with the private _stackTrace field.
BTW, did you look at the [Exception.ToString implementation](https://referencesource.microsoft.com/#mscorlib/system/exception.cs,9ce1ff20e283169f)? Not sure if we should rely on private reflection, but as long as you set the _className private field, then the ToString will be as expected.

I'm not sure if I understand the round tripping issue you refer to. You mean the additional thing you talked about when sending this exception back to a silo that does have the correct exception type loaded?

**Comment by ReubenBond** [comment]
> You mean the additional thing you talked about when sending this exception back to a silo that does have the correct exception type loaded?

When I say round-tripping, I mean:

1. Silo throws unknown `SuperSecretException` to client (it will be deserialized into `RemoteNonDeserializableException`)
2. Client resends that exception to silo.

With round-tripping support, the silo will deserialize the exception as `SuperSecretException` as though it was known by both ends. Without round-tripping support, it will deserialize the exception as `RemoteNonDeserializableException`.

I'm saying that because of how serialization works, round-tripping cannot be supported without additional effort. This is due to our references system (which is a great system, imo).

**Comment by ReubenBond** [comment]
I've added support for round-tripping exceptions which don't add any additional fields to `Exception` & some tests for robustness.

I've made quite a lot of changes to ILBasedSerializer besides this latest one:
* Efficient enum serialization (statically selects the right integral type & directly encodes `Enum.ToObject` calls)
* Direct (non-boxing) serialization of simple types 
* Improvements to emitted IL:
  * Select between `call` & `callvirt` OpCode depending on method
  * Select between `Ldsfld` & `Ldfld` depending on whether a field is static or non-static
  * Use optimal OpCodes where applicable. Eg: `Ldarg_0` with no `int` value rather than `Ldarg` + `0`
* Cache result of `Type.GetTypeFromHandle` in static fields for generated IL rather than calling that method every time a `Type` is needed.
* (more) Compact representation of types
* Misc fixes like consolidating & renaming classes + reducing allocations

Should I submit a PR for each or lump them into one PR?

**Comment by jdom** [comment]
I would separate the exception stuff from the rest, since it's useful to have them separate.
For all the rest I guess it's fine to lump them in one PR, as they are all general serialization fixes. If different commits, even better, but not necessarily if it's too much extra work to split them up.

**Comment by kogir** [comment]
Since I'm currently encountering the exact scenario described in this issue (see #2528), please let me know if there's anything I can do help. I'd be happy to dig in and polish up the prototype implementation with a little guidance.

**Comment by sergeybykov** [comment]
Resolved via https://github.com/dotnet/orleans/pull/2633.

**Comment by skyflyer** [comment]
@ReubenBond, @sergeybykov, is this really resolved? I was seeing exception with the message `Could not load file or assembly 'Microsoft.EntityFrameworkCore...;` until I added the appropriate references to the client. I understand the mechanics - there is no way to deserialize a type which does not exist on the client, but reading this ticket, I thought that the type should be transformed to something readable at least?

The exception in question was indeed a `DbUpdateException`, but still -- is the only way forward to wrap all of the grain code with an exception wrapper and transform underlying exceptions into something all clients can handle?

Or am I missing a switch?

**Comment by ReubenBond** [comment]
Unfortunately this is only supported when using the `ILBasedSerializer` as a fallback serializer, which is not the default. The default serializer is BinaryFormatterSerializer, for backwards-compatibility reasons.

Perhaps we should port support to the default serializer or add a custom exception serializer which supports this. I'd feel more comfortable with that change once we have automated testing on a wider matrix of platforms (at least to include .NET Core 2.x rather than only .NET Framework 4.7.2)
