### ISSUE TITLE
Issues during Azure deployment

### ISSUE THREAD

**Issue by ponsakthi** [dotnet/orleans#2319]
We are using Orleans version 1.0.9

1)We are often seeing the following error in our silos.

> Response did not arrive on time in 00:01:00 for message: Request S10.241.170.52:11111:214572891_grn/D97D11B/a84263ac@85999b88->S10.76.34.82:11111:214573133_grn/91DE5597/37c0a8a4@628e5e81 #3854: GrainNameSpace.GrainName.MethodName(). Target History is: S10.76.34.82:11111:214573133:*grn/91DE5597/37c0a8a4:@628e5e81

2)We have 3 silo hosts and 2 clients in Azure Cloud Service. During deployment we get the following issue

> System.TimeoutException: Response did not arrive on time in 00:01:00 for message: NewPlacement Request S10.76.34.82:11111:214197380_grn/D97D11B/1aeda494@73c13bb9->S10.76.16.5:11111:214197610_grn/D66845D2/3130a881@b7cb0d91 #2477787: GrainNameSpace.GrainName.MethodName(). Target History is: S10.76.16.5:11111:214197610:*grn/D66845D2/3130a881:@b7cb0d91

For issue 1, is there any way to narrow down the grain(With Full GrainId) that is causing the bottle neck and dump its caller queue list? The Grain methods are not generally time consuming ones, but too many requests to the same grain may make the grain hot, which is what I assume is happening in our case. 

For issue 2, how do we know from logs that when a silo goes down all its activations are successfully migrated to other silo. Since it is Azure cloud service deployment atleast 1 workerrole(silo) will be active at any given time.

I saw that there are nice visualization tools available for 1.3.0 to help in these issues. But we will not be able to upgrade to 1.3.0 readily now.

Any workarounds or thoughts?

**Comment by sergeybykov** [comment]
This happens in the absence of any failures?

You can decode the target grain type identity by looking at how it is constructed in https://github.com/dotnet/orleans/blob/master/src/Orleans/IDs/GrainId.cs#L240. It's not straightforward to decode the type code part (`91DE5597` and `D66845D2`) but you probably have just a handful if grain classes anyway. I'm surprised to see "GrainNameSpace.GrainName.MethodName()." there. It should be the target grain class and method. Maybe it was a bug in 1.0.9, I don't remember.

>The Grain methods are not generally time consuming ones, but too many requests to the same grain may make the grain hot, which is what I assume is happening in our case. 

If you have a hot grain overloaded by too many requests, you should see warning in the log about that grain activation's queue size exceeding the threshold. Do you see that?

>For issue 2, how do we know from logs that when a silo goes down all its activations are successfully migrated to other silo.

They don't get migrated per se. They rather get activated on other remaining silos upon a first requests to each.

**Comment by ponsakthi** [comment]
> System.TimeoutException: Response did not arrive on time in 00:01:00 for message: NewPlacement Request 

The above error says it timed out while making a new placement.  Does that mean that the system is really loaded and Orleans was not able to activate a new grain?

**Comment by sergeybykov** [comment]
>Does that mean that the system is really loaded and Orleans was not able to activate a new grain?

I doubt that's the case. And it's easy to check by looking at the CPU utilization and slow turn execution warnings. Both should be in the log.

More often than not we see issues like that caused by blocking synchronous calls within grain code. Although I'm speculating until I can see the logs and, ideally, grain code.
