### ISSUE TITLE
Grain throws NullRefExceptions when using default constructor in unit test scenarios

### ISSUE THREAD

**Issue by rrector** [dotnet/orleans#2337]
Grain will throw difficult to track down NullReferenceExceptions when the default constructor is used to create grains in a unit test environment. Additionally, version 1.3 now throws NullRef exceptions in this scenario when accessing GrainFactory and ServiceProvider properties where these used to return null.

To aid in debugging, Orleans should provide more descriptive exceptions or expected results when the runtime is not available.

**Comment by sergeybykov** [comment]
Resolved via #2338.
