### ISSUE TITLE
Worker roles in a separate deployment cannot connect without secondary client

### ISSUE THREAD

**Issue by jschieck** [dotnet/orleans#2356]
We've encountered an interesting issue when setting up a new silo on azure running the latest version. Here's the setup:

Virtual Network (Classic)
    Silo Worker Role (DeploymentA)
    Client REST API Worker Role (DeploymentB)

Both use the AzureTable SystemStore and have matching DeploymentId's in their configuration. The setup works perfectly when in the emulator. When deployed however, the DeploymentB cannot connect to the Silo. It simply says "Found Gateway", tries to connect, cannot, then marks the silo as offline. The information in OrleansSiloInstances is correct. Now here's where it gets weird. We searched all over and double checked all the configurations and they were all correct. Then thought maybe it was an issue with the VN but that wasn't the case. We have another project using a slightly different setup so we tested it on that project and it worked fine. SO what finally ended up working for this project was the following.

Virtual Network (Classic)
    Silo Worker Role (DeploymentA)
    Test Client Worker Role (DeploymentA) <--- Simply prints hello world from a grain
    Client REST API Worker Role (DeploymentB)

When we added this second client worker role to the same deployment as the Silo, it connected and printed Hello World just fine. What's weird is it also allowed the client in DeploymentB to connect and work as expected. We then removed the test worker role, and again the client in DeploymentB stopped working.

Is there any known reason why having a client in the same deployment as the silo allows other clients to then connect? It doesn't seem like expected behavior. I'm wondering if we've stumbled across some kind of bug. It's also worth noting that there are no apparent errors or issues in the logs, and the silo and clients all startup without issue other than the connection.

**Comment by sergeybykov** [comment]
This is weird, indeed. I suspect it might be something with the vNet configuration. Orleans client simply tries to open a connection to the Gateway IP/port endpoint listed in the table. So it should work oblivious to whether or not there's another client in DeploymentA.

Can you manually try to connect to the Gateway endpoint (telnet?) from within a DeploymentB client VM (by remoting to it) with and without the Test Client to confirm that it's a networking issue? I just can't think what in Orleans can possibly prevent it from connecting.

**Comment by gabikliot** [comment]
Yes, sounds like an infrastructure/configuration problem in vnet setup.

**Comment by sergeybykov** [comment]
I'm closing this as it looks like an external infrastructure issue.

**Comment by jschieck** [comment]
Yeah we've done more digging and it appears that the Azure VN is not opening up internal endpoints  between roles without having more than one role in the silo deployment. The second role doesn't even need to be an Orleans client, just present in the deployment. Still haven't found a fix for that, but doesn't appear to be an issue with Orleans itself.

**Comment by sergeybykov** [comment]
@jschieck Thank for confirming!
