### ISSUE TITLE
.NET 4.6.2 in the vNext solution.  Upgrade to 1.3.0 get a very bad warning

### ISSUE THREAD

**Issue by sundong1982** [dotnet/orleans#2357]
When debugging press F11, from client into silo's grain，jump out of a page display： 
No source available   The source information is missing from the debugging information for this module

then the computer will become very slow

1.2.4 and 1.2.3 is ok!

**Comment by sergeybykov** [comment]
In the Modules window in debugger, do you see symbols loaded for Orleans binaries? You can right-click on, say, Orleans.dll and ask VS to load symbols.
