### ISSUE TITLE
Remove usage of named mutexes

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#2366]
As part of the first test of Orleans in .Net Core (#2145), I tried to run the @jdom Hello World sample project in Linux but it throw `PlatformNotSupportedException`:

```
Named synchronization primitives are not supported on this platform.
Exception = System.PlatformNotSupportedException: Named synchronization primitives are not supported on this platform.
   at System.Threading.EventWaitHandle..ctor(Boolean initialState, EventResetMode mode, String name, Boolean& createdNew, EventWaitHandleSecurity eventSecurity)
   at Orleans.Runtime.Host.SiloHost.StartOrleansSilo(Boolean catchExceptions)
```

That is one of the issues on coreclr repo related to it: https://github.com/dotnet/coreclr/issues/3422

We need to find a workaround for it.

**Comment by jdom** [comment]
BTW,  I used SiloHost in my samole, but could have used Silo directly. 
Still, we probably need to address this, just letting you know that it shouldn't be a blocker

**Comment by galvesribeiro** [comment]
@jdom yes, it is just a blocker on linux. There are other thtings I had to change on your hello world but we can talk offline when you get back.

**Comment by jdom** [comment]
What I meant is this is not a blocker, since you are not required to use SiloHost, so there is a valid workaround. That said, we still need to fix it

**Comment by galvesribeiro** [comment]
Oh! Ok, will change to silo directly and check it out

**Comment by galvesribeiro** [comment]
@jdom just confirmed. Replacing `SiloHost` with `Silo` did the trick: https://twitter.com/galvesribeiro/status/792455412746481664

**Comment by jdom** [comment]
Any takers to fix this one?

**Comment by galvesribeiro** [comment]
@jdom will ping u Monday and I can probably do that after align with you.

**Comment by galvesribeiro** [comment]
@JacobSnyder done on #2462
