### ISSUE TITLE
Links from Google are all broken

### ISSUE THREAD

**Issue by dandago** [dotnet/orleans#2368]
When the documentation was revamped, the link structure changed. If you follow a link from Google, you get:

"Sorry this page does not exist =("

Example: https://dotnet.github.io/orleans/Getting-Started-With-Orleans/Developing-a-Grain
Correct URL: http://dotnet.github.io/orleans/Documentation/Getting-Started-With-Orleans/Developing-a-Grain.html

This is causing a lot of inconvenience for people who want to go directly to a particular page in the documentation based on a targeted search.

**Comment by gabikliot** [comment]
Maybe we can add a redirect from the old to the new page?

**Comment by sergeybykov** [comment]
Isn't Google supposed to recrawl pages periodically?

**Comment by pditterline** [comment]
I'm seeing the new pages in google more now, but I've had the same issue. Might depend what you search for, but the old ones are definitely still coming up in search results.

For me, googling "orleans tutorial" (chose something randomly) gives me both the new page (first) and the old page (second) as results. Might go away eventually.

**Comment by sergeybykov** [comment]
@gabikliot can you reach for the `Flush` lever there to remove the outdated links?

**Comment by gabikliot** [comment]
Yes, sure, I will talk to my people.

**Comment by sergeybykov** [comment]
Let's rely on Google doing the right thing eventually.
