### ISSUE TITLE
Documentation is not printer friendly

### ISSUE THREAD

**Issue by dandago** [dotnet/orleans#2373]
The Orleans documentation doesn't print properly. Two main issues here:
1. Indentation of the main content is evident in the printout, resulting in lots of wasted whitespace on the left side.
2. An "improve this doc" link is superposed over the main content on every page.

![orleans-print-2](https://cloud.githubusercontent.com/assets/13241564/19836735/e6373bda-9ea9-11e6-93e3-74de77f5db06.png)
![orleans-print-1](https://cloud.githubusercontent.com/assets/13241564/19836734/e63634ec-9ea9-11e6-91c0-8ebd7b61aa08.png)

**Comment by dandago** [comment]
Also it is debatable whether including the full URL of each link is useful. For me it adds a lot of clutter; I can't actually click on it on paper, and it's very unlikely that I'm going to type it in.

**Comment by sergeybykov** [comment]
Is this a browser bug? IT's supposed to provide WYSIWYG. I'm not sure what we can do here.

**Comment by dandago** [comment]
No, the above screenshots are from Chrome but I get similar symptoms with Edge. This is a CSS thing; probably easy to fix if you have control over the output CSS.

**Comment by sergeybykov** [comment]
@richorama Do you know off the top of your head how much control over this we have?

<rant>Still sounds to me like browsers not doing their job of printing WYSIWYG.</rant>
But if we can work around it, that would help of course.

**Comment by richorama** [comment]
We don't override any of the CSS for printing, so it's the default DocFX behaviour. 

In fact we only override [a couple of templates](https://github.com/dotnet/orleans/tree/gh-pages/src/template) to customise the layout of the homepage.

Although we could add some custom CSS rules to change the formatting on print, I think it best if this was fixed upstream in the [DocFX repo](https://github.com/dotnet/docfx).

I have created an issue on the DocFX repo: https://github.com/dotnet/docfx/issues/852

**Comment by dandago** [comment]
This has been solved and can be closed.
