### ISSUE TITLE
GrainReference parsing has some drawbacks (e.g. delimiter collision)

### ISSUE THREAD

**Issue by peter-perot** [dotnet/orleans#2380]
Let's say we have the following grain interface:

```csharp
public interface IImageGrain<T> : IGrainWithStringKey
{
}
```

_Note: I don't know if it is possible to get a `GrainReference` instance from a "grain interface" reference in a different way than doing it in a storage provider; so all my testing took place in a storage provider implementation._

Say we have a grain

``` csharp
var g = GrainClient.GrainFactory.GetGrain<IImageGrain<StringBuilder>>(" foo ");
```

and let `gr` be the corresponding `GrainReference` instance.

Have a look at the following code (*):

``` csharp
var key = gr.ToKeyString();
var gr2 = GrainReference.FromKeyString(key);
Assert.AreEqual(gr, gr2); // exception here!
```

We get an exception here though the grain references should be considered equal.

However - the code works for the following grain instance:

``` csharp
var g = GrainClient.GrainFactory.GetGrain<IImageGrain<StringBuilder>>("foo");
```

It seems as if the spaces in the key `" foo "` are trimmed; this way the grain references are considered unequal.

But we are not done yet. Say we have the following grain instance:

``` csharp
var g = GrainClient.GrainFactory.GetGrain<IImageGrain<StringBuilder>>(
    " GenericArguments=foo ");
```

The code above (*) throws an exception when parsing the key of this grain. The reason is that the key contains a magic string: `"GenericArguments="`.

This is sort of a [delimiter collision](https://en.wikipedia.org/wiki/Delimiter#Delimiter_collision).

**Comment by peter-perot** [comment]
**Proposal for a solution:**

Encode the string part of the grain key with Base64 **without** padding.

```csharp
string encodedKey = Convert.ToBase64String(key).Replace("=", "");
```

Since all magic strings I have seen in the source code contain the `=` character, there is no way to get a collision.

To decode the string part of the key, you simply do this:

``` csharp
string key = Convert.FromBase64String(
    encodedText.PadRight(encodedKey.Length + (4 - encodedKey.Length % 4) % 4, '='));
```

The bad thing: this would be a breaking change, since any data persisted by a storage provider will not be found anymore using the new version.

**Comment by sergeybykov** [comment]
We should look at this as part of revisiting the grain/stream identity question.

https://github.com/dotnet/orleans/issues/1123
https://github.com/dotnet/orleans/issues/1882
https://github.com/dotnet/orleans/issues/2115

**Comment by ReubenBond** [comment]
This should not be an issue for 7.0+. Please open a new issue if you find that I am mistaken.
