### ISSUE TITLE
Unity3d can use the Orleans client dll directly or not?

### ISSUE THREAD

**Issue by Jesse1205** [dotnet/orleans#2398]

**Comment by ReubenBond** [comment]
Typically Orleans is intended for deployment and access within a cloud service environment and should not be directly exposed to untrusted clients, so even if Unity3d could reference Orleans.dll directly, it would currently be strongly advised against.

One common architecture is to put Web frontend machines in front of an Orleans cluster. The Web front-ends handle authentication and make requests directly to the Orleans cluster.

If you describe your scenario in more detail, I can try to offer suggestions.

Hope that helps! 😄

**Comment by Jesse1205** [comment]
Thanks much ， If  use the socket server , I should create a console application to connect the Orleans?

**Comment by ReubenBond** [comment]
@Jesse1205 yes, you can host a socket server online and use it to access Orleans

**Comment by Jesse1205** [comment]
Thank you !
