### ISSUE TITLE
Warning "No target activation" with subsequent exception

### ISSUE THREAD

**Issue by peter-perot** [dotnet/orleans#2412]
I have the following grain interface and implementation (simplified version):

``` csharp
public interface IUserAccountContextGrain : IGrainWithStringKey
{
  Task Expire();

  Task Initialize();

  Task TimerCallbackInternal(Guid timerId);
}
```

``` csharp
public class UserAccountContextGrain : Grain, IUserAccountContextGrain
{
  private static readonly TimeSpan expirationTime = TimeSpan.FromMinutes(5);

  private IDisposable timer;
  private Guid timerId;

  public Task Expire()
  {
    this.UninitializeAndDeactivate();
    return TaskDone.Done;
  }

  public async Task Initialize()
  {
    this.Uninitialize();

    this.ConfigureTimer();
    this.isFullyInitialized = true;
  }

  public override Task OnActivateAsync()
  {
    this.DelayDeactivation(expirationTime + TimeSpan.FromHours(1));
    return base.OnActivateAsync();
  }

  public Task TimerCallbackInternal(Guid timerId)
  {
    if (!this.isFullyInitialized)
    {
      this.UninitializeAndDeactivate();
      return TaskDone.Done;
    }

    if (this.timerId != timerId)
    {
      return TaskDone.Done;
    }

    this.UninitializeAndDeactivate();
    return TaskDone.Done;
  }

  private void ConfigureTimer()
  {
    this.timerId = Guid.NewGuid();
    this.timer?.Dispose();

    this.timer = this.RegisterTimer(this.TimerCallback, null, expirationTime, Timeout.InfiniteTimeSpan);
  }

  private Task TimerCallback(object state)
  {
    this.timerId = Guid.NewGuid();

    var thisGrain = this.GrainFactory.GetGrain<IUserAccountContextGrain>(this.GetPrimaryKeyString());
    return thisGrain.TimerCallbackInternal(this.timerId);
  }

  private void Uninitialize()
  {
    this.isFullyInitialized = false;

    this.timerId = Guid.NewGuid();
    this.timer?.Dispose();
    this.timer = null;
  }

  private void UninitializeAndDeactivate()
  {
    this.Uninitialize();
    this.DeactivateOnIdle();
  }
}
```

Basically the code in this simplified does nothing but deactivating the grain after five minutes (if not `Initialize()` is called again and before the timeout). [In the fully fleshed out version the grain additionally caches some data which expires after 5 minutes.]

Once in a while I see the following error message in the logs:

```
[2016-11-10 15:51:54.944 GMT    11	WARNING	100148	Dispatcher	127.0.0.1:11145]	No target activation S127.0.0.1:11145:216479237*grn/F8F8090E/00000000+TEST_SPED_1008@50b38c98 for response message: Response S127.0.0.1:11145:216479237*grn/F8F8090E/00000000+TEST_SPED_1008@50b38c98->S127.0.0.1:11145:216479237*grn/F8F8090E/00000000+TEST_SPED_1008@50b38c98 #51499: global::Services.Infrastructure.Grains.IUserSessionRegistryGrain:TimerCallbackInternal()	
[2016-11-10 15:52:24.929 GMT     8	WARNING	100157	CallbackData	127.0.0.1:11145]	Response did not arrive on time in 00:00:30 for message: Request S127.0.0.1:11145:216479237*grn/F8F8090E/00000000+TEST_SPED_1008@50b38c98->S127.0.0.1:11145:216479237*grn/F8F8090E/00000000+TEST_SPED_1008@50b38c98 #51499: global::Services.Infrastructure.Grains.IUserSessionRegistryGrain:TimerCallbackInternal(). Target History is: <S127.0.0.1:11145:216479237:*grn/F8F8090E/00000000+TEST_SPED_1008:@50b38c98>. About to break its promise.	
[2016-11-10 15:52:24.929 GMT     8	WARNING	101217	Scheduler.WorkItemGroup	127.0.0.1:11145]	Enqueuing task System.Threading.Tasks.ContinuationTaskFromResultTask`1[System.Object] to a stopped work item group. Going to ignore and not execute it. The likely reason is that the task is not being 'awaited' properly. WorkItemGroup:Name=[Activation: S127.0.0.1:11145:216479237*grn/F8F8090E/00000000+TEST_SPED_1008@50b38c98 #GrainType=Services.Infrastructure.Grains.Implementations.UserSessionRegistryGrain Placement=RandomPlacement],WorkGroupStatus=Shutdown. Currently QueuedWorkItems=0; Total EnQueued=48; Total processed=48; Quantum expirations=0; TaskRunner=ActivationTaskScheduler-38:Queued=0; Detailed SchedulingContext=<[Activation: S127.0.0.1:11145:216479237*grn/F8F8090E/0000000000000000000000000000000006fffffff8f8090e+TEST_SPED_1008-0x858ACCA8@50b38c98 #GrainType=Services.Infrastructure.Grains.Implementations.UserSessionRegistryGrain Placement=RandomPlacement State=Invalid NonReentrancyQueueSize=0 EnqueuedOnDispatcher=0 InFlightCount=0 NumRunning=0 IdlenessTimeSpan=00:00:30.0001003 CollectionAgeLimit=02:00:00]>	
[2016-11-10 15:52:34.335 GMT     2	ERROR  	100102	Silo	127.0.0.1:11145]	!!!!!!!!!! Silo caught an UnobservedException with context==null.	
Exc level 0: System.TimeoutException: Response did not arrive on time in 00:00:30 for message: Request S127.0.0.1:11145:216479237*grn/F8F8090E/00000000+TEST_SPED_1008@50b38c98->S127.0.0.1:11145:216479237*grn/F8F8090E/00000000+TEST_SPED_1008@50b38c98 #51499: global::Services.Infrastructure.Grains.IUserSessionRegistryGrain:TimerCallbackInternal(). Target History is: <S127.0.0.1:11145:216479237:*grn/F8F8090E/00000000+TEST_SPED_1008:@50b38c98>.
[2016-11-10 15:52:34.351 GMT     2	ERROR  	100005	UnobservedExceptionHandler	127.0.0.1:11145]	!!!!!!!!!! UnobservedExceptionsHandlerClass Caught an UnobservedTaskException event sent by [Id=392675, Status=Faulted]. Exception = 
Exc level 0: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
Exc level 1: System.TimeoutException: Response did not arrive on time in 00:00:30 for message: Request S127.0.0.1:11145:216479237*grn/F8F8090E/00000000+TEST_SPED_1008@50b38c98->S127.0.0.1:11145:216479237*grn/F8F8090E/00000000+TEST_SPED_1008@50b38c98 #51499: global::Services.Infrastructure.Grains.IUserSessionRegistryGrain:TimerCallbackInternal(). Target History is: <S127.0.0.1:11145:216479237:*grn/F8F8090E/00000000+TEST_SPED_1008:@50b38c98>.	
[2016-11-10 15:52:34.351 GMT     2	ERROR  	100006	UnobservedExceptionHandler	127.0.0.1:11145]	!!!!!!!!!! Exception remained UnObserved!!! The subsequent behavior depends on the ThrowUnobservedTaskExceptions setting in app config and .NET version.	
```

It seems that the Task returned from `TimerCallbackInternal()` has lost it's target activation. I think the problem lies in these two methods:

``` csharp
public Task TimerCallbackInternal(Guid timerId)
{
  if (!this.isFullyInitialized)
  {
    this.UninitializeAndDeactivate();
    return TaskDone.Done;
  }

  if (this.timerId != timerId)
  {
    return TaskDone.Done;
  }

  this.UninitializeAndDeactivate();
  return TaskDone.Done;
}

private Task TimerCallback(object state)
{
  this.timerId = Guid.NewGuid();

  var thisGrain = this.GrainFactory.GetGrain<IUserAccountContextGrain>(this.GetPrimaryKeyString());
  return thisGrain.TimerCallbackInternal(this.timerId);
}
```

The reason for this code...

```csharp
var thisGrain = this.GrainFactory.GetGrain<IUserAccountContextGrain>(this.GetPrimaryKeyString());
return thisGrain.TimerCallbackInternal(this.timerId);
```

... is to get non-reentrant behavior (since timer callbacks are handled in a reentrant manner in Orleans).

Any ideas?

**Comment by peter-perot** [comment]
Maybe the problem here is that the timer is disposed in the timer callback itself. In `ActivationData.cs` I see a method called `WaitForAllTimersToFinish()` which checks for registered timers. Could it be that since the callback disposes its own timer, the grain is sometimes deactivated too early?

Just a suggestion.

**Comment by gabikliot** [comment]
Just add logging in deactivate async and heavily in your code: before and after you call the inner timer method, and when the outer timer method is called, and when you initialize and uninitialize.

**Comment by gabikliot** [comment]
OK, I got it. The problem is indeed related to what @peter-perot  said: you are disposing the timer within the timer callback.
Usually there is no problem with that and it is allowed. But the right way to do it is to dispose the timer as the last thing in the method and do nothing async after that.
But in your case when you dispose the timer you still have an outstanding request in flight and the response arrives AFTER timer was disposed (that is since you dispose inside the call and not inside the timer callback). By the time the response arrives, the activation is already gone. So its just like non-awaited call (by disposing the time you told us: don't await the timer callback).

The fix on your side could be to move the timer dispose outside the `TimerCallbackInternal` and AFTER the call to TimerCallbackInternal was awaited.

On the Orleans side if we want to handle his case correctly, I think the most robust approach is to wait with deactivation to all outsanding requests (wait until all responses arrived). We currently do not do that.
We only wait for current request and all timers. We currently don't have an effecient way to know all the outstanding requests for an activation, since the global per silo data structure of all requests (callback datas) is keyed on request id, and not on activation id. We could change that in needed, or track all outstanding requests inside the activation data. Sounds a bit overkill just for that case, but it will be the correct way that will handle potentially other cases (like if you realty did not await a request inside the regular method call). On the flip side, that would delay the deactivation, which arguably, by not awaiting you told us explicitly to not await. So its not even clear if this is "the right way".

**Comment by peter-perot** [comment]
Thank you, @gabikliot. I changed the code as follows:

``` csharp
    // returns true if the grain should be kept activated;
    // otherwise, the grain should be deactivated
    public Task<bool> TimerCallbackInternal(Guid timerId)
    {
      if (!this.isFullyInitialized)
      {
        return Task.FromResult(false);
      }

      if (this.timerId != timerId)
      {
        return Task.FromResult(true);
      }

      return Task.FromResult(false);
    }

    private async Task TimerCallback(object state)
    {
      this.timerId = Guid.NewGuid();
      var thisGrain = this.GrainFactory.GetGrain<IUserSessionRegistryGrain>(this.GetPrimaryKeyString());

      if (!await thisGrain.TimerCallbackInternal(this.timerId))
      {
        this.UninitializeAndDeactivate();
      }
    }
```

This way `UninitializeAndDeactivate()` (which contains the `DeactivateOnIdle()` call and the disposal of the timer instance) is called from the timer callback.

**Comment by peter-perot** [comment]
In this context I have two questions:

### Question 1: Interleaving

**Q 1.a:** In method `TimerCallback(...)` **immediately before** `thisGrain.TimerCallbackInternal(this.timerId)` is called, is it possible that another queued call is handled first before the `TimerCallbackInternal(...)` call gets handled?

**Q 1.b:** In method `TimerCallback(...)` **immediately after** `thisGrain.TimerCallbackInternal(this.timerId)` completes, is it possible that another queued call is handled first before the `TimerCallbackInternal(...)` call returns its result?

``` csharp
    private async Task TimerCallback(object state)
    {
      this.timerId = Guid.NewGuid();
      var thisGrain = this.GrainFactory.GetGrain<IUserSessionRegistryGrain>(this.GetPrimaryKeyString());

      if (
        // interleaving possible here?
        !await thisGrain.TimerCallbackInternal(this.timerId)
        // interleaving possible here?
      )
      {
        this.UninitializeAndDeactivate();
      }
```

### Question 2: Timer Disposal

1. Say a thread is currently executing code in method `MethodA()` of a non-reentrant grain `GrainA`.

2. During execution of step (1) a grain timer fires an event on `GrainA`. The callback is not executed immedialely since we have a turn-based execution model; instead it is queued.

3. Let's assume that the thread of step (1) is still in method `MethodA()`, and now the timer which caused the event of step (2) is disposed.

**Q:** What happens to the queued callback of step (2)? Is it dropped since the timer has been disposed, or is it executed after `MethodA()` returns?

[HINT: Since I do not know the exact behavior I introduced the `timerId` GUID in my code above, just to skip outdated callbacks.]

**Comment by sergeybykov** [comment]
>Q 1.a: In method TimerCallback(...) immediately before thisGrain.TimerCallbackInternal(this.timerId) is called, is it possible that another queued call is handled first before the TimerCallbackInternal(...) call gets handled?

Not for non-reentrant grains. Not event for reentrant grains, if there is no `await` before that line.

>Q 1.b: In method TimerCallback(...) immediately after thisGrain.TimerCallbackInternal(this.timerId) completes (the return value/task/message is available), is it possible that another queued call is handled first before the TimerCallbackInternal(...) call returns its result and execution continues in method TimerCallback?

After `await` executes and returns the value, it's not possible. Between the call to `thisGrain.TimerCallbackInternal` and `await` returning, it is possible for reentrant grains.

>Q: What happens to the queued callback of step (2)? Is it dropped since the timer has been disposed, or is it executed after MethodA() returns?

The enqueued callback should execute after MethodA() returns regardless of whether the timer has been disposed or not.

**Comment by peter-perot** [comment]
@sergeybykov: Just to clarify - assuming we have a **reentrant** grain, will the following code execute without breaking the assertions even if `MethodC()` is called heavily from an other unrelated grain?

``` csharp
[Reentrant]
public class MyGrain : Grain, IMyGrain
{
  private Guid guid;

  public async Task MethodA()
  {
    this.guid = Guid.NewGuid();
    var guidToCheck = await this.MethodB(this.guid);

    Debug.Assert(this.guid == guidToCheck);
  }

  public Task<Guid> MethodB(Guid guidToCheck)
  {
    Debug.Assert(this.guid == guidToCheck);

    this.guid = Guid.NewGuid();
    return Task.FromResult(this.guid);
  }

  public Task MethodC()
  {
    this.guid = Guid.NewGuid();
    return TaskDone.Done;
  }
}
```

**Comment by sergeybykov** [comment]
The assertion will get violated at some point because in between a) the moment `thisGrain.MethodB(this.guid) returns a `Task<Guid>` and b) the moment `await` "returns" a value for the Guid, one or more requests to any method of the grain can get executed.

One way to visualize it is that there is a thick line going across the `await` keyword, and within that thick line many requests can get in and get processed.

`Task<Guid> t = thisGrain.MethodB(this.guid);`
`---------------`
`await`
`---------------`
`var guidToCheck = t.Result;`

**Comment by peter-perot** [comment]
Thank you, @sergeybykov - I suspected this to be the case. So the line

``` csharp
if (!await thisGrain.TimerCallbackInternal(this.timerId))
{
  this.UninitializeAndDeactivate();
}
```

in my code sample above should read

``` csharp
var tempTimerId = this.timerId;

if (!await thisGrain.TimerCallbackInternal(tempTimerId) && this.timerId == tempTimerId)
{
  this.UninitializeAndDeactivate();
}
```

to prevent uninitialization in case the old timer has been disposed and a new one has been created (with a new `timerId`.

Corrected code of the example above in the thread:

``` csharp    
    // returns true if the grain should be kept activated;
    // otherwise, the grain should be deactivated
    public Task<bool> TimerCallbackInternal(Guid timerId)
    {
      if (!this.isFullyInitialized)
      {
        return Task.FromResult(false);
      }

      if (this.timerId != timerId)
      {
        return Task.FromResult(true);
      }

      return Task.FromResult(false);
    }

    private async Task TimerCallback(object state)
    {
      var tempTimerId = this.timerId = Guid.NewGuid();
      var thisGrain = this.GrainFactory.GetGrain<IUserSessionRegistryGrain>(this.GetPrimaryKeyString());

      if (!await thisGrain.TimerCallbackInternal(tempTimerId) && this.timerId == tempTimerId)
      {
        this.UninitializeAndDeactivate();
      }
    }
```

**Comment by peter-perot** [comment]
@gabikliot, @sergeybykov: I think we can close this issue, since I don't think that the behavior of timers in case of an early disposal needs to be changed. But it would be nice to mention this behavior in the docs. When I have some time left I would send you a PR for updating the docs if you like.

**Comment by sergeybykov** [comment]
I don't understand why `TimerCallbackInternal` returns a `Task<bool>`. It executes synchronously and could or should simply return a `bool`. Then you won't need the `await`. Unless this is an incomplete implementation and the real `TimerCallbackInternal` will end up making async calls.

**Comment by peter-perot** [comment]
@sergeybykov: Yes, this is an incomplete implementation. I use it as a pattern for grains I call "expirable grains" which have a defined expiration time. In the fully fleshed out implementations of this pattern, async stuff can occur in the `TimerCallbackInternal()` method; this async stuff has to be executed with non-reentrant behavior, and that's the reason why I call `TimerCallbackInternal()` from `TimerCallback(…)`: timer callbacks execute with reentrant behavior (no matter if the grain is declared reentrant or not).

**Comment by sergeybykov** [comment]
@peter-perot, is this resolved?
