### ISSUE TITLE
Serializing Entity with ObservableCollection

### ISSUE THREAD

**Issue by mauriciomagni** [dotnet/orleans#2416]
Hello 

I have a PCL with entities to be shared between the backend and the frontend.
In order to use these entities in the frontend I want to take advantage of an observable collection. To avoid issues with the events raised by the observable collection during deserialization I created an additional array property. The code:
```C#
[IgnoreDataMember]
[JsonIgnore]
[NonSerialized]
public ObservableCollection<UserTenantEntity> TenantCollection { get; set; }
[DataMember]
public UserTenantEntity[] TenantArray { get; set; }
```
I was trying to make Orleans ignore the property TenantCollection (you can see IgnoreDataMember, JsonIgrnore, NonSerialized). But Orleans keeps producing in DeepCopier method this line:
```C#
result.@TenantCollection = (global::System.Collections.ObjectModel.ObservableCollection<global::Visible.Realm.UserTenantEntity>)global::Orleans.Serialization.SerializationManager.@DeepCopyInner(input.@TenantCollection);
```

When running the test I get this message:
```
Type 'Visible.Realm.UserTenantEntity' in Assembly 'RealmService.Entities, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
```
This message disappears if instead of using an ObservableCollection is used a List.

Is there any way to instruct Orleans not to serialize a property? 

Thank you,
Mauricio.

**Comment by ReubenBond** [comment]
The serializer likely doesn't know how to serialize `ObservableCollection<T>`, so it is falling back to the 'fallback serializer', which uses `BinaryFormatter` by default. `BinaryFormatter` can only serialize types marked as `[Serializable]`.

What I don't understand is how you're able to put `[NonSerialized]` on a property, when AFAICT, `[NonSerialized]` is for fields only.

```C#
[AttributeUsage(AttributeTargets.Field, Inherited = false)]
[ComVisible(true)]
public sealed class NonSerializedAttribute : Attribute
```

Orleans *does* respect `[NonSerialized]` - we use it often. You will need to use a field instead of a property, though.

Does this answer your question?

**Comment by mauriciomagni** [comment]
Hello Reuben

The NonSerialized attribute was a desperate intent using bait and switch to see if it worked, but it did not (the attribute was tweaked to accept properties).
I was trying to instruct Orleans to just ignore my observablecollection property, I was unable to reached that goal. 

I even tried to create a class to force a json serialization but that make my testing failed in a really weird way (no message at all). 

Is it possible to ask Orleans code generator to ignore a property?

Thank you in advance,
Mauricio.

**Comment by ReubenBond** [comment]
We could potentially include a NonSerialized attribute which is valid on autoproperties to instruct our serializer. As a work around, you can make this a field-backed property (manual get and set) and use NonSerialized on it. Does that work?

**Comment by mauriciomagni** [comment]
I will implement it as a field, it should work and let me move forward.
For the future I would love to see custom Orleans attributes that could be used in Portable Libraries. 
Thank you for your support.
