### ISSUE TITLE
Intermittent Reminder Issue: Grain implementation

### ISSUE THREAD

**Issue by dandago** [dotnet/orleans#2419]
We are getting this intermittent problem with reminders. Every few iterations, we get this error:

    [2016-11-14 14:50:28.419 GMT    21      ERROR   102915  ReminderService 127.0.0.1:11111]        !!!!!!!!!! Could not deliver reminder tick for [[ReminderName], GrainReference:*grn/D2636715/0000000000000000000000000000000006ffffffd2636715+[GrainName]-0x4BE9D7B4, 00:05:00, 2016-11-08 16:45:27.663 GMT, 18, 10, Ticking], next 14-Nov-16 14:55:28.
    Exc level 0: Orleans.Runtime.OrleansException: Unexpected: Cannot find an implementation class for grain interface -765237483
      at Orleans.Runtime.GrainTypeManager.GetTypeInfo(Int32 typeCode, String& grainClass, PlacementStrategy& placement, MultiClusterRegistrationStrategy& activationStrategy, String genericArguments)
      at Orleans.Runtime.Dispatcher.<AddressMessage>d__32.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Orleans.Runtime.Dispatcher.<AsyncSendMessage>d__29.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Orleans.Runtime.ReminderService.LocalReminderService.LocalReminderData.<OnTimerTick>d__19.MoveNext()

Haven't really investigated it in detail so that's all the info I have available at the moment.

**Comment by sergeybykov** [comment]
Does the target grain class implement `IRemindable`?

**Comment by dandago** [comment]
I suppose so; I'll confirm when I'm back at work.

However I imagine that if something like that were missing, then it would fail consistently (as opposed to once every few iterations), no?

**Comment by sergeybykov** [comment]
Sorry, I was wrong - we check within `RegisterOrUpdateReminder` that the grain class implements `IRemindable`. So this shouldn't be possible.

Can you search in the orleans.codegen.cs for -765237483 to see what interface that it?

**Comment by centur** [comment]
We had that issue before - there is a chance that someone registered a reminder for a grain, then the grain was removed or refactored completely, and reminder stays there unregistered but trying to tick. 
Check the Grain name in the GrainIdentity line - this is what was removed or renamed probably.

**Comment by veikkoeeva** [comment]
@centur Maybe there is a place for a little fix to be logged and done in the future where a clearer message and some instructions are provided?

**Comment by DixonDs** [comment]
@centur Will it make sense to remove such reminders automatically (on the first reminder invocation, for instance), if the target grain type doesn't exist anymore?

**Comment by sergeybykov** [comment]
>@centur Will it make sense to remove such reminders automatically (on the first reminder invocation, for instance), if the target grain type doesn't exist anymore? 

This is a dangerous option I think. A deployment mistake would potentially cause wiping of all reminders.

**Comment by gabikliot** [comment]
I agree it's dangerous. Potentially better is to have a manually executed tool, which will slowly scan the reminder table,  try to poke each grain, and delete if wrong code. We can add a no op pocke method to the grain, which will be invisible to the grain code, and only used by those health check tools .

**Comment by veikkoeeva** [comment]
Could a method added to `IManagementGrain` that could provide a list of orphaned rows and a purge operation? This could be useful for storage providers too. The ADO.NET one, for instance, does not purge the table unless the user specifically does an in-storage scrubbing operation. This is to avoid some potentially serious index and deadlocking issues while the `DELETE` operations are running.

**Comment by centur** [comment]
@DixonDs I don't think that it's valid for the framework to decide what must be removed automatically, especially when reminders are used as part of business logic . I'd prefer to have more details in the logs and some way to list all of the orphaned and valid reminders, as well as some options to clean up these entries.

**Comment by DixonDs** [comment]
I agree with @sergeybykov that could be dangerous in case of human error (although in case of deployment mistake much worse issues may happen anyway), but there should some cleanup options in case of some grains deliberately gone for good - at least some API for listing and deleting orphaned reminders.

btw I think a similar problem could be with stream subscriptions when subscribed grains are not there anymore.
