### ISSUE TITLE
error.txt from ClientCodeGenerator created in wrong folder.

### ISSUE THREAD

**Issue by attilah** [dotnet/orleans#2431]
When ClientGenerator fails it outputs an error.txt file, but into the project's folder (or current workign folder) instead of the intermediate directory of the project.

I think it should be in the very same directory where it was invoked from where commandargs.txt is put by bootstrapping.

**Comment by ReubenBond** [comment]
Or we could just get rid of `error.txt`, the output can be seen during the build anyway.

**Comment by sergeybykov** [comment]
I'm fine with removing error.txt altogether.

**Comment by attilah** [comment]
Solved by not writing error.txt at all.
