### ISSUE TITLE
Codegen error when a method argument type has nested private class

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#2433]
I have a case then the result type of a grain method uses class X which have nested private class Y defined. Codegen fails to generate proper serializer code for class X.

I have something like this in X serializer code:
```
private static readonly global::System.Func<global::MyNamespace.X, global::MyNamespace.X.Y> getField0 = (global::System.Func<global::MyNamespace.X, global::MyNamespace.X.Y>)global::Orleans.Serialization.SerializationManager.@GetGetter(field0);
private static readonly global::System.Action<global::MyNamespace.X, global::MyNamespace.X.Y> setField0 = (global::System.Action<global::MyNamespace.X, global::MyNamespace.X.Y>)global::Orleans.Serialization.SerializationManager.@GetReferenceSetter(field0);
```

and it cannot be compiled because of `error CS0122: 'X.Y' is inaccessible due to its protection level `

Is it something that can be fixed in Orleans or I need to refactor my code so that nested classes are avoided in objects passed to/from Orleans?

**Comment by ReubenBond** [comment]
@DixonDs I'm surprised it generated that code - it should have avoided generating the serializer, since the type is not accessible. Regarding the code you posted: what code should be generated in order for that to work?

**Comment by DixonDs** [comment]
@ReubenBond Unfortunately, I am not really familiar how the code generation works, so I can't answer your last question. 

Other interesting thing is that I just downgraded from 1.3.1 to 1.3.0, and the serializer is not generated for type X at all, and everything seems to be working ok.

**Comment by ReubenBond** [comment]
Interesting. Is the error reproducible with any nested private class?

**Comment by DixonDs** [comment]
@ReubenBond Not any it seems. I was able to create a simple class that could be used for reproducing this error:
```
public class MainClass
    {
        private List<NestedClass> _field;

        public MainClass(string value) : this(new List<NestedClass> { new NestedClass { Property = value } })
        {
        }

        private MainClass(List<NestedClass> field)
        {
            _field = field;
        }

        private class NestedClass
        {
            public string Property { get; set; }
        }
    }
```
