### ISSUE TITLE
External Tasks + Client Observers

### ISSUE THREAD

**Issue by mtdaniels** [dotnet/orleans#2455]
I have a grain which uses an external task (Task.Run) to perform some work.  After it is complete, observers are notified.  I have read through http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/External-Tasks-and-Grains.html and http://dotnet.github.io/orleans/Documentation/Getting-Started-With-Orleans/Observers.html?q=Observer fairly thoroughly, and have something like this:

```
public interface IMyObserver : IGrainObserver {
   void WorkComplete(object result);
}

public interface IMyGrain : IGrain {
   Task Subscribe(IMyObserver observer);
   Task Start();
}

public class MyGrain : Grain, IMyGrain {
   private ObserverSubscriptionManager<IMyObserver> _observers;
   public override async Task OnActivateAsync(){...}
   public async Task Subscribe(IMyObserver observer){...}

   public async Task Start() {
      // intentionally not awaited
      // Start just kicks off the work in a fire-and-forget fashion
      this.DoWorkAndPublish();
   }

   private async void DoWorkAndPublish() {
      var result = await Task.Run(() => /* some external code that can take a long time */);
      this._observers.Notify(s => s.WorkComplete(result));
   }
}
```

As far as I understand, the Task.Run will use the default task scheduler (not the orleans one), but the await will return on the orleans scheduler thread.  

**My question is**, is the above pattern _safe_?  In the External Tasks and Grains documentation, there is an example for "Making a grain call from code that runs on a thread pool".  I don't think I need to do that, because I am returning to the Orleans thread / scheduler with the await.  I am mostly concerned about whether or not the pattern I implemented preserves single threaded execution within the grain, or not.

Side note - in my actual implementation, there is a reminder which prevents the grain from going idle / handles restarting the work if the grain was reactivated for some reason / etc.

**Comment by sergeybykov** [comment]
`async void` is a dangerous construct that in general shouldn't be used outside of synchronous methods like `Main` and synchronous event handlers. It is considered dangerous primarily because it loses exceptions thrown from inside it. A safer alternative I think is to make `DoWorkAndPublish` return a `Task`, and then explicitly call `.Ignore` on it in `Start`.

**Comment by mtdaniels** [comment]
@sergeybykov - good point. But, does the Orleans scheduler guarantee single threaded execution when it returns from the await in DoWorkAndPublish?

**Comment by sergeybykov** [comment]
It should.

**Comment by mtdaniels** [comment]
Excellent.  Thanks for your help!

Side note - one thing that must be handled in this case is grain deactivation while the background task is executing.  One cause of this, is if the silo hosting the directory partition which addresses the grain dies.  I believe the grain deactivates itself because it has been orphaned.  Any number of ways to handle that (the simplest of which is to just cancel the task).  Just thought I'd mention it in case someone else stumbles upon this.

**Comment by sergeybykov** [comment]
@mtdaniels Yes, that's one more reason to be very careful with not awaiting Tasks and avoid that if possible.
