### ISSUE TITLE
Cross-platform Build

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#2461]
As part of #2145, we should port the build script from a .cmd batch file to a cross-platform one.

Since Powershell now run anywhere .Net Core run, we can easily port the batch scripts to powershell since there is no platform specific code on those batches.

The new script should check if running on Windows so it can build the libraries that target the full framework along with dotnet standard ones. If running on linux, only the dotnet core assemblies should be built.

**Comment by ReubenBond** [comment]
I wonder if we could have a pure MSBuild build pipeline - or does even the thought of such a thing send shudders?

**Comment by galvesribeiro** [comment]
@ReubenBond yes, we can have a pure MSBuild and that would be the ideal. The idea on have a powershell script is to deal with any directory manipulation we need and to invoke the test as well... If we could have everything on MSBuild without script would be the ideal, but I'm not sure if it is possible, at least for now with current tooling...

**Comment by galvesribeiro** [comment]
As agreed with core team, I'm closing this issue for now. The xplat build will be revisited later on.
