### ISSUE TITLE
Support multiple Orleans cluster in same database

### ISSUE THREAD

**Issue by dandago** [dotnet/orleans#2472]
It would be nice if we could reuse the same physical database for different Orleans clusters.

This could be done by prefixing table names, schema, or any other approach that makes sense. (Assuming actually using the same tables is not an option.)

**Comment by veikkoeeva** [comment]
You can alter the queries in `QueryTable` so as to prefix the table names with the schema name of your choice and run the script to the same schema. I would even encourage you to do that and lock down the schema appropriately. It's basically what keeps your system running and you should make sure either inadvert or malicious modifications aren't possible. One thing also is [filegroups](http://thomaslarock.com/2013/01/database-filegroups-just-like-seatbelts-but-with-less-chafing/), especially if you use the storage. You should consider putting it to a filegroup of its own, maybe a schema of its own, and modify the queries appropriately.

This modification of the queries and tables to fit your particular needs is, by the way, one of the scenarios envisioned would need to be supported.

I remember it wrong yesterday, `ServiceId` is used only in reminder and storage queries. If you search for it at https://github.com/dotnet/orleans/blob/master/src/OrleansSQLUtils/CreateOrleansTables_SqlServer.sql, you can see it in the queries in the `WHERE` clauses. I don't think there should be a trouble, as far as ADO.NET storage is concerned, in that check to all membership queries too. It would require:
1. Orleans transmits the parameter when it does query. It needs to be added to the code as a new parameter.
2. The queries stored in `OrleansQuery` table need to be amended to use it.

This shouldn't cause trouble in the old systems if they update the queries, as they're picked up when the silos restart and the old scripts continue functioning. This is needed if you run multiple services and want to concentrate all of them under the same schema.

**Comment by mtdaniels** [comment]
So long as you use a different DeploymentId, what is the downside to hosting multiple clusters in the same schema / tables?

**Comment by ReubenBond** [comment]
By now, people regularly deploy multiple Orleans instances against the same backing databases by distinguishing deployments/services using ClusterId/ServiceId. If there is work to be done on specific storage/reminder/clustering/etc providers, we can open individual issues for those
