### ISSUE TITLE
Internal representation of type arguments within generic grain references is verbose

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#2483]
While non-generic grains have compact grain references in the form `MyNamespace.MyGrain`, generic grains have pretty verbose references like ``MyNamespace.MyGrain`1[[MyNamespace.MyGenericType, MyAssembly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]``

Is there a good reason why it can't be `MyNamespace.MyGrain[MyNamespace.MyGenericType]` or `MyNamespace.MyGrain<MyNamespace.MyGenericType>` ?

**Comment by sergeybykov** [comment]
>While non-generic grains have compact grain references in the form MyNamespace.MyGrain

Non-generic shouldn't have data like that in them because the type is encoded in the type code. Where are you seeing this?

In the generic case, `genericArguments` contains the type arguments. Maybe they can be expressed in a more compact way. But is that a real issue?

**Comment by DixonDs** [comment]
Yes, sorry, it seems I confused something here with grain references. I had issues with generic grains in two places:

1. Dashboard. It is partially related to https://github.com/OrleansContrib/OrleansDashboard/issues/22
2. RowKey in Table Storage. I had issues in past with RowKey being too long to store because of a grain with one or two generic parameters. Looking at `IStorageProvider`, `grainType` comes as string already, I guess in the form I mentioned.

So not really grain references, but rather grain type string representations used internally.

**Comment by veikkoeeva** [comment]
I'll cross-reference, since relevant: https://github.com/dotnet/orleans/issues/1998.
