### ISSUE TITLE
Getting exception when instantiating TestCluster object using TestCluster(ClusterConfiguration clusterConfiguration, ClientConfiguration clientConfiguration) constructor  

### ISSUE THREAD

**Issue by dyereve** [dotnet/orleans#2489]
Hello everyone,
I'm trying to use TestCluster inside my integration testing class. I'm doing something like the following:
```
ClusterConfiguration clusterConfig;
var serverConfigFile = (AppDomain.CurrentDomain.BaseDirectory +"\\DevTestServerConfiguration.xml");
            using (TextReader sr = new StringReader(File.OpenText(serverConfigFile).ReadToEnd()))
            {
                clusterConfig = new ClusterConfiguration(sr);
            }
ClientConfiguration clientConfig;
 var clientConfigFile = (AppDomain.CurrentDomain.BaseDirectory +"\\DevTestClientConfiguration.xml");
            using (TextReader sr = new StringReader(File.OpenText(clientConfigFile).ReadToEnd()))
            {
                clientConfig = new ClientConfiguration();
                clientConfig.Load(sr);
            }
			this.HostedCluster = new TestCluster();
  #region SetManuallyProviderConfiguration
            foreach (var item in clusterConfig.Globals.ProviderConfigurations)
            {
                this.HostedCluster.ClusterConfiguration.Globals.ProviderConfigurations.Add(item);
            }

            foreach (var item in clientConfig.ProviderConfigurations)
            {
                this.HostedCluster.ClientConfiguration.ProviderConfigurations.Add(item);
            }
			#endregion  
            if (this.HostedCluster.Primary == null)
            {
                    HostedCluster.Deploy();
            }
```
... the above code working as a charm but when i try to instantiate TestCluster object passing ClusterConfiguration and ClientConfiguration directly to the constructor (replacing  #region ManuallySetProviderConfigurations snippet with the following) :

```this.HostedCluster = new TestCluster(clusterConfig, clientConfig);```
 
...i'm getting the following exception when it tries to execute HostedCluster.Deploy():

> Message = "The target silo became unavailable for message: Request *cli/9f78b28f@3ca3eb98->S127.0.0.1:40000:0TypeManagerId@S00000011 #2: global::Orleans.Runtime.ITypeManager:GetTypeCodeMap(). Target History is: <S127.0.0.1:40000:0:TypeManagerId:@S00000011>. See https...

Any ideas why is that happening?

**Comment by xiazen** [comment]
In the working scenario, you only feed `ProviderConfigurations` to your `HostedCluster`. In this case, HostedCluster will use default value for other configuration. 

While in the non-working scenario, you feed all the config in your DevTestServerConfiguration.xml and DevTestClientConfiguration.xml to your `HosterCluster`.  And it stopped working. I suspect there's incorrect config value in  your xml config files. Mind share them so we can see what's going on? 

Sorry for the late response. Hopefully you already find the answer.

**Comment by sergeybykov** [comment]
@dyereve, have you solved the problem already?

**Comment by dyereve** [comment]
Hello,
I'm on vacations currently an i m expected to return to my duties in a couple of days. I receive the email from one of your team members but I didn't make any progress on that for the same reason.I' ll give you my feedback in the next few days.
Cheers!
Achilles

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Jan 3, 2017 at 3:53 PM +0000, "Sergey Bykov" <notifications@github.com<mailto:notifications@github.com>> wrote:


@dyereve<https://github.com/dyereve>, have you solved the problem already?

**Comment by dyereve** [comment]
Hello,
I attached the configuration files as you asked me. Unfortunately i didn't find a solution on how to use the TestCluster object passing clusterConfig and clientConfig directly on constructor.

[DevTestClientConfiguration.txt](https://github.com/dotnet/orleans/files/687362/DevTestClientConfiguration.txt)
[DevTestServerConfiguration.txt](https://github.com/dotnet/orleans/files/687361/DevTestServerConfiguration.txt)

Thank you!

**Comment by xiazen** [comment]
You need to add Override config to your cluster config, such as
  ```
<Override Node="Primary">
    <Networking Port="22222" />
  </Override>
```

When `TestCluster` deploy, it deploys a list of silo names from its `ClusterConfiguration.Overrides.Keys`. 
See TestCluster.cs ->        
```
        public void Deploy()
        {
            this.Deploy(this.ClusterConfiguration.Overrides.Keys);
        }
```

**Comment by xiazen** [comment]
I tested your config with code snippet : 

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Orleans;
using Orleans.Runtime.Configuration;
using Orleans.TestingHost;
using Tester;
using TestExtensions;
using UnitTests.GrainInterfaces;
using UnitTests.Grains;
using Xunit;

namespace UnitTests
{
    public class TestClusterTests : TestClusterPerTest
    {
        public override TestCluster CreateTestCluster()
        {

            ClusterConfiguration clusterConfig;
            var serverConfigFile = "DevTestServerConfiguration.xml";
            using (TextReader sr = new StringReader(File.OpenText(serverConfigFile).ReadToEnd()))
            {
                clusterConfig = new ClusterConfiguration(sr);
            }
            ClientConfiguration clientConfig;
            var clientConfigFile = "DevTestClientConfiguration.xml";
            using (TextReader sr = new StringReader(File.OpenText(clientConfigFile).ReadToEnd()))
            {
                clientConfig = new ClientConfiguration();
                clientConfig.Load(sr);
            }

          return new TestCluster(clusterConfig, clientConfig);
        }

        [Fact, TestCategory("Functional"), TestCategory("TestCluster")]
        public async Task TestClusterTests1()
        {
            Assert.NotNull(this.HostedCluster.Primary);
            ISimpleGrain grain = GrainClient.GrainFactory.GetGrain<ISimpleGrain>(random.Next(), SimpleGrain.SimpleGrainNamePrefix);
            await grain.SetA(1);
            Assert.Equal(await grain.GetA(), 1);
        }
    }
}

```

it worked. 
Let me know if you have further issues

**Comment by xiazen** [comment]
@dyereve does the fix work for you?

**Comment by xiazen** [comment]
closing this issue, feel free to reopen it if you still have other problems
