### ISSUE TITLE
Trying to deploy Orleans project - Local and on Azure throws runtime error-Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironmentException: error

### ISSUE THREAD

**Issue by stephenosr** [dotnet/orleans#2491]
Am using the Azure emulator and the Orleans host runs fine. 
This piece of code below in my MVC - global.asax.cs is throwing an error at AzureClient.DefaultConfiguration()...

I tried deploying into Azure too, got the same error.
Has anyone faced this issue and been able to solve it? Don't know what I am missing.
----------------------------------------------------------------------------------

if (RoleEnvironment.IsAvailable)
{
      //azure
      var config = AzureClient.DefaultConfiguration();
      AzureClient.Initialize(config);
      //AzureClient.Initialize();
 }
 else
 {
      //Local deployment
       GrainClient.Initialize(
             Server.MapPath(
             @"~/OrleansClientConfiguration.xml"));
  }

ERROR:
		
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironmentException: error

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[RoleEnvironmentException: error]
   Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.GetConfigurationSettingValue(String configurationSettingName) +341

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   AzureWebAppTestRole.MvcApplication.Application_Start() in F:\Projects\Azure\TestDeplyProjects\BST\BST_Test3\AzureTestWebApp\AzureTestWebApp\AzureWebAppTestRole\Global.asax.cs:67

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +588
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +181
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +322
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +402
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +452

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +646
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +159
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +778

**Comment by attilah** [comment]
@stephenosr can you share the project or global.asax file for starters.

From the stacktrace it seems that it has nothing to do with Orleans itself, it can be a configuration problem.

From the stacktrace what I see is that ```GetConfigurationSettingsValue``` call fails. The only setting what we're reading is ```DataConnectionString``` make sure that you've it configured in Local and Cloud configs too.

One thing you can try is to debug it locally and enable First Chance Exceptions, that way we probably can see what setting cannot by read.

Please check and get to us with the results.

**Comment by stephenosr** [comment]
@attilah i've been a little tied down and therefore haven't uploaded the project, will do so in the next couple of days, First Change Exception wasn't very helpful...will upload that too. Thanks much.

**Comment by attilah** [comment]
@stephenosr did you have a chance look into this?

**Comment by attilah** [comment]
Closing, since the problem seems to be outside of Orleans.

**Comment by kogir** [comment]
If I had to guess, @stephenosr was trying to use `AzureClient.DefaultConfiguration` outside of Azure Cloud Services. I had to roll my own similar helper for my app on Azure App Services, which has no RoleEnvironment.

Ideally, Orleans would update to use [CloudConfigurationManager](https://msdn.microsoft.com/en-us/library/azure/mt634650.aspx) which works on local IIS, App Services, and Cloud Services.

**Comment by attilah** [comment]
Reopening for investigation about using ```CloudConfigurationManager``` class.

**Comment by attilah** [comment]
AzureClient and AzureSilo designed to work in Azure Worker Role and Azure Web Role scenarios only, their purpose is to simplify the initial burden of deploying Orleans. Therefore there are some requirements to this like the presence of the ```DataConnectionString``` configuration value which is used in subsequent operations, so we're depending on it.

After discussing with the team we decided to not to change this existing behavior, and since the original issue was about this I'm closing the issue and the PR (without merging it) too.

**Comment by sergeybykov** [comment]
`AzureClient` and `AzureSilo` are simple wrappers around `GrainClient` and `SiloHost`. There is no need to complicate then when the underlying classes can be used as easily with a couple of explicit config steps.
