### ISSUE TITLE
Configurable option in Table Storage Provider to ignore ETag

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#2493]
We occasionally get write conflicts when using Table Storage provider. While the source of errors is still to be found out (one theory is that the previous write could time out, and while the client didn't receive updated ETag, it was in fact updated in storage), it would be useful and acceptable in some particular cases to allow rewriting the persisted stage regardless of what that stage is. 

I see it as adding one more option to Table Storage provider configuration and invoke `AzureTableDataManager.UpsertTableEntryAsync(T data)` instead of `AzureTableDataManager.UpdateTableEntryAsync(T data, string dataEtag)`. If it acceptable, I can provide a PR for that.

**Comment by sergeybykov** [comment]
I'm concerned this would be a very dangerous option, and people may unknowingly run with it for a long time not realizing they are losing data in a small percentage of cases. A safer way to get the same result I think is to read latest state with `ReadStateAsync`, reapply the update, and retry `WriteStateAsync`. There may be a place for an extension or helper method that would automate this.

**Comment by DixonDs** [comment]
> A safer way to get the same result I think is to read latest state with ReadStateAsync, reapply the update, and retry WriteStateAsync.

That's what we do now, but it is basically has the same effect as update with ETag to be ignored just that in the later case there is clear performance benefit. I think if the new configuration option will be defaulted to the current, safer behavior, people will get issues only if they change it explicitly and thus they should understand the outcome of that decision.

**Comment by jason-bragg** [comment]
My concern about this is the global nature of a configuration switch, especially if it is applied to a storage provider that is configured as the default storage provider 

The need to ignore etags, to me seems very grain specific, and since most systems written on top of Orleans grain storage have not been written with this expectation, it would be dangerous to configure a provider to act in this way unless one was confident that all grains using it expect the same behavior. 

I think what we'd want is a way to specify that a specific type of grain wanted to ignore etags.  Maybe a different storage provider attribute on the grain?

**Comment by DixonDs** [comment]
@jason-bragg Yes, ideally only some grains should be using this behavior. But it can be easily done by making two configurations of Table Storage provider (one with ETag ignored and the other one with normal behavior) by different names, and use the desired provider for specific grains just by using `StorageProviderAttribute` with corresponding provider name. Adding a new parameter to `StorageProviderAttribute` has downside has it changes a common attribute with implementation-specific details.

**Comment by jason-bragg** [comment]
I'm not convinced changes to the attribute would be implementation specific.  It may be, I'm just not yet convinced.  The etag is part of the IStorageProvider interface, but we don't have a strong contract for it's meaning.

Currently the grain nor storage bridge do anything with the etag, so it's entirely the domain of the provider implementation.  Adding some sort of 'overwrite' setting to the attribute could be detected by the bridge and used to set the etag to "*" or some other token that indicates a forced write.  It would then be up to the provider developers to recognize this token and act accordingly if they wish to support the override behavior, or throw if they do not.

I'm not confident in this approach..  Just exploring the idea..

As far as the storage provider wide setting, I understand your argument.  It is perfectly possible to get the behavior one desires with the setting.  My argument was never about possibility, it was about usability and likeliness for one to introduce unexpected behaviors.  Given a provider wide flag, I can easily envision a scenario where a developer of a grain determines that they need forced write capability for their grain, and changes a providers configuration without considering (or even knowing) what other grains may be using that provider.  This is, in my view, at least as harmful a compromise as adding an overwrite option to the attribute that may not be respected by all providers.

**Comment by DixonDs** [comment]
@jason-bragg I feel that I need to stress that I am not really opposing to changes to storage provider attribute. I am fine with any option that will allow me to use writes with ETag="*" without need to do current write/fail/read/update/write again approach :)

**Comment by jason-bragg** [comment]
Iterating internally, there are others that are concerned about the attribute approach, but we've not settled on any better solutions.  Given the lack of solutions we'd feel comfortable enough integrating in Orleans two paths come to mind.
1) We could continue to iterate on this until we find a viable solution.
2) One could write a simple storage decorator that modified the etag to "*" in the WriteStateAsync call prior to passing the call though to the decorated provider.

something like:
    public class ForceWriteStorageProvider<T> : IStorageProvider
        where T : IStorageProvider, new()
    {
        private readonly IStorageProvider provider;

        public string Name => this.provider.Name;
        public Logger Log => this.provider.Log;

        public ForceWriteStorageProvider()
        {
            provider = new T();
        }

        public Task Init(string name, IProviderRuntime providerRuntime, IProviderConfiguration config)
        {
            return this.provider.Init(name, providerRuntime, config);
        }

        public Task Close()
        {
            return this.provider.Close();
        }

        public Task ReadStateAsync(string grainType, GrainReference grainReference, IGrainState grainState)
        {
            return this.provider.ReadStateAsync(grainType, grainReference, grainState);
        }

        public Task WriteStateAsync(string grainType, GrainReference grainReference, IGrainState grainState)
        {
            grainState.ETag = "*";
            return this.provider.WriteStateAsync(grainType, grainReference, grainState);
        }

        public Task ClearStateAsync(string grainType, GrainReference grainReference, IGrainState grainState)
        {
            return this.provider.ClearStateAsync(grainType, grainReference, grainState);
        }
    }

    public class ForceForceWriteAzureTableStorage : ForceWriteStorageProvider<AzureTableStorage>
    {
    }

**Comment by jason-bragg** [comment]
Since AzureTableStorage is not sealed, this would probably work:

    public class ForceWriteAzureTableStorage : AzureTableStorage, IStorageProvider
    {
        Task IStorageProvider.WriteStateAsync(string grainType, GrainReference grainReference, IGrainState grainState)
        {
            grainState.ETag = "*";
            return base.WriteStateAsync(grainType, grainReference, grainState);
        }
    }

**Comment by DixonDs** [comment]
@jason-bragg @sergeybykov Just to confirm. Closing this issue means that the preferred approach stays to use `ForceWriteAzureTableStorage` from the previous post, right? Maybe in this case it is worth to include it in codebase so that it is discoverable by others who might need it

**Comment by jason-bragg** [comment]
@DixonDs, I assume Sergey closed the issue because he was of the impression that you had a solution you were happy with, though his mind is a magical thing so I can never be sure. :)

As for pulling this solution into Orleans, I am of the opinion that the solution we came up with is not a good general solution, for reasons previously mentioned in this thread.

>The need to ignore etags, to me, seems very grain specific, and since most systems written on top of Orleans grain storage have not been written with this expectation, it would be dangerous to configure a provider to act in this way unless one was confident that all grains using it expect the same behavior.

It is expected that users will implement their own storage providers to handle their specific scenarios, and given the lack of agreement on what a good general solution would look like, keeping this as a user specific scenario would be my preference.

If you'd care to continue discussing a general solution we could incorporate into Orleans, please feel free to reopen the thread, and we can continue the discussion.
