### ISSUE TITLE
Consider renaming dlls \ exes \ namespaces

### ISSUE THREAD

**Issue by jkonecki** [dotnet/orleans#25]
Not as simple as changing NuGet package names but I think this should be discussed before wider adoption. Those are breaking changes and it's better to bite the bullet now. 

I would like to suggest we change Orleans dlls \ exes to **Microsoft.Orleans.xxx.** and change the namespaces accordingly.

What are your thoughts?

**Comment by jesuspsalas** [comment]
+1 to bite the bullet as soon as possible on this!

**Comment by sergeybykov** [comment]
I'm not sure about this one. It would be much more disruptive for all the people that already reference the binaries, internally and externally. NuGet packages don't have that problem, as we never published them.

**Comment by jkonecki** [comment]
Sergey, I do understand the knock-on effect. I would just like to avoid the pain that Azure Storage Client or EntityFramework caused with namespace / dll changes once the usage was much wider...

Again, it's just a suggestion to consider as it will be more and more difficult to implement as the time goes.

**Comment by overeemm** [comment]
I would encourage the rename! We already reference the dll's from the SDK. Changing everything to nuget is already work, so I do not mind the rename of namespaces and DLL's.

**Comment by richorama** [comment]
My two pence - in a cost/benefit analysis, I'm not sure I see much benefit, but there is potentially quite a bit of cost.

Theoretical question; how permanent is the name 'Orleans'? Will Orleans be renamed to 'Microsoft Virtual Actor Model for .NET' at some point?

**Comment by sergeybykov** [comment]
It doesn't look likely that 'Orleans' will get renamed to something like 'Microsoft Virtual Actor Model for .NET'.

**Comment by akoeplinger** [comment]
I'd say I'm in favor of the rename, if only to make it consistent with all the other "next-gen" MS frameworks like ASP.NET5 (`Microsoft.AspNet.*`), Roslyn (`Microsoft.CodeAnalysis.*`) etc.

**Comment by MovGP0** [comment]
the demon Legion would be a fitting name too. ("My name is Legion: for we are many") 

ym2c

**Comment by sergeybykov** [comment]
We'll stick with the current name.
