### ISSUE TITLE
Profiling length of SMS Provider stream length/contents

### ISSUE THREAD

**Issue by geoffperry** [dotnet/orleans#2503]
We are using an SMS provider, is there a way to monitoring the length of the stream? Performance counters or a property that can be reference periodically?

We are using FireAndForgetDelivery = true and are happy after awaiting adding to the stream that it moves onto adding the next item in the stream, however we loose visibility at this point and would like to monitor if the messages in the streams could be backing up, ie if the further logic is taking longer to process.

Thanks

**Comment by jason-bragg** [comment]
We don't have anything built-in for this.

Some consumers have encoded timestamps and/or ordering information to detect delivery delays or data loss.

Recently we've added another ephemeral stream provider (Like SMS) called the MemoryStreamProvider which has a little more support for recoverability  and ordering protections.  It passes an EventSequenceToken to the consumer that has a sequence number in it.
