### ISSUE TITLE
Nuget package dependencies

### ISSUE THREAD

**Issue by yevhen** [dotnet/orleans#251]
Orleans.Core package does not specify dependency on `Windows.Azure.Storage` and `Windows.Azure.Configuration`. Just referencing Core and Runtime is not enough to start the silo. It fails with: 

```
Could not load file or assembly 'Microsoft.WindowsAzure.Storage, Version=4.2.0.0 ...
```

Similar situation with `OrleansAzureUtils`. The `Azure.OrleansProviders` package need to imported in order to successfully run in Azure environment. Please specify this dependency for `AzureUtils` package

**Comment by yevhen** [comment]
Also, please unlist obsolete Orleans packages in the Nuget gallery.

**Comment by sergeybykov** [comment]
You are now supposed to reference Microsoft.Orleans.Server for a silo and Microsoft.Orleans.Client for a client (frontend). Microsoft.Orleans.Core doesn't have any dependencies anymore, so that it doesn't pull them into grain interface and grain implementation projects (via Microsoft.Orleans.Templates.*) that aren't needed there and only polluted such projects with all of their dependencies. 

 I'm going to write a doc page describing the NuGet layout. Do you see any gap here?

**Comment by yevhen** [comment]
OMG. Ok.

**Comment by yevhen** [comment]
> I'm going to write a doc page describing the NuGet layout. Do you see any gap here?
Yes. The fact that Orleans.Core doesn't list any dependencies is misleading.

I understand that this creates problems when referencing from interface project, but it also highlights the fact that current dependency graph in Orleans need to be revisited. Perhaps, more time need to be invested into #136.

**Comment by yevhen** [comment]
> You are now supposed to reference Microsoft.Orleans.Server

Ye, and this has references to AzureUtils and rest of Azure stuff. Really, confuses people who wants to run Orleans on-premises.

Are you trying to push people to use Orleans only in conjunction with Azure? What's the deal here?

**Comment by sergeybykov** [comment]
> Perhaps, more time need to be invested into #136.

Agreed.

> Are you trying to push people to use Orleans only in conjunction with Azure? What's the deal here?

No, we are not trying to push anybody anywhere. Historically, Azure for us has been a priority. The majority of Orleans customers use it in Azure. So I think it makes sense to keep that path smooth and easy, and not complicate it suddenly for the majority.

What's been a bit confusing though is that we found using Azure Storage for membership also the easiest option for running Orleans deployments on premises. Much simpler and more reliable than setting up a SQL Server or writing a custom membership provider. We need to do a better job of explaining the deployment options and make the dependencies better structured and more obvious.

**Comment by veikkoeeva** [comment]
> What's been a bit confusing though is that we found using Azure Storage for membership also the easiest option for running Orleans deployments on premises. Much simpler and more reliable than setting up a SQL Server or writing a custom membership provider. We need to do a better job of explaining the deployment options and make the dependencies better structured and more obvious.

If possible, could someone elaborate informally somewhere about  SQL Server/relational database observations? With taking a quick glance on ``CreateTables.sql`` it looks like there's some repetition on tables (e.g. ``OrleansSiloMetricsTable``) and perhaps normalizing a bit more I/O load could be reduced, it looks like also indexing could be improved and so on. On-premises are more likely to use relational databases, hence my interest.

**Comment by sergeybykov** [comment]
I added a documentation page for NuGets - http://dotnet.github.io/orleans/NuGets.
