### ISSUE TITLE
Requests Timing out Without Debugger Attached

### ISSUE THREAD

**Issue by MikeHardman** [dotnet/orleans#2516]
We're working with 1.3.1, we have a solution that is only functioning correctly when a debugger is attached to the client project. When a debugger isn't attached we are able to get a Grain reference from the client, but calls to the grain time out.

I've attached a small sample project -> [OrleansTest.zip](https://github.com/dotnet/orleans/files/652279/OrleansTest.zip) that demonstrates the issue, when we run with the debugger we get an answer from the grain, when we don't have a debugger it times out.

**Comment by MikeHardman** [comment]
I should note that we're using a SqlServer system store which is a SqlExpress instance running in AWS. We only have a single Silo running and obviously it works correctly with the debugger attached.

We have also tried to wrap the call to GetTestString as follows -> Task.Run(async () => { Console.WriteLine(await grain.GetTestString()}); and get identical results, it works with a debugger, but times out when run without a debugger attached.

**Comment by MikeHardman** [comment]
Further detail on this, I cannot reproduce this when I run the silo and client on the same machine, silo and client must be on different hosts to reproduce this behavior.

**Comment by benjaminpetit** [comment]
I am not sure to understand why whith a debugger it could works, but in the config you provide to the silo:

``` xml
  <Defaults>
    <Networking Address="127.0.0.1" Port="11111"/>
    <ProxyingGateway Address="127.0.0.1" Port="30000"/>
  </Defaults>
```

Replaccing that with:
``` xml
  <Defaults>
    <Networking Address="" Port="11111"/>
    <ProxyingGateway Address="" Port="30000"/>
  </Defaults>
```

seems to work, with or without debugger :)

**Comment by MikeHardman** [comment]
Now I'm more confused about why this works with the debugger attached....

**Comment by awsxdr** [comment]
Hi Benjamin. I'm the dev working on this with Mike and have tried out your suggestion this morning. Unfortunately it doesn't appear to have fixed the issue.

The configuration file which was running on the server had the correct IP address for that server. I have now removed the IP altogether but it's still working with a debugger attached but failing when not attached.

I've tried isolating the issue and I've got down to discovering that the debugger needs to be attached by the time GrainClient.Initialize is called. I'm going to see if I can dig into this method to find out exactly when it needs the debugger attached by within Orleans.

In addition to what Mike said about silo and client having to be on different hosts, we've found that if we run it between two hosts on our local network then it works but if we put the silo in an AWS host then it stops working. I don't know whether this is to do with latency or is something to do with AWS itself.

Dan

**Comment by awsxdr** [comment]
OK so I've done a bit more investigation into this now. I was wrong above, it wasn't the GrainClient.Initialize method the debugger had to be attached for, it was the loading of the configuration file.

I've moved over to using programmatic configuration as I believe that's where things are going anyway and after digging through the verbose output I've found that there's a bit of code in Orleans which detects the debugger and sets the ResponseTimeout property to 30 _minutes_ instead of 30 _seconds_. If I explicitly set the timeout to 30 minutes then the code works even without the debugger attached.

So we have a workaround for now but it still seems important to figure out why on earth this change would make a difference. The program certainly isn't taking anywhere near 30 seconds to startup and connect (I'm currently timing it at about 4 seconds) so why this timeout needs to be so high is a mystery to me.

**Comment by benjaminpetit** [comment]
You are correct, when a debugger is attached, the `Configuration.ResponseTimeout` value is ignored and we use `TimeSpan.FromMinutes(30)` instead.

Are you 100% sure that the call that timeout is the grain call, not the client initialization, right?

As you said, I cannot reproduce the issue on a local network. I don't have access to AWS but I will try to reproduce it with two host on different network.

**Comment by benjaminpetit** [comment]
One possible explanation could be that there is a big clock skew between your client and your silo (more than 31 sec but less than 30min). 

When your client send a message to a silo, the expiration field is set like this:
```` csharp
message.Expiration = DateTime.UtcNow + responseTimeout + Constants.MAXIMUM_CLOCK_SKEW;
````

The silo will check this field value and will directly drop the received message if it is expired. Could you check your silo logs if you see something like "Dropping an expired message"

**Comment by MikeHardman** [comment]
There was a 2 minute clock skew between my desktop and the server hosting the silo, I've brought this network in line with our NTP configuration in other parts of our system. This is looking like the likely cause and it fits with our results when we change the timeout in code. We'll confirm and close this on Monday. Thanks again!

**Comment by ReubenBond** [comment]
Clock skew detection or clock synchonization could be useful - is it overkill? It would be preferable to add it in a manner which is not contingent on the membership provider.

I'm sure the team have considered it before

**Comment by sergeybykov** [comment]
There are already similar issues #1524 and #1525. Maybe we need another one specifically for client-gateway clock skews.

We could detect such skews upon client connection, and reject the client if its clock is beyond a tolerance threshold, e.g. 5 seconds.

We could also have gateway check timestamps on incoming client messages, and reject those that exceed the tolerance threshold, assuming there shouldn't be a significant latency on client's sending side. Of course, GC is an elephant in the room here. If a silo or a client get frozen for several seconds, such time sensitive assumptions may lead to more instability. Although one can argue that 'fail fast' would be better when app over-allocates or leaks objects.
