### ISSUE TITLE
XML Configuration Requires a Reminder Assembly when specifying a custom membership table

### ISSUE THREAD

**Issue by brianqcgames** [dotnet/orleans#2527]
When SystemStoreType is set to "Custom" it sets both the LivenessType and the ReminderServiceType to custom. This in turn requires an assembly be specified for both the membership table and the reminder service.

I would expect that the LivenessType (and Membership) table could be specified without requiring a custom reminder service.

The exception is thrown on the following line...
if (ReminderServiceType == ReminderServiceProviderType.Custom && String.IsNullOrEmpty(ReminderTableAssembly))
                            throw new FormatException("ReminderTableAssembly should be set when ReminderServiceType is \"Custom\"");

**Comment by brianqcgames** [comment]
Tagging @galvesribeiro

**Comment by galvesribeiro** [comment]
AFAIK this `if` is not valid, at least not now. If we set the `SystemStore` to `Custom` using codeconfig and right after it we set the reminder service to disabled, this exception will not be thrown. 

We should fix it.

**Comment by sergeybykov** [comment]
Resolved via #2589.
