### ISSUE TITLE
[Question] Streams over BinaryTokenStreamReader 

### ISSUE THREAD

**Issue by idudinovr8** [dotnet/orleans#2539]
Hi,

I'm wondering how I can use Streams instead or over the BinaryTokenStreamReader. 
The motivation of such approach is based on conclusion that allocating the whole String or Byte[] for an DTO being serialized/deserialized is considered to be pretty expensive. 

All examples of using `BinaryTokenStreamReader` I've found suggest to either write/read a json String which will be passed to json serializer and back, or use binary data and add to (or read from) the start of the bytes sequence total length of it. Both approaches need to be whole data to be allocated at the moment, which I'd like to avoid.

So my attempt was to write trivial Stream wrapper over the `BinaryTokenStreamReader`, soon I've got something like this:

```csharp
private class BinaryTokenStream : Stream
{
    private readonly BinaryTokenStreamReader _reader;
    private readonly BinaryTokenStreamWriter _writer;
            
    public override bool CanRead { get { return _reader != null; } }
    public override bool CanSeek { get { return false; } }
    public override bool CanWrite { get { return _writer != null; } }
    public override long Length { get { throw new NotSupportedException(); } }
    public override long Position
    {
        get { return _reader?.CurrentPosition ?? 0; }
        set { throw new NotSupportedException(); }
    }

    public BinaryTokenStream(BinaryTokenStreamReader reader)
    {
        _reader = reader;
    }

    public BinaryTokenStream(BinaryTokenStreamWriter writer)
    {
        _writer = writer;
    }

    public override void Flush()
    { }

    public override long Seek(long offset, SeekOrigin origin)
    {
        throw new NotSupportedException();
    }

    public override void SetLength(long value)
    {
        throw new NotSupportedException();
    }

    public override int Read(byte[] buffer, int offset, int count)
    {
        if (!CanRead)
            throw new InvalidOperationException();

        _reader.ReadByteArray(buffer, offset, count);
        return count;
    }

    public override void Write(byte[] buffer, int offset, int count)
    {
        if (!CanWrite)
            throw new InvalidOperationException();

        _writer.Write(buffer, offset, count);
    }
}
```
 
But unfortunately `BinaryTokenStreamReader` will not allow to request bytes from it more that it has left. And  the worse thing is that I cannot get reader's total length based on which I could clamp `count` when calling `_reader.ReadByteArray(buffer, offset, count);`. Sources do have such property like totalLength, but I'm not sure am I legal to count on it.

So in general I'm not sure have I chosen efficient way to solve my problem, and had no chance to find any other way to override serializing and deserializing except using those reader & writer.

Any suggestions regarding this?
Thanks

**Comment by jason-bragg** [comment]
@idudinovr8 

> So in general I'm not sure have I chosen efficient way to solve my problem, and had no chance to find any other way to override serializing and deserializing except using those reader & writer.

The BinaryTokenStreams are part of our serialization system and they use pooled buffers to mitigate the buffer allocation costs associated with serialization that you mentioned in your opening remarks.  With this in mind, I'm unclear what your intentions are here.  What are you serializing/deserializing that necessitates the need for the above stream implementation?

**Comment by idudinovr8** [comment]
@jason-bragg 
Thanks for the reply.
I'll try to describe situation I have from the beginning. 
I have custom serialization/deserialization code that works on top of Streams. Using Streams looks like the most universal and efficient approach for it. To avoid GC spikes or falling objects to Large Objects Heap I would like never serialize or deserialize data via solid-allocated strings or byte arrays. So my intention was just to find a way in which I can handle serialization via streaming. Does it make sense? I was wondering if I miss something or should I look for another approach?

**Comment by jason-bragg** [comment]
As some terms are overloaded, I'll restate my understanding of your request, which may be in error.  Can you please confirm my understanding.

You are using Orleans streams (http://dotnet.github.io/orleans/Documentation/Orleans-Streams/index.html).
While using Orleans streams, instead of sending full objects over the stream, you are serializing the data yourself, using dotnet streams (System.IO,Stream).
To reduce allocation costs you want to use BinaryTokenStream, and are attempting to do this by creating an implementation of System.IO.Stream that uses BinaryTokenStream.

Is that correct?

**Comment by idudinovr8** [comment]
@jason-bragg

Thanks for trying to understand me :)

I'm not using Orleans Streams, I'm just trying to override serialization/deserialization for types used in messaging between Grains. I'm using my own implementation of Orleans' IExternalSerializer for this, but its worker methods have the same signature as for general approaches described here http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Serialization.html
So my issue is that I'm limited to BinaryTokenStreamReader/-Writer when using this API, and have to wrap them via own implementation of .NET Stream to pass it in my serialization lib in its turn.
Hope this will reveal my intentions about this request. Thanks!

**Comment by jason-bragg** [comment]
Ah.  Thanks for the clarifications.  

> I'm just trying to override serialization/deserialization for types used in messaging between Grains.

Are you doing this because the types are not natively serializable over Orleans (like bond or protobuf objects for example) or is there another reason?

From the code, the BinaryTokenStreamReader has a public property for it's current position, but no means of acquiring it's total size and does not allow a reader to request data beyond the total size, so it expects some knowledge by the reader.  This is what is causing issue, correct?

Below are a couple suggestions, though I hope better options will present themselves with more thought.

1) Change BinaryTokenStreamReader
Submit a PR that exposes BinaryTokenStreamReader's totalLength as a public property.  That, with the CurrentPosition, should be sufficient to derive remaining size.  We can bundle this change with 1.4.  If you can't wait that long you can build custom nugets from your own branch to use the change immediately.

2) Encode total size
One could encode the total size into the beginning of the payload.  The problem with this is that we don't know the total size until we've serialized the object, so we'd need to serialize the object into a new BinaryTokenStreamWriter, get it's buffers (IList<ArraySegment<byte>> ToBytes()), calculate the total size, then encode the total size and all of the buffers into the BinaryTokenStreamWriter that was passed to the external serializer.  On the read size, we'd read the total size first, then deserialize the object using the CurrentPosition and the total size to cap reads to ensure we never requested more data than was available.

Solution 2 is hacky, but allows one to solve the problem without changes to Orleans.  Solution 1 is better.  If you try solution 2, you may want to double check to ensure that the solution does not leak buffers.  The buffers returned by ToBytes are from the buffer pool, an it's not clear to me if they would be copied or reuses when passed between writers.  If they are copied they will need to be returned to the buffer pool.

**Comment by jason-bragg** [comment]
Reflecting on this over lunch, I think another alternative, coming at the cost of space, would be to encode the size of a buffer prior to any Write(buffer, offset, count) call, then read the size prior to the buffer read.  If the buffer writes as small (integers for instance) this could, unfortunately, double the size though.

**Comment by idudinovr8** [comment]
Thanks @jason-bragg !

I've tried to step onto the second way, and here I've got more precise implementation of `BinaryTokenStream`:

```csharp
private class BinaryTokenStream : Stream
{
    private readonly BinaryTokenStreamReader _reader;
    private readonly BinaryTokenStreamWriter _writer;
            
    public override bool CanRead { get { return _reader != null; } }
    public override bool CanSeek { get { return false; } }
    public override bool CanWrite { get { return _writer != null; } }
    public override long Length { get { throw new NotSupportedException(); } }
    public override long Position
    {
        get { return _reader?.CurrentPosition ?? 0; }
        set { throw new NotSupportedException(); }
    }

    private int _readCountLeft;
    private readonly List<byte[]> _writeChunks;

    public BinaryTokenStream(BinaryTokenStreamReader reader)
    {
        if (reader == null)
            throw new ArgumentNullException(nameof(reader));
                
        _reader = reader;
        // TODO handle errors?
        _readCountLeft = _reader.ReadInt();
    }

    public BinaryTokenStream(BinaryTokenStreamWriter writer)
    {
        if (writer == null)
            throw new ArgumentNullException(nameof(writer));

        _writer = writer;
        _writeChunks = new List<byte[]>(); // TODO Use Pooling?
    }

    public override void Flush()
    {
        if (!CanWrite)
            return;

        if (_writeChunks.Count <= 0)
            return;

        var writeCount = 0;
        for (int i = 0; i < _writeChunks.Count; i++)
            writeCount += _writeChunks[i].Length;

        if (writeCount > 0)
        {
            _writer.Write(writeCount);

            for (int i = 0; i < _writeChunks.Count; i++)
                _writer.Write(_writeChunks[i]);
        }

        _writeChunks.Clear();
    }

    public override long Seek(long offset, SeekOrigin origin)
    {
        throw new NotSupportedException();
    }

    public override void SetLength(long value)
    {
        throw new NotSupportedException();
    }

    public override int Read(byte[] buffer, int offset, int count)
    {
        if (!CanRead)
            throw new InvalidOperationException();

        if (_readCountLeft == 0)
        {
            // It is the case when data has been written in more than one steps,
            // i.e. Flush() was called before write finished
            // (but 100% was called when Stream was closed, 
            // which should be guaranteed by the user of this Stream)
            // If it was so, data separated into few parts, all of them divided by 'length' 
            // markers, so we can just keep reading it 

            _readCountLeft = _reader.ReadInt();
        }

        var readCount = count.Clamp(0, _readCountLeft);

        if (readCount > 0)
        {
            _reader.ReadByteArray(buffer, offset, readCount);
            _readCountLeft -= readCount;
        }
                
        return readCount;
    }

    // This will not actually write to underlying _writer 
    // but will collect all data to know summary length to write it at the beginning.
    public override void Write(byte[] buffer, int offset, int count)
    {
        if (!CanWrite)
            throw new InvalidOperationException();

        if (count <= 0)
            return;

        // TODO Here get from pool with predefined size, split input data if needed
        var chunkCopy = new byte[count]; 
        Array.Copy(buffer, offset, chunkCopy, 0, count);

        _writeChunks.Add(chunkCopy);
    }
            
    public override void Close()
    {
        Flush();
        base.Close();
    }
}
```

Slippery thing here is `Flush()` method. It can be called multiple times and in general things do not seem reliable here. However, I've run some simple tests with my code and it seems the code works well, at least for for the start. And what do think about this?

My serialization is token-based to provide better versioning support. So my plan was to let deserializer to stop reading input stream when it finds special 'EndObject' token, so no info about data length should be stored.

My new plan here is to wrap each of `BinaryTokenStreamWriter` and `BinaryTokenStreamReader` with similar to Newtonsoft's JsonReader/JsonWriter interfaces, implement own tokens for common token types and inject these into my serializer. This approach should be much more stable for me and more straightforward.

My initial questions was not actually about finding the solution for my internal issues, but know is there a way to hook into Orleans serialization/deserialization process more deeply and get access to input/output streams.

Thanks

**Comment by jason-bragg** [comment]
> what do think about this?

I think this is probably viable as a point solution, but not a good general solution.  The reason for this is that Flush should be able to be called at any time and even multiple times, but for the read to work correctly the Flush must be called only at the end.  This means the usage patterns one would generally expect from and implementation of System.IO.Stream would not all be valid.  Again, as a point solution for your purposes, I see no issue with this.

> is there a way to hook into Orleans serialization/deserialization process more deeply and get access to input/output streams.

Not to my knowledge.  The network read/write logic deals with pooled buffers.  The serialization layer serializes into, and deserializes out of, these buffers.  So the paths are roughly:

Out:  object -> serialize -> pooled buffers -> network
In:  network -> pooled buffers -> deserialize -> object

The BinaryTokenStream classes are part of the system that reads/writes data from/to the pooled buffers.

The serialization is intertwined with our messaging/networking stack.  This [Orleans networking discussion](https://www.youtube.com/watch?v=F1Yoe88HEvg&t=56s) is probably more information than you're looking for, and only tangentially relates to what your asking, but it may be interesting if you're trying to obtain a deeper understanding of the Orleans internals.

We've performed some investigations into replacing the networking library as serialization and networking is needed by Orleans, but not our core value add, but that work has only been investigated.  The existing code was intended to be fast but is not terribly modular or easily modified.

**Comment by idudinovr8** [comment]
Thanks @jason-bragg !

Now it's clear for me that there can't be such extension point that I was expecting for :)

So things are pretty clear for me now, and my solution will be to make wrappers for BinaryTokenStream Writer & Reader that will generalize them up to some ISerializationWriter/Reader interfaces and then could be used in serialization/deserialization instead of default readers & writers.

Approach with wrapping with Stream I would consider as more unstable and risky one. 
Hope this thread will help someone.

Thanks!
