### ISSUE TITLE
condition bug in sample code "\GPSTracker\GPSTracker.GrainImplementation\PushNotifierGrain.cs"

### ISSUE THREAD

**Issue by energiehund** [dotnet/orleans#254]
The method SendMessage(...) in "Sample\GPSTracker\GPSTracker.GrainImplementation\PushNotifierGrain.cs" would like to flush the queue if the queue size is greater than 25 but the condition is in reverse.
See snapshot below.

![snapshot](https://cloud.githubusercontent.com/assets/1596768/6768274/c4e7d660-d09c-11e4-84d5-7a30d91d364b.png)

**Comment by sergeybykov** [comment]
@energiehund Thanks! Want to try a one-line PR? :-)

**Comment by gabikliot** [comment]
There are also missing awaits on Invoke and Start in Flush():

                    if (hub.Item1.State == ConnectionState.Connected)
                    {
                        hub.Item2.Invoke("LocationUpdates", new VelocityBatch { Messages = messagesToSend });
                    }
                    else
                    {
                        hub.Item1.Start();
                    }

**Comment by gabikliot** [comment]
Fixed via https://github.com/dotnet/orleans/pull/393.
