### ISSUE TITLE
Behavior changed on ServiceDescriptor between 1.3.1 and 1.4.0 (master)

### ISSUE THREAD

**Issue by jamescarter-le** [dotnet/orleans#2545]
I am using Castle.Windsor in my application as the DI provider.

I used to be able to register the services described in the ServiceCollection as follows:

            // Register those services which have been provided to us by the Orleans Framework
            foreach (var orleansService in orleansServiceCollection)
            {
                var component = Component.For(orleansService.ServiceType)
                 .UsingFactoryMethod(x => orleansService.ImplementationFactory(m_ServiceProvider));

However, now the `ImplementationFactory` is missing on some `ServiceDescriptors` provided in the `ServiceCollection` - does anyone know what has changed here?

I cannot run the latest code as my DI fails when trying to instantiate Orleans services such as the `AssemblyProcessor`.

**Comment by attilah** [comment]
@jamescarter-le can you share a repro project to be able to look into it?

**Comment by attilah** [comment]
What is changed in this area is that now a lot more Orleans service getting injected into DI, see at: https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Silo/Silo.cs#L204

If something is not working, isn't it possible that the Castle/Windsor adapter you're using is not functioning correctly? As I checked the official [Castle/Windsor](https://github.com/castleproject/Windsor/issues/120) repo, the adapter is not completed for thie DI? However in the [last comment](https://github.com/castleproject/Windsor/issues/120#issuecomment-223905258) there is a link to a working adapter.

**Comment by attilah** [comment]
Closing, since the issue (if there is any) it outside of Orleans.
