### ISSUE TITLE
Can I change silo's address dynamically in orleans client? And what's the road map of orleans version in .net core?

### ISSUE THREAD

**Issue by vincentshow** [dotnet/orleans#2549]
In my scenario, there're many data centers that deployed orleans cluster in themself lan, but I don't want to they communicate with each other directly for the sake of performance and security. And I have one centralized dispatcher that used to process requests across data center. In this case, the dispatcher(orleans client) must change silo connection address by request dynamically.

By the way, can you tell me what's the road map of Orleans 2.x, said its target is compatible with .net core. For some reasons, you know, I'm in China, I can't visit youtu.be you mentioned in #2143.

**Comment by ReubenBond** [comment]
@vincentshow maybe we should re-upload the videos to YouKu or something. For now, I've uploaded it to OneDrive here: https://1drv.ms/v/s!AoDgz69KDjB_w-5hOZXWWb8H9sEBvw. Other meetups are here: https://1drv.ms/f/s!AoDgz69KDjB_w-5g04G5UiRpALI5uw

The slides are in the Presentations folder of the `gh-pages` branch: https://github.com/dotnet/orleans/tree/gh-pages/Presentations, the specific slides are here: https://github.com/dotnet/orleans/raw/gh-pages/Presentations/VM-10%20-%20Orleans%202.0%20plan.pptx

We have an open issue to allow you to connect to multiple separate clusters simultaneously: #467 and I am actively working on it.

As a workaround, you can use AppDomains to separate each GrainClient, just like we currently do for testing.

I hope that helps, please let us know if there's anything else we can add
