### ISSUE TITLE
Running of grain Timer callback blocks grain methods being called

### ISSUE THREAD

**Issue by shykln** [dotnet/orleans#2550]
I used RegisterTimer() to register a timer. And when the timer callback A() is called, I found that at that time, if I use a client to call another method B() of that grain instance, the method is blocked by the timer callback A(). After the timer callback A() finishes, the method B() gets executed.

But according to the [documentation](http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Timers-and-Reminders.html), *This means that invocations of asyncCallback should be considered to behave as if running on a reentrant grain with respect to other messages to that grain.*
I got confused by this statement from that doc. 

I thought that invocations of the callback will not block other messages to the grain.  But it does not look true in this case. Is this an issue?

I'm using 1.2.3

**Comment by gabikliot** [comment]
Can you share the code in the callback A()?
Is this reentrant or non reentrant grain?

**Comment by shykln** [comment]
Here is the callback A()
        public Task SpendSomeTime(TimeSpan span)
        {
            var logger = GetLogger();
            logger.Info(0, $"##############################################Timer started");
            
            var startTime = DateTime.Now;
            while (DateTime.Now - startTime < span)
            {

            }
            logger.Info(0, $"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Timer finished");
            return TaskDone.Done;
        }

This SpendSomeTime() is something that takes up the thread for a period of time.

**Comment by gabikliot** [comment]
That callback is synchronously camping on the thread. It never relinquished it via await. That means it will execute without interruptions. Otherwise, we would be violating single threaded execution.

The doc talks about interleaving, situation when you have await or other async block of code within a method.
