### ISSUE TITLE
Access to grain client connection status

### ISSUE THREAD

**Issue by mhertis** [dotnet/orleans#2551]
> If a client loses connection to the cluster, all of the existing producers and consumers on that client will be removed from the pubsub system, even if the client does not unsubscribe. @jason-bragg 

For this reason we need to know client connection status, some kind of a signal/event on connection change (i.e. is lost, reestablished, ..) so that client can resubscribe to the stream.

There was also short conversation on this topic on [gitter](https://gitter.im/dotnet/orleans?at=5858397bc895451b75f77b42).

**Comment by sergeybykov** [comment]
@benjaminpetit, can we easily do something like this?

**Comment by benjaminpetit** [comment]
Sorry for the delay, I am looking into it

**Comment by benjaminpetit** [comment]
We could expose public events when a gateway connect/disconnect, and keep a counter of opened connections. This way, when the counter go back to 0, we know that we are no longer connected to the cluster.

It seems that using `NetworkingStatisticsGroup` we already have this mechanism: when a gateway connects, it calls `NetworkingStatisticsGroup.OnOpenedGatewayDuplexSocket()`` and `NetworkingStatisticsGroup.OnClosedGatewayDuplexSocket` when the gateway is disconnected.

Should we refactor `NetworkingStatisticsGroup` to fit our need or should we add propoer event in the `GrainClient`?

**Comment by jason-bragg** [comment]
some background discussion on this can be found in issue 1421. https://github.com/dotnet/orleans/issues/1421

**Comment by sergeybykov** [comment]
>Should we refactor NetworkingStatisticsGroup to fit our need or should we add propoer event in the GrainClient?

I think we need to add support for an optional callback that we'd invoke upon client disconnect.

**Comment by sergeybykov** [comment]
Resolved via #2628.
