### ISSUE TITLE
[Question] Unexpected error serializing message - Collection was modified

### ISSUE THREAD

**Issue by mhertis** [dotnet/orleans#2552]
Can you guys help me figure it out why I'm getting exceptions below. It seems that when I push (or consume?) message to the stream, serialization fails because dictionary was modified?

`Runtime.Messaging.GatewaySender/GatewaySiloSender_1	100.104.2.49:11111]	Unexpected error serializing message Request S100.104.2.49:30000:0*grn/5B91ACDA/00000000+WDC:87a3d5d3-d4e1-62b1-a05e-11bf2de91f72@15a52896->*cli/467c4d8e@eb8000bcd70c748e #7382800: global::Orleans.Streams.IStreamConsumerExtension:DeliverImmutable() on the gateway	`

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at Orleans.Serialization.BuiltInTypes.SerializeDictionary[K,V](Object original, BinaryTokenStreamWriter stream, Type expected)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, BinaryTokenStreamWriter stream, Type expected)
   at Orleankka.OrleansCodeGenNomnio_Unullo_Core_Contracts_MessageEnvelopeSerializer`1.Serializer(Object untypedInput, BinaryTokenStreamWriter stream, Type expected)
   at Orleans.Serialization.SerializationManager.SerializeInner(Object obj, BinaryTokenStreamWriter stream, Type expected)
   at Orleans.Serialization.BuiltInTypes.SerializeStringObjectDictionary(Object original, BinaryTokenStreamWriter stream, Type expected)
   at Orleans.Serialization.SerializationManager.SerializeMessageHeaderDictHelper(Dictionary`2 headers, BinaryTokenStreamWriter stream)
   at Orleans.Serialization.SerializationManager.SerializeMessageHeaders(Dictionary`2 headers, BinaryTokenStreamWriter stream)
   at Orleans.Runtime.Message.Serialize_Impl(Int32& headerLengthOut, Int32& bodyLengthOut)
   at Orleans.Runtime.Messaging.Gateway.GatewaySender.Send(Message msg, Socket sock)
```

**Comment by attilah** [comment]
Cannot be the case that the dictionary you're passing receives new items?!

**Comment by gabikliot** [comment]
That does not look good.
This is running on the silo and you are publishing events on the stream, that is consumed by the client, correct? Can you share your code in the grain?

We are serializing headers here, not app data, so I cant see how this could happen (unless there is a newly introduced bug in Orleans.)
What is:
`Orleankka.OrleansCodeGenNomnio_Unullo_Core_Contracts_MessageEnvelopeSerializer`
and why it is in the header?
Is this part of the request context? Do you mutate it? How do you use it?

**Comment by ReubenBond** [comment]
It looks like this is occurring while serializing the `RequestContext`

**Comment by gabikliot** [comment]
That's what I though too. This is the only place where custom serializer can be used in headers.
I wonder what is `Orleankka.OrleansCodeGenNomnio_Unullo_Core_Contracts_MessageEnvelope` and how it is being mutated.

**Comment by gabikliot** [comment]
There is some delicate stuff about how logical call context works in .NET, about lazy copy, ....
or maybe there was some recent change that introduced a bug around that code. I saw some changes in the request context lately, but I did not look deeply.

**Comment by ReubenBond** [comment]
@gabikliot for safety, it would be nice if RequestContext was separated out from the rest of the headers. For example, the issue where message serialization exceptions would result in dropped message was fixed but only for the message body - droppages can still occur if the RequestContext has something unserializable in it

**Comment by gabikliot** [comment]
Ok, one option is if this `Orleankka.OrleansCodeGenNomnio_Unullo_Core_Contracts_MessageEnvelope` does  not implement deep copy correctly. we call SerializationManager.DeepCopy(kvp.Value) when we Export the RC (on the calling thread when the call is made). 
The exception above is thrown later on the sending thread. Which means we are trying to send the dictionary referenced from  MessageEnvelope and it is being mutated at this time. Which means it was not deep copied. 
I would check the deep copy method of MessageEnvelope.

**Comment by gabikliot** [comment]
@ReubenBond , good idea about separating the RC from the headers. You will need to add support to stick custom data into the Invocation Request. So will require a bunch of changes. But generally I agree it is better to separate app objects from the runtime headers.

**Comment by mhertis** [comment]
Let me give you some additional context.

When messageEnvelope (`IMessageEnvelope`) is received by an actor we are setting it into the RequestContext (`RequestContext.Set(MESSAGE_ENVELOPE_CONTEXT_KEY, messageEnvelope);`). Next, message envelope is unwraped and passed to an actor (grain) message handler. 

There are few use cases where we need access to the headers of the message envelope. Therefore, we put entire message envelope to the RequestContext. 

Now, it is pretty much clear to me, that this was not a good idea - sending/serializing entire messageEnvelope within headers. =D Maybe AsyncLocal would be more fit in this use case, or if I put only required headers to the RequestContext instead of entire envelope...

Still I don't see how messageEnvelope would be mutated as it should be immutable. But again, it could be bug in our code.

Our interfaces looks like:
``` 
    public interface IMessageEnvelope
    {
        Dictionary<string, string> Headers { get; }
    }

    public interface IMessageEnvelope<out TMessage> : IMessageEnvelope
    {
        TMessage Body { get; }
    }
```

**Comment by gabikliot** [comment]
Can u find the generated code and copy paste the deep copy method?

**Comment by mhertis** [comment]
Where should I look, we are using run-time code-gen...

**Comment by gabikliot** [comment]
@ReubenBond  is there a way to check the serializer code with run time code gen?

**Comment by ReubenBond** [comment]
@gabikliot @mhertis you can log the generated code by increasing the log level to `Verbose3` (if you want, specifically increase it for "CodeGenerator") and then watch for log code 3803 or search for "Generating assembly" in the output

**Comment by mhertis** [comment]
````
   [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.2.3.0"), global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute, global::Orleans.CodeGeneration.SerializerAttribute(typeof(global::Nomnio.Unullo.Core.Contracts.MessageEnvelope<>))]
        internal class OrleansCodeGenNomnio_Unullo_Core_Contracts_MessageEnvelopeSerializer<TMessage>
        {
            private static readonly global::System.Reflection.FieldInfo field0 = typeof(global::Nomnio.Unullo.Core.Contracts.MessageEnvelope<TMessage>).@GetField("<Body>k__BackingField", (System.@Reflection.@BindingFlags.@Instance | System.@Reflection.@BindingFlags.@NonPublic | System.@Reflection.@BindingFlags.@Public));
            private static readonly global::System.Action<global::Nomnio.Unullo.Core.Contracts.MessageEnvelope<TMessage>, TMessage> setField0 = (global::System.Action<global::Nomnio.Unullo.Core.Contracts.MessageEnvelope<TMessage>, TMessage>)global::Orleans.Serialization.SerializationManager.@GetReferenceSetter(field0);
            private static readonly global::System.Reflection.FieldInfo field1 = typeof(global::Nomnio.Unullo.Core.Contracts.MessageEnvelope).@GetField("<Headers>k__BackingField", (System.@Reflection.@BindingFlags.@Instance | System.@Reflection.@BindingFlags.@NonPublic | System.@Reflection.@BindingFlags.@Public));
            private static readonly global::System.Action<global::Nomnio.Unullo.Core.Contracts.MessageEnvelope, global::System.Collections.Generic.Dictionary<global::System.String, global::System.String>> setField1 = (global::System.Action<global::Nomnio.Unullo.Core.Contracts.MessageEnvelope, global::System.Collections.Generic.Dictionary<global::System.String, global::System.String>>)global::Orleans.Serialization.SerializationManager.@GetReferenceSetter(field1);
            [global::Orleans.CodeGeneration.CopierMethodAttribute]
            public static global::System.Object DeepCopier(global::System.Object original)
            {
                return original;
            }

            [global::Orleans.CodeGeneration.SerializerMethodAttribute]
            public static void Serializer(global::System.Object untypedInput, global::Orleans.Serialization.BinaryTokenStreamWriter stream, global::System.Type expected)
            {
                global::Nomnio.Unullo.Core.Contracts.MessageEnvelope<TMessage> input = (global::Nomnio.Unullo.Core.Contracts.MessageEnvelope<TMessage>)untypedInput;
                global::Orleans.Serialization.SerializationManager.@SerializeInner(input.@Body, stream, typeof(TMessage));
                global::Orleans.Serialization.SerializationManager.@SerializeInner(input.@Headers, stream, typeof(global::System.Collections.Generic.Dictionary<global::System.String, global::System.String>));
            }

            [global::Orleans.CodeGeneration.DeserializerMethodAttribute]
            public static global::System.Object Deserializer(global::System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                global::Nomnio.Unullo.Core.Contracts.MessageEnvelope<TMessage> result = new global::Nomnio.Unullo.Core.Contracts.MessageEnvelope<TMessage>();
                global::Orleans.@Serialization.@DeserializationContext.@Current.@RecordObject(result);
                setField0(result, (TMessage)global::Orleans.Serialization.SerializationManager.@DeserializeInner(typeof(TMessage), stream));
                setField1(result, (global::System.Collections.Generic.Dictionary<global::System.String, global::System.String>)global::Orleans.Serialization.SerializationManager.@DeserializeInner(typeof(global::System.Collections.Generic.Dictionary<global::System.String, global::System.String>), stream));
                return (global::Nomnio.Unullo.Core.Contracts.MessageEnvelope<TMessage>)result;
            }
        }

**Comment by gabikliot** [comment]
Well, here you go: `DeepCopier` does not really deep copy. 
Any ideas why @ReubenBond ?  maybe it gets confused somehow due to how `IMessageEnvelope` is defined?

**Comment by ReubenBond** [comment]
Is `MessageEnvelope<T>` marked with `[Immutable]`, @mhertis? If it is, it will not be copied.
It looks like you're hitting this branch in the code generator:
![image](https://cloud.githubusercontent.com/assets/203839/21660316/003109dc-d323-11e6-82bd-daf2acf86c07.png)

**Comment by gabikliot** [comment]
Great catch Reuben!
Maybe it will be a good idea to emit a comment in the deep copy generated code "this type was marked with immutable attribute and thus will be shallow copied". Will help with future diagnosis and troubleshooting.

**Comment by ReubenBond** [comment]
Good idea, @gabikliot - I'll do that now

**Comment by ReubenBond** [comment]
How does this look?
```C#
public static global::System.Object DeepCopier(global::System.Object original)
{
    // No deep copy required since Orleans.Streams.StreamImpl<T> is marked with the [Immutable] attribute.
    return original;
}
```

**Comment by ReubenBond** [comment]
@mhertis we've merged #2568, which adds a comment to the generated code to make this more obvious. Is your issue solved?

**Comment by mhertis** [comment]
@ReubenBond yes that is the case, it is marked with `[Immutable]`. It was bug in our code that mutate message envelope at the first place.  We can close this issue, lesson learned. =D

**Comment by ReubenBond** [comment]
Fantastic, I'm glad that we could help
