### ISSUE TITLE
Link to clean dev CI Builds broken

### ISSUE THREAD

**Issue by mkstephenson** [dotnet/orleans#2553]
The link to the latest CI dev builds is broken, when I try and access it, I get a DNS error for dotnet-ci.cloudapp.net. Is this domain only available inside the Microsoft network? Or has the name changed?

**Comment by ReubenBond** [comment]
Thanks for pointing that out, @mkstephenson. It looks as though the CI server moved and the latest builds for full .NET can be found here: https://ci.dot.net/job/dotnet_orleans/job/master/job/netfx/lastStableBuild/artifact/

**Comment by mkstephenson** [comment]
Awesome thanks!
