### ISSUE TITLE
Orleans Silo Performance Optimization Tips

### ISSUE THREAD

**Issue by sbrohi15** [dotnet/orleans#2566]
Hello,

We are using MS Orleans to run a distributed application and we have encountered serious slowness with the silo one hour after service startup.

Our client (windows service) sends data files to our Orleans cluster (windows service) for processing. Post-processing, the data is written into a SQL Server database. We measure throughput by analyzing the number of files processed by the cluster each hour.

At service start, the number of activations appears to be ~3000+, but that number decreases to about ~1200 activations after the first hour and then remains constant, at which the performance has seriously degraded - ~3000 files processed in the first hour, and then ~700 files in each subsequent hour after.

We have experimented with increasing **MaxActiveThreads** and have also run the silo on a 4 core and 8 core VM, but in any case, it has not yielded any significant performance boost.

What tips and strategies should we apply in order to optimize and boost the performance of our silos?

I have attached a copy of our **OrleansConfiguration.xml** file as a reference (server names redacted).

We are running Orleans version 1.0.10. 

Thank You,

Shazad Brohi
[OrleansConfiguration.txt](https://github.com/dotnet/orleans/files/685630/OrleansConfiguration.txt)

**Comment by sergeybykov** [comment]
What level of CPU utilization are you seeing?
Is the grain code 100% asynchronous (with `Tasks` and `awaits` properly used and no thread blocking?
Can you share silo statistics from the logs (they are dumped every 5 minutes by default)?
Are there any warnings in the silo logs?
Are there any abnormalities in the .NET memory perf counters, e.g. excessive % of CPU time spent in GC?
Is it possible that the app is leaking a managed resource, i.e. object leaking?

**Comment by gabikliot** [comment]
<GrainType Type="EImporterGrainCollection.Statistics.StoreStatisticsGrain">
        <Deactivation AgeLimit="60m"/>
      </GrainType>

as well

<StorageProviders>
      <Provider Type="Orleans.Storage.MemoryStorage" Name="MemoryStore" />
    </StorageProviders>

looks suspicious to me.

**Comment by sergeybykov** [comment]
@gabikliot has a good point - if you gradually accumulate state in the `MemoryStorage` provider, it will quickly become a bottleneck. It is mostly meant for development and for some light-weight scenarios. Even in those light-weight cases we recommend to configure it for a large number of storage grains.

**Comment by sbrohi15** [comment]
@sergeybykov do you recommend that I remove the "MemoryStore" configuration from OrleansConfiguration.xml? And what do you think would be wrong with using the current deactivation limit of 60m for the "EImporterGrainCollection.Statistics.StoreStatisticsGrain"?

CPU utilization appears to be fine - 15-25% on average.
To the best of my knowledge, we are making use of Tasks and awaits for each call, though I can confirm.
Attached are the statistics from the OrleansStatisticsTable in XLSX format.
I am not aware of any managed resources being leaked by the app, how can I determine this?
I have not noticed any abnormalities from the .NET performance counters. What is the message in the Orleans log that indicates that an excessive amount of CPU time is spent in GC?


[OrleansStatistics.xlsx](https://github.com/dotnet/orleans/files/685995/OrleansStatistics.xlsx)

I have noticed many warnings in the silo logs 
indicating the following:

> 	Line 99197: 2017-01-04 14:03:30,797: [Runtime.Scheduler.WorkerPoolThread/7] WARN  [2017-01-04 20:03:30.797 GMT    15	WARNING	101215	Scheduler.WorkItemGroup	10.15.15.90:11111]	Task [Id=2468, Status=RanToCompletion] in WorkGroup [Activation: S10.15.15.90:11111:221246319*grn/8FEB36A3/00000000+import>dfw04-eimp92>import_30_0bb16dfa-4f80-41f8-af88-fef8bc71d282>1@18916d92 #GrainType=EImporterGrainCollection.Database.Import.DatabaseImportGrain Placement=RandomPlacement State=Valid] took elapsed time 0:00:00.7176085 for execution, which is longer than 00:00:00.4000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/7, ManagedThreadId=15, Executing Task Id=2468 Status=RanToCompletion for 00:00:00.7187704>

**Comment by sbrohi15** [comment]
@sergeybykov Also to note, we do use the MemoryStore for caching data with our grains.

**Comment by sergeybykov** [comment]
>I have noticed many warnings in the silo logs
indicating the following: ... took elapsed time 0:00:00.7176085 for execution

This could be the problem. If a requests takes .7 seconds of *synchronous* execution, then you can't execute more even two such requests per second per thread. Do you know what it taking that long. Smells like a blocking IO call to me. If that's the case, it needs to be turned into an async equivalent.

Are you using "MemoryStore" for your grains? I.e. do you have  `[StorageProvider(ProviderName = "MemoryStore")]` anywhere in your code? If not, you can simply remove it from the config.

>How can we configure it to be used for a large number of storage grains?

You need to set `NumStorageGrains=X` in the provider config, where X is high enough, e.g. 1000.

>What do you think would be wrong with using the current deactivation limit of 60m for the "EImporterGrainCollection.Statistics.StoreStatisticsGrain"?

I don't see a problem with that, unless you use a large and fast growing number of grain of this type.

>CPU utilization appears to be fine - 15-25% on average.

That's very low. You are likely either not pushing enough requests to the system or the grain code blocks threads or both. How do you do push requests to the system? Do you run one or more single-threaded load generators or send a bunch of parallel requests?

>I am not aware of any managed resources being leaked by the app, how can I determine this?

You can take a memory dump of the silo process, load it into debugger and look at the object counts by type. If there's an abnormally high number of object of a particular type or types, that may indicate a leak.

>I have not noticed any abnormalities from the .NET performance counters. What is the message in the Orleans log that indicates that an excessive amount of CPU time is spent in GC?

There is a warning if the runtime detects what appears like a GC pause. With such low CPU utilization it's unlikely.

**Comment by sergeybykov** [comment]
The statistics you attached, is it a dump form the statistics table? Unfortunately, only a subset of statistics are written there. The full set is in the log, starts with something like:
>[2017-01-03 06:55:20.047 GMT    76	INFO   	100704	SiloLogStatistics	10.197.9.219:11111]	Statistics: ^^^

**Comment by sbrohi15** [comment]
@sergeybykov We are using MemoryStore for a few grains to cache data but not in a way that gradually accumulates state. I will go ahead and remove the MemoryStore tag.

Very good point about the blocking grain call. I am not sure of which part of the grain is using a synchronous call, but I will examine the grain and find it.

I am also pulling the statistics from one of my log files and will send it shortly.

**Comment by sergeybykov** [comment]
>We are using MemoryStore for a few grains to cache data but not in a way that gradually accumulates state. I will go ahead and remove the MemoryStore tag.

If you are using the provider and remove it from config, your code won't work anymore unless you replace it with a different provider. Better leave it then and increase `NumStorageGrains`.

**Comment by galvesribeiro** [comment]
> We are using MemoryStore for a few grains to cache data but not in a way that gradually accumulates state. I will go ahead and remove the MemoryStore tag.

If it is just a cache and don't require persistence, you don't need a storage provider at all. I have several grains which has state but doesn't persist it anywhere. It is just cached data in-memory while the grain is activated.

**Comment by gabikliot** [comment]
+1 on the last comment. Why do you need to use memory storage provider at all? The in memory grain state already keeps the state for you. That is the whole point behind grains.

**Comment by sbrohi15** [comment]
@sergeybykov Attached are the Silo Log Statistics from the silo logs. These were just a random sampling from the silo log.

[SiloLogStatistics.txt](https://github.com/dotnet/orleans/files/687443/SiloLogStatistics.txt)

**Comment by sergeybykov** [comment]
The file for some reason is missing `Rintime.CpuUsage`, `Runtime.GC.*`, and some other core statistics. However, `Scheduler.NumLongRunningTurns.Current=43883` seems to point to the key issue - synchronous execution of IO operations, as was suggested above.

**Comment by sbrohi15** [comment]
@sergeybykov Is there any additional visibility provided in the silo logs that will allow us to track down the specific grain class or LoC that is causing the warning messages displayed earlier?

**Comment by sergeybykov** [comment]
The warning points to the grain:
>grn/8FEB36A3/00000000+import>dfw04-eimp92>import_30_0bb16dfa-4f80-41f8-af88-fef8bc71d282>1@18916d92 #GrainType=EImporterGrainCollection.Database.Import.DatabaseImportGrain 

If you add logging to the begin/end of the grain methods, you should be able to easily correlate the warnings with the offending methods.

**Comment by sbrohi15** [comment]
@sergeybykov That makes sense. I will try that.

**Comment by galvesribeiro** [comment]
@sbrohi15 you can add interceptor to instrument granin method calls

**Comment by peter-perot** [comment]
@sbrohi15: If you use a grain to cache data for a longer time, you can call `this.DelayDeactivation(…)` to prevent the grain from being deactivated too early.

**Comment by sergeybykov** [comment]
@sbrohi15 Any luck?

**Comment by sbrohi15** [comment]
@sergeybykov We have eliminated the warning message and have put in changes to get rid of the memory store, but the performance has not significantly improved. Our next approach will be to upgrade our application to use the latest version of Orleans (1.3.0) and test.

Would you have any other suggestions to look at? If not, then we can probably close this thread.

**Comment by sergeybykov** [comment]
>but the performance has not significantly improved.

Could you elaborate on that - how you measure performance?

**Comment by sbrohi15** [comment]
@sergeybykov We measure performance by counting how many data files are processed by each silo per hour. We use a batch file to copy over 10000 data files to a group of silos (2). In our prior tests, we observed ~2000 files per silo per hour, that number is now at ~2200 per silo per hour, so the increase isn't significant.

**Comment by sergeybykov** [comment]
@sbrohi15 How do you dispatch work (files) to grains? The low CPU utilization of 15%-25% makes me suspect that either grains don't get enough work dispatched to them (not enough parallelism in getting work to grains) or that the grain threads get blocked by synchronous waits, even if for short periods of time.

Can you share the logs?

**Comment by sbrohi15** [comment]
@sergeybykov We have an FTP service that sends files to a file share on each silo. An Orleans client (windows service) resides on the same server as each silo and constantly scans the file share for files. For each file the client finds, it invokes a grain call on the silo - ProcessFile(). At that point, the silo processes the file.

Attached are log files from our environment.

[eImporterLog_20170124_SILO_ONE_000001.txt](https://github.com/dotnet/orleans/files/727432/eImporterLog_20170124_SILO_ONE_000001.txt)
[eImporterLog_20170124_SILO_ONE_000002.txt](https://github.com/dotnet/orleans/files/727437/eImporterLog_20170124_SILO_ONE_000002.txt)

**Comment by peter-perot** [comment]
Could it be that the I/O API is not async in all execution paths? Maybe using external tasks could help: https://dotnet.github.io/orleans/Documentation/Advanced-Concepts/External-Tasks-and-Grains.html

**Comment by sergeybykov** [comment]
Looks like is it indeed sync operation on grain threads - see warnings 101215:
>2017-01-24 00:53:10,777: [Runtime.Scheduler.WorkerPoolThread/6] WARN  [2017-01-24 06:53:10.777 GMT    14	WARNING	101215	Scheduler.WorkItemGroup	10.15.15.90:11111]	Task [Id=9767, Status=RanToCompletion] in WorkGroup [Activation: S10.15.15.90:11111:222910781*grn/8FEB36A3/00000000+import>dfw04-eimp91>import_31_156fdcee-1335-421a-bfd8-c8d7ccebbffc>2@b0252387 #GrainType=EImporterGrainCollection.Database.Import.DatabaseImportGrain Placement=RandomPlacement State=Valid] took elapsed time 0:00:01.0371024 for execution, which is longer than 00:00:00.2000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/6, ManagedThreadId=14, Executing Task Id=9767 Status=RanToCompletion for 00:00:01.0313007>

1 second of synchronous execution.

>2017-01-24 00:53:12,902: [Runtime.Scheduler.WorkerPoolThread/7] WARN  [2017-01-24 06:53:12.902 GMT    15	WARNING	101215	Scheduler.WorkItemGroup	10.15.15.90:11111]	Task [Id=9768, Status=RanToCompletion] in WorkGroup [Activation: S10.15.15.90:11111:222910781*grn/8FEB36A3/00000000+import>dfw04-eimp90>import_31_1ac0e682-bca3-4015-afcb-0e0a63e380a0>2@b8e2a682 #GrainType=EImporterGrainCollection.Database.Import.DatabaseImportGrain Placement=RandomPlacement State=Valid] took elapsed time 0:00:02.1113416 for execution, which is longer than 00:00:00.2000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/7, ManagedThreadId=15, Executing Task Id=9768 Status=RanToCompletion for 00:00:02.1094587>

2 seconds. And so forth.

Switching to async APIs (better) or 'oursourcing' of the synchronous operations to the .NET thread pool (if async APIs are unavailable) should help increase the throughput.
