### ISSUE TITLE
GetStreamProvider KeyNotFoundException' in Orleans.dll

### ISSUE THREAD

**Issue by AwsomeCode** [dotnet/orleans#2570]
At ASP.Net client side I am getting KeyNotFoundException at below highlighted line

> var guid = Guid.NewGuid();
string streamNamespace = "OnConnect";
string providerToUse = "SMSProvider";
var userGrain = GrainClient.GrainFactory.GetGrain<IUserGrain>(name);
await userGrain.BecomeProducer(guid, streamNamespace, providerToUse);
**IStreamProvider streamProvider = GrainClient.GetStreamProvider(providerToUse);**
consumer = streamProvider.GetStream<string>(guid, streamNamespace);
consumerHandle = await consumer.SubscribeAsync(OnNextAsync);

Exception 
> Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in Orleans.dll
iisexpress.exe Information: 0 : [2017-01-05 14:45:35.652 GMT    18	INFO   	101309	Messaging.GatewayManager	192.168.3.99:0]	Refreshed the live GateWay list. Found 1 gateways from Gateway listProvider: [gwy.tcp://127.0.0.1:40000/0]. Picked only known live out of them. Now has 1 live Gateways: [gwy.tcp://127.0.0.1:40000/0]. Previous refresh time was = 05-01-2017 14:44:29	
Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in mscorlib.dll

Server Side Config is

> var config = ClusterConfiguration.LocalhostPrimarySilo();
config.AddMemoryStorageProvider("Default");
config.AddMemoryStorageProvider("PubSubStore");
config.AddSimpleMessageStreamProvider("SMSProvider");
hostWrapper = new OrleansHostWrapper(config, args);

**Comment by galvesribeiro** [comment]
As I mentioned on Gitter, you are only registering the stream provider on the Silo. Do that in the client and the problem should go away.
