### ISSUE TITLE
[Question] SimpleMessageStreamProducer NullReferenceException on Cleanup

### ISSUE THREAD

**Issue by mhertis** [dotnet/orleans#2584]
I'm seeing a lot of `NullReferenceException`  and I cannot figure out the source of the problem. Any idea how/when this could happen on Orleans 1.2.3.0?

Assembly: Orleans, Version=1.2.3.0, Culture=neutral, PublicKeyToken=null
Exception type: System.NullReferenceException
Failed method: Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1+<Cleanup>d__27.MoveNext
Handled at: UserCode
Innermost exception message: Object reference not set to an instance of an object.
Innermost exception type: System.NullReferenceException
Outer exception assembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Outer exception message: Object reference not set to an instance of an object.
Outer exception method: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
Outer exception type: System.NullReferenceException
Problem ID: System.NullReferenceException at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1+<Cleanup>d__27.MoveNext

Stack Trace
System.NullReferenceException: Object reference not set to an instance of an object.
    at  System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
    at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
    at  Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1+<Cleanup>d__27.MoveNext

**Comment by sergeybykov** [comment]
Is this the one that was fixed via #2040 in v1.2.4?

**Comment by mhertis** [comment]
It could be, I can report when we upgrade to latest.

**Comment by mhertis** [comment]
We are also observing `NullReferenceException` on `RegisterProducer`. Possibly related and fixed via #2040 in v1.2.4.

[2017-01-18 15:19:10.446 GMT    12	ERROR  	103410	PubSubRendezvousGrain-S100.104.2.49:11111:221904462-*grn/716E8E94/0000000000000000000000000000000006000000716e8e94+sms_MessageRouter:GWD1:1da9d81a31d10000-Commands-0xC6BF6E80	]	!!!!!!!!!! Failed to register a stream producer.  Stream: MessageRouter:GWD1:1da9d81a31d10000-Commands-00000000-0000-0000-0000-000000000000-sms, Producer: GrainReference:*grn/C89508F2/00000000+MessageRouter:GWD1:1da9d81a31d10000	
Exc level 0: System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.Streams.PubSubRendezvousGrain.<RegisterProducer>d__14.MoveNext()

How can we fix this without restarting cluster?

**Comment by jason-bragg** [comment]
The null reference bug can show up any time a stream's PubSubRendezvousGrain's state has been cleared, both for adding producers and consumers.

Unfortunately, I am not aware of any way to fix this that does not involve a cluster restart. :/

**Comment by mhertis** [comment]
Is there any setting available to prevent state to be cleared? I could delete entire row from table storage and restart cluster. 

We cannot upgrade to 1.2.4 at the moment.

**Comment by jason-bragg** [comment]
Clearing the entries from table storage would not likely solve the problem as the grain would still be in memory.  Clearing the table and cycling the service would temporarily mitigate the issue, but the grains would eventually get back into a bad state.

>We cannot upgrade to 1.2.4 at the moment.

Are any code changes possible at this time?  Without an Orleans upgrade, you may still be able to code a mitigation to this with a (very hacky) custom storage provider..  This is not recommended, as it would be a horrifying hack.

**Comment by mhertis** [comment]
Thnx for clarification. We will upgrade to 1.2.4. to resolve this issue.
