### ISSUE TITLE
[Question] set ServerGC to true

### ISSUE THREAD

**Issue by sgratwohl** [dotnet/orleans#2585]
Hi,

While investigating some `Response did not arrive on time in 00:00:30 for message` errors I came across a very informative logfile analysis in issue #284 where it is stated that you should turn ServerGC on for better performance. However after adding
`<gcServer enabled="true"/> <gcConcurrent enabled="false"/>`
to my app.config of the silo WorkerRole orleans still complains on startup that the silo is not running with ServerGC turned on:

> 
> Silo starting with GC settings: ServerGC=False GCLatencyMode=Interactive
> 
> Note: Silo not running with ServerGC turned on or with GCLatencyMode.Batch enabled - recommend checking app config : < configuration>-< runtime>-< gcServer enabled="true"> and < configuration>-< runtime>-< gcConcurrent enabled="false"/>

The WorkerRole runs on a 4 core instance.
Did I miss something in the configuration?

Thanks for hints!

**Comment by sergeybykov** [comment]
Unfortunately, adding those settings to app.config in not enough in case of Azure Roles. There are known workarounds as described in https://blogs.msdn.microsoft.com/cie/2013/11/14/enable-server-gc-mode-for-your-worker-role/ and https://blogs.msdn.microsoft.com/cclayton/2014/06/05/server-garbage-collection-mode-in-microsoft-azure/.

**Comment by sgratwohl** [comment]
`Silo starting with GC settings: ServerGC=True GCLatencyMode=Batch`

Thank you very much for the help!
