### ISSUE TITLE
.Net Garbage Collection not triggering

### ISSUE THREAD

**Issue by jake-bauer** [dotnet/orleans#2586]
I have the 
`<runtime>
    <gcServer enabled="true" />
    <gcConcurrent enabled="false" />
</runtime>`

configured however I am never seeing the log message coming that garbage collection has been fired. Is there something that I am missing or is this a bug

The specific log message I am looking for is this line 
`logger.Info("Forcing garbage collection on {0}", Utils.EnumerableToString(silos));`

in the ManagementGrain.cs

Current version of orleans being used is 1.3.0

**Comment by sergeybykov** [comment]
This code only executes when `ForceGarbageCollection` is explicitly called by application (usually some admin or test tool) to induce a .NET garbage collection in a silo or a set of silos. It is there for diagnostic and testing purposes, not for production use. So it is expected that you don't see the log message unless you call `ForceGarbageCollection`.
