### ISSUE TITLE
CorrelationId/ActivityId for every Orleans requests

### ISSUE THREAD

**Issue by MishaUliutin** [dotnet/orleans#2588]
Suppose we have system where Orleans uses as a backend for one of system service and user request comes in and after various aspects of the request has been handled by several system services something goes wrong. Even though every service would have been logging along the way it’s no easy task to find all the relevant log messages for this request, so an easy way to correlate logs at different services that belong to the same user request is associating a correlation ID to it and let this ID flow through the system and mark all logs with this ID, so you can later reconstruct the whole history of that request as it went across the system. In case of HTTP implementation is pretty straightforward: you just add to every request custom header (e.g. X-Request-Id), read it in http server request pipeline and set it to request context so log library will be able to read it and automagically mark all log messages (e.g. in case of .Net it could be https://msdn.microsoft.com/en-us/library/system.diagnostics.correlationmanager.activityid(v=vs.110).aspx or https://msdn.microsoft.com/en-us/library/system.runtime.remoting.messaging.callcontext(v=vs.110).aspx). 
Is there any way to implement such correlation id for every requests to Orleans cluster opaque for the actors? E.g. something kinda message handlers in MVC (https://www.asp.net/web-api/overview/advanced/http-message-handlers) + custom HTTP headers. Of course it is always possible to add correlation id to all grains method, but this solution is error prone and ugly...

**Comment by sergeybykov** [comment]
Yes, there is `RequestContext` for this purpose - http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Request-Context.html.
