### ISSUE TITLE
Orleans nominated for JAX Awards 2015 "Most Innovative Open Technology" Section

### ISSUE THREAD

**Issue by jthelin** [dotnet/orleans#259]
**Orleans** has been nominated for the "**Most Innovative Open [Source] Technology**" section in the [**2015 JAX Awards**](http://jaxenter.com/jax-awards-2015/submit-your-vote)

While it is always an _hono[u]r_ to have a project we are working on nominated for an industry award, it is even more _humbling_ when that nomination comes from someone in the user community rather the core project team itself !

The Orleans Core Team would like to extend our heart-felt thanks to each and every one of our users (aka **you**!) who have experimented with Orleans and provided us with great feedback and helped us make a better product for everyone.

Many of you are already making significant contributions in the [GitHub community](https://github.com/dotnet/orleans), with great suggestions, bug fixes and actively leading discussions about areas for enhancement and future directions. Please keep those coming! Orleans is no longer “our” project, but it truly is “your” product now!

Lastly, it would be remiss of me not to ask you to visit the JAX web site and carefully consider how to cast your votes. :smile:  There are many great infrastructure software projects on the JAX Awards list which are helping to bring in a new era of robust cloud-scale systems.
http://jaxenter.com/jax-awards-2015/submit-your-vote

Thank you!
Jorgen, on behalf of the Orleans Core Team.

----------
For reference, the candidates for JAX Awards Nominees for 2015 are:

# Most Innovative Open Technology #
-	Kubernetes
-	Groovy
-	Apache Mesos
-	logstash
-	Homebrew
-	Nginx
-	Node-RED
-	Dropwizard
-	Docker Orchestration
-	Akka
-	Socketplane
-	Weave
-	Tachyon
-	Microsoft Orleans

# Most Innovative Java Technology #
-	Nodyn
-	Apache Storm
-	OpenHAB
-	Apache Kafka
-	Neo4J
-	Apache Cassandra
-	Java 8
-	JRebel
-	Vaadin
-	NASA

**Comment by veikkoeeva** [comment]
:+1: * :100:

**Comment by lilinghui** [comment]
good

**Comment by mirobert-msft** [comment]
👏
=

**Comment by jthelin** [comment]
Congratulations to this years winners:

http://jaxenter.com/jax-awards-winners-announced-at-jax-2015-conference-116358.html
