### ISSUE TITLE
Runtime exception serializing property of type derived from Dictionary<string,object>

### ISSUE THREAD

**Issue by globeport** [dotnet/orleans#2603]
I'm returning an object from one of my grains that contains a property of type DataObject where DataObject is of type Dictionary<string, object>. Nothing else special about DataObject. (NB It has a default constructor.)

The runtime throws the following exception: "No serializer found for object of type DataObject. Perhaps you need to mark it [Serializable] or define a custom serializer for it?"

I can't mark this class as serializable because it is defined in a portable assembly where the Serializable attribute is not available.

Do I really need to define a custom serializer for this class? I would have expected Orleans to be able to handle this implicitly just as it can handle objects of direct type Dictionary<TKey,TValue>.

Thanks

**Comment by globeport** [comment]
I've added the following custom serializer to get around this for now. Id be grateful if you could let me know if there's better way. Thanks,

```
[RegisterSerializerAttribute()]
    internal class DataObjectSerializer
    {
        static DataObjectSerializer()
        {
            Register();
        }

        public static object DeepCopier(object original)
        {
            return SerializationManager.DeepCopy(new Dictionary<string, object>((DataObject)original));
        }

        public static void Serializer(object untypedInput, BinaryTokenStreamWriter stream, Type expected)
        {
            SerializationManager.Serialize(new Dictionary<string, object>((DataObject)untypedInput), stream);
        }

        public static object Deserializer(Type expected, BinaryTokenStreamReader stream)
        {
            return new DataObject((Dictionary<string, object>)(SerializationManager.Deserialize(typeof(Dictionary<string, object>), stream)));
        }

        public static void Register()
        {
            SerializationManager.Register(typeof(DataObject), DeepCopier, Serializer, Deserializer);
        }
    }
```

**Comment by ReubenBond** [comment]
@globeport does the object you're returning from your grain method have a serializer generated for it?
What happens if you add an assembly-level `[assembly: KnownType(typeof(DataObject))]`?

**Comment by ReubenBond** [comment]
@globeport is this issue still affecting you?

**Comment by globeport** [comment]
Hi sorry, I meant to respond to this. I ended up serializing this type using Json.NET using a registered serializer similar to above but implementing the serialize and deserialize methods using Json.NET.

I didn't have time to explore it further. I did try including the assembly directive but this didn't solve the problem. From memory I think I found the serializer posted above would fail for nested dataobjects in the data structure.

**Comment by sergeybykov** [comment]
Does this still happen with 1.4.0?

**Comment by globeport** [comment]
No issues now with 1.4.0 having removed the registered serializers mentioned above.

Thanks,
Stuart

**Comment by ReubenBond** [comment]
Thanks for confirming, @globeport :)
