### ISSUE TITLE
Advice for debugging timeouts?

### ISSUE THREAD

**Issue by kogir** [dotnet/orleans#2606]
I'm running a 5 silo cluster in Azure Cloud Services using Azure Table Storage for membership.

Occasionally in my logs I'll see a lot of error messages about timeouts. Lines like: "Exc level 0: System.TimeoutException: Response did not arrive on time in 00:00:30 for message: Request S10.1.0.5:11111:222398284*grn/C7446283/048f6644@02ad2daf->S10.1.0.4:11111:222398298*grn/E9DE4AC/00014635@5e1a309d #159914: global::RealArtists.ShipHub.ActorInterfaces.GitHub.IGitHubActor:Labels(). Target History is: <S10.1.0.4:11111:222398298:*grn/E9DE4AC/00014635:@5e1a309d>."

What's the best way to debug these? Is `159914` the ID of the `IGitHubActor` grain? Is this perhaps the scenario mentioned in #1383 and addressed in #2387?

I searched through previous issues and the docs and wasn't able to find any obviously applicable answers. Sorry if I missed something.

**Comment by ReubenBond** [comment]
@kogir, which version of Orleans are you using?

**Comment by kogir** [comment]
We're using 1.3.1 from NuGet.

I've not been able to catch it under a debugger, but we have pretty extensive logging. Is there something I should be looking for? Or were you suggesting that I catch the exception in the debugger and deduce the grain identity from the surrounding context?

I don't think this is a deadlock, because the `IGitHubActor` grain makes no other grain calls - its single purpose is to interface with GitHub over HTTP via their API. We're using HttpClient, WinHttpHandler, and (I think) proper asynchronous calls for that.

When you recommend increasing log verbosity - should I do that on the silos, the grain clients, or both?

The one (perhaps) complication - The grain is re-entrant, and uses a semaphore internally to limit concurrency. It's implemented as follows:

```c#
public class GitHubActor : Grain, IGitHubActor, IGrainInvokeInterceptor, IDisposable {
  // (I think) irrelevant implementation details elided

  private SemaphoreSlim _maxConcurrentRequests = new SemaphoreSlim(4);

  public async Task<object> Invoke(MethodInfo method, InvokeMethodRequest request, IGrainMethodInvoker invoker) {
    await _maxConcurrentRequests.WaitAsync();

    object result;
    try {
      result = await invoker.Invoke(this, request);
    } finally {
      _maxConcurrentRequests.Release();
    }

    // Work that can't deadlock and I don't think is relevant

    return result;
  }
}
```

**Comment by kogir** [comment]
Looking at it again now, I suppose it's possible the HttpClient or WinHttpHandler are somehow getting stuck. I'll add logging and a timeout in the interceptor to see if that's the case.

This will probably end up being an issue in my code. I'll close the issue for now, and only re-open if further information implicates Orleans.
