### ISSUE TITLE
ProviderManagerSystemTarget taking more time

### ISSUE THREAD

**Issue by ponsakthi** [dotnet/orleans#2607]
I am using 1.0.9 version of Orleans. We are seeing occasional performance issues in random fashion. However we were able to see that performance degrades soon after the following log

`Message="[2017-01-18 08:52:26.298 GMT 32   WARNING 101215  Scheduler.**ProviderManagerSystemTarget**.WorkItemGroup 100.77.188.57:11111]    Task [Id=714, Status=RanToCompletion] in WorkGroup [SystemTarget: S100.77.188.57:11111:222421447ProviderManagerSystemTarget@S00000013] took elapsed time **0:00:20.2351085** for execution, which is longer than 00:00:00.2000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/System.9, ManagedThreadId=32, Executing Task Id=714 Status=RanToCompletion for 00:00:20.2477911>   `

ProviderManagerSystemTarget WorkItem took close to 21 seconds. 

What could be the possible root cause?

Note: We are not using streams. Bootstrap code was not running at this point of time.

**Comment by sergeybykov** [comment]
This sounds very strange. `ProviderManagerSystemTarget` is only used during silo startup. Are you seeing the warning much later? Can you share the full log?
