### ISSUE TITLE
Remove SerializationManager.Register method

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#2610]
Currently, when `SerializationMananger` is scanning types in `FindSerializationInfo`, it checks types for the `[RegisterSerializer]` attribute and calls their `Register` method if one is found.

Since `Register` is a static, parameterless method, implementations currently call into the static `SerializationManager.Register` method to register serialization delegates.

With `SerializationManager` becoming non-static, a change needs to be made here and I see two options:
1. Remove `[RegisterSerializer]` and `Register` altogether and instead rely on `[Serializer(typeof(TargetType))]` attributes like we do in our generated code.
1. Change the signature of the `Register` method so that it takes a parameter of type `SerializationManager` or some purpose-built interface like so:
```C#
public interface ISerializerRegistrar
{
    void Register(
        Type type,
        SerializationManager.DeepCopier copier,
        SerializationManager.Serializer serializer,
        SerializationManager.Deserializer deserializer);
}
```

I'm in favor of the 1st option. What do you think?

**Comment by jason-bragg** [comment]
+1 for option 1.  Seems very straight forward.

My preference here would be for the SerializationManager to be agnostic to how registration occurs.   That is, there can be an assembly processor that finds serializers and registers them with the SerializationManager, a test harness that registers them, some configuration logic that registers them, or any number of other systems that register them, but the SerializationManager is independent of these methods.  All these methods depend on the SerializationManager, but the SerializationManager itself is agnostic.

**Comment by galvesribeiro** [comment]
I'm all for 1 but I also agree that the registration mechanism shouldn't matter for `SerializationManager` as @jason-bragg mentioned.

**Comment by ReubenBond** [comment]
@galvesribeiro that can come later. This effectively removes SerializationManager out of the registration path, so registration can happen however we want.
