### ISSUE TITLE
Removing invalid stream subscriptions

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#2618]
We have cases when a grain subscribed to a stream, then this grain was refactored (the type name was renamed or the grain was removed altogether). Now every time we call `stream.OnNextAsync` we get errors like "Cannot find an implementation class for grain interface 213853254" 

So the question is how to remove those invalid subscriptions? Is there API that could be used for that? I think it is a quite common scenario so I wonder how other people deal with it

**Comment by jason-bragg** [comment]
There is currently no supported programmatic way to remove the subscriptions if the grain type has changed.  :/

Using TypeCodeOverrideAttribute, one should be able to specify the grain type code, so it would be preserved regardless of grain name changes.  Unfortunately, at this point, if this is occurring in production (not caught in test) storage will now have subscriptions using the new grain type code along with the old ones.

The simplest Orleans fix for this would be to make the IPubSubRendezvousGrain interface public, so subscriptions could be managed directly, but we'd need the subscription ID. If that's not being reported in the error then we'd need to add it.

Only code way of doing this I can think of, without modifying Orleans, would be to use reflection to get a grain reference to the IPubSubRendezvousGrain and call it to remove the subscription.  This would be horribly hacky, but might be possible.

**Comment by cata** [comment]
+1 for making the IPubSubRendezvousGrain public.

**Comment by jamescarter-le** [comment]
@jason-bragg, @sergeybykov, @AlexMeakin

We would like to do the work to make `IPubSubRendezvousGrain` public so we can manage Consumers and the count of these. Specifically to know whether to perform work only if there are Consumers of a Stream, (either Client or Grain consumers).

If we were to submit a pull request to this effect would you be receptive in finding resource to help see this over the line into a 1.5.x release?

The public interface to `IPubSubRendezvousGrain` makes extensive use of the `internal` `StreamId`, but could instead be coaxed to use `IStreamIdentity`, what would be your thoughts on this?

**Comment by sergeybykov** [comment]
I think `IStreamPubSub` is a better abstraction to expose, so that `IPubSubRendezvousGrain` is just one of possible implementation of pub-sub. But @jason-bragg and @xiazen may correct me.

**Comment by jamescarter-le** [comment]
Thanks @sergeybykov 

It looks like trying to resolve an IStreamPubSub which is not IAddressable would not work, it could make it IAddressable and refactor IPubSubRendezvousGrain to inherit from it, but it would need a IGrainWithXKey to be found through GrainFactory.

**Comment by jamescarter-le** [comment]
Or are you thinking of exposing IStreamPubSub at the Runtime level?

**Comment by sergeybykov** [comment]
>Or are you thinking of exposing IStreamPubSub at the Runtime level?

That's what I'm thinking, likely via DI. But I'll defer to @jason-bragg and @xiazen, as they know this area better.

**Comment by jamescarter-le** [comment]
Thanks I'll wait for their input.

**Comment by xiazen** [comment]
I think we did the work in 1.5 to exposing part of `IStreamPubSub `'s methods through `IStreamSubscriptionManager`, which includes removing certain subscription. 
As follows is its interface: 
```
    public interface IStreamSubscriptionManager
    {
        Task<StreamSubscription> AddSubscription(string streamProviderName, IStreamIdentity streamId, GrainReference grainRef);
        Task RemoveSubscription(string streamProviderName, IStreamIdentity streamId, Guid subscriptionId);
        Task<IEnumerable<StreamSubscription>> GetSubscriptions(string streamProviderName, IStreamIdentity StreamId);
    }
```
You can access subscription manager through `IStreamSubscriptionManagerAdmin`, like
`this.ServiceProvider.GetService<IStreamSubscriptionManagerAdmin>().GetStreamSubscriptionManager(StreamSubscriptionManagerType.ExplicitSubscribeOnly);`

Does this meets your needs?

**Comment by jamescarter-le** [comment]
Thanks @xiazen - We are just in the process of updating to 1.5 so I've not seen this yet.

Does GetSubscriptions expose Consumers or would it be possible to expose ConsumerCount on this interface?

Thanks

**Comment by xiazen** [comment]
`GetSubscription `currently just wrap on top of `streamPubSub.GetAllSubscriptions(streamId)`, it returns all subscription for one stream. You can see the code as follows,

```
        public Task<IEnumerable<StreamSubscription>> GetSubscriptions(string streamProviderName, IStreamIdentity streamIdentity)
        {
            var streamId = StreamId.GetStreamId(streamIdentity.Guid, streamProviderName, streamIdentity.Namespace);
            return streamPubSub.GetAllSubscriptions(streamId).ContinueWith(subs => subs.Result.AsEnumerable());
        }
```

> Does GetSubscriptions expose Consumers or would it be possible to expose ConsumerCount on this interface?

It exposes subscription count. So if you consumer is 1 to 1 relationship with subscription, then yes. If one consumer have multiple subscription count, then it is not equal.

**Comment by xiazen** [comment]
What's your use case for getting consumer count, instead of subscription count? just curious.

**Comment by jamescarter-le** [comment]
Understood that is great thank you Xiao. No work required on our side once
we finish the migration to 1.5.0!

**Comment by jamescarter-le** [comment]
We have a grain receiving messages that something that would affect its output has changed. We want to react to that by performing a long running CPU and memory intensive task (1 - 30 minutes) to emit this calculation through a Stream. We want to gate this based on Consumer count so that if there is no listeners we avoid performing this task as we may only have a low percent of these Grains having a subscriber at the time, especially as these changes could come in batches to a lot of these Grains.

If you have any suggestions about how Orleans could provide a better way to gate this I would be grateful to receive them.

**Comment by xiazen** [comment]
Ah I see. it is always interesting to know how people use streams for. I think your way works well. Glad I can help. Take care.
