### ISSUE TITLE
Advice on Grain Call latency

### ISSUE THREAD

**Issue by igalmirom** [dotnet/orleans#2624]
I have a setup of a cluster receiving requests to a stateless reentrant grain and it, in turn, sends a request to another statefull grain.

Most of the requests will hit a new grain so Orleans will need to place and activate it.

 I run it on a cluster of 3,  24 cores 2.20GHz dedicated servers at a rate of ~10req/s.

The weird thing is that for ~20% of the calls I see a latency of up-to 200ms for calling the inner grain (avg latency is 30ms).

I set up a server interceptor and measured that the grain call itself is <1ms.
I added a timer around the Activate method and it's ~5ms.
But a timer around the call to the grain shows a median of 30ms.

All the code is async, nothing blocking.
CPU is at around 20%
Network and disk activities are low.
This happens for both inter and intra silo calls.
Tried to raise and lower the size of the cluster (2-6 nodes), no effect.
The latency distribution is the same after restart as after a long run.
More requests (higher rate) show the same results.

I did the same setup in aws: 16 cores,  2.80GHz VMs and there, the latency is negligible: 
50ms for the 99.9%.

I'm running out of ideas for what can cause this.

Any advice or additional test suggestions would be appreciated.

**Comment by sergeybykov** [comment]
Do you send any data in those calls?
Are silos configures with ServerGC?
Can you share the logs?

**Comment by tsibelman** [comment]
@sergeybykov silos are using recommended GC configuration , we pass some amount of data in these calls but it small.  What Orleans or machine metrics would you recommend us to check in order to find a root cause of this issue ?

**Comment by sergeybykov** [comment]
I'm curios about the memory and CPU related statistics - those with the `Runtime.` prefix. Also, if there are any warnings or errors in the logs.

**Comment by igalmirom** [comment]
[log.txt](https://github.com/dotnet/orleans/files/724675/log.txt)

I Attached the file for the log statistics. 
If you need any specific key I can tell you how it changes over time although they pretty much stay constant (the non-accumulating metrics).

The message size is < 1kb
No warning or errors in the logs.

**Comment by sergeybykov** [comment]
The statistics look healthy to me. No warnings in the logs?

>I did the same setup in aws: 16 cores, 2.80GHz VMs and there, the latency is negligible:
50ms for the 99.9%.

Are you saying that in AWS you are not seeing the long tail of latencies, only with on premises servers? Or did I misinterpret what "dedicated servers" mean?

**Comment by igalmirom** [comment]
No warnings in the logs.
You are correct: no latency in aws, only on prem.

**Comment by sergeybykov** [comment]
Hmm, this is weird. I'm out of good ideas. Only hardware issues and software interferences from things like antivirus and corporate management come to mind. But those aren't very likely to be the culprit.

You are running on physical servers, not VMs, right?

**Comment by igalmirom** [comment]
Yes that is correct.

We are trying to run one of the orleans samples on the same setup to see
how it behaves.

**Comment by gabikliot** [comment]
When you say: "I did the same setup in aws", you mean you run Orleans sample in AWS on Windows machines and that it better than Orleans  on Windows machines on prem?

**Comment by gabikliot** [comment]
BTW, the log says you have 6 (Membership.ActiveClusterSize=6) and not 3 silos.

**Comment by igalmirom** [comment]
@gabikliot No I ran our code on aws and there the latency is all but gone.

I said that I experimented with several cluster sizes. The log was taken when the cluster size was six.

We tried to run with just a single silo which dropped the response time in half (25ms median instead of 50ms) but it's still not anywhere near the 5ms median that I see in aws.

**Comment by gabikliot** [comment]
Sorry, I don't understand.
>No I ran our code on aws 
What does that mean? What our code?

**Comment by igalmirom** [comment]
Sorry I'll try to explain:

Our program has an entry grain, let's call it a Service Grain which is labeled Stateless & Reentrant.
It receives requests regarding users and forwards them to a User grain.
Most of the requests are for different users (so the grain for the specific user Id is not active yet).
So Orleans activates the grain, invokes the method on the user grain, it goes back to the service grain and back to the client.

I added logs with timestamps in the following locations:
1. before calling to user grain (inside service grain)
2. onActivate of user grain (inside user grain)
3. In the end of the user grains method (inside user grain)
4. After calling the user grain (inside service grain)

In some requests (not all) I see that a 100ms can pass between logs 1 and 2 
or between logs 3 and 4.
between 2-3 there is no latency other than the cost of loading the state < 5ms.

If I measure the total request time on my on prem setup the median is 40ms with a 99.9% of 200ms
and the same setup on aws yields a median of 4ms with a 99.9% of 50ms.

Is it more clear now?

**Comment by gabikliot** [comment]
Yes, it's clear now, thank you.
Very weird indeed, I agree with Sergey about potential causes.
Can you share the full silo log (at info level) from on prem setup, maybe privately with Sergey and/or me. A lot of times we can find some clue in the log.

**Comment by gabikliot** [comment]
Are the 2 setups use the same membership? Is it possible that in the on prem setup client connects to only one silo while on AWS to all silos?

**Comment by igalmirom** [comment]
It will take some log routing magic on our part but will do :)

The 2 setups use different memberships and the requests are distributed across all silos.
Plus, no single silo is overloaded and all silos are under 20% cpu.

**Comment by gabikliot** [comment]
I definitely see in the log you sent that this silo has 0 clients connected (it never had a single client connect to it). We usually recommend all clients connect to all silos.

**Comment by igalmirom** [comment]
Yes that's a long story.. 
We don't use an Orleans client, we have an httpListener which receives the requests and internally forwards them to the grains...

I bumped the log level to info and see a lot of:
Log code 101033 occurred 190 additional times in the previous 00:01:02.3395980
Log code 101031 occurred 190 additional times in the previous 00:01:02.3395980

**Comment by sergeybykov** [comment]
@igalmirom Is it possible that you generate load differently in the two cases?

101031 and 101033 are related to message forwarding. If concurrent requests for the same grain (user) that's not activated yet arrive to different silos, those silos will independently make placement decisions for new activations. When those activations will be tried to get registered in the grain directory, only one will win the race. The other activations that lost the registration race get removed, and their requests get forwarded to the winner activation. That's part of the process that provides the single activation guarantee. The process involves more work and messaging roundtrips than when a message is delivered to an already created activation. Hence, if the workload, especially synthetic, has a large number of concurrent requests for the same entities, you may see higher latencies for a small percentage of requests that will skew the averages and percentiles.

Just a hypothesis of what could be going on here if concurrency of requests is different between the two setups.

**Comment by igalmirom** [comment]
@sergeybykov It's not a synthetic load. It's a small portion of actual traffic.
Also I see the same info messages in the aws setup as well.

I like your theory. However we do not have concurrent requests for the same user.
We do have consecutive calls for the same user one after the other which can reach a different silo (the calls to the silos are round robin).
Can this also cause the same 101031 and 101033 messages?
Where the grain is already activated in one silo but the other silo is not aware of it yet?

**Comment by sergeybykov** [comment]
>We do have consecutive calls for the same user one after the other which can reach a different silo (the calls to the silos are round robin).
Can this also cause the same 101031 and 101033 messages?
Where the grain is already activated in one silo but the other silo is not aware of it yet?

This is only possible if more than one request arrive to different silos within a window of a few milliseconds, so that both queries into the directory return no existing activation of the target grain. If a request for a grain arrives to any silo after a previous request has been processed, the race will not happen because the directory will return the activation address registered while processing the first request.

**Comment by igalmirom** [comment]
I managed to narrow it down:

I am running an Orleans client against a single Silo, all on the same machine.
The client is configured to local silo to use a loopback address.

If I send a request to the silo every 100ms, the average response time will be 20ms. The metrics within the silo show that it took  4ms.

If I remove the delay and just run it consecutively the average drops to 5ms.

Naturally the same setup on AWS works the same with or without the 100ms delay.

**Comment by tsibelman** [comment]
@sergeybykov 

We created a layer that exposes Orleans based microservices via HttpListener, we receive http calls and forward them into Orleans via internal Orleans client, we were able to achieved this by storing reference to TaskScheduler of Boostraping grain and using it to start calls to Orleans.

It mostly works but looks like this performance issue is what we getting in one enviroment,  so now I thinking it could be caused by the fact that we copied ActivationTaskScheduler instead of OrleansTaskScheduler.

What do you think ?

**Comment by sergeybykov** [comment]
@igalmirom Can you run client and silo on different machines? We've see too many times that benchmarking a distributed system on a single machine is often misleading because client and server inevitably compete for system resources.

@tsibelman So you forward all requests that the HttpListener receives via a single grain context?

**Comment by tsibelman** [comment]
Yes we using ActivationTaskScheduler of bootstrap grain and then forward calls to stateless reentrant grains. Idealy we would like to have something like CallGrain method from GrainController [class ](https://github.com/richorama/orleans/blob/23e5e659cbff39a1692d87cc51c036ee9e99cf09/src/OrleansRuntime/Http/GrainController.cs) so we could pass requests from httplistener to Orleans

**Comment by igalmirom** [comment]
@sergeybykov  We ran the tests where the client is on a different machine but the results are the same.
Remember that we are issuing one request each 100ms so the machine's resources are pretty idle.

We found one bottleneck where in our server grain interceptor we would write to log using async void.

something like:

```C#
async void WriteToLog() 
{
    await _log.writeAsync();
}
```
Changing it to: `_log.writeAsync().Ignore()`
fixed the issue when using Orleans client.
However when we use http client like @tsibelman described, and our implementation is almost exactly like [httpClient ](https://github.com/OrleansContrib/OrleansHttp) from orleansContrib we see the latency comes back.

I want to remind again that on a vm in aws or on a local dev machine no latency is visible.

**Comment by tsibelman** [comment]
I made a private copy of Orleans where Silo properties are public  and copied the code from httpClient
It looks like this taskScheduler is OrleansTaskScheduler take from Silo.

```csharp
            Task task = null;
            var sw = Stopwatch.StartNew();
            await taskScheduler.QueueAction(async () =>
            {
                var sw2 = Stopwatch.StartNew();
                task = (Task)grainMethod.Invoke(grain, grainMethodArguments);
                await task;
                Console.WriteLine("inner " + sw2.ElapsedMilliseconds);
            }, schedulingContext);
            Console.WriteLine("outer "+ sw.ElapsedMilliseconds);
```
Outer measurement is 30-50 ms but inner measurement is  2-5 ms, @sergeybykov why this can happen in your opinion ? We on a physical server with 24 cores and publishing only one request every 100 ms.

**Comment by gabikliot** [comment]
Can u share your silo log beginning, where we can see all silo config properties? Maybe u are misconfiguring the local silo.

**Comment by sergeybykov** [comment]
@igalmirom Can you disable all logging on the silo/grain side for benchmarking? That's another thing we've encountered several times - that a single seemingly innocuous logging statement can derail a benchmark based on what it entails under the covers.

As @gabikliot already mentioned, it would help to see the local silo config, ideally side by side with the AWS config.

@tsibelman Can you share a bigger snippet? I can't seem to find a direct equivalent of your code in https://github.com/OrleansContrib/OrleansHttp/blob/master/OrleansHttp/GrainController.cs.

Also, `Console.WriteLine` bothers me. It may be nothing, but calling it on a hot path may lead to unexpected costs due to locking inside it. Maybe accumulate timing statistics over a number of calls, e.g.  100 or 1000, and output it once.

**Comment by igalmirom** [comment]
@sergeybykov @gabikliot I have attached a small host that recreates the issue and a log of a run on the problematic machine.

Basically the code just send a request to a stateless reentrant grain every 100ms using the TaskScheduler from the Bootstrap.
This mimics the same usage as in Grain Controller:[https://github.com/OrleansContrib/OrleansHttp/blob/master/OrleansHttp/GrainController.cs#L101](https://github.com/OrleansContrib/OrleansHttp/blob/master/OrleansHttp/GrainController.cs#L101)

I added lots of log writes and measures but the issue is reproducible even when all the logs are turned off.

[OrleansTest.zip](https://github.com/dotnet/orleans/files/761644/OrleansTest.zip)
[Host-2017-02-08-18.19.35.106Z.txt](https://github.com/dotnet/orleans/files/761651/Host-2017-02-08-18.19.35.106Z.txt)

**Comment by tsibelman** [comment]
Just want to add that we also tried to use OrleansTaskScheduler  in the same scenario and got same effect

**Comment by tsibelman** [comment]
I copied the minimal code snipet from @igalmirom example 

```csharp
internal class ReproBootstrapProvider : IBootstrapProvider
{
        public Task Init(string name, IProviderRuntime providerRuntime, IProviderConfiguration config)
        {
            Task.Run(async () =>
            {
                var grain = grainFactory.GetGrain<IStatelessWorkerGrain>(0);
                while (true)
                {
                   //-----------Takes 30-50 ms to execute
                    var task = await Task.Factory.StartNew(
                        async () =>
                        {
                            await grain.CallStateFullGrain();
                        }, CancellationToken.None, TaskCreationOptions.None, grainTaskScheduler);

                    await task;
                   ///-------------
                    await Task.Delay(100);
                }
            }).Ignore();

            return Task.FromResult(1);
        }
    }
 }
```

**Comment by tsibelman** [comment]
Thank you for all your support we found the issue, looks like in one of the data centers power option was set to balanced instead of high performance, here is a before and after shot

I don't fully understand why Orleans tcp client was not affected by this in the same way our HTTP client was affected. 

![unnamed](https://cloud.githubusercontent.com/assets/172522/22789040/844baef6-eeea-11e6-8e8f-0e908549c82b.png)

**Comment by gabikliot** [comment]
Orleans client was not affected, or was yes affected? I thought u were saying Orleans was slower.

**Comment by tsibelman** [comment]
When we used orleans client it was working fine

**Comment by sergeybykov** [comment]
Looks like this can be closed now.
