### ISSUE TITLE
Make Membership, Reminders and Statistics providers more configurable

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#2626]
Today when trying to register a Membership, Reminder or Statistics provider, if they are the *default* ones that has on that base enums, we internally register the proper type without much need of configuration. However, if you are using a Custom membership provider you need to provide the Assembly name which contain those types.

```csharp
config.Globals.LivenessType = GlobalConfiguration.LivenessProviderType.AzureTable;
config.Globals.ReminderServiceType = GlobalConfiguration.ReminderServiceProviderType.AzureTable;
```

My proposal is to remove all those enums and make all providers to be registered by a new method to be introduced for each provider type just like we do with `RegisterStorageProvider<T>()`:

```csharp
RegisterMembershipProvider<T>(string name, Action<T> factory);
RegisterReminderService<T>(string name, Action<T> factory);
RegisterClientStatisticsProvider<T>(string name, Action<T> factory);
RegisterSiloStatisticsProvider<T>(string name, Action<T> factory);
```

That would allow more configuration at the provider level. For example, today we can't change the MBR table name for example. Other provider/level configs would be useful there.

That is a breaking change, so it would probably be moved to 2.0. 

I'll tackle that if there is no objections.

**Comment by ReubenBond** [comment]
@galvesribeiro Registering those types via the DI container works today and will override the config. We can add helper methods like `config.UseMembership<T>()` with a few instance/factory overloads.

Of course, clients do not have DI support yet.

I agree about removing the enums.

**Comment by galvesribeiro** [comment]
@ReubenBond oh! great! So I can ignore all those configs and register it with DI. Great! Wasn't aware of it. However, the DI is configures thru `config.UseStartup<T>()` and there is no way to pass in parameters to the underlying types (for example by receiving the connection string from command line parameters - useful in Containers).

The overloads would make people live easier as well.

In all cases, we need to change the providers so we can pass parameters on its Ctors like name, table name, connection string, etc...

**Comment by ReubenBond** [comment]
> However, the DI is configures thru config.UseStartup<T>() and there is no way to pass in parameters to the underlying types (for example by receiving the connection string from command line parameters - useful in Containers).

This really needs to be fixed, I very much dislike the current experience

**Comment by galvesribeiro** [comment]
So, can we create an action plan here? 

This is really annoying. Make people to have multiple storage accounts is something really bad. Besides, there are tons of configurations on providers that today we have to encode/hack in a single `DataConnectionString` string which makes things even worse...

**Comment by ReubenBond** [comment]
> So, can we create an action plan here?

Yes, perhaps we should plan/impl the `SiloBuilder` idea

**Comment by galvesribeiro** [comment]
hummm yeah, we should... 

I'll think about it and come up with a proposal in a separated issue for the SiloBuilder and link this issue.

Thanks for now for the feedback.

**Comment by attilah** [comment]
For this we need the revamped configuration, which will automagically enable similar scenarios on other parts of the system. *Builders which ones building Configurations :D

**Comment by laredoza** [comment]
Would this include this include the storage provider?

**Comment by sergeybykov** [comment]
>Would this include the storage provider?

Yes, `SiloBuilder` will include storage providers, too.

**Comment by laredoza** [comment]
Thanks @sergeybykov

**Comment by sergeybykov** [comment]
I believe this is fully addressed now. Please reopen if you feel otherwise.
