### ISSUE TITLE
RemoteDeployment subfolder missing from SDK

### ISSUE THREAD

**Issue by davidpodhola** [dotnet/orleans#263]
Reading http://dotnet.github.io/orleans/Step-by-step-Tutorials/On-Premise-Deployment I get to the sentence
> The SDK installation folder has a sub-folder called ‘RemoteDeployment’ where everything we need can be found

The folder is not there, although it is present in GitHub https://github.com/dotnet/orleans/tree/master/misc/scripts/RemoteDeployment

I think either the docs should be changed or the SDK should include this folder

**Comment by sergeybykov** [comment]
Thanks! Fixed.
