### ISSUE TITLE
Autofac dependency injection for orleans unit tests

### ISSUE THREAD

**Issue by jake-bauer** [dotnet/orleans#2635]
I am attempting to use AutoMoq as a way to inject dependencies into a unit test for Orleans. This is the setup I have currently.

namespace UnitTests.Grains
{
    [TestClass]
    public class UserMappingTest : TestingSiloHost
{
        [ClassCleanup]
        public static void ClassCleanup()
        {
            StopAllSilosIfRunning();
        }

        [TestMethod]
        public async Task TestingSiloIsAlive()
        {
            //Backbone
            var guid = Guid.NewGuid();

            //App Settings
            var mockAppSettings = new Mock<IApplicationSettings>();
            mockAppSettings.Setup(m => m.UserMappingRefreshTime).Returns(TimeSpan.Parse("00:02:00"));

            //Logger
            var mockLogger = new Mock<ILogger>();

            //AuthenticationProvider
            var userMapping = new List<UserMapping>();
            userMapping.Add(new UserMapping()
            {
                UserNumber = "123456",
                UserName = "TEST_USER"
            });
            var mockAuthenticationProvider = new Mock<IAuthenticationProvider>();
            mockAuthenticationProvider.Setup(m => m.GetUsers(guid)).ReturnsAsync(userMapping.ToArray());

            using (var mock = AutoMock.GetLoose())
            {
                
                mock.Provide<IApplicationSettings>(mockAppSettings.Object);
                mock.Provide<ILogger>(mockLogger.Object);
                mock.Provide<IAuthenticationProvider>(mockAuthenticationProvider.Object);
                Assert.IsTrue(mock.VerifyAll);
                IUserMappingGrain userGrain = GrainFactory.GetGrain<IUserMappingGrain>(0);
                var result = await userGrain.GetDriverNumberFromUserName("TEST_USER");
            }

        }

    }
}

The error that is being generated is 
Test Name:	TestingSiloIsAlive
Test Outcome:	Failed
Result Message:	
Unable to create instance of class UnitTests.Grains.UserMappingTest. Error: System.Exception: Exception during test initialization: 
Exc level 0: System.Runtime.Serialization.SerializationException: Type 'Autofac.Core.Registration.ComponentNotRegisteredException' in assembly 'Autofac, Version=4.2.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' is not marked as serializable.
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Orleans.TestingHost.TestingSiloHost.LoadSiloInNewAppDomain(String siloName, SiloType type, ClusterConfiguration config, AppDomain& appDomain)
   at Orleans.TestingHost.TestingSiloHost.StartOrleansSilo(TestingSiloHost host, SiloType type, TestingSiloOptions options, Int32 instanceCount, AppDomain shared)
   at Orleans.TestingHost.TestingSiloHost.<InitializeAsync>d__72.MoveNext().
Result StandardOutput:	
Did not find the OrleansTestSecrets.json file or it was empty. Using Default Storage Data Connection String instead.
----------------------------- STARTING NEW UNIT TEST SILO HOST: UnitTests.Grains.UserMappingTest -------------------------------------

Debug Trace:
Did not find the OrleansTestSecrets.json file or it was empty. Using Default Storage Data Connection String instead.

I'm not exactly sure where the configuration issue is and so I was looking for a solid example of how to inject mock back configurations into Orleans unit tests.

**Comment by ReubenBond** [comment]
It looks like there's a `ComponentNotRegisteredException` during initialization and that cannot be thrown across AppDomains because it's not marked as `[Serializable]`. What's missing is how you're configuring Orleans to use Autofac

**Comment by jake-bauer** [comment]
This is the Configuration for the service provider

       public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            var builder = new ContainerBuilder();

            Log.Logger = CreateLogger();
            builder.RegisterLogger(Log.Logger, true);

            var container = builder.Build();
            return container.Resolve<IServiceProvider>();
        }



I have attached my config file as a text document
[config.txt](https://github.com/dotnet/orleans/files/730938/config.txt)

This is based on our production startup file which is currently working.

**Comment by ReubenBond** [comment]
Thanks, @jake-bauer, how about the grain's dependencies, since that's what Autofac is complaining about

**Comment by jake-bauer** [comment]
I was actually trying to create the dependencies in the test itself. If you look at my initial post the code includes the registration within the test itself based on autofacs automoq examples. I have a feeling this is incorrect but I am not sure where to place them. Do you actually need to simply need to register things explicitly with the container in the configure services method of my startup class?

**Comment by jake-bauer** [comment]
I have solved the issue and am working on a write up with better documentation on how to do it, the short of it is you need to explicitly register your test modules or orleans will fail to find the grain dependencies. Will update this thread again when that is done.

**Comment by ReubenBond** [comment]
Thanks, @jake-bauer. In the code snippet above, dependencies are being registered in the test method but not in the system under test. Note that `GrainFactory.GetGrain<T>(...)` returns a *reference* to a grain, but does not synchronously construct that grain in the silo. Construction happens in the silo when the grain is activated (which happens when it's first messaged). Therefore, services must be registered in the silo, not the client.
