### ISSUE TITLE
Log / Trace File does not rollover automatically

### ISSUE THREAD

**Issue by sarmut** [dotnet/orleans#2650]
The trace file name & path is configured thru <Tracing..> element in the xml or corresponding property in the code.  But there is no way to specify automatic rollovers of this trace/log file.  When a silo runs for multiple days/weeks without restart, the log file grew very huge and no popular text editors can open the file.  Need this automatic rollovers in a production environment, so we can get separate log files for each hour or day, depending on the configuration.

**Comment by erictuvesson** [comment]
@sergeybykov This seems to be an issue from Orleans 1.x, is that still relevant?

**Comment by sergeybykov** [comment]
Thank you, @erictuvesson. This is obsolete indeed. Closing.
