### ISSUE TITLE
[Question] Why is a new SchedulingContext created for each grain call?

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#2677]
This question has been on the back of my mind for a while now: Why is a new `SchedulingContext` created for each grain call?

Could we move the `ISchedulingContext` implementation to `ActivationData` either by making that class implement it itself or by including it as a property? `SystemTarget` does something like this. The current implementation seems a bit allocation-heavy.

Perhaps @gabikliot or @sergeybykov or someone else can shed some light?

**Comment by gabikliot** [comment]
There is no reason, as far as I remember. You can mimic the way it is done in system targets and store it inside the activation data. It is definitely bound to the life of the activation data.

**Comment by ReubenBond** [comment]
Thanks, @gabikliot. I've implemented this in #2692
