### ISSUE TITLE
What is the cleanest way to start multiple silos in process (and toggle them)?

### ISSUE THREAD

**Issue by veikkoeeva** [dotnet/orleans#269]
This may be a dumb question, but what would be the cleanest way to have a command line application that starts a variable number of silos, at least two, that can then also close and restart them upon request?

The reason I ask is that I'd like to do exactly that, have a command line application that runs from ``bin\<config>`` and I can toggle the silos up and down at will. It'd be nice if the same code would also in testing project.

I see [HelloWorld example](https://github.com/dotnet/orleans/blob/master/Samples/HelloWorld/HelloWorld/Program.cs) has an example, then also the [testing project has one way](https://github.com/dotnet/orleans/blob/master/src/Tester/UnitTestSiloHost.cs#L536).

**Comment by sergeybykov** [comment]
Are you allergic to feeding it a config file with a list of silos to start, somewhat along the lines of how we did remote deployment - https://github.com/dotnet/orleans/blob/master/misc/scripts/RemoteDeployment/Deployment.xml? I know some people are strongly against XML in general, but it doesn't have to be XML, of course.

I think once you need to pass different configurations for different silos, you quickly overstay your welcome with command line arguments. That's what we reached with ClientGenerator.exe at some point, and had to move parameters to an args file.

**Comment by veikkoeeva** [comment]
@sergeybykov It's just that I didn't find the material whilst searching. To my defense, I'm incredible occupied at the moment, but I don't want to postpone *really* learning this stuff till summer. Hmm, continuing in this same vein, how should I use this file? I'm not allergic to XML, I'm just thinking the next two hours tomorrow &ndash; and I plan to work bring #255 forwards too. I agree with the parameters thing too. One "easy" way I see is that just whip up a .NET class and serialize it with a JSON or a XML serializer and then read the file back with a serializer and pass the object to a silo construction thingy. Then the command line could provide a pointer to the file or ``stdin`` (i.e. piping).

Continuing about my business and perhaps misplaced priorities, this is somewhat hilarous in that I have a somewhat complex, albeit small, instance running in Azure without that much of a thinking. Perhaps a testament of the simplicity of Orleans? In any event, currently I have the gear configured to running in Azure and I run things in emulator, but it feels like a lot of *bleh* now to always start the compute emulator. What I'd like to have is a sufficiently easy method to configure a variable number of silos and then preferably stop and start new ones and a nice plus would be to be able to use the same code in a test setting too. Additional pondering is how to trace the grain graph and trace the messages through it, but they are future questions and I feel in part related to the SQL question (I'd like to enable analysis on these things).

**Comment by sergeybykov** [comment]
If you only have two hours, wouldn't the fastest way be to wrap the Tester project in a console app? If you need this for testing, you can easily write tests that start/stop silos along with running client test code. Or do you have a different purpose for such a local deployment in mind?

**Comment by veikkoeeva** [comment]
@sergeybykov I think you have answered all I want to know and a more already. What would be the appropriate section to expand in Wiki with regard running silos? Maybe candinates would be [Running the Application](http://dotnet.github.io/orleans/Getting-Started-With-Orleans/Running-the-Application) and [Silos](http://dotnet.github.io/orleans/Getting-Started-With-Orleans/Silos).

Maybe one way putting this is that I was thinking to do something like [Orleankka here](https://github.com/yevhen/Orleankka/blob/master/Source/Demo.App/Program.cs), but without actually taking the code. That is, having less features and being more lightweight and expand as I go. In anticipation if something similar lands to Orleans project around, say, summer. If not, I can expand the initial code, but I wouldn't want to down completely wrong path and hence thinking if there is something "simple already". A balancing act in using time to do business features and building technical ability (or reducing technical debt).

**Comment by veikkoeeva** [comment]
I think we can close this. I went with just loading the ``OrleansRuntime`` as the other classes look like being wrappers with various degrees of automation and it didn't looks like too complicated to go straight to the heart of matters.

What follows is very rudimentary code (that came in about 1.5 hours after reading the Orleans bits and fudging with my n00b F#, just to mention with regards the previous), but I provide it here. It might be of interest to someone. There are various ways to improve this, some are mentioned at [Understanding Application Domains](http://blogs.msdn.com/b/cclayton/archive/2013/05/21/understanding-application-domains.aspx) by **Chris Clayton**, taking cues from the testing project about shutting down silos gracefully and then better F#.

```F#
open System
open Orleans.Runtime
open System.Globalization
open System.Reflection
open Orleans.Runtime.Configuration
open Orleans.Runtime.Host
open Orleans
open X.GrainInterfaces


 type IDelegateEvent<'d when 'd :> Delegate> with
    member this.Subscribe handler =
        do this.AddHandler(handler)
        { new IDisposable with 
            member x.Dispose() =
                this.RemoveHandler(handler) }

[<EntryPoint>]
let main argv =         
               
    let domainErrorHandler (sender:obj) (args:UnhandledExceptionEventArgs) =
        let problemDomain = sender :?> AppDomain
        printfn "Unhandled exception in app domain: %s" problemDomain.FriendlyName
       
    let currentAppDomainSetup() =
        let currentAppDomain = AppDomain.CurrentDomain            
        new AppDomainSetup(
            ApplicationBase = Environment.CurrentDirectory,
            ConfigurationFile = currentAppDomain.SetupInformation.ConfigurationFile,
            ShadowCopyFiles = currentAppDomain.SetupInformation.ShadowCopyFiles,
            ShadowCopyDirectories = currentAppDomain.SetupInformation.ShadowCopyDirectories,
            CachePath = currentAppDomain.SetupInformation.CachePath
        )

    let fileConfig() =
        let config = new ClusterConfiguration()
        config.LoadFromFile("DeveloperSiloHostsConfiguration.xml");
        config    

    let loadSiloInNewAppDomain (siloName:string) (siloType:Orleans.Runtime.Silo.SiloType) (configProvider: unit -> ClusterConfiguration) (appDomainSetupProvider: unit -> AppDomainSetup) =
        let appDomain = AppDomain.CreateDomain(siloName, null, appDomainSetupProvider())
        let args:obj[] = [|siloName; siloType; configProvider()|]        
        let silo = appDomain.CreateInstanceAndUnwrap("OrleansRuntime", typeof<Silo>.FullName, false, BindingFlags.Default, null, args, CultureInfo.CurrentCulture, Array.empty) :?> Silo
                
        (silo, appDomain)
    
    let unloadAppDomain (appDomain:AppDomain) = AppDomain.Unload(appDomain)

    let unhandledExceptionHandler = AppDomain.CurrentDomain.UnhandledException.Subscribe domainErrorHandler               
    let (silo, appDomain) = loadSiloInNewAppDomain "primary-test" Orleans.Runtime.Silo.SiloType.Primary fileConfig currentAppDomainSetup
    silo.Start()
    
    GrainClient.Initialize("DeveloperClientConfiguration.xml")
    let helloer = HelloFactory.GetGrain(Guid.Empty);
    Console.WriteLine("\n\n{0}\n\n", helloer.SayHello("Good morning!").Result);
        
    Console.ReadLine() |> ignore    
    AppDomain.Unload appDomain
    unhandledExceptionHandler.Dispose()

    0


```

**Comment by AnaitBI** [comment]
@sergeybykov
Please help,
VS 2017, ASP.NET Core, Orleans 2.0
In multiple silos, I open for each silo a new project?
image
![image](https://user-images.githubusercontent.com/39155784/42205256-978836ee-7eac-11e8-81d6-60878e885dfd.png)

in every one, I mention the addresses and ports.
what is the better way to do it instead:

var siloBuilder = new SiloHostBuilder()
.UseLocalhostClustering(siloPort, gatewayPort, primarySiloEndpoint).Build();

I don't want to use the UseLocalhostClustering, what is the alternative?

**Comment by RainingNight** [comment]
@AnaitBI  any solution?

**Comment by AnaitBI** [comment]
Yes, I used Consul in my case, but you can use any other membership table so the Silos and the Client will recognize each other.

https://dotnet.github.io/orleans/1.5/Documentation/Runtime-Implementation-Details/Consul-Deployment.html

**Comment by RainingNight** [comment]
@AnaitBI Thanks, but I don't know how to config in 2.0.

**Comment by RainingNight** [comment]
I'm use single Client connect multipul diffence grains SiloHost, throw "Cannot find an implementation class for grain interface xxx", then wait 30s it's ok! Why?
