### ISSUE TITLE
Why was the project named Orleans

### ISSUE THREAD

**Issue by danielkrainas** [dotnet/orleans#2702]
Not sure if this is the best place to ask this but I was just curious of the name choice. Was it just related to how projects within Microsoft are codenamed or was there a specific reasoning behind Orleans?

**Comment by alexanderdevoid** [comment]
I'm gonna go out on a limb here and say it has something to do with this song ;)

https://www.youtube.com/watch?v=GO1U-V4RmOQ

**Comment by gabikliot** [comment]
We wanted to save the world from poorly built distributed services, just like Janna D'ark saved Orleans.

**Comment by dVakulen** [comment]
@gabikliot Then why didn't you named it "Janna D'ark"?

**Comment by alexanderdevoid** [comment]
@danielkrainas I thought Sergey would find it funny. Oh well... :D

**Comment by gabikliot** [comment]
@dVakulen, liability.

**Comment by jason-bragg** [comment]
I found it funny, but I don't speak .. don't even know the language .. , so I don't think I should count :)

**Comment by danielkrainas** [comment]
I would have never guessed that, thanks for the insight!

**Comment by ReubenBond** [comment]
>We wanted to save the world from poorly built distributed services, just like Janna d'Ark saved Orleans.

I had no idea that's where the name came from, @gabikliot. I recall that the original app icon was the New Orleans Mardi Gras flag and so I assumed it was named after New Orleans
![image](https://cloud.githubusercontent.com/assets/203839/22807689/5cea60ae-ef7c-11e6-8ac1-e577c16a532d.png)

I like the Joan of Arc inspiration

**Comment by sergeybykov** [comment]
The general rule for project codenames here is to use geographic names because they aren't trademark-able. "Orleans" was chosen I believe by Jim Larus and Galen Hunt before the project started in earnest.
