### ISSUE TITLE
Remove Code Generation for C# Serializers

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#2704]
Currently we have two distinct serializers which generate near-identical code:
* C# Serializers which are generated at build-time or run-time
* IL Serializers which are generated at run-time and are currently only used as a 'fallback' serializer

This issue is to gather feedback & potentially track the removal of the C# serializers.

Reasons to **remove** the C# serializers:
* They require generating a large amount of code
* They cannot access `readonly` members (eg, get-only properties) or inaccessible types without the help of IL code (lazily generated at runtime)
* Because of their restrictions, deep accessibility checks have to be performed before generating them. This significantly slows code generation times and requires complex logic.
* It is a maintenance burden

Reasons to **keep** the C# serializers:
* Since the IL-based serializer does not generate exactly identical code (it has some additional optimizations), removing them would break compatibility.
* Some users may want to inspect the generated code and commit it into their version control system.

I would argue that we should break compatibility in order to also add version-tolerant serialization, that most serializers do not generate readable code, and that serializer generation is deterministic w.r.t the version of Orleans and the type which the serializer is being generated for. So version control really doesn't add anything.

What are people's thoughts? There were positive responses in [Gitter when I mentioned this proposal](https://gitter.im/dotnet/orleans?at=589b8ceb567b0fc8138ccd81), citing startup speed issues and package sizes.

**Comment by galvesribeiro** [comment]
Just one question:

>C# Serializers which are generated at build-time or run-time
IL Serializers which are generated at run-time and are currently only used as a 'fallback' serializer

The way you mention here, means that there will be only run-time codegen if we remove the C# serializers... Is that correct?

**Comment by galvesribeiro** [comment]
Right. But to have the startup and codegen times improved as @yevhen mentioned, I guess you need to revamp the assembly loading and make it imperative in sense that user must say exactly which assemblies code generation should be applied to.

Besides that, what would happen with `Orleans.dll` which requires build-time codegen? Will it use the runtime one?

**Comment by ReubenBond** [comment]
@galvesribeiro we would skip the costly steps required for the serialization generation part of that codegen process - which from what I recall when optimizing it (yonks ago) easily dominated the total cost. We can also avoid assemblies which cannot possibly have grains (don't reference Orleans.dll) and hence avoid interrogating every type

**Comment by amccool** [comment]
@ReubenBond how can I try out using only the IL serializers?  We are struggling with build times and load times in 1.3.1.   Are we talking a nuget upgrade to a pre-release and a configuration change, or something more substantial?

**Comment by ReubenBond** [comment]
Apologies for the slow response, @amccool. See the section on Fallback Serialization in the Serialization doc: http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Serialization.html

1.4.0 has just been pushed to NuGet, and that will be required to use the ILBasedSerializer

**Comment by ReubenBond** [comment]
Closing for now. We can discuss this further down the track when we have a full replacement
