### ISSUE TITLE
Adjusting OrleansTaskScheduler.TurnWarningLengthThreshold

### ISSUE THREAD

**Issue by jake-bauer** [dotnet/orleans#2722]
I was wondering if it is possible to adjust the OrleansTaskScheduler.TurnWarningLengthThreshold to be longer than the standardized .2 seconds.

**Comment by dVakulen** [comment]
@jake-bauer  Yes, it is possible: https://github.com/dotnet/orleans/blame/0f4ba048a7bf31a7de99a4ae4c52cd59a33db7b0/src/Orleans/Configuration/OrleansConfiguration.xsd#L1085

**Comment by jake-bauer** [comment]
Thank you very much
