### ISSUE TITLE
Rename or remove DuplicateActivationException to prevent confusion 

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#2733]
`DuplicateActivationException` doesn't mean that a duplicate activation has been created. It is just a means to resolve a race between two or more silos trying concurrently to register activations for the same grain. However, the very name of the exception class and the message of it misleads people to think that they get duplicate activations.

I suggest we rename the exception class to prevent this confusion from happening.

`RegistrationRaceException`? `ActivationAlreadyRegisteredException`? `ExistingActivationException`?

**Comment by attilah** [comment]
This can be a huge breaking change for the ones who catching this, right? Can't we fix just the message part more easily? or Derive the new exception from ```DuplicateActivationException``` to support backward compat?

**Comment by sergeybykov** [comment]
It is handled 100% internally. Nobody can catch it today in the app code I believe.

**Comment by attilah** [comment]
Ah so. ;-)

**Comment by gabikliot** [comment]
Or return a value instead of an exception. I think someone suggested that in the past.
But also OK with any renaming you pick.

**Comment by ReubenBond** [comment]
Returning a well-typed value is my preference. Otherwise, I prefer `ExistingActivationException`.

**Comment by chris-eaton** [comment]
Just a thought from an outside observer... Should it even be an exception? If this is being thrown all the time (which it is) then surely its expected (and thus not exceptional) to find existing activations? When things go wrong in Orleans I found it very useful turning on all exceptions and this exception caused some confusion to me.

**Comment by sergeybykov** [comment]
@chris-eaton You are correct. It shouldn't have been an exception in the first place. Somehow it evolve that way bad in the days. That's the point @gabikliot also raised above:
>Or return a value instead of an exception.
