### ISSUE TITLE
Grain execution pipelining

### ISSUE THREAD

**Issue by Scottlr** [dotnet/orleans#2740]
Is there a way to always have x amount of invocations executing on other grains? So for instance, if i had 1 grain invoking into 1,000 other grains. Instead of taking x amount of grains, invoke, wait till the batch is done then move onto the next batch, I could always have say 20 grains being invoked/executing?

In my particular case, one grain might take a few milliseconds, whereas another could take a couple of seconds - the whole batch is held up until that longest running grain is finished.

Is this currently possible? or is there a cleaner way of achieving this?

**Comment by sergeybykov** [comment]
Would a simple fan-out work where `grain` is an array or collection of grains to invoke in parallel?

```csharp
List<Task> tasks = new List<Task>();
foreach (var grain in grains)
   tasks.Add(grain.Foo(args));

await Task.WhenAll(tasks);
```

**Comment by Scottlr** [comment]
That's what we're doing currently, but that problem is that one grain might take a long period of time and the majority take barely any time at all. 
If I take one single batch of 20 from 1000 grains to invoke, and 19 of them take 1 second, and one takes 10 seconds, that whole batch will take 10 seconds to complete, holding up time to start invoking on the next batch.

**Comment by sergeybykov** [comment]
I see. You could use `WhenAny` instead of `WhenAll`, so that you are immediately aware of a free slot (grain).

I'm not sure if `AsyncBatchedContinuationQueue` will help here. Maybe you can twist it to do what you need .

**Comment by Scottlr** [comment]
Thanks, looks promising - I'll try it out and reply back if it's working as I hoped 👍

**Comment by Scottlr** [comment]
Happy with Task.WhenAny, thanks!
