### ISSUE TITLE
Serializing State classes with null grain references fail in 1.4

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [dotnet/orleans#2751]
As @ReubenBond  and I discussed when I want to serialize a State using WriteStateAsync, if the state class contains a reference to a grain interface say `IPlayer` which was a `GrainWithStringKey` , the serializer (the generated code) throws an exception `ArgumentNullException` when calling `AsReference`

The test failed on a relatively lohng running project which was ok on previous Orleans versions. I can post more info if needed

**Comment by ashkan-saeedi-mazdeh** [comment]
@sergeybykov  I rolled back to 1.3.1 but isn't this important enough to trigger a 1.4.x ?

**Comment by ReubenBond** [comment]
This is fixed in #2756, but I agree that we should consider 1.4.1 given this and the DI issue which was also fixed.

**Comment by sergeybykov** [comment]
@ashkan-saeedi-mazdeh Yes, we'll include the fix in 1.4.1.
