### ISSUE TITLE
Request for Location Aware Grain Placement – Grain placement strategy

### ISSUE THREAD

**Issue by sarmut** [dotnet/orleans#2764]
**Goal**: Add an additional placement strategy called LocationAwarePlacement where the activation of the grain type should be placed subject to a given list of node locations inside a silo.

**Motivation**: In our system, we have a collection of files distributed across several servers. Each file is replicated in 3 different servers for availability.  Orleans silo is running in the same cluster.  For any kind of operations that involve processing the file, it makes sense to activate a grain that processes a particular file on the same server where it is being held to provide data-compute locality. 

**Suggested Path**: When calling GetGrain<>(), inject the desired silo locations for the grain activation.  Orleans can pick the silo from this given list.  If none of the desired locations are not possible due to heavy load, it can throw an exception.

This approach does not require changing the existing PlacementStrategy and PlacementDirector interfaces. However, we need to turn the two interfaces from internal to public. 

**Challenges**:  Orleans placement related classes are marked ‘internal’.  This needs to open for injection from outside.

**Sample Solution:**

A sample solution could encode the file identifier as part of the grain identifier so that when asked for an activation location, the placement director could do the following:

1.	Get the file identifier from the grain identifier
2.	Retrieve the replica locations for the file
3.	Choose the activation locations based on the replica locations

The director prefers to activate the grain on the same machine as one of the replica, but may choose another machine when the constraint cannot be satisfied (e.g., workloads).

**Related Threads:**

- https://github.com/dotnet/orleans/issues/96 
- https://github.com/dotnet/orleans/issues/1123 
- https://github.com/dotnet/orleans/issues/2345

**Comment by sergeybykov** [comment]
>Suggested Path: When calling GetGrain<>(), inject the desired silo locations for the grain activation.

`GetGrain()` doesn't perform activation placement. It happens upon a first call to the target grain.

It seems to me this requires support for custom placement strategy & director. Internally, the director will pick a target silos for each new activation. The question I have here is if a static configuration (supplied at silo startup) will be enough for the custom placement director. Or if it'll need updates about location of the resources at runtime. The former, obviously, is much simpler.

**Comment by rapoth** [comment]
Thanks @sergeybykov.

While I agree static configuration for the director is a bit easy, my impression is that in our current situation, there are several reasons why a static configuration might not work well:

- Continuously arriving files are distributed and replicated across servers active at that point in time
- If a server is getting full or having any health issues, files could be moved around
- Servers are assumed to fail randomly so the list of active servers is a function of time

Thanks again!

+ @kaizeng, @luomai and @anjaneya17

**Comment by sergeybykov** [comment]
Support for custom placement strategies/directors was added in #2932. You can use https://github.com/dotnet/orleans/blob/master/test/TestGrainInterfaces/CustomPlacement.cs as an example until the docs are added.

**Comment by kai-zeng** [comment]
Thanks @sergeybykov !
We will try it immediately and get back.

**Comment by enewnham** [comment]
Thanks @sergeybykov !
The example provided was clear, and our implementation works a treat.

The one gotcha was I didn't understand how PlacementAttribute as the base class worked, but I think it makes sense now, I would recommend emphasizing this in the docs. However it is a slick implementation!

**Comment by sergeybykov** [comment]
Thank you, @enewnham, for confirming! We definitely need to document the feature for 1.5.0 final.

**Comment by cmeyertons** [comment]
@sergeybykov can we get an updated link?

Interested in implementing a custom grain placement strategy and having some example to go off of would be fantastic.
