### ISSUE TITLE
How to configure Orleans Client to monitor multiple standalone silos

### ISSUE THREAD

**Issue by sbrohi15** [dotnet/orleans#2775]
Hi,

I have a use case in which I need to run 2 or more "standalone" silos with one or more Orleans clients which can identify any one of the standalone silos. A standalone silo here would be an Orleans host which uses a single membership database, resulting in at most, a single entry in the OrleansMembershipTable. Each of my virtual machines runs both the Orleans host and client as windows services. I use one SQL Server instance to host all of my Orleans databases (2) for all of my standalone silos (2).

While I do not want any of the silos to know about each other and thus run independently of one another, I want my Orleans clients to be able to identify all of these silos, even though they are using separate Orleans databases. 

What should I do to accomplish this? Can this be done via a configuration change to **ClientConfiguration.xml** and/or non-invasive code changes?

I am currently running Orleans 1.0.10, but I plan to upgrade to version 1.3.1 soon.

Thank you,

Shazad Brohi

**Comment by sergeybykov** [comment]
At the moment, client is static, and hence can only connect to a single cluster (standalone silos in your case). To make you app talk to more than one cluster at the same time, you need to initialize clients for those cluster in different app domains.

We are almost at the point of making client non-static, which will allow among other things having multiple clients connected to different clusters in a single app domains. That change is very likely to ship in 1.5.0.

**Comment by sbrohi15** [comment]
@sergeybykov Can you tell me what I have to do to set up clients in different app domains? And by app domains, what would you specifically be referring to?

**Comment by sergeybykov** [comment]
Take a look at https://github.com/dotnet/orleans/blob/master/test/TesterInternal/GeoClusterTests/TestingClusterHost.cs#L357 as an example. It is more involved than you need, but the basic mechanism is the same.

**Comment by sbrohi15** [comment]
@sergeybykov Thanks, I will look into it.

 Additionally, is it true that there is a version of Orleans that supports running two different versions of the silos in the same cluster to resolve deployment issues between two different versions?

**Comment by sergeybykov** [comment]
If you are referring to the support for heterogeneous silos, than yes, it was added in 1.4 - http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Heterogeneous-Silos.html.

**Comment by sbrohi15** [comment]
@sergeybykov Would it also be possible to use the Fixed Gateway configuration for the client to accomplish this? https://dotnet.github.io/orleans/Documentation/Orleans-Configuration-Guide/Client-Configuration.html

**Comment by sergeybykov** [comment]
No, it's not the same thing. A client can only connect to a single cluster, even if via multiple gateways.

**Comment by AnaitBI** [comment]
@sergeybykov 
Please help,
VS 2017, ASP.NET Core, Orleans 2.0
In multiple silos, I open for each silo a new project?
![image](https://user-images.githubusercontent.com/39155784/42204852-8170527a-7eab-11e8-9491-12cb980d3d40.png)
in every one, I mention the addresses and ports.
what is the better way to do it instead:
            
var siloBuilder = new SiloHostBuilder()
                .UseLocalhostClustering(siloPort, gatewayPort, primarySiloEndpoint).Build();

I don't want to use the UseLocalhostClustering, what is the alternative?

**Comment by AnaitBI** [comment]
@sergeybykov

Please help,
VS 2017, ASP.NET Core, Orleans 2.0
multiple silos in a cluster with a client

what is the better way to do it instead:
var gateways = new int[] { 30001, 30002, 30003 };
var client = new ClientBuilder().UseLocalhostClustering(gateways).Build();

I don't want to use the UseLocalhostClustering, what is the alternative?

**Comment by AnaitBI** [comment]
Yes, I used Consul in my case, but you can use any other membership table so the Silos and the Client will recognize each other.

https://dotnet.github.io/orleans/1.5/Documentation/Runtime-Implementation-Details/Consul-Deployment.html

**Comment by HassanHashemi** [comment]
@AnaitBI I guess you mean `Multiple nodes in a cluster` .
Take a look at other Cluster Membership provider, The easiest one is `AdoNetClustering`.

**Comment by AnaitBI** [comment]
@HassanHashemi 
Can you please send me a link of an example with 'AdoNetClustering'

**Comment by HassanHashemi** [comment]
@AnaitBI Here it is:
https://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/configuring_ADO.NET_providers.html

**Comment by AnaitBI** [comment]
@HassanHashemi 
Thanks,
Is it enough to use only the siloHostBuilder.UseAdoNetClustering()
Why do we need the other two? (UseAdoNetReminderService, AddAdoNetGrainStorage)
what is the meaning of each one?

Thanks,

**Comment by HassanHashemi** [comment]
AnaitBI They cover other areas, see:

https://dotnet.github.io/orleans/1.5/Documentation/Core-Features/Timers-and-Reminders.html

**Comment by RainingNight** [comment]
@HassanHashemi I'm use single Client connect multipul diffence grains SiloHost, throw "Cannot find an implementation class for grain interface xxx", then wait 30s it's ok! Ask, thanks!

**Comment by sillyousu** [comment]
>@HassanHashemi I'm use single Client connect multipul diffence grains SiloHost, throw "Cannot find an implementation class for grain interface xxx", then wait 30s it's ok! Ask, thanks!

Do you mean having a single client connecting to multiple silo cluster?
You should use different client instance for each cluster afaik.

**Comment by RainingNight** [comment]
@sillyousu Each micro-service corresponds to a silohost, then deploy in one cluster.

**Comment by sergeybykov** [comment]
@RainingNight What version are you using?
Are you running a single cluster of silos with multiple grain assemblies or multiple clusters of silos, each with a different set of grain assemblies?

**Comment by RainingNight** [comment]
@sergeybykov Yes, multiple different grain assemblie silos running a single cluster , version:2.1.2.

**Comment by sergeybykov** [comment]
@RainingNight Do you make sure the cluster is up and running before the client tries to send a request?

**Comment by RainingNight** [comment]
@sergeybykov 

I'm push the sample code：

[SiloHost/Program](https://github.com/RainingNight/orleans/blob/master/Samples/2.0/HelloWorld/src/SiloHost/Program.cs)
[SiloHost2/Program.cs](https://github.com/RainingNight/orleans/blob/master/Samples/2.0/HelloWorld/src/SiloHost2/Program.cs)
[OrleansClient/Program.cs](https://github.com/RainingNight/orleans/blob/master/Samples/2.0/HelloWorld/src/OrleansClient/Program.cs)

Client code snippet:
```csharp
bool isContinue = true;
var watch = new Stopwatch();
watch.Start();
using (var client = await StartClientWithRetries())
{
    while (isContinue)
    {
        isContinue = false;
        try
        {
            await DoClientWork(client);
            await DoClientWork2(client);
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            isContinue = true;
        }
    }
}

Console.WriteLine("Successed!.....Elapsed " + watch.Elapsed.TotalSeconds + "s!");
```

The response: 
```text
...
System.ArgumentException: Cannot find an implementation class for grain interface: HelloWorld.Interfaces2.IHello2. Make sure the grain assembly was correctly deployed and loaded in the silo.
...

Successed!.....Elapsed 61.6261225s!
```

**Comment by RainingNight** [comment]
@sergeybykov Hi, any news, very thanks!

**Comment by sergeybykov** [comment]
So you are starting two silos with different grain assemblies and connecting a single client that invokes grains from both, correct?

I suspect what you might be seeing is the client connecting to the cluster before the two silos exchange their type maps. Until that happens, each silo is only aware of the grain types it loaded itself. Try delaying running the client, and see if that will make it succeed with both calls.

**Comment by RainingNight** [comment]
@sergeybykov Yes, Try delaying running the client, it's ok. And the correct way is create two client?

**Comment by sergeybykov** [comment]
You don't need two clients here. A single client connecting to a cluster with different silos, like in your case above, is enough. It's only a question of waiting for the cluster to get ready (silos exchanged their grain type maps).
