### ISSUE TITLE
Client should not try to reconnect to GW that is no longer in the list returned by IGatewayListProvider

### ISSUE THREAD

**Issue by benjaminpetit** [dotnet/orleans#2789]
On the client, right now when we mark a GW as disconnected, we force a refresh of the list of available gateways, but we don't use it directly: we will try to reconnect to this GW anyway.

I think we should declare the GW dead as soon as the client is disconnected and that this GW is no longer returned by the IGatewayListProvider

**Comment by gabikliot** [comment]
@benjaminpetit , disconnected and dead were 2 different states for a GW. You are suggesting to get rid of the 2 states and consolidate into one. The reason for 2 states was to allow quick reconnect if the GW had a short temporal connection glitch (socket just broke). If we declare it dead, while it is not, we may unnecessary loose connectivity for longer then needed. Instead, we call it disconnect and try to reconnect X times (2 times I think).
Also think in case of 1 GW only (and temporal lost connectivity with it).

**Comment by yevhen** [comment]
Maybe a third state ShuttedDown is what actually needed here? We are experiencing problem with rolling restart as shutted down silo is considered Disconnected and client wastes enormous amount of time trying to reconnect to a silo (like 40 seconds) before declaring it Dead.

**Comment by gabikliot** [comment]
What is the down side of wasting 40 sec to declare silo as dead?
If it causes a msg to not get routed and delayed by 40 sec, then  we should fix that - msg that are queued to a Disconnected silo can be rerouted elsewhere as soon as silo becomes disconnected.
Otherwise, no harm to, right? Does it block any other activity on this client?
Being too aggressive on the other hand can  by mistake declare god silo as as dead.
Its basically back to the same fundamental failure detection tradeoff of completeness vs. accuracy.

**Comment by yevhen** [comment]
> What is the down side of wasting 40 sec to declare silo as dead?

Immediate. We're currently having absolutely horrible experience during deploys. Every action spins for 40 seconds and make users angry

**Comment by yevhen** [comment]
What is the downside of being able to recognize when silo is Disconnected, Dead or Shutted Down? In the latter case it means was gracefully shutted down (by operator)

**Comment by gabikliot** [comment]
Can u please explain what  action spins for 40 ?

**Comment by yevhen** [comment]
User action. When user sends command to a grain which was on shutted down silo, it can not be delivered for 40 seconds due to this issue, making user-experience horrible.

**Comment by yevhen** [comment]
In perfect world the grain will be re-activated immediately on still alive silo and request is routed to it. But that doesn't happen. 40 seconds timeout

**Comment by gabikliot** [comment]
That is what I wrote above:

"If it causes a msg to not get routed and delayed by 40 sec, then we should fix that - msg that are queued to a Disconnected silo can be rerouted elsewhere as soon as silo becomes disconnected."

What the sentence above says is: we can decouple declaring GW as dead from an ability to route to a grain (in other words - availability of a grain can be decoupled from an availability of a GW). Now they are coupled.

**Comment by sergeybykov** [comment]
>I think we should declare the GW dead as soon as the client is disconnected and that this GW is no longer returned by the IGatewayListProvider

I read @benjaminpetit's proposal differently - if a gateway that client got disconnected from is no longer in the list of gateways returned by the gateway provider, then (and only then) declare the gateway dead immediately. Otherwise, do whatever we do today.

This proposal makes sense to me. Unless I misinterpreted it.

**Comment by benjaminpetit** [comment]
Yes @sergeybykov is right, sorry if I wasn't clear in my first post, what I wanted to say: 

Do not try to reconnect to a gw that is no longer in the list returned by the gw provider, instead call `MarkAsDead()` immediately in the `Connect()`  so awaiting message in the queue are rerouted as soon as possible.

**Comment by gabikliot** [comment]
Makes sense.
