### ISSUE TITLE
Orleans fault tolerance and failure modes

### ISSUE THREAD

**Issue by veikkoeeva** [dotnet/orleans#280]
It occurred me that there's very thorough discussion at [A look at Microsoft Orleans through Erlang-tinted glasses](http://theburningmonk.com/2014/12/a-look-at-microsoft-orleans-through-erlang-tinted-glasses/). Should a link be provided in the [Wiki](http://dotnet.github.io/orleans/)?

**Comment by jthelin** [comment]
We should also probably also include a link somewhere to the PluralSight online training course by @richorama which I noticed while reading that article :)

http://www.pluralsight.com/courses/microsoft-orleans-introduction

**Comment by veikkoeeva** [comment]
@jthelin It should be added. Under *Links* it'd be buried, on the main page under *Orleans Documentation Resources* it'd look like standing out so that it should be under other education material. Though I suppose this would require further thinking on the Wiki organization and in the meanwhile it could added directly there.

**Comment by gabikliot** [comment]
Added the link to [A look at Microsoft Orleans through Erlang-tinted glasses](http://theburningmonk.com/2014/12/a-look-at-microsoft-orleans-through-erlang-tinted-glasses/) to http://dotnet.github.io/orleans/Links/.

Also please notice that we later on clarified a lot of the questions raised in this blog here: http://dotnet.github.io/orleans/Runtime-Implementation-Details/

**Comment by veikkoeeva** [comment]
@gabikliot Heh, I wonder if it was there already. :) I think my initial point got served with this, though @jthelin made a good point @richorama's course should probably be listed too.

**Comment by sergeybykov** [comment]
@richorama Do you plan to update http://www.pluralsight.com/courses/microsoft-orleans-introduction to the latest dev experience? You published it just before we made a number of breaking API changes (mostly renames). Sorry about that. :-) Also, nugets weren't there at the time.

**Comment by veikkoeeva** [comment]
@sergeybykov, @gabikliot Just noticed this. As far as I'm concerned, we can close this down. :)
