### ISSUE TITLE
Blocking bootstrap provider freezes up silo

### ISSUE THREAD

**Issue by Scottlr** [dotnet/orleans#2813]
So we recently wanted to use Kestral to host a self hosted web API within the bootstrap provider. Turns out that hosting the API is actually a blocking call, and meant that we couldn't invoke any grains after that point.

I threw together a more simpler scenario where I am executing a blocking action within the bootstraps Init method, and try to invoke a grain.

Should a bootstrap provider really freeze up the whole silo? If it does maybe this could be added to the documentation that any blocking action within the bootstrap provider should be avoided, or offloaded to a different thread.

This was tested on 

- Orleans 2.0 TP1
- Orleans 2.0 TP2
- Orleans 1.3

All versions had the same behavior

Test repository: https://github.com/Scottlr/orleans-blockingbootstrapprovider

Bootstrap Init method [here](https://github.com/Scottlr/orleans-blockingbootstrapprovider/blob/master/BlockingBootstrapProvider/BlockingBootstrapProvider/BlockingBootstrapProvider.cs#L13)
Bootstrap provider registered [here](https://github.com/Scottlr/orleans-blockingbootstrapprovider/blob/master/BlockingBootstrapProvider/BlockingBootstrapProvider/OrleansHostWrapper.cs#L34)
Grain invocation [here](https://github.com/Scottlr/orleans-blockingbootstrapprovider/blob/master/BlockingBootstrapProvider/BlockingBootstrapProvider/Program.cs#L34)

**Comment by gabikliot** [comment]
This is not just blocking, this is infinite loop. The provider has to init before silo init is done, and if it does never finish it's init, the silo will be stuck forever.
It sounds pretty obvious I think, but I agree it should also be documented.

**Comment by Scottlr** [comment]
Yeah, in our first scenario when we was trying to host the self hosted api using kestral, it was pretty tricky to track down.

If initializing the bootstrap provider is such a fundamental part of the silo initialization than I definitely feel there's value in this being documented.

So if I had say 6 bootstrap providers, all taking 10 seconds to initialize, it would increase the total silo initialization time by 1 minute?

**Comment by gabikliot** [comment]
That's a separate questions: whether we initialize providers in parallel or sequentially. I don't remember off my head, but sounds like we should be doing it in parallel.

And yes, it is a fundamental part of silo startup. If bootrstrap  provider fails to init, silo should fail to start. That is by design.

**Comment by Scottlr** [comment]
I'm happy to close this issue under the understanding that bootstrap providers are fundamental to the overall silo initialization process by design. 

Thank you for clearing that up @gabikliot
