### ISSUE TITLE
Use Microsoft.Extensions.Logging for logging abstractions

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#2814]
Just saw this idea in the comment by @jdom in https://github.com/dotnet/orleans/pull/2712 . So raising this issue to see if it is supported by the rest of the community.

**Comment by galvesribeiro** [comment]
@DixonDs, after talking with @ReubenBond Today, I'm going to separate trace/log from Telemetry APIs and make it work with ASP.Net abstractions. Will let you know here once a PR come out.

**Comment by jdom** [comment]
Yup, I would really like this too, so that we can leverage the community instead of having our custom logging

**Comment by sergeybykov** [comment]
This has been implemented for 2.0.0.
