### ISSUE TITLE
Orleans specific grain activation not responding

### ISSUE THREAD

**Issue by somnathnitb** [dotnet/orleans#2831]
Hello Experts,

We are seeing a weird issue in our SILO. Sometimes there are certain grain activations which doesn't respond at all. Any request for any method for that specific activation simply times out. When I see orleans dashboard I do not see any requests in the queue.

Any idea what might be the root cause? I do not have much logs other than standard orleans timeout. It happend only on specific activation of a grain but other activation of the same grain work as expected.

PS: We have set up default Garbage collection time of 2 hours.

Thanks,
Somnath

**Comment by benjaminpetit** [comment]
Hello,

Do you have logs from the client(s)? How many clients do you have?

It might simply be an issue between on client and a gateway, but without logs we cannot be sure.

**Comment by somnathnitb** [comment]
Only logs we get there is request timed out. I understand that it's difficult to say anything without proper logs but that's all we got. Its a web client it works for other grain activation. Like we have a user grain for one user in our system. When user X logs in UserGrain responds with the details when user Y logs in it fails. We also tried to login from the same machine using both the user it's same behavior which invalidates the assumption of issue between client and gateway. We do not see any connection drops between SILO gateway and client as this will be logged and no logs found on those lines.

**Comment by benjaminpetit** [comment]
How did you try to "login from the same machine using both the user"? If you had multiple clients, is this grain activation also unresponsive?

**Comment by somnathnitb** [comment]
Yes logged in same machine using both the users. Ours is a azure webrole talking to multiple SILOs hosted on workers on the same cloud service. Are you saying there is a possibility that from one webrole there might be some issue getting one specific instance of a grain? BTW one thing I forgot to mention was we located the SILO on which the grain was activated and when we restarted that SILO, with new grain activation it all worked fine for few days and issue popped up again in couple of days. Another thing to note here is Grain activation was available in CLR and it was always active until we restarted the SILO. We have garbage collection set to 2 hours(default) for all the grains. BTW do we have any patterns and practices around setting up time for garbage collection? What is the intent of setting default to 2 hours by Orleans?

**Comment by sergeybykov** [comment]
@somnathnitb Have you found out any more data. With the logs it's impossible to tell what's going on with your setup. In general, any grain is available to any caller. I'd suspect that maybe one of the clients wasn't properly configured to connect to the silo/cluster.

**Comment by somnathnitb** [comment]
Apologies we were busy with our release. Once we get the below error grains doesn't respond at all.
**Few issues we have found out**

EventName="MessageEvent" Message="[2017-04-10 02:31:33.567 GMT    53  ERROR  101212    Runtime.Scheduler.WorkerPoolThread/5                10.91.132.138:11111]             !!!!!!!!!! Worker pool thread Runtime.Scheduler.WorkerPoolThread/5 (ManagedThreadId=25) has been busy for long time: Executing Task Id=128 Status=Running for 9.17:28:51.8873651 on WorkItem=WorkItemGroup:Name=[Activation: S10.91.112.1:11111:228645961*grn/A3E31552/00000000+BarServiceBusListenerGrain_4@fc55bfa4 #GrainType=Foo.Global.BarProcessing.Grains.BarServiceBusMessageProcessorGrain Placement=RandomPlacement],WorkGroupStatus=Running Executing for 9.17:28:51.8873651. WorkItemGroup Details: WorkItemGroup:Name=[Activation: S10.91.112.1:11111:228645961*grn/A3E31552/00000000+BarServiceBusListenerGrain_4@fc55bfa4 #GrainType=Foo.Global.BarProcessing.Grains.BarServiceBusMessageProcessorGrain Placement=RandomPlacement],WorkGroupStatus=Running. Currently QueuedWorkItems=64; Total EnQueued=1268; Total processed=1203; Quantum expirations=0; TaskRunner=ActivationTaskScheduler-33:Queued=64; Detailed SchedulingContext=<[Activation: S10.91.112.1:11111:228645961*grn/A3E31552/0000000000000000000000000000000006ffffffa3e31552+BarServiceBusListenerGrain_4-0x87E68D0A@fc55bfa4 #GrainType=FooProcessing.Grains.FooServiceBusMessageProcessorGrain Placement=RandomPlacement State=Deactivating NonReentrancyQueueSize=6942 EnqueuedOnDispatcher=61 InFlightCount=0 NumRunning=0 IdlenessTimeSpan=9.17:28:52.8717340 CollectionAgeLimit=02:00:00]>. " TraceSource="WaWorkerHost.exe"

**Comment by sergeybykov** [comment]
>GrainType=Foo.Global.BarProcessing.Grains.BarServiceBusMessageProcessorGrain Placement=RandomPlacement],WorkGroupStatus=Running Executing for 9.17:28:51.8873651.

Looks like the grain method blocks the thread forever. It is bad to perform blocking synchronous calls on grain threads for performance and responsiveness reasons. But this is even worse - the grain is unavailable because it is "busy" executing the request for 9 days. I suggest you review the code of `BarServiceBusMessageProcessorGrain` and eliminate all non-asynchronous IO operations from it. Looks as if there's a call somewhere there that never returns.

**Comment by benjaminpetit** [comment]
Hi @somnathnitb , any update on this?
