### ISSUE TITLE
Unexpected SILO crashes when long running tasks are executed on Orleans task schedular

### ISSUE THREAD

**Issue by somnathnitb** [dotnet/orleans#2836]
Hello Experts,

We are seeing some issues around SILO crashes when long running tasks are performed on Orleans task schedular. So what we have in place is a Listerner to service bus topic which is started from a bootstrap provider -> Grain -> to new service bus topic listerner instance which processes messages on a task which has been assigned orleans schedular which is received from the grain using TaskSchedular.Current.

Now if there are sevaral messages getting processed continuously through the listener and if message processing takes sevaral minutes may be in Order of 10 minutes we are seeing SILO get's crashed abruptly. Any clue what might be the root cause here. We got the crash dump from our SILO worker and found there were some timeouts but I can't recall whether grain timeouts will cause SILO to crash. Below is the code snippet we use.
**BootStrapProvider:-**
 public async Task Init(string name, IProviderRuntime providerRuntime, IProviderConfiguration config)
        {
            Name = name;
            var instanceCount = Convert.ToInt32(config.Properties["InstanceCount"]);
            var fooStatusListenersList = new List<Func<Task>>();
            var listenerStoreGrain =
               providerRuntime.GrainFactory.GetGrain<IListenerGrainsStoreGrain>(ListenerConstants.ListenerGrainsStore);
            for (var i = 0; i < instanceCount; i++)
            {
                var fooStatusServiceBusListernerGrain =
                    providerRuntime.GrainFactory.GetGrain<IFooStatusServiceBusMessageProcessorGrain>(string.Concat(GatewayStatusListenerGrainName, "_", i + 1));
                await listenerStoreGrain.AddGatwayStatusServiceBusMessageListenerGrains(fooStatusServiceBusListernerGrain);
                fooListenersList.Add(fooServiceBusListernerGrain.StartListening);
            }
            await Task.WhenAll(fooStatusListenersList.Select(listener => listener()));
        }

**FooListenerGrain:-**
public async Task StartListening()
        {
            ExceptionDispatchInfo exInfo = null;

            try
            {
                await
                    RegisterOrUpdateReminder(FooStatusReminderName, new TimeSpan(0, 0, 5, 0),
                        new TimeSpan(0, 0, 5, 0));
                State.IsConnected = true;
                await WriteStateAsync();

                await _fooStatusMessageListener.StartAsync(TaskScheduler.Current);
            }
            catch (Exception e)
            {
                exInfo = ExceptionDispatchInfo.Capture(e);
            }

            if (exInfo != null)
            {
                State.IsConnected = false;
                await WriteStateAsync();
                throw new Exception(exInfo.SourceException.Message);
            }
        }

**Listener Processing:-**
protected override async void ProcessMessage(ITopicQueuing arg1, FooNotificationMessageV1 fooNotificationMessageV1, MessageHeader arg3)
        {
            var fooMessageProcessingTask = Task.Factory.StartNew(() => _fooMessageProcessor.ProcessMessage(fooNotificationMessageV1),
                CancellationToken.None, TaskCreationOptions.None, TaskScheduler); **//Task schedular is the same pass in previous grain to start listener and when this method processing take long time this crashes the SILO.**
 var result = await(await fooMessageProcessingTask);
}

Thanks

**Comment by sergeybykov** [comment]
What's the call stack when silo crushes? Can you share the logs? In general, silos are not supposed to crash no matter what grain code does. This sounds very strange.

**Comment by akshayGT** [comment]
Please find the logs attached. 
[Logs.txt](https://github.com/dotnet/orleans/files/837965/Logs.txt)

**Comment by somnathnitb** [comment]
There was one more interesting observation.
I could see some Orleans watchdog traces saying ".NET Runtime Platform stalled for" at least 3 seconds
2017-03-10 04:31:46.668 GMT	.NET Runtime Platform stalled for 00:00:03.5314074 - possibly GC? We are now using total of 80MB memory. gc=3541, 717, 99
2017-03-10 04:21:47.112 GMT	.NET Runtime Platform stalled for 00:00:03.0578966 - possibly GC? We are now using total of 108MB memory. gc=356, 68, 9
2017-03-10 03:57:44.743 GMT	.NET Runtime Platform stalled for 00:00:03.3972124 - possibly GC? We are now using total of 78MB memory. gc=1813, 241, 23
2017-03-10 03:31:05.995 GMT	.NET Runtime Platform stalled for 00:00:03.7491158 - possibly GC? We are now using total of 73MB memory. gc=11994, 2593, 348

According to Orleans code (Watchdog.cs), this log will happen only if Orleans watchdog misses two of its ticks.
I don't suspect a memory leak, because the memory usage doesn't look a big number. Also it is getting garbage collected after some.

@gabikliot do you see our issue to be violating some of the issues you mentioned here https://github.com/dotnet/orleans/issues/935

**Comment by sergeybykov** [comment]
@somnathnitb The log snippet you shared shows that the silo the log is from, 100.77.240.153, lost connection to another silo - 100.77.216.106. Can you share logs from the latter?

**Comment by sergeybykov** [comment]
Were you able to resolve this?

**Comment by somnathnitb** [comment]
Hi @sergeybykov apologies for delayed response. @AkshayGT attached logs in this thread . Can you please check that?

**Comment by sergeybykov** [comment]
I didn't see logs from 100.77.216.106 there.

**Comment by somnathnitb** [comment]
We found out the issue. Issue was we were calling a grain from an async void method, the grain method used to update a grain state and when several such calls used to happen from void method SILO crashes. But still not sure why this was causing to crash silo. After we made the void method to call the grain with Wait we are not observing the issue anymore. Do you have any clue?

**Comment by somnathnitb** [comment]
protected override async **void** ProcessMessage(ITopicQueuing arg1, FooNotificationMessageV1 fooNotificationMessageV1, MessageHeader arg3)
{
var fooMessageProcessingTask = Task.Factory.StartNew(() => _fooMessageProcessor.ProcessMessage(fooNotificationMessageV1),
CancellationToken.None, TaskCreationOptions.None, TaskScheduler); //Task schedular is the same pass in previous grain to start listener and when this method processing take long time this crashes the SILO.
var result = await(await fooMessageProcessingTask); **//Changed this to use Wait()**
}

**Comment by akshayGT** [comment]
protected override **async void** ProcessMessage(ITopicQueuing arg1, FooNotificationMessageV1 fooNotificationMessageV1, MessageHeader arg3)
{
  var fooMessageProcessingTask = Task.Factory.StartNew(() => 
  _fooMessageProcessor.ProcessMessage(fooNotificationMessageV1),
  CancellationToken.None, TaskCreationOptions.None, TaskScheduler); 
  var result = await(await fooMessageProcessingTask); 
}

Here we can see that  ProcessMessage() method is an **async** method returning **void**, all the exceptions in ProcessMessage() method would go unhandled. Unhandeled exceptions got uncovered during the garbage collection crashing the worker process.  Hence it was worker process which was getting restarted.

**Comment by sergeybykov** [comment]
>Here we can see that ProcessMessage() method is an async method returning void, all the exceptions in ProcessMessage() method would go unhandled. Unhandeled exceptions got uncovered during the garbage collection crashing the worker process. Hence it was worker process which was getting restarted.

Yes, this is a known behavior of .NET, regardless of Orleans. That's why `async void` is not recommended to be used for anything other than `Main` in a console app or `void` event handlers like UI callbacks.
