### ISSUE TITLE
Microsoft Orleans Tools for Visual Studio

### ISSUE THREAD

**Issue by kishan3034** [dotnet/orleans#2838]
didn't find tools for visual studio.

**Comment by miker1423** [comment]
Hello, the tools are not required to run Orleans, if you follow [this tutorial](http://dotnet.github.io/orleans/Tutorials/Minimal-Orleans-Application.html) is easier to get it running.

**Comment by attilah** [comment]
It was not indexed by VS, hence was not visible. Now it is: https://marketplace.visualstudio.com/items?itemName=sbykov.MicrosoftOrleansToolsforVisualStudio
