### ISSUE TITLE
Hourly lockups

### ISSUE THREAD

**Issue by peanutbutterlou** [dotnet/orleans#284]
We have v1.0.5 of Orleans deploying to an Azure Worker Role and are experiencing some strange behavior. *Every hour, on the hour* (right at 1:00, 2:00, 3:00, etc.), we begin to see all forthcoming requests into Orleans getting locked up, returning errors of "UNHANDLED_EXCEPTION, Response did not arrive on time in 00:00:30 for message." Even requests to entirely different grains and different activations of the same grain we have been targeting are failing.

We've ruled out anything (both internally and externally to the environment) that would be interfering on such a regular basis. The only thing that seems to remedy the situation is a reboot of the Worker Role instance. 

Any thoughts or ideas as to what could possibly be causing such behavior, and what we might do to diagnose the occurrences? 

-Lou

**Comment by sergeybykov** [comment]
Do you have call stacks from these exceptions?

**Comment by JoshStardock** [comment]
What is the best way to get the call stacks?

**Comment by sergeybykov** [comment]
They should be in the silo logs. In general, logs can tell a lot about what might be going on.

**Comment by peanutbutterlou** [comment]
Here are logs between 10:00 a.m. EST (14:00 GMT) - 12:02 p.m. EST (16:02 GMT):

http://www.stardock.com/lou/Tachyon.Orleans_IN_0_2015-03-31-14.00.55.681Z.txt
and 
http://www.stardock.com/lou/Tachyon.Orleans_IN_0-2015-03-31-15.02.53.561Z.txt

Within the first file, Tachyon.Orleans_IN_0-2015-03-31-14.00.55.681Z.log, you'll see a timeout error at 15:00:35, which is where Orleans stops responding from there-on-out. You'll see the errors continue through to 15:02 when the silo is rebooted via a scheduled task.

Within the first file, Tachyon.Orleans_IN_0-2015-03-31-15.02.53.561Z.log, you'll see a timeout error at 16:00:32, where Orleans begins to stop responding to new requests. You'll see the errors continue through to 16:02 when the silo is rebooted via a scheduled task.

Some background information:
- There are 4 different reminders being registered by various grains. 
- The recommended procedure for enabling Server Garbage Collection is being used, as prescribed here: http://dotnet.github.io/orleans/Advanced-Concepts/Configuring-.NET-Garbage-Collection and here: http://blogs.msdn.com/b/cclayton/archive/2014/06/05/server-garbage-collection-mode-in-microsoft-azure.aspx. <gcServer enabled="true"><gcConcurrent enabled="false">
- Server is being rebooted 2 minutes after the hour

**Comment by gabikliot** [comment]
From the logs I see a couple of issues:
1)  **"Silo not running with ServerGC turned on - recommend checking app config" GC Type=Client 
GCLatencyMode=Batch**. So you are NOT setting server GC. correctly.
2) **Processor Count: 1** - we recommend running on 4 or 8 core. Orleans silo is a highly concurrent server and with 1 or 2 cores only it’s hard to manage all the multithreaded activities. We work best on 8 cores. It’s better to have 10 8-core machines than 80 singke-core machines. 
3) **Slow access to Azure Table OrleansSiloInstances for InitTable, Slow access to Azure Table OrleansReminders for ReadTableEntriesAndEtags**  – looks like you might have issues accessing Azure table. Can you check on this?
4) **Worker pool thread Runtime.Scheduler.WorkerPoolThread/1 (ManagedThreadId=13) has been busy for long time: Executing Task Id=25 Status=Running for 00:01:10.59944** – Busy for 1 hour? Is it possible you have a blocking call  (storage call for example, or grain call) inside your grain code?
5) **Grain.Tachyon.Grains.Stats.BaseStatsGrain.Current=1** - There is only one grain of this type. Is it possible that it becomes a bottleneck?
6) The reminders you create – **what due time sand period do you use**?

**Comment by peanutbutterlou** [comment]
Thank you for all your comments. They have all proven useful. Turns out your #5 was at the root of it. That grain was bottlenecking. Soo...nothing to see here. Move along.

**Comment by gabikliot** [comment]
:+1:

**Comment by gabikliot** [comment]
http://www.emoji-cheat-sheet.com/

**Comment by AwsomeCode** [comment]
Hi @gabikliot 
I am also having same issue.
>  5. Grain.Tachyon.Grains.Stats.BaseStatsGrain.Current=1 - There is only one grain of this type. Is it possible that it becomes a bottleneck?

Is this means there is only one active grain and its busy calling him self?(bottleneck)

**Comment by sergeybykov** [comment]
>Is this means there is only one active grain and its busy calling him self?(bottleneck)

This means that there is only one grain of this type in the silos. The concern is that if that single grain is frequently called by other grains or by clients, it may become a bottleneck and get overloaded.
