### ISSUE TITLE
Microsoft.Orleans.OrleansCodeGenerator.Build.targets breaks if IntermediateOutputPath is an absolute path

### ISSUE THREAD

**Issue by andhesky** [dotnet/orleans#2864]
IntermediateOutputPath is a relative path by default and the targets file assumes this is always true when it sets the output path of the codegen to "$(ProjectDir)$(IntermediateOutputPath)$(TargetName).codegen.cs". If IntermediateOutputPath is a full path, then the logic breaks. and the output path for codegen is set to an invalid path, for example "C:\enlistment\project\c:\enlistment\project\intermediate\target.codegen.cs"

**Comment by sergeybykov** [comment]
Resolved via #2865 and #2871.
