### ISSUE TITLE
PSUtils - Silo cannot find System.Reflection.Metadata 1.2.0.0 assembly

### ISSUE THREAD

**Issue by selimser** [dotnet/orleans#2866]
We are using a Powershell script to invoke a method in the Silo when the silo is activated. I've updated Orleans binaries to use 1.4.0. Whenever I execute the PS script, I get the error "System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.Metadata, Version=1.2.0.0" on the PS output. System.Reflection.Metadata version is 1.3.0.0 in the Silo, which comes with the nuget packages. 

However I've checked the PSUtils project in Orleans solution and it was pointing to 1.2.0.0 reflection package so I've updated this to get 1.3.0.0 as well. I'm now using PSUtils dll's with Reflection.Metadata 1.3.0.0 in my Silo but whenever I execute the Powershell script, I am still getting "could not load reflection 1.2.0.0 error" so the script fails.

**Comment by selimser** [comment]
In the Orleans project, seems like Microsoft.Orleans.Core uses the following dependency. Could this be the reason? We're using nuget packages so not sure how to fix this.

`<dependency id="System.Reflection.Metadata" version="1.2.0" />`

**Comment by sergeybykov** [comment]
Have you tried adding an assembly binding redirect for `System.Reflection.Metadata`?

**Comment by selimser** [comment]
@sergeybykov Yes I have tried that. Still the same.

**Comment by selimser** [comment]
If I actually get the Reflection.Metadata 1.2.0 and swap the DLL in my silo's bin folder with that one, the powershell script works just fine. The grain client works without any errors or warnings. But when I launch my silo while that reflection 1.2.0 dll is there, it naturally fails because the silo is expecting System.Reflection.Metadata 1.3.0 (and obviously that's what I get with the Orleans nuget packages).

The thing is, I've tried updating the Orleans and OrleansPSUtils project's System.Reflection.Metadata and built the Orleans solution like that. After building it, I've moved the Orleans.dll and OrleansPSUtils.dll into my bin folder - so in theory, after this, it should be looking for System.Reflection.Metadata 1.3.0.0 right? But it is still printing warnings and errors for version 1.2.0.

To see more details, I've modified the code where Orleans handles exception for assembly loading in TypeUtils.GetDefinedTypes(). I am now printing every exception for typeLoadException.LoaderExceptions but it's not giving me anything different.

```
foreach (var excSelim in typeLoadException.LoaderExceptions)
{
   logger.Error(ErrorCode.SiloShutdownEventReceived, "Selim Exception!", excSelim);
}
```

Any further ideas?
thanks.

**Comment by sergeybykov** [comment]
>I also have the binding redirect in my silo.

That's on the silo side. Did you do the same on the `OrleansPSUtil` side?

**Comment by selimser** [comment]
Yeah, I've tried that as well.

**Comment by galvesribeiro** [comment]
That is weird... We didn't caught those errors while testing... 

Also, PS assembly redirect is kind of weird... 

The config files are here:

```
C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe.Config
C:\Windows\syswow64\Windowspowershell\v1.0\powershell.exe.Config
```

I'm not sure if it work by merging an App.Config file.

As @sergeybykov mentioned, it must be at client side, not silo. PSUtils is nothing more than a wrapper around regular OrleansClient.

Can you try change that on PS config files and let me know if it make any difference?
