### ISSUE TITLE
"TFactory not found" when creating grain interface with generic parameter + IGrain constraint

### ISSUE THREAD

**Issue by mistakenot** [dotnet/orleans#287]
When creating a grain interface with a generic type parameter constrained to be a grain and a method that receives that type as an argument, this compile error is generated:

The type or namespace name 'TFactory' does not exist in the namespace '...' (are you missing an assembly reference?)	...\orleans.codegen.cs

Here's the code generating the error:

    public interface ILookupGrain<T, U> : Orleans.IGrain where T : IGrain
    {
        Task Add(T value);

        Task<T> Get(U key);
    }

The exception leads to the orleans.codegen.cs code generated for the Add(T value):

    System.Threading.Tasks.Task Server.Bindings.ILookupGrain<T,U>.Add(T value)
            {

                return base.InvokeMethodAsync<object>(1598727640, new object[] {value is global::Orleans.Grain ? Server.Bindings.TFactory.Cast(value.AsReference()) : value} );
            }

Removing the interface declaration of Add(T value) gets rid of the error.

I imagine that this is most likely me misusing it, but would appreciate anyone's input.

**Comment by sergeybykov** [comment]
Looks like a bug in codegen. There is a decent chance it'll be fixed by https://github.com/dotnet/orleans/issues/195, as it'll eliminate the need for Cast().

**Comment by sergeybykov** [comment]
It actually requires a two-line fix. Will submit a PR shortly.

**Comment by gabikliot** [comment]
Fixed via #298.
