### ISSUE TITLE
From Codeplex: Types used in IGrainObserver have to be serializable

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#289]
Types used in IGrainObserver have to be decorated with SerializableAttribute. This is not a problem - the real problem is that it took me a while to figure out, because everything just fails silently if you use a non-serializable type.

1.The requirement should be mentioned in the documentation / wiki (it's not in the Observer article). 
2.Orleans should throw an exception, rather than silently ignoring the notification. Or really, do anything to point you in the right direction - perhaps send null instead of the actual value, but not ignoring the call altogether, with no message anywhere.

**Comment by ReubenBond** [comment]
> Types used in IGrainObserver have to be decorated with SerializableAttribute.

That is not true: we generate serializers for all types referenced from `IGrainObserver` methods.
They do have to be accessible for serialization, though (i.e, generated code must be able to reference the type).
Eventually we could consider using a serializer which uses IL to circumvent such accessibility requirements.

**Comment by grahamehorner** [comment]
@ReubenBond I don't like the sound of 

Eventually we could consider using a serializer which uses IL to circumvent such accessibility requirements.

sounds like a hack, and could cause issues; anything like this should be safe and supported by CoreCLR

**Comment by ReubenBond** [comment]
CoreCLR supports dynamically emitting IL, right?

**Comment by sergeybykov** [comment]
@ReubenBond, this is already fully supported for .NET Core, right?

**Comment by ReubenBond** [comment]
Yep it is indeed. We:
1. Throw exceptions back to the caller when messages cannot be serialized/deserialized correctly
2. Have ILBasedSerializer so we can serialize almost anything which comes our way
