### ISSUE TITLE
From Codeplex: Actor Host, Dashboard, BAM and Co.

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#290]
Orleans provide us definitely an interesting (different) and helpful approach to solve typical problems which become more and more important with cloud computing. Assuming that "ORLEANS approach" is the way to go, we will get one thing solved: "We can build distributed systems easier". This is huge benefit, no question. 

 However when one system is done we will need to operate it for hopefully very long time. 
 In another words we need lot of tooling around all hosts which we already have (On-Prem, Debug and Cloud). 

 Here are just few ideas (requirements from real world scenarios):
1.Automatically generated architecture picture of running silos including all common technical monitoring.

1.Dashboard which shows how many actor types are defined in the system?
1.Dashboard which shows how many actor-instances are running and where?

3.Persistence (Life Cycle) history. (When actor state has been activated/reloaded/persisted. 

 4.We will also need some kind of (custom) Business Activity Monitoring which can be attached (and detached) on running Grains. 
 Of course we will then need tolling which helps to create information from BAM data. Dashboards, Excel, Custom,...?
1.If we understand actors as native services, then we will need deployment tools. 
 For example, I implemented a new grain and want to deploy it. Or I want to stop/start/take-offline.

2.Versioning of grains, like running of multiple versions of the same grain type.

I'm pretty sure, this list can be much longer. I put here just few requirements to indicate how important is for such a new technology to be maintainable. Honestly, when selling such technologies most decision makers even do not now how hard is concurrency & Co. But when they see how "some complex system" is running and delivering business value, they will understand benefits.

Is there any investments in this direction?

Veikko wrote Jul 8, 2014 at 10:50 PM
This surely is a long list already and it could be longer. A start would be cleaner logging, perhaps in some kind of a "standard format" so that it'd be easier to distinquish messages originating from Orleans.

 I do agree on the bigger picture, all the stuff one can gt, preferably via a public API one can plug "own stuff" like collectors, filters etc. Some of this looks like being available through the tracing facilities already (by superficial reading).

Veikko wrote Oct 31, 2014 at 11:53 AM
I'll Richard Astbury's Silomon here as a relevant resource.

**Comment by ReubenBond** [comment]
This sounds like so much fun! Alright, so there are a few companies (including mine) which are running Orleans in prod. @richorama gave us [SiloMon](https://github.com/richorama/SiloMon), maybe others have things which can be contributed?

Our little Web console which lets you go and run ad-hoc commands against actors & see the result. It's very handy for testing & administration. When someone adds new functionality to an actor (or adds an entirely new actor), the console automatically reflects that change & it shows up in tab-completion. Of course, you're likely more interested in graphical tools.
![image](https://cloud.githubusercontent.com/assets/203839/6995198/ec163534-db7c-11e4-9473-c8b8c9de0fac.png)

There's also our event sourcing system, which gives us a write-ahead journal of all commands. It's used for auditing, debugging, and eventually for billing & statistics. Decision makers should be able to see the value in having a full audit trail - but you'd have to visualize it to make it tangible.
![image](https://cloud.githubusercontent.com/assets/203839/6995248/894cb7ae-db7f-11e4-9438-e9404931a294.png)

That's a little newer, so I'm still criticizing the API.

We are open to releasing any of this if there's interest.

> Dashboard which shows how many actor types are defined in the system?

That should be easy. Tab-completion in the console uses a description of all actors in the system. It reflects into the interfaces assemblies and generates a description on startup.

> Automatically generated architecture picture of running silos including all common technical monitoring.
> Dashboard which shows how many actor-instances are running and where?

It would be cool to create a visualization of messages in the system. Something similar to [Logstalgia](https://www.youtube.com/watch?v=HeWfkPeDQbY), perhaps. Or a simple static graph based on which actors interact with which other actors, similar to [this visualization](https://www.youtube.com/watch?v=bIOLJUKOJkw). If we had a hook allowing us to get all sent messages, that might help.

If we build a nicer Web UI, I'll keep the community in mind and try to make it applicable to all Orleans deployments.

**Comment by gabikliot** [comment]
>We are open to releasing any of this if there's interest.

We are definitely interested in the Web console! 
It can also probably be extended to return some internal runtime info, which is not accessible to the application, for debugging/troubleshooting (we can make it friendly assembly with runtime, or it can query [ManagementGrain](https://github.com/dotnet/orleans/blob/master/src/Orleans/SystemTargetInterfaces/IManagementGrain.cs)). For example, where is the activation for this grain currently located. We have some of this, in a limited form, in [OrleanManager](https://github.com/dotnet/orleans/tree/master/src/OrleansManager).

As for visualization of messages in the system, it is also a good idea. There are open tools out there. For example, visualization of messages in the network is quite popular in network simulators. [See here for some examples](http://www.cs.technion.ac.il/~gabik/Jist-Swans/javis/index.html) (quite outdated).

**Comment by veikkoeeva** [comment]
@ReubenBond Me too! :)

**Comment by sergeybykov** [comment]
There are several complimentary efforts in this area that were demoed during the meetup - https://github.com/OrleansContrib/meetups#meetup-11-a-monitoring-and-visualisation-show-with-richard-astbury-dan-vanderboom-and-roger-creyke.

We should eventually bring some of that into the core codebase.

**Comment by ReubenBond** [comment]
Closing. We have the lovely Orleans Dashboard project: https://github.com/OrleansContrib/OrleansDashboard as one implementation of this idea which has seen solid traction in the community.
