### ISSUE TITLE
Is Orleans supporting Azure SDK 3.0?

### ISSUE THREAD

**Issue by hyha** [dotnet/orleans#2905]
Hi there,

I saw in documentation that Orleans support Azure SDK 2.4-2.8 ([ref](http://dotnet.github.io/orleans/Documentation/Installation/Prerequisites.html)), we are planning to upgrade to Azure SDK 3.0 (March 2017). Is Orleans now supporting Azure SDK 3.0?

We also planning to upgrade .Net 4.5.1 to 4.6 as well, don't know if Orleans already supports that?

Thanks in advance

**Comment by sergeybykov** [comment]
We are unaware of any issues with running Orleans with Azure SDK 3.0. In general, we only require a minimal compatible version, and higher versions just work. However, there were a couple of instances in the past when a breaking change in Azure Storage client library broke us. Can you try Orleans with 3.0, and let us know?

**Comment by hyha** [comment]
Thanks Sergey, we will try and feedback. 
Btw, will be any issues upgrading to .Net Framework 4.6 on Orleans based projects?

**Comment by sergeybykov** [comment]
@hyha Great.
>Btw, will be any issues upgrading to .Net Framework 4.6 on Orleans based projects?

There shouldn't be any issues. Many Orleans users have been running on 4.6.x for a long time by now.

**Comment by jdom** [comment]
And BTW, it's very likely that Orleans 1.5 will target 4.6.2. Were you planning to upgrade o that or just 4.6?
