### ISSUE TITLE
Is it possible that a grain activation never be deactivated before silo down/restarted

### ISSUE THREAD

**Issue by hotants** [dotnet/orleans#2923]
Hi Guys,

https://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Activation-Garbage-Collection.html

can we set AgeLimit to Infinite, or if there is any better way if we want to let a grain(activation) always alive even it does not receive any call for long long time.

we have placed an activation of a grain in every silo, we need to make sure that there would be always an activation on every silo which always alive to receive a message from stream. Reminder could not guarantee an activation will be reativated in a silo.

we are using Orleans SDK 1.0.9

Thanks

**Comment by sergeybykov** [comment]
It is possible to set idle time to a very long value. It is also possible for an activation to call `DelayDeactivation(TimeSpan.MaxValue)` to prevent its collection. However, this is not a strong guarantee that the activation will stay in memory. For example, it will get deactivated if the silo that holds the grain directory partition where this activation is registered dies.

In general, trying to keep activations in memory artificially isn't a recommended pattern. `GrainService` feature was added recently to enable scenarios with a grain-like object automatically created on every silo. We still lack documentation for `GrainService`, but there are tests that show how to use it.

**Comment by hotants** [comment]
Thanks @sergeybykov,  We are going to upgrade Orleans to the latest version, but it will take time as migration is always painful esp for state. that's really a complain as Orleans does not support back-compatibility, :-<

**Comment by sergeybykov** [comment]
We are looking at upgrade scenarios and back-compat now. Will take time, of course.

**Comment by hotants** [comment]
that's great news. 
But we observed that in latest version of BlobProvider(1.4.1)
It does not support serialze/deserialze ObserverSubscriptionManager. 
Observer pattern is widely used in our code.

ObserverSubscriptionManager<IDeviceStatusObserver> DeviceStatusObservers { get; set; }

is this correct? any plan to support it?

**Comment by sergeybykov** [comment]
>It does not support serialze/deserialze ObserverSubscriptionManager.

How does this manifest? `ObserverSubscriptionManager` should be serializable, as we generate a serializer for it. That being said, `ObserverSubscriptionManager` is essentially just a helper class with very little logic in it. You can create your own, more advanced, variation of it easily. In the hindsight, I think we should have made a sample instead of including into the codebase.

**Comment by hotants** [comment]
Ok, thanks, it's not serialzable.  Creating our own ObserverSubscriptionManager, would have more migration work, if Orleans has made change to office one, we also need to update it accordingly.

**Comment by sergeybykov** [comment]
>Ok, thanks, it's not serialzable.

I don't understand. https://github.com/dotnet/orleans/blob/master/src/Orleans/Async/ObserverSubscriptionManager.cs#L12. Which triggers generation of `OrleansCodeGenOrleans_ObserverSubscriptionManagerSerializer<T>`.

**Comment by hotants** [comment]
Because of private property:  private readonly HashSet<T> observers; 
it's not able to be serialzed into JSON, as we are using **BlobProvider**.

**Comment by hotants** [comment]
@sergeybykov one more question back to the original topic(Broadcasting to per silo). 

while we are upgading to latest Orleans SDK to use GrainService(it takes time),  still trying to continously implement Orleans Stream for a broadcasting. 

But the problem is that, from our logs shows that it's subscribe to a Stream in few of silos(1 or 3), message is not delivered to those silos.
 
Here are some backgroud:
1. We have a 4 silos, place an activation of stream consumer grain.
    For each silo, using a bootstrap provider to place an activation of Stream Consumer grain.
    when it's activated, we have DelayDeactivation to TimeSpan.Max, and on OnDeactivationAsync, we will try to place a new activation of Stream Consumer Grain(primary key will be unique), so that there would be a activation in every silo.

2. We have a MemoryStorage for PubSubStore, have to stick to a MemoryStorage for PubSubStore(does it support multiple PubSubStores with different providers?)

Currently the problem we are facing is that after every deployment, we could see from log that each Silo has an consumer activation subscribed to the stream successfully, but broadcast message are not delivered to all silos, only to 3 silos or even 1 silo.

is that possible that because of memory storage based PubSubStore, although we have no idea where the pub and sub mapping persisit in memory(which silo),  when a silo which keep the mapping down, lost them?

Another strange thing is that OnDeactivateAsyn is triggered twice for one activation.

could you give me a light on what the possible reason?

**Comment by sergeybykov** [comment]
>is that possible that because of memory storage based PubSubStore, although we have no idea where the pub and sub mapping persisit in memory(which silo), when a silo which keep the mapping down, lost them?

Yes, `MemoryStorage` is inherently unreliable, and should only be used for development or for the rare cases where you can afford to lose data in case of a silo failure.

>Another strange thing is that OnDeactivateAsyn is triggered twice for one activation.

This sounds very strange. I don't think we've ever heard something like that. Can you share the logs?
