### ISSUE TITLE
Bot Framework sample wanted

### ISSUE THREAD

**Issue by davidgristwood** [dotnet/orleans#2938]
Orleans would seen a great fit for bots, with one grain per conversation. Has anyone tried to use Orleans with the bot framework? https://dev.botframework.com/

**Comment by ashkan-saeedi-mazdeh** [comment]
@davidgristwood  when the bot framework came out and I looked at it, almost instantly I realized if I want to use it, I would use it in Orleans, 
The main way Microsoft meant it to be used was with stateless computations which use azure storage however and I guess some automatic dialog designers were working using that assumption, I don't remember if it was possible to still use that feature with Orleans or not but the bare-bones framework can be used for sure with Orleans. 

I don't have the time to implement it but definitely it is an interesting case.

**Comment by ReubenBond** [comment]
Closing for staleness & lack of signal.
