### ISSUE TITLE
Orleans Grain Class Collection cannot find orleans.codegen.cs file

### ISSUE THREAD

**Issue by GianniBortoloBossini** [dotnet/orleans#296]
I added an Interface Collection project and it compiles.
I added a Class Collection project but it does not compile. I have this error:
![image](https://cloud.githubusercontent.com/assets/4663018/6959053/acf9f508-d914-11e4-9ccd-918f877c8dab.png)
An empty orleans.codegen.cs file exists into Properties folder.

**Comment by GianniBortoloBossini** [comment]
I solved the problem.
In the Class Collection project, it is necessary to show all files, expand the Properties item and "Include in project" the orleans.codegen.cs.

**Comment by sergeybykov** [comment]
Looks like a bug in the project template. You can manually add a link to Properties\Orleans.codegen.cs to the project.

![addlink](https://cloud.githubusercontent.com/assets/8248806/6968100/e8eab346-d918-11e4-9d0f-e2c3e1ca08c3.png)

**Comment by sergeybykov** [comment]
Need to fix the template. Unlike the template, adding a reference to Microsoft.Orleans.Templates.Grains adds orleans.codegen.cs correctly.

**Comment by jthelin** [comment]
PR #297 should fix this.
