### ISSUE TITLE
OrleansHost and Orleans application development

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [dotnet/orleans#2964]
I've had a weeks old conversation with @sergeybykov  about relevance of OrleansHost.exe and the fact that it should be deprecated in favor of code  based config and some other reasons.

Again it came up on gitter and I wanted to replace the getting started page which uses it and I myself I guess modified as well.

Now there are few pathes for a good getting started page, 

- Point people to the template which creates a development silo/include the code required for starting a host in another AppDomain and a client in the main one, inside the page.
- Have some utility class / method in Orleans which takes a ClusterConfig and starts a silo in another AppDomain for dev and test purposes
- Have a client and a host project which both start and Orleans client connects to the local silo, each started in the main AppDomain without any additional AppDomain code, is it harder to debug?

Which one should we choose 

I myself at first used the template and now copy from my own projects and modify, specially now that I'm using topshelf but others might go with YAMS and want normal console apps instead of windows services.

I really don't know what is the best way to make it easy for people to write a Orleans application the first time and even after that without being confused or having to look at 10 documentation pages scattered around. 

Maybe choosing one of the above and having one sample page per scenario, azure, windows service, console app is a good idea, and HostBuilder would help I understand.

**Comment by sergeybykov** [comment]
>Have a client and a host project which both start and Orleans client connects to the local silo, each started in the main AppDomain without any additional AppDomain code

That's the direction we are taking.

**Comment by sergeybykov** [comment]
OrleansHost project has been removed as part of #3415.
