### ISSUE TITLE
Load ClientConfiguration from Microsoft.Extensions.Configuration.IConfiguration

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#2992]
Would it make sense to have `public static ClientConfiguration LoadFromConfiguration(IConfiguration configuration)` in `ClientConfiguration` or is it something out of scope of the core Orleans? Something like this would be useful for ASP.NET Core clients, I reckon

**Comment by jdom** [comment]
We are thinking something along these lines, although a little more extreme. Right now we are designing the silo part of it, but client should be updated too: https://github.com/dotnet/orleans/issues/2936

**Comment by jdom** [comment]
Progress is on the way to support IConfiguration and IOptions natively, with ClientConfiguration only as a back compat-only way to configure Orleans, but will no longer be required in the core
