### ISSUE TITLE
Unable to immediately restart a Silo after entire cluster shuts down unexpectedly.

### ISSUE THREAD

**Issue by Saraphite** [dotnet/orleans#3009]
Hey there,

As noted in the title, it appears that we are unable to restart a Silo after the entire cluster dies unexpectedly.

To replicate this issue, we have two Silos running together on the same machine. 
One is using Port 22222 and Proxy Port 40000 (Silo A), the other Port 22223 and Proxy Port 40001 (Silo B). 
After them running for a period of time (the length of which doesn't seem to matter), we close both of them together.
At this point the OrleansMembershipTable displays both Silos as Active (3) due to nothing being able to update this.
We then restart the Silo A.
This then takes 5 minutes (almost exactly) before failing to initialize the Silo.
It then reports that Silo A became unavailable for messaging.

Upon inspecting the OrleansMembershipTable at this point, we can see that Silo A has had its status changed to 'Joining' (2).

After this, starting Silo A or B is fine, regardless of their current status in the OrleansMembershipTable.

Through some investigation, we've managed to determine that the issue is in SiloHost.StartOrleansSilo();

What we're wanting to know is if there is any way around this issue.

Thank you

Extra Info:
Orleans Version 1.3

StartupError Log (Side note: the C:\w\Git\Orleans_GeoSamples\src\OrleansRuntime\Silo\Silo.cs is not my directory)

>2017-05-10-10.34.19.856ZZ
>ERROR starting Orleans silo name=[REDACTED] Exception=
>Exc level 0: System.AggregateException: One or more errors occurred.
>   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
>   at Orleans.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout) in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\TaskExtensions.cs:line 210
>   at Orleans.Runtime.Silo.DoStart() in C:\w\Git\Orleans_GeoSamples\src\OrleansRuntime\Silo\Silo.cs:line 550
>   at Orleans.Runtime.Silo.Start() in C:\w\Git\Orleans_GeoSamples\src\OrleansRuntime\Silo\Silo.cs:line 439
>   at Orleans.Runtime.Host.SiloHost.StartOrleansSilo(Boolean catchExceptions) in C:\w\Git\Orleans_GeoSamples\src\OrleansRuntime\Silo\SiloHost.cs:line 178
>Exc level 1: Orleans.Runtime.OrleansException: -Silo S127.0.0.1:22222:232108136 failed to update its status to Active in the table due to failures (socket failures or table read/write failures) after 38 attempts: ExecuteWithRetries has exceeded its max execution time of 00:05:00. Now is 2017-05-10 10:34:19.828 GMT, started at 2017-05-10 10:29:17.236 GMT, passed 00:05:02.5922384
>   at Orleans.Runtime.MembershipService.MembershipOracle.<UpdateMyStatusGlobal>d__48.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\OrleansRuntime\MembershipService\MembershipOracle.cs:line 390
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.Runtime.MembershipService.MembershipOracle.<BecomeActive>d__30.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\OrleansRuntime\MembershipService\MembershipOracle.cs:line 168
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass1_0.<<QueueTask>b__0>d.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\OrleansRuntime\Scheduler\ShedulerExtensions.cs:line 38
>Exc level 2: System.TimeoutException: ExecuteWithRetries has exceeded its max execution time of 00:05:00. Now is 2017-05-10 10:34:19.828 GMT, started at 2017-05-10 10:29:17.236 GMT, passed 00:05:02.5922384
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 185
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.AsyncExecutorWithRetries.<ExecuteWithRetriesHelper>d__5`1.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\Orleans\Async\AsyncExecutorWithRetries.cs:line 179
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Orleans.Runtime.MembershipService.MembershipOracle.<UpdateMyStatusGlobal>d__48.MoveNext() in C:\w\Git\Orleans_GeoSamples\src\OrleansRuntime\MembershipService\MembershipOracle.cs:line 366

**Comment by gabikliot** [comment]
This is by design. Silo A is waiting for silo B to respond. One workaround is to start both silos . Another workaround is to wipe the table before you restart.
There is also a way to shorten the wait period, so silo a will wait less time for b. I will add a details of the config parameter to do that later.

**Comment by gabikliot** [comment]
The third and easiest option is to set orleansConfig.Globals.ValidateInitialConnectivity to false. 

That will completely disable the check in A of B. A will start OK and will just ignore this old entry of B saying Active.
Once B will start, it will mark its own old entry in the table as Dead and write a new entry and will be OK.

**Comment by Saraphite** [comment]
Initial impressions seem to be that this worked!

Thank you.
