### ISSUE TITLE
Documentation for understand the reliability properties of Orleans

### ISSUE THREAD

**Issue by gabomgp** [dotnet/orleans#3013]
I don't found the docs that describe de reliavility properties of Orleans. Specially, i'm interested in the event of unexpected silos breaks. What happens whith the messages that are sended to that silo? can be dropped messages when i use Orleans?

**Comment by gabikliot** [comment]
http://dotnet.github.io/orleans/Documentation/Runtime-Implementation-Details/Messaging-Delivery-Guarantees.html

**Comment by gabomgp** [comment]
Thanks you very much @gabikliot
