### ISSUE TITLE
Release timeline for Orleans 1.5.0

### ISSUE THREAD

**Issue by somnathnitb** [dotnet/orleans#3021]
Hi All,

We are running on Orleans 1.3.1 and we are planning to migrate to latest version of Orleans. Considering we already have some good improvements in Orleans 1.4.1, is it worth to wait for 1.5.0? If yes do we have any timeline for an RTM version of 1.5.0 which is currently in beta? Our upgrade is planned on 1st week of June.

Thanks,
Somnath

**Comment by xiazen** [comment]
I think 1st week of June is very close to the 1.5 public release right? @jdom

**Comment by jdom** [comment]
Yes, we don't have a hard target date, but depending on feedback from the beta and so on, we'll accommodate. Our current intention is indeed to release in a couple of weeks.

**Comment by centur** [comment]
Also in the light of #2921 - is there any planned breaking changes between 1.4.1 and 1.5 ?

**Comment by ReubenBond** [comment]
@centur there are some breaking changes listed in the 1.5.1-beta release notes: https://github.com/dotnet/orleans/releases/tag/v1.5.0-beta1. The biggest is the .NET Framework update. The `GrainClient` change shouldn't affect you, but keep it in mind for the future. `SerializationManager` is made non-static, but you can inject it if needed. More DI.

**Comment by somnathnitb** [comment]
Thank you all appreciate it.
