### ISSUE TITLE
Serialization of interface implementations should be improved

### ISSUE THREAD

**Issue by andrew-hampton** [dotnet/orleans#3022]
When there is an interface as an argument for a grain method the error message for a missing serializer is difficult to troubleshoot.

When debugging you can see an exception when it tries to route the call that it doesn't understand how to serialize that type, but the end user experience is that the grain timed out after the grain timeout length so there's not an easy actionable step to determining the issue. At very least the error handling in this scenario should be improved, but ideally Orleans should search for implementations of interfaces on grain methods and generate serializers for them without needing to be add a [KnownType] or [GenerateSerializer] .

**Comment by ReubenBond** [comment]
@andrew-hampton which version of Orleans are you running?

**Comment by andrew-hampton** [comment]
@ReubenBond 1.3.1

**Comment by ReubenBond** [comment]
Thanks, @andrew-hampton. This should be improved in 1.4.0 via #2364

**Comment by andrew-hampton** [comment]
Sounds like that will fix the silent failure behavior. What about doing more to automatically create the appropriate serializers?

**Comment by ReubenBond** [comment]
> At very least the error handling in this scenario should be improved, but ideally Orleans should search for implementations of interfaces on grain methods and generate serializers for them without needing to be add a [KnownType] or [GenerateSerializer] .

See lines [140](https://github.com/dotnet/orleans/blob/master/src/OrleansCodeGenerator/GrainReferenceGenerator.cs#L140) & [150](https://github.com/dotnet/orleans/blob/master/src/OrleansCodeGenerator/GrainReferenceGenerator.cs#L150) here, where we do perform this search. Are you using build-time code generation (via the [Microsoft.Orleans.OrleansCodeGenerator.Build](https://www.nuget.org/packages/Microsoft.Orleans.OrleansCodeGenerator.Build/1.3.1) NuGet pkg) or runtime code generation?

**Comment by andrew-hampton** [comment]
We're using the NuGet package. The interface implementations are marked as serializable, but they are not in a library that references Orleans.

Based off the docs here http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Serialization.html we currently fall into bucket #3 for generated serializers

**Comment by ReubenBond** [comment]
@andrew-hampton for now, I think `[KnownAssembly]` + `[Serializable]` is the way to go. I'll keep our discussion in mind and hopefully we can come up with ways to make the system more intuitive. Can we close this for now?

**Comment by andrew-hampton** [comment]
Thanks, we can close this for now
