### ISSUE TITLE
Recommended System Requirement

### ISSUE THREAD

**Issue by shanahmed** [dotnet/orleans#3025]
#question
What are the recommended system requirements for Microsoft Orleans?

Thanks,
Shan

**Comment by sergeybykov** [comment]
We generally recommend running Orleans silos on machines or VMs with more than one core: at least 2, 4+ is better. This is primarily for better experience, as the app will be more responsive with a true parallelism in the system. Although it will work on a single-core system, too.

**Comment by shanahmed** [comment]
Thanks for you reply Sergey Bykov. 

I remember previously there was some detail of system requirement mentioned in documentation. Can you please send some link or docmentation related to system requirement. 

Thanks,
Shan

**Comment by sergeybykov** [comment]
I don't think we ever had more than http://dotnet.github.io/orleans/Documentation/Installation/Prerequisites.html.
