### ISSUE TITLE
Strange exception on one role instance.

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#3029]
During our attempt to upgrade our codebase to 1.4.1 when deployed new package to our Test Cloud Service one of our instances (this role is an always running client to a cluster) stuck with this exception:
```
Orleans.Runtime.OrleansException: Cannot find an invoker for interface *unavailable* (ID=471740693,0x1C1E3115).

Server stack trace: 
   at Orleans.Runtime.GrainTypeManager.GetInvoker(Int32 interfaceId, String genericGrainType)
   at Orleans.Runtime.SystemTarget.Orleans.Runtime.IInvokable.GetInvoker(GrainTypeManager typeManager, Int32 interfaceId, String genericGrainType)
   at Orleans.Runtime.InsideRuntimeClient.<Invoke>d__59.MoveNext()

Exception rethrown at [0]: 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Orleans.GrainClient.InternalInitialize(ClientConfiguration config, OutsideRuntimeClient runtimeClient)
   at DBCloud.JobsHost.WorkerRole.configureOrleansClient()
```

What's interesting - another instance of the same role initialized just fine. Also this error disappeared when I forced the VM to be re-imaged. I never saw this before, neither I can explain how `Role_IN_0` initialized and ran w\o any problems and `Role_In_1` stuck, give that the package with code is exactly the same.
We are using in-place upgrade for test, not a vip-swap.
Any ideas what could it be and any chance this is a bug in Orleans ?

**Comment by sergeybykov** [comment]
Weird. I wonder if this is some kind of assembly loading/type resolution race. I would try referencing a type from the assembly explicitly in the startup code to force its loading deterministically.

**Comment by centur** [comment]
This what I suspect - some in-place upgrade failed to unload\delete app domain so new assembly didn't replaced old one that was in use. Maybe just one off mystery bug, thought that it worth a report in case we stepped on some rare bug\race in orleans itself.

**Comment by sergeybykov** [comment]
>some in-place upgrade failed to unload\delete app domain

How is this possible? If it's in Azure, then it reboots the VM as part of in-place upgrade IIRC.

**Comment by DixonDs** [comment]
@centur We experienced this issue as well. My theory is that since upgrade is done by upgrade domains it could be that you (and we) had a 1.4.1 client talking to an older silo. Rebooting that client helped as far as I remember.

**Comment by centur** [comment]
@sergeybykov I don't know, just throwing some "looks valid" theories in the air.
@DixonDs interesting, your theory sounds more valid than mine.
Had that happened when you significantly changed a grain interface ? I don't think we changed any interfaces with that deployment, it was just 1.3 to 1.4 upgrade, though... 

I'm not sure this issues is easy to reproduce as it was one off for us, so it can be closed and kept for search purposes.
