### ISSUE TITLE
Orleans + NuGet4 + ActivityDesigner causes OutOfMemoryException in VS15

### ISSUE THREAD

**Issue by lmagyar** [dotnet/orleans#3042]
Steps to reproduce:
* VS15 & fresh new empty solution
* add Workflow Activity library from original VS template & change framework to net461
* add Microsoft.Orleans.Core 1.5.0-beta1 with PackageReference (**NOT** with packages.config)
* open the empty Activity1.xaml

Instead of opening the designer, VS says:
```
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at VSLangProj.Reference.get_PublicKeyToken()
   at Microsoft.VisualStudio.Activities.Helper.CreateAssemblyNameFromReference(Reference r)
   at Microsoft.VisualStudio.Activities.Helper.GetReferenceAssemblies(VSProject project)
   at Microsoft.VisualStudio.Activities.EditorPane.get_ReferencedAssemblies()
   at Microsoft.VisualStudio.Activities.EditorPane.ResetShadowCopyPath()
   at Microsoft.VisualStudio.Activities.EditorPane.CreateWorkflowDesignerInIsolatedMode()
   at Microsoft.VisualStudio.Activities.EditorPane.Microsoft.VisualStudio.Shell.Interop.IPersistFileFormat.Load(String fileName, UInt32 formatMode, Int32 readOnly)
```

Build results in 2 warnings:
* Could not run workflow validation because file **'System.Net.Http, PublicKeyToken=b03f5f7f11d50a3a' has an incorrect format.** This will not prevent workflows from running; but any workflow that has a validation error will fail at runtime. If the file is a platform-specific library or executable, consider building the project using MSBuild.exe from a command prompt of the targeted platform.
* Could not compile workflow expressions because file 'file:///C:\Users\lmagyar\.nuget\packages\ **System.Net.Http\4.3.0\ref\net46\System.Net.Http.dll' has an incorrect format.** Workflows in this project may still run, if they do not require expression compilation. If the file is a platform-specific library or executable, consider building the project using MSBuild.exe from a command prompt of the targeted platform.	

I tried to investigate:
* with packages.config nuget package installation, no problem
* I've added all the ~50 nuget packages that is referenced through Microsoft.Orleans.Core (based on the packages.config in another project), with PackageReference, no problem
  * finally adding Microsoft.Orleans.Core results in the exception
* I've tried several assembly binding redirects, nothing changes, exception
* System.Net.Http 4.3.1 and 4.3.2, exception
* with previous versions (1.4.1, 1.1.2), exception
* with net 452, exception

It seems to me, that it is related with Orleans and assembly loading, but have no clue how can it be related with NuGet4's PackageReference.

How could I investigate it deeper???

**Comment by sergeybykov** [comment]
@lmagyar From your description I get the impression this is a VS/VSIX bug. Have you tried the same in VS 2017 for a comparison?

**Comment by lmagyar** [comment]
I've tried it in VS 15, ie. VS 2017, only this has NuGet 4.x as I know. It's a bug, that shows itself only when Orleans.dll is loaded in NuGet4's PackageReference "environment" under VS15. It's only a hunch, that Orleans.dll itself contains something special. I try to investigate it deeper.

**Comment by lmagyar** [comment]
Reported it in VS FeedBack (https://developercommunity.visualstudio.com/content/problem/61637/vs-2017-outofmemoryexception-in-xaml-activity-desi.html), closing it here.

**Comment by sergeybykov** [comment]
Makes sense. Orleans.dll doesn't contain anything special that could interfere with VS, I don't think.
