### ISSUE TITLE
Docs search doesn't work in Edge

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#3046]
Search used to work fine in Edge before and continues to work in Chrome, but seems broken in Edge in Win10 15063.296.

**Comment by dandago** [comment]
Works for me with:

Win10 14393.447
Edge 38.14393.0.0

**Comment by sergeybykov** [comment]
Mine is Win10: 15063.296, Edge: 40.15063.0.0, and it's not working.

**Comment by dandago** [comment]
Reproduced here on same Edge version on another laptop.

**Comment by dandago** [comment]
I checked on DocFX's own site, e.g. here: https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html .

Search seems to work but it is A LOT slower on Edge than it is in Chrome.

**Comment by sergeybykov** [comment]
Looks like it's a known issue - https://github.com/dotnet/docfx/issues/1581 and it was already fixed via https://github.com/dotnet/docfx/pull/1680. Need to verify that.

**Comment by sergeybykov** [comment]
Resolved via #3108.
