### ISSUE TITLE
DeepCopier with ObservableCollection suddenly requires all class graph to be marked as [Serialized]

### ISSUE THREAD

**Issue by shlomiw** [dotnet/orleans#3064]
Hi,

I've changed a property of a class from List<> to ObservableCollection<>.
This class is EF entity and it has a deep graph of classes connected.

I'm sending this class via grain, and I had no issues before the change.
Now I'm getting SerializationException: 'Type .. in Assembly .. is not marked as serializable'. And I need to do it to *all* the different classes types in the object graph.

Can we avoid setting all these classes as [Serializable]?

Thanks in advance,
Shlomi

Attaching a screenshot of the exception:
![image](https://cloud.githubusercontent.com/assets/1025170/26555235/c8055db0-449c-11e7-94fb-0dc1a7052703.png)

**Comment by ReubenBond** [comment]
Hi @shlomiw, here's what's happening: `ObservableCollection<T>` does not have a defined serializer, therefore the fallback serializer (BinaryFormatter) is being used. BinaryFormatter requires that classes be marked as`[Serializable]`.

To fix it, follow the instructions in the [Serialization documentation](http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Serialization.html) for creating a custom serializer for `ObservableCollection<T>`. Note that the class defined under 'Method 3' of that documentation can be an open generic type (eg `MyObservableCollectionSerializer<T>`) - just make sure to mark it as a serializer for that type: `[Serializer(typeof(ObservableCollection<>))]`.

Let me know if that helps

**Comment by shlomiw** [comment]
@ReubenBond - thank you very much! I'll try it and update you.

**Comment by shlomiw** [comment]
@ReubenBond - I used method 3 and it works :)
Thanks!!

**Comment by shlomiw** [comment]
@ReubenBond - one small question: 
IsOrleansShallowCopyable is internal, but could be useful for custom serializers. What about exposing it? maybe via SerializationManager.IsOrleansShallowCopyable(Type t) (or <T>)

**Comment by ReubenBond** [comment]
@shlomiw DeepCopy is a no-op in the case that a type is shallow-copyable. In which cases would `IsShallowCopyable` be useful to you? We can consider exposing it

**Comment by shlomiw** [comment]
@ReubenBond for my custom serializer I've used the code of Orleans List<T> serialization as a reference.
From Orleans.Serialization.BuiltInTypes:

```
        internal static object DeepCopyList<T>(object original, ICopyContext context)
        {
            var list = (List<T>)original;

            if (typeof(T).IsOrleansShallowCopyable())
            {
                return new List<T>(list);
            }

            // set the list capacity, to avoid list resizing.
            var retVal = new List<T>(list.Count);
            context.RecordCopy(original, retVal);
            retVal.AddRange(list.Select(element => (T)SerializationManager.DeepCopyInner(element, context)));
            return retVal;
        }
```

As you can see - it uses the **IsOrleansShallowCopyable** for optimization (very useful for immutable objects). I can also check for immutable etc, but would be great to be aligned with Orleans serialization.

**Comment by ReubenBond** [comment]
Sounds good to me, how do you feel about submitting a PR?

**Comment by shlomiw** [comment]
Why not, it's holiday here, will do it when I'll be back at office :)

Is `SerializationManager` is the right place?

**Comment by ReubenBond** [comment]
@shlomiw thanks :D yep, SerializationManager is the right place

**Comment by shlomiw** [comment]
@ReubenBond - I'm a bit struggling with building the Orleans solution, and it taking me too much time for 3 lines of code.
If you be kind enough to just add these to SerializationManager, I'll be grateful. 
In case I'll have a larger contribution in the future, I will do a proper PR :)

The code:
```
/// <summary>        
        /// This method exposes internal IsOrleansShallowCopyable to allow external custom serializers to check if is it ok to shallow copy objects when deep copying.               
        /// </summary>
        /// <param name="type">The type to check.</param>
        /// <returns>Returns true if ok to shallow copy.</returns>
        public static bool IsTypeOrleansShallowCopyable(Type type)
        {
            return type.IsOrleansShallowCopyable();
        }
```

I think the right place is to put it at the end of 'Deep copying' region.
Would be nice if you'll add it to 1.4.2.

Many thanks!

**Comment by shlomiw** [comment]
@ReubenBond - please disregard my previous comment, I've created the PR.
