### ISSUE TITLE
Pulling out stream pooling agents

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#3080]
Hello guys, 

After some discussions today, I ended up with an unanswered question...

Does it worth to have the Stream Pooling agents pulled out from Silo host into its own process?

The idea is to potentially open the stream ingestion endpoint abstracted from the silo so new scenarios for stream ingestion would open easily like containers, non-conventional/queue-based protocol (for example UDP stream, etc.)

Also, I think it somehow would relieve the silos from the ingestion load, freeing resources to grain code specially in very hot ingestion scenarios like IoT for example.

I just want to capture feedback here. This is not a proposal or a design issue. I just would like to hear from the community if they have ideas regarding it.

**Comment by sergeybykov** [comment]
The benefits of hosting stream pulling agents within silos are:
- simpler deployment model
- automatic elastic scaling with the cluster size, a single scale factor to manage
- leveraging of the cluster membership protocol for dynamically distributing work, load balancing, and handling of node failures
- possibility for local processing of events without sending them over the wire

If you were to take just the pulling agent and provider logic and host it in a set of nodes/containers, you'll lose all of these benefits. That was the typical situation before we added streaming - people had to deploy and manage a separate set of nodes, e.g. a worker role, just to pull data from ServiceBus, Azure Queue, EventHub, etc., and send it to an Orleans cluster.

If instead we tried to factor out the pieces like cluster membership, messaging, etc. to make it runnable with all the above benefits as non-silo nodes, that's a non-trivial amount of work. While doable, I don't think the complexity of such a surgery and the cost of maintaining it justifies the benefits. I suspect it would be cheaper to build a simpler version of the load balancing logic from scratch.

**Comment by galvesribeiro** [comment]
I see the rationale...

>  I suspect it would be cheaper to build a simpler version of the load balancing logic from scratch.

How do you think it would work? And what a new load balancing bring to the table?

**Comment by sergeybykov** [comment]
>How do you think it would work? And what a new load balancing bring to the table?

I'll use Azure Worker Role as an example, but it'll likely apply to most other hosting options. A Worker Role instance can use the information available to it via API to discover the size of the role and its own instance ID. It can also subscribe to notifications and query about changes to the size of the role and individual instances joining and leaving. Based on that information, an instance can deterministically pick a set of queues/partitions to pull events from, in such a way that the responsibilities are divided and balanced across all available instances.

That's the basic premise. It can be refined further to optimize for failover time or avoiding duplicate events. You can look at the set of queue balancers we have in streaming that make different tradeoffs there.

**Comment by sergeybykov** [comment]
It should be more efficient to run and scale out them together. If you want to isolate the ingestion work from processing, that's a different reason, but at the expense of efficiency in my opinion.
