### ISSUE TITLE
Difficulties Moving from [RegisterSerializer] to [Serializer]

### ISSUE THREAD

**Issue by morwn** [dotnet/orleans#3087]
Hey,
[RegisterSerializer] allow me to dynamically registers others serialization types by the static Register method.
As you can see, in my case I register all the derived types:
```
public static void Register()
        {
            // go over all derived types and register the serializer for all of them
            var derivedTypes = from t in typeof(MyCustomType).Assembly.GetTypes()
                              where t.IsClass && !t.IsAbstract && typeof(MyCustomType).IsAssignableFrom(t)
                              select t;

            foreach (var derived in derivedTypes)
            {
                SerializationManager.Register(derived, DeepCopier, Serializer, Deserializer);
            }
        }
```

its works fine.

But with [Serializer] I had Difficulties, First I must declare at the class attribute a specific types and Second I didn't have the static Register method for handling my dynamic initialization.

Thanks for helping

**Comment by ReubenBond** [comment]
Hi @morwn, apologies for the slow reply.

There is another approach which you can use: `IExternalSerializer`. You can create a `HashMap<T>` of all the types which you support in the constructor or `Initialize` method and in the `IsSupportedType` method you can return true if `supportedTypes.Contains(t)`.

Does that help?
