### ISSUE TITLE
StopOrleans in UtilityFunctions.ps1 - Get-WmiObject filter needs ".exe"

### ISSUE THREAD

**Issue by crwells** [dotnet/orleans#3089]
In UtilityFunctions.ps1, the StopOrleans function uses Get-WmiObject to see if the process is still running.  This seems to always report that the process isn't running because it is only looking for (as an example) "OrleansHost" instead of "OrleansHost.exe".  If I change the "Program ExecName" in Deployment.xml to include the ".exe" then the other deployment scripts don't run correctly.  I think the code in UtilityFunctions.ps1 needs to be as follows:

$command = "Get-WmiObject Win32_Process -ComputerName $machineList -filter ""name='$exeName.exe'"""

**Comment by sergeybykov** [comment]
@crwells These scripts are very outdated and assume OrleansHost.exe (even if with the bug you pointed), which we are looking to deprecate altogether soon. But if you can submit a PR with a fix, that would be appreciated. Thank you.
