### ISSUE TITLE
Azure CPU usage-- typical?

### ISSUE THREAD

**Issue by jptaylor226** [dotnet/orleans#309]
My scenario is that I have two workers, hosting silos, and one web api with this configuration:

<poem>
&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;ServiceDefinition name="HanoiCloud" xmlns="http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition" schemaVersion="2014-06.2.4"&gt;
  &lt;WorkerRole name="HanoiWorker" vmsize="Medium"&gt;
    &lt;ConfigurationSettings&gt;
      &lt;Setting name="DataConnectionString" /&gt;
    &lt;/ConfigurationSettings&gt;
    &lt;LocalResources&gt;
      &lt;LocalStorage name="LocalStoreDirectory" cleanOnRoleRecycle="false" /&gt;
    &lt;/LocalResources&gt;
    &lt;Endpoints&gt;
      &lt;InternalEndpoint name="OrleansSiloEndpoint" protocol="tcp" port="11111" /&gt;
      &lt;InternalEndpoint name="OrleansProxyEndpoint" protocol="tcp" port="30000" /&gt;
    &lt;/Endpoints&gt;
  &lt;/WorkerRole&gt;
  &lt;WorkerRole name="MonasteryRole" vmsize="Small"&gt;
    &lt;Endpoints&gt;
      &lt;InputEndpoint name="Endpoint1" protocol="http" port="80" localPort="80" /&gt;
    &lt;/Endpoints&gt;
  &lt;/WorkerRole&gt;
&lt;/ServiceDefinition&gt;
</poem>

I'm not performing any load testing-- there are no clients making requests through the Api or calls forwarded from the Api to the silo hosting "HanoiWorker"s.  

Yet, when deployed and active, my CPU usage seems really high-- I'm expecting it to be near 0, but 51% and 99% seem really off-base:
![image](https://cloud.githubusercontent.com/assets/11837591/7049667/e57a4c18-dde0-11e4-9a5a-b3f4a26e3d82.png)

Being a neophyte, am I doing something obviously wrong?

**Comment by jptaylor226** [comment]
Note for the curious regarding use of "Hanoi" and "Monastery"-- I'm implementing the recursive classic "Towers of Hanoi" problem-- it seems a quick way to recursively spawn millions of grains and watch what happens when they're tagged as StatelessWorkers, etc.  If I were more sophisticated, I'd be running FFTs.

**Comment by gabikliot** [comment]
I don't understand: are you saying you have a silo to which you do not send ANY requests and still it's CPU is 99%?
This of course should not be happening.
Can you please send the full silo log? From the log we will most surely be able to figure out what is wrong. You can also send the client log, it will be useful.

**Comment by gabikliot** [comment]
We also do not recommend using small or medium. We recommend using extra larges.

**Comment by jptaylor226** [comment]
Well, I definitely violated the framework by including static members within a Grain subclass.  As soon as those were removed, CPU usage became reasonable. [3%-5%]  Statics are clearly not appropriate, was just surprised they would be so impactful.

**Comment by gabikliot** [comment]
Ye, I am also surprised that statics would have perf. impact. They violate grain isolation, but I don't see how they could have impacted perf. Unless you spin lock on them or do some locking that somehow caused threads to spin wild.
