### ISSUE TITLE
awaiting SMSProvider inconsistency between silo and TestCluster

### ISSUE THREAD

**Issue by shlomiw** [dotnet/orleans#3105]
Hi,
I'm not sure how important is it, but it got me confused for long time until I understood why my Grains where stuck in TestCluster, in-contrast to normal silo execution.

Eventually I found out that if you `await smsStream.OnNextAsync()` in the producer:
- Normal silo host - will continue immediately, as expected!
- TestCluster - will **wait** until the stream consumer will finish its work. 
i.e. in the consumer can be Grain with `ImplicitStreamSubscription` and in the `OnNextAsync` method just have `await Task.Delay()'` to simulate it.

The TestCluster behavior was totally unexpected for me.

What do you think?

**Comment by sergeybykov** [comment]
Unless the stream provider in `TestCluster` is configured as `FireAndForgetDelivery=true`, the behavior should be identical.

**Comment by shlomiw** [comment]
@sergeybykov - I'm happy to confirm that you nailed it! that was exactly the difference.

In the normal silo I've followed the example of adding SMSProvider:
```
   <StorageProviders>
      <Provider Type="Orleans.Storage.MemoryStorage" Name="Default" />
      <Provider Type="Orleans.Storage.MemoryStorage" Name="PubSubStore" />
    </StorageProviders>
    <StreamProviders>
      <!-- Simple Message Stream (SMS) Provider -->      
      <Provider Type="Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProvider" Name="SMSProvider" FireAndForgetDelivery="true"/>
    </StreamProviders>
```
Which has `FireAndForgetDelivery="true"`.

And in `TestCluster`:
I've configured:
```
            TestClusterOptions options = new TestClusterOptions();
            var clusterConfig = options.ClusterConfiguration;      
            // config stream
            clusterConfig.AddMemoryStorageProvider("PubSubStore");
            clusterConfig.Globals.RegisterStreamProvider<SimpleMessageStreamProvider>("SMSProvider");  
```
Which set the `FireAndForgetDelivery` by default as false.

Many thanks!
