### ISSUE TITLE
Cannot delete/upgrade Orleans deployed to SF in timely fashion

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#3106]
Steps to reproduce:
1) Unpack attached OrleansSF.zip
2) Set "MainTableStorage" in "ApplicationParameters/Development.xml" and "ClusterConnectionParameters" in "PublishProfiles/Development.xml"
3) Deploy to Azure SF cluster
4) Once deployed, try to delete it (or upgrade to other version)

[OrleansSF.zip](https://github.com/dotnet/orleans/files/1062048/OrleansSF.zip)

The deletion or upgrade hangs then. In SF explorer, I can see the following warning:
```
Unhealthy event: SourceId='System.RAP', Property='IStatelessServiceInstance.CloseDuration', HealthState='Warning', ConsiderWarningAsError=false.
```

The only thing that helps is to kill the service processes on SF nodes.

**Comment by DixonDs** [comment]
I left it overnight and still not deleted. Other warning from the Naming service:
```
Unhealthy event: SourceId='System.NamingService', Property='Duration_AODeleteService.fabric:/OrleansSF/Orleans', HealthState='Warning', ConsiderWarningAsError=false.
The AODeleteService started at 2017-06-08 19:14:09.245 is taking longer than 30:00.000.
```

**Comment by DixonDs** [comment]
Removing Dashboard helps, so it might be connected to this issue https://github.com/OrleansContrib/OrleansDashboard/issues/43 

Still, even if some bootstrapper misbehaves, there must be some fault-tolerant mechanism in Orleans itself to prevent this kind of hanging.

**Comment by sergeybykov** [comment]
>Removing Dashboard helps

Does upgrading to 1.4.12 of `Dashboard` where https://github.com/OrleansContrib/OrleansDashboard/issues/43 was addressed help?

**Comment by DixonDs** [comment]
@sergeybykov yes, it does
