### ISSUE TITLE
Orleans 2 (w/ .netCore): Exception = System.TypeAccessException

### ISSUE THREAD

**Issue by pfrendo** [dotnet/orleans#3110]
When loading multiple instances of a Silo I get  a ```System.TypeAccessException``` exception. 

I am accessing some types and a grain which are found in two different libraries, I have also tried to forcefully load both assemblies before the silo starts up but this had no effect.

My structure is as follows:

    ContentModels
          - Models

    SharedGrains(Class Library)
          - ContentGrain (Accesses ContentModels)

     Microservice
         - Grains - Which access ContentGrain(This is where the exception happens) & ContentModels 
         - Grain Contracts
         - Silo
         - WebApi

Here are the full logs:
https://gist.github.com/pfrendo/587bc9e57a37f064d190bc1b2b412dab

**Comment by pfrendo** [comment]
@ReubenBond @sergeybykov

**Comment by pfrendo** [comment]
Update on this issue
-----------------------------------------------------

Moving the ContentGrain (that were in SharedGrains) directly where they are being created and used does not solve the issue.

**Comment by pfrendo** [comment]
Update
-----------------------------------------------------------------

Found a work around by doing the following:
```
var assembly = typeof(<use an externally referenced model here>).GetTypeInfo().Assembly;
var assemblyName = AssemblyLoadContext.GetAssemblyName(assembly.Location);
```

a nicer/safer version of this would be
```
var entryAssembly = Assembly.GetEntryAssembly();
var referencedAssemblies = entryAssembly.GetReferencedAssemblies().Where(x => x.Name.StartsWith(<Library Namespace Here>));

foreach (var referencedAssembly in referencedAssemblies)
{
	Assembly.Load(referencedAssembly);
}
```

**Comment by pfrendo** [comment]
Update
---------------------------

While the above fix did make it more stable, it still does occur :( any help on this would be appreciated

**Comment by ReubenBond** [comment]
@pfrendo 
> after an X amount of time it still does occur

The exact same error, or is it a different type?

**Comment by ReubenBond** [comment]
You're running on Docker, but what is your build environment, Linux or Windows? I'm looking into logs from @stephenlautier in which the silo succeeded to start. Hopefully I can also see some logs from a failed run, but maybe that will have to wait until another day.

**Comment by ReubenBond** [comment]
Could you show me the declaration of `PaymentMethodContentModel`? Is it abstract?

**Comment by pfrendo** [comment]
@ReubenBond so the error is still the same. A silo NEVER fails to start it is a run time exception which occurs after a while and just give a serialize error. 

```PaymentMethodContentModel``` is only a model and is not abstract, but no it has no ```[Serializable]```.

The thing I don't understand is that it works for a span of time....

**Comment by ReubenBond** [comment]
@pfrendo are you sure it works for a span of time - are you saying that not every invocation of that method fails? I don't believe that there's a serializer being generated for that type. What happens when you put `[Serializable]` on it? Are you using build time code generation? What's your build environment?

**Comment by pfrendo** [comment]
@ReubenBond , it does look like no serializer is being created (as it's being created for the models found within the same solution). I will try to put ```[Serializable]``` for it and see what happens. 

My build environment is basically docker swarm on AWS (linux based).... Is that what you meant by build env?

**Comment by pfrendo** [comment]
@ReubenBond good news !! 

Putting ```[Serializable]``` on the models along with the assembly loading has worked :D !!!!!

**Comment by ReubenBond** [comment]
Great to hear, @pfrendo! Am I correct in assuming that `PaymentMethodContentModel` does not appear in any grain interfaces as either an parameter or a return value? I'll look into this further anyhow

**Comment by pfrendo** [comment]
@ReubenBond correct I am only using it to pass in a type to a method so I can serialize accordingly
