### ISSUE TITLE
Startup Error logging needs configuration options

### ISSUE THREAD

**Issue by chris-eaton** [dotnet/orleans#3111]
In my recent testing I come across scenarios where a deployment to a staging environment has a bug for some reason.  What happens then is Orleans tries to start but fails in some way so it writes a log for each failure.

As its running as a service it keeps spinning and the result is 100,000s of log files, each labelled as StartupError which is both [a] hard to manage and [b] hard to delete. In fact when my build server tries to deploy a fix it fails because theres that many log files.  Last I checked today we had over 600k and 1.5gb, solely in these `StartupErrors`.

Having [looked at the code](https://github.com/dotnet/orleans/blob/7cf2035e868e81b90767d7aff748405d01145117/src/OrleansRuntime/Silo/SiloHost.cs#L421) I see there is no way to configure it.

Could we perhaps look at either making it write only one log file per hour|day or allowing it to delete files after some period or allow some configuration of it... Currently its unmanageable :)

**Comment by sergeybykov** [comment]
I would expect a silo to create a log file per startup attempt. Are you seeing more than that? I don't understand - what keeps trying to start the silo so many times?

You can disable writing logs to file altogether, but sounds like you are looking for something else. I don't see a silo being responsible for deleting old log files. It seems to me that should be done by the deployment infrastructure.

**Comment by chris-eaton** [comment]
Because im running it as a service, if it fails during Orleans startup it crashes out and the service restarts it.  This generated, over a few hours, 1.6million log files :)

I can write something to clear it up myself, but to know that I need to do this I need to encounter this problem, then look to Orleans for a solution and then decide to write my own. I thought it sounds like something many people would benefit from.

**Comment by sergeybykov** [comment]
>Because im running it as a service, if it fails during Orleans startup it crashes out and the service restarts it. 

The service was restarting the silo that kept crashing and made about a million attempts to do that? Is that what happened? If that's the case, I imagine you want to protect from a situation like that regardless of the issue with log files.

In my opinion, it is a dangerous proposition to have silo delete some files from the file system, and assume that they aren't needed.
