### ISSUE TITLE
Managing the reminders list from the application code

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#3115]
Is it possible to access the list of reminders from the application code? There is `IReminderTableGrain` (https://github.com/dotnet/orleans/blob/27b2a10a8c0dc44dfe839ae5fa638059828cd747/src/Orleans/SystemTargetInterfaces/IReminderTable.cs) but it is internal.

The reason I ask is to assist this feature request for Orleans Dashboard: https://github.com/OrleansContrib/OrleansDashboard/issues/51

**Comment by sergeybykov** [comment]
`IReminderTableGrain` is simply an unreliable in-memory storage for reminders intended for dev/test scenarios. `IReminderService` is a low level runtime API for manipulating reminders.

**Comment by DixonDs** [comment]
@sergeybykov Could you please show me some example in Orleans codebase how to get and use `IReminderService`?

**Comment by sergeybykov** [comment]
@DixonDs Take a look at `ReminderRegistry` class.

**Comment by DixonDs** [comment]
In result, I've found out that `IReminderTable` is injected by the runtime in 1.5.0, that allowed to add reminders to Dashboard.
