### ISSUE TITLE
Cannot find an implementation class for grain interface

### ISSUE THREAD

**Issue by zyisilvan** [dotnet/orleans#3121]
I am new to Orleans and I met this error for my first project. The message was : "Exc level 2: System.ArgumentException: Cannot find an implementation class for grain interface: Project.Grains.HelloEnvironmentHelloGrain. Make sure the grain assembly was correctly deployed and loaded in the silo. Loaded grain assemblies:  file:///C:/SfDevCluster/Data/_App/_Node_2/ProjectType_App35/StatelessSiloPkg.Code.1.0.0/OrleansRuntime.DLL file:///C:/SfDevCluster/Data/_App/_Node_2/ProjectType_App35/StatelessSiloPkg.Code.1.0.0/Project.Grains.DLL"

I looked at the dll with ILSpy, it does contain the implementation of the class. After 2 hours searching online and debugging offline, I figure out providerRuntime.GrainFactory.GetGrain<T> only takes interface in the as the generic type, not the actual class. Maybe this is not the root cause, but it solves the problem. 

It would be very helpful to make a type validation on the GetGrain calls or throw some more precise error message.

**Comment by chris-eaton** [comment]
Hi.. Yes you are correct, GetGrain only accepts an interface as a type i.e.

`var g = this.GrainFactory.GetGrain<IMyAwesomeGrain>(0);`

**Comment by sergeybykov** [comment]
@zyisilvan To make sure I understand correctly. Did you get the exception when you called `GetGrain<HelloEnvironmentHelloGrain>` instead of `GetGrain<IHelloEnvironmentHelloGrain>`?

**Comment by zyisilvan** [comment]
@sergeybykov Yes I got the error when I call GetGrain<HelloEnvironmentHelloGrain> where HelloEnvironmentHelloGrain is a class instead of an interface

**Comment by sergeybykov** [comment]
Thanks for confirming!
