### ISSUE TITLE
Null reference when deserializing State

### ISSUE THREAD

**Issue by mauriciomagni** [dotnet/orleans#3131]
Hello
I have changed a state object, adding a string property (Slot), below is current version:
```C#
    public class EnvironmentData
    {
       public string DbConnectionString { get; set; }
        public string StorageConnectionString { get; set; }
       public string Slot { get; set; } //added property
     }
```

This is the generated code that raises the error:
```C#
        [global::Orleans.CodeGeneration.DeserializerMethodAttribute]
        public static global::System.Object Deserializer(global::System.Type expected, global::Orleans.Serialization.IDeserializationContext context)
        {
            global::Visible.EnvironmentData result = new global::Visible.EnvironmentData();
            context.@RecordObject(result);
            result.@DbConnectionString = (global::System.String)global::Orleans.Serialization.SerializationManager.@DeserializeInner(typeof (global::System.String), context);
            result.@StorageConnectionString = (global::System.String)global::Orleans.Serialization.SerializationManager.@DeserializeInner(typeof (global::System.String), context);
            setField2(result, (global::System.String)global::Orleans.Serialization.SerializationManager.@DeserializeInner(typeof (global::System.String), context));
            return (global::Visible.EnvironmentData)result;
        }
```

the error is raise by the line: `setField2(result,...`
the error message is: `System.NullReferenceException: 'Object reference not set to an instance of an object.'`

The stack trace is:
```
"   at Orleans.Serialization.BinaryTokenStreamReader.TryReadSimpleType(Object& result, SerializationTokenType& token)\r\n   
at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)\r\n   
at Visible.OrleansCodeGenVisible_EnvironmentDataSerializer.Deserializer(Type expected, IDeserializationContext context) in C:\\Virtusway\\Development\\VisibleSuite\\Suite\\Server\\Biz\\obj\\Debug\\Visible.Server.Biz.orleans.g.cs:line 196\r\n   
at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)\r\n   
at Orleans.Serialization.SerializationManager.DeserializeInner[T](IDeserializationContext context)\r\n   
at Orleans.Serialization.SerializationManager.DeserializeFromByteArray[T](Byte[] data)\r\n   
at Orleans.Storage.AzureTableStorage.ConvertFromStorageFormat(DynamicTableEntity entity)"
```

I was using Orleans 1.4.1 and upgraded to 1.4.2 but that did not solve the issue.

I have added this code in order to overcome the error:
```C#
        protected override async Task ReadStateAsync()
        {
            try
            {
                await base.ReadStateAsync();
            }
            catch
            {
                await ClearStateAsync();
            }
        }
```
but this did not solve the issue either.
Any help will be greatly appreciated.
Kind regards

**Comment by ReubenBond** [comment]
Hi @mauriciomagni, just so I'm clear, your scenario is:
* Serialize some state
* Change the class definition to add a new property
* Attempt to deserialize that state

Is that correct?

**Comment by mauriciomagni** [comment]
Hello @ReubenBond
Your anderstanding is correct.

**Comment by ReubenBond** [comment]
@mauriciomagni unfortunately the current default serializer does not support version tolerance, meaning that these changes are not supported. We plan to remedy this in an upcoming release. In the meantime, please take a look at the serialization documentation and configure either Protocol Buffers or Bond as the serializer for your types - this may require modifying your types to support the chosen serializer https://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Serialization.html

I hope that helps. #2653 is assigned to me and when it is resolved, we will have a better story here.
