### ISSUE TITLE
Grain<T>.ReadStateAsync is not called before OnActivateAsync 

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#3137]
I feel confused, I always thought `Grain<T>.ReadStateAsync` was called before `OnActivateAsync` if overridden. And basically the docs state the same (http://dotnet.github.io/orleans/Documentation/Getting-Started-With-Orleans/Grain-LifeCycle.html): 

> If a grain class uses declarative persistence by inheriting from Grain<T>, the Orleans runtime automatically loads state of grain of that class as part of the activation process by calling ReadStateAsync before invoking OnActivateAsync and processing a request to the grain

But somehow it doesn't seem to be the case. Looking at code at https://github.com/dotnet/orleans/blob/cf4afe936912221864b90a8a950d45ba14b46cb9/src/OrleansRuntime/Catalog/Catalog.cs#L939 , it looks like `ReadStateAsync` is called directly on the storage provider, not `Grain<T>.ReadStateAsync`. What am I missing here?

**Comment by sergeybykov** [comment]
It does sound confusing. I think it meant to say that the state is loaded before `OnActivateAsync` is called. I don't remember if we actually ever called it on the grain object during activation. Maybe in some early versions. I think it is dangerous to call a virtual method of a grain before it is activated.

We are also looking to introduce very soon a new model of facets that would be suitable for state management (that will also enable multiple pieces of state per grain) and other kinds of extensibilities. In that world, I think it will make even less sense to call a virtual method on a grain for each kind of facet.

I think we should just correct the docs here.

**Comment by DixonDs** [comment]
>I think it is dangerous to call a virtual method of a grain before it is activated.

Could you elaborate why if it is a method that is clearly designed to handle reading the state?

Anyway, I am fine with either way as long as the docs reflect the truth :)

**Comment by sergeybykov** [comment]
The way we've been explaining `OnActivateAsync` is that it's like a "constructor" for a grain activation. Hence, it's kind of easier to think that that's when the grain code gets control from the runtime for its initialization. Giving grain code control before it is considered by the runtime ready for execution may potentially lead to confusion. That's the concern.
