### ISSUE TITLE
Flag Postgresql as synchronous in RelationalStorage to avoid deadlocking

### ISSUE THREAD

**Issue by veikkoeeva** [dotnet/orleans#3141]
This is related to https://github.com/dotnet/orleans/pull/2949. It appears the Npsql provider has similar problems to MySQL one, the fix is [to flag it likewise](https://gitter.im/dotnet/orleans?at=59445bb6f31c8ced0c42e583). More information at findings at Gitter discussion at https://gitter.im/dotnet/orleans?at=59445bb6f31c8ced0c42e583.

**Comment by jdom** [comment]
I think this is a good safe approach until https://github.com/npgsql/npgsql/issues/1130 is fixed.

PR at https://github.com/dotnet/orleans/pull/3164
