### ISSUE TITLE
Allow passing additional endpoints from OrleansCommunicationListener.OpenAsync result

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#3142]
We use OlreansDashboard using auto-assigned port by SF, so it would be helpful if that information is included in `OpenAsync` result so that it can be seen in the SF explorer. 

I guess there could be different ways to achieve that. For example, `OrleansCommunicationListener` could accept info about additional endpoints being used in the constructor (it could be `List<EndpointResourceDescription>`) or there could be some extension point added in `OrleansCommunicationListener` so that it could be overridden in subclasses.

**Comment by ReubenBond** [comment]
Interesting request. How do you think this should be exposed and how would you consume it? It seems the dashboard should be a separate communication listener and hence return its own endpoints.

I'm not dismissing this at all - just exploring the idea.

**Comment by DixonDs** [comment]
Currently, Dashboard is implemented as a silo bootstrapper opening a port, so I think currently it cannot be a separate communication listener. Maybe if Dashboard could be separated from silo, for instance, by using a grain client to communicate with it, it would be possible to use a separate listener or even host it as a separate SF service. But that's different discussion.

As for OrleansCommunicationListener, maybe the part where `OpenAsync` result object is created could be exposed as a virtual method? Something like
```
protected virtual object GetEndpointInfo(ClusterConfiguration clusterConfiguration, NodeConfiguration nodeConfiguration)
{
	return new FabricSiloInfo(this.SiloHost.NodeConfig);
}
```
and to be used in `OpenAsync` as 
```
return Task.FromResult(JsonConvert.SerializeObject(GetEndpointInfo(configuration, this.SiloHost.NodeConfig)));
```

I am not sure what is the best way to make that extension point, but if none of the options seem good enough, maybe we can at least make 'OpenAsync` virtual?

**Comment by rikbosch** [comment]
@DixonDs as a workaround we created a no-op communicationlistener, which just registers the listener, so it is known within SF:

```csharp
  /// <summary>
    /// workaround for dynamic http dashboard port
    /// </summary>
    internal class OrleansDashboardCommunicationListener : ICommunicationListener
    {
        private StatelessServiceContext _context;

        public OrleansDashboardCommunicationListener(StatelessServiceContext context)
        {
            _context = context;
        }

        public Task<string> OpenAsync(CancellationToken cancellationToken)
        {
            var endpoint = _context.CodePackageActivationContext.GetEndpoint("OrleansDashboardEndpoint");

            return Task.FromResult(
                $"http://{FabricRuntime.GetNodeContext().IPAddressOrFQDN}:{endpoint.Port}");
        }

        public Task CloseAsync(CancellationToken cancellationToken)
        {
            //noop
            return Task.CompletedTask;
        }

        public void Abort()
        {
            //noop
        }
    }
```

**Comment by ReubenBond** [comment]
@rikbosch @DixonDs I think the above workaround is the correct approach to take. I'll close this for now, but we can reopen it if desired.

**Comment by DixonDs** [comment]
@ReubenBond it doesn't sound right to me that a workaround could be a correct approach, but I am fine with closing the issue

**Comment by ReubenBond** [comment]
I was going to put quotes around "workaround", since I think that the workaround makes sense over modifying the core to add extensibility for piggybacking additional endpoints.

However, we can consider adding some free-form `string->object` dictionary to the value returned by the main `ICommunicationsListener` which you can customize using DI if you feel it would be better.

**Comment by DixonDs** [comment]
@ReubenBond I believe it should, thanks.
