### ISSUE TITLE
Rollback Journaled Grain State Using Events

### ISSUE THREAD

**Issue by charleszipp** [dotnet/orleans#3143]
I am looking at using orleans journaled grains to be part of our CQRS + Event sourcing architecture. Journaled grains would be responsible for executing commands that will eventually update state and be replicated (via stream) to the read store. 

Part of the command processing requirement is to have distributed transaction rollback. If we are executing a tree of commands and part of those commands execute on the same level, in parallel, i need a means to implement a strategy where if one fails, i can rollback the others than run on the same level.

- update account amount
-- update sub total
-- update grand total (fails!)

In this case, both the update of the sub total and grand total can run in parallel and are managed by different actors. If one fails i want to rollback the other.

I was wondering if this would be possible to rollback to an earlier state by using the events stored for the journaled grain. Is there something in the journaled grain api that would allow for this?

**Comment by jdom** [comment]
looping @jason-bragg and @sebastianburckhardt, as they are actually looking at these scenarios

**Comment by sebastianburckhardt** [comment]
The journaled grain API does not allow rollback of events - the event log is immutable and can only grow.

You can however implement roll-back at the application level. 

For example, you can do something along the lines of 

```csharp
class StateWithRollback
{
    ApplicationState stableState;
    List<ApplicationEvent> tentativeEvents;

    void Apply(AddEvent e) { 
        tentativeEvent.Add(e.Event) }
    }
    void Apply(ConfirmEvent e) { 
        foreach(var e in tentativeEvents)
            stableState.Apply(e);
        tentativeEvents.Clear();
    }
    void Apply(RollbackEvent e) {  
        tentativeEvents.Clear();
    }
}
class AddEvent { ApplicationEvent Event { get;set; }}
class ConfirmEvent { }
class RollbackEvent{ }
```

In fact, this is similar to what we do for our general-purpose transaction support that we are working on currently.

**Comment by charleszipp** [comment]
Thanks for the @sebastianburckhardt ! Closing this
