### ISSUE TITLE
How to install Orleans documentation is confusing!

### ISSUE THREAD

**Issue by nehmebilal** [dotnet/orleans#3144]
I was trying to find out what is the latest recommended way of installing Orleans. Even for someone who's familiar with Orleans, I got quickly confused.

The [My First Orleans Application](https://dotnet.github.io/orleans/Tutorials/My-First-Orleans-Application.html) recommends using the project templates (i.e. install the SDK).

The [Minimal Orleans Application](https://dotnet.github.io/orleans/Tutorials/Minimal-Orleans-Application.html) tutorial shows the NuGets approach but hints to that it may not be production ready.

The README page makes it clear that the NuGets is the way to go.

I think it would make sense that the [My First Orleans Application](https://dotnet.github.io/orleans/Tutorials/My-First-Orleans-Application.html), which is the first place that most people are going to look at, shows the latest approach of installing Orleans.

**Comment by dandago** [comment]
I had the same problem when learning Orleans. In fact I wrote "[Getting Started With Microsoft Orleans](http://gigi.nullneuron.net/gigilabs/getting-started-with-microsoft-orleans/)" specifically because the things you need to set up a basic Orleans application are scattered throughout the documentation. Hopefully that might help until the documentation is updated.

**Comment by nehmebilal** [comment]
@dandago That looks pretty good!

**Comment by JillHeaden** [comment]
@nehmebilal @dandago 
I have created Tutorial 1 and incorporated information I learned from @xiazen  along the way into the Hello World overview.

http://dotnet.github.io/orleans/Documentation/tutorials_and_samples/index.html

I would like to know if you think that this is a good starting place to continue writing Orleans tutorials and whether you think this satisfies the original request.
