### ISSUE TITLE
GetPrimaryKeyString throwing during unit-tests even when IGrainIdentity is injected.

### ISSUE THREAD

**Issue by luciobemquerer** [dotnet/orleans#3145]
Sometimes we need to call `GrainExtensions.GetPrimaryKeyString()` from within the grain to retrieve the grain PK, in most cases to enhance logs and make debugging easier.

All our unit tests inject `IGrainIdentity` through the Grain constructor, however calling `GrainExtensions.GetPrimaryKeyString()` - and other `GrainExtensions` methods as well - during unit tests result in an `ArgumentException` being thrown at [GrainExtensions:91](https://github.com/dotnet/orleans/blob/d631957a73a7923ec11b2874066d5ae98fdb23f9/src/Orleans/Core/GrainExtensions.cs#L91) 

Stepping in the debugger reveals that the internal property `Grain.Data` is null, which is the reason why the method throws. Checking the source code for this property, we found the following comment:

```
        // Do not use this directly because we currently don't provide a way to inject it;
        // any interaction with it will result in non unit-testable code. Any behaviour that can be accessed 
        // from within client code (including subclasses of this class), should be exposed through IGrainRuntime.
        // The better solution is to refactor this interface and make it injectable through the constructor.
        internal IActivationData Data;
```

[Link](https://github.com/dotnet/orleans/blob/3785b957958ecec39f58492aebbcb81d64bb8a14/src/Orleans/Core/Grain.cs#L19)

It doesn't cause any problems for grains running in a proper cluster. And is also somehow easy to work-around the problem by wrapping `GrainExtensions.GetPrimaryKeyString()` with `try-catch`, but it is not usually a good idea to modify the code-base in order to work-around unit-testing issues.

Is there any proper way of retrieving the grain PK that can be used in both production and unit-test runtimes? Would there be any problems if `GrainExtensions.GetGrainId()` accessed `Grain.Identity` instead of `Grain.Data.Identity`?

**Comment by dandago** [comment]
I use a simple workaround to encapsulate the primary key extension methods in such a way that I can easily mock them. Refer to [this issue](https://github.com/dotnet/orleans/issues/3086), look for `GrainIdService`. You can use it in combination with DI to mock it for your unit tests.
