### ISSUE TITLE
Injecting IGrainIdentity/IGrainRuntime not working

### ISSUE THREAD

**Issue by kumbhare** [dotnet/orleans#3148]
To be able to unit test the grain, we are using constructor injection for IGrainIdentity and IGrainRuntime as suggested in #443.
```
        public UserGrain(IGrainIdentity identity, IGrainRuntime runtime) : base(identity, runtime)
        {
        }
```

But when I run silo and call a grain function, we see the following error:
```
    "InnerException": {
      "Message": "An error has occurred.",
      "ExceptionMessage": "Unable to resolve service for type 'Orleans.Core.IGrainIdentity' while attempting to activate 'Treehouse.Grains.UserGrain'.",
      "ExceptionType": "System.InvalidOperationException",
      "StackTrace": "   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)\r\n   at lambda_method(Closure , IServiceProvider , Object[] )\r\n   at Orleans.Runtime.GrainCreator.CreateGrainInstance(Type grainType, IGrainIdentity identity)\r\n   at Orleans.Runtime.Catalog.CreateGrainInstance(String grainTypeName, ActivationData data, String genericArguments)\r\n   at Orleans.Runtime.Catalog.SetupActivationInstance(ActivationData result, String grainType, String genericArguments)\r\n   at Orleans.Runtime.Catalog.GetOrCreateActivation(ActivationAddress address, Boolean newPlacement, String grainType, String genericArguments, Dictionary`2 requestContextData, Task& activatedPromise)\r\n   at Orleans.Runtime.Dispatcher.ReceiveMessage(Message message)"
    }
```

Note that, we have setup DI using the startup configuration, and can inject our own services. Here if I have a constructor with IUserOprations, it is injected as expected.

```
    public class Startup
    {
        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<IUserOperations, UserOperations>();

            return services.BuildServiceProvider();
        }
    }
```
```
OrleansServerConfiguration:
<Defaults>
    <Startup Type="My.Silos.Startup,My.Silos" />
  </Defaults>
```
```
 config.UseStartupType<Startup>();
 silo = new AzureSilo();
 bool ok = silo.Start(config);
```
We have tried:
1. Add a parameterless constructor, with DI enabled gives following error
```
InnerException": {
      "Message": "An error has occurred.",
      "ExceptionMessage": "Multiple constructors accepting all given argument types have been found in type 'Treehouse.Grains.UserGrain'. There should only be one applicable constructor.",
      "ExceptionType": "System.InvalidOperationException",
      "StackTrace": "   at Microsoft.Extensions.Internal.ActivatorUtilities.FindApplicableConstructor(Type instanceType, Type[] argumentTypes, ConstructorInfo& matchingConstructor, Nullable`1[]& parameterMap)\r\n   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateFactory(Type instanceType, Type[] argumentTypes)\r\n   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactory(Type instanceType, Type[] argumentTypes)\r\n   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)\r\n   at Orleans.Runtime.GrainCreator.CreateGrainInstance(Type grainType, IGrainIdentity identity)\r\n   at Orleans.Runtime.Catalog.CreateGrainInstance(String grainTypeName, ActivationData data, String genericArguments)\r\n   at Orleans.Runtime.Catalog.SetupActivationInstance(ActivationData result, String grainType, String genericArguments)\r\n   at Orleans.Runtime.Catalog.GetOrCreateActivation(ActivationAddress address, Boolean newPlacement, String grainType, String genericArguments, Dictionary`2 requestContextData, Task& activatedPromise)\r\n   at Orleans.Runtime.Dispatcher.ReceiveMessage(Message message)"
    }
```

2. If we disable DI, and add parameterless constructor, grain creation works fine. But this is not acceptable since we would like to use DI for injecting our services.

What are we missing here? Is there some configuration to add in startup for IGrainIdentity/IGrainRuntime injection to work?

**Comment by DixonDs** [comment]
@dandago I might be not the best authority to answer, just trying to be helpful. `IGrainIdentity` is not injected by runtime, hence the first error you get. You need either to register `IGrainIdentity` on your own (which I imagine is not really possible) or remove it from the ctor.

Then it seems for some reason Orleans doesn't allows grains to have multiple public ctors, even though the service provider itself can be able to resolve it. If your goal is to have one ctor for the runtime and another one for unit tests, you can make the second ctor internal with `InternalsVisibleToAttribute` to allow the test project to access it.

**Comment by jdom** [comment]
Hi @kumbhare, what @DixonDs says is correct. `IGrainIdentity` is not automatically injected by DI. The base constructor mentioned in #443 is so that you can call it from your internal constructor when unit testing, but Orleans itself cannot use that constructor (yet). So the guidance given on having an internal constructor for your unit tests is spot on.

Having said that, we plan to support this scenario in the future by adding activation scoped services (see #2856), but because it didn't gain much traction from others yet, we plan to release it after 1.5 which is coming very soon, to minimize some risks.

**Comment by kumbhare** [comment]
Thanks @jdom and @DixonDs, the internal constructor approach works as expected. Will update that with scoped services #2856 once available.
