### ISSUE TITLE
Unexplained behaviour of a grain (related to incoming mailbox or double delivery?) 

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#3149]
We have some very strange and rare behaviour of a grain that somehow breaks our business logic.
We've seen this once or twice in total, but when this happens - it kills the grain functionality completely and we have to restart silo instance with stuck grain.

Some implementation details:

* We are hosting on top of Cloud Service so production and staging can't really talk to eachother and only area where 2 envs can conflict with eachother is Storage and blob etags.

* We are using @yevhen's StreamStone to capture and serialize all calls we are sending to almost any grain instance. * It has duplication detection enabled and we are using our base DTO's `MessageId` as unique id (it's defined like this `public string MessageId { get; set; } = Guid.NewGuid().ToString();` )

* When any of our grains receives a call with exactly same MessageId - Streamstone would throw an exception about concurrent write to Azure Table. This happens rarely and after the grain deactivation usually goes away as failed grain mailbox with such duplicated message will be discarded

So it works fine and keeps our grains dry and safe (not handling 100% duplicated messages).

But when we are doing a deployment - we sometimes get into a bit nasty situation - when both production and staging environments are online - our system is in a state of flux - we expect to see some duplication errors and recover from them (usually it's a copy of message pulled from Azure Queue by stream and processed on both Staging\Production envs with OK result on the first and Error result on the second try).

But today we observed some weird behaviour  - one of our grains stuck for 2 hours because same message with exactly same ID was delivered to it over and over again. And grain invocation (the code where message and ID are actually created) looks pretty safe:
```
var innerCommand = new InnerSyncSubscriptionAccountCommand(command.SecurityContext, command.SubscriptionAccountId, command.AccountData);
await getSubscriptionAccountGrain(innerCommand).Perform(innerCommand);
```
we always `new`-ing the message before sending it and there is a veeeery low chance that this object construction was generating exactly same Guid in `MesageId` field  for 2 hours straight (with 3 mins intervals).

And after duplicate detection happens - exception is being thrown in the recipient grain and grain is being explicitly deactivated (we are tracking activation and deactivation for some nasty grains and can see it had happened in logs after each exception). And after 3 mins reminder - the process starts again and ends up in exception again.

Based on my knowledge, I can't explain how that can happen for 2 hours straight.

So the question is - could it be that internal Orleans message\structure re-appears in the grain mailbox over and over again, persisting between grain instance deactivations? It may be that the same Grain activation happens on the same silo (thus in the same AppDomain, I assume).

The bad part of this bug is that it can be solved by rebooting that nasty silo. So it's clearly related to the state of the memory in app domain.

Does this problem description sounds and makes sense ? 
Happy to hear any thoughts and opinions.

**Comment by sergeybykov** [comment]
I'm trying to tease apart to understand what is going on here.

>So the question is - could it be that internal Orleans message\structure re-appears in the grain mailbox over and over again, persisting between grain instance deactivations?

No, there's no facility that would do that.

>usually it's a copy of message pulled from Azure Queue by stream and processed on both Staging\Production envs with OK result on the first and Error result on the second try).

This immediately attracted my attention. Is it possible that the message doesn't get deleted from the Azure Queue, and keeps reappearing there later?

I complete shot in the dark - do you use `Random` anywhere in generation of the message ID or something by chance? It's not thread-safe, and can get corrupted.

**Comment by centur** [comment]
>This immediately attracted my attention. Is it possible that the message doesn't get deleted from the Azure Queue, and keeps reappearing there later?

This specific scenario is driven by reminders. I mentioned queue message as an example where we can observe and assume that some duplication may happen. In the code example above we are always `new`-ing DTO message before sending it to the grain so there is no input message which ID can be mistakenly copied to trigger the problem above.

We are not using `Random` for `MessageID` generation, it's always `Guid.NewGuid()`, unless guid may use Random somehow internally. We do use `Random` from time to time but just to get a balanced Id for our proxies - e.g. we have proxy (which encapsulates "unit of work") but for independent events we are getting proxies with random ids in a given range like "Random Even integer in the range between 0 and 100"

**Comment by sergeybykov** [comment]
@centur Have you seen this issue reoccurring since? I'm really puzzled about what we can do here.

**Comment by centur** [comment]
No, not one since this issue open. But neither we understand or can identify how it appeared first time :(. If needed, you can close the issue to progress with milestone. It still will be searchable. Maybe later we or someone else get some more info and will post it here.

**Comment by sergeybykov** [comment]
Since I don't see what we could do here at the moment, I'll close it. Please reopen if new information surfaces.
