### ISSUE TITLE
Get grain interface or implementation type from GrainReference

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#3156]
Is is possible from the application code? This is again to assist https://github.com/OrleansContrib/OrleansDashboard/issues/51

/cc @richorama

**Comment by ReubenBond** [comment]
Yes, that should be possible using reflection. I wonder if it would make sense to have an API which provided some metadata about a grain reference. What kind of information would be useful? Would interface type and id be sufficient?

**Comment by DixonDs** [comment]
@ReubenBond 
>Would interface type and id be sufficient?

Ideally, implementation types would better, I think, because it would make easier to correlate reminders with the existing grain views on Dashboard, which all show implementation types, but even just interface types would be great.

**Comment by veikkoeeva** [comment]
@DixonDs Extracting IDs from the grain references, https://github.com/dotnet/orleans/blob/master/src/OrleansSQLUtils/Storage/Provider/AdoNetStorageProvider.cs#L513 might be useful. If there's a desire to remove assembly version etc., https://github.com/dotnet/orleans/blob/master/src/OrleansSQLUtils/Storage/Provider/AdoNetStorageProvider.cs#L537 might be useful too.

**Comment by richorama** [comment]
I believe something like this will convert a `GrainRef` to a string representation for human consumption: 

```c#
private static string PrimaryKeyAsString(GrainReference grainRef)
{
    if (grainRef.IsPrimaryKeyBasedOnLong())
    {
        // long
        var pk = grainRef.GetPrimaryKeyLong(out var ext).ToString();
        return $"{pk} + {ext}";
    }

    if (null != grainRef.GetPrimaryKeyString())
    {
        // string
        return grainRef.GetPrimaryKeyString();
    }
    
    // guid
    var guidPk = grainRef.GetPrimaryKey(out var guidExt).ToString();
    return $"{guidPk} + {guidExt}";
}
```

...please correct me if I'm wrong.

I'm still failing to understand how to convert a `GrainRef` to an interface name.

I can see an `InterfaceName` property, but it throws an exception saying it should be implemented in a deriving class.
