### ISSUE TITLE
ISiloStatusOracle is not registered in ServiceFabric Utils

### ISSUE THREAD

**Issue by rikbosch** [dotnet/orleans#3159]
ref https://github.com/OrleansContrib/OrleansDashboard/issues/47

SF utils uses a custom IMembershipOracle, but does not register the implementation as ISiloStatusOracle.

This causes problems in the ManagementGrain when using OrleansDashboard

**Comment by ReubenBond** [comment]
Thanks for reporting, I'll fix it asap
