### ISSUE TITLE
Alternative for GrainReference.FromKeyString

### ISSUE THREAD

**Issue by laredoza** [dotnet/orleans#3162]
Hi,

I see that from Orleans 1.5 GrainReference.FromKeyString is no longer a public method. In my MongoReminder implementation I currently have the following method:

```
private ReminderEntry Parse(RemindersCollection reminder)
        {
            if (reminder != null)
            {
                string grainId = reminder.GrainId;

                if (!string.IsNullOrEmpty(grainId))
                {
                    return new ReminderEntry
                               {
                                   GrainRef = GrainReference.FromKeyString(grainId),
                                   ReminderName = reminder.ReminderName,
                                   StartAt = reminder.StartTime,
                                   Period = TimeSpan.FromMilliseconds(reminder.Period),
                                   ETag = reminder.Version.ToString()
                               };
                }
            }

            return null;
        }
```

How would I get a similar result now?

Thanks in advance.

**Comment by laredoza** [comment]
I'm going to close this issue as I came right with it.

Added a constructor:
`
public MongoReminderTable(IGrainReferenceConverter grainReferenceConverter
{
     this.grainReferenceConverter = grainReferenceConverter;
 }
`
This injected object (grainReferenceConverter) has the required method which I needed.

**Comment by ReubenBond** [comment]
Oh, I was just writing a comment about the same thing :) Thank you, @laredoza

**Comment by laredoza** [comment]
No problem, I just discovered that Orleans 1.5 was released on the 6th, so this and an issue with the Storage Provider suddenly became real important :)
