### ISSUE TITLE
Adding OrleansCodeGenerator to a project breaks ValueTuple

### ISSUE THREAD

**Issue by Porges** [dotnet/orleans#3166]
Hi,

I have a fresh project that I've just started, to try out Orleans. I'm targeting .NET 4.7 and Orleans 1.5.0-rc.

Without OrleansCodeGenerator, the project builds fine (but I get the runtime error in #1335 when I try to contact a grain from the client). After adding it, the project fails to build, with:

    error CS8137: Cannot define a class or member that utilizes tuples because the compiler
    required type 'System.Runtime.CompilerServices.TupleElementNamesAttribute' cannot be found.
    Are you missing a reference?
    error CS8179: Predefined type 'System.ValueTuple`2' is not defined or imported

It seems like the code generator is forcing the project to reference 4.6 or something?

Adding a package reference to System.ValueTuple does *not* fix the problem. (It's already pulled in by Orleans.Server).

**Comment by ReubenBond** [comment]
@Porges (hey! :)) is a minimal repro for me to just create a new project and reference the ValueTuple package or is there something else I need to do?

**Comment by Porges** [comment]
(Sent to Reuben directly.)

**Comment by Porges** [comment]
This seems to be a Roslyn problem.

Updating to the (out-of-band?) version of ValueTuple 4.4.0-preview1-25305-02 makes this go away (4.3.0 is what you get when you install OrleansCodeGenerator usually, and 4.3.1 doesn't fix it).
