### ISSUE TITLE
ProxyingGateway with localhost does not work across machines

### ISSUE THREAD

**Issue by dandago** [dotnet/orleans#3169]
Say I have a basic configuration like this for my silo:

    <?xml version="1.0" encoding="utf-8"?>
    <OrleansConfiguration xmlns="urn:orleans">
      <Globals>
        <SeedNode Address="localhost" Port="11111" />
        <BootstrapProviders>
          <Provider Type="OrleansDashboard.Dashboard" Name="Dashboard" Port="8080" />
        </BootstrapProviders>
      </Globals>
      <Defaults>
        <Networking Address="localhost" Port="11111" />
        <ProxyingGateway Address="localhost" Port="30000" />
      </Defaults>
    </OrleansConfiguration>

If I open the firewall on the machine, I can connect from another machine to port 8080, but not to 30000.

If I change `localhost` to `0.0.0.0` (which presumably means `IpAddress.Any`) throughout, then I can telnet into both ports 8080 and 30000 from another machine, but an Orleans client still cannot connect to port 30000.

The only way I managed to get a client on one machine to talk to a silo on another is by specifying the actual machine name in the `Address` attribute.

I should be able to configure a silo to listen on any network interface without specifically speficying the machine name.

**Comment by sergeybykov** [comment]
Have you tried leaving `Address` empty?

**Comment by dandago** [comment]
I think so.

**Comment by sergeybykov** [comment]
@dandago I double-checked: if I change the config above to `Address=''`, the silo picks up its non-localhost IP address (if you are using the unreliable configuration, then you need to do the same for the `<SeedNode>` part. So long as port 30000 is open in the firewall, the client should be able to connect to it.
