### ISSUE TITLE
Strange performance drop on multi-hop

### ISSUE THREAD

**Issue by justmara** [dotnet/orleans#3177]
I've trying to start with Orleans but after creating simple test project I found it extremely slow with processing pretty decent scenario. I've spent two days localizing main slowdown factor and result confuses me: I totally cant explain it. 

Here is my [test project](https://github.com/justmara/orleans-test/tree/feature/count).
There is Web project 'Uploader' that creates new Generator task and starts it. Generator then sends massive amount of messages to single receiver (Tacker). When Tacker is done receiving all the messages it calls the Report() method of the sender. 
In this simple scenario my laptop shows about 10k requests per second, so calling it with "100000" will report something like this in Host's console: `upload stop: 00:00:09.9028321`.
But if I add another one link in this chain making it look like this: `Generator->Ticker->Tacker` performance drops to somewhere around 600 rps. Calling it with 100k will take ages so you can simple open `http://localhost:8080/` and check OrleansDashboard there.
`Ticker` makes nothing - only forwarding call to `Tacker` instance.

Where does this drop comes from? Am I doing something wrong (probably yes - I this is my first attempt of using Orleans).

Both cases can be checked in the Shared/Workers/Generator.cs file, [Start method](https://github.com/justmara/orleans-test/blob/feature/count/Workers/Generator.cs#L46) 

And needless to say that in both cases it tops CPU to 100% load of all cores.

**Comment by aprooks** [comment]
most probably performance drop is due to Generator awaiting whole chain of calls to be finished and overhead related to this.  Event if ticker is a stateless worker, chain becomes

**Comment by richorama** [comment]
I have cloned your repo and tried the sample. 

The raw performance I got for a count of 20000 was 21302ms (~1ms per call). I noticed that each call then makes a call back to the generator, so the number of methods calls made is 40k.

Your code makes each call one after the other, so (as far as I can tell) you're measuring the latency of 20000 calls to `ITacker` added together.

Have you considered testing Orleans by driving the load externally? i.e. have a multi-threaded program which directly calls a large pool of activations randomly? This would allow for parallelism in the message processing.

I also saw 100% CPU, which I can't explain.

I'd also disable the dashboard if you want to measure the best possible performance :¬)

**Comment by justmara** [comment]
@richorama :) I am not measuring performance here now, but trying to display a problem.
Surely I understand, that in case of full chanin `Genererator->Ticker->Tacker` the first one waits for reply from last one. I could understand 2x drop of `performance` because of 2x more calls (more latency, overheads etc).
But not 16x drop!

**Comment by benjaminpetit** [comment]
Could it be because your hardware is under-powered for your load? I guess your laptop only have 2 core / 4 threads at best?

On my dev machine (core i7 5820k, 6C/12T), building in Release and running outside VS;

With ITacker

- 100000  upload stop: 00:00:13.8381584
- 2000000 upload stop: 00:04:39.2728367

With ITicker

- 100000  upload stop: 00:00:34.8222813
- 2000000 upload stop: 00:11:48.4514334

I was still using the machine on the meantime so it is not a real load test but I definitely don't see a performance drop like you.

**Comment by justmara** [comment]
@benjaminpetit hmm, looks legit. Keeping in mind `forced single-threaded` nature of Grains there must be some real bump of thread sync/switch overhead with 3-grain chain on 4 cores. I'll try to check it on better hardware then. Thank you for idea.
