### ISSUE TITLE
C# Scripting in Orleans

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [dotnet/orleans#3179]
I've created a C# integration for our game backend with the following features

- Scripts are analyzed for safe code.
- Scripts are compiled on each silo and are only compiled once.
- A specific user method gets executed
- One specific class is passed to the scripts as our API

Do you guys think I should include it in contrib ? How can it be generalized?

Currently I think it should

- Allow changing allowed types in scripts
- Allow custom validation methods for script safety checks
- The ability to run scripts without having specific functions

cc @reubenbond @sergeybykov @galvesribeiro @jdom

**Comment by jdom** [comment]
Very interesting. Would the scripts also define the grain interface/contract or would they go through a conforming interface where you just vary the message type?
I see a lot about validation. Is it because you may not trust the script code you are hosting as it may be malicious or in case it's buggy?

**Comment by DixonDs** [comment]
@ashkan-saeedi-mazdeh just curious, what part of your scripting logic is specific to Orleans? We also use C# scripting for business rules but it was done way before Orleans and hasn't changed much after we migrated to Orleans.

**Comment by ashkan-saeedi-mazdeh** [comment]
@jdom  The script is not defining the grain interface. I don't think that is much of a usecase to define the whole interface of the grain using a script. If you think that is a valid usecase we can discuss it and I can add it. The current one executes a script when a specific grain interface is called. Actually it even looks for a specific method in the script to call but that restriction was needed in my case and surely can be relaxed. 
The point was that a client in a game calls a script much like a RPC and sends parameters and receives the return value of the script. 

I do care about validation because the scripts are made by users of a game backend service much like www.playfab.com and gamesparks.com and I even execute scripts in a separate thread and abort it after timeout if the script doesn't finish. 

@dixonds Basically it is a script runner integrated with Orleans in the following way

- When users modify scripts they are persisted as grain state (IScriptEventCompiler grain) and whenever a IScriptEventRunner wants to run it we check if the compiled version of the latest script version is available on the local silo we run it, otherwise we compile it and store it and then run it.

All other stuff like validation and aborting timed-out scripts aren't Orleans specific.

My environment is a none-trusted one but I went in length to avoid spawning processes or AppDomains for user scripts , 

User scripts can be harmful by not finishing, using types which can cause security issues or other problems and also by causing a StackOverFlow which terminates the whole process. I run scripts in a separate thread and don't allow types like File, Process ... (Actually have white-list of types to be allowed) and should add the logic for creating a graph of method calls and disallow recursion to avoid StackOverFlow as well.

**Comment by sergeybykov** [comment]
I think OrleansContrib is a good place to publish this. As it evolves, would be interesting to see is something generic enough will grow out of it. Sounds exciting!

**Comment by ashkan-saeedi-mazdeh** [comment]
Sure, Will do it after the expo. Also maybe it is a good idea to present it in 5-10 minutes in a meetup as well. I don't know how much common the use-case is.
