### ISSUE TITLE
Unit Testing Grain State

### ISSUE THREAD

**Issue by morwn** [dotnet/orleans#3180]
Hey,
I would like to write a test that get a grain, call his public methods that will add/remove data from his State and then assert the State data.

How can I Mock State and inject it to grain, or get a State of a grain instance.

I try mock it this way:(but i got error said State property is not virtual)
```
Mock<MyGrain> grainMock = new Mock<MyGrain>();
grainMock.Protected().Setup<MyGrainState>("State");
```

and that way:
MyGrain C'tor call Grain(IGrainIdentity identity, IGrainRuntime runtime, TGrainState state, IStorage storage).
but then i can not use DI in MyGrain.

Thanks

**Comment by xiazen** [comment]
I have an idea, You can implement a IStorageProvider for testing, where you can manipulate/mock your grain state by grain id or grain ref. 
And for the grain to always run on the updated/mocked state from the storage provider, you need to add ReadStateAsync in every grain method to force read its state from the storage provider.

**Comment by dandago** [comment]
Refer to discussion here: https://github.com/dotnet/orleans/issues/3086.
