### ISSUE TITLE
GrainClient.Initialize() error

### ISSUE THREAD

**Issue by noobwu** [dotnet/orleans#3188]
Orleans version 1.4.2
call method GrainClient.Initialize();
Orleans.Runtime.SiloUnavailableException : The target silo became unavailable for message: Request *cli/c1f9c088@932040b1->S127.0.0.1:40000:0TypeManagerId@S00000011 #2: global::Orleans.Runtime.IClusterTypeManager:GetClusterTypeCodeMap(). Target History is: <S127.0.0.1:40000:0:TypeManagerId:@S00000011>. See https://aka.ms/orleans-troubleshooting for troubleshooting help.

**Comment by sergeybykov** [comment]
Sounds as if there is no silo the client is trying to connect to. But this isn't enough information to be sure. How are you deploying and configuring your silos? How is the client configured?

**Comment by EshG** [comment]
@sergeybykov I experience the same when starting a new test Silo from the default default template provided here:
https://marketplace.visualstudio.com/items?itemName=sbykov.MicrosoftOrleansToolsforVisualStudio

**Comment by noobwu** [comment]
thank you very much EshG
