### ISSUE TITLE
Add packages.config and restore on DevHost/TestHost Projects

### ISSUE THREAD

**Issue by nicolocodev** [dotnet/orleans#319]
I've updated to SDK v.1.0.5 and noticed that when I create/add new DevHost/TestHost Project (from VS2013 ultimate) is not included any of Orleans dlls. You must add these references from nuget: ```Microsoft.Orleans.Core``` and ```Microsoft.Orleans.OrleansRuntime``` manually :(

**Comment by nicolocodev** [comment]
Just noticed that an ```ItemGroup``` including the ```packages.config``` was not added in the ```VSProjectSiloHost```, and the package used in the template is: ```Microsoft.Orleans.Server```.

I added the ```packages.config``` file and rebuild the VSIX, the package is now restored but not installed, TIL that [nuget doesn't run scripts on restore](https://nuget.codeplex.com/discussions/436395) :confused:

**Comment by sergeybykov** [comment]
@nicolocodev I see the same. Can you submit a PR with the VSIX fix you had to make? I'm curious what @jthelin will say about this.

**Comment by jthelin** [comment]
PR #335 should fix this issue, but please retest if possible before merge.
