### ISSUE TITLE
Orleans reminder self deactivated

### ISSUE THREAD

**Issue by yzhao174** [dotnet/orleans#3200]
I am trying to use reminder grain for health monitoring. The task is very simple. The grain is registered as a reminder and will talk to another grain when timer ticks. 

The log shows this reminder (HealthMonitorGrain) is active at the beginning. But it is then deactivated for unknown reason:

```
...
Grain.ControlPlane.Grains.HealthMonitorGrain.Current=1
...
Grain.ControlPlane.Grains.HealthMonitorGrain.Current=0
...
Grain.ControlPlane.Grains.HealthMonitorGrain.Current=0
...
Grain.ControlPlane.Grains.HealthMonitorGrain.Current=0
```

I register the reminder on activation:
```
public override async Task OnActivateAsync()
        {
            this.grainFactory = base.GrainFactory;
            await RegisterOrUpdateReminder("HealthMonitor", HealthMonitorGrainSettings.Instance.ReminderDueTime, HealthMonitorGrainSettings.Instance.ReminderPeriod);
        }
```
The grain is activated at bootstrap:
```
public class SiloBoostrapProvider : IBootstrapProvider
    {
        public string Name { get; private set; }

        public Task Close()
        {
            return Task.CompletedTask;
        }

        public async Task Init(string name, IProviderRuntime providerRuntime, IProviderConfiguration config)
        {
            this.Name = name;
            var healthMonitorGrain = providerRuntime.GrainFactory.GetGrain<IHealthMonitorGrain>("HealthMonitor");
            await healthMonitorGrain.OnActivateAsync();
        }
    }
```
What could possibly deactivate this reminder?

**Comment by sergeybykov** [comment]
Does `HealthMonitorGrain` implement `IRemindable`? 
What is the value of `HealthMonitorGrainSettings.Instance.ReminderPeriod` and `HealthMonitorGrainSettings.Instance.ReminderDueTime`?
This looks rather strange:
>await healthMonitorGrain.OnActivateAsync();

Did you add `OnActivateAsync()` to `IHealthMonitorGrain` to make it remotely invokable? In general, `OnActivateAsync()` is not supposed to be called by application code. You can call any other method of the target grain to trigger its activation, and `OnActivateAsync()` will get called by the runtime as part of the activation process.

**Comment by yzhao174** [comment]
The ReminderPeriod is 1 minute and ReminderDueTime is 30 seconds. 
Yes, the class implements IRemindable. The class is defined below
```
public class HealthMonitorGrain : Grain, IHealthMonitorGrain
    {
        private readonly TimeSpan retryInterval;
        private readonly IServiceFabricHealthClient serviceFabricHealth;
        private IGrainFactory grainFactory;

        public HealthMonitorGrain(IStatelessServicePartition partition)
            : this(null, HealthMonitorGrainSettings.Instance.DefaultRetryInterval, partition)
        {
        }

        internal HealthMonitorGrain(IGrainFactory grainFactory, TimeSpan retryInterval, IStatelessServicePartition partition)
        {
            this.grainFactory = grainFactory;
            this.retryInterval = retryInterval;
            serviceFabricHealth = new ServiceFabricHealthClient(partition, GetType().Name);
        }

        public async Task ReceiveReminder(string reminderName, TickStatus status)
        {
            try
            {
                GrainProbeAgent grainProbeAgent = new GrainProbeAgent(grainFactory);
                await Retry.Do(() => grainProbeAgent.TestProbeTestGrain(), retryInterval, HealthMonitorGrainSettings.Instance.MaxRetry);
                serviceFabricHealth.ReportDeployedServicePackageHealth(HealthState.Ok, HealthProperty.GrainToGrainProbeTest);
            }
            catch (Exception exception)
            {
                serviceFabricHealth.ReportDeployedServicePackageHealth(HealthState.Warning, HealthProperty.GrainToGrainProbeTest, exception.ToFullDescription());
            }
        }

        public override async Task OnActivateAsync()
        {
            this.grainFactory = base.GrainFactory;
            await RegisterOrUpdateReminder("HealthMonitor", HealthMonitorGrainSettings.Instance.ReminderDueTime, HealthMonitorGrainSettings.Instance.ReminderPeriod);
        }

public interface IHealthMonitorGrain : IRemindable, IGrainWithStringKey
    {
        Task OnActivateAsync();
    }
```
I will try not to use OnActivateAsync for activation

**Comment by sergeybykov** [comment]
What did you configure as the reminder storage?

**Comment by yzhao174** [comment]
Hmm. It seems I am not using any reminder storage. But the reminder would work sometimes even without reminder storage.

**Comment by sergeybykov** [comment]
Is your `config.Globals.ReminderServiceType` set to `GlobalConfiguration.ReminderServiceProviderType.ReminderTableGrain`?

**Comment by yzhao174** [comment]
Yes,
`config.Globals.ReminderServiceType = GlobalConfiguration.ReminderServiceProviderType.ReminderTableGrain;`

**Comment by sergeybykov** [comment]
And you are not restarting the silo where the `ReminderTableGrain` resides by any chance?

**Comment by yzhao174** [comment]
We have an upgrade happens  regularly, which would restart the service. It seems the failure usually happens after the restart if not always. Is ReminderTableGrain in memory table? Which would be lost after restart?

Curious that if the ReminderTableGrain is refreshed, then actually the service would register the new reminder grain again in the bootstrap method. But that doesn't seem to bring the reminder gain back.

**Comment by sergeybykov** [comment]
>Is ReminderTableGrain in memory table? Which would be lost after restart?

Yes and yes. It is not meant for production use, only for testing.

**Comment by yzhao174** [comment]
I see. That makes sense now. I will change to use reminder storage then. Thanks for the answer

**Comment by sergeybykov** [comment]
Great. I'll close the issue then. Thanks.
