### ISSUE TITLE
Unit tests and GrainCreator in v1.5

### ISSUE THREAD

**Issue by wattsm** [dotnet/orleans#3205]
What is the recommended alternative to using `GrainCreator` in unit tests now that it is internal in v1.5?

For example, `TestGrainFactory` in the tests for the Hello, World sample use `GrainCreator` to activate test grains. ([Source code](https://github.com/dotnet/orleans/blob/master/Samples/HelloWorld/NonSiloTests/TestGrainFactory.cs))

**Comment by DixonDs** [comment]
There is a related discussion here: https://github.com/dotnet/orleans/issues/3086 . You can inject and use `IGrainFactory` in both production code and test code
