### ISSUE TITLE
Receiving events (from a non Orleans-Scheduled thread/task) in grains

### ISSUE THREAD

**Issue by maiorfi** [dotnet/orleans#321]
Hi.

I'm working on a sample where a grain contains a reference to (well, kind of) a TCP client.
Once TCP client is connected to a listener, it can receive unsolicited data by mean of a .NET event.
In my grain code, I subscribe to such event using a private grain method as an handler.

While locking members shared between grain methods and event handler seems enough to protect concurrent access, it seems that grain can't update its State (yes, with capital case since my grain is a stateful one, using Orleans state persistence infrastructure) within handler.

Is it due to accessing State from outside Orleans-managed task scheduler?

Should it be the reason, how could I "schedule" a method/delegate/lambda call (like one usually does managing UI affinity issues, like Dispatcher.Invoke in WPF or Control.Invoke in WindowsForms) in such a way that it can update grain state?

Thanks!

**Comment by richorama** [comment]
Hi,

I don't think you should put a TCP client in a grain and leave it open to receive messages, as calls to this lambda won't be scheduled by the Orlean task scheduler.

You should place this code outside Orleans, and send messages to a grain when messages are received on the socket.

**Comment by sergeybykov** [comment]
@maiorfi I agree with @richorama - usually you want to open such connections from outside of Orleans silo. However, if you need to do that from within a grain or for a demo purpose, you can marshal a call to the grain's context by capturing it first, e.g. from within OnActivateAsync(), along with a reference to the grain:

```csharp
private TaskFactory factory;
private me = this.AsReference<IFoo>();
factory = new TaskFactory(TaskScheduler.Current);
```

You can then schedule a call via

```csharp
factory.StartNew(async () => await me.Bar());
```
where IFoo is your grain interface and Bar() is a method of it.

**Comment by maiorfi** [comment]
@richorama You're absolutely right: what I'm doing is trying (improperly) to split front-end stuff among grains: is there any suggested pattern for that? Maybe making grains observe a OrleansStream "filled" with data coming from an external service?

@sergeybykov Thanks, I'm going to try it just now!

**Comment by sergeybykov** [comment]
@maiorfi One purpose of the streaming extensions is to help decouple ingestion of data from the processing logic. In this pattern, the client receives incoming data (e.g. over TCP connections) and publishes it to streams (e.g. per-user or per-device). Grains do processing by implicitly or explicitly subscribing to the streams. By choosing a stream provider you define desired reliability, latency, and throughput of the event flow.
