### ISSUE TITLE
Allow interception in GrainClient for outgoing grain method invocations

### ISSUE THREAD

**Issue by rikbosch** [dotnet/orleans#3214]
We are currently investigating how to implement end-to-end tracing using DiagnosticsSource ( https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/HttpCorrelationProtocol.md )

Looking at HttpClient's diagnostichandler implementation (https://github.com/dotnet/corefx/blob/c082d21361608e3cc2ea3cddd90c2a0306828002/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs), I would like to be able to intercept an outgoing remote grain invocation in the client and Start / End an activity in the DiagnosticsSource, but intercepting the end of a remote grain invocation is not possible with a `ClientInvokeCallback`

**Comment by ReubenBond** [comment]
@rikbosch I was thinking that we should remove `ClientInvokeCallback` and instead implement the ability to inject `IGrainCallFilter` on the client side (during construction), the same way it's done on server side:
```C#
services.AddGrainCallFilter(async context =>
{
  // Start trace
  await context.Invoke();
  // End trace
});
```

What do you think?

**Comment by rikbosch** [comment]
That would be great!
