### ISSUE TITLE
Hosting Orleans client within a Worker Role

### ISSUE THREAD

**Issue by maiorfi** [dotnet/orleans#323]
Hi. It seems that hosting a Orleans client inside a worker role requires a different way to initialize client itself, since AzureConfigUtils throws several NullReferenceExceptions when evaluating computed properties like ClientConfigFileLocation:

```C#
FileInfo clientConfigFile = AzureConfigUtils.ClientConfigFileLocation;

if (!clientConfigFile.Exists)
{
    throw new FileNotFoundException(string.Format("Cannot find Orleans client config file for initialization at {0}", clientConfigFile.FullName), clientConfigFile.FullName);
}

AzureClient.Initialize(clientConfigFile);
```

What is the proper way to initialize client that is not hosted inside a WebRole?

Thanks!

**Comment by sergeybykov** [comment]
Can you share call stacks of those NullReferenceExceptions? ClientConfigFileLocation only scans a few known locations trying to find the config file. It shouldn't be throwing NullReferenceExceptions.

**Comment by sergeybykov** [comment]
Are you using IntelliTrace by chance as in https://github.com/dotnet/orleans/issues/327#issuecomment-93048388?

**Comment by maiorfi** [comment]
I have IntelliTrace disabled at Visual Studio level.

The stack trace of the NullReferenceExeption is:

   in Orleans.Runtime.Host.AzureConfigUtils.<FindAppDirectoryLocations>d__0.MoveNext()

**Comment by maiorfi** [comment]
Ok, I solved using following path, but probably it could be done much better than this:

```C#
FileInfo clientConfigFile = new FileInfo(Environment.GetEnvironmentVariable("RoleRoot") + Path.DirectorySeparatorChar + "approot" + Path.DirectorySeparatorChar + "ClientConfiguration.xml");

**Comment by ReubenBond** [comment]
This is what I do:
```c#
private static string GetAssemblyPath()
{
    return Path.GetDirectoryName(new Uri(Assembly.GetExecutingAssembly().CodeBase).LocalPath);
}
```
And then:
```c#
var clientConfigFile = new FileInfo(Path.Combine(path, "ClientConfiguration.xml"));
```

Hope it helps :).
