### ISSUE TITLE
ExtendedKey Grain throwing 'Cannot find a type code for an implementation class for grain interface'

### ISSUE THREAD

**Issue by carlos-sarmiento** [dotnet/orleans#324]
I'm updating an application that was running the old version of Orleans (pre v1) and had a grain that used the ExtendedPrimaryKey feature.

Now, when running the code, I get the following exception:

    Cannot find a type code for an implementation class for grain interface

The code that calls the grain is:
    
    var AggregateID = Guid.NewGuid();
    var InternalSystemID = "some-system";
    var agg = GrainFactory.GetGrain<IAggregateGrain>(AggregateID, InternalSystemID);

I see that the signature of GetGrain changed, so my question is how can I still use the ExtendedPrimaryKey (or is it gone?)

**Comment by gabikliot** [comment]
You need to put an attribute [ExtendedPrimaryKey] on the grain:
http://dotnet.github.io/orleans/Step-by-step-Tutorials/Actor-Identity

**Comment by sergeybykov** [comment]
GrainFactory.GetGrain<> doesn't currently support compound keys (GUID+string). You can use the generated interface-specific factory for that:

```csharp
AggregateGrainFactory.GetGrain(AggregateID, InternalSystemID);
```

**Comment by carlos-sarmiento** [comment]
@gabikliot The attribute is there. The code worked perfectly before upgrading to v1.
@sergeybykov The signature for the specific factory also uses grainClassNamePrefix.

After the proposed change, the code is still throwing the same exception.

**Comment by carlos-sarmiento** [comment]
After checking, I can see that the generated code is calling 

    MakeGrainReferenceInternal 

instead of 

    MakeKeyExtendedGrainReferenceInternal

I deleted the codegen file and regenerated it and it generated the same code, using the wrong method

**Comment by carlos-sarmiento** [comment]
Just in case, here is the declaration of the interface

    [ExtendedPrimaryKey]
    public interface IAggregateGrain : IGrainWithGuidKey

**Comment by sergeybykov** [comment]
Try instead

```csharp
public interface IAggregateGrain : IGrain
```

**Comment by carlos-sarmiento** [comment]
It works.

Seeing this situation I would suggest that instead of implementing the ExtendedPrimaryKeyAttribute, we could use an interface like IGrainWithCompoundKey. 

That way the intent of the developer is cleaner and we avoid the situation in which the developer uses IGrainWithXxxKey and ExtendedPrimaryKey and wonders (like I did) why is it not working.

**Comment by sergeybykov** [comment]
I agree. IGrainWithXxxKey were added after [ExtendedPrimaryKey] already existed, so it's a confusing mix of two generations of the API. I'll open an issue for it. Thanks for exposing it!

**Comment by carlos-sarmiento** [comment]
I'd love to contribute that change to the codebase

**Comment by sergeybykov** [comment]
That's be great! https://github.com/dotnet/orleans/issues/326.

**Comment by sergeybykov** [comment]
In addition, we want to get rid of generating interface-specific factories altogether, and leave GrainFactory.GetGrain<T> as the only way of getting grain references. This will get us one step closer to that goal.

**Comment by gabikliot** [comment]
Fixed in #326 and merged in #330.

**Comment by sergeybykov** [comment]
@carlos-sarmiento Thank you for the PR! It's in.

**Comment by carlos-sarmiento** [comment]
@sergeybykov My pleasure, hope to be able to keep helping

**Comment by sergeybykov** [comment]
:+1:
