### ISSUE TITLE
What is ServiceId & DeploymentId when running under Service Fabric?

### ISSUE THREAD

**Issue by charleszipp** [dotnet/orleans#3242]
I wanted to ask what we should be setting these to be while running under service fabric? Our deployment would look something like the following. We have one silo "Silo A" that is responsible for grains 1 & 2. The silo will be deployed on 3 nodes in the service fabric cluster.

- Node 1
-- Silo A
--- Grain 1
--- Grain 2
- Node 2
-- Silo A
--- Grain 1
--- Grain 2
- Node 3
-- Silo A
--- Grain 1
--- Grain 2

DeploymentId is required for the Azure Queue stream provider so I need to set it to something. However, i wasnt sure what the semantics were around these two values and what they control.

**Comment by ReubenBond** [comment]
@charleszipp set `ServiceId` and `DeploymentId` to a value which is consistent between all silos and clients in the cluster.

**Comment by sergeybykov** [comment]
`ServiceId` is supposed to stay the same across multiple deployments of the same service over time as you deploy new versions of the deployment/cluster.

**Comment by charleszipp** [comment]
Thanks for the responses @ReubenBond and @sergeybykov ! That gives me what i needed to know.

**Comment by talarari** [comment]
@ReubenBond  @sergeybykov Does DeploymentId need to be different across deployments?
what will happen if i just set it to a hardcoded string?

**Comment by sergeybykov** [comment]
>@ReubenBond @sergeybykov Does DeploymentId need to be different across deployments?
what will happen if i just set it to a hardcoded string?

The danger here is that you may end up deploying at some point have a different service/cluster with the same DeploymentId.

**Comment by talarari** [comment]
Im not sure i understand what's the purpose of deployment id.
What is it used for?

**Comment by sergeybykov** [comment]
It should have been caller `ClusterId` instead. It is the unique identifier of a cluster, and silos in a cluster find each other using it as a key.

**Comment by talarari** [comment]
Ok that sounds more clear to me.
I was under the impression that deployment id should be different between two vervsion deployments to the same cluster, something like a versionid.
So basically if its the only orleans cluster running on those machines this can just be a costant name?
Or is it used for things like versioned grains and placements strategies?

**Comment by sergeybykov** [comment]
>So basically if its the only orleans cluster running on those machines this can just be a costant name?

Yes.

>Or is it used for things like versioned grains and placements strategies?

No.

It's just a key for silos and clients to find each other in the membership table.
