### ISSUE TITLE
When does Orleans support RabbitMQ and DotNetty?

### ISSUE THREAD

**Issue by Qoooooooooooo** [dotnet/orleans#3246]
:)

**Comment by sergeybykov** [comment]
There is a stream provider for RabbitMQ in OrleansContrib - https://github.com/OrleansContrib/Orleans.Providers.RabbitMQ.

No concrete plans for DotNetty yet.

**Comment by sundong1982** [comment]
this Contrib  is too simple :(       There will be errors in the 1.5.0

**Comment by bobanco** [comment]
@sundong1982 you can take a look at my RabbitMQ stream implementation. https://github.com/bobanco/Orleans.Providers.RabbitMQ

**Comment by sergeybykov** [comment]
I didn't realize there are two implementations! @bobanco and @creyke, would it make sense to reconcile them into one?

**Comment by creyke** [comment]
I'm keen to pool efforts here and create a high quality library. I anticipate requiring this for a production product soon (this requirement has been delayed hence it's not moving forward) so then I will be able to dedicate some serious time to it. I think this is a key dependency for Orleans on premise as well so it's important it's taken seriously and I don't want my current have baked effort to hamper progress.

It's worth highlighting there isn't a good generic test suite for stream providers yet. I would like to see this, so third party stream developers can validate the correctness of their implementation.

Happy to work with others on this - and validate it in production!

**Comment by sergeybykov** [comment]
Great. The core team can help, too.

**Comment by bobanco** [comment]
Mine implementation is passing all of the stream tests, and is based on AzureQueue implementation, @creyke  if you have a time you could check at mine implementation  https://github.com/bobanco/Orleans.Providers.RabbitMQ, we can work on 1 implementation so to not split our efforts.

**Comment by creyke** [comment]
@bobanco Sure - I'll check this out on Monday. Would you be up for moving it to OrleansContrib?

**Comment by creyke** [comment]
In fact it looks like some of the [test code](https://github.com/bobanco/Orleans.Providers.RabbitMQ/blob/master/Orleans.Providers.RabbitMQ.Tests.Host/Grains/ProducerGrain.cs) at least is from [OrleansContrib](https://github.com/OrleansContrib/Orleans.Providers.RabbitMQ/blob/master/Orleans.Providers.RabbitMQ.Tests.Host/Grains/ProducerGrain.cs) already 👍

**Comment by bobanco** [comment]
@creyke yh i took your sample :) i will push the code to OrleansContrib over this weekend.

**Comment by creyke** [comment]
What the status here @bobanco ?

**Comment by sundong1982** [comment]
@bobanco @creyke  waiting for you :)

**Comment by mickdelaney** [comment]
Hi, has there been any progress on this ?

**Comment by rafikiassumani-msft** [comment]
We will close this issue since we have not had any activity or progress on this for the past 3 years. Please open a new issue if this is something you are still interested in.
