### ISSUE TITLE
Setting GrainClient.ClientInvokeCallback raises NullReferenceException [Orleans 1.5.0]

### ISSUE THREAD

**Issue by peter-perot** [dotnet/orleans#3251]
Today I updated my project from Orleans 1.4.2 to 1.5.0. Now I experience the following issue:

When setting `GrainClient.ClientInvokeCallback`, I get a `NullReferenceException`:

```csharp
GrainClient.ClientInvokeCallback = (request, grain) => { RequestContext.Set("IsExceptionConversionEnabled", true); };
```

This did not happen in Orleans 1.4.2.

After digging deeper I found a way to fix this: in my code I set the callback **before** calling `GrainClient.Initialize(...)`. I swapped the lines of code, so the callback is set **after** the grain client has been initialized. Now everything works properly.

I think if it is not allowed to set the callback before initialization, an `InvalidOperationException` with a hint in the exception message should be thrown instead of a `NullReferenceException`.

**Comment by ReubenBond** [comment]
Thanks, @peter-perot - I've opened #3258 with a fix to check that the client is initialized.
