### ISSUE TITLE
Registering InvokeInterceptor via DI not working [Orleans 1.5.0]

### ISSUE THREAD

**Issue by peter-perot** [dotnet/orleans#3252]
@ReubenBond In pull request https://github.com/dotnet/orleans/pull/3083 you proposed to register interceptors this way:

```csharp
services.AddSingleton<InvokeInterceptor>((method, request, target, invoker) =>
{
    RequestContext.Set(InterceptedPropertyKey, 1);
    return invoker.Invoke(target, request);
});
```

I tried to follow your proposal since the `SetInvokeInterceptor()` method on interface `IProviderRuntime` is marked obsolete.

However when I set a breakpoint on `RequestContext.Set(InterceptedPropertyKey, 1);` it is never hit, i.e. the interceptor is never initialized (the singleton is never resolved from the container).

So I reverted my code to the orginal but now obsolete way via `IProviderRuntime.SetInvokeInterceptor()`.

Any idea why the DI registration is never resolved?

**Comment by ReubenBond** [comment]
Hi @peter-perot, the comment at the top of that PR was the initial proposal, but the shape of that API was changed before the PR was merged. If you take a look at the later comment [here](https://github.com/dotnet/orleans/pull/3083#issuecomment-308575448) you can see an example.

You can register an interceptor like so:
```C#
services.AddGrainCallFilter(context => {
  // Do something before the call, eg inspect method, grain reference, arguments
  RequestContext.Set(InterceptedPropertyKey, 1);
  await context.Invoke();
  // Do something with the result
});
```

There are other extension methods to help specify grain call filters here: https://github.com/dotnet/orleans/blob/master/src/Orleans/Configuration/ServiceCollectionExtensions.cs

**Comment by peter-perot** [comment]
Thank you, @ReubenBond, now it works!
