### ISSUE TITLE
Add IGrainWithCompoundKey inteface and remove ExtendedPrimaryKeyAttribute

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#326]
This is to make extended primary keys usable with GrainFactory.GetGrain<T> and eliminate the confusion from the fact that ExtendedPrimaryKeyAttribute only works today for grain interfaces that extend IGrain.

**Comment by carlos-sarmiento** [comment]
Questions:

1. Should we have only one interface IGrainWithCompoundKey or two interfaces IGrainWithGuidCompoundKey and IGrainWithIntegerCompoundKey?
2. Should we remove ExtendedPrimaryKeyAttribute or leave it for backwards compatibility?

**Comment by sergeybykov** [comment]
For symmetry, I think we need both version.

**Comment by carlos-sarmiento** [comment]
To confirm: we implement IGrainWithXxxCompoundKey and leave ExtendedPrimaryKeyAttr?

**Comment by sergeybykov** [comment]
Sorry, I didn't answer your second question. I think we should remove ExtendedPrimaryKeyAttr and codegen logic that uses it altogether. Let's break it to make it cleaner.
