### ISSUE TITLE
TypeAccessException when sending an immutable of ICollection between silos

### ISSUE THREAD

**Issue by selimser** [dotnet/orleans#3268]
We are on Orleans 1.5 now and we are running into an issue. The problem happens on a cluster of silos, not a single silo.

- Grain A calls Grain` B.MyMethod(Immutable<ICollection<IMyInterface>>)`
- Grain B has `[PreferLocalPlacement]` attribute.
- Even if we keep the `PreferLocalPlacement `on grain B, the error rarely happens, but it still happens.
- If we remove the local placement attribute, it happens quite a lot. This suggests that this error is happening when it is sending an immutable object to another silo in the cluster.
- If we do not send the ICollection<IMyInterface> as Immutable<>, we are not running into this issue at all but it is a significant performance hit.

The exception we are getting is something like this:
`"Orleans.Concurrency.Immutable1<ICollection1<MyNamespace.Entities.IMyInterface>>" is invalid: Type string "ICollection``1'1" cannot be resolved.`

In the Orleans code base, the exception is thrown in the `SerializationManager.ResolveTypeName(string) `method, as the string argument is passed in as `ICollection'1'1`. Therefore, `var i = typeName.IndexOf('<')` returns -1 and throws TypeAccessException in the same class.

As far as I can tell, we did not have this issue on 1.3 binaries.

Is this a known issue?

**Comment by sergeybykov** [comment]
@selimser Would it be possible to create a unit test that reproduces the issue?

**Comment by sergeybykov** [comment]
>"Orleans.Concurrency.Immutable1<ICollection1<MyNamespace.Entities.IMyInterface>>" is invalid: Type string "ICollection``1'1" cannot be resolved.

I see what appears like a typo here -> "Immutable1". Is this not the exact copy-pasted error message?

**Comment by selimser** [comment]
That was the copy paste exception message. Just couldn't find a way to escape left quote &#96; character (now I got it!)


So exact message would be:
"Orleans.Concurrency.Immutable&#96;1<ICollection&#96;1<MyNamespace.MyInterface>>" is invalid: Type string "ICollection&#96;1'1" cannot be resolved."

except for the MyNamespace.MyInterface bit...

**Comment by sergeybykov** [comment]
@selimser Is there a chance you are mutating the collection after you passed it as an argument? Also, are the objects you put into a collection serializable? Is there an Orleans serializer generated for it?

**Comment by selimser** [comment]
@sergeybykov I don't think so. After further experimenting with our side of code, I've managed to reproduce this again on a clustered environment. I'm pretty confident that this only happens with ICollection. I've tried passing Immutable types of IList, List or arrays, and they all looked fine. However, the following code was enough to cause it to throw the mentioned exception...

```csharp
public interface IWeirdIssueGrain : IGrainWithIntegerKey
{
    Task SayHello(Immutable<ICollection<IWeirdType>> something);
}

public interface IWeirdType
{
    string Name { get; set; }
}

[Serializable]
public class WeirdType : IWeirdType
{
    public string Name { get; set; }
}

public class WeirdIssueGrain : Grain, IWeirdIssueGrain
{
    public Task SayHello(Immutable<ICollection<IWeirdType>> something)
    {
        Console.WriteLine("Hellowww");
        return Task.CompletedTask;
    }
}
```


I've done some digging on the Orleans code base. In the SerializationManager class, where you register the types (in the RegisterBuiltInSerializers() method), ICollection is not part of it. What I've simply done is to add the `Register(typeof(ICollection<>));` to that list, and used that binary instead of the one I got from NuGet, and it was happy with my above implementation of `IWeirdIssueGrain`. So now I am simply looking for a way to reproduce this with a unit test... Further ideas @sergeybykov @ReubenBond ?

**Comment by sergeybykov** [comment]
Thank you, @selimser! This is a great repro. Still makes little sense to me what's going on here.
@ReubenBond, do you have an idea why registering `ICollection` would make a difference when what is actually passed is `List`?

**Comment by selimser** [comment]
@sergeybykov @ReubenBond just to clarify a bit more;

```csharp
ICollection<IWeirdType> list = new List<IWeirdType>(); //this does not work without registering ICollection
IList<IWeirdType> list = new List<IWeirdType>(); //works fine
```
There is a register for IList though... Maybe ICollection is needed as well?

```csharp
internal void RegisterBuiltInSerializers()
{
    ...yada yada

    Register(typeof(IList<>));
    Register(typeof(IDictionary<,>));
    Register(typeof(IEnumerable<>));
    //Register(typeof(ICollection<>));

    ...yada yada
}
```

**Comment by ReubenBond** [comment]
@sergeybykov it's because the method call arguments are serialized as `object[]` in `InvokeMethodRequest` and the concrete, runtime type of that argument includes `ICollection<T>` - even though the actual value of the field in the `Immutable<ICollection<T>>` is `List<T>` at runtime.

So as a resolution we can register `ICollection<T>` as mentioned by @selimser. I'll open a PR.
