### ISSUE TITLE
DI ready Orleans logger

### ISSUE THREAD

**Issue by pherbel** [dotnet/orleans#3276]
Hi,

We would like to inject logger into our service classes, but I just found this, but it is not an idial solution #3132 
Would be great to use Microsoft.Extensions.Logging package to in Orleans system for logging and inject it to our service classes.

All the advice is appreciated

Thanks

**Comment by sergeybykov** [comment]
We plan to integrate with Microsoft.Extensions.Logging in the next release. The work has already started. Will that address your concern?

**Comment by pherbel** [comment]
> We plan to integrate with Microsoft.Extensions.Logging in the next release. The work has already started. Will that address your concern?

Yes. It would be great.

**Comment by xiazen** [comment]
The issue summarizing this integration has been opened in #3303. Take a look if interested. It contains information about current plan of how logging would look like in 2.0

**Comment by xiazen** [comment]
this is resolved through #3333 which is target to 2.0 beta
