### ISSUE TITLE
PubSubRendevousGrain state does not support JSON serialization

### ISSUE THREAD

**Issue by ca-ta** [dotnet/orleans#328]
I am using a custom storage provider (which uses JSON serialization) and I've noticed that the PubSubRendevousGrain state fails to round-trip.

The culprits are ```PubSubSubscriptionState```, ```PubSubPublisherState``` and ```GuidId```.

I have it now working locally, but it smells:
* Removing ```readonly``` from the ```PubSubSubscriptionState```,  ```PubSubPublisherState```  and ```GuidId``` properties. 
 * This might be tolerable for the first two, as the classes are internal. Still, it's ugly.
 * I do not think it is acceptable for GuidId

* making the constructors public for all three classes:
 * again, this might be OK for ```PubSubSubscriptionState``` and ```PubSubPublisherState```  
 * However, ```GuidId``` is a public class and uses a lazy cache (```Interner```). Having a public constructor smells quite badly.

Are there any plans on supporting JSON serialization for PubSubRendevousGrain state? 
Before digging further (or move to using binary serialization) I though of asking if a pattern for addressing this type of issues is already in place...

**Comment by gabikliot** [comment]
It used to work. AzureTableStorage  supports json as well and we had it working with PubSubRendevousGrain.
There are multiple ways one can integrate with Newtonsoft serializer. In some cases we picked to explicitly implement ISerializable, in others have all the properties public. At some point we changed the default to not use json in AzureTableStorage and thus it is possible that at some point we broke the support for Json in PubSubRendevousGrain and missed the time when it broke. 
The easiest way I think is to define ISerializable on  GuidId  and implement the ISerializable  explicitly(like we do now on [GrainReference](https://github.com/dotnet/orleans/blob/master/src/Orleans/Runtime/GrainReference.cs#L715)) and remove readonly  from the  PubSubSubscriptionState,  PubSubPublisherState.

Would you like to take a look and submit or PR? If not, I can look at it later on.

**Comment by ca-ta** [comment]
Thanks Gabi -  I'll submit a PR shortly

**Comment by gabikliot** [comment]
Fixed via #331.
