### ISSUE TITLE
InvalidOperationException thrown at regular intervals by OnRefreshClusterMapTimer

### ISSUE THREAD

**Issue by Liversage** [dotnet/orleans#3285]
I am having some issues where `InvalidOperationException` is thrown in a silo with a message similar to this:

> Trying to send a message Request S127.0.0.1:11111:239965139-> #<span></span>2:  on a silo not from within grain and not from within system target (RuntimeContext is not set to SchedulingContext) RuntimeContext.Current=null TaskScheduler.Current=System.Threading.Tasks.ThreadPoolTaskScheduler

The exception is handled so perhaps I should just ignore it but I would still like to understand why this happens.

Using a debug version of Orleans (v1.5) I can inspect `debugContext` in [`InsideRuntimeClient.SendRequestMessage()`](https://github.com/dotnet/orleans/blob/v1.5.0/src/OrleansRuntime/Core/InsideRuntimeClient.cs#L135) and it has the following value:

    global::Orleans.Runtime.Versions.IVersionStoreGrain:GetCompatibilityStrategy()

I then set a breakpoint at `Orleans.Runtime.Versions.GrainVersionStore.GetCompatibilityStrategy()` and when the debugger breaks I see the following stack trace:

    OrleansRuntime.dll!Orleans.Runtime.Versions.GrainVersionStore.GetCompatibilityStrategy()
    OrleansRuntime.dll!Orleans.Runtime.TypeManager.GetAndSetDefaultCompatibilityStrategy()
    OrleansRuntime.dll!Orleans.Runtime.TypeManager.OnRefreshClusterMapTimer(object _)
    Orleans.dll!Orleans.Runtime.SafeTimerBase.HandleAsyncTaskTimerCallback(object state)
    Orleans.dll!Orleans.Runtime.SafeTimerBase.HandleTimerCallback(object state)
    mscorlib.dll!System.Threading.TimerQueueTimer.CallCallbackInContext(object state)

So apparently a timer fires to call [`TypeManager.OnRefreshClusterMapTimer()`](https://github.com/dotnet/orleans/blob/v1.5.0/src/OrleansRuntime/GrainTypeManager/TypeManager.cs#L141) which eventually tries to call [`IVersionStoreGrain:GetCompatibilityStrategy()`](https://github.com/dotnet/orleans/blob/v1.5.0/src/OrleansRuntime/Versions/GrainVersionStore.cs#L75) from the thread pool thread used by the timer leading to the exception being thrown by `InsideRuntimeClient`. At least that is my analysis.

Should I just ignore this? Am I doing something wrong? As far as I can see the timer fires at regular intervals so I keep seeing these exceptions when my Orleans application executes.

(This happens during development with a single silo configured to use Azure tables for system store and liveness.)

**Comment by sergeybykov** [comment]
This is getting addressed in https://github.com/dotnet/orleans/pull/3256. The plan is to include the fix in 1.5.1.

**Comment by ReubenBond** [comment]
Fixed by #3256
