### ISSUE TITLE
TestsAll.cmd Failing 3 tests in master

### ISSUE THREAD

**Issue by carlos-sarmiento** [dotnet/orleans#329]
Currently, the HEAD commit of the master branch (hash: 813d766785ba91cf8cb56c5e1d8f36df3ec76abb) has 3 tests that are failing in the TestAll.cmd

The tests are: 

    UnitTests.StorageTests.AzureTableDataManagerTests.AzureTableDataManager_MergeTableAsync
    UnitTests.StorageTests.AzureTableDataManagerTests.AzureTableDataManager_UpdateTableEntryAsync
    UnitTests.StorageTests.AzureTableDataManagerTests.AzureTableDataManager_UpdateTwoTableEntriesConditionallyAsync

I found no mention in the documentation on whether these tests should fail or not, so I'm reporting it here.

All the tests in Test.cmd are passed correctly.

**Comment by gabikliot** [comment]
Those tests depend on Azure storage emulator running on your local machine OR providing a file with Azure storage account in a folder pointed by an environment variable. This is the reason they are currently not a part of automatic CI. Did you have the storage emulator running?

**Comment by ca-ta** [comment]
@gabikliot: I am seeing the same behavior (I do have the storage emulator running)

**Comment by carlos-sarmiento** [comment]
@gabikliot I also had the Storage Emulator running. I'll try to take a look at why they are failing and report back

**Comment by gabikliot** [comment]
I think I know the reason. Will fix soon.

**Comment by gabikliot** [comment]
This is so sweet!
Azure emulator and real Azure storage service return different rest status strings for the same operation(UpdateConditionNotSatisfied vs. ConditionNotMet).
This did not impact our runtime code, which was robust to this discrepancy, just the test.
Fixed the test to be more "flexible" in this case, via #333.

**Comment by gabikliot** [comment]
Thank you both for reporting the issue! Fixed now.
