### ISSUE TITLE
Make interception of unhandled exceptions optional and non-static

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#3293]
Today, `UnobservedExceptionsHandlerClass` unconditionally intercept unhandled exceptions by adding itself to `TaskScheduler.UnobservedTaskException`. This interferes with application code if it intercepts those exceptions already and pollutes the logs. Need to make our interception optional (still on by default).

For logging unhandled exceptions, `UnobservedExceptionsHandlerClass` gets a logger instance via a static `LogManager.GetLogger("UnobservedExceptionHandler")` call. That likely has to change too, to align with the logging infra getting revamped.

**Comment by xiazen** [comment]
The way it gets its logger will be changing from LogManager.GetLogger to get a ILogger<UnobservedExceptionsHandlerClass > from DI, after we completely migrate to asp.net logging abstraction. 

To make it optional, the class will need to at least remove its static constructor. But I would suggest the following: 
- remove its static properties and methods. Make it a singleton in DI if multiple classes in the same runtime need to access it. But based on my observation in code, that is not the case. So mostly it will just become a normal class . 
- add a config in ClusterConfiguration for user to turn it on or off. By default turn it off. 

what do you think?

**Comment by xiazen** [comment]
can close after #3829 is merged
