### ISSUE TITLE
Push messages with Orleans more more slower than parallel functions

### ISSUE THREAD

**Issue by hidavidpeng** [dotnet/orleans#3321]
Hi everyone, I have some questions in orleans use.

Now I'm build my MessagePush service with v2.0. I choose the orleans as the base toolkit.
At first I tested that I can push 10k messges / second in redis. 
 ```
           QueueService service = new QueueService();
            var tsks = Enumerable.Range(1, 10001).Select(async i =>
            {
                var value = "message";
                await service.Publish(JsonConvert.DeserializeObject<TransimissionMessage>(value));
                Console.WriteLine(i);
            });
            Task.WhenAll(tsks).Wait();
```

But when i used the orleans. I have a client to push the message to silo. But it run more slow
that only have 200 messages / second in redis.

```
        public async Task<Result<string>> Push(Immutable<TransimissionMessage> message)
        {
            if (message.IsNull() || message.Value.IsNull())
            {
                return await Task.FromResult<Result<string>>( new Result<string>() { Status = StatusType.InvalidArguments, Summary = "can not be null or empty" });
            }
            var queue = new QueueService();
            var result=await queue.Publish(message.Value);
        }
```
It do the same work in grain.

I think the Orleans engine will store all the workitems in the bolckedcollection and the engine take all workitem in queue from  blockedcollection. The all run in threadpool.
So Why both functions has so big different?
I hope you can give me some advice. Thank you.

**Comment by ReubenBond** [comment]
@hidavidpeng could you please provide some more information? What is `QueueService`? It seems in your grain method you're creating a new one in every call and then immediately publishing to it - but does that QueueService perform some kind of network call? If so, does it need to connect or be configured?

**Comment by hidavidpeng** [comment]
@ReubenBond 
Thank you for your reply. 
The details of QueueService is get the connected redis subscribe and push the message to redis server.
 I realize it base stackoverflow.redis and initialize the connect when the app start. 
So its only purpose is to keep thread safe.
```
        public QueueService()
        {
            

            _here I only try to mapping the fresh instance which has initialized when app start_

            _messageQueue = new Lazy<RedisQueue<TransimissionMessage>>(()=> { return new RedisQueue<TransimissionMessage>(RedisNodeTypes.MessagePushQueue); });
        }
       
        public async Task<bool> Publish(TransimissionMessage message)
        {
            var pattern = _messageQueue.Value.Pattern;
            var result = await _messageQueue.Value.Publish(pattern, "Transimission", message);
            ...
         }
```


Also I can new it only once. Both them do the same work.
I watched that I push 10K message in redis with only 1 second by parallel
and it cost almost 20 seconds by orleans.

**Comment by ReubenBond** [comment]
If I understand correctly, @hidavidpeng, you're passing messages from a client to a grain and then to redis. Grains are single-threaded, so that will be slower than pushing those messages in parallel.

Comparing these two methods doesn't make sense to me: is the grain only there to act as an abstraction over the Redis queue? In that case, are you calling this grain from other grains or from a client?

**Comment by hidavidpeng** [comment]
@ReubenBond 
yes my friend.
Actually I have a WebAPI to the others. 
below is my code that fake 10k webapi requests. It will collect the post message and send to to my messageRouter.
**my fake requests**
```
           Parallel.For(1, 10001, index => {
                var value = "message";
                var item = new Immutable<TransimissionMessage>(JsonConvert.DeserializeObject<TransimissionMessage>(value));
                routerGrain.Push(item);
            });
```
**my parallel way**
```
           Parallel.For(1, 10001, index => {
                var value = "message";
                var item = new Immutable<TransimissionMessage>(JsonConvert.DeserializeObject<TransimissionMessage>(value));
                routerGrain.Push(item);
            });
```

It seems that i have some misunderstood of it internal realize. How can I speed it up?  Can you give me some ideas? thank you.

**Comment by ReubenBond** [comment]
Hi @hidavidpeng you can use multiple `[StatelessWorker]` grains with different identifiers (eg, round robin 16 grains)

**Comment by hidavidpeng** [comment]
@ReubenBond  thank you for you reply.
yes I have tried this function. But it only speed it up to about 1.5k/s . It also far more slower than parallel function. and event i add the [statelesswork] to 32 or more it can't speed it up again.

**Comment by ReubenBond** [comment]
@hidavidpeng it will necessarily be slower.
On one hand you have:
`Client` -> `Redis`
On the other hand you have:
`Client` -> `Something Else` -> `Redis`

No matter what the `Something Else` is, the same calls are being made from the client to redis, but with an extra step.
