### ISSUE TITLE
ServerGC recommendation warning incorrect in log files

### ISSUE THREAD

**Issue by chris-eaton** [dotnet/orleans#3322]
At the top of my log files I receive this warning

`[2017-08-18 12:33:06.834 GMT     6	WARNING	100405	Silo	192.168.5.182:22222]	Note: Silo not running with ServerGC turned on or with GCLatencyMode.Batch enabled - recommend checking app config : <configuration>-<runtime>-<gcServer enabled="true"> and <configuration>-<runtime>-<gcConcurrent enabled="false"/>	`

I thought the recommendation was to enable both of these settings? I guess this means this warning is incorrect?

**Comment by sergeybykov** [comment]
Yes, we switched the recommendation recently in #3271, and now we'll only warn you if ServerGC is off.

**Comment by chris-eaton** [comment]
Sorry, I didn't copy everything I meant to.. I have those two parameters set and its still giving me the warning

    <gcServer enabled="true" />
    <gcConcurrent enabled="true" />

**Comment by sergeybykov** [comment]
Yes, 1.5.0 still warns you about gcConcurrent=true. But 2.0 will not anymore. We made the change after 1.5.0 was released.

**Comment by sergeybykov** [comment]
Resolved via #3271.
