### ISSUE TITLE
Problem deserializing dictionary type in grain state

### ISSUE THREAD

**Issue by dandago** [dotnet/orleans#3330]
I have a grain state class that looks like this:

    public class PersonGrainState
    {
        public bool SaidHello { get; set; }
        public HashSet<string> HashSet { get; set; }
        public Dictionary<long, string> Dictionary { get; set; }
    }

When I save the grain state, it's fine. When the grain tries to read that state, though, I get errors like the following:

> Could not convert string '$id' to dictionary key type 'System.Int64'. Create a TypeConverter to convert from the string to the key type object. Path 'Dictionary.$id', line 1, position 258.
> Exception = Newtonsoft.Json.JsonSerializationException: Could not convert string '$id' to dictionary key type 'System.Int64'. Create a TypeConverter to convert from the string to the key type object. Path 'Dictionary.$id', line 1, position 258. ---> Newtonsoft.Json.JsonSerializationException: Error converting value "$id" to type 'System.Int64'. Path 'Dictionary.$id', line 1, position 258. ---> System.FormatException: Input string was not in a correct format.
>    at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
>    at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
>    at System.String.System.IConvertible.ToInt64(IFormatProvider provider)
>    at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
>    --- End of inner exception stack trace ---
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
>    --- End of inner exception stack trace ---
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at Orleans.Storage.AdoNetStorageProvider.<>c__DisplayClass41_0.<<ReadStateAsync>b__1>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Orleans.SqlUtils.RelationalStorage.<SelectAsync>d__12`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Orleans.SqlUtils.RelationalStorage.<ExecuteReaderAsync>d__13`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Orleans.SqlUtils.RelationalStorage.<ExecuteAsync>d__14`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Orleans.SqlUtils.RelationalStorage.ReadAsync[TResult](String query, Action`1 parameterProvider, Func`4 selector, CancellationToken cancellationToken, CommandBehavior commandBehavior)
>    at Orleans.Storage.AdoNetStorageProvider.<ReadStateAsync>d__41.MoveNext()

The saved state looks like this:

```
{
	"$id" : "1",
	"$type" : "OrleansStorage.PersonGrainState, OrleansStorage",
	"HashSet" : {
		"$type" : "System.Collections.Generic.HashSet`1[[System.String, mscorlib]], System.Core",
		"$values" : ["str1", "str2"]
	},
	"SaidHello" : true,
	"Dictionary" : {
		"1" : "value",
		"$id" : "2",
		"$type" : "System.Collections.Generic.Dictionary`2[[System.Int64, mscorlib],[System.String, mscorlib]], mscorlib"
	}
}
```

The deserializer seems to be confused, thinking $id is a key in the dictionary. Same thing happened with $type in another project. I have tried serializing and deserializing the same sort of classes via JSON .NET without Orleans and had no problem there.

I am using Orleans 1.4.0 and MySQL for persistent storage.

I will upload a simple repro project shortly.

**Comment by dandago** [comment]
This is a simple repro project based on an example from a talk I've given (just added a hashset and a dictionary into the grain state).

Be sure to **run it twice**. The first time, it will just save the state. The second time, it will try to read the state, and that's when the error will occur.

[OrleansStorage.zip](https://github.com/dotnet/orleans/files/1240995/OrleansStorage.zip)

**Comment by veikkoeeva** [comment]
@dandago I don't know if this help, but [the (de)serialization settings](https://github.com/dotnet/orleans/blob/ddcbdee5be747af2d2e0c2cde444168151a53606/src/OrleansSQLUtils/Storage/AdoNetConfigurationExtensions.cs) and without other settings, ADO.NET uses the default cluster settings (you can see it [here](https://github.com/dotnet/orleans/blob/64899914079d4a876a681b379928276d66dc420a/src/OrleansSQLUtils/Storage/Provider/AdoNetStorageProvider.cs#L576)).

**Comment by veikkoeeva** [comment]
The problems resembles that of https://stackoverflow.com/questions/36222394/newtonsoft-json-populate-dictionary-failed, so maybe a converter or some other typename handling thing is needed. Maybe the Orleans default isn't the same as in the tests (I haven't checked the zip file).

**Comment by veikkoeeva** [comment]
Related, so cross-referencing: https://github.com/dotnet/orleans/issues/3331.

**Comment by ReubenBond** [comment]
$id and $type both come from Json.NET. It seems that we need to try to avoid using Json.NET's `PopulateObject` method.
