### ISSUE TITLE
Grain Implementation Selection

### ISSUE THREAD

**Issue by sagron** [dotnet/orleans#3345]
Right now if you have two grains (Grain1, Grain2) that implement the same interface (IMyGrain1) then when you request a (IMyGrain1) grain logically it could choose either implementation.
Is there any way to specify the implementation that should be used by default? Or maybe orleans should just produce an warning/error when it attempts to build?

**Comment by galvesribeiro** [comment]
@sagron all [`GetGrain<T>()`](https://github.com/dotnet/orleans/blob/3ddc89756add274df0b3fba903ec50b93d8bd1e5/src/Orleans/Core/ClusterClient.cs#L156) has a parameter called `grainClassNamePrefix` which you can use to specify the concrete type at runtime.

**Comment by sagron** [comment]
Ah, when I was trying to use that parameter before I was just using the class name instead of the full qualification (with namespace). Thanks!

**Comment by galvesribeiro** [comment]
Yep, you need full qualified name otherwise we can't figure out the proper type to load. Glad it helped.
