### ISSUE TITLE
Reorganize Orleans packages and project structure

### ISSUE THREAD

**Issue by jdom** [dotnet/orleans#3353]
For several years we have been wanting to re-structure our assemblies and packages, as a lot of the decisions have been made before the NuGet rise when Orleans was still distributed in an MSI. We decided that Orleans 2.0 is finally the time for us to start that path.

TL;DR version: the biggest most important piece here is to get to a `Microsoft.Orleans.Core.Abstractions` package that we version very infrequently and try not to have breaking changes, and hopefully start applying SemVer practices at least on that one. The rest of the projects is less thought out, and we will improve with time, but the benefits of the Abstractions project heavily outweights any other comments in this issue.

Long version: This is a rough project structure that we came up with, although it might be too detailed for people not very familiar with the Orleans codebase itself:

![image](https://user-images.githubusercontent.com/1361686/29797414-c7bc0faa-8c0b-11e7-91c2-2dc323c3689c.png)

## Core.Abstractions 
  - Should not be revved frequently. Once we get to the point where we want it, it should not be modified frequently, as we should try to minimize breaking changes as much as possible. 
  - Users will mostly reference this package only from the application code, and hopefully only have to upgrade the host/client when we release new versions, but the Abstractions reference stays the same.
  - Should mostly have contracts, but no logic that might require updates/bug fixes.
  - When requiring to do changes to this assembly, extra scrutiny should be paid to the review to avoid breaking changes as much as possible (both compile time as well as runtime binding breaking changes).
  - Apply SemVer practices on this library as a first step (eventually also on other Orleans packages, but the biggest benefit for our users will be in this one).
  - Should have no configuration code. Configuration is the concern of clients and hosts.
  - This is not the place to put shared logic or small non-core utils (for example to share logic between Codegen and Core)
  - Currently requires some contracts for streaming and storage, but hopefully they can be eliminated with scoped activation services in the future (aka Facets).
      - For example, I'd like for `Grain` and `Grain<T>` to not link to storage/streaming stuff, and use scoped services to opt into that functionality (but this is too far out, as `Grain` is rooted strongly throughout the codebase)
  - We do not do build-time codegen on this assembly directly. The generated code for this assembly goes into the Core project.
    - This makes it so that updating codegen, or how we do scanning, etc, does not imply revving the abstractions nuget
    - This also avoids the need for the extremely annyoing bootstrap build step (when building Orleans itself), as the Codegen project should only reference Core.Abstractions and not Core.
  - Serialization considerations
    - `SerializationManager` will not be here (although potentially some small abstractions, but certainly not logic nor anything that mandates using our Orleans binary serializer. @ReubenBond still needs to figure this out).
    - No serialization logic for types (other than some basic BinaryFormatter annotations). Hopefully not even JSON annotations, so that this project doesn't depend on `Newtonsoft.Json`.
  - Can temporarily have logging abstractions, but they should go away and be deprecated in favor of Microsoft.Extensions.Logging (MEL)
    - This is a little bit challenging if we want to keep `LogManager` outside of Core.Abstractions. I'd advocate to try to migrate to MEL before doing Core.Abstractions, otherwise `LogManager` will attempt to bring a ton of stuff.
    - Core.Abstractions should reference `Microsoft.Extensions.Logging.Abstractions` (and not `Microsoft.Extensions.Logging` directly, as it might be a smell that we are pre-configuring logging in this abstractions assembly).
    - Metrics telemetry interface can go here (not the runtime). MEL does not handle metrics telemetry, so unfortunately we still need to have an abstraction for them (although validate first if they created abstractions for this in the upcoming release).
   
## Core
  - Shared runtime for client and silo (similar to our current Orleans.dll)
  - App developers might want to reference a few types from this, but it shouldn't be very common.
  - Runtime extensions will likely need to reference this.
  - Contains the codegen'ed code from Core.Abstractions
  - Contains the serialization code (although can potentially be split out in the future to a separate assembly)
  - Helpers/utilities that just support the core and other 3rd party assemblies should not be here, unless they require being part of the core runtime. For those supporting classes see `Sharing non-core Code`.
  - Configuration considerations
    - As we start the reorganization, we can have `ClusterConfiguration` and `ClientConfiguration` almost as is, but our intention is that they disappear eventually.
    - Create small strongly-typed Option classes (following `Microsoft.Extensions.Options` style) for the different components in Orleans, but the configuration parsing logic should not be here.
    - Create extension methods to configure the shared components, but they should just take strongly-typed Options or `IConfiguration`, but should not make any assumptions of how the settings coming from IConfiguration are parsed (we'll just leverage `Microsoft.Extensions.Configuration` for that)
    - `ClientBuilder` and `SiloBuilder` should hopefully share just source code between them and be defined in the Client and Silo projects respectively. Only include here the minimum abstractions needed for these builders to facilitate configuring both client and silos from the user's perspective.
    - Client and Silo only configuration methods should be defined in the Client and Silo projects respectively.
    - Extensions (1st part and 3rd party providers) should define the extension methods for them in their own projects.
    - If we want to support the legacy XML configuration (or the `ClusterConfiguration` and `ClientConfiguration` god objects), I would move that logic to a separate assembly that knows about both Client & Silo, and it do the translation to the smaller strongly typed extension methods (and mark this assembly as obsolete). Not saying that we should do this, just suggesting an option in case we DO want to support legacy configuration.
 
## Client
  - Client-only related classes 
  - Runtime for the client
  - ClientBuilder and utilities/extension methods related to configuring just the client
    - ClientBuilder and SiloBuilder should hopefully share just source code
  - This assembly will probably be fairly small

## Silo
  - Silo-only related classes (similar to our current `OrleansRuntime.dll`)
  - Runtime for the silo. Hopefully only the application silo host needs to reference this DLL. 
    - Until we abstract everything away nicely, I assume silo extensions might require to reference this. In the far future, if we make things such a storage providers, reminders, etc as opt-in features, they can be externalized into separate packages, so that 3rd party extensions would need to reference those instead of the Silo package.
  - SiloBuilder (See #3302 and #2936)

## OrleansCodeGenerator
  - Should not reference Core, just Core.Abstractions.
  - Any utilities that it needs to share with Core (such as for type scanning, etc) should be done by sharing source, but not referencing Core.
  - Should not require bootstrapping during the build of Orleans.sln
  - Special logic so that codegen for Core goes into Core.Abstractions, but when compiling user-level grains that just reference Core.Abstractions (and not Core), it should assume that Core.Abstractions is already codegened.

## OrleansCodeGenerator.MsBuild
  - Get rid of the console ClientGenerator project, and replace it with one that has an MsBuild task that is cross plat, as explained here: http://www.natemcmaster.com/blog/2017/07/05/msbuild-task-in-nuget/
  - Similar to OrleansCodeGenerator, do not reference Core, just Abstractions (and potentially PlatformServices)

## PlatformServices
Not related to Orleans core, but provides some simple platform-specific implementations that might be required for cross plat, so that no other project in the solution requires multi-targeting. Can be used by any project that needs platform-specific logic (but not Core.Abstractions, which should contain no complex logic).
  
## Orleans.Logging
  - Logging should eventually be deprecated in favor of Microsoft.Extensions.Logging (work started in #3333), although we can create this package to have some adaptors to support people using `ILogConsumer` as a back-compat feature (work started in #3284).  The detailed plan has been described in #3303

## Sharing non-core Code
Some extension methods / static utilities that are used by a few different projects should share the source, but not tightly couple themselves by type references, which harms version independence (creates issues with runtime binding if one nuget package version is updated by the end user, but not the other). Typical examples of these include nice-to-have internal classes that require other projects to have `InternalsVisibleToAttribute` so that they can use these handy utilities (we have several of those in our codebase).
Examples of classes that should be shared by source (to have an idea of what I mean):
  - Interner
  - SafeTimer / SafeRandom
  - TypeUtils / TypeUtilities
  - CachedReadConcurrentDictionary
  - ErrorCodes
  - LogFormatter
  - Extension methods for logging that take error code enum

There is currently a challenge to share source files in multiple projects by linking them if these projects also have `InternalsVisibleTo` to each other, as the same internal type will be defined in the same namespace as the other project. Once we get good at versioning each project independently, hopefully there will no longer be a need for `InternalVisiblesTo` in the first place, so namespace collisions will not be an issue then. But we are far out from this.

## General comments
- Align DLL names with package IDs, including the Microsoft.Orleans prefix.

Any feedback is welcome

**Comment by ReubenBond** [comment]
> migrate to MEL

My plan is finally coming to fruition! Come come come! Come to Melbourne! 🎉 👐

(plan looks good to me, I'm working out the serialization stuff)

**Comment by galvesribeiro** [comment]
> Metrics telemetry interface can go here (not the runtime). MEL does not handle metrics telemetry, so unfortunately we still need to have an abstraction for them (although validate first if they created abstractions for this in the upcoming release).

I want to do the telemetry vNext and hopefully it make the 2.0 cut as we talked before.

I'm without a Windows machine so I'm waiting the solution to build on non-windows so I can contribute that from OSX.

Good plan btw.

**Comment by sergeybykov** [comment]
I think #3833 is the last change we need here for 2.0.0.

**Comment by sergeybykov** [comment]
Closing as #3833 has been merged.
