### ISSUE TITLE
OutsideRuntimeClient should handle failures better

### ISSUE THREAD

**Issue by elqueffo** [dotnet/orleans#3363]
We are having issues with the message pump task going away and being unable to detect this from ClusterClient. I suggest making OutsideRuntimeClient either keep track of the message pump task and restart it if needed, wrapping it in a while (listenForMessages), or allow us to detect this condition via IClusterClient so that we can re-create the client.

If the message pump task dies for some reason, ProxiedMessageCenter.PendingInboundMessages will grow until the whole system exhausts its memory and things start going really wrong(tm).

Things i have considered include looking for ErrorCode.Runtime_Error_100326 in our log consumer and then recreate the ClusterClient. This would however not work for the case when the code breaks out:

                if (message == null) // if wait was cancelled
                    break;

...which would happen not only if cancelled, as one could think from the comment, but pretty much any failure reading messages.

I did a branch off of 1.5.1 and tried adding a while (listenForMessages) which seems to work reasonably well, but does kinda feel somewhat 'hacky':

        private async Task StartInternal()
        {
            ...
            // Keeping this thread handling it very simple for now. Just queue task on thread pool.
            Task.Run(
                () =>
                {
                    while (listenForMessages)
                    {
                        try
                        {
                            RunClientMessagePump(ct);
                        }
                        catch (Exception exc)
                        {
                            logger.Error(ErrorCode.Runtime_Error_100326, "RunClientMessagePump has thrown exception",
                                exc);
                        }
                    }
                },
                ct).Ignore();

Either way, i think this needs looking into, as it seems to happen in our system quite a lot; especially under heavy load. I would suggest a more sane fix, but i haven't had time to look into the interaction between all the components involved.

**Comment by ReubenBond** [comment]
Very interesting, @elqueffo. Do you happen to know of a way to reproduce the case you mentioned? I believe your resiliency suggestion is a good one anyway.

**Comment by elqueffo** [comment]
@ReubenBond Sorry, I don't have a reliable "real" repro. Usually if we run our load tests overnight we have it happen at least once. The test we do runs at more or less constant 100% CPU on a 5 node SF cluster.

You can simulate the failure by stepping out of the message pump task using the debugger.

**Comment by ReubenBond** [comment]
How are you verifying that the message processing loop is exiting?

**Comment by elqueffo** [comment]
I added very simple and obvious temporary logging in the code paths where it could exit.
