### ISSUE TITLE
Cant add logging call filter 

### ISSUE THREAD

**Issue by talarari** [dotnet/orleans#3364]
I'm trying to add a logging call filter (interceptor) to log gran calls.
i followed the documentation here:
https://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Interceptors.html

i'm getting an this error:
```
System.InvalidOperationException: Unable to resolve service for type 'Orleans.Providers.IProviderRuntime' while attempting to activate 'Felix.OrleansHost.LoggingCallFilter'.
```

not sure what i'm doing wrong. 
where am i supposed to register the IProviderRuntime implementation?

**Comment by ReubenBond** [comment]
Resolved by #3365, confirmed with @talarari that the new sample works.
