### ISSUE TITLE
IGrain interface method that receives an object of type Expression<Func<MyObject, object>>

### ISSUE THREAD

**Issue by noobwu** [dotnet/orleans#3380]
I tried to create an IGrain interface method that receives an object of type Expression<Func<MyObject, object>>, but I get the following runtime error: "No copier found for object of type System.Linq.Expressions.Expression<System.Func<MyNamespace.MyObject,System.Object>>. Perhaps you need to mark it [Serializable] or define a custom serializer for it?"
Does Orleans support Expressions serialization? I'm running v1.5.1, and MyObject is serializalbe.
_

**Comment by ReubenBond** [comment]
We currently do not support Expression serialization. You may be able to create a custom serializer for `Expression<T>` using https://github.com/esskar/Serialize.Linq by writing a [serialization provider](http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Serialization.html#method-2-writing-a-serializer-provider)
