### ISSUE TITLE
Gateway received unexpected non-proxied connection from SiloDirectConnectionId at source address

### ISSUE THREAD

**Issue by wavchik** [dotnet/orleans#3383]
On PROD environment very often I saw the following exception:

Runtime.Messaging.GatewayAcceptor" "Gateway received unexpected non-proxied connection from SiloDirectConnectionId at source address 172.29.2.1:58725" 101311
--

I don't know what is the reason of this issue and how to fix it?

I have used the following code to collect statistics from Grains (see loginstatusfetcher.txt
[LoginStatusFetcher.txt](https://github.com/dotnet/orleans/files/1280301/LoginStatusFetcher.txt)
)

Also the following configuration for Orleans has been used (see OrleansCluster.Release.txt
[OrleansCluster.Release.txt](https://github.com/dotnet/orleans/files/1280309/OrleansCluster.Release.txt)
)

We are using Microsoft.Orleans.Server (1.4.2).

After some deeper investigation I would say that issue is connected with GetDetailedGrainStatistics method.

These lines of code work well:
`var systemManagement = grainFactory.GetGrain<IManagementGrain>(ManagementGrainIndex);`
`var siloHosts = await systemManagement.GetHosts(true);`

but the next one is not
`var playerGrainStatistics =
                systemManagement.GetDetailedGrainStatistics(new[] { PlayerGrainSessionStoreName }, hostsIds);
`

![orleans-issue](https://user-images.githubusercontent.com/3667789/30119519-b1ef1c1a-932e-11e7-901c-d733f186fe29.PNG)

Also, according to Kibana logs the situation is the following:
- firstly we got `"Runtime.Messaging.GatewayAcceptor" "Gateway received unexpected non-proxied connection from SiloDirectConnectionId at source address 172.29.2.1:58724" 101311`
- then there is a Warning:
`"CallbackData" "Response did not arrive on time in 00:00:30 for message: Request S172.29.2.1:22222:239901061*grn/7483D9D2/00000001@4b522792->S172.29.2.1:30002:239901061SiloControl@S0000000c #23875037: global::Orleans.ISiloControl:GetDetailedGrainStatistics(). Target History is: <S172.29.2.1:30002:239901061:SiloControl:@S0000000c>. About to break its promise." 100157`
- then the message is :
ErrorInvoke \"S172.29.2.1:22222:239901061\" \"ManagementGrain\" null \"GetDetailedGrainStatistics\" [[\"SBTech.SessionStore.Grains.PlayerGrain\"], [\"S172.29.2.1:30002:239901061\", \"S172.29.2.2:30002:241175346\", \"S172.29.2.3:22222:241175361\"]]

and exceptions are:
`{
  "Depth": 0,
  "ClassName": "System.TimeoutException",
  "Message": "Response did not arrive on time in 00:00:30 for message: Request S172.29.2.1:22222:239901061*grn/7483D9D2/00000001@4b522792->S172.29.2.1:30002:239901061SiloControl@S0000000c #23875037: global::Orleans.ISiloControl:GetDetailedGrainStatistics(). Target History is: <S172.29.2.1:30002:239901061:SiloControl:@S0000000c>.",
  "Source": "mscorlib",
  "StackTraceString": "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Orleans.Runtime.Management.ManagementGrain.<GetDetailedGrainStatistics>d__20.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Orleans.PublicOrleansTaskExtensions.<BoxAwait>d__8`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at SBTech.SessionStore.Host.SerilogBootstrap.InvocationLogger.<Interceptor>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at OrleansDashboard.GrainProfiler.<InvokeInterceptor>d__16.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Orleans.Runtime.InsideRuntimeClient.<Invoke>d__59.MoveNext()",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": {
    "Name": "ThrowForNonSuccess",
    "AssemblyName": "mscorlib",
    "AssemblyVersion": "4.0.0.0",
    "AssemblyCulture": "",
    "ClassName": "System.Runtime.CompilerServices.TaskAwaiter",
    "Signature": "Void ThrowForNonSuccess(System.Threading.Tasks.Task)",
    "MemberType": 8
  },
  "HResult": -2146233083,
  "HelpURL": null
}`

Orleans Silos are:
![orleans-description](https://user-images.githubusercontent.com/3667789/30119808-9abb9c52-932f-11e7-92d1-5be8e0ca3abe.PNG)

**Comment by sergeybykov** [comment]
I'm trying to wrap my head around this.

You are running 3 silos with membership grain as the cluster state option or do you configure it to something else programmatically? In the former case you'd have to set a primary node (`SeedNode` in config). `DataConnectionString="http://localhost:8500"` hints that you might be using Consul, but I don't see it in the config.

This may or may not be related to the issue you are seeing. I'm just trying to understand the setup first.

**Comment by yevhen** [comment]
I've seen this few times ocassionally with Azure based membership when running multiple silos locally against storage emulator. This was after migration to 1.5. Try running multiple silos (separate processes) on different ports locally (storage emulator), should be reproducible

**Comment by wavchik** [comment]
Sergey, you're right, we are running 3 silos with membership grain as the cluster state. And yes, we are using Consul as a Membership Provider.

Below there is a code that we are using to configure membership provider. It was done due to the article
https://dotnet.github.io/orleans/Documentation/Runtime-Implementation-Details/Consul-Deployment.html
`public bool Start()
{
	Console.WriteLine("Starting SiloHost...");

	var config = new ClusterConfiguration();
	config.LoadFromFile(_configPath);

	_siloHost = new SiloHost(_siloName, config);

	try
	{
		// if we run not DEV env, we need special initialization for Consul
		if (_siloHost.Config.Globals.LivenessType != GlobalConfiguration.LivenessProviderType.MembershipTableGrain)
		{
			_siloHost.Config.Globals.LivenessType = GlobalConfiguration.LivenessProviderType.Custom;
			_siloHost.Config.Globals.MembershipTableAssembly = "OrleansConsulUtils";
			_siloHost.Config.Globals.ReminderServiceType = GlobalConfiguration.ReminderServiceProviderType.Disabled;
		}

		_siloHost.InitializeOrleansSilo();
		var ok = _siloHost.StartOrleansSilo();

		if (ok)
		{
			Console.WriteLine($"Successfully started Orleans silo '{_siloHost.Name}' as a {_siloHost.Type} node.");
		}
		else
		{
			Console.WriteLine($"Failed to start Orleans silo '{_siloHost.Name}' as a {_siloHost.Type} node.");
		}
		return ok;
	}
	catch (Exception exc)
	{
		_siloHost.ReportStartupError(exc);
		var msg = $"{exc.GetType().FullName}:\n{exc.Message}\n{exc.StackTrace}";
		Console.WriteLine(msg);
		return false;
	}
}
`

**Comment by benjaminpetit** [comment]
Are you running the 3 silos on the same machine? If yes, are they supposed to share the same ip address?

Also, could you log the values of `hostIds` that you are using as a parameter? Do you have the same issue if you leave this parameter null?

From what I understand, you get this message when a silo is trying to connect to another silo via the Gateway port ( that should only accept client connection), not the silo to silo port.

From your configuration, the gw port is `300002`, the silo-to-silo is `22222`. And in your logs, we can see:

> Request S172.29.2.1:**22222**:239901061*grn/7483D9D2/00000001@4b522792->S172.29.2.1:**30002**:239901061SiloControl@S0000000c

So it seems that the silo where the `ManagementGrain` is trying to send a message to its own local gateway? And the generation id doesn't seems to match either...

**Comment by sergeybykov** [comment]
@wavchik
>Sergey, you're right, we are running 3 silos with membership grain as the cluster state. And yes, we are using Consul as a Membership Provider.

Do you mean that you are using membership grain for local (development) case and Consul for production case?

In the code snippet above:
>// if we run not DEV env, we need special initialization for Consul
	if (_siloHost.Config.Globals.LivenessType != GlobalConfiguration.LivenessProviderType.MembershipTableGrain)

that *if* is what switches between local and production case, right?

If that's the case, are you seeing the connection issue in the local case? Are you starting more than one silo with exact same silo and gateway ports? In the XML config I only see 22222/30002.

If you start more than one silo locally with membership grain, then each silo needs to unique ports, and one of them designated as the primary (seed) node. I don't see that in the XML config or the code above.

It feels like I'm missing something here still.

@yevhen 
Can you elaborate? We run some tests in such a configuration, and have never seen a silo trying to connect to a gateway port. I've done the same when doing and Orleans workshop. Work just fine. I can try again, but I'd be very surprised...

**Comment by yevhen** [comment]
@sergeybykov I'm not sure how I did that but it was related to the content of membership table. It was containing some confusing entries, like silo in a status JOINING while it was actually dead. After clean up I can't repro it anymore.

**Comment by sergeybykov** [comment]
@yevhen I just tried running a couple silos with Azure Storage Emulator, and they started and formed a cluster just fine. If you had old records in the table for the same cluster ID, it could take some time for the protocol to mark them as DEAD. That's expected. I suspect @wavchik is seeing something else.

**Comment by wavchik** [comment]
@benjaminpetit 

> Are you running the 3 silos on the same machine? If yes, are they supposed to share the same ip address?


In my case there are 3 different servers where Orleans is running up.

> Also, could you log the values of hostIds that you are using as a parameter? Do you have the same issue if you leave this parameter null?
Nope, I didn't do it. But I definitely will check this case.
After some investigation I did re-deploy of Orleans and currently there is no such issue.

@sergeybykov 

> Do you mean that you are using membership grain for local (development) case and Consul for production case?
Yes. In our case on local env we are running Orleans in membership grain and on QA / STG / PROD we are using Consul.

> that if is what switches between local and production case, right?
Yes. _siloHost.Config.Globals.LivenessType equals to GlobalConfiguration.LivenessProviderType.MembershipTableGrain on local env only.

> If that's the case, are you seeing the connection issue in the local case? Are you starting more than one silo with exact same silo and gateway ports? In the XML config I only see 22222/30002.
Nope. On local env I didn't see something similar. Even on STG I ddin't see this issue.
In my case STG and PROD are the same servers: we have 3 servers and run Orleans on them, but in appropriate configuration. i.e. 
STG => <Networking Address="" Port="11111" /> and <ProxyingGateway Address="" Port="30001" />,  DeploymentId="LoginCaptcha_SessionStore_Staging_1"
PROD => <Networking Address="" Port="22222" /> and <ProxyingGateway Address="" Port="30002",
DeploymentId="LoginCaptcha_SessionStore_Production_1" />


> If you start more than one silo locally with membership grain, then each silo needs to unique ports, and one of them designated as the primary (seed) node. I don't see that in the XML config or the code above.
Localy we are running one instance of Orleans.

**Comment by benjaminpetit** [comment]
So you are using the same `DeployementId` across multiple deployements, correct (ie when upgrading your prod, the value doesn't change)?

**Comment by yevhen** [comment]
@benjaminpetit yes, we do rolling restart

**Comment by wavchik** [comment]
@benjaminpetit 
Yes, all PROD Orleans' instances use the same `DeployementId`.
STG Orleans also use the same `DeployementId`, but it differs from the PROD one.

**Comment by sergeybykov** [comment]
@wavchik Has this been resolved?
