### ISSUE TITLE
Hello World Silo on different machine

### ISSUE THREAD

**Issue by samcov** [dotnet/orleans#3392]
It's not immediately obvious how to configure the client/server to make the separate process sample work.

Is there an example somewhere?

**Comment by benjaminpetit** [comment]
I don't think we have a sample like you describe, but [this documentation](https://dotnet.github.io/orleans/Documentation/Deployment-and-Operations/Configuration-Guide/Typical-Configurations.html#reliable-production-deployment-using-azure) should help you for the configuration.

**Comment by samcov** [comment]
Thanks!
