### ISSUE TITLE
Unable to start Silo by StartOrleansSilo

### ISSUE THREAD

**Issue by Sheshadrinath** [dotnet/orleans#3408]
I am following the step-by-step guide provided in Orleans. I installed necessary nuget packages as per the guidelines and replicated the same code as given in the example. When I run the program, the silo host is not starting and returning always false.

`
                siloHost = new SiloHost(System.Net.Dns.GetHostName());
                siloHost.ConfigFileName = "OrleansConfiguration.xml";
                siloHost.InitializeOrleansSilo();
                var startedok = siloHost.StartOrleansSilo();
                
if (!startedok)
                                throw new SystemException(String.Format("Failed to start Orleans silo '{0}' as a {1} node", siloHost.Name, siloHost.Type));
`

I tried with Orleans.Core with version starting from 1.2.3 to 1.5.1 (latest). I am getting same error in with Windows and Mac computer. I am not able to get much help. Can anybody help and tell me what is the mistake I am doing?

**Comment by sergeybykov** [comment]
What does it say in the log?

**Comment by sergeybykov** [comment]
Have you tried following the steps described in http://dotnet.github.io/orleans/Documentation/Getting-Started-With-Orleans/Running-the-Application.html? The tutorials are somewhat outdated. The documentation is more current.
