### ISSUE TITLE
When to use injected service instead of a worker

### ISSUE THREAD

**Issue by csyszf** [dotnet/orleans#3417]
I'm confused with workers and injected service.
It seems like that most workers in my project could be replaced by DI services, for example, I have a password hasher in my project, should it be a worker or DI service ?

**Comment by ReubenBond** [comment]
Injecting the password hasher is a fine approach 👍 Personally, I used workers for services like SMS, Email, push notifications (eg, GCM, APN). Those services could also have been injected, so perhaps that's not much guidance.

One case for using a `[StatelessWorker]` instead is when you have a fairly long-running process (sending 50 fire-and-forget push notifications, for example) and you want the calling grain to be free to process other requests while that's occurring.

**Comment by csyszf** [comment]
@ReubenBond thanks for your response
