### ISSUE TITLE
Orleans can not use Autofac.Extensions.DependencyInjection

### ISSUE THREAD

**Issue by noobwu** [dotnet/orleans#3433]
/// <summary>
        /// 
        /// </summary>
        /// <param name="services"></param>
        /// <returns></returns>
        public override IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddAutofac((config)=> ConfigBuilder(config));
            return services.BuildServiceProvider();
        }
Autofac.Extensions.DependencyInjection version is  4.2.0    
Orleans verion is 2.0.0-preview3
 var factory = (IServiceProviderFactory<ContainerBuilder>)ServiceProvider.GetService(typeof(IServiceProviderFactory<ContainerBuilder>));
factory is null

**Comment by MikeHardman** [comment]
We are using AutoFac successfully with 1.5.1 but we have to return a new AutofacServiceProvider, a simple example is below:

`   /// <summary>
    /// 
    /// </summary>
    /// <param name="services"></param>
    /// <returns></returns>
    public override IServiceProvider ConfigureServices(IServiceCollection services)
    {
        services.AddScoped<IService,Service>();

        var builder = new ContainerBuilder();
        builder.Populate(services);         
        builder.RegisterModule<MyModule>();

        return new AutofacServiceProvider(builder.Build());
    }`

**Comment by noobwu** [comment]
thank you @MikeHardman  i
let me try
