### ISSUE TITLE
Startup ConfigureServices result doesn't appear to be used

### ISSUE THREAD

**Issue by MikeHardman** [dotnet/orleans#3460]
We have a ConfigureServices implementation that returns a fallback service provider implementation that we only intend to use as a transitional device while we (finally) move away from Ninject in our legacy code base. It looks as follows:

   ```
public class LegacyServiceProvider : IServiceProvider
    {
        private readonly IServiceProvider _systemProvider;
        private readonly IKernel _kernel;

        public LegacyServiceProvider(IServiceProvider systemProvider, IKernel kernel)
        {
            _systemProvider = systemProvider;
            _kernel = kernel;
        }

        public object GetService(Type serviceType)
        {
            var systemService = _systemProvider.GetService(serviceType);            
            return systemService ?? _kernel.Get(serviceType);
        }
    }
```

This type is returned by ConfigureServices as follows:
```
var orleansProvider = services.BuildServiceProvider();
 var serviceProvider = new LegacyServiceProvider(orleansProvider, container);
 return serviceProvider;
```

This worked fine in 1.4.2 but after moving to 1.5.1 GetService in the LegacyServiceProvider isn't being hit for GrainActivations and dependent services need to be added to the IServiceCollection being passed into the ConfigureServices method or they fail to be resolved by ActivatorUtilities.GetService.

**Comment by kogir** [comment]
I had a similar problem when I upgraded to 1.4: https://gitter.im/dotnet/orleans?at=58ae13fa7ceae5376a273e4d

To fix it I just loaded my services into Orleans' default container.

**Comment by MikeHardman** [comment]
Hi kogir, thanks for your response. Unfortunately I'm not in a position to migrate some of our legacy bindings just yet, some are quite bound to a specific container implementation. I have a workaround that is starting to become a little messy in that I create wrapper services for the legacy services I want to call upon from grain code and bind those into the provided service collection but I would much prefer to be able to use my own container consistently.

I've added a demonstration project with no dependencies other than Orleans that I think shows what's going on over at [https://github.com/MikeHardman/OrleansDIIssue](https://github.com/MikeHardman/OrleansDIIssue) The client successfully activates the grain with the dependency bound into the service collection, but not the grain with the dependency only available in the returned service provider. It is clear the provider is being used for *some* services internal to Orleans though, so perhaps I'm just missing a binding somewhere?

**Comment by jdom** [comment]
Did you register this legacy provider as the `IServiceProvider` returned by it? That's probably the immediate issue. Nevertheless, be aware that having layers of service providers is a big pain and ~can probably~ will bite you next.
For example, if from IServiceProvider you resolve ServiceA, which ends up forwarding the request to the decorated container, and then ServiceA wants to inject something that is on the wrapper container, the decorated container will not be able to resolve it. Just passing the request back to a decorated container is not enough.

Orleans is meant to play nicely with a single container, whether that's the one that comes by default, or one that integrates will the conforming DI abstraction. As far as I know, Ninject didn't release any official integration to Microsoft.Extensions.DependencyInjection yet.

Any chance you can switch to either the default container or some that integrates with the conforming container abstraction?

**Comment by jdom** [comment]
BTW, in case you haven't seen it, but are willing to push forward, we have an extensibility point specifically to enable some non-conforming containers, but it's still not friction free. That's [IGrainActivator](https://github.com/dotnet/orleans/blob/v1.5.1/src/OrleansRuntime/Catalog/IGrainActivator.cs). Notice that there is some churn coming in 2.0.0 in this area, as we are using the conforming container approach more, and benefiting from scoped services (each grain activation will use a new scope).

**Comment by MikeHardman** [comment]
That looks like the ideal plug point that I have missed! I'll keep my eye on the 2.0.0 stuff, I don't think our transition will be straight forward at all but it will probably serve as a much needed project re-organisation opportunity in the future!

**Comment by MikeHardman** [comment]
I'm not sure how this behavior can be rectified without a conforming extension for Ninject in our case, given other issues we are experiencing with Ninject regarding scope in OWIN we've pushed ahead with work to change our module system over to conform wherever possible and used AutoFac at the core for any of the late or contextual binding. This is no longer a significant issue for us now that a successful migration path is at least clear.
