### ISSUE TITLE
Orleans 1.3.0, Grain factory instance across app domains 

### ISSUE THREAD

**Issue by edikep2000** [dotnet/orleans#3461]
Hello everyone,

I have a use case where I need to sandbox a user request in another app domain from within a silo.
However, the method to be sandboxed has a dependency on grain factory instance to be passed in to the method from within the silo. However since grain factories  are not serializable it seems a straightforward approach does not exist. 

Please does anyone have any ideas as to how to accomplish this,  I. E marshal grain calls across app domains

**Comment by sergeybykov** [comment]
Can't you instead of passing a grain factory into the sandbox app domain give it a custom `MarshalByRefObject` object and invoke respective calls in the silo app domain? I don't think trying to marshal a grain factory will work. And app domains are largely going away in .NET Core anyway.
