### ISSUE TITLE
Stack trace growth with async/await and TaskCompletionSource

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#3470]
Illustrated by @yevhen and investigated by @dVakulen in https://stackoverflow.com/questions/46467275/weird-stack-trace-growth-with-async-await-and-taskcompletionsource. The implications are excessive stack traces that can grow fast and potential related performance issues.

**Comment by yevhen** [comment]
The best course of action here is to create specialized exception, such as BatchItemException and wrap original exception as inner exception.

**Comment by sergeybykov** [comment]
Let's consider what we can do for 2.0.0.

**Comment by ReubenBond** [comment]
I think there's nothing much we can do about it other than be careful. Are there any places in Orleans code where this manifests?
