### ISSUE TITLE
Clarifications on grains backward compatibility

### ISSUE THREAD

**Issue by talarari** [dotnet/orleans#3478]
Hi, 
I've read through the docs provided on grain versioning and compatibility and i have some questions.

In regards to what is said here: 
http://dotnet.github.io/orleans/Documentation/Grain-Versioning/Compatible-grains.html
http://dotnet.github.io/orleans/Documentation/Grain-Versioning/Backward-compatibility-guidelines.html

I understand all the restrictions on changing a grain interface signature.
you cant remove/change anything because old client/silo will still try to use the old interface.

What i don't understand though, are the restrictions on changing a grain's implementation.

These comments for instance:
1. http://dotnet.github.io/orleans/Documentation/Grain-Versioning/Compatible-grains.html#definition
_"since Orleans use an internal built-in serializer, modifying/renaming a field (even private) can make the serialization to break"_
Why would a change to a private field in a grain's implementation break compatibility?

2. http://dotnet.github.io/orleans/Documentation/Grain-Versioning/Backward-compatibility-guidelines.html#avoid-changing-existing-method-logic
Why is it dangerous to change the method body of a grain's implementation? if its provides the same signature why should Orleans care about the implementation?

Would appreciate some more info, thanks!

**Comment by benjaminpetit** [comment]
> Why would a change to a private field in a grain's implementation break compatibility?

What we meant about that is: "modifying/renaming a method parameter or changing anything in the object passed as a parameter can make serialization to break"

You can change private field in a grain implementation without any issue related to serialization, if this field is not serialized.

> Why is it dangerous to change the method body of a grain's implementation? if its provides the same signature why should Orleans care about the implementation?

Orleans don't care about the implementation. It is just a simple rule to avoid any issue with backward compatibility of your code (ie if your new implementation have  new side effects that would not be handled by older clients0. If you know what you are doing, you should be fine
