### ISSUE TITLE
Staging production deployment on service fabric

### ISSUE THREAD

**Issue by talarari** [dotnet/orleans#3479]
We have an Orleans cluster deployed on service fabric.
We currently use rolling upgrades and it works fine for now, but we want to switch to a staging/production deployment process.

I've read the docs:
https://dotnet.github.io/orleans/Documentation/Grain-Versioning/Deployment.html#using-a-staging-environment.

_" The Production and the Staging silos and clients will be part of the same cluster. It is important that silos from both environment can talk to each other."_

How can i achieve this on service fabric?

Basically i can provision a new (v2) version in the same cluster in service fabric, and when i'm ready to switch to it i can unprovision v1.

What i'm missing is how will these two versions talk to each other?
What should i configure in service fabric to make the two deployments know each other and basically act as one cluster with multiple versions of the same grains?

In this case i will have v1 grains that are configured to talk to orleans like this
```
  var client = new ClientBuilder()
                .UseConfiguration(new ClientConfiguration())
                .AddServiceFabric(new Uri("fabric:/Felix.App/Felix.OrleansHost"))
                .Build();
```
So that same Uri should also somehow be aware of the new v2 silos.

**Comment by ReubenBond** [comment]
@talarari I'm not sure how you would achieve this on Service Fabric - it's not something which most SF is intended for, as far as I know. Instead they employ a rolling update model.

A common alternative is to deploy your updates to a pre-production environment and test them there before deployment to your production environment.

This is the strategy I'm familiar with from past systems. We used it for all of our services (some of which were built on SF).

**Comment by talarari** [comment]
I read that this is how you do blue green deployments on service fabric.
But how would you do this even without service fabric? My question is How do you make the new staging silo talk to the old prod silo?

**Comment by talarari** [comment]
Ok i couldn't get silos from two different service fabric app to be in the same cluster (i guess this is a heterogeneous silo?), if i'm getting this right, this is the approach suggested here:
https://dotnet.github.io/orleans/Documentation/Grain-Versioning/Deployment.html#using-a-staging-environment.
couldn't find any docs to help me with this, so any help on that is welcome.

i'm going to try a different approach, would appreciate feedback if i'm way off here:
I want to use the multi cluster feature to help me with blue green deployments, so basically :
lets say we have blue cluster up and running as the production cluster.

*deploy new version:*
1. spin up a new cluster with the new code to green
2. join green cluster to the multi cluster.
3. direct traffic to green cluster.
3. shut down the blue cluster, causing all activations to jump to the new cluster.
4. remove the blue cluster from the global cluster configuration.

*rollback*
1.re-provision blue cluster with the same app version it had before shutting it down.
2. join blue cluster to global cluster.
3. direct traffic to blue cluster.
4. shut down green cluster.
4. remove the green cluster from the global cluster configuration.

thoughts?

**Comment by ReubenBond** [comment]
I don't suggest blue/green deployments with Service Fabric, use rolling upgrades instead.

If you do want to use staging deployments with a cluster hosted on Service Fabric, you can do so by not using the Service Fabric integration package and instead start a silo inside your Stateless service manually using a membership provider such as Azure Tables. With that approach, you can have multiple SF apps which are a part of the same cluster and hence you can deploy different versions side-by-side.

**Comment by talarari** [comment]
@ReubenBond thanks for the suggestion, can you direct me to docs/sample code to start the silo manually?

the reasons we want blue green deployments are:
1. support grain versioning, like suggested here:https://dotnet.github.io/orleans/Documentation/Grain-Versioning/Deployment.html#using-a-staging-environment
2. run smoke tests on the environment before directing traffic to it
3. fast rollback 

number 1 is the primary reason, how do i support grain versioning with rolling updates?
making sure the grain is always fully compatible is impossible, our code will change and we need to support that.

What's mentioned here: https://dotnet.github.io/orleans/Documentation/Grain-Versioning/Deployment.html#using-a-staging-environment
is the closest i could find to a suggested strategy for changing grain interfaces.

appreciate the help!

**Comment by ReubenBond** [comment]
@talarari apologies for not getting back to you. If this is still an issue, we can schedule a skype call to talk about deployment options. Blue/green is not supported by SF, so I still strongly suggest not pursuing that avenue and instead opting for the [Rolling Upgrade option in the versioning docs](https://dotnet.github.io/orleans/Documentation/Grain-Versioning/Deployment.html#rolling-upgrade). When you perform a rolling upgrade, you can manually advance and rollback the upgrade with SF. 

In 2.0 we have introduced a SiloHostBuilder to ease configuration. Along with that, we've also added a distinction between Service Fabric *Hosting* and *Clustering*: you can now more easily host a service on SF while using Azure Tables for clustering. See the sample here: https://github.com/dotnet/orleans/blob/2931252c567bedcd9ce1f8dfd8e1a2f14e46e39f/Samples/ServiceFabric/Stateless/StatelessCalculatorService/StatelessCalculatorService.cs#L39

**Comment by talarari** [comment]
thanks for the answer @ReubenBond .
We're currently using a test environment and rolling updates in production.
That gives us some level of confidence that the deployment wont break production. 

What we wanted to achieve with a staging production deployment is 2 things:
1. Validate the actual deployment to production before directing traffic to it.
In a rolling upgrade this is not possible, so when something goes wrong it goes wrong in production.
Even with staging/production (using versions and table membership) this is pretty hard to do in Orleans, since we use streams and reminders test traffic we direct to the staging silos might affect non-staging grains as well.
(I can go into more detail on this if needed)

2. Not needing to keep the grains backwards compatible.
since our only case for 2 different versions of grains is while upgrading, if we just deployed a new version and swapped to it - we wouldn't have to think about backwards compatibility.

Our current setup is workable, we we're used to using staging/prod with stateless web apis before and it made life easy.
Not sure this is possible with Orleans but any advice you have on solving these 2 problems is definitely appreciated.

**Comment by talarari** [comment]
@ReubenBond would love to take you up on the offer of having a skype call to talk about recommended ways to achieve this.
How do you want to set this up?

Thanks again

**Comment by ReubenBond** [comment]
Hi @talarari, could you DM me on Gitter and we'll work out a time? Apologies for the delay.

**Comment by talarari** [comment]
Sure, will do, thanks!

**Comment by sergeybykov** [comment]
Closing it. Feel free to reopen if something else is needed here.
