### ISSUE TITLE
dotnetcore2.0 client configuration for testing

### ISSUE THREAD

**Issue by pms1969** [dotnet/orleans#3493]
Hi.  Thanks for the new Preview3.  You guys are doing a great job.

So Preview3 works quite well in a deployed scenario.  But for testing scenarios from VS or Rider or even using `dotnet test`, if I spin up a silo (from another project or a docker container) and then want to run some client tests that target this silo (from a aspnetcore2.0 app - nunit testing project), I have to copy the grains to the fallback folder for the Microsoft.Orleans.Core package.  This is because of the way that the Assembly loader works.  It loads assemblies from the directory of the assembly that it exists in.  Since there's very little copying of assemblies in dotnetcore apps, this creates an issue when the tests start up, and prevents the client from finding any dlls to scan for grains.

I don't know if there is some way to do the copying in dotnetcore (if so, please let me know), but either way, it would be nice to have a way of telling the client where to find grains, the same way that the silo has the ability to over-ride (using AdditionalAssemblyDirectories?).  At worst, that would require me to publish the grain and then configure the client to search the publish directory during the test run.

Thanks again.
Paul

**Comment by jdom** [comment]
yes, this is a known issue that we are planning to address. I'm not sure what's the best workaround in the meantime, although I do believe you can make the `build` target to also `publish`, correct? Not sure what does mean for testing, but it's something to explore.

**Comment by jdom** [comment]
This should no longer be an issue in preview4 or beta, with the new way the type discovery works and explicitly providing assembly parts to scan. Feel free to reopen if you are still having issues
