### ISSUE TITLE
Enhancing threading model

### ISSUE THREAD

**Issue by dVakulen** [dotnet/orleans#3498]
Based on research done in https://github.com/dotnet/orleans/pull/2060 which is currently in some unreadable state, but have shown performance  improvements of [up to 80%](https://github.com/dotnet/orleans/pull/2060#issuecomment-297853999).

**Short overview  of current design:**
 - Orleans uses SEDA pattern with `BlockingCollection`s as work items storage. 
 - Main contention and CPU burning points are located in descendants of `AsynchQueueAgent` and in `WorkQueue`. They caused by usage of `BlockingCollection`'s, specifically the behavior of spinning for a bit on dequeue when there's no items, which happens quite often under low to medium load. This also is source of increased thread switching with related overhead. 
 - Descendants of `AsynchQueueAgent`  encapsulate in themselves threading, queuing and 'business' logic at the same time, thus having a few orthogonal responsibilities. 

**Theoretical solution:** 
 - Use of single work-stealing queue and single thread pool should cut latency of end to end request-response cycle by ~50% due to increased data cache locality (tests have shown that with such implementation more than half of work items are being retrieved from thread local storage). It also completely removes CPU burning, which can lead to increased operational costs while running in cloud and on premises, and reduces number of thread context switches, thus improving latency and throughput at the same time. 

**Suggested solution:**
- Abstract threading and queuing logic behind  `ExecutorService` with API somewhat similar to .Net ThreadPool, this service will have switchable implementations. 
One of them will be just moved current logic, and another - the new one implemented as described in theoretical solution part. After move of current implementation descendants of `AsynchQueueAgent`  will be responsible only for the relevant to each of them algorithms and queuing of tasks to `ExecutorService`,  while `WorkerThread`s will be executing not only grain call path related items, but also those from  `AsynchQueueAgent`s. It's fairly easy to make such stage logic move without losing of any of current contracts, stages will still be existent, but behind the abstraction. 

**Details of additional threading implementation**:
 - In https://github.com/dotnet/orleans/pull/2060 it was implemented by adopting .Net ThreadPool code with necessary changes to make it work outside .Net library and support some features of existing implementation. Such approach gives flexibility, but also brings high costs of reviewing and supporting. 
 - Alternatively .Net ThreadPool can be used directly. It has 2 main API for queuing of work - `QueueUserWorkItem` and, indirectly, `Task.Run`. The latter one has unacceptable performance implications, but allows work to be stealed,  while `QueueUserWorkItem` shows relatively good performance, but all queued work items going to global (shared between threads) queue, which easily can become the bottleneck with Orleans queuing rates. 
- So if taking the burden of supporting some kind of mirror of .Net ThreadPool is not an option - there's three alternatives: 1 - Use reflection to get work items queued to thread local queues, which also comes at risk of breaking due to .Net library updates, though that part of .Net was relatively stable through releases. 2 - wait for [exposing of `QueueUserWorkItem` with 'preferLocal' optional parameter](https://github.com/dotnet/coreclr/pull/14214), which will allow items queued through that API to land into thread local queues, to get into release and use that. And the third one - combined approach of using reflection for now (it does not incur high risks, as there will be configuration - which `ExecutorService` implementor to use) and switching on `QueueUserWorkItem` method overload after release containing it will become Orleans target. 

**Questions**: 
- Does suggested approach seems acceptable?
- Whether there's a need in it's implementation  (it will need very thoughtful review, while requiring additional changes directed on removing of contention points in other places of Orleans, which have arisen during testing of prototype (most of them were fixed in scope of https://github.com/dotnet/orleans/pull/2060, but they still require extracting, refactoring and are subjects to separate PR's), otherwise it  will provide smaller performance improvements under silo saturation condition, than mentioned in the start of the issue).

**Comment by sergeybykov** [comment]
Thank you for driving this effort! It's very interesting and seems to have a good potential for performance improvements. I think we should seriously consider it after 2.0 is out.

**Comment by gabikliot** [comment]
Going to follow up this thread with a lot of interest. Thank you @dVakulen for driving this!
Abstracting the implementation behind a common interface (like you suggested) and being able to compare the different approaches on different workloads will be the key for success here.

**Comment by ReubenBond** [comment]
I believe we have achieved the goals of this now, first by using a modified fork of the CoreCLR ThreadPool code (#3792), and eventually removing that fork and using the .NET Thread Pool directly (#6261) - with several steps in between.
