### ISSUE TITLE
Grain implementing more than one IGrain-derived interface?

### ISSUE THREAD

**Issue by maiorfi** [dotnet/orleans#350]
Hi.

I'd like to "partition" Grains public interface according to access from different front-ends.

Is possible and/or convenient implementing different IGrain-derived interfaces on same Grain?

Thanks!

**Comment by sergeybykov** [comment]
Yes, it's totally possible and easy for a grain to implement more than one grain interface.

**Comment by gabikliot** [comment]
@maiorfi , it is currently supported and works.

**Comment by maiorfi** [comment]
Great news, thanks!
