### ISSUE TITLE
HelloWorld.NetCore sample cannot load cluster configuration

### ISSUE THREAD

**Issue by bluexo** [dotnet/orleans#3506]
```
System.MissingMethodException: 'Method not found: 'Void Orleans.Runtime.Configuration.NodeConfiguration.set_DefaultTraceLevel(Orleans.Runtime.Severity)'.'
```
I think 'NodeConfiguration.DefaultTraceLevel' field has removed in new version cause this question

**Comment by jdom** [comment]
Yes, it was removed recently, although I don't believe it was removed for preview3... Do you have a mix of different versions of Orleans? Those kind of exceptions only occur if something was compiled against some assembly version, but you are running with a different version of that same assembly.
