### ISSUE TITLE
Good fit or not? Imaging documents

### ISSUE THREAD

**Issue by mishakogan** [dotnet/orleans#351]
Let's say I have a billion word documents and I need to image them (create images out of every page).
Ideally I would use something that can expand to 100 of servers, process documents and then reduce to few servers and continue working on smaller jobs until another billion word documents come in.

I was thinking that each grain can be responsible for processing a document or a page of a document using third-party imaging api? 

Is orleans a good fit for above?

**Comment by sergeybykov** [comment]
In my opinion this is a borderline app. It is doable with Orleans but it appears to be more of batch processing in nature, at least from my interpretation of your description. Orleans is better suited for interactive workloads, e.g. if you had to image these documents and return results to the callers within milliseconds/seconds. It can be used to distribute and orchestrate a parallelizable batch job like this one, but there are more options for parallel batch job execution out there.
