### ISSUE TITLE
Orleans Client Use BenchmarkDotNet Error

### ISSUE THREAD

**Issue by noobwu** [dotnet/orleans#3512]
Orleans Version is Github Master
![image](https://user-images.githubusercontent.com/4328356/31303641-9262e8f4-ab43-11e7-8d29-7c38b22705ed.png)
Parse error in the following line:
      	* Assembly contains no types assignable from Orleans.Providers.IProvider.

**Comment by jdom** [comment]
I'm not sure I understand what's the context or the issue here. Can you provide more information?

**Comment by noobwu** [comment]
No BenchmarkDotNet can run normally
It's wrong to use BenchmarkDotNet 
 /// <summary>
    /// Categories Grain测试
    /// </summary>
    public class CategoryGrainBenchmark : OrleansBenchmarkBase
    {
        private ICategoryGrain grain;
        [GlobalSetup]
        public void GlobalSetup()
        {
            StartClient();
            grain = GrainClient.GrainFactory.GetGrain<ICategoryGrain>(GetIntGrainId());
        }
        #region Select/Get/Query
        /// <summary>
        /// Gets an entity with given primary key.
        /// </summary>
        /// <param name="id">Primary key of the entity to get</param>
        /// <return awaits>Entity</return awaits>
        [Benchmark]
        public virtual async Task<Category> SingleAsync()
        {
            int id = RandomData.GetInt();
            return await grain.SingleAsync(id);
        }
   }
var summary = BenchmarkRunner.Run<CategoryGrainBenchmark>();

**Comment by ReubenBond** [comment]
@noobwu see the [Benchmarks](https://github.com/dotnet/orleans/blob/master/test/Benchmarks/Benchmarks/Ping/PingBenchmark.cs) project for an example on how to set up BenchmarkDotNet with Orleans
