### ISSUE TITLE
Grain versioning stream support

### ISSUE THREAD

**Issue by talarari** [dotnet/orleans#3513]
In the docs for grain versioning it mentions that versioning is not supported in streaming interfaces, what does that mean?

We have a grain that publishes messages on a stream and other grains subscribe to it.

Were planning to move to a staging/production kind of deployment using the version selector strategy of minimum version.
Which the docs for deployment describe allows you to set up your staging silos with the new version, and because of the version strategy, untill you direct traffic to the new silos no activations will be created there.
Does that mean that if i  a grain on the old silos publishes a message on a stream it can reach activations in the new staging silos?

**Comment by benjaminpetit** [comment]
> In the docs for grain versioning it mentions that versioning is not supported in streaming interfaces, what does that mean?

That mean that we didn't tested anything here yet :)

> Does that mean that if i a grain on the old silos publishes a message on a stream it can reach activations in the new staging silos?

It depends on what version selector / compatibility strategy you have configured.

By default (minimum version + backward compatible), If there is any pulling agent working on the new silos, then they will create "v2" activations. I think, for now, if you want to validate the new silos, you should not start any pulling agents on them before the validation.

If you use minimum version + all versions compatible then your new pulling agent should only create activations on the "old" silos. But to use this combination, you have to be sure that there is no breaking change between grain versions.

**Comment by talarari** [comment]
Thanks for the answer.
From what i get streams act like grain calls, so they should at some point check the version selector strategy to get the right grain right?
I tried reading through the code to find this and couldn't find that, could someone guide me to a specific place this happens?

We want to somehow have two environments and be able to very quickly switch between them (deploy new code and rollback) and also be able to validate new code before directing 100 traffic to it. basically a blue green deployment.
But we are having trouble with understanding how this can be done without the two environment affecting one another due to the fact that we use streams for a lot of things.

**Comment by benjaminpetit** [comment]
> From what i get streams act like grain calls, so they should at some point check the version selector strategy to get the right grain right?
> I tried reading through the code to find this and couldn't find that, could someone guide me to a specific place this happens?

Yes the streaming pull agent will do regular grain calls.

> But we are having trouble with understanding how this can be done without the two environment affecting one another due to the fact that we use streams for a lot of things.

Could you do "manual" grain call client to validate the new grains?

**Comment by talarari** [comment]
@benjaminpetit  not sure what you mean by "manual", could you explain?

Just to make sure i understand then.
**In a system built like this:**
For simplicity lets assume i only have one silo in my cluster.
Lets say i have these grains:
1. PublisherGrain (v1)
2. SubscriberGrain (v1)

Also there's a WebApi referencing IPublisherGrain and ISubscriberGrain (both v1) deployed in the same cluster.

Calling a WebApi with some data, calls PublisherGrain.publish(data).
PublisherGrain calls OnNext(data) on "topic-1" stream
SubscribeGrain is subscribed to "topic-1" receives the data and handles it.

**Can i assume this is true?**
if i deploy a new silo with all grains versioned to v2 and with a new WebApiV2 referencing theses v2 grains.
Can i expect that until i direct traffic to WebApiV2 , stream events being published by PublisherGrain(v1) in silo 1 will not reach SubscriberGrain(v2) ?
