### ISSUE TITLE
Is the Multi-Cluster silo configuration only available for AzureTable?

### ISSUE THREAD

**Issue by Kimserey** [dotnet/orleans#3515]
I looked through the code and samples and could only find an implementation with AzureUtils.

In my application, I have multiple clusters, different grains implementation on each cluster, and therefore instantiate multiple clients (one per cluster).
If I understand correctly, multi-cluster will allow me to have clusters with different grain implementations acting as a single deployment and therefore only one client will be needed to communicate with all grains.

If this is correct, is the Multi-Cluster silo configuration only available for AzureTable?

**Comment by sergeybykov** [comment]
>I have multiple clusters, different grains implementation on each cluster, and therefore instantiate multiple clients (one per cluster).

The multi-cluster feature is primarily intended for geo-distribution (for fault tolerance and/or locality). I wonder if Heterogeneous Silos (http://dotnet.github.io/orleans/Documentation/Deployment-and-Operations/Heterogeneous-Silos.html) within a single cluster fit your needs better.

**Comment by Kimserey** [comment]
> The multi-cluster feature is primarily intended for geo-distribution

I see, thanks for the answer. I'll look into heterogeneous silos.

**Comment by sergeybykov** [comment]
To be clear, the design of multi-cluster gossip is not limited to Azure Table. That's just a first implementation of gossip channel we put in. But there can (and should) be other gossip implementations. Contributions are more than welcome.
