### ISSUE TITLE
Upgrade NonSilo.Tests to .NET 4.7 to support ValueTuple

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#3531]
ValueTuple support is "spotty" on older versions of .NET and we're seeing that type equality fails.

**Comment by ReubenBond** [comment]
For the time being, I'm going to skip some tests and link them to this issue. We must reenable the tests when this is fixed.

**Comment by AwsomeCode** [comment]
Is it better to upgrade to 4.7.1?

**Comment by ReubenBond** [comment]
either way is fine for ValueTuple. Generally we try to stick to Version - 1. In this case it's just a test project, though.
