### ISSUE TITLE
Cleaning Orleans.Core.Abstractions

### ISSUE THREAD

**Issue by benjaminpetit** [dotnet/orleans#3557]
For 2.0 beta, we moved some internals types to Abstractions, that we want to remove it for 2.0 final.

- [x] Remove `FieldUtils` to remove dependency on `System.Reflection.Emit.Lightweight`
- [x] Embbed in generated code used code from `PublicOrleansTaskExtensions`, `TaskUtils` and `GrainExtensions`
- [x] Remove the member `Silo.StreamProviderManager` and uses DI instead
- [x] Add missing XML comments
- [x] Move logger to a "legacy" project

**Comment by ReubenBond** [comment]
I assume we're planning to keep `PublicOrleansTaskExtensions.Ignore()` exposed. Perhaps it should be in Core and not Abstractions, though

**Comment by jason-bragg** [comment]
Orleans has a set of 'utilities' that are not central to the actor model.  We've discussed how to expose these without adding risk to the core framework and abstractions.  I suspect these should be considered in that discussion.

**Comment by sergeybykov** [comment]
`Ignore()` is a good example of the tradeoff. We want (I think) it available to grain developers. So it can't be in Core, even though it has some logic, and in general we don't want to have logic in Abstractions.

**Comment by benjaminpetit** [comment]
It seems that everything is ticked now. We can close this one
