### ISSUE TITLE
Call OnDeactive before marking the silo as killed

### ISSUE THREAD

**Issue by jdahl** [dotnet/orleans#3563]
The setup
- Grain gets lots of calls at the rate of 1000's per seconds
- You want to do a safe rolling update or shutdown of a silo in a cluster without loosing state
- Storage update is done on a timer (Doesnt have to be for this issue)
- Storage update is done in OnDeactiveAsync to guarantee no state is lost during a rolling update
- Updating state in durable storage for every update that is done isn't possible for other reasons

The problem is that if a silo is shutdown gracefully it will now tell all other silos its killed. Then it will call OnDeactiveAsync. This will store the state of the grain. However if any other silo has got a call during this time (Enough with a few seconds at these call rates) it would have had time to startup and read the old state of the grain before the call to OnDeactiveAsync was done in the silo that is going down. At lower call rates this can of course happen but will be much harder for a user/operator to discover.

I know state will be lost during crashes and other failures. This is only for the graceful shutdown of a silo. Where you want to be sure no state can ever be lost since it is graceful. Other cases can be ignored to make this issue more manageable.

I wonder if a solution to this specific problem would be to change Terminate(bool gracefully) to call
```c# 
 // 3: Deactivate all grains
SafeExecute(() => catalog.DeactivateAllActivations().WaitWithThrow(stopTimeout));
```
before
```c#
// 1: Write "ShutDown" state in the table + broadcast gossip msgs to re-read the table to everyone
scheduler.QueueTask(this.membershipOracle.ShutDown, (this.membershipOracle as SystemTarget)?.SchedulingContext).WaitWithThrow(stopTimeout);
```
You would probably also need a new silo state before this that didn't allow this silo to start new grains but otherwise function as normal during the time OnDeactiva is called on all grains

**Comment by sergeybykov** [comment]
>I wonder if a solution to this specific problem would be to change Terminate(bool gracefully) to call

I don't think this will work. Unless the silo announces that it is in the shutdown mode, new activation may get placed to it, which is undesirable.

>However if any other silo has got a call during this time (Enough with a few seconds at these call rates) it would have had time to startup and read the old state of the grain before the call to OnDeactiveAsync was done in the silo that is going down.

This is surprising. We shouldn't unregister a grain activation from directory before it is fully deactivated (including calling `OnDeactiveAsync`). There's something to investigate here.

However, we generally advise against relying on `OnDeactiveAsync` for state management. Any state that you don't want to lose needs to be written to storage immediately. `OnDeactiveAsync` is intended for optional best effort notifications about grain getting deactivating.

**Comment by jdahl** [comment]
If this shouldn't be possible as far as you know then I better analyze the issue more on our side so it's not actually a fault in our system before you spend any more time on it.

**Comment by sergeybykov** [comment]
A repro case (ideally, a failing test) would help here greatly. Thanks!

**Comment by jdahl** [comment]
After some investigation this is on our side and orleans is doing exactly what it should so I'll close this issue.
