### ISSUE TITLE
We have unhandled exception 'There are no context policies' in cancelToken.Register and application crashes (ThrowUnobservedTaskExceptions = false)

### ISSUE THREAD

**Issue by alexvmk** [dotnet/orleans#3570]
Hello! when the cluster is running, after some time I get an unhandled exception: Unhandled Exception: [2017-10-13 13:32:02.142 GMT 205 ERROR 100324 Silo 127.0.0.1:22230] !!!!!!!!!! Called DomainUnobservedExceptionHandler with context Name:*.Host.ConsoleApp.exe
There are no context policies. .
Exc level 0: MyException: exception text. Server stack trace: .......... And my host application crashes. Could you help me? Because of what I can receive such an unhandled exception, because of which the application falls?

My code:
cancellationToken?.CancellationToken.Register(async (state1) =>
{
Log("cancelled outside");
...
}, state);
I get an unhandled exception inside Register callback.
we have https://github.com/dotnet/orleans/blob/master/test/Tester/CancellationTests/GrainCancellationTokenTests.cs#L86 but it is not incleded in test's sets.

Orleans **version**: 1.5.1.
I do not have full **stack trace** now.
**Exception** kind: inner exception - it is my exception which i threw.

@sergeybykov wrote:
I see that we have a test for this, CancellationTokenCallbacksThrow_ExceptionShouldBePropagated but it's not included in either BVT or Functional sets. @dVakulen might remember what's going on here.

**Comment by ReubenBond** [comment]
@alexvmk there are many potential causes. Do you have a full stack trace? What kind of exception is it? Which version of Orleans are you using?

The `DomainUnobservedExceptionHandler` is called when an exception goes unobserved. It handles the `AppDomain` `UnhandledException` event. You can add your own handler to that event and observe it for yourself: `AppDomain.CurrentDomain.UnhandledException += (sender, args) => { /* observe exception */ };`

**Comment by kogir** [comment]
`CancellationToken.Register` does not expect an async delegate. Just pass a normal Action:

```
cancellationToken?.CancellationToken.Register(state1 =>
{
Log("cancelled outside");
...
}, state);
```

The way you've currently written it the result of the Task produced when the action is invoked is never observed.
