### ISSUE TITLE
Abrupt client disconnection from stream causes Silo's to stall

### ISSUE THREAD

**Issue by chris-eaton** [dotnet/orleans#3571]
I have 4 silos (running in production) that send data to a SMS stream like so

Setup
```
var streamProvider = this.GetStreamProvider("SMSProvider");
this.plotPointDataStream 
          = streamProvider.GetStream<string>(this.account.Id.ToGuid(), "PlotDataStream");
```

I then send data like so
```
await this.plotPointDataStream.OnNextAsync(Newtonsoft.Json.JsonConvert.SerializeObject(plot));
```

FYI I have had issues with Orleans automatically serialising Plot itself, so for now have opted to serialize it to a string manually - I doubt this is affecting me at the moment.

In the client (IIS) I subscribe to the stream like so

```
var streamProvider = this.grainClient.GetStreamProvider("SMSProvider");var stream = streamProvider.GetStream<string>(accountId.ToGuid(), "PlotDataStream");

var streamHandle = await stream.SubscribeAsync(async (plot, token) =>
{
   await this.SendPlotToWebsockets(accountId, plot);
});
```

So if I shut down IIS Express (I have only tested whilst running the website from a debugger) or set a breakpoint then the entire Orleans cluster pauses completely.  If I quit IIS Express from VS then the Orleans cluster (which is running in production) pauses for 30-60 seconds.

This doesnt seem right to me, is this an issue or expected behaviour? I'm worried about deploying this code as it may adversely affect processing for fairly large periods of time.

**Comment by sergeybykov** [comment]
>If I quit IIS Express from VS then the Orleans cluster (which is running in production) pauses for 30-60 seconds.

How exactly to you see the cluster "pausing" manifesting? In general, clients cannot impact execution of silos (other than by sending them work via requests). So I don't see the connection here.

Or do you mean that you see a pause in messages being delivered over the stream after you abruptly kill a subscribed client?

**Comment by chris-eaton** [comment]
Hey Sergey.

I see basically message throughput drop to 0, I presume because the application sending data to Orleans has a concurrent message limit and I think that when the subscribed client dies the await on the OnNextAsync method waits blocking that grain. After a while the data sender hits a concurrency limit (we impose max of 20 concurrent messages sent at once) 

I am using the Orleans Dashboard to monitor it. After a while throughput resumes and no data is lost.

**Comment by chris-eaton** [comment]
It seems related to this https://github.com/dotnet/orleans/issues/982

**Comment by sergeybykov** [comment]
@chris-eaton Are you still experiencing this issue?
>I see basically message throughput drop to 0, I presume because the application sending data to Orleans has a concurrent message limit and I think that when the subscribed client dies the await on the OnNextAsync method waits blocking that grain.

I'm not sure I understand this. Does "the application sending data to Orleans" refere to an Orleans client making calls to grains? Or is it something else?

>and I think that when the subscribed client dies the await on the OnNextAsync method waits blocking that grain.

Where's that `await` you are referring to: in the client code or within the grain method being invoked?

**Comment by chris-eaton** [comment]
Hi @sergeybykov it doesnt seem to happen anymore. I believe (I cant 100% remember) that I solved it by reducing the client timeout setting.

When the message throughput dropped to 0 that was the ability for clients to send data into Orleans via Grain calls.

The `await` I mentioned was within a Grain within a Silo.

**Comment by sergeybykov** [comment]
Thanks. So I'll close it then. Please reopen if you run into this issue again.
