### ISSUE TITLE
Orleans 2 Preview 3 - Bug - when using AuthenticationHandler<JwtBearerOptions>

### ISSUE THREAD

**Issue by claylaut** [dotnet/orleans#3572]
# Orleans 2, Preview 3 - Bug when using AuthenticationHandler

Trying to create custom `AuthenticationHandler` is throwing an exception in `Orleans.CodeGenerator`.

I've created the below sample so it will be easily reproducible. 

## Replication Steps:
* Git Clone https://github.com/claylaut/OrleansCustomAuthHandlerSample
* Build Solution
* Launch Project (F5)

## Extra Information:
* I've created `AuthHandler` which inherits from `: AuthenticationHandler<JwtBearerOptions>` which is not being used.
* This is throwing a `Orleans.CodeGenerator.CodeGenerationException` during runtime in `OrleansConfig.cs` at `Line 41`.

## Exception Details:
```
Exc level 0: Orleans.CodeGenerator.CodeGenerationException: (1,3052): error CS0266: Cannot implicitly convert type 'object' to 'Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerEvents'. An explicit conversion exists (are you missing a cast?)
(1,8967): error CS0266: Cannot implicitly convert type 'object' to 'Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerEvents'. An explicit conversion exists (are you missing a cast?)
   at Orleans.CodeGenerator.CodeGeneratorCommon.CompileAssembly(GeneratedSyntax generatedSyntax, String assemblyName, Boolean emitDebugSymbols)
   at Orleans.CodeGenerator.RoslynCodeGenerator.CompileAndLoad(GeneratedSyntax generatedSyntax, Boolean emitDebugSymbols)
   at Orleans.CodeGenerator.RoslynCodeGenerator.GenerateAndLoadForAssemblies(Assembly[] inputs)	
```

## Other
If it will throw an exception at `Line 43` that `Orleans.Runtime.SiloUnavailableException: The target silo became unavailable for message:` it means that the applications is working fine.

**Comment by claylaut** [comment]
Anyone has any ideas/other implementations/workarounds which I can use for now?

**Comment by attilah** [comment]
@claylaut Would you give it a try with Orleans 2.0 Preview 4 bits what we published 2 days ago?

Since Preview 3 we changed the whole assembly loading, type discovery and codegen.

There is no runtime codegen, only build time codegen. Based on the error you see that is a runtime codegen problem.

**Comment by attilah** [comment]
Fixing the broken meta packages: https://github.com/dotnet/orleans/pull/3582

**Comment by claylaut** [comment]
@attilah Thanks for fixing this :). this was blocking me to continue migrating to `.NET CORE 2`.

@attilah @jdom do you know when this will be released please? #3582

**Comment by jdom** [comment]
I already pushed it to myget

**Comment by claylaut** [comment]
Cheers! I will close this issue since it should be fixed.

Thanks again guys!
