### ISSUE TITLE
Improve logging in 2.0.0

### ISSUE THREAD

**Issue by jdom** [dotnet/orleans#3580]
In the 2.0.0 beta release, there is no default logging, as we migrated to Microsoft.Extensions.Logging, and it's up to the user to configure it.
We can provide some documentation and templates that log something useful by default, as it's critical in a distributed system.

There is no Microsoft-owned rolling text file logger, but we should still provide an easy approach for this, making sure it includes timestamps for each entry (either endorse a 3rd party or re-target our legacy logger against the new abstractions).

Also, as we are moving off the legacy ClusterConfiguration and ClientConfiguration objects as the mechanism for configuring Orleans, we need to provide a way to output important configuration information when the silo/client starts. This is critical to troubleshoot issues from external customers when the person helping does not have access to the code, as well as having it in a well-known place even with code access.

**Comment by xiazen** [comment]
> We can provide some documentation and templates that log something useful by default, as it's critical in a distributed system.

Definitely agree. 

> There is no Microsoft-owned rolling text file logger, but we should still provide an easy approach for this, making sure it includes timestamps for each entry (either endorse a 3rd party or re-target our legacy logger against the new abstractions).

We have a Orleans.Logging.FIleLogger in master, and targeting to release with 2.0 beta. Just to point out that we already have that in Orleans. 

> Also, as we are moving off the legacy ClusterConfiguration and ClientConfiguration objects as the mechanism for configuring Orleans, we need to provide a way to output important configuration information when the silo/client starts. This is critical to troubleshoot issues from external customers when the person helping does not have access to the code, as well as having it in a well-known place even with code access.

I can see that this is valuable. But to which level of detail we log and how exactly we plan to achieve this is debatable. Is this here just as an issue to track remaining work in logging?

**Comment by xiazen** [comment]
Finished: 
- documentation on logging for orleans 2.0 
- `Orleans.Logging.FileLogger` is released with 2.0 beta, which supports rolling text file logging. 

TODO:
provide a way to output important configuration information when silo/client starts

**Comment by sergeybykov** [comment]
Done.
