### ISSUE TITLE
Orleans on .NET Core (preview) - Using Current Directory and missing to load grain assemblies in AppDomain Base Directory

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/orleans#3584]
Hello,

This might not be an issue, but I address it anyway.

I'm using the preview (2.0.0-preview3-20170913) on .NET Core, and walked through the tutorial. The Silo missed my grain, for some reason, and inspecting the output gave me the hint that the Silo looked for assemblies with grains in the current directory (and not probing sub directories) (another indication is that log files ends up in the current directory - same directory as the project is defined). Since I add reference to the Grain project (in the Host project), the grain assembly ends up in the build - or execution - directory, not in the project directory (hence the miss).

By using 'Directory.SetCurrentDirectory' with the directory from 'AppDomain.Current.BaseDirectory', the tutorial sample worked (as expected) (and the log files ended up in the executing directory).

I have no idea if this is an issue or not.

**Comment by sergeybykov** [comment]
In 2.0.0-preview4 we switched to explicit passing of application assemblies to the runtime for scanning. See https://github.com/dotnet/orleans/blob/master/Samples/HelloWorld.NetCore/src/SiloHost/Program.cs for an example. This makes assembly scanning more deterministic and silo initialization much faster.

**Comment by jan-johansson-mr** [comment]
The sample code is actually very clean :-)

Thanks!
