### ISSUE TITLE
Performance Counter alternatives in 2.0.0

### ISSUE THREAD

**Issue by attilah** [dotnet/orleans#3586]
In current Orleans we are using Performance counters for multiple things:
- Expose [Orleans system metrics](https://github.com/dotnet/orleans/blob/master/src/Orleans.Core/Statistics/RuntimeStatisticsGroup.cs) as Performance counters
- Read CPU utilization for the load shedding [streaming](https://github.com/dotnet/orleans/blob/bfcc00f4fcd001334431bbf2511915e75747c192/src/Orleans.Runtime/Streams/LoadShedQueueFlowController.cs) feature
- Collect [Thread context switch](https://github.com/dotnet/orleans/blob/bfcc00f4fcd001334431bbf2511915e75747c192/src/Orleans.Core/Statistics/ThreadTrackingStatistic.cs#L209) statistics
- Make it possible to [register performance counters](https://github.com/dotnet/orleans/blob/bfcc00f4fcd001334431bbf2511915e75747c192/src/Orleans.TelemetryConsumers.Counters/OrleansPerfCounterTelemetryConsumer.cs) for grain by grain type, so grain count per type can be monitored

As Orleans 2.0 will support multiple OS platforms, Performance Counters are not a viable way ahead, so we're looking for alternate solutions:
- Keep the performance counter feature, but separate it into a Windows only package
- Move away from performance counters at all and implement a similar functionality on top of [System.Diagnostics.Tracing.EventSource](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventsource?view=netcore-2.0) and associated classes, since they're part of .Net Standard 2.0
- Since reading the processor utilization without elevated privileges through ETW is not possible, it's probable, that load shedding will be abstracted out from the system and be a Windows only feature in Orleans 2.0

Building on top of the Tracing infrastructure it enables us to provide richer statistics and insights - with the support of event payloads - into a running system which can be consumed with standard ETW (Event Tracing for Windows) tools, when running under Windows, like [perfview](https://github.com/Microsoft/perfview).

**Comment by xiazen** [comment]
I thought performance counters is back in netstandard, according to @jdom 's notes. Is this not true? 

btw just linking related issue so we can tackle them together. #2609
