### ISSUE TITLE
Microsoft.Orleans.OrleansCodeGenerator.Build Cant't Build

### ISSUE THREAD

**Issue by hanxinimm** [dotnet/orleans#3597]
![image](https://user-images.githubusercontent.com/13499426/31983974-30867ecc-b992-11e7-8b68-7eb690c65f3f.png)

![image](https://user-images.githubusercontent.com/13499426/31998040-dfe6b07a-b9c0-11e7-935b-f44934f5537a.png)

1>Expression: [Recursive resource lookup bug]
1>Description: Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: ArgumentNull_Generic
1>Stack Trace:

But Microsoft.Orleans.OrleansCodeGenerator work well.

**Comment by sergeybykov** [comment]
>But Microsoft.Orleans.OrleansCodeGenerator work well.

I'm confused - you said it "work well", but the title says "Cant't Build". What is the issue exactly?

**Comment by xiazen** [comment]
his title said Microsoft.Orleans.OrleansCodeGenerator.Build  can't build. 

although I'm not sure if there is a difference between Microsoft.Orleans.OrleansCodeGenerator.Build  and Microsoft.Orleans.OrleansCodeGenerator ?

**Comment by ReubenBond** [comment]
Thanks for reporting, @hanxinimm :) Could you provide us with build logs?

**Comment by jdom** [comment]
This seems similar to https://github.com/dotnet/orleans/issues/3598 (which I believe it's related to running in a non-English runtime)

**Comment by hanxinimm** [comment]
@sergeybykov  Microsoft.Orleans.OrleansCodeGenerator 2.0.0-preview3-20170913 work well
but #3582 Remove it
@jdom is right
https://github.com/dotnet/corefx/issues/24832
