### ISSUE TITLE
[Question] Configuring Azure table membership when running Orleans on ServiceFabric

### ISSUE THREAD

**Issue by rvarna** [dotnet/orleans#3607]
We are seeing a lot of timeouts happening when a grains client is calling in to a grain when Orleans is hosted on Service Fabric. Currently we use Service fabric for maintaining Orleans membership. We want to try using Azure Table storage to eliminate one variable in our debugging. Both are client and silo are running on the same service fabric cluster. I have tried setting a few properties on the Silo and ClientConfiguration to get it to use AzureTables but I do not see the SiloInstances table show in Azure Storage.

Client:
```
var config = new ClientConfiguration
            {
                DeploymentId = Regex.Replace(siloServiceUri.PathAndQuery.Trim('/'), "[^a-zA-Z0-9_]", "_"),
                GatewayProvider = ClientConfiguration.GatewayProviderType.AzureTable,
                //DataConnectionString = siloServiceUri.AbsoluteUri,
                DataConnectionString =  <Azure_storage_connectionString>,
                PropagateActivityId = true
            };

var orleansClient = new ClientBuilder()
                .UseConfiguration(config)
                .AddServiceFabric(siloServiceUri)
                .AddClientInvokeCallback(CopyContextToOrleansContext)
                .Build();
await orleansClient.Connect();
```

Silo configuration:
```
Dictionary<string, string> tableStorageProviderProperties = new Dictionary<string, string>();
tableStorageProviderProperties["DataConnectionString"] = <Azure_storage_connectionString>;
tableStorageProviderProperties["DeleteStateOnClear"] = "true";
config.Globals.DataConnectionString = storageConnectionString;
config.Globals.RegisterStorageProvider<AzureTableStorage>("Default", tableStorageProviderProperties);
config.Globals.LivenessType = GlobalConfiguration.LivenessProviderType.AzureTable;
config.Globals.UseLivenessGossip = true;
config.Globals.MembershipTableAssembly = typeof(AzureConfigurationExtensions).Assembly.FullName;
config.Defaults.StartupTypeName = typeof(ClusterStartup).AssemblyQualifiedName;
config.Defaults.PropagateActivityId = true;
```

_ClusterStartup_ (used as startupTypeName above) is defined as:
```
public class ClusterStartup
        {
            public static ServiceFabricSilo Service { get; set; }

            public IServiceProvider ConfigureServices(IServiceCollection services)
            {
                services.AddServiceFabricSupport(Service);
                services.AddSingleton(Service.Partition);
                return services.BuildServiceProvider();
            }
        }

```
Any ideas on what we are doing wrong?
The grain timeout example:
`System.TimeoutException: Response did not arrive on time in 00:00:30 for message: Request *cli/8bcc209e@c176c49e->S10.0.0.4:40000:246669425*grn/5E295826/00000000+00000000-0000-0000-0000-000000001e4d:e2d7dfbb-26cf-44cb-9951-f2f767ca83c2 #1613: global::ControlPlane.GrainInterfaces.IDeploymentGrain:CreateDeployment(). Target History is: <S10.0.0.4:40000:246669425:*grn/5E295826/00000000+00000000-0000-0000-0000-000000001e4d:e2d7dfbb-26cf-44cb-9951-f2f767ca83c2:>.\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at ControlPlane.Frontend.DeploymentController.<>c__DisplayClass1_0.<<CreateOrUpdateDeployment>g__Create0>d.MoveNext() in src\\ControlPlane\\ControlPlane.Frontend\\Controllers\\DeploymentController.cs:line`

**Comment by ReubenBond** [comment]
Membership looks in from the DI container for an implementation of `IMembershipOracle` & `ISiloStatusOracle` (which should resolve to the same instance) before looking at the configuration.

To configure Azure Tables for membership with ServiceFabric, you can drop the call to `AddServiceFabricSupport()` on both the client and the silo.

/cc @elqueffo: what was your experience in configuring Azure Tables with Service Fabric?

**Comment by rvarna** [comment]
That seems to do the trick, thanks!

**Comment by talarari** [comment]
@rvarna
Were experiencing lots of timeouts on service fabric as well, mostly during deployment.
was actually considering switching to table storage for the same reason.

Did it solve the timeouts for you?

**Comment by rvarna** [comment]
Yes, it did. I haven't seen an instance of the timeout after we made the change.

**Comment by talarari** [comment]
@rvarna what did you use as deploymentId for the host and clients?

**Comment by rvarna** [comment]
@talarari We just use ServiceFabriAppName_ServiceName. For example, for fabric:/CalculatorApp/CalculatorService, we use DeploymentId == CalculatorApp_CalculatorService in client and silo.
