### ISSUE TITLE
I can't get 'GrainClient.ClientInvokeCallback' to fire, with Orleans '2.0.0-preview4-20171025'

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/orleans#3614]
Hi,

I try to wire up a callback on the client side, but it doesn't fire at all. I'm puzzled.

Here is a snippet (taken from the sample and modified slightly):

        while (true) {
                try {
                        var config = ClientConfiguration.LocalhostSilo();

                        client = new ClientBuilder()
                                .UseConfiguration(config)
                                .AddApplicationPartsFromReferences(typeof(IMyGrain).Assembly)
                                .ConfigureLogging(logging => logging.AddConsole())
                                .Build();

                        GrainClient.Initialize(config);
                        GrainClient.ClientInvokeCallback = (request, grain) => { RequestContext.Set("IsExceptionConversionEnabled", true); };

                        await client.Connect();

                        Console.WriteLine("Client successfully connect to silo host");
                        break;
                } catch (SiloUnavailableException) {
                        attempt++;
                        Console.WriteLine($"Attempt {attempt} of {initializeAttemptsBeforeFailing} failed to initialize the Orleans client.");
                        if (attempt > initializeAttemptsBeforeFailing) {
                                throw;
                        }
                        await Task.Delay(TimeSpan.FromSeconds(4));
                }
        }

This causes an exception in the grain, since I try to get the value from the 'RequestContext' (it's never set on the client before sending the message).

E.g. on the Grain side:

        var q0 = (bool) RequestContext.Get("IsExceptionConversionEnabled");

Causes an 'NullReferenceException'

**Comment by ReubenBond** [comment]
Hi @jan-johansson-mr, when you're using `ClientBuilder`, don't use `GrainClient` - `ClientBuilder` replaces it.

We should add `[Obsolete]` attributes to the `GrainClient` methods.

Instead, use the `AddClientInvokeCallback(...)` extension method of the client builder.

**Comment by jan-johansson-mr** [comment]
Thanks,

Will try it out!

**Comment by jan-johansson-mr** [comment]
It worked great! :-)
