### ISSUE TITLE
Could not unregister reminder, from the reminder table, due to tag mismatch.

### ISSUE THREAD

**Issue by NitishMittalHon** [dotnet/orleans#3615]
Hi,

I am getting below exception:

`ERROR 102912	Orleans.Runtime.ReminderService.LocalReminderService 10.150.152.254:11111]	!!!!!!!!!! Could not unregister reminder <IOrleansReminder: GrainRef=GrainReference:*grn/A1FE6CB/4512adee1e5289478c74ff931ed0f1b1030000000a1fe6cb-0x26027D15 ReminderName=SomeReminderName ETag=W/"datetime'2017-10-27T11%3A33%3A08.4598111Z'"> from the reminder table, due to tag mismatch. You can retry.`

`WARNING	100843	Orleans.Runtime.ReminderService.LocalReminderService 10.150.152.254:11111]	Delete failed on the reminder table. Will retry. Entry = Reminder [ PartitionKey=00000000-0000-0000-0000-000000000000_26027D15 RowKey=GrainReference=4512adee1e5289478c74ff931ed0f1b1030000000a1fe6cb-SomeReminderName GrainReference= ReminderName= Deployment= ServiceId= StartAt= Period= GrainRefConsistentHash=]`

I wanted to understand what might  be happening here. It happens occasionally. Looks like same grain have been stuck and not able to receive Reminder ticks as well:

`ERROR 102915	Orleans.Runtime.ReminderService.LocalReminderService 10.150.152.254:11111]	!!!!!!!!!! Could not deliver reminder tick for [SomeReminderName, GrainReference:*grn/A1FE6CB/4512adee1e5289478c74ff931ed0f1b1030000000a1fe6cb-0x26027D15, 00:02:00, 2017-10-27 11:33:38.873 GMT, W/"datetime'2017-10-27T11%3A33%3A08.4598111Z'", 155, Ticking], next 10/27/2017 11:42:13 AM.	Exc level 0: System.TimeoutException: Response did not arrive on time in 00:01:00 for message: Request S10.150.152.254:11111:246799154/567A1EA9/00000000@S00000000->S10.150.152.254:11111:246799154*grn/A1FE6CB/1ed0f1b1@5374c2a8 #506: global::Orleans.IRemindable:ReceiveReminder(). Target History is: <S10.150.152.254:11111:246799154:*grn/A1FE6CB/1ed0f1b1:@5374c2a8>. at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Orleans.Runtime.ReminderService.LocalReminderService.LocalReminderData.<OnTimerTick>d__19.MoveNext()`

I am using Orleans 1.4.2

**Comment by sergeybykov** [comment]
What are you using for reminder storage?

**Comment by NitishMittalHon** [comment]
Hi @sergeybykov ,
we are using Azure BlobStore for storage.

**Comment by sergeybykov** [comment]
>we are using Azure BlobStore for storage.

I don't think this is even possible - to use Azure Blob Store for reminders. Can you share your config?

**Comment by NitishMittalHon** [comment]
Hi @sergeybykov ,
Sorry for the wrong information; I thought Orleans uses same storage for storing reminders as for storing grain state. Following is the configuration:

```
<?xml version="1.0" encoding="utf-8"?>
<OrleansConfiguration xmlns="urn:orleans">
  <Globals>
    <Liveness LivenessType="AzureTable"/>
    <SystemStore SystemStoreType="AzureTable" />
    <BootstrapProviders>
      <Provider Type="CloudService.OrleansBoostrapProvider"
                Name="OrleansBoostrapProvider"
                InstanceCount="1"/>
    </BootstrapProviders>

    <StreamProviders>
      <Provider Type="Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProvider" Name="SMStreamProvider"/>
    </StreamProviders>
    <Messaging ResponseTimeout="60s"/>
    <PlacementStrategy DeploymentLoadPublisherRefreshTime="1m" />
  </Globals>
  <Defaults>
    <Networking Address="" Port="11111" />
    <ProxyingGateway Address="" Port="30000" />
    <Tracing DefaultTraceLevel="Info" TraceToConsole="false" BulkMessageLimit="1600" PropagateActivityId="true">
      <TraceLevelOverride LogPrefix="Application" TraceLevel="Info" />
      <TraceLevelOverride LogPrefix="SiloLogStatistics" TraceLevel="Verbose" />
    </Tracing>
    <Statistics MetricsTableWriteInterval="300s" PerfCounterWriteInterval="300s" LogWriteInterval="30s" WriteLogStatisticsToTable="true"/>
    <Limits>
      <Limit Name="MaxEnqueuedRequests" HardLimit="50000" SoftLimit="10"/>
    </Limits>
  </Defaults>
</OrleansConfiguration>

```
Please note that the grain which is using reminder is storing its state in BlobStore. This is how the storage is initialized:

```csharp
var properties = new Dictionary<string, string>();
var connectionString = CloudConfigurationManager.GetSetting("DataConnectionString");
properties.Add("DataConnectionString", connectionString);
properties.Add("ContainerName", "grainstate141");
config.Globals.RegisterStorageProvider<AzureBlobStorage>("BlobStore", properties);
config.Globals.RegisterStorageProvider("Orleans.Storage.MemoryStorage", "PubSubStore");
```

**Comment by sergeybykov** [comment]
Is it possible that the reminder storage was populated with a different version of the application? Did you try to clear it before starting the app?

>Could not deliver reminder tick for [SomeReminderName, GrainReference:*grn/A1FE6CB/4512adee1e5289478c74ff931ed0f1b1030000000a1fe6cb-0x26027D15, 00:02:00, 2017-10-27 11:33:38.873 GMT, W/"datetime'2017-10-27T11%3A33%3A08.4598111Z'", 155, Ticking], next 10/27/2017 11:42:13 AM. Exc level 0: System.TimeoutException: Response did not arrive on time in 00:01:00 for message: Request S10.150.152.254:11111:246799154/567A1EA9/00000000@S00000000->S10.150.152.254:11111:246799154*grn/A1FE6CB/1ed0f1b1@5374c2a8 #506: global::Orleans.IRemindable:ReceiveReminder().

Does the grain target get activated? Is it possible that it is busy processing (for a very long time) another request?
