### ISSUE TITLE
Orleans Docker support

### ISSUE THREAD

**Issue by benjaminpetit** [dotnet/orleans#3620]
Let's track here all issue about running Orleans in Docker.

Issues/Fixes to do:

- [ ] Rewrite documentation page
 ~~[  ] Add a config flag to not listen to the `AppDomain.CurrentDomain.ProcessExit` event~~
- [x] Fix the shutdown issue in Linux #3621 
- [ ] Fix or find a workaround for the shutdown issue when using Windows Container #3621

**Comment by SebastianStehle** [comment]
I would prefer not to have a config flag. This is something that should just work. Because when you have an on premise solution you also have to expose this flag to the users / customers.

**Comment by benjaminpetit** [comment]
Updated the issue

**Comment by petargyurov** [comment]
Is there any update on when the docs will be updated? The client and silo configuration on the current docs is using the legacy `ClientConfiguration()` and `ClusterConfiguration()`; updating this would be extremely helpful.
