### ISSUE TITLE
Orleans silo shutdown in Docker

### ISSUE THREAD

**Issue by benjaminpetit** [dotnet/orleans#3621]
Related to #3620 

When running in a container, when the container is asked to stop, docker should send `SIGTERM` signal to the entrypoint of the container, allowing it to shutdown gracefully.

- Using Windows container: it seems that no signal is sent to the running process in the container. We are still working to find where the issue is
~~- Using Linux container: we are able to be notified that the container should stop with the `AssemblyLoadContext.Default.Unloading` event, so we can plugin the Silo graceful shutdown in there. The issue is that `AppDomain.CurrentDomain.ProcessExit` is also triggered, and by default Orleans start a "FastKill" process. So we should expose a flag to disable this behavior.~~ fixed with #3796

**Comment by benjaminpetit** [comment]
Updating the issue section regarding the Linux case. Fix incoming!

**Comment by benjaminpetit** [comment]
Updating the issue regarding the Linux situation

**Comment by benjaminpetit** [comment]
The issue using Windows container is described here: https://github.com/dotnet/corefx/issues/26246

**Comment by stephenlautier** [comment]
Was the linux fixed or is it still an issue?

Currently, we are running .NET Core 2, using orleans `2.0.0-beta3` (latest) and we use docker (linux) as well as Dynamo Db (AWS) for membership, however when silo's are shutdown, they are always marked as active. Is this related?

**Comment by benjaminpetit** [comment]
Issue using Linux was fixed in the latest beta. Could you post your code where you handle the sigterm signal?

**Comment by stephenlautier** [comment]
@benjaminpetit basically our start/stop look something like this https://github.com/dotnet/orleans/blob/master/Samples/HelloWorld.NetCore/src/SiloHost/Program.cs (infect one in my team had contributed that)

Do we have to handle something special? Unfortunately, I'm not familiar with sigterm signal

**Comment by benjaminpetit** [comment]
As far as I know, in docker you should not rely on `Console.ReadLine` to detect that the silo should stop, but instead listen to `AssemblyLoadContext.Default.Unloading`.

There is a sample here: https://github.com/dotnet/orleans/blob/master/Samples/Docker-Simple/Silo/Program.cs

**Comment by stephenlautier** [comment]
@benjaminpetit ahh I wasn't aware of that, we can give it a shot thanks!

Actually ours wasn't exactly like the one I gave you, it was like the following:

```cs
public static int Main(string[] args)
{
	_log = Log.Logger;
	return RunMainAsync(args).Result;
}

private static async Task<int> RunMainAsync(string[] args)
{
	try
	{
		_hostingEnvironment = new HostingEnvironment();
		var builder = new ConfigurationBuilder()
			.SetBasePath(Directory.GetCurrentDirectory())
			.AddCommandLine(args)
			.AddJsonFile("appsettings.json")
			.AddJsonFile($"appsettings.{_hostingEnvironment.Environment}.json")
			.AddJsonFile("app-info.json")
			.AddEnvironmentVariables();

		if (_hostingEnvironment.IsDockerDev)
			builder.AddJsonFile("appsettings.dev-docker.json");

		var configuration = builder.Build();

		var appInfo = new AppInfo(configuration);
		Console.Title = $"Silo - {appInfo.Name}";

		var config = new Config(configuration, _hostingEnvironment, appInfo);

		var logger = new LoggerConfigurationBuilder()
			.CreateLogger(configuration, _hostingEnvironment.IsDev, appInfo);

		Log.Logger = logger;
		_log = logger.ForContext<Program>();

		_log.Information("Initializing Silo host {appName} ({version}) [{env}]...", appInfo.Name, appInfo.Version, _hostingEnvironment.Environment);
		var host = await StartSilo(config, configuration, logger);

		await host.Stopped;
		_log.Information("Stopping Silo host '{siloName}'...", appInfo.Name);

		await host.StopAsync();
		_log.Information("Silo '{siloName}' shutdown.", appInfo.Name);
		return 0;
	}
	catch (Exception ex)
	{
		_log.Error(ex, "An error has occurred while initializing or starting silo.");
		await Task.Delay(TimeSpan.FromSeconds(5)); // Make sure logs were written.
		return 1;
	}
}

private static async Task<ISiloHost> StartSilo(Config config, IConfiguration configuration, ILogger logger)
{
	var stopwatch = Stopwatch.StartNew();
	var builder = new SiloHostBuilder()
		.UseConfiguration(config.Get())
		.ConfigureLogging(logging => logging.AddSerilog(logger, true))
		...
		);

	var host = builder.Build();

	_log.Information("Silo initialized in {timeTaken:#.##}s. Starting...", stopwatch.Elapsed.TotalSeconds);
	await host.StartAsync();
	_log.Information("Successfully started Silo node in {timeTaken:#.##}s (total).", stopwatch.Elapsed.TotalSeconds);
	return host;
}
```

**Comment by andrew-laughlin** [comment]
@benjaminpetit we're currently running a single silo in Azure Container Instances, with plans to move to K8s. Below is the shutdown code we're using, which is intended to support graceful shutdown from both Windows and Docker. I haven't tested Windows containers yet. I am hoping to get feedback as to whether the code is correct.

The code seems to work, however there's at least one issue. When docker stop is executed, the AppDomain.CurrentDomain.ProcessExit event fires. The docs indicate only 2 seconds are allowed for the app to shutdown or SIGKILL is issued and the process is killed. This isn't enough time for Orleans to cleanup everything we've opened (e.g. event hub agents, database connections, table storage, etc). This is problematic and I'm not sure of the best solution. Thoughts?

see:
https://github.com/dotnet/coreclr/issues/2688#issuecomment-394843595
https://github.com/dotnet/coreclr/issues/8565
https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.processexit?view=netcore-2.1
 

    public class Program
     {
         private static int siloStopping = 0;

        public static int Main(string[] args)
        {
            var logger = ApplicationInsightsLoggerProvider.BuildLogger("Bootstrapper");
            logger.LogInformation("Starting SiloHost. Press Ctrl+C to terminate ...");

            try
            {
                // Configure silo services
                var siloHost = buildSilo();

                // Configure shutdown
                var resetEvent = new ManualResetEvent(false);
                ConfigureShutdown(logger, siloHost, resetEvent);

                // Start the silo
                siloHost.StartAsync().Wait();

                // Block main thread
                resetEvent.WaitOne();
            }
            catch (Exception ex)
            {
                logger.LogError("SiloHost encountered an error. Stopping. \n {0}", ex.StackTrace);
                logger.Flush();
                throw;
            }

            return 0;

			// this method has the call .Configure<ProcessExitHandlingOptions>(options => options.FastKillOnProcessExit = false)
            ISiloHost buildSilo() { ... }
        }

        private static void Shutdown(IFlushableLogger logger, ISiloHost siloHost, ManualResetEvent resetEvent)
        {
            if (Interlocked.Exchange(ref siloStopping, 1) == 0)
            {
                logger.LogInformation($"Shutting down silohost from thread ID:'{Thread.CurrentThread.ManagedThreadId}' name:'{Thread.CurrentThread.Name}'");

                try
                {
                    siloHost.StopAsync().Wait();
                }
                finally
                {
                    logger.LogInformation($"SiloHost stopped at {DateTime.UtcNow} UTC.");
                    logger.Flush();
                    resetEvent.Set();
                }
            }
            else
            {
                logger.LogInformation("Shutdown in progress. Ignoring shutdown request.");
                logger.Flush();
            }
        }

        /// <summary>
        /// Handle various shutdown events in an effort to shutdown gracefully.
        /// see:
        /// https://github.com/dotnet/coreclr/issues/2688
        /// https://github.com/dotnet/coreclr/issues/8565
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="siloHost"></param>
        /// <param name="resetEvent"></param>
        private static void ConfigureShutdown(IFlushableLogger logger, ISiloHost siloHost, ManualResetEvent resetEvent)
        {
            // ctrl+c (SIGINT) on Windows fires all events in order (i.e. CancelKeyPress, Unloading, ProcessExit)
            Console.CancelKeyPress += (sender, eventArgs) =>
            {
                logger.LogInformation($"Received shutdown via {nameof(Console.CancelKeyPress)}.");

                // Don't terminate the process immediately, wait for the main thread to exit gracefully.
                eventArgs.Cancel = true;
                Shutdown(logger, siloHost, resetEvent);
            };

            // Fired on SIGTERM from Linux. "docker stop <container id>" sends SIGTERM.
            // This runs on the GC thread and we only get 2 seconds to shutdown before being killed:
            // https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.processexit?view=netcore-2.1
            AppDomain.CurrentDomain.ProcessExit += (sender, eventArgs) =>
            {
                logger.LogInformation($"Received shutdown via {nameof(AppDomain.CurrentDomain.ProcessExit)}.");
                Shutdown(logger, siloHost, resetEvent);
            };
        }
    }

**Comment by benjaminpetit** [comment]
> The docs indicate only 2 seconds are allowed for the app to shutdown or SIGKILL is issued and the process is killed. This isn't enough time for Orleans to cleanup everything we've opened (e.g. event hub agents, database connections, table storage, etc). This is problematic and I'm not sure of the best solution. Thoughts?

Can you configure which signal is sent to shutdown the silo? I think SIGINT is handled by `Console.CancelKeyPress`, and if you cancel it the silo will not be killed.

If you cannot, you can try to call the silo stop method with a cancelled token, it will speed up the shutdown sequence a lot but... it will not be graceful (OnDeactivate will not be called on grain activations, some providers will not be shutdown gracefully, ect) but at least the silo will try to mark itself as `Dead` in the membership table.

Your code seems correct, but instead of having your own `ManualResetEvent`you should be able to await the `Stopped` task from `ISiloHost`

**Comment by benjaminpetit** [comment]
@claylaut sorry for the delayed response, I was out.

After a quick glance I don't see anything wrong with your code, my guess is that the silo doesn't have enough time to shut down? If you have the log it would be very helpful.

You can try to call `StopAsync` with a cancelled token, it will force a "fast" shutdown, it will be less clean but it will be faster.

**Comment by claylaut** [comment]
@benjaminpetit no worries, I refactored the silo to use c# 7 main async and I saw major improvements in shutdown. Still, I m not happy with this since I've noticed that we have certain silos that are using external message brokers that are consuming messages from external applications are still having problems to shutdown properly.

**Comment by sergeybykov** [comment]
@claylaut We made some improvements to the shutdown sequence in 2.2.3. Have you tried it?

**Comment by claylaut** [comment]
@sergeybykov I've just upgraded yesterday to .NET Core 2.2 and Orleans 2.2.3 :) I will let you know how it goes.

**Comment by claylaut** [comment]
@benjaminpetit @sergeybykov unfortunately, we're still noticing that shutdown is not working 100% correctly. Sometimes few silos remain with status 3 in the clustering table and if we're restarting the services for any reason it wont manage to start due they try to join the previous cluster. We have to clear the cluster table manually.

**Comment by benjaminpetit** [comment]
@claylaut do you have logs of the silo that appears to not shutdown properly?

**Comment by pinkfloydx33** [comment]
@sergeybykov

> We made some improvements to the shutdown sequence in 2.2.3. Have you tried it?

Is this documented anywhere, or is there a sample? The links to the samples above are outdated but I was able to find the latest ones for 2.3. However none of them seem to deal with the shutdown scenario like the older 2.0 example "docker-dotnet-core". Is this still the same suggested strategy, or has the fact that the examples changed to use `HostBuilder`+`RunConsoleAsync`/`RunAsync` somehow handle shutdown under the hood?

**Comment by sergeybykov** [comment]
>Is this documented anywhere, or is there a sample? 

Only in release notes at this point. But noting changed in the APIs or their usage except for additional config switches.

**Comment by KSemenenko** [comment]
I found this method ``` .UseConsoleLifetime() ```really useful

**Comment by ReubenBond** [comment]
Thanks, @KSemenenko.
Methods on host builder such as `IHostBuilder.UseConsoleLifetime()` and `IHostBuilder.RunConsoleAsync()` are a good choice.
Closing, since the above methods solve this issue.
