### ISSUE TITLE
Store providers

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/orleans#3626]
Hi,

I've experimented with store providers (2.0.0-preview4-20171025), and it works beautifully (I had to do some minor changes to the Json storage provider (sample code in the repository) to make it work).

Is there a store provider for PostgreSQL (ready to use)? How do I go about state [DB] sharding?

**Comment by sergeybykov** [comment]
SQL provider (that we are looking at renaming to AdoNet for 2.0 in #3544) supports PostgreSQL.

**Comment by jan-johansson-mr** [comment]
Thanks Sergey, I have a go with that, and try it out!
