### ISSUE TITLE
How does Docker swarm deploy Orleans 2.0?

### ISSUE THREAD

**Issue by beckjin** [dotnet/orleans#3630]
I think Docker swarm is a natural Orleans cluster, but I may be wrong . 

I now have 3 Docker swarm nodes. But I don't know how to modify the Address attribute of the configuration files. Here's my configuration:

```
<?xml version="1.0" encoding="utf-8" ?>
<OrleansConfiguration xmlns="urn:orleans">
    <Globals>
        <SystemStore SystemStoreType="SqlServer" DeploymentId="OrleansTest" DataConnectionString="Server=.;Database=OrleansStorage;User ID=sa;Password=123456;Pooling=true;Max Pool Size=32767;Min Pool Size=0;"/>
    </Globals>
    <Defaults>
        <Networking Address="xxxx" Port="22222" />
        <ProxyingGateway Address="xxxx" Port="40000" />
    </Defaults>
</OrleansConfiguration>
```

**Comment by benjaminpetit** [comment]
Not sure it is doable with XML file configuration, but if you use programmatic config you could do something like that:

```
config.Defaults.Port = 11111;
config.Defaults.ProxyGatewayEndpoint = new IPEndPoint(IPAddress.Any, 30000);
```

Then Orleans will take the first non-loopback IP address that it founds. Do you have one or do you have multiple network available in your containers?

**Comment by beckjin** [comment]
Thanks. I will try.

I have one network in my containers.

**Comment by egmkang** [comment]
`0.0.0.0`, does it work?

**Comment by beckjin** [comment]
I tried it. I didn't work it.

**Comment by sergeybykov** [comment]
@beckjin Is this still an issue for you or you already figured it out?

**Comment by RainingNight** [comment]
I'm use IPAddress.Any,  I didn't work it in Orleans 2.0!
