### ISSUE TITLE
Update Library and Service Sample 

### ISSUE THREAD

**Issue by xiazen** [dotnet/orleans#3632]
Sample [Interaction with Libraries and Services](http://dotnet.github.io/orleans/1.5/Tutorials/Interaction-with-Libraries-and-Services.html) is using an yahoo finance api  which is recently disabled by yahoo, as below is their comment on the reasoning: 

> It has come to our attention that this service is being used in violation of the Yahoo Terms of Service. As such, the service is being discontinued. For all future markets and equities data research, please refer to finance.yahoo.com.

Need to update the sample to use the new api.

**Comment by kutensky** [comment]
Looks like it's outdated link. Here is the right one [Interaction with Libraries and Services](http://dotnet.github.io/orleans/1.5/Tutorials/Interaction-with-Libraries-and-Services.html)

**Comment by aprooks** [comment]
@sergeybykov 	looks like this sample is no more, and this task can be closed

**Comment by sergeybykov** [comment]
@aprooks It's not a formal sample, just some sample code as part of the tutorial. I fixed the link to the page - http://dotnet.github.io/orleans/1.5/Tutorials/Interaction-with-Libraries-and-Services.html.

**Comment by aprooks** [comment]
I have checked, and Yahoo API is now available via some hacks. This seems to be the easiest provider with automatic api key generation on request. https://www.alphavantage.co/support/#api-key

I will migrate example for this one

**Comment by xiazen** [comment]
Thank you !

**Comment by aprooks** [comment]
see #5108 

I have a runnable sample, but not sure if it's worth uploading it. Let me know if adjusting docs was enough
