### ISSUE TITLE
Build time codegen fails on beta1 (netcore 2)

### ISSUE THREAD

**Issue by tinpl** [dotnet/orleans#3636]
Hello guys. 
my GrainInterfaces/Grains projects reference some project which require PInvoke. When I build (say GrainInterfaces project) without referencing "System.Runtime.InteropServices.PInvoke" I have this build log: https://pastebin.com/A5TYCLdh
args: https://pastebin.com/HsyzS8q7
It requires for PInvoke to be references, so I have added ref from myget source:
<PackageReference Include="System.Runtime.InteropServices.PInvoke" Version="4.0.0-rc2-24027" />
After that build log changed to: https://pastebin.com/4sypRYB6
args are similar to this: https://pastebin.com/YXYvJkh4
seems important line is:
/r: C:\Users\Tinpl\.nuget\packages\system.runtime.interopservices.pinvoke\4.0.0-rc2-24027\ref\netstandard1.3\System.Runtime.InteropServices.PInvoke.dll

Seems it can't load assembly from ref folder.
However, if I 
1) Manually edit args file to get lib from /lib/ instead of /ref/ folder
2) build orleans master and manually run the orleans codegen build on this file, seems it is capable to produce g.cs file, not sure if it will be working assembly, however on previous steps .g.cs was absent
buildlog: https://pastebin.com/HxizBLhc

I'm not quite sure if I'm doing all this correctly. Is it expected behavior that args file generated references the pinvoke assembly from ref folder, and after that fails to build?

**Comment by attilah** [comment]
@tinpl could you please confirm that is it still failing with the latest code in master? Since we've some assembly loading fixes since beta1.

**Comment by tinpl** [comment]
I will try to add build time codegen back in the following week, we already have something working using runtime codegen for now

**Comment by tinpl** [comment]
With new master had the same exception, however, was capable to see under debug that S.R.IS.Pinvoke was referenced by part = some library from nuget package (Triangle/0.0.6-Beta3). After I cloned its sources locally and referenced it from the inside of a solution, exception gone away. I rechecked new solution build on beta1, and it works also.  Seems that it was caused by some runtime platform dependencies of the nupkg.
btw. Is Buildtime codegen fully supported on linux machines now?

**Comment by sergeybykov** [comment]
>Is Buildtime codegen fully supported on linux machines now?

Should be fully supported. Although we have very limited testing on Linux at the moment.

**Comment by ReubenBond** [comment]
Apologies for the delay, @tinpl. I'm trying to repro now

**Comment by ReubenBond** [comment]
I'm unable to repro so far using latest master. Could you please try again against beta2 or the latest nightly? If it doesn't work, please attach a repro sln or repro steps.
