### ISSUE TITLE
[Question] Returning Tasks instead await

### ISSUE THREAD

**Issue by Xanatus** [dotnet/orleans#3648]
I was wondering how returned Tasks in orleans grains behalf.
Are they beeing awaited by orleans internaly before unlocking the grain for other requests? Would it break the single threaded gaurantee? Would task operations become interleaved?

Eg.:

```
class MyGrain : Grain, IMyGrain
{
    public Task Foo() {
        return Bar(); 
    }
    public async Task Bar() {
        await x(); 
        await y();
    }
}
```

If another Grain or Client would call `await GetGrain<IMyGrain>(id).Foo()` would execution inside MyGrain be the same as if Foo() would have been async and Bar() awaited?

**Comment by sergeybykov** [comment]
Execution will be the same in both cases.

**Comment by jdom** [comment]
the `async` keyword is syntactic sugar, but the end result is that both grain methods return a `Task` that completes when the `Bar` task completes in the first example or when the `y` task completes in the second.
