### ISSUE TITLE
[ Orleans 2.0 ] Deserialization and deep copy fail for F# types

### ISSUE THREAD

**Issue by cata** [dotnet/orleans#3650]
There are a number of circumstances in which serialization and deep copy fail for F# types:

- [ ] F# discriminated union when the union case has an F# list, F# set, or F# map field
  * Results in a `System.Security.VerificationException : Operation could destabilize the runtime.` exception
   * Note that stand-alone F# list deep-copy works as expected
- [ ] Non-empty F# set
  * The deep copy result is an empty set
- [ ] Non-empty F# map
   * The deep copy result is an empty ~set~ map

Repro PR coming in a few minutes.

**Comment by cata** [comment]
Repro tests in #3651

**Comment by ReubenBond** [comment]
Thank you for reporting and providing a repro, @cata! I'll try to fix this asap

**Comment by cata** [comment]
Thanks - greatly appreciated!
Note that the PR will fail the BVT checks - I did not skip the failing tests (let me know if you want me to do so and I'll re-submit)
