### ISSUE TITLE
Orleans cluster hosted on service fabric fails to activate grains

### ISSUE THREAD

**Issue by cata** [dotnet/orleans#3654]
We are currently using Service Fabric for maintaining Orleans membership.

The cluster has unexpectedly become unable to activate grains, while still being accessible to clients.

We are considering moving the cluster membership back to Azure tables (see also #3607), at least temporarily, to verify that Service Fabric membership is indeed the culprit.

Please see [the log](https://github.com/dotnet/orleans/files/1455845/cluster.zip) for details - note that the log is for a 5 nodes cluster.

Orleans version: 1.5.2
Service Fabric version: 6.0.219.9494

**Comment by ReubenBond** [comment]
@cata
> We are considering moving the cluster membership back to Azure tables (see also #3607), at least temporarily, to verify that Service Fabric membership is indeed the culprit

I recommend taking that route. There are fixes which remediate what you're experiencing in `master`, but they're not backported to 1.5.x. I'm investigating a more substantial overhaul of how Service Fabric membership is implemented.

**Comment by cata** [comment]
@ReubenBond - thank you for the advice, will do so.

**Comment by cata** [comment]
Done - works like a charm, with Orleans still hosted in SF.
Also, #3638  looks good 👍 - it will make it clear that one can use SF without necessarily having to use SF membership.
