### ISSUE TITLE
Prevent deactive on activation garbage collection

### ISSUE THREAD

**Issue by bluexo** [dotnet/orleans#3655]
I have a problem about grain deactive 
example:
```
public class RoomGrain : Grain, IRoomGrain
    {
        private List<Player> players = new List<Player>();
        // ...
        public Task OnDeactivateAsync()
        {
            if (players.Count > 0) {

                /// How to prevent deactive  ???  DelayDeactivation(TimeSpan) cannot  ;

                return Task.CompletedTask;
            } else
                return base.OnDeactivateAsync();
        }
    }
```
Has some approach prevent grain deactive on activation garbage collection ,  except  configure grain agelimit ?

My current solutions is that use a grain Timer to manage the delay deactivation logic , but it's cause more and more grain Timer.

I suggest using blow code in abstract grain class : 
```
 public abstract class Grain : IAddressable, ILifecycleParticipant<IGrainLifecycle>
        {
            /// if return false prevent deactive
            public virtual async Task<bool> OnDeactiveAsync()
            {

            }
        }
```
or using a ManualAGCAttribute class to skip activation garbage collection 
```
[ManualAGC]
public class RoomGrain : Grain , IRoomGrain
{
     private List<Player> players = new List<Player>();

     public Task RemovePlayer(Player player)
     {
          players.Remove(player);
          if(players.Count <=0)  this.DeactivateOnIdle();
          return Task.CompletedTask;
     }
}
```

**Comment by AwsomeCode** [comment]
Basically you don't have to keep the grain active if its ideal. I recommend you to change your logic.

**Comment by jokin** [comment]
You can use DelayDeactivation, just not in the OnDeactivateAsync method. You should call whenever your grain starts, and it should work just like your "ManualAGC" attribute.

**Comment by sergeybykov** [comment]
@bluexo I believe the existing mechanisms mentioned above provide enough options for delaying deactivation when desired. `OnDeactivateAsync` shouldn't be used for trying to manage activation lifecycle or for any significant logic.

**Comment by bluexo** [comment]
@sergeybykov  I have a lot of grains need delay dactiveation and I have to implements the delaying logic everyone , why not add a mechanism like "ManaulAGCAttribute" to skip activation garbage collection without config Agelimit ? `<addr>`

**Comment by sergeybykov** [comment]
>why not add a mechanism like "ManaulAGCAttribute" to skip activation garbage collection without config Agelimit ?

`ManaulAGCAttribute` would be equivalent to setting age limit to infinity (or a very long time), right? If so, then these two approaches are functionally identical. My preference to sticking with the age limit mechanism has the following reasons:

1) Age limits are set at configuration time, and hence can be changed without recompiling grain code.
2) Grains are virtual actors, and having them activated forever (as opposed to having a long age limit) goes ideologically against the virtual nature of them.
3) Providing two mechanisms to achieve the same goal always adds some degree of confusion.
