### ISSUE TITLE
NullReferenceException on State in Chirper Sample

### ISSUE THREAD

**Issue by javier-alvarez** [dotnet/orleans#366]
I am trying to change your Chirper sample to use nuget packages.

I have the silo running and when I execute the loader I get a NullReferenceException because State is null in ChirperAccount.

This is the change: https://github.com/javier-alvarez/orleans/commit/ff77e4b500fffe16fcd9318fbaea1a604fe5afb5

Any ideas why?

Thanks

**Comment by sergeybykov** [comment]
I think @jthelin ran into something like that but I don't remember the details.

**Comment by gabikliot** [comment]
@javier-alvarez , this happens if the project uses the wrong code gened file (ChirperGrains\Propertiesorleans.codegen.cs in the Grains project). Make sure it is generated and updated when you rebuild the project. If not, you probably did not add it correctly.

**Comment by jthelin** [comment]
@javier-alvarez - I went through your change set, and the main issues seems to be that the Grains project should also include package ```Microsoft.Orleans.Templates.Grains``` otherwise the server-side code-gen won't get triggered.

``` xml
  <package id="Microsoft.Orleans.Templates.Grains" version="1.0.5" targetFramework="net45" />
```

**Comment by javier-alvarez** [comment]
Thanks for your help! It works now!

**Comment by gabikliot** [comment]
Great! Would you be willing to submit a PR with porting Chirper to use Nugets? That would be great. Eventually we want to port all samples to use Nugets.
