### ISSUE TITLE
Orleans Icon for contrib projects

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#3660]
Quick question: Are you fine when we use Orleans Icon for contrib projects, e.g.: https://github.com/OrleansContrib/Orleans.Providers.MongoDB

Or can you provide another icon?

**Comment by SebastianStehle** [comment]
Hi, have you made a decision?

**Comment by ReubenBond** [comment]
I say use it and  if there's an issue then we can make a variant with a different color

**Comment by ReubenBond** [comment]
I hear a lot of good things about Goldfish Orange

**Comment by SebastianStehle** [comment]
lol, thanks.
