### ISSUE TITLE
Support gzipping blob content in azure blob storage provider

### ISSUE THREAD

**Issue by talarari** [dotnet/orleans#3661]
we're seeing some performance issues with saving large blobs (500kb takes around 1 second).
would be great if it was possible to have the storage provider gzip the blob content, since its json it compresses pretty well.

i downloaded one of our blobs (around 500kb) and it gzipped to 1/10 of the size (50 kb).

**Comment by sergeybykov** [comment]
This can be done by extending the existing provider or by creating a new one. If you'd like to add the option to any of the existing storage providers, we'd welcome your contribution.
