### ISSUE TITLE
Grain life-management - issue with continuously consuming event/message bus

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/orleans#3667]
Hi,

I want to wire up grains to read from message/event bus (or stream), and I'm concerned with run-time life-management of grains, since I want a grain consuming events/messages to stay up "forever" to listen to the bus.

I was reading about streaming (a very powerful concept), and how a grain can be implicitly wired up by the run-time when a message target a [stream] namespace correlating to the same namespace. But only one such instance will be fired up auto-magically.

The other way to go about it is to send a message to a grain, and have the run-time activate the grain, and in that activation to let the grain subscribe to the stream (or bus). But now the grain can be deactivated by the run-time at any time (thus the read-out from the stream/bus will stop).

How can I detect when the run-time (Silo) deactivates a grain, and activate it again? Or maybe if there is an option to let the grain stay in memory (as in this case consumers of events/messages), by telling the run-time that this particular grain should not be deactivated?

**Comment by jokin** [comment]
you can call DelayDeactivation(TimeSpan timeSpan) and the grain will not timeout. but I would use a reminder anyway to periodically call the grain and check the bus connection status in case another failure happened.

**Comment by jan-johansson-mr** [comment]
Thanks Jokin,

I've just completed a "study" of streams, implicit, explicit, with all kind of configuration, and learned a lot. Now I know even more :-)
