### ISSUE TITLE
Consecutive transactions on grains can cause rollbacks

### ISSUE THREAD

**Issue by jsteinich** [dotnet/orleans#3681]
Setup:

1. Start with the Account Transfer sample
2. Put the atm transfer (optionally the balance retrieval as well) inside a small for loop
3. Run

Observations:

- The ending balances don't always match what they should be.
- This is more apparent if adding `await Task.Delay(100)` at the end of the for loop
- [exampleOutput.txt](https://github.com/dotnet/orleans/files/1483434/exampleOutput.txt)

Theories:

It appears as though the `TransactionAgent`'s aborted transaction checks are too aggressive. When `TransactionalState` goes to get or save the current state, it goes through `Restore()` which ends up rolling back transactions that are still in the log but older than the abort threshold that `TransactionAgent` is using. Adding a delay that is longer than `TransactionAgent`'s processing interval causing more issues seems to back up the aggressive aborting since it ensures that the abort threshold is updated between transactions.

**Comment by jason-bragg** [comment]
@jsteinich, can you provide your DoClientWork logic?
I have:

        private static async Task DoClientWork(IClusterClient client)
        {
            IATMGrain atm = client.GetGrain<IATMGrain>(0);
            Guid from = Guid.NewGuid();
            Guid to = Guid.NewGuid();
            for(int i=0; i<5; i++)
            {
                await atm.Transfer(from, to, 100);
                uint fromBalance = await client.GetGrain<IAccountGrain>(from).GetBalance();
                uint toBalance = await client.GetGrain<IAccountGrain>(to).GetBalance();
                Console.WriteLine($"\n\nWe transfered 100 credits from {from} to {to}.\n{from} balance: {fromBalance}\n{to} balance: {toBalance}\n\n");
            }
        }

and am not seeing what you are..?
Tnx

**Comment by jason-bragg** [comment]
NM, I upped it to 10 loops and was able to repro.
Looking into it.
Thanks!

**Comment by jason-bragg** [comment]
@jsteinich,
Plz see fix "Fixed intermittent transaction test failures. #3725"

Transactions is still in alpha, so if you want to pay with the latest, I suggest using the transaction benchmarks in Orleans/tests/Benchmarks.  

Thanks for helping us find this.

**Comment by jsteinich** [comment]
Thanks for the fix.

I'm planning to use transactions quite a bit, so I'll probably look into running from master to continue testing.

**Comment by jason-bragg** [comment]
@jsteinich, Great!  Please let us know if you see anything else unexpected.

As Orleans is open source, adding tests to our Transaction test harnesses (as seen in #3725), which cover your usage scenarios, would be welcomed.

**Comment by jason-bragg** [comment]
Addressed in "Fixed intermittent transaction test failures. #3725"
