### ISSUE TITLE
Service Fabric - PartitionResolutionChangeHandler logging problem

### ISSUE THREAD

**Issue by pintmil** [dotnet/orleans#3691]
We have an Application based on Orleans Framework 1.5.1.0, it is deployed on an Azure Service Fabric Cluster with 3 nodes. 
Without using the application, so it is just deployed and just Orleans run on it without userspace grain activations, the Service Fabric generates tonnes of log files (around 500Mb/min at now). It has an increasing tendency, few days ago it was "just" 200Mb/min.
After some investigation with help of the Azure support team, it turned out that **RegisterServicePartitionResolutionChangeHandler** function is called very often, and the registred handlers won't be unregistred, Service Fabric log out every registred handler ID every time if a new is registred. So in the logs is every time more and more from that rows. 
We don't use this function in our code, but orleans maybe use it in orleans/src/Orleans.Membership.ServiceFabric/FabricServiceSiloResolver.cs.
Can somebody confirm that, it is an Orleans bug?

**Comment by ReubenBond** [comment]
This was fixed in [1.5.2](https://github.com/dotnet/orleans/releases/tag/v1.5.2) via #3411

**Comment by pintmil** [comment]
Thank you!
