### ISSUE TITLE
Documentation on client configuration does not explain what 'target deployment ID' is

### ISSUE THREAD

**Issue by urig** [dotnet/orleans#3694]
The [documentation page](https://github.com/dotnet/orleans/blob/gh-pages/src/Documentation/Deployment-and-Operations/Configuration-Guide/Client-Configuration.md/#L1) for Client Configuration makes references to the term 'target deployment ID'. However, the page does not explain what this term means or how to obtain the value for it. It might be a good idea to add an explanation of the term and instructions on how a user can find out the value to put in their client configuration.

**Comment by Kimserey** [comment]
From what I understand the deployment ID on the client configuration targets the deployment ID of a cluster set in the `server configuration` in `GlobalConfiguration`.

There is slightly more explanation on the `server configuration` section of the doc with the following:
> DeploymentId is a unique string that defines a particular deployment. When deploying an Orleans based service to Azure it makes most sense to use the Azure deployment ID of the worker role.

I am quite confuse with the purpose of it.  

**When is it necessary to set a deployment ID?**

For example, when using a localhost primary silo configuration, the deployment ID is not set.

**Comment by sergeybykov** [comment]
In the hindsight, `DeploymentId` should have been called `ClusterId` because it identifies the cluster that a set of silos belong to. That's how silos find each other to form a cluster. It is also used by clients to connect to a cluster.

@jdom is working on a PR that should improve the API for 2.0.0. We'll need to update the docs when 2.0.0 is out.

**Comment by sergeybykov** [comment]
@urig We generally moved away from DeploymentId in 2.0 and settled on ClusterId instead. Do you agree that this is resolved now?

**Comment by urig** [comment]
Yes. Thank you @sergeybykov and team.
