### ISSUE TITLE
Contribution idea: Add support for Bond/Avro/other serialization

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#37]
One way to support Bond is to allow to use it optionally in addition to the built-in Orleans-generated serializers, similar to custom serializers. That way code that already uses Bond could work with Orleans.
The solution will probably need to add a message header to indicate serializer used
Will be less automatic than the built-in option but compatible with non-.NET clients
Explore other ways to use Bond.

**Comment by robrodi** [comment]
That sounds lovely.

**Comment by veikkoeeva** [comment]
I'll add [Simple Binary Encoding](http://mechanical-sympathy.blogspot.fi/2014/05/simple-binary-encoding.html) here too as it's used in low-latency financial Trading and may prove to be useful. This is like a continuation to the [Codeplex thread](https://orleans.codeplex.com/discussions/577637v) where I ditched some haphazard ideas (I blame myself for not being able to engage in more thoroughly currently, but maybe sharing these is of use top). This touches upon #38 as in Codeplex there's a link to [MBrace and code serialization](https://eiriktsarpalis.wordpress.com/2014/12/29/deploying-net-code-instantly-using-vagrant/) which may be a useful idea.

**Comment by MovGP0** [comment]
missing links: 

* [Microsoft Bond](https://github.com/Microsoft/bond) 
* [Apache Avro](http://avro.apache.org/) 
* [Google Protocol Buffers](https://code.google.com/p/protobuf-net/) .

**Comment by gabikliot** [comment]
Looks like that was implemented via #953?

**Comment by veikkoeeva** [comment]
@gabikliot As far as I see, that is the case.

**Comment by sergeybykov** [comment]
Yes, the generic solution that @Carlm-MS put together also covers non-Bond cases.
