### ISSUE TITLE
[Question] Using Orleans 2.0 in legacy .NET 4.7.1 applications

### ISSUE THREAD

**Issue by ifle** [dotnet/orleans#3705]
Please can you clarify again about using of Orleans 2.0 in legacy applications?
Are there any limitations of using Orleans 2.0 in legacy applications?
We have asp.net mvc 4 applications that run on 4.7.1
Is Orleans 2.0 will support not .core projects?

**Comment by Liversage** [comment]
Orleans 2.0 targets .NET Standard 2.0. The platform .NET 4.7.1 is hardly legacy and fully supports .NET Standard 2.0.

[.NET Framework 4.7.1 provides built-in support for .NET Standard 2.0](https://github.com/dotnet/standard/issues/514)

.NET Standard defines a specific set of API's. .NET Core as well as .NET 4.7.1 are platforms that may or may not support as specific version of .NET Standard. In this case Orleans 2.0 targets .NET Standard 2.0 that is supported on both .NET Core 2.0 and .NET 4.7.1.

**Comment by sergeybykov** [comment]
Yes, Orleans 2.0 should run equally well on .NET Core 2.0+ and .NET Framework 4.6.1+.

**Comment by ifle** [comment]
Thanks

**Comment by RockNHawk** [comment]
I have create two Unit Test Project, one is .NET Core another is .NET Framework, the setup code is all the same, the .NET Core UnitTest works well, but .NET Framework fails .
https://github.com/dotnet/orleans/issues/6314
