### ISSUE TITLE
How to write a circuit breaker in orleans

### ISSUE THREAD

**Issue by sundong1982** [dotnet/orleans#3712]
Is there a demo?

**Comment by jdom** [comment]
You mean against external services? It should be no different than from non-Orleans code. You can use Polly or some other library normally. Just be conscious of the total time it can take for the call to complete, as by default the grain call will time-out after 30 seconds. Total time starts ticking from the client perspective the moment it sent the request, so on a hot grain it means that even if total cut-off time for the retries and circuit breaker has calls taking 10 seconds in normal conditions, but you have more than 3 calls enqueued for that grain, then some calls might start timing out, even if they didn't start executing on the grain.

**Comment by sundong1982** [comment]
@jdom thx:)

**Comment by ccerrato147** [comment]
> You mean against external services? It should be no different than from non-Orleans code. You can use Polly or some other library normally. Just be conscious of the total time it can take for the call to complete, as by default the grain call will time-out after 30 seconds. Total time starts ticking from the client perspective the moment it sent the request, so on a hot grain it means that even if total cut-off time for the retries and circuit breaker has calls taking 10 seconds in normal conditions, but you have more than 3 calls enqueued for that grain, then some calls might start timing out, even if they didn't start executing on the grain.

For calls between grains is the a circuit breaker not needed or implemented already inside Orleans?

**Comment by jdom** [comment]
Retries is built-in. Circuit breaker isn't needed since the cluster will self-heal and reactivate a grain in another silo if the original activation is unreachable due to a dead silo.

**Comment by ccerrato147** [comment]
> Retries is built-in. Circuit breaker isn't needed since the cluster will self-heal and reactivate a grain in another silo if the original activation is unreachable due to a dead silo.

Thanks!
