### ISSUE TITLE
OrleansCodeGenerator.Build  does not implement interface member  on same class name

### ISSUE THREAD

**Issue by hanxinimm** [dotnet/orleans#3713]
![image](https://user-images.githubusercontent.com/13499426/33259593-4db738ae-d398-11e7-9da7-53cf4e8bb720.png)

**Comment by ReubenBond** [comment]
Hi @hanxinimm, I don't understand the issue. I think what you're asking is some like "why doesn't Manager have a serializer generated for it".

Could you check that `Manager` is marked as `[Serializable]` and is `public`?

**Comment by hanxinimm** [comment]
yes, error:
OrleansCodeGenAccountCommandHandlerReference' does not implement interface member 'IAccountCommandHandler.ExecuteAsync(UnFollowCommand)

![image](https://user-images.githubusercontent.com/13499426/33260049-b49df93a-d399-11e7-8453-10116cb23010.png)
![image](https://user-images.githubusercontent.com/13499426/33260064-bddec79a-d399-11e7-9219-c9572e5e8ed2.png)

same interface name ,when i use partial interface

**Comment by ReubenBond** [comment]
Could you check that `Manager` is marked as `[Serializable]` and is `public`?

**Comment by hanxinimm** [comment]
yes , i sure it
my code like this

![image](https://user-images.githubusercontent.com/13499426/33261871-45ddfa94-d39f-11e7-817c-ee8f492d36a6.png)
![image](https://user-images.githubusercontent.com/13499426/33261874-49d6da9e-d39f-11e7-95fb-16dbd24f087f.png)
![image](https://user-images.githubusercontent.com/13499426/33261886-57470514-d39f-11e7-9aa7-62b962ba0a93.png)
![image](https://user-images.githubusercontent.com/13499426/33261892-5e6c171c-d39f-11e7-997f-a5d3ab43fe65.png)

**Comment by ReubenBond** [comment]
Can you see what the generated `GrainReference` for `IAccountCommandHandler` looks like? I believe you may need to add `[MethodId(some random int)]` attributes to the different `ExecuteAsync` methods.

**Comment by hanxinimm** [comment]
The problem is still

![image](https://user-images.githubusercontent.com/13499426/33262724-4905bd30-d3a2-11e7-88e7-1bec9e56a3c3.png)
![image](https://user-images.githubusercontent.com/13499426/33262736-545fe796-d3a2-11e7-95da-b5d512a3f96b.png)

![image](https://user-images.githubusercontent.com/13499426/33262776-6e87f42e-d3a2-11e7-8885-10472b27e760.png)

**Comment by ReubenBond** [comment]
Seems that this is a bug on [this line](https://github.com/dotnet/orleans/blob/ddfe036d2a584bb9f7bb87a96718e2bf55fb41fb/src/Orleans.Core/CodeGeneration/GrainInterfaceUtils.cs#L375).

You could work around this issue by changing the name of one of the types. Hopefully we can fix it soon.

**Comment by hanxinimm** [comment]
@ReubenBond 
Whether to support the grain group?
i have more CommandHandler like this 
![image](https://user-images.githubusercontent.com/13499426/33266057-fcd9a8ec-d3ae-11e7-8d82-014203be4481.png)
They are different categories of operation module in the same domain,they operate with an aggregate root.
So I want to control their concurrency,now i must be use partial interface. what's the better way?
![image](https://user-images.githubusercontent.com/13499426/33266511-eac7e7f2-d3b0-11e7-8083-6484d11398c5.png)
![image](https://user-images.githubusercontent.com/13499426/33266523-f6e8c6dc-d3b0-11e7-9a24-6a83f541bc6b.png)

**Comment by ReubenBond** [comment]
You could use separate interfaces. Grains can implement multiple interfaces and you can decide which interface to call using the .Cast<TInterface>() method. Does that work for you? As long as multiple grains don't implement the same interface then there is no ambiguity. If multiple grains do implement the same interface, it's still not ambiguous as long as you use GetGrain to get the grain using its main interface and then use Cast to cast it.

**Comment by hanxinimm** [comment]
that is a good way,
but i think do it like this is more better.

`
[GrainGroup("AccountDomain")] //use GrainGroup Attribute
    public partial class AccountCommandHandler : Grain
    {

    }

    [GrainGroup("AccountDomain")] //int or string or GUID
    public partial class EmployerCommandHandler : Grain
    {

    }
`

Or 

`
  public class AccountDomainGrainGroup : GrainGroup
    {

    }

    public partial class AccountCommandHandler : AccountDomainGrainGroup
    {

    }

    public partial class EmployerCommandHandler : AccountDomainGrainGroup
    {

    }`

**Comment by SebastianStehle** [comment]
I would just make a generic interface: 

    interface ICommandHandler<TCommand>
    {
        Task Execute(TCommand command);
    }

This works well and you can rearrange the handlers, when they become too big.

**Comment by hanxinimm** [comment]
@SebastianStehle  The function interface will become too fragmented, i use it like this:
handle event
![image](https://user-images.githubusercontent.com/13499426/33358817-ef8ee3b6-d505-11e7-8cc5-03fdfff36f21.png)

base class

![image](https://user-images.githubusercontent.com/13499426/33358918-7f6d24d4-d506-11e7-97f9-5f07eb768149.png)
