### ISSUE TITLE
Muliti-cluster high availability

### ISSUE THREAD

**Issue by talarari** [dotnet/orleans#3714]
We want to set up another cluster for high availability, We thought about using the multi cluster support for that.

Lets say i have two clusters joined in a multi cluster, lets say one is in east-us and the other is in west-us.
By default grain activation will be placed randomly in both clusters right? 
So if i'm directing all traffic to east us, and a grain in east-us is activated and publishes a message in a stream, Grains will be activated in west-us to handle that message too right?

Is there a way to tell Orleans to prefer staying in one cluster ?

That way we can enjoy good latency in the usual case, and when the main cluster is down for what ever reason, it will start using the secondary cluster.

Is this something that is supported? How is high availability usually achieved? 

Thanks!

**Comment by sebastianburckhardt** [comment]
If you are using the  `[GlobalSingleInstance]` attribute on the grain class, its instances are activated in the cluster where it is *first accessed*. 

So, if you are accessing all grains in east-us in the normal case, no grains are activated in west-us.

**Comment by talarari** [comment]
Great, and that is true for streams as well as grain calls?

**Comment by sebastianburckhardt** [comment]
Yes, I believe so, though I haven't worked with streams much myself, so maybe someone else can confirm.

From what I understand, a stream activates a grain only if that grain has an implicit subscription. I am assuming that this activation proceeds via the normal grain activation procedure which uses the GlobalSingleInstance protocol.

**Comment by sergeybykov** [comment]
>From what I understand, a stream activates a grain only if that grain has an implicit subscription.

Implicit or explicit. Conceptually, stream events are handled just like other calls to grains.

However, one needs to be more careful with streams and multi-clusters. For example, it would be rather confusing if more than one cluster were to pull events from the same set of queues and sending duplicates of every event, most of them going across the inter-cluster links. But if only one cluster pulls events, then availability will suffer if that cluster goes down. There's currently no support for inter-cluster coordination/balancing of stream pulling agents.
