### ISSUE TITLE
Transferring grains without persistence on silo shutdown

### ISSUE THREAD

**Issue by sudsy** [dotnet/orleans#3726]
We are currently running a small Orleans cluster without using persistence.

I am trying to understand how I can handle a shutdown of a silo in the most graceful way possible. This is part of our planning for in place upgrades of our silo cluster while retaining grain state.

What I would like to do is handle the shutdown of certain grain types by creating a new instance of the grain on another silo and transferring the state of that grain to the other silo.

Is there any way I could achieve this in Orleans without using persistence?

**Comment by sergeybykov** [comment]
This kind of functionality isn't directly supported today. There's always a way to build an elaborate overlay infrastructure to track and control location of all grains, to keep there state in some kind of grain-based "virtual storage" on other silos, etc. But I wouldn't recommend starting down that path. It's too much of error prone work to mimic persistence.

I have a more general question - when running the app without persistence, how do you handle a node failure?

**Comment by sudsy** [comment]
At the moment, state is lost when there is a node failure.

It's not a big problem for our current use case because the period where
individual clients rely on the state is generally very short.

The new use case involves retaining the state for a user until the grain
activations are collected. Really we are planning to use it to maintain the
state of their session and allowing them to elect to persist specific
grains if they want to.

We have some customers who require us not to store their data to disk to
comply with security requirements.

It may be that we just enable persistence for everyone but these customers.
Ideally though, the persistant data would expire over time unless the user
had elected to persist that grain.

I am looking at using aws s3 and expiration policies.
