### ISSUE TITLE
Differences between AddApplicationPart and AddApplicationPartsFromReferences in builders Orleans v2.0.0-beta1

### ISSUE THREAD

**Issue by Kimserey** [dotnet/orleans#3740]
In Orleans v2.0.0-beta1, I am confused by the two extensions found In the `ISiloHostBuilder` extension and `IClientBuilder` extension:
- `AddApplicationPart` 
- `AddApplicationPartsFromReferences` 

Both take an assembly as input but in the samples only `AddApplicationPartsFromReferences` is used.

__What are the differences between both of the functions and which should be used in which circumstances?__

**Comment by jdom** [comment]
Hi @Kimserey:
- `AddApplicationPart` will just add the passed in assembly as an application part (and discover grains and serializers only in that one). 
- `AddApplicationPartsFromReferences` will add the passed in assembly, as well as the (deep) references of that assembly. This one is probably the one you want to use, as the scanning is very fast regardless. It's just checking for an assembly level attribute in each assembly, and if it doesn't contain anything Orleans related, it will just skip it.

The first one is just the basic logic, but you'll very likely use the second one, and only in very particular unit testing scenarios or something where you want to have very strict control of what you load, you might want to do something different (unlikely, but possible).
