### ISSUE TITLE
Minimal Project: Could not load file or assembly 'System.Security.Cryptography.Algorithms

### ISSUE THREAD

**Issue by dandago** [dotnet/orleans#3741]
I just created a project using the Dev/Test Host template. Out of the box, it builds and runs fine.

If I just add this interface...

    public interface IPersonGrain : IGrainWithStringKey
    {
        Task DoNothingAsync();
    }

...and this grain...

    public class PersonGrain : IPersonGrain
    {
        public Task DoNothingAsync()
        {
            return Task.CompletedTask;
        }
    }

...not even calling them on the client side, the application explodes at the client construction and complains about a missing assembly.

![image](https://user-images.githubusercontent.com/13241564/33551626-e02951b2-d8e9-11e7-9fb4-df6babd6df00.png)

Surely I shouldn't be getting this with such a minimal Orleans setup?

I created the project just now, so it should be the latest Orleans out there (1.5 I guess).

**Comment by sergeybykov** [comment]
I checked, and it runs fine for me. I just need to add `Grain` as the base class for `PersonGrain`:

`public class PersonGrain : Grain, IPersonGrain`

**Comment by dandago** [comment]
Right, I may have missed that. But do you get the same error if you leave it out?

**Comment by sergeybykov** [comment]
Then I get a different one:
>Cannot find an implementation class for grain interface: GrainInterfaces1.IPersonGrain

That helped me find the missing base class in your code.

**Comment by dandago** [comment]
That's weird. Well, it's no use if you can't reproduce the problem. Just close this, and I'll reopen if there are any updates.

**Comment by dandago** [comment]
My project was targeting .NET Framework 4.6.1. I managed to fix the problem by upgrading to .NET Framework 4.6.2 and reinstalling packages.

Still no clue what was the cause though.
