### ISSUE TITLE
Service Fabric: wrong TaskScheduler in Notify-call using observers cross-silo

### ISSUE THREAD

**Issue by martinothamar** [dotnet/orleans#3744]
Hi!

We have 2 different silo's who needs to communicate. We use ObserverSubscriptionManager. Subscribing to the grain in the other silo works fine, and when notifying back the request reaches the silo and the grain that is subscribed. The issue: `TaskScheduler.Current == TaskScheduler.Default`, so when I try to call another grain from the method which is notified I get this:

`Trying to send a message Request S127.0.0.1:33003:250097472-> #84:  on a silo not from within grain and not from within system target (RuntimeContext is not set to SchedulingContext) RuntimeContext.Current=null TaskScheduler.Current=System.Threading.Tasks.ThreadPoolTaskScheduler`.

I have a colleague who uses the same pattern but isn't using Service Fabric who doesn't have this issue, therefore wondering if it is a Service Fabric issue.

Subscription code:
```csharp
var observer = await _client.CreateObjectReference<IEventObserver>(this);
await _eventGrain.Subscribe(observer);
```

Notified method:
```csharp
public async void OnNewEvent(string ev)
{
    await Process(ev);
 }
```

Inside Process I do `GrainFactory.GetGrain` and try to call that grain, which throws the exception.

**Comment by ReubenBond** [comment]
I want to get a clearer picture of what's happening here. Please correct my understanding:
* There are two silos
* On each silo, a client is created which subscribes to notifications from some grain (presumably this happens either within the bootstrap provider or after the silo is initialized).
* That grain responds to some event (what kind of event: is it a cluster change notification or something else?) and then notifies all subscribers.
* The subscribers handle that notification and this is where the exception occurs.

Is the `Process(ev)` call making a grain call?
Which version of Orleans are you using?

**Comment by martinothamar** [comment]
* There are two different silos (or should I say clusters?) with different grains.
* Right now it happens in the bootstrap provider yes, since I'm testing this communication.
* The grain with the ObserverSubscriptionManager just notifies straight away because I'm debugging this.
* The subscriber handles the message but inside `Process` the exception is thrown when I call a method on a newly acquired grain reference from the GrainFactory.

I'm using Orleans 1.5.2.
Hope this helps.

**Comment by ReubenBond** [comment]
How are you getting a reference to the client and the grain? Is the grain in the `ev` and the is the client created using `ClientBuilder`?

**Comment by martinothamar** [comment]
The solution with the grain with the ObserverSubscriptionManager publishes its grain-interfaces as a NuGet-package, which is included in the solution with the subscriber-grain. The client from the latter to the former is initialized using `ClientBuilder` and `builder.AddServiceFabric(serviceName);`. The `ev` string is just being passed on to other grains in that same silo. I use the primary key of the subscriber grain to get some other grains that need to be notified.

**Comment by ReubenBond** [comment]
Which grain factory do you use to get the grain inside `Process()`? Are you taking one from the bootstrap provider or is it from your `IClusterClient`?

**Comment by martinothamar** [comment]
The subscriber is a grain itself, so its this.GrainFactory

**Comment by ReubenBond** [comment]
I might be misunderstanding, but it seems like you're creating a client and using that client to create an object reference for a grain. Is that right?

Instead of `CreateObjectReference`, pass the grain reference to the other grain directly (`this.AsReference<TSomeInterface>()`) and make calls on it directly.

Grain should never have `void` methods (and `async void` should almost never be used: only for WPF apps or interop)

If you want to achieve a kind of fire-and-forget, you can use the `[OneWay]` attribute on a grain interface's method declaration. That means that the `Task` returned from that method will return immediately, successfully. This is similar to the `void` return for `IGrainObserver` interfaces. Usually this is not required, though.

**Comment by martinothamar** [comment]
The reason its a `void` method is because `IGrainObserver` enforces it. I think CodeGeneration throws an error if the interface deriving from `IGrainObserver` declares a method returning something other than `void`. I'll give it a go (without ObserverSubscriptionManager) and report back.

**Comment by ReubenBond** [comment]
Thanks & good luck! Perhaps we should add an additional rule to the code generator to also throw if a `Grain` implements `IGrainObserver` - it's not the intended usage.

What was happening is:
* Client receives notification from remote grain
* Client dispatches call to local grain on the client's dispatch thread
* Grain is now executing that call on a non-grain thread (bad)
* When grain tries to call another grain, we perform a sanity check and throw because the grain's execution model has been violated

**Comment by martinothamar** [comment]
Hi again. I now get an exception saying it doesn't find the implementation class for the interface. I'm now using `AsReference` and passing that reference to the grain on the silo through the client. Does the reference know that it has to communicate through the client connection? The exception is thrown in the subscriber silo, when calling `OnNewEvent` on the observer reference on the other silo.

**Comment by ReubenBond** [comment]
@martinothamar you shouldn't need the client at all now, just pass the grain reference directly to the other grain in a method call

**Comment by martinothamar** [comment]
There are 4 separate parts of this project each in its own silo-type/cluster (they are different VS-solutions). They serve different purposes and we want them to scale independently. So we need the client for communication between them. We discussed this issue earlier and found that we would rather just call directly instead of dealing with subscriptions. We originally wanted subscriptions because we want to filter out some events/messages based on some settings on the observer-grains, now we will control the filtering on what used to be the side of the `ObserverSubscriptionManager`. 

Another issue we've had with `ObserverSubscriptionManager` is that there is no interface behind it, so it was hard to mock and test. This will be easier now without the observer-pattern in Orleans.
Thanks for all the help!

**Comment by ReubenBond** [comment]
Please feel free to copy the `ObserverSubscriptionManager` code and improve it: either to contribute back or just to use in your own projects. For example, here's a version which I made for my own projects a few years ago: https://gist.github.com/ReubenBond/70257d59f1a540e90db6

**Comment by sergeybykov** [comment]
>Perhaps we should add an additional rule to the code generator to also throw if a Grain implements IGrainObserver - it's not the intended usage.

Is it an intended usage (for better or worse) for symmetry, so that the origin of observer notifications doesn't have to know whether the observer is a grain or a client object.

**Comment by ReubenBond** [comment]
@sergeybykov how about a runtime check to ensure that values passed to `OutsideRuntimeClient.CreateObjectReference` do not inherit from `Grain`?

**Comment by sergeybykov** [comment]
Sure. I guess this wasn't a problem before because `OutsideRuntimeClient.CreateObjectReference` was only available on the client side?

**Comment by ReubenBond** [comment]
I haven't looked at the code history, but it's available in `IGrainFactory` now. The `InsideRuntimeClient` implementation of it throws `InvalidOperationException: Cannot create a local object reference from a grain.`. Since it's easier to create clients and silos in the same process/AppDomain, it's likely more of an issue now.

**Comment by sergeybykov** [comment]
Yes, makes sense.

**Comment by ReubenBond** [comment]
@martinothamar are you happy to close this? I'll open a PR to validate that the argument passed to `CreateObjectReference` is not a `Grain` instance.

**Comment by martinothamar** [comment]
Yeah seems like a good solution to me :thumbsup:
