### ISSUE TITLE
Azure samples (.NET 4.6.2) cannot target Orleans 2.0.0

### ISSUE THREAD

**Issue by sebastianburckhardt** [dotnet/orleans#3751]
I want to update my existing Azure deployments (built on .NET 4.6.2) to use the latest Orleans build. My Azure deployments follow are built exactly like the Azure samples (AzureWebSample, HelloGeoSample, ReplicatedChatGrainSample, ReplicatedEventSample), so I started by trying to run those with the latest build.

Supposedly this should work as net standard is portable? But no luck. 

After updating the NuGet packages I get a error message: "The version of Microsoft.NET.Sdk used by this project is insufficient to support references to libraries targeting .NET Standard 1.5 or higher.  Please install version 2.0 or higher of the .NET Core SDK.	"

Does this mean that starting with Orleans 2.0.0 I can ONLY use .NET core projects in my application, and can no longer use my .NET 4.6.2 projects? 

Either way, the Azure samples should probably be updated or migrated so they work with 2.0.0.

**Comment by ReubenBond** [comment]
@sebastianburckhardt possibly you can add `<DependsOnNETStandard>false</DependsOnNETStandard>` to your csproj files.
Alternatively, installing .NET Core 2.0 SDK should fix the issue. It's not required for deployment

**Comment by sebastianburckhardt** [comment]
I tried today to run these samples against the latest stable (1.5.2), even that does not work. For whatever reason, some .netstandard NuGet packages get pulled in which break the compilation of the cloud deployment projects.

**Comment by ReubenBond** [comment]
@sebastianburckhardt have you tried upgrading your projects to the newer csproj format? (no `<?xml>` tag on first line, and `Sdk` attribute on the `<Project>` tag)

**Comment by jdom** [comment]
Unfortunately, ASP.NET WebForms is not supported in the new csproj tooling. We did try that first but hit that roadblock

**Comment by sebastianburckhardt** [comment]
After lots of trial and error I finally got one of the Azure samples running on 2.0.0-beta1!

First I updated the Orleans version in two steps to get the correct NuGet packages. This fixed some of the weirder errors I hit initially. But then I was still hitting problems with conflicting assembly versions.

In the end it boiled down to broken binding redirects in the app.configs... for some reason NuGet just can't update those correctly, even if reinstalling all packages. This is tiresome since there are easily over a hundred of those that need fixing, so manual editing really is not attractive.

Luckily I ended up discovering a feature of Web projects where you can double-click a assembly conflict warning in VS, and it generates the binding redirects for you in the web.config. Then I manually copied those redirects to all other projects in my solution, into the app.config file. That made it work in the end.

**Comment by sebastianburckhardt** [comment]
Something about the samples directory breaks the build. 

I got this to work on a snapshot of master from several months ago (in Samples/ReplicatedChatGrain/...)

But when I copy that directory into the latest master, the build no longer works. Are there some build settings that are magically set based on the location of the solution folder?

**Comment by sergeybykov** [comment]
This seems like a tooling issue. Nothing we change in Orleans itself can help this I think. We can and should revamp the sample to target 2.0.0 though.
