### ISSUE TITLE
Serializers are being generated for unneeded types 

### ISSUE THREAD

**Issue by dVakulen** [dotnet/orleans#3771]
Such as `OutboundMessageQueue`,  `OrleansTaskScheduler`, etc:

![image](https://user-images.githubusercontent.com/5787619/33783016-9b0a1ac6-dc63-11e7-9daf-0434f411620c.png)

It results in 20k+ LOC generated files, slowing the build and IDE. 

(using latest `master` branch (https://github.com/dotnet/orleans/commit/0aa92f39e7f22baff4d13ea6888c1adf26fe1263))

**Comment by sergeybykov** [comment]
Indeed, I see `OrleansCodeGenOrleans_Runtime_Messaging_MessageCenterSerializer`, `OrleansCodeGenOrleans_Runtime_SocketManagerSerializer`, `OrleansCodeGenOrleans_Runtime_Messaging_OutboundMessageQueueSerializer` and more such classes getting generated. Looks like a regression to me.

**Comment by sergeybykov** [comment]
I just checked that at https://github.com/dotnet/orleans/commit/43efc4b39e876b10767d8fdf4aec7ddeb70df1a4 this wasn't the case. So it's a relatively recent regression.

I *think* we can still release beta2 with this as it doesn't seem to break anything.

**Comment by sergeybykov** [comment]
The regression got introduced as part of https://github.com/dotnet/orleans/pull/3669.

**Comment by ReubenBond** [comment]
My bad, I widened the search to consider all types as though they were marked `[Serializable]`. I'll undo it if it's causing builds to be slower or build output to be significantly larger

**Comment by onionhammer** [comment]
Why not only generate serializers for the types used by Orleans grain interface contracts?

**Comment by sergeybykov** [comment]
@onionhammer Since Orleans is very accommodating when it comes to data types being passed (interfaces, `object` arguments, various collection types), it would be too restrictive to do that. We give developers a few ways to point to more types that they know could be passed over the wire.

**Comment by onionhammer** [comment]
It seems like those indeterminate types could be generated at runtime and cached

**Comment by sergeybykov** [comment]
In theory, yes. In practice, we ran into a number of corner cases and subtle issues (e.g. with loading of dependency types and their order) with run time generation of serializers. Because of that, in 2.0 we are making run time codegen optional and more explicit - it runs only for specified assemblies and only during silo/client build time. That seems to produce more predictable and repeatable results.
