### ISSUE TITLE
error building after adding OrleansCodeGenerator.Build to .net core class library

### ISSUE THREAD

**Issue by myusrn** [dotnet/orleans#3776]
vs17 15.4.5 | file | new | project | visual c# | .net core | class library (.net core) | ok
PM> Install-Package Microsoft.Orleans.OrleansCodeGenerator.Build
<project> | Build

expected: build succeeds w/o errors
actual: build fails with following error
%userprofile%\.nuget\packages\microsoft.orleans.orleanscodegenerator.build\1.5.3\build\Microsoft.Orleans.OrleansCodeGenerator.Build.targets(70,5): error MSB3073: The command ""%userprofile%\.nuget\packages\microsoft.orleans.orleanscodegenerator.build\1.5.3\build\..\tools\ClientGenerator.exe" "@obj\Debug\netcoreapp2.0\ClassLibrary1.orleans.g.args.txt"" exited with code 3.

**Comment by tinpl** [comment]
I believe 1.5.3 doesn't support .net core. Explicitly specified 2.0.0-beta1 version seems to be what you are looking for

**Comment by myusrn** [comment]
Thanks enabling view of pre-release packages in nuget package manager exposed the 2.0.0-beta1 update which resolved this build error.

Now when I run the https://github.com/dotnet/orleans simple code example I get a Orleans.Runtime.OrleansException "Message: Orleans.Runtime.OrleansException : You must initialize the Grain Client before accessing the GrainFactory" when I step into "var friend = GrainClient.GrainFactory.GetGrain<IHello>(0);"

Adding a "if (!GrainClient.IsInitialized) GrainClient.Initialize();" before that line replaces that runtime error with a System.IO.FileNotFoundException "Message=Cannot locate Orleans client config file."

Any pointers to the 2.0.0-beta1 specifics on what is needed that it seems the https://github.com/dotnet/orleans simple code example based on 1.5.3 did not require?

**Comment by sergeybykov** [comment]
Take a look at https://github.com/dotnet/orleans/tree/master/Samples/HelloWorld.NetCore as an example of how to use non-static client. `GrainClient.Initialize()` is a deprecated method of configuring clients. It should still work though if you feed it a `ClientConfiguration` object or (really old way) an XML config file.

**Comment by myusrn** [comment]
Thanks for the pointer to .net core applicable sample especially one containing details on how to setup and execute GrainClient.Initialize().  

I've been working through the readme.md reference to "[Virtual Actor Model](http://research.microsoft.com/apps/pubs/default.aspx?id=210931)" pdf and the statement “Actors allow building a stateful middle tier that has the performance benefits of a cache with data locality and the semantic and consistency benefits of encapsulated entities via application-specific operations.” This leaves me wondering about the possible overlap with exactly what the azure service fabric platform is meant to provide. I recall a mark russinovich service fabric talk highlighting the point about support for local data persistence, and seamless low latency distribution of those changes to other nodes, being a part of the service fabric model.

Is there a more recommended place for the differences and scenario applicability of these two different platforms to be discussed than this issues forum or is this an okay place to get clarification?

**Comment by sergeybykov** [comment]
Yes, there's definitely some overlap, as Service Fabric Reliable Actors is an alternative implementation of the virtual actor model, tightly integrated with SF.
