### ISSUE TITLE
Azure - Client with InternalEndpoint not able to connect with Silo in the same VNet

### ISSUE THREAD

**Issue by NitishMittalHon** [dotnet/orleans#3777]
[ClientLogs.txt](https://github.com/dotnet/orleans/files/1550314/ClientLogs.txt)
Hi Team,

I am deploying two separate cloud services each containing one worker role in same virtual network. Cloud service CS1 is hosting Orleans host worker role and cloud service CS2 is hosting Orleans client worker role. Following are the scenarios I tried with:

1. When both the host and client endpoints are configured as InputEndpoint - Working
2. When host is configured as InternalEndpoint and client is configured as InputEndpoint - Working
3. When client is configured as InternalEndpoint, regardless endpoint configuration for host - **Not Working**

We do not want to expose the ports of client worker and thus cannot configure it as InputEndpoint. Is there any workaround for this?
Attaching some of the client logs.

**Comment by sergeybykov** [comment]
The client is trying to connect to 172.29.0.4:30000. Is that a VN address? You can configure silo to bind to a specific IP address, and in this case you need to make sure it's the VN one.

**Comment by NitishMittalHon** [comment]
Hi @sergeybykov 
172.29.0.4 is the IP of SiloHost in VNet. IP 172.29.0.5 is of client worker role (as in logs); both are in same subnet. I can see in Orleans Silo membership table that the Silo have an active entry with IP, then why we should bind it to a specific address, also we can have multiple instances of the Silos [with dynamic scaling configured]. We are using default configurations for the mentioned deployment.

**Comment by sergeybykov** [comment]
I see. Is port 30000 open in the silo firewall?

**Comment by NitishMittalHon** [comment]
Hi @sergeybykov 
Yes the port is open. We are using Orleans 4.5.2.

**Comment by sergeybykov** [comment]
@NitishMittalHon Did you get this to work?

**Comment by sergeybykov** [comment]
Closing for now. Fell free to reopen.
