### ISSUE TITLE
Orleans Silo Blocking

### ISSUE THREAD

**Issue by sbrohi15** [dotnet/orleans#3783]
Hi,

I have a silo which imports data from a TXT file into a SQL Server Database. I have seen some scenarios where the silo appears to be idle for a long period of time (20 minutes or more) then eventually appears to resume activity. In every case where I have seen the silo to be idle, it eventually recovers. I want to fully understand how this occurs.

Some questions below:

1) How do I interpret the following 2 messages?

**Message One**
`--WorkItemGroup:Name=[Activation: S10.0.8.152:11111:248905601*grn/E927CDB7/00000000+\\dfw01-eimp152\u$\import\bkt01\6268\bkt01-6268-20171129-105603-20171129-cdp.aee@625a69bb #GrainType=EImporterGrainCollection.File.FileGrain Placement=RandomPlacement],State=Shutdown. Currently QueuedWorkItems=0; Total EnQueued=50; Total processed=50; Quantum expirations=0; TaskRunner=ActivationTaskScheduler-563112:Queued=0; SchedulingContext=[Activation: S10.0.8.152:11111:248905601*grn/E927CDB7/00000000+\\dfw01-eimp152\u$\import\bkt01\6268\bkt01-6268-20171129-105603-20171129-cdp.aee@625a69bb #GrainType=EImporterGrainCollection.File.FileGrain Placement=RandomPlacement State=Valid]`

**Message Two**
`--WorkItemGroup:Name=[Activation: S10.0.8.152:11111:248905601*grn/E927CDB7/00000000+\\dfw01-eimp152\u$\import\tcc06\952\tcc06-952-20171129-210019-20171129-deposit.aee@d88c7293 #GrainType=EImporterGrainCollection.File.FileGrain Placement=RandomPlacement],State=Shutdown. Currently QueuedWorkItems=0; Total EnQueued=50; Total processed=50; Quantum expirations=0; TaskRunner=ActivationTaskScheduler-563118:Queued=0; SchedulingContext=[Activation: S10.0.8.152:11111:248905601*grn/E927CDB7/00000000+\\dfw01-eimp152\u$\import\tcc06\952\tcc06-952-20171129-210019-20171129-deposit.aee@d88c7293 #GrainType=EImporterGrainCollection.File.FileGrain Placement=RandomPlacement State=Valid]`

2) In the above messages, I see one message containing the text "ActivationTaskScheduler-563112" and another containing "ActivationTaskScheduler-563118". Are 563112 and 563118 both tasks that reside in a FIFO queue? Can they be processed in parallel or does 563112 have to be processed before 563113 and so forth? If 563112 is a long-running task, will it block 563113 from completing?

3) Attached is the log snippet where you can see processing activity beginning at 07:58:29.563 then stopping at 08:00:44.605, then processing activity resumes at 08:22:32.337. That is a total of 22 minute of idleness in the silo. What is causing that to happen? What should I do to correct? Do the statistics indicate anything that is wrong with the silo? 

[OrleansLog_12-9.txt](https://github.com/dotnet/orleans/files/1550278/OrleansLog_12-9.txt)

**Comment by sbrohi15** [comment]
@sergeybykov Please take a look at this issue when you have some time. Thank you.

**Comment by sbrohi15** [comment]
@sergeybykov This is an urgent issue and I need your input on it as soon as possible. Thanks.

**Comment by sergeybykov** [comment]
I don't see any obvious problem in the log other than verbose logging being enabled. It makes scheduler dump details of all activations to the log, which is a large message. The only warnings I see are about that.

I don't see any idleness. Silo statistics get reported about every 5 minutes, as expected. So what's the problem here?

**Comment by sbrohi15** [comment]
@sergeybykov The problem is that the silo is not processing any data for 20 minutes or more. 

Was there anything in the statistics provided that alarmed you?

**Comment by sergeybykov** [comment]
>The problem is that the silo is not processing any data for 20 minutes or more.

What makes it do work? External requests? Timers? I don't see anything obviously wrong in the logs.

**Comment by sbrohi15** [comment]
@sergeybykov External requests. We have a grain client which sends requests to the silo to perform tasks. These tasks consist of various actions such as populating a SQL Database, etc.

**Comment by sergeybykov** [comment]
So what happens to those requests during the 'idle' 20 minutes? Do they arrive to the target grains? Does the client receive any errors?

**Comment by sbrohi15** [comment]
@sergeybykov They arrive and the client does not receive any errors.

**Comment by sbrohi15** [comment]
@sergeybykov Correct. We currently have a stateless worker class called "DatabaseGrain" which contains methods for executing SQL queries, stored procedures, etc. It is a utility class. We currently have 6 workers allocated for this worker which is equivalent to the number of processors on the server.

We use this worker for all of our database calls in our application (thousands). Could the use of this worker be considered a bottleneck if we have some database calls lasting 30 minutes or more? Would increasing the number of stateless worker replicas from the default (6) to 100 help improve silo throughput?

**Comment by sergeybykov** [comment]
>Could the use of this worker be considered a bottleneck if we have some database calls lasting 30 minutes or more?

If they are non-reentrant, then yes. You can either mark them as `[Reentrant]` or increase the max number of them.

Those 30 minute calls, I presume, are executed asynchronously, right? And the client doesn't wait for their completion, and only initiates them?

**Comment by sbrohi15** [comment]
@sergeybykov The 30 minute calls are executed asynchronously and the client does not wait for their response.

**Comment by sergeybykov** [comment]
If requests are getting delivered to the stateless worker grains, and they start the database operations, I don't understand how you discover that:
> The problem is that the silo is not processing any data for 20 minutes or more.

I feel like something is missing in the picture.

**Comment by sbrohi15** [comment]
@sergeybykov Are there any major downsides using the "Reentrant" feature with a stateless worker? Thanks!

**Comment by sergeybykov** [comment]
Nothing different from normal grains in that respect.

**Comment by sbrohi15** [comment]
@sergeybykov Are there any risks or serious implications from using this feature in Orleans that we should watch out for? Aside from marking the worker as reentrant, are any additional code changes required to prevent issues from inter-leaving calls?

**Comment by sergeybykov** [comment]
The typical risk is if there's in-memory state in that stateless worker grain (ironically, against the term). If different interleaving requests mutate and read that state, then one has to be very careful with considering all interleaving possibilities.

If there's no such shared state within the grain, then I'd say no particular risk.

**Comment by sbrohi15** [comment]
@sergeybykov One more concern I had is the effect this change may have on the database connection pool. If marked, "Reentrant", I presume this will increase the number of connections to the SQL Server and possibly may exceed default connection pool size of 100. Is there a workaround for that or way to keep the reentrant grain from exceeding that connection pool size?

**Comment by veikkoeeva** [comment]
@sbrohi15 Not a discussion about Orleans as such, but it strikes me you have to have a lot of data or a lot of computation to have single calls last that long. Could you perhaps create a special _staging table_, stream/bulk load the data in and then in the database if there's other kind of processing, do it when moving from the staging tables to proper tables?

**Comment by sergeybykov** [comment]
@sbrohi15 I only have a limited understanding of SQL connection pooling, but I believe you should be able to control it via ADO objects shared between grains in a silo relatively easily (even though this technically violates isolation of grains).

**Comment by veikkoeeva** [comment]
@sergeybykov, @sbrohi15 The connection pool size can be increased if needed. Inceasing the size isn't usually a problem. It just feels strange to need to have a 30 minutes long transaction, it suggests there's some processing happening that could perhaps be split in two so that that first load in the data, close the connection and do the processing independently of the loading part.
