### ISSUE TITLE
Sample does not build ...

### ISSUE THREAD

**Issue by scharada** [dotnet/orleans#3803]
the sample does not build

Program.cs(52,26): error CS1061: 'IClientBuilder' does not contain a definition for 'AddApplicationPartsFromReferences' and no extension method 'AddApplicationPartsFromReferences' accepting a first argument of type 'IClientBuilder' could be found (are you missing a using directive or an assembly reference?) [....\orleans\Samples\AccountTransfer.NetCore\src\OrleansClient\OrleansClient.csproj]
Program.cs(46,18): error CS1061: 'ISiloHostBuilder' does not contain a definition for 'AddApplicationPartsFromReferences' and no extension method 'AddApplicationPartsFromReferences' accepting a first argument of type 'ISiloHostBuilder' could be found (are you missing a using directive or an assembly reference?) [....\orleans\Samples\AccountTransfer.NetCore\src\SiloHost\SiloHost.csproj]
Program.cs(48,53): error CS0246: The type or namespace name 'TransactionsConfiguration' could not be found (are you missing a using directive or an assembly reference?) [....\orleans\Samples\AccountTransfer.NetCore\src\SiloHost\SiloHost.csproj]
    0 Warning(s)
    3 Error(s)

**Comment by jason-bragg** [comment]
We pushed out a 2.0 beta 2 last week, and have not updated all the samples yet.
I'll update this thread when AccountTransfer.NetCore been updated.

**Comment by jason-bragg** [comment]
PR out with fix.  "Update transactions sample. #3804"

@scharada if you're blocked you can pull that pr directly, though it should be merged some time today.

**Comment by sergeybykov** [comment]
Fixed via #3804.
