### ISSUE TITLE
Call OnDeactivateAsync on silo shutdown

### ISSUE THREAD

**Issue by jdahl** [dotnet/orleans#381]
Would it be possible to add so OnDeactivateAsync is called on all grains in the silo when a silo is shutdown?

The scenario for this is that a complete crash of a silo is a very rare occurrence so if the grains get this call when the silo goes down in a nice way (For host update or grain version refresh) they could do a nicer handover to the next activation by serializing any data they have.  

This would also help in the case where you save data on a timer. If this signal is sent then you could save the data only when the OnDeactiveAsync was received. Even if you did use a timer to save it periodically you would be sure to save the latest data using this. Even if you can recover this would be nicer since no data would be lost.

**Comment by gabikliot** [comment]
Yes, this is a really good idea. Improving the graceful shutdown overall, and what you suggested in particular, is a really good idea.

**Comment by gabikliot** [comment]
This was fixed via #457, #448, #413. 
Silo now calls OnDeactivateAsync on all grains upon shutdown. 
This is also integrated with Azure stopping event: when the role stops, it calls Silo.Stop that does the graceful shutdown.
This is also integrated with regular on prem. SiloHost : when the SiloHost is stopped gracefully via Stop call, it calls Silo.Stop that does the graceful shutdown.

**Comment by jdahl** [comment]
Great to hear! Thanks!
