### ISSUE TITLE
Possible to make GrainReference and GrainId publicly accessible?

### ISSUE THREAD

**Issue by Arshia001** [dotnet/orleans#3810]
Everything important about GrainReference and GrainId is internal. This is fine for normal use, but really hurts when trying to implement custom storage providers or serializers.

One specific case for which I really need to access the internals of GrainId is to implement grain reference serialization/deserialization in my custom serializer, which is optimized for storage space and having only a ~100 character ToKeyString() result to store is not ideal when I could, under the best circumstances, have between maybe 4 and 20 bytes to store (not counting the possibility of long string keys).

I can just take the source and change the members to be public, but I'm wondering if there is a specific reason they were made internal (other than to simplify the API), and if they can't be made public altogether.

**Comment by yevhen** [comment]
`GrainReference` gives you `InterfaceName` and `PrimaryKey`. You can store that info instead of `KeyString`. Then upon deserialization call `IGrainFactory.GetGrain<T>(pk)`. You would need to use `typeof(factory).MakeGenericMethod` and restore interface name to `Type` to make it work.

It's not optimal but will work. I wonder why such functionality is not built-in thus. Perhaps, we need to open an issue.

**Comment by Arshia001** [comment]
‌@yevhen I'm doing just that with grain references, but since you have no such API for client references, you can't use it there. You gave me an idea however (don't ask how, you just did). As a less hacky workaround, one could theoretically parse the key string and get the data out, and then put the data back in key string form when needed. This won't exactly be performant, but  it'll work. I'd still love to hear from the Orleans team as to why they made GrainId internal though.

**Comment by yevhen** [comment]
@Arshia001 what you mean by *client reference*?

**Comment by Arshia001** [comment]
Yes. That. They're called "client grains" in the source.

**Comment by yevhen** [comment]
@Arshia001 check what I'm doing [here](https://github.com/OrleansContrib/Orleankka/blob/master/Source/Orleankka/Core/ClientEndpoint.cs#L85) and then [back](https://github.com/OrleansContrib/Orleankka/blob/master/Source/Orleankka/Core/ClientEndpoint.cs#L88). But this requires access to internals `GrainReference.FromKeyString(key, null);`

For client (observer) references you can only store full key, since it is completely opaque. There is no type information there

**Comment by yevhen** [comment]
@Arshia001 and there is no point to serialize them permanently

**Comment by Arshia001** [comment]
But there is, clients may be much more long-lived than one would normally imagine. I do wonder if a grain could still communicate with the  observers if it was activated on a different silo though...

**Comment by yevhen** [comment]
@Arshia001 yes, it can. By *permanent* I meant "can outlive system redeploy".

**Comment by Arshia001** [comment]
Depends. If you have separate gateway machines which run clients and other machines for hosting silos which may decide to deactivate grains, then yes, you'd definitely want to persist observer references.

**Comment by Arshia001** [comment]
Here's the source for my less-than-absolutely-ugly hack. The SerializationGrainReference class uses only primitive types for storage and is perfectly serializable with any reasonable serializer. Combined with a smart serializer (I use a heavily modified version of the Bond serializer) this can reduce the size of the stored data from ~60-100 bytes to something between 10 and 40 bytes for grains with no string key and no generic arguments.

```public class SerializationGrainReference
{
    private const string GRAIN_REFERENCE_STR = "GrainReference";
    private const string SYSTEM_TARGET_STR = "SystemTarget";
    private const string OBSERVER_ID_STR = "ObserverId";
    private const string GENERIC_ARGUMENTS_STR = "GenericArguments";


    static void ParseGrainId(string GrainIdStr, out ulong n0, out ulong n1, out ulong typeCodeData, out string keyExt)
    {
        var trimmed = GrainIdStr.Trim();

        var fields = trimmed.Split(new char[] { ',' }, 2);
        n0 = ulong.Parse(fields[0].Substring(0, 16), NumberStyles.HexNumber);
        n1 = ulong.Parse(fields[0].Substring(16, 16), NumberStyles.HexNumber);
        typeCodeData = ulong.Parse(fields[0].Substring(32, 16), NumberStyles.HexNumber);
        keyExt = null;
        switch (fields.Length)
        {
            default:
                throw new InvalidDataException("UniqueKey hex strings cannot contain more than one + separator.");
            case 1:
                break;
            case 2:
                keyExt = fields[1];
                break;
        }
    }

    public static SerializationGrainReference Serialize(GrainReference GrainRef)
    {
        var KeyString = GrainRef.ToKeyString();
        var Ref = new SerializationGrainReference();

        // Parse grain reference key string
        string grainIdStr;
        int grainIdIndex = (GRAIN_REFERENCE_STR + "=").Length;

        int genericIndex = KeyString.IndexOf(GENERIC_ARGUMENTS_STR + "=", StringComparison.Ordinal);
        int observerIndex = KeyString.IndexOf(OBSERVER_ID_STR + "=", StringComparison.Ordinal);
        int systemTargetIndex = KeyString.IndexOf(SYSTEM_TARGET_STR + "=", StringComparison.Ordinal);

        if (genericIndex >= 0)
        {
            grainIdStr = KeyString.Substring(grainIdIndex, genericIndex - grainIdIndex).Trim();

            string genericStr = KeyString.Substring(genericIndex + (GENERIC_ARGUMENTS_STR + "=").Length);
            if (!String.IsNullOrEmpty(genericStr))
                Ref.GenericArgs = genericStr;
        }
        else if (observerIndex >= 0)
        {
            grainIdStr = KeyString.Substring(grainIdIndex, observerIndex - grainIdIndex).Trim();

            string observerIdStr = KeyString.Substring(observerIndex + (OBSERVER_ID_STR + "=").Length);
            Ref.ObserverReferenceId = Guid.Parse(observerIdStr);
        }
        else if (systemTargetIndex >= 0)
        {
            grainIdStr = KeyString.Substring(grainIdIndex, systemTargetIndex - grainIdIndex).Trim();

            string systemTargetStr = KeyString.Substring(systemTargetIndex + (SYSTEM_TARGET_STR + "=").Length);
            Ref.SystemTargetSiloAddress = systemTargetStr;
        }
        else
        {
            grainIdStr = KeyString.Substring(grainIdIndex);
        }

        ParseGrainId(grainIdStr, out ulong n0, out ulong n1, out ulong typeCode, out string keyExt);
        Ref.IdN0 = n0;
        Ref.IdN1 = n1;
        Ref.TypeCodeData = typeCode;
        Ref.KeyExt = keyExt;

        return Ref;
    }

    public static GrainReference Deserialize(SerializationGrainReference Ref, IGrainReferenceConverter GrainReferenceConverter)
    {
        var s = new StringBuilder();
        s.AppendFormat("{0:x16}{1:x16}{2:x16}", Ref.IdN0, Ref.IdN1, Ref.TypeCodeData);
        if (Ref.KeyExt != null)
        {
            s.Append("+");
            s.Append(Ref.KeyExt);
        }
        string IdStr = s.ToString();

        string KeyString;
        if (Ref.ObserverReferenceId != null)
        {
            KeyString = String.Format("{0}={1} {2}={3}", GRAIN_REFERENCE_STR, IdStr, OBSERVER_ID_STR, Ref.ObserverReferenceId.ToString());
        }
        else if (Ref.SystemTargetSiloAddress != null)
        {
            KeyString = String.Format("{0}={1} {2}={3}", GRAIN_REFERENCE_STR, IdStr, SYSTEM_TARGET_STR, Ref.SystemTargetSiloAddress);
        }
        else if (Ref.GenericArgs != null)
        {
            KeyString = String.Format("{0}={1} {2}={3}", GRAIN_REFERENCE_STR, IdStr, GENERIC_ARGUMENTS_STR, Ref.GenericArgs);
        }
        else
        {
            KeyString = String.Format("{0}={1}", GRAIN_REFERENCE_STR, IdStr);
        }

        return GrainReferenceConverter.GetGrainFromKeyString(KeyString);
    }


    public ulong IdN0 { get; set; }

    public ulong IdN1 { get; set; }

    public ulong TypeCodeData { get; set; }

    public string KeyExt { get; set; }

    public string GenericArgs { get; set; }

    public Guid? ObserverReferenceId { get; set; }

    public string SystemTargetSiloAddress { get; set; }
}```

**Comment by Alxandr** [comment]
I just ran into this issue, which ended up with resigning to use the KeyString which is much longer then I would like. If making GrainId and GrainReference detail public is problematic, would it be possible to make a `GrainReferenceKeyInfo` (or similar name) class/struct, so that you could do something like this?

```csharp
// refInfo contains *all* information required to produce the grain reference again.
// basically, the key string, but as parts, instead of a string, so that default values
// can be ignored, and integers can be serialized as such.
var refInfo = myGrainReference.GetKeyInfo();

var myRefCopy = grainReferenceConverter.GetGrainFromKeyInfo(refInfo);
```

**Comment by Arshia001** [comment]
@Alxandr I like your solution, but nameless tuples in public interfaces are a bad idea.

**Comment by Alxandr** [comment]
@Arshia001 Generally I would agree. But the type here is intended to be a simple structure containing the data needed to produce a GrainReference and nothing more, and while not leaking information from the grain reference you don't need. It's up to serializer implementers to deal with if they want to name these things in their serialization format. Anyways, I'm not saying it has to be this way, I could certainly be convinced to change it, but for now I think this is the cleaner solution. What the data is should not matter to the serializers (which is the only target audience). Only the fact that if you give me 3 ulongs and a string, I can give you a reference.

**Comment by yevhen** [comment]
You're looking for something like this :) https://github.com/OrleansContrib/Orleankka/blob/master/Source/Orleankka/ActorPath.cs

**Comment by Alxandr** [comment]
@yevhen That's still just 2 strings though. As opposed to being able to serialize using just a few bytes in some cases. If you're using long IDs with no extensions and small IDs, you could get down to a single byte of storage for an entire actor id.

**Comment by Arshia001** [comment]
How would you store an ID in one byte? VLQ? Considering that we need at least 3 different pieces of data, that's an unlikely scenario. With small integer keys you can go quite low, but with GUIDs (handy as they are) you need the 16 bytes + one or two more to store the fact that there is no string key extension and no server address and whatnot. Still a lot shorter than those key strings though.

**Comment by Alxandr** [comment]
You're right. I missed one data point. The type code data contains both "type data", and the category enum. The category enum is often 0 though, so if we assume we need 3 bytes ([category enum](https://github.com/dotnet/orleans/blob/master/src/Orleans.Core.Abstractions/IDs/UniqueKey.cs#L377) seems to use 1) for the type code, and the category enum is 0, we can get down to 4 bytes. Not 1. Though that's in specifically crafted cases. Regardless, you can *at least* get down to half the data needed for string encoding using hex, and that's the worse case.
