### ISSUE TITLE
Simplify grain reference deserialization

### ISSUE THREAD

**Issue by yevhen** [dotnet/orleans#3811]
Related to #3810 

It is a common pattern to serialize/deserialize grain references using non-opaque keys. Instead of serializing `GrainReference.ToKeyString()` which is too long an opaque (GUIDs?), it is enough to just get interface name and primary key, basically storing grain interface type + id. 

But then to deserialize it back to `GrainReference` we need to dance with:
1. Resolve interface name string to a `Type`
2. Call `typeof(IGrainFactory).MakeGenericMethod<T>` and perhaps cache it
3. Use dynamic invoke or better compile and cache a delegate

I think this could be greatly simplified if grain factory can provide and additional non-generic overload which takes interface name string (or `Type`) and primary key and do that for us. This should be dead simple since all of the information (interface name + factory method) is already (or could be easily) cached by the framework.

This would greatly simplify a lot of scenarios related to serialization of grain references.

**Comment by yevhen** [comment]
Also, serializing and deserializing client observer references is just a total hack. It would be great to provide an easy way to do custom serialization.

**Comment by sergeybykov** [comment]
#1511 also seems relevant here.

**Comment by ReubenBond** [comment]
Starting in 4.0.0-preview1, `GrainReference` instances are defined by two serializable types:
`GrainId`, which is essentially two strings, and `GrainInterfaceType`, which is essentially a string.

Deserializing a `GrainReference` instance now involves deserializing the above (from strings) and calling `GrainFactory.GetGrain(grainId, grainInterfaceType)`. That will give you back a `GrainReference` which you can directly cast to the type you want. Alternatively, you can use the `.AsReference<T>()` method on it.
