### ISSUE TITLE
When silo is down, but not set by orleans as down, call grains in that silo may hang

### ISSUE THREAD

**Issue by bob-dawson** [dotnet/orleans#3824]
I'm using the orleans 2.0 beta 3.  I'm using two silos for test, and zookeeper as SystemStore.  When one silo down (maybe lost network connection, or simply kill process for simulate), but at that time , Orlean still think it's alive, then call from client connect to other silo proxy, but use grain which is activated at the down silo, call may never return, and without any exception.  I think that's a big problem.  In orlean log, it is reported as a warn, but no exception return to caller:

2017-12-27 16:45:51.0647 Warn - No target activation S192.168.73.1:10000:252060047*cli/9eb2fe83@8ebaef87 for response message: Transient Rejection (info: Silo S192.168.73.1:10000:252060047 is rejecting message: Request S192.168.73.1:10000:252060047*cli/9eb2fe83@8ebaef87->S192.168.73.2:10000:252059839*grn/558F2F/00000000@0881db9a #750: global::Ecm.Interface.IServerManage:SetActive(). Reason = Recent (00:00:00.0009711 ago, at 2017-12-27 08:45:51.022 GMT) connection failure trying to reach target silo S192.168.73.2:10000:252059839. Going to drop Request msg 750 without sending. CONNECTION_RETRY_DELAY = 00:00:01.) Response S192.168.73.2:10000:252059839*grn/558F2F/00000000@0881db9a->S192.168.73.1:10000:252060047*cli/9eb2fe83@8ebaef87 #750: global::Ecm.Interface.IServerManage:SetActive()

how to reproduce:  
just write a client call a grain repeatedly, say every 5 seconds.  Then start silo 1, client 1 connect to silo1, make the grain activate in silo 1.   Then start silo 2, client 2 connecct to silo2,  and kill silo 1, then client 2 will hang in the grain call.  I test wait for 10 minutes, it still not return.

**Comment by benjaminpetit** [comment]
So if I understood correctly, you killed a silo (or completely cut off his networking access) when you are experiencing this? I would say it is to be expected. 

> but no exception return to caller:

On the client you should get a `TimeoutException` after 30 seconds (the default value, you can change this in the configuration). 

In your example, the silo that is still available will mark the other silo as dead after a certain period of time. You can also customize this value in configuration.

We don't use aggressive value by default but you can change it to what seems best in your case.

**Comment by bob-dawson** [comment]
But the problem is there is no TimeoutException after 30 seconds.   I've tested wait 10 minutes, still no timeout exception. So when in this situation,  every call to grain on the deat silo, will hang forever.   That will make to write correct code which can survive this silo down very difficult.

**Comment by bob-dawson** [comment]
I've tried to debug this, and add 2 lines of code, seems this can be fixed, but I'm not sure weather it will have other side effects, because I'm quite new to the Orleans source code.

In the orleans\src\Orleans.Runtime\Core\Dispatcher.cs, Line 185, the code is:

                        logger.Warn(
                            ErrorCode.Dispatcher_NoTargetActivation,
                            nonExistentActivation.Silo.IsClient
                                ? "No target client {0} for response message: {1}. It's likely that the client recently disconnected."
                                : "No target activation {0} for response message: {1}",
                            nonExistentActivation,
                            message);

                        this.localGrainDirectory.InvalidateCacheEntry(nonExistentActivation);

I think it should be something like this:

                        logger.Warn(
                            ErrorCode.Dispatcher_NoTargetActivation,
                            nonExistentActivation.Silo.IsClient
                                ? "No target client {0} for response message: {1}. It's likely that the client recently disconnected."
                                : "No target activation {0} for response message: {1}",
                            nonExistentActivation,
                            message);

                        this.localGrainDirectory.InvalidateCacheEntry(nonExistentActivation);

                        //add by bob dawson, not hang caller, should do response
                        if (Transport.TryDeliverToProxy(message))
                            return;

                        this.catalog.RuntimeClient.ReceiveResponse(message);
The added 2 line is copy from this method:
private void ReceiveResponse(Message message, ActivationData targetActivation)

**Comment by benjaminpetit** [comment]
Can you show me the signature of the grain call?

I think the issue here is that you are doing a "OneWay" call, and the client doesn't expect any response, so Orleans just drop the message if the target activation is not found.

**Comment by bob-dawson** [comment]
No, It's not a OneWay call.  The sinature is:
    public interface IServerManage: IGrainWithIntegerKey
    {
        Task<List<string>> SetActive(string serverId, IPEndPoint address);
    }

**Comment by benjaminpetit** [comment]
Are you testing this with the debugger attached? Orleans will detect it and set the Timeout value to 30 minutes. That's maybe why you are not seeing any timeout.

I think that we could maybe send a rejection message more quickly, but I am not sure if your proposition is the best way to implement that.

**Comment by bob-dawson** [comment]
Yes, you are correct, I'm debugging.  I've done test without debug, and the timeout exception is received after 30 seconds.  I think that's acceptable.  But if a a rejection message can be send more quickly, that's preferable.  Thans for the explanation.  I don't see documentation about the timeout debugging behavior before.

**Comment by benjaminpetit** [comment]
Closing the issue. If you have more comments, feel free to add them and I will reopen.

Thanks!
