### ISSUE TITLE
Logical call context data not flowing to constructor and ReadStateAsync

### ISSUE THREAD

**Issue by nirhp** [dotnet/orleans#3825]
Hi,

We piggyback on Orlean's logical call context slot "#ORL_RC" to have request-specific data flow through to all grain who handle it, which aid in diagnostics and logging (e.g. we store a correlation ID in it). This has been working well for us, except during a grain's constructor and the initial ReadStateAsync on stateful grains, both being called without the data in logical call context that exists in the context that triggered the grain's activation. Is there a way to have the logical call context data flow to the constructor and ReadStateAsync like it does for OnActivateAsync and any other grain method call?

**Comment by benjaminpetit** [comment]
I quicly tested manually, and it seems that the `RequestContext` is flowing in the `OnSetupState` and all calls (including the first one) of `ReadStateAsync`. Which version of Orleans are you using?

**Comment by nirhp** [comment]
We are using version 1.3.1

**Comment by nirhp** [comment]
Let me elaborate my issue.

I tested this in Orleans 1.5.3 by writing / reading data using `RequestContext.Set()` / `RequestContext.Get()`.
Indeed, the 1st call to the Grain's `ReadStateAsync `had the data.
My issue is that the 1st call to the StorageProvider `ReadStateAsync `is done with an empty RequestContext, please note that this call takes place before the 1st Grain `ReadStateAsync `call.

I added reproduction code which writes the calls to by their order to c:\orleans.txt
[SiloHost1.zip](https://github.com/dotnet/orleans/files/1603634/SiloHost1.zip)

**Comment by benjaminpetit** [comment]
I confirm the issue in 1.5.x, but using 2.0.0-beta3 the `RequestContext` is correctly populated in the first `ReadStateAsync`:

```
Grain1.ctor request context data: ''
Grain1.ReadStateAsync request context data: '=> Data flowed from request context'
FakeStorageProvider.ReadStateAsync request context data: '=> Data flowed from request context'
Grain1.ReadStateAsync request context data: '=> Data flowed from request context'
FakeStorageProvider.ReadStateAsync request context data: '=> Data flowed from request context'
```

Note that the `RequestContext` was not populated for the constructor (and I don't think it should)

**Comment by nirhp** [comment]
1. Great! Would it be fixed in 1.5.x?
2. I'm trying to recreate it in 2.0.0 beta3, but I'm getting:

> Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Orleans.Runtime.OrleansConfigurationException: No application assemblies were added to ApplicationPartManager. Add assemblies using the AddApplicationPart(Assembly) extension method on the client builder.
>    at Orleans.ApplicationPartValidator.ValidateConfiguration()
>    at Orleans.ClientBuilder.ValidateSystemConfiguration(IServiceProvider serviceProvider)
>    at Orleans.ClientBuilder.Build()

**Comment by benjaminpetit** [comment]
1. I don't know if we planned to do another 1.5.x release yet. @sergeybykov ?
2. Yes configuration changed a lot in 2.0, see here: https://dotnet.github.io/orleans/Documentation/2.0/Configuration2.0.html
You need to use the `SiloHostBuilder` with someting like 
```
.ConfigureApplicationParts(parts => 
    parts.AddApplicationPart(typeof(YourGrainHere).Assembly)
         .WithReferences())
```

**Comment by sergeybykov** [comment]
I think we need to release 1.5.4 around the time we are done with 2.0.0 to include fixes that makes sense to backport.

**Comment by benjaminpetit** [comment]
Closing this issue, since I don't think we will do 1.5.x release at this point.
