### ISSUE TITLE
ToGatewayUri will cause exception when using IPv6

### ISSUE THREAD

**Issue by Cuge** [dotnet/orleans#3832]
Orleans.Core\Utils\Utils.cs 
Method 
        **public static Uri ToGatewayUri(this System.Net.IPEndPoint ep)**
and         
        **public static Uri ToGatewayUri(this SiloAddress address)**
will generate UriFormatException exception when Address is the IPv6 format.

I think UriBuilder should fix the problem.
Code below:

        public static Uri ToGatewayUri(this System.Net.IPEndPoint ep)
        {
            var builder = new UriBuilder("gwy.tcp", ep.Address.ToString(), ep.Port);
            return builder.Uri;
        }

        /// <summary>
        /// Represent a silo address in the gateway URI format.
        /// </summary>
        /// <param name="address">The input silo address</param>
        /// <returns></returns>
        public static Uri ToGatewayUri(this SiloAddress address)
        {
            var builder = new UriBuilder("gwy.tcp", address.Endpoint.Address.ToString(), address.Endpoint.Port, address.Generation.ToString());
            return builder.Uri;
        }

**Comment by sergeybykov** [comment]
@Cuge Thanks for reporting the issue! Do you want to submit a PR with a fix?

**Comment by Cuge** [comment]
@sergeybykov it is a small bug fix, you can use code comments to fix it.
