### ISSUE TITLE
ClientConfiguration.LoadFromFile, sync over async

### ISSUE THREAD

**Issue by danielwertheim** [dotnet/orleans#3835]
Works like a charm when executing in a context where restoring on captured context isn't a problem (e.g. Console) but when switching to e.g. ASP.Net environment where bootstraping happens in a non async flow one might think that the exposed `ClientConfiguration.LoadFromFile()` is safe (due to being sync). This seems to be wrong.

https://github.com/dotnet/orleans/blob/master/src/Orleans.Core/Configuration/ConfigUtilities.cs#L349
https://github.com/dotnet/orleans/blob/master/src/Orleans.Core/Configuration/ClusterConfiguration.cs#L440

None of the lines has `ConfigureAwait(false)` so when https://github.com/dotnet/orleans/blob/master/src/Orleans.Core/Configuration/ClientConfiguration.cs#L222 happens, the blocking call seem to cause a dead-lock, at least it hangs for me.

Either expose `LoadFromFile` as pure `async` and let the consumer decide or perhaps start using `ConfigureAwait(false)`? Guess the first option is hard has that would be breaking and exposing `LoadFromFileAsync` is hard is not an option since that seem to violate the naming convention with other async methods.

**Comment by xiazen** [comment]
Hi @danielwertheim 

Sorry for the confusion. Our legacy `ClientConfiguration` and `ClusterConfiguration` is not great. That's part of the reason why we are going to deprecate them in orleans 2.0. In 2.0, configuration will be mostly replaced by  [ASP.Net `IOption`](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options). As to how to load those config objects, such as from file, env variable etc, ASP.Net provided `[IConfiguration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?tabs=basicconfiguration)` system to do that. Let me know if the new way is better and whether you have further concern.

**Comment by xiazen** [comment]
Can you explain more on why you think there's a deadlock there? I have limited understanding  on your application start up flow. Can you tell me more where is the deadlock? 

`LoadFromFile` is a sync method by c# standard. Are you implying their `TestWaiter.GetResult()` method has a bug in it?

**Comment by danielwertheim** [comment]
Some info: https://blog.stephencleary.com/2014/12/a-tour-of-task-part-6-results.html
```
GetAwaiter().GetResult()
```

is blocking. And since you do that nested in async flow, you can become victim to deadlocks in ASP.Net as `ConfigureAwait` is not used.

One way to cause it is to e.g. try and load the config in a controller action:

```
var c = ClientConfiguration.LoadFromFile(HttpContext.Current.Server.MapPath("~/App_Data/ClientConfiguration.xml"));
```

The way I bumped into it was during bootstrapping of the application.

**Comment by xiazen** [comment]
We can add a documentation warn people about this potential deadlock as well.

**Comment by danielwertheim** [comment]
I'm over it as I switched to 2.0 and manual config.

With bootstrap I didn't mean Orleans specific feature, but seen to my app. As I said, in my case it was in `Startup`.

**Comment by xiazen** [comment]
that's good to hear. let me know if you have further issues.

**Comment by xiazen** [comment]
close this for now, welcome to reopen it if you have more question
