### ISSUE TITLE
Question about Grain relations 1 to n where n is large

### ISSUE THREAD

**Issue by JanEggers** [dotnet/orleans#3836]
as far as i understand the API if i have a 1 to n relation in my model i have to do the following: 

The info is from looking at your AdventureSample (i didnt yet do it on my own):

initialize:
1. create parent entity if its needeed or not
2. read all childs from the storage
2. call a method on the parent to register all childs (and keep a list/dictionary of em in the parent)

access it:
1. get the parent grain.
2. call a method on the parent to get its childs

What would it take / is it possible at all to build a interface like  `IQueryable<T> GetGrains<T>()` on the IGrainFactory . So i can formulate a linq against the underling storage and get back only the grainreferences that match the query. It should be working either in the client or an existing grain.

Like:

`parent.GetGrains<Child>().Where( c => c.Age < 21);`

Im asking because I think that houskeeping of references is errorprone and resource intensive and the db is much more capable of doing so... and for me it literally destroys the "virtual" part of the virtual actor model.

**Comment by JanEggers** [comment]
I thisnk this is what im looking for:

https://github.com/OrleansContrib/Orleans.Indexing

**Comment by veikkoeeva** [comment]
@JanEggers And/or https://github.com/dotnet/orleans/issues/3413.

**Comment by JanEggers** [comment]
@veikkoeeva jup thats the same thing :)

**Comment by sergeybykov** [comment]
@JanEggers There's work underway in Research to bring https://github.com/OrleansContrib/Orleans.Indexing into the main codebase after 2.0.0.
