### ISSUE TITLE
Docs and logs, inconsistent

### ISSUE THREAD

**Issue by danielwertheim** [dotnet/orleans#3837]
Docs (http://dotnet.github.io/orleans/Documentation/Deployment-and-Operations/Configuration-Guide/Configuring-.NET-Garbage-Collection.html) says GC should be configured:

```
<configuration>
  <runtime>
    <gcServer enabled="true"/>
    <gcConcurrent enabled="true"/>
  </runtime>
</configuration>

```

But when doing so, logs seem to recommend `gcConcurrent.enabled=false`.

```
Note: Silo not running with ServerGC turned on or with GCLatencyMode.Batch enabled - recommend checking app config : <configuration>-<runtime>-<gcServer enabled="true"> and <configuration>-<runtime>-<gcConcurrent enabled="false"/>
```

How should it be?

**Comment by sergeybykov** [comment]
`gcConcurrent` shold be set to `true` The message in the log has been adjusted a while ago in #3271. What version are you running?

**Comment by danielwertheim** [comment]
Latest non pre release from NuGet (v1.5.3)

Should I be using the beta of 2.0.0 instead? Is it stable enough?

**Comment by sergeybykov** [comment]
I see that we didn't include this change into any of the 1.5.x releases. The warning about `gcConcurrent` is totally benign though.

2.0.0 is stable. It's absolutely fine to use it, even in production.

**Comment by sergeybykov** [comment]
@danielwertheim You are not testing it on a single core VM by chance?

**Comment by danielwertheim** [comment]
No. Bare metal quad core, Win10-x64, but single node, not cluster.

**Comment by sergeybykov** [comment]
Please take a look at #3942. By setting `ServerGarbageCollection` to `true` or `false` I can turn the warning on or off. So I see it working as expected.
