### ISSUE TITLE
ClientInvokeCallback for grain to grain call in Orleans 1.5.3

### ISSUE THREAD

**Issue by MishaUliutin** [dotnet/orleans#3840]
I am migrating project from Orleans 1.4.2 to 1.5.3 and faced with issue set ClientInvokeCallback inside Silo. We are using ClientInvokeCallback/IGrainCallFilter(IProviderRuntime.SetInvokeInterceptor in 1.4.2) for propagate log correlation id between http frontend -> grain and grain to grain call, but looks like in Orleans v1.5.3 it is not possible anymore set ClientInvokeCallback inside Silo as GrainClient uses directly OutsideRuntimeClient class (and guard which checks client initialization was added). What is proper way to add ClientInvokeCallback for grain to grain call inside Silo? or something other should be used for the same purpose?

**Comment by sergeybykov** [comment]
Is this still relevant in 2.0?

**Comment by ReubenBond** [comment]
This isn't relevant in 2.0 - it's replaced by `IOutgoingGrainCallFilter`
