### ISSUE TITLE
Dependency Injection in ASP.NET Core

### ISSUE THREAD

**Issue by darting** [dotnet/orleans#3847]
Hi there .. for orleans 2.0, what I should register to IServiceCollection? ClientBuilder? what will be its lifetimes? Transient or Scoped or Singleton? Thanks for help.

**Comment by alirezajm** [comment]
From my short experience with orleans:
Within a grain the scope is the lifetime of the grain activation.

So as the grains will live a long time normally (2 hours I believe is the default), which means the same instance will process requests, the services are injected only once per activation (If you're doing constructor injection). And when you resolve services within a grain yourself you'll get the same instance if you register them as scoped. So it's "a little" different compared to per request scopes like in asp.net mvc.

**Comment by ReubenBond** [comment]
The lifetime is whatever you decide: Singleton, Scoped (per-activation), or Transient

As for what you should register to: there is only one IServiceCollection per ClientBuilder or SiloHostBuilder, so it doesn't matter how you register a service.

**Comment by SebastianStehle** [comment]
I think the question was, what he should register TO the asp.net core application.

I would register the IClient as Singleton to the Asp.Net Core DI.

**Comment by ReubenBond** [comment]
Oh, got it!

Yes, register the IClusterClient as a singleton.
Optionally also register it as IGrainFactory in case that's all you need.

**Comment by SebastianStehle** [comment]
The `IGrainFactory` is also nice for co-hosting. Then you have 2 DI containers. One for the Silo and the other one for the asp.net part. But I need to access the grains from both parts. The IGrainFactory is a common interface and therefore you do not have to care, whether you are in the Silo or not.

**Comment by darting** [comment]
Hey got it .. thanks
