### ISSUE TITLE
[Question] Streams limitations, lots of subscribe/unsubscribes

### ISSUE THREAD

**Issue by alirezajm** [dotnet/orleans#3848]
I'm trying to use orleans streams to manage channel subscriptions in a websocket server. What happens is when sockets are connected, the server will ask a grain to give back a stream Id. The socket server (orleans client) then creates a subscription to that stream. Now these are a lot of subscriptions/unsubscriptions, and when the numbers grow I start to receive lots of exceptions on the client side when adding a message to the stream. SerializationExceptions to be exact.

Now my question is does the runtime sends a message from the silo for each subscription on the client side, or one message will be sent to the client and then the client forwards it to all local subscribers?
And on the broader sense is using streams in this way a good choice for this scenario?

_I'm using SMS provider with fire and forget and a memory storage provider for pubsubstore._

Things I've already tried to find the cause:
- Made stream messages Immutable. This was actually the way it was from the beginning, this leads to NullReferenceExceptions which made me think maybe the message is disposed (well not technically speaking).
- Added ILBasedSerializer for fallback serializer. No help to get the actual exception message.

**Comment by alirezajm** [comment]
I also get a lot of timeouts when subscribing 
```
warn: Orleans.Runtime.CallbackData[100157]
      Response did not arrive on time in 00:00:30 for message: Request *cli/e4c6a48b@78892cae->S127.0.0.1:40000:0*grn/716E8E94/dec7a082+SP_MemoryChannelWorker_WebSocket #1591141: global::Orleans.Streams.IPubSubRendezvousGrain:RegisterConsumer(). Target History is: <S127.0.0.1:40000:0:*grn/716E8E94/dec7a082+SP_MemoryChannelWorker_WebSocket:>. About to break its promise.
```

**Comment by xiazen** [comment]
Hi @alirezajm 

one message will be sent per subscription. So if client subscribe every time when the socket connect, client will end up with many subscriptions for the same stream. So if a messages is sent to the stream from a producer, then the same message will be sent to all the subscribers for that stream. In your case, client will receive many duplicated messages. 

To avoid this, when the socket connect, instead of subscribe again, client can resume on its existing subscription. 
 ```
            IStreamProvider streamProvider = Client.GetStreamProvider(streamProviderName);
            var stream = streamProvider.GetStream<int>(streamGuid, streamNamespace);
            var subscriptions = await stream.GetAllSubscriptionHandles();
            foreach (var sub in subscriptions)
            {
                await sub.ResumeAsync(onNextAsync);
            }
```

> Now my question is does the runtime sends a message from the silo for each subscription on the client side, or one message will be sent to the client and then the client forwards it to all local subscribers?

Just to clarify, runtime doesn't send a message, it is producer who sends a message, streaming runtime distribute the message to all its subscribers. Client in this case is a consumer who has many subscription to the same stream. Client doesn't forward it to all local subscribers, streaming runtime does. 

> And on the broader sense is using streams in this way a good choice for this scenario?

I'm not sure what your scenario is. If you just want client to subscribe to a stream and receive events from it, streaming is a good choice for that. You just need to avoid unnecessary subscriptions. 

Let me know if this make sense.

**Comment by xiazen** [comment]
Or if I misunderstood your workflow, please give me more information to understand. :)

**Comment by alirezajm** [comment]
Hi @xiazen,
Yeah I think you misunderstood a part of it.

> Just to clarify, runtime doesn't send a message, it is producer who sends a message, streaming runtime distribute the message to all its subscribers

I chose the wrong word there. My issue is actually about the distribution of messages.

Let me explain a bit more:
In the silo I have a producer grain.
In the socket server(orleans client), I have lots of socket handlers (consumers).
The socket server job is to merely proxy received messages from orleans streams down to socket connections. Every handler has a reference to the underlying socket and needs to have a separate subscription (hence the resume is not an option here cause there are different subscriptions). Now while there are a lot of handlers active at the same time they're also created and destroyed in a high rate (I've benchmarked to 5k connections/sec) leading to a lot of sub/unsub.

To clarify my question, I was wondering if a client subscribes multiple times to a stream does the runtime deliver the messages (from silo to client) multiple times, or just once from silo to client, and the client runtime then calls all subscription code? I think as you said the first scenario is what is happening, which is a waste of resources in my case (or similar scenarios), so if it is the case I have to do this manually, meaning subscribe once to every stream I need then dispatch the message to whatever handler I have to.

Further clarification, what i'm not sure is which flow is happening (arrows represent flow of a single message):
silo runtime -> client runtime -> subscription code -> socket#1 stream
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \\-> client runtime -> subscription code -> socket#2 stream
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \\-> client runtime -> subscription code -> socket#3 stream
or 
silo runtime -> client runtime -> subscription code -> socket#1 stream
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \\-> subscription code -> socket#2 stream
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; \\-> subscription code -> socket#3 stream

The second question was actually this concern: it may be that my view of the client is somewhat wrong and the client runtime (when it comes to streams) should be viewed as in a simple server-client architecture. So the client wasn't meant to have lots of subscriptions to the same stream.

Thank for your time 👍

**Comment by alirezajm** [comment]
You already answered the first question so I assume I've gotta handle the distribution in the client side myself. I just wanted to share why I can't simply use one subscription directly in socket handlers. If you have any other ideas i'd be very happy to hear them 😄

cheers.

**Comment by xiazen** [comment]
Hi @alirezajm 

thanks for the explain. it is much more clear now. Unfortunaly, messages is delivered at per subscription, not per stream consumer ->per subscription. So you will have to manage the distrbute to different socket connection in the client side yourself. 

There's another mechnism called [Observers](http://dotnet.github.io/orleans/Documentation/Core-Features/Observers.html), which supports sending async notification from silo to client. but it is also sending notification on  a per observer base, I guess it won't be helpful to you either. But it is much lighter than streaming, and seems fit in your use case more. Maybe worth to take a look .

**Comment by alirezajm** [comment]
Oh OK thank you.
also thanks for the observers tip I kinda missed that part in the docs.
