### ISSUE TITLE
Add OrleansJsonSerializer to external serializers causes circular references

### ISSUE THREAD

**Issue by csyszf** [dotnet/orleans#3853]
OrleansJsonSerializer's constructor:
`public OrleansJsonSerializer(SerializationManager serializationManager, IGrainFactory grainFactory)`

RegisterSerializationProviders:
`var serializer = ActivatorUtilities.CreateInstance(serviceProvider, typeInfo.AsType()) as IExternalSerializer;`

**Comment by ReubenBond** [comment]
I opened #3960 to fix this
