### ISSUE TITLE
Could not load type 'Orleans.Hosting.SiloBuilderApplicationPartExtensions' from assembly 'Orleans.Runtime, Version=2.0.0.0,

### ISSUE THREAD

**Issue by dazinator** [dotnet/orleans#3857]
I am attmepting to get a sample running targeting netstandard2 and the beta packages.

In my startup method I am attempting to use orleans dashboard, but I get the following exception:

![image](https://user-images.githubusercontent.com/3176632/34855101-cb6a1d14-f735-11e7-9b54-828be369db40.png)

```
Could not load type 'Orleans.Hosting.SiloBuilderApplicationPartExtensions' from assembly 'Orleans.Runtime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

Here is my code:

```

 var configBuilder = new ConfigurationBuilder()
                .AddCommandLine(args)
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("config.json", false, false);


            Configuration = configBuilder.Build();


            // starting host

            var builder = new SiloHostBuilder()
                .ConfigureLogging(ConfigureLogging)
                .UseConfiguration(LoadClusterConfiguration())
                .UseServiceProviderFactory(ConfigureServices)
                .UseDashboard((a) => { })
                .ConfigureApplicationParts(ConfigureApplicationParts);

```

I assume this is something I am not configuring correctly?

If I remove all dashboard related code, It gets further but then I get this error:

```

No service for type 'Orleans.Messaging.IGatewayListProvider' has been registered.

```

**Comment by ReubenBond** [comment]
@dazinator what's the stack on that last error?

The version you're using is likely built against 2.0-beta2, whereas you're likely using 2.0-beta3

**Comment by dazinator** [comment]
I am using all beta-3 packages, except for dashboard, which I have now updated to beta-4 - however I have removed dashboard configuration methods from my code in order to just see orleans working without dashboard first.

This is the error I get on the client:

> No service for type 'Orleans.Messaging.IGatewayListProvider' has been registered.

Stack:
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Orleans.OutsideRuntimeClient.ConsumeServices(IServiceProvider services)
   at Orleans.ClientBuilder.Build()
   at Radiate.Silo.HyperV.Program.<RunClient>d__8.MoveNext() in C:\Users\Darrell\Source\Repos\radiate\src\Radiate.Client\Program.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Radiate.Silo.HyperV.Program.<MainAsync>d__7.MoveNext() in C:\Users\Darrell\Source\Repos\radiate\src\Radiate.Client\Program.cs:line 39

Here is my Program.cs for the client:

```csharp

  class Program
    {
        private static readonly ManualResetEvent _exitEvent = new ManualResetEvent(false);

        public static IConfiguration Configuration { get; set; }     
      
        
        private static void ConfigureLogging(ILoggingBuilder loggingBuilder)
        {
            loggingBuilder.AddConsole();
        }

        static void Main(string[] args)
        {
            Console.WriteLine("Press any key once server is running...");
            Console.ReadKey();
            MainAsync(args).Wait();
        }


        static async Task MainAsync(string[] args)
        {         
                      
            await RunClient();
            Console.CancelKeyPress += (s, e) => _exitEvent.Set();
            _exitEvent.WaitOne();
        }

        private static async Task RunClient()
        {           

            IClusterClient client = new ClientBuilder().ConfigureApplicationParts(ConfigureApplicationParts)
                .LoadConfiguration("OrleansConfiguration.dev.xml")
                .ConfigureLogging(ConfigureLogging)
             //   .UseConfiguration(config)
                 .UseServiceProviderFactory(ConfigureServices)
                 //.UseStaticGatewayListProvider((a) => a.Gateways.Add(new Uri("http://localhost:3000")))
                .Build();

            await Task.Run(async () =>
            {
                await client.Connect();

                //  var imageName = "Windows Server 2012 R2";
                var registry = client.GetGrain<IHyperVisorRegistry>();

                await Task.Delay(new TimeSpan(0, 0, 30));
                var images = await registry.GetHyperVImageNames();
                Console.WriteLine($"Image count is: {images.Length}");
                // var status = image.GetStatus();
                //  Console.WriteLine($"Status of {imageName} is: {status}");
            });

            //  await task;

            Console.WriteLine("Press any key to exit");
            Console.ReadKey();
        }

        private static void ConfigureApplicationParts(IApplicationPartManager partManger)
        {
            partManger.AddApplicationPart(typeof(IHyperVisorRegistry).Assembly);
            partManger.AddApplicationPart(typeof(Program).Assembly);
        }

        private static IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddOptions();
            services.AddLogging();         

            return services.BuildServiceProvider();
        }      

    }

```

**Comment by dazinator** [comment]
Oh wow.
It was because I was using the same configuration file for both client and server.
Client requires its own seperate configuration.. Once I amended that it worked.

i.e my client was using:

> <?xml version="1.0" encoding="utf-8"?>
<OrleansConfiguration xmlns="urn:orleans">
  <Globals>
    
    <SeedNode Address="localhost" Port="11111" /> 
    <Liveness LivenessType ="MembershipTableGrain" />
  </Globals>
  <Defaults>
    <Networking Address="localhost" Port="11111" />
    <ProxyingGateway Address="localhost" Port="30000" />
  </Defaults>
</OrleansConfiguration>

And now its using:

```
<ClientConfiguration xmlns="urn:orleans">
  <Gateway Address="localhost" Port="30000"/>
</ClientConfiguration>
```

I must have missed this bit in the getting started docs, apologies.

**Comment by dazinator** [comment]
As a side note, it would be a nice enhnacement if the client configuration methods detected the absence of a `<ClientConfiguration>` node when loading from an xml file, and raised some sort of informative error :-)

**Comment by ReubenBond** [comment]
Glad you got it sorted :) In 2.0 we are discouraging the use of the xml configuration system and instead using programmatic configuration, so that should reduce the scope for errors.
