### ISSUE TITLE
Grain.InvokeException being reported as a Warning?

### ISSUE THREAD

**Issue by amccool** [dotnet/orleans#3859]
why is Grain.InvokeException being reported as a Warning?

When tracking down a problem, especially a problem with a stream message we get a Warning in the logs when an exception occurs.

Exception during Grain method call of message: Request S172.18.124.51:11111:253489437*cli/b116d8b2@db94af81->S172.18.124.53:11111:253489427*grn/3159BD7A/00000000+STRING_IDENT@069db998 #24: global::Rb.ReactivePrototype.PhoneGrainInterfaces.IPhoneGrain:PhoneGrainInviteReceived()

https://github.com/dotnet/orleans/blob/b0d7edfdb148614b1210cf37e0c0d555dc68b6c7/src/Orleans.Runtime/Core/InsideRuntimeClient.cs#L382

```
catch (Exception exc1)
                {
                    if (invokeExceptionLogger.IsEnabled(LogLevel.Debug) || message.Direction == Message.Directions.OneWay)
                    {
                        invokeExceptionLogger.Warn(ErrorCode.GrainInvokeException,
                            "Exception during Grain method call of message: " + message, exc1);
                    }
```

obviously we dont want to re-throw the exception, but it would be nice to have it reported as an Error.   Was this intention?

**Comment by sergeybykov** [comment]
It's an interesting semantics question. We tend to log errors when there's a failure at the framework/runtime level. An exception thrown by application code, while very well may be an error for the app, is a 'normal' case for the framework, meaning that we haven't encountered an exceptional case in *our* code. But I can see how this case can be argued differently.
