### ISSUE TITLE
The MembershipOracle not work with Npgsql 3.2.6

### ISSUE THREAD

**Issue by ijsgaus** [dotnet/orleans#3860]
When run silo MembershipOracle timeout after 5 min. With Npgsql 3.1.9 all work as expected.
Expected behavior: 
Npgsql 3.1.9
Npgsql 3.1.10
Timeout on any Npgsql 3.2.*

**Comment by veikkoeeva** [comment]
@ijsgaus This might help: https://github.com/dotnet/orleans/pull/3163. There's some trouble to track down the XUnit serialization failure in the CI.

**Comment by sergeybykov** [comment]
@ijsgaus Is there something in the logs beside timeouts?

**Comment by PDarkTemplar** [comment]
It is just locks, i have same problem [#1130](https://github.com/npgsql/npgsql/issues/1130) last working version is 3.1.10 
Npgsql remove all configureAwait(false) from async requests somewhere after 3.1.10

**Comment by veikkoeeva** [comment]
@ijsgaus, @PDarkTemplar Which version of the ADO.NET libraries are you running? Since there's a fix [here](https://github.com/dotnet/orleans/blob/918b6c1b8ec8a944047ad767371e41c2e756bd5d/src/AdoNet/Shared/Storage/RelationalStorage.cs#L284) that offloads the providers that have trouble into a new thread. This was there from the beginning for MySQL (it blocks in certain situations, not all) and then after this problem appeared, also Npgsql was offloaded.

**Comment by PDarkTemplar** [comment]
.NET framework 4.6.2
Orleans 1.5.4

**Comment by sergeybykov** [comment]
@veikkoeeva Are you saying that they just need to configure the related config values, and `isSynchronousAdoNetImplementation` will take care of offloading blocking calls?

**Comment by veikkoeeva** [comment]
@sergeybykov No need for configuration, Orleans marks Npgsql currently as blocking automatically regardless of version ([here](https://github.com/dotnet/orleans/blob/918b6c1b8ec8a944047ad767371e41c2e756bd5d/src/AdoNet/Shared/Storage/DbConstantsStore.cs#L45)). Checking https://github.com/dotnet/orleans/pull/3164, the fix went in 1.5.0 and unblocked many PostgreSQL users as far as Gitter conversations were an indicator.

There is another problem (which is a problem I caused in some version by overly eagerly removing awaits) that #3163 might fix, but I'm not sure. Though I have trouble finding out what is the actual problem there. The tests pass locally, but not on the CI (a serialization exception). I kind of a have a hunch (see links towards the end of the issue), albeit I'm afraid I need to wait for the weekend to troubleshoot in more depth.

**Comment by sergeybykov** [comment]
Looks like there isn't anything else *we* can do about the blocking issues with `Npgsql` beyond the mitigation that's already in place. I'll close it then. Feel free to reopen if I missed something.

**Comment by PDarkTemplar** [comment]
Just for heads up, all working fine on orleans 2.0 and .net core
