### ISSUE TITLE
Running Orleans client in .NET 3.5

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [dotnet/orleans#387]
One of the compelling use cases for Orleans is gaming related applications and Unity www.unity3d.com is one of the most popular game engines which people use. Usually the game should communicate with the server using some sort of Web service interface or a custom TCP protocol but for testing in first stages it might be desirable to use actors directly from Unity. 
The problem is that Unity is using Mono 2.8 (.NET 3.5) so TPL doesn't exist there, I would like to see if anyone considered running Orleans clients in .NET 3.5 using packages like this
https://www.nuget.org/packages/TaskParallelLibrary/

I'm willing to put some time and effort on this. 

As mentioned in some places generating automatic Web API code for acotrs is a desired feature which makes thins partly redundant. 

In order to make it more appealing I should point out the obvious that other than things which Halo 4 used Orleans 4, Orleans is very good for implementing most async networked games which dominate the free to play games market these days.

**Comment by gabikliot** [comment]
Orleans is definitely very good for all kind of gaming scenarios, among many other non-gaming related scenarios.

As fort your question, I am a bit confused. What is that exactly you are asking about:
1) Running silo and grain code over .NET 3.5?
2) Running Orleans client only on .NET 3.5, while silo running on 4.5?
3) Generating automatic Web API that your code from Unity over .NET 3.5 will invoke which will communicate remotely with 4.5 based Orleans client and silo?
4) Running Orleans silo and grain code on latest Mono that supports 4.5, hoping that Unity could also be upgraded to work on the latest Mono?

Gabi

**Comment by sergeybykov** [comment]
@ashkan-saeedi-mazdeh For generated Web API frontends, take a look at https://github.com/OrleansContrib/OrleansTemplates/.

Also, wouldn't CoreCLR be a better target now? We already have an issue open for making Orleans CoreCLR compatible.

**Comment by ashkan-saeedi-mazdeh** [comment]
@sergeybykov  Thanks, This web API template fully solves my problem. Even if the code is not optimized for production use, It's good for development and testing and then one could optimize the Web API part. 

Also I did not mean changing directions in terms of supporting .NET 3.5 with a lot of work in Orleans code base, Just wanted to see if it's easily possible or not but now my need is fulfilled thanks to the template. 

@gabikliot  I wanted to be able to easily call my grain code from Unity which uses a .NET 3.5 equivalent version of Mono. It could be done either by being able to have grain clients in .NET 3.5 or having an automatic way of generating the Web API. Now that I see the template for generating the API exist, the problem is considered solved. 

On the possibility of Unity being upgraded to .NET 4.5 or CoreCLR: Unity Technologies said they'll use CoreCLR at least partly but I think it will take a long time for them to come to the feature set of 4.5 for the following reasons. 

1) Historically they are slow at upgrading middleware.
2) The need for async awaik pattern is less available there because Unity has its own coroutines which are all running on the same thread but it is solving many of the problems and their devs commented that async and await are not a priority for Unity's user base.
3) Last but not least, They are in the process of moving much of the user's code from running in an actual .NET runtime to a compiled version. They have their own tool called IL2CPP which compiles the CIL code to C++ and then builds it for the target platform. For now it's only used for WebGL and iOS but they are determined to move more platform to it.

The windows phone and Windows Store builds can use the features of the .NET on the platform but on all other platforms they are still on 3.5 API set and .NET 2's runtime. Supporting 4.5's feature set can become easier thanks to CoreCLR being open source but still they have many reasons to not worry much.

Since at the end the game will communicate using Web API or a binary protocol on TCP, it doesn't matter much for connecting to Orleans in Unity games. 


Just one request, Please make the templates visible in the docs. Later on when I find out the time. I'll start creating a test and will write an article about it so we can add it to the docs and also I'll publish it on my blog in gamasutra.com for the development community to see.

**Comment by gabikliot** [comment]
Sounds great @ashkan-saeedi-mazdeh. The timing was really good for this Web API support. Thanks @nehmebilal for that!
So we can close this issue?

**Comment by ashkan-saeedi-mazdeh** [comment]
@gabikliot  Surely we can close this. Yes the timing was perfect :)

**Comment by gabikliot** [comment]
Thanks.
