### ISSUE TITLE
Custom serializer and Stream

### ISSUE THREAD

**Issue by dazinator** [dotnet/orleans#3874]
I am attempting to write a custom serialiser based on CSLA's serialiser here:

https://github.com/MarimerLLC/csla/blob/0041bc665942aa7e3a4a546adde6e5f8ad715aab/Source/Csla.Shared/Serialization/Mobile/MobileFormatter.cs

Most serialiser implementations support deserializing from a `System.IO.Stream` and Serializing to a given `System.IO.Stream`.

However Orleans `IDeserializationContext` requires deserializing from a `IBinaryTokenStreamReader` which does not derive from stream, as well as Serializing to a `IBinaryTokenStreamWriter` which again doesn't derive from stream.

I read some further comment here that suggests that third party serializer authors change their implementation:
https://github.com/dotnet/orleans/blob/master/src/Orleans.Serialization.Protobuf/ProtobufSerializer.cs#L81

If I want to plug in a third party serialiser that deals purely at the stream level - what is the recommended path for me to do that?

Is there some reason why `IBinaryTokenStreamWriter / Reader` can't derive from Stream, or some StreamAdaptor can be written for them, so that Orleans can gain easier pluggability?

At the moment I am deserializing by reading the data into a seperate memory stream like this:

```csharp
        public object Deserialize(Type expectedType, IDeserializationContext context)
        {
            var size = context.StreamReader.ReadInt();        

            using (var memoryStream = new MemoryStream(size))
            {
                memoryStream.Write(context.StreamReader.ReadBytes(size), 0, size);               
                var deserialised = _cslaSerializarionFormatter.Deserialize(memoryStream);
                return deserialised;
            }     
        }
```

I am assuming this will essentially make a copy of the data? I am worried about performance of that.

Many Thanks

**Comment by ReubenBond** [comment]
@dazinator using MemoryStream is the recommended approach for interfacing with external serializers which support Stream. Other serializers (such as Bond) are able to be adapted to our low-level reader/writer interfaces.

The writer is necessary to ensure that all data written conforms to Orleans' wire format.
It's possible in future that we could offer an easier way to directly write bytes without first serializing them to an array, but it's unlikely that it would directly support Stream (i.e, an adapter might be required).

I hope that helps.

**Comment by dazinator** [comment]
Ok thank you!
