### ISSUE TITLE
Deserialiser issue: Message: System.TypeAccessException 

### ISSUE THREAD

**Issue by dazinator** [dotnet/orleans#3876]
I am using latest beta packages, running on netcoreapp2.0 targeting netstandard2.0

I am having an issue implementing an `IExternalSerializer`.

I am seeing:

> Message: System.TypeAccessException : Named type "Csla.Orleans.Tests.BusinessObjects.Root" is invalid: Type string "Csla.Orleans.Tests.BusinessObjects.Root" cannot be resolved.

Repro is here: ~https://github.com/dotnet/orleans/issues/1536~ https://github.com/dazinator/Csla.Orleans

1. Set `Csla.Orleans.TestLocalHost` project as the Startup project, and run the solution.
2. CD into the `Csla.Orleans.Tests` directory and run `dotnet test` to run the xunit tests in the console - this will create a client and call the server passing an object which is serialized with the custom serialiser.

Alternatively, to debug the client:

1. CD into `Csla.Orleans.TestLocalHost` and run `dotnet run`
2. Build the `Csla.Orleans.Tests` projects, and then right click on the test named "Csla.Orleans.ConfigurerTests.Can_Create` in test explorer window, and click "Debug Selected Test"

On the client side, I can step through my custom serialiser and it seems to be serialising the object fine.

On the server side, I can't see deserialising happening.

I then get the above error :-(

Any pointers greatly appreciated!

**Comment by dazinator** [comment]
Updated to correct link!

**Comment by ReubenBond** [comment]
Even if you implement an external serializer, it might be useful to make sure that those types have serializers generated for them, since the name of the type is being serialized on the wire when you use an `IExternalSerializer` (that's how it knows which serializer to pick).

So in your test program where you call `ConfigureApplicationParts`, make sure to also include the assembly containing those business objects (`Csla.Orleans.Tests.BusinessObjects`)

**Comment by dazinator** [comment]
@ReubenBond  - Thanks. I have added to both client and server:

```
            partManger.AddApplicationPart(typeof(Root).Assembly);
            partManger.AddApplicationPart(typeof(Csla.ApplicationContext).Assembly);

```

`Root` is the object being serialised, and it derives from a base class in a `Csla` assembly, so I have added a part for that assembly also.

I still get the same error though.

Could this be to do with the fact that I am running on `netcoreapp2.0` - perhaps type resolution works differently?

**Comment by dazinator** [comment]
Doh. I think its because my library is actually defined as an exe.. Let me correct that and retry :-)

**Comment by dazinator** [comment]
Nope same error still.
I have also tried changing to net461 - same error.

**Comment by dazinator** [comment]
Could it be because my grain interface uses `object` for some arguments?

```
 public async Task<DataPortalResult> Update(object obj, DataPortalContext context, bool isSync)
```

**Comment by dazinator** [comment]
Ok thanks your hint was helpful.

So in my case, it turned out it wasn't enough just having ` <PackageReference Include="Microsoft.Orleans.OrleansCodeGenerator.Build" Version="2.0.0-beta3" />` in my grain implementation and grain interface projects. This is probably because my grain does not have any strongly typed reference to these business objects that are pass to it. 

I added the above package  it to my Host and to my Client / Test project too - and now it works!
I hadn't realise that orleans still needs to generate serialisation code for these types even when a custom serialiser is used :-)

**Comment by ReubenBond** [comment]
@dazinator do you have the library specified on both the client and the silo?

**Comment by ReubenBond** [comment]
glad to hear you got it sorted :)

**Comment by dazinator** [comment]
@ReubenBond - yep all sorted. I did have the library referenced on both projects, and assembly parts added, but I didn't have the build task - the build task was only on the referenced grain / grain interface projects - and my grains don't reference these objects, as they are passed as `object`! :-)

Thanks again for your help.
