### ISSUE TITLE
Build Time Code Generation on MacOS Failing 2.0.0-beta3

### ISSUE THREAD

**Issue by MikeHardman** [dotnet/orleans#3880]
When attempting to build a 2.0.0 project on MacOS Sierra we get the attached Msbuild error: https://i.imgur.com/ikpdTq1.png

The text if the image won't load is as follows:

The "Orleans.CodeGeneration.GetDotNetHost" task could not be loaded for the assembly '.../Orleans.CodeGeneration.Build.dll'. Could not resolve type with token 0100001e (from typeref, class/assembly System.MarshalByRefObject, System.Runtime, Version=4.2.0.0, Culture=neutral....

It looks like that goes on to cause a ReflectionTypeLoadException in MSBuild.

**Comment by ReubenBond** [comment]
Hi @MikeHardman, build time code generation is not yet supported on *nix - only windows.

However, if you rename this issue to something like "Support Build Time Code Generation on Mac OSX" then we'll track it and fix it (possibly post 2.0)

**Comment by martinothamar** [comment]
Actually I think this is VS Mac only, works using the CLI for me but running/building in VS fails with this error.

**Comment by ReubenBond** [comment]
@martinothamar I might have to find a MacBook so I can debug this

**Comment by martinothamar** [comment]
I could have a look tomorrow, if you havent gotten to it yet

**Comment by ReubenBond** [comment]
I won't have. I'm unsure what would cause the error in the original post

**Comment by martinothamar** [comment]
Using msbuild on Mac OS: `Microsoft (R) Build Engine version 15.4.0.0 (master/f296e67b Wed Oct 25 12:26:03 EDT 2017) for Mono`

`nuget restore OrleansCrossPlatform.sln`
`msbuild OrleansCrossPlatform.sln`
^ Reproduces the issue.

Tried removing the `MarshalByRefObject` base class from `CodeGenerator`, then it throws a different error:

```
"/Users/martinothamar/dev/orleans/OrleansCrossPlatform.sln" (default target) (1) ->
"/Users/martinothamar/dev/orleans/src/Orleans.Core/Orleans.Core.csproj" (default target) (2) ->
(GenerateOrleansCode target) -> 
  /Users/martinothamar/dev/orleans/src/Orleans.CodeGeneration.Build/build/Microsoft.Orleans.OrleansCodeGenerator.Build.targets(54,5): error MSB4018: The "Orleans.CodeGeneration.GetDotNetHost" task failed unexpectedly. [/Users/martinothamar/dev/orleans/src/Orleans.Core/Orleans.Core.csproj]
/Users/martinothamar/dev/orleans/src/Orleans.CodeGeneration.Build/build/Microsoft.Orleans.OrleansCodeGenerator.Build.targets(54,5): error MSB4018: System.TypeLoadException: Could not resolve type with token 01000024 (from typeref, class/assembly System.AppDomain, System.Runtime.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a) [/Users/martinothamar/dev/orleans/src/Orleans.Core/Orleans.Core.csproj]
/Users/martinothamar/dev/orleans/src/Orleans.CodeGeneration.Build/build/Microsoft.Orleans.OrleansCodeGenerator.Build.targets(54,5): error MSB4018:   at Orleans.CodeGeneration.GetDotNetHost.Execute () [0x00001] in <a6026c99e4c742a7a14ce0539e831b66>:0  [/Users/martinothamar/dev/orleans/src/Orleans.Core/Orleans.Core.csproj]
/Users/martinothamar/dev/orleans/src/Orleans.CodeGeneration.Build/build/Microsoft.Orleans.OrleansCodeGenerator.Build.targets(54,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in <76dd0031e0df4aa99d9befb4c4585c69>:0  [/Users/martinothamar/dev/orleans/src/Orleans.Core/Orleans.Core.csproj]
/Users/martinothamar/dev/orleans/src/Orleans.CodeGeneration.Build/build/Microsoft.Orleans.OrleansCodeGenerator.Build.targets(54,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder+<ExecuteInstantiatedTask>d__26.MoveNext () [0x0022d] in <76dd0031e0df4aa99d9befb4c4585c69>:0  [/Users/martinothamar/dev/orleans/src/Orleans.Core/Orleans.Core.csproj]
```

So the task loads but crashes when it tries to interact with AppDomain? I don't see System.Runtime.Extensions installed, does it need to be?
Not sure how to debug this tbh.

**Comment by jamiemitchellconsultants** [comment]
@ReubenBond Do you still need to debug on a mac? I can give you remote access to one from Saturday.

JetBrains Ride compiles my Orleans project on a mac where VS Mac won't. (you can get any Resharper discount you have built up applied to a Ride subscription)

**Comment by ReubenBond** [comment]
@jamiemitchellconsultants I can do it on my linux host, but I haven't found the time yet. It seems to be a Mono issue

**Comment by nh43de** [comment]
We're having the same issue when using AppCenter to build the project

**Comment by ReubenBond** [comment]
@nh43de which runtime is being used to build your project there, are you able to provide some diagnostics?

**Comment by ibondy** [comment]
Having a same issue here on MacBook Pro. Builds fine from a command line, but an error in VS Mac.

**Comment by mo-esmp** [comment]
Same issue for me on VS Mac and JetBrains Rider.

**Comment by hyphappy011** [comment]
Same issue for me on VS for MAC

**Comment by ekalachev** [comment]
The same issue for me(  VS for MAC

**Comment by EliTayrien** [comment]
@ReubenBond I have a repro on my mac box. If you'd like, I'd be happy to host a screenshare where you can drive and see it in action.

**Comment by jsteinich** [comment]
@ReubenBond When do expect the new code generator to be available for testing?

**Comment by ReubenBond** [comment]
@jsteinich I don't have an ETA at the moment, sorry. I would say that we wont have a replacement in the v2.1.0 timeframe, but hopefully it's soon after.

**Comment by mehmetakbulut** [comment]
I have observed the same issue with Rider 2018.1.4 on Ubuntu 16.04. (Orleans.Core.Abstraction 2.0.0 and Orleans.OrleansCodeGenerator.Build 2.0.4)

```
  Microsoft.Orleans.OrleansCodeGenerator.Build.targets(60, 5): [MSB4062] The "Orleans.CodeGeneration.GetDotNetHost" task could not be loaded from the assembly /home/mehmet/.nuget/packages/microsoft.orleans.orleanscodegenerator.build/2.0.4/build/../tasks/netcoreapp2.0/Orleans.CodeGeneration.Build.dll. Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```
```
  Caelex.Interfaces: [MSB4062] The "Orleans.CodeGeneration.GetDotNetHost" task could not be loaded from the assembly /home/mehmet/.nuget/packages/microsoft.orleans.orleanscodegenerator.build/2.0.4/build/../tasks/netcoreapp2.0/Orleans.CodeGeneration.Build.dll. Could not resolve type with token 0100001e (from typeref, class/assembly System.MarshalByRefObject, System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a) Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```

**Comment by brendanmckenzie** [comment]
I came across this issue as well on macOS.  It was only an issue if i ran `dotnet build` from the directory containing the `.sln` file, if I ran `dotnet build` (and `dotnet run`) from the `.csproj` folder is worked as expected.

**Comment by sergeybykov** [comment]
@brendanmckenzie What version is this with. Have you tried using `Microsoft.Orleans.CodeGenerator.MSBuild` package instead of `Microsoft.Orleans.OrleansCodeGenerator.Build`?

**Comment by brendanmckenzie** [comment]
@sergeybykov now that I have it working I'm unable to make it not work. Even after running `dotnet clean` and clearing out my ~/.nuget/packages folder.
