### ISSUE TITLE
Silo to Silo Communication

### ISSUE THREAD

**Issue by larsfjerm** [dotnet/orleans#3888]
Hi, we got a few questions regarding **silo to silo communication**. We have created an implementation using streams (SMS provider), and the communication works, but we are facing a couple of issues with handling of subscriptions.

There are 2 different silos in this example: Silo A - the producer of the streaming events, and Silo B - subscribes to these streams.
Below is a code sample for Silo B which demonstrates the usage with `EventManagerGrain` and `EventGrain`. Here we receive an exception:

> System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Trying to send a message Request S127.0.0.1:22222:254231219-> # 594:  on a silo not from within grain and not from within system target (RuntimeContext is not set to SchedulingContext) RuntimeContext.Current=null TaskScheduler.Current=System.Threading.Tasks.ThreadPoolTaskScheduler

`EventManagerGrain`
```C#
[ImplicitStreamSubscription("EventActivated")]
...

public async Task Init() 
{
  var streamProvider = _clusterClient.GetStreamProvider("SMSProvider");
  _activationStream = streamProvider.GetStream<int>(Guid.Empty, "EventActivated");

  await _activationStream.SubscribeAsync(async (eventId, token) =>
  {
    // GrainFactory throws an exception here (see above)
    await GrainFactory.GetGrain<IEventGrain>(eventId).SubscribeStreams();
  });
}
```

`EventGrain`
```C#
[ImplicitStreamSubscription("ActionAdded")]
[ImplicitStreamSubscription("ActionRemoved")]
...

public async Task SubscribeStreams()
{
  var provider = _clusterClient.GetStreamProvider("SMSProvider");
  _actionAddedStream = provider.GetStream<ActionAdded>(this.GetPrimaryKey(), "ActionAdded");
  _actionRemovedStream = provider.GetStream<ActionRemoved>(this.GetPrimaryKey(), "ActionRemoved");

  await _actionAddedStream.SubscribeAsync((actionAdded, token) => Handle(actionAdded)));
  await _actionRemovedStream.SubscribeAsync((actionRemoved, token) => Handle(actionRemoved));
}
```
___

Another solution that has been considered is a central `DistributorService` that connects to all the silo clusters and receives messages (using a pub/sub framework), and distribute them to their corresponding silo using `ClusterClient`.
![Other solution](https://www.lucidchart.com/publicSegments/view/62f6062b-83a9-438f-83f8-925be3880d62/image.png)

We couldn't find any documentation describing approaches for silo-to-silo communication. Issue #1670 suggest communication over HTTP, but will this be a viable solution? Some guidelines for best practices on this would be much appreciated.

**Comment by sergeybykov** [comment]
I'm trying to wrap my head around these questions, and I get thrown off track almost immediately by the usage of silos as key entities in the application logic:
>There are 2 different silos in this example: Silo A - the producer of the streaming events, and Silo B - subscribes to these streams.

In general, silos are just mostly invisible containers for grains to live in, and they usually do not surface to the application code.

I think it would probably help to start top down from the high level description of the purpose of this application. What is the origin of these events? Are there external actions that cause them or they are generated within the cluster? Without such high level understanding it is hard for me to evaluate the solution with multiple clusters, too.

When it comes to cluster-to-cluster communication, each cluster (grains in it) can be reached via a `IClusterClient` configured to communicate with it, from an external service or from another cluster. The HTTP frontend layer in front of `IClusterClient` is strongly recommended for connections from untrusted networks, such as the Internet. Often times, it's also a good idea to isolate clusters with HTTP frontends even on trusted networks for better decoupling and easier maintainability of different clusters that are usually a form of microservices.

**Comment by larsfjerm** [comment]
Thanks for the input, I will try to clarify:

>What is the origin of these events? Are there external actions that cause them or they are generated within the cluster?

Events are coming from an external data feed which `Cluster A` receives and store them in separate grains. Each event can have a set of actions added/removed to them - this will also be received outside of this cluster. 

The general idea is that `Cluster A` works like a data storage cluster where data is coming in and stored. `B` and `C` clusters can use `A` to retrieve the current state of a stored event (this is accomplished by direct grain calls to `A` using `IClusterClient`).
`A` also streams messages for different kind of events (1 stream per event grain), this is for letting `B` or `C` _react_ on specific kind of actions that occurs. 

An Event is a core part of the whole system - `A` will stream out an `EventActivated` message when a new event is registered. In the first post's example there is an `EventManagerGrain` in `B` that is used for activating new grains of type `EventGrain` and subscribe to streams (action messages) that `A` is producing. 

There are currently 5 different clusters planned for this system. They will have different tasks for calculating/producing and provide data. We also thought about placing all the grains and logic into the same cluster/silohost for quick and easy access to the whole system, but then it could turn into a lot of grains with no separation of concerns.
___
Are we on a wrong track here? I will try to create a flow chart for visualizing a bit more, but I hope the big picture is a bit clearer.

**Comment by sergeybykov** [comment]
Thanks. It is more clear now.

>The general idea is that Cluster A works like a data storage cluster where data is coming in and stored. B and C clusters can use A to retrieve the current state of a stored event (this is accomplished by direct grain calls to A using IClusterClient).

This should be pretty straightforward.

>A also streams messages for different kind of events (1 stream per event grain), this is for letting B or C react on specific kind of actions that occurs.

Are you planning to use persistent queues for that?

>In the first post's example there is an EventManagerGrain in B that is used for activating new grains of type EventGrain and subscribe to streams (action messages) that A is producing.

So `EventManagerGrain` will be subscribed to the 'metadata' stream, and will make `EventGrain`s subscribe to the data streams announced on the 'meadata' stream? This should work, so long as various potential failure cases are taken care of.

>There are currently 5 different clusters planned for this system. They will have different tasks for calculating/producing and provide data. We also thought about placing all the grains and logic into the same cluster/silohost for quick and easy access to the whole system, but then it could turn into a lot of grains with no separation of concerns.

What cluster sizes do you envision here? Is efficiency a concern? An architecture with 5 different clusters will obviously use resources less efficiently than a single cluster. But for large enough clusters the degree of inefficiency will be less. Heterogeneous silos allow for *some* separation of concerns, but not as robust as separate clusters.

>Are we on a wrong track here? 

I don't think so. At least, I don't see a major problem here.

**Comment by martinothamar** [comment]
One problem we've run into is recieving events on a stream through a cluster client. Seems like the task (OnNextAsync) is run on the wrong TaskScheduler. I guess something like [this](https://github.com/dotnet/orleans/issues/321#issuecomment-92404515) could be done to get the right context but that seems hacky and unsafe?

**Comment by sergeybykov** [comment]
>One problem we've run into is recieving events on a stream through a cluster client.

Do you mean you had a grain subscribed to a stream from another cluster via `IClusterClient`?

**Comment by martinothamar** [comment]
Yes, so I'm guessing usage from grains isn't really intended for `IClusterClient` at all. In that case we'll have to step out of the Orleans-world for arranging pubsub? Either that or making sure all the grains run in the same cluster? Right now we have 5 different solutions. If we had included all the grains in the same solution/silohost-thing we could avoid clients and everything would work as expected, but the tradeoff is that we end up with a monolith, and we wouldn't be able to deploy parts separately as we can now when it's split up. The alternative I assume is creating frontends for every solution and handle pubsub through some other tech.

**Comment by larsfjerm** [comment]
>Are you planning to use persistent queues for that?

I think persistent streams solved most of our issues here. Instead of `_clusterClient.GetStreamProvider("SMSProvider");` - use a persistent stream provider without the cluster client: `GetStreamProvider("PersistentStreamProvider")`.

Closing for now - thanks Sergey!

**Comment by sergeybykov** [comment]
>Yes, so I'm guessing usage from grains isn't really intended for IClusterClient at all.

It is intended for grains as well, for cross-cluster grain calls. However, I don't think we ever considered or tested it for SMS streams. I'm almost sure that won't work today.
