### ISSUE TITLE
Configure activation GC per type via attribute

### ISSUE THREAD

**Issue by yevhen** [dotnet/orleans#3892]
According to docs activation GC could be configured on per-type  basis by using xml config:

```xml
 <GrainType Type="MyGrainAssembly.DoNotDeactivateMeOften">
        <Deactivation AgeLimit="24hr"/>
 </GrainType>
```

It would be great if that could be controlled via attribute, like `[DeactivationAgeLimit(Hours = 24, Minutes=0)]` without resorting to xml, which is considered legacy at the moment.

**Comment by sergeybykov** [comment]
We already support programmatic configuration of activation GC (via `GlobalConfiguration.Application.SetCollectionAgeLimit`). Like the xml option that is being deprecated, it allows to set those values without recompiling the app code.

Do you see much value in adding a static option that would require recompilation for a change. I can see a potential minor discoverability benefit, but not much.

**Comment by yevhen** [comment]
@sergeybykov I'm not sure what you mean with "without recompiling the app code".  Host's code still requires re-compilation and re-deployment, right?

The point is to have all type-specific configuration to be closer to the type. With `GlobalConfiguration.Application.SetCollectionAgeLimit` type-specific configuration is scattered across code. I view this attribute much the same as `PlacementAttribute`. 

Either we drop all attributes altogether and configure everything in one place (ie cluster config), or make a clear distinction between global (type-agnostic) configuration and type-specific settings. Using cluster config for former, and attributes for latter. It's about consistency.

**Comment by sergeybykov** [comment]
>@sergeybykov I'm not sure what you mean with "without recompiling the app code". Host's code still requires re-compilation and re-deployment, right?

Not necessarily. For example, host code can (and in many cases does) load config values from a configuration store at run time. So one can update config values in the store and redeploy/restart same bits of application code without recompiling it (and retesting) it.

I'm not pushing back on the attribute idea at all. I think it has some benefits, like you mentioned. I just wasn't sure if you were aware of the already existing programmatic config option.

**Comment by yevhen** [comment]
@sergeybykov no, I didn't know. Relying too much on docs which only list xml option )) http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Activation-Garbage-Collection.html

**Comment by sergeybykov** [comment]
I submitted #3912 to update the doc.

**Comment by sergeybykov** [comment]
#3912 has been merged.
