### ISSUE TITLE
how to use IClusterClient 

### ISSUE THREAD

**Issue by sundong1982** [dotnet/orleans#3903]
1.Create a static IClusterClient, all use it. ex: static IClusterClient clusterClient = clusterClient.Connect().Wait();

2.or each client's method build a instance (IClusterClient clusterClient=IClientBuilder.Build() cost 0.5second),
then clusterClient.Connect()-> todo->clusterClient.Dispose(),  
next time IClusterClient clusterClient=IClientBuilder.Build()  clusterClient.Connect()-> todo->clusterClient.Dispose()

Which one? or other?

**Comment by ReubenBond** [comment]
@sundong1982 **1**: share a single instance of the client.
Build & Connect the client when the app starts and stop it when the application finishes.

**Comment by sundong1982** [comment]
thank u :)

**Comment by sundong1982** [comment]
@ReubenBond thx:)
