### ISSUE TITLE
Does orleans support permission verification, or is there any way to achieve?

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#3905]
Does orleans support permission verification, or is there any way to achieve?

**Comment by sergeybykov** [comment]
Orleans does not have any built-in permission verification. At the system level, it expects clients (frontends) to be trusted. 

At the call level, application can implement an implicit verification of invocations by installing [interceptors/call filters](http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Interceptors.html).

**Comment by aqa510415008** [comment]
Is there any way to use JWT for built-in permission verification, does Orleans have an AOP interceptor?

**Comment by aqa510415008** [comment]
If not, then only JWT use DTO sent over the use of succession to verify authority? Is there any other way?

**Comment by aqa510415008** [comment]
@sergeybykov

**Comment by sergeybykov** [comment]
>Is there any way to use JWT for built-in permission verification

Orleans does not have any built-in permission verification. 
>does Orleans have an AOP interceptor?

Orleans supports [interceptors/call filters](http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Interceptors.html).

>If not, then only JWT use DTO sent over the use of succession to verify authority? Is there any other way?

You can send extra call metadata via [Request Context](http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Request-Context.html?q=request).

**Comment by aqa510415008** [comment]
Thanks for giving me a way of thinking
