### ISSUE TITLE
[Proposal] New codegen hint

### ISSUE THREAD

**Issue by yevhen** [dotnet/orleans#3910]
The functional way (style) for doing communication is via messages, which in C# are usually implemented by classes. Currently, Orleans codegen can only generate serializers for class if it's marked with `Serializable` attribute, which means that each and every message class need to be marked with it. That creates a lot of unnecessary noise and make definitions more verbose.

It would be great to have new hint for codegen (ie done via config) to generate serializers for all types which could be assigned from specified type. For example, Orleankka provides 2 base interfaces `Message` and `Result` (for requests and responses respectively) which are used for strongly typed actors (`ActorMessage<TActor>``, ActorMessage<TActor, TResult>`). Having this ability will save 1 line of code per each message definition and will make them more compact.

**Comment by ReubenBond** [comment]
How should the configuration be implemented? Supposing that Orleankka consumers tend to use F# rather than C#, would they typically to use runtime code generation? In that case we could pass an option in at runtime. Would that be sufficient?

Another option (not mutually exclusive) is to accept properties via MSBuild similarly to our property for setting codegen log level

**Comment by yevhen** [comment]
Ye, it’s only for runtime codegen and it’s mainly for C# users, since DUs in F# are already generate classes marked with Serializable. 

I was thinking about configuration option but assembly-level attribute similar to KnownType will be good solution too and will enable this option for build-time codegeneration as well

**Comment by sergeybykov** [comment]
@ReubenBond Do you think we should add this in 2.0.0?

**Comment by ReubenBond** [comment]
I think we can consider this for 2.0.0-final but skip it for RC

**Comment by ReubenBond** [comment]
@yevhen how about if we had a type-level attribute like `[KnownBaseType]` which can be applied to `Message` and `Result` such that when we check if a type is serializable, we also check for that attribute on all base types (interfaces and classes)

**Comment by yevhen** [comment]
@ReubenBond good option!

**Comment by ReubenBond** [comment]
@yevhen I've opened #4133 with an implementation. Let me know what you think.
