### ISSUE TITLE
Odd virtual methods in Grain class

### ISSUE THREAD

**Issue by yevhen** [dotnet/orleans#3911]
Why following methods are virtual:
- RegisterTimer
- RegisterOrUpdateReminder
- UnregisterReminder
- GetReminder
- GetReminders
- GetStreamProvider
- DeactivateOnIdle
- DelayDeactivation
- GetLogger
- Participate

Those are considered to be called by consumers not by Orleans (like `OnActivateAsync()`) so overriding them make little or no sense. In fact, all these methods do nothing but merely delegate to `IGrainRuntime`. IMHO, it might be better to seal them to not confuse developers.

If this was done for unit-testing (mocking) purposes, this now seems unnecessary as all mocking could be done against IGrainRuntime.XXX.

**Comment by sergeybykov** [comment]
I think the suggestion is totally valid. However, we don't know how many people that opted to override these methods we'll break. On the one hand, 2.0.0 is a good release for breaking changes.

**Comment by lmagyar** [comment]
@sergeybykov Isn't there a very similar problem with `JournaledGrain` virtual methods?
* RaiseEvent
* RaiseEvents
* RaiseConditionalEvent
* RaiseConditionalEvents

Meanwhile ConfirmEvents and RefreshNow are non-virtual.

**Comment by sebastianburckhardt** [comment]
Yes, those should not be virtual. 
This is already fixed in #3773.
