### ISSUE TITLE
Remove Orleans.Core.Abstractions Newtonsoft.Json Dependency

### ISSUE THREAD

**Issue by jsteinich** [dotnet/orleans#3913]
Would it be possible to remove the Newtonsoft.Json dependency from Orleans.Core.Abstractions?
It appears to only be used here: https://github.com/dotnet/orleans/blob/f98bd17fa980160c348ff75a4e819d39ff740eb1/src/Orleans.Core.Abstractions/IDs/UniqueIdentifier.cs#L10

I am sharing some classes that use Orleans attributes with a Unity project. I am able to add the dependency in Unity, but it causes an error message on startup. It doesn't actually break anything, so this isn't a high priority, but it would be nice to clean it up.

**Comment by sergeybykov** [comment]
That attribute is there, so that `UniqueIdentifier` and its subclasses can be correctly JSON-serialized. I'm not sure how we can achieve that without referencing Newtonsoft.Json.

**Comment by jsteinich** [comment]
Would it be possible to use `System.Runtime.Serialization.DataMemberAttribute`? The documentation says that it looks for "Standard .Net Serialization Attributes": https://www.newtonsoft.com/json/help/html/SerializationAttributes.htm

**Comment by sergeybykov** [comment]
Good question. I wonder what @ReubenBond thinks.

**Comment by ReubenBond** [comment]
We can use `[DataMemberAttribute]` instead and hopefully drop the dependency. Are you able to submit a PR, @jsteinich?

**Comment by sergeybykov** [comment]
Resolved via #3926.
