### ISSUE TITLE
Connection failed after restart client/silo in docker-deployment

### ISSUE THREAD

**Issue by csyszf** [dotnet/orleans#3919]
Error log:
> Unhandled Exception: System.AggregateException: One or more errors occurred. (The target silo became unavailable for message: Request *cli/b1d88196@02695dbc->S10.0.2.6:10400:0???/00000011@S00000011 #2: global::Orleans.Runtime.IClusterTypeManager:GetClusterTypeCodeMap(). Target History is: <S10.0.2.6:10400:0:???/00000011:@S00000011>. See https://aka.ms/orleans-troubleshooting for troubleshooting help.) ---> Orleans.Runtime.SiloUnavailableException: The target silo became unavailable for message: Request *cli/b1d88196@02695dbc->S10.0.2.6:10400:0???/00000011@S00000011 #2: global::Orleans.Runtime.IClusterTypeManager:GetClusterTypeCodeMap(). Target History is: <S10.0.2.6:10400:0:???/00000011:@S00000011>. See https://aka.ms/orleans-troubleshooting for troubleshooting help.

It happens sometimes when:
1. start silo, then start client
2. silos are running, and then restart clients.
and if those errors occurred, **clients cannot connect to silos unless i restart silos.**

And:
If clients are running, then restart silos
clients will mark silo dead, and will not connect silo again
it's a faulty error because in [docker-deployment](https://github.com/dotnet/orleans/blob/master/Samples/Docker-Simple/Client/Program.cs), there's only one gateway endpoint.

**Comment by benjaminpetit** [comment]
> It happens sometimes when:
> start silo, then start client
> silos are running, and then restart clients.
> and if those errors occurred, clients cannot connect to silos unless i restart silos.

Not sure to understand this one, but for

> If clients are running, then restart silos
> clients will mark silo dead, and will not connect silo again
> it's a faulty error because in docker-deployment, there's only one gateway endpoint.

When the new silo will be available, your client should detect it (client check every 60s the membership table I believe) and should reconnect to it. Is it not the case?
