### ISSUE TITLE
Sending an impl instead of the interface as parameter can fail silently

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [dotnet/orleans#3920]
I have a `IUNetMessageProcessor` interface and an implementation type named `UNetMessageProcessor` , I have a method in another grain which takes as argument `IUNetMessageProcessor` and was sending myself to it from a UNetMessageProcessor grain by using `AsReference<IUNetMesageProcessor>(this)` but by mistake i instead wrote `AsReference<UNetMessageProcessor>(this)` 

What happened was that I was getting InvalidOperationException in Orleans.dl-l>mscorlib.dll which was being swallowed and i only was getting a log message. 

This can be improved in two ways. More important is to throw it and let it crash (maybe if it doesn't break backward compatibility) and another is writing a Roslyn analyzer which checks you are only passing interfaces if there is no elegant way of preventing it altogether 

Today I got reminded of the type errors which we sometimes got in Erlang and actually felt great about Orleans after 3 hours of debugging

**Comment by ReubenBond** [comment]
@ashkan-saeedi-mazdeh could you paste the stack of the log message?

**Comment by sergeybykov** [comment]
Seems like `AsReference` should throw if something other than a grain interface is passed as a type argument.

**Comment by ashkan-saeedi-mazdeh** [comment]
@sergeybykov I've sent an implementation of a grain interface but maybe that throw. 

@ReubenBond  this is the log
```
*** here i pass the implementation class instead of the interface to AsReference***
*** here i pass the implementation class instead of the interface to AsReference***
Exception thrown: 'System.InvalidOperationException' in Orleans.dll
Exception thrown: 'System.InvalidOperationException' in Orleans.dll
Exception thrown: 'System.InvalidOperationException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in mscorlib.dll

```

Seeing the issue here i realized and fixed it and don't know if that trow or not but can check it if needed

**Comment by ashkan-saeedi-mazdeh** [comment]
Yes it throws, thanks Sergey


The stack trace is

```
		StackTrace	"   at Orleans.Runtime.TypeMetadataCache.GetGrainReferenceType(Type interfaceType)\r\n   at Orleans.GrainFactory.MakeCaster(Type interfaceType)\r\n   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)\r\n   at Orleans.GrainFactory.Cast(IAddressable grain, Type interfaceType)\r\n   at Orleans.GrainFactory.Cast[TGrainInterface](IAddressable grain)\r\n   at Collection.UNetMessageProcessor.<ProcessFindMatchRequest>d__57.MoveNext() in C:\\Users\\Ashkan\\Documents\\Projects\\apadana\\Apadana\\SiloHost\\Collection\\UNetMessageProcessor.cs:line 1089"	string

```

The exception is 

```
-		ex	{"Cannot find generated GrainReference class for interface 'Collection.UNetMessageProcessor'"}	System.Exception {System.InvalidOperationException}

```

Again the grain class and interface relation is like this

``` csharp
class UNetMessageProcessor : Grain, IUNetMessageProcessor
```

So it throws actually, that was my bad but still i guess the analyzer would be good.

**Comment by sergeybykov** [comment]
>So it throws actually, that was my bad but still i guess the analyzer would be good.

Good. Let's close this one then and open a new clean issue for the analyzer idea.
