### ISSUE TITLE
When released 2.0 stable version?

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#3922]
When released 2.0 stable version?

**Comment by ReubenBond** [comment]
@aqa510415008 we're close to preparing the 2.0.0-rc1 release. We hope to have the 2.0.0-final release not too long afterwards.

**Comment by aqa510415008** [comment]
Probably these two days can be released, beta3 version seems to have many problems, download instance analysis found that the application is not beta3 version.

**Comment by ReubenBond** [comment]
@aqa510415008 I don't understand: which problems are you having?

**Comment by aqa510415008** [comment]
The sample HelloWorld.NetCore example project into a Beta-3 version of the project, it reported the following error：
None of the assemblies added to ApplicationPartManager contain generated code. Ensure that code generation has been executed for grain interface and class assemblies.

**Comment by aqa510415008** [comment]
I did not change any code, only changed the reference version, I swear

**Comment by aqa510415008** [comment]
@ReubenBond

**Comment by ReubenBond** [comment]
@aqa510415008 could you upload your modified projects in a zip file?

**Comment by aqa510415008** [comment]
@ReubenBond That I deleted, so 2.0 after the official version of our trial, it seems 2.0 document is not perfect?

**Comment by ReubenBond** [comment]
If you have trouble upgrading to 2.0, feel free to contact me in [Gitter](https://gitter.im/dotnet/orleans) @aqa510415008
