### ISSUE TITLE
I would like to ask, each request to call Grain can be viewed in EventSourcing?

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#3924]

**Comment by sergeybykov** [comment]
It is the responsibility of a grain to turn incoming calls into an Event Sourcing style stream of updates to its state. There is no built-in mechanism in Orleans that would do that.

**Comment by aqa510415008** [comment]
@seralexeev Will Orleans.EventSourcing what is the use of this?

**Comment by aqa510415008** [comment]
@sergeybykov
Sorry, I am a beginner, effective problem is very elementary, please excuse me.
The call between Grain, the client's request can be stored as a log?

**Comment by sergeybykov** [comment]
>Will Orleans.EventSourcing what is the use of this?

Orleans.EventSourcing is *a* way to implement event sourcing of grain state. But there are other ways to do that in the application logic if needed.

>Sorry, I am a beginner, effective problem is very elementary, please excuse me.

No need to apologize at all.

>The call between Grain, the client's request can be stored as a log?

It can be stored as an event in a log, but that's the responsibility of the application code. Orleans doesn't do anything for that by itself.

**Comment by aqa510415008** [comment]
@sergeybykov Are there any specific examples of the lolo.eventsourcing?

**Comment by sergeybykov** [comment]
Have you looked at dotnet.github.io/orleans/Documentation/Event-Sourcing/Overview.html?

**Comment by aqa510415008** [comment]
@sergeybykov Thank you, a lot of benefits
