### ISSUE TITLE
Error starting orleans beta 3 silo in .net core stateless service fabric

### ISSUE THREAD

**Issue by jamiemitchellconsultants** [dotnet/orleans#3925]
I have a trivial set of .net core 2.0 orleans beta 3 interfaces/implementations . A local host silo works fine. When I use the .net core preview azure service fabric tools to create a stateless silo I get an unhandled exception error when starting.

https://gist.github.com/jamiemitchellconsultants/fa498a292f7342ee4f61d6b126848010

**Comment by ReubenBond** [comment]
@jamiemitchellconsultants this ought to be fixed in 2.0-rc2: our Service Fabric integration now supports .NET Standard/Core
