### ISSUE TITLE
TestMultiClusterConf_3_3 fails intermittently

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#3929]
TestMultiClusterConf_3_3 has been failing intermittently for some time now. I submitted #3928 to skip it for now. This issue is to remember to investigate it.

https://orleans.visualstudio.com/Orleans/Orleans%20Team/_TestManagement/Runs#_a=resultSummary&runId=3414&resultId=101084
>Assert.Equal() Failure\r\n ↓ (pos 10)\r\nExpected: 21100,21101\r\nActual: 21100,21102\r\n ↑ (pos 10)

https://orleans.visualstudio.com/Orleans/Orleans%20Team/_TestManagement/Runs?_a=resultSummary&runId=3397&resultId=101169
>Assert.Equal() Failure\r\n ↓ (pos 10)\r\nExpected: 21100,21101\r\nActual: 21100,21102\r\n ↑ (pos 10)

https://orleans.visualstudio.com/Orleans/Orleans%20Team/_TestManagement/Runs#_a=resultSummary&runId=3341&resultId=101222
>Assert.Equal() Failure\r\n ↓ (pos 10)\r\nExpected: 21200,21201\r\nActual: 21200,21202\r\n ↑ (pos 10)

**Comment by sebastianburckhardt** [comment]
Yes, I am investigating. I am seeing failures in other tests as well.

**Comment by sebastianburckhardt** [comment]
I have a fix for this test (see PR #3970)

It turned out to be a simple oversight in the test construction - need to sort the silo addresses in the test so they match the order used by the multi-cluster gateway selection.

I have found some other issues in other tests but will track them separately.

**Comment by sergeybykov** [comment]
The test is still failing intermittently but quite often.

**Comment by rafikiassumani-msft** [comment]
@benjaminpetit I am closing this issue as I could not find the test that is failing.
