### ISSUE TITLE
Consult a cluster configuration problem.

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#3930]
Whether the Orleans can be assembled into a cluster between different systems.
Example:
A system (user system) : obtain user information function, and configure gateway address: 123.135.13.13:4545.
B system (message system) : send message function, configure gateway address and A system. Is it feasible?
If the client can call 123.135.13.13:4545 gateway address, it can obtain the user of A system and send information to system B.
Because I didn't succeed in the experiment.

**Comment by sergeybykov** [comment]
The distinction between A and B isn't 100% clear to me.

If that's just a separation of the externally visible APIs, then you could expose A APIs via A HTTP frontend endpoints and B APIs via B frontend endpoints while having both sets of frontends talk to a single homogenous cluster with grains handing both A and B requests.

You could then extend this approach further to isolate A grains from B grains if needed via [heterogeneous silos](http://dotnet.github.io/orleans/Documentation/Deployment-and-Operations/Heterogeneous-Silos.html).

**Comment by aqa510415008** [comment]
This is the way heterogeneous silos is. Is there a specific implementation instance?

**Comment by aqa510415008** [comment]
@sergeybykov This is the way heterogeneous silos is. Is there a specific implementation instance?

**Comment by sergeybykov** [comment]
I'm afraid we only have https://github.com/dotnet/orleans/blob/master/test/Tester/HeterogeneousSilosTests/HeterogeneousTests.cs besides the documentation page.

**Comment by aqa510415008** [comment]
@sergeybykov Do you have some examples in the 2.0 update? For our beginners, a lot of concepts don't understand, if there are examples, that's even better?

**Comment by sergeybykov** [comment]
Do you mean examples of 2.0 in general or heterogeneous silo in 2.0?

Heterogeneous silo don't require any special configuration, and should just work, in 2.0 or 1.5.

For 2.0 in general, we have some preliminary documentation under http://dotnet.github.io/orleans/Documentation/2.0/New.html. and a basic sample https://github.com/dotnet/orleans/tree/master/Samples/HelloWorld.NetCore for now.

**Comment by aqa510415008** [comment]
Document is not detailed enough, the future will have a corresponding example?

**Comment by aqa510415008** [comment]
@sergeybykov Document is not detailed enough, the future will have a corresponding example?

**Comment by sergeybykov** [comment]
What kind of sample are you looking for? Of heterogeneous silos?

**Comment by aqa510415008** [comment]
@sergeybykov Yes

**Comment by sergeybykov** [comment]
I'm not sure what kind of sample would help here. It's pretty straightforward.

If you have grain classes grouped into assemblies A, B, and C, you can deploy them to different silos in the cluster in any combination: only A, only B, B and C, and so forth. You just need grain *interfaces* assemblies for grain classes in A, B, and C to be deployed to *every* silo in the cluster.

**Comment by aqa510415008** [comment]
@sergeybykov When the gateway address is not configured to be the same?

**Comment by sergeybykov** [comment]
Everything is configured the same way, except instead of A, B, and C grain assemblies being on every silo in the cluster, like in a typical deployment, you can put any combination of A, B, and C on each of the silos.

In most cases you'll probably have some silos with only A, some with only B, and some with only C. But other than that, configuration is the same on all silos.
