### ISSUE TITLE
Orleans Telemetry API 2.0

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#3934]
We are close to get 2.0 released and a lot of things changes because of it.

Telemetry was no different. The Log/Tracing APIs which were originally moved to a telemetry provider (i.e. implementations of `ITraceTelemetryConsumer`) were now moved/deprecated on 2.0 in favor of logging plugins based on the well know `Microsoft.Extensions.Logging` (aka MEL).

This issue will be used to track the discussion and work towards the revamped Telemetry APIs in Orleans post-2.0 release.

I'm closing #992 as it is huge and reflect the old design.

More details about the new design proposal soon.

**Comment by shlomiw** [comment]
@galvesribeiro 
Can you please update what's the status of this? can I use custom telemetry consumer (i.e. via `IEventTelemetryConsumer`), or was it moved to `Microsoft.Extensions.Logging`?

**Comment by galvesribeiro** [comment]
@shlomiw You can use all telemetry consumers except the Trace one which is now handled by `MEL`.
