### ISSUE TITLE
Allow overriding mechanism used to terminate silos during catastrophic failure

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#3940]
Currently `ILoggerExtensions.Fail` is used to abruptly terminate the process via `Environment.FailFast()` in these situations:
1. A silo is declared dead by `MembershipOracle`
2. A worker thread (`AsynchAgent`) crashes and its `OnFault` behavior is `FaultBehavior.CrashOnFault`
3. (test only) A particular assertion fails in `LocalGrainDirectory`

In testing and multi-silo scenarios, this approach may be undesirable.

Currently we have an override called `ClusterConfiguration.IsRunningAsUnitTest` which will avoid calling `Environment.FailFast` in the first case above.

We should consider a consistent method for allowing users to intercept/override behavior during a catastrophic failure.

Note that doing so increases the risk of zombie processes or misbehaving silos in the event that the mechanism fails to terminate correctly.

**Comment by dmitrig89** [comment]
+1 On this.
Running on a production environment, I've had this happen on a working Silo and it resulted in inconsistent data. We need to allow some time for grains to deactivate and for the process to shut down gracefully, even at the cost of the Silo being dead for longer.
