### ISSUE TITLE
2.0 version can be configured to optimize it?

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#3944]
![image](https://user-images.githubusercontent.com/28291464/35657078-94d68246-0735-11e8-9cfa-25a06ec968af.png)

**Comment by sergeybykov** [comment]
I'm sorry, I don't understand the question. To optimize what? `ConfigureApplicationParts` tells the runtime what application assemblies to load and scan for types, such as grain classes/interfaces, serializers, etc.

**Comment by aqa510415008** [comment]
@sergeybykov  You do not need to specify the corresponding grain classes / interfaces, let the system to find their own, so that the configuration will be much easier

**Comment by sergeybykov** [comment]
Prior to 2.0.0, Orleans Runtime would scan all assemblies in the folder to find grain classes/interfaces, serializers, etc., and that sometimes caused some undesirable side effects and slowed silo startup. In 2.0.0, `SiloHostBuilder` needs to be explicitly told what *assemblies* to scan.

**Comment by aqa510415008** [comment]
Oh, so ah, 2.0 official version about how long it is released, we intend to use Orleans. Now we use Web Api

**Comment by aqa510415008** [comment]
@sergeybykov Oh, so ah, 2.0 official version about how long it is released, we intend to use Orleans. Now we use Web Api

**Comment by sergeybykov** [comment]
We are trying to finish a Release Candidate in a matter of, hopefully, days. Then we plan to have it out for a few weeks to address any last minute feedback. But you should be able to develop against Beta3 now, and especially against the upcoming RC.

**Comment by aqa510415008** [comment]
@sergeybykov Yes, I am learning and customizing something
