### ISSUE TITLE
Configuration Work - TestingHost

### ISSUE THREAD

**Issue by jason-bragg** [dotnet/orleans#3951]
Remove use of legacy configuration from Orleans.TestingHost, introducing a Orleans.TestingHost.Legacy if necessary.

**Comment by xiazen** [comment]
finished in #4081

**Comment by xiazen** [comment]
we haven't talked about what do we want to do with Orleans.TestingHost.Legacy package. Do we release that package, or just keep it internal?

**Comment by sergeybykov** [comment]
I don't think we want to encourage usage of `Orleans.TestingHost.Legacy` by releasing a package with it. I hope we can keep for internal testing of the legacy configuration only.

**Comment by xiazen** [comment]
there's opinion in both sides. let's keep this issue and talk about I t

**Comment by xiazen** [comment]
I'm with the side of keeping it internal. @jason-bragg here since I remember he has a different opinion. And also @benjaminpetit @ReubenBond in case they have opinion

**Comment by jason-bragg** [comment]
I'm ok with keeping it internal, unless the community rebels.  I mainly wanted to make sure this was an informed choice, not an oversight.

**Comment by ReubenBond** [comment]
I'm also ok with keeping it internal. We can always publish it later on if we wish

**Comment by sergeybykov** [comment]
Closing this then.
