### ISSUE TITLE
Configuration Work - Extension libraries

### ISSUE THREAD

**Issue by jason-bragg** [dotnet/orleans#3952]
We need to remove references to legacy configuration classes (and references to legacy packages) from extension libraries and their test assemblies.  This work can (should) be subdivided into per extension library change sets.

**Comment by jason-bragg** [comment]
Remaining packages which rely on legacy systems.

Orleans.Hosting.AzureCloudServices - I think the plan is to keep this as is, and only support azuresilo on legacy systems.  Do we need to add any helper logic to run the new patterns on azure?

Orleans.Hosting.ServiceFabric - Needs port the endpoint setup.  @ReubenBond?

Orleans.PowerShell - Relies on old xml.  We'll need to vet that we can read from file using IConfiguration and wire this up read from external config for this to be ported.  Suggest pushing to post 2.0 unless there is demand.

Orleans.TelemetryConsumers.AI - Need to setup in telemetry options, and add it's own options for it's settings.
Orleans.TelemetryConsumers.Counters - Just needs to setup in telemetry options - trivial.
Orleans.TelemetryConsumers.NewRelic- Need to setup in telemetry options, and add it's own options for it's settings.

OrleansManager - Relies on old xml.  We'll need to vet that we can read from file using IConfiguration and wire this up read from external config for this to be ported.  What is this used for?  What is the priority of this?

**Comment by sergeybykov** [comment]
I agree on Orleans.Hosting.AzureCloudServices.
Orleans.Hosting.ServiceFabric is tracked by #4109.
@xiazen will look into the telemetry packages.
PowerShell and OrleansManager I think can wait post 2.0. Contributions are welcome.

**Comment by sergeybykov** [comment]
Everything but `Orleans.PowerShell` and `OrleansManager` was addressed. Moving to Backlog.
