### ISSUE TITLE
Configuration Work - assembly loaded types

### ISSUE THREAD

**Issue by jason-bragg** [dotnet/orleans#3953]
Many patterns carried over from the legacy configuration use strings or enums to identify component implementations.  These settings trigger assembly loads of pre defined assemblies and creation of types assumed to be in those assemblies.  This pattern is error prone and poorly maintainable.

In new systems this is done by requiring component implementations to be registered in the container by name and configured values are used by named service resolution, but no consensus has been built around this pattern.

We need to design a better pattern and replace the legacy pattern.

**Comment by ReubenBond** [comment]
I believe that we do have consensus around the pattern of how things are resolved from DI now, since we are using it in transactions
