### ISSUE TITLE
Configuration Work - Option home and namespace

### ISSUE THREAD

**Issue by jason-bragg** [dotnet/orleans#3956]
Currently all options derived from legacy cluster and client configurations live in Orleans.Core and are under the namespace Orleans.Host.

The namespace was selected for discoverability.
The location was selected to avoid dependency issues, since Orleans Core is where the original configurations lived.

It's not clear if this pattern is what we want to maintain in the long run.

Revisit where options should live, what should be in core, runtime, and what options should be with their components.

**Comment by sergeybykov** [comment]
#3948 move options classes to the right projects.

I think the proper namespace for all options is `Orleans.Configuration`. #4020 moves options of `Orleans.Core` and `Orleans.Runtime` from `Orleans.Hosting` to `Orleans.Configuration`.

If we agree with this approach, next step is to move options of extensions to `Orleans.Configuration` as well.

**Comment by sergeybykov** [comment]
#4030 is for moving remaining *Options classes to `Orleans.Configuration` namespace.

**Comment by sergeybykov** [comment]
Now that #4030 is merged, I believe this is done.
