### ISSUE TITLE
Configuration Work - unwanted or improperly organized settings

### ISSUE THREAD

**Issue by jason-bragg** [dotnet/orleans#3957]
While moving from monolithic Cluster and Client configurations to options, settings surfaced which should probably not be part of Orleans core or may not be categorized correctly.

Below is a list of some such settings, and I encourage others to contribute to this list if the current options seem ill conceived or unnecessary.

AdoNetOptions - should not be in Orleans core.
ServicePointOptions - should not be in Orleans core.
Load shedding settings - Probably should not be part of statistics. (EDIT: moved to its own options)
FastKillOnCancelKeyPress - probably should not be in Orleans core.

Figure out what to do about these.

[Edit]
Thread pool options - don't think thread pool settup should be part of orleans core.

**Comment by ReubenBond** [comment]
Is this fixed now?

**Comment by xiazen** [comment]
fixed and can close now
