### ISSUE TITLE
Reference Microsoft.Orleans.OrleansCodeGenerator.Build problem？

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#3959]
Reference Microsoft.Orleans.OrleansCodeGenerator.Build, it seems invalid, it is not completed 2.0 or I configure here?
![image](https://user-images.githubusercontent.com/28291464/35715634-bcf3d8f8-080e-11e8-846c-496511b5c92d.png)

![image](https://user-images.githubusercontent.com/28291464/35715660-dad566fc-080e-11e8-9ea6-707b255a9ccc.png)

**Comment by aqa510415008** [comment]
Microsoft.Orleans.OrleansCodeGenerator.Build component is used to do what? how to use?

**Comment by ReubenBond** [comment]
@aqa510415008 you must also reference other packages, like Microsoft.Orleans.Core.Abstractions

**Comment by ReubenBond** [comment]
`Microsoft.Orleans.OrleansCodeGenerator.Build` is used for build-time code generation, which is used to generate serializers for your types as well as grain reference classes and grain method invokers.

**Comment by aqa510415008** [comment]
@ReubenBond Microsoft.Orleans.OrleansCodeGenerator.Build I found him referring to Microsoft.Orleans.Core?

**Comment by aqa510415008** [comment]
@ReubenBond That documents and examples need to be updated, otherwise it will be misleading for beginners.

**Comment by ReubenBond** [comment]
@aqa510415008 in Orleans 2.0.0-beta3 it does not reference Microsoft.Orleans.Core. See here:
https://www.nuget.org/packages/Microsoft.Orleans.OrleansCodeGenerator.Build/2.0.0-beta3
![image](https://user-images.githubusercontent.com/203839/35716148-f251bbfc-082a-11e8-8b45-509af64730ad.png)


Which docs need updating?

**Comment by aqa510415008** [comment]
Append a reference to Microsoft.Orleans.Core.Abstractions
![image](https://user-images.githubusercontent.com/28291464/35716185-110b5ec2-0812-11e8-9d67-ee2bb6f1a5b1.png)

**Comment by ReubenBond** [comment]
@aqa510415008 the documentation is for the current stable version of Orleans (1.5.3) for 2.0.0-beta3 documentation, see the link at the bottom of the menu "Orleans 2.0.0-beta".

It might help you to look at the .NET Core 2.0 sample: https://github.com/dotnet/orleans/tree/master/Samples/HelloWorld.NetCore
