### ISSUE TITLE
Orleans Core Versions for Silo Host

### ISSUE THREAD

**Issue by samcov** [dotnet/orleans#3966]
I installed System.Data.SqlClient -Version 4.4.2, and Orleans couldn't find some types, so I tried to reinstall the nugets for the **silo host**, and now there are a lot of complaints.

In HelloWorldCore, the version used is 2.0.0-ci.0, I can no longer find that version.

I tried 2.0.0-beta3 & 2.0.0-beta2, but I still get exceptions thrown, starting with the memory storage provider. Actual Error - _"Method 'get_Log' in type 'Orleans.Storage.MemoryStorage' from assembly 'OrleansProviders, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation."_

Any clue as to what is going on, everything was working perfectly with 2.0.0-ci.0.

**Comment by samcov** [comment]
More Info: I was able to get the ci.0 version back by modifying the csproj as shown below. Unfortunately, Visual Studio will not load the package. Anyone know how to force it to do that?

**csproj Modification**:
    <PackageReference Include="Microsoft.Orleans.OrleansRuntime" Version="**$(OrleansPackageVersion)**" />
    <PackageReference Include="Microsoft.Orleans.OrleansProviders" Version="**$(OrleansPackageVersion)**" />

**Comment by samcov** [comment]
Ok, got the nuget package to load, but I guess the current version is now ci.2018xxx, and now even HelloWorldCore fails to work as ClusterConfiguration no longer exists in the runtime.

**Has there been a breaking change?**

**Comment by samcov** [comment]
Here is a picture of the situation, notice that other orleans tpes appear to be there.
![image](https://user-images.githubusercontent.com/1551314/35826735-7b93891e-0a6e-11e8-91cb-b2a2dd17ce24.png)

**Comment by ReubenBond** [comment]
@samcov I believe that HelloWorld.NetCore in the current master references `2.0.0-beta3` instead of a nightly (continuous integration) build. Would that be suitable for you?

There are some changes between beta3 and latest CI which mean the projects need to be updated. Primarily, some types were moved into `*.Legacy` packages

**Comment by ReubenBond** [comment]
@samcov the idea is that we're moving away from the old `ClusterConfiguration` class and to a model which allows separate, strongly typed configuration for each subsystem. The new configuration use `Microsoft.Extensions.Options`, aligning Orleans configuration with ASP.NET Core configuration.

**Comment by samcov** [comment]
Great, that makes sense!

**Comment by samcov** [comment]
FYI: Successfully migrated to beta3, thanks for the help!

**Comment by ReubenBond** [comment]
Any time, @samcov
