### ISSUE TITLE
Suggest RequestContext add an IServiceProvider property, so easy to control

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#3967]
Suggest RequestContext add an IServiceProvider property, so easy to control

**Comment by aqa510415008** [comment]
Suggest RequestContext and AspNet HttpContext can make an object, and then access (HttpContextAccessor) accessor.

**Comment by sergeybykov** [comment]
I don't understand the `HttpContext` part. Can't serialize and pass it to another machine (silo host), can we?

**Comment by xiazen** [comment]
Can I know what's the use case of adding `IServiceProvider` to RequestContext? What do you intend to do with it?

**Comment by aqa510415008** [comment]
@sergeybykov  @xiazen  I recently custom an authorization module passed through the RequestContext JWT Token in the authorization module need to pass IServiceProvider into it, if RequestContext IServiceProvider then there is no need to pass

**Comment by ReubenBond** [comment]
@aqa510415008 any place where you might need `IServiceProvider`, you can inject it.

**Comment by aqa510415008** [comment]
@ReubenBond I just use this method to solve, RequestContext IServiceProvider more friendly.

**Comment by ReubenBond** [comment]
`RequestContext` is for transferring metadata along with a request only, not for acting as a [Service Locator](http://blog.ploeh.dk/2010/02/03/ServiceLocatorisanAnti-Pattern/).
