### ISSUE TITLE
IServiceProvider service was not available in Interceptors

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#3973]
IServiceProvider service was not available in Interceptors

**Comment by ReubenBond** [comment]
@aqa510415008 please feel free to chat to me directly on Gitter using this link: https://gitter.im/ReubenBond

You can inject services directly into IGrainCallFilter implementations. See the `LoggingCallFilter` sample here: http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Interceptors.html
`loggerFactory` is injected. You could also inject `IServiceProvider` and use that if you want to.

**Comment by aqa510415008** [comment]
Sorry, I forgot

**Comment by ReubenBond** [comment]
No worries, @aqa510415008 :)
