### ISSUE TITLE
Refactor statistic and metric system

### ISSUE THREAD

**Issue by xiazen** [dotnet/orleans#3976]
Currently orleans metric and statistic system has some problems which  made it confusing to use, and error prone 
- [ ]  use assembly loading to configure default `IMetricsDataPublisher` and `IStatisticsPublisher`, which is error prone and also against the new way of configuring providers 
- [ ] use questionable way to determine to use default metric publisher and statistic publisher or not. See `CanUseAzureTable` in `ClientStatisticsManager` as an example. 
- [x] has multiple interfaces, such as `IStatisticsPublisher`, `IMetricDataPublisher`, whose difference isn't clear. For example, Which metrics belongs to statistics, and which belongs to metrics? 
- [ ] overlap with telemetry. So basically now we have three system reporting metrics in orleans, and their responsibility and infrastructure overlap with each other. This made metrics harder to maintain and harder to use. 

Considering refactor it.

**Comment by sergeybykov** [comment]
The plan here is to remove the notion of metrics altogether, as they have outlived their utility, and to get out of assembly loading for statistics. Refactoring and reconciliation of statistics and telemetry will be considered post 2.0.0.

**Comment by ReubenBond** [comment]
`SiloPerformanceMetrics` is used in a few places still, after #3988:
* For [gateway load shedding](https://github.com/dotnet/orleans/blob/d88fa34b68c9100423bc43ecb608e4caa48693e2/src/Orleans.Runtime/Messaging/GatewayAcceptor.cs#L101) `IsOverloaded` + the related test hooks to force the value)
* For thread injection in [`WorkerPoolThread`](https://github.com/dotnet/orleans/blob/d88fa34b68c9100423bc43ecb608e4caa48693e2/src/Orleans.Runtime/Scheduler/WorkerPoolThread.cs#L332)
* As the basis for `SiloRuntimeStatistics` which is pushed to other silos in `DeploymentLoadPublisher`.

Should we keep that or try to remove it? Either way, I can try to slim it down

**Comment by xiazen** [comment]
I think we can remove it. 
Most of its metrics is covered by `IAppEnvironmentStatistics` and `IHostEnvironmentStatistics`. So for `SiloRuntimeStatistics` and `WorkerPoolThread`, we can use those two , instead of SiloPerformanceMetrics. Right? 

For gateway load shedding, we can use a combination of `LoadSheddingOptions` and `IHostEnvironmentStatistics` to determine where it is over loaded or not. So we don't need to keep `iSiloPerformanceMetrics` here either. 

Am I right? Or Am I missing anything?

**Comment by ReubenBond** [comment]
What about for latching the value in tests? `CpuUsage` and `IsOverloaded` are the important ones.

**Comment by ReubenBond** [comment]
For the just-in-time assembly loading of the Azure statistics publishes, can we just axe that? I'm talking about this code
![image](https://user-images.githubusercontent.com/203839/36055618-cb793ce4-0e51-11e8-8d26-1c7af2cfadba.png)
