### ISSUE TITLE
When is version 2.0 expected to be used in a production environment? We are now new system development, intended to be applied, if the time is too long, we can only choose other

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#3979]
When is version 2.0 expected to be used in a production environment? We are now new system development, intended to be applied, if the time is too long, we can only choose other

**Comment by sergeybykov** [comment]
Current beta3 can be used in a production environment. Upcoming rc1 (days out) will be even more so, will all new configuration APIs completed.
