### ISSUE TITLE
Test failures in DelayedQueueRebalancingTests_*

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#3993]
DelayedQueueRebalancingTests_2 seems to be failing consistently with errors like the following:
>Assert.Equal() Failure\r\nExpected: 2\r\nActual: 4

>Assert.Equal() Failure\r\nExpected: 2\r\nActual: 3

and sometimes
>Orleans.Runtime.OrleansMessageRejectionException : Silo S127.0.0.1:28513:255762038 is rejecting message: Request S127.0.0.1:28513:255762038*stg/14/0000000e@S0000000e->S127.0.0.1:28514:255762039*stg/10/0000000a@S0000000a #110: . Reason = Recent (00:00:00.0468768 ago, at 2018-02-08 05:00:52.321 GMT) connection failure trying to reach target silo S127.0.0.1:28514:255762039. Going to drop Request msg 110 without sending. CONNECTION_RETRY_DELAY = 00:00:01.

DelayedQueueRebalancingTests_1 is failing infrequently
>Orleans.Runtime.OrleansMessageRejectionException : Silo S127.0.0.1:22815:255804984 is rejecting message: Request S127.0.0.1:22815:255804984*stg/10/0000000a@S0000000a->S127.0.0.1:22816:255804985*stg/10/0000000a@S0000000a #215: . Reason = Recent (00:00:00 ago, at 2018-02-08 16:56:43.128 GMT) connection failure trying to reach target silo S127.0.0.1:22816:255804985. Going to drop Request msg 215 without sending. CONNECTION_RETRY_DELAY = 00:00:01.

**Comment by xiazen** [comment]
pr submitted for this #4309

**Comment by xiazen** [comment]
issue fixed in #4309
