### ISSUE TITLE
Upgrade Suggestions - How to Handle Persisted Grain States

### ISSUE THREAD

**Issue by nkm8** [dotnet/orleans#4002]
I have been trying to upgrade from v1.2.2 to v1.5.3, but I am having some issues. Our code persists instances of grains using [Orleans.StorageProviders.SimpleSQLServerStorage](https://github.com/OrleansContrib/Orleans.StorageProviders.SimpleSQLServerStorage) and after upgrading Orleans and SimpleSQLServerStorage, the grains fail to deserialize:
`!!!!!!!!!! Error clearing: GrainType=Orleans.Runtime.Versions.VersionStoreGrain GrainId=GrainReference:*grn/13BAB4D8/00000000+OrleansTest ETag= in to DataSource=`

The grains were serialized as binary to a SQL Server DB before VersionStoreGrain was added, so the deserialize always fails and I can't find an easy way to add a fallback serializer to the old 1.2.2 way. This could work for new/clean installs, but existing installs of our current codebase would require deleting all of the stored grains before upgrading, which requires too much manual work to document and re-create all the grain configurations during an upgrade.

I really like the recent work that was done to add versioning to the grains, which addresses one of our main limitations of using v1.2.2.  Does anyone have any suggestions on how they have handled these types of situations?

**Comment by sergeybykov** [comment]
@ReubenBond Do you think there's a way to take serialization code generated by 1.2.2 (or any other old version for that matter) and handcraft a 'migrating serializer' in this kind of situation? Any other ideas?

**Comment by ReubenBond** [comment]
The generated serializers have not changed in a material way since 1.2.2, but there could be some incompatibilities for types which have changed since then. In this case, it might be an issue with that particular storage provider. Here is a similar looking issue: https://github.com/OrleansContrib/Orleans.StorageProviders.SimpleSQLServerStorage/issues/22

**Comment by nkm8** [comment]
I think it's a gray area; I agree that the underlying serializers likely haven't changed recently, but the introduction of versioned grains is causing the issue.

OrleansContrib/Orleans.StorageProviders.SimpleSQLServerStorage#22 is similar, but I don't think swallowing the exception/error will resolve the problem.  The grain is failing to deserialize, so it needs to be handled differently during an upgrade scenario.

One could make the argument that this is an Orleans issue because Orleans defines the serializers and the underlying grain types.  However, the grain states aren't meant to be persisted, so one could also make the argument that the storage provider is responsible for handling the upgrade.

I'll defer to @amccool on which repo this issue falls under.  I'm surprised this doesn't come up more often, but I'm guessing that most Orleans users either don't persist grain states with a storage provider or they aren't bumping the Orleans version very often, if at all.

**Comment by ReubenBond** [comment]
@nkm8 I wonder why the grain would be failing to deserialize if it doesn't exist in the older version.

Orleans' internal serializers aren't designed to be used for persistence primarily because of the versioning story. It's something that I hope to work on in the future.

**Comment by nkm8** [comment]
I haven't looked at the code closely, but I'm guessing the actual type that is serialized in the DB is whatever existed before `Orleans.Runtime.Versions.VersionStoreGrain` was introduced.  I think it used to be `Grain`, but I'm not sure of the namespace.

That's why I was curious if there was a way to use a fallback serializer to try `Grain` when `VersionStoreGrain` fails, but I'm not sure where that code should ultimately live.

**Comment by nkm8** [comment]
I have a new employer and no longer work with Orleans, but I'll defer to @jtfarino and @alexhoneygosky on this issue.

If you don't hear from either in a few days, I think it is safe to close this issue.
