### ISSUE TITLE
ToDo: Better error reporting for missing Orleans.Templates.Grains nuget dependency in the Grain project

### ISSUE THREAD

**Issue by gabikliot** [dotnet/orleans#401]
If a grain project is missing Orleans.Templates.Grains nuget dependency, it compiles fine but statefull Grain will have a State field set to null.
We need better error reporting to this case, maybe fail at compile time.
Issue reported by at least 2 users:
https://github.com/dotnet/orleans/issues/366#issuecomment-97934602
http://orleans.codeplex.com/discussions/637359#post1423953

**Comment by sergeybykov** [comment]
This shouldn't be required anymore with run time codegen of https://github.com/dotnet/orleans/pull/528.
