### ISSUE TITLE
[Question] - Grain Placement

### ISSUE THREAD

**Issue by dazinator** [dotnet/orleans#4013]
I am attempting to model a cluster of Hyper-V servers, where I want a Grain to represent a particular Hyper-V image, but where that Hyper-V image can only exist in silo's where the HyperVisor actually has that image available!

For example, the cluster consists of:

1. Silo A for HyperVisor machine A has Images "A" and "B"
2. Silo B for HyperVisor machine B has Images "A", "B" and "C"

When an orleans client requests the grain for Image "A" - I'd like this grain to be activated in either Silo 1 or 2. 

When an orleans client requests the grain for Image "C" - I'd like this grain to be activate in Silo B because thats the only silo where the image is available.

Is it possible for me to achieve something like this? Or is this kind of thing frowned upon? (If so any suggestions on how I would change the model would be welcome.

Thanks

**Comment by dazinator** [comment]
It seems I am after something similar to [Heterogeneous-Silos](https://dotnet.github.io/orleans/Documentation/Deployment-and-Operations/Heterogeneous-Silos.html) - except instead of different grain types, I am trying to control which silo's a grain is activated in based on the grain's key, and knowing which silo's can support that key.

**Comment by ReubenBond** [comment]
@dazinator you should be able to achieve something like this by implementing a custom `IPlacementDirector`. Take a look at the usages of `IPlacementDirector` in tests for an example of how to implement and use it. https://github.com/dotnet/orleans/blob/master/test/Tester/Placement/CustomPlacementTests.cs

**Comment by dazinator** [comment]
Thanks I have looked into this more closely now.

The `IPlacementDirector` has to select the appropriate silo from the list of all compatible silos.

```
  var silos = context.GetCompatibleSilos(target).OrderBy(s => s).ToArray();
``

In my case I need to pick a silo from the compatible ones, based on whether the silo has a hyperv image installed locally or not.

The name of the image is the grain key (string)

```
var hyperVImageName = target.GrainIdentity.PrimaryKeyString;
var allowedSilos = silos.Where(s=>HasHyperVImage(s, hyperVImageName));

```

The thing is, the placement director can't know which silos have the image available without:

1. Asking them (polling)
2. They tell it (i.e it can access some singleton grain state, that all silos can register their images with)

I don't like option 1 because the images available to a silo are very unlikely to change for long periods of time, and polling before each activation seems overkill.

I'd like to go with number 2, but i'm not sure of the best means of accomplishing that:

1. I need my placement director to have access to some state, and for this state to be updated by a singleton grain in the cluster, so that when silos come online, they can register their hyperv images that they have installed locally with the singleton grain, and then my placement director can access that information to determine where to place grains.

Should this be possible?

**Comment by dazinator** [comment]
Another thought that occurred to me, was that this could perhaps be implemented as a generic "blacklist / whitelist" strategy placement director that can be added to the framework. 

The idea is that it would be a `PlacementDirector` that is capable of using a `Blacklist` or `Whitelist` strategy, for activations based on lookup of blacklisted or whitelisted silos for the GrainKey, and where silo's can register themselves on the blacklist or whitelist for particular grain keys.

For example, the placement director code would be along the lines of:

```
// all compatible
var silos = context.GetCompatibleSilos(target).OrderBy(s => s).ToArray();

var key = target.GrainIdentity.PrimaryKeyString;

// filter to only silos that haven't blacklisted the key, or if the strategy is whitelist, only silos that have explicitly whitelisted themselves against this key

var allowedSilos = silos.Where(s=>SatisfiesBlacklistWhitelist(s, key));

// Potentially defer placement to a chained placement director for allowedSilos? i.e Random etc

```

This logic seems more about filtering the compatible silos though, more so than placement. I.e I would still like to use in built placement mechanisms such as Random - which makes me think it might be a better design if we could hook into `GetCompatibleSilos` to apply this logic so that the out of the box placement directors could be used as before.  

Does orleans allow you to hook into the GetCompatibleSilos() somehow to filter what would be returned to the placement director?

**Comment by sergeybykov** [comment]
>Question: On which silo is the PlacementDirector run on? Is it locked to a single silo within the cluster, or can it run on any silo within the cluster?

Placement directors run on all silos.

>Question: On which silo is the PlacementDirector run on? Is it locked to a single silo within the cluster, or can it run on any silo within the cluster?

There are several options here. You can use a bootstrap provider (startup task) to get an initial map of images to silos. Subsequent updates to the map can be disseminated either by polling a central source of truth (e.g. storage) or by pushing update to subscribers or a combination of the two.

For example, the placement director could periodically call a local `StatelessWorker` grain to update the local map.

>Does orleans allow you to hook into the GetCompatibleSilos() somehow to filter what would be returned to the out of the box placement directors?

`GetCompatibleSilos` is only concerned with availablity of the target grain class (and version). I'm not sure I see value in the general notion of black/white lists. Any logic like that I think can be added at the placement director level and easily reused across a number of directors if needed.

**Comment by dazinator** [comment]
Ok thanks

> For example, the placement director could periodically call a local StatelessWorker grain to update the local map.

Ok so the placement director itself can be an orleans client. I will look into what you have suggested. This would give me a mechanism to poll for changes which is ok.

Ideally though I'd like my placement director to be notified of changes - i'm asuming it can't be used like an ordinary orleans grain as if it could be then i'd have the silos register their images with it on startup!

Anyway you have given me plenty to think about :-)

**Comment by sergeybykov** [comment]
If I were to build such a feature, I would consider completely decoupling placement director from the map acquisition and update mechanism via DI. That would allow me to easily try various push and pull based mechanisms without making the director aware of them, or making it call grains.

**Comment by dazinator** [comment]
Good idea. So inject some `IMapProvider` into my `PlacementDirector` and have `IMapProvider` expose the Mapping, which I can experiment in how I keep that mapping current.

Are you aware if Orleans provides any pub/sub mechanism where by a message can be broadcast from one silo to all silos in the cluster? I'd need something like this so that I could distribute my mappings to all silo's in the cluster, such that the PlacementDirector could be instantiated on any of them and have the current map available without polling.

**Comment by dazinator** [comment]
> Are you aware if Orleans provides any pub/sub mechanism where by a message can be broadcast from one silo to all silos in the cluster?

I guess I could create such a mechanism via a singleton per cluster grain to manage the subscriptions, and then seeprate publisher and subscriber grains? But that sounds like a reasonable amount of work so wondering if there was anything out of the box for that kind of thing

**Comment by dazinator** [comment]
Should have googled a bit more first - I found this IGrainObserver concept which looks like exactly what i need: https://coderead.wordpress.com/2014/07/23/using-observers-for-pub-sub-in-project-orleans/

**Comment by sergeybykov** [comment]
There's also the (still undocumented) option of grain services that gives one grain-like instance per silo:
#2459 
https://github.com/dotnet/orleans/blob/master/test/Tester/GrainServiceTests/GrainServiceTests.cs

**Comment by talarari** [comment]
Are placement directors relevant after a grain is activated?
For instance if a grain needed to be activated and the placement director selected a silo for it, then something changed and that silo is no longer compatible with that silo according to the placement director, will the grain be deactivated and reactivated in a new silo?

**Comment by sergeybykov** [comment]
>Are placement directors relevant after a grain is activated?

Placement directors are only involved when deciding where to place a new grain activation. After that, they are not called.

>For instance if a grain needed to be activated and the placement director selected a silo for it, then something changed and that silo is no longer compatible with that grain according to the placement director, will the grain be deactivated and reactivated in a new silo?

If something changed after the grain is activated, no action will be taken. But I can't see how a silo may become incompatible while the grain activation is already executing on it.

**Comment by talarari** [comment]
Looking for a way to implement a staging production swap. Something that will cause all grain to move to a new silo.

**Comment by sergeybykov** [comment]
Have you looked at http://dotnet.github.io/orleans/Documentation/Grain-Versioning/Grain-versioning.html?

**Comment by talarari** [comment]
I tried that once, had a problem with streams.
Couldn't keep my staging environment from getting activations for grains that are registered to streams being published by the production silo.

I guess since the call to activate grains from the pulling agents are not versioned.

Would love it if there was a way to do a staging production swap. Any advice is welcome.

**Comment by benjaminpetit** [comment]
> I guess since the call to activate grains from the pulling agents are not versioned.

Unless I'm mistaken, pulling agent just do regular grain calls. So they will ask for the version they were compiled against? I guess your issue is that you start pulling agent on 'v2' silos that will explicitely need 'v2' activations

**Comment by sergeybykov** [comment]
Stream events are sent as regular grain calls over built-in streaming interfaces that aren't versioned as of today. They get resolved to grain classes of subscribed grains via the normal placement mechanism that can be subject to versioning and versioned-based placement policies.

**Comment by talarari** [comment]
Thanks for the explanation, maybe I missed something, I'll try again and see if it works.

**Comment by sergeybykov** [comment]
Looks like we can close this. Feel free to reopen if there's more.
