### ISSUE TITLE
[Question] - How to build bootstrap providers without legacy package?

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#4014]
Hi,

I try to figure out how to build a bootstrap provider without the legacy stuff in beta3.

My attempt:

    public sealed class EventConsumerBootstrap : ILifecycleParticipant<ISiloLifecycle>
    {
        private readonly IGrainFactory grainFactory;

        public EventConsumerBootstrap(IGrainFactory grainFactory)
        {
            this.grainFactory = grainFactory;
        }

        public void Participate(ISiloLifecycle lifecycle)
        {
            lifecycle.Subscribe(SiloLifecycleStage.SiloActive, ct =>
            {
                var grain = grainFactory.GetGrain<IEventConsumerManagerGrain>("Default");

                return grain.ActivateAsync();
            });
        }
    }

But the problem is that I have no access to the scheduler. The legacy package uses the OrleansScheduler, which is internal. Therefore my call to the grain fails.

**Comment by ReubenBond** [comment]
@SebastianStehle take a look at #4026 and let me know if it's suitable for your needs.

**Comment by SebastianStehle** [comment]
Yes, perfect 👍
