### ISSUE TITLE
Add a config option to not intercept AppDomain.CurrentDomain.ProcessExit in Silo

### ISSUE THREAD

**Issue by benjaminpetit** [dotnet/orleans#4016]
Dev that want to intercept `AppDomain.CurrentDomain.ProcessExit` to control silo shutdown currently cannot to it reliably since in `Silo` we always listen to this event and do a "FastKill".

We should add an option to disable this behavior, but let it by default

**Comment by SebastianStehle** [comment]
Thx you for pushing it to RC1 :)

**Comment by benjaminpetit** [comment]
Fixed with #4036

**Comment by SebastianStehle** [comment]
Thank you
