### ISSUE TITLE
[Question] Running beta 3 on azure worker role

### ISSUE THREAD

**Issue by miker1423** [dotnet/orleans#4021]
Hello! I'm trying the latest beta of 2.0.0 on a azure worker role, but I can not even start the silo, the error thrown is the next one 

OrleansMessageRejectionException: Silo S10.43.44.207:54629:256167661 is rejecting message: Request S10.43.44.207:0:256167661???/00000013@S00000013->S10.43.44.207:0:256167661???/dc13e0a2@Sdc13e0a2 #5: global::Orleans.Streams.IPersistentStreamPullingManager:Initialize(). Reason = Recent (00:00:00.7408936 ago, at 2018-02-12 21:41:16.135 GMT) connection failure trying to reach target silo S10.43.44.207:0:256167661. Going to drop Request msg 5 without sending. CONNECTION_RETRY_DELAY = 00:00:01.

and the configuration I'm using the next config 
```
var config = AzureSilo.DefaultConfiguration();
config.AddAzureTableStorageProvider();
config.AddAzureQueueStreamProviderV2("StreamProvider");
config.AddMemoryStorageProvider("PubSubStore");
config.Globals.ReminderServiceType = GlobalConfiguration.ReminderServiceProviderType.AzureTable;
```

**Comment by xiazen** [comment]
Hi @miker1423 

I noticed you haven't configure any Azure connection string, for AzureTableStorageProvidfer , or the other Azure stuff. Is it you haven't configured, or you just didn't post them? 

And do you see other Error or Warning logs prior to the one you posted?

**Comment by miker1423** [comment]
Well, this is a project which was running on the previews version (1.5.4), so I just upgraded the packages, changed how the silo is been built, since I can run the same sample with out specifying the connection string on version 1.5.4, I thought it was not needed now, but, I can try specifying it, I'll post my results here.

**Comment by miker1423** [comment]
After adding the connection string, the configuration looks as follows 
```
var connectionString = RoleEnvironment.GetConfigurationSettingValue("DataConnectionString");
var config = AzureSilo.DefaultConfiguration();
config.Globals.ReminderServiceType = GlobalConfiguration.ReminderServiceProviderType.Disabled;
config.AddAzureTableStorageProvider(connectionString: connectionString);
config.AddAzureQueueStreamProviderV2("StreamProvider", connectionString: connectionString);
config.AddMemoryStorageProvider("PubSubStore");
```

But the exception is still been thrown, it is the same exception and no other thing on the log, except for the stack trace

**Comment by xiazen** [comment]
this seems bad. Let me  investigate in my end . will get back to you. Thanks for reporting !

**Comment by miker1423** [comment]
Hello, forgot to update the issue, I got it running, but lot of things had to be done, may I DM you at Gitter @xiazen ?

**Comment by xiazen** [comment]
please do and share with me what you have done. Thanks !

**Comment by xiazen** [comment]
After communication on gitter, we realize the real issue is migration guide from 1.5 to 2.0. Configuration changed a lot in 2.0, and user are not clear which ones they need to configure explicitly now, and which ones not. 

For example,  In 1.5.4, `AzureSilo.DefaultConfiguration()` used to configure silo endpoint, gateway ports, etc. But in 2.0 beta, we don't configure those two by default. User need to explicitly configure them, hence the confusion. But we recently added default values for both in #4033 , which will be included in rc. 

I think the action item here is to provide a way to asist user migrate to use ISiloHostBuilder to configure silos, such as documentation, extension method on `ISiloHostBuilder` etc.

**Comment by miker1423** [comment]
Glad to help 😃

**Comment by xiazen** [comment]
thanks so much for the investigation! 
and by 

> Glad to help 

do you mean you volunteer to write the migration doc for AzureSilo?! ;)  if yes, much thanks .  💃

**Comment by xiazen** [comment]
nice talking to you today

**Comment by miker1423** [comment]
Given that the RC has been released, I'll start writing the docs for the migration from 1.5.x to 2.0 RC1, any suggestions?

**Comment by xiazen** [comment]
You can writer how to migrate off AzureSilo, in Orleans 2.0-rc -> Migration secion. If you'd like, you can even help us migrate our AzureWebService sample off AzureSilo. What do you think ?

**Comment by miker1423** [comment]
Sure, sounds great 😃

**Comment by xiazen** [comment]
thank you so much !

**Comment by miker1423** [comment]
PR with the migration path docs is ready https://github.com/dotnet/orleans/pull/4336

**Comment by xiazen** [comment]
Thanks so much for the contribution. Really appreciate it. And btw I merged your pr. So close this issue now.
