### ISSUE TITLE
Grain Bulk Creation

### ISSUE THREAD

**Issue by teedty1** [dotnet/orleans#4038]
Does anyone have an ideas on how to create grains in batch? We use DynamoDB to store JSON records which I'm hoping to deserialize into Grains. I've tried code in two ways:

1. Do a BatchGetItemAsync and then for each result create a grain and set the value
2. Do a GetItemAsync in the Grain OnActivateAsync() and set the value

Option 1 is much faster by doing the batch, but it means I have code in a different grain to do the BatchGetItemsAsync and then set the Grain values. Option 2 leads to cleaner code, but is significantly slower.

I would like to have my Grain know how to initialize itself, but need to do it some way using Batch.

**Comment by tinpl** [comment]
not that I know the best possible way, but maybe something like like this could probably work? :
```csharp
class GrainsConstructor {
    async Task<IEnumerable<ISomeGrainInterface>> GetGrains() {  return BatchGetItemAsync().Select(x => { var g = await GrainFactory.GetGrain<ISomeGrainInterface>(someUid); g.SetValue(x); return g; });
}
```

**Comment by teedty1** [comment]
@tinpl  That is pretty much how I am doing it right now with Option 1.  The problem with this is that I'm still needing a separate class that "creates" the grains from the BatchGetItemAsync call.  This may just be the only way to do this...

**Comment by sergeybykov** [comment]
Can you route `GetItemAsync` calls through a layer that would batch them, to get the benefits of both approaches?

**Comment by teedty1** [comment]
I think we can close this.  I was able to work out a way using some of the suggestions here and in Gitter.  I added methods into my Record grain that can either load directly from DynamoDB or receive byte[] for when loading in bulk.  Thanks everyone for your suggestions.
