### ISSUE TITLE
Using a generic method on a grain interface results in needed reference to Orleans.Core from interface project

### ISSUE THREAD

**Issue by jsteinich** [dotnet/orleans#4039]
The generated code when a grain interface has a generic method results in a reference to GenericMethodInvoker which is in Orleans.Core. Following the sample projects, the interface project only has references to Orleans.Core.Abstractions and code gen.

While it isn't hard to add the extra reference, that may not be the desired fix. 

Looking into what GenericMethodInvoker depends on in core / what it is doing, it doesn't really feel like it should be moved. Perhaps an IGenericMethodInvoker would make sense, but I'm not sure where the implementation would get injected.

**Comment by sundong1982** [comment]
this bug solved?

**Comment by ReubenBond** [comment]
Not yet. This is currently a limitation. The workaround is fairly simple: add the `Microsoft.Orleans.Core` package to your project.

**Comment by ReubenBond** [comment]
Fixed in 7.0
