### ISSUE TITLE
[Question] With FastKillOnCancel removed whats the guidance on handling CTRL-C fast shutdown.

### ISSUE THREAD

**Issue by jsukhabut** [dotnet/orleans#4043]
With FastKillOnCancel removed and AppDomain wired for fast kill, what is guidance on handling CTRL-C fast kill?

This way:
```
                Console.CancelKeyPress += (sender, eventArgs) =>
                {
                    Environment.Exit(0);  
                };
```

This way:
```
                Console.CancelKeyPress += (sender, eventArgs) =>
                {
                    var cancellationSource = new CancellationTokenSource();
                    cancellationSource.Cancel();
                    this.silo.StopAsync(cancellationSource.Token);
                };
```

Or this way:

```
                Console.CancelKeyPress += (sender, eventArgs) =>
                {
                    var cancellationSource = new CancellationTokenSource();
                    cancellationSource.Cancel();
                    this.silo.StopAsync(cancellationSource.Token).GetAwaiter().GetResult();
                };
```

**Comment by ReubenBond** [comment]
If you want to just exit the process in the fastest and dirtiest way possible, use the first.
If you want to stop the silo cleanly but ungracefully (not informing the rest of the cluster), use the last one.

**Comment by jms69** [comment]
Thanks.  It is a better model because devs can now add their own shutdown code along with the silo shutdown, it just needs to be documented how to replace the missing FastKillOnCancel function.

**Comment by veikkoeeva** [comment]
@jms69 One more thing to notice, you can also call `.Dispose` on the silo. It's fast, but I'm not entirely sure of the implications of calling it.

**Comment by ReubenBond** [comment]
Modern versions of Orleans encourage the use of the .NET Generic Host, which handles Ctrl+C when configured to do so (using the console lifetime) https://learn.microsoft.com/en-us/dotnet/core/extensions/generic-host
