### ISSUE TITLE
Cannot find generated GrainReference class

### ISSUE THREAD

**Issue by ForkBug** [dotnet/orleans#4052]
Hi，in my test environment, a silo and a client are started.
There are two grains in the silo: GrainA and GrainB.

When I try to get a GrainB reference, in the CLIENT, it works fine.

But when I try to get a GrainB reference, in the GrainA's OnActivateAsync,  an exception is thrown out:
System.InvalidOperationException: 'Cannot find generated GrainReference class for interface 'MyInterfaces.IInterfaceOrleans''

Orleans version: 2.0.0 beta3 from nuget.org

Any suggestion for further diagnosing?

**Comment by ReubenBond** [comment]
@ForkBug you need to add the interface assembly and not just the assembly with grain classes in it.
There's some more information in the docs: http://dotnet.github.io/orleans/Documentation/2.0/Configuration2.0.html#application-parts
