### ISSUE TITLE
Update Samples and docs to show necessity of using ObserverSubscriptionManager.IsSubscribed()

### ISSUE THREAD

**Issue by finsterdexter** [dotnet/orleans#4061]
Both the Orleans docs and several samples just call ObserverSubscriptionManager.Subscribe() without handling the OrleansException that is generated if the observer that is subbed/unsubbed is already subbed/unsubbed. That seems like an important failure state to handle, especially since the current docs actually suggest re-subbing as a means of improving reliability of this feature.

**Comment by sergeybykov** [comment]
@finsterdexter Valid point. Thank you. Would you be willing to contribute an update to the docs and samples?

**Comment by finsterdexter** [comment]
Yeah possibly. Gotta see if I can fit it into my spare time. I mainly wanted to float the issue before tackling it.

**Comment by finsterdexter** [comment]
Yikes, I didn't realize all my commit --amends would end up on here... sorry about the mess!

![20161119151919 sorry_about_the_mess](https://user-images.githubusercontent.com/98887/38998653-a88416e8-43b5-11e8-9af1-eb9332f0e48d.gif)

**Comment by xiazen** [comment]
thanks for pointing this out for us. Your PR looks good. I merged it.

**Comment by xiazen** [comment]
close issue, since issue resolved through #4489
