### ISSUE TITLE
End-To-End Identity

### ISSUE THREAD

**Issue by johannescolmsee** [dotnet/orleans#4069]
Hello,

are there any plans to integrate "end-to-end (windows)identity" feature into Orleans?

By this I mean "running the grain method in the context of a windows-user" - something which you get for free for most other MS-Products (WCF / ASMX services, etc).

This is mandatory for our use case, and I have been struggling implementing this (I kinda have it working now, using SSPI Api....but right now the solution is a little messy, and implementing that in all places where it is needed will be a lot of work).

So - are there any plans on integrating this into Orleans?

**Comment by ReubenBond** [comment]
In the past, I've implemented identity using ASP.NET Identity + IdentityServer. You could do the same. You could set the user principal in an `IGrainCallFilter` and pass it along via the `RequestContext` so that it's available along a call chain

**Comment by softwaretirol** [comment]
I´m struggling with the same problem - do you have any further information about that or a small example?

**Comment by ifle** [comment]
It's very interesting. Please share you experience with small example

**Comment by ReubenBond** [comment]
The whole thing is wildly out of date, but I wrote this implementation of ASP.NET Identity backed by Azure Table Storage:
[Identity.zip](https://github.com/dotnet/orleans/files/1755432/Identity.zip)

⬆ Strictly speaking, that's not necessary, but I was high on grain dust at the time.

Then, I added a wrapper over `RequestContext`, called `ActorRequestContext`:
```C#
public static class ActorRequestContext
{
    private const string ClaimsKey = "claims";

    private const string UserKey = "user";

    /// <summary>
    /// Returns the current user id.
    /// </summary>
    /// <returns>The current user id.</returns>
    public static Guid? GetUserId() => GetUser()?.Id;

    /// <summary>
    /// Returns a value indicating whether or not the current user is in the specified org.
    /// </summary>
    /// <param name="orgId">
    /// The org id.
    /// </param>
    /// <returns>
    /// Whether or not the current user is in the specified org.
    /// </returns>
    public static bool IsInOrg(Guid orgId)
    {
        var user = GetUser();
        return user == null || user.Orgs != null && user.Orgs.Contains(orgId);
    }

    public static UserPrincipal GetUser()
    {
        var user = RequestContext.Get(UserKey) as UserPrincipal;
        if (user == null || !user.Claims.Any())
        {
            var claims = RequestContext.Get(ClaimsKey) as List<SerializableClaim>;
            if (claims != null)
            {
                user = new UserPrincipal(claims);
                RequestContext.Set(UserKey, user);
            }
        }

        return user;
    }

    public static bool IsAdmin()
    {
        var user = RequestContext.Get(UserKey) as UserPrincipal;
        return user == null || user.IsAdmin;
    }
    
    public static void SetUser(UserPrincipal identity)
    {
        if (identity?.Claims == null)
        {
            SetValue(ClaimsKey, null);
        }
        else
        {
            var claims = new List<SerializableClaim>(identity.Claims.Select(_ => new SerializableClaim(_)));
            SetValue(ClaimsKey, claims);
        }
    }

    private static void SetValue(string key, object value) => RequestContext.Set(key, value);
}
```

On the client side (which was an ASP.NET WebAPI project), I hooked `ClientInvokeCallback` to flow the user principal from WebAPI -> Orleans
```C#
GrainClient.ClientInvokeCallback += (request, grain) =>
{
    var user = HttpContext.Current?.User as UserPrincipal;
    ActorRequestContext.SetUser(user);
}
```
Note that in 2.0 you would accomplish this by injecting an `IOutgoingGrainCallFilter`, *not* by using `ClientInvokeCallback`.

Authorization was performed in the grains themselves (AuthN on the FE, AuthZ on the BE):
```C#
public async Task<string> GenerateNewTransferToken(TimeSpan? lifespan = null, bool plaintextToken = false)
{
    AuthAssert.OwnerOrProducer(this.State.Item.OrganizationId, this.State.Item.OwnerId);
// ...
```
In 2.0, AuthZ could be moved to attributes and enforced using an `IIncomingGrainCallFilter`.

Hope that helps

**Comment by ifle** [comment]
Thanks a lot

**Comment by johannescolmsee** [comment]
Thanks for that example ReubenBond,

however...I cannot find any info on **Windows**User **Impersonation** with IdentityServer4...Is that even possible?

**Comment by ReubenBond** [comment]
@johannescolmsee hmm, for that I'm not sure - it's not really in the scope of Orleans to impersonate Windows users. I'm sure it's possible somehow, though, except it might require a bit of leg work to see how impersonation works in WCF under the hood and then replicate that behavior.

**Comment by johannescolmsee** [comment]
Hmm...ok...guess I will continue with SSPI then.

At least that new IOutgoingGrainFilter looks like it could help with my problems (the signature of that method suggests that now we could do "longer" operations, like....do some grain calls)
