### ISSUE TITLE
Nano Server and Orleans

### ISSUE THREAD

**Issue by ghost** [dotnet/orleans#407]
I'm wondering with the announcement with regards Nano Server will/are is there any work on getting Orleans running on Nano Server and or the core 5 framework in general?

**Comment by sergeybykov** [comment]
Yes, we have https://github.com/dotnet/orleans/issues/368 to make Orleans CoreCLR-compatible.

**Comment by gabikliot** [comment]
@HornerGrahame , your help on #368 would be greatly appreciated!

**Comment by grahamehorner** [comment]
@gabikliot would be glad to help out in anyway I can; loving the work the team is doing and would love to be a part of this.

**Comment by gabikliot** [comment]
Thank you @grahamehorner. See my reply here: https://github.com/dotnet/orleans/issues/368#issuecomment-121126309.

**Comment by sergeybykov** [comment]
Closing this as a duplicate of #368.
