### ISSUE TITLE
IVersionStore should not be used before the silo is ready

### ISSUE THREAD

**Issue by benjaminpetit** [dotnet/orleans#4075]
Right now it is used in `ServiceLifecycleStage.RuntimeGrainServices`, and sometimes when the first silo starts you can get these errors in the logs:

> [2018-02-23 01:23:05.417 GMT 45	Error	102202	Orleans.Storage.AzureTableGrainStorage]	!!!!!!!!!! Error from storage provider AzureTableGrainStorage.Orleans.Runtime.Versions.VersionStoreGrain during ReadState for grain Type=Orleans.Runtime.Versions.VersionStoreGrain Pk=*grn/13BAB4D8/000000000000000000000000000000000600000013bab4d8+loadtests636549168964888958-0xD87DF39E Id=GrainReference:*grn/13BAB4D8/00000000+loadtests636549168964888958 Error=

I think we should move its initialization in  `ServiceLifecycleStage.ApplicationServices`

**Comment by sergeybykov** [comment]
Resolved via #4077.
