### ISSUE TITLE
Failure loading MemoryStorageGrain

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#4084]
On latest RC, calling `.AddMemoryGrainStorageAsDefault()` fail to register the provider if we are adding any type to application parts manager (i.e. the auto-discovery is disable since I'm adding assemblies manually).

This method is supposed to add the `IMemoryStorageGrain` to the App parts internally.

Logs attached.

Thanks
[logs-from-kubesilo-in-kubesilo-57bf49b4b7-zzs9f (1).txt](https://github.com/dotnet/orleans/files/1764074/logs-from-kubesilo-in-kubesilo-57bf49b4b7-zzs9f.1.txt)

**Comment by jason-bragg** [comment]
> This method is supposed to add the IMemoryStorageGrain to the App parts internally.

Not disagreeing with this, but think we need to consider this in the context of a general pattern, as whatever we come up with for solving this should be generally applicable for Orleans extensions.  Are these sorts of extension functions supposed to ensure that the necessary parts have been loaded?  Is there a risk of duplication of the part loading?

**Comment by galvesribeiro** [comment]
Yeah, that was my first thought... For now it is this memory grain. Later on it will be whatever other internal component (i.e. SystemTargets, grain services, etc.). 

The point is, I think the general pattern should be to always require and use the app part manager. If the user want to use the _dynamic_ scan of folders, then a new extension method targeting the part manager should be implemented, but in all cases, part manager should be required to be configured. That will avoid the ambiguity of whether or not something was added to the part manager.

I also think this must be decided/handled before 2.0 RTM as it will be source of many questions/issues and troubleshooting sessions on Gitter.

**Comment by ReubenBond** [comment]
This is one of the reasons that we shouldn't be hanging methods from `IServiceCollection` - it doesn't have access to `IApplicationPartManager` to configure the parts.

The extension method *should* be adding OrleansProviders to the parts.
There is no risk of duplication:
* `ApplicationPartManager.AddApplicationPart(part)` adds to the internal `HashSet<IApplicationPart>`
* `AssemblyPart` overrides `GetHashCode()` & `Equals(object)`, delegating them to the underlying assembly

**Comment by galvesribeiro** [comment]
Ok but, you agree that regardless of where we hang the extension method, the problem here is that when we externally set the application parts, then we also need to register other services that were _built-in_ like the memory grain manually when what should happen is that the memory grain extension _should_ do it itself, right?

**Comment by jason-bragg** [comment]
> This is one of the reasons that we shouldn't be hanging methods from IServiceCollection

Agreed, it was suggested a while back (I think by @ReubenBond, but I can't say for sure) that we should remove the extension over IServiceCollection and hang everything on the ISiloHostBuilder (or IClientBuilder).  We'd not really followed up on that, but maybe we should in light of this shortcoming.

> The extension method should be adding OrleansProviders to the parts.

Agreed.

> ApplicationPartManager.AddApplicationPart(part) adds to the internal HashSet<IApplicationPart>, assemblyPart overrides GetHashCode() & Equals(object), delegating them to the underlying assembly.

It's good that duplications are taken care of, but this means of achieving this is suspect.  This is a hidden agreement between implementations which is not communicated via the abstractions.  One, unaware of this hidden expectation. could reasonably implement an IApplicationPart which violates this constraint.

**Comment by ReubenBond** [comment]
@jason-bragg what other means for removing duplicates would you suggest?

I doubt we'll see any other implementation of `IApplicationPart` any time soon (or maybe ever) and if we do, they design is up to the implementer. The only sensible use for a custom implementation would be if it were paired with a custom `IApplicationFeatureProvider` and the semantics for that are totally up to them in that case.

In the worst case, with no deduplication, the end-consumers of these parts tend to deduplicate anyway, since the parts feed Dictionaries keyed on CLR types (string, Type, int)

**Comment by jason-bragg** [comment]
I understand that an application part need have some understanding of it's application feature provider.  Anyone writing a part would be writing it for a feature.  Both those abstractions are opaque to the point of being little more than markers.

My concern is mainly between the manager interface and the things it manages.  If the manager is expected to guarantee uniqueness, which is what currently seems to be the expectation, it needs be clear from the public surfaces how this is to be done.  Having this as a hidden agreement between implementations defeats the point of having an abstraction.

> what other means for removing duplicates would you suggest?

I don't have a strong opinion about how this is solved.  Some options:
* IApplicationPart and IApplicationFeatureProvider can inherit from IEquatable<interface>
* Calls adding parts and feature provider can take a unique key.  String should probably suffice.
* Manager should not have this responsibility, but instead feature providers, which have much more intimate knowledge of the type of part can be made responsible, when uniqueness is important.

**Comment by jason-bragg** [comment]
@ReubenBond, I'm cool with that.

I very slightly favor the feature provider being responsible for deduping parts, as it would have a better understanding of the parts and if duplicates should be allowed, but this is an extremely minor preference.

Inheriting from IEquatable seems to me a viable solution.
