### ISSUE TITLE
Unclear dependency of Reminders to Membership on ADO.net providers

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#4095]
If I have something like this:

```
builder
        .Configure(c => c.ClusterId = configRoot["ClusterId"])
        .ConfigureSiloName(serviceName)
        .UseAdoNetReminderService(opt =>
        {
          opt.ConnectionString = configRoot["ClusterStorage"];
          // opt.Invariant = ADO_INVARIANT;
        })
        .ConfigureEndpoints(IPAddress.Parse(siloIp), port, port + 1000, true)
        .UseAdoNetClustering(options =>
        {
          options.ConnectionString = configRoot["ClusterStorage"];
          options.AdoInvariant = ADO_INVARIANT;
        })
...
```

The silo fail to start saying that the membership provider relational storage can't have a null value on `AdoInvariant`.

If I uncomment `// opt.Invariant = ADO_INVARIANT;` at the Reminders configuration (kudos to @rikbosch), the silo start just fine.

I understand that reminders as any other AdoNet provider requires the `Invariant` to not be null. What I doesn't understand is why the Membership provider blow up when the reminder is not properly configured.

To remediate that, I think the AdoNet provider would love to receive a configuration validator like the other providers so it can fail fast by the time you call `builder.Build()`.

**Comment by ReubenBond** [comment]
@galvesribeiro what's the exact error message you see?
I added extra validation in #4097

**Comment by galvesribeiro** [comment]
@ReubenBond it comes from https://github.com/dotnet/orleans/blob/master/src/AdoNet/Shared/Storage/RelationalStorage.cs#L90

Now it is clear to me what is happening... I've following the code thru the lifecycle events, and the silo fail to start not because the membership is depending on reminders. Right after the membership starts, the reminders try to start and connect to the table and if that fail, the silo startup fail.

So, yeah. With the extra validations you added we will probably have a better experience and not wait to startup the silo and mix messages.

I'm closing this issue as it is not relevant anymore.

Thanks!
