### ISSUE TITLE
gitter activity not linked to github activity

### ISSUE THREAD

**Issue by ghuntley** [dotnet/orleans#410]
## CoreFX/CoreCLR (working)
![working](https://cloud.githubusercontent.com/assets/127353/7585842/e2a0fc2a-f8e9-11e4-8a66-db665282a5dc.png)

## Orleans (not working)
![not-working](https://cloud.githubusercontent.com/assets/127353/7585836/d0cf6068-f8e9-11e4-837a-30d6044f758e.png)

Side effects include: no notifications within chat when a new issue is opened/closed or a pull request is merged or created. Potential team/activity communication inhibitor.

**Comment by gabikliot** [comment]
I think I fixed it. Added Integration via Gitter web hooks.

**Comment by gabikliot** [comment]
Trying to close to test the Gitter activity.
