### ISSUE TITLE
is there any libiary for C++ as create a orleans client

### ISSUE THREAD

**Issue by sgf** [dotnet/orleans#4104]
is there any libiary for C++ as create a orleans client

**Comment by ReubenBond** [comment]
@sgf no, but you can put an HTTP server in front of Orleans and communicate with that using C++

**Comment by sgf** [comment]
@ReubenBond tks

**Comment by ReubenBond** [comment]
@sgf we don't have plans to support other runtimes yet, however you could put a TCP/RPC service in front of a cluster manually

**Comment by aqa510415008** [comment]
@ReubenBond There is no DotNetty support

**Comment by sgf** [comment]
@ReubenBond  thank u again
