### ISSUE TITLE
Move IStartupTask to Runtime Abstractions package

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#4106]
As any other abstractions used by the Silo, I think `IStartupTask` and its extensions to register it should be moved to `Microsoft.Orleans.Runtime.Abstractions`. 

Is there any particular reason for that still on the Runtime package?

**Comment by ReubenBond** [comment]
No reason, please feel free to move it.

**Comment by galvesribeiro** [comment]
Done. #4108

**Comment by ReubenBond** [comment]
Thanks :)

**Comment by sergeybykov** [comment]
Resolved via #4108.
