### ISSUE TITLE
2.0 rc1 ServiceFabric clustering is dependent on Legacy Configuration

### ISSUE THREAD

**Issue by rikbosch** [dotnet/orleans#4109]
The service fabric clustering components are still dependent on the Legacy GlobalConfiguration object (and legacy nuget package).  

Is ServiceFabric clustering considered to be legacy as well? Since I saw some threads indicating to use another membership provider (like azure table) in SF.

**Comment by ReubenBond** [comment]
@rikbosch SF is not considered legacy - I just need to update the components to support the new options.
