### ISSUE TITLE
Warning in logs: Ignoring unhandled exception during PubSub.UnregisterProducer

### ISSUE THREAD

**Issue by peter-perot** [dotnet/orleans#4110]
I'm running Orleans 1.5.3 and currently playing around with Orleans streams, especially with the SMSProvider.

I wrote a grain called `AppSettingsGrain` which contains settings for the service, which can be configured via a client.

In order to make the settings locally available in all silos, I replicate the data by utilizing streams. As soon as the settings are changed in the `AppSettingsGrain`, they are propagated to all _explicitly_ subscribed `AppSettingsObserverGrain` instances. The latter grains live in each silo, and only one per silo (using the `PreferLocalPlacement` strategy).

This works fine. BTW: I'm using a `FileStorageProvider` for persisting the stream subscriptions.

Now there is a simple test case: I start the debugger only using one (primary) silo. Then I change the settings by calling the `AppSettingsGrain`; the changes correctly get propagated to the `AppSettingsObserverGrain`.

Then I stop the debugger and restart. Again I change the settings by calling the `AppSettingsGrain`. 

Now I see the following log message:

```
[2018-03-01 15:13:03 +01:00 WRN] [2018-03-01 14:13:03.108 GMT    10     WARNING 103405  InsideRuntimeClient     127.0.0.1:11111]     Extension not installed on grain Services.Infrastructure.Grains.Implementations.AppSettingsGrain attempting to invoke type Orleans.Streams.OrleansCodeGenStreamProducer
ExtensionMethodInvoker from invokable Orleans.Runtime.ActivationData for message IsAlwaysInterleave NewPlacement Request S127.0.0.1:11111:257609562*grn/716E8E94/00000000+SMSProvider_AppSettings@2bb98899->S127.0.0.1:11111:257609562*grn/A64CC0FF/00000000@a9167ba3 #61: global::Orleans.Streams.IStreamProducerExtension:AddSubscriber()
Exc level 0: Orleans.Runtime.GrainExtensionNotInstalledException: Extension not installed on grain Services.Infrastructure.Grains.Implementations.AppSettingsGrain attempting to invoke type Orleans.Streams.OrleansCodeGenStreamProducerExtensionMethodInvoker from invokable Orleans.Runtime.ActivationData
[2018-03-01 15:13:03 +01:00 WRN] [2018-03-01 14:13:03.177 GMT    13     WARNING 103406  PubSubRendezvousGrain-S127.0.0.1:11111:257609562-*grn/716E8E94/0000000000000000000000000000000006000000716e8e94+SMSProvider_AppSettings-0xBAEA8216      ]       Producer PubSubPublisherState:StreamId=AppSettings-00000000-0000-0000-0000-000000000000-SMSProvider,Producer=GrainReference:*grn/A64CC0FF/00000000. on stream AppSettings-00000000-0000-0000-0000-000000000000-SMSProvider is no longer active - permanently removing producer.
```

I think this warning has to be ignored and is caused by the pub-sub infrastructure, which reads the persisted subscription data and realizes that the former producer grain is gone (due to the restart). Right?

Anyway, the changes are correctly propagated to the `AppSettingsObserverGrain`.

Again, everything works fine so far.

From now on I don't touch the debugger anymore. I simply let the debugger run over night.

The next day I see the following log messages:

```
[2018-03-01 17:14:49 +01:00 INF] <T:[Services.Infrastructure.Grains.Implementations.AppSettingsObserverGrain]> Local observer grain "baea66cccdbd441ea3f4fba2bded6bfb$923ad49009794fb9a5d5007190fbeea8" deactivated.
[2018-03-01 17:44:50 +01:00 WRN] [2018-03-01 16:44:50.048 GMT     7     WARNING 100157  CallbackData    127.0.0.1:11111]        Response did not arrive on time in 00:30:00 for message: Request S127.0.0.1:11111:257609562*grn/A64CC0FF/00000000@a9167ba3->S127.0.0.1:11111:257609562*grn/716E8E94/00000000+SMSProvider_AppSettings@2bb98899 #8239: global::Orleans.Streams.IPubSubRendezvousGrain:UnregisterProducer(). Target History is: <S127.0.0.1:11111:257609562:*grn/716E8E94/00000000+SMSProvider_AppSettings:@2bb98899>. About to break its promise.
[2018-03-01 17:44:50 +01:00 WRN] [2018-03-01 16:44:50.083 GMT    10     WARNING 103402  SimpleMessageStreamProducer`1   127.0.0.1:11111]        Ignoring unhandled exception during PubSub.UnregisterProducer
Exc level 0: System.TimeoutException: Response did not arrive on time in 00:30:00 for message: Request S127.0.0.1:11111:257609562*grn/A64CC0FF/00000000@a9167ba3->S127.0.0.1:11111:257609562*grn/716E8E94/00000000+SMSProvider_AppSettings@2bb98899 #8239: global::Orleans.Streams.IPubSubRendezvousGrain:UnregisterProducer().
Target History is: <S127.0.0.1:11111:257609562:*grn/716E8E94/00000000+SMSProvider_AppSettings:@2bb98899>.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1.<Cleanup>d__28.MoveNext()
```

As you can see, after 2 hours the `AppSettingsObserverGrain` has correctly been deactivated by activation garbage collection.

But after further 30 minutes, an exception occurs:

```
[2018-03-01 17:44:50 +01:00 WRN] [2018-03-01 16:44:50.048 GMT     7     WARNING 100157  CallbackData    127.0.0.1:11111]        Response did not arrive on time in 00:30:00 for message: Request S127.0.0.1:11111:257609562*grn/A64CC0FF/00000000@a9167ba3->S127.0.0.1:11111:257609562*grn/716E8E94/00000000+SMSProvider_AppSettings@2bb98899 #8239: global::Orleans.Streams.IPubSubRendezvousGrain:UnregisterProducer(). Target History is: <S127.0.0.1:11111:257609562:*grn/716E8E94/00000000+SMSProvider_AppSettings:@2bb98899>. About to break its promise.
[2018-03-01 17:44:50 +01:00 WRN] [2018-03-01 16:44:50.083 GMT    10     WARNING 103402  SimpleMessageStreamProducer`1   127.0.0.1:11111]        Ignoring unhandled exception during PubSub.UnregisterProducer
Exc level 0: System.TimeoutException: Response did not arrive on time in 00:30:00 for message: Request S127.0.0.1:11111:257609562*grn/A64CC0FF/00000000@a9167ba3->S127.0.0.1:11111:257609562*grn/716E8E94/00000000+SMSProvider_AppSettings@2bb98899 #8239: global::Orleans.Streams.IPubSubRendezvousGrain:UnregisterProducer().
Target History is: <S127.0.0.1:11111:257609562:*grn/716E8E94/00000000+SMSProvider_AppSettings:@2bb98899>.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1.<Cleanup>d__28.MoveNext()
```

After analyzing the magic strings I made the following observation:

The warning which appears on silo startup contains the following magic strings (I think they are identifying grains and their placements):

```
NewPlacement Request S127.0.0.1:11111:257609562*grn/716E8E94/00000000+SMSProvider_AppSettings@2bb98899->S127.0.0.1:11111:257609562*grn/A64CC0FF/00000000@a9167ba3

Producer=GrainReference:*grn/A64CC0FF/00000000

PubSubRendezvousGrain-S127.0.0.1:11111:257609562-*grn/716E8E94/0000000000000000000000000000000006000000716e8e94+SMSProvider_AppSettings-0xBAEA8216

Producer PubSubPublisherState:StreamId=AppSettings-00000000-0000-0000-0000-000000000000-SMSProvider,Producer=GrainReference:*grn/A64CC0FF/00000000.
```

Now have a look at the strings which are logged after 2.5 hours:

```
Request S127.0.0.1:11111:257609562*grn/A64CC0FF/00000000@a9167ba3->S127.0.0.1:11111:257609562*grn/716E8E94/00000000+SMSProvider_AppSettings@2bb98899

Target History is: <S127.0.0.1:11111:257609562:*grn/716E8E94/00000000+SMSProvider_AppSettings:@2bb98899>.
```

As you can see, some of the strings are matching.

So I blame the "orphaned" producer grain subscription, which is loaded on silo startup, for causing the exception.

Anyway - when I changed the settings of the `AppSettingsGrain` the next morning in order to find out whether the change notification is still working regardless of the exception, everything worked okay. Can I safely ignore the exception?

**Comment by peter-perot** [comment]
According to issue https://github.com/dotnet/orleans/issues/3711 I can ignore the `GrainExtensionNotInstalledException`.

But this does not explain the time out exception thrown from `global::Orleans.Streams.IPubSubRendezvousGrain:UnregisterProducer()`.

**Comment by peter-perot** [comment]
This is the `PubSubGrainState` persisted into a file - I think nothing special to observe here:

```
{
    "$id": "1",
    "$type": "Orleans.Streams.PubSubGrainState, OrleansRuntime",
    "Producers": {
        "$type": "System.Collections.Generic.HashSet`1[[Orleans.Streams.PubSubPublisherState, Orleans]], System.Core",
        "$values": [
            {
                "$id": "2",
                "$type": "Orleans.Streams.PubSubPublisherState, Orleans",
                "Stream": {
                    "$id": "3",
                    "$type": "Orleans.Streams.StreamId, Orleans",
                    "Guid": "00000000-0000-0000-0000-000000000000",
                    "ProviderName": "SMSProvider",
                    "Namespace": "AppSettings"
                },
                "producerReference": {
                    "$type": "Orleans.Streams.OrleansCodeGenStreamProducerExtensionReference, Orleans",
                    "GrainId": "0000000000000000000000000000000003ffffffa64cc0ff",
                    "GenericArguments": ""
                }
            }
        ]
    },
    "Consumers": {
        "$type": "System.Collections.Generic.HashSet`1[[Orleans.Streams.PubSubSubscriptionState, Orleans]], System.Core",
        "$values": [
            {
                "$id": "4",
                "$type": "Orleans.Streams.PubSubSubscriptionState, Orleans",
                "SubscriptionId": {
                    "$id": "5",
                    "$type": "Orleans.Runtime.GuidId, Orleans",
                    "Guid": "443304d0-d381-4686-9dcd-9e05e3434064"
                },
                "Stream": {
                    "$ref": "3"
                },
                "consumerReference": {
                    "$type": "Orleans.Streams.OrleansCodeGenStreamConsumerExtensionReference, Orleans",
                    "GrainId": "441ecdbdbaea66ccfb6bedbda2fbf4a306ffffffbe701f9c+923ad49009794fb9a5d5007190fbeea8",
                    "GenericArguments": ""
                }
            }
        ]
    }
}
```

**Comment by jason-bragg** [comment]
> Extension not installed on grain ..

This can occur on a consumer grain if it deactivated and does not resubscribe to the stream when it reactivates (in OnActivate).  I suggest calling stream.GetAllSubscriptionHandles in the grain's OnActivate, and either resuming or unsubscribing from any existing subscriptions.

> Response did not arrive on time 

Getting this error in the pubsub grain often indicates timeouts when talking to storage.  I'm unfamiliar with the FileStorageProvider, so I can't speculate on how likely it is to be the culprit.  I suggest attempting to duplicate these issues using the memory storage provider.  If the timeout remains, it's not storage, if it goes away, there may be an issue in the storage provider.

Regarding the use of PreferLocalPlacement with streams, if a grain deactivates due to idleness, and is still subscribed to the stream (it does not unsubscribe on deactivate), the next event on the stream will activate it on another silo.  Using sms, the activation will be created on the same silo as the producer of the stream event.

**Comment by peter-perot** [comment]
> Regarding the use of PreferLocalPlacement with streams, if a grain deactivates due to idleness, and is still subscribed to the stream (it does not unsubscribe on deactivate), the next event on the stream will activate it on another silo. Using sms, the activation will be created on the same silo as the producer of the stream event.

Yeah, I know this pitfall, hence I already solved this issue.

* A subscriber grain has a compound key containing a GUID and a string.

* In addition each silo becomes a GUID assigned on startup (and a new GUID on each restart).

* When I activate a subscriber grain, the key is the GUID of the current silo plus an additional string key (a random string, actually also a GUID).

* When a subscriber grain is deactivated (for whatever reason), and it is reactivated, say, by a stream event, then I compare the GUID of the grain to the GUID of the current silo. When they match, everything is fine. If not, I mark the grain "orphaned" and deactivate it in the stream event handler. [Hint: Deactivation in `OnActivateAsync` is not possible, since calling `DeactivateOnIdle` is prohibited from that method.]

* When a grain accessing a subscriber grain sees that it is orphaned (this is always checked), the subscriber grain is also deactivated, and a new grain is created with the correct GUID and a new random string.

* I have a global reference per silo, which is pointing to the last known subscriber grain; this way I avoid having multiple subscribers per silo.

**Comment by jason-bragg** [comment]
On activate logic looks good.

The "is no longer active" error occurs in SMS when a producer was not cleaned up correctly.  This is usually caused by a silo with a producer terminating ungracefully.  It 'should' be benign, as the system will clean itself up.

As far as the FileStorageProvider, the suggestion to try the memory provider was only to rule out the custom storage provider.  There is not much information on what is/was causing the pubsub timeouts..

**Comment by peter-perot** [comment]
I tested again last night with the same scenario (using file storage provider), but I did not get the warning (exception occurred) again. Will keep my eyes on it. Closing the issue for now.
