### ISSUE TITLE
EndpointOptions enhancement concerns/suggestions

### ISSUE THREAD

**Issue by attilah** [dotnet/orleans#4115]
This issue is more about "how to" and not an actual bug.

[```EndpointOptions```](https://github.com/dotnet/orleans/blob/master/src/Orleans.Runtime/Hosting/EndpointOptions.cs) class:

- Options classes generally should be dumb. An options class intialization should not make operations like dns lookup. IOptions infrastructure has better vehicles for such things like an ```IConfigureOptions<EndpointOptions>``` implementation. That would be a much better place to provide default values if it was not provided by the developer in the ```Configure``` method, since Setup runs after it. And the fact that ```Result``` is used on the async operation does not feel right.
- Since ```IPEndpoint``` class contains the Port itself too, so it feels like a duplicated effort to include that separately, especially that the given ```Port``` properties are use to construct the ```IPEndPoint``` instance, but on a contrary there is no way to specify just an IP Address as string to be able to get composed with the individual ```Port``` property.

[```EndpointOptionsExtensions```](https://github.com/dotnet/orleans/blob/master/src/Orleans.Runtime/Hosting/EndpointOptionsExtensions.cs) class:

- These methods are "demoting" the usage of ```IOptions``` by offering extension methods for individual properties, it is not a common pattern with ```IOptions```.
- ```listenOnAllHostAddresses``` should be ```listenOnAnyHostAddress``` based on that later ```IPAddress.Any``` is used. Also this property should be part of the ```EndpointOptions``` class, since it defines behavior

Kestrel is more complex in terms of "listening" capabilities, but since devs are/will be more familiar with it perhaps it should be good to follow their already implemented patterns and as Orleans 2.x will go forward deeper Linux support, SystemD and Linux Sockets support will come some day eventually and the options in Kestrel already having a place for it there.

My suggestion here is to rethink how the IP Address/Ports are exposed in ```EndpointOptions``` based on the above.

** EDIT **

One more thing to add is that Gateway is an "optional" Silo feature, maybe we can have a Silo and Gateway endpoint option separately, especially because of the new ```AdvertisedIPAddress``` property.

**Comment by sergeybykov** [comment]
Resolved via #4158.
