### ISSUE TITLE
Code Review of Orlean.Providers.MongoDB

### ISSUE THREAD

**Issue by laredoza** [dotnet/orleans#4118]
Hi,

We'd appreciate a code review of the rc1 branch ( https://github.com/OrleansContrib/Orleans.Providers.MongoDB/tree/rc1)
There is a test application as well as unit tests.

Packages can be found at https://www.nuget.org/packages/Orleans.Providers.MongoDB

@SebastianStehle has done a significant refactor of the providers(https://github.com/OrleansContrib/Orleans.Providers.MongoDB/issues/26).  

Would it be possible to add this to the Orleans Providers? It feels like MongoDb would be ideal for an opensource Linux enviroment.

**Comment by ReubenBond** [comment]
I added some comments to a new issue here: https://github.com/OrleansContrib/Orleans.Providers.MongoDB/issues/39

**Comment by ReubenBond** [comment]
I'll close this, since the review issue is open
