### ISSUE TITLE
Register InMemoryRemindersTable

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#4120]
There is no registration for this class. Therefore reminders do not work out of the box.

**Comment by SebastianStehle** [comment]
Perhaps not a good idea, because the ReminderTableGrain is not recommended for production, but a better exception message would be good. At the moment I get:

    Orleans.Runtime.OrleansMessageRejectionException: 'SystemTarget *stg/0/00000000 not active on this silo. Msg=Request S127.0.0.1:11111:257964952*grn/D32F2751/000000e3@4389ee96->S127.0.0.1:11111:257964952*stg/0/00000000@S00000000 #40: '

**Comment by sergeybykov** [comment]
@ReubenBond #4091 took care of this, didn't it?

**Comment by ReubenBond** [comment]
I think this issue is about having a default reminder service implementation - but the in-memory one is not suitable for production

**Comment by sergeybykov** [comment]
I don't think we can have a default reminder implementation because it depends on storage for reliability, and reliability is one of the main scenarios for reminders. I'll close it then.
