### ISSUE TITLE
RC2.0 Error when starting

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#4121]
![image](https://user-images.githubusercontent.com/28291464/36941250-13b16738-1f92-11e8-88bb-1ab278cc8de5.png)
![image](https://user-images.githubusercontent.com/28291464/36941256-29587176-1f92-11e8-9f60-b6371563bae6.png)
![image](https://user-images.githubusercontent.com/28291464/36941254-1fd3397e-1f92-11e8-954f-f14a5fc43b6a.png)

**Comment by ReubenBond** [comment]
@aqa510415008 have you configured your database using the SQL scripts?

**Comment by aqa510415008** [comment]
Yes  used

**Comment by aqa510415008** [comment]
@ReubenBond  [4126](https://github.com/dotnet/orleans/issues/4126)
