### ISSUE TITLE
Change the type of the Gateways property in StaticGatewayListProviderOptions in rc1

### ISSUE THREAD

**Issue by akosradler** [dotnet/orleans#4123]
The type of Gateways in StaticGatewayListProviderOptions is IList<Uri>.
The absence of the AddRange method in IList makes adding multiple gateway endpoints in ClientBuilder unnecessarily cumbersome.

Changing it to a List resolves this issue.

**Comment by ReubenBond** [comment]
Apparently, adding a PR also self-assigns the issue

**Comment by benjaminpetit** [comment]
And close the issue automatically when the PR is merged :)
