### ISSUE TITLE
MySQL-Persistence.sql   execution error

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#4126]
![image](https://user-images.githubusercontent.com/28291464/36964119-9ba60e60-2090-11e8-82ac-d9a02a8c64bf.png)

**Comment by veikkoeeva** [comment]
@aqa510415008 Which version of the library are you using? The error looks like the one described at https://stackoverflow.com/questions/1267172/mysql-delimiter-error. Can you retry the script either from the Nuget package or from the repo [here](https://github.com/dotnet/orleans/blob/master/src/AdoNet/Orleans.Persistence.AdoNet/MySQL-Persistence.sql)?

I just took the script from the repo and deployed it, my result is
![MySQL-Persistence.sql](https://user-images.githubusercontent.com/5158694/36979225-7d21fa36-208f-11e8-8232-b961a202d8c2.png)

**Comment by aqa510415008** [comment]
@veikkoeeva MySQL-Persistence.sql problem, but I do not know how to submit contribution, I put the screenshot posted here, change the script in trouble, plus 141 "DELIMITER $$"

**Comment by aqa510415008** [comment]
@vadimzozulya  How to submit contributions

**Comment by veikkoeeva** [comment]
@aqa510415008 It looks like so, the strange thing is the screenshot I shared is by a script I took from the repo and it deployed succesfully. I'm not aware of version differences or any differences here in this regard, but things are possible.

To submit a contribution, you could fork the project (see GitHub forking), make the change, commit, push to your repo and then from GitHub make a PR. There are plenty of tutorials, so I won't go into specifics and refer to one: https://help.github.com/articles/creating-a-pull-request-from-a-fork/.
