### ISSUE TITLE
Observers function can not install the document configuration, please update the document

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#4127]
Observers function can not install the document configuration, please update the document

**Comment by sergeybykov** [comment]
Could you please clarify or give an example.

**Comment by aqa510415008** [comment]
@sergeybykov I found in accordance with the use of the document ObserverSubscriptionManager gone, I think the Observer mechanism has changed, I now see the source code to know how to use Observer, the use of the document is not updated to 2.0 RC

**Comment by ReubenBond** [comment]
@aqa510415008 `ObserverSubscriptionManager` has moved to `Orleans.Core.Legacy`
