### ISSUE TITLE
Bug: PerfCounterEnvironmentStatistics never reports CpuUsage

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#4129]
I think the registration is wrong, because OnStart is never called. 

cpuCounterPF != null, but cpuUsageTimer == null

**Comment by benjaminpetit** [comment]
You are right, it seems we are missing something like `services..AddFromExisting<ILifecycleParticipant<ISiloLifecycle>, PerfCounterEnvironmentStatistics>()` in the extension methods

**Comment by sergeybykov** [comment]
Resolved via #4148.

**Comment by SebastianStehle** [comment]
Still does not work, I think the PR should fix it: https://github.com/dotnet/orleans/pull/4219

**Comment by benjaminpetit** [comment]
Tested manually and it seems that now it works on silo and clients. Thanks!
