### ISSUE TITLE
Silo Host Could not load file or assembly for 3rd party libraries used in Grain implementation project

### ISSUE THREAD

**Issue by narinfinity1** [dotnet/orleans#4144]
Silo Host Could not load file or assembly for 3rd party libraries used in Grain implementation project.
For ex. I'm using NuGet package -> Microsoft.Store.PartnerCenter, Version=1.7.0.0 in Grain implementation project (targets .net framework 4.7.1) and the SiloHost project (targets .netstandard2.0) has -> Microsoft.Store.PartnerCenter.dll in bin folder(SiloHostProject\bin\Debug\netcoreapp2.0), but it throws an exception -> Could not load file or assembly.

**Comment by sergeybykov** [comment]
Is `Microsoft.Store.PartnerCenter` getting copied to SiloHostProject\bin\Debug\netcoreapp2.0?

**Comment by narinfinity1** [comment]
yes, it is getting copied into directory -> SiloHostProject\bin\Debug\netcoreapp2.0

**Comment by ReubenBond** [comment]
Does the SiloHost *reference* Microsoft.Store.PartnerCenter or is it just copied to the output? Could you post the stack trace?

**Comment by narinfinity1** [comment]
if I add NuGet for -> Microsoft.Store.PartnerCenter v1.7 into SiloHost(.netstandard2.0) it will only then load it, otherwise it can not (but Microsoft.Store.PartnerCenter.dll is in directory -> SiloHost\bin\Debug\netcoreapp2.0)

**Comment by ReubenBond** [comment]
@narinfinity1 does your output contain a `*.deps.json` file? If so, could you upload it?

**Comment by sergeybykov** [comment]
If you could also share your silo initialization code, that would help.

**Comment by narinfinity1** [comment]
this is the line where app-parts are registered ->
.ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(MyGrainImpl).Assembly).WithReferences());

**Comment by ReubenBond** [comment]
@narinfinity1 could you include your *.deps.json file & *.runtimeconfig.json file as well as the full error message?
You say the SiloHost is .NET Standard 2.0. Just to be sure, you mean .NET Core 2.0 - is that correct?

**Comment by narinfinity1** [comment]
the files You've mentioned I'll provide later, but the project where the SiloHost is created is a class-lib targetting .netstandars2.0, which is partially compatible with .netcore2.0(includes more apis than .netstandars2.0) and compatible with .net framework 4.7.1(includes much more apis than .netstandars2.0)

**Comment by ReubenBond** [comment]
@narinfinity1 how are you launching the silo host if it targets .NET Standard 2.0 and not an actual runtime?

**Comment by narinfinity1** [comment]
I meant SiloHost is created is a console app (excuse me, I was wrong above by writing -> class-lib) targetting .netstandars2.0

**Comment by ReubenBond** [comment]
@narinfinity1 you cannot create a console app targeting .NET Standard 2.0

**Comment by narinfinity1** [comment]
SiloHost is a .netcoreapp2.0 targeting .netstandard2.0

**Comment by narinfinity1** [comment]
yes, I mean .NET Core 2.0 app for SiloHost

**Comment by ReubenBond** [comment]
No worries, @narinfinity1 :) I'll wait for the deps/runtimeconfig files. Could you show me the .csproj file, too?

**Comment by narinfinity1** [comment]
here the .csproj file content ->

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.Orleans.Clustering.AzureStorage" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.Core" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.Core.Abstractions" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.Core.Legacy" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.OrleansCodeGenerator" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.OrleansProviders" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.Persistence.AzureStorage" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.Server" Version="2.0.0-rc1" />
    <PackageReference Include="System.Data.SqlClient" Version="4.5.0-preview1-26216-02" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Grains\GrainCollection\GrainCollection.csproj" />
    <ProjectReference Include="..\..\Grains\GrainInterfaces\GrainInterfaces.csproj" />
    <ProjectReference Include="..\..\UtilityService\PartnerCenter.Abstraction\PartnerCenter.Abstraction.csproj" />
    <ProjectReference Include="..\..\UtilityService\PartnerCenter.Service\PartnerCenter.Service.csproj" />
  </ItemGroup>

</Project>

**Comment by narinfinity1** [comment]
here the .csproj file ->
`
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.Orleans.Clustering.AzureStorage" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.Core" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.Core.Abstractions" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.Core.Legacy" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.OrleansCodeGenerator" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.OrleansProviders" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.Persistence.AzureStorage" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.Server" Version="2.0.0-rc1" />
    <PackageReference Include="System.Data.SqlClient" Version="4.5.0-preview1-26216-02" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Grains\GrainCollection\GrainCollection.csproj" />
    <ProjectReference Include="..\..\Grains\GrainInterfaces\GrainInterfaces.csproj" />
    <ProjectReference Include="..\..\UtilityService\PartnerCenter.Abstraction\PartnerCenter.Abstraction.csproj" />
    <ProjectReference Include="..\..\UtilityService\PartnerCenter.Service\PartnerCenter.Service.csproj" />
  </ItemGroup>

</Project>
`

**Comment by narinfinity1** [comment]
here the .csproj file content ->
[SiloHost1.csproj.txt](https://github.com/dotnet/orleans/files/1788195/SiloHost1.csproj.txt)

**Comment by ReubenBond** [comment]
@narinfinity1 how do you launch the application?
I believe you need to launch `dotnet` with `--additionalprobingpath PATH_TO_FOLDER_CONTAINING_YOUR_DLL`.

Note that is not an Orleans issue, it's just how .NET Core 2.0 works.

I would suggest that you either reference your library using `<PackageReference>` or using `<Reference>`, What you are trying to do is not typical.

**Comment by narinfinity1** [comment]
in .net 4.7.1 project NuGet packs are referenced like ->
<Reference Include="Microsoft.Store.PartnerCenter, Version=1.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\..\..\packages\Microsoft.Store.PartnerCenter.1.7.0\lib\Net45\Microsoft.Store.PartnerCenter.dll</HintPath>
    </Reference>

**Comment by narinfinity1** [comment]
but .net core project uses these packs in its csproj file like ->
`
<ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.Orleans.Clustering.AzureStorage" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.Core" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.Core.Abstractions" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.Core.Legacy" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.Persistence.AzureStorage" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.Server" Version="2.0.0-rc1" />
  </ItemGroup>

  <ItemGroup>
    
    <ProjectReference Include="..\..\Grains\PartnerCenter.Abstraction\PartnerCenter.Abstraction.csproj" />
    <ProjectReference Include="..\..\Grains\PartnerCenter.Service\PartnerCenter.Service.csproj" />
  </ItemGroup>
`

**Comment by narinfinity1** [comment]
All right, this is the issue of .Net Core, when trying to load  .net framework project's NuGet packs' assemblies, which is not related to Orleans, so many Thanks to Orleans Team!
