### ISSUE TITLE
Silos start running timer

### ISSUE THREAD

**Issue by a641545621** [dotnet/orleans#4149]
What to do when the silo starts running the timer，Not through the client call

 public class Test: Orleans.Grain
    {
        public void TestTime()
        {
            Console.WriteLine("get..");
            TimeSpan t1 = TimeSpan.FromSeconds(10);
            base.RegisterTimer(OnClientRefreshTimer, null, t1 - TimeSpan.FromSeconds(2), t1);
        }

        private async Task OnClientRefreshTimer(object data)
        {
            Console.WriteLine("write");
        }
    }

**Comment by sergeybykov** [comment]
What's the problem/question here? Looks like a correct way to start a grain timer to me. Except if `Test` is a grain class (which looks like it is, as it extends `Orleans.Grain`), then `TestTime()` needs to be invoked from a grain method which is part of a grain interface.

**Comment by a641545621** [comment]
Starting background timers to perform periodic housekeeping tasks.  2.0.0-rc1

**Comment by sergeybykov** [comment]
You can use a bootstrap provider (getting renamed to start task in 2.0) to execute code upon silo startup.
