### ISSUE TITLE
Silo hang while shutdown

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#4150]
Since 2.0 beta, shutdown isn't being properly handled. It never call grain services, stream providers, storage Shutdown()/Close() methods.

While trying to debug the issue, several of those NRE happens and the silo hang:

```

'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\System.Globalization.dll'. Cannot find or open the PDB file.
Exception thrown: 'System.NullReferenceException' in Orleans.Core.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\System.Diagnostics.StackTrace.dll'. Cannot find or open the PDB file.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5\System.Reflection.Metadata.dll'. Cannot find or open the PDB file.
Exception thrown: 'System.Net.Sockets.SocketException' in System.Net.Sockets.dll
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in System.Collections.Concurrent.dll
Exception thrown: 'System.InvalidOperationException' in System.Collections.Concurrent.dll
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll
Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll
Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.OperationCanceledException' in System.Collections.Concurrent.dll
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in System.Collections.Concurrent.dll
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in System.Collections.Concurrent.dll
```

If I enable Orleans debug, I can see it breaks on this exception:

![image](https://user-images.githubusercontent.com/4714040/37073886-50d12e06-21a8-11e8-8b33-86fd12c9bb80.png)

And this one:

![image](https://user-images.githubusercontent.com/4714040/37073897-62fbdf4a-21a8-11e8-9c38-07908e5ecbce.png)

After that, the silo hangs in a state that it never shutdown but is not active either as new activations nor stream messages are being processed. Funny enough, the dump of statistics and Activation Collection is printed on the console as if it were running.

**Comment by benjaminpetit** [comment]
I don't think the `NullReferenceException` is a real bug here, it is just due to the silo stopping.

Grain Services were never stopped, the PR #4135 should fix that.

I am not able to reproduce the issue you are describing with the other providers, could you share the config you are using?

**Comment by galvesribeiro** [comment]
@benjaminpetit There is no config files. I was using code config and that was happening when using either GrainServices or RabbitMQ stream provider. Neither one of those got their Shutdown() methods called. 

Those exceptions may not be related but after they happen nothing else does which led to me believe that the graceful shutdown process somehow had stopped and led the silo in a weird state where it neither receive new activations nor it shutdown the process.

**Comment by benjaminpetit** [comment]
Could you try with the latest master? GrainServices should be fixed now

How do you register the RabbitMQ provider?

**Comment by galvesribeiro** [comment]
@benjaminpetit It was fixed. Closing the issue now.

Thanks!
