### ISSUE TITLE
Silo as IHostedService on Azure App Service

### ISSUE THREAD

**Issue by turowicz** [dotnet/orleans#4156]
**Summary**

It works just fine when there is only one instance within the App Service Plan. Problems start when I scale out.

**Background**

I'm using an App Service Plan with 2x S3 instances inside of it.
The silo is started as a singleton IHostedService that I've implemented.
It is running within a .NET Core 2.0 API that translates the HTTP traffic into Grain calls.
In this scenario GrainClient and Silo are both within the same application.
First silo starts fine.
Second silo gets stuck in "Joining" state, which then transitions to "Dead".

**Configuration**

Orleans version: `2.0-beta3`

SiloConfiguraton.xml
```
<OrleansConfiguration xmlns="urn:orleans">
<Globals>
  <SystemStore SystemStoreType="AzureTable"
               DeploymentId="MyDeployment"
               DataConnectionString="removed-for-github" />
  <Liveness LivenessType="AzureTable" />
</Globals>
<Defaults>
  <Networking Address="" Port="11111" />
  <ProxyingGateway Address="" Port="40000" />
</Defaults>
</OrleansConfiguration>
```

ClientConfiguration.xml
```
<ClientConfiguration xmlns="urn:orleans">
  <SystemStore SystemStoreType="AzureTable"
               DeploymentId="MyDeployment"
               DataConnectionString="removed-for-github" />
</ClientConfiguration>
```

**Questions**

- Should I update to the recently released `2.0-rc1` Orleans?
- Have I provided enough information?

CC @sergeybykov

**Comment by turowicz** [comment]
I'm also having hard time getting App Insights to show anything in there. 

Using the following method doesn't cut it:

```
dotnet add package Microsoft.Orleans.OrleansTelemetryConsumers.AI
...
config.AddPerfCountersTelemetryConsumer(key);
```

**Comment by turowicz** [comment]
Forgot to mention, I add the `Orleans.Storage.AzureBlobStorage` in runtime.

**Comment by sergeybykov** [comment]
Do you configure a virtual network for ports 11111 and 40000 to be accessible from other instances?

**Comment by turowicz** [comment]
Hey I did create a vnet thinking this might help for cluster node communication but I think I may need some help setting this up correctly.

**Comment by turowicz** [comment]
I'm trying to make the silos to listen on the vnet IPs... will let you know if this makes a difference.

**Comment by turowicz** [comment]
@sergeybykov do you think it is possible to run a Silo in App Service?

**Comment by sergeybykov** [comment]
I don't. I suggest you ask people in https://gitter.im/dotnet/orleans. Silos just need network connectivity between nodes and silo and gateway ports open in the firewall.

**Comment by Liversage** [comment]
> do you think it is possible to run a Silo in App Service with instance count >1?

No, I don't think it is possible. As far as I know an App Service is proxied by a web server listening on port 80 and 443. Running one instance works fine because your process listens on the loopback adapter without any "real" network communication. However, if you scale out the instances are unable to communicate.

You can connect an App Service to a Virtual Network using VNET Integration. This allows you to host your Orleans cluster on VMs or some other "execution mechanism" and connect an Orleans client in the App Service to the cluster connected to the Virtual Network.

**Comment by turowicz** [comment]
That's what I'll have to do then. It would be so nice if Orleans could work on App Service. I did try to make it work by detecting which port is the process listening on but even though port was open they couldn't connect over the "internal" network - probably due to proxy that you mention.
