### ISSUE TITLE
Client is not initialized. Current client state is Created.

### ISSUE THREAD

**Issue by hanxinimm** [dotnet/orleans#4163]
ServiceFabric RunAsync Finish : 
protected override async Task RunAsync(CancellationToken cancellationToken)
        {
            // Creat the client and connect to the cluster.
            GrainFactory.PayQuery = GrainFactory.CreateFromFabricClient("fabric:/PayApp/StatelessQueryService");

            await GrainFactory.PayQuery.ConnectAsync();

        }

**Comment by ReubenBond** [comment]
@hanxinimm what's `GrainFactory.CreateFromFabricClient`?

I need much more detail to be able to help you.

**Comment by hanxinimm** [comment]
@ReubenBond 

 internal static IClusterClient CreateFromFabricClient(string serviceName, FabricClient fabricClient = null)
        {
            return new ClientBuilder()
                .UseConfiguration(new ClientConfiguration())
                .UseServiceFabricClustering(new Uri(serviceName))
                .ConfigureServices(
                    services =>
                    {
                        // Some deployments require a custom FabricClient, eg so that cluster endpoints and certificates can be configured.
                        // A pre-configured FabricClient can be injected.
                        services.AddSingleton(fabricClient ?? new FabricClient());
                    })
                .ConfigureApplicationParts(parts => parts.AddFromApplicationBaseDirectory())
                .Build();
        }

**Comment by ReubenBond** [comment]
@hanxinimm when client initialization fails, you need to destroy and create the client completely, using a new `ClientBuilder`.

We are looking at implementing internal connection retries in #4161

**Comment by hanxinimm** [comment]
Can I do it like this?

```
internal static Lazy<Task<IClusterClient>> Initialize(string serviceName, FabricClient fabricClient = null)
        {
            var client = CreateFromFabricClient(serviceName, fabricClient);

            return new Lazy<Task<IClusterClient>>(async () =>
            {
                await client.ConnectAsync().ConfigureAwait(false);
                return client;
            });
        }
```

```
internal static IClusterClient CreateFromFabricClient(string serviceName, FabricClient fabricClient = null)
        {
            return new ClientBuilder()
                .UseConfiguration(new ClientConfiguration())
                .UseServiceFabricClustering(new Uri(serviceName))
                .ConfigureServices(
                    services =>
                    {
                            // Some deployments require a custom FabricClient, eg so that cluster endpoints and certificates can be configured.
                            // A pre-configured FabricClient can be injected.
                            services.AddSingleton(fabricClient ?? new FabricClient());
                    })
                .ConfigureApplicationParts(parts => parts.AddFromApplicationBaseDirectory().WithCodeGeneration())
                .Build();
        }
```

```
   static void Main(string[] args)
        {
            GrainFactory.IDCreator = GrainFactory.Initialize("fabric:/StatelessWorkApp/StatelessWorkService");
            Run(args).Wait();
        }

        private static async Task Run(string[] args)
        {

            var client = await GrainFactory.IDCreator.Value;
            var calculator = client.GetGrain<Labor.Work.ICommandHandler.IIDCreatorHandler>(0, keyExtension: "HolidayWork");

            var i = await calculator.ExecuteAsync();

            Console.WriteLine(i);
        }
```

**Comment by ReubenBond** [comment]
@hanxinimm the `ClusterClient.Connect()` call might fail. If it fails, the client must be destroyed and recreated.

I believe that #4161 allows you to fix the issue by specifying a retry delegate.

**Comment by hanxinimm** [comment]
my provisional solution :
```
  internal static Lazy<Task<IClusterClient>> Initialize(string serviceName, FabricClient fabricClient = null)
        {

            return new Lazy<Task<IClusterClient>>(async () =>
            {
                int attempt = 0;
                while (true)
                {
                    var client = CreateFromFabricClient(serviceName, fabricClient);

                    try
                    {
                        await client.Connect();
                        return client;
                    }
                    catch (SiloUnavailableException)
                    {
                        attempt++;
                        if (attempt > 3)
                        {
                            throw;
                        }
                        await Task.Delay(TimeSpan.FromSeconds(4));
                    }
                }
            });
        }
```

#4161  next release can I use it?

**Comment by ReubenBond** [comment]
@hanxinimm yes, you can - I hope it helps

**Comment by ReubenBond** [comment]
We merged the referenced issue, so this is rectified.
