### ISSUE TITLE
Will the 2.0RC version of the cluster how to configure?

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#4167]
Will the 2.0RC version of the cluster how to configure?

**Comment by ReubenBond** [comment]
What do you want to configure, @aqa510415008 ?

**Comment by aqa510415008** [comment]
Compared to version 1.5, the configuration of version 2.0 has changed a lot. Find a Demo

**Comment by aqa510415008** [comment]
@ReubenBond I am not familiar with the working principle of Orleans cluster, beginner.

**Comment by ReubenBond** [comment]
There are some 2.0 samples here: https://github.com/dotnet/orleans/tree/master/Samples/2.0
Some 2.0 documentation here: http://dotnet.github.io/orleans/Documentation/2.0/Configuration2.0.html

Most of the 2.0 documentation has not been written yet.

**Comment by aqa510415008** [comment]
@ReubenBond There is no description of this, the configuration of the cluster

**Comment by ReubenBond** [comment]
If you want to configure the cluster id, you can use: `builder.Configure<ClusterOptions>(options => options.ClusterId = "cluster id");`

For configuring cluster membership, you need to use one of the Use*Clustering methods, like UseDevelopmentClustering(), UseAzureStorageClustering(), etc
