### ISSUE TITLE
When Silo shutdown, Grain deactivation is happening too late in the lifecycle

### ISSUE THREAD

**Issue by benjaminpetit** [dotnet/orleans#4174]
Silo will accept new activation in the `Active` state, but will deactivate its grain activation only at stage `RuntimeServices` which is happening after the `ApplicationServices` state.

It will cause issue if the grain implementation rely on a component that is dependant on the `ApplicationServices` state (like storage providers...)

**Comment by sergeybykov** [comment]
Resolved via #4177.
