### ISSUE TITLE
Can I use Grain like this?

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#4178]
![image](https://user-images.githubusercontent.com/28291464/37198769-5a20d380-23ba-11e8-88e9-557e8e4a09fd.png)
![image](https://user-images.githubusercontent.com/28291464/37198881-bb6d189c-23ba-11e8-86fe-5f0573c13d8d.png)

`  var ta = await ser.GetMessage1(name);`  error when executing：

![image](https://user-images.githubusercontent.com/28291464/37198458-4d0c3d34-23b9-11e8-9e97-9bb7fccdb9cf.png)

If you change  `ITest1Service<TTest>`  to  `ITest1Service`

Don't know if the above example is not allowed or have other problems?

**Comment by ReubenBond** [comment]
@aqa510415008 why do the interfaces implement 2 `IGrainWithXXXKey` interfaces? They should implement only one.

Otherwise, the code looks ok.

**Comment by aqa510415008** [comment]
@ReubenBond When using the generic interface method error? I do not know how it is? Do not need me to provide further code, check what is the problem?

**Comment by ReubenBond** [comment]
@aqa510415008 I don't quite understand what you're saying. Yes, providing the code would help me to understand what's happening.

**Comment by aqa510415008** [comment]
@ReubenBond The above code is all my code, I do not know what is missing?

**Comment by sergeybykov** [comment]
You cannot declare a grain interface as
```csharp
ITestService : IGrainWithIntegerKey, IGrainWithGuidKey
```
You need to choose between
```csharp
ITestService : IGrainWithIntegerKey
```
and
```csharp
ITestService : IGrainWithGuidKey
```

**Comment by aqa510415008** [comment]
@sergeybykov  However, this method can be used normally
`ITestService : IGrainWithIntegerKey, IGrainWithGuidKey`

**Comment by ReubenBond** [comment]
@aqa510415008 do you also have `ITest1Service` defined with no generic parameters?

**Comment by aqa510415008** [comment]
@ReubenBond  `ITest1Service` Define generic parameters, you can see the first layer of code

**Comment by ReubenBond** [comment]
@aqa510415008 are you able to upload a full repository which can reproduce this error?

**Comment by aqa510415008** [comment]
[HelloWorld.zip](https://github.com/dotnet/orleans/files/1809864/HelloWorld.zip)
This code can reproduce errors?

**Comment by ReubenBond** [comment]
![image](https://user-images.githubusercontent.com/203839/37387506-c272ecbc-27b0-11e8-9b77-a16c01a4a157.png)

The TestEntity class is duplicated

**Comment by aqa510415008** [comment]
HelloWorld.Grains.TestEntity   Not used

**Comment by ReubenBond** [comment]
Removing it fixes your issue

**Comment by aqa510415008** [comment]
@ReubenBond  
The problem has been reproduced and used
    `Var svr = this.GrainFactory.GetGrain<IHello<TestEntity>>(0)`
  Error in `IIncomingGrainCallFilter
[HelloWorld.zip](https://github.com/dotnet/orleans/files/1810116/HelloWorld.zip)



`

**Comment by ReubenBond** [comment]
Okay, thanks - I see the issue. I'll try to fix it.

**Comment by aqa510415008** [comment]
@ReubenBond Thank you, you guys also worked hard

**Comment by ReubenBond** [comment]
@aqa510415008 I opened #4233 for the issue you're seeing, so I will close this issue
