### ISSUE TITLE
Correct way to add GrainCallFilter

### ISSUE THREAD

**Issue by jsteinich** [dotnet/orleans#4184]
The extension methods `AddGrainCallFilter` are marked as obsolete, but after https://github.com/dotnet/orleans/pull/4091 the methods they say to use instead have been made internal.

Should either remove obsolete designation, put other methods back to public, or create and link to a desired implementation.

**Comment by sergeybykov** [comment]
Take a look at `AddIncomingGrainCallFilter` and `AddOutgoingGrainCallFilter` extension methods for `ISiloHostBuilder` and are part of `SiloHostBuilderGrainCallFilterExtensions`.

**Comment by jsteinich** [comment]
Thanks. That did the trick. I was still trying to use IServiceCollection extensions.
