### ISSUE TITLE
Problems using `Microsoft.Orleans.TestingHost` in a separate .NET Core console app

### ISSUE THREAD

**Issue by alexandrnikitin** [dotnet/orleans#4186]
I want to use the Test Cluster in a separate console app, so I create one and reference the latest `2.0.0-rc1` `Microsoft.Orleans.TestingHost`.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.5</RuntimeFrameworkVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.TestingHost" Version="2.0.0-rc1" />
  </ItemGroup>

</Project>

```

```
using Orleans.TestingHost;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var host = new TestClusterBuilder(1).Build();
            host.Deploy();
        }
    }
}
```

Launching it throws the following exception:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
```

I install the latest `2.1.0-preview1-final` `Microsoft.Extensions.Configuration.Binder` package (which is referenced by `Microsoft.Orleans.TestingHost`)
```
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="2.1.0-preview1-final" />
```

Then it throws this:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Orleans.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

I install all direct latest dependencies of `Microsoft.Orleans.TestingHost`

```
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.Orleans.Core" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.OrleansProviders" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.OrleansRuntime" Version="2.0.0-rc1" />
    <PackageReference Include="Microsoft.Orleans.TestingHost" Version="2.0.0-rc1" />
  </ItemGroup>

```
It prints starting messages and throws `System.TypeLoadException`:

```
----------------------------- STARTING NEW UNIT TEST SILO HOST: Orleans.TestingHost.TestCluster -------------------------------------
Starting a new silo in app domain Primary


Unhandled Exception: System.TypeLoadException: Could not load type 'System.AppDomainSetup' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```

The same happens if I have references to Grain interfaces and Grains library projects from that console app. What am I doing wrong?

**Comment by Liversage** [comment]
Perhaps replacing the `TargetFramework` element with

    <TargetFramework>net47</TargetFramework>

or another recent full framework version of your liking will fix the problem? The `Microsoft.Orleans.TestingHost` NuGet package is declared to only have dependencies for `.NETFramework 4.6.1`. Of course you will only be able to run this on Windows.

**Comment by alexandrnikitin** [comment]
@Liversage Oh yes, that could be the reason. I didn't check that and thought that it has .NET Core support (I don't know why; probably because of its version `2.0.0-...` or because it compiled 😄 ) I'll try to check that tomorrow. I'm closing it for now. Thank you!

**Comment by alexandrnikitin** [comment]
Issue to track: #3032
