### ISSUE TITLE
Search grains by value in state. Is it possible?

### ISSUE THREAD

**Issue by KSemenenko** [dotnet/orleans#4187]
I have a problem, I need to find all grains with a certain value in their state.
For example, a grain in a state has a variable IsOnline and I would like to get a list of all such grains.
Now I'm doing this with queries in the repository (I'm using CosmosDB) but maybe there is a better way?

**Comment by sergeybykov** [comment]
As of today, querying directly in storage or building your own indexing solution are the only two options.

https://github.com/OrleansContrib/Orleans.Indexing is being actively worked on in Research to provide a better built in experience. We expect a 2.0-compatible version in a few months.

/cc @philbe

**Comment by sergeybykov** [comment]
Take a look also at #602 and #3413.

**Comment by KSemenenko** [comment]
Thank you for your responses @sergeybykov
