### ISSUE TITLE
Removing a grain interface from the project fails the build

### ISSUE THREAD

**Issue by alexandrnikitin** [dotnet/orleans#4189]
How to reproduce:

1. Create a new project for grain interfaces
2. Reference `Microsoft.Orleans.OrleansCodeGenerator.Build` `2.0.0-rc1` and `Microsoft.Orleans.Runtime.Abstractions` `2.0.0-rc1`
3. Add two grain interfaces
4. Build the project so that the code will be generated
5. Remove one interface and rebuild the project
6. Build fails with the following output
```
1>------ Rebuild All started: Project: DMCTS.GrainInterfaces, Configuration: Debug Any CPU ------
1>obj\Debug\netcoreapp2.0\DMCTS.GrainInterfaces.orleans.g.cs(19,305,19,317): error CS0234: The type or namespace name 'ITreeGrainV2' does not exist in the namespace 'DMCTS.GrainInterfaces' (are you missing an assembly reference?)
1>obj\Debug\netcoreapp2.0\DMCTS.GrainInterfaces.orleans.g.cs(87,192,87,204): error CS0234: The type or namespace name 'ITreeGrainV2' does not exist in the namespace 'DMCTS.GrainInterfaces' (are you missing an assembly reference?)
1>obj\Debug\netcoreapp2.0\DMCTS.GrainInterfaces.orleans.g.cs(20,127,20,139): error CS0234: The type or namespace name 'ITreeGrainV2' does not exist in the namespace 'DMCTS.GrainInterfaces' (are you missing an assembly reference?)
1>Done building project "DMCTS.GrainInterfaces.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

Deleting `obj` directory helps.

**Comment by sergeybykov** [comment]
> 5. Remove one interface and rebuild the project

Did you rebuild it with `Build Solution` or `Rebuild Solution`? The latter should work.

**Comment by alexandrnikitin** [comment]
I tried both, neither works. Actually `Build Solution` shows that the project is up-to-date, keep silence and doesn't show any error. But I believe it doesn't change the generated code which isn't correct.

**Comment by sergeybykov** [comment]
What version of VS are you running? I just tried the following code, and both `Build Solution` and `Rebuild Solution` work fine after I comment out one of the interfaces.
```csharp
using Orleans;
using System.Threading.Tasks;

namespace FooBar
{
    public interface IFoo : IGrainWithGuidKey
    {
        Task Foo();
    }

    public interface IBar : IGrainWithGuidKey
    {
        Task Bar();
    }
}
```

What am I doing differently? I'm running VS 15.6.1.

**Comment by alexandrnikitin** [comment]
I have the interfaces in separate files and delete the file.

**Comment by sergeybykov** [comment]
I see. Yes, I was able to repro this. `Clean Solution` before `Build Solution` fixes it. But it's a problem that `Rebuild Solution` doesn't do the same.

**Comment by alexandrnikitin** [comment]
I've just double checked: `Clean Solution` then `Build Solution` didn't help either. Only deleting the `obj` directory with generated code helped me. I'm using VS 15.6.1.

**Comment by sergeybykov** [comment]
You are right, `Clean Solution` doesn't seen to help. I don't know what I did differently the first time.

**Comment by ReubenBond** [comment]
Ah, I see the problem.
I tried reproducing this as Sergey did: by having both interfaces in one file, but it wouldn't repro.
The reason it fails when the interface is in its own file is that all of the files in the expanded `@(Compile)` item list have a modification time older than the generated file.

Now we just need to work out a way to fix this.
