### ISSUE TITLE
Orleans.OrleansCodeGenerator.Build Failed to execute

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#4206]
![image](https://user-images.githubusercontent.com/28291464/37336461-67e10050-26ec-11e8-8746-aa2eb16bb703.png)

**Comment by aqa510415008** [comment]
There may be a problem with this place
![image](https://user-images.githubusercontent.com/28291464/37338547-bd6de154-26f2-11e8-9b7e-957ad1416540.png)

**Comment by aqa510415008** [comment]
I know the problem is because of an attribute I added in Grain's interface
![image](https://user-images.githubusercontent.com/28291464/37338774-6ad7d69c-26f3-11e8-8b89-04c60be44797.png)

**Comment by ReubenBond** [comment]
Thanks for reporting, @aqa510415008.

Properties are not supported on grain interfaces, but we should be reporting an error instead of throwing an `IndexOutOfRangeException`.

**Comment by ReubenBond** [comment]
@aqa510415008 I was unable to reproduce this error:

![image](https://user-images.githubusercontent.com/203839/37372978-de476582-2768-11e8-89a2-d60a139f54eb.png)

By the way, do not add *both* `IGrainwithIntegerKey` and `IGrainWithGuidKey` to a single interface: choose one.

**Comment by aqa510415008** [comment]
@ReubenBond Does the problem reappear? If I do not need to provide an instance?

**Comment by ReubenBond** [comment]
@aqa510415008 it does not.

**Comment by aqa510415008** [comment]
After I upgraded RC2.0, there was no way to reproduce this situation. I will close this question first.
