### ISSUE TITLE
[2.0 RC2 ] Invalid configuration using IServiceCollection.UseAdoNetReminderService

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#4208]
![image](https://user-images.githubusercontent.com/28291464/37348401-ee2b09d6-270e-11e8-841a-85f340b4ebc8.png)
![image](https://user-images.githubusercontent.com/28291464/37348466-13caa52a-270f-11e8-93d0-dc3aa4e655a5.png)

**Comment by AdamWyzgol** [comment]
duplicate of #4207

**Comment by sergeybykov** [comment]
Closing in favor of #4207.
