### ISSUE TITLE
Is IServiceCollection.AddScoped seemingly invalid in Orleans?

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#4229]

**Comment by ReubenBond** [comment]
@aqa510415008 each grain activation has its own scope, so when you call AddScoped, you are adding a service which is created per activation

**Comment by xiazen** [comment]
Thanks reuben for answering. @aqa510415008 does this answer your question? or do you have further questions?

**Comment by aqa510415008** [comment]
@ReubenBond @xiazen Thank you, I understand
