### ISSUE TITLE
Chirper Scale Subscriber (Follower)

### ISSUE THREAD

**Issue by rjcdn** [dotnet/orleans#4230]
Is there a limit to the number of subscribers of a publisher? Example: users with 20 million followers each. pub-sub cache in Pulling Protocol resolves this? I've seen Benchmarks in [https://www.researchgate.net/publication/233416056_Orleans_Cloud_Computing_for_Everyone](url), but the example each user only has 27 followers each. I'm having a Fan-out-on-write feed project and would like to know if this is the correct way?
Thanks

**Comment by sergeybykov** [comment]
For a large number of subscribers, you need a more sophisticated implementation with state and computation spread over space and time. The potential pattern here is two have two grain classes, one for regular users and one for "super-users" with large numbers of followers, and to promote a user from former to the latter when necessary.

**Comment by rjcdn** [comment]
Thanks very much
