### ISSUE TITLE
Generic interface, non-generic grain causes Exception from Method property in interceptor

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#4233]
The following code demonstrates an issue which occurs in `IIncomingGrainCallFilter` implementations when accessing `IGrainCallContext.Method` from a non-generic grain which is called using a generic reference. For example, calling `CaterpillarGrain` below using `IHungryGrain<Apple>` will reproduce this issue.

```C#
public interface IHungryGrain<T> : IGrainWithIntegerKey
{
  Task Eat(T food);
}

public interface ICaterpillarGrain : IHungryGrain<Apple> { }

public class CaterpillarGrain :
  Grain,
  ICaterpillarGrain,
  IHungryGrain<Apple>,
  IIncomingGrainCallFilter
{
  Task IIncomingGrainCallFilter.Invoke(IIncomingGrainCallContext ctx)
  {
    // System.InvalidOperationException: Type CaterpillarGrain does not
    // implement interface with id -1378928681 (ADCF37D7)
    Console.WriteLine(ctx.Method);
    return ctx.Invoke();
  }

  Task Eat(Apple food) => Task.CompletedTask;
}

// Causes exception:
var generic = grainFactory.GetGrain<IHungryGrain<Apple>>(0);
await generic.Eat(new Apple("Jazz"));

// No exception:
var nonGeneric = grainFactory.GetGrain<ICaterpillarGrain>(0);
await nonGeneric.Eat(new Apple("Jazz"));
```

Workaround: Access the grain using a non-generic interface. In the above example, this is `ICaterpillarGrain`

xref: #4178

**Comment by pentp** [comment]
Ran into this issue today. Grains with generic interfaces work as expected otherwise, but logging is a problem.

**Comment by petriashev** [comment]
I have the same problem with activated Orleans.Dashboard.

**Comment by petriashev** [comment]
Repro: https://github.com/OrleansContrib/OrleansDashboard/issues/260#issuecomment-537672807
