### ISSUE TITLE
How to configure Default Collection Age Limit in Orleans 2.0

### ISSUE THREAD

**Issue by KSemenenko** [dotnet/orleans#4247]
Hello,
I need to configure Default Collection Age in Orleans 2.0.
Could you please, tell me how can I do this?
I found this documentation, but it's not for Orleans 2.0
http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Activation-Garbage-Collection.html

I think it's related to #4244

**Comment by sergeybykov** [comment]
`GrainCollectionOptions` are now for that, and they can be configured via `ISiloHostBuilder.Configure<GrainCollectionOptions>( options => { options.x = y; })` like any other options I the new configuration API.

We need to document this really soon.

**Comment by KSemenenko** [comment]
Thanks for your answer @sergeybykov 
I like this modified syntax. but need documentation what settings exist
Once again more thanks!

**Comment by sergeybykov** [comment]
We are working on more documentation, but contributions are always welcome - https://github.com/dotnet/orleans/tree/gh-pages/src. 😊

**Comment by sergeybykov** [comment]
Documented in dotnet.github.io/orleans/Documentation/Advanced-Concepts/Activation-Garbage-Collection.html.
