### ISSUE TITLE
Orleans 2.0-rc2 - enums with GeneratedCode attribute cannot be serialized by grain client

### ISSUE THREAD

**Issue by engenb** [dotnet/orleans#4248]
First off, I want to be very clear that I don't see this as an issue per se.  Just FYI in case others deem this worthwhile to deal with.

My grain interfaces project referenced a common business model project with classes generated from an xml schema codegen tool, adding `[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]` to each class.  This was fine with Orleans 1.5, but not with 2.0.  In 2.0, *some* types from this package with this `GeneratedCode` attribute are not serializable - particualrly enums.

Again, not a real issue as it's simple enough for me to remove this attribute.  We're considering separating our silo business models from the xml generated ones anyway, so I'm good.  Just posting this in case others encounter this issue or if people feel it's worth resolving.

**Comment by ReubenBond** [comment]
Thanks, @engenb 
I opened #4249 with a fix
