### ISSUE TITLE
Azure Table API with Orleans rc2

### ISSUE THREAD

**Issue by mikuam** [dotnet/orleans#4251]
Is it possible to use persist grain state in Azure Table API or any other Azure storage? I'm trying to configure it but I haven't found any useful example. Is it ready?

I'm referring to Orleans on .net core.

**Comment by miker1423** [comment]
I've been working on the migration path from 1.5.x to 2.0.0 when running on azure, you might want to look at my fork [this is where I'm adding everything](https://github.com/miker1423/orleans/blob/ef202235067cd422b4e94b85a68158dd49361b85/src/Documentation/2.0/MigrationAzure2.0.md)

**Comment by sergeybykov** [comment]
Documentation is coming. In the meantime, look for `AddAzureTableGrainStorage` extension methods on `ISiloHostBuilder` and similar methods for other providers.

**Comment by mikuam** [comment]
I configured my Azure Table storage and state is saved to CosmosDB, but it also throws an exception: _Transaction 50001 aborted because of Wait-Die cycle prevention_

This is my configuration:
`            var builder = new SiloHostBuilder()
                .UseLocalhostClustering()
                .Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Loopback)
                .ConfigureServices(context => ConfigureDI(context))
                .ConfigureLogging(logging => logging.AddConsole())
                .UseInClusterTransactionManager()
                .UseInMemoryTransactionLog()
                .AddAzureTableGrainStorageAsDefault(
                    (options) => {
                        options.ConnectionString = CosmosBDConnectionString;
                        options.UseJson = true;
                    })
                .UseTransactionalState();

            var host = builder.Build();
            await host.StartAsync();
            return host;`

And this is my grain:
`    [Serializable]
    public class Balance
    {
        public decimal Value { get; set; } = 0;
    }
    
    public class AccountGrain : Grain<Balance>, IAccountGrain
    {
        private readonly IServiceBusClient serviceBusClient;

        private readonly ITransactionalState<Balance> balance;

        public AccountGrain(
            IServiceBusClient serviceBusClient,
            [TransactionalState("balance")] ITransactionalState<Balance> balance)
        {
            this.serviceBusClient = serviceBusClient;
            this.balance = balance ?? throw new ArgumentNullException(nameof(balance));
        }

        async Task IAccountGrain.Deposit(decimal amount)
        {
            try
            {
                this.State.Value += amount;
                await this.WriteStateAsync();

                await NotifyBalanceUpdate();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }

        async Task IAccountGrain.Withdraw(decimal amount)
        {
            this.balance.State.Value -= amount;
            this.balance.Save();

            await NotifyBalanceUpdate();
        }

        Task<decimal> IAccountGrain.GetBalance()
        {
            return Task.FromResult(this.balance.State.Value);
        }

        private async Task NotifyBalanceUpdate()
        {
            var balanceUpdate = new BalanceUpdateMessage
            {
                AccountNumber = (int)this.GetPrimaryKeyLong(),
                Balance = this.balance.State.Value
            };

            var message = new Message(Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(balanceUpdate)));
            await serviceBusClient.SendMessageAsync(message);
        }
    }`

This code is based on one of the samples, but I added sending Service Bus messages.

**Comment by jason-bragg** [comment]
I'm not up to speed on cosmoDB, so I can't say what would happened if you pointed code built against azure tables at a cosmoDB server.  I can say we've never tested nor support that pattern.  The azure table grain storage is build and tested to run against azure table storage using azure storage connection strings.

On a side note, I'm not clear what the grain logic is trying to do.  The Deposit uses the grains state, which goes to grain storage of the default storage provider, while the withdraw reads from the transactional state facet.  These are not the same data, one (balance) is transactional, the other (State) is not.  Further, the notifications to service bus will happened even if a transaction fails, so the data in service bus may not reflect the current or committed balance.

**Comment by mikuam** [comment]
Hey, thanks for the help! After I fixed state handling in the grain it started to work. I also updated my code to full version 2.0 and it also works with Cosmos DB Table API.

I have put my code in GitHub repo: https://github.com/mikuam/orleans-core-example
and make a blog post about it: http://www.michalbialecki.com/2018/04/03/add-cosmosdb-persistent-storage-to-microsoft-orleans-in-net-core/

**Comment by sergeybykov** [comment]
@mikuam That's great! But I see you left a key there - https://github.com/mikuam/orleans-core-example/blob/master/MichalBialecki.com.OrleansCore.AccountTransfer.Grains/ServiceBusClient.cs#L9.

**Comment by mikuam** [comment]
Fixed, thank you :)

**Comment by sergeybykov** [comment]
Make sure you roll the key. Otherwise, too many people have it by now. :-)

**Comment by mikuam** [comment]
Done, thanks :)
