### ISSUE TITLE
What is PubSubStore for? Running one night will produce more than 140,000 data

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#4260]
What is PubSubStore for? Running one night will produce more than 140,000 data

**Comment by sergeybykov** [comment]
This is where stream subscription information is stored.

**Comment by ReubenBond** [comment]
@aqa510415008 you could use in-memory storage for `PubSubStore`, but just be aware that it means that your subscriptions can disappear.

**Comment by aqa510415008** [comment]
@ReubenBond Thank you for your advice, I also plan to try Redis, but there is a situation where there is too much data, I do not want to save, I do not know whether it can be achieved?

**Comment by jason-bragg** [comment]
@aqa510415008, What version of orleans are you using?

The amount of data in the pubsub should be proportional to the number of active producers and consumers.  Assuming producers and consumers are being cleaned up correctly, this data should not grow indefinitely, but only with active load.  So if your service, at peak load, stores 140,000 (k, mb, something?) data in storage, it shouldn't grow beyond that.  If it does, there may have some sort of resource leak in the service code.  For instance, not unsubscribing from streams when they become inactive, or dead producers left over from ungraceful shutdown of silo.

Safest way to avoid pubsub state is to use implicit subscriptions, assuming the application needs fit the pattern.

One can also cleanup pubsub state programmatically using the IStreamSubscriptionManager, assuming one knows the stream Id's of inactive streams.

As @ReubenBond suggested, if the service can accept data loss during silo crashes and the stream subscriptions do not need to live beyond a specific cluster deployment, using memory storage for pubsub state may be a viable solution.

**Comment by aqa510415008** [comment]
@jason-bragg use orleans 2.0RC

**Comment by jason-bragg** [comment]
@aqa510415008 what grain storage implementation are you using for the pubsub?

Subscriptions are persistent.  You need to unsubscribe to remove the subscription, or they will remain forever.  Are you doing that?

**Comment by aqa510415008** [comment]
@jason-bragg Is the subscription still stored after the subscription is completed? Can I choose not to store it?
