### ISSUE TITLE
Support for Method Invoke Attributes on Interface to apply to all methods

### ISSUE THREAD

**Issue by jsteinich** [dotnet/orleans#4263]
I'm running into a case where I am adding an attribute (specifically `TransactionAttribute`) to all methods on a grain interface. It would be nice to instead add the attribute to the interface and have it apply to all methods.

It looks like this would involve changing `GrainReferenceGenerator.GenerateInvokeMethods()` to generate the invoke options for the interface and then merge with individual method options into the invocation expression.

I'm happy to work on a PR for this, but I wanted to get some feedback before pursuing.

**Comment by sergeybykov** [comment]
We discussed this offline. The concern is that allowing for the attribute at the interface level, while a shortcut for some, will promote a wrong approach to attributing transactional methods. We think it is rather rare that all methods in an interface need the same level of transactionality: required, required new, read-only.

Hence, the belief is that the modest overhead of explicitly adding the attribute on each method will emphasize the right application and granularity of the attribute.

**Comment by jsteinich** [comment]
For our uses, this is likely to be a common occurrence (a read-only `TransactionOption` would change that). I can see it not being generally the case though. I'm fine having the over-head, but maybe it's worth explaining our uses a bit more.
We tend to have a tiered approach where required new transactions exist on one tier which talks to a lower tier that has required transactions.
More concretely, we have messages coming in from an external client. Each message gets processed in a transaction. As part of the transaction, some amount of grains are accessed and/or modified.
