### ISSUE TITLE
How to determine message is delivered on OneWay mode ？

### ISSUE THREAD

**Issue by csyszf** [dotnet/orleans#4268]
Seems orleans send self a rejection response message while request message fail to send
but in OneWay mode,  error message will not throw so i can't catch it

is there any way could ensure message will arrive in OneWay mode?

**Comment by ReubenBond** [comment]
The purpose of `[OneWay]` is to eliminate response messages, so it should only be used when you do not need to know if a message was delivered or if you are using some other mechanism to determine that.

Could you explain your use case?

**Comment by csyszf** [comment]
@ReubenBond I need send some ordered events to grains, those events will not cause any exceptions and no need for response, so the only issue is network connection.

You're right, either inspect all the request-response flow, or never concern about it at all.
but i think throw request layer exception immediately will be good for some custom retry/fault-handling policies.

**Comment by ReubenBond** [comment]
What if there's a fault on the remote end after you've sent the message?

**Comment by csyszf** [comment]
Caller only be focus on its own duty (deliver events to handler grains), and it fully trust handlers' logic,
exceptions happened only if network failure, and in this case remote end will lose those data.
it doesn't implement at-least-once, only reduce network errors on caller side.

**Comment by ReubenBond** [comment]
Your error detection logic needs to handle the case where there are network partitions between you and the remote application.
Having some way to detect only local errors might sound desirable at first, but I believe it doesn't give significant benefit.

Why not just make the method return a `Task` and remove `[OneWay]`?
Alternatively, would streams be useful for this case?
