### ISSUE TITLE
ClientBuilder is not bound to IKeyedServiceCollection<,> Invalid extension method using AddSingletonNamedService

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#4279]
`ClientBuilder` is not bound to  `IKeyedServiceCollection<,>` Invalid extension method using  `AddSingletonNamedService`

**Comment by ReubenBond** [comment]
I don't understand, @aqa510415008 - are you able to provide more details?

**Comment by jason-bragg** [comment]
I think he may be saying that we don't have an IKeyedServiceCollection registered in DI on the client.

        services.TryAddSingleton(typeof(IKeyedServiceCollection<,>), typeof(KeyedServiceCollection<,>));

This may be the case in 1.5.x, I don't recall.
If so, this can probably be compensated for by the application registering one itself, using the above code.

@aqa510415008, what version of Orleans are you using?

**Comment by aqa510415008** [comment]
@jason-bragg Yes, that's what I meant. I'm using RC2.0

**Comment by jason-bragg** [comment]
@aqa510415008 Thanks for the clarification.
That should be addressed in the latest code.  I thought it would be in rc2 as well.  Surprised it's not.
Did adding that line to your service collection work?  If not it would point to something else.
