### ISSUE TITLE
Error calling grain's

### ISSUE THREAD

**Issue by hanxinimm** [dotnet/orleans#4291]
0.
"Exception" : "Orleans.Storage.BadGrainStorageConfigException: No storage provider named \"Default\" found loading grain type Orleans.Runtime.Versions.VersionStoreGrain.
1.
Lifecycle start canceled due to errors at stage 1000
2.
Error calling grain's OnActivateAsync() method - Grain type = Orleans.Runtime.Versions.VersionStoreGrain Activation = [Activation: S127.0.0.1:8271:259483257*grn/13BAB4D8/00000000+fabric:/SecurityApp/StatelessCommandService@1cbfe087 #GrainType=Orleans.Runtime.Versions.VersionStoreGrain Placement=RandomPlacement State=Activating]
3.
Failed to InvokeActivate for [Activation: S127.0.0.1:8271:259483257*grn/13BAB4D8/00000000+fabric:/SecurityApp/StatelessCommandService@d6345997 #GrainType=Orleans.Runtime.Versions.VersionStoreGrain Placement=RandomPlacement State=Invalid].

**Comment by sergeybykov** [comment]
What version of Orleans is this with? This should have been fixed in 2.0.0-rc2.

**Comment by hanxinimm** [comment]
![image](https://user-images.githubusercontent.com/13499426/37885394-7e760f5e-30e7-11e8-8ee7-e74e8b6b1c90.png)

I find it DI injection failure can cause this problem

**Comment by benjaminpetit** [comment]
Are you using service fabric clustering?

**Comment by hanxinimm** [comment]
@benjaminpetit  yes

![image](https://user-images.githubusercontent.com/13499426/38015228-b5b3ac3a-329d-11e8-9e21-61965c879c74.png)

**Comment by ReubenBond** [comment]
@hanxinimm I recommend using a different clustering provider - we wont be releasing SF clustering in 2.0 final because the current version causes too much trouble.

**Comment by thiagoloureiro** [comment]
I'm running Orleans 1.5.2 and I had a Similar issue:
I don't use ServiceFabricClustering.

```
ConnectionSessionGrain.HandlePacketAsync | Error calling grain's OnActivateAsync() method - Grain type = PlaynGO.Firefly.Implementation.Grains.PlayerGrain Activation = [Activation: S172.30.14.77:22223:261645863*grn/A99D037D/000004b6@6867a68f #GrainType=PlaynGO.Firefly.Implementation.Grains.PlayerGrain Placement=RandomPlacement State=Activating]
20180420 23:12:32.387 | 0 | W |  |  |  |  | Failed to InvokeActivate for [Activation: S172.30.14.77:22223:261645863*grn/A99D037D/000004b6@6867a68f #GrainType=PlaynGO.Firefly.Implementation.Grains.PlayerGrain Placement=RandomPlacement State=Invalid].

// And a bit after:

Failed to InvokeActivate for [Activation: S172.30.14.77:22223:261645863*grn/A99D037D/000004b6@f541a9bd #GrainType=PlaynGO.Firefly.Implementation.Grains.PlayerGrain Placement=RandomPlacement State=Invalid].
20180420 23:12:32.390 | 0 | W |  |  |  |  | Forwarding failed: tried to forward message NewPlacement Request S172.30.14.90:22223:261917349*grn/99183723/00000000+ux7kHsoFNgr@254ecdab->S172.30.14.77:22223:261645863*grn/A99D037D/000004b6@f541a9bd #542571[ForwardCount=2]: global::PlaynGO.Firefly.Contracts.IPlayerGrain:NewConnection() for 2 times after Failed InvokeActivate to invalid activation. Rejecting now.
20180420 23:12:32.397 | 0 | E |  |  |  |  | Failed to ProcessPacket: Orleans.Runtime.OrleansMessageRejectionException: Forwarding failed: tried to forward message NewPlacement Request S172.30.14.90:22223:261917349*grn/99183723/00000000+ux7kHsoFNgr@254ecdab->S172.30.14.77:22223:261645863*grn/A99D037D/000004b6@f541a9bd #542571[ForwardCount=2]: global::PlaynGO.Firefly.Contracts.IPlayerGrain:NewConnection() for 2 times after Failed InvokeActivate to invalid activation. Rejecting now. PlaynGO.Firefly.GDK.ValidationException: Exception of type 'PlaynGO.Firefly.GDK.ValidationException' was thrown.
   at PlaynGO.Firefly.Implementation.Grains.PlayerGrain.<OnActivateAsync>d__76.MoveNext() in C:\TeamCity\buildAgent2\work\3f96b8aeac52203c\src\PlaynGO.Firefly.Implementation\Grains\PlayerGrain.cs:line 208
```
