### ISSUE TITLE
Build-time generation issue in Microsoft.Orleans.OrleansCodeGenerator.Build

### ISSUE THREAD

**Issue by jmvermeulen** [dotnet/orleans#4295]
Hi guys,

Found the following issue in the latest 2.0.0-rc-2 version.

**Download for the the reproduction:**
[OrleansIssue.Libs.zip](https://github.com/dotnet/orleans/files/1841533/OrleansIssue.Libs.zip)

One of my grain uses RabbitMq to receive messages.
The moment I reference the NuGet pacakge RabbitMQ.Client v5.0.1 (.NET 4.5.1) and used a type from the package in a grain the this error comes up:

`..OrleansIssue.Libs\packages\Microsoft.Orleans.OrleansCodeGenerator.Build.2.0.0-rc2\build\..\tasks\net461\Orleans.CodeGeneration.Build.exe" "@obj\Debug\codegen\OrleansIssue.Libs.orleans.g.args.txt"" exited with code 3.`

And the build output:

```
1>  Orleans-CodeGen - Generating file <path>source\repos\OrleansIssue.Libs\obj\Debug\OrleansIssue.Libs.orleans.g.cs
1>  warn: Orleans.CodeGenerator.RoslynCodeGenerator[101723]
1>        Exception loading types from assembly 'RabbitMQ.Client, Version=5.0.0.0, Culture=neutral, PublicKeyToken=89e7d7c5feba84ce': 
1>        Exc level 0: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
1>           at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
1>           at System.Reflection.RuntimeAssembly.get_DefinedTypes()
1>           at Orleans.Runtime.TypeUtils.GetDefinedTypes(Assembly assembly, ILogger logger) in D:\build\agent\_work\9\s\src\Orleans.Core\CodeGeneration\TypeUtils.cs:line 561
1>        Exc level 1: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Diagnostics.Tracing.EventSource, Version=1.1.28.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
1>        Exc level 2: System.IO.FileLoadException: The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
1>        Exc level 1: System.IO.FileLoadException: The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).
1>  System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
1>     at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
1>     at System.Reflection.RuntimeAssembly.get_DefinedTypes()
1>     at Orleans.Runtime.TypeUtils.GetDefinedTypes(Assembly assembly, ILogger logger) in D:\build\agent\_work\9\s\src\Orleans.Core\CodeGeneration\TypeUtils.cs:line 561
1>  -- Code Generation FAILED -- 
1>  
```

After some digging I found a relation with `Microsoft.Diagnostics.Tracing.EventSource.Redist`. As soon as this package is **downgraded** from 2.0.0-> 1.1.28 the issue is resolved.

Please note that there is no compilation error in the code,  its only the grain code generation at build-time.

Code:

```
 public class MyGrain : Grain, IMyGrain
    {
        // RabbitMq type from RabbitMQ.Client
        private ConnectionFactory _factory;

        public Task DoWork()
        {
            throw new NotImplementedException();
        }
    }
```

Involved packages:

Used RabbitMq package:
`<package id="RabbitMQ.Client" version="5.0.1" targetFramework="net471" />`

Package that throws the error:
`package id="Microsoft.Orleans.OrleansCodeGenerator.Build" version="2.0.0-rc2" targetFramework="net471"`

Can someone find out what goes wrong here?

**Comment by jmvermeulen** [comment]
@ReubenBond maybe you remember, we spoke about this issue in the gitter.im chat :-)

**Comment by ReubenBond** [comment]
I remember, thanks for opening the issue complete with a repro, @jmvermeulen 😁
