### ISSUE TITLE
tutorial about of Grain Persistence

### ISSUE THREAD

**Issue by guopenglun** [dotnet/orleans#4298]
Do you plan on creating tutorial about of Grain Persistence？

**Comment by mehmetakbulut** [comment]
Do either of the following satisfy what you are looking for?

- http://dotnet.github.io/orleans/Documentation/Core-Features/Grain-Persistence.html
- https://github.com/dotnet/orleans/tree/master/Samples/1.x/StorageProviders

If the doc page is insufficient and you are looking for something more like the 1.x sample, I can try to port it.

**Comment by guopenglun** [comment]
yes,
I have read, 
I am concerned about the difference between 1.x and 2.x.
I am not sure and confused

**Comment by sergeybykov** [comment]
@guopenglun I just merged #4300 (Thank you, @mehmetakbulut!). Does it help?
What exactly are you confused about?

**Comment by guopenglun** [comment]
@sergeybykov 
For example, whether the configuration method is transferred from XML to using code for configuration
http://dotnet.github.io/orleans/
The document is not very detailed

**Comment by sergeybykov** [comment]
We are deprecating XML-based configuration. It continues to be supported via the legacy packages and for legacy providers. Moving forward, only code-based configuration via `IOptions` will be developed. That's why the new tutorial uses
```csharp
builder.AddAzureTableGrainStorage(option => option.ConnectionString = your_connection_string);
```
and
```csharp
builder.AddAzureBlobGrainStorage(option => option.ConnectionString = your_connection_string);
```
as examples. The same API with provider specific options classes is how all new providers will be configured.

**Comment by guopenglun** [comment]
@sergeybykov 
This looks great，much better than XML.thank you!
