### ISSUE TITLE
Codegen mixing up VB and C#

### ISSUE THREAD

**Issue by BenjaminGibbs** [dotnet/orleans#43]
I have a class in which is make up of a set of properties just to store data data, when I but that as a parameter or result in a grain interface the class library fails to build.

for example `Function FindByEmailAsync(email As String) As Task(Of UserDataEntity)`

I am currently using VB, when I look at the errors it is failing because the generated code (orleans.codegen.vb) it is a mix of VB and C#.

The generated class the errors appear in is the '*_UserDataEntitySerialization' and appears in the functions DeepCopier, Serializer and Deserializer.

For example the following is generated:
`Dim temp21 As Object = CType(Orleans.Serialization.SerializationManager.DeepCopyInner(fieldInfo21.GetValue(input)),Action<Object,OperationContext,IDictionary<String,EntityProperty>>)`

But I would assume it should be something like:
`Dim temp21 As Object = CType(Orleans.Serialization.SerializationManager.DeepCopyInner(fieldInfo21.GetValue(input)), Action(Of Object, OperationContext, IDictionary(Of String, EntityProperty)))`

Or I am doing something totally wrong, if so happy to be guided in the right direction.

**Comment by rwray** [comment]
This is happening because of TypeUtils.GetTemplatedName assumes C# syntax of angle brackets for generic type names.

https://github.com/dotnet/orleans/blob/308534e5be14757860eb96912e50d707d8e3607a/src/Orleans/CodeGeneration/TypeUtils.cs#L103

Could by making GetTemplatedName language aware (i.e. a language parameter), but I'm unsure if this is the direction the team wants to take.

**Comment by sergeybykov** [comment]
Looks like this it the issue indeed. I agree that GetTemplatedName has to be language aware. The only exception I think is its usage from within GrainInterfaceData.GetTypeCode where we need to stay language neutral and generate same hash regardless of the language used.

Want to try to fix it? The codegen code is very convoluted, I know. :-)

**Comment by BenjaminGibbs** [comment]
Another bug I've hit which I believe is the same issue.

```vbnet
Public Interface IExampleGrain
    Inherits IGrain
    Function DoMathAsync() As Task(Of Byte())
End Interface
```

Creates a compile error; this is compiled code.
```vbnet
Public Function DoMathAsync() As System.Threading.Tasks.Task(Of System.Byte[]) Implements onShowcase.Distributed.GrainInterfaces.IExampleGrain.DoMathAsync
Return MyBase.InvokeMethodAsync(Of System.Byte[])(93759235, New System.Object() {} )
End Function
```

Where it should be
```vbnet
Public Function DoMathAsync() As System.Threading.Tasks.Task(Of System.Byte()) Implements onShowcase.Distributed.GrainInterfaces.IExampleGrain.DoMathAsync
Return MyBase.InvokeMethodAsync(Of System.Byte())(93759235, New System.Object() {} )
End Function
```

Is the language fixing something that is on the  high up the 'fix' list or something I should look at doing a PR for? We are working with VB for this project so while Orleans works with VB, we are having to avoiding certain things due to the code gen.

**Comment by sergeybykov** [comment]
@BenjaminGibbs  If you can prepare a PR, that would be great. Otherwise, we'll eventually get to it.

**Comment by BenjaminGibbs** [comment]
Sure I will take a look at it this weekend; and see if I can get my head around the codegen to make it language aware.
