### ISSUE TITLE
Orleans SDK Version 

### ISSUE THREAD

**Issue by ElanHasson** [dotnet/orleans#430]
The SDK version is still showing as 1.0, even though I downloaded it from the 1.0.7 release.

This makes it hard to determine which version one has installed.

 
![image](https://cloud.githubusercontent.com/assets/234704/7717124/ee54e9c0-fe69-11e4-8409-f54c5765fd98.png)

Assemblies also versioned with 1.0:

![image](https://cloud.githubusercontent.com/assets/234704/7717099/a4f231a2-fe69-11e4-9cac-ff4ac677cceb.png)

This is same for the NuGet packaged assemblies as well.

**Comment by ElanHasson** [comment]
This is same for the NuGet packaged assemblies as well.

**Comment by gabikliot** [comment]
Fixed via #432.
