### ISSUE TITLE
ProtobufSerializer

### ISSUE THREAD

**Issue by guopenglun** [dotnet/orleans#4305]
Hi
I called this method in the Client & Silo
`.Configure<SerializationProviderOptions>(opt => opt.SerializationProviders.Add(typeof(ProtobufSerializer).GetTypeInfo()))`
To ensure the Protobuf Serialization is work.What do I need to do?
Do I need to manually call serialization before calling Grains?

**Comment by ReubenBond** [comment]
@guopenglun ProtoBuf will be used automatically for any types which are generated by protoc. Those types will have a field called `Parser` of type `Google.Protobuf.MessageParser`.

Note that in 2.0-final we will also have `ProtobufNetSerializer`, so you can use the [protobuf-net](https://github.com/mgravell/protobuf-net) library instead

**Comment by guopenglun** [comment]
cool .
I just need  use the protoc.exe to generated  *.proto file.
it's very easy to use. I like the function.
Thank you very much.

**Comment by ReubenBond** [comment]
Glad to hear it, @guopenglun! I'll close this issue for now
