### ISSUE TITLE
How Cluster calls each other?

### ISSUE THREAD

**Issue by guopenglun** [dotnet/orleans#4333]
Hi. everybody
I learned from the tutorial how the client invokes silo's Grains.
But I didn't find a way for silo to call silo (cluster call cluster).
Orleans 2.x has very little documentation

**Comment by guopenglun** [comment]
I'm sorry.I did not indicate my intention.
What I want to express is How to configure  silo to silo invoker by code .

**Comment by ReubenBond** [comment]
@guopenglun grains within a silo can call other grains within another silo - but a grain does not need to know which silo the other grain is activated on.

If you need to call a grain from code on a silo, you can use a startup task:
```C#
hostBuilder.AddStartupTask(
    async (services, cancellation) =>
    {
        var grainFactory = services.GetRequiredService<IGrainFactory>();
        var grain = grainFactory.GetGrain<ISimpleGrain>(1);
        await grain.SetA(888);
    });
```

**Comment by guopenglun** [comment]
thank you .
But the code did not work.
I spent a lot of time studying how to communicate between silo.
But there are no 2.0 documents and tutorials.
I am very frustrated. I will go ahead and do some other things and look forward to the emergence of the document.
thank you very much.

**Comment by ReubenBond** [comment]
@guopenglun apologies for the documentation not being fully up-to-date yet. Please feel free to message me on gitter and I will help you with this
