### ISSUE TITLE
Consistent format in documentation

### ISSUE THREAD

**Issue by LeeCampbell** [dotnet/orleans#434]
Hi guys,

Just a small request. I am currently reviewing Orleans after I saw Mark R demo this at Build. The docs are clearly in flux and I have already added some PRs to them.

However, it would be a lot easier to help out if there were some conventions followed

1. If each sentence is on its own line, it makes merging a lot nicer with git. It also has the added benefit of spotting when a sentence is overly verbose. Currently whole paragraphs are on a single line meaning any change to a paragraph by two people will conflict.
2. Have a spell checker turned on? Maybe use http://markdownpad.com/ which has it built in. There are heaps of spelling mistakes in here at the moment. I went to fix a bunch tonight, but the docs all changed under my feet and the merge went to the too-hard basket.
3. Favor headings e.g. \### instead of **bold text** above paragraphs. 
4. Use italics for file names, and paths. e.g. _../dir/file.ext_

**Comment by gabikliot** [comment]
Just a comment @LeeCampbell: we are currently very actively editing streaming related documents, so you better hold off editing those, for a couple of days until we are done.

**Comment by LeeCampbell** [comment]
Cheers. Will give me time to get my hands on some code and actually use Orleans instead of reading about it :-)

**Comment by jthelin** [comment]
Great suggestions @LeeCampbell 

Would you like to add a note to the repo with these items in some kind of simple "Documentation Style Guide" doc so that we have an enduring checklist that can be added to over time?
