### ISSUE TITLE
Microsoft.Orleans.ServiceFabric meta package references non-released 2.0.0 package

### ISSUE THREAD

**Issue by Vhab** [dotnet/orleans#4350]
`Microsoft.Orleans.Clustering.ServiceFabric` was pulled from 2.0.0, and left at 2.0.0-rc2,
However `Microsoft.Orleans.ServiceFabric` was bumped from rc2 to final.

I suppose options are to leave the meta package at rc2, or have it reference only `Microsoft.Orleans.Hosting.ServiceFabric` on 2.0.x

**Comment by ReubenBond** [comment]
@Vhab it was intentional: https://github.com/dotnet/orleans/pull/4259

The SF clustering package is not stable enough for 2.0, so we recommend using a different clustering provider for now.

**Comment by Vhab** [comment]
Yep, that part I knew. But is it also intentional that a 2.0.0-final meta package references a now non-existent package that was left at rc2?

**Comment by sergeybykov** [comment]
Had to publish https://www.nuget.org/packages/Microsoft.Orleans.ServiceFabric/2.0.2 to fix the dependency on `Microsoft.Orleans.Hosting.ServiceFabric` to 2.0.0.
