### ISSUE TITLE
Ado.net storage provider try to insert null for non nullable column

### ISSUE THREAD

**Issue by AdamWyzgol** [dotnet/orleans#4351]
After upgrade to 2.0 I got this error when using ado.net storage: 
` Exc level 0: System.Data.SqlClient.SqlException: Cannot insert the value NULL into column 'ServiceId', table 'Orleans.dbo.Storage'; column does not allow nulls. INSERT fails.`

**Comment by AdamWyzgol** [comment]
probably before 2.0 in clusterOptions serviceId was set to default "00000000-0000-0000-0000-000000000000" now it's set to null, after configure serviceId to value that used to have everything is working. When serviceId is null ado.net storage is not working even when I set this column to nullable.

**Comment by quaider** [comment]
serviceId's type may changes from guid to  string

**Comment by veikkoeeva** [comment]
I'll page @xiazen as she did a lot of hard work on this lately and might know if there's a good place for PR to go and check the ID really is set. Very good you had yourself unblocked. 👍

**Comment by sergeybykov** [comment]
Yes, this is because we changed `ServiceId` from `Guid` that implicitly defaulted to empty GUID to `string`.

Beware also of http://dotnet.github.io/orleans/Documentation/2.0/Migration1.5.html#provider-configuration.

**Comment by veikkoeeva** [comment]
@sergeybykov To make a bit progress, is this behavior consistent across all providers and what would be the path of least surprise (e.g. provide a default if one isn't set or something else)?

**Comment by sergeybykov** [comment]
One option is to add validation similar to #4160 to make sure service ID is configured.

**Comment by ReubenBond** [comment]
We have a validator now, so this particular issue should no longer occur
