### ISSUE TITLE
Orleans 2.0 DI - Using Autofac

### ISSUE THREAD

**Issue by satishviswanathan** [dotnet/orleans#4375]
Host Builder Code
===========

var builder = new SiloHostBuilder()
                    .UseLocalhostClustering()
                    .Configure<ClusterOptions>(options =>
                    {
                        options.ClusterId = "App_Cluster1";
                        options.ServiceId = "App Service";
                    })
                    .ConfigureServices(service => service.AddAutofac())
                    .Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Loopback);

                var host = builder.Build();
                await host.StartAsync();

In the above I've added code AddAutofac to hook Autofac into the startup pipeline, but not sure how we configure the StartUpClass

**Comment by tinpl** [comment]
instead of ConfigureServices, try to:
`builder.UseServiceProviderFactory(services => StartUpClass.ConfigureServices(services, config))`

**Comment by satishviswanathan** [comment]
Thank you, that worked !
