### ISSUE TITLE
what is the equivalent class of "ObserverSubscriptionManager" in Orleans 2.0

### ISSUE THREAD

**Issue by srinathgnath** [dotnet/orleans#4378]
what is equivalent class of "ObserverSubscriptionManager" in Orleans 2.0. If this is obsolete, how do I implement client observer in 2.0?

**Comment by ReubenBond** [comment]
Hi @srinathgnath, ObserverSubscriptionManager was moved to a legacy package, but please feel free to create your own, for example by copying this class here: https://github.com/dotnet/orleans/blob/master/Samples/2.0/ServiceFabric/Grains/GrainObserverManager.cs

**Comment by srinathgnath** [comment]
Thanks @ReubenBond Actually I wanted to implement pub-sub messaging. Whats your thought on using above observermanager over mq like rabbitmq.

**Comment by ReubenBond** [comment]
@srinathgnath why not use streams? I am unsure on the details of what an implementation using observers vs RabbitMq would look like

**Comment by ReubenBond** [comment]
Closing this in favor of #4434, we can open it again if you wish

**Comment by sjbthfc2** [comment]
Hi, I was following the docs to implement pub/sub between Grains and only now have discovered that ObserverSubscriptionManager is not available. Can we do pub/sub in Orleans?

**Comment by ReubenBond** [comment]
@sjbthfc2 yes, what kind of pub/sub are you looking for? Orleans Streams supports reliable (or unreliable) pub/sub, and you can use observers (unreliable), despite the lack of ObserverSubscriptionManager (it is essentially just an in-memory dictionary)
