### ISSUE TITLE
Looking source of TaskCanceledException [1.5.2]

### ISSUE THREAD

**Issue by amccool** [dotnet/orleans#4381]
We are seeing this `TaskCanceledException` sporadically.   they seem to always be unobserved.
this is running a 3silo cluster on 1.5.2

`{
  "_index": "trace-2018-03-30-22",
  "_type": "doc",
  "_id": "AWJ5EmT5AD6OAjO5VISl",
  "_score": 1,
  "_source": {
    "Severity": "Error",
    "LoggerType": "Runtime",
    "Caller": "UnobservedExceptionHandler",
    "Message": "UnobservedExceptionsHandlerClass Caught an UnobservedTaskException event sent by [Id=2092254, Status=Faulted]. Exception = \r\nExc level 0: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.\r\nExc level 1: System.Threading.Tasks.TaskCanceledException: The request was aborted",
    "IPEndPoint": "172.18.124.51:11111",
    "Exception": null,
    "EventCode": 100005,
    "UtcDateTime": "2018-03-30T22:41:11.1194856Z",
    "MachineName": "NCI-R5EAS01"
  },
  "fields": {
    "AggregateSource": [
      "UnobservedExceptionHandler"
    ],
    "AggregateLogLevel": [
      "Error"
    ],
    "UtcDateTime": [
      1522449671119
    ]
  }
}`

we will try to attach more details to like as we find them

The initial thought was that a grain call was made (maybe from client, maybe from another grain) that causes many hundreds of new activation to occur, and that time was a lengthy process.  However we haven't been able to deduce the exception.

**Comment by sergeybykov** [comment]
Is the code not awaiting some of the `Task`s, and that causes unhandled exceptions to get re-thrown on the CLR finalizer thread?

**Comment by bstauff** [comment]
I wrote a simple program to exhibit this error:

https://github.com/bstauff/OrleansTimeoutTest

 I created a simple debug silo host (1.5.2), with a simple bootstrapper that makes a grain call.  The grain call then calls another grain, which waits for 5 minutes then returns.

If the siloConfig.Globals.ResponseTimeout is left at default value of 30 seconds, the second delayed grain call is allowed to complete after 5 minutes, and everything is fine.

If I change the value of siloConfig.Globals.ResponseTimeout to anything less than 5 minutes, then a warning and a System.Timeout exception is thrown for the second delayed grain call.

**Comment by amccool** [comment]
see https://github.com/bstauff/OrleansTimeoutTest/blob/master/SiloHost1/Program.cs#L18

by commenting out `siloConfig.Globals.ResponseTimeout = xxx`   the exception does not occur

**Comment by ReubenBond** [comment]
The source of kind of exception can be difficult to track down, but the easiest way I've found is by using `procdump` to capture first chance exceptions matching a specific filter. Closing for now.
