### ISSUE TITLE
GrainTypeResolver is null

### ISSUE THREAD

**Issue by miker1423** [dotnet/orleans#4393]
Hello! After upgrading to Orleans 2.0 I've been having this problem almost random, doesn't seems to be related to something in specific.
```
warn: Orleans.OutsideRuntimeClient[104202]
      Refresh the GrainTypeResolver failed. WIll be retried after
```
but even after the Orleans client connects, I have a null reference for the GrainTypeResolver
![image](https://user-images.githubusercontent.com/8826013/38282047-9132e882-3773-11e8-8e40-84484ffc0473.png)

then, when trying to get a grain, it throws a NullReferenceException and the stack trace looks like this
```
at Orleans.GrainFactory.GetGrainClassData(Type interfaceType, String grainClassNamePrefix)  
at Orleans.GrainFactory.GetGrain[TGrainInterface](String primaryKey, String grainClassNamePrefix)  
at TuRuta.Web.Services.RoutesService..ctor(IClusterClient clusterClient) in C:\\Users\\migue\\source\\repos\\TuRuta\\src\\TuRuta\\TuRuta.Web\\Services\\RoutesService.cs:line 23
```

NOTE: I'm just supposing that all this three things are related, I'm not sure if the warning logged has to do with everything else.

UPDATE: I'm using Azure TableStorage clusterting, and seems that deleting the table of old registries helps to avoid the exception.

**Comment by benjaminpetit** [comment]
> UPDATE: I'm using Azure TableStorage clusterting, and seems that deleting the table of old registries helps to avoid the exception.

Do you change the `ClusterId` everytime you deploy a new version? How to you handle silo shutdown?

My guess is that the client tries to get a new typemap from a silo that is dead. We may have a bug here to reset the typemap to `null` when there is an issue when the refresh goes wrong.

**Comment by miker1423** [comment]
Was because of the ClusterID, is there a way to share that String? I see that it is saved in the clustering provider (this case, azure table storage).

**Comment by benjaminpetit** [comment]
What do you mean by share? It should be part of your configuration

**Comment by Maarten88** [comment]
I see the same problem in a small test project that I just made. It uses LocalHostClustering and MemoryStorage.

I suspect this is happening specifically when using the new retryFilter parameter in `clusterClient.Connect(retryFilter)`, and a retry happens there. If the first connection attempt is successful, GrainTypeResolver is set normally and grains can be resolved immediately. But if a retry happens (I can simulate that by delaying silo startup a few seconds) then GrainTypeResolver is null after the Connect, and it takes quite some time until it becomes set in the background.

**Comment by Maarten88** [comment]
I think https://github.com/dotnet/orleans/pull/4429 fixed this issue. A new build from source doesn't have this issue.
