### ISSUE TITLE
Documention of the logic behind of clusterclient.GetGrain<ISomeGrain>()

### ISSUE THREAD

**Issue by quaider** [dotnet/orleans#4400]
I think we need a original rational explanation of  what happening when our cluster client send a request(
`GetGrain<ISomeGrain>()`
) to the silo.  i want to know what happed of the entire request.

These original rational knowledge should be documented.

when client started, it get active gateways from `MembershipTable`,  how client decide which gateway to process the request? how gateway forward the request to the correct silo?

when entire request process ends, does orleans cache the `grain -> bucket(grain list?) -> gateway ->  connection -> silo`?

According to our test results, when the client sends the message, it seems that only 3 silos ( _i have 5 total_) opened the socket connection (in order to be effective, I used **client per request**) and then close the connection(why 3?)

**Comment by quaider** [comment]
Are then codes generated by silo in compile time is shared by multiple silo at run time？How do they share or merge? I don't find such a way in source code at present.  @sergeybykov 
```csharp
internal sealed class OrleansCodeGen289f65fb12FeaturePopulator :
global::Orleans.Metadata.IFeaturePopulator<global::Orleans.Metadata.GrainInterfaceFeature>, 
global::Orleans.Metadata.IFeaturePopulator<global::Orleans.Metadata.GrainClassFeature>, 
global::Orleans.Metadata.IFeaturePopulator<global::Orleans.Serialization.SerializerFeature>
```

**Comment by seniorquico** [comment]
> For most grains it tries to pick a gateway consistently, based on the hash of grain ID.

Is the behavior different for client-initiated calls to `[StatelessWorker]` grains?

**Comment by sergeybykov** [comment]
>Is the behavior different for client-initiated calls to [StatelessWorker] grains?

It is different. There is no affinity to a specific gateway when routing a client call to a `[StatelessWorker]` grain and different gateways are used for different calls.

**Comment by ReubenBond** [comment]
Fixed by https://github.com/dotnet/docs/pull/38700
