### ISSUE TITLE
Getting a null reference error on ServiceId when I call GetReminder on a silo with no ServiceId

### ISSUE THREAD

**Issue by prerakpradhan** [dotnet/orleans#4401]
Hey,
I was using Orleans 2.0.0 Stable and have the following code in my grain
`
public async Task<AsyncOperationResult> SubmitOperation(OperationContext context, Type asyncOperationType, AsyncOperationInput operationInput)
{
            var grainId = this.GetPrimaryKeyString();

            var newOperationData = new AsyncOperationState
            {
                OperationType = asyncOperationType,
                Input = operationInput,
                Context = context
            };
			
            // Setup the lifeline reminder if it does not exist already
            IGrainReminder lifelineReminder = await this.GetReminder(OperationManagerGrain.ReminderName);
            if (lifelineReminder == null)
            {
                this.logger.LogInformation("[Grain {0}]: Setting up lifeline reminder.", grainId);
                await this.RegisterOrUpdateReminder(OperationManagerGrain.ReminderName, this.grainConfig.ReminderTickInitialDelay, this.grainConfig.ReminderTickPeriod);
            }

            // Add the new operation to the persistent store
            this.logger.LogInformation("[Grain {0}]: Modifying the grain state to include the new operation to run: [id={1}; type={2}]", grainId, newOperationData.Context.OperationId, newOperationData.OperationType.Name);
            this.State.CurrentOperation = newOperationData;
            this.State.IdleReminderTicks = 0;
            await this.WriteStateAsync();

            // Launch the submitted operation
            this.logger.LogInformation("[Grain {0}]: launching the current operation.", grainId);
            AsyncOperationResult submissionResult = await this.LaunchCurrentOperation();

            this.logger.LogInformation("[Grain {0}]: Returning ACK back to submitter.", grainId);
            return submissionResult;
}
`
My silo initialization code is as follows:

`Program.silo = new SiloHostBuilder()
                .Configure(options => options.ClusterId = orleansConfig.ClusterId)
                .Configure<ProcessExitHandlingOptions>(o =>
                {
                    o.FastKillOnProcessExit = true;
                })
                .UseAzureTableReminderService(options => options.ConnectionString = connectionString)
                .UseAzureStorageClustering(options =>
                {
                    options.ConnectionString = connectionString;
                    options.MaxStorageBusyRetries = 3;
                })
                .AddAzureBlobGrainStorage("grainBlobStore", (AzureBlobStorageOptions options) =>
                {
                    options.ConnectionString = connectionString;
                })
                .ConfigureGrainApplicationParts()
                .ConfigureEndpoints(siloPort: orleansConfig.SiloPort, gatewayPort: orleansConfig.GatewayPort)
                .ConfigureServices((services) =>
                {
                    // have some services here being initialized
                })
                .Build();`

If I were to queue two simultaneous job with the same grainId, I am encountering the following error:
`warn: Orleans.Runtime.ReminderService.AzureBasedReminderTable[100846]
      Intermediate error reading row with grainId = GrainReference:*grn/2E596F41/00000000+67db82be-6884-48e0-aafe-9f7a9f37350e reminderName = LifelineReminder from table OrleansReminders.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.Runtime.ReminderService.AzureBasedReminderTable.ConvertFromTableEntry(ReminderTableEntry tableEntry, String eTag)
   at Orleans.Runtime.ReminderService.AzureBasedReminderTable.<ReadRow>d__14.MoveNext()
fail: Microsoft.MachineLearning.Common.AsyncOperationsFramework.AsyncOperationsManager[0]
      System.NullReferenceException: Object reference not set to an instance of an object.
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Orleans.OrleansTaskExtentions.<<ToTypedTask>g__ConvertAsync4_0>d`1.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() `

I believe Orleans requires serviceid to be set but does not do a validation of this when I create my silo which leads to this issue down the line. We should add in validation that causes the silo init to break if serviceId is not passed in.

**Comment by benjaminpetit** [comment]
This is fixed since we added ServiceId check now
