### ISSUE TITLE
Nullpointer exception when running ping benchmark in release mode

### ISSUE THREAD

**Issue by JanEggers** [dotnet/orleans#4405]
debug mode runns fine but if i run ping benchmark in release i get this:

Running Ping benchmark
----------------------------- STARTING NEW UNIT TEST SILO HOST: Orleans.TestingHost.TestCluster -------------------------------------

Unbehandelte Ausnahme: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Orleans.Serialization.FieldUtils.GetGetter(FieldInfo field) in C:\Users\Jan Eggers\Documents\orleans\src\Orleans.Core\Serialization\FieldUtils.cs:Zeile 12.
   bei OrleansGeneratedCode5C168FDA.OrleansCodeGenOrleans_Serialization_SerializationManagerSerializer..ctor(IFieldUtils fieldUtils) in C:\Users\Jan Eggers\Documents\orleans\src\Orleans.Runtime\obj\Release\netstandard2.0\Orleans.Runtime.orleans.g.cs:Zeile 1733.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   bei Orleans.Serialization.SerializationManager.InitializeSerializer(Type serializerType) in C:\Users\Jan Eggers\Documents\orleans\src\Orleans.Core\Serialization\SerializationManager.cs:Zeile 242.
   bei Orleans.Serialization.SerializationManager.Register(Type type, Type serializerType) in C:\Users\Jan Eggers\Documents\orleans\src\Orleans.Core\Serialization\SerializationManager.cs:Zeile 445.
   bei Orleans.Serialization.SerializationManager.RegisterSerializers(SerializerFeature serializerFeature) in C:\Users\Jan Eggers\Documents\orleans\src\Orleans.Core\Serialization\SerializationManager.cs:Zeile 204.
   bei Orleans.Serialization.SerializationManager.RegisterSerializers(IApplicationPartManager applicationPartManager) in C:\Users\Jan Eggers\Documents\orleans\src\Orleans.Core\Serialization\SerializationManager.cs:Zeile 176.
   bei Orleans.Runtime.Silo..ctor(ILocalSiloDetails siloDetails, IServiceProvider services) in C:\Users\Jan Eggers\Documents\orleans\src\Orleans.Runtime\Silo\Silo.cs:Zeile 146.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   bei Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   bei Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   bei Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   bei Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   bei Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   bei Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   bei Orleans.TestingHost.TestClusterHostFactory.CreateSiloHost(String hostName, IEnumerable`1 configurationSources) in C:\Users\Jan Eggers\Documents\orleans\src\Orleans.TestingHost\TestClusterHostFactory.cs:Zeile 84.
   bei Orleans.TestingHost.InProcessSiloHandle.Create(String siloName, IList`1 configurationSources) in C:\Users\Jan Eggers\Documents\orleans\src\Orleans.TestingHost\InProcessSiloHandle.cs:Zeile 33.
   bei Orleans.TestingHost.TestCluster.StartOrleansSilo(Int32 instanceNumber, TestClusterOptions clusterOptions, IReadOnlyList`1 configurationOverrides, Boolean startSiloOnNewPort) in C:\Users\Jan Eggers\Documents\orleans\src\Orleans.TestingHost\TestCluster.cs:Zeile 482.
   bei Orleans.TestingHost.TestCluster.<InitializeAsync>d__56.MoveNext() in C:\Users\Jan Eggers\Documents\orleans\src\Orleans.TestingHost\TestCluster.cs:Zeile 433.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Orleans.TestingHost.TestCluster.<DeployAsync>d__36.MoveNext() in C:\Users\Jan Eggers\Documents\orleans\src\Orleans.TestingHost\TestCluster.cs:Zeile 170.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Orleans.TestingHost.TestCluster.Deploy() in C:\Users\Jan Eggers\Documents\orleans\src\Orleans.TestingHost\TestCluster.cs:Zeile 125.
   bei Benchmarks.Program.<>c.<.cctor>b__4_18() in C:\Users\Jan Eggers\Documents\orleans\test\Benchmarks\Benchmarks\Program.cs:Zeile 78.
   bei Benchmarks.Program.RunBenchmark[T](String name, Func`1 init, Action`1 benchmarkAction, Action`1 tearDown) in C:\Users\Jan Eggers\Documents\orleans\test\Benchmarks\Benchmarks\Program.cs:Zeile 112.
   bei Benchmarks.Program.<>c.<.cctor>b__4_5() in C:\Users\Jan Eggers\Documents\orleans\test\Benchmarks\Benchmarks\Program.cs:Zeile 82.
   bei Benchmarks.Program.Main(String[] args) in C:\Users\Jan Eggers\Documents\orleans\test\Benchmarks\Benchmarks\Program.cs:Zeile 107.

**Comment by JanEggers** [comment]
@ReubenBond can i provide any more Info so this gets resolved? are you able to reproduce?

**Comment by ReubenBond** [comment]
Very sorry for taking so long to answer you, @JanEggers. I'm not seeing the `NullReferenceException` when I run this locally.

I do see that the Ping load test is overloading its silo on my machine, though.

I'll close this because updates to the benchmark project seem to make this a no-repro, but there's room for improvement in that little load test.

**Comment by JanEggers** [comment]
ill try the latest version if I have time and maybe open a new issue if I see anything
