### ISSUE TITLE
DependencyResolutionException while using Autofac & SMS

### ISSUE THREAD

**Issue by srinathgnath** [dotnet/orleans#4407]
Hello,

After start using SMS in Host configuration, I have been having below exceptions.  

Exception 1:
DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IGrainStorage (DelegateActivator), Services = [Orleans.Storage.IGrainStorage], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope
Exception 2:
DependencyResolutionException: A delegate registered to create instances of 'Orleans.Storage.IGrainStorage' returned null.

Code Snippet:
var builder = new SiloHostBuilder()
                .Configure<ClusterOptions>(options => options.ClusterId = "TestCluster")
                .UseDevelopmentClustering(
                    options => options.PrimarySiloEndpoint = new IPEndPoint(siloAddress, siloPort))
                .ConfigureEndpoints(siloAddress, siloPort, gatewayPort)
                .AddMemoryGrainStorage("PubSubStore")
                .AddSimpleMessageStreamProvider("Teststream")
                .UseServiceProviderFactory(Startup.ConfigureServices)
                .ConfigureApplicationParts(parts =>
                    parts.AddApplicationPart(typeof(IEventAggregator).Assembly).WithReferences());

Startup:
  public static IServiceProvider ConfigureServices(IServiceCollection services)
        {
            var builder = new ContainerBuilder();
            builder.Populate(services);
            builder.RegisterModule<TestModule>();
            var container = builder.Build();
            //Create the IServiceProvider based on the container.
            return new AutofacServiceProvider(container);
        }

**Comment by srinathgnath** [comment]
Thanks Team.
Closing this issue as it worked fine after correcting memorygrainstorage configuration.

**Comment by ifle** [comment]
I have similar issue with ado storage. Can you please explain what is were wrong in your configuration?
Thanks

**Comment by srinathgnath** [comment]
After adding memorygrainstorageasdefault configuration, it worked.
.AddMemoryGrainStorageAsDefault()

**Comment by xiazen** [comment]
I think the failure is due to missing config on Default grain storage. @srinathgnath  is trying to configure memory grain storage, so they should call `AddMemoryGrainStorageAsDefault`.
@ifle  if you want to  use Ado Storage, then you should call `AddAdoGrainStorageAsDefault`

**Comment by ifle** [comment]
@srinathgnath @xiazen Thanks a lot. Adding AddMemoryGrainStorageAsDefault is fixed this error. 
Please add the configuration validation, that will very helpful.
