### ISSUE TITLE
System.InvalidOperationException: 'Grain was created outside of the Orleans creation process and no runtime was specified.'

### ISSUE THREAD

**Issue by srinathgnath** [dotnet/orleans#4409]
Team,

Am getting below exception while trying to call a grain in startup task during silohost generation:
System.InvalidOperationException: 'Grain was created outside of the Orleans creation process and no runtime was specified.'
Grain Constructor: Exception is thrown in first line : GetStreamProvider
public Aggregator()
        {
            var streamProvider = GetStreamProvider("samplestream");
            _stream = streamProvider.GetStream<RequestMessage>(Guid.NewGuid(), "TestNamespace");
            this._observer = GrainFactory.GetGrain<ITestObserver>(Guid.Empty);
        }

Thanks

**Comment by srinathgnath** [comment]
While debugging, found that Grainruntime is null which is causing core/grain.cs to throw exception mentioned in the issue description.

**Comment by ReubenBond** [comment]
This is likely fixed by #4429

**Comment by srinathgnath** [comment]
This worked once I moved the code to  OnActivateAsync() method. Thanks.

**Comment by rammicz** [comment]
I also had some code in the constructor, which should not be there.
