### ISSUE TITLE
Issue in configuring Orleans Load balancing

### ISSUE THREAD

**Issue by satishviswanathan** [dotnet/orleans#4410]
I have 2 Silos running on 2 different ports and is using consul for clustering. Now I have multiple clients trying to connect to the host to invoke a grain, but it seems the request is always going to the first silo. As soon as I bring the first Silo down the requests starts flowing to the 2nd Silo.

Not sure what I'm missing here, any help is highly appreciated. Please find below the code for Silo host and the client. 

Silo Host configuration
+++++++++++++++
 var builder = new SiloHostBuilder()
                    .Configure<ClusterOptions>(options =>
                    {
                        options.ClusterId = "Clust1";
                        options.ServiceId = "Service1";
                    })
                    .UseServiceProviderFactory(HostStartUp.ConfigureServices)
                    .UseConsulClustering(gatewayOptions =>
                    {
                        gatewayOptions.Address =
                            new Uri(ConfigurationManager.AppSettings["ServiceDiscoverEndPoint"]);
                    })
                    .Configure<EndpointOptions>(options =>
                    {
                        options.SiloPort = Convert.ToInt32(ConfigurationManager.AppSettings["SiloPort"]);
                        options.GatewayPort = Convert.ToInt32(ConfigurationManager.AppSettings["GatewayPort"]);
                        options.AdvertisedIPAddress =
                            IPAddress.Parse(ConfigurationManager.AppSettings["AdvertisedIPAddress"]);
                    })
                    .AddMemoryGrainStorageAsDefault();

                var host = builder.Build();
                host.StartAsync().Wait();

Client Configuration
+++++++++++++

 var builder = new SiloHostBuilder()
                    .UseLocalhostClustering()
                    .Configure<ClusterOptions>(options =>
                    {
                        options.ClusterId = "Cluster1";
                        options.ServiceId = "Service1";
                    })
                    .UseServiceProviderFactory(HostStartUp.ConfigureServices)
                    .Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Loopback);
                var client = builder.Build();
                await client.StartAsync().Wait();

**Comment by sergeybykov** [comment]
The code shows you are trying to use `SiloHostBuilder` to build a cluster client. Is that correct?

Here's an example of how client is configured via `ClientBuilder` - https://github.com/dotnet/orleans/blob/master/Samples/2.0/HelloWorld/src/OrleansClient/Program.cs#L49.

**Comment by junpark12** [comment]
I have the same issue. In my case, i use Azure Storage Cluster.
-- Client
var client = new ClientBuilder()
             //
             .UseAzureStorageClustering(options => options.ConnectionString = connectionString)

**Comment by satishviswanathan** [comment]
I had published the wrong code for client builder


 client = new ClientBuilder()
                      .Configure<ClusterOptions>(options =>
                        {
                            options.ClusterId = "Cluster1";
                            options.ServiceId = "Service";
                        })
                       .UseConsulClustering(gatewayOptions =>
                        {
                            gatewayOptions.Address = new Uri("http://10.xxx.xxx.xx:9998/");
                        })
                        .Build();
                    await client.Connect();

With this it did work but the KV store in consul shows the Siloport number. I thought the Gatewayport would be published for the client to communicate.

@sergeybykov please advice. Whether this is right?

**Comment by benjaminpetit** [comment]
If you send requests to the same grain, it's expected that the client will always use the same silo gateway to preserve ordering
