### ISSUE TITLE
Grain not found if in same project

### ISSUE THREAD

**Issue by dandago** [dotnet/orleans#4417]
I'm following the [Hello World sample documentation](https://dotnet.github.io/orleans/Documentation/Samples-Overview/Hello-World.html). But rather than build a full project structure (as the [actual code sample](https://github.com/dotnet/orleans/tree/master/Samples/2.0/HelloWorld) does), I'm dumping everything (silo, client, grain and interface) in the same console app. This is because I want to keep it simple, and not complicate an introductory exercise with additional infrastructure. First I make it work, then I make it nice.

Unfortunately, the "make it work" part didn't play out very nicely. The grain is not being found, even though it sits literally in the same file as the `Main()` method.

![image](https://user-images.githubusercontent.com/13241564/38455497-286185e2-3a71-11e8-8cb8-1c3360663e51.png)

According to the [Server Configuration documentation](https://dotnet.github.io/orleans/Documentation/Deployment-and-Operations/Configuration-Guide/Server-Configuration.html), this should work without the need for additional configuration:

> "Although this step is not technically required (if not configured, Orleans will scan all assembly in the current folder), developers are encouraged to configure this. This step will help Orleans to load user assemblies and types."

However, I have also tried `.ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(HelloGrain).Assembly).WithReferences())` and `.ConfigureApplicationParts(parts => parts.AddFromAppDomain())` and I still get the same error.

I am attaching a repro project.

[Orleans2TestDrive.zip](https://github.com/dotnet/orleans/files/1886403/Orleans2TestDrive.zip)

**Comment by ReubenBond** [comment]
Make sure you add the code generation package

**Comment by dandago** [comment]
Yes, that solved it.

    Install-Package Microsoft.Orleans.OrleansCodeGenerator.Build

So it is required now, and there is no default if you don't install a codegen package?

**Comment by ReubenBond** [comment]
That's correct, @dandago, there is no default.
For all intents and purposes, that package is required

**Comment by ReubenBond** [comment]
Thank you, @dandago
