### ISSUE TITLE
Local and Development clustering?

### ISSUE THREAD

**Issue by dandago** [dotnet/orleans#4421]
`SiloHostBuilder` has the following two methods:

![image](https://user-images.githubusercontent.com/13241564/38455897-2294377c-3a76-11e8-8a3d-93a869c97bde.png)

I'm not sure if these are documented anywhere, but the documentation we get in VS doesn't tell much about what they actually do:

* `UseLocalhostClustering()` says: "Configures a localhost silo for development and testing".
* `UseDevelopmentClustering()` says: "Configures the silo to use development-only clustering".

What is the difference between localhost and development clustering? What is involved in the "development and testing" configuration? What does "development-only" clustering mean?

The method docs should be improved to explain what they actually do, and why there are two different methods for what seems to be the same thing. This should also be added to the online documentation if it is not already there.

**Comment by ReubenBond** [comment]
The key word is localhost. UseLocalhostClustering configures a silo which listens on localhost, but UseDevelopmentClustering does not configure listening endpoints.

They are both just helper methods. For testing scenarios, use localhost. If you want to deploy multiple silos, use development and configure the endpoints manually. I'll try to clarify the distinction in the doc comments.
