### ISSUE TITLE
[2.0] MySql.Data was configured using AdoNetReminderService, but the system did not find the file

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#4423]
![image](https://user-images.githubusercontent.com/28291464/38464508-725325d6-3b41-11e8-80f1-752cd8c43675.png)

![image](https://user-images.githubusercontent.com/28291464/38464522-a6b7a50e-3b41-11e8-9f44-b6f3af45d8d6.png)

![image](https://user-images.githubusercontent.com/28291464/38464520-9d56abd6-3b41-11e8-8504-2bc79d2c8952.png)

**Comment by aqa510415008** [comment]
The problem was found. Because ServiceID is not set, but this error is also inexplicable

**Comment by sergeybykov** [comment]
Looks like another duplicate of #4401.

**Comment by sergeybykov** [comment]
Closing as a duplicate.
