### ISSUE TITLE
Documentation: 1.5 -> 2.0 links broken

### ISSUE THREAD

**Issue by dandago** [dotnet/orleans#4425]
Taking the example of the [Server Configuration](https://dotnet.github.io/orleans/1.5/Documentation/Deployment-and-Operations/Configuration-Guide/Server-Configuration.html?q=server) doc for Orleans 1.5, I see this:

![image](https://user-images.githubusercontent.com/13241564/38472183-f425028c-3b73-11e8-9702-cf0481b56b25.png)

Both links are broken.

![image](https://user-images.githubusercontent.com/13241564/38472191-044f8f24-3b74-11e8-9cb9-5e74ddc18dca.png)

Broken documentation link: https://dotnet.github.io/Documentation/Introduction.html
Broken tutorials link: https://dotnet.github.io/Tutorials/index.html

**Comment by sergeybykov** [comment]
Should be fixed now.
Thanks you, @dandago!
