### ISSUE TITLE
Not existed link in documentation for Orleans Configuration Guide

### ISSUE THREAD

**Issue by MelnikovIG** [dotnet/orleans#4430]
In the page `http://dotnet.github.io/orleans/Documentation/Deployment-and-Operations/Configuration-Guide/index.html` link to `Options pattern documentation`  leads to non exist source `http://dotnet.github.io/orleans/Documentation/Deployment-and-Operations/Configuration-Guide/(https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options)`

**Comment by MelnikovIG** [comment]
Looks like fixed in code, but site is not updated. Can be closed when site will be updated.

**Comment by sergeybykov** [comment]
Fixed. Thank you, @MelnikovIG!
