### ISSUE TITLE
Issues with IClusterClient

### ISSUE THREAD

**Issue by dandago** [dotnet/orleans#4436]
1. Should we call `Close()` or `Dispose()` to clean up the client, or both?
2. IClusterClient has an awaitable `Connect()` method, whereas ISiloHost has an awaitable `StartAsync()`. That -Async() suffix is inconsistent. I know Microsoft recommends the -Async() suffix, but the Orleans team had decided against it a while back. Either way, it should be consistent. Personally, I prefer the -Async() suffix as it is immediately recognisable as needing an `await` (or other Task-based approach).

**Comment by sergeybykov** [comment]
We inherited `StartAsync()` from https://github.com/aspnet/Hosting/issues/1163 via https://github.com/dotnet/orleans/pull/3431. Hence "Async" in the method name. Otherwise, we try not to add the suffix.

I personally don't see a clean and easy way out of this compromise. It's too late for us to rename public methods anyway.

**Comment by ReubenBond** [comment]
@dandago `Close()` is graceful. `Dispose()` is identical to `Abort()`, which is ungraceful. So, if possible, always opt for `await client.Close();`

**Comment by ReubenBond** [comment]
Does this answer your question, @dandago?

**Comment by dandago** [comment]
Yes, although I'm very surprised at this design decision. This goes against a common convention in the .NET Framework of `Close()` and `Dispose()` being equivalent, and prevents people from wrapping their client in a `using` block.

**Comment by ReubenBond** [comment]
@dandago the client is intended to be long-lived, unlike a `DbContext`, which may be per-request. So the client typically lives for the duration of the app.

`Close()` is not *identical* to `Dispose()` because it's naturally `async`.

Here's the relationship between them:
```
                    graceful
           Close() +------------+
              (async)           |
                                |
                    ungraceful  v
           Abort() +----------> Stop(bool gracefully) (private)
           ^  (blocking)          * if graceful, shutdown gracefully
           |                      * clean up internal state
Dispose() ++                    
```

**Comment by dandago** [comment]
Why does `Close()` need to be async in this case? If it's doing cleanup, that will typically involve internal resources and no I/O operations.

**Comment by ReubenBond** [comment]
@dandago because it tells the cluster that the client is disconnecting, because it's graceful.

**Comment by dandago** [comment]
OK, got it.
