### ISSUE TITLE
High memory consumption by SerializationContext in SerializationManager

### ISSUE THREAD

**Issue by kylespinner** [dotnet/orleans#4443]
I noticed memory slowly being exhausted on client side servers.  A process dump from one server shows over 5GB of memory for SerializationContext records.  This averages 11MB / instance.

Count    TotalSize        Class Name
480        5629484224  System.Collections.Generic.Dictionary`2+Entry[[System.Object, mscorlib],[Orleans.Serialization.SerializationContext+Record, Orleans]][]

Running !gcroot on a couple of these instances shows they are coming from the serializationContext field in the SerializationManager class.

00000007652bdd50 00007fff7c103534 Orleans.Messaging.ProxiedMessageCenter.WaitMessage(Categories, System.Threading.CancellationToken)
        rbp+10: 00000007652bddb0
            ->  0000010b15165fd8 Orleans.Messaging.ProxiedMessageCenter
            ->  0000010794ebad60 Orleans.Serialization.SerializationManager
            ->  0000010794ebaee0 System.Threading.ThreadLocal`1[[Orleans.Serialization.SerializationContext, Orleans]]
            ->  0000010794ebaf08 System.Threading.ThreadLocal`1+LinkedSlot[[Orleans.Serialization.SerializationContext, Orleans]]
            ->  0000010b1cde8998 System.Threading.ThreadLocal`1+LinkedSlot[[Orleans.Serialization.SerializationContext, Orleans]]
.....

This process dump showed 591 background threads and based on the count above a lot of these seem to have an Orleans serialization context in thread local storage.  Would it be more memory efficient to keep a pool of SerializationContexts inside the SerializationManager instead of using ThreadLocal storage?  

Our application does have objects with large serialization subgraphs but even if we reduced this from an average of 11MB to say 2MB if there are 500 threads with a SerializationContext in local storage we're still looking at 1GB of consumed memory.  We don't create threads and most of the threads in the process dump are marked (Threadpool Worker) so I'm not sure we have a good way to reduce thread count.

**Comment by sergeybykov** [comment]
This is very strange. Are you creating a new `ClusterClient` for each request by chance? Can you share the client logs.

**Comment by kylespinner** [comment]
I don't think so.  We initialize the client once via AzureClient.Initialize.  Then we use GrainClient.GrainFactory.GetGrain<T> to obtain grains and make requests.

We log to a kibana/elastic search cluster instead of file.  Are there particular messages I should look for?  Let me see if I can export data for the server from which this dump was taken to a file and provide that.  It might be a day or two before I have that.

**Comment by kylespinner** [comment]
@sergeybykov I have a log export ready for you.  I'd prefer not to post online.  Is there another way I can send to you?

**Comment by sergeybykov** [comment]
You can email it or a link to it to me. My email address is in my profile.

**Comment by kylespinner** [comment]
Sent via email.

**Comment by ReubenBond** [comment]
@kylespinner is this no longer an issue for you? I think it's worth keeping open anyway, since I would like to address this.

**Comment by kylespinner** [comment]
@ReubenBond it is still an issue if you have time to address at some point that would be great.  Another developer pointed out to me that there might be a work around in 2.0 by periodically creating/releasing instance GrainClients (say ever 24 hours) instead of using the single static instance in 1.5.  Haven't verified this yet but worth a look I think.

**Comment by ReubenBond** [comment]
I'm looking at a memory dump where I see relatively high counts of SerializationContext: 74 instances. Thankfully it seems that none of them are actually referencing any objects (so they're being cleared correctly), except the internal `processedObjects` dictionary is not freeing its entries on `Clear()`. Ideally we would create less of these and clean up old instances over time.

I'm examining two alternatives:
1. Allocating a temporary context per-request
2. Pooling contexts in a shared pool
