### ISSUE TITLE
[2.0]Orleans host throws an exception

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#4447]
Orleans host Throws a MysqlDataExceptions exception:
 MysqlDataExceptions client does not exist, the client will throw such an exception

![image](https://user-images.githubusercontent.com/28291464/38599724-3ddf54d2-3d94-11e8-9005-d5c1dac450e6.png)

**Comment by xiazen** [comment]
seems like dependency issue you are running into... but I don't know what's the cause without more info. Can you parse the full stack trace, any logs you got and which version you are using?

**Comment by xiazen** [comment]
and my wild guess is , is assembly `MySQL.Data` in your app folder ?

**Comment by aqa510415008** [comment]
@xiazen This is because when the Host throws an exception and the client serializes the exception information, the analysis fails to serialize the error message and an error is reported.
