### ISSUE TITLE
Question - Orleans real world usage scenario.

### ISSUE THREAD

**Issue by junpark12** [dotnet/orleans#4454]
Hi.
I'm new to orleans. I wonder if there are any useful scenarios using Orleans.
The only scenario, i can think of this moment is ticketing service.
One of my customers have ticketing service for concerts.
When they host famous singer's concert, they receive lots of traffic in
very short amounts of time like Ddos attacks.
As a results sometimes bottleneck is web servers, sometimes it's database.
I think Orleans will help to mitigate this situation.
So i have two questions.

1.  Are there any other useful scenarios ?
2.  If I had to convert a traditional three-tier(web,api,db) application into Orleans, 
    what would it be changed? I know that this is a broad question, but please give me 
    any descriptions or link to help me understand the general idea.
   (ex - Azure's table storage is recommended than traditional Relational Database)

Thanks.

**Comment by sergeybykov** [comment]
1. There are way more useful scenarios. For example, take a look at https://github.com/hataytuna/Distributed/blob/master/Applied%20Actor%20Model%20with%20Orleans%20v1.1.pdf for some ideas.

2. Unlike in a traditional three-tier app where the middle tier is stateless, which makes it call the storage layer for every request and requests for the same entity can arrive to two or more different middle tier servers in parallel, in Orleans grains act as a natural cache allowing to respond to many read requests without calling storage, and route all requests for the same entity to a single grain in the cluster that processes them in a single-threaded manner, hence eliminating races and conflicts.

There are other differences, of course, but these are the most immediate ones.

**Comment by junpark12** [comment]
Thanks
