### ISSUE TITLE
UseDevelopmentClustering and UseLocalhostClustering helper methods do not configure ServiceId

### ISSUE THREAD

**Issue by benjaminpetit** [dotnet/orleans#4468]
UseDevelopmentClustering and UseLocalhostClustering helper methods configure a default ClusterId, but no ServiceId. This is an issue since ServiceIs is required too.

These methods should take an optional parameter (with a default value) for setting the ServiceId

**Comment by sergeybykov** [comment]
Resolved via #4438.
