### ISSUE TITLE
Is it possible to configure silo using DNS name instead of IP address

### ISSUE THREAD

**Issue by srinathgnath** [dotnet/orleans#4478]
Team,
Below is code snippet for Silo host. Is there any option where I can configure endpoint using DNS name instead of IP address.

            var siloPort = Convert.ToInt32(ConfigurationManager.AppSettings["SiloPort"]);
            var gatewayPort = Convert.ToInt32(ConfigurationManager.AppSettings["GatewayPort"]);
            var advertisedIp = IPAddress.Parse(ConfigurationManager.AppSettings["AdvertisedIP"]);
            var builder = new SiloHostBuilder()
                .Configure<ClusterOptions>(options =>
                {
                    options.ClusterId = ConfigurationManager.AppSettings("CLUSTER_ID");
                    options.ServiceId = ConfigurationManager.AppSettings("SERVICE_ID");
                })
                .ConfigureEndpoints(siloPort: siloPort, gatewayPort: gatewayPort, advertisedIP: advertisedIp)
                .UseConsulClustering(gatewayOptions =>
                {
                    gatewayOptions.Address =
                        new Uri(ConfigurationManager.AppSettings("ServiceDiscoverEndPoint"));
                })

Thanks

**Comment by ReubenBond** [comment]
HI @srinathgnath, there is an overload of ConfigureEndpoints which accepts a hostname:
```C#
public static ISiloHostBuilder ConfigureEndpoints(
    this ISiloHostBuilder builder, 
    string hostname, 
    int siloPort, 
    int gatewayPort,
    AddressFamily addressFamily = AddressFamily.InterNetwork,
    bool listenOnAnyHostAddress = false)
```

Does that work for you?

**Comment by srinathgnath** [comment]
Thanks
