### ISSUE TITLE
Metrics Documentation Community Effort

### ISSUE THREAD

**Issue by petargyurov** [dotnet/orleans#4506]
The Orleans Telemetry interface outputs a lot of metrics. Some are crucial, some are less useful (and it depends on your needs).

As it stands there is no centralized space where these are documented and one shouldn't have to do guesswork to figure out which metrics they need to track. Some are self explanatory (`Runtime.CpuUsage.Current`) but some, if not most, are not (`Grain.DBCloud.ActorCollection.MeasureScales.Grains.MeasureScaleProxyGrain.Current`). Explanation of units is a particular issue.

We are currently beginning to build our backend with Orleans, and are carrying out investigations into which metrics are useful. This would work would be beneficial to others, and we implore those who already track certain metrics on their projects to contribute.

## Proposal
The overall goal is to enrich the official docs with more information on telemetry and internal metrics.

- Provide an explanation for each metric (what it tracks, units, etc...)
- Provide a list of **recommended** (crucial)  and optional metrics to track
- Provide use-cases and examples of **custom metric** implementations

I am not sure what the best place for user submitted examples would be, but it would be a great addition to have.

From a little digging around, and mostly from #3065 we can start with this list of seemingly useful metrics:

`App.Requests.Latency.Average.Millis`
`App.Requests.LatencyHistogram.Millis`
`App.Requests.TimedOut.Current`
`Catalog.Activation.CurrentCount`
`Grain.*.Current` (quite a lot of these, would be great to know more about this)
`Runtime.CpuUsage.Current`
`Runtime.GC.GenSizesKb`
`Runtime.GC.LargeObjectHeapSizeKb`
`Runtime.GC.PercentOfTimeInGC`
`Runtime.Memory.AvailableMemoryMb.Current`
`Runtime.Memory.TotalPhysicalMemoryMb.Current`
`Runtime.GC.TotalMemoryKb.Current`
`Runtime.Threads.AsynchAgent.TotalThreadsCreated.Current`
`Scheduler.NumLongRunningTurns.Current`
 
And I am including this definition from @sergeybykov as well:

> In general, Current is the latest value of the counter and Delta is the change in its value since the last time metrics were reported. By default metrics are reported every 5 minutes. So deltas give a rough idea of the counters' velocity.

also:

> Storage.* counters except for .Latency simply count invocations of the corresponding methods and their failures.

It would be good to start providing worded definitions and units for these as most are relatively clear in their functionality. 

To stress once more, this work would be greatly improved if it was a community effort 😃 **What is the best way/place to start contributing to this?**
________________________________________________________________________________________

**Comment by SebastianStehle** [comment]
I suggest that we put the explanation directly in code and generate the documentation from it. Because then we could also consume it in the Orleans dashboard and show it there directly.

**Comment by galvesribeiro** [comment]
Code docs and web docs are both appreciated. 

What you are looking now is what is the meaning of each of those counters. They are not related to the telemetry as they pre-date telemetry itself.

There is a (frozen) discussion about revamping telemetry APIs after 20 release. I'll see where it ends.

In meanwhile, if you can grab information and contribute at least to the docs site that would be good.

**Comment by ReubenBond** [comment]
Meters are documented here now: https://learn.microsoft.com/en-us/dotnet/orleans/host/monitoring/?pivots=orleans-7-0#orleans-meters
