### ISSUE TITLE
why so many handle ?

### ISSUE THREAD

**Issue by zhanlanghun** [dotnet/orleans#4516]
My Orleans service will have 5,000 handles in a moment. Is this normal? Sometimes more than 10,000. Who knows what this is about?

**Comment by zhanlanghun** [comment]
The environment is the asp.net framework 4.6.2. Instance code:
public async Task<int> RemoveProperty(int propertyId)
        {
            if (propertyId <= 0)
            {
                return 0;
            }
            using (var tran = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
            {
                await CategoryPropertyProxy.RemoveProductProperty(propertyId);
                await CategoryPropertyRelProxy.RemoveByPropertyId(propertyId);
                cacheProperty.Remove(propertyId.ToString());
                tran.Complete();
            }
            return 1;
        }

**Comment by zhanlanghun** [comment]
The information that was captured by windbg.：There's a lot of this information.
Handle = 0x0000000000000d14 - OPEN
Thread ID = 0x000000000000ef78, Process ID = 0x000000000000f2dc

0x00007ffb242e0744: ntdll!NtCreateEvent+0x0000000000000014
0x00007ffb21412f05: KERNELBASE!CreateEventW+0x0000000000000055
0x00007ffb12420606: mscorlib_ni!DomainNeutralILStubClass.IL_STUB_PInvoke(SECURITY_ATTRIBUTES, Boolean, Boolean, System.String)$##6000000+0x0000000000000106
0x00007ffb1239052a: mscorlib_ni!System.Threading.EventWaitHandle..ctor(Boolean, System.Threading.EventResetMode, System.String)$##6003A75+0x000000000000006a
0x00007ffb123904b6: mscorlib_ni!System.Threading.ManualResetEvent..ctor(Boolean)$##6003AFA+0x0000000000000016
0x00007ffb12d45d4a: mscorlib_ni!System.Threading.CancellationTokenSource.get_WaitHandle()$##6003DE2+0x000000000000003a
0x00007ffb10f56297: System_ni!System.Collections.Concurrent.BlockingCollection`1[System.__Canon].TryTakeFromAnyCoreSlow(System.Collections.Concurrent.BlockingCollection`1<System.__Canon>[], System.__Canon ByRef, Int32, Boolean, System.Threading.CancellationToken)$##600251B+0x00000000000000c7
0x00007ffb10f561bc: System_ni!System.Collections.Concurrent.BlockingCollection`1[System.__Canon].TryTakeFromAnyCore(System.Collections.Concurrent.BlockingCollection`1<System.__Canon>[], System.__Canon ByRef, Int32, Boolean, System.Threading.CancellationToken)$##600251A+0x00000000000000bc
0x00007ffb10f56041: System_ni!System.Collections.Concurrent.BlockingCollection`1[System.__Canon].TryTakeFromAny(System.Collections.Concurrent.BlockingCollection`1<System.__Canon>[], System.__Canon ByRef, System.TimeSpan)$##6002517+0x0000000000000051
0x00007ffab49f9632: +0x00007ffab49f9632
0x00007ffab49f8e50: +0x00007ffab49f8e50
0x00007ffab49f8874: +0x00007ffab49f8874
0x00007ffb123ac5d6: mscorlib_ni!System.Threading.Tasks.Task.Execute()$##6003F61+0x0000000000000046
0x00007ffb12384740: mscorlib_ni!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)$##6003AAB+0x0000000000000160
--------------------------------------

**Comment by ReubenBond** [comment]
Did you find out the cause, @zhanlanghun?

**Comment by zhanlanghun** [comment]
@ReubenBond   yes.Originally a colleague in the grain is used in the System. The Runtime. Caching. MemoryCache, because most of the code is modified from the old code.I'm very sorry about this.

**Comment by ReubenBond** [comment]
No need to apologize, @zhanlanghun :) I'm just glad it's all fixed
