### ISSUE TITLE
Microsoft.extentions.Logging when using log.LogInformation postion argument does not work

### ISSUE THREAD

**Issue by IanHot** [dotnet/orleans#4521]
If you have the code 
 log.LogInformation ("logic is 1={1}, 2={0}", 2 , 1);
The message appears as "logic is 1=2, 2=1". 
If you do log.LogInformation (String.Format("logic is 1={1}, 2={0}", 2 , 1))
 you get "logic is 1=1, 2=2".

I am not sure what happens if you reuse an argument.

I am using assembly version "v4.0.30319"
I believe this is a bug

**Comment by ReubenBond** [comment]
I believe this is not an Orleans issue and that it belongs on https://github.com/aspnet/Logging instead

**Comment by benjaminpetit** [comment]
As Reuben said, it belongs ton aspnet, but what you see is expected: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1&tabs=aspnetcore2x#log-message-template

**Comment by IanHot** [comment]
Thanks for you help and the ik.
