### ISSUE TITLE
Orleans call grain within a grain

### ISSUE THREAD

**Issue by satishviswanathan** [dotnet/orleans#4523]
I've got a requirement to call a grain within a grain. I had tried this in version 1.5 not sure how it works in 2.0. If somebody can provide a sample it would be great. This was what I was trying.

 public class CustomerRule : Grain, ICustomerRule
{
    private ISomeGrain _someGrain;
    public override async Task OnActivateAsync()
        {
              _someGrain = GrainFactory.GetGrain<ISomeGrain>(this.GetPrimaryKeyString());
              await base.OnActivateAsync();
         }
     public Task<bool> TestHello(GrainCancellationToken tc, string customer)
     {
               var string =  _someGrain.SayHello(tc, customer);
              return Task.FromResult(string);
      }
}

Due to some reason SayHello() is not being invoked.

**Comment by sergeybykov** [comment]
The code is missing `await` in front of `_someGrain.SayHello(tc, customer);`. Is this the exact code or pseudo-code?

`GrainFactory.GetGrain(this.GetPrimaryKeyString());` doesn't look right either.

**Comment by sergeybykov** [comment]
You can simply do
```csharp
public async Task TestHello(GrainCancellationToken tc, string customer)
{
  return await _someGrain.SayHello(tc, customer);
}
```
or even
```csharp
public Task TestHello(GrainCancellationToken tc, string customer)
{
  return _someGrain.SayHello(tc, customer);
}
```
instead of that code.

>What I'm not sure is how we can access another grain within the CustomerRule grain. 

Calling a grain from another grain is a bread-and-butter scenario for Orleans. The code you wrote should just work for that. How do you determine that `SayHello` is not getting invoked? Do you get a error/exception?

**Comment by satishviswanathan** [comment]
How is this _someGrain created on the calling grain in this case CustomerRule ?

basically I was not getting any results from the method SayHello(). also I had a break point and log return to see if it hits there but both didn't work.

**Comment by ReubenBond** [comment]
@satishviswanathan `Grain` has a `GrainFactory` property, so you can create the grain reference, `_someGrain`, by using `this.GrainFactory.GetGrain<ICustomerGrain>(customer)`.

In the end, your method might look like this:

```C#
public Task TestHello(GrainCancellationToken tc, string customer)
{
  var grain = this.GrainFactory.GetGrain<ICustomerGrain>(customer)
  return grain.SayHello(tc, customer);
}
```

Here I am assuming you have `ICustomerRuleGrain` with a `TestHello` method and it calls into `ICustomerGrain`'s `SayHello` method.

**Comment by satishviswanathan** [comment]
@ReubenBond The was my mistake I had an error being thrown from one of the grain and that was blowing the brain grain to return the result.

Thanks a lot for your support.

**Comment by ReubenBond** [comment]
We are happy to help, @satishviswanathan :)

Is this issue resolved now?

**Comment by satishviswanathan** [comment]
Yes the issue is resolved now.
