### ISSUE TITLE
Orleans Client in front end web server - Setup

### ISSUE THREAD

**Issue by satishviswanathan** [dotnet/orleans#4525]
Scenario: I've got a front end web api which is going to invoke the grain to execute the business logic.

In Orleans 1.5 GrainClient once initialized it was available across, basically I had the client initialization code in by WebApiConfig class.

 GrainClient.Initialize(HttpContext.Current.Server.MapPath("OrleansConfiguration.xml"));

And in my end point I would simply access the GrainClient static class to create the grain factory and all the method like this.

 public async Task<HttpResponseMessage> HealthCheckGrain()
 {
     GrainClient.GrainFactory.GetGrain<IHello>(0).SayHello("Test");
}

Since 2.0 doesn't have this how can I initialize the client once and then use the same client again to invoke the grain, or is it expected to create the client each time you invoke the grain.

**Comment by sergeybykov** [comment]
In 2.0, you can do exact same thing with `IClusterClient` created via `ClientBuilder`.

**Comment by satishviswanathan** [comment]
Do you have any examples of using IClusterClient from a  Web Api point of view?

**Comment by sergeybykov** [comment]
Take a look at http://gigi.nullneuron.net/gigilabs/getting-organised-with-microsoft-orleans-2-0-in-net-core/.

**Comment by sergeybykov** [comment]
Great. Closing this then.
