### ISSUE TITLE
Grain timeouts

### ISSUE THREAD

**Issue by careless6666** [dotnet/orleans#4531]
Hi. I want to use grain with different lifetime by type. Some my grains execute so long and this normal. Then i call grain from client, i can registered standardClient and longTimeLive client, but i can do this inside silo host. When i cal my grain A from grain B, i want that grain B can wait A more that another grains. How i can do this?

**Comment by sergeybykov** [comment]
You should be able to do the same - create a separate client for those calls. However, long running RPC calls aren't a recommended pattern in general. The preferred alternative is to make a quick call to start a long running operation and later have a quick call back to notify about completion.

**Comment by Kritner** [comment]
I know this was already closed, but I'd like to do something similar, are there any examples of how to accomplish this?  Would this require a stateful grain? Something like a `start` method that returns immediately, a private member representing the result, and a `getresult` method that returns either the result, or a "not finished" indicator?
