### ISSUE TITLE
DI documentation incorrect client sample

### ISSUE THREAD

**Issue by dandago** [dotnet/orleans#4532]
This concerns the [Dependency Injection](https://dotnet.github.io/orleans/Documentation/Core-Features/Dependency-Injection.html) documentation page for Orleans 2.0.

There's this code sample that shows how the _client_ should be configured to use DI:

![image](https://user-images.githubusercontent.com/13241564/39409406-6d25766a-4bde-11e8-9cbf-1b2a2be293cb.png)

It seems to be a direct copy/paste from the sample above which is for the silo. The name of the builder variable was changed, but the rest was left the same.

**Comment by ReubenBond** [comment]
Thanks, @dandago - would you be able to submit a fix?

**Comment by dandago** [comment]
Once the docs are regenerated, I think we can close this.

**Comment by sergeybykov** [comment]
Done. Closing.

Thank you, @dandago!
