### ISSUE TITLE
Cannot process Service Bus messages correctly

### ISSUE THREAD

**Issue by mikuam** [dotnet/orleans#4533]
I'm trying to use Orleans to receive Service Bus messages and process them very fast. I got stuck on completing messages. My subscription lock duration is 30 seconds and after that time I always get "The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue.", that means I was not able to process message in 30 seconds. It also happens when I set 2 minutes, but when I debug, processing message takes much less and it does not throw anything.

To test that I took AccountTransfer sample and my client code looks like this:
`        

            private static void DoClientWork(IClusterClient client)
            {
            var subscriptionClient = new SubscriptionClient(ServiceBusConnectionString, "accountTransferUpdates", "orleansSubscription");
            subscriptionClient.PrefetchCount = 1000;

            try
            {
                subscriptionClient.RegisterMessageHandler(
                    async (message, token) =>
                    {
                        var messageJson = Encoding.UTF8.GetString(message.Body);
                        var updateMessage = JsonConvert.DeserializeObject<AccountTransferMessage>(messageJson);

                        await client.GetGrain<IAccountGrain>(updateMessage.From).Withdraw(updateMessage.Amount);
                        await client.GetGrain<IAccountGrain>(updateMessage.To).Deposit(updateMessage.Amount);

                        await subscriptionClient.CompleteAsync(message.SystemProperties.LockToken);
                    },
                    new MessageHandlerOptions(HandleException)
                    { MaxConcurrentCalls = 1, AutoComplete = false });
            }
            catch (Exception e)
            {
                Console.WriteLine("Exception: " + e.Message);
            }
        }

        private static Task HandleException(ExceptionReceivedEventArgs args)
        {
            Console.WriteLine(args.Exception + ", stack trace: " + args.Exception.StackTrace);
            return Task.CompletedTask;
        }`

This code for receiving messages works with console application and there seems to be a problem of execution _await subscriptionClient.CompleteAsync(message.SystemProperties.LockToken);_

Maybe it is not executed instantly?
Do you have any working example of handling Service Bus messages in Orleans for .Net Core?

I posted full code here: [https://github.com/mikuam/orleans-core-example](https://github.com/mikuam/orleans-core-example)

**Comment by mikuam** [comment]
Hi Sergey,
No, It does not work correctly. I still get MessageLockLostException. Seems that something is just not working right when I'm completing the message.

However, I poked around a bit with the code and changed receive method to ReceiveAndDelete and it started to work perfectly. Code is here: https://github.com/mikuam/orleans-core-example

**Comment by sergeybykov** [comment]
So it looks unrelated to Orleans to me - you commented out the only Orleans calls, and it didn't fix it. Or am I missing something?

**Comment by mikuam** [comment]
Hmm, yes that is correct. I'll close the issue. However, I'd really like to see how it can work with Service Bus and ReceiveAndDelete mode.

Thanks for having a look.

**Comment by sergeybykov** [comment]
I remember people using SB from Orleans just fine, but I don't remember the details, sorry.
