### ISSUE TITLE
Regression on ClusterClient

### ISSUE THREAD

**Issue by onionhammer** [dotnet/orleans#4536]
The ClusterClient seems very persnickety when it comes to maintaining a connection

`Client is not initialized. Current client state is Starting.`

This just seems to happen randomly during the lifecycle of a ClusterClient, and there is no way for the ClusterClient to recover, it just needs to be torn down and replaced, which means major rearchitecting my application.

**Comment by ReubenBond** [comment]
@onionhammer that is very strange - could you show me the code that's being used to create the `ClusterClient`?

**Comment by onionhammer** [comment]
```C#

        /// <summary>
        /// Connect to Orleans
        /// </summary>
        /// <param name="maxWaitSeconds">Maximum amount of time to wait in seconds.</param>
        public static IClusterClient BuildClusterClient(int maxWaitSeconds = 5, CancellationToken cancellationToken = default)
        {
            var end = DateTimeOffset.Now.AddSeconds(maxWaitSeconds);

            var clusterId        = GetClusterId();
            var connectionString = Configuration.Instance.GetValue(ConfigurationKey.DataConnectionString);

            while (true)
            {
                cancellationToken.ThrowIfCancellationRequested();

                // Configure Orleans Cluster Client
                var client = new ClientBuilder()
                    .Configure((ClusterOptions options) => options.ClusterId = clusterId)
                    .Configure((ClientStatisticsOptions options) =>
                    {
                        options.CollectionLevel           = StatisticsLevel.Critical;
                        options.LogWriteInterval          = TimeSpan.FromMinutes(10);
                        options.PerfCountersWriteInterval = TimeSpan.FromMinutes(10);
                    })
                    .UseAzureStorageClustering(options => options.ConnectionString = connectionString)
                    .AddSimpleMessageStreamProvider(Streams.StreamProvider, options =>
                    {
                        options.FireAndForgetDelivery    = true;
                        options.OptimizeForImmutableData = true;
                    })
                    .Build();

                try
                {
                    if (!client.Connect().Wait(maxWaitSeconds * 1000, cancellationToken))
                        new SiloUnavailableException($"Unable to establish connection after {maxWaitSeconds} seconds");

                    return client;
                }
                catch (Exception)
                {
                    client.Dispose();

                    if (DateTimeOffset.Now > end)
                        throw;
                    else
                    {
                        Thread.Sleep(50);
                        continue;
                    }
                }
            }
        }
```

**Comment by ReubenBond** [comment]
There is an issue before `return client`. The code creates a new exception but does not throw it, so the client may be returned without being connected.

Please also note that you can pass a delegate to Connect if you wish, which may simplify your logic.

**Comment by onionhammer** [comment]
@ReubenBond Ahh, good catch, I will try that out tomorrow. Clumsy mistake if that fixes i!

**Comment by ivantomchev** [comment]
@ReubenBond Is this issue "Client is not initialized. Current client state is Starting" can be handled let say prettier. Instead of creating OrleansClientAccessor class. I'm pretty new in Orleans world and so far I'm struggling even to do something simple. So far I'm injecting the Client directly through IServiceCollection but if the silo is not accessible I'm receiving this error. I'm trying to follow this https://dotnet.github.io/orleans/docs/host/client.html, but even simple things are hard.

Is there a way to use OrleansClient without writing any additional code or helper classes? 

Thanks
