### ISSUE TITLE
Question about  Item System*WorkItemGroup:Name=*stg/28/0000001c

### ISSUE THREAD

**Issue by bluexo** [dotnet/orleans#4540]
I got much warning infomation on my application that base on Orleans 2.0 ,
```
2018/05/01 08:27:44.717|WARN|Queue wait time of 00:00:10.0157850 for Item System*WorkItemGroup:Name=*stg/28/`0000001c`,WorkGroupStatus=Runnable |Runtime.Scheduler.WorkerPoolThread/System.9|EventId_Id=101201, EventId_Name=, EventId=101201
```
 I noticed that `System*WorkItemGroup:Name=*stg/28/0000001c` maybe the  [TransactionAgentSystemTargetId](https://github.com/dotnet/orleans/blob/ba5531ba90053bb2f799c5ce36e90e8db6b94a93/src/Orleans.Core/Runtime/Constants.cs#L46) , but I never use any `TransactionAgentSystemTarget` on my system , why is this  ?

**Comment by ReubenBond** [comment]
@bluexo do these warnings start immediately or after a period of time? Could you tell me more about the application such as the load (requests per sec) and the number of silos and clients and the environment?

Do you have logs which you can share with me?

**Comment by bluexo** [comment]
@ReubenBond Of course , the warnings start after 10 hours ,  this is the siloHost and client  configuration  and logs

SiloHost : 
```C#
  var builder = new SiloHostBuilder()
                .Configure<ClusterOptions>(Config.GetSection(nameof(ClusterOptions)))
                .ConfigureApplicationParts(p => p.AddFromApplicationBaseDirectory())
                .UseSiloUnobservedExceptionsHandler()
                .AddLogStorageBasedLogConsistencyProvider()
                .AddStateStorageBasedLogConsistencyProvider()
                .AddCustomStorageBasedLogConsistencyProvider("CustomStorage")
                .AddMemoryGrainStorageAsDefault()
                .AddMongoDBGrainStorage("PubSubStore", op => op.Bind(Config.GetSection(nameof(MongoDBOptions))))
                .AddMongoDBGrainStorage("MongoDBStorage", op => op.Bind(Config.GetSection(nameof(MongoDBOptions))))
                .AddMongoDBGrainStorage("LogStorage", op => op.Bind(Config.GetSection("LogStorageOptions")))
//#if DEBUG
                .UseLocalhostClustering()
                .UseInMemoryReminderService()
//#else
                //.UseMongoDBMembershipTable(Config.GetSection(nameof(MongoDBMembershipTableOptions)))
                //.UseMongoDBReminders(Config.GetSection(nameof(MongoDBRemindersOptions)))
//#endif
                .AddSimpleMessageStreamProvider("SMS")
                .AddStartupTask<MongoDBQueryProvider>()
                .AddStartupTask<GameInitializer>()
                .ConfigureEndpoints(IPAddress.Loopback, SiloPort ?? siloPort, gatewayPort)
                .ConfigureServices(AddServices)
                .ConfigureLogging(AddLogging);
   var host = builder.Build();
```

ClusterClient:
```C#
                  ClusterClient = new ClientBuilder()
                        .AddClusterConnectionLostHandler(OnClusterLost)
                        .Configure<ClusterOptions>(Config.GetSection(nameof(ClusterOptions)))
//#if DEBUG
                        .UseStaticClustering(options => options.Gateways.Add(staticUrl))
//#else
                        //.UseConsulClustering(options => options.Address = consulUrl)
                        //.UseMongoDBClustering(Config.GetSection(nameof(MongoDBGatewayListProviderOptions)))
//#endif
                        .AddSimpleMessageStreamProvider("SMS")
                        .ConfigureLogging(AddLogging)
                        .ConfigureServices(AddServices)
                        .Build();
                    await ClusterClient.Connect();
```
Log of Silo start:
`2018/04/30 09:04:42.553|WARN|No implementation of IHostEnvironmentStatistics was found. Load shedding will not work yet |Orleans.Runtime.NoOpHostEnvironmentStatistics|EventId_Id=100708, EventId_Name=, EventId=100708
2018/04/30 09:04:43.905|WARN|Task [Id=1, Status=RanToCompletion] in WorkGroup [SystemTarget: S127.0.0.1:11111:262746282*stg/20/00000014@S00000014] took elapsed time 0:00:00.264343 for execution, which is longer than 00:00:00.2000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/System.9, ManagedThreadId=16, Executing Task Id=1 Status=RanToCompletion for 00:00:00.2686785 on WorkItem=System*WorkItemGroup:Name=*stg/20/00000014,WorkGroupStatus=Running Executing for 00:00:00.2697079. .> |Orleans.Runtime.Scheduler *stg/20/00000014.WorkItemGroup|EventId_Id=101215, EventId_Name=, EventId=101215
2018/04/30 09:04:44.460|WARN|Task [Id=2, Status=RanToCompletion] in WorkGroup [SystemTarget: S127.0.0.1:11111:262746282*stg/20/00000014@S00000014] took elapsed time 0:00:00.5135257 for execution, which is longer than 00:00:00.2000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/System.9, ManagedThreadId=16, Executing Task Id=2 Status=RanToCompletion for 00:00:00.5135742 on WorkItem=System*WorkItemGroup:Name=*stg/20/00000014,WorkGroupStatus=Running Executing for 00:00:00.5135809. .> |Orleans.Runtime.Scheduler *stg/20/00000014.WorkItemGroup|EventId_Id=101215, EventId_Name=, EventId=101215
2018/04/30 09:05:08.406|WARN|Task [Id=3, Status=RanToCompletion] in WorkGroup [Activation: S127.0.0.1:11111:262746282*grn/716E8E94/d2ca26af+SMS_IUserSession@c95533b1 #GrainType=Orleans.Streams.PubSubRendezvousGrain Placement=RandomPlacement State=Valid] took elapsed time 0:00:00.2349744 for execution, which is longer than 00:00:00.2000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/3, ManagedThreadId=20, Executing Task Id=3 Status=RanToCompletion for 00:00:00.2361378 on WorkItem=WorkItemGroup:Name=[Activation: S127.0.0.1:11111:262746282*grn/716E8E94/d2ca26af+SMS_IUserSession@c95533b1 #GrainType=Orleans.Streams.PubSubRendezvousGrain Placement=RandomPlacement],WorkGroupStatus=Running Executing for 00:00:00.2389462. .> |Orleans.Runtime.Scheduler.WorkItemGroup|EventId_Id=101215, EventId_Name=, EventId=101215
2018/04/30 09:05:28.156|WARN|Task [Id=4, Status=RanToCompletion] in WorkGroup [Activation: S127.0.0.1:11111:262746282*grn/BEB786B8/97afb893@7d1392bd #GrainType=PlayCity.Grains.FishPoolScene Placement=RandomPlacement State=Valid] took elapsed time 0:00:01.7126241 for execution, which is longer than 00:00:00.2000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/6, ManagedThreadId=23, Executing Task Id=4 Status=RanToCompletion for 00:00:01.7126920 on WorkItem=WorkItemGroup:Name=[Activation: S127.0.0.1:11111:262746282*grn/BEB786B8/97afb893@7d1392bd #GrainType=PlayCity.Grains.FishPoolScene Placement=RandomPlacement],WorkGroupStatus=Running Executing for 00:00:01.7126976. .> |Orleans.Runtime.Scheduler.WorkItemGroup|EventId_Id=101215, EventId_Name=, EventId=101215`

And util now logs [content is basically the same]:
`
2018/04/30 20:15:14.062|WARN|Queue wait time of 00:00:11.0016916 for Item System*WorkItemGroup:Name=*stg/28/0000001c,WorkGroupStatus=Runnable |Runtime.Scheduler.WorkerPoolThread/System.9|EventId_Id=101201, EventId_Name=, EventId=101201
2018/04/30 20:16:21.108|WARN|Queue wait time of 00:00:18.0630412 for Item System*WorkItemGroup:Name=*stg/28/0000001c,WorkGroupStatus=Runnable |Runtime.Scheduler.WorkerPoolThread/7|EventId_Id=101201, EventId_Name=, EventId=101201
2018/04/30 20:17:04.310|WARN|Queue wait time of 00:00:10.0156014 for Item System*WorkItemGroup:Name=*stg/28/0000001c,WorkGroupStatus=Runnable |Runtime.Scheduler.WorkerPoolThread/System.9|EventId_Id=101201, EventId_Name=, EventId=101201
2018/04/30 20:17:43.689|WARN|Queue wait time of 00:00:15.3311790 for Item System*WorkItemGroup:Name=*stg/28/0000001c,WorkGroupStatus=Runnable |Runtime.Scheduler.WorkerPoolThread/System.9|EventId_Id=101201, EventId_Name=, EventId=101201
2018/04/30 20:18:42.123|WARN|Queue wait time of 00:00:10.1562517 for Item System*WorkItemGroup:Name=*stg/28/0000001c,WorkGroupStatus=Runnable |Runtime.Scheduler.WorkerPoolThread/System.9|EventId_Id=101201, EventId_Name=, EventId=101201
`

**Comment by ReubenBond** [comment]
Are you able to capture a memory dump of the silo, @bluexo?

My concern is that this is the same issue as #4505

**Comment by ReubenBond** [comment]
Even during startup you are seeing slow grain calls - but they are much slower after 10 hours.
Do you know if the queue wait time increases slowly from the beginning?

**Comment by bluexo** [comment]
@ReubenBond  In my application , when the silo startup , some grain do a lot of initialize works ,  so they are active slowly , that didn't reappear until now.  Maybe same to #4505 , 
Is there any way can solve this problem ?

**Comment by ReubenBond** [comment]
We're still trying to diagnose the issue, @bluexo - if you have full logs, that may be useful.
For now, We should close this issue and instead discuss on #4505 since they seem to be the same.
