### ISSUE TITLE
Dbghelp.dll not found - .netcore

### ISSUE THREAD

**Issue by stephenlautier** [dotnet/orleans#4545]
I found the following error:

`Unable to load DLL 'Dbghelp.dll': The specified module or one of its dependencies could not be found`

#### Message
```
-Silo S10.0.4.15:11111:262798481 failed to update its status to Dead in the table due to failures (socket failures or table read/write failures) after 121 attempts: Unable to load DLL 'Dbghelp.dll': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
```

#### Screenshot
![2018-04-30 18_54_54-discover_ errors and warnings and concern is middleware - kibana](https://user-images.githubusercontent.com/3908723/39521661-c2495d18-4e0f-11e8-9117-63767d76b6f5.png)

Probably its because we are using .netcore.

#### Info
- .net core 2.0
- orleans 2.0
- using docker with the following image: microsoft/dotnet:2.0-runtime (linux)

Also not sure if this is causing the silo to be dead but the silo process still running (e.g. not exit).

**Comment by aqa510415008** [comment]
Your question is a bit similar #4447

**Comment by aqa510415008** [comment]
You need to add a filter on Host
-` public class OrleansExceptionsFiltered : IIncomingGrainCallFilter
    {
        public async Task Invoke(IIncomingGrainCallContext context)
        {
            try
            {
                await context.Invoke();
            }
            catch (Exception ex)
            {
                Exception InnerEx= ex.InnerException;
                while (true)
                {
                    if (InnerEx.InnerException == null)
                    {
                        throw new ZopException(InnerEx.Message);
                    }
                      
                    else
                        InnerEx = InnerEx.InnerException;
                }

            }
        }
    }`

**Comment by stephenlautier** [comment]
@aqa510415008 thanks for your reply, but I highly doubt it is the same as the error is coming from the silo and not the client/consumer (web) so its not a serialization error. My assumption its something which is windows specific and we are using linux.

**Comment by sergeybykov** [comment]
I don't see how dbghelp.dll is Orleans related. Maybe one of the assemblies in the folder has a dependency on it? Are you explicitly specifying application assemblies in the `SiloHostBuilder`? If you do, that should prevent scanning (and hence loading) of other assemblies in the silo folder.

**Comment by sergeybykov** [comment]
Oh, sorry, I completely forgot about that. Indeed. 

This call I'm almost sure is not portable. Sounds like we should either condition it or maybe remove altogether. Has anybody ever used those automatic minidumps in reality?
