### ISSUE TITLE
How to register a BootstrapProvider in Orleans 2.0 programmatically?

### ISSUE THREAD

**Issue by NitishMittalHon** [dotnet/orleans#4546]
Hi,
With Orleans 1.x.x we used to register a BootstrapProvider in OrleansConfiguration.xml as below:
```xml
    <BootstrapProviders>
      <Provider Type="MyNamespace.OrleansHostWorkerRoleBoostrapProvider"
                Name="OrleansHostWorkerRoleBoostrapProvider"
                InstanceCount="1"/>
    </BootstrapProviders>
```

With Orleans 2.0 `IBootstrapProvider` is now in Legacy library. We do not want to use the Legacy library for configurations. Also, I do not see any new service to register a bootstarp provider. I might need to replace `IBootstapProvider` with `IProvider` and register `OrleansHostWorkerRoleBoostrapProvider` as a service using `SiloHostBuilder`, but didn't get any example or code sample for that. I need your guidance here to register a BootstrapProvider.
Thanks.

**Comment by ReubenBond** [comment]
Hi @NitishMittalHon, we introduced a replacement in 2.0 called Startup Tasks, which you can read about here: https://dotnet.github.io/orleans/Documentation/Advanced-Concepts/StartupTasks.html

I hope the documentation there is able to guide you in the right direction, but please feel free to ask any follow up questions here.

**Comment by NitishMittalHon** [comment]
Thanks @ReubenBond
