### ISSUE TITLE
[doc] Ideas for Contributions needs updating

### ISSUE THREAD

**Issue by dandago** [dotnet/orleans#4548]
This thread concerns [Ideas for Contributions](https://dotnet.github.io/orleans/Community/Ideas-for-Contributions.html), which is part of the documentation under Community.

* What is OrleansMonitor? Some earlier incarnation of the OrleansDashboard?
* Port Orleans to coreclr - does this mean .NET Core? (which obviously would be resolved as of 2.0)

Not sure what other points may be obsolete, and what others may be worth adding.

**Comment by JillHeaden** [comment]
The "Ideas for Contributions" page is being deleted.
