### ISSUE TITLE
Orleans 1.5 IManagementGrain.GetRuntimeStatistics returns incorrect value for memory usage

### ISSUE THREAD

**Issue by richorama** [dotnet/orleans#4570]
Orleans 1.5.

An issue has been raised on the OrleansDashboard, where memory usage is reported to be a large negative number. 

https://github.com/OrleansContrib/OrleansDashboard/issues/140

The percentage is calculated with this formula: `(TotalPhysicalMemory ?? 0) - (AvailableMemory ?? 0)`

So perhaps TotalPhysicalMemory is not being set?

Should 'MemoryUsage` be used instead?

It's interesting to note that AvailableMemory is a float?, and MemoryUsage and TotalPhysicalMemory are both long?.

All values are passed straight through the dashboard API without being stored on alternative variables.

I haven't got a repro.

**Comment by benjaminpetit** [comment]
Closing this issue, since I don't think we will do 1.5.x release at this point.
