### ISSUE TITLE
Stream best practice question...  Should the "message" be a grain or its "primary key"? 

### ISSUE THREAD

**Issue by ausarb** [dotnet/orleans#4574]
I've been experimenting with using implicit streams to have stateless worker grains react to data becoming available.  I've got something that produces an IFoo grain and then writes it to a stream via the stream.OnNextAsync(foo) method.

This works fine (I'm currently using the SMSProvider) but I'm curious if I should be publishing the grain's primary key instead and then the stream subscriber retrieves the grain using GrainFactory.  Publishing the grain is easier and less code, but I'm assuming that the grain and its state is serialized for this to work and therefore could drastically increase network traffic between me and my eventual stream provider of Rabbit or Azure. 

_externalPublisher in this case is my own creation and I'm just using the same OnNext method name as Orleans.  It's implemented by something that will serialize the state to json and then publish it to a Rabbit exchange.

Grain as message:
```
/// <summary>
/// Reacts to new Foo's by publishing its state to Rabbit for external consumption.
/// </summary>
[StatelessWorker]
[ImplicitStreamSubscription(StreamNamespaces.FooAvailable)]
public class FooPublisherGrain : Grain, IFooPublisherGrain, IAsyncObserver<IFoo>
{
    public async Task OnNextAsync(IFoo foo, StreamSequenceToken token = null)
    {
        await _externalPublisher.OnNext(foo);
    }
}
```

Grain primary key as message:
```
/// <summary>
/// Reacts to new Foo's by publishing its state to Rabbit for external consumption.
/// </summary>
[StatelessWorker]
[ImplicitStreamSubscription(StreamNamespaces.FooAvailable)]
public class FooPublisherGrain : Grain, IFooPublisherGrain, IAsyncObserver<Guid>
{
    public async Task OnNextAsync(Guid fooKey, StreamSequenceToken token = null)
    {
        var foo = GrainFactory.GetGrain<IFoo>(fooKey);
        await _externalPublisher.OnNext(foo);
    }
}
```

**Comment by jason-bragg** [comment]
The grain reference will be serialized, not the entire grain (and it's state), but yes, that is more expensive than just sending the primary key.

**Comment by ausarb** [comment]
@jason-bragg , thanks!  If it is just the grain reference, while technically "more" expensive, that expense is worth it to me as it allows me to be more specific in my IAsyncObserver<TMessage> declaration.
