### ISSUE TITLE
Add dependency in nuget package Microsoft.Orleans.OrleansCodeGenerator.Build on Microsoft.Orleans.Core.Abstractions

### ISSUE THREAD

**Issue by Ma3yTa** [dotnet/orleans#4579]

**Comment by sergeybykov** [comment]
@ReubenBond Is there a reason `Microsoft.Orleans.OrleansCodeGenerator.Build` isn't referencing `Microsoft.Orleans.Core.Abstractions` as a dependency.

**Comment by ReubenBond** [comment]
In my opinion, the user's code should be referencing the abstractions package, and the code generator should not reference any packages.

The build-time code generator package is not a library
