### ISSUE TITLE
aka.ms/orleans

### ISSUE THREAD

**Issue by richorama** [dotnet/orleans#46]
Could I suggest pointing the http://aka.ms/orleans link to this repo now?

(also - on an unrelated note) I see there is a 1.0.0 branch, is this a release branch? Where can I get the installer for that? (codeplex is still on 0.9)

...and the CI server is returning a 404 :¬(

**Comment by jthelin-microsoft** [comment]
The DotNet group renamed the CI server last night to:

http://dotnet-ci.cloudapp.net/job/dotnet_orleans/

The Build Status badge on GitHub home page points to the right place.

**Comment by sergeybykov** [comment]
There is no 1.0.0 release yet. We were waiting to sort out the NuGet naming and the release process. Coincidentally, we had a power outage with out scale tests infrastructure for a few days that just got resolved. Now we are able to run scale/load tests against the code before we release it. Probably in a few days.

I need to figure out how to update the aka.ms link. Good point.

**Comment by sergeybykov** [comment]
Updated https://aka.ms/orleans to point to https://github.com/dotnet/orleans.
