### ISSUE TITLE
Cluster-to-Cluster communication extensibility

### ISSUE THREAD

**Issue by jsukhabut** [dotnet/orleans#4604]
I want to use Orleans Multi-cluster feature but I am hitting a road block.  I want to build a primary and failover cluster and use event sourcing to synchronize the cluster.  The problem is that I cannot set up a VPN between the two cluster.  Being able to synchronized clusters without an exposed gateway is a very valid and important scenario.

I was trying to figure out if I can extend and plug in an alternate ILogConsistencyProtocolGateway which will make calls to the other cluster through [Service Bus relays](https://docs.microsoft.com/en-us/azure/service-bus-relay/relay-hybrid-connections-http-requests-dotnet-get-started).  I difficulty because some interfaces are internal only.

What I am looking for is to be able to write implementations for the interfaces below and override the default implementation.  This was I can use other technologies proxy or relay the calls into the remote cluster.

```
    public interface IClusterMessageForwarder
    {
        Task<ILogConsistencyProtocolMessage> ForwardMessageToCluster(string clusterId, string grainId, ILogConsistencyProtocolMessage payload);
    }
```
```
    public interface IClusterMessageReceiver
    {
        Task<ILogConsistencyProtocolMessage> ReceiveMessage(string grainIdStr, ILogConsistencyProtocolMessage payload);
    }
```

**Comment by sergeybykov** [comment]
Sorry about delayed response.

Sounds like an interesting idea to me. I wonder what others think, @benjaminpetit  and @sebastianburckhardt in particular.

**Comment by sebastianburckhardt** [comment]
Sounds reasonable. I believe this would work at least for the event-sourced grains (but not for the single-instance grains).

As you observed correctly, all the synchronization code for the event-sourced replicas goes through a single communication point and we could therefore provide extensibility quite easily using dependency injection.

**Comment by benjaminpetit** [comment]
We removed the old multi cluster implementation, closing this for now

**Comment by jsukhabut** [comment]
You still have it on documentation

https://dotnet.github.io/orleans/docs/deployment/multi-cluster_support/Overview.html
