### ISSUE TITLE
SerializationManager measures ticks, not milliseconds

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#4607]
The serialization manager measures the ticks: https://github.com/dotnet/orleans/blob/e87f0e458d36dccf145de06295475831331ff0bf/src/Orleans.Core/Serialization/SerializationManager.cs#L609

But the counter says: Serialization.Body.DeepCopy.Milliseconds.Current

**Comment by ReubenBond** [comment]
@SebastianStehle the counter converts from ticks to milliseconds at display time. Here's how it's defined:
```C#
CopyTimeStatistic = CounterStatistic
    .FindOrCreate(StatisticNames.SERIALIZATION_BODY_DEEPCOPY_MILLIS, store)
    .AddValueConverter(Utils.TicksToMilliSeconds);
```

**Comment by SebastianStehle** [comment]
Strange. I enabled these counters, made a few calls to my silo and the numbers have been really large. I will check it again.

**Comment by ReubenBond** [comment]
How are you examining the value? It's only converted to millis when we read the counter as a string, the raw value always remains as ticks

**Comment by SebastianStehle** [comment]
With the dashboard.

**Comment by SebastianStehle** [comment]
https://github.com/OrleansContrib/OrleansDashboard/blob/master/OrleansDashboard/DashboardTelemetryProducer.cs

**Comment by ReubenBond** [comment]
Oh, I see... how unfortunate. The semantics of the conversion are not applied before calling your consumer

**Comment by ReubenBond** [comment]
Opened #4623 - it would be great if you could validate that it gives the right result in the dashboard, @SebastianStehle

**Comment by SebastianStehle** [comment]
Before consumers are called, right? There is nothing special about my consumer.

**Comment by ReubenBond** [comment]
No problem, @SebastianStehle, I verified locally that this works as intended.

**Comment by SebastianStehle** [comment]
Okay, thank you. I am on a business trip and my internet connection is bad most of the time.
