### ISSUE TITLE
Error when client tries to communicate with silo: Gateway received unexpected non-proxied connection

### ISSUE THREAD

**Issue by petargyurov** [dotnet/orleans#4620]
Please see this repo that should help replicate the issue. The README should explain the issue and reproduction steps in detail:

https://github.com/petargyurov/orleans-gateway-issue/tree/master

There has been some discussion on Gitter with @benjaminpetit already.

Thanks.

**Comment by sergeybykov** [comment]
These cases are cause by misconfiguration - port in client config must match the gateway port of the silo.
