### ISSUE TITLE
SiloHost ResponseTimeout won't let me change it from 30 seconds

### ISSUE THREAD

**Issue by eckerdj7** [dotnet/orleans#4622]
We have some grain methods that take longer than 30 seconds to execute, so I am trying to set the response timeout to 2 minutes. I set it on the config.Globals.ResponseTimeout and pass that config object to the SiloHost and then call InitializeOrleansSilo(). Which runs and resets the ResponseTimeout back to 30 seconds.

We've tried setting it in our config.xml file as well, to no avail. What am I doing wrong here?

**Comment by eckerdj7** [comment]
Btw, this is Orleans 1.5.

**Comment by ReubenBond** [comment]
I don't see where `ResponseTimeout` is being reset, @eckerdj7. You could try setting the value after initialization.

How are you determining that it is being overwritten?

**Comment by eckerdj7** [comment]
@ReubenBond I set a breakpoint before the initialization call and stepped over it. So beforehand, it's definitely being set.
![beforeinit](https://user-images.githubusercontent.com/4165786/40497039-36a0826e-5f49-11e8-903e-cb50e5476b1b.PNG)

And then after it is back to 30 seconds.
![afterinitialize](https://user-images.githubusercontent.com/4165786/40497086-53d8730a-5f49-11e8-8013-cd0593c5b4b5.PNG)

Setting it after initialization did not work either.

**Comment by ReubenBond** [comment]
Your VS theme is glorious, never apologize.

I see the issue, it's because `SiloHost.Config` is being set after construction and it's side-stepping the logic which says that configuration has been loaded and therefore to not load it.
If you pass the configuration in to the SiloHost constructor then this issue will not happen.

Hope that helps. This wont affect 2.x users who are not using legacy packages.

**Comment by eckerdj7** [comment]
Haha, thanks. Oh, interesting. Sounds good, I'll try that out tomorrow!

**Comment by eckerdj7** [comment]
Awesome, that worked! Thanks, @ReubenBond. Appreciate the help!

**Comment by ReubenBond** [comment]
Fantastic, happy to help!
