### ISSUE TITLE
environment connections

### ISSUE THREAD

**Issue by a641545621** [dotnet/orleans#4624]
server
   var siloPort = 20028;
            int gatewayPort = 30020;
            var siloAddress = IPAddress.Parse("0.0.0.0");// IPAddress.Loopback;
            var builder = new SiloHostBuilder()
                .UseEnvironment("Development")
                 .Configure<ClusterOptions>(options =>
                 {
                     options.ClusterId = "test1";
                     options.ServiceId = "test1";
                 })
                .UseDevelopmentClustering(options => options.PrimarySiloEndpoint = new IPEndPoint(siloAddress, siloPort))
                .ConfigureEndpoints(siloAddress, siloPort, gatewayPort)
                 .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(Test).Assembly).WithReferences());

client 
   var siloAddress = "127.0.0.1"; //IPAddress.Loopback; 
                    var gatewayPort = 30020;
                    var uri = (new IPEndPoint(IPAddress.Parse(siloAddress), gatewayPort)).ToGatewayUri();
                    client = new ClientBuilder()
                        .ConfigureDefaults()
                       // .UseLocalhostClustering(gatewayPort)
                       .Configure<ClusterOptions>(opt =>
                       {
                           opt.ClusterId = "test1";
                           opt.ServiceId = "test1";
                       })
                        ////集群
                        .UseStaticClustering(options => options.Gateways.Add(uri))//集群  
                        .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(ITest).Assembly).WithReferences())

server
 var siloAddress = IPAddress.Parse("0.0.0.0");      Can connect but cannot get information
 var siloAddress=IPAddress.Loopback;     Cannot connect service Should be server port listening failed

can you tell me the reason？
I want to test the deployment of the production environment，A silo A client silo is deployed on the server，Local test is normal access

**Comment by a641545621** [comment]
client   var siloAddress = "192.168.1.250";  
Client access address Fill in intranet address can not access normally
![94vbidke s5 _ h 6jw z5](https://user-images.githubusercontent.com/33652128/40525487-e227457c-6012-11e8-840b-361640fbb83e.png)
![e6 ksvnozwaz_ lv9x59u 4](https://user-images.githubusercontent.com/33652128/40525488-e27ec914-6012-11e8-9f5d-531bca73382f.png)

**Comment by ReubenBond** [comment]
对不起,我不明白,但是我觉得你应该用`listenOnAnyHostAddress: true`:
```C#
builder.ConfigureEndpoints(siloAddress, siloPort, gatewayPort, listenOnAnyHostAddress: true)
```

**Comment by a641545621** [comment]
normal circumstances
![1](https://user-images.githubusercontent.com/33652128/40531490-263f70d8-602f-11e8-963e-a3b8e8c54cb6.png)
![2](https://user-images.githubusercontent.com/33652128/40531495-271ac3b8-602f-11e8-8697-874d2e25434e.png)
![3](https://user-images.githubusercontent.com/33652128/40531496-2780d69e-602f-11e8-861a-dbda8d50042e.png)

The first kind of abnormal situation
![4](https://user-images.githubusercontent.com/33652128/40531639-8026434c-602f-11e8-9ca1-8ebd81f7ea14.png)
![5](https://user-images.githubusercontent.com/33652128/40531640-807d2a04-602f-11e8-83cd-ef441cd2685c.png)
![8](https://user-images.githubusercontent.com/33652128/40531871-34b2f620-6030-11e8-992c-1bf65a10903c.png)



The second abnormal situation
![6](https://user-images.githubusercontent.com/33652128/40531663-975677a8-602f-11e8-91e5-eae4b58104f6.png)
![7](https://user-images.githubusercontent.com/33652128/40531664-97b4f99a-602f-11e8-94a3-05e2f32ae609.png)

There are two problems,
1.IPAddress.Parse("192.168.1.250")   Connection failed
2.port:30020 Connection failed

I want to find out why and how to solve it

**Comment by ReubenBond** [comment]
Could you upload your broken code, @a641545621? I'll test locally

**Comment by ReubenBond** [comment]
Why is it connecting to 30020 when the silo is configured to listen on 30000?

**Comment by a641545621** [comment]
https://github.com/a641545621/orleans-test2/blob/master/host.rar
the silo is configured to listen on 30020

**Comment by ReubenBond** [comment]
After removing the `<RuntimeIdentifier>` element from your project and removing unused packages, your code works for me

**Comment by ReubenBond** [comment]
@a641545621 please reopen this issue if you are still seeing this error.
