### ISSUE TITLE
Silo Dead

### ISSUE THREAD

**Issue by mohamedhammad** [dotnet/orleans#4630]
In a two silos cluster we got the following in the log of one of them
[2018-05-26 22:14:34.069 GMT    44	WARNING	100150	Watchdog	10.1.0.6:22222]	.NET Runtime Platform stalled for 00:00:02.3323971 - possibly GC? We are now using total of 487MB memory. gc=330899, 131795, 2104	
after that with about three minutes the silo failed.
this is a log of this silo

[----APP-01-2018-05-24-11.39.24.307Z.zip](https://github.com/dotnet/orleans/files/2042566/----APP-01-2018-05-24-11.39.24.307Z.zip)

the other silo log is
[APP-01-2018-05-24-11.39.29.339Z.zip](https://github.com/dotnet/orleans/files/2042568/APP-01-2018-05-24-11.39.29.339Z.zip)

**Comment by sergeybykov** [comment]
Looks like it's actually the other silo, `10.1.0.6:22223`, got abruptly killed at 22:22:10, and `10.1.0.6:22222` logged that its socket got forcibly closed at 22:22:12. But the log of `10.1.0.6:22222` right after that.

So it appears as if somebody killed both silos at almost the same time. And that seems unrelated to the warning from 8 minutes prior to that.

**Comment by mohamedhammad** [comment]
thank you.
