### ISSUE TITLE
Orleans.Runtime.OrleansConfigurationException

### ISSUE THREAD

**Issue by bouyeijiang** [dotnet/orleans#4633]
i can't initialize configuration for orleans framework and that exception error about is it:
None of the assemblies added to ApplicationPartManager contain generated code. Ensure that code generation has been executed for grain interface and class assemblies.

my code:
interface code:

public interface IQueryLayer:IGrainWithIntegerKey
    {
        Task<List<string>> QueryPhone(string cond);
    }

instance:

public class QueryLayer:Grain,IQueryLayer
    {
        static List<string> collection = new List<string>();
        public override Task OnActivateAsync()
        {
            collection.AddRange(new string[] {"12345","23456","1254204","2142212","12451212","1824557" });
            return base.OnActivateAsync();
        }

        public Task<List<string>> QueryPhone(string cond)
        {
            var items = collection.FindAll(x => x.Contains(cond));
            return Task.FromResult<List<string>>(items);
        }
    }

function main:
var hostBuilder = new SiloHostBuilder().UseLocalhostClustering().Configure<ClusterOptions>(options =>
            {
                options.ClusterId = "dev";
                options.ServiceId = "bouyei";
            })
            .Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Loopback)
            .ConfigureApplicationParts(p => p.AddApplicationPart(typeof(QueryLayer).Assembly).WithReferences())
            .ConfigureLogging(logging => logging.AddFilter(x => x == LogLevel.Debug));

            using (var host = hostBuilder.Build())
            {
                host.StartAsync().ContinueWith(x =>
                {
                    Console.WriteLine("stared!");
                });

                Console.ReadKey();
                host.StopAsync().ContinueWith(x=> {
                    Console.WriteLine("stoped!");
                });
            }

**Comment by ReubenBond** [comment]
Add this package to your QueryLayer project: https://www.nuget.org/packages/Microsoft.Orleans.OrleansCodeGenerator.Build/

**Comment by bouyeijiang** [comment]
it is base on .net core project,but no effect

**Comment by bouyeijiang** [comment]
i got,it can be used.but client exception
System.InvalidOperationException:“Cannot find generated GrainReference class for interface 'ICorBusLayer.IQueryLayer'”

**Comment by bouyeijiang** [comment]
i got , still reference https://www.nuget.org/packages/Microsoft.Orleans.OrleansCodeGenerator.Build/

**Comment by bouyeijiang** [comment]
yeah,it is to work

**Comment by sergeybykov** [comment]
Thanks. I'll close this then.
