### ISSUE TITLE
[Migration from 1.4.2 to 2.0] Could there be incompatibility issues during deployment when upgrade is taking place?

### ISSUE THREAD

**Issue by MittalNitish** [dotnet/orleans#4636]
We are currently using Orleans 1.4.2 and upgrading the solution to Orleans 2.0.0. Ours is an Azure Cloud Service with multiple client and Silo instances.
When we will be deploying the latest build with upgraded version of Orleans, there could be some instances still up and working on Orleans 1.4.2 while others on 2.0.0. The concern is the potential incompatibility between these instances (could be because of a change in wire protocol or something else). It would be great if you can help in highlighting any such potential incompatibility and possible workarounds.

Thanks

**Comment by sergeybykov** [comment]
We discussed this over email. Do we still need this issue open?

**Comment by MittalNitish** [comment]
Thanks @sergeybykov for your inputs. Summarizing the few key point here:
1) Cluster mixing 2.0 and 1.4.2 will not work, need to deploy a new cluster.
2) ServiceId and ClusterId are two important configurations: In 2.0, now ClusterId is meant to identify a cluster in a given time, and ServiceId to identify the service: which means that during the lifetime of a service, ServiceId will be stable, but the ClusterId can change (and if you are using multicluster, you will use multiple ClusterId at the same time but still only one ServiceId). ServiceId is used for data partitioning in some storage providers, so it can be a breaking change.
3) Using a different ClusterId should work, but be aware that two different cluster will access the same data at the same time.
