### ISSUE TITLE
Orleans 1.5.2 - client side interceptor inside silo is internal

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#4643]
Hi,

I run an Orleans based cloud service without an Orleans client, purely backend, and I want to leverage client side interceptors when a grain calls another grain to transfer data using `RequestContext`. I dived into the code if I understand correctly, when a grain reference is invoked using `IGrainFactory` from within a silo, e.g. bootstrap provider or another grain, that grain reference will run `ClientInvokeCallback` delegate registered to `InsideRuntimeClient` implementing `ISiloRuntimeClient`, and those are internal, and there's no public API that makes their `ClientInvokeCallBack` accessible to user. Can this callback be exposed, perhaps via `IProviderRuntime` so a bootstrap provider could register a callback with it?

My code inspection lead to a realization that the only way to go around it (without reflection in internal types) is setup  `GrainClient` on some kind of local silo mode and use that to obtain `IGrainFactory`, and I don't like that idea since it's unnatural to invoke a grain from a silo using the `GrainClient`, and I believe it will have some cost I can't precisely describe.

**Comment by sergeybykov** [comment]
If you upgrade to 2.0, you'll be able to leverage outgoing call filters for that - http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Interceptors.html.

I don't think it's a worthwhile effort for us to backport the feature to 1.5.
