### ISSUE TITLE
Needlessly controversial terminology

### ISSUE THREAD

**Issue by palpha** [dotnet/orleans#4648]
https://github.com/dotnet/orleans/blob/cb7b101ee4847c865baefb31a78dcc6461dcf9f2/src/Orleans.Runtime/MembershipService/MembershipOracle.cs#L651
https://github.com/dotnet/orleans/blob/cb7b101ee4847c865baefb31a78dcc6461dcf9f2/src/Orleans.Runtime/MembershipService/MembershipOracle.cs#L682
https://github.com/dotnet/orleans/blob/cb7b101ee4847c865baefb31a78dcc6461dcf9f2/src/Orleans.Runtime/MembershipService/MembershipOracle.cs#L1010

There's no need to use the phrase "commit suicide". Self-destruct would be an okay euphemism, but "will shut down" feels like a perfectly good, neutral way to put it.

Feel free to avoid making any comments about "political correctness" here. ❤️

**Comment by veikkoeeva** [comment]
@palpha As a related note, there has been discussion of using `EventId` and semantic logging in general. Maybe some of this come into consideration if/when there is such refactoring.

I'll pester @jdom a bit here since he was actively discussing logging ideas not long ago in Gitter. :)

**Comment by sergeybykov** [comment]
Resolved via #4649.
