### ISSUE TITLE
Orleans - Consul clustering

### ISSUE THREAD

**Issue by satishviswanathan** [dotnet/orleans#4652]
We have been able to successfully integrate Consul for Orleans clustering. But recently we enabled ACL (Access Control List) to restrict the access to data and api and generated a acl master token and acl agent token.

Do you have an sample of passing the token from the Orleans Silo application.

var builder = new SiloHostBuilder()
                    .Configure<ClusterOptions>(options =>
                    {
                        options.ClusterId = "Cluster1";
                        options.ServiceId = "Service1";
                    })
                    .UseServiceProviderFactory(HostStartUp.ConfigureServices)
                    .UseConsulClustering(gatewayOptions =>
                    {
                        gatewayOptions.Address =   new Uri("http://10.203.xxx.xx:8500/");
                    })
                    .ConfigureEndpoints(siloPort: 11112), 
                        gatewayPort: 30002, hostname: Dns.GetHostName() )
                    .AddMemoryGrainStorageAsDefault();

**Comment by sergeybykov** [comment]
I'm afraid you need to change the Consul clustering provider to support additional configuration properties, such as to ACL master token to [ConsulClusteringSiloOptions](https://github.com/dotnet/orleans/blob/master/src/Orleans.Clustering.Consul/Options/ConsulClusteringSiloOptions.cs#L10).

If you are interested in contributing a change like that, we'll be more than happy to review.

**Comment by satishviswanathan** [comment]
@sergeybykov Thank you for you help we were able to make changes on [ConsulClusteringSiloOptions](https://github.com/dotnet/orleans/blob/master/src/Orleans.Clustering.Consul/Options/ConsulClusteringSiloOptions.cs) and [ConsulClusteringClientOptions](https://github.com/dotnet/orleans/blob/master/src/Orleans.Clustering.Consul/Options/ConsulClusteringClientOptions.cs) and got Orleans Silo and Client working with ACL token.

Please let me know if I can contribute this change.

**Comment by sergeybykov** [comment]
Great. We'd very much appreciate your contribution!

**Comment by satishviswanathan** [comment]
@sergeybykov Sorry for the delay, I've have a PR for this. 

https://github.com/dotnet/orleans/pull/4942

**Comment by sergeybykov** [comment]
@satishviswanathan That's awesome. Thank you!

**Comment by ReubenBond** [comment]
Fixed by #4942

**Comment by leoterry-ulrica** [comment]
Can hostname be replaced with IP？
@sergeybykov
