### ISSUE TITLE
How to debug deadlocks in orleans 2.0 ? (Target History)

### ISSUE THREAD

**Issue by Xanatus** [dotnet/orleans#4655]
When running into deadlocks due to circular references or other reasons, orleans gets stuck until it eventualy times out with a TimeoutException.

In orleans 1.5 it used to give an error including the grain/method name that got stuck in readable form in the target history.

In orleans 2.0 I just get something like this:

![image](https://user-images.githubusercontent.com/20849443/41015805-3f19c518-698f-11e8-94d7-241a99b7c243.png)

I have no idea how to debug this in a sane way to find which method got stuck.

Is there some kind of setting I can use to get better error messages?

**Comment by weitaolee** [comment]
I have the same problem
