### ISSUE TITLE
Give ability to configure testingHost services with lambda function

### ISSUE THREAD

**Issue by AdamWyzgol** [dotnet/orleans#4670]
I think it will be more flexible to have ability to configure testingcluster dependencies with lambda function instead of configuration class, TestClusterOptions should have additional list of functions to configure dependencies additionally to SiloBuilderConfiguratorTypes

**Comment by xiazen** [comment]
this is a good idea. It would make test cluster configuration much more convenient. Currently no matter how small a config I want to apply to a test cluster, I need a implement a ISilo(Client)BuilderConfigurator to do it. And as a result my tests project have a million configurator in it. 

And I suspect it is fairly easy to build this feature on top of our existing test cluster infrastructure. I will bring it to the team. I think they will like it too.

**Comment by AdamWyzgol** [comment]
I'm not sure if it's so easy, Actual mechanism serialize configuration to plain text before used it in cluster creation. It's easy to serialize class name, but it will be much harder to deal with lambda.

**Comment by xiazen** [comment]
yeah you are right. I didn't think deep to that. Have you thought about how to solve that?

**Comment by AdamWyzgol** [comment]
I don't have any idea how to do that now, if I found some solution I update this issue
