### ISSUE TITLE
Detected blocking task call in Orleans context

### ISSUE THREAD

**Issue by yevhen** [dotnet/orleans#4679]
We're using blocking task call detector and after we migrated to 2.x it started screaming about this line:

https://github.com/dotnet/orleans/blob/master/src/Orleans.Core/Messaging/GatewayManager.cs#L199

Please advice, whether it's a bug or not.

**Comment by benjaminpetit** [comment]
I don't think it is a big issue, since this method is called when on a timer tick, that should happen only once every 30s by default (if I remember correctly).

**Comment by benjaminpetit** [comment]
Let's move this into the backlog, because it might be a small optimization that could be done
