### ISSUE TITLE
Rename UseDistributedTM method

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#4688]
The `UseDistributedTM()` method sits on `IServiceCollection` and `ISiloHostBuilder`, but there's no way that we should have a method so ambiguously named.

Please rename to `UseDistributedTransactionManager` or something more obvious.

**Comment by xiazen** [comment]
In the case of there's only one type of TM in our system now, pointing out of which type of TM to be used is less useful now IMO. I think it might be better to just skip on the DistributedTM since it is implementation details. We can rename it to `UseTransactions` or something along the line.

**Comment by ReubenBond** [comment]
That sounds good to me, too.

In that case, though, I wonder if we should call it `AddTransactions`. I don't know the convention, but I think because we're saying "add support for transactions" rather than "use the distributed transaction manager". We should work out the convention used by the ASP.NET folk

**Comment by xiazen** [comment]
I think the convention in orleans is to use "Add" if there's multiple, such as storage providers. If it is just one, our code base almost always use "Use"

**Comment by ReubenBond** [comment]
Fixed by #4871
