### ISSUE TITLE
How to get Grain primary key from GrainReference string key

### ISSUE THREAD

**Issue by talarari** [dotnet/orleans#4693]
Hey,
we're using azure blob storage for grain state persistence.
all our grains are IGrainWithGuidKey.
We're investigating storage issues getting lots of 404 errors for blobs.
our problem is the primary key in the grainState table looks like this:
GrainReference=11e798b4058027ec3ea216eb790ad2bf03ffffff810989d7

how do we get the grain's primary key from this? i want to be able to troubleshoot this but this grainReference string means nothing to me.

**Comment by ReubenBond** [comment]
@talarari there is a utility method called `Orleans.Runtime.Utils.FromKeyString(string key, IGrainReferenceRuntime runtime)` which I think can help you

**Comment by ReubenBond** [comment]
Closing - this is answered + inactive
