### ISSUE TITLE
Message response delay on serialization failures

### ISSUE THREAD

**Issue by yevhen** [dotnet/orleans#4709]
We observe a situation where Orleans don't return a response immediately on serialization failures but rather response is timing out. Is this by design?

**Comment by sergeybykov** [comment]
Unintentionally, but sort of by design. Is the case you are seeing when a response is failing to deserialize?

**Comment by ReubenBond** [comment]
@yevhen do you have a stack trace from the silo which this occurs on? I'd like to try and fix it if possible.

**Comment by yevhen** [comment]
@sergeybykov nope, Orleans logs serialization error but client gets TimeoutException

@ReubenBond can't find it, but it occurs when trying to serialize non-serializable exception.

**Comment by ReubenBond** [comment]
As long as the non-serializable type is being sent in the message body and not in the RequestContext, then there should not be a timeout.

Either way, I need to investigate, so any repro steps/hints are appreciated

**Comment by ReubenBond** [comment]
We've made improvements to exception propagation in #4907 and backported those changes to 1.5.5 in #4944. If there's still an issue, please open a new issue to detail.
