### ISSUE TITLE
Runtime motioning on 1.5.x

### ISSUE THREAD

**Issue by talarari** [dotnet/orleans#4712]
https://dotnet.github.io/orleans/Documentation/Deployment-and-Operations/Monitoring/Runtime-Monitoring.html

there's only documentation on how to add Application insights and new relic for 2.0.
is this usable on 1.5.x? would be pretty helpful.

**Comment by xiazen** [comment]
yes, telemetry system is usable in 1.5.x. Just the public API is different. You will need to add your telemetry consumer through `LogManager.TelemetryConsumers`

Are you asking how to configure it, or are you suggesting to add a doc for it?

**Comment by xiazen** [comment]
close due to inactivity. Feel free to reopen if needed
