### ISSUE TITLE
Documentation URL structure makes no sense, lacks default pages

### ISSUE THREAD

**Issue by dandago** [dotnet/orleans#4717]
Let me walk through this to show what I mean.

I go to the 2.0 Documentation... URL is:
https://dotnet.github.io/orleans/Documentation/Introduction.html

![image](https://user-images.githubusercontent.com/13241564/41998681-36a3ce68-7a53-11e8-993c-d734e5b22231.png)

I remove Introduction.html from the URL. New URL is:
https://dotnet.github.io/orleans/Documentation/

![image](https://user-images.githubusercontent.com/13241564/41998728-5a413c5c-7a53-11e8-9e61-23180b4e993d.png)

Of course, removing another level is okay, because this is the real root of everything:
https://dotnet.github.io/orleans/

![image](https://user-images.githubusercontent.com/13241564/41998785-7aad3176-7a53-11e8-944b-273ad3d6db73.png)

Now, let's go into 1.5 Documentation. URL is:
https://dotnet.github.io/orleans/1.5/Documentation/Introduction.html

Removing the filename and going up one or two levels, as you can imagine, results in a "this page does not exist".

![image](https://user-images.githubusercontent.com/13241564/41998933-e9559ca8-7a53-11e8-9d7c-23610ca3101b.png)

I think the least we can do here is toss in an index.html in a few places and use it to redirect to Introduction.html.

But if you think about it, you have to do that under:

* /orleans/Documentation/ (points to /orleans/Documentation/Introduction.html)
* /orleans/1.5/Documentation/ (points to /orleans/1.5/Documentation/Introduction.html)
* /orleans/1.5/ (points to /orleans/1.5/Documentation/Introduction.html)

I think the above illustrates how the folder structure doesn't make that much sense. Probably that Documentation folder isn't even necessary.

This is obviously not going to change though, for link preservation and SEO reasons.

**Comment by jason-bragg** [comment]
@dandago thanks for the feedback.
We've a tech writer (for the first time!?) working on our docs now.  How much of this will effect the doc tree structure vs. just updating existing docs is unclear at this time, but feedback and suggestions are definitely welcomed.

Please see:
Orleans Documentation Tech Writer #4625
Help generating documents from code comments #4678

**Comment by dandago** [comment]
@jason-bragg thanks for pointing me to the relevant issues, it's a great thing.

As I said the structure is unlikely to change, though simply having an index page that redirects to the intro may alleviate some awkwardness for those who manually try to navigate the URL.

This is obviously a very low priority thing.

**Comment by JillHeaden** [comment]
@dandago 
I'm still working out some of the issues with the restructure, but one of the things I did was to make sure that each directory has an index.md/index.html file, so I'm hoping that will fix this. 

Just letting you know that you've been heard.

**Comment by dandago** [comment]
Thanks, I appreciate it.

**Comment by JillHeaden** [comment]
Hi again, @dandago 
The new documentation structure is in place. Would you please let me know if this was what you had in mind?
If so, I would like to close this issue.

Thanks!

**Comment by dandago** [comment]
Yes - the structure seems to make a lot more sense now. Just a few points I'd like to mention:

* Unfortunately, this change in structure breaks any existing links from other sites (including my own blog). This is what I meant by "for link preservation and SEO reasons" in my original post here. I presume this was taken in consideration when the structure was changed.
* The first page in each section (e.g. "What is a Grain" under "Core Concepts") now seems to be the index. I'm not sure this is a great idea - first because it may be necessary to rearrange the order of these pages, and secondly because that particular page loses the SEO value of having a good filename (like "what_are_orleans_packages.html").
* The first page in each section does not seem to have a large main heading in the page, like all other pages do.
* [Resources Overview](https://dotnet.github.io/orleans/Documentation/resources/index.html) - having a page like this for each section (being essentially the page for that section) could solve my second point above. Though in the case of Resources Overview, I don't think the content should go in a heading (maybe this was intended just as a placeholder).

**Comment by JillHeaden** [comment]
Those are good points. 
I'm sorry about breaking your links. My primary concern was putting things into a structure that made sense to me as a starting point. 

You are correct that it would be better to create a whole new page for each directory to be the index.html landing page that gives an overview of what is in each section and maybe has some suggestion about where the reader should go, at least for the more complicated sections. That page needs to be well thought out and I would appreciate your help with it, if you're amenable.

I will fix the missing large main heading issue soon. That will make the style more consistent.

You are spot-on about the Resources Overview. That's what I put together while I was changing the structure, and since that seems to be stable for now. 

Thank you for your insight!.

**Comment by dandago** [comment]
> I'm sorry about breaking your links. My primary concern was putting things into a structure that made sense to me as a starting point.

Oh, I'm not concerned about my blog links. I'm more concerned about developers getting confused when their Google search results for Orleans documentation yield pages that no longer exist.

> You are correct that it would be better to create a whole new page for each directory to be the index.html landing page that gives an overview of what is in each section and maybe has some suggestion about where the reader should go, at least for the more complicated sections. That page needs to be well thought out and I would appreciate your help with it, if you're amenable.

It probably just needs to be a summary of what the section is about, and perhaps provide a quick gateway/summary for each page within that section. If I were to not read any of the pages within, I should still (from this page) get a high-level, at-a-glance understanding of what concepts are covered in each page. I'd further suggest that this page is written in such a way that it conveys a story - while it could be written as a list of the pages and what they're about, it's a lot more effective if the page tells a story that flows from one concept to another without a rigid structure. I've seen this applied in books and University theses, and it tends to work very well.

**Comment by dandago** [comment]
Sure.
