### ISSUE TITLE
There is no sqlite DbConstants in DbConstantsStore?

### ISSUE THREAD

**Issue by mokezhuhy** [dotnet/orleans#4732]

**Comment by veikkoeeva** [comment]
@mokezhuhy That is true. To make it useful, adding it one would like add a the name of the ADO.NET library and load it and  then see how to (efficiently) use the database. I don't know if Sqlite would be useful considering production, but maybe on testing scenarions in case other options aren't desirable.

**Comment by mokezhuhy** [comment]
Thank you for your sharing, @veikkoeeva .

**Comment by joqkey** [comment]
@mokezhuhy How did you create the persistence files for SqLite like those listed in the repo [github orleans persistance](https://github.com/dotnet/orleans/tree/master/src/AdoNet/Orleans.Persistence.AdoNet)
