### ISSUE TITLE
404 for Code Samples link on Orleans Streams page in the documentation

### ISSUE THREAD

**Issue by jafletch** [dotnet/orleans#4733]
The page at:
[http://dotnet.github.io/orleans/Documentation/Orleans-Streams/index.html](http://dotnet.github.io/orleans/Documentation/Orleans-Streams/index.html)

Contains a link to a sample at:
[https://github.com/dotnet/orleans/blob/master/test/TestGrains/SampleStreamingGrain.cs](https://github.com/dotnet/orleans/blob/master/test/TestGrains/SampleStreamingGrain.cs)

Which is a 404. I no longer find such a file in the repo.

**Comment by JillHeaden** [comment]
The updated link is: https://github.com/dotnet/orleans/blob/master/test/Grains/TestGrains/SampleStreamingGrain.cs

I have updated the page and submitted a PR.

**Comment by JillHeaden** [comment]
@jafletch The updated page has been merged and the link works. I'd like to close this issue this week, if there are no further changes.

@jason-bragg FYI
