### ISSUE TITLE
how to build microsoft orleans source code

### ISSUE THREAD

**Issue by 731315163** [dotnet/orleans#4742]
run Build.cmd ,then error msb3802 task failed because csc.dll not found.  i used vs2017 last version.

**Comment by ReubenBond** [comment]
@731315163 do you have the .NET Core SDK installed?
https://www.microsoft.com/net/download/windows

**Comment by 731315163** [comment]
i used visual studio installer installed .net core cross platform tool ,

**Comment by ReubenBond** [comment]
Try installing the SDK from the link I provided and restart the shell before attempting to build. Maybe visual studio is installed in a non-standard location and vswhere cannot find it

**Comment by 731315163** [comment]
Hi,i installed dotnet-sdk-2.1.301-win-x64.exe.But, build.cmd say that .Net Core version required: 2.1.300
Found dotnet.exe at: "C:\Program Files\dotnet\dotnet.exe"
Found dotnet.exe at: "C:\Program Files (x86)\dotnet\dotnet.exe"
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
Tools are already initialized.

**Comment by 731315163** [comment]
the missing that D:\Project\C#Project\Orleans\Tools\dotnetcli\sdk\2.1.300\Roslyn\Microsoft.CSharp.Core.targets(52,5): error MSB3082: Task failed because "csc.dll" was not found. [D:\Project\C#Project\Orleans\test\Misc\TestInterfaces\TestInterfaces.csproj]
D:\Project\C#Project\Orleans\Tools\dotnetcli\sdk\2.1.300\Roslyn\Microsoft.CSharp.Core.targets(52,5): error MSB3883: Unexpected exception:  [D:\Project\C#Project\Orleans\test\Misc\TestInterfaces\TestInterfaces.csproj]
D:\Project\C#Project\Orleans\Tools\dotnetcli\sdk\2.1.300\Roslyn\Microsoft.CSharp.Core.targets(52,5): error : System.NullReferenceException: Object reference not set to an instance of an object. [D:\Project\C#Project\Orleans\test\Misc\TestInterfaces\TestInterfaces.csproj]
D:\Project\C#Project\Orleans\Tools\dotnetcli\sdk\2.1.300\Roslyn\Microsoft.CSharp.Core.targets(52,5): error : at Microsoft.CodeAnalysis.CommandLine.BuildServerConnection.GetBasePipeName(String compilerExeDirectory) [D:\Project\C#Project\Orleans\test\Misc\TestInterfaces\TestInterfaces.csproj]
D:\Project\C#Project\Orleans\Tools\dotnetcli\sdk\2.1.300\Roslyn\Microsoft.CSharp.Core.targets(52,5): error : at Microsoft.CodeAnalysis.CommandLine.BuildServerConnection.GetPipeNameForPathOpt(String compilerExeDirectory) [D:\Project\C#Project\Orleans\test\Misc\TestInterfaces\TestInterfaces.csproj]
D:\Project\C#Project\Orleans\Tools\dotnetcli\sdk\2.1.300\Roslyn\Microsoft.CSharp.Core.targets(52,5): error : at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [D:\Project\C#Project\Orleans\test\Misc\TestInterfaces\TestInterfaces.csproj]

**Comment by 731315163** [comment]
It’s very good ！thank you very much ，How is this going？

**Comment by ReubenBond** [comment]
This is going well :) Glad to hear that it is working now :)
