### ISSUE TITLE
Different implementations of one grain interface

### ISSUE THREAD

**Issue by muxa** [dotnet/orleans#4752]
I have a case where i need to test different implementations of a grain interface. E.g. `IMyGrain` is implemented as `MyGrainOption1` and `MyGrainOption2`. 

How do i register only one of them?

**Comment by ericgla** [comment]
There is an overload on GrainFactory.GetGrain that takes a grain class name prefix as a parameter.

`var grain = GrainFactory.GetGrain<IMyGrain>(12345, "GrainCollection.MyGrainOption1");`
