### ISSUE TITLE
Build.cmd fails on a clean environment without the Azure SDK pre installed

### ISSUE THREAD

**Issue by yoadsn** [dotnet/orleans#478]
There is a bug in the nuget restore process of the build script, only restoring the orleans.csproj project. The Microsoft.WindowsAzure.ServiceRuntime dependency is missing from this project's packages.config file and so it is not installed.
Later, the code gen fails with
error CS0234: The type or namespace name 'ServiceRuntime' does not exist in the namespace 'Microsoft.WindowsAzure'
Which fails the build.

Looking at the CI build logs, the only reason it does not fail it due to the azure SDK being preinstalled on the build machine (assuming this is an Azure instance - it makes sense).

Possible quick fix is to add this dependency to the "orleans" project packages file.

A better long term solution would be to migrate the NuGet restore to it's new approach since the 2.7 Nuget version to avoid the problem in the first place. (restoring from all projects would have solved it)

**Comment by yoadsn** [comment]
Apparently, the same problem occurs with a dependency on the Newtonsoft.Json which is fulfilled from the "Blend" installation on the CI machine.
Again, same package restore problem.

**Comment by sergeybykov** [comment]
@yoadsn Can you create a PR with the fix?

**Comment by yoadsn** [comment]
Sorry for the noise on this PR, my local settings got crazy. Last commit is the actual clean PR contents.

**Comment by jthelin** [comment]
@yoadsn - Could you try PR #481 and see if that fixes the problem you are seeing?

I think that PR should be a more complete solution compared to #480

**Comment by yoadsn** [comment]
Correct usage of NuGet restore is the ultimate solution - I agree. it's just that migration is not a simple process (I have done it multiple times, it takes tweaking to get it right).
I would wait until #481 is passing build on the CI and test it.
