### ISSUE TITLE
Gossip Channel Implementations

### ISSUE THREAD

**Issue by satishviswanathan** [dotnet/orleans#4789]
If we do not specify a Gossip channel then what would be the default gossip channel?

**Comment by benjaminpetit** [comment]
I assume your are talking about multi-clustering?

As far as I know, we only have one implementation, and that's the azure one. It will probably not work if you don't set it explicitely

**Comment by benjaminpetit** [comment]
Closing this issue, if you think you need more infos, don't hesitate to reopen it!
