### ISSUE TITLE
Request help, No client request, The  system auto Downtime

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#4790]
No concurrency, no call to Grain, born unexplained problem.
After this error, Client cannot connect to Orleans silo

Use .Net Core  V2.1.2
Use Orleans V2.0.4 

@ReubenBond Please help me see
This is all the logs that have an exception.
[Exception log.txt](https://github.com/dotnet/orleans/files/2238467/Exception.log.txt)

**Comment by HermesNew** [comment]
This problem is also encountered in the 1.5.1 .

**Comment by aqa510415008** [comment]
@ReubenBond Please help me see
This is all the logs that have an exception.
[Exception log.txt](https://github.com/dotnet/orleans/files/2238467/Exception.log.txt)

**Comment by ReubenBond** [comment]
@aqa510415008 do you have the logs which lead up to that point?

**Comment by aqa510415008** [comment]
@ReubenBond Thank you for your attention
This is all logs from startup to downtime.
[Exception log.txt](https://github.com/dotnet/orleans/files/2238481/Exception.log.txt)
Do you need a DMP file? I can reproduce this problem 100%。

**Comment by aqa510415008** [comment]
The system repeatedly reports three logs

```
[warn] Orleans.Runtime.Scheduler.WorkItemGroup[101215]: Task [Id=56, Status=RanToCompletion] in WorkGroup [Activation: S127.0.0.1:22222:270398345*grn/7483D9D2/00000000@fd32fb9d #GrainType=Orleans.Runtime.Management.ManagementGrain Placement=RandomPlacement State=Valid] took elapsed time 0:00:00.3062415 for execution, which is longer than 00:00:00.2000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/2, ManagedThreadId=12, Executing Task Id=56 Status=RanToCompletion for 00:00:00.3063404 on WorkItem=WorkItemGroup:Name=[Activation: S127.0.0.1:22222:270398345*grn/7483D9D2/00000000@fd32fb9d #GrainType=Orleans.Runtime.Management.ManagementGrain Placement=RandomPlacement],WorkGroupStatus=Running Executing for 00:00:00.3070091. .>
[fail] Runtime.Scheduler.WorkerPoolThread/3[101212]: Worker pool thread Runtime.Scheduler.WorkerPoolThread/3 (ManagedThreadId=32) has been busy for long time: Executing Task Id=5 Status=Running for 01:41:55.1708459 on WorkItem=System*WorkItemGroup:Name=*stg/14/0000000e,WorkGroupStatus=Running Executing for 01:41:55.1708995. WorkItemGroup Details: System*WorkItemGroup:Name=*stg/14/0000000e,WorkGroupStatus=Running. Currently QueuedWorkItems=0; Total EnQueued=1574; Total processed=1573; Quantum expirations=0; TaskRunner=ActivationTaskScheduler-12:Queued=0; Detailed SchedulingContext=<[SystemTarget: S127.0.0.1:22222:270398345*stg/14/0000000e@S0000000e] CurrentlyExecuting=null>.
[warn] Orleans.Runtime.Watchdog[102603]: Watchdog had 1 Health Check Failure(s) out of 2 Health Check Participants.

```

**Comment by ReubenBond** [comment]
@aqa510415008 what if you disable the dashboard?

**Comment by aqa510415008** [comment]
@ReubenBond Ok, I try to disable the dashboard,

**Comment by aqa510415008** [comment]
@ReubenBond  The problem was found. When I was doing warehousing, I implemented the IDisposable interface. The code was written to call this.Dispose(), causing Orleans to crash.

**Comment by ReubenBond** [comment]
You're calling `.Dispose()` on what?

**Comment by aqa510415008** [comment]
@ReubenBond  thank you for your help. It is when the GC is released and an error occurs and an infinite loop occurs. Cause me this problem**
