### ISSUE TITLE
OrleansAzureUtils 2.0.4 no longer depends on Streaming.AzureStorage

### ISSUE THREAD

**Issue by seniorquico** [dotnet/orleans#4800]
I updated our project's dependencies to the 2.0.4 bits on NuGet and encountered the following build error:

> The type or namespace name 'AzureQueue' does not exist in the namespace 'Orleans.Providers.Streams' (are you missing an assembly reference?)

After some quick digging, I found that the `Microsoft.Orleans.OrleansAzureUtils` package no longer depends on the `Microsoft.Orleans.Streaming.AzureStorage` package:

https://www.nuget.org/packages/Microsoft.Orleans.OrleansAzureUtils/2.0.0
https://www.nuget.org/packages/Microsoft.Orleans.OrleansAzureUtils/2.0.4

Is this expected, and should it be documented in the release notes on GitHub?

**Comment by jason-bragg** [comment]
Microsoft.Orleans.OrleansAzureUtils is a legacy package to help 1.5.x users migrate to 2.0.  Should probably avoid using it, in favor of the more specific packages (like Microsoft.Orleans.Streaming.AzureStorage).

That being set, if we're update this package, we should have the dependencies correct.
Adding to 2.0.5
