### ISSUE TITLE
Orleans StatelessWorker Grain throw System.TypeLoadException

### ISSUE THREAD

**Issue by kekekeke4** [dotnet/orleans#4801]
I create 3 projects:OLTest.Client,OLTest1.Silo,OLTest2.Silo. I implemented a StatelessWorker Grain "Hello2Stateless" in OLTest2.Silo. Then run a LTest1.Silo instance and 2 OLTest2.Silo instances.Use OLTest.Client to call Hello2Stateless for testing (grainFactory.GetGrain<IHello2Stateless> (Guid.Empty).Say ()),It runs well at this time.After that, I close Hello2Stateless Grain to activate Silo (one of two instances of OLTest2.Silo), and then use OLTest.Client to call after cluster recovery.
Hello2Stateless will throw "System.TypeLoadException: Cannot find GrainTypeData for class OLTest2.Grains.Hello2Stateless in OLTest1.Silo instance.At Orleans.Runtime.GrainTypeManager.get_Item (String className) exception." (I use OrleansDashboard to see that OLTest.Client is connected to the LTest1.Silo instance, if one of the instances in which OLTest.Client is connected to OLTest2.Silo does not appear, the cluster is using the Sql Server mode).

**Comment by ReubenBond** [comment]
@kekekeke4 are you saying that you have two separate silo projects with different `Grain` class implementations on each?

Silo 1 does not have your grain.
Silo 2 does have your grain.

Everything works at first, but then you kill silo 2 and after that you are unable to call your grain. Is that correct?

**Comment by kekekeke4** [comment]
@ReubenBond  
I create  two separate silo projects with different Grain class implementations on each
eg:project-1,project-2
then I run 3 silos :
Silo 1 does not have my grain.  (it's the project-1)
Silo 2 does have my grain.  (it's the project-2)
Silo 3 does have my grain.   (it's the project-2)
Everything works at first, but then kill silo 2 and after that  unable to call the grain. 
I think that although I shut down Slio 2,the client should be able to continue calling the gain from Silo 3,
but the client  unable to call the grain

**Comment by ReubenBond** [comment]
I believe this was fixed by #5917
