### ISSUE TITLE
Question: Silo overloaded behaviour

### ISSUE THREAD

**Issue by dekibeki** [dotnet/orleans#4806]
I am planning on using Orleans with a custom placement strategy.

If I accidently place too many grains on a particular silo, so that the particular silo cannot service all requests, what happens to the silo and/or the grains?

-Josip

**Comment by yevhen** [comment]
1. Eveything will be slow (CPU overload, Virtual Memory paging) 
2. OutOfMemoryException eventually

**Comment by dekibeki** [comment]
Thanks for the information @yevhen, and thanks for the lead @benjaminpetit 

Besides the rejecting of requests, does the load shedding deactivate or move grains?

I'm willing to implement my own shedding which does this (to fix mistakes made by my placement) and have been looking through the source to find ways to find information about the silo load so I can deactivate/move things when the load is too high.

I've found IHostEnvironmentStatistics after poking at the inbuilt shedding , but after some testing it looks like it doesn't contain useful values running on .net core 2.0. Do I need the full .NET and Windows like the inbuilt shedding to get stats through this?

Would you recommend any other way to get information about the current silo load? 

-Josip

**Comment by benjaminpetit** [comment]
> Do I need the full .NET and Windows like the inbuilt shedding to get stats through this?

Yes, it requires installing the nuget package `Microsoft.Orleans.OrleansTelemetryConsumers.Counters` and registering the performance counter like this: `siloHost.Microsoft.Orleans.OrleansTelemetryConsumers.Counters()`.

We don't have any .NET Core 2.0 implementation for `IHostEnvironmentStatistics` yet. But you can implement your own and registering with DI in the silo host.

An if you have a implementation compatible, we are open to contributions :)

**Comment by benjaminpetit** [comment]
Closing this issue, if you need more info, feel free to reopen it!
