### ISSUE TITLE
Grain can't be collection normally

### ISSUE THREAD

**Issue by luohuazhiyu** [dotnet/orleans#4818]
I set up the following：
```
...
.Configure<GrainCollectionOptions>(options =>
{
    options.CollectionAge = TimeSpan.FromMinutes(1);

})
.UseDashboard(options => { options.Port = 9090; })
```
After the Grain is collection, it can be seen through the Dashboardand has not been collection successfully.
I will not be able to activate these Grain again.
But if update SqlEventStorage.cs line 136 use Task.Run will not the problem.
This problem is very easy to happen if you introduce a third party library.

Example:
Startup need the postgresql and rabbitmq.
[Ray.git.zip](https://github.com/dotnet/orleans/files/2260031/Ray.git.zip)

**Comment by luohuazhiyu** [comment]
@benjaminpetit Some mongodb calls will also cause this problem and need to add task. Run

**Comment by benjaminpetit** [comment]
Fix should be implemented in external storage provider
