### ISSUE TITLE
Which code files are maintained for memberships tables and grain directory tables?

### ISSUE THREAD

**Issue by liuhan907** [dotnet/orleans#4822]
I'm studying the implementation of Orleans, but I've found that I can't find the specific maintenance code for the memberships table and the grain directory table. Including the entry of members, normal exit and abnormal exit, Grain activation and deactivation, and node failure when the table recovery operations.

  Could you tell me which files are the specific implementation codes of these operations?

**Comment by sergeybykov** [comment]
Did you inside the following folders?

`src\Orleans.Runtime\MembershipService`
`src\Orleans.Runtime\GrainDirectory`

Is that not what you are looking for?

**Comment by liuhan907** [comment]
I also read the code under these two folders, but I didn't know where the remote request was received and caused the two services to be invoked.

**Comment by sergeybykov** [comment]
Take a look at `MembershipOracle` and `RemoteGrainDirectory` classes.

**Comment by liuhan907** [comment]
Thank you.
I use Visual Studio to do single step tracing to study the code. There is a clue. Thank you for your reply.
