### ISSUE TITLE
Dependency on Unofficial.Microsoft.WindowsAzure.ServiceRuntime

### ISSUE THREAD

**Issue by onionhammer** [dotnet/orleans#483]
OrleansAzureUtils depends on Unofficial.Microsoft.WindowsAzure.ServiceRuntime; this out-of-date dependency is preventing update of orleans SDK from 2.5 to 2.5.1 or 2.6.

Error at runtime with azure 2.6 sdk installed:

>The type 'Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment' exists in both 'Microsoft.WindowsAzure.ServiceRuntime.dll' and 'Microsoft.WindowsAzure.ServiceRuntime.dll'

**Comment by gabikliot** [comment]
I think you should be able to solve this with binding redirect.
Take a look here:
http://dotnet.github.io/orleans/Deployment-and-Versioning-of-Dependencies

**Comment by sergeybykov** [comment]
Also, we are looking at the possibility of removing a compile time dependency on WindowsAzure.ServiceRuntime altogether.

**Comment by gabikliot** [comment]
and here: https://github.com/dotnet/orleans/issues/424

**Comment by onionhammer** [comment]
ah, thank you guys. @sergeybykov glad to hear it!

manually changing the app.config bindingredirect in silo worked;

```
        <bindingRedirect oldVersion="0.0.0.0-2.6.0.0" newVersion="2.6.0.0" />
```

**Comment by sergeybykov** [comment]
Yes, it works but too many people tripped over this. So if we can eliminate the need for a redirect, it will be better experience.

**Comment by onionhammer** [comment]
You could always provide your own package hosting the serviceruntime rather than rely on that Unofficial.Microsoft one :)

**Comment by sergeybykov** [comment]
I'd prefer us not to get into this business. :-)
