### ISSUE TITLE
Accepting into an existing Socket is not supported on this platform.

### ISSUE THREAD

**Issue by sudsy** [dotnet/orleans#4833]
Hi There, 

I am deploying Orleans within docker on linux for the first time and have found an exception in my log that so far does not seem to be causing any issues. I though it worth reporting nonetheless.

My base image for docker deployment is microsoft/dotnet:2.1-runtime 

The log I have is as follows:

`Hosting Environment is dockerprod
Using DynamoDB Clustering
[40m[1m[33mwarn[39m[22m[49m: Orleans.Runtime.NoOpHostEnvironmentStatistics[100708]
No implementation of IHostEnvironmentStatistics was found. Load shedding will not work yet
[40m[1m[33mwarn[39m[22m[49m: Orleans.Runtime.MembershipService.MembershipOracleData[100601]
Silo silo1 migrated from host ip-10-0-1-240 silo address S10.0.1.240:11111:271491670 to host ip-10-0-0-38 silo address S10.0.0.38:11111:271491664.
Orleans Silo Running
[40m[1m[33mwarn[39m[22m[49m: Orleans.Runtime.Messaging.IncomingMessageAcceptor[101036]
Exception on accepting socket during AcceptAsync
System.PlatformNotSupportedException: Accepting into an existing Socket is not supported on this platform.
at System.Net.Sockets.Socket.GetOrCreateAcceptSocket(Socket acceptSocket, Boolean unused, String propertyName, SafeCloseSocket& handle)
at System.Net.Sockets.Socket.AcceptAsync(SocketAsyncEventArgs e)
at Orleans.Runtime.Messaging.IncomingMessageAcceptor.StartAccept(SocketAsyncEventArgs acceptEventArg)
[40m[1m[33mwarn[39m[22m[49m: Orleans.Runtime.Messaging.IncomingMessageAcceptor[101036]
Exception on accepting socket during AcceptAsync
System.PlatformNotSupportedException: Accepting into an existing Socket is not supported on this platform.
at System.Net.Sockets.Socket.GetOrCreateAcceptSocket(Socket acceptSocket, Boolean unused, String propertyName, SafeCloseSocket& handle)
at System.Net.Sockets.Socket.AcceptAsync(SocketAsyncEventArgs e)
at Orleans.Runtime.Messaging.IncomingMessageAcceptor.StartAccept(SocketAsyncEventArgs acceptEventArg)
[40m[1m[33mwarn[39m[22m[49m: Orleans.Runtime.Scheduler.WorkItemGroup[101215]`

**Comment by benjaminpetit** [comment]
Can you show me how do you configure your silo?

**Comment by sudsy** [comment]
Here is my config.

```
 var deploymentId = "development";

            var environmentName = "Production";

#if DEBUG
            environmentName = "Development";
#endif


            var configBuilder = new ConfigurationBuilder()
             .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
             .AddJsonFile($"appsettings.{environmentName}.json", optional: true);

            configBuilder.AddEnvironmentVariables();
            var Configuration = configBuilder.Build();

            var pvlConfig = new PVLSettings();
            Configuration.GetSection("PVLSettings").Bind(pvlConfig);

            _taskList = new List<Task>();

            var ips = Dns.GetHostAddressesAsync(Dns.GetHostName()).Result.Where(ip => ip.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork);
            var currentIP = ips.FirstOrDefault();

            var builder = new SiloHostBuilder()


                .ConfigureEndpoints(currentIP, pvlConfig.Orleans.siloPort, pvlConfig.Orleans.gatewayPort, true)


                //Set service ID and cluster ID
                .Configure<ClusterOptions>(options =>
                {

                    options.ClusterId = pvlConfig.Orleans.clusterID;
                    options.ServiceId = pvlConfig.Orleans.serviceID;
                })
                //// Set silo name
                .Configure<SiloOptions>(options => options.SiloName = "silo1")
               //Then, we can configure the different endpoints


               //Then, we set the connection string for the storage
               .ConfigureLogging(logging => logging.SetMinimumLevel(pvlConfig.Orleans.TraceLevel).AddConsole())
                //If reminders are needed, add the service, the connection string is required
                //.UseAzureTableReminderService(connectionString)
                //If Queues are needed, add the service, set the name and the Adapter, the one shown here
                //is the one provided with Orleans, but it can be a custom one
                .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(Grains.ClientHubV2).Assembly).WithReferences())
                //If Grain Storage is needed, add the service and set the name
                //.AddAzureTableGrainStorage("AzureTableStore")
                .AddSimpleMessageStreamProvider("SMS")
                .AddMemoryGrainStorage("PubSubStore")
                //.Configure<TelemetryOptions>(options => options.AddConsumer<AITelemetryConsumer>()) //TODO, add back telemetry
                .ConfigureServices(services => {
                    services.AddTransient<IHttpClient, HttpClientProxy>();
                    services.AddTransient<IActiveMQ, LocalActiveMQ>();
                    if(environmentName == "Development")
                    {
                        services.AddTransient<ILambdaFactory, LocalDebugLambdaFactory>(_ => new LocalDebugLambdaFactory(_taskList, pvlConfig));
                    }
                    else
                    {
                        services.AddTransient<ILambdaFactory, LambdaFactory>(_ => new LambdaFactory(pvlConfig));
                    }
                    services.AddTransient<IDictionary<Guid, String>, Dictionary<Guid, String>>(_ => new Dictionary<Guid, string>());
                    services.Configure<PVLSettings>(Configuration.GetSection("PVLSettings")); 
                    
                });

            Console.WriteLine($"Hosting Environment is {pvlConfig.Orleans.HostingEnvironment}");

            switch (pvlConfig.Orleans.HostingEnvironment)
            {
                case "dockerprod":
                    Console.WriteLine("Using DynamoDB Clustering");
                    builder.UseDynamoDBClustering(options => {
                        options.Service = pvlConfig.Orleans.ClusterConfig.serviceEndpoint;
                        options.TableName = "OrleansClusterMembership";
                        });
                    break;
                case "dockerdev":
                    builder.UseDevelopmentClustering(new IPEndPoint(currentIP, pvlConfig.Orleans.siloPort));
                    break;
                case "localhostdev":
                    builder.UseLocalhostClustering();
                    break;

            }
```

In this case environmentName is set to "Production" and pvlConfig.Orleans.HostingEnvironment = "dockerprod"

**Comment by benjaminpetit** [comment]
`options.SiloName` should be unique per silo, you can have weird behaviors if multiple silos in your cluster have the same name. I would let the default value (generated guid) for now.

Can you logs all IP address available in your container? Can you try with with `listenOnAnyHostAddress` in `ConfigureEndpoints` set to false?

**Comment by sudsy** [comment]
Just FYI,
I am finally back on this project and updated my config as follows and still seeing that error.

 ```
  builder.Configure<EndpointOptions>(options =>
                    {
                        options.SiloPort = dockerSiloPort;
                        options.GatewayPort = dockerGatewayPort;
                        options.AdvertisedIPAddress = IPAddress.Parse(dockerhostip);
                        options.GatewayListeningEndpoint = new IPEndPoint(currentIP, 30000);
                        options.SiloListeningEndpoint = new IPEndPoint(currentIP, 11111);
                    });
```

**Comment by benjaminpetit** [comment]
Can you see what values are set for `dockerhostip` and `currentIP` ?

**Comment by sudsy** [comment]
Sure, an example for one of the silos is Docker host IP is 10.223.0.10, docker container ip is 172.17.0.2 .

**Comment by sudsy** [comment]
I think I have tracked down the cause. It seems to happen when I start up a second instance of an orleans silo on the same docker host. 

So for example on Docker host 10.223.0.243.

The first Docker container starts up on docker network ip address 172.17.0.2 with silo port 11111 and gateway 30000 mapped to 10.223.0.243:32769 and 10.223.0.243:32768 respectively. This container reports no errors.

When I start up a second container on the same host (for a staged a deployment prior to shutting down the first container) I see the error. The second container starts up on docker ip address 172.17.0.3 with silo port 11111 and gateway 30000 mapped to 10.223.0.243:32772 and 10.223.0.243:32771 respectively.

**Comment by benjaminpetit** [comment]
Orleans networking should be internal and not mapped to ports on the host.

I am closing this issue, please ping me if you still need help
