### ISSUE TITLE
Change Orleans.TelemetryConsumers.Counters project target platform to netstandard or netcoreapp

### ISSUE THREAD

**Issue by MelnikovIG** [dotnet/orleans#4835]
Currently `Orleans.TelemetryConsumers.Counters` targets `net461` framework. I am unable to use it with .net core app. I have an exception building `SiloHost` with `AddPerfCountersTelemetryConsumer` extension method
`System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Diagnostics.PerformanceCounter, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.' `

Looks like it uses full framework version of `System.Diagnostics.PerformanceCounter`. I think we can use netstandart version of `System.Diagnostics.PerformanceCounter` since  it is already available for netstandart https://www.nuget.org/packages/System.Diagnostics.PerformanceCounter/

**Comment by ReubenBond** [comment]
Fixed by #4914
