### ISSUE TITLE
Why is it that only the last Silo suspected of P can declare its death?

### ISSUE THREAD

**Issue by liuhan907** [dotnet/orleans#4847]
If the successor node ABC of P starts at intervals, then it is possible that A suspects P, writes; B suspects P, writes; C suspects P, writes, and in such a dead cycle can not really declare P's death.

**Comment by sergeybykov** [comment]
After each change to the cluster state (nodes added or removed) each silo recalculates which other silos in the cluster it needs to monitor. There's special handling in cases of small clusters. Even if cluster is configured for 2 votes before declaring a node dead, if the cluster has only 2 silos left, one vote will be enough to declare the suspected node dead.

**Comment by liuhan907** [comment]
Suppose the following scenario:
We have 9 nodes, called S1 - S9 respectively.
Clusters are run by default configuration.
The detection interval is 10s.
A ping failure can lead to suspicion.
The node start interval is 1s, and the 9 nodes start in sequence.
Node S1 starts at 0s.

1.  90s, node S6 offline.
2.  92S, node S3 doubting S6.
3.  93s, node S4 doubting S6.
4.  94S, node S5 doubting S6.
5.  102s, node S3 doubting S6
6.  ...

The cycle will continue, and S6 will never be declared dead.

**Comment by sergeybykov** [comment]
I'm not sure I understand this case. With default configuration of 2 votes necessary to declare a silo dead, S4 should declare S6 dead at step 3. I don't see a cycle here. Am I missing something?

**Comment by liuhan907** [comment]
Sorry, I thought the default was 3.
But even in this third step, S6 can not be declared dead.
Because, according to the Orleans document, declaring the death of a node must satisfy the following conditions:
1.  Had Z - 1 suspectors.
2.  the node that is being suspected must be the last in the list of suspectors.

So in Step 3, the last one on the list of suspectors is S3, not S4. so S4 can't declare S6 dead, just add yourself to the list of suspectors.

This information comes from Section 5.4 of [Cluster Management](http://dotnet.github.io/orleans/Documentation/Runtime-Implementation-Details/Cluster-Management.html).

**Comment by sergeybykov** [comment]
"the node that is being suspected must be the last in the list of suspectors" here means "last in time". It doesn't matter which node is the second (last) suspector in this case. It will declare the suspected node dead with its second vote on it.

**Comment by liuhan907** [comment]
>5.4 ***If S is the last suspector*** (there have already been Z-1 suspectors within time period T, as written in the suspicion column), S decides to declare P as Dead. In this case, S adds itself to list of suspectors and also writes in P's Status column that P is Dead.
>5.5 Otherwise, if S is not the last suspector, S just adds itself to the suspectors column.

Then how do we understand the "last suspector" here? Can you give an example, I still don't quite understand how to deal with it.

**Comment by sergeybykov** [comment]
The same way - last in the period of T.

Let's say Z=3, which means 3 votes are required to declare a silo dead. If S suspects P might be dead, it reads the record of P in the table, and then does one of the following two things:

1) If it sees that there are already 2 votes (Z-1) within the period of now-T in the record, it declares P dead as the last (meaning the third) suspector.

2) If it sees less than Z-1 votes within now-T in the record, it simply adds its vote (with its timestamp) to it.

**Comment by liuhan907** [comment]
Thank you very much. I made a mistake before.

**Comment by sergeybykov** [comment]
No worries. Good questions. I'll close the issue then if you don't mind.
