### ISSUE TITLE
How to create arduino web server with laravel

### ISSUE THREAD

**Issue by IsoftTech** [dotnet/orleans#4848]
Am developing a web server that collect data in a remote area using arduino, wifi, bluetooth and ethernet shield. It will automatically switch on water tabs, Arduino board to perform a specific task, check soil fertility-texture, notification on weather changes, control LEDs, notification on oil spillage, use google api to check locations, retrieve data, show temperature: humidity, read temperature, wind and humidity,check water depth, oil quality does all the analysis and show on chart: 1.Would the following languages/frameworks do the work and if not which is the best for this project? laravel, javascript, jquery and bootstrap. 2.Am using difference devices in difference places, am i creating api for each of them? 3. Is mysql good for this project or mongodb? Please, I need guide on how to start preferably videos and pdf. or if anyone interested in joining this project fork me on [github][1] thanks in advance

**Comment by ReubenBond** [comment]
Laravel is a PHP framework, but Orleans is a .NET framework - are you aiming to use Orleans in this project?

Is all of this supposed to run on Arduinos? .NET Core does not work on Arduinos, they typically use Atmel chips, which aren't a supported architecture, and they don't run a supported OS (Windows, Mac OSX, or Linux).

MongoDB and MySQL are both fine.

Do you have a question about Orleans?

**Comment by ReubenBond** [comment]
This issue was posted to another repository, specific to Laravel. I will close this here because it is not an Orleans-specific question.

**Comment by IsoftTech** [comment]
That means I'll using new framework. please can guide me?
