### ISSUE TITLE
Orleans.Transactions.TransactionInfo not in Core

### ISSUE THREAD

**Issue by JoshCollinsMSFT** [dotnet/orleans#4858]
When a transaction aborts for whatever reason, the exception that is serialized contains the Orleans.Transactions.TransactionInfo type.  That type is in Orleans.Transactions, not in Orleans.Core, so if the client doesn't reference the transactions package it fails to deserialize the exception (which unfortunately causes a grain timeout exception instead of a failed to deserialize exception to be delivered to the caller).

**Comment by jason-bragg** [comment]
What exception is including the TransactionInfo?

**Comment by xiazen** [comment]
@jason-bragg it is TransactionInfo failed to deserialize, since client side doesn't have its deserializer, because client doesn't depend on Orleans.Transaction.

**Comment by jason-bragg** [comment]
@xiazen 
"the exception that is serialized contains the Orleans.Transactions.TransactionInfo type"

I'm asking what exception this is, because no exception should include the transaction info.  If the transaction info is coming back to the client in an exception, we need to know what exception is including it, but my suspicion is that it's coming back to the client in another way, like call context, or something, .. but not inside an exception.

The client 'shouldn't' need the transaction info, so figuring out why it's being sent to the client seems central to resolving this issue.

**Comment by sergeybykov** [comment]
Cross-referencing #4793 in case there is a relation here.

**Comment by mthird** [comment]
I experienced a related problem where client applications would throw an exception while building the client.  This was with grain interfaces/clients targeting netstandard2.0 and client apps targeting netcoreapp2.1 running inside a docker container with Orleans 2.1.2.  I tried both the MSBuild and legacy Build tooling, and both threw the exception.  I was able to resolve it by referencing Microsoft.Orleans.Transactions directly in the client apps.

```
Unhandled Exception: System.TypeLoadException: Method 'get_Id' in type 'Orleans.Transactions.TransactionInfo' from assembly 'Orleans.Runtime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at OrleansGeneratedCode.OrleansCodeGen8bfc2893baFeaturePopulator.Populate(SerializerFeature feature)
   at Orleans.ApplicationParts.AssemblyAttributeFeatureProvider`1.PopulateFeature(IEnumerable`1 parts, TFeature feature)
   at Orleans.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Orleans.ApplicationPartManagerExtensions.CreateAndPopulateFeature[TFeature](IApplicationPartManager applicationPartManager)
   at Orleans.Serialization.SerializationManager.RegisterSerializers(IApplicationPartManager applicationPartManager)
   at Orleans.ClientBuilder.Build()
```

**Comment by JoshCollinsMSFT** [comment]
This is a known issue which will be addressed in a coming release.  For now, as a simple workaround you can reference the Transactions library on the client so it can deserialize these messages.

**Comment by ReubenBond** [comment]
`TransactionInfo` is now a part of a separate `Microsoft.Orleans.Transactions` package, alongside the attributes which must be placed on the interface methods to use a transaction. This means that any direct call to a transactional method must reference the `Microsoft.Orleans.Transactions` package and therefore this is no longer an issue.
