### ISSUE TITLE
Silo with EFCore Lazy Loading failed to catch System.ExecutionEngineException and crash silently

### ISSUE THREAD

**Issue by Zonciu** [dotnet/orleans#4859]
* Orleans.Server: 2.0.4
* EntityFrameworkCore: 2.1.1

I'm using EF Core and enable Lazy Loading for grain to store data.
When I use the EF entity proxy object as a return value for grain method, it will throw a `System.ExecutionEngineException`in `unknown module`, and silo fails to catch it and crash without any error message, until you debug it.
It looks like crash in `ILBasedSerializer` while deep copying the return object.

The best practice is map the entity to a dto and return, but it shouldn't causing exception if you return the proxy object directly, in ASP.NET Core when you return a EF Core proxy entity to the browser(Or serialize to json), it will works(just get an extra json key `LazyLoader: {}`).

**Comment by ReubenBond** [comment]
We're removing ILBasedSerializer in an upcoming release. For now I would recommend to avoid it - it was indented as a replacement for `BinaryFormatter` in the cases where `BinaryFormatter` was not available.
