### ISSUE TITLE
Documentation - should "Orleans Grain Interface Project" read "...Collection"?

### ISSUE THREAD

**Issue by misterspeedy** [dotnet/orleans#490]
In this page:

http://dotnet.github.io/orleans/Getting-Started-With-Orleans/Developing-a-Grain

...there is a reference to a "Orleans Grain Interface Project" template.  I can only see a "Orleans Grain Interface Collection" template.  Is this a typo in in the doc?

**Comment by sergeybykov** [comment]
Fixed the typos. Thanks!
