### ISSUE TITLE
Error Updating Orleans project to Roslyn 2.9.0

### ISSUE THREAD

**Issue by samcov** [dotnet/orleans#4915]
Using .net core 2.1,

**Note 1**: Not sure if this is a Roslyn issue or an Orleans issue
**Note 2**: Version 2.8.2 of both packages below works just fine

Upgraded Roslyn, used by one of my grains to the following:
1.  Microsoft.CodeAnalysis.Scripting 2.9.0
2. Microsoft.CodeAnalysis.CSharp.Scripting 2.9.0

Get this error: **"@obj\Debug\netstandard2.0\codegen\IvcOrleansGrains.orleans.g.args.txt"" exited with code 3.**

The assemblies changed in the nuget update process:
Successfully uninstalled 'Microsoft.CodeAnalysis.Analyzers 1.1.0' from IvcOrleansGrains
Successfully uninstalled 'Microsoft.CodeAnalysis.Common 2.8.2' from IvcOrleansGrains
Successfully uninstalled 'Microsoft.CodeAnalysis.CSharp 2.8.2' from IvcOrleansGrains
Successfully uninstalled 'Microsoft.CodeAnalysis.CSharp.Scripting 2.8.2' from IvcOrleansGrains
Successfully uninstalled 'Microsoft.CodeAnalysis.Scripting 2.8.2' from IvcOrleansGrains
Successfully uninstalled 'Microsoft.CodeAnalysis.Scripting.Common 2.8.2' from IvcOrleansGrains
Successfully uninstalled 'System.Collections.Immutable 1.3.1' from IvcOrleansGrains
Successfully uninstalled 'System.Reflection.Metadata 1.4.2' from IvcOrleansGrains

Successfully installed 'Microsoft.CodeAnalysis.Analyzers 2.6.1' to IvcOrleansGrains
Successfully installed 'Microsoft.CodeAnalysis.Common 2.9.0' to IvcOrleansGrains
Successfully installed 'Microsoft.CodeAnalysis.CSharp 2.9.0' to IvcOrleansGrains
Successfully installed 'Microsoft.CodeAnalysis.CSharp.Scripting 2.9.0' to IvcOrleansGrains
Successfully installed 'Microsoft.CodeAnalysis.Scripting 2.9.0' to IvcOrleansGrains
Successfully installed 'Microsoft.CodeAnalysis.Scripting.Common 2.9.0' to IvcOrleansGrains
Successfully installed 'System.Collections.Immutable 1.5.0' to IvcOrleansGrains
Successfully installed 'System.Reflection.Metadata 1.6.0' to IvcOrleansGrains

**Comment by ReubenBond** [comment]
Could you paste the build log, @samcov?

I hope to rectify this in future with #4934.

If you need a workaround, I believe runtime code generation should work for you.

**Comment by samcov** [comment]
I assumed that you wanted the build log when 2.9 was installed, but **I can't install 2.9 anymore in the grain project**. I recently updated VS to 15.8.3, and this is what I get from nuget.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Package restore failed. Rolling back package changes for 'IvcOrleansGrains'.				
Error	NU1107	**Version conflict detected for Microsoft.CodeAnalysis.Scripting.Common**. Install/reference Microsoft.CodeAnalysis.Scripting.Common 2.9.0 directly to project IvcOrleansGrains to resolve this issue. 
 IvcOrleansGrains -> Microsoft.CodeAnalysis.Scripting 2.9.0 -> Microsoft.CodeAnalysis.Scripting.Common (= 2.9.0) 
 IvcOrleansGrains -> Microsoft.CodeAnalysis.CSharp.Scripting 2.8.2 -> Microsoft.CodeAnalysis.Scripting.Common (= 2.8.2).	IvcOrleansGrains	H:\SignalRMicroServicesOrleansCore\src\HelloWorld.Grains\IvcOrleansGrains.csproj	1	
Error	NU1605	Detected package downgrade: Microsoft.CodeAnalysis.Scripting from 2.9.0 to 2.8.2. Reference the package directly from the project to select a different version. 
 IvcOrleansGrains -> AbaScript -> Microsoft.CodeAnalysis.Scripting (>= 2.9.0) 
 IvcOrleansGrains -> Microsoft.CodeAnalysis.Scripting (>= 2.8.2)	IvcOrleansGrains	H:\SignalRMicroServicesOrleansCore\src\HelloWorld.Grains\IvcOrleansGrains.csproj	1	
Error	NU1605	Detected package downgrade: Microsoft.CodeAnalysis.Scripting from 2.9.0 to 2.8.2. Reference the package directly from the project to select a different version. 
 IvcOrleansSiloHost -> IvcOrleansGrains -> AbaScript -> Microsoft.CodeAnalysis.Scripting (>= 2.9.0) 
 IvcOrleansSiloHost -> IvcOrleansGrains -> Microsoft.CodeAnalysis.Scripting (>= 2.8.2)	IvcOrleansSiloHost	H:\SignalRMicroServicesOrleansCore\src\SiloHost\IvcOrleansSiloHost.csproj	1

**Comment by samcov** [comment]
Ok, I managed to get it installed, and only get this error during the build.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command ""dotnet" "C:\Users\Samuel\.nuget\packages\microsoft.orleans.orleanscodegenerator.build\2.0.5\build\..\tasks\netcoreapp2.0\Orleans.CodeGeneration.Build.dll" "@obj\Debug\netstandard2.0\codegen\IvcOrleansGrains.orleans.g.args.txt"" exited with code 3.	IvcOrleansGrains	C:\Users\Samuel\.nuget\packages\microsoft.orleans.orleanscodegenerator.build\2.0.5\build\Microsoft.Orleans.OrleansCodeGenerator.Build.targets	82
