### ISSUE TITLE
Race condition with SimpleQueueCache allows for broken cursor

### ISSUE THREAD

**Issue by berdon** [dotnet/orleans#4935]
See https://gitter.im/dotnet/orleans?at=5b8ed56958a3797aa301e47e:

Essentially, a cursor being spun up with an empty sequence token was set to the first available token but not tracked. This allows for periodic purging to purge the item with the token causing the cursor to report a cache miss forever.

The fix is pretty simple and supplied by @jason-bragg. I'll throw a PR up shortly.

**Comment by jason-bragg** [comment]
Fix merged.
Thanks Berdon
