### ISSUE TITLE
Orleans.Transactions.ITransactionManagerGrain. Make sure the grain assembly was correctly deployed and loaded in the silo

### ISSUE THREAD

**Issue by zhaoqinghai** [dotnet/orleans#4938]
i use orleans.transactions v2.04 nuget, when i silobulider add UseInClusterTransactionManager() it run error,if i delete it ,it will run ok.
![image](https://user-images.githubusercontent.com/26404526/45068227-06122d80-b0f9-11e8-94f7-c52fe1c02d70.png)

**Comment by xiazen** [comment]
hmm that might be a bug in our end. `UseInClusterTransactionManager` should add transaction grain assembly as an application part, but it doesn't. 

Are you using Transaction in your application?

**Comment by xiazen** [comment]
To work around it, you can add a line to siloHostBuilder. 
```
siloHostBuilder.ConfigureApplicationParts(parts=> parts.AddApplicationPart(typeof(ITransactionManagerGrain).Assembly).WithReferences())
```

**Comment by zhaoqinghai** [comment]
yes it runs ok,but when i use transaction,it does not rollback to database, what problem does it resolve

**Comment by xiazen** [comment]
I'm afraid I don't understand the problem, I thought the problem is transaction manager grain assembly isn't added to application parts, which caused the exception. What does it have to do with database? Please elaborate more.
