### ISSUE TITLE
Tutorial code doesn't compile(?)

### ISSUE THREAD

**Issue by misterspeedy** [dotnet/orleans#494]
Following the tutorial and get stuck at this point:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Text;
using Orleans;

namespace OrleansTutorial1
{
    /// <summary>
    /// Orleans grain implementation class PlayerGrain
    /// </summary>
    public class PlayerGrain : Orleans.Grain, IPlayerGrain
    {
        private IGameGrain currentGame;

        // Game the player is currently in. May be null. 
        public Task<IGameGrain> GetCurrentGameAsync()
        {
            return TaskDone<IGameGrain>.Finished(currentGame);
        } 
    }
}

The return statement gives: 'The non-generic type Orleans.TaskDone cannot be used with type arguments."  I created the project from the suggested template.

**Comment by sergeybykov** [comment]
Fixed - should be `return Task.FromResult(currentGame);`.
