### ISSUE TITLE
Documentation on handling failures

### ISSUE THREAD

**Issue by seniorquico** [dotnet/orleans#4955]
A question came up on Gitter that highlights many of the topics on the following page are only discussed in the 1.5 Tutorials section:

http://dotnet.github.io/orleans/1.5/Tutorials/Failure-Handling.html

Finding this information in the 1.5 Tutorials section may not be intuitive to new users, and I think it would be great to see this migrated to the new Documentation navigation tree.

**Comment by JillHeaden** [comment]
This has been done and the PR has been submitted.
