### ISSUE TITLE
Multiclustering using Oracle

### ISSUE THREAD

**Issue by satishviswanathan** [dotnet/orleans#4958]
Just wanted to know whether the oracle implementation for gossip channel is complete and ready to use?

I was referring to the class MultiClusterOracle.cs

**Comment by sergeybykov** [comment]
Unless I misunderstood your question, "Oracle" in "MultiClusterOracle" has nothing to do with Oracle Database. It's rather used in the sense of "Authority". Probably, unfortunate naming.

**Comment by sergeybykov** [comment]
Hard for me to say. In principle, I don't see why not. But I'm not familiar enough with Consul to be sure.

**Comment by satishviswanathan** [comment]
@sergeybykov  I would like to get more insights on implementation of multi clustering.

My understanding of multi clustering is the ability to configure multi cluster or in my usecase we call it as different datacenters. The silo would be connected to one primary cluster and in the event of a cluster failure the next cluster should be able to the work. Is that a correct understanding?

If so in that case do we still need to implement the clustering provider?

**Comment by sergeybykov** [comment]
With multi-clustering, an app/service transparently spans multiple clusters as if they were a single cluster. 

For example, if you deploy clusters A, B, and C to three different datacenters (and configure them with the multi-cluster config), grains will be activated in silos of all three clusters, and they will be able to invoke each other no matter where they are located. Placement of grains will be determined by which of the clusters receives a first request for a particular grain. If a silo in cluster A receives a message for grain X, and X isn't currently activated anywhere, X will be placed on a silo within A.

Clients (frontends) in all three datacenters will connect their respective clusters. However, they will be able to invoke any grain activated in any of the clusters (or not yet activated). Local cluster will forward requests to other clusters if needed, and will receive responses from them in the opposite direction.
>The silo would be connected to one primary cluster and in the event of a cluster failure the next cluster should be able to the work. Is that a correct understanding?

Correct. Each silo is part of one cluster, and the clustering protocol runs as is within in. It's just on top on that, grains (and clients) can also invoke grains activated in other clusters as if they were in the same cluster. You don't necessarily need to *implement* a clustering provider. You can use an existing one. But you need to configure it separately for each of the clusters, e.g. with a storage account local to the datacenter.

In case of a cluster failure, the remaining clusters continue to operate as before. Grains that were activated in the failed cluster will eventually get reactivated in the remaining clusters, similar to how a failure of a silo is handled within a cluster.

**Comment by satishviswanathan** [comment]
@sergeybykov  I'm sharing my Silo and Client configuration code.


Silo Configuration
*******************
Using the following code I have a Silo running under PDC_Cluster and FDC_Cluster.

 var builder = new SiloHostBuilder()
                    .Configure<ClusterOptions>(options =>
                    {
                        options.ClusterId = "PDC_Cluster";
                        options.ServiceId = "MyService";

                    })
                    .UseAzureStorageClustering(azureOptions =>
                    {
                        azureOptions.ConnectionString = "DefaultEndpointsProtocol=https; ......";

                    })
                    .Configure<MultiClusterOptions>(options =>
                        {
                            options.HasMultiClusterNetwork = true;
                            options.DefaultMultiCluster = new[] { "FDC_Cluster", "PDC_Cluster" };
                            options.BackgroundGossipInterval = TimeSpan.FromSeconds(30);
                            options.UseGlobalSingleInstanceByDefault = false;
                            options.GlobalSingleInstanceRetryInterval = TimeSpan.FromSeconds(30);
                            options.MaxMultiClusterGateways = 10;
                            options.GossipChannels.Add("AzureTable", "DefaultEndpointsProtocol=https;AccountName= .....");

                        })

Client Configuration
********************

client = new ClientBuilder()

                        .Configure<ClusterOptions>(options =>
                        {
                            options.ClusterId = "PDC_Cluster";
                            options.ServiceId = "MyService";
                        })
                        .UseAzureStorageClustering(azureOptions =>
                        {
                            azureOptions.ConnectionString = "DefaultEndpointsProtocol=https;AccountName= .";
                            
                        })


Now I have my client primarily connecting to PDC_Cluster data center and able to activate the grain running in PDC Silo and when I shutdown my Silo running in PDC_Cluster then will the grain get activated in FDC_Cluster ? It doesn't seem to work for me, not sure if I'm missing something.

**Comment by satishviswanathan** [comment]
@sergeybykov. I've the Consul based gossip channel implementation almost ready, just wanted to run few test scenarios. One of which is the above mentioned one. Can you please check and let me know if I'm missing anything?

**Comment by satishviswanathan** [comment]
@sergeybykov Thank you for your reply. I didn't have any client connected to FDC cluster. I'll try that and update you.

**Comment by satishviswanathan** [comment]
@sergeybykov that use case still doesn't seem to work for me.

Initial set up
*************

1. PDC_Cluster and FDC_Cluster running with 1 silo each
2. PDC client activated a grain in PDC cluster
3. FDC client activated a grain in FDC cluster
4. Stopped 1 Silo connected to PDC cluster. So we have no silos in PDC cluster.
5. Used PDC client again to invoke the same grain and then I'm getting the exception "No gateways available."

**Comment by sergeybykov** [comment]
This is by design - the PDC client has no cluster to connect to. The FDC client should be able to talk to the grain.

The proper test here I think is as follows:
- PDC client connects to PDC cluster, activates a gain X  and sets some value in its state that the grain persists.
- FDC client connects to FDC and gets the value from the same grain X. It should see the value that PDC client has set.
- Shut down the PDC cluster (single silo in your case).
- FDC client reads the value from X. Eventually, it should read the value that PDC client has set.

**Comment by sergeybykov** [comment]
In general, we try not to delete such data, and instead use it as historical data for investigations. When somebody asks why something happened in their cluster, it is often very helpful to be able to correlate log messages with the history of node state changes.

**Comment by satishviswanathan** [comment]
@sergeybykov. The only reason I thought deleting the records would be good is when we do multiple deployments and over the period we have these stale records and the data store keeps growing.

**Comment by sergeybykov** [comment]
There was a suggestion to add auto-cleaning of old record (with a configurable definition of "old") for clustering tables. This hasn't been implemented yet.

**Comment by sergeybykov** [comment]
#3261.

**Comment by sergeybykov** [comment]
@satishviswanathan Is it working for you now as expected?
