### ISSUE TITLE
Question about 2.0 ChatRoom example

### ISSUE THREAD

**Issue by snarlynarwhal** [dotnet/orleans#4960]
How can the Channel grain detect when a user disconnects/closes the Client app in order to remove them from the onlineMembers list?

I know the client can leave the channel, but I wanted to know of a more reliable way to detect this since if a client just closes the app without leaving the channel, the user remains in the onlineMembers list indefinitely.

**Comment by sergeybykov** [comment]
Without client explicitly removing itself from the list, the Channel grain can implement a time-based expiration policy to remove registered clients if they don't rejoin periodically.

**Comment by snarlynarwhal** [comment]
Ahh okay thank you.
