### ISSUE TITLE
Code generation fails when running dotnet build without --no-restore flag

### ISSUE THREAD

**Issue by LinusCenterstrom** [dotnet/orleans#4963]
Possibly the same problem as #4877 (so the --no-restore flag might be a possible workaround there)
Using version 2.1.0-beta1 on Windows. 
Building the project from Visual Studio also works fine.
Let me know if you need more information to reproduce

The error I get is : 
`root\.nuget\packages\microsoft.orleans.orleanscodegenerator.build\2.1.0-beta1\build\Microsoft.Orleans.OrleansCodeGenerator.Build.targets(62,5): error MSB4062: The "Orleans.CodeGeneration.GetDotNetHost" task could not be loaded from the assembly root\.nuget\packages\microsoft.orleans.orleanscodegenerator.build\2.1.0-beta1\build\..\tasks\netcoreapp2.1\Orleans.CodeGeneration.Build.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask`

**Comment by ReubenBond** [comment]
@LinusCenterstrom this is likely caused by inconsistent versions of the code generator package being referenced by your projects. Please check that the versions are all identical.

**Comment by LinusCenterstrom** [comment]
The versions are the same but just like in #4877 my GrainInterfaces project is netstandard2.0 and my Silo project is netcoreapp2.1. Since I'm referencing the GrainInterfaces project from both full framework projects and Net Core projects I want to keep it netstandard.

**Comment by ReubenBond** [comment]
The new code generator package may help you here, @LinusCenterstrom. Try using  `Microsoft.Orleans.CodeGenerator.MSBuild` instead

**Comment by ReubenBond** [comment]
I'm not able to repro this, but would you be able to try adding this to your csproj files as a potential workaround?

``` xml
<PropertyGroup>
  <DotNetHost>dotnet</DotNetHost>
</PropertyGroup>
```

**Comment by LinusCenterstrom** [comment]
Switching to Microsoft.Orleans.CodeGenerator.MSBuild did fix it, thanks!
