### ISSUE TITLE
Argument Null Exception on 1.5 Cluster Startup

### ISSUE THREAD

**Issue by eckerdj7** [dotnet/orleans#4966]
I've been testing our stuff on a localhost primary silo setup for a while now and finally moved to getting onto a cluster setup. But I can't get even one silo started. I keep getting this error on startup:

![image](https://user-images.githubusercontent.com/4165786/45377348-504b5100-b5c8-11e8-9c62-812c4292548c.png)

I figure I must be missing something in the config, but I can figure out what. 

Here's my startup code:

```
var dataConnString = Config.ConnectionString("Orleans");
var config = new ClusterConfiguration();			

//	Globals
config.Globals.DataConnectionString = dataConnString;
config.Globals.RegisterStorageProvider<Orleans.StorageProviders.SimpleSQLServerStorage.SimpleSQLServerStorage>("sqlKeyValueStorage",
	new Dictionary<string, string>
	{
			{ "DataConnectionString", dataConnString },
			{ "ProviderName", "System.Data.SqlClient" },
			{ "UseJsonFormat", "both" }
	});

config.Globals.RegisterStorageProvider<Orleans.StorageProviders.SimpleSQLServerStorage.SimpleSQLServerStorage>("PubSubStore",
	new Dictionary<string, string>
	{
			{ "DataConnectionString", dataConnString },
			{ "ProviderName", "System.Data.SqlClient" },
			{ "UseJsonFormat", "both" }
	});

config.Globals.RegisterStreamProvider<SimpleMessageStreamProvider>("SmsProvider",
	new Dictionary<string, string>
	{
		{ "DataConnectionString", dataConnString },
		{ "ProviderName", "System.Data.SqlClient" },
		{ "FireAndForgetDelivery", "True" }
	});

config.Globals.ClusterId = Config.AppSetting("ClusterId");
config.Globals.ServiceId = Guid.Parse(Config.AppSetting("ServiceId"));
config.Globals.LivenessEnabled = true;
config.Globals.LivenessType = GlobalConfiguration.LivenessProviderType.SqlServer;
config.Globals.ReminderServiceType = GlobalConfiguration.ReminderServiceProviderType.SqlServer;
//config.Globals.type
config.Globals.AdoInvariant = "System.Data.SqlClient";
config.Globals.DeploymentId = "LocalHost";

//	Scheduler
config.Defaults.TurnWarningLengthThreshold = TimeSpan.FromSeconds(1);

//	Networking
config.Defaults.HostNameOrIPAddress = "127.0.0.1";
config.Defaults.Port = int.Parse(Config.AppSetting("SiloPort"));
config.Defaults.ProxyGatewayEndpoint = new IPEndPoint(IPAddress.Loopback, int.Parse(Config.AppSetting("GatewayPort")));

//	Tracing
config.Defaults.DefaultTraceLevel = Severity.Warning;
config.Defaults.TraceToConsole = true;
config.Defaults.BulkMessageLimit = 1000;
config.Defaults.TraceLevelOverrides.Add(Tuple.Create("Grain", Severity.Info));
config.Defaults.TraceLevelOverrides.Add(Tuple.Create("Runtime", Severity.Warning));

config.Globals.UseGlobalSingleInstanceByDefault = true;

var siloHost = new SiloHost(Dns.GetHostName(), config);

siloHost.SetSiloType(Silo.SiloType.None);

siloHost.InitializeOrleansSilo();

var started = siloHost.StartOrleansSilo();

if (!started)
	throw new SystemException(String.Format("Failed to start Orleans silo '{0}' as a {1} node", siloHost.Name, siloHost.Type));

Console.WriteLine("Orleans Silo is running.\nPress Enter to terminate...");
Console.ReadLine();


siloHost.ShutdownOrleansSilo();
siloHost.Dispose();
GC.SuppressFinalize(siloHost);
Console.WriteLine($"Orleans silo '{siloHost.Name}' shutdown.");
siloHost = null;
```

**Comment by ReubenBond** [comment]
Please remove this line: `config.Globals.ClusterId = Config.AppSetting("ClusterId");`

The issue here is that in 1.x, Orleans determines whether or not you're using multi-clustering simply by checking for the existence of `ClusterId`.

In 2.x, `DeploymentId` replaces `ClusterId`.

**Comment by eckerdj7** [comment]
Ok, so now I can get two silos up and running on my machine, but the second one keeps migrating to the first one. I changed the ports on the second one. Is there anything else that needs to be changed to make this work right?

**Comment by sergeybykov** [comment]
>In 2.x, DeploymentId replaces ClusterId.

Just so there is no confusion. This is true when the *legacy* configuration objects from 1.5 are used with 2.0. In the mainstream 2.0 configuration, via `ClusterOptions`, it's `ClusterId`, not `DeploymentId`.

**Comment by sergeybykov** [comment]
>Ok, so now I can get two silos up and running on my machine, but the second one keeps migrating to the first one.

What do you mean by "keeps migrating"? The two silos need to have distinct IP endpoints. If they use the same IP address, they need to use unique: `Defaults.Port` and `Defaults.ProxyGatewayEndpoint`.

**Comment by eckerdj7** [comment]
So I copied my debug folder and changed the port and proxy endpoint, then when I startup the second silo in a new cmd prompt, I get this message:

![image](https://user-images.githubusercontent.com/4165786/45437404-bac0c780-b682-11e8-9c62-1e9f01c499a8.png)

**Comment by sergeybykov** [comment]
That must be because you game those silo the same name. I believe it's a benign warning though to help detect VM migrations, as silo name is not used as the actual identity of a silo. Try giving each silo a unique name.

**Comment by eckerdj7** [comment]
Gotcha, yeah, that got rid of the warning. Everything seems to be in working order! Thanks for the help, guys!
