### ISSUE TITLE
Strange timers behaviour in Orleans 1.5.4

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#4969]
We just spotted some strange timers behaviour in our system. 
We have a healthGrain which performs some basic operations in cluster.
Invocation of that grain is in our `/api/health` endpoint and we are using it to do some regular "checking" of the entire system. It's nowhere near a comprehensive health check in a cluster but it allows us to ensure that the following is true:
1. API client can address and reach grain in silo
2. That grain can invoke other grain
3. Message to stream is passable + 
4. Timer in arbitrary grain is up and running - I would assume all other timers are working too.
5. Internally that grain being invoked on reminder every 1-5 minutes - thus I would assume all other reminders are working.

Not a rocket science and the entire implementation looks like this:
```
public class HealthCheckGrain : BaseProxyGrain, IHealthCheckGrain, IRemindable
	{
		private string _context = nameof(HealthCheckGrain);
		
		private readonly IGrainLogger _logger;
		private readonly IGrainFactory _grainFactory;
		private readonly IReminderRegistry _reminders;
		private readonly ITimerRegistry _timers;
		private readonly IStreamProviderManager _streamProvManager;

		private IDisposable _maintenanceJobTimer;

		public HealthCheckGrain(IGrainLogger logger, IGrainFactory grainFactory, IReminderRegistry reminders, ITimerRegistry timers, IStreamProviderManager streamProvManager)
		{
			// DI is working in proxy grains
			_logger = logger;
			_grainFactory = grainFactory;
			_reminders = reminders;
			_timers = timers;
			_streamProvManager = streamProvManager;
		}


		public override async Task OnActivateAsync()
		{
			// New way to register timers with DI
			_maintenanceJobTimer = _timers.RegisterTimer(this, timerCallback, null, TimeSpan.FromMinutes(1), TimeSpan.FromMinutes(3));
			// New way to register Reminders with DI
			var grainReminder = await _reminders.RegisterOrUpdateReminder(_context, TimeSpan.FromMinutes(1), TimeSpan.FromMinutes(5));

			await base.OnActivateAsync();
		}

		public override Task OnDeactivateAsync()
		{
			return base.OnDeactivateAsync();
		}

		/// <summary> Returns health response </summary>
		/// <returns> </returns>
		public async Task<string> CheckHealth()
		{
			
			var hello = _grainFactory.GetGrain<IHello>(0);
			var helloResult = await hello.SayHello($"HealthCheck @ {DateTimeOffset.UtcNow:O}");
			
			var prov = _streamProvManager.GetStreamProvider(StreamNames.StronglyTypedCoreEvents_Provider);
			await prov.GetStream<CoreEvent>(Guid.NewGuid(), nameof(HealthCheckStreamEvt)).OnNextAsync(new HealthCheckStreamEvt {Msg = "Hey hey stream is reachable WITH Injection"});
			
			await raise(new HealthCheckStreamEvt {Msg = "Hey hey stream is reachable"});

			return $"Hi, I'm a healthy grain! Stream is reachable. Response from Stateful grain: {helloResult}";
		}


		private async Task timerCallback(object grainState)
		{
			_logger.LogInfo("Working timer in 1.5.4", _context);

			await Task.CompletedTask;
		}

		public async Task ReceiveReminder(string reminderName, TickStatus status)
		{
			_logger.LogInfo($"Working reminder {reminderName} in 1.5.4", _context);
			await Task.CompletedTask;
		}
	}
```
Results of timer and reminder callbacks look like this in our SEQ logs.
Reminder (which is valid, ticks every 5 mins, as per registration above) : 
![image](https://user-images.githubusercontent.com/720822/45402627-ec915880-b699-11e8-96cc-ddc474c1bff2.png)

And timer ( should tick once every 3 minutes):
![image](https://user-images.githubusercontent.com/720822/45402680-26faf580-b69a-11e8-90e4-bdae87619ff7.png)

And the question is - what happens with timer ? It has some crazy random invocation pattern.
Grain is not marked as `[StatelessWorker]` so I would assume there is only 1 grain activation in the cluster. Previously we had bug when api endpoint was calling grain with random Guid and that registered plenty of reminders. We fixed it, now it uses Guid.Empty as grain id and cleaned up reminders from system table. But timers are stateless and looks like there is something wrong, either in Timers or in our code. And I can't understand what's and where.

**Comment by sergeybykov** [comment]
This is very strange indeed. Can you include identity of the grain in the log message? It does look as if multiple grains have the timer registered.

Also, if you pass a freshly generated `Guid` as the `state` argument to `RegisterTimer` and theninclude it in the log message, we should see how many times `RegisterTimer` gets called.

**Comment by centur** [comment]
I will do it on a separate branch, right now we removed this timer check completely cause it creates a lot of noise.

**Comment by centur** [comment]
So far I can't repro this case again in emulator :( . 
![image](https://user-images.githubusercontent.com/720822/45604280-238ab400-ba76-11e8-8ccf-4fa8a4c55757.png)

Those screenshots were from prod deployment, to run this experiment in the cloud on test - I need to set up some extra bits (health checks for TEST  from multiple locations

**Comment by centur** [comment]
I'll close this issue, haven't seen this since that incident and it's not reproduced in emulator. Looks like it was one-off glitch.
