### ISSUE TITLE
Code generation fails when there are multiple netcore SDKs on the machine

### ISSUE THREAD

**Issue by Avd6977** [dotnet/orleans#4970]
Error	MSB3073	The command ""dotnet" \.nuget\packages\microsoft.orleans.orleanscodegenerator.build\2.1.0-beta1\build\..\tasks\netcoreapp2.0\Orleans.CodeGeneration.Build.dll" "@obj\Debug\netstandard2.0\codegen\Squidex.Infrastructure.orleans.g.args.txt"" exited with code 3.	Squidex.Infrastructure	\.nuget\packages\microsoft.orleans.orleanscodegenerator.build\2.1.0-beta1\build\Microsoft.Orleans.OrleansCodeGenerator.Build.targets	82	

Removing previous SDKs fixes the issue.

**Comment by SebastianStehle** [comment]
@Avd6977 Thank you, I already reported it there: https://github.com/dotnet/orleans/issues/4956

**Comment by sergeybykov** [comment]
Closing as a duplicate of #4956. Thank you, @Avd6977!

**Comment by MatthewShelby** [comment]
I solved this by repairing the SKD file from the windows Control Panel.
