### ISSUE TITLE
No storage provider named "PubSubStore" found loading grain type Orleans.Streams.PubSubRendezvousGrain.

### ISSUE THREAD

**Issue by HawkSharp** [dotnet/orleans#4973]
When I used IAsyncstream to notify the client, I was prompted that a storage provider named “PubSubStore” was not found, but I did configure the storage provider, only the configuration name was not “PubSubStore”, and if I had storage provider's name configured as “PubSubStore”, there would be no problem. In the end, I found the class PubSubRendezvousGrain in the source code with the attribute[Storageprovider (ProviderName =  "Pubsubstore")], so I wonder if  this attribute is the reason I have to configure a stroage provider named PubSubStore?

**Comment by sergeybykov** [comment]
Yes, that's the reason. See http://dotnet.github.io/orleans/Documentation/streaming/streams_programming_APIs.html#fully-managed-and-reliable-streaming-pub-suba-namefully-managed-and-reliable-streaming-pub-suba

**Comment by HawkSharp** [comment]
Do I have to configure the name of  storage provider into "PubSubStore"? Is there any way to use other names? If I use the name "PubSubStore" to configure a MemoryGrainStorage, can I use AdoNetGrainStorage to configure others, and would this cause other problems? Could this issue be resolved in the newer version later? Much appreciation.

**Comment by HawkSharp** [comment]
But I'll report an error if I don't configure storage with the name "PubSubStore". I want to use one storage, and not multiple storage, and the name is not "PubSubStore", but is it impossible to implement now?

**Comment by sergeybykov** [comment]
>But I'll report an error if I don't configure storage with the name "PubSubStore".

Only if you are using streaming. It need a storage provider to persist subscription information.

 >I want to use one storage, and not multiple storage

What exactly do you mean by that? You can still use a single storage account or a single database. You can consider storage provider as multiple 'aliases' for the same storage they would point to in that case.

**Comment by HawkSharp** [comment]
My English is not very good and the description is not accurate. All in all, storage providers, which are alias "PubSubStore", must be configured; otherwise, IAsyncstream cannot be used

**Comment by sergeybykov** [comment]
No worries.

Yes, in order to use streams (`IAsyncStream`), you need to configure a storage provider named "PubSubStore" in the silos that the client is connecting to. See http://dotnet.github.io/orleans/Documentation/grains/grain_persistence/index.html#configuring-igrainstorage-providers for how to do that.
