### ISSUE TITLE
Error from ManagementGrain.GetRuntimeStatistics after rolling update

### ISSUE THREAD

**Issue by martinothamar** [dotnet/orleans#4980]
After a rolling update this morning the `ManagementGrain` is throwing some exception on every third call to this method. Still a 2-node cluster. The cluster is pretty new but the previous ~5 rolling updates this issue wasn't seen. Info:

- 2 Ubuntu 16.04 vm's with docker (18.06.1-ce) installed.
- Orleans 2.1.0-beta1 cohosted with ASP.NET Core running .NET Core 2.1 in docker: `FROM microsoft/dotnet:2.1-aspnetcore-runtime`

Deployment process:
* Stop silo 1, start new version of silo 1
* Wait 60 seconds
* Stop silo 2, start new version of silo 2

![Error](https://files.gitter.im/dotnet/orleans/ra9s/image.png "Orleans Dashboard")

Searched both Elasticsearch logs and stdout via `docker logs` but can't see any mention of the errors in the ManagementGrain. Only OrleansDashboard should be calling that method.

**Comment by sergeybykov** [comment]
@martinothamar Can you share the silo logs? You can email them privately if don't want to post them here.

**Comment by sergeybykov** [comment]
@martinothamar Any update on this?

**Comment by martinothamar** [comment]
Can't reproduce it anymore. It might happen for a short period during rolling updates now but always goes away in the matter of seconds. Sorry this took so long, busy times at work. We're on 2.1.0 final now and things are working very well. I'll reopen this if it happens again
