### ISSUE TITLE
Reminders documentation improvement idea

### ISSUE THREAD

**Issue by bboyle1234** [dotnet/orleans#4989]
This knowledge should be added to the Orleans reminders documentation: 

![image](https://user-images.githubusercontent.com/1445862/43936561-5d9737c4-9c9c-11e8-80df-43f80fb6d241.png)

**Comment by JillHeaden** [comment]
@ReubenBond @sergeybykov 

To clarify, it seems like I should add this information...

> If you set a reminder for a particular date and time, and the cluster happens to be down at that exact time, then the reminder tick will be skipped or missed and only the next tick of that reminder will happen.

… to the Timers and Reminders page, possibly as a caveat to the "in all situations" wording, which I have emphasized below.

> [Description
> ](http://dotnet.github.io/orleans/Documentation/grains/timers_and_reminders.html#description-1)
> Reminders are similar to timers with a few important differences:
> Reminders are persistent and will continue to trigger **in all situations** (including partial or full cluster restarts) unless explicitly cancelled.
> Reminders are associated with a grain, not any specific activation.
> If a grain has no activation associated with it and a reminder ticks, one will be created. e.g.: If an activation becomes idle and is deactivated, a reminder associated with the same grain will reactivate the grain when it ticks next.
> Reminders are delivered by message and are subject to the same interleaving semantics as all other grain methods.
> Reminders should not be used for high-frequency timers-- their period should be measured in minutes, hours, or days.

Given my understanding, that bullet point could be changed to this:

- Reminders are not written to storage, but they are persistent and will continue to trigger unless explicitly cancelled.
- Reminders will trigger during partial or full cluster restarts, but if the cluster is completely down, then the reminder tick will be missed and only the next tick of the reminder will happen.

**Comment by bboyle1234** [comment]
Something like this? 

Reminder "definitions" are written to storage. However each specific occurrence, with its specific time, is not. This has the side effect that if the cluster is completely down at the time of a specific reminder tick, it will be missed and only the next tick of the reminder will happen.

**Comment by JillHeaden** [comment]
Works for me! I will put that in and submit a PR. 

Thank you!

**Comment by sergeybykov** [comment]
Resolved via #5032.
