### ISSUE TITLE
How to debug the source code using Visual Studio 2017?

### ISSUE THREAD

**Issue by HermesNew** [dotnet/orleans#4998]
Is it possible to debug the Orleans source code in my projects?

**Comment by ReubenBond** [comment]
You ought to be able to enable SourceLink support in Visual Studio and debug it

**Comment by HermesNew** [comment]
yes,I Can Set the SourceLink in Visual Studio,but how to find the Orleans's SourceLink?

**Comment by ReubenBond** [comment]
SourceLink should discover this GitHub repo using the Orleans packages

**Comment by HermesNew** [comment]
Thanks,I already know why.unselecting the "Enable Just my code" checkbox.
