### ISSUE TITLE
[Question] Any plans for migration to netstandard2.1?

### ISSUE THREAD

**Issue by MelnikovIG** [dotnet/orleans#5000]
And start using improved .net core runtime and new built-in features like `Span<T>` and others?

**Comment by sergeybykov** [comment]
Did you mean .NET Core 2.1? I don't see .NET Standard 2.1 being available.

In general, we are conservative about moving to latest and greatest versions of dependencies, so that we don't force Orleans users to migrate before they are ready. With support for .NET Core 2.0 ending soon, we could consider moving to building against 2.1. Not Orleans 2.1.0 that is pretty much done, but potentially 2.2.0.

**Comment by MelnikovIG** [comment]
@sergeybykov I got you point, make sense. How do you decide when users are ready? I think with self contained feature of net core apps it will not be a problem for end users to migrate from 2.0 to 2.1.

**Comment by ReubenBond** [comment]
@MelnikovIG we hope to always be able to support the latest version. By supporting .NET Standard 2.0, we will be compatible with .NET Core 2.1, 2.2, and beyond. In the case where there are features in those newer platforms which we want to take advantage of *in the Orleans codebase*, then we will need to multi-target.

**Comment by MelnikovIG** [comment]
@ReubenBond  multi-target is nice, can we use this approach? In this case we need to prepare tests to run on multiple platforms, and add some tricky conditional references, if we want to use for example `System.Span`, which is included in platform starting from core 2.1, and can be added as nuget package for lower versions https://www.nuget.org/packages/System.Memory/

**Comment by ReubenBond** [comment]
@MelnikovIG you can use that in your own applications with Orleans today - but we cannot use it within Orleans itself yet.

.NET Standard 2.1 adds most of what we might want, but we will continue targeting .NET Standard 2.0 as a minimum in the Orleans 2.x series, even when .NET Standard 2.1 becomes available. Perhaps we can multi-target .NET Standard 2.1 at that time, or .NET Core 2.1.

For Orleans 3.x, maybe we can target a higher minimum.

**Comment by MelnikovIG** [comment]
@ReubenBond Thanks for clarification, i think issue can be closed?

**Comment by ReubenBond** [comment]
Sure thing - hopefully we can make use of the newer runtime features soon.
