### ISSUE TITLE
New CodeGenerator fails with packages such as Orleans.Dashboard which are built with old code generator

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#5007]
I tested 2.1.0-ci.20180919.3 from myget.

The build works but when I run the application I get the following exception:

`Method not found: 'Void Orleans.Serialization.SerializerFeature.AddSerializerType(System.Type, System.Type)`

The stacktrace is from Orleans Dashboard which was build with the old code generator.

But because you added  a  new parameter it fails: https://github.com/dotnet/orleans/blob/ffabe550a7891e7378f9f076e88a8e3c184d967f/src/Orleans.Core.Abstractions/Serialization/SerializerFeature.cs#L36

A good old method overload should fix the problem.

**Comment by ReubenBond** [comment]
@SebastianStehle, we've pushed a new CI build to MyGet, could you please test it? I hope it rectifies the issue.

**Comment by SebastianStehle** [comment]
Is the second merge also pushed?

**Comment by ReubenBond** [comment]
It should be on MyGet - which version do you have now? Make sure to do a full clean, etc, and upgrade all pkgs

**Comment by ReubenBond** [comment]
20180921.1 should be the correct suffix
