### ISSUE TITLE
Can a Grain subscribe to multiple streams at the same time?

### ISSUE THREAD

**Issue by TulkasLaugh** [dotnet/orleans#5009]
Hi, I've been trying to use Explicit Streams and have 2 separate clients calling the grain's method to subscribe to different streams. However, when the 2nd client is trying to have the grain subscribe to a second stream (after it subscribed to a different stream), nothing happens. No errors, no exceptions or anything. Can grains subscribe to multiple different streams at the same time (assuming all the OnNextAsync() are stubbed out)?.

**Comment by sergeybykov** [comment]
Yes, a grain can subscribe to multiple streams at the same time.

**Comment by sergeybykov** [comment]
It's not 100% clear to me how you organized that. Make sure that you don't have call cycles between those grains: grain A calling grain B which while executing the call calls A. It shouldn't be happening is you are using streams, unless you are using the SMS provider.

**Comment by sergeybykov** [comment]
@TulkasLaugh Any update?
