### ISSUE TITLE
Two sets of Orleans tutorials

### ISSUE THREAD

**Issue by misterspeedy** [dotnet/orleans#501]
There seem to be two sets of tutorials online:

These:

http://dotnet.github.io/orleans/Getting-Started-With-Orleans/

...and these:

https://orleans.codeplex.com/wikipage?title=My%20First%20Orleans%20Application&referringTitle=Step-by-step%20Tutorials

The latter seem to be a bit more step-by-step while the former seem to vary between being tutorial ("do this, do that and it'll work") and being a more general discussion of Orleans concepts, so it's hard to see which bits of code one should actually be implementing.  On the other hand things usually seem to get migrated from codeplex to github so maybe the github one is the more up to date.  It would be good to have one clearly signposted tutorial series.

**Comment by jthelin** [comment]
This page should be the equivalent of that old one on CodePlex. 
We migrated all the docs across from CodePlex and recreated using github pages.

http://dotnet.github.io/orleans/Step-by-step-Tutorials/

We should probably remove the old pages on CodePlex and/or mark them as deprecated to avoid confusion like this.

**Comment by gabikliot** [comment]
@jthelin , did you delete the old codeplex tutorials? We removed the main link a while ago, but forgot to delete the actual content I guess, so people with direct link can still get to it. We should completely remove it, to avoid any future confusion.

**Comment by jthelin** [comment]
@gabikliot - Yes, i am already talking to the CodePlex guys internally about how to remove all the out-of-date wiki pages on CP. 
Worst case we might have to just delete them one-by-one, but i was hoping they have an easier way to do bulk delete for us. 
Watch this space....

**Comment by gabikliot** [comment]
Thanks.

**Comment by gabikliot** [comment]
I just deleted all old CodePlex documentation files manually.
No more confusion any more.
All documentation is on github.io pages.

**Comment by misterspeedy** [comment]
Thankyou Gabriel.   Nice one.
