### ISSUE TITLE
How to write a client in .NET Standard 2.0 that can connect to old v1.5 server?

### ISSUE THREAD

**Issue by marcin-synak** [dotnet/orleans#5013]
I have an old Orleans v1.5 cluster which cannot be updated to v2 ATM.

I'm writing an Azure Function v2 which is a .NET Standard 2.0 application.

This applications needs an Orleans Client to connect to the old cluster. Unfortunately, the latest available client library (NuGet: Microsoft.Orleans.Client 1.5.5) does not work with .NET Standard 2.0 (there is an issue with dependency injection described in #3325).

I tried using the latest v2 client (NuGet: Microsoft.Orleans.Client 2.0.3), but it is obviously not compatible with old cluster, since it fails with an exception during connection:

``
NotImplementedException
Orleans: interfaceId=-1666714017,methodId=1041119701.
``

Is there some workaround (legacy mode?) to make new client work with old server? There was a fix that would make the old client work with .NET Standard 2.0 (issue #3356) but it was never implemented into 1.5 branch.

**Comment by sergeybykov** [comment]
No easy workaround I'm afraid other than maybe running a 1.5.5 client as a separate process and marshalling commands to and responses from it.

**Comment by marcin-synak** [comment]
That's what I was afraid of.

For now, we've decided to write a simple web proxy. Instead of calling grains directly, we make HTTP calls. The proxy performs grain operations and returns JSON.
Most of our grains are used to gather and return information when needed so it should be enough.
