### ISSUE TITLE
Tutorial on Codeplex doesn't compile

### ISSUE THREAD

**Issue by misterspeedy** [dotnet/orleans#502]
The tutorial code here:

https://orleans.codeplex.com/wikipage?title=My%20First%20Orleans%20Application&referringTitle=Step-by-step%20Tutorials

Has the same issue as logged (and fixed - thanks!) here:

https://github.com/dotnet/orleans/issues/494

**Comment by jthelin** [comment]
There have been several minor but significant changes in the APIs since the project moved to GitHub.
Try these tutorial pages instead:

http://dotnet.github.io/orleans/Step-by-step-Tutorials/

Sorry for confusion.
