### ISSUE TITLE
Build is failed while using Microsoft.AspNetCore.SignalR.Client in a grain

### ISSUE THREAD

**Issue by arsamigullin** [dotnet/orleans#5038]
I want each grain to be a SignalR client. In each grain, I have a HubConnection instance.  This is a code of grain :
```
public class MyGrain : Grain, IMyGrain
{
	private string _accessToken;
	private HubConnection connection;
	private MyHttpClient = _httpClient; // initialized in a constructor (constructor is omitted)
	
	public async Task Login(string username, string password)
	{
		//
		//... some stuff
		//
		var response = await _httpClient.Login(username, password);
		_accessToken = response.AccessToken;
		connection = new HubConnectionBuilder()
		// having this overload of WithUrl the code compilation is successful
		.WithUrl("https://some_server/eventpipelinehub") //row 17
		// having this overload of WithUrl the code compilation is failed
        .WithUrl("https://some_server/eventpipelinehub", options => options.AccessTokenProvider = () => Task.FromResult(_accessToken)) // row 19
        .Build();
	}
}

```

The code above is compiled successfully only when I have an overload of the WithUrl method as shown in row 17.
But I need another overload and the code compilation is failed when I have an overload of WithUrl method as shown in row 19 with the following message:
Error	MSB3073	The command ""dotnet" "C:\Users\UserName\.nuget\packages\microsoft.orleans.orleanscodegenerator.build\2.1.0-rc2\build\..\tasks\netcoreapp2.1\Orleans.CodeGeneration.Build.dll" "@C:\projects\myProjectName\\_obj\Debug\Bots\netcoreapp2.1\codegen\Bots.orleans.g.args.txt"" exited with code 3.	Bots	C:\Users\UserName\.nuget\packages\microsoft.orleans.orleanscodegenerator.build\2.1.0-rc2\build\Microsoft.Orleans.OrleansCodeGenerator.Build.targets	82 

I saw a similar issue https://github.com/dotnet/orleans/issues/2896 and I saw ReubenBond added new Code Generator and tried to compile the code with Microsoft.Orleans.OrleansCodeGenerator.Build package of versions 2.05 and 2.1.0-rc2 (as). The error still persists. In the project properties, the Platform Target is Any CPU

This is what I have on my machine:
MS Windows 10 x64
Microsoft.AspNetCore.SignalR.Client 1.0.3
Microsoft.Orleans.OrleansCodeGenerator.Build 2.1.0-rc2 and 2.0.5
Microsoft.Orleans.Core 2.0.3
C:\Users\UserName>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  1.1.7 [C:\Program Files\dotnet\sdk]
  1.1.9 [C:\Program Files\dotnet\sdk]
  1.1.10 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by ReubenBond** [comment]
The new code generator package is `Microsoft.Orleans.CodeGenerator.MSBuild`, is that the one you used?

**Comment by arsamigullin** [comment]
I used Microsoft.Orleans.OrleansCodeGenerator.Build 2.1.0-rc2 from https://www.nuget.org/packages/Microsoft.Orleans.OrleansCodeGenerator.Build/2.1.0-rc2

**Comment by arsamigullin** [comment]
I tried the generator from https://www.nuget.org/packages/Microsoft.Orleans.CodeGenerator.MSBuild/2.1.0-rc2
Now I have such errors:
Error	CS1501	No overload for method 'AddSerializerType' takes 3 arguments	MyProj C:\projects\ProjectName\_obj\Debug\MyProj\netcoreapp2.1\Bots.orleans.g.cs	244	Active

**Comment by ReubenBond** [comment]
Are all packages updated to use the new code generator? If not, update them, and update all packages to 2.1.0-rc2.

**Comment by arsamigullin** [comment]
@ReubenBond updating packages helped. Thank you.

**Comment by ReubenBond** [comment]
Great, should we close this issue?

**Comment by arsamigullin** [comment]
@ReubenBond, unfortunately, have to reopen the issue. **Everything is updated**:
Microsoft.Orleans.Core 2.1.2
Microsoft.Orleans.OrleansCodeGenerator.Build 2.1.2, taken from https://www.nuget.org/packages/Microsoft.Orleans.CodeGenerator.MSBuild/2.1.2

The build is failed because of row 19 in the code snippet (a very first comment) with an error:
Error	MSB3073	The command ""dotnet" "C:\Users\User\.nuget\packages\microsoft.orleans.orleanscodegenerator.build\2.1.2\build\..\tasks\netcoreapp2.1\Orleans.CodeGeneration.Build.dll" "@C:\projects\projectName\\_obj\Debug\Bots\netcoreapp2.1\codegen\Bots.orleans.g.args.txt"" exited with code 3.	C:\Users\User\.nuget\packages\microsoft.orleans.orleanscodegenerator.build\2.1.2\build\Microsoft.Orleans.OrleansCodeGenerator.Build.targets	82

**Comment by arsamigullin** [comment]
Sorry, my bad. Everything works fine. Thank you

**Comment by leoterry-ulrica** [comment]
@arsamigullin I had the same problem, but the same solution didn't work.

MSB3073	命令“"dotnet" "C:\Users\thinkpad\.nuget\packages\microsoft.orleans.codegenerator.msbuild\2.1.2\build\..\tasks\netcoreapp2.0\Orleans.CodeGenerator.MSBuild.dll" SourceToSource "D:\aws-gitlab\dme\SH2018CP030\src\Dist.Product.Dme\Dist.Dme.Orleans.Interfaces\obj\x86\Debug\netcoreapp2.1\Dist.Dme.Orleans.Interfaces.orleans.g.args.txt"”已退出，代码为 3。	Dist.Dme.Orleans.Interfaces	C:\Users\thinkpad\.nuget\packages\microsoft.orleans.codegenerator.msbuild\2.1.2\build\Microsoft.Orleans.CodeGenerator.MSBuild.targets	122

**Comment by arsamigullin** [comment]
@leoterry-ulrica, like ReubenBond said, make sure that all the Orleans packages have the same versions as Orleans Code Generator.

**Comment by leoterry-ulrica** [comment]
@arsamigullin all version is 2.1.2

**Comment by arsamigullin** [comment]
@leoterry-ulrica, let's reopen the issue then and please refer your question to @ReubenBond

**Comment by leoterry-ulrica** [comment]
@arsamigullin thanks
the target framework of all projects is .NET CORE2.1. 
![image](https://user-images.githubusercontent.com/18339429/47411396-25dddd80-d79b-11e8-9bcc-a84c4e9c4abf.png)
![image](https://user-images.githubusercontent.com/18339429/47411406-31310900-d79b-11e8-934a-a98be85fd645.png)
![image](https://user-images.githubusercontent.com/18339429/47411417-3aba7100-d79b-11e8-9f14-3d50c710c63d.png)

the detail of exception is 

错误	MSB3073	命令“"dotnet" "C:\Users\thinkpad\.nuget\packages\microsoft.orleans.codegenerator.msbuild\2.1.2\build\..\tasks\netcoreapp2.0\Orleans.CodeGenerator.MSBuild.dll" SourceToSource "D:\aws-gitlab\dme\SH2018CP030\src\Dist.Product.Dme\Dist.Dme.Orleans.Interfaces\obj\x86\Debug\netcoreapp2.1\Dist.Dme.Orleans.Interfaces.orleans.g.args.txt"”已退出，代码为 3。	Dist.Dme.Orleans.Interfaces	C:\Users\thinkpad\.nuget\packages\microsoft.orleans.codegenerator.msbuild\2.1.2\build\Microsoft.Orleans.CodeGenerator.MSBuild.targets	122	

Looking forward to your solution. Thanks.

**Comment by arsamigullin** [comment]
@leoterry-ulrica, I suggest examining [some solutions](https://stackoverflow.com/questions/37208853/net-2015-references-with-yellow-triangle-for-nuget-packages-on-portable-librari) to get rid of these warning triangles

**Comment by leoterry-ulrica** [comment]
@arsamigullin Reloading the project solves the warning triangles.

**Comment by leoterry-ulrica** [comment]
The problem has been solved.  #5124 
thx

**Comment by sergeybykov** [comment]
This can be closed again, right?

**Comment by arsamigullin** [comment]
From my side, there are no any concerns as well. I am closing it. Thanks.
