### ISSUE TITLE
When I Use Orleans Microsoft.Orleans.CodeGenerator.MSBuild 2.1.0 Build the Interface  failed.

### ISSUE THREAD

**Issue by HermesNew** [dotnet/orleans#5041]
` public void Populate(global::Orleans.Serialization.SerializerFeature feature)
        {
            feature.AddSerializerType(typeof(global::Services.ES.DTO.Tool.Bulk.Respond.RespondBeginBulkDTO), typeof(Services.ES.DTO.Tool.Bulk.Respond.OrleansCodeGenMJSaas_Services_ES_DTO_Tool_Bulk_Respond_RespondBeginBulkDTOSerializer), false);
            feature.AddKnownType("System.Threading.Tasks.Task`1", "Task'1");
}`

Error Message: CS1501 “AddSerializerType” method not have 3 parameters override.

**Comment by HermesNew** [comment]
The reason may be that the interface contains serializable type.

**Comment by ReubenBond** [comment]
Could you please post your csproj files?

**Comment by HermesNew** [comment]
I remove the serializable type,it's can build success.

**Comment by HermesNew** [comment]
Of course, after being cleared

**Comment by HermesNew** [comment]
This attribute: [Serializable]

**Comment by HermesNew** [comment]
Implement have the same issue.

**Comment by HermesNew** [comment]
I have use the Microsoft.Orleans.OrleansCodeGenerator.Build,it can build success.

**Comment by ReubenBond** [comment]
Could you please post a repro? I'll try to fix it next week. Thanks for reporting

**Comment by HermesNew** [comment]
ok

**Comment by HermesNew** [comment]
btw,my .net version is .net framework4.6.1

**Comment by HermesNew** [comment]
@ReubenBond  repro : https://github.com/HermesNew/OrleansTest.git

**Comment by ReubenBond** [comment]
@HermesNew update your csproj format to support the new tooling:
``` xml
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Core.Abstractions" Version="2.1.0" />
    <PackageReference Include="Microsoft.Orleans.CodeGenerator.MSBuild" Version="2.1.0" PrivateAssets="All" />
  </ItemGroup>

</Project>
```

**Comment by HermesNew** [comment]
Change the TargetFramework to netstandard2.0,it can work well.
Thanks.
