### ISSUE TITLE
Lifetime of services injected into grains

### ISSUE THREAD

**Issue by ifle** [dotnet/orleans#5042]
It's not clear what is lifetime of a service that registered as services.AddScoped in silo and injected into grain? In case of silo and grains what is different between AddScoped and AddTransient?
For example I have a grain that can be activated by client, stream or reminder. This grain can activate hundred another grains . By default lifetime of each grain is 2 hour. In this case what is request scope?
I have not found any documentation about DI on Olreans.

**Comment by xiazen** [comment]
if AddScoped is used, each grain activation has its own scope, so the service's lifetime is within the grain activation. 
If AddTransient is used, then each time you call GetService on that type,  it is a new one. For docs on this one, please go to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1. 

AddScope is also their concept, it is just orleans create a new scope for each grain activaiton.

**Comment by xiazen** [comment]
close due to inactivity. Feel free to reopen.
