### ISSUE TITLE
Grain services documentation

### ISSUE THREAD

**Issue by bboyle1234** [dotnet/orleans#5046]
This knowledge could be included in the documentation concerning grain services:

![image](https://user-images.githubusercontent.com/1445862/46273805-6c745980-c59a-11e8-9a3e-3d16bb60c9b6.png)

**Comment by JillHeaden** [comment]
I added the information to Note 1:

> The `Orleans.Runtime` Nuget package should be imported into the GrainService base class.

**Comment by sergeybykov** [comment]
Resolved via #5050.
