### ISSUE TITLE
Slow access to Azure Table "OrleansReminders" for "ReadTableEntriesAndEtags", which took 00:00:03.0158598

### ISSUE THREAD

**Issue by ifle** [dotnet/orleans#5048]
Where is a problem in case of these warnings:
`
Slow access to Azure Table "OrleansReminders" for "ReadTableEntriesAndEtags", which took 00:00:03.0158598.
`

`
Slow access to Azure queue "xxx-app-appeventsstreamprovider-6" for "GetQueueMessages", which took 00:00:04.1207254. 
`

**Comment by rmja** [comment]
Are you using the storage emulator? I am getting this warning a-lot when using the emulator. It is incredibly slow.

**Comment by ifle** [comment]
No, this is production environment

**Comment by sergeybykov** [comment]
If you only see them occasionally, they may simply indicate occasional delay response from Azure Storage. If you see them consistently, I would check that the .NET thread pool isn't overloaded (which can delay execution of storage call responses).

**Comment by ifle** [comment]
I only see them occasionally

**Comment by ifle** [comment]
Yes, thanks
