### ISSUE TITLE
Sample Project Cross Reference

### ISSUE THREAD

**Issue by raybooysen** [dotnet/orleans#505]
The sample projects seem to cross reference each other.  For example, at the moment, on a clean clone, the HelloWorld sample does not build.  If you open the csproj file, note this line:

``` csharp
<Error Condition="!Exists('..\..\AzureWebSample\packages\Microsoft.Orleans.Templates.Interfaces.1.0.8\build\Microsoft.Orleans.Templates.Interfaces.props')" Text="$([System.String]::Format('$(ErrorText)', '..\..\AzureWebSample\packages\Microsoft.Orleans.Templates.Interfaces.1.0.8\build\Microsoft.Orleans.Templates.Interfaces.props'))" />
    <Error Condition="!Exists('..\..\AzureWebSample\packages\Microsoft.Orleans.Templates.Interfaces.1.0.8\build\Microsoft.Orleans.Templates.Interfaces.props')" Text="$([System.String]::Format('$(ErrorText)', '..\..\AzureWebSample\packages\Microsoft.Orleans.Templates.Interfaces.1.0.8\build\Microsoft.Orleans.Templates.Interfaces.props'))" />
    <Error Condition="!Exists('..\..\AzureWebSample\packages\Microsoft.Orleans.Templates.Interfaces.1.0.8\build\Microsoft.Orleans.Templates.Interfaces.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\AzureWebSample\packages\Microsoft.Orleans.Templates.Interfaces.1.0.8\build\Microsoft.Orleans.Templates.Interfaces.targets'))" />
```

These lines reference the AzureWebSample project.  Note that the AzureWebSample project references the same HelloWorld projects in the HelloWorld solution, notable HelloWorldGrains and HellowWorldInterfaces.

I suggest that each sample should be able to work on it's own, so the AzureWebSample should have it's own copies of HelloWorld, and HelloWorld should have the references to the AzureWebSample removed.

**Comment by jthelin** [comment]
Those lines are part of the auto-magic stuff that NuGet Package Manager does, but quite often it does not seem to do the "right" thing, particularly when it updates package versions. :(

A PR to fix this would definitely be welcome.

**Comment by raybooysen** [comment]
Sure.  Does the suggestion that each sample has it's own copy of the code to prevent the cross references?  I.e. AzureWebSample has it's own HelloWorld code?

**Comment by sergeybykov** [comment]
I don't like the idea of *copying* the HelloWorld sample to AzureWebSample from the code duplication perspective. Wouldn't it be better to replace it within AzureWebSample with something as simple as HelloWorld but different? A method to return an environment variable or a perf counter by name instead of `SayHello()`?

**Comment by raybooysen** [comment]
Sounds good 






On Fri, Jun 12, 2015 at 9:56 AM -0700, "Sergey Bykov" <notifications@github.com> wrote:












I don't like the idea of copying the HelloWorld sample to AzureWebSample from the code duplication perspective. Wouldn't it be better to replace it within AzureWebSample with something as simple as HelloWorld but different? A method to return an environment variable or a perf counter by name instead of SayHello()?
