### ISSUE TITLE
Build a Azure Orleans offering just like the Azure SignalR offering

### ISSUE THREAD

**Issue by erikrenaud** [dotnet/orleans#5053]
Make it easy to deploy and enable connectivity from azure web apps

**Comment by sergeybykov** [comment]
@tuath Do you something similar to #4131?

**Comment by tuath** [comment]
Sounds very similar.. I think that #4131 is more about Grains can be mapped to a serverless front with a Orleans Host. 

My Ask is an easy way to deploy an Orleans based app where in "dev" i can UseLocalOrleans() and in production can UseAzureOrleans(). I do not want the complexity of hosting a ServiceFabric cluster to host Orleans. What I want is a Azure service that I can deploy into using a container or directly with my dotnetcore app,  choose how much ram and how many instances and bingo. For now the same kind of availability as Azure App Service, maybe in the future have Geo Replication...

Silo States should be managed by the service itself (no need to specify a storage plugin). 

The Silo should be useable from the internet (auth of some sort) or oonly within Azure as a backend.

I think this would require a memory based pressure system to release grains (but there is a PR for that).

**Comment by sergeybykov** [comment]
Thanks for the details. Sounds indeed like what we keep hearing from other Orleans users. I can't promise anything at this point, just can confirm that we are aware of this kind of asks.

**Comment by tuath** [comment]
I`m an ex MVP and very willing to test whatever comes out of this in a private fashion if ever i can help...
