### ISSUE TITLE
Log compact/aggregation not working after 2.x migration

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#5058]
Hello folks!

According to the [docs](http://dotnet.github.io/orleans/Documentation/clusters_and_clients/monitoring/silo_error_code_monitoring.html): 

> If multiple logs of the same log code occur within a designated time interval (the default is >5 within 1 minute) then additional log messages with that log code are suppressed and output as a "bulk" entry with log code equal to the original log code + 500000. So for example, multiple 100157 entries will show in the logs as 5 x 100157 + 1 x 600157 log entry per minute.

After migrating to 2.x and using the new logging infrastructure based on MEL, the logs aren't being aggregated anymore.

Can someone take a look why?

**Comment by galvesribeiro** [comment]
Ping

**Comment by ReubenBond** [comment]
FYI I believe this is not an Orleans issue per-se.

Documentation should be updated to remove mention of de-duplication.

This is necessarily a concern of logging or log consumers & outside the scope of Orleans.

**Comment by sergeybykov** [comment]
@JillHeaden Please update the doc page to remove the info about log bulking (deduplication).

**Comment by galvesribeiro** [comment]
Ok cool. Now at least we will know that should not happen anymore. Thanks!

**Comment by galvesribeiro** [comment]
Okey, looks like @JillHeaden fixed the docs. Closing the issue, thanks!
