### ISSUE TITLE
proposal: add issue template

### ISSUE THREAD

**Issue by patricksuo** [dotnet/orleans#5076]
e.g. 
1. https://github.com/golang/go/issues/new
2. https://github.com/golang/go/blob/master/.github/ISSUE_TEMPLATE

**Comment by ReubenBond** [comment]
Should we add an issue template?

Vote on the top comment:
👍 for yes
👎 for no

**Comment by MelnikovIG** [comment]
Voted down because it can scary new users and contributors

**Comment by sergeybykov** [comment]
A couple of obvious questions we often ask on new issues are Orleans version and environment (.NET Full/Core & OS). Would these questions put upfront still scare new users?

Clustering provider used would be also a valuable piece of information for us. But there I do see how it may be hard to answer for a newbie.

**Comment by sillyousu** [comment]
Can we log the valuable information while starting up?
So that new users can easily find out with minimal and clear instruction.

**Comment by ReubenBond** [comment]
It would be nice if the template was optional for the user - we could add a note saying it's optional at the top of the template.

> Voted down because it can scary new users and contributors

This is my primary concern

**Comment by sergeybykov** [comment]
>It would be nice if the template was optional for the user - we could add a note saying it's optional at the top of the template

I like this - the template could *suggest* to provide some core information, but wouldn't force them to fill it in.

**Comment by berdon** [comment]
I'm 👍 for an _optional_ template. A mandatory template leads to pedantically closing issues and cultivating an exclusionary culture. 🤷‍♂️

**Comment by sillyousu** [comment]
I agree it should be optional.

**Comment by ReubenBond** [comment]
It seems we can add a comment to markdown using this one weird trick:
`[//]: #(your comment goes here)`

**Comment by ReubenBond** [comment]
We don't have much signal for this and as a maintainer, I feel that the quality of most new issues is high enough that a template would be more of a detractor than a boon.
