### ISSUE TITLE
is it possible to prevent timers from starting?

### ISSUE THREAD

**Issue by talarari** [dotnet/orleans#5079]
We have a case where we shut all silos down at once and start them again.
this is mainly when we need to rollback to a previous version or perform an upgrade that is not possible as a rolling upgrade (like upgrading to orleans 2.0).

what we see is we have a lot of reminders ticking just as soon as some silos become available and therefore have a lot of stuff happening before we are ready for it.
this also causes most of the activations to go on the first silo that was ready, then we have to restart that one to rebalance the activations.

what do you suggest doing?

**Comment by sergeybykov** [comment]
What is driving most of the load on the cluster? Is it reminders or client requests?

**Comment by sergeybykov** [comment]
Sorry about delayed response.

I can't think of a way currently to prevent reminders from starting right away. We probably need to add something here. The options I see are:

- Configurable delay of starting the Reminder Service from silo start, with a default to, say, 5 minuets.
- Configurable delay but from the last cluster state change (to wait until other silos join the cluster).
- Configurable number or percentage of silos to join the cluster before starting the Reminder Service.
