### ISSUE TITLE
Orleans.Storage.InconsistentStateException after migrating to Orleans 2.1 (repro sample included)

### ISSUE THREAD

**Issue by MelnikovIG** [dotnet/orleans#5080]
I have an issue after updating to Orleans 2.1. I am using `MemoryGrainStorage` for my integrational tests, and tests started failing after update (maybe problem not in memory storage, but in new scheduler). I have created small project to reproduce this issue. I think this is trivial flow for grains and shouldn't throw any exceptions.
[Grains.zip](https://github.com/dotnet/orleans/files/2457102/Grains.zip)

**Comment by MelnikovIG** [comment]
@sergeybykov @benjaminpetit Any news with this issue? I think it is very critical issue.

**Comment by benjaminpetit** [comment]
I am able to repro it with `MemoryGrainStorage` and the Azure table provider, so it doesn't seems to be related to a particular provider.

When I downgrade to 2.0, I am not able to reproduce this.

Still investigating

**Comment by galvesribeiro** [comment]
Yeah, like I pointed on #5059 it _should_ happens on any provider...

**Comment by benjaminpetit** [comment]
@MelnikovIG @galvesribeiro found the regression, I will open a PR ASAP.

Thanks a lot @MelnikovIG for the easy repro, it was super helpful.

**Comment by sergeybykov** [comment]
Fixed via #5086.

**Comment by sergeybykov** [comment]
We published a nightly build with the fix to https://dotnet.myget.org/gallery/orleans-ci. 
@MelnikovIG @galvesribeiro Could you please confirm that it fixes the issue for you.

**Comment by MelnikovIG** [comment]
@sergeybykov I confirm that issue is fixed in nightly build. Btw, you can add my sample flow in Orleans integration tests to prevent this issue in future.

**Comment by sergeybykov** [comment]
@MelnikovIG @galvesribeiro Thank you both for validating the fix so quickly!
We'll publish 2.1.2 packages with the fix ASAP. Yes, we'll definitely add the repro as a regression test.
