### ISSUE TITLE
Will you join sagas in the later plan?

### ISSUE THREAD

**Issue by sundong1982** [dotnet/orleans#5091]
actor+sagas is very good.
ex:  https://github.com/apache/incubator-servicecomb-saga
https://github.com/OpenSagas-csharp/servicecomb-saga-csharp

**Comment by sergeybykov** [comment]
There's already https://github.com/creyke/Orleans.Sagas by @Creyke.

**Comment by creyke** [comment]
While I’m not actively maintaining Orleans.Sagas it should provide a good example of how easily sagas could be implemented in virtual actors. Sagas are pretty simple really when compared to something like transactions.

The reason I was dubious about proposing merging this into Orleans is it’s a very opinionated way of doing it, and I think there are many ways to implement sagas with virtual grains etc.

If you want to take it as a base or have any questions just shout on Gitter.

**Comment by creyke** [comment]
Sure it can be “donated” but it needs an active consumer to take it to production quality. In its current form it’s unproven.

**Comment by sergeybykov** [comment]
@creyke Up to you, of course. I think it's totally fine to put unproven projects to OrleansContrib (with a disclaimer). Somebody else might find it useful as a base to build on top of.

**Comment by creyke** [comment]
Done https://github.com/OrleansContrib/Orleans.Sagas

**Comment by sergeybykov** [comment]
Thank you!

**Comment by sergeybykov** [comment]
@sundong1982 Are you okay if we close this, now that @creyke added Orleans.Sagas to OrleansContrib?

**Comment by sundong1982** [comment]
@sergeybykov yeah,ok!
