### ISSUE TITLE
Java service as producer of Orleans stream events

### ISSUE THREAD

**Issue by ifle** [dotnet/orleans#5099]
I have question regarding producing stream events. We have java service the will store event to azure queue. Is it possible to integrate this events with Orleans streams?

**Comment by xiazen** [comment]
It depends on how the workflow is. It is totally possible. But I'd like to know more about how you plan to use streams in your case. 

Orleans stream has producing side and consuming side. For producing, we have user use grains(c#) to produce messages, which streaming infra would put those messages into queues.  And we also have user to produce messages to queues directly.I assume you are more going in the second route? 

When the java service produce events to azure, based on my understanding of azure queue, the actual message in azure queue can be a UTF-8 format string which isn't langauge spefic. In other words, you can produce using java sdk, and consume using c# sdk, is this correct? Or the java service produce bytes to azure queue, which can be landguege specific? 

Do you still plan to use orleans grains to consume, which is c#?

**Comment by ifle** [comment]
Java will produce messages directly to azure queue by using the azure java sdk. 
Orleans grains will be consumers.

Will be nice to have orleans sdk for java, nodejs that allows integrating with orleans silo, like azure signalr service that has sdk for java, nodejs or seamless integration with [Orbit](https://github.com/orbit/orbit)

**Comment by xiazen** [comment]
I believe we had some  integration with js, @sergeybykov will know more about this. 

For your case, I think a orleans java sdk is not needed, but you will need to implement a custom stream provider, more specificly a custom IQueueDataAdapter(interface may vary depends on which stream provider), since you are producing directly to the queues, instead of using grains as producer.

**Comment by xiazen** [comment]
close this due to inactive, feel free to reopen
