### ISSUE TITLE
Replace compile-time code generation of IGrainMethodInvoker

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#510]
This is a sub issue for #474 (Minimize/eliminate the usage of code generation in Orleans). Motivations for this are covered in that issue, so I won't reiterate.

@gabikliot mentioned some different techniques for eliminating the need for compile-time code generation of IGrainMethodInvoker including the possibility of using dynamic method invocation, reflection, or runtime code generation (eg, using Roslyn. See #40).

I believe that runtime code generation is the most optimal approach: it has the best amortized performance at runtime. Other options might be sufficient, though.

**Comment by gabikliot** [comment]
I think doing runtime code generation is a good solution, and not trying to dismiss it in any way.
But I do think that looking at potential alternatives is worthwhile as well. That way we can compare different solutions and pick the better one.

The case of `IGrainMethodInvoker` is actually much simpler that grain references (issue #511). In this case we do not need to return any object to application. What ever we do in this case is completely inside the runtime. A simple solution would be to do reflection based invoke. Upon first call to a grain method we will create a method info object (we already have all the interface and method type info inside the runtime) and cache it. Upon subsequent calls we will just do `.Invoke` on the cached method info. Presumably (I did not measure that), this will be not more expensive that just a direct method call via the generated invoker.

The advantage of this approach is that we are completely out of the business of code generation (static or dynamic) - much simper code, less maintenance cost, ...

**Comment by sergeybykov** [comment]
Resolved by https://github.com/dotnet/orleans/pull/528.
