### ISSUE TITLE
HelloWorld Tutorial/sample needs a correction

### ISSUE THREAD

**Issue by alkreddy** [dotnet/orleans#5115]
Hello,

The documentation of HelloWorld sample available at http://dotnet.github.io/orleans/Documentation/tutorials_and_samples/Hello-World.html needs a correction. The **Improve this Doc** link on the page is broken too

`.Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Loopback)
 .ConfigureLogging(logging => logging.AddConsole());`
needs to be corrected to 
`.Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Loopback)`
**_.ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(HelloGrain).Assembly).WithReferences())_**
  `.ConfigureLogging(logging => logging.AddConsole());`

With the missing statement related to adding the assembly that holds definition of the _Grains_, the documentation misses the point on how the _SiloHost_ picks the _grains_ to host

**Comment by xiazen** [comment]
thanks for reporting this. we are currently updating this sample in #5102 , I will let our doc writer know of this ! @JillHeaden

**Comment by xiazen** [comment]
close due to inactivity and also resolved by new HelloWorld sample.
