### ISSUE TITLE
gossip channels across Azure availability zones?

### ISSUE THREAD

**Issue by danvanderboom** [dotnet/orleans#5118]
What are the requirements for the gossip channel(s) to work correctly?

With Azure now having 3+ "Availability Zones" per region, is multi-cluster support needed for silos to span zones, or would these inter-zone hops be low enough latency to form a single cluster across zones within a single region?

Any thoughts on hierarchical partitioning/silo-affinity ("within zone, across zones, across regions", for example)? Is it done anywhere, or considered for Orleans? Or does existing multi-cluster support in Orleans already cover every conceivable scenario?

**Comment by sergeybykov** [comment]
This is an interesting question. I suspect, it might be worthwhile to try running a single cluster spanning multiple availability zones within a region. That would be simpler than setting up a multi-cluster. Presumably, network reliability and latency should be pretty close to a single datacenter case.
