### ISSUE TITLE
Orleans method call slower than Orleans streams

### ISSUE THREAD

**Issue by avinash0161** [dotnet/orleans#5119]
We have implemented a workflow execution system using Orleans 2.0.0. The workflow contains 4 operators  connected one after the other. Each operator (implemented as its own grain class), after it processes a tuple, passes it to the next operator. This 'passing' is implemented in two ways - 1) method calls to the downstream operator, 2) Streams between each consecutive operators and the downstream operators subscribe to the stream of their previous operator. We use SMSProvider for our streams.

In both implementations, the results from the last operator reach the Client using a stream (SMSProvider).

We ran tests using two input sizes - 1) 100,000 tuples and 2) 1 million tuples. Following are the time taken for the two implementations (averaged over multiple iterations):

```
                             Method Calls                               Orleans Streams
100,000 tuples                 20 s                                              6 s
1 million tuples          didn't finish after 15 min                        1 min 8 s
```

In the 1 million tuple method calls case, we saw that that we were getting a warning 

> Orleans.Runtime.CallbackData[100157]
>       Response did not arrive on time in 00:00:30 for message: Request *cli/65424186@696554ac->S127.0.0.1:30000:0*grn/B3410F44/0000000b#82: . Target History is: <S127.0.0.1:30000:0:*grn/B3410F44/0000000b:>. About to break its promise. 

In the Orleans dashboard, we see that the grains of operators after the first operator aren't even getting activated. However, we don't know how accurate the data shown by Orleans Dashboard is. We had a print statement to be shown when the second operator finished its processing. The print statement was never shown for 1 million `Method Call` case.

For all other cases, everything goes on fine. But we do see the slower performance of Method Calls as compared to streams.

The two implementations are in my Github repository under the branches [workflow_RPCs_with_ordering_v2](https://github.com/avinash0161/TexeraPrototypes/tree/workflow_RPCs_with_ordering_v2) and [workflow_streams_with_ordering](https://github.com/avinash0161/TexeraPrototypes/tree/workflow_streams_with_ordering).

**Comment by HermesNew** [comment]
May be related to your grainkey, if your grainkey is the same, such as 0, it will cause queue processing and reduce concurrent processing power.

**Comment by avinash0161** [comment]
@HermesNew I agree. We are not awaiting the calls (both in method and streams cases) and have implemented our own layer to ensure FIFO and exactly once delivery. So, it can be that requests get queued in grains. But, two questions: -

1. Why doesn't this affect stream implementation? The stream implementation is exactly similar to the `method call` in terms of architecture and grains. However, in both experiments that we did, it can be seen that streams perform better than method calls.

2. Is there a way to check the request queue length of grains so that we can slow down once it goes above a threshold? What should that threshold be?

**Comment by avinash0161** [comment]
Thanks for the explanation @HermesNew. However, I think I may have miscommunicated the architecture. The architecture is like below:

![image](https://user-images.githubusercontent.com/3867317/47337378-7e509600-d648-11e8-8694-beefb55f94c9.png)


The operators in the workflow are represented by grains (each operator has 10 grains) and we define their keys (or IDs) statically for both `method call` and `stream` implementations. The only difference between the stream and method call implementation is that the arrow represents next grain's method call in `method call` case, whereas each arrow represents unique streams between consecutive grains in `stream` case. We also statically designate the namespace and key of each stream to be the same as the type and ID of the next grain. Therefore, I don't think that Guid.New() is used anywhere.

**Comment by jason-bragg** [comment]
I could be misunderstanding the code, but I think you're simply flooding the cluster.  In the loop:

    for (int i = 0; i < TexeraConfig.num_scan; ++i)
    {
        operators[i].SubmitTuples();
    }

if TexeraConfig.num_scan is 1,000,000, then you're flooding the cluster with a burst of 1,000,000.  Depending on you're cluster size, this may be fine, but this sort of burst can overload a silo.  I suggest some sort of client throttling.  Maybe a configurable max number of in-flight messages per client.  For instance if you spin up TexeraConfig.num_scan_inflight submit calls, then await Task.WhenAny(..) on the set, spinning up new calls for any that were completed, this would keep num_scan_inflight operations in flight, avoiding overloading a cluster.

**Comment by avinash0161** [comment]
@jason-bragg `TexeraConfig.num_scan` is fixed to 10, which actually is the number of grains per operator. But you are correct otherwise. eg: In 1 million tuples case, operators[i].SubmitTuples() means that each of the 10 instances of Operator_1 submits 100,000 tuples (1 million/10) to the instances of Operator_2. I agree that this could be overloading the cluster and your solutions are well received (If there is any piece of code snippet that you can provide to elaborate on your solutions, it will be great).

However, my reason for raising this issue is why doesn't this overload happen when we use Orleans streams to pass the tuples? The number of grains is the same whether it be Streams implementation or method call implementation. And the better performance of streams is also visible when we use only 100,000 tuples total in input (20s for method calls Vs. 6s for streams). Why is streams faster than method calls?

**Comment by jason-bragg** [comment]
@avinash0161, ah, I see.  Thanks for clarification.  Streams should take longer than grain calls as they have more overhead.  One difference I see is that the logic to explicitly activate the grains in the RPC solution does not actually activate them.  Getting a grain reference does not activate the grain, so this logic:

    // Explicitly activating other grains
    client.GetGrain<IOrderedFilterOperator>(i+2);
    client.GetGrain<IOrderedKeywordSearchOperator>(i+2);
    client.GetGrain<IOrderedCountOperator>(i+2);
    client.GetGrain<IOrderedCountFinalOperator>(1);

doesn't really do anything.

In both cases the SubmitTuples spam messages by not awaiting the OnNextAsync/Process calls.  In general, this is not a good pattern as it can overload the system and not awaiting the calls allows for order to be lost under error conditions.  For the OnNextAsync/Process calls, I'd suggest batch calles rather than single event delivery.  For instance, a stream of List<object> rather than object or a Process call that takes a list of inputs rather than a single item, then calling (and awaiting) OnNextAsync/Process with a batch of 100 or 1000 messages would be much better performance and ensure ordered delivery.

**Comment by avinash0161** [comment]
@jason-bragg You are correct. When we saw that grains were not being activated in method calls scenario, we thought of explicitly activating them by the code marked above by you. But, as you said, the code didn't achieve that. I will comment it out to avoid any confusion. The suggestion to batch calls as stream of lists is good. We will try that.

But as you said, `Streams should take longer than grain calls as they have more overhead.`, and I concur. However, our readings, as shown above, suggest otherwise.So, the question still remains `how is streams performing better than method calls despite their overhead`

**Comment by jason-bragg** [comment]
As a general architectural note, when working with distributed systems (which is what Orleans was developed for), for performance reasons, minimizing the distribution cost of data is very important.  The processing time of a work item must justify the cost of distributing the work.  For instance if an item takes 10 ticks to process but takes 1ms to distribute the work, then you're losing performance by distributing the work.  However if you batch those into 10000 work items which also takes about 1ms to distribute, then distribution starts making more sense.

**Comment by jason-bragg** [comment]
"how is streams performing better than method calls despite their overhead"

Unclear, but we're not currently comparing apples to apples, as the stream test -does- pre-initialize the grains, and the rpc does not.  Rather than commenting out the section I noted, maybe add some sort of Load call onto the grains, so they can be activated before the events are pushed to them.  Then the two tests would be comparable.  If we still see streams performing better after that, then we can investigate further.

**Comment by jason-bragg** [comment]
One optimization I found in streaming that the RPC model does not have (though I'm not convinced it's significant to account for the entire difference), is that SMS, by default sends the data as immutable messages, which reduces some of the data copying involved.  To use immutable data in the RPC model the interface would look something like this:

    public interface INormalGrain : IGrainWithIntegerKey
    {
        Task Process(Immutable<object> row);
    }

**Comment by avinash0161** [comment]
@jason-bragg We have done the two changes that you suggested - added load to the grains and made tuple immutable. The changes have been pushed to the branch. And now indeed, the other operator's grains are getting activated. The observations are pointed out as follows: 
1. 1 million case (100,000 tuples each to 10 grains) still fails to complete for method call case. 
2. The downstream operators grains are getting activated now.
3. For 100,000 tuples case totally (i.e. 10,000 tuples each to 10 grains), the running time reduced to 9s.

The updated time taken by the two implementations is summarized below:

```
                             Method Calls                               Orleans Streams
100,000 tuples                 9 s                                              6 s
1 million tuples          didn't finish after 10 min                        1 min 8 s
```

We are still seeing that Streams is performing better.

**Comment by jason-bragg** [comment]
Found a config issue.. App configures MessagingOptions, which is an abstract base class and shouldn't be directly used.  To configure silo messaging options, SiloMessagingOptions should be used.

I can only speculate at this point..
I suspect that ordering is resulting in the difference in times.  I suggest tracking how many out of order messages (dropped or placed in stash) each impl is seeing.

As for the method calls not ever finishing in the 1 mill case, I suspect data loss due to timeouts.  You can increase the timeout by setting SiloMessaginOptions.ResponseTimeout.  Default is 30 second, so I'd suggest at least 1 minute for your senario.

**Comment by jason-bragg** [comment]
hmm.. looks like the ordering logic is off because filtering leaves hole such that the index counters in the grains don't line up with the incoming messages.

**Comment by ifle** [comment]
Is not the waiting of long running tasks is anti pattern in orleans?

**Comment by jason-bragg** [comment]
i'd not call It an anti-pattern, but yes, in general awaiting a long running task can have some undesirable side effects.  The pattern of calling grain, and awaiting them can create a call chain that is less responsive, is subject to timeouts, and may have long running tasks.  Assuming data loss during silo crashes is acceptable, which is the behavior of the processing pipe in the reference implementations long call chained processing pipes can be established by processing and caching the results in each grain, then sending those in ordered batches.  Something like:

        private Task sending = Task.CompletedTask;
        List<Tuple> next = new List<Tuple>();

        public async Task Process(Immutable<List<Tuple>> obj)
        {
            foreach (Tuple t in obj.Value)
            {
                Tuple result = await Process(t);
                if (result != null)
                {
                    this.next.Add(result);
                }
            };
            if(this.next.Count!=0 && this.sending.IsCompleted)
            {
                this.sending = SendNext();
                this.sending.Ignore();
            }
        }

        private async Task SendNext()
        {
            while(next.Count != 0)
            {
                await this.next_op.Process(this.next.Take(Program.batchSize).ToList().AsImmutable());
                this.next = this.next.Skip(Program.batchSize).ToList();
            }
        }

In the above code tuples are delivered in batches (of max size Program.batchSize) to be processed.  The grain process the tuples then sends there resulting batch to the next processor.  If the next batch has not been sent, the messages simply stay in the 'next' buffer until the send is complete and then it grabs the next batch.

Note: The use of linq's 'take' and 'skip' are not terribly performant, I was just being lazy, so this code can be optimized further.

**Comment by avinash0161** [comment]
@jason-bragg Greatly appreciate the suggestions and am trying them out. We didn't await the results because it was causing a chain of await through the operators, which essentially meant only one tuple was in the workflow till it got processed completely. Not having await, gives us operator parallelism and operators can process tuples independently.

We want this stream vs method call efficiency question to be resolved properly, because it will decide our further implementation decisions. Thanks again for the continuous help.

**Comment by jason-bragg** [comment]
Regarding the streams vs. method call efficiency question, method calls should be faster.  I don't know why streams are performing better in your scenario, but my suspicion is that it is related to how many out of order messages the application is processing.  I suspect streams, for some reason, have less out of order messages.  Also looking at the logic, the ordering logic is not resilient to data loss.  That is, if a message is lost, the ordering logic will prevent all future messages.  I suspect this as the reason for some test runs to not finish.

I suggest a pattern, using streams or method calls, which roughly follows my previous batch delivery post.  Using that pattern, you shouldn't need special logic to handle out of order messages.  You should probably still have ordering information in the messages (or better, per batch), to detect out of order messages or data loss, but it should be rare enough that you probably don't need special logic to handle it.

For initial prototyping and investigation, the single silo test is fine, but the performance characteristics, especially in relation to messaging, will be very different when running in a full cluster, as opposed to the single silo scenario your currently investigating.  When in a single silo, there is no network serialization cost involved in grain calls and grain placement is much faster as everything is placed locally.

**Comment by sergeybykov** [comment]
@avinash0161 
>We didn't await the results because it was causing a chain of await through the operators, which essentially meant only one tuple was in the workflow till it got processed completely.

If you mark grain classes as `[Reentrant]`, they would process other tuples while awaiting downstream calls. I +1 @jason-bragg's feedback that making non-awaited calls to grains is a dangerous anti-pattern. Slamming the cluster with 1M requests submitted within a short span of time isn't healthy. `AsyncPipleine` class is a useful backpressure helper that allows to easily control the number of in-flight requests, so that the cluster can be saturated at capacity without overloading it.

**Comment by avinash0161** [comment]
@sergeybykov You are right and this is something that Reuben had also suggested. However, this may lead to a situation where the messages arriving later to a grain are processed earlier and will lead to out-of-order message execution (but, we need FIFO). 

However, now that we have our own layer of FIFO and exactly once implementation, I wonder if `[Reentrant]` can be used to ensure message delivery, and our own layer to ensure FIFO. This may be something worth exploring.

Thanks for pointing out `AsyncPipeline` class. Is there some code snippet that illustrates its use?

**Comment by sergeybykov** [comment]
>However, this may lead to a situation where the messages arriving later to a grain are processed earlier and will lead to out-of-order message execution (but, we need FIFO).

The possibility of messaging arriving out of order is there for both reentrant and non-reentrant grains, unless the order is managed by the application logic. So FIFO and reentrancy are really orthogonal concerns to me.

However, reentrant calls may *interleave* at `await` statements in their respective methods, and that can easily lead to non-deterministic (unanticipated) order of execution of the remainders of those methods. That's the main reason we chose non-reentrant execution as the default.

**Comment by ifle** [comment]
@jason-bragg  @sergeybykov  Very interesting topic. 
I very like code sample of @jason-bragg . That prototype of the batch service that can works 24/7.
But can you please clarify how to prevent timeout exceptions\warning in case. of long waiting operations. 
Also interesting  to see code that call to process function and timeout configurations

**Comment by sergeybykov** [comment]
>But can you please clarify how to prevent timeout exceptions\warning in case. of long waiting operations.

I see these as two different although related concerns.

Timeouts are built into the Orleans programming model to protect the caller from waiting forever. During normal operation, timeouts should never happen, as the timeout time (30 seconds by default) should be significantly higher than the expected response time (usually under a second). To protest from occasional outlier IO calls taking longer than they should, you can use the `WithTimeout()` extension method to gain control back to the grain code.

Timeouts may also happen when the target grain is overloaded and cannot keep up with the growing queue of requests. That's usually an indicator of a design mistake. So timeout are just a symptom.

Synchronous execution that blocks a thread for tens or hundreds of milliseconds usually come from either 1) synchronous IO calls or 2) executing an expensive compute operation. 1) is much more likely to happen and is easy to fix by switching to asynchronous IO.

2) can be done in several different ways from what described in http://dotnet.github.io/orleans/Documentation/grains/external_tasks_and_grains.html to launching external processes.

If compute operations and even asynchronous IO calls take time comparable with the timeout, it is better not to model them as a single call to a grain, but to turn it into a pair of call: BeginOperation() and CheckOperationStatus(). That way the grain can launch a long running operation on the thread pool, as a separate process, etc., and still be responsive to CheckOperationStatus() calls.

**Comment by avinash0161** [comment]
Hi Guys. Sorry for not being responsive in the last few weeks. I just changed my `method call` code to use batching (each batch 1000 tuples) and the entire workflow ran in under a second. So, you guys were right in saying that my requests with 1 million tuples were overloading the grains. I still have to make changes so as to try and await the calls, but that isn't within the purview of this issue. 

However, this problem of overloading the grains isn't there in `streams` case, even though I am not using any batching there. Is it because streams are using some kind of backpressure to manage the requests rate?

**Comment by avinash0161** [comment]
@jason-bragg one last question, what is the purpose of  `this.sending.Ignore()` in the code snippet you provided. I couldn't find any such function under `Task`.
