### ISSUE TITLE
System.InvalidOperationException : No default ITransactionalStateStorageFactory nor IGrainStorage was found while attempting to create transactional state storage.

### ISSUE THREAD

**Issue by zhaoqinghai** [dotnet/orleans#5125]
var builder = new SiloHostBuilder()
                .Configure<ClusterOptions>(options =>
                {
                    options.ClusterId = "dev";
                    options.ServiceId = "fiiipay";
                })
                .UseLocalhostClustering()
                .Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Loopback)
                .ConfigureApplicationParts(parts =>
                {
                    parts.AddApplicationPart(typeof(HelloGrain).Assembly).WithReferences();
                })
                .AddAdoNetGrainStorage("store0",configureOptions =>
                {
                    configureOptions.ConnectionString =
                        "Data Source=.;Database=FiiiPay.Account;Integrated Security=True;Pooling=False;Max Pool Size=200;";
                    configureOptions.Invariant = "System.Data.SqlClient";
                })
                .AddAdoNetGrainStorage("store1",configureOptions =>
                {
                    configureOptions.ConnectionString =
                        "Data Source=.;Database=Test;Integrated Security=True;Pooling=False;Max Pool Size=200;";
                    configureOptions.Invariant = "System.Data.SqlClient";
                })
                .UseTransactions(); 
this is my host code

**Comment by sergeybykov** [comment]
For `.UseTransactions()` to work, you need to add a transactional state provider - one that implements `ITransactionalStateStorage<TState>`. `AddAdoNetGrainStorage` doesn't do that. We currently have a provider for Azure Table that you can add with `AddAzureTableTransactionalStateStorage()`. Alternatively, you can create and add your own provider.

**Comment by jason-bragg** [comment]
The transactional state storage will fallback to a configured grain state storage if no TransactionalStateStorage is found and a grain state store of the same name is found.  Your configuration does seem to have two grain state storages, "store0" and "store1", so if either of those are referenced in the transaction facet attribution, it should use them.  The fact that the error message mentions no 'default' indicates that the attribution has no storage specified so it looks for a store called 'default'.  If you want to keep the attribution the way it is, you can also add a grain state store named 'default', which will be used.

**Comment by jason-bragg** [comment]
As a side note about the 'fallback' behavior, the usage patterns needed by transactional storage differ from those needed by grain storage, that's why we have a different abstraction.  While we've bridged the two to allow transactions to be used with any grains state storage, storage specific implementations of ITransactionalStateStore will likely perform better than a bridged grain state storage.

**Comment by zhaoqinghai** [comment]
thank you, i want to use muti database by sqlserver, how i configure my silohostbuilder? i worry one database it will slow performance when data item arrive so much
