### ISSUE TITLE
Update https://dotnet.github.io/orleans/Documentation/grains/index.html

### ISSUE THREAD

**Issue by dzmitry-lahoda** [dotnet/orleans#5127]
1. Update `Asynchronous Programming with Async and Await` link from https://msdn.microsoft.com/en-us/library/hh191443.aspx into up to date https://docs.microsoft.com/en-us/dotnet/csharp/async

2. Document possibility to use ValueTask #4562.

3. Document possibility of grain to have 2 interfaces and one implementation ( I tested in single Silo and seems #1511 kind of works)

```
namespace UserNotification.Host
{
    public class MatchMakingGrain : Grain,
    IGameGrain, IPlayerDisconnect
    { 
        // ...
    }

var grainClassNamePrefix= "UserNotification.Host.MatchMakingGrain";
var sameActivationDifferentFace1 = this.GrainFactory.GetGrain<IGameGrain>("13", grainClassNamePrefix);
var sameActivationDifferentFace1  = this.GrainFactory.GetGrain<IPlayerDisconnect>("13", grainClassNamePrefix);

```

**Comment by sergeybykov** [comment]
Resolved via #5135.
