### ISSUE TITLE
Exc level 0: System.InvalidOperationException: Compilation has no syntax trees

### ISSUE THREAD

**Issue by leoterry-ulrica** [dotnet/orleans#5128]
why? 
1>------ 已启动生成: 项目: Dist.Dme.Orleans.Interfaces, 配置: Debug x86 ------
1>Orleans.CodeGenerator - command-line = SourceToSource D:\aws-gitlab\dme\Dist.XData.Dme\Dist.Dme.Orleans.Interfaces\obj\x86\Debug\netstandard2.0\Dist.Dme.Orleans.Interfaces.orleans.g.args.txt
1>-- Code Generation FAILED --
1>
1>Exc level 0: System.InvalidOperationException: Compilation has no syntax trees.
1>   at Orleans.CodeGenerator.CodeGenerator..ctor(Compilation compilation, ILogger log) in D:\build\agent\_work\24\s\src\Orleans.CodeGenerator\CodeGenerator.cs:line 37
1>   at Orleans.CodeGenerator.MSBuild.CodeGeneratorCommand.Execute(CancellationToken cancellationToken) in D:\build\agent\_work\24\s\src\Orleans.CodeGenerator.MSBuild\CodeGeneratorCommand.cs:line 129
1>   at Microsoft.Orleans.CodeGenerator.MSBuild.Program.SourceToSource(String[] args) in D:\build\agent\_work\24\s\src\Orleans.CodeGenerator.MSBuild\Program.cs:line 126
1>   at Microsoft.Orleans.CodeGenerator.MSBuild.Program.Main(String[] args) in D:\build\agent\_work\24\s\src\Orleans.CodeGenerator.MSBuild\Program.cs:line 16
1>C:\Users\thinkpad\.nuget\packages\microsoft.orleans.codegenerator.msbuild\2.1.2\build\Microsoft.Orleans.CodeGenerator.MSBuild.targets(122,5): error MSB3073: 命令“"dotnet" "C:\Users\thinkpad\.nuget\packages\microsoft.orleans.codegenerator.msbuild\2.1.2\build\..\tasks\netcoreapp2.0\Orleans.CodeGenerator.MSBuild.dll" SourceToSource "D:\aws-gitlab\dme\Dist.XData.Dme\Dist.Dme.Orleans.Interfaces\obj\x86\Debug\netstandard2.0\Dist.Dme.Orleans.Interfaces.orleans.g.args.txt"”已退出，代码为 3。
1>已完成生成项目“Dist.Dme.Orleans.Interfaces.csproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

**Comment by ReubenBond** [comment]
Please share your csproj file.

Does your project have any source code?

**Comment by leoterry-ulrica** [comment]
Sorry, it's not happening now.

**Comment by sergeybykov** [comment]
@leoterry-ulrica So this issue can be closed?

**Comment by GhostSource** [comment]
What solved this issue? I'm currently having the exact same problem
