### ISSUE TITLE
Using Microsoft.Orleans.ProtobufNet

### ISSUE THREAD

**Issue by Dewaldf** [dotnet/orleans#5136]
I have a question about the ProtobufNet serializer in orleans. I have tried to implement it, but I could not find allot of documentation around using this within Orleans. I just want to make sure that what I have done, is what is required to use this serializer. 

I am currently using Orleans 2.1, and from [this issue](https://github.com/dotnet/orleans/issues/4305) it looks like it is as simple as the steps below. 

1. I have installed **Microsoft.Orleans.ProtobufNet** package into both my Silo and client projects.
2. Added the following to the Silo and Client configuration
```
builder.Configure<SerializationProviderOptions>(opt =>
{
    opt.SerializationProviders.Add(typeof(ProtobufNetSerializer).GetTypeInfo());
});
```
3. Added the following attributes to my response object from grain
```
[ProtoContract]
public class Person
{
     [ProtoMember(1)]
     public string Name { get; set; }

     [ProtoMember(2)]
     public string Surname { get; set; }
}
```

Is this all that is needed to use the ProtobufNet serializer ? Or Am I missing something.

**Comment by sergeybykov** [comment]
This looks correct to me.

**Comment by Dewaldf** [comment]
Thanks. A follow up question, have you guys done performance benchmarks between this and the default serializer ? I did this implementation expecting faster times but it was a bit slower than the default serializer. The expectation for faster results is purely because of the hype around protobuff

**Comment by sergeybykov** [comment]
I don't remember if we ever compared the performance, but I doubt it would be faster than the default serializer. The need for the ProtoBuf serializer stems primarily from when you already use ProtoBuf for sending or storing your data and don't want to waste cycles on reserializing it.

**Comment by Dewaldf** [comment]
We have seen that we are getting slower response times using Protobuf, thanks for the replies.
