### ISSUE TITLE
Exception of type 'zookeeper.KeeperException+NoNodeException' was thrown in Orleans client

### ISSUE THREAD

**Issue by handlespeed** [dotnet/orleans#5137]
We use Orleans 2.0 to build orleans cluster by docker deployment: the docker containers contains: 3 silos containers, 1 client container, 3 zookeeper containers (used as membership table). There are 3 VMs to host containers. We ensure 3 silos are in separate vms(1,2,3), 3 zookeepers are in separate vms(1,2,3), 1 client is in vm1. 
Most time this cluster works well, but sometimes (about one per week) client throws exception as follows:

> org.apache.zookeeper.KeeperException+NoNodeException: Exception of type 'org.apache.zookeeper.KeeperException+NoNodeException' was thrown. at org.apache.zookeeper.ZooKeeper.getDataAsync(String path, Watcher watcher) at Orleans.Runtime.Membership.ZooKeeperBasedMembershipTable.GetRow(ZooKeeper zk, SiloAddress siloAddress) at Orleans.Runtime.Membership.ZooKeeperBasedMembershipTable.<>c.<<ReadAll>b__11_0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at org.apache.zookeeper.ZooKeeper.TryOperation[T](ZooKeeper zk, Func`2 zkMethod) at org.apache.zookeeper.ZooKeeper.<>c__DisplayClass62_0`1.<<Using>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at org.apache.zookeeper.ZooKeeper.Using[T](ZooKeeper zk, Func`2 zkMethod) at Orleans.Runtime.Membership.ZooKeeperClusteringClientOptions.GetGateways() at Orleans.Messaging.GatewayManager.RefreshSnapshotLiveGateways_TimerCallback(Object context)

We doubt if there is any dirty data in zookeeper node so that exception thrown when trying to retrieve active gateway list from zk, but membership table are fully maintained by Orleans runtime (package 'Microsoft.Orleans.OrleansZooKeeperUtils' used is version 2.0.0). Could you please give some information what happened? Thanks!

**Comment by sergeybykov** [comment]
>org.apache.zookeeper.KeeperException+NoNodeException: Exception of type 'org.apache.zookeeper.KeeperException+NoNodeException' was thrown. at org.apache.zookeeper.ZooKeeper.getDataAsync(String path, Watcher watcher) 

This tells me that the it's likely a ZooKeeper issue. Is it transient?

Orleans Client is just failing to refresh the list of available gateways. It shouldn't interrupt its work - it should continue to use the gateways it is already aware of, unless it has none.

**Comment by handlespeed** [comment]
Thanks for reply!
It is not transient. After exception happened, it will keep until we restart orleans client.You are right that when exception happens, the client will still connect to previous gateways, but what if those gateway are updated (restarted)? It may generate new gateway with new ip or epoch so that client will not find and connect to new gateways by that time.

发送自我的三星 Galaxy 智能手机。
-------- 原始信息 --------由： Sergey Bykov <notifications@github.com> 日期: 18/10/27  00:01  (GMT+08:00) 收件人： dotnet/orleans <orleans@noreply.github.com> 抄送： handlespeed <handlespeed@163.com>, Author <author@noreply.github.com> 主题： Re: [dotnet/orleans] Exception of type
  'zookeeper.KeeperException+NoNodeException' was thrown in Orleans client
  (#5137) 

org.apache.zookeeper.KeeperException+NoNodeException: Exception of type 'org.apache.zookeeper.KeeperException+NoNodeException' was thrown. at org.apache.zookeeper.ZooKeeper.getDataAsync(String path, Watcher watcher)

This tells me that the it's likely a ZooKeeper issue. Is it transient?
Orleans Client is just failing to refresh the list of available gateways. It shouldn't interrupt its work - it should continue to use the gateways it is already aware of, unless it has none.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dotnet/orleans","title":"dotnet/orleans","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/dotnet/orleans"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sergeybykov in #5137: \u003eorg.apache.zookeeper.KeeperException+NoNodeException: Exception of type 'org.apache.zookeeper.KeeperException+NoNodeException' was thrown. at org.apache.zookeeper.ZooKeeper.getDataAsync(String path, Watcher watcher) \r\n\r\nThis tells me that the it's likely a ZooKeeper issue. Is it transient?\r\n\r\nOrleans Client is just failing to refresh the list of available gateways. It shouldn't interrupt its work - it should continue to use the gateways it is already aware of, unless it has none."}],"action":{"name":"View Issue","url":"https://github.com/dotnet/orleans/issues/5137#issuecomment-433457883"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dotnet/orleans/issues/5137#issuecomment-433457883",
"url": "https://github.com/dotnet/orleans/issues/5137#issuecomment-433457883",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [dotnet/orleans] Exception of type 'zookeeper.KeeperException+NoNodeException' was thrown in Orleans client (#5137)",
"sections": [
{
"text": "",
"activityTitle": "**Sergey Bykov**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@sergeybykov",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"dotnet/orleans\",\n\"issueId\": 5137,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"dotnet/orleans\",\n\"issueId\": 5137\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/dotnet/orleans/issues/5137#issuecomment-433457883"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 401565129\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by handlespeed** [comment]
Hi all, any suggestion on that? 

This client side exception is being kept and if I just restart client docker container, the exception will be gone, so I do not think it is because of zookeeper issue, please correct me if I am wrong. 

The actual impact is what if issue happens and keeps there and after sometime we need to update grain code so that silo docker container are updated? The client will not be able to connect gateways by that time because ip of gateways is changed.

Thanks for every comment and suggestion :)

**Comment by sergeybykov** [comment]
It seems to me that the issue is either in the ZooKeeper library or in `ZooKeeperBasedMembershipTable`. Can you debug it to see what is passed to `org.apache.zookeeper.ZooKeeper.getDataAsync(String path, Watcher watcher)` when it's in that state? If the input is legitimate, then I would suspect the library. If not, I'd look into why.

**Comment by handlespeed** [comment]
Thanks, I will try to add log for that and monitor it later.

Because this issue is not always happened, so the way to find input of 'getDataAsync' is to add log code into related Orleans code and build that dll, then replace it into our output folder in our Orleans client Docker container. 

Is that right way or is there better way? Thanks.

**Comment by sergeybykov** [comment]
Yes, you can instrument the ZooKeeper clustering provider, build a private version of it, and deploy to reproduce the issue and capture the data.

**Comment by sergeybykov** [comment]
@handlespeed Any update?

**Comment by handlespeed** [comment]
@sergeybykov Sorry I have no time to check this issue recently because of another higher priority work of my team. I will do that in short future.

**Comment by sergeybykov** [comment]
No worries. If I close this issue, you won't able to reopen it. Unfortunately, that's how GitHub works as we learned. But if *you* do that, you'll be able to reopen it later when you get new information.

**Comment by handlespeed** [comment]
Close it and will reopen when I get time to monitor issue, thanks for help @sergeybykov

**Comment by handlespeed** [comment]
@sergeybykov  I have add some detailed log into Cluster.Zookeeper assembly and found following info when the issue happened again. Seems it was trying to get data of one zk node '10.42.152.178:**30000**@280057970' which was not existing in my zookeeper nodes list. I configured default 2 ports for silo and gateway when start silo. '10.42.152.178' is an active silo and its zk node actually is 10.42.152.178:**11111**@280057970

**Zookeeper node list:**
[zk: localhost:2181(CONNECTED) 3] ls /data-aggregation
[10.42.232.9:11111@278234608, 10.42.93.8:11111@278741469, **10.42.152.178:11111@280057970**, 10.42.198.235:11111@279700613, 10.42.198.140:11111@278741476, 10.42.23.47:11111@277340282, 10.42.28.92:11111@278245488, 10.42.138.53:11111@279700061, 10.42.37.242:11111@277263312, 10.42.113.142:11111@278245448, 10.42.212.247:11111@277340277, 10.42.227.211:11111@277977174, 10.42.56.117:11111@278234604, 10.42.198.235:11111@279700640, 10.42.241.18:11111@277263345, 10.42.14.56:11111@279700544, 10.42.34.137:11111@280057893, 10.42.242.162:11111@278234566, 10.42.106.53:11111@279699990, 10.42.51.224:11111@277340246, 10.42.236.55:11111@279700055, 10.42.237.38:11111@278245497, 10.42.187.205:11111@277263334, 10.42.103.218:11111@277977218, 10.42.223.173:11111@278741419, 10.42.161.154:11111@277977210, 10.42.48.64:11111@279700602, 10.42.206.170:11111@280057954]

**Logs with detailed node info I added**:
`11/19/2018 11:21:37 AM[03:21:37 INF] Category:Orleans.Runtime.Membership.ZooKeeperClusteringClientOptions|zk.getDataAsync(rowPath), rowPath:/10.42.232.9:11111@278234608, rowIAmAlivePath:/10.42.232.9:11111@278234608/IAmAlive
11/19/2018 11:21:37 AM[03:21:37 INF] Category:Orleans.Runtime.Membership.ZooKeeperClusteringClientOptions|zk.getDataAsync(rowIAmAlivePath), rowPath:/10.42.232.9:11111@278234608, rowIAmAlivePath:/10.42.232.9:11111@278234608/IAmAlive
11/19/2018 11:21:37 AM[03:21:37 INF] Category:Orleans.Runtime.Membership.ZooKeeperClusteringClientOptions|zk.getDataAsync(rowPath), rowPath:/10.42.93.8:11111@278741469, rowIAmAlivePath:/10.42.93.8:11111@278741469/IAmAlive
11/19/2018 11:21:37 AM[03:21:37 INF] Category:Orleans.Runtime.Membership.ZooKeeperClusteringClientOptions|zk.getDataAsync(rowIAmAlivePath), rowPath:/10.42.93.8:11111@278741469, rowIAmAlivePath:/10.42.93.8:11111@278741469/IAmAlive
11/19/2018 11:21:37 AM[03:21:37 INF] Category:Orleans.Runtime.Membership.ZooKeeperClusteringClientOptions|zk.getDataAsync(rowPath), rowPath:/10.42.152.178:30000@280057970, rowIAmAlivePath:/10.42.152.178:30000@280057970/IAmAlive
11/19/2018 11:21:37 AM[03:21:37 INF] Category:Orleans.Runtime.Membership.ZooKeeperClusteringClientOptions|zk.getDataAsync(rowIAmAlivePath), rowPath:/10.42.152.178:30000@280057970, rowIAmAlivePath:/10.42.152.178:30000@280057970/IAmAlive
11/19/2018 11:21:37 AM[03:21:37 INF] Category:Orleans.Runtime.Membership.ZooKeeperClusteringClientOptions|zk.getDataAsync(rowPath), rowPath:/10.42.198.235:11111@279700613, rowIAmAlivePath:/10.42.198.235:11111@279700613/IAmAlive
11/19/2018 11:21:37 AM[03:21:37 INF] Category:Orleans.Runtime.Membership.ZooKeeperClusteringClientOptions|zk.getDataAsync(rowIAmAlivePath), rowPath:/10.42.198.235:11111@279700613, rowIAmAlivePath:/10.42.198.235:11111@279700613/IAmAlive
11/19/2018 11:21:37 AM[03:21:37 INF] Category:Orleans.Runtime.Membership.ZooKeeperClusteringClientOptions|zk.getDataAsync(rowPath), rowPath:/10.42.198.140:11111@278741476, rowIAmAlivePath:/10.42.198.140:11111@278741476/IAmAlive
11/19/2018 11:21:37 AM[03:21:37 INF] Category:Orleans.Runtime.Membership.ZooKeeperClusteringClientOptions|zk.getDataAsync(rowIAmAlivePath), rowPath:/10.42.198.140:11111@278741476, rowIAmAlivePath:/10.42.198.140:11111@278741476/IAmAlive
11/19/2018 11:21:37 AM[03:21:37 INF] Category:Orleans.Runtime.Membership.ZooKeeperClusteringClientOptions|zk.getDataAsync(rowPath), rowPath:/10.42.23.47:11111@277340282, rowIAmAlivePath:/10.42.23.47:11111@277340282/IAmAlive
11/19/2018 11:21:37 AM[03:21:37 INF] Category:Orleans.Runtime.Membership.ZooKeeperClusteringClientOptions|zk.getDataAsync(rowIAmAlivePath), rowPath:/10.42.23.47:11111@277340282, rowIAmAlivePath:/10.42.23.47:11111@277340282/IAmAlive
11/19/2018 11:21:37 AM[03:21:37 INF] Category:Orleans.Runtime.Membership.ZooKeeperClusteringClientOptions|zk.getDataAsync(rowPath), rowPath:/10.42.28.92:11111@278245488, rowIAmAlivePath:/10.42.28.92:11111@278245488/IAmAlive
11/19/2018 11:21:37 AM[03:21:37 INF] Category:Orleans.Runtime.Membership.ZooKeeperClusteringClientOptions|zk.getDataAsync(rowIAmAlivePath), rowPath:/10.42.28.92:11111@278245488, rowIAmAlivePath:/10.42.28.92:11111@278245488/IAmAlive
11/19/2018 11:21:37 AM[03:21:37 INF] Category:Orleans.Runtime.Membership.ZooKeeperClusteringClientOptions|zk.getDataAsync(rowPath), rowPath:/10.42.138.53:11111@279700061, rowIAmAlivePath:/10.42.138.53:11111@279700061/IAmAlive
11/19/2018 11:21:37 AM[03:21:37 INF] Category:Orleans.Runtime.Membership.ZooKeeperClusteringClientOptions|zk.getDataAsync(rowIAmAlivePath), rowPath:/10.42.138.53:11111@279700061, rowIAmAlivePath:/10.42.138.53:11111@279700061/IAmAlive
11/19/2018 11:21:37 AM[03:21:37 INF] Category:Orleans.Runtime.Membership.ZooKeeperClusteringClientOptions|**Exception found in GetRow()!!!, rowPath:/10.42.152.178:30000@280057970, rowIAmAlivePath:/10.42.152.178:30000@280057970/IAmAlive**, exception:org.apache.zookeeper.KeeperException+NoNodeException: Exception of type 'org.apache.zookeeper.KeeperException+NoNodeException' was thrown.
11/19/2018 11:21:37 AM   at org.apache.zookeeper.ZooKeeper.getDataAsync(String path, Watcher watcher)
11/19/2018 11:21:37 AM   at Orleans.Runtime.Membership.ZooKeeperBasedMembershipTable.GetRow(ZooKeeper zk, SiloAddress siloAddress, ILogger logger)`

**Comment by handlespeed** [comment]
Any update for detailed info above? :) (Client tried to get data of one non-existing zk node (with port **30000**) when refreshed gateways)

**Comment by handlespeed** [comment]
Is there anyone can help on this issue? We need suggestion to establish further work for it, thanks a lot :)

**Comment by sergeybykov** [comment]
I wonder if you are hitting #5025 that was fixed by #5054. Can you try the fix included in [2.2.0-beta1](https://github.com/dotnet/orleans/releases/tag/v2.2.0-beta1)?

**Comment by handlespeed** [comment]
Thanks @sergeybykov , I will try version 2.2.0-beta1 to run around 1~2 week and get back again.

**Comment by handlespeed** [comment]
@sergeybykov We have run service with Orleans version 2.2.0-beta1 for around 1 week and the previous issue cannot occur, I think I can close it now, thanks for great help!
