### ISSUE TITLE
Does Orleans fit my case?

### ISSUE THREAD

**Issue by quicoli** [dotnet/orleans#5138]
Hello friends,

sorry for posting a question here. I'd like to ask for some suggestions for my scenario and check if Orleans is a good fit for it. 
I have a bunch (about 30000-70000) of processing to perform and would like to split this among 5 high spec computers we have (16 processors, 32GB RAM and SSD each).  The processing consists of creating a small input text file and send it to a 3rd party app that process it and return a string as result. This 3rd party app can eat some CPU, sometimes it can take 1-3 seconds to process the input.
So the idea would be to create a Job list, dispatch this and get the result as its happens. 

Do you thing Orleans is a good pick for this or would you recommend something else?

Thank you

**Comment by sergeybykov** [comment]
Not need to apologize. This is a 100% appropriate question to ask.

I think Orleans is *a* way to build the system you described. It would help you easily run processing on those 5 nodes, especially if at some point you'll need to coordinate processing of different jobs.

At the same time, there are other ways to divide processing of a batch of jobs, statically or dynamically, among 5 nodes. So it is hard to tell if Orleans is a better approach here without knowing more detailed requirements and having an idea how they might evolve in the future. But I don't see anything wrong with using Orleans here based on the information you provided.

**Comment by quicoli** [comment]
Thank you very much @sergeybykov  👍
