### ISSUE TITLE
multi silos，how can i configure my client

### ISSUE THREAD

**Issue by leoterry-ulrica** [dotnet/orleans#5141]
silo1=>port : 11111, gatewayport: 30000
silo2=>port : 11112, gatewayport: 30001( can i use the same gateway port?)
my silos/clients running on the same host.

_Originally posted by @leoterry-ulrica in https://github.com/dotnet/orleans/issues/4384#issuecomment-433624135_

**Comment by leoterry-ulrica** [comment]
@ReubenBond do u have any solutions? thx

**Comment by benjaminpetit** [comment]
@leoterry-ulrica something like clientBuilder.UseLocalhostClustering(new[] { 30000, 30001 }) should work if your silo and clients live on the same machine

And no, you cannot use the same gw port

**Comment by leoterry-ulrica** [comment]
> @leoterry-ulrica something like clientBuilder.UseLocalhostClustering(new[] { 30000, 30001 }) should work if your silo and clients live on the same machine
> 
> And no, you cannot use the same gw port

I don't think it's a good idea.Because two gateway ports are configured, the two silos are responsible for different businesses, and sometimes the exact service cannot be invoked.

**Comment by benjaminpetit** [comment]
I don't think I understand what you mean?

If you are running two silos with gateway enabled on the same host, they should use different port.
