### ISSUE TITLE
Unexpected token 'Error' introducing type specifier when calling grain method. 

### ISSUE THREAD

**Issue by darthkurak** [dotnet/orleans#5147]
Hi! Im getting
"Unexpected token 'Error' introducing type specifier " every time when i call method Recieve on my grain  which have following signature:

```
Task Recieve(IEnumerable<GrainsInterfaces.EventData> messages)

public class EventData
    {
        public ArraySegment<byte> Body { get; set; }

        public IDictionary<string, object> Properties { get; set; }

        public SystemPropertiesCollection SystemProperties { get; set; }

        public sealed class SystemPropertiesCollection : Dictionary<string, object>
        {
            public long SequenceNumber { get; set; }

            public DateTime EnqueuedTimeUtc { get; set; }

            public string Offset { get; set; }

            public string PartitionKey { get; set; }
        }
    }
```

Grain has  [StatelessWorker] and [Reentrant] attributes.

Other method, which has simplier signature:

 Task<string> SayHello(string greetings) works ok.

Do you know what can cause this? Is there any limitation if comes to data contract?

**Comment by sergeybykov** [comment]
`IEnumerable<T>` is not supported as an argument or return type because it is evaluated lazily. Try using `IList<T>` or something like that instead.

**Comment by darthkurak** [comment]
Works now, thanks!
