### ISSUE TITLE
[DebuggerStepThrough] for Orleans codegen methods

### ISSUE THREAD

**Issue by bboyle1234** [dotnet/orleans#5150]
Is it possible to make orleans code gen add the `[DebuggerStepThrough]` attribute to the generated code? 
If so, could instructions for it please be added to Orleans documentation?

**Comment by tim-fay** [comment]
Hi, @ReubenBond any plans to add this support?
I wonder if this option can be made configurable...

**Comment by ReubenBond** [comment]
@tim-fay yes, we can make this configurable using csproj settings. I don't have immediate plans to add support for this (it could be a good "up for grabs" issue, I can help). Hopefully I'll eventually get to it. I'll put it on the backlog for now.

**Comment by ReubenBond** [comment]
Hi folks, I realize we implemented this some time back: https://github.com/dotnet/orleans/pull/6017

I'll close this for now, but please let us know if that does not solve the issue by opening a new issue (to make sure we see it)

**Comment by tim-fay** [comment]
Thanks for noticing and for doing all this @ReubenBond, much appreciate it!
