### ISSUE TITLE
The request return type cannot be converted

### ISSUE THREAD

**Issue by 2821840032** [dotnet/orleans#5151]
Host Fail:
fail: Orleans . Runtime .Messaging.IncomingMessageAcceptor[101027]ProcessReceivedBuffer exception with RemoteEndPoint 127.0.0.1:6772:System.TypeAccessExceptign: Named type "Entity.Bill" is invalid: Type string "EnBill cannat be resolved

Error returned by silo request
The class returned by silo does not seem to be converted
But
The silo processed by the host was successfully returned
Is something wrong with me
Thank you for your answers

**Comment by 2821840032** [comment]
String is ok

**Comment by sergeybykov** [comment]
Is this on the client? Is the assembly where Entity.Bill is defined deployed there?

**Comment by 2821840032** [comment]
> Is this on the client? Is the assembly where Entity.Bill is defined deployed there?
Thank you for reply
The error location is in host
Entity.bill is a class passed by the client
Seems like a problem with serialization
I read the documentation yesterday and configured the serialization, but I still have this problem
Code:

Host configuration
```
var builder = new SiloHostBuilder()
                  .Configure<SerializationProviderOptions>(d => { d.SerializationProviders.Add(typeof(BondSerializer).GetTypeInfo()); d.FallbackSerializationProvider = typeof(BondSerializer).GetTypeInfo(); })

```
Entity.Bill
```
namespace Entity
{
    [DataContract]
    [Serializable]
    [ProtoContract]
    public class Bill
    {
        [DataMember]
        [ProtoMember(1)]
        public int ID { get; set; }

        [DataMember]
        [ProtoMember(2)]
        public int GoodsID { get; set; }
    }
}

```
Use
```
commodityInformation = cluster.GetGrain<IBillInformation>(0);
            var result = commodityInformation.GetGoodByID(1);
```
```
  Task<Bill> IBillInformation.GetGoodByID(int ID)
        {
            return Task.FromResult(GoodsTable.Where(d => d.ID == ID).FirstOrDefault());
        }
```
I feel there is something wrong with my configuration. Could you tell me how to use BondSerializer or ProtobufSerializer?
Thank you again for

**Comment by 2821840032** [comment]
Thanks for your reply. I found the problem
Is my entity class does not install Microsoft. The part that goes from the OrleansCodeGenerator. Build
I installed it and it worked
I don't see a description of this in the documentation
source

> https://github.com/dotnet/orleans/issues/4795
