### ISSUE TITLE
Microsoft.Orleans.OrleansCodeGenerator.Build and Microsoft.Orleans.CodeGenerator.MSBuild

### ISSUE THREAD

**Issue by leoterry-ulrica** [dotnet/orleans#5152]
Which one should I use?
What's the difference?

thx

**Comment by sillyousu** [comment]
use Microsoft.Orleans.CodeGenerator.MSBuild

**Comment by leoterry-ulrica** [comment]
> use Microsoft.Orleans.CodeGenerator.MSBuild

why

**Comment by leoterry-ulrica** [comment]
@ReubenBond What's the reason, please

**Comment by 2821840032** [comment]
I am using
Microsoft.Orleans.OrleansCodeGenerator.Build

你能告诉我orleans的序列化怎么弄吗？
看你的截图似乎解决了这个问题

文档地址
http://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/serialization.html#fallback-serialization)

我的配置

    var builder = new SiloHostBuilder()
                .Configure<SerializationProviderOptions>(d => { d.SerializationProviders.Add(typeof(ProtobufSerializer).GetTypeInfo());d.FallbackSerializationProvider = typeof(ProtobufSerializer).GetTypeInfo(); })

我这样做了
但是并没有什么用

**Comment by leoterry-ulrica** [comment]
> I am using
> Microsoft.Orleans.OrleansCodeGenerator.Build
> 
> 你能告诉我orleans的序列化怎么弄吗？
> 看你的截图似乎解决了这个问题
> 
> 文档地址
> http://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/serialization.html#fallback-serialization)
> 
> 我的配置
> 
> ```
> var builder = new SiloHostBuilder()
>             .Configure<SerializationProviderOptions>(d => { d.SerializationProviders.Add(typeof(ProtobufSerializer).GetTypeInfo());d.FallbackSerializationProvider = typeof(ProtobufSerializer).GetTypeInfo(); })
> ```
> 我这样做了
> 但是并没有什么用

private static async Task<ISiloHost> StartSilo()
        {
            int siloPort = EndpointOptions.DEFAULT_SILO_PORT;
            int gatewayPort = EndpointOptions.DEFAULT_GATEWAY_PORT;
            var orleansSection = config.GetSection("Orleans");
            if (orleansSection != null)
            {
                siloPort = orleansSection.GetValue<int>("SiloPort");
                gatewayPort = orleansSection.GetValue<int>("GatewayPort");
            }
            // define the cluster configuration
            var builder = new SiloHostBuilder()
                // .UseDashboard(options => { }) // 开启dashboard后，控制台会不断打印信息，应该可以通过CounterUpdateIntervalMs设置频率
                .UseLocalhostClustering(siloPort, gatewayPort)
                .Configure<ClusterOptions>(options =>
                {
                    options.ClusterId = "dev"; // 相同的集群id，才能组件在同一个集群内
                    options.ServiceId = "DmeApp";
                })
                .Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Loopback)
                .ConfigureApplicationParts(parts => parts
                .AddApplicationPart(typeof(TaskService).Assembly)
                .WithReferences())
                .ConfigureLogging(logging => logging.AddNLog().AddConsole());

            var host = builder.Build();
            await host.StartAsync();
            return host;
        }

**Comment by sergeybykov** [comment]
`Microsoft.Orleans.CodeGenerator.MSBuild` analyzes source code of the project while `Microsoft.Orleans.OrleansCodeGenerator.Build` loads and scans a precompiled assembly. As a result, `Microsoft.Orleans.CodeGenerator.MSBuild` isn't sensitive to differences in versions of dependency libraries and is faster. A known downside of `Microsoft.Orleans.CodeGenerator.MSBuild` is that it generates a longer list of known types, which doesn't impact execution but does produce longer source files.

**Comment by leoterry-ulrica** [comment]
@sergeybykov Should I use Microsoft.Orleans.CodeGenerator.MSBuild?

**Comment by HermesNew** [comment]
如果你的程序集是.netstandard2.0的话，就可以使用Microsoft.Orleans.CodeGenerator.MSBuild来生成orleans的代码。

**Comment by sergeybykov** [comment]
>Should I use Microsoft.Orleans.CodeGenerator.MSBuild?

Yes, that's what we recommend going forward.

**Comment by leoterry-ulrica** [comment]
> 如果你的程序集是.netstandard2.0的话，就可以使用Microsoft.Orleans.CodeGenerator.MSBuild来生成orleans的代码。

程序集是.net core2.1

**Comment by HermesNew** [comment]
@leoterry-ulrica 程序集你为什么不用.netstandard2.0呢? 改成.netstandard2.0吧，程序集是netcore就有点奇葩了

**Comment by leoterry-ulrica** [comment]
@HermesNew 奇葩在哪里

**Comment by 2821840032** [comment]
他应该是写在控制台里了，目标框架.net core 2.0

**Comment by HermesNew** [comment]
@leoterry-ulrica 如果你觉得不奇葩，那你可以继续的。

**Comment by sergeybykov** [comment]
@leoterry-ulrica Are you okay closing this now?

**Comment by leoterry-ulrica** [comment]
@sergeybykov yes, thx
