### ISSUE TITLE
System.NotSupportedException: Call cannot be made outside of a transaction.  

### ISSUE THREAD

**Issue by zhaoqinghai** [dotnet/orleans#5156]
i use interceptor and transactions,it runs wrong. how do i solve, thank you

**Comment by sergeybykov** [comment]
Can you provide more information, maybe code of what you are trying to do?

**Comment by zhaoqinghai** [comment]
var builder = new SiloHostBuilder()
                .AddIncomingGrainCallFilter(async context =>
                {
                    try
                    {
                        await context.Invoke();
                    }
                    catch (Exception ex)
                    {
                        context.Result = 1;
                    }
                })
                .Configure<ClusterOptions>(options =>
                {
                    options.ClusterId = "dev";
                    options.ServiceId = "hello";
                })
                .UseLocalhostClustering()
                .Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Loopback)
                .ConfigureApplicationParts(parts =>
                {
                    parts.AddApplicationPart(typeof(HelloGrain).Assembly).WithReferences();
                })
                .AddAdoNetGrainStorageAsDefault(configureOptions =>
                {
                    configureOptions.ConnectionString =
                        "Data Source=.;Database=hello;Integrated Security=True;Pooling=False;Max Pool Size=200;";
                    configureOptions.Invariant = "System.Data.SqlClient";
                })
                .UseTransactions();
