### ISSUE TITLE
Is it possible to cross the LAN

### ISSUE THREAD

**Issue by 2821840032** [dotnet/orleans#5157]
I wonder if the two lans can communicate with him
I've tried non-reliable deployments, and the problem is that my primary repository can only use UseLocalhostClustering(), which is 127.0.0.1 and seems inaccessible to outsiders

**Comment by sergeybykov** [comment]
Localhost clustering should only be used for development and local testing. For any real deployment, externally accessible IP addresses should be used.

**Comment by 2821840032** [comment]
I want to deploy an unreliable Orleans, but how do I start the main silo?

**Comment by sergeybykov** [comment]
Have you found http://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/typical_configurations.html#unreliable-deployment-on-a-cluster-of-dedicated-servers?

`PRIMARY_SILO_IP_ADDRESS` is the address of the first (primary) silo in the cluster.

**Comment by 2821840032** [comment]
`For testing on a cluster of dedicated servers when reliability isn’t a concern you can leverage MembershipTableGrain and avoid dependency on Azure Table. You just need to designate one of the nodes as a Primary.`

`You just need to designate one of the nodes as a Primary`

How does the specified master silo start? UseLocalhostClustering? I can't seem to find him on the LAN

**Comment by 2821840032** [comment]
Thank you for your answer. I looked at the source code of the CoreHostingExtensions class and found the result I wanted. I just need to Configure "Configure<EndpointOptions>" and "UseDevelopmentClustering", thanks again
