### ISSUE TITLE
VS 2015 RC, Code Gen not happening

### ISSUE THREAD

**Issue by ElanHasson** [dotnet/orleans#516]
See https://github.com/ElanHasson/NoCodeGenOrleans/ for working example.

Build Output: https://gist.github.com/ElanHasson/a3a1957c988e9a13eddf

![image](https://cloud.githubusercontent.com/assets/234704/8152257/de8b3056-12e8-11e5-8382-1ece56798760.png)

**Comment by jthelin** [comment]
Check that your grain classes project references the Microsoft.Orleans.Templates.Grains package.

Sorry, i can't access that repo (permissions?) to confirm, but build log looks consistent with that hypothesis.

**Comment by raybooysen** [comment]
And additionally, check that in your csproj, the project have the correct imports.  This should be added by the nuget package. You can compare it to the HelloWorld sample if needed.

**Comment by ElanHasson** [comment]
@jthelin  I've readded the missing repo.

The issue was: I had to uninstall and reinstall the Microsoft.Orleans.Templates.* nugets

**Comment by ElanHasson** [comment]
This issue may be closed.

**Comment by ElanHasson** [comment]
project file was referencing the build targets for grains as well as grain references.

@ReubenBond  saved the day.
