### ISSUE TITLE
The SocketAsyncEventArgs.Buffer is not cleared when it's returned to the pool.

### ISSUE THREAD

**Issue by linluxiang** [dotnet/orleans#5160]
The Buffer of the SocketAsyncEventArgs is not cleared when it's returned to the pool. When this args is used for the next time, the old buffer, which may contains the legacy data, will still be passed to IncomingMessageBuffer.UpdateReceivedData. Then if the IncomingMessageBuffer wanted to read "e.BytesTransferred" bytes from the Buffer, it might get the old message.

This code should be added to the method below.
`
Array.Clear(args.Buffer, 0, args.Buffer.Length);

args.SetBuffer(0, args.Buffer.Length);
`

https://github.com/dotnet/orleans/blob/6b802f6365e78d691430360a4101b1993eb7afee/src/Orleans.Runtime/Messaging/IncomingMessageAcceptor.cs#L441

==

Update: There could be another bug in .net core runtime on linux. After I called SetBuffer, and when it triggered the OnCompleted event, the BytesTransferred is not zero but the args.Offset is zero.

Maybe it could be solved if we don't use a pool

**Comment by jason-bragg** [comment]
Hi @linluxiang, thanks for the investigation.

Are you seeing an unexpected behavior? Can you provide a repro?

The contents of the buffer are copied in IncomingMessageBuffer.UpdateReceivedData.  No need to clear the buffer because contents will be overwritten up to BytesTransferred, which is all we look at.  Messages are processed from the IncomingMessageBuffer.

Where should these lines be added in the code?  Can you submit a pr with your suggested changes?

**Comment by linluxiang** [comment]
@jason-bragg Yes, I saw some unexpected behavior. I was doing stresstest on our service, and I found that if I used a Orleans Client connecting and disconnecting to an Orleans Silo rapidly and repeated several times. The Orleans Silo stopped responding and the client got a timeout (response did not arraive in 30 seconds) error. Then I did a remote debugging to find out the cause of it. I found that in the "TryDecodeMessage" method of class IncomingMessageBuffer, the body size of the top 1 message in the readBuffer was different from what the client sent before. The BytesTransferred was 137, the body size should be 16. But the body size of first message in the readBuffer is 50, which made this check failed `            if (receiveOffset - decodeOffset < CalculateKnownMessageSize())
                return false;
`. Then I was trying to find out why the first message was incorrect. And I found that the IncomingMessageBuffer is new for each newly-accepted socket, but the SocketAsyncEventArgs is reused. This may lead to a scenario that, when a new socket is accepted, an old SocketAsyncEventArgs is assigned to it. As there is no clean-up for the Buffer of the old SocketAsyncEventArgs, the new IncomingMessageBuffer will still try to parse the left-over data in the Buffer. And this is the cause of the unexpected behavior.

**Comment by linluxiang** [comment]
It's easy to reproduce. My running environement is Ubuntu LTS 16.04 and .net core version is 2.1.403. I just added some logs in OutgoingMessageSender and IncomingMessageBuffer to print the headerLength and bodyLength, and found they are not equal.

**Comment by linluxiang** [comment]
I can paste some logs that I recorded below. As you can see, the bodyLength is negative in receiving.

Sender side
```
Messaging.GatewayConnection/GatewayClientSender_gwy.tcp://192.168.15.165:30000/279114651 - =====!!: send msg: header length: 150, body length: 16
```

Receiver side

```
12:00:52,019 UTC [63] INFO  Orleans.Runtime.IncomingMessageBuffer -   =======  received header length: 131 bodyLength: 16
12:00:52,020 UTC [63] INFO  Orleans.Runtime.IncomingMessageBuffer -   =======  received header length: 1628480243 bodyLength: -1477026000
```

**Comment by linluxiang** [comment]
@jason-bragg WOW, I found something new.
When I ran the same dll under dotnet-runtime-2.0.9, this error went away!
And then I tried dotnet-runtime-2.1.5, this error happend, and I also tried the latest 2.2.0-preview-3, this error still exists.

So it looks like this bug is releated the the implementation of SocketAsyncEventArgs.

**Comment by sergeybykov** [comment]
@linluxiang Do you have `TieredCompilation` turned on by chance?

**Comment by linluxiang** [comment]
@sergeybykov No I don't

**Comment by linluxiang** [comment]
Latest update. I found someone else has found the same problem I met. I turns out to be a dotnet core runtime bug. https://github.com/dotnet/corefx/issues/33794

**Comment by sergeybykov** [comment]
Interesting. I wonder if it's the same bug @jason-bragg discovered years ago.
