### ISSUE TITLE
The orleans client connection to the silo often occurs timeout

### ISSUE THREAD

**Issue by codesee** [dotnet/orleans#5161]
I have developed a product using the Orleans .net core version, which uses .net core
 webapi is connected to Silo(server side) as a client. Unfortunately, some problems occurred after the product went online, that is, the orleans client connect to the silo often (about every half a day) occurs timeout.The following error messages appear in the log:

`Orleans.Runtime.CallbackData Response did not arrive on time in 00:00:30 for message: IsAlwaysInterleave Request S10.123.6.17:11111:278069385*grn/F8588497/00000000+cf03f099-e162-41e3-9d12-abc02245aea4@38484092->S10.123.6.17:11111:278069385*grn/9C2A0175/00000000+cf03f099-e162-41e3-9d12-abc02245aea4@757ca091 #1966753: . Target History is: <S10.123.6.17:11111:278069385:*grn/9C2A0175/00000000+cf03f099-e162-41e3-9d12-abc02245aea4:@757ca091>. About to break its promise.`

After the above situation, the entire product becomes unavailable.I initially thought from the above log that the webapi client could not connect to the silo server, but I don't know what caused the problem.I searched a lot of relevant information, but still can't solve the problem.Currently I have to make the product available by restarting Silo.

The following is the starting Silo code in the Silo server side of the product:

```csharp
private static async Task<ISiloHost> StartConsulSilo()
        {
            var orleansCluster = GetOrleansClusterOptions();
            var siloServerOptions = GetSiloServerOptions();

            var builder = new SiloHostBuilder()
                .Configure<EndpointOptions>(ConfigureSiloOptions)
                .Configure<ClusterOptions>(options => { options.ClusterId = orleansCluster.ClusterId; options.ServiceId = siloServerOptions.ServiceId; })
                .UseConsulClustering(options => { options.Address = new Uri(orleansCluster.ConsulAddress); })
                .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(CacheGrain<>).Assembly).WithReferences())
                .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(UserGrain).Assembly).WithReferences())
                .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(AuditGrain).Assembly).WithReferences())
                .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(TaskGrain).Assembly).WithReferences())
                .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(ProductGrain).Assembly).WithReferences())
                .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(ParameterGrain).Assembly).WithReferences())
                .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(FtpGrain).Assembly).WithReferences())
                .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(BaseFileGrain).Assembly).WithReferences())
                .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(TaskFileGrain).Assembly).WithReferences())
                .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(RoleGrain).Assembly).WithReferences())
                .ConfigureLogging(logging => logging.AddNLog())
                .ConfigureServices(services =>
                {
                    services.UseNLog("nlog.config");
                    services.AddTransient<IDbContext, DefaultDbContext>();
                    services.AddSingleton<IAppFolders>(SetAppFolders());
                })
                .AddMongoDBGrainStorageAsDefault(options =>
                {
                    var mongoOptions = new MongoOptions();
                    hostConfiguration.GetSection("MongoDB").Bind(mongoOptions);
                    options.Configure(config =>
                    {
                        config.ConnectionString = mongoOptions.ConnectionString;
                        config.DatabaseName = mongoOptions.DatabaseName;
                        config.CollectionPrefix = "State_";
                    });
                });

            var host = builder.Build();
            await host.StartAsync();
            return host;
        }
```

The following is the connecting Silo code in the webapi client of the product:

```csharp
private static async Task<IClusterClient> StartClientWithRetries(ILogger<Startup> logger, int initAttemptBeforeFailing = 5)
        {
            int attempt = 0;
            IClusterClient client;
            var orleansCluster = GetOrleansClusterOptions();

            while (true)
            {
                try
                {
                    client = new ClientBuilder()
                        .Configure<ClusterOptions>(options => options.ClusterId = orleansCluster.ClusterId)
                        .UseConsulClustering(gatewayOptions => { gatewayOptions.Address = new Uri(orleansCluster.ConsulAddress); })
                        .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(ICacheGrain<>).Assembly).WithReferences())
                        .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(IUserGrain).Assembly).WithReferences())
                        .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(IAuditGrain).Assembly).WithReferences())
                        .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(ITaskGrain).Assembly).WithReferences())
                        .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(IProductGrain).Assembly).WithReferences())
                        .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(IParameterGrain).Assembly).WithReferences())
                        .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(IModuleGrain).Assembly).WithReferences())
                        .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(IDfsGrain).Assembly).WithReferences())
                        .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(IBaseFileGrain).Assembly).WithReferences())
                        .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(ITaskFileGrain).Assembly).WithReferences())
                        .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(IRoleGrain).Assembly).WithReferences())
                        .ConfigureLogging(logging =>
                        {
                            logging.ClearProviders();
                            logging.AddNLog();
                        })
                        .Build();

                    await client.Connect();

                    logger.Info("The client successfully connected to the silo");
                    break;
                }
                catch (SiloUnavailableException ex)
                {
                    attempt++;
                    logger.LogError(ex, $"Trying to initialize the Orleans client fails {attempt}/{initAttemptBeforeFailing}");

                    if (attempt > initAttemptBeforeFailing)
                    {
                        throw ex;
                    }

                    await Task.Delay(TimeSpan.FromSeconds(3));
                }
            }

            return client;
  }
```

Have you encountered this situation? Is the way I use the client and server as it is correct? 
I am looking forward to your help so that I can solve this problem as soon as possible.Thank you.

**Comment by sergeybykov** [comment]
Can you share silo and client logs around the time when this happens?

Have you tried a different clustering provider for a comparison? We definitely don't see anything like this happening. So I wonder if the clustering provider is failing here. But it's impossible to tell without seeing the logs.

**Comment by sergeybykov** [comment]
In the silo log snippet you posted it says:
>Enqueuing task System.Threading.Tasks.ContinuationTaskFromResultTask1[System.Int32] to a stopped work item group. Going to ignore and not execute it. The likely reason is that the task is not being 'awaited' properly. 

Are you awaiting all asynchronous calls properly?

It also has a warnings about an operation blocking a thread for hundreds of milliseconds:
>Task [Id=2, Status=RanToCompletion] in WorkGroup [Activation: S127.0.0.1:19898:279170146*grn/52C037A8/00000000+5b7abddbdd0a3b06d4f5a125@soonfor@1,2,3@releases@1f510a93 #GrainType=SF.Update.PackageFile.PackageFileGrain Placement=StatelessWorkerPlacement State=Valid] took elapsed time 0:00:00.2597448 for execution, which is longer than 00:00:00.2000000

Are you performing synchronous IO operations there?

**Comment by codesee** [comment]
Hi @sergeybykov, I am very grateful for your patience.
I am not awaiting all asynchronous calls. But there are multiple tasks for ModuleGrain's GetTree in ProductGrain,which awaits  all of these tasks. As shown in the following code.

The code snippet  implemented in ProductGrain is as follows:

`public virtual async Task<ListResultDto<TreeNodeDto>> GetAllProductAndModuleTree(CancellationToken cancellationToken = default(CancellationToken))
 {
            var products = (await Repository.QueryAsync(cancellationToken)).ToList();
            var moduleGrain = GrainFactory.GetGrain<IModuleGrain>("module");

            var tasks = new Task<ListResultDto<TreeNodeDto>>[products.Count()];
            int count = products.Count();

            for (int i = 0; i < count; i++)
            {
                tasks[i] = moduleGrain.GetTrees(products[i].Id, cancellationToken);
            }

            await Task.WhenAll(tasks);

            var productAndModuleTree = new List<TreeNodeDto>();

            for (int i = 0; i < count; i++)
            {
                var product = products[i];
                var treeNode = new TreeNodeDto($"{product.Code}({product.Name})", $"P:{product.Id}");
                treeNode.Other = product.Id;
                treeNode.Children = tasks[i].Result.Items.ToList();

                productAndModuleTree.Add(treeNode);
            }

            return new ListResultDto<TreeNodeDto>(productAndModuleTree);
 }`

IModuleGrain's GetTrees method is：

` Task<ListResultDto<TreeNodeDto>> GetTrees(string productId, CancellationToken cancellationToken = default(CancellationToken));`

Is there a problem with the asynchronous call above? please let me know.

In addition, I did perform synchronous IO operations in some private methods of PackageFileGrain, and I have adjusted to asynchronous operation.

However, in some other Grains, although there is no synchronous IO operation, the following similar warnings will still appear in the silo log:

`Task [Id=2, Status=RanToCompletion] in WorkGroup [Activation: S127.0.0.1:19898:279170146*grn/52C037A8/00000000+5b7abddbdd0a3b06d4f5a125@soonfor@1,2,3@releases@1f510a93 #GrainType=SF.Update.XXX Placement=StatelessWorkerPlacement State=Valid] took elapsed time 0:00:00.2597448 for execution, which is longer than 00:00:00.2000000`

Is there any other reason for the above problem? thank you.

**Comment by sergeybykov** [comment]
>I am not awaiting all asynchronous calls.

Why not? To be clear, joining several `Task`s and awaiting the `Task` returned by `Task.WhenAll` counts as awaiting all joined `Task`s. Returning a `Task` from an asynchronous method count as well.

>Is there a problem with the asynchronous call above? Please let me know.

I don't see anything wrong with the code above other than what I would consider an inefficiency - calling `moduleGrain.GetTrees()` in a loop instead of making a single call with an array of product IDs.

>However, in some other Grains, although there is no synchronous IO operation, the following similar warnings will still appear in the silo log:
Task [Id=2, Status=RanToCompletion] in WorkGroup [Activation: S127.0.0.1:19898:279170146*grn/52C037A8/00000000+5b7abddbdd0a3b06d4f5a125@soonfor@1,2,3@releases@1f510a93 #GrainType=SF.Update.XXX Placement=StatelessWorkerPlacement State=Valid] took elapsed time 0:00:00.2597448 for execution, which is longer than 00:00:00.2000000

Are you sure the grain class with type code `52C037A8` does not perform a synchronous operation blocking the thread?

**Comment by sergeybykov** [comment]
The code looks fine to me. Returning a `Task` is perfectly fine. you are injecting an implemntation of `IFtpClient`. Is it a singleton? Is it thread safe?

**Comment by codesee** [comment]
No, It is a transient. I have tried to inject the implementation of `IFtpClient` with singleton lifetime,but it did not work properly. I really can't find the reason for the previous problem (the orleans client connection to the silo often occurs timeout). Due to the development schedule, I intend to give up the use of Orleans in the current project. However, I will always look for a solution to this problem. Thank you very much for your answer, @sergeybykov .

**Comment by sergeybykov** [comment]
The experiment I'd suggest to run to rule out the possibility of the `IFTPClient` being the culprit here is to wrap each call to `_ftpClient.XYZAsync()` as `await Task.Run(_ftpClient.XYZAsync())` to make those calls entirely run on the .NET thread pool, and to see if that make any difference.

**Comment by codesee** [comment]
This is a good idea, but I didn't do that, and I have a better way.

The following error issues have not been resolved yet, I don't know what caused it.

`Enqueuing task System.Threading.Tasks.ContinuationTaskFromResultTask1[System.Int32] to a stopped work item group. Going to ignore and not execute it. The likely reason is that the task is not being 'awaited' properly. WorkItemGroup:Name=[Activation: S127.0.0.1:19898:279170146*grn/49B72F98/00000000+5b7abddbdd0a3b06d4f5a125@soonfor@1,2,3@products@f1462fb7 #GrainType=SF.Update.Products.ProductGrain Placement=StatelessWorkerPlacement],WorkGroupStatus=Shutdown. Currently QueuedWorkItems=0; Total EnQueued=297; Total processed=297; Quantum expirations=0; TaskRunner=ActivationTaskScheduler-14:Queued=0; Detailed SchedulingContext=<[Activation: S127.0.0.1:19898:279170146*grn/49B72F98/000000000000000000000000000000000600000049b72f98+5b7abddbdd0a3b06d4f5a125@soonfor@1,2,3@products-0xF2287E47@f1462fb7 #GrainType=SF.Update.Products.ProductGrain Placement=StatelessWorkerPlacement State=Invalid NonReentrancyQueueSize=0 EnqueuedOnDispatcher=0 InFlightCount=0 NumRunning=0 IdlenessTimeSpan=02:01:18.0967877 CollectionAgeLimit=02:00:00]> |Orleans.Runtime.Scheduler.WorkItemGroup|EventId_Id=101217, EventId_Name=, EventId=101217`

**Comment by sergeybykov** [comment]
@codesee @fduman Did you manage to resolve these issues?
