### ISSUE TITLE
[Question] EventStore Read-only stream adapter

### ISSUE THREAD

**Issue by darthkurak** [dotnet/orleans#5165]
Hi. Im trying use Orleans for CQRS - EventSource pattern. I want grains to persist their state in EventStore.
That part is pretty obvious - we can use OnActivate and load all neccesery events and build Grain State.
But when Grain publish new Event to the EventStore we want to subscribe to this events in other Grains and it seems that great option is use Orleans Streams with own custom adapter which is read-only and read via subscriptions new events from EventStore streams and pushes them to the subscribed grains.
I want to try write this stream adapter. 
My first concern is - a queueID and it's concept and how this should map to the EventStore inftrastrucute. 
EventStore only contains streams - we can subscribe to them. How to achieve this with QueueID concept in Orleans? It should be one queue for each stream? What piece of code decide how many queues will be created? Can anyone guide me here?

**Comment by sergeybykov** [comment]
Streams in Orleans are virtual. There maybe a very large (in theory infinite) number of them. They are deterministically mapped to queues that are physical entities in the underlying infrastructure - queues, topics, partitions, etc. For scalability and performance, handling of queues (pulling events from them) is dynamically distributed across silos in the cluster with each pulling agent responsible for one or more queues. See [my comment on another issue](https://github.com/dotnet/orleans/issues/5164#issuecomment-436734532).

If you can divide the work of pulling events from EventStore (by topics or something), so that it can be distributed across multiple agents, then you should be able to fit the streaming pattern with each slice of pulling responsibility presented as a "queue".

**Comment by darthkurak** [comment]
EventStore doesn't have anything beside streams. I could use mapping one stream - one Orleans queue, but that means that i would have potentially millions of queues what is equal to having millions of pulling agents. That seems to not be good. 
Second option is that i could arbitrary divide EventStore streams number by some desired constant (for example 32) which would make 32 queues and each queue would subscribe to the almost same number of streams, which was assigned by some simple algorithm. But then my main consideration is - what when new stream would come up? How Orleans could know that and assign to it?
Third option is make one queue which subscribe to all streams in EventStore - but then, this means only one pulling agent and no scalability at all.
And last, but maybe the best option - EventStore have something like PersistentSubscription which implement Competing Consumers - we could create such subscription to all streams, and then use constant number of queues which would be competing consumers in this scenario, but each of them will get different set of events from EventStore and then EventStore is responsible to maintain what sent to what consumer/queue. 
My guesss would be the 4th option. 
But what do you think?

**Comment by sergeybykov** [comment]
>Second option is that i could arbitrary divide EventStore streams number by some desired constant (for example 32) which would make 32 queues and each queue would subscribe to the almost same number of streams, which was assigned by some simple algorithm. But then my main consideration is - what when new stream would come up? How Orleans could know that and assign to it?

Your stream provider would have to have a way to learn about new streams by periodically polling EventStore or subscribing to some notifications (I have no idea if EventStore supports that). Orleans would be oblivious to that. Pulling agents would simply call the stream provider asking for more events.

>And last, but maybe the best option - EventStore have something like PersistentSubscription which implement Competing Consumers - we could create such subscription to all streams, and then use constant number of queues which would be competing consumers in this scenario, but each of them will get different set of events from EventStore and then EventStore is responsible to maintain what sent to what consumer/queue.

This might work. The downside I see with this option, if I understand it correctly, is that there will be no affinity of streams/queues to the competing consumers. That would make caching of events mostly pointless and would easily break ordering of events if switching consumers will deliver events from different batches concurrently.

With the *puling agent -> queue* affinity you get ordering and sequence tokens naturally, and caching helps pull events into memory faster than subscribers can consumer them, which is good for recovery and handling of multiple subscribers having different 'cursors' on the same stream. On top of that, you can easily optimize for subscribing grains to be mostly placed on the same silos as the pulling agents that send events to them, hence eliminating the cross-silo grain calls.
