### ISSUE TITLE
[Question] Writing to storage performance

### ISSUE THREAD

**Issue by darthkurak** [dotnet/orleans#5169]
Hi everyone! I have following scenario: ClusterClient read events from EventHub and then send them to the Orleans. One grain takes those batches, groups them by the key and then send to the second grain which writes to Blob Storage (append blob - one blob for one key). 

I have implementation of this (stateless workers) and everything works fine when key granularity is low. (we make less connection to blobs writing grouped batches). 

But when granularity of key grow (for example in worst scenario we can have one event - one key) bad things start happen and everything chocks up. I understand that this is due to almost one event - one write to blob, but i wonder what optimizations can be done here to improve this. 

I tried raising DefaultConnectionLimit, play with number of activation of statlessworkers, but i can't go beyond of 250 messages per second on single machine (Azure Standard F8s_v2 (8 vcpus, 16 GB memory)). This is with default settings. 

To contrast that, when i choose one single key to write everything to the same blob in batches (exact same batch which was received in EventHubProccesorHost), i can achieve 25k messages per second on the same machine and have almost half cpu % reserve. Of course, the number of writes to the blob storage is far less than 25k messages, as single write has up to 1024 messages).
Quotas on blob storage says that it can achieve 20k requests per second. 
Do you have idea how to improve this? How many concurrent connection to the blob one single machine can achieve?

big picture:

![orleanstopology](https://user-images.githubusercontent.com/4254758/48219499-f5966180-e38c-11e8-9cb0-ccfee0b4cd7c.png)

Few notes: 
- Everything is async/await

**Comment by darthkurak** [comment]
Also i wonder, what this settings in PerformanceTuningOptions mean:

        public bool Expect100Continue { get; set; }

        public bool UseNagleAlgorithm { get; set; }

**Comment by sergeybykov** [comment]
>To contrast that, when i choose one single key to write everything to the same blob in batches (exact same batch which was received in EventHubProccesorHost), i can achieve 25k messages per second on the same machine and have almost half cpu % reserve.

What is the CPU utilization in the one event - one key case? Is the silo running with `gcServer=true`? Is this on Windows? Anything flagged in the logs?

**Comment by darthkurak** [comment]
I have update on this.
I managed to get 5k/s messages per second. (around 5 Receive Grains / s - as it takes batches 1024 from EventHubHost - then split them one by one and send to Write Grain). I did this by playing around with DefaultConnectionLimit and ThreadPool.MinThreads settings.
Utilization is around 60% in that case. A lot Memory available. gcServer set to true. Ubuntu 18.04 TLS azure vm. Can't go beyond that.
What is more, i created single application (.net core) which is just EventHubProccesorHost directly writing to blob in same manner just using Task = WriteToBlob and then Taksk.WhenAll with the same settings. I had hope that eliminating Orleans and focus on just pure writing scenario i manage to get more throughput but i was hugely surprised when i get a lot worse results. (around 10 times).
I'm really confused now ;/

**Comment by sergeybykov** [comment]
@darthkurak Sorry about delay. What's the latest on this?

**Comment by darthkurak** [comment]
Let's close now, as this was a while ago, and we switched to MongoDB.

**Comment by sergeybykov** [comment]
Thanks.
