### ISSUE TITLE
Expected request rate to OrleansSilos table

### ISSUE THREAD

**Issue by jsteinich** [dotnet/orleans#5177]
What rate/volume of requests can be expected to the OrleansSilos table?

Context:
We have a dev environment setup using DynamoDB for primary storage and for clustering. We are using default grain membership configuration. To save costs we have the provisioning limit set very low. We observed that with only a few users hitting the system we were hitting throttling on read requests to the OrleansSilos table.
One thing that might be impacting our workload is using `IManagementGrain` on a regular basis.

We can certainly increase the provisioning, but are a bit concerned about how those accesses might scale.

**Comment by sergeybykov** [comment]
In a stable state, each silo should touch the cluster membership table only once a minute (by default).

**Comment by jsteinich** [comment]
Thanks for the response. I'm pretty sure the issue is our use of the management grain to implement a sudo transaction hook while we are waiting for the 2.2 transaction changes.

**Comment by jsteinich** [comment]
Usage has stabilized since removing that hook.
