### ISSUE TITLE
How to deal with the relationship between the gateway and transmission entity？

### ISSUE THREAD

**Issue by 2821840032** [dotnet/orleans#5179]
Main Silo (gateway) seems to be quoted all transport entities, or the gateway will throw an exception.
`Fail: Orleans.Runtine.Messaging. IncomingMessageAcceptor[101027]ProcessReceivedBuffer exception with RemoteEndPoint 10.10.10.140:1886: System.TypeAccessException: Named type "Entity.GoodsEntity" is invalid: Type str ing "Entity.GoodsEntity" t be resolued.`
If so, in the development, each time a colleague modify transport entities to restart gateway?

**Comment by sergeybykov** [comment]
Every time you add a new type or change an existing one that can be sent over the wire, you need to make both sides aware of it. Hence, restarting of the running gateway is needed. If I understood your question corretly.
