### ISSUE TITLE
How to Serialize/Deserilize DataTable?

### ISSUE THREAD

**Issue by ishowfun** [dotnet/orleans#5181]
I wrote an interface like this:
``` C#
    public interface  IUserService:IGrainWithIntegerKey
    {
        ...       
        Task<DataTable> GetData();
        ...
    }
```
and I wrote a grain then.
When I call this method in a garin client ,the exception occured:
>System.InvalidCastException: Unable to cast object of type 'Orleans.Serialization.SerializationContext' to type 'System.IConvertible'.

Now I have to convert the DataTable to  a IEnumerable<IDictionary<string,object>> to make it work.
I wonder if there's a graceful way to handle it.

**Comment by sergeybykov** [comment]
`IEnumerable<T>` cannot be used as an argument or return value type because its elements are dynamically produced. You can use a concrete container class instead, e.g. List<T>.

**Comment by ReubenBond** [comment]
@ishowfun I do not believe that there is a graceful way to handle this unless you create a custom serializer (see docs on serialization: https://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/serialization.html).

The core issue, as far as I can recall, is that `DataTable` implement `ISerializable` in a way that requires a specific value to be passed in via the `SerializationContext` which `BinaryFormatter` uses. Orleans uses the `SerializationContext` to pass in runtime information, so this is not compatible.

Converting to another, well-defined, serializable type would be preferable.

**Comment by ishowfun** [comment]
@sebastianburckhardt @ReubenBond  thx for reply,I'll try your suggestion.
