### ISSUE TITLE
More graceful graceful shutdowns

### ISSUE THREAD

**Issue by emilevr** [dotnet/orleans#5183]
Orleans version: **2.1.2**

I've been experimenting with rolling upgrades (primarily in Kubernetes) and have noticed some inconsistent behaviour when shutting silos down gracefully (calling ISiloHost.StopAsync()). It is not specific to running in containers though, the same behaviour can be observed in console applications.

Note: Generally Orleans does what is advertised on the box, but I do feel that graceful shutdowns could be more consistent and ... well, more graceful. Even if that means that graceful shutdown would be slower/consist of more phases.

It would be great if errors can be avoided completely when all shutdowns are graceful, as is the case with rolling upgrades. This is particularly important when end users interact with grains - long pauses affecting some users during rolling upgrades are not ideal.

To help visualise these I've attached a simple solution consisting of two console apps:
* GracefulShutdownReproSiloHost is the host, which should be run a few times to start up a couple of silos.
* GracefulShutdownReproUI requests state and displays placement for 100 grains, once per second.

With a few silos running and while watching the UI, gracefully shut down a silo by pressing Ctrl+C in its console window.

Some non-ideal behaviours I've observed:
* Spamming the logs with warnings related to shutting down (would it not be better to either avoid these or suppress these as they seem to be just noise?):
`warn: Orleans.Runtime.Dispatcher[101032]
      Forwarding failed: tried to forward message Request S...:14377:280331499*cli/62b67d9a@35412dbd->S...:14377:280331499*grn/9FBF3810/00000044@d2463480 #2595[ForwardCount=2]:  for 2 times after Non-existent activation to invalid activation. Rejecting now.
warn: Runtime.Messaging.GatewaySender/GatewaySiloSender_0[0]
      Invalid usage attempt of Runtime.Messaging.GatewaySender/GatewaySiloSender_0 agent in Stopped state`
* A few errors in the log (would it not be better to either avoid these or suppress these as they seem to be just noise?):
`fail: Runtime.Messaging.IncomingMessageAgent/Application[100026]
      Asynch agent Runtime.Messaging.IncomingMessageAgent/Application encountered unexpected exception The Stage will be restarted.
System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.Exit(Object obj)
   at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Collections.Concurrent.BlockingCollection``1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection``1.TryTake(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Collections.Concurrent.BlockingCollection``1.Take()
   at Orleans.Runtime.Messaging.InboundMessageQueue.WaitMessage(Categories type) in D:\build\agent\_work\24\s\src\Orleans.Runtime\Messaging\InboundMessageQueue.cs:line 96
   at Orleans.Runtime.Messaging.MessageCenter.WaitMessage(Categories type, CancellationToken ct) in D:\build\agent\_work\24\s\src\Orleans.Runtime\Messaging\MessageCenter.cs:line 244
   at Orleans.Runtime.Messaging.IncomingMessageAgent.Run() in D:\build\agent\_work\24\s\src\Orleans.Runtime\Messaging\IncomingMessageAgent.cs:line 50
   at Orleans.Threading.FiltersApplicant``1.Apply(T action) in D:\build\agent\_work\24\s\src\Orleans.Core\Threading\ActionFilter.cs:line 86`
* In various silos, some warnings about non-existent and duplicate activations when another silo is gracefully shut down (these could persist for up to 30 seconds):
`warn: Orleans.Runtime.Dispatcher[101032]
      Forwarding failed: tried to forward message Request S...:14377:280331499*cli/62b67d9a@35412dbd->S...:16512:280331498*grn/9FBF3810/0000001c@fe65279b #2656[ForwardCount=2]:  for 2 times after Non-existent activation to invalid activation. Rejecting now.
warn: Orleans.Runtime.Dispatcher[101032]
      Forwarding failed: tried to forward message NewPlacement Request S...:41545:280331496*cli/62b67d9a@35412dbd->S...:16512:280331498*grn/9FBF3810/0000004b@d3fea594 #2804[ForwardCount=2]:  for 2 times after Duplicate activation to invalid activation. Rejecting now.`
* Sometimes a shutdown will result in very quick movement of all grains to different silos, bar one or two. The calls to the grains that did not move quickly will not time out but could take 5-10 seconds before they return successfully.
* Sometimes requests to a fair number of grains (those where the silo that was gracefully shut down was the grain directory master) will take about 10 seconds to return, with or without warnings logged in the client app and/or by other silos. These are often easier to demonstrate with 2 silos via shutting down one of them, as more grains are affected, but the behaviour is similar with higher numbers of silos.

PS. When the UI console app runs out of colours, just restart it.

[GracefulShutdownRepro.zip](https://github.com/dotnet/orleans/files/2595625/GracefulShutdownRepro.zip)

**Comment by benjaminpetit** [comment]
We see improvements with some of the latest changes. Please open a new issue if you are still seeing these errors
