### ISSUE TITLE
EventHubStreamProvider run out for memory

### ISSUE THREAD

**Issue by darthkurak** [dotnet/orleans#5187]
Hi. I did adaptation of EventHubStreamProvider to read from EventHubs external messages.
It works and im getting messages.
Then i run load test running silo on VM machine with 16 GB rams. 
I populated EventHub with huge amount of small messages, and then run Orleans - with grain attached to the Stream. Grain is StatelessWorker. Grain just receive messages and return Task.CompletedTask. 
I get something around 45-50k reuqests/s on that grain and that was great. But i noticed that the memory on VM machine quickly grow to 14-15 GB and then my VM starts to be unresponsive, orleans dashboard hangs, and orleans console start signaling that requests cannot be completed. I wait a long time, but situation never changed - memory was still overload and not cleaned. 

My grain:
```
[StatelessWorker]
    [ImplicitStreamSubscription("messages")]
    public class ReadFromEventHubGrain : Grain, IReadFromEventHubGrain
    {
        public override async Task OnActivateAsync()
        {
            var streamProvider = GetStreamProvider("eventhub");
            var stream = streamProvider.GetStream<EventHubMessage>(this.GetPrimaryKey(), "messages");

            IList<StreamSubscriptionHandle<EventHubMessage>> allMyHandles = await stream.GetAllSubscriptionHandles();

            foreach (var subscriptionHandle in allMyHandles)
            {
                await subscriptionHandle.ResumeAsync((data, token) => HandleSubscription(data, token));
            }

            await base.OnActivateAsync();
        }


        private Task HandleSubscription(EventHubMessage data, StreamSequenceToken token)
        {
            return Task.CompletedTask;
        }
    }
```
Any thoughts about this?

**Comment by darthkurak** [comment]
Additionally, i deleted subscription to that stream, and nothing has changed besides a lot of warnings.
They notify about constantly increasing Tasks count and about RanToCompletion took longer than unusual.

![image](https://user-images.githubusercontent.com/4254758/48842782-76922780-ed95-11e8-92b7-63b1177d7e8e.png)

**Comment by HermesNew** [comment]
Are you using MemoryGrainStorage?
If you using MemoryGrainStorage,the messages will write into Memery.
So it will lead to continuous memory growth

**Comment by darthkurak** [comment]
No, im not using grain storage. HandleSubscription just return Task.Completed;
I think that i found the reason - stream provider internal cache, which have 30 minutes of retention - with really high throughput that cache exceed RAM of machine. I reduced this time to 5 minutes, and now uses something around 8-10 GB. 
But this i would consider as a problem too - because of that, solution cannot be a full auto-scale - i have to adjust internal cache retention to the actual throughput manually. (for high throughput 5 minutes retention is ok, but for low, it can be too small. )

**Comment by HermesNew** [comment]
@darthkurak 
yes,if you not using MemoryGrainStorage.Maybe the reason is Grain Collection Age Limit setting problem.The default Collection Age Limit is 2 hours.
[https://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/activation_garbage_collection.html](url)
Collection Age Limit 
This period of time after which an idle grain activation becomes subject to Activation GC is called Collection Age Limit. The default Collection Age Limit is 2 hours, but it can be changed globally or for individual grain classes.

**Comment by darthkurak** [comment]
This is not the case. Memory consumption occur even where there is zero active grains. It seems, that cache is filled with data and with enough big window, machine exceed max memory.

**Comment by jason-bragg** [comment]
I apologize for missing this thread.  EventHub Streams cache messages for error recovery purposes.  The default is 30 minutes, which means it will store 30 minutes of messages bases on the injection timestamp.  For some loads this default is too large.  For instance, if your service is expected to ingest 1gb of data per minute under peak load, and you've 10gb free memory on the silo host, the cache period would need be less then 10 minutes.

This can be configured via StreamCacheEvictionOptions using ConfigureCacheEviction.
