### ISSUE TITLE
Question: Can an IGrainService or IGrainServiceClient be called from an Orleans Client?

### ISSUE THREAD

**Issue by jsukhabut** [dotnet/orleans#5189]
Can an IGrainService or IGrainServiceClient be called from an Orleans Client or is it only accessible within a silo?

Can I get a handle to an IGrainService via clusterClient.GetGrain<T>?

**Comment by sergeybykov** [comment]
`GrainServiceClient` depends on `IConsistentRingProvider` (for mapping to silos) that is only available in a silo. So the only way to invoke a grain service is from within a silo.
