### ISSUE TITLE
Requests to old silo incarnation

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#5202]
Hi,

I just had the following scenario:

A silo was restarted (IP 10.0.0.46) and it was correctly updated in the membership table (MongoDB):

![membership table](https://user-images.githubusercontent.com/1236435/49216292-03a73300-f3cb-11e8-9833-b7c865dc1446.PNG)

The orleans dashboard only shows the new incarnation of this silo:

![dashboard](https://user-images.githubusercontent.com/1236435/49216319-128de580-f3cb-11e8-8205-f52865bb62dd.PNG)

Then I see a lot of exceptions like

`The target silo is no longer active: target was S10.0.0.46:11111:280671239, but this silo is S10.0.0.46:11111:281180672`

or 

`Response did not arrive on time in 00:00:30 for message: Request S10.0.1.38:11111:280671207*cli/da7976b3@755c9398->S10.0.0.46:11111:280671239*grn/23E3C64D/e1aa2aaa@654c47ab #10491769[ForwardCount=1]: . Target History is: <S10.0.0.46:11111:280671239:*grn/23E3C64D/e1aa2aaa:@654c47ab>    <S10.0.1.38:11111:280671207:*grn/23E3C64D/e1aa2aaa:@a63ff19e>.`

or

`
No target activation S10.0.1.38:11111:280671207*cli/da7976b3@755c9398 for response message: Transient Rejection (info: Silo S10.0.1.37:11111:280671208 is rejecting message: Request S10.0.1.38:11111:280671207*cli/da7976b3@755c9398->S10.0.0.46:11111:280671239*grn/16D28AEC/73a42f8e@704b21ad #10487332[ForwardCount=1]: . Reason = Target S10.0.0.46:11111:280671239 silo is known to be dead) Response S10.0.0.46:11111:280671239*grn/16D28AEC/73a42f8e@704b21ad->S10.0.1.38:11111:280671207*cli/da7976b3@755c9398 #10487332: 
`

It stopped after I terminated this node. The new node got a new IP and everything was fine.

It could be a bug in the MongoDB Membership Table, but I am confused why everything else looks good.

**Comment by sergeybykov** [comment]
This looks very strange, as incarnation (epoch) is part of silo identity, and all silos in the cluster quickly learn about a change like that. So I do wonder if this is indeed a bug in the MongoDB provider. Can you share the silo and client log when this repros? Have you tried the same with a different provider?

**Comment by SebastianStehle** [comment]
I think I cannot export the old logs anymore, but I can give you access to the Google Cloud Console if you want.

I cannot reproduce it, it only happened once after Kubernetes terminated my Node because out of Memory and I never had other problems, also not with the MongoDB Membership Table.

**Comment by SebastianStehle** [comment]
We still have the logs there in stackdriver but I cannot export them in an easy way.

**Comment by SebastianStehle** [comment]
I tried to reproduce it and forcefully terminated nodes, but It never happened again, but it was scary

**Comment by sergeybykov** [comment]
Should we close this for now then, and reopen when there's a repro or logs?

**Comment by SebastianStehle** [comment]
I can try it again to export the logs again, only problems with that :(

**Comment by SebastianStehle** [comment]
Lets close it for now.
