### ISSUE TITLE
Handling canary deployments

### ISSUE THREAD

**Issue by rore** [dotnet/orleans#5203]
This is a new incarnation of an old subject we wrap our head against since starting to use Orleans some years ago :-) 
It's all about deployment strategies. 

A quick description of the problem - we build microservices that use Orleans as their infrastructure. Each microservice is a separate Orleans cluster (with several silos on several machines).
To reduce deployment risks, we would like to use canary deployments. Meaning deploy a new version of the service, switch a portion of the traffic to it (1%, 5%), monitor for differences in behavior, if all is well switch to the new version. 

This is a deployment strategy that works well with stateless services. But when using Orleans there are multiple obstacles - 

- You cannot randomly switch traffic. Since you have stateful grains, you need to be able to switch a portion of the traffic according to a specific identifier that can signify the grains that are used (so all requests for certain grains ends up in the same cluster - prod or canary). Otherwise, you have multiple activation and stale states.

- What do you do if there is no consistent identifier that you can route on for all the methods the service exposes? What if you identify the "id" only in the middle of handling the request in the service?

- What if you need to switch off the canary? Some grains were already instantiated in the canary cluster, but they might be also active in the prod cluster. Now traffic will go again to prod, possibly to the old grains, and again you have stale state.

I don't think that the grain versioning feature answers this problem fully. I'm wondering if anyone else tried to handle this, or what are the deployment strategies that are actually used in production for high scale systems that are running on Orleans.

**Comment by sergeybykov** [comment]
@rore Sorry about delayed response. This is not a oneliner kind of question. 😊

A sister team of ours looked into this problem and worked with us on it a while ago. We had to use a combination of grain versioning and a custom version aware placement director. You can find some of those scenarios covered in our testcode: https://github.com/dotnet/orleans/blob/master/test/Grains/TestGrains/VersionAwarePlacementDirector.cs
https://github.com/dotnet/orleans/blob/master/test/Grains/TestVersionGrains/VersionGrainsSiloBuilderfactory.cs
https://github.com/dotnet/orleans/blob/master/test/Tester/HeterogeneousSilosTests/UpgradeTests/VersionPlacementTests.cs

The high-level approach is to deploy a new version of the service code as part of the same Orleans cluster and frontend clients. If you can segregate traffic at the frontends, then it is easy to control what requests would get routed to grains of the new version.

But as you pointed, that's not always easy/possible. That's where the custom placement director can help. For example, if there is no way to pick a version based on the grain ID (whitelisting or something), then the director can pick target versions randomly with desired probabilities to route the percentage of traffic you want to the new version.

We weren't able to generalize this approach yet to make it an out-of-the-box feature. But I see a possibility of encoding such strategies in the form of a reusable upgrade 'orchestration' feature.

**Comment by sergeybykov** [comment]
@rore Any update on your thinking?

**Comment by rore** [comment]
@sergeybykov we haven't really advanced much with the subject. There are some issues with grain versioning that might block us from actually using it but we didn't have time to fully investigate. The issues we see are - 
- The problem with placement by ID when we know the ID only in the middle of handling the request is still something we need to figure out
- We have a lot of complex flows that require interaction between multiple grains. The possible compatibility of grain versioning seems to be a problem, as some grains might be new and some old. What happens if the flow starts on a v2 grain but needs to use another existing v1 grain
- It seems to require a lot of developers discipline (you need to make sure you update the grain version every time you make a change and think about the implications), which is not very scalable in terms of development effort in a multi-service (multi-clusters) continuous delivery environment. Maybe it's possible to automatically update every grain version to the build version in build time, this way you don't need to worry about it and every deployment will be a new version for all grains
