### ISSUE TITLE
How do I deploy Silo on Azure as a app service?

### ISSUE THREAD

**Issue by keshavk** [dotnet/orleans#5206]
I am trying to deploy to my first Orleans project on Azure as a service but was not able to find any solution.
Right now I am using a local cluster and it is working fine.

**Comment by ReubenBond** [comment]
Hi @keshavk, I'm not familiar with how to deploy to Azure App Services or configure them for hosting. I believe it's possible to host a cluster there - but I am not sure. From my rudimentary understanding, it would require an App Service Environment: https://docs.microsoft.com/en-us/azure/app-service/environment/intro

You must have network connectivity between your clients and silos (they should be in the same environment).

I may be able to help with specific questions.

If anyone else is more familiar, please chime in.

**Comment by bsrini** [comment]
Hey @keshavk, the fastest way to getting Orleans working on Azure is to start with the [Service Fabric samples](https://github.com/dotnet/orleans/tree/master/Samples/2.1/ServiceFabric), and go from there, IMO.

**_Additional background information_**
The biggest barrier to getting Orleans working from an Azure App service based hosting environment (web-job, functions, web-app etc.) is that the networking infrastructure is tightly locked down for code hosted on it. Orleans requires 2 additional ports (gateway and silo) open for communication amongst the nodes, so it can set up the logical cluster, and that isn't permitted on app-service.

If you use _[service-fabric](https://azure.microsoft.com/en-us/services/service-fabric/)_ as your hosting environment, it comes with a vnet that already allows the virtual machines to talk to each other on any arbitrary port, so its much easier hosting Orleans on top of it than on app-service.

Alternatively, if you want to host on Linux VMs, you could look into setting-up an [AKS (Azure Kubernetes Service)](https://docs.microsoft.com/en-us/azure/aks/concepts-network) cluster and set up the vnet appropriately to allow the hosts to communicate with each other on the silo & gateway ports.

**Comment by knight1219** [comment]
Is there any docs for setting up a docker/k8s environment for Orleans? I saw there _used_ to be some docs but they were deleted last year and never came back.

**Comment by sergeybykov** [comment]
@knight1219 There's an old documentation page - http://dotnet.github.io/orleans/1.5/Documentation/Deployment-and-Operations/Docker-Deployment.html. It needs to be revisited. But you might be able to find something useful in it.

**Comment by GersonDias** [comment]
I'm trying to find some guidance though Orleans + Kubernetes and it is really hard to find good info about the deployment in general. I looking forward for a better deployment/operations documentation of an Orleans silo and to have a clear view of what kind of deployments we can have (can I deploy it to azure app services? how?) and I think this is a huge barrier to the broad adoption of Orleans...

**Comment by mofolom** [comment]
Has there been any more news on this?

**Comment by sjbthfc2** [comment]
Hi,

I am researching Orleans and I believe it is a brilliant choice for an IoT project my company is starting. Compared to Akka.net it's concepts are simple and easy to understand. However, as the comments above suggest, I have found it so hard to get any information on how to actually host and deploy Orlans silos to Azure or AWS cloud services and this is definitely scaring me off and I wonder if this has been a barrier to adoption. What I would like to know is:

1. What is a good unit of deployment choice for hosting a silo, e.g. a .NET Core Web API, console app, or generic host?
2. What physical infrastructure/cloud service is a good choice for the deployment platform, e.g. AWS ECS, Fargate, EC2, Azure App Service, Kubernetes, VMs, etc?

It seems like guidance here is non-existent, is it possible to get some more information around these scenarios? I would actually love to see an Azure Orleans PaaS, where you could pay for a "silo" host and just add new ones and connect clients to it which would be a hosted Orleans Actor environment in the cloud as a service.

**Comment by sjbthfc2** [comment]
Hi @bsrini 

Thank you so much for your response. So I guess using Orleans, we need to think about IaaS for long-lived hosting. Would a good option be the following:

1. Use several ASP.NET .NET Core Web APIs as a host process each used to build a silo and a client all joined to an Orleans cluster.
2. Deploy these silo API processes to Docker that are running on a platform that enables us to control the tcp communication between them.
3. Provide a load-balancer of some sort to the Web API processes and allow client requests to the cluster via this.

**Comment by ChristianEder** [comment]
@sjbthfc2 I would say it depends on your requirements on scalability and fault tolerance. If you're ok with the occasional downtime and limited CPU *a single* Azure App Service instance (meaning a single node) can offer, Orleans is just as easy to host on the Azrue App Service as any ASP.NET Core API project. Just today, I built a sample project for this (https://github.com/ChristianEder/orleans-iot) load testet it. With some fiddling around with batch sizes on message *ingestion*, but no real batching in place when *storing* received data, I got it to process around 600 messages per second from an Azure IoT Hub...

**Comment by ChristianEder** [comment]
Also, perhaps this part in the Orleans docs goes in the right direction? https://dotnet.github.io/orleans/docs/deployment/azure_web_apps_with_azure_cloud_services.html

**Comment by GersonDias** [comment]
the new Kubernetes section in the docs is definitely in the right direction and also has a nice sample application. @ChristianEder, the one you sent is also going in the right direction but feels to me incomplete yet (especially after the Kubernetes one)

**Comment by ReubenBond** [comment]
Closing since we have https://github.com/dotnet/orleans/issues/7553 now, which also links to an App Service sample (https://github.com/bradygaster/OrleansOnAzureAppService)
