### ISSUE TITLE
[Question] Google Cloud Platform PubSub

### ISSUE THREAD

**Issue by keithazzopardi** [dotnet/orleans#5218]
Hello,

In the Orleans.Stream.GCP.csproj, there is the following:

` <PropertyGroup>
    
    <IsPackable>false</IsPackable>
</PropertyGroup>`

Since Google.Cloud.PubSub has been release and is not in beta version, can we consider Orleans Google's PubSub as a stable version?

https://www.nuget.org/packages/Google.Cloud.PubSub.V1

**Comment by aldric** [comment]
Hello,

+1 for this comment.

While browsing the nuget.org repo, I could find Microsoft.Orleans.OrleansGCPUtils in version 2.0.0-rc2 which bundle : Google.Cloud.PubSub.V1 (1.0.0-beta13).

Two months ago google has released v1.0.0 of their PubSub Library. 

Would you be able to rebuild this nuget please ? 

Thanks,
A.

**Comment by sergeybykov** [comment]
Looks like there were some breaking API changes between 1.0.0-beta13 and 1.0.0. One can see that build breaks after changing https://github.com/dotnet/orleans/blob/master/Directory.Build.props#L89 from "1.0.0-beta13" to "1.0.0".
Are you willing to help by submitting a PR to address that?

**Comment by aldric** [comment]
Definitely yes. checking it out and pushing a PR soon.

**Comment by sergeybykov** [comment]
@aldric Did you get a chance to look into this?
