### ISSUE TITLE
Use of null in IAsyncObserver->OnNextAsync (vb.net)

### ISSUE THREAD

**Issue by BenjaminGibbs** [dotnet/orleans#522]
I have hit an issue which is stopping me implementing IAsyncObserver. (in VB)

The signature of the function is:
```
Task OnNextAsync(T item, StreamSequenceToken token = null);
```
Now the problem comes down to VB not having 'null' it uses 'nothing', and null is not nothing. The Error I am getting is:
```
xxx cannot implement 'Orleans.Streams.IAsyncObserver.OnNextAsync' because they differ by default values of optional parameter.
```
I am hoping their is an easy fix, but I have never run in to this before, I have had a quick google and can't see a way to reference null in VB.

If it is an issues that can't be fixed without a change the source, one solution would be to remove the optional parameter, and split the signature in to two, one without and one with the StreamSequenceToken.

What are peoples thoughts?

**Comment by sergeybykov** [comment]
So you are trying to implement `IAsyncObserver.OnNextAsync`, and you are unable to define a method equivalent to `Task OnNextAsync(T item, StreamSequenceToken token)`? I'm not familiar with VB.Net but this looks very strange to me.

**Comment by BenjaminGibbs** [comment]
Correct, however it is the operational parameter causing the issues, because VB does not have a 'null' object (it sounds strange but true). Because VB has no null it can't match up with the signature.

![ScreenShot](http://i.imgur.com/u9xA81y.png)

However while the IDE is throwing an error; that test project is actually building fine, I've not wired it in to test it running yet thou - which I will do in the next day or so, to see how it behaves.

**Comment by gabikliot** [comment]
Can't you just pass some dummy `StreamSequenceToken` instead of nothing?
So in your code you never have to match Nothing to null?

**Comment by sergeybykov** [comment]
Can you declare `token` argument as not optional?

**Comment by BenjaminGibbs** [comment]
@gabikliot it is the signature that is giving the error, not anything I pass in to it.
@sergeybykov I can't find a way around the IDE throwing the error (I have tried lots of ways). But it appeared to compile fine if I leave it as the default.

I have been using a inline function to avoid implementing ```IAsyncObserver``` for the time being.

**Comment by sergeybykov** [comment]
@BenjaminGibbs Are you sure this isn't a warning from ReSharper. VS seems to be happy - no error or warning at compilation. And logically I don't see an issue here - if the optional parameter isn't passed, it shouldn't matter what VB or C# use for `null`.

Adding an overload with a single parameter overload to `IAsyncObserver` seems like a wrong approach to me here because it would force every implementation to have two overloads for no good reason. This is exactly what optional parameters are for, I think.

**Comment by gabikliot** [comment]
@BenjaminGibbs , is this still an open issue?
