### ISSUE TITLE
Timeout exception when using Simple Message Stream Provider / Implicit Subscription

### ISSUE THREAD

**Issue by nvella88** [dotnet/orleans#5224]
I activate 3122 grains via a [OneWay] grain (Grain A) method. This first grain (Grain A), saves state, pushes an event (Event A) to stream and activates 2 more grains (Grain B and Grain C). Both Grain B and C save state and push an event to stream (Event B and Event C).

Event A and Event B are not picked up by any Grain (no subscribers). We do this to save the event, that is, event sourcing.

This is how we save state and push the event (Grain A, B and C inherit from a base class).
```
protected async Task WriteStateAndPublishEventAsync(TEventBase @event)
        {
            IEventLogGrain eventLogGrain = null;
            bool isEventSaved = false;
            try
            {
                // 1. Save event.
                var eventGuid = Guid.NewGuid();
                eventLogGrain = base.GrainFactory.GetGrain<IEventLogGrain>(eventGuid);
                await eventLogGrain.SaveEventAsync(@event);
                isEventSaved = true;

                // 2. Write State.
                await base.WriteStateAsync();

                // 3. Send even on the stream.
                IAsyncStream<TEventBase> stream = this.StreamProvider.GetStream<TEventBase>(this.GetKey(), @event.GetType().Name);
                IAsyncObserver<TEventBase> producer = stream;
                if (producer != null)
                {
                    await producer.OnNextAsync(@event);
                }
            }
            catch
            {
                // Roll-back event.
                if (eventLogGrain != null)
                {
                    if (isEventSaved)
                    {
                        await eventLogGrain.RollbackEventAsync(@event);
                    }
                }

                // Tell Orleans to deactivate grain after the current grian is completed.
                // In this way, any state is removed from the memory.
                base.DeactivateOnIdle();

                throw;
            }
        }
```

Event C is picked up by 2 grains, Grain D and Grain E. Grain D saves the state while Grain E makes an HTTP Call which POSTs some value. So with this logic, all grains need to be activated 3122 times, I should have 3122 saved states for Grain A, B, C and D, 3122 HTTP calls from Grain E, as well as 9366 entries in the event log (we save them all under one table).

This code shows how we subscribe to the stream:

```
protected override async Task BecomeConsumer()
        {
            IStreamProvider streamProvider = GetStreamProvider(StreamsConstants.AzureStreamProvider);
            IAsyncStream<EventC> stream = streamProvider.GetStream<GrainCEvent>(this.GetPrimaryKey(), nameof(EventC));

            var promises = new List<Task>();
            promises.Add(stream.SubscribeAsync(EventCHandler));
            await Task.WhenAll(promises);
        }
```

The numbers add up except the HTTP calls. The number, however, is haphazard and not always the same. During this whole process, I can see the following message, for Grain C (the grain for which it has 2 grains subscribed to its event).

```
[17:33:52 WRN] Exception during Grain method call of message: NewPlacement OneWay S10.0.75.1:11111:281723462*cli/2fe333bd@c798b2b4->S10.0.75.1:11111:281723462*grn/2262AE79/e6f679bd@307e2ba8 #171:
System.TimeoutException: Response did not arrive on time in 00:00:30 for message: NewPlacement Request S10.0.75.1:11111:281723462*grn/2262AE79/e6f679bd@307e2ba8->S10.0.75.1:11111:281723462*grn/2F2DBAA7/e6f679bd@582e2ab1 #16579: . Target History is: <S10.0.75.1:11111:281723462:*grn/2F2DBAA7/e6f679bd:@582e2ab1>.
```

I am seeing this message too:

```
[17:35:44 WRN] Response did not arrive on time in 00:00:30 for message: NewPlacement Request S10.0.75.1:11111:281723462*grn/2F2DBAA7/f586ea16@d23ea6b9->S10.0.75.1:11111:281723462*grn/CE1C7277/f586ea16@ab709c91 #61856: . Target History is: <S10.0.75.1:11111:281723462:*grn/CE1C7277/f586ea16:@ab709c91>. About to break its promise.
[17:35:44 INF] DeactivateActivationOnIdle: [Activation: S10.0.75.1:11111:281723462*grn/716E8E94/bf83f8d1+AzureStreamProvider_EventC@8384eab5 #GrainType=Orleans.Streams.PubSubRendezvousGrain Placement=RandomPlacement State=Deactivating] later when become idle.
[17:35:44 INF] DeactivateActivationOnIdle: [Activation: S10.0.75.1:11111:281723462*grn/2F2DBAA7/431e3197@fdd503a3 #GrainType=GrainC Placement=RandomPlacement State=Deactivating] later when become idle.
```

The rest of the message is just a stack trace from Grain C, up to the invocation of the [OneWay] method of Grain A.

After this process, some statistics show up in the console. Let me share some of them with you:
```
Grain.GrainA.Current=3122
Grain.GrainB.Current=3122
Grain.GrainC.Current=186
Grain.GrainD.Current=3122
Grain.GrainE.Current=2917
```

Grain C and Grain E do not make sense at all. Somehow, the messages are not being picked up on time and lost completely. This behaviour only appears when we launch the application without debugging. When we debug the application, everything works fine.

**Comment by nvella88** [comment]
I changed Grain to save state instead of making an HTTP call. The correct number of activations occurred (3122).

**Comment by jason-bragg** [comment]
What version of Orleans are you using?
Are grains using implicit or explicit subscriptions?

"Response did not arrive on time in 00:00:30 for message" indicates that the service is getting timeouts somewhere.  In code above, it looks like grains are deactivated on error, which would explain the deactivate on idle log messages and the disparity in grain counts.  In provided code I see no logging on errors.  You'll need better logging to identify where things are going wrong.

**Comment by nvella88** [comment]
We are using Implicit Subscription.
We made significant progress by doing a small change in the code. Previously we had this code:

```
// Grain E (The one that makes HTTP Calls)
public override async Task OnActivateAsync()
        {
            await base.OnActivateAsync();
			IStreamProvider streamProvider = GetStreamProvider(StreamsConstants.AzureStreamProvider);
            IAsyncStream<GrainCEvent> stream = streamProvider.GetStream<GrainCEvent>(this.GetPrimaryKey(), nameof(GrainCEvent));

            var promises = new List<Task>();
            promises.Add(stream.SubscribeAsync(GrainCEventHandler)); //GrainCEventHandler does an HTTP call
            await Task.WhenAll(promises);            
        }
```

This simple change fixed the issue on our local machine, meaning that al HTTP calls are being done. However, this still did not solve the issue when deployed on the server.
```
// Grain E (The one that makes HTTP Calls)
public override async Task OnActivateAsync()
        {
			IStreamProvider streamProvider = GetStreamProvider(StreamsConstants.AzureStreamProvider);
            IAsyncStream<GrainCEvent> stream = streamProvider.GetStream<GrainCEvent>(this.GetPrimaryKey(), nameof(GrainCEvent));

            var promises = new List<Task>();
            promises.Add(stream.SubscribeAsync(GrainCEventHandler)); //GrainCEventHandler does an HTTP call
            await Task.WhenAll(promises);            
            await base.OnActivateAsync(); //We put this here
        }
```

On our local machines, we are still seeing this error:
```
[08:23:11 WRN] Exception during Grain method call of message: NewPlacement OneWay S10.0.75.1:11111:281776789*cli/8b0594a9@654684b4->S10.0.75.1:11111:281776789*grn/2262AE79/943d3a9c@62e47f85 #2317:
System.TimeoutException: Response did not arrive on time in 00:00:30 for message: NewPlacement Request S10.0.75.1:11111:281776789*grn/2262AE79/943d3a9c@62e47f85->S10.0.75.1:11111:281776789*grn/2F2DBAA7/943d3a9c@657df691 #23256: . Target History is: <S10.0.75.1:11111:281776789:*grn/2F2DBAA7/943d3a9c:@657df691>.
```

Side Question: Do we need to call `await base.OnActivateAsync();` when doing Implicit Subscription?

**Comment by nvella88** [comment]
In Grain E, if I put a try, catch (the catch does not re-throw any exception) around the code making the HTTP Call I am getting statistics like these:

```
Grain.GrainA.Current=3122
Grain.GrainB.Current=3122
Grain.GrainC.Current=186 // Pushes Event
Grain.GrainD.Current=3122
Grain.GrainE.Current=3122 //Subscribes to event C and makes an HTTP call
```

I am logging inside the catch but nothing is logged.

**Comment by nvella88** [comment]
After more logging and trial and error, I found out that the HTTP Call was throwing this exception:
`[13:10:32 FTL] No connection could be made because the target machine actively refused it`
Question: I only found this exception because I wrapped the HTTP call around a try, catch block. Why was not this exception logged during execution? My logger is set to Information level.

I added transient fault handling, and although all HTTP calls are made, I am still getting this result on the Silo Client:

`Response did not arrive on time in 00:00:30 for message: NewPlacement Request S10.0.75.1:11111:281797566*grn/2262AE79/616a67bb@e95be79d->S10.0.75.1:11111:281797566*grn/2F2DBAA7/616a67bb@d9965da1 #23977: . Target History is: <S10.0.75.1:11111:281797566:*grn/2F2DBAA7/616a67bb:@d9965da1>.`

Occasionally I notice that I all grains activate, except one. It does not always happen though. Any idea why I am still receiving this error?

**Comment by nvella88** [comment]
I am using Simple Message Stream Provider. The above-mentioned solution does not apply when I put my laptop on battery, the loss of power all of sudden makes the whole setup not able to keep up.

**Comment by jason-bragg** [comment]
> On our local machines, we are still seeing this error: Timeout

Timeout exceptions indicate that a grain call is taking longer than 30 seconds.  This could be due to overloading the grain or the calls taking too long.  Do you know what call is timing out?  In that case it looks like this is happening on a new placement, with may indicated long running OnActivateAsync calls.  I suggest running the service with a smaller number of grain, to first ensure correctness, then all more load and optimized as issues are encountered.

> Side Question: Do we need to call await base.OnActivateAsync(); when doing Implicit Subscription?

Only if you're base class does something in it's OnActivateAsync.  Orleans Grain and Grain<T> do nothing in their OnActivateAsync, so the changes made to when/how that's called shouldn't have mattered at all.

> I am logging inside the catch but nothing is logged.

Is you SMS stream provider configured for FireAndForget delivery?

> Why was not this exception logged during execution?

This is application code, right?  Orleans logs quite a bit to help application developers understand what's happening in the cluster, but the application layer is still responsible for it's own monitoring, logging, and statistics.

**Comment by nvella88** [comment]
> Timeout exceptions indicate that a grain call is taking longer than 30 seconds. This could be due to overloading the grain or the calls taking too long. Do you know what call is timing out? In that case it looks like this is happening on a new placement, with may indicated long running OnActivateAsync calls. I suggest running the service with a smaller number of grain, to first ensure correctness, then all more load and optimized as issues are encountered.

The event handler of the stream, (which is called during OnActivateAsync) is doing an HTTP call. Sometimes this call fails, adding transient fault handling helps but it may take more than 30 seconds. Could this be it?

**Comment by nvella88** [comment]
> Timeout exceptions indicate that a grain call is taking longer than 30 seconds.

Can you extend this timeout?

**Comment by jason-bragg** [comment]
> Is it possible to extend this timeout?

Yes.  It's configurable.  See SiloMessagingOptions.ResponseTimeout

**Comment by skyflyer** [comment]
@nvella88,

I suggest you add an incoming grain call filter and try/catch there:

For instance:
```c#
using System;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Orleans;

public class ExceptionCallFilter : IIncomingGrainCallFilter
{
    private readonly ILogger<ExceptionCallFilter> _logger;

    public ExceptionCallFilter(ILogger<ExceptionCallFilter> logger)
    {
        _logger = logger;
    }

    public async Task Invoke(IIncomingGrainCallContext context)
    {
        try {
            await context.Invoke();
        } catch (Exception x) {
            _logger.LogError(x, "Exception while invoking grain type method {method} on {type}", context.InterfaceMethod.Name, context.Grain.GetType());
        }
    }
}
```

and then when configuring a silo, add `.AddIncomingGrainCallFilter<ExceptionCallFilter>()`. That would log the exceptions (if they happen) when the request times out.

Also, with SMS provider, if you're not using `FireAndForget`, then your calls are being awaited during the whole chain, which is not OK and not how it plays out in practice with other queue implementations (to the best of my knowledge).

**Comment by nvella88** [comment]
Thank you both. We will do more tests, even a revision of the approach if it has too. I will keep this thread updated.
