### ISSUE TITLE
AzureStorageClustering does not work with Azurite

### ISSUE THREAD

**Issue by rmja** [dotnet/orleans#5241]
I was trying out Azurite as the storage emulator as the version 5.8 of the official storage emulator has a huge bug (https://github.com/Azure/azure-storage-net/issues/801) where blobs cannot be written. Since I am relying on blob storage for non-orleans use, I had to move away from using the emulator since I was unable to find an installer for the previous 5.7 version of the emulator (https://github.com/Azure/azure-storage-net/issues/810#issuecomment-446123225)

However, my silo will not start using azurite. The OrleansSiloInstances table is created and populated with the SampleStore/VersionRow entry. The following is the output from the Azurite terminal:

![image](https://user-images.githubusercontent.com/2112306/49789609-b6ad5000-fd2c-11e8-9457-7fcd4e1811e8.png)

Storage emulator fiddler:
![image](https://user-images.githubusercontent.com/2112306/49792023-004c6980-fd32-11e8-99b8-36f9b33e9569.png)

Azurite fiddler:
![image](https://user-images.githubusercontent.com/2112306/49792051-135f3980-fd32-11e8-902a-d13031708323.png)

I know that this is not an Orleans bug, but maybe we could help the Azurite guys to reproduce what is going on...?

**Comment by sergeybykov** [comment]
>However, my silo will not start using azurite.

Is there something in the silo log that indicates what's going wrong?

**Comment by rmja** [comment]
Yes, basically it says that it is unable to connect:

![image](https://user-images.githubusercontent.com/2112306/49852946-e3716e00-fde5-11e8-94f7-8a5f6fc05546.png)

**Comment by sergeybykov** [comment]
How do you specify the connection string? Having glanced at https://github.com/Azure/Azurite#usage-with-azure-cross-platform-cli-20, looks like one needs to add the local endpoint to it explicitly.

**Comment by rmja** [comment]
The thing is that it works partially.  The table is in fact created, and
the schema version row is added.

ons. 12. dec. 2018 17.56 skrev Sergey Bykov <notifications@github.com>:

**Comment by sergeybykov** [comment]
Right at the top of https://github.com/azure/azurite they say: "A lightweight server clone of Azure Blob, Queue, and Table Storage that simulates **most of the commands supported by it** with minimal dependencies."

And then below at https://github.com/azure/azurite#table-storage---api-implementation-status:
>Entity Group Transaction (Batch Operation) [TODO]

Transactional updates are a requirement for the clustering provider. So I suspect that's the gap.

**Comment by rmja** [comment]
The storage emulator is now working again in version 5.9 that was just released (https://github.com/Azure/azure-storage-net/issues/810#issuecomment-446784146)

Azurite remains incompatible with Orleans, but I guess we can close now when there is a fix. We can maybe reopen later if we want to support Azurite (which is cross-platform).
