### ISSUE TITLE
MSBuild code generator cannot generate serializer for struct with array field

### ISSUE THREAD

**Issue by Liversage** [dotnet/orleans#5243]
I changed the code generator in my project to `Microsoft.Orleans.CodeGenerator.MSBuild` hoping to work around some code generation problems I had on my build server. Supposedly, the new code generator is better anyway.

However, it seems that it cannot generate a serializer for a value type containing an array of a "primitive" type. This is the gist of the exception that is thrown by the code generator:

> System.NotSupportedException: Field MyStruct.myArray in type MyStruct is not an INamedTypeSymbol and therefore is not supported. Type is Microsoft.CodeAnalysis.CSharp.Symbols.ArrayTypeSymbol+SZArray

This would be my value type:

```
public readonly struct MyStruct
{
    private readonly byte[] myArray;
}
```

As far as I can tell the exception is thrown in [SerializerGenerator.IsValueTypeFieldsShallowCopyable](https://github.com/dotnet/orleans/blob/008605e3717ccd5f7396c388090e8c7a6ea1a46c/src/Orleans.CodeGenerator/Generators/SerializerGenerator.cs#L633).

The issue seems to be that the new code generator will only create a serializer if the field can be shallow copied. However, an array of a type that can be shallow copied can also be shallow copied by copying the array. The old code generator didn't have this issue and I hope this can be fixed in the new code generator.

**Comment by ReubenBond** [comment]
I left this issue unanswered for an embarrassingly long time - I apologize, @Liversage.
I tried reproducing this but was unable. I've opened #6008 with a regression test just to be sure (the projects in the `test` directory are all built using the MSBuild codegen)
