### ISSUE TITLE
Connection Silos from Multiple Cloud services

### ISSUE THREAD

**Issue by clintonsweetnam** [dotnet/orleans#525]
We currently have our Orleans Silo and Client running within the same cloud service so we are just using the basic Azure Configuration using the AzureSilo and AzureClient. Everything is working very well.

We now want to start up another version of that cloud service and we want the silos from both the be in the same "Silo Cluster". Is it possible to continue using Azure Silo and AzureClient(They will both be using the same AzureTable storage) or do I have to instead use SiloHost and GrainClient to implement the the silo so that we can set the Deployment Id??

Thanks in advance!

**Comment by sergeybykov** [comment]
Yes, this should be possible, so long as you have direct TCP connectivity between the two services, e.g. via a vNet.

**Comment by clintonsweetnam** [comment]
Thanks for the quick response.

And if they were not able to share AzureTable storage. Would that require a switch to a SiloHost and a GrainClient?

**Comment by sergeybykov** [comment]
Why would they not share Azure Table storage? They have to use the same cluster membership table.

**Comment by clintonsweetnam** [comment]
Hi Sergey,

I guess the issue we are predicting is that even though both cloud services will be sharing the same Azure Storage Table, they will have different deployment Id's. Even if these deployment Id's don't match will it still allow the Silos on both Cloud Services to act as a Silo Cluster. In essence will deployments with different DeploymentId's share the same customer membership table?

Just a a reference we are using hte standard azure configurations for both our Silo's and Clients as detailed in the samples.

Thanks,

Clinton

**Comment by sergeybykov** [comment]
Deployment ID is the primary key in the membership table. So both deployments have to use the same deployment ID, in this case different from Azure Hosted Service deployment ID. So you'll need to use SiloHost and GrainClient directly, instead of the AzureSilo and AzureClient wrapper classes.

**Comment by clintonsweetnam** [comment]
Hi Sergey,

Ok we will look at changing our implementation. Thanks very much for your help!

Clinton

**Comment by gabikliot** [comment]
Hi @clintonsweetnam . Do you still have open questions on this issue? Can it be closed?

**Comment by clintonsweetnam** [comment]
Hey Gabriel

We implemented it by using the SiloHost and GrainClient directly with a self-generated deployment Id and using AzureTable as a backing store.

Appears to be be working very well!

Thanks for you help guys!

Clinton
