### ISSUE TITLE
Fix build warnings caused by new codegen in test tree 

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#5255]
The warning introduced in #5031 shows up in our build logs because some test state classes inherit from `Dictionary<,>`

**Comment by RamanBut-Husaim** [comment]
@ReubenBond Hello. Sorry for pinging with this. 

Maybe you could take a look?

Thanks.

**Comment by ReubenBond** [comment]
@RamanBut-Husaim for the new code generator, you cannot *inherit* from `Dictionary<K,V>` or another collections type. It's a shortcoming of how we generate serializers, but it's caused by the .NET 'ref-only' assemblies stripping out private fields.

Apologies for the slow reply

**Comment by RamanBut-Husaim** [comment]
@ReubenBond hello.

Ah, ok. So such cases should be refactored. For example, inline dictionary inside.

Thanks!

**Comment by ReubenBond** [comment]
Yes, precisely
