### ISSUE TITLE
P2P network?

### ISSUE THREAD

**Issue by antonwilc0x** [dotnet/orleans#5259]
I noticed in the adventure example that the host was also the client. This has me wondering: what is stopping you from axing the middle man altogether and making the client the host too? I.e. a P2P network?

**Comment by sergeybykov** [comment]
This was always possible - to host client and silo in the same process. We do that for testing and #3362 made it more efficient. The concern is usually about security, with most people wanted to physically separate their frontend nodes (web servers) from their silo nodes.
