### ISSUE TITLE
Question - Architecture - Processing a file

### ISSUE THREAD

**Issue by dealproc** [dotnet/orleans#5262]
I am working presently on parsing a zip file.  In that file has about 1000 +/- files that I need to seek 4 of them out and do some backend work to extract information about the contents of the file (and maybe need to extract a subsequent 4-5 files thereafter... undecided yet).

My current implementation is doing this via my web portal, and although it works, it does not seem ideal long-term.

What I think I want to do is to basically:
1. Create a worker node for this parsing
2. Teach the upload API to accept the file, drop it to Azure storage, then create an item in a queue and/or publish it via an Orleans stream
3. Have a subscriber on the Orleans stream and/or queue pick it up and do the work on the back-end, reporting back to the user that uploaded the file what the status is.

Think of doing an operation within the Azure portal today.

Are there any best practices available from the team as to how to properly do this within Orleans and/or has anyone done anything like this within Orleans?  If so, what were the gotchas, etc????

**Comment by sergeybykov** [comment]
Sounds to me like a basic workflow:
* Record the job request
* Perform step 1 of processing
…
* Perform step N of processing
* Notify about completion
* End the workflow

Can be implemented as a simple state machine grain that would persist data associated with the request and update it with the progress after every step. Registering a reminder at the very beginning will ensure that the workflow will continue/complete after any failure and even a complete shutdown/restart of the cluster.

**Comment by dealproc** [comment]
Can you permalink to an example of such a grain so that the pattern can be quickly digested @sergeybykov?

**Comment by dealproc** [comment]
Funny.  Thanks for that.  I think it is about what I expected it to be, but wanted to be sure.

**Comment by sergeybykov** [comment]
@dealproc Anything else here or this can be closed?
