### ISSUE TITLE
CPU leak in aspnetcore runtime 2.1

### ISSUE THREAD

**Issue by aprooks** [dotnet/orleans#5263]
We experienced a CPU leak like this 

![image](https://user-images.githubusercontent.com/1265082/50019754-1ed18f80-ffd4-11e8-94ca-66eb2766e1c3.png)

On this graph, the peak is on runtime ver. 2.1 and the right side after deployment to 2.0. Nothing else was changed and the load was the same.  

for a small solution which does health checks via HTTP client. (Grain + reminder + perform Http call). Hosted via docker on AWS ECS

Orleans versions tested 2.0, 2.1.0, 2.1.1. 2.1.2. Both separate and direct client. None of the versions affected behavior.

Leak observed only with microsoft/dotnet:2.1-aspnetcore-runtime. Both with enabled and disabled HttpClient implementation based on native sockets. 

The problem was not observed when deployed with runtimes 2.0 and 2.2

**Comment by ReubenBond** [comment]
Which version of .NET Core 2.1 was it, do you recall?

**Comment by aprooks** [comment]
Should be 2.1.6

But I'm not sure if it is worth investigating unless someone else stumbles upon this issue. There are could be a bug in the internal code which was affected only by runtime version.

**Comment by aprooks** [comment]
Sounds reasonable. Closing so it does not clutter
