### ISSUE TITLE
Client throws "Named type predicate is invalid: Type string cannot be resolved." for the custom implicit stream subscription attribute

### ISSUE THREAD

**Issue by alexeyzimarev** [dotnet/orleans#5274]
I have a solution with one Orleans cluster node and one client. Both reference the project that contain one grain interface `IUnitGrain` and also another project that contains POCO types that are used as parameters for the grain methods.

```csharp
    public interface IUnitGrain : IGrainWithStringKey
    {
        Task HandleHardwareEvent(IHardwareEvent @event);

        Task HandlePosition(Position position);

        Task HandleEtsEvent(TripCreatedInEts @event);
    }
```

However, the cluster node project also contains one more grain, which is not in any way exposed to the client, called `ITripGrain` and the implementation of that grain has a custom implicit stream subscription attribute `StartsWithStreamNamespacePredicate`. The implementation of the `IUnitGrain` has no relation to the `ITripGrain` or its implementation.

None of the shared projects contains any reference to this custom attribute, it is solely internal.

However, when the client tries to get a reference to the `IUnitGrain`, it throws an exception:

> Named type "Infrastructure.Orleans.StartsWithStreamNamespacePredicate" is invalid: Type string "Infrastructure.Orleans.StartsWithStreamNamespacePredicate" cannot be resolved.

I don't understand why the client even cares about the implementation details of the grain that hasn't been added to its application parts and not referenced anywhere inside the client project?

**Comment by alexeyzimarev** [comment]
In case I don't use this custom attribute and instead use the
```
[RegexImplicitStreamSubscription("/trip-.*/")] 
```

on the `TripGrain`, the client gets another exception when connecting to the cluster:

> System.Runtime.Serialization.SerializationException: Type 'System.Text.RegularExpressions.RegexReplacement' in Assembly 'System.Text.RegularExpressions, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable.

For me, it looks like the Orleans Streams are completely unusable with implicit subscription attributes if the client is not a part of the same executable.

**Comment by alexeyzimarev** [comment]
Seems like #5247 refers to the similar problem.

**Comment by ReubenBond** [comment]
@alexeyzimarev I added a comment to #5247

**Comment by alexeyzimarev** [comment]
@ReubenBond do you want to keep this open or the fix will be tracked in the referenced issue?

**Comment by ReubenBond** [comment]
@alexeyzimarev let's close this and track via #5247
