### ISSUE TITLE
Grain Persistence and polling

### ISSUE THREAD

**Issue by TulkasLaugh** [dotnet/orleans#5286]
I'm working on a project with a design where individual Grains would make Http calls to poll on web services. My code has it so the grain would do Task.Run(), to poll on the web service until it's finished. I'm trying to implement grain persistence and thinking through a scenario where a silo goes down while a grain is polling and I'm not sure how to ensure it will pick back up where it left off. 

Do you guys have a recommended way to do something like that?

**Comment by sergeybykov** [comment]
Why `Task.Run` and not regular asynchronous calls from within the grain cotext, e.g. from a timer callback?

For fault tolerance, in general, you likely want to persist the request and schedule a reminder (that will reactivate the grain if necessary) before returning success from the call that initiates polling.

**Comment by sergeybykov** [comment]
>So to apply what you're recommending for fault tolerance, do I persist the request, schedule a reminder so that if a silo goes down, the reminder will start the grain back up again?

Yes, I think you need the polling grain to doo all of that *before* responding to the caller that it started the polling job successfully.

**Comment by TulkasLaugh** [comment]
Cool, I followed your advice and got the reminders to work with grain persistence. However, I am noticing that Console.Write that I would rely on for local development are no longer working when code is being executed inside of a reminder. It won't affect staging, or production because we use a logger, but is there any explanation for why code being executed within a Reminder is not being displayed in console and is there any way to set it up so that it can?

**Comment by sergeybykov** [comment]
That's strange. Console should work. I don't believe we are interfering with it in any way. Could it be buffering? Have you tried `Console.WriteLine()`?
