### ISSUE TITLE
C# appearing in VB codegen

### ISSUE THREAD

**Issue by BenjaminGibbs** [dotnet/orleans#529]
I've been extending some of our project today and ran in to a codegen error, I've worked around it by adjusting the signature of my class, but thought I would share.

I have an object ```HistoryItemModel(of T)```, which doesn't have an empty constructor, only one which takes 3 params; this is used as a return time for a grain.

The error from the codegen is:

```vbnet
Dim result As Showcase.Core.Models.Cross.HistoryItemModel(Of T) = CType(System.Runtime.Serialization.FormatterServices.GetUninitializedObject(GetType(HistoryItemModel<T>)),Showcase.Core.Models.Cross.HistoryItemModel(Of T))
```

The ``` HistoryItemModel<T> ``` isn't valid, it is happening in ```HistoryItemModelSerialization``` generated class, in the ```DeepCopier``` and ```Deserializer``` functions.

I've had a look at the Orleans source, and I think I can pin it down to code generated by ```SerializationGenerator.cs``` line 238-->240 but I am not 100% sure which param is not VB formatted. - mind you I could be totally looking in the wrong place.

Any thoughts?

**Comment by sergeybykov** [comment]
Can you try if https://github.com/sergeybykov/orleans/tree/vb-codegen fixes the problem?

**Comment by BenjaminGibbs** [comment]
I will take a look and get back to you.

**Comment by sergeybykov** [comment]
This has been obviated by https://github.com/dotnet/orleans/pull/528.
