### ISSUE TITLE
The switch statement contains multiple cases with label value...

### ISSUE THREAD

**Issue by berdon** [dotnet/orleans#5295]
Grain interfaces with duplicate/hidden method definitions of a base interface cause invalid code to be generated.

Example:
```C#
public interface IBaseGrain : IGrainWithGuidKey
{
    Task Foo();
}

public interface IFooGrain : IBaseGrain
{
    Task Foo();
}
```

Ends up generating:

```C#
switch (methodId)
{
    case (int)0x6D596ED9:
        return "Foo";
    // ...
    case (int)0x6D596ED9:
        return "Foo";
    // ...
}
```

Normal VS setup does cause a warning on the hidden method but that doesn't break compilation. The generated code does.

I'll see if I can get around to a PR. Not sure I'll have time though. :( Likely either deduping in GrainInterfaceCommon.GenerateGrainInterfaceAndMethodSwitch *or*, perhaps more properly, accounting for hidden methods during ID generation in OrleansLegacyCompat.GetMethodId...

**Comment by ReubenBond** [comment]
MethodId computation doesn't currently take into account the target interface.

One workaround is to add an explicit `[MethodId(x)]` to either method.

We should fix the duplicate switch case anyway - if you can open a PR, that would be most appreciated.

**Comment by berdon** [comment]
Thanks @ReubenBond and co for all your guys' hard work. Sorry I never got around to a PR :(

**Comment by ReubenBond** [comment]
No worries at all, @berdon :)
