### ISSUE TITLE
ASP.NET Core Identity store implementation

### ISSUE THREAD

**Issue by idizh** [dotnet/orleans#5309]
What do you think about ASP.NET Core Identity and Orleans, should it be implemented on Front-end project or in Orleans Grains, I mean store Users, roles, tenants and so on? In case if it is decoupled from Orleans Grains, how can I reference Orders(Grain) Entity to Users and Tenants from Identity store? Or it would be better to have something like this Microsoft.AspNetCore.Identity.EntityframeworkCore but
Microsoft.AspNetCore.Identity.OrleansStore?

**Comment by ReubenBond** [comment]
In the past I have implemented ASP.NET Identity using IdentityServer & Orleans grains for Users, etc, so it is doable. I'm not sure how things have changed in ASP.NET Identity. I'm not sure I understand your question about decoupling.

**Comment by idizh** [comment]
Thx ReubenBond.
I meant if I'll implement storage in Orleans ecosystem everything is fine. But in case if identity will be implemented in another service, and another DB, how can I reference users and tenants with Orleans grains, just store userId and tenantId in models on Orleans side?

**Comment by SebastianStehle** [comment]
The question is: How would you implement the different queries?

**Comment by KarenTazayan** [comment]
I'm working on similar idea to integrate ASP.NET Core, IdS4 and Orleans 2.0. I uploaded it on GitHub last weak and have some plans to develop and publish via NuGet.

**Comment by KarenTazayan** [comment]
This is the [reference](https://github.com/Async-Hub/Orleans.Security).

**Comment by ReubenBond** [comment]
Closing - @KarenTazayan provided an implementation here https://github.com/Async-Hub/Orleans.Security
