### ISSUE TITLE
Grain State Validation

### ISSUE THREAD

**Issue by philreindl** [dotnet/orleans#531]
What is the recommended pattern for validating grain state?  What I'd like to be able to do is decorate the state interfaces with DataAnnotations such as [Required] or [MaxLength(16)] and ensure they are checked before state is persisted.  My thought was to extend the orleans code generation functionality to add in these checks.  From looking at the issue list here though, it appears the generated code may be going away soon.  If there's an established pattern for this, I'm definitely open to suggestions. 

Thanks
Phil

**Comment by sergeybykov** [comment]
Yes, the plan is to move away from grain state interfaces and generation of grain state classes soon. https://github.com/dotnet/orleans/pull/476 enabled specifying classes as type arguments to Grain<T>. If the validation functionality is generis enough, one could define a base class for a bunch of state classes. Or we could even include one into the codebase.

**Comment by philreindl** [comment]
The ability to create a base class for all of the state objects will make this much easier to achieve.  

Is it fair to say there is no established "best practice" for grain state validation at this time?

Thanks

**Comment by sergeybykov** [comment]
Yes, it is fair. An opportunity to set a precedent. :-)

**Comment by philreindl** [comment]
Sounds good, when the next version without code generation is out I'll let you know what I come up with.

Thanks
