### ISSUE TITLE
Need design advice regarding version selection strategy canary testing grains

### ISSUE THREAD

**Issue by JanEggers** [dotnet/orleans#5315]
Hi there im working on an IOT project for a production facility and would like to use orleans

One requirement is that I need to be able to roll out updates for only one / some of the devices.

At first I thought I simply create one grain for each device. But im not sure if this will work.

I read the docs but for me it is not clear if / how I can achive what I want. http://dotnet.github.io/orleans/Documentation/deployment/grain_versioning/version_selector_strategy.html

Lets say I have device A and B both running Grain Version 1. And I want to deploy a new version only for Device A.

From what I understand the version is only chosen for new activations. So if an activation exists with V1 it will not be created in V2.

I think I can overcome this with a programmatic deactivation after deploying the update to one of the cluster nodes and then activating the grain again.

The other issue is that I need some custom version selection strategy so the cluster knows that it should create A as V2 and B as V1. 

Is this possible at all?

One thing I found is IPlacementDirector would that be the correct place to implement the desired behavior?

**Comment by JanEggers** [comment]
Just forgot the other Idea i have is creating a seperate cluster for each device. but id rather would like to avoid that as it increases deployment complexity

**Comment by JanEggers** [comment]
I found IVersionSelector but that interface is lacking some context I need to determine what version is want to use.

**Comment by sergeybykov** [comment]
`IVersionSelector` operates on the basis of requested and available versions. It does not receive identity of the grain the is being placed. So it cannot pick a version based on the grain identity. Maybe we should consider that. I wonder what @benjaminpetit thinks.

At the same time, it's not 100% clear to me that that's what you need here. When you say:
>Lets say I have device A and B both running Grain Version 1. And I want to deploy a new version only for Device A.

for how long do you want this to be that way? The versioning functionality is meant for in-place upgrade where one might want to test a new version on a subset of the grain population before rolling it all grains of the type. The goal is to upgrade everything to the new version as soon as that is deemed (by the devops person) safe. If you would like to run specific different grains as different versions for an extended period of time, then a different approach might be more suitable.

You can deploy two (or more) grain classes that implement the same set of grain interfaces and use those classes as different versions. That way the client (frontend) could pick a desired grain class for each individual grain ID. This approach is not without challenges (for example, how to consistently tell all frontends to use a new version for what grains). But it does allow multiple versions (implementations) of the same logic coexist and be used in parallel for an arbitrary long period of time.

Like I said, it's not 100% clear what you actually need. But I thought I'd add this option into the mix.

**Comment by JanEggers** [comment]
>  The versioning functionality is meant for in-place upgrade where one might want to test a new version on a subset of the grain population before rolling it all grains of the type.

that is exactly the usecase I need covered. 

The thing is that im controlling physical devices so I want to have control over which devices use the new version.

**Comment by sergeybykov** [comment]
>that is exactly the usecase I need covered.

If you want to use versioning for that, then you'd have to start by putting `[Version(N+1)]` attribute on the grain interface in the new version of the grain interface assembly. If you set the [version strategy selector](http://dotnet.github.io/orleans/Documentation/deployment/grain_versioning/version_selector_strategy.html) to `MinimumVersion`, then calls made via the N+1 version of the grain interface assembly will be routed to an N+1 version of the grain (deactivating version N before that if needed). So, by choosing to make calls from the frontends via version N or N+1 of the grain interface assembly for specific grain IDs, you can control with which version each grain will get activated.

It is a bit tricky how to use two different versions of the same assembly, but that should be solvable via assembly versioning, app domains, or separate frontends.

>How can I control which grain class gets picked for wich identity?

If you have more than one grain class implementing the same grain interface, you can request a specific one by passing the optional last argument to `GetGrain()`, which is a fully qualified name of the grain class you need or a prefix of it. For example, if you have two grain classes define as follows:
```csharp
namespace MyCompany.IoT.SimpleDevices
{
  public class SimpleDeviceGrain : IDevice
  {
  }
}

namespace MyCompany.IoT.AdvancedDevices
{
  public class AdvancedDeviceGrain : IDevice
  {
  }
}
```

you call select the desired grain class by doing one of the following calls
```csharp
var g1 = client.GetGrain<IDevice>(id, "MyCompany.IoT.SimpleDevices.SimpleDeviceGrain");
var g2 = client.GetGrain<IDevice>(id, "MyCompany.IoT.AdvancedDevices.AdvancedDeviceGrain");
var g3 = client.GetGrain<IDevice>(id, "MyCompany.IoT.SimpleDevices");
var g4 = client.GetGrain<IDevice>(id, "MyCompany.IoT.AdvancedDevices");
```

**Comment by JanEggers** [comment]
thx I will give that a try and let you know if it worked out

**Comment by JanEggers** [comment]
related #5203

**Comment by benjaminpetit** [comment]
A bit late to the party, but you can set some property in the [`RequestContext`](http://dotnet.github.io/orleans/Documentation/grains/request_context.html). It will be passed in the `IPlacementContext.RequestContextData` in the `IPlacementDirector.OnAddActivation`
