### ISSUE TITLE
Orleans client takes a long time to close()

### ISSUE THREAD

**Issue by TulkasLaugh** [dotnet/orleans#5317]
Hi, I designed a web API endpoint to take in work and distribute that work to various grains. During the API call, I have it instantiating a new client to connect to the cluster and then close at the end when it's finished. However, it's causing significant lag where the client could take upwards to 30 seconds to close. Do you guys have a recommended way to manage orleans client or simply make the API call not wait for the client to close() before responding back to the consumer? Thanks.

**Comment by ReubenBond** [comment]
@TulkasLaugh the Orleans client is designed to be instantiated and connected once, when your application starts up and closed only when your application terminates. It is designed to be accessed from multiple threads concurrency (i.e, you only need a single instance and you do not need to place locks around your usages).

I hope that helps.

Regarding the time taken to close it, it seems are you running inside of classic ASP.NET (not ASP.NET Core)? If so, the issue could be with the ASP.NET SynchronizationContext. In that case you would have to close the client inside of a `Task.Run` call. Just to be clear, though, I strongly recommend sharing a single client among all callers and instantiating and connecting that client on application startup (not per-request)

**Comment by TulkasLaugh** [comment]
Ah, I see. I'll have to change the architecture but that make sense.
