### ISSUE TITLE
Some questions about placements / discovery / grain types

### ISSUE THREAD

**Issue by jrouaix** [dotnet/orleans#5320]
Hello there,

We are about to run a silo with multiple grain types, let's say IA, IB, IC ... 10 to 15 of them.

They are really distinct domains but we'd like to embed all this little world in the same cluster
- to avoid having to configure multiple IClusterClient and manage them
- and to have aggregated silos statistics all in one on the dashboard.

Those grain are hosted in distinct applications, runned in a K8s cluster, let's say 3 to 10 replica for each grain type (this way we have the ability to scale each part of the system independendly).

I was a little surprise to see that if I entirely drop a service let's say IZ (it's representing a good 1/3 part of the all system, so it's 1/3 silos that are down on the same time) all the clients of the system, who are actually never calling Z grains are starting to raise exceptions (mostly TimeOut). Until the cluster is stable again.

My guess is that in fact all silos are responsible for the placement/discovery of any grain of the cluster, so the loss of any silo will impact randomly any client in the system depending on the partitions responsiblity ...

Would you say it's an expected behavior ? something that I could avoid somehow ? Is there something I could have greatly missunderstood ?

**Comment by jrouaix** [comment]
> Could you clarify what you mean by "drop a service". Does that mean that you abruptly kill a set of silos in the cluster?

Yes sir ! (helm delete on Kubernetes)

> I may have misunderstood your setup, but if you have distinct sets of grain classes (applications) that don't interact with each other, you could look at deploying them as [heterogenous silos](https://dotnet.github.io/orleans/Documentation/clusters_and_clients/heterogeneous_silos.html) in the same cluster.

Yep, did it actually.

> Clients are the other part of the equation. By default, each client eventually connects to all silos (client gateway endpoints) in the cluster. I suspect that might be the reason you are seeing errors on seemingly unrelated clients - they are likely sending requests through the silos (gateways) they you presumably killed. You can always initialize a client with a fixed set of silos/gateways to connect to. But that brings the burden of knowing which silo addresses to pass to which client and handing of cluster changes to the application level, and most people don't want to deal with that complexity.

I could init the client using the adresses provided by a DNS lookup on the kubernetes service on the deployement, but it won't resist a rolling upgrade of the pods. So is there a way to update those client gateways while running ?

Also I have to say, the IClusterClient instance used was not initiated by myself here but was the one passed IoC to a GrainService running on each Silo, and targeting only Grain types availables on the same Silo (and other same silo instances). So i'll have to override the default IClusterClient right ?

**Comment by sergeybykov** [comment]
>So is there a way to update those client gateways while running ?

You can always close the current client and initialize a new one instead with a different configuration. Although it's obviously no fun to get into managing the infrastructure concerns that the Orleans runtime is supposed to abstract away for you.

>Also I have to say, the IClusterClient instance used was not initiated by myself here but was the one passed IoC to a GrainService running on each Silo, and targeting only Grain types availables on the same Silo (and other same silo instances). So i'll have to override the default IClusterClient right ?

`IClusterClient` within a silo always has latest cluster state information (after failed/killed nodes are declared dead, of course). So it should automatically route requests correctly after cluster reconfiguration completes. Is that not what you are seeing?

**Comment by jrouaix** [comment]
By the way, I wonder if it could be possible to upgrade Orleans and enhance this experience:

If I got it right, the client is today unaware of which silo is providing which grain type. Only it has a knowledge of which grain types are provided by the cluster in global. And the placement of grains are dicided by silo that might not provide the grain type => there is only one big hash ringh for all grain types.

How much would it take to :
- have one hash/placement ring per grain type, shared by only silos that are actually capable of instantiate this grain.
- get the client aware of those multiple "placement quorums" so it can call the a silo actually close concerned about the call it's about to make.

Possible probably I don't  have the full picture here ...

Thank you @sergeybykov for all the responses already provided, I think we'll be able to continue from here \o/

**Comment by sergeybykov** [comment]
>How much would it take to :
>* have one hash/placement ring per grain type, shared by only silos that are actually capable of instantiate this grain.
>* get the client aware of those multiple "placement quorums" so it can call the a silo actually close concerned about the call it's about to make.

If we did that, how would grains of different types talk to each other (across rings)?

**Comment by jrouaix** [comment]
Like clients, they would how which silo to contact in order to get the placement ?

**Comment by sergeybykov** [comment]
That would break the programming model of grains freely talking to each other. Also, that would make it indistinguishable from running separate clusters for different grain types, wouldn't it?

**Comment by jrouaix** [comment]
Well, they could still talk freely to each others, asuming as the clients each silo is aware of all rings even if it doesn't participate on each.

But ok, I'm sure I have a naive sight of the problem as i'm a noob here and you are core maintainer. I assume I can trust your word.

Thanks !
