### ISSUE TITLE
SimpleMessageStream performance seems not good enough

### ISSUE THREAD

**Issue by Salty-Sailor** [dotnet/orleans#5326]
According to the [Orleans Streams Documention](https://dotnet.github.io/orleans/Documentation/streaming/index.html), I try to write a chat demo which uses the SimpleMessageStream. I just want to simulate some simple usecases in a chat system such as one-to-one chat. 

The demo looks like:
1. A silo cluster(more than 2 silo servers )
2. Several clients, each one simulates hundreds of users(in fact it's a gateway between the silo server and the user's devices. Because Orleans doesn't want to directly exposed the server address to the user, right?)  
3. Each user has a unique ID, and subscribes a stream which is based on his ID.So other users can publish a message to a user's stream if they know his ID, and the user will receive it because he subscribes himself.

I am concerned about the latency in the chat system, so I divide the users into two group(A and B). In group A, each user will cyclic(now it is 5 second) send a message with a local unix timestamp to several(now it is 10) users in group B. In group B, when a user receive a message from group A, it would send the same message(the unix timestamp not change) back to the user in group A. When the user in group A receive the response message, he could use the local unix timestamp to calculate the latency.

the client side's code looks like that:
```C#

// consumer class to subscribe a stream
public class ClientConsumer : IAsyncObserver<Ping>
{
    public Action<Ping> OnNextCallBack;

    public Task OnCompletedAsync()
    {
        Console.WriteLine("ClientConsumer Complete");
        return Task.CompletedTask;
    }

    public Task OnErrorAsync(Exception ex)
    {
        Console.WriteLine($"ClientConsumer Error:{ex}");
        return Task.CompletedTask;
    }

    public Task OnNextAsync(Ping item, StreamSequenceToken token = null)
    {
        OnNextCallBack?.Invoke(item);
        return Task.CompletedTask;
    }
}

public class UserClient
{
    public long selfId;
    private ClientConsumer selfStreamConsumer;
    private Guid selfGuid;

    ...

    public async Task InitAsSender()
    {
        var selfStream = streamProvider.GetStream<Ping>(selfGuid, $"PrivateStream_{selfPlayerId}");

        selfStreamConsumer.OnNextCallBack = msg =>
        {
            //caculate the latency and record it
        };
        await selfStream.SubscribeAsync(selfStreamConsumer);
    }

    public async Task InitAsReceiver()
    {
        var selfStream = streamProvider.GetStream<Ping>(selfGuid, $"PrivateStream_{selfPlayerId}");

        selfStreamConsumer.OnNextCallBack = msg =>
        {
            //get the sender's stream and send back
        };
        await selfStream.SubscribeAsync(selfStreamConsumer);
    }
}
```

I use the ConsulCluster, deploy 2 silo servers and simulate 12000 users to chat. Here is the test result:
```
Unit (ms = milliseconds)
SimpleMessageStream
Max:1134 ms
Mid:137 ms
Min:1 ms
Avg:152 ms

distribution:
99.9% < 1066 ms
99.0% < 860 ms
95.0% < 243 ms
90.0% < 163 ms
```
In order to compare, I use a message queue([NATS](https://github.com/nats-io/gnatsd), only a single point, no cluster) to simulate the same case. The result is much more better.
```
NATS
Max:218 ms
Mid:37 ms
Min:1 ms
Avg:56 ms

distribution:
99.9% < 168 ms
99.0% < 161 ms
95.0% < 142 ms
90.0% < 127 ms
``` 

The server/client machine's all use CentOS 7, and their cpu(8 cores) usage doesn't reach 100%(in 
 fact the server's usage is only about 40% and the bandwidth is enough. 

Although the average latency seems good, but there is 5% latency more than 240 ms and 1%  more than 860 ms. Compare to the NATS's result, it is a little bit unacceptable :(

PS:I guess some off-cpu analysis work will be down. I am trying to use bcc tools to do some analysis, but have met some problems about the dotnet core symbols.

**Comment by sergeybykov** [comment]
You mentioned that you are testing with 2 silos. How many clients? Are they running on a separate set of machines?

In general, this is a corner case setup - you are testing client-to-client streaming, which is supported but is not the main focus of Orleans. You are supposed to get parallelism by executing requests on a large enough number of grain in the cluster. With the client-only setup you are only exercising the client gateway subsystem. Its performance is dependent on the number of connected clients. Hence, the first question.

**Comment by sergeybykov** [comment]
>In my case, I simulate 12000 clients which runs on 3 linux machines.

Do you mean 3 Orleans clients connected to the cluster that publish subscribe on behalf of 12000 users/streams?

If that's the case, the bottleneck might be the topology. Each client connection to Client Gateway uses a single thread in the silo. So with 2 silos and 3 clients you end up with 6 threads doing most of the work across the 2 silos. I'd suggest to try increasing the number of client machines from 3 to, say, 10, and simulate the same 12000 users/streams.

For a comparison, you can try using direct client (#3362) instead. That would eliminate the Client Gateway stage. But you'll need to either co-host client in the same process or expose an http endpoint for remote clients to invoke.

**Comment by Salty-Sailor** [comment]
```
Do you mean 3 Orleans clients connected to the cluster that publish subscribe on behalf of 12000 users/streams?
```
Yes,and I will try to increase the Orleans Clients

**Comment by Salty-Sailor** [comment]
With the number of Orleans Clients increase, the performance dose improve, but the result is still not as good as NATS in my use cases. Since I just need some kind of simple message notification mechanism and don't need to use it within a grain, so I think a message queue is enough for me :) 

Close this issue.
