### ISSUE TITLE
Access Grain from Controller in Orleans 2.0

### ISSUE THREAD

**Issue by shaneol** [dotnet/orleans#5327]
Hi. I'm migrating an MVC project from Orleans 1.5.6 to Orleans 2.0. Previously, I would have accessed a Grain from a Controller by doing something like this:

`var player = GrainClient.GrainFactory.GetGrain<IPlayerGrain>("Bob");`

How can I do this in Orleans 2.0?

I've tried creating the Orleans Client itself as part of a Startup.cs class, and injecting that as part of a ServiceCollection:

```
var siloConfiguration = new ClusterConfiguration();
siloConfiguration.UseStartupType<Silo.DI.Startup>();

this.builder = new SiloHostBuilder()
                .UseConfiguration(siloConfiguration)
                .Etc
                .Etc
```

But the Startup class seems to be ignore when the Silo starts up. Has Startup class implementation changed in 2.0?

I've also tried injecting the GrainFactory as a dependency in the SiloHostBuilder like this:

`.ConfigureServices(services => services.AddSingleton<IGrainFactory>());`

But there is no implementation type for GrainFactory that I can access.

Am I missing something obvious here? Feels like there should be a straightforward way to access a Grain from a Controller.

**Comment by sergeybykov** [comment]
Have you found the [migration doc](http://dotnet.github.io/orleans/Documentation/resources/Migration/Migration1.5.html#configuring-and-connecting-a-client-using-the-new-clientbuilder-api-and-legacy-clientconfiguration-object) ?

**Comment by shaneol** [comment]
Yes thanks, I followed the [Azure Cloud Services doc](http://dotnet.github.io/orleans/Documentation/resources/Migration/MigrationAzure2.0.html) to get the client and silos to start up, so no problems there.

My issue is to do with accessing Grains. In Orleans 1.5 I can do this:

`var player = GrainClient.GrainFactory.GetGrain<IPlayerGrain>("Bob");`

I want to know how to accomplish the same thing in Orleans 2.0. Dependency injection seems to be the solution, but it's not clear from the docs what exactly I need to inject, or how?

**Comment by sergeybykov** [comment]
Oh, I see. You simply call `GetGrain<>()` on the `IGrainClient` after you build and connect it. See an example in the [Hello World sample](https://github.com/dotnet/orleans/blob/master/Samples/2.0/HelloWorld/src/OrleansClient/Program.cs#L83).

**Comment by shaneol** [comment]
I can't access the client directly from the controller though?

Maybe I'm not explaining it very well. My issue is similar to this: https://github.com/dotnet/orleans/issues/681

The trick/hack mentioned there doesn't seem to work any more, I guess because the GrainFactory is protected now, which is also stopping me from passing it as a dependency.

**Comment by sergeybykov** [comment]
#681 is very old. 
>I can't access the client directly from the controller though?

Why? So long as a cluster client is [built and connected](https://github.com/dotnet/orleans/blob/master/Samples/2.0/HelloWorld/src/OrleansClient/Program.cs#L60), you can use it obtain grain references (and making grain calls through them) from pretty much any context.

**Comment by shaneol** [comment]
Thanks for the help. I managed to work this one out eventually. Turns out I wasn't injecting the Grains correctly in the SiloHostBuilder.

**Comment by wuzhenda** [comment]
it seems have to got a client instance first. but  how to call gains in gains? in the sample  gps tracker DeviceGrain call the PushNotifierGrain.
`public async Task ProcessMessage(DeviceMessage message)
        {
            if (null == this.LastMessage || this.LastMessage.Latitude != message.Latitude || this.LastMessage.Longitude != message.Longitude)
            {
                // only sent a notification if the position has changed
                var notifier = GrainFactory.GetGrain<IPushNotifierGrain>(0);
                var speed = GetSpeed(this.LastMessage, message);

                // record the last message
                this.LastMessage = message;

                // forward the message to the notifier grain
                var velocityMessage = new VelocityMessage(message, speed);
                await notifier.SendMessage(velocityMessage);
            }
            else
            {
                // the position has not changed, just record the last message
                this.LastMessage = message;
            }
        }`

**Comment by wuzhenda** [comment]
OK,I got it by this issus.
[https://github.com/dotnet/orleans/issues/4523#issuecomment-385072170](url)
