### ISSUE TITLE
Orleans on OpenShift

### ISSUE THREAD

**Issue by iamdmitrij** [dotnet/orleans#5329]
We are trying to launch _Orleans 2.2_ on [OpenShift](https://www.openshift.com/) platform.
However, we do have one important network limitation. We are only allowed to communicate between Orleans silos (Docker containers) through a single gateway address. Our security limitations we cannot allow direct TCP "silo-to-silo" communication. 
If I try to initialize `EndpointOptions.SiloListeningEndpoint = new IPEndPoint(..., SiloPort);`  with our gateway address and allowed port, Orleans cannot let me launch a second silo on the same IP address. It just deactivates old silo and starts up a new one.
Are there any ways to circumvent that? Or using _Orleans_ on our current infrastructure is not the way to be?

**Comment by sergeybykov** [comment]
Can you use different TCP ports for silos? There's no way to run multiple silos with the same IP/port combination, what I think is true for any other application.
