### ISSUE TITLE
Every call to the grain sends a packet over the network for a request? 

### ISSUE THREAD

**Issue by guopenglun** [dotnet/orleans#5330]
Is there a way to get the requested data directly to silo, because each time the requested parameter is a complex object, it will take some time to make a memory copy and then send it over the network. Assuming my program is only running on one server, the above operations will waste a lot of performance.
Thank you for reading。

**Comment by sergeybykov** [comment]
If a call to a grain is made within the same silo where that grain is activated, no data is sent over the network, only memory copy of the arguments is performed. Memory copy can be eliminated by wrapping argument type with `Immutable<>`. However, in that case the code must not mutate the arguments after making a call.

**Comment by guopenglun** [comment]
Thank you for your reply, very helpful :)
