### ISSUE TITLE
Is it possible to connect other virtual actor systems in Orleans？

### ISSUE THREAD

**Issue by venyowong** [dotnet/orleans#5335]
Hi.

Is it possible to connect other virtual actor systems in Orleans? Like [orbit](https://github.com/orbit/orbit)

I think there may be tasks that need to be implemented in other languages, so maybe the communication of two different virutal actor systems will become a difficult problem to solve.

**Comment by sergeybykov** [comment]
Two different systems like Orleans and Orbit, even though they are conceptually similar, cannot talk to each other directly or form a shared cluster. However, there's always a way make calls from one to another, presumably over HTTP, just like in case of any other external service.

**Comment by venyowong** [comment]
Thanks for your reply. Maybe HTTP is the easiest way.
