### ISSUE TITLE
Receiving Orleans.Storage.InconsistentState Exception while using Streams and Reminders

### ISSUE THREAD

**Issue by TulkasLaugh** [dotnet/orleans#5346]
Hi, I recently added Reminders to my project to add fault tolerance. After adding it though and doing some stress testing with increasing load, I see errors popping up such as 

"Error from storage provider AdoNetGrainStorage.Orleans.Streams.PubSubRendezvousGrain during WriteState" 

and 

"Failed to register a stream producer."

I've noted that possibly this issue https://github.com/dotnet/orleans/issues/2565 may have been related. However, I'm using Reminders and not timers. Do you guys have any thoughts on this?

**Comment by sergeybykov** [comment]
`PubSubRendezvousGrain` definitely has nothing to do with reminders. It is key component in the pub-sub part of the streaming feature. It sounds like it is failing to write its state to the database. So seems unrelated to reminders.

**Comment by TulkasLaugh** [comment]
So as an update I found the issue. I implemented Reminders along with Grain persistence and the issue I'm facing involves doing base.WriteStateAsync() while receiving payload from Streams.

I have a ThrottlingGrain that holds in its state a Dictionary<string, currentRunningWork>, let's call it WorkingTable. There are multiple working grains doing stuff and when they finish, they send their completion status to a stream that the ThrottlingGrain is subscribed to. The ThrottlingGrain receives notification that a working grain is finished and updates the WorkingTable and then does base.WriteStateAsync(). I'm running into problems when the stream of notification has multiple finished work and the ThrottlingGrain would try to service them simultaneously to update its WorkingTable and when it tries to do base.WriteStateAsync() it would get InconsistentVersionException.

Do you have recommendations for when I need to base.WriteStateAsync() from Stream events but want the events from the stream to be worked one at a time due to wanting to avoid InconsistentVersionException. Adding to the challenge is that the grain is listening to multiple Streams as well.

**Comment by sergeybykov** [comment]
Is ThrottlingGrain reentrant?

**Comment by TulkasLaugh** [comment]
No, there's none of the things listed in the reentrancy documentation (https://dotnet.github.io/orleans/Documentation/grains/reentrancy.html).

**Comment by sergeybykov** [comment]
Are you awaiting the call to `base.WriteStateAsync()` in the notification handler?
