### ISSUE TITLE
Persistent Grain super slow after having more than 5 active

### ISSUE THREAD

**Issue by TulkasLaugh** [dotnet/orleans#5351]
I recently converted all my grains to be persistent grains that hold grain state. After starting to do load testing however, I'm noticing that beyond a threshold of 5 grains being active (single silo), it takes a long long time for me to get another grain and have it kick off to doing work. Does anyone have any thoughts as to why this would happen?

Here is the workflow.

POST to web api to create a factory (FactoryGrain)
POST to web api a bunch of orders to be worked on by the factory.

Factory spawns WorkerGrains to work on each order and then report back when they finish.

If I have 2 factories with 3 worker each, another POST to create a factory times out with more than 30 second response time. 

During POST Factory, I set up a FactoryGrain, set an instance int variable and have it subscribe it to 2 streams. When it's timing out, it hangs at setting the instance variable.

**Comment by sergeybykov** [comment]
Is it possible that the worker grains block grain threads (by using blocking IO or locks) and stall all progress? Anything in the logs?

**Comment by TulkasLaugh** [comment]
So, to add on extra info, we found that the GetAllSubscriptionHandles() that happens in grain activation for FactoryGrain is the part taking a long time. Especially right after previously creating a factory with a lot of orders. The worker grain doesn't seem to be blocking the grain threads.

My factory grain is set up to subscribe to 2 streams. Here is a sample code for my OnActivateAsync() for my FactoryGrain.

    var queueStreamProvider = this.GetStreamProvider("QueueStream");
    var unitStreamProvider = this.GetStreamProvider("CompletionStream");
    
    var queueStream = queueStreamProvider.GetStream<List<Order>>(this.GetPrimaryKey(), "ORDER_QUEUE");
    var unitCompletionStream = unitStreamProvider.GetStream<Order>(this.GetPrimaryKey(), "ORDER_COMPLETION");
    
    var queueSubscriptionHandles = await queueStream.GetAllSubscriptionHandles();
    var unitCompletionSubscriptionHandles = await unitCompletionStream.GetAllSubscriptionHandles();
    
    await this.ResumeQueueSubscriptions(queueSubscriptionHandles);
    await this.ResumeUnitCompletionSubscriptions(unitCompletionSubscriptionHandles);
    
    await base.OnActivateAsync();

**Comment by sergeybykov** [comment]
I'm not sure I understand. Even if a FactoryGrain is slow to activate due to slow a PubSub operation, that shouldn't interfere with other FactoryGrains or WorkerGrains activating or executing in parallel, so long as all IO operations are asynchronous.

What are you using for PubSub storage? Do you see any warnings/errors in the log?
