### ISSUE TITLE
OMG DDS vs Orleans

### ISSUE THREAD

**Issue by AllamSudhakara** [dotnet/orleans#5367]

**Comment by AllamSudhakara** [comment]
What are the comparisons between pub/sub middle ware architectures compared to Orleans such as OMG DDS Or any other broker frame works? I got involved in middle ware and came across Orleans platform and wondering how closely they match by funcitonality

**Comment by sergeybykov** [comment]
I personally haven't heard of OMG DDS before. So I don't have a comparison. Can you formulate the comparison or at least the key questions answers to which would be the differentiators?
