### ISSUE TITLE
Firewall: Silo nodes do not allow incoming TCP connections. Allow inter-Silo communication via a proxy.

### ISSUE THREAD

**Issue by tedvanderveen** [dotnet/orleans#5368]
Silo node communication depends on **incoming** TCP connections. Sometimes this is not possible due to firewalls or other constraints. In these situations it would be beneficial when Silo nodes on startup initiate a bi-directional socket to a proxy via which inter-Silo communication is routed.

**Comment by tedvanderveen** [comment]
This can enable scenarios described in #4156

**Comment by tedvanderveen** [comment]
Potential implementation can be based on Redis pub/sub
https://redis.io/topics/pubsub

**Comment by tedvanderveen** [comment]
Hi @ReubenBond following up on our conversation via Twitter, and after taking a closer look at the default implementation, I guess the key area to look at are the (currently `internal`) classes `MessageCenter`, `IncomingMessageAcceptor` and internal enumerator member `SocketDirection.SiloToSilo`?

**Comment by sergeybykov** [comment]
@ReubenBond is working on moving to Kestrel/Bedrock based messaging, which should eventually enable scenarios like that.

**Comment by ReubenBond** [comment]
Networking is implemented using Bedrock now, and is generally more pluggable. For example, there's a TLS middleware implemented without access to Orleans internals.

As far as this particular issue is concerned, though, I do not see myself implementing this - at least not in the foreseeable future. If someone has the need and is willing to implement it, then it would be a welcome contribution.

My inclination is to close this issue and allow someone to open a new issue to discuss implementing this on top of, for example, [BedrockFramework](https://github.com/davidfowl/BedrockFramework/)
