### ISSUE TITLE
Orleans Streaming - sparse streams scenario

### ISSUE THREAD

**Issue by darthkurak** [dotnet/orleans#5419]
Hi! In our company we are trying to use Orleans for IoT scenario. We using IoT Hub/EventHub.
I did a significant amount of research around how to do this properly using available possibilities in Orleans. It turned out that we cannot use Streaming with modified EventHub provider as current implementation has problems with huge number of sparse streams (if we would like to use Stream per Device). Each device can send relatively small amount of data in not so short period like one minute for example. But we can have them really huge number like half millions. That in average can give us around 8k messages per second to the system, but for each device - one message per minute. 
Currently, using Orleans that way (Stream per Device) turns out really quickly to be inefficient (around 10-20k streams). For that reason we choose hosting EPH along with the silo (as GrainService) and just pass messages directly to the "device" grain. That easily could handle 500k grains (if machine RAM was enough). 
I did some time ago discussion about that with @jason-bragg and eventually possibilities of implementing/improving current Streams to handle sparse streams. 
Now i have a time to do more investigation on that and would like to play with it a bit. I wonder if we could have discussion here how this could be handled inside Orleans runtime - some guidance from you, guys, so i could know where to start looking at.

**Comment by koenbeuk** [comment]
I'm in the preparation phase for solving a very similar problem. Scale target for millions of iot devices, all publishing a few events each hour, that need to find their way to their respective grain. (each device is represented by a grain). The current proposal includes an Azure EventHub -> Azure function -> Grain

Being able to use Orleans streaming rather than having to capture events outside of Orleans and pushing to a grain directly would reduce cost and complexity and open up new doors (e.g. different subscribers for each event stream). Hence I'd like to contribute on this where I can.

**Comment by darthkurak** [comment]
Small off top : why are you using azure functions but not event hub processor host directly?

**Comment by koenbeuk** [comment]
That's what we have on paper right now, we may come back on that decision. The main reason being hosting. Using Azure functions, there is a single centralized source which distributes events throughout the silos. To my understanding, If I was to use a GrainService, then each Silo would have an instance of this service running. I would then have to go and either find a way to only have 1 instance running per cluster- which would unbalance load on the silo's- or find a way to have multiple instances running in parallel (which doesn't sound like a trivial job). Perhaps I'm wrong in my understanding of how the EventProcessorHost or GrainServices work. I would love to see your implementation.

**Comment by darthkurak** [comment]
PM me on gitter. EPH is written that way that it can be run in multi instances on the same EH (it has leasing manager). Actually AF using EPH underhood. I'm not saying that using Azure Functions is wrong, but maybe not needed and could save you a few bucks. It depends on your scenario.

**Comment by jason-bragg** [comment]
I'd like to start with making sure I understand the requirements of your test senario.  Please vet my understanding:

- 8k events / second total
- 1 event / minute / stream

**Deductions**
- This results in about 480k active streams.
- Using eventhub with a limit of 1k events / second / partition, this mean service would need hub with at least 8 partitions.
- That comes out to be about 60k active streams per partition.

**Questions**
Are the streams using implicit or explicit subscriptions?
How many silos are in the cluster?
What is the average size of the events?

The overhead of managing recoverable streams is likely too high for this pattern, but I want to make sure I'm understanding the senario befor exploring optimizations.

**Comment by darthkurak** [comment]
More or less - yes. But this is ONLY example scenario. This can change. For example, like - one event per 30 seconds on device. Or one event per minute. But this example give idea of the problem - many streams, with relatively slow data.
Few things to point out:
- I would assume 32 partitions on EventHub as this could allow achieve more throughputs in terms of single cluster
- Assuming empty grain logic I was able to achieve around 40k - 60k messages / s with Event Processor Host as Grain Service on single machine (Standard_F8s_v2) (32 partitions on Event Hub, 0.5M devices, EventHub data populated earlier, so - it grabs messages as quickly as possible)
- Streams should use implicit subscriptions
- As i did tests on single machine cluster, i would like to compare basing on that (Standard_F8s_v2)
- Around 1 kB - 2 kB (in test scenario, but this could vary a lot depends on devices) 
- Requirements is that this should have at least one delivery, the best would be some de-duplication mechanism (exactly one delivery)

**Comment by darthkurak** [comment]
@jason-bragg ? :)
