### ISSUE TITLE
Question: implement custom read-only stream provider

### ISSUE THREAD

**Issue by rikbosch** [dotnet/orleans#5427]
Hi,

We have a global event-log in our system (implemented using [SQLStreamStore](https://github.com/SQLStreamStore/SQLStreamStore)).

The system is based on JournalledGrains which write (produce) events to the log. 

After an event is sucessfully written it is published onto an orleans stream with a fixed namespace and a fixed id, so essentially there is one large stream.

Eventprocessors are implemented using Implicit Subscriptions on the global stream.

Currently we're using the Azure storage queue streamprovider, which is not optimal for our use-case. We're facing several problems:

1 a slow eventprocessor impact all event processing (because we use a single streamid/streamnamespace)
2 we can not rewind (start at a specific position) per eventprocessor
3 latency of eventprocessing is suboptimal, because of dispatching the event to azure storage

We've discussed this internally and come up with 2 possible solutions:

**Drop orleans streams and subscribe directly to global event-log**

In this solution, our eventprocessors each have an own cursor to the event-log, this let's them work at their own pace, without impacting other eventprocessors. They each poll the event-log for new messages after their last-processed event.

Challenges in this solution are
* Database overload.  
Because each eventprocessor is polling the database in short intervals, this could overload the db. Solution would could to cache this per silo, where each eventprocessor subscribes to the cache where it is activated, challenges with this caching strategy are how to handle slow consumers
* Always-on eventprocessors
Eventprocessors have to be kept alive, this could be implemented by some sort of watchdog-grain, which invokes the eventprocessors at timed intervals to keep them alive. (we previously relied on implicit subscriptions for this).

**Hybrid solution, implementing custom readonly-streamprovider**

Because our event-log is basically a stream, we could implement our own (readonly) streamprovider for it. I've looked at the azure storage queue and the AWS implementations. Implementing something like that is fairly straightforward. But I have a few questions:
* how to make them rewindable
* how to implement this so each streamconsumer (on one single stream) does not impact each other.
* can orleans streaming be adapted so it is feasible to use with 1 stream and many subscribers

**Comment by jason-bragg** [comment]
> how to make them rewindable

We tend to refer to 'rewindable' stream providers as 'recoverable' stream providers, as they don't really allow consumers to fully rewind a stream, but rather, allow them to rewind sufficiently to recover from transient errors, hence the term 'recoverable'

For streams to be rewindable, the events need some sort of ordering information they can use in the StreamSequenceToken.  The ability to rewind is limited to the reliability of this ordering information, so it's best if the underlying backend queueing system is an authoritative and accurate source of this information.  For instance, when using EventHub we use the sequence number of the even in the hub, which EventHub enforces.

The PooledQueueCache will also need be used to cache messages in memory.  Rewinding of streams only works up to the amount of cached messages.  So if one caches 15 minutes of messages, the application cannot rewind streams back further than 15 minutes.

EventHubAdapterFactory, GeneratorAdapterFactory, and MemoryAdapterFactory are probably the best examples of recoverable stream providers. 

> how to implement this so each streamconsumer (on one single stream) does not impact each other

This should be handled by the streaming infrastructure for any persistent stream.  As the events are read from the queue, they are placed into a cache (like PooledQueueCache referenced above).  Consumers each get a cursor into the cache and deliver from that cursor.  Each consumer reads at it's own rate.  Events are cleared from the cache via an eviction strategy (IEvictionStrategy), and depending on how strict that policy is, consumers that get too far behind can either loose data or slow the reading from the queue, which can effect all consumers.

> Can orleans streaming be adapted so it is feasible to use with 1 stream and many subscribers

It "can", but there are implications.  Below is how subscriptions->streams->queues are organized.
-A subscription maps a single stream to a single consumer.
-A stream can have multiple subscriptions, but a subscription is for only one stream.
-All of the events in a stream are expected to come from a single queue.
-A queue can have data for multiple streams but a stream is fed by a single queue.
-The message reading, caching, and delivery to consumers is performed per queue.

The implications of the above is that if one limits their service to a single stream, they will also be limited to a single queue, which means all of the application events will be read and cached on a single host in their cluster.  Usually there are multiple queues with multiple streams per queue so the load can be more evenly distributed over the cluster.

The above may be fine, it really depends on the application..
