### ISSUE TITLE
How to use consul to implement cluster

### ISSUE THREAD

**Issue by leoterry-ulrica** [dotnet/orleans#5438]
How to use consul to implement cluster?
Is there relevant source code?
thx

**Comment by sergeybykov** [comment]
Have you found https://dotnet.github.io/orleans/Documentation/deployment/consul_deployment.html?

**Comment by leoterry-ulrica** [comment]
Can you provide demo source code? 
![image](https://user-images.githubusercontent.com/18339429/54245813-587f4b80-456d-11e9-984f-b12a47facb62.png)

**Comment by leoterry-ulrica** [comment]
now I have  some code below：
` private static async Task<ISiloHost> StartSilo()
        {
            int siloPort = EndpointOptions.DEFAULT_SILO_PORT;
            int gatewayPort = EndpointOptions.DEFAULT_GATEWAY_PORT;
            var orleansSection = config.GetSection("Orleans");
            if (orleansSection != null)
            {
                siloPort = orleansSection.GetValue<int>("SiloPort");
                gatewayPort = orleansSection.GetValue<int>("GatewayPort");
            }
            // define the cluster configuration
            var builder = new SiloHostBuilder()
                // .UseDashboard(options => { }) // 开启dashboard后，控制台会不断打印信息，应该可以通过CounterUpdateIntervalMs设置频率
                //.UseLocalhostClustering(siloPort, gatewayPort)
                .Configure<ClusterOptions>(options =>
                {
                    options.ClusterId = "dev"; // 相同的集群id，才能组件在同一个集群内
                    options.ServiceId = "DmeApp";
                })
                .UseConsulClustering(gatewayOptions =>
                {
                    gatewayOptions.Address = new Uri("http://127.0.0.1:8500/");
                })
                .ConfigureEndpoints(siloPort: 11112, gatewayPort: 30002, hostname: Dns.GetHostName())
                .AddMemoryGrainStorageAsDefault()
                .Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Loopback)
                //.ConfigureApplicationParts(parts => parts
                //.AddApplicationPart(typeof(TaskService).Assembly)
                //.WithReferences())
                .ConfigureLogging(logging => logging.AddNLog().AddConsole());

            var host = builder.Build();
            await host.StartAsync();
            return host;
        }`

but on consul administrator console, I cannot find  anything about soli.
![image](https://user-images.githubusercontent.com/18339429/54246664-c37e5180-4570-11e9-8245-bbcced650c63.png)

**Comment by leoterry-ulrica** [comment]
sorry,  I've got the answer.
![image](https://user-images.githubusercontent.com/18339429/54293396-de8da780-45ea-11e9-91cc-f631c6563ab2.png)

**Comment by sergeybykov** [comment]
Good. Can we close this?

**Comment by leoterry-ulrica** [comment]
yes  thx
