### ISSUE TITLE
Garbage Collection kill silo

### ISSUE THREAD

**Issue by mohamedhammad** [dotnet/orleans#5440]
Would garbage collection lead to silo failure, knowing that i am using gcserver=true and concurrent=true

**Comment by mohamedhammad** [comment]
"You can monitor GC pause times " how would i monitor for that ? do you recommend a reference or methodology ?

**Comment by ReubenBond** [comment]
Perhaps there are some tips here: https://mattwarren.org/2014/06/18/measuring-the-impact-of-the-net-garbage-collector/ or here https://mattwarren.org/2017/01/13/Analysing-Pause-times-in-the-.NET-GC/

I typically use PerfView and record short (30s samples) then look at the GC Stats view. I'm sure there are other ways, though.

**Comment by sergeybykov** [comment]
@mohamedhammad Is there anything else we can do here?
