### ISSUE TITLE
Protected property in base class being changed by another grain at the same millisecond execution time

### ISSUE THREAD

**Issue by rsuharta** [dotnet/orleans#5446]
Suppose we have the following class:

```
protected abstract class PersonBase : Grain, IGrainWithGuidKey
{
public abstract string SetFullName(string fullname);
public abstract string DisplayFullName();
  protected string FullName {get;set;}
}

public class PersonGrain : PersonBase
{

public async Task SetFullName(string fullname)
{
await this.LogDebugAsync("Calling SetFullName").ConfigureAwait(false);
 this.FullName = fullname;
return Task.FormResult(null);
}

public async Task<string> DisplayFullName()
{
await this.LogDebugAsync("Calling DisplayFullName").ConfigureAwait(false);
return this.FullName;
}
}

```
If two grains (say PersonGrainA and PersonGrainB) being executed at the same millisecond execution time, either PersonGrainA takes PersonGrainB's 'FullName' value or vice versa.

This is known issue within our prod env.  The work around we have now is to have FullName property in the actual class rather than in base class

```
protected abstract class PersonBase : Grain, IGrainWithGuidKey
{
  
}

public class PersonGrain : PersonBase
{
public string FullName {get;set;}
}

```

We have parallel for each when calling the grain
`
Parallel.ForEach(grainIds, (grainId) => { var person = client.GetGrain<PersonGrain>(grainId); person.SetFullName(someRandomName);  person.WriteLine(person.GetFullName());}`

Please note the grainIds is list collection with more 10K+ (the more the better chance to reproduce the behaviour) records all the time

**Comment by ReubenBond** [comment]
No, this can not happen

**Comment by ReubenBond** [comment]
@rsuharta closing for now. I believe the bug is in your code, for example the code you included does not wait for the tasks to complete, so a race between the two is possible (there's no enforcement of ordering in your code). Please feel free to re-open if you believe this is an Orleans issue or reach out to me directly if you would prefer
