### ISSUE TITLE
Registration based on interface name

### ISSUE THREAD

**Issue by leoterry-ulrica** [dotnet/orleans#5452]
To do an early cluster based on zookeeper or consul, Orleans supports registration based on interface names? such as **Alibaba RPC high performance framework-DUBBO** .

**Comment by sergeybykov** [comment]
Can you provide more details or an example?

**Comment by leoterry-ulrica** [comment]
for example，zookeeper is the registry center of dubbo, registration based on interface name.
![image](https://user-images.githubusercontent.com/18339429/55275447-2ddd1300-5321-11e9-8765-27c891031769.png)

@sergeybykov

**Comment by sergeybykov** [comment]
The clustering providers for ZooKeeper and Consul could do that. I don't see that this requires any change in the Orleans itself.

**Comment by sergeybykov** [comment]
@leoterry-ulrica Is there anything else here or we can close this?
