### ISSUE TITLE
How to clear JournaledGrain's state or events

### ISSUE THREAD

**Issue by zh6335901** [dotnet/orleans#5459]
I have some JournaledGrains that never activate later. So i need to clear these grains state/events, In order to  reduce grain state storage space used. But i can't find **ClearStateAsync()** method in JournaledGrain class.  

So my question is: How to clear JournaledGrain state or events?

**Comment by BenjaminGibbsMorris** [comment]
I am also interested in this; my current solution is that I submit an event that clears the state however that does still end up with something in storage even if it is blank/empty state and does not delete the state as the clear state does normally.

**Comment by zh6335901** [comment]
Hi @BenjaminGibbsMorris, Your solution is great, but it's only effect for state storage provider. But for log storage provider, It's store events to storage,  cannot clear by submit an event

**Comment by zh6335901** [comment]
I quick through the source code, I found the solution. We can use **GetGrainStorage** extension method get the grain storage, then invoke the **ClearStateAsync** method:
```
public Task Clear()
{
    DeactivateOnIdle();

    var grainStorage = this.GetGrainStorage(ServiceProvider);
    // Almost grain storage not use grain state when clear state
    // So we can simply set the parameter null
    return grainStorage.ClearStateAsync(this.GetType().FullName, this.GrainReference, grainState: null);
}
```
