### ISSUE TITLE
Sending messages on the initiative of the silo?

### ISSUE THREAD

**Issue by iamkisly** [dotnet/orleans#5464]
Hello! I successfully use Orleans for request-response, but did not find in the documentation is it possible to send messages on the initiative of the silo? Is it possible Is there a sample code, or other documentation?

**Comment by ReubenBond** [comment]
Hi @iamkisly, I do not understand what you mean by "on the initiative of the silo", could you explain further?

**Comment by iamkisly** [comment]
I'm talking about the possibility of sending a message from the silo to the client without prior request from the client.

**Comment by ReubenBond** [comment]
I think what you're looking for is streaming: http://dotnet.github.io/orleans/Documentation/streaming/streams_quick_start.html

Alternatively you can use grain observers: http://dotnet.github.io/orleans/Documentation/grains/observers.html

**Comment by ReubenBond** [comment]
@iamkisly I'm closing this for now, we can reopen it if needed.
