### ISSUE TITLE
Add configuration support for ISiloBuilder to TestClusterBuilder

### ISSUE THREAD

**Issue by erikljung** [dotnet/orleans#5465]
Hi, in order to configure common options for a "test silo" and a "real silo" -- it would be great if there was some way to configure a `ISiloBuilder` in the same way as `TestClusterBuilder.AddSiloBuilderConfigurator<T>()` is working today.

**Comment by xiazen** [comment]
Thanks for the suggestion, but I'm not entirely sure what you mean. Are you suggesting that a new feature of something like `TestClusterBuilder.AddSiloBuilderConfigurator<T>()` but for "real silo"? So for example. it would be useful in scenario like, mulitple applications share the same common base silo configuration, but at the same time have different configuration on top of the base one?

**Comment by erikljung** [comment]
So an example of what I mean:
I will have an application with a implementation of a Silo - A program which uses `new HostBuilder().UseOrleans(HostBuilderContext, ISiloBuilder)` where I will configure the `ISiloBuilder` according to my needs.
In addition I will have a test project to verify the implementation above, where I will configure `new TestClusterBuilder()`, which exposes `ISiloBuilderConfigurator` for configuration. 

I would like a more aligned way to do common configuration for both the `ISiloBuilder` and the `TestClusterBuilder()`. I would like to **not** duplicate all configuration for test and the real implementation. I am however not sure how this should be achieved from the point of current design principles.

**Comment by erikljung** [comment]
An example where this seems to work "better" is `TestClusterBuilder.AddClientBuilderConfigurator<>();` where the configurable type IClientBuilder is the same from a test and real implementation scenario.

**Comment by xiazen** [comment]
Are you saying, right now TestClusterBuilder only has AddSiloBuilderConfigurator for `ISiloHostBuilder`, you want that for `ISiloBuilder` as well?

**Comment by ReubenBond** [comment]
In my view we should replace the existing `ISiloHostBuilder` usage with `ISiloBuilder` for `TestClusterBuilder` and all related infrastructure.

At the same time we should consolidate `ISiloHostBuilder` and `ISiloBuilder` across the codebase since `ISiloBuilder` is stable and has proven its worth

**Comment by ReubenBond** [comment]
Opened #6250 with an implementation of this
