### ISSUE TITLE
HashSet grain method argument makes empty filter context with new Codegenerator.MSBuild

### ISSUE THREAD

**Issue by justmara** [dotnet/orleans#5470]
Assuming the code:
```
    public interface IHashGrain : IGrainWithIntegerKey
    {
        Task Create(HashSet<Guid> data);
        Task CreateIEnumerable(IEnumerable<Guid> data);
    }

    public class HashGrain : Grain, IHashGrain, IIncomingGrainCallFilter
    {
        public Task Create(HashSet<Guid> data)
        {
            if (data == null)
                throw new ArgumentNullException(nameof(data));
            return Task.CompletedTask;
        }

        public Task CreateIEnumerable(IEnumerable<Guid> data)
        {
            if (data == null)
                throw new ArgumentNullException(nameof(data));
            return Task.CompletedTask;
        }

        public Task Invoke(IIncomingGrainCallContext context)
        {
            if (context.InterfaceMethod == null)
                throw new ArgumentNullException("InterfaceMethod");

            return context.Invoke();
        }
    }
```

If built using `Microsoft.Orleans.OrleansCodeGenerator.Build` version 2.3.0 everything works fine.
But using new `Microsoft.Orleans.CodeGenerator.MSBuild` 2.30 the method with `HashSet<Guid>` argument has half-empty `IIncomingGrainCallContext` model:
![image](https://user-images.githubusercontent.com/4157587/54872186-40ab9100-4dd1-11e9-80d1-f9aa6464a933.png)
While `IEumerable` version still works fine.

Since older `Microsoft.Orleans.OrleansCodeGenerator.Build` now fails in `dotnet run` scenario and we're forced to update to MSBuild package - this behavior is pretty frustrating.

**Comment by ReubenBond** [comment]
Thanks for reporting, @justmara. I can reproduce this locally & confirm that it's an issue. I'm looking into the root cause.

**Comment by justmara** [comment]
Until now we're still using older `Microsoft.OrleansCodeGeneration.Build` package and it works fine. But now since we're trying to migrate netcore 3.0 we've found that older package simply fails on 3.0 build. And new one fails to work with our existing grains because of this error :(

**Comment by ReubenBond** [comment]
The cause of this issue is that using source analysis we end up seeing a different type identity for `HashSet<T>` than what's present at runtime. In particular, the assembly which it belongs to is different. This causes a disparity with the ids which are calculated for `HashSet<T>`.

I'm unsure of the best approach to rectify this - perhaps hard-coding certain assemblies/types?

**Comment by manums** [comment]
I have the same issue with `HashSet<T>` type for an input parameter of `IGrainWithGuidKey`. I can get it working by changing input parameter to any other type like `ICollection<T>`.

What appears to be a bit strange is -  I see this issue only for input parameters of `HashSet<T>` type but If return type is `HashSet<T>` then I don't see any issue. In that case, even context gets valid InterfaceMethod, ImplementationMethod etc and works perfectly as expected. See `GetAvailableEventNames`

```cs
Task UpdateAvailableEventTypes(ICollection<string> allSeenEventTypes);

Task<HashSet<string>> GetAvailableEventNames();
```
