### ISSUE TITLE
Microsoft.Orleans.CodeGenerator.MSBuild 2.2.4 infinite loop

### ISSUE THREAD

**Issue by isen-ng** [dotnet/orleans#5473]
The following code is probably causing an infinite loop in `Microsoft.Orleans.CodeGenerator.MSBuild`. 
When I build the following code, it hangs after generating `..orleans.g.args.txt`

this is the exit error message:
```
Orleans.CodeGenerator - command-line = SourceToSource /code/GrainInterfaces/obj/Debug/netstandard2.0/GrainInterfaces.orleans.g.args.txt
<...hangs for a long time...>
         Process is terminating due to StackOverflowException.
```

This code compiles without problem with `Microsoft.Orleans.OrleansCodeGenerator.Build`, `2.2.4`

GrainInterface.cs

```
    public interface IFoo : IGrainWithGuidKey
    {
        Task Bar(Complex request);
    }
```

Complex.cs
```
    public class Complex : Simple<Complex>
    {    
    }
    
    public abstract class Simple<T> where T : Simple<T>
    {
        public T DoSomething(T input)
        {
            // do something to input
            return input;
        }
    }
```

It is probably this line `public abstract class Simple<T> where T : Simple<T>` that is causing the infinite loop.

**Comment by ReubenBond** [comment]
Thank you for reporting, @isen-ng. I've opened a PR with a fix here: #5688
