### ISSUE TITLE
Azure Table Storage Provider Throughput

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/orleans#5483]
A long time ago I remember reading somewhere that you should use the `ShardedStorageProvider` with multiple Azure Table Storage providers if you thought that one Azure Table Storage account would not give you enough throughput. I also remember reading that you should predict what your max throughput is going to be because you can't change it later on.

I can't seem to find this information in the docs or issues. Does this still even hold with the latest version of Orleans and Azure Table Storage? If it does, what is the max throughput of a single Azure Table Storage account?

**Comment by sergeybykov** [comment]
We removed the sharded provided a while ago. It seemed like a good idea at the time when a single Azure Storage account was throttled at 10K RPS. In reality, this sort of implicit sharding layer of a provider on top of other providers was too cumbersome, and we didn't see people using it.

> If it does, what is the max throughput of a single Azure Table Storage account?

From https://docs.microsoft.com/en-us/azure/storage/common/storage-scalability-targets?toc=%2fazure%2fstorage%2fblobs%2ftoc.json 👍 
>Maximum request rate per storage account | 20,000 transactions per second, which assumes a 1-KiB entity size
Target throughput for a single table partition (1 KiB-entities) | Up to 2,000 entities per second

**Comment by RehanSaeed** [comment]
Thanks. I guess if you wanted more throughput than that, you could use multiple Storage accounts for each grain type.
