### ISSUE TITLE
Question: How can one access the IReminderRegistry from a static Grain extension method.

### ISSUE THREAD

**Issue by JorgeCandeias** [dotnet/orleans#5485]
I'm attempting to write a static extension method for the `Grain` type, which, in addition to other things, also registers a timer.

The easiest way would be to call `RegisterTimer()` from the grain, however that method is protected and hence not available to a static extension method.

I'd like to avoid weird stuff like creating an extension `.UseSomething()` method on `IHostBuilder` to expose the timer registry to some static variable.

Is there some nice way to reach the `ITimerRegistry` in this context?

**Comment by ReubenBond** [comment]
All of the important methods/properties of `Grain` are either `protected` or `internal`. If `Grain.Runtime` was exposed then you would be able to access `grain.Runtime.TimerRegistry`.

To the best of my knowledge, `Grain` is never exposed to user code directly except perhaps via `IIncomingGrainCallContext` (and in that case it's exposed as `IAddressable`).

Perhaps we should expose `IGrainRuntime` via `Grain`'s `Runtime` property. What do you think?

There are protections in the `IGrainRuntime` impl to prevent access from outside of the grain's execution context (eg, you can't access it from `Task.Run`). I assume that's fine for you.

**Comment by ReubenBond** [comment]
If you only need this functionality for your own grains then you can create a grain base class or interface which exposes `IGrainRuntime` property in some way (inject it if needed).

**Comment by JorgeCandeias** [comment]
This is to improve the ad-hoc reactive caching sample PR (and the improvement will spill into out own solutions here). I'm fine with deriving the class for my own solution. However I'd prefer having something less intrusive for the benefit of the sample users.

---

> Perhaps we should expose IGrainRuntime via Grain's Runtime property. What do you think?

I'm always weary of exposing API surface *by default* without a good reason, as it's hard to go back on that decision. If it's just for this use case, I don't think that API change is warranted.

> There are protections in the IGrainRuntime impl to prevent access from outside of the grain's execution context (eg, you can't access it from Task.Run). I assume that's fine for you.

That's fine - the extension is meant to be called from within the grain. It's a comfort method, nothing else.

---

Right now I'm considering the interface way, e.g.:

* Create an interface that allows implementations to expose a timer registry, for example:
``` csharp
public interface ISomeExposingInterface
{
    ITimerRegistry TimerRegistry { get; }
}
```
* Implement the interface on the given grain, thereby *explicitly* exposing the TimerRegistry.
* Extend the interface with the static method instead of the grain class.

This works, is explicit, is 100% application code... but it feels like over-engineering a very simple thing and pollutes the grain code.

Another way can be to just take the TimerRegistry in the extension method itself:

``` csharp
public static IDisposable StartSomethingHere(this Grain grain, ITimerRegistry registry, ...) { }
```

But it doesn't look very pretty either.

I can also attempt to add support for the use case itself to grain in a generic way, e.g.

``` csharp
public class Grain
{
    protected IDisposable CreateReactivePoll(...);
}
```

But it feels very very wrong to pollute wide-concern platform classes with narrow-concern comfort methods.

Sigh. Thumbs up/down on either? Or it there some other nice pattern that could fit here?

**Comment by JorgeCandeias** [comment]
> If you only need this functionality for your own grains then you can create a grain base class or interface which exposes `IGrainRuntime` property in some way (inject it if needed).

Apologies, didn't notice this reply. I guess this replaces the first option of my previous reply.

**Comment by JorgeCandeias** [comment]
Hmm, the grain also has a protected `IServiceProvider` property. I think exposing this one as public could facilitate writing extension methods in general, in addition to this one. What do you think?

**Comment by JorgeCandeias** [comment]
Closing this one. Further experience since opening this issue has shown me having a base Grain class to inherit from, (e.g. AppGrain) as a productive practice overall. Therefore we just pass whatever we need to base class constructor as usual. This removes the need to open up any easy-to-misuse API surface.
