### ISSUE TITLE
(Attempt To) Create Integration Sample w/ Apache Arrow

### ISSUE THREAD

**Issue by JorgeCandeias** [dotnet/orleans#5489]
[Apache Arrow](https://arrow.apache.org/) is another edge technology we have on the to-look-at list in order to improve performance of certain workloads within Orleans. As [Microsoft FASTER](https://github.com/Microsoft/FASTER) in #5488, it's also a young project, but it shows very promising potential as a columnar storage solution for large collections that support analytical workloads. I'm also bound to build a prototype of this at some point, so I'm creating this issue here in case anyone wants to have a go at it in the mean time. Otherwise, feel free to assign this to me.

**Comment by veikkoeeva** [comment]
Maybe of interest at this discussion: https://github.com/Microsoft/Trill/issues/6 (has popped up in Gitter also) as Orleans is used in conjunction with Trill apparently.

A bit lazy and just going to be, so links to CNTK Gitter at https://gitter.im/Microsoft/CNTK?at=59887b6b614889d475275902 about hyperparameter tuning, hardware acceleration (heterogenous siloes) and reactive actor systems regarding AI. Indeed, something that would be great if someone could lend and eye on.

**Comment by JorgeCandeias** [comment]
Jumping Jellybeans, I had totally forgotten about Trill! Thanks a lot for sharing those links and reshuffling my memory, @veikkoeeva! I'm looking at integration possibilities in the context of a CQRS-style fast projection architecture running on Orleans where every ms counts. The way Trill looks now, it's inevitable that we'll prototype it at some point. We've been talking about ML.NET as well, but it's still a ways off that one. I'll raise a couple more issues for Trill and ML.NET samples, in case someone wants to have fun building them before I get a chance to.
