### ISSUE TITLE
Docker + Consul + Memory Storage - how to ?

### ISSUE THREAD

**Issue by pchalamet** [dotnet/orleans#5491]
Hello,

I'm hitting the wall while trying to get a silo running under docker with only Consul and Memory Storage. The configuration I use is in this gist: https://gist.github.com/pchalamet/d486e846a16cbf2b871712cd846fefa3

Looks like Consul is correctly used by Orleans:
![image](https://user-images.githubusercontent.com/1562400/55293052-ea9ea500-53f1-11e9-9552-ad6380c72121.png)

But at some point, the silo is shutting down - and I really do not understand why (full logs in the gist): 
![image](https://user-images.githubusercontent.com/1562400/55293035-c773f580-53f1-11e9-82ef-1733c8ee3c62.png)

I miss something for sure in the configuration (see gist). I also found https://dotnet.github.io/orleans/Documentation/deployment/consul_deployment.html but looks like `SiloHost` & friends are obsolete now and `UseConsulClustering` does initialize everything as expected instead.

So, is there something I do the wrong way ?
Thanks for your help!

**Comment by ReubenBond** [comment]
Could you add your program.cs, too? The silo may be shutting down because the program is terminatin

**Comment by pchalamet** [comment]
Updated Silo.cs. It does work outside docker btw.

**Comment by ReubenBond** [comment]
What if you print a message after the Console Read statement to see if that's why it's shutting down?

**Comment by pchalamet** [comment]
Oh... yes you are right. The process is getting past `Console.ReadLine();` normally and just shut down :-(
That's really weird. Thanks for pinpointing the problem!

**Comment by pchalamet** [comment]
I still do not know why the process is exiting this way (in Docker only) but blocking indefinitively does solve the problem for now. I will investigate this later.

Thanks a lot @ReubenBond for helping!

**Comment by ReubenBond** [comment]
Try waiting for Ctrl + C (SIGINT) instead, Console.CancelKeyPress is the event, I believe

**Comment by pchalamet** [comment]
I've already tried this (that's what is in the Kubernetes sample) and unfortunately same problem again. There is something weird that I have to investigate because I'm so upset to have spent so much time on something so ridiculous 😒 I will keep you posted if it's Orleans related.

**Comment by ReubenBond** [comment]
@pchalamet folks in Gitter may have some tips

**Comment by ReubenBond** [comment]
How does your `Console.CancelKeyPress` code look?

**Comment by seniorquico** [comment]
I started a small [Docker sample project](https://github.com/seniorquico/OrleansDockerSample) for reference. This, and some other projects our team has in production, have been using the following to block/wait and listen for SIGTERM from Docker:

```cs
private static async Task Main(string[] args)
{
    // Cancel all tasks on SIGINT (Ctrl+C) and SIGTERM (process exiting).
    var cancellationTokenSource = new CancellationTokenSource();
    AssemblyLoadContext.Default.Unloading += context =>
    {
        cancellationTokenSource.Cancel();
    };
    Console.CancelKeyPress += (sender, e) =>
    {
        cancellationTokenSource.Cancel();
        e.Cancel = true;
    };

    ... // start silo

    await Task.Delay(Timeout.Infinite, cancellationTokenSource.Token);

    ... // stop silo
}
```

**Comment by pchalamet** [comment]
I shall not work at night and mess with the semaphore (initialCount should be 0, not 1). So it does work perfectly now 😅 

````
                var sem = new SemaphoreSlim(0, 1);
                void cancelKeyPress(object sender, ConsoleCancelEventArgs e)
                {
                    e.Cancel = true;
                    sem.Release();
                }
                Console.CancelKeyPress += cancelKeyPress;
                await sem.WaitAsync();
````

**Comment by pchalamet** [comment]
Thanks @seniorquico, probably better.

**Comment by JorgeCandeias** [comment]
Out of curiosity, have you tried the generic host builder yet? Here's an example from the newer samples:

``` csharp
public static Task Main(string[] args)
{
    return new HostBuilder()
        .UseOrleans(builder =>
        {
            builder
                .UseLocalhostClustering()
                .ConfigureApplicationParts(manager =>
                    {
                        manager.AddApplicationPart(typeof(GameGrain).Assembly).WithReferences();
                    });
        })
        .ConfigureLogging(builder =>
        {
            builder.AddConsole();
        })
        .ConfigureServices(services =>
        {
            services.Configure<ConsoleLifetimeOptions>(options =>
            {
                options.SuppressStatusMessages = true;
            });
        })
        .RunConsoleAsync();
}
```

This wires up Ctrl+C and SIGTERM for you and starts the silo in one go. Haven't tried it on docker yet though.

**Comment by seniorquico** [comment]
Nice, @JorgeCandeias! `RunConsoleAsync` registers `ConsoleLifetime` as a singleton `IHostLifetime` in the host DI container. `ConsoleLifetime` uses a very similar approach to my example above, but it subscribes to `AppDomain.CurrentDomain.ProcessExit` instead of `AssemblyLoadContext.Default.Unloading`. (It's quite possible my example code originated in a pre-.NET Standard 2 project.)

The ASP.NET Core docs indicate `ConsoleLifetime` is the default `IHostLifetime` registration (in their projects). Given all of my ASP.NET Core projects have worked out of the box in Docker, I'd assume this works just fine for Orleans+Docker. I'll have to update/simplify my projects! Thanks for the pointer!

References:
[RunConsoleAsync (extension method)](https://github.com/aspnet/Extensions/blob/v2.2.2/src/Hosting/Hosting/src/HostingHostBuilderExtensions.cs)
[ConsoleLifetime (the part that listens for SIGINT and SIGTERM)](https://github.com/aspnet/Extensions/blob/v2.2.2/src/Hosting/Hosting/src/Internal/ConsoleLifetime.cs)

**Comment by RehanSaeed** [comment]
I came here after reading [Andre Lock's post](https://andrewlock.net/introducing-ihostlifetime-and-untangling-the-generic-host-startup-interactions/) on `ConsoleLifetime` to see if Orleans supports it.

I'd like to update my [Dotnet Boxed Orleans project template](https://github.com/Dotnet-Boxed/Templates/blob/master/Docs/Orleans.md) using 'dotnet new' to use this new system. Is there any documentation for it?

**Comment by ReubenBond** [comment]
@RehanSaeed 

> I came here after reading Andre Lock's post on `ConsoleLifetime` to see if Orleans supports it.
> [...] Is there any documentation for it?

Not yet, we have to update documentation. The documentation would largely focus on using `IHostBuilder.AddOrleans(Action<ISiloBuilder>)` and point to the generic host builder documentation for the rest (lifetime, etc). Most/all methods which support `ISiloHostBuilder` have overloads to support `ISiloBuilder`, so the configuration looks almost identical
