### ISSUE TITLE
UseSiloUnobservedExceptionsHandler extension is not available in Orleans 2.3.0

### ISSUE THREAD

**Issue by pashchuk** [dotnet/orleans#5496]
The [following](https://github.com/dotnet/orleans/blob/master/src/Orleans.Runtime/Utilities/SiloUnobservedExceptionsHandler.cs#L22) extension method  is exposed only to ISiloHostBuilder, but there is no similar extension for Generic Host configuration flow.  
Also we can't add it manually as a singleton instance to the container due to it's internal protection level.

**Comment by pashchuk** [comment]
I can submit a PR to fix this if you want.

**Comment by JorgeCandeias** [comment]
Why not extending `ISiloBuilder` instead (or as well), in order to use it inside `.UseOrleans()`?

**Comment by xiazen** [comment]
@pashchuk  please do if you have time ! And thank you so much.

**Comment by pashchuk** [comment]
Ok I'll fix this in few days)
