### ISSUE TITLE
Add ISiloBuilder support to UseLinuxEnvironmentStatistics

### ISSUE THREAD

**Issue by seniorquico** [dotnet/orleans#5497]
The `UseLinuxEnvironmentStatistics` extension method in the new Orleans.TelemetryConsumers.Linux package [only operates on a `ISiloHostBuilder`](https://github.com/dotnet/orleans/blob/v2.3.0/src/TelemetryConsumers/Orleans.TelemetryConsumers.Linux/HostBuilderExtensions.cs#L48). I was playing around with the new `ISiloBuilder` and got stuck. Just as a quick test... I wrapped my `ISiloBuilder` in a `ISiloHostBuilder` facade, piped `ConfigureServices` through, and it appeared to work as expected.

Should there be a second `UseLinuxEnvironmentStatistics` extension method that operates on a `ISiloBuilder`? Or am I missing part of the new `ISiloBuilder` pattern?

**Comment by benjaminpetit** [comment]
For now yes, it's best to be able to do it on both builder
