### ISSUE TITLE
Wiki - wrong CodePlex url

### ISSUE THREAD

**Issue by jkonecki** [dotnet/orleans#55]
Since http://aka.ms/orleans url has been re-pointed to GitHub repo the CodePlex link in *Installation* page is wrong:

``You can get the installer from the Orleans Codeplex site.``

The link should be updated to http://orleans.codeplex.com.
I do not have permissions to update wiki so I log this issue instead.

**Comment by sergeybykov** [comment]
Updated to point to http://orleans.codeplex.com/releases.
