### ISSUE TITLE
(Attempt To) Create Integration Sample w/ ML.NET

### ISSUE THREAD

**Issue by JorgeCandeias** [dotnet/orleans#5501]
[ML.NET](https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet) @ [GitHub](https://github.com/dotnet/machinelearning) in the new shiny tech on the .NET space.

Though our own use cases are still a ways off, I think showing how this can integrate with Orleans for work distribution, and most importantly, *cached state* distribution, could help raise the profile of Orleans itself. Compute is cheap, it's *moving data* that kills performance, something that machine learning solutions suffer a lot from. Sharding state and moving it efficiently is something Orleans is very good at and I can therefore see these two technologies working well, especially if we're able to add something like [Apache Arrow](https://arrow.apache.org/) on top to compress data on the move *and* at rest, without the overhead of transforming said data for processing. Anyway, these are all in the air right now. This issue is here in case anyone wants to have fun with it. Otherwise, I'll come back to this at some point just for kicks.

**Comment by veikkoeeva** [comment]
Cross-referencing https://github.com/dotnet/machinelearning/issues/3239 and https://github.com/dotnet/orleans/issues/5520#issuecomment-481123304.

**Comment by unruledboy** [comment]
I am also into this combination, getting ML.net with Orleans & Trill

**Comment by veikkoeeva** [comment]
I'll add here that looking to add it at https://github.com/dotnet/orleans/tree/master/Samples/OneBoxDeployment. Specifically looking at transfer learning scenarios (grains as digital twins, maybe even semi-automatic decision making by calling other grains and using claims for access control and other decision logic), but why not also hyper-parameter tuning at some point.

**Comment by ReubenBond** [comment]
Closing due to staleness, but we can reopen this if there is interest / a PR.
