### ISSUE TITLE
what is the best way to  transmit request from grainA to grainB.

### ISSUE THREAD

**Issue by zjsjmvn** [dotnet/orleans#5508]
I don`t know how many IGrainB silos in the cluster,it is scaled.
If I use  GrainFactory.GetGrain<IGrainB>(0), it is inefficient.Only one grainB busy. 
If I use  GrainFactory.GetGrain<IGrainB>(randomid) ,it means per request creates per grain.Im afraid It will  create amount of Gains there. 
How should I do it? Thanks.

**Comment by JorgeCandeias** [comment]
What does GrainA and GrainB mean in your use case?

We tend to model grains to match logical entities in the application. For example, a "user" entity could have a `IUserGrain` interface and a `UserGrain` class if that makes sense. Then each distrint user in the application would get its own grain instance via its key.

``` csharp
var user1 = GrainFactory.GetGrain<IUser>("SomeUserNameHere1");
var user2 = GrainFactory.GetGrain<IUser>("SomeUserNameHere2");
```

You can use integers, guids or strings as keys, so you're free to model it as it makes sense.
Orleans will place these grain instances *randomly* on the cluster, which often works fine for most use cases.
You can also use other placement strategies if *random* is not good enough for the use case.

For stateless workloads and throw away stateful workloads there other approaches too.

**Comment by zjsjmvn** [comment]
> For stateless workloads and throw away stateful workloads there are other approaches too.
thanks.GrainB is Gate ,when the orleans client get the message from others,I transmit it to the gate (GrainB).
I don`t know the best way to get GrainB.

**Comment by JorgeCandeias** [comment]
I do not yet understand your use case.

* What is “Gate”?
* What is “others”?
* What do they represent in the application?
* Are they things with business keys?

Can you provide more background detail about what your solution requirements?
