### ISSUE TITLE
Design pattern for starting and not blocking on long running task, but notified of completion

### ISSUE THREAD

**Issue by Plasma** [dotnet/orleans#5513]
Hello,

I have a use case where a Grain may want to kick off a long running operation, and I want to be notified of its completion, but don’t want to block (even via await’ing a thread pool task) the long running operation, so the Grain can continue to respond to other messages.

I’m thinking I need to have this Grain maybe queue a message in a regular job/service bus queue, with the Id of the Grain who asked for the long running task to be performed, have a non-Orleans worker process do that task.

When the task is complete, send a message back to the Grain.

Am I on the right track?

**Comment by Xanatus** [comment]
There's multiple ways you can do this, but easiest might be use to use an interleaved method and eg. a windows threadpool task.

Note, however, that spawning additional threads can slow down your silos performance significantly, so depending on what you're doing, you may want to offload this to a different server or something.

```
interface IMyGrain : GrainWithGuidKey {
    [AlwaysInterleave]
    Task SpawnTaskAndDoSomethingWhenFinished();
    Task DoSomething();
}

class MyGrain : Grain, IMyGrain {
    public async Task SpawnTaskAndDoSomethingWhenFinished()
    {
        await Task.Delay(10000); //or Task.Run() with slow code
        await DoSomething(); //called after 10 seconds.
    }
    public asnyc Task DoSomething()
    {
        //run code that can be called while waiting for long task, but is also called after long task finished.
    }
}
```

**Comment by sergeybykov** [comment]
@Plasma Did you find [this section of the docs](http://dotnet.github.io/orleans/Documentation/grains/external_tasks_and_grains.html#advanced-example---making-a-grain-call-from-code-that-runs-on-a-thread-pool)?

**Comment by Plasma** [comment]
Thank you both. Yes I’ll offload the work to a seperate server.

Interleaving sounds like what I want, but does introduce some more complexity as mentioned.

I’m also thinking of emitting a job using a queue for an external server to process, with the Grain to send a completion message to.

This makes it a little less easy to read flow control wise though, but let’s me not block (even awaited block).

**Comment by sergeybykov** [comment]
@Plasma Can we close this or you have a suggestion how make this case simpler?

**Comment by Plasma** [comment]
@sergeybykov Thank you, for now I think we can close this issue.
