### ISSUE TITLE
 PROCEDURE XXx.WriteToStorage does not exist

### ISSUE THREAD

**Issue by PccCodesix** [dotnet/orleans#5515]
is there more detailed document describing how to use AdoNetGrainStorage?

when I used ADO.NET Grain Storage Provider with mysql
I get the MySql.Data.MySqlClient.MySqlException: PROCEDURE orleansstoragetest.WriteToStorage does not exist.
Can someone help me see what going wrong? orlens version is 2.3.0

**Comment by veikkoeeva** [comment]
@PccCodesix It appears there isn't the stored procedure `WriteToStorage` in the schema/database `orleansstoragetest`. Have you deployed the storage script succesfully?

**Comment by PccCodesix** [comment]
@veikkoeeva I checked the database ,found the script did not execute completely successfully. 
Reexecute the storage script execute succesfully.and  program run successfully.
Thank you for your help. 

I have some confusion. Can you help me solve it?
Is there have any examples for 2.3.0, use the additional persistence providers – IGrainStorage in the Samples Folder.
and Is there any difference between IGrainStorage and  IStorageProvider

**Comment by veikkoeeva** [comment]
@PccCodesix There has been internal and external refactoring regarding the storage code. The docs at https://dotnet.github.io/orleans/Documentation/grains/grain_persistence/index.html should be up-to-date. You can use multiple storage providers in the system.
