### ISSUE TITLE
Orleans silo windows service Log

### ISSUE THREAD

**Issue by IbrahimAhmed201** [dotnet/orleans#5517]
hi ,
how to configure Orleans silo to Log its error and Trace its problem ?

**Comment by IbrahimAhmed201** [comment]
hi ,
how to configure Orleans silo to Log its error and Trace its problem ?

**Comment by SebastianStehle** [comment]
Just read this: https://docs.microsoft.com/en-US/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2

**Comment by IbrahimAhmed201** [comment]
we use .Net framework 4.7.1 not .Net core

**Comment by SebastianStehle** [comment]
It does not matter. All these packages are available for NetStandard and it is the same code.

**Comment by sergeybykov** [comment]
@IbrahimAhmed201 Can we close this now?

**Comment by IbrahimAhmed201** [comment]
yes we can 
Thanks,
