### ISSUE TITLE
Development clustering: Primary silo endpoint optional?

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#5519]
Hi, the documentation says:
       
     // <param name="primarySiloEndpoint">
    /// The endpoint of the primary silo, or <see langword="null"/> to use this silo as the primary.
    /// </param>

But in code I see:

https://github.com/dotnet/orleans/blob/1d49d416e04f4ce7b354a87db8f2b0bbf0744687/src/Orleans.Runtime/MembershipService/SystemTargetBasedMembershipTable.cs#L34

**Comment by ReubenBond** [comment]
Thanks, @SebastianStehle - I'll submit a PR to fix it at configuration time.
