### ISSUE TITLE
how to get the dbContext  is always new when call the grain

### ISSUE THREAD

**Issue by Varorbc** [dotnet/orleans#5520]
# version info:
Orleans : 2.3.0
EF Core:2.2.3

```csharp
services.AddDbContextPool<TestContext>(options =>
{
	options.UseSqlServer("");
});
```

```csharp
    public class TestGrain : Grain,ITest
    {
        private  TestContext _testContext;

        public TestGrain(TestContext testContext)
        {
            _testContext = testContext;
        }

        public void Test()
        {
            var testContext = ServiceProvider.GetRequiredService<TestContext>();
        }
    }
```

I used the above 2 ways to get the context, I got the context used in the last call, not a new context.

**Comment by ReubenBond** [comment]
Grains are not recreated for every call, so constructor injection (`public TestGrain(TestContext testContext)`) will not work. The second approach (`ServiceProvider.GetRequiredService<TestContext>()` inside a grain method) should work: each grain activation has its own dependency injection scope.

`AddDbContext` registers contexts [using `Scoped` lifetime *by default*](https://docs.microsoft.com/en-us/ef/core/miscellaneous/configuring-dbcontext#implicitly-sharing-dbcontext-instances-across-multiple-threads-via-dependency-injection). That means that you will have one context per grain activation. You can change this behavior: https://docs.microsoft.com/en-au/dotnet/api/microsoft.extensions.dependencyinjection.entityframeworkservicecollectionextensions.adddbcontext?view=efcore-2.1

I do not see any overload to change the behavior for `AddDbContextPool`, however: https://docs.microsoft.com/en-au/dotnet/api/microsoft.extensions.dependencyinjection.entityframeworkservicecollectionextensions.adddbcontext?view=efcore-2.1

It may be worth opening an issue or PR in the [EF Core repo](https://github.com/aspnet/EntityFrameworkCore) to implement that

**Comment by Varorbc** [comment]
@ReubenBond Thank you very much for your reply. I will consult EF core about overload later.

I want to know why the scope of Service Provider in the second way is not for every grain.

var scope = ServiceProvider.CreateScope ();
scope.GetRequireService<TestContext>();

I find that in this way, the context I get is new.

**Comment by ReubenBond** [comment]
@Varorbc if you create a new scope in your call then you will be retrieving services from that new scope. That's fine if it works for you, just be sure to dispose the scope when the call ends.

**Comment by Varorbc** [comment]
@ReubenBond I would like to ask you can modify the ServiceProvider in the underlying? Let me get this ServiceProvider for every call, just like in asp.net core, I can get the ServiceProvider for each request.

**Comment by ReubenBond** [comment]
You can implement the behavior you want using a base class like this:

```C#
public class GrainBase : Grain, IIncomingGrainCallFilter
{
    public IServiceProvider RequestServices { get; set; }

    public async Task Invoke(IIncomingGrainCallContext context)
    {
        var scope = this.ServiceProvider.CreateScope();
        try
        {
            this.RequestServices = scope.ServiceProvider;
            await context.Invoke();
        }
        finally
        {
            scope.Dispose();
            this.RequestServices = null;
        }
    }
}

public class MyGrain : GrainBase, IMyGrain
{
    public Task<int> MyMethod()
    {
        var context = this.RequestService.GetRequiredService<MyDbContext>();
        // use db context
    }
}
```

**Comment by Varorbc** [comment]
@ReubenBond Thank you very much for the solution. If you have time, you can check this out.https://github.com/aspnet/EntityFrameworkCore/issues/13434#issuecomment-481075307

**Comment by ReubenBond** [comment]
I'll monitor that issue, thanks, @Varorbc 
Should we close this one?

**Comment by Varorbc** [comment]
ok,thanks @ReubenBond

**Comment by JorgeCandeias** [comment]
Just adding an alternative method...

This registers a bare-bones factory of transient contexts:

``` csharp
.ConfigureServices(services =>
{
    services.AddDbContext<RegistryContext>(options =>
    {
        options.UseInMemoryDatabase("SomeDatabase", _registryContextRoot);
    }, ServiceLifetime.Transient);
    services.AddSingleton<Func<RegistryContext>>(_ => () => _.GetService<RegistryContext>());
})
```

Then the grain requests the factory:

``` csharp
public class StorageRegistryGrain : Grain, IStorageRegistryGrain
{
    private readonly Func<RegistryContext> _factory;

    public StorageRegistryGrain(Func<RegistryContext> factory)
    {
        _factory = factory;
    }
```

Then grain methods request a new context as and when required:

``` csharp
public async Task RegisterChannelUserAsync(ChannelUser entity)
{
    using (var context = _factory())
    {
        // do stuff here
    }
}
```
