### ISSUE TITLE
How to know whether a transaction is over or not.

### ISSUE THREAD

**Issue by danpat04** [dotnet/orleans#5524]
Is there any way to find out a transaction is over or not with transaction id?

**Comment by danpat04** [comment]
Is there any way for it?

**Comment by jason-bragg** [comment]
A transactional grain call will be complete when the task resolves, unless the call throws a timeout or a OrleansTransactionInDoubtException.  In those cases, the transaction may still be in progress and retries may lead to cascading aborts.

**Comment by danpat04** [comment]
I know that, but I was wondering if there's any way to find out whether a transaction is over or not when I want to know.
