### ISSUE TITLE
Can the transaction state provider use other databases or redis? Does the official have any plans for this?

### ISSUE THREAD

**Issue by qgxcry** [dotnet/orleans#5529]
For `.UseTransactions()` to work, you need to add a transactional state provider - one that implements `ITransactionalStateStorage<TState>`. `AddAdoNetGrainStorage` doesn't do that. We currently have a provider for Azure Table that you can add with `AddAzureTableTransactionalStateStorage()`. Alternatively, you can create and add your own provider.

_Originally posted by @sergeybykov in https://github.com/dotnet/orleans/issues/5125#issuecomment-433463902_

-------------------------------------------------------------------------------------
Can the transaction state provider use other databases or redis? Does the official have any plans for this?

**Comment by veikkoeeva** [comment]
Yes. Has not been implemented yet. Referencing https://github.com/dotnet/orleans/issues/4569 as related discussion.

**Comment by jsteinich** [comment]
There is also a wrapper that will use whatever grain storage you have configured. In many ways it isn't as efficient, but it does work. The `TransactionalStateAttribute` has an optional `storageName` parameter, but you can also use default grain storage.

**Comment by rafikiassumani-msft** [comment]
@qgxcry I will close this issue since we have #4569 for tracking work related to you question.
