### ISSUE TITLE
Direct Client Orleans 2.2

### ISSUE THREAD

**Issue by mrhoga** [dotnet/orleans#5531]
Hello, 
I‘m trying to get my head around using DirectClient which is mentioned in the 2.1 release notes. Looking into the sources of 2.2 it seems like it is already obsolete again. Is there any replacement or how is this feature meant to use?

**Comment by SebastianStehle** [comment]
It is registered by default. You can just use the IGrainFactory from everywhere. Thats it.

**Comment by ReubenBond** [comment]
It's registered by default in Orleans 2.3.0, but not in Orleans 2.2.0: https://github.com/dotnet/orleans/pull/5395

That PR obsoleted the `EnableDirectClient` method because it's now a no-op.
