### ISSUE TITLE
Serialize grains into memory to avoid GC pressure

### ISSUE THREAD

**Issue by wanton7** [dotnet/orleans#5532]
Serialize grains to native or GC handled memory to avoid GC pressure (long GC pauses). This article provides similar approach
https://www.infoq.com/articles/Big-Memory-Part-1
https://www.infoq.com/articles/Big-Memory-Part-2

It could go something like this
- Serialize grain to memory after inactivity timeout or if there is high amount of live grains
- Deserialize grain if it activates or remove serialized grain from memory after another inactivity timeout

**Comment by sergeybykov** [comment]
It seems to me that the only difference between this proposal and what Orleans already does is where grain state is stored - external storage vs. local memory. Am I wrong?

Assuming my understanding is correct, I see the potential benefit of faster reactivation from memory vs. slower loading from [usually remote] storage. On the flip side, the directory overhead of keeping track of much more grains (active and passivated) might negate the latency benefit.

**Comment by wanton7** [comment]
It's true that this would only help tail latency and keeping track of all serialized grains might have and overhead. Maybe in time these tail latency problems will be gone if .NET will gets similar garbage collector to Java's new Z Garbage Collector (ZGC) that has max 10ms pauses with cost of <15% on throughput. I'll close this this.
