### ISSUE TITLE
NullReferenceException in deserialization when mixing serializers

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#5534]
Hi, I have a strange case.

I have an EventConsumerGrain that retrieves events from an event sourcing database and calls an IEventConsumer.

One of these consumers throws a NullReferenceException:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Squidex.Domain.Apps.Entities.Contents.Text.GrainTextIndexer.On(Envelope`1 event) in /src/src/Squidex.Domain.Apps.Entities/Contents/Text/GrainTextIndexer.cs:line 68
   at Squidex.Infrastructure.EventSourcing.Grains.EventConsumerGrain.DispatchConsumerAsync(Envelope`1 event) in /src/src/Squidex.Infrastructure/EventSourcing/Grains/EventConsumerGrain.cs:line 232
   at Squidex.Infrastructure.EventSourcing.Grains.EventConsumerGrain.<>c__DisplayClass10_0.<<OnEventAsync>b__0>d.MoveNext() in /src/src/Squidex.Infrastructure/EventSourcing/Grains/EventConsumerGrain.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at Squidex.Infrastructure.EventSourcing.Grains.EventConsumerGrain.DoAndUpdateStateAsync(Func`1 action, String caller) in /src/src/Squidex.Infrastructure/EventSourcing/Grains/EventConsumerGrain.cs:line 165
```

The code where the exception is thrown:

https://github.com/Squidex/squidex/blob/master/src/Squidex.Domain.Apps.Entities/Contents/Text/GrainTextIndexer.cs#L68

As you can see there is only a reference to the grain. The content event cannot be null because of the pattern matching.

If I scale down the cluster to 1 it works, so I guess it has something to do with the remote call. But I do not receive details.

EDIT: I am not sure yet, but I would say that it only happens under load, e.g. when many requests per second are done (~100)

**Comment by ReubenBond** [comment]
Could you test with a null check after the `GetGrain` call?

**Comment by SebastianStehle** [comment]
Sure, I hope I can reproduce it then. But what else could be null?

**Comment by ReubenBond** [comment]
I'm not yet sure, but if `IndexAsync` is returning `null` then that would also cause an NRE. It shouldn't be returning null.

**Comment by SebastianStehle** [comment]
Thats true, but the null must be returned by orleans then. And I have checked the dashboard. In these cases the dashboard does not log these calls.

**Comment by ReubenBond** [comment]
@SebastianStehle agreed: from what we can surmise at the moment, the null is either being returned from `GrainFactory` or the generated `GrainReference` impl.

**Comment by SebastianStehle** [comment]
I don't get it. I have added a few checks:

https://gist.github.com/SebastianStehle/cac1bb0151fa3689672a6c47b55e0394

And now I get the exception at line 98:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Squidex.Domain.Apps.Entities.Contents.Text.GrainTextIndexer.NewMethod(Envelope`1 event, ContentEvent contentEvent) in /src/src/Squidex.Domain.Apps.Entities/Contents/Text/GrainTextIndexer.cs:line 98
   at Squidex.Domain.Apps.Entities.Contents.Text.GrainTextIndexer.On(Envelope`1 event) in /src/src/Squidex.Domain.Apps.Entities/Contents/Text/GrainTextIndexer.cs:line 58
   at Squidex.Infrastructure.EventSourcing.Grains.EventConsumerGrain.DispatchConsumerAsync(Envelope`1 event) in /src/src/Squidex.Infrastructure/EventSourcing/Grains/EventConsumerGrain.cs:line 232
   at Squidex.Infrastructure.EventSourcing.Grains.EventConsumerGrain.<>c__DisplayClass10_0.<<OnEventAsync>b__0>d.MoveNext() in /src/src/Squidex.Infrastructure/EventSourcing/Grains/EventConsumerGrain.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at Squidex.Infrastructure.EventSourcing.Grains.EventConsumerGrain.DoAndUpdateStateAsync(Func`1 action, String caller) in /src/src/Squidex.Infrastructure/EventSourcing/Grains/EventConsumerGrain.cs:line 165
```

**Comment by ReubenBond** [comment]
Is the remote grain throwing an NRE? If you attach a debugger and break on all exceptions, maybe you can find out where the exception is actually being thrown.

**Comment by SebastianStehle** [comment]
As I said: it seems that the method is not called as I cannot see it in dashboard. Not sure how to debug an kubernetes application published as self-contained build. I will add some more logs. 

If the exception happens within a grain: Would I not see the stacktrace?

**Comment by SebastianStehle** [comment]
I have done a test and created a client in this client to enforce serialization and networking and I see the error now in the following line:

https://github.com/dotnet/orleans/blob/8102beadca87bb03b2bf7960598bf449c44a00da/src/Orleans.Core/Serialization/BinaryTokenStreamReader.cs#L91

The currentBuffer is null, no idea why:

![image](https://user-images.githubusercontent.com/1236435/56186837-13917d80-6021-11e9-9cc5-6b28fb20e49b.png)

**Comment by SebastianStehle** [comment]
I have a simple sample application with the same behavior.

**Comment by SebastianStehle** [comment]
I think it happens when I mix custom and default serializers.

**Comment by ReubenBond** [comment]
Thanks for the repro, @SebastianStehle - looking into it

**Comment by SebastianStehle** [comment]
Sorry, I have forgotten to push my latest tests.

**Comment by ReubenBond** [comment]
Ok, let me know when it's updated.

**Comment by SebastianStehle** [comment]
It is, this is what i wanted to say ;)

I have tested the different combinations of custom serializer and built in serializer: https://github.com/SebastianStehle/OrleansTest/blob/master/OrleansTest/Program.cs#L70

**Comment by SebastianStehle** [comment]
Have you found something?

**Comment by SebastianStehle** [comment]
I have a similar exception now where a custom exception cannot be serialized. Unfortunately I cannot reproduce it yet, but it seems to be related.

**Comment by SebastianStehle** [comment]
Sorry, was another issue: https://github.com/dotnet/orleans/issues/5534

**Comment by SebastianStehle** [comment]
@ReubenBond  I have another observation. I made the mistake again and now I get this: 

```
message: "Insufficient data present in buffer."
stackTrace: "   at Orleans.Serialization.BinaryTokenStreamReader2.ThrowInsufficientData()
   at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.TryReadSimpleType[TReader](TReader this, Object& result, SerializationTokenType& token)
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
   at Orleans.Serialization.BuiltInTypes.DeserializeInvokeMethodRequest(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
   at Orleans.Runtime.Messaging.MessageSerializer.OrleansSerializer`1.Deserialize(ReadOnlySequence`1 input, T& value)
   at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message)
   at Orleans.Runtime.Messaging.Connection.ProcessIncoming()"
type: "System.InvalidOperationException"
```

**Comment by ReubenBond** [comment]
Ok, that makes sense. Do you think the error is too obtuse? Maybe we could add to it, eg: "... This may indicate a mismatch between the serializer and deserialize used or may be a result of adding, removing, or altering fields in the underlying data types"

**Comment by SebastianStehle** [comment]
I mean the question is still: Can I combine serializers and how to prevent that serializer A ready beyond the limits? I think this is what might happen here.

**Comment by ReubenBond** [comment]
Is the best way to repro this issue still the repository you posted previously?

I wonder if what's needed is a version-tolerant serializer? Previously, the issue was related to how call filters were being used, right?

**Comment by SebastianStehle** [comment]
Yes, I think so.

The problem is when you have a method with two arguments and one of the arguments has a custom serializer. In my case I use a json serializer.

What I guess happens in my scenario:

1. I use a custom stream as a wrapper around IBinaryTokenStreamReader. The length of the IBinaryTokenStreamReader does not represent the length that was written for this argument, it is the total length of the whole message.
2. I use JSON.NET which uses stream reader. Stream reader readers entire chucks not bytes bytes.
3. The first argument with a custom serializer is reading beyond the bytes that are written for the first argument.
4. The second argument with the default serializer only gets an empty IBinaryTokenStreamReader or too few bytes.

**Comment by ReubenBond** [comment]
@SebastianStehle the serializer doesn't know the current object length: they aren't length prefixed. You could choose to serialize with a length prefix yourself if you want, but that's not something which the generated serializers do.

**Comment by SebastianStehle** [comment]
I know, but that seems to be the issue, why you cannot mix serializers. With the nullrefexception it was unclear for me, but now it is.

It should be either supported or pointed out in the docs.

If it is supported, the best option would be to show only the length of the current argument in the IBinaryTokenStreamReader.

**Comment by ReubenBond** [comment]
I thought that the NRE was caused by a misbehaving grain call filter (swallowing an exception and not setting the .Result property, AFAICR)? I don't think you will be able to mix serializers for a given type even if you do have an object-length property, will you?

I only know of a few serialization formats that use length prefixing, and only in some cases. For example, ProtoBuf *may* have a length-prefixed field, or it could be tag delimited. ProtoBuf also uses different encoding schemes, like varints and fixed-width types. JSON is always delimited in a way that requires parsing. For my side-project serializer, Hagar, I also heavily favored not length prefixing when possible, since it requires two passes for types which do not have a length that's known ahead of time (eg, UTF8 strings or complext types like classes/structs).

If you use a custom serializer and want to length-prefix the output of it, you can, though. Most of the custom `IExternalSerializer` serializers do that, eg the `ProtobufNetSerializer`. The JSON implementation calls into `IBinaryTokenStreamReader.ReadString()`, which itself uses length prefixing for the string that's read.

I believe I may still be misunderstanding how a per-object length prefix would help here.

**Comment by SebastianStehle** [comment]
Yes, the NRE also happened in another filter, but I am talking about method signatures with different serializers like in my example

```
public interface IIndexGrain : IGrainWithGuidKey
    {
        Task<bool> Index1Async(Guid id, J<IndexData1> data, bool onlyDraft);
    }
```

The `J<>` type indicates that it should be serialized with json serializer. the Guid and boolean use the default serializer.

I understand that I can prefix it myself, but it is not obvious for me that I have to do it and also requires custom buffer management and more allocations. My implementation of the JSON serializer writes directly the IBinaryTokenStreamWriter and does not need the hack you need for ProtobufNetSerializer. Actually the comments for Protobuf only mention that BinaryTokenStreamWriter is not compatible with Stream, which is not the case. 

As I said: I can live with it how it is, but it should be documented I think. We can also close this now if you think my case is too special.

**Comment by ReubenBond** [comment]
Fair enough. I wish there was something more that we could do here, but it would break wire compatibility and also come with a non-negligible cost. That custom buffer management would also be required if Orleans was to do this out of the box, since it would need to back-track to write the length header, but back-tracking is not supported in an obvious way by the underlying IBufferWriter abstraction that .NET offers. It ends up looking pretty complex (see [PrefixingBufferWriter](https://github.com/dotnet/orleans/blob/master/src/Orleans.Core/Messaging/PrefixingBufferWriter.cs))

I agree that some documentation could help. If you would like to contribute a docs edit to help others in the future, I'd greatly appreciate it.
