### ISSUE TITLE
Analyzer/CodeGen: block usage of [AlwaysInterleave] on class method

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#5540]
`[AlwaysInterleave]` must only be used on the grain *interface* method and not the grain class method.

Users can accidentally add this attribute (and others) in the wrong place and we currently have no way to warn them or stop them.

Add a misuse error to a new analyzer package (better) or to the code generator (easier, since the code generator exists).

See also #2841

**Comment by mholo65** [comment]
@ReubenBond I can take a look at this (you probably want something similar as in [EF](https://github.com/aspnet/EntityFrameworkCore/tree/99fb2d4e3d52f8a3be67fe6815a4fc288e63fe50/src/EFCore.Analyzers)). I'll create a new analyzers package and create `[AlwaysInterleave]` checking as the first rule. Afterwards we can add the other ones listed in #2841

**Comment by ReubenBond** [comment]
@mholo65 that would be greatly appreciated!

**Comment by ReubenBond** [comment]
Fixed by #5589
