### ISSUE TITLE
Issues with stateless workers producing SMS stream events

### ISSUE THREAD

**Issue by jsteinich** [dotnet/orleans#5542]
Events produced by stateless worker grains aren't always delivered to consumers for SMS.
Digging into this, the problems seems to be related to the `SimpleMessageStreamProducerExtension`. When the worker first produces an event everything works fine. The extension is installed and it is registered with pub sub.
The problem starts when a new consumer is added and the pub sub tried to notify producers about it. Since it is a stateless worker, the notification isn't guaranteed to go to the same activation. When it goes to a different one, the extension isn't installed there and that causes the producer to become unregistered. This is still sort of ok until the original worker tries to produce a new event. At that point it still has the extension so it thinks it knows all of the consumers, but it didn't get the previous notification and thus doesn't send to the new consumer.

If producing to SMS from a stateless worker isn't meant to be supported that is fine (I can workaround it), but from the surface I don't think anyone would expect it to not work.

**Comment by sergeybykov** [comment]
Your description sounds accurate to me. SMS being this pseudo-queue provider is clearly incompatible with stateless workers. Maybe we should look at detecting these cases and throwing an exception instead of allowing for such non-obvious unexpected behavior?
