### ISSUE TITLE
Cannot resolve scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[Orleans.Configuration.AzureBlobStorageOptions]' from root provider.

### ISSUE THREAD

**Issue by Alxandr** [dotnet/orleans#5543]
I enabled validation of services on the service provider, and this gives me an `InvalidOperationException` with the message `Cannot resolve scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[Orleans.Configuration.AzureBlobStorageOptions]' from root provider.`.

The issue stems from the `GetService` call here: https://github.com/dotnet/orleans/blob/master/src/Azure/Orleans.Persistence.AzureStorage/Hosting/AzureBlobSiloBuilderExtensions.cs#L110.

It seems that calling `GetService(MyScopedServiceType)` on a root service provider is disallowed. Any reason this is using a factory function, and not just using normal constructor injection?

**Comment by Alxandr** [comment]
Replacing with `IOptionsMonitor` solves the problem.

**Comment by wanton7** [comment]
I'm getting similar error ```Microsoft.Extensions.Options.IOptionsSnapshot`1[Orleans.Configuration.AdoNetGrainStorageOptions]``` when trying to use AddAdoNetGrainStorageAsDefault with ASP.NET Core 3.0 preview4.

**Comment by Alxandr** [comment]
@wanton7 yeah, there is the same error ~20 places in the code.
