### ISSUE TITLE
Orleans Core Project - Host Silo or Client Using Azure 

### ISSUE THREAD

**Issue by AnikethNagansurya** [dotnet/orleans#5544]
Hi,

I have created a project using .net core (console) for Silo and .net core (API) for Client. I am able to run using local development with Azure Storage Clustering, but is there any helpful resources for deploying to cloud for .net core referenced projects.

**Comment by sergeybykov** [comment]
Orleans isn't opinionated about which cloud hosting technology one should use. The Azure Storage Clustering provider will work with pretty much any of the Azure hosting options: Cloud Services, Service Fabric, AKS, VMSS, etc. What do you use to run your code in Azure today?

**Comment by AnikethNagansurya** [comment]
> Orleans isn't opinionated about which cloud hosting technology one should use. The Azure Storage Clustering provider will work with pretty much any of the Azure hosting options: Cloud Services, Service Fabric, AKS, VMSS, etc. What do you use to run your code in Azure today?

**Comment by AnikethNagansurya** [comment]
Thanks for the quick response. As of today we run applications On-Premises but we are trying to accommodate deployment through Azure Cloud Services hosting both Client and Silo in same cluster. Any reference links for above scenarios or hosting examples via Azure would be very helpful.

**Comment by sergeybykov** [comment]
Have you found http://dotnet.github.io/orleans/1.5/Tutorials/Cloud-Deployment.html ? It's quite outdated, especially when it comes to configuration silo/client configuration, but might still give a general idea.

**Comment by AnikethNagansurya** [comment]
Thanks for the information 👍.
