### ISSUE TITLE
After enabling cleaning of dead entries occour NotImplementedException.

### ISSUE THREAD

**Issue by HermesNew** [dotnet/orleans#5546]
Orleans Version is:2.3.0
Membership:Consul

SiloConfig:
`Configure<ClusterMembershipOptions>(options=> options.DefunctSiloCleanupPeriod=TimeSpan.FromMinutes(3))`

After silo starts, it prompts the following error:

fail: Orleans.Runtime.MembershipService.MembershipOracleData[100662]
      DeleteDeadMembershipTableEntries operation is not supported by the current implementation of IMembershipTable. Disabling the timer now.

**Comment by HermesNew** [comment]
I see ConsulBasedMembershipTable.cs code:
`public Task CleanupDefunctSiloEntries(DateTimeOffset beforeDate)
        {
            throw new NotImplementedException();
        }`
Is there an implementation plan?

**Comment by benjaminpetit** [comment]
Not yet, but we welcome every contribution :)

**Comment by RainingNight** [comment]
+1
