### ISSUE TITLE
Documentation: Broken link

### ISSUE THREAD

**Issue by Abhith** [dotnet/orleans#5547]
[SQL Tables](http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Configuring-SQL-Tables) link is broken in **[Documentation/grains/grain_persistence/relational_storage.md](https://github.com/dotnet/orleans/blob/docs/src/Documentation/grains/grain_persistence/relational_storage.md/#L1)**

**Comment by sergeybykov** [comment]
Fixed. Thank you, @Abhith!
