### ISSUE TITLE
Provide a Direct Client Example

### ISSUE THREAD

**Issue by ehouarn-perret** [dotnet/orleans#5553]
According to a comment to [a question of mine in SO](https://stackoverflow.com/questions/55832345/can-i-use-orleans-for-in-process-actors-grains?noredirect=1#comment98346266_55832345)

> Yes, it's possible out of the box in Orleans 2.3. They have a "hosted client" (sometimes referred to as a "direct client") in the service container by default. Unfortunately, there are no docs for it yet. Additionally, it looks like you're using Orleankka. I haven't looked at that library in detail, so I'm not sure how configuration of the silo with a hosted client differs (if at all) from vanilla Orleans. 

Would be it possible to provide a simple example where two grains communicate with each other with that sort of direct client and the simplest silo possible ever, I just want something to startup (note: not using Orleankka).

**Comment by iJzFan** [comment]
You can try this. https://github.com/iJzFan/orleansdemo

**Comment by ehouarn-perret** [comment]
@iJzFan thanks will check this out!

**Comment by ReubenBond** [comment]
This sample also demonstrates the 'direct client' - see how the controller consumes the client from dependency injection and uses it directly: https://github.com/dotnet/orleans/tree/master/Samples/3.0/AspNetCoreCohosting

Closing for now, since we have a sample.
