### ISSUE TITLE
Specify Bond Serializer for the MsBuildTask

### ISSUE THREAD

**Issue by fuocor** [dotnet/orleans#5556]
Question...
How do I tell the MsBuildTask to use the Bond Serializer?

regards,
rich

**Comment by ReubenBond** [comment]
Apologies for the slow reply. The code generator does not specify a serializer, instead it generates serialization methods regardless of which serializer you plan to use. At runtime you can configure Bond as your preferred serializer using code similar to this on the client + silos:

```C#
// builder is ISiloBuilder or IClientBuilder
builder.Configure<SerializationProviderOptions>(
  options => options.SerializationProviders.Add(typeof(BondSerializer)))
```

**Comment by ReubenBond** [comment]
@fuocor I'll close this issue for now, but please feel free to open another or add a comment if there's anything I can help with
