### ISSUE TITLE
Hosting Silo as Azure App Service Throws Error

### ISSUE THREAD

**Issue by AnikethNagansurya** [dotnet/orleans#5558]
I am facing issues when deploying Silo as Azure App Service, it throws error when i request from client.

**Comment by AnikethNagansurya** [comment]
Any update ?

**Comment by vmendi** [comment]
Aniketh, we tried to deploy Orleans to App Service some time ago but it was not straightforward and we gave up. The App Service instances are virtualized in a way that makes communication between the silos impossible by default. Silos of course need communication among them to form a cluster.

If I recall correctly, there was a Tier that you could select (and pay for!) in which you app was deployed in a private vnet. Being in its own vnet means that your app can communicate with other private ips in the same vnet. I never tried it, but I assume using it is a precondition to make Orleans work in the App Service environmet.

**Comment by ReubenBond** [comment]
> The App Service instances are virtualized in a way that makes communication between the silos impossible by default

This is the core issue. App Services are not suitable for deployment at this time because they cannot expose internal ports to each other for routing. It's possible to work around this but I cannot recommend any options
