### ISSUE TITLE
Client does not close connection to a dead Silo

### ISSUE THREAD

**Issue by benjaminpetit** [dotnet/orleans#5560]
If a Silo stop responding to other silos for some reason, it will be voted `Dead`. The silo in question will then shutdown itself, closing all sockets.

Clients does not check for this status, and instead just get the list of active gateways on a regular basis. If a silo has been voted `Dead`, but for some reason its socket are still open, clients will continue to send message to this faulty silo.

**Comment by sergeybykov** [comment]
Resolved via #5561.
