### ISSUE TITLE
request to add Chinese documents

### ISSUE THREAD

**Issue by Varorbc** [dotnet/orleans#5562]
request to add Chinese documents

**Comment by sergeybykov** [comment]
It would be a great contribution by the community. There was an attempt a while ago - https://orleanscn.github.io/orleans/. But looks like it hasn't been maintained recently.

**Comment by Varorbc** [comment]
Can officials increase their support for internationalization?

**Comment by fawdlstty** [comment]
http://www.manongjc.com/article/50985.html
this is one of chinese thanslated document

**Comment by fawdlstty** [comment]
where is the repo url of the Chinese document?

**Comment by ReubenBond** [comment]
@fawdlstty there are community-translated docs here in Chinese https://github.com/orleanscn/orleans/

**Comment by Caldas** [comment]
@sheng-jie wrote at #6075 about the idea to start writing Chinese documentation. I believe we should focus on #6075 issue to this matter. So we can close this one.

Agree @sergeybykov, @ReubenBond ?

**Comment by sergeybykov** [comment]
Agreed.
