### ISSUE TITLE
NullReferenceException when you catch exceptions

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#5565]
Hi,
when you just catch execptions with a filter like:

```
    public sealed class LoggingFilter : IIncomingGrainCallFilter
    {
        private readonly ILogger<LoggingFilter> log;

        public LoggingFilter(ILogger<LoggingFilter> log)
        {
            this.log = log;
        }

        public async Task Invoke(IIncomingGrainCallContext context)
        {
            try
            {
                await context.Invoke();
            }
            catch (Exception ex)
            {
                log.LogError(ex, "foo");
            }
        }
    }
```

you get a NullReferenceException. I think such a filter should be allowed for grains that void result (Task).

**Comment by SebastianStehle** [comment]
Or at least a special exception, something that does not cause headache ;)

**Comment by ReubenBond** [comment]
I'm not getting an NRE when I try this. Could you elaborate?

**Comment by SebastianStehle** [comment]
See my repo from the other issue (#5534), https://github.com/SebastianStehle/OrleansTest/blob/master/OrleansTest/Program.cs#L75

**Comment by ReubenBond** [comment]
Thanks for the repro. In that code, the grain is returning `J<object>` so I'm not sure what the behavior should look like. Still, I'll look into making it not throw an inexplicable exception. Eg, `default` may be a better value for when the user fails to set a result in a filter.

**Comment by SebastianStehle** [comment]
It was also a bug on my side, I just wanted to log exceptions because I had the other serialization problem and have forgotten to add the throw inside the catch statement.

**Comment by SebastianStehle** [comment]
Thx
