### ISSUE TITLE
Possible NullReferenceException in AzureTableStorage.ReadStateAsync for Grain<Nullable<T>>

### ISSUE THREAD

**Issue by ilyalukyanov** [dotnet/orleans#5569]
If `Nullable<T>` is used for grain state type, the following line will throw a NullReference Exception: https://github.com/dotnet/orleans/blob/v2.3.1/src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureTableStorage.cs#L83

This would happen as `StateStorageBridge<TState>` instantiates it as `new GrainState<TState>(new TState())`, and when `TState` is e.g. `int?`, then `(new int?()) == null)`.

I'm going to submit a PR that fixes that shortly.

**Comment by sergeybykov** [comment]
A PR will be greatly appreciated. Thanks!

**Comment by ilyalukyanov** [comment]
@sergeybykov already created https://github.com/dotnet/orleans/pull/5570 and also tested, but only in simple scenarios - we are using `Grain<int?>` in our application.

**Comment by sergeybykov** [comment]
Hmm, builds fine for me using build.cmd. I'm not sure we've been paying much attention to build.sh recently.
