### ISSUE TITLE
I need someone who can write a customized version of the msbuild task

### ISSUE THREAD

**Issue by fuocor** [dotnet/orleans#5572]
This is off-topic from Orleans issues, but I'll put it out there.

I have a solution that is built up from an interface based meta-model.

It outputs CSharp, C++, Typescript/JavaScript, & Go client proxies, as well as a socket gateway handler used to communicate with the Orleans cluster(s). 

To date I have used reflection with a post build task but would like to migrate it to a build task using code analysis the same way Orleans does.

My ask is simple. Is there anyone out there with the time and experience to do the work?

rich

**Comment by SebastianStehle** [comment]
I would just use GPRC or Swagger

**Comment by fuocor** [comment]
The code I need is more complicated than GPRC. The cluster gateways are geographically distributed to adhere to GDPR and the proxy class must support communication to multiple cluster gateways simultaneously. The API surface area will change continuously as our inventory of supported devices increases. So while GPRC and Swagger support the trivial parts, it's the rest that interests me.

**Comment by sergeybykov** [comment]
@fuocor I'm not sure what to do with this issue. What if anything do you think needs to be done in Orleans for this?
