### ISSUE TITLE
Question on TransactionOptions

### ISSUE THREAD

**Issue by jinhong-** [dotnet/orleans#5591]
Which TransactionOption should i use when i just want to read the committed state of the grain via the ITransactionalState facet without participating in a transaction? I just want to retrieve a "snapshot" of the currently committed state of the transaction. Will the TransactionOption.Suppress work?

**Comment by jsteinich** [comment]
There isn't a way to read transactional state without participating in the transaction. It depends on the current context which of `CreateOrJoin`, `Create`, or `Join` you want to use.

A read only transaction is lighter weight than a read-write one.

**Comment by jinhong-** [comment]
From my understanding, when u have an operation that reads the grain transaction state participates in a transaction, no other transactions can write into the same grain transaction state until the initial transaction is finished. 
I need to be able read the grain state within the first transaction without blocking the writing of the grain state in a second transaction.
My question is if i used TransactionOption.Suppress for a grain method that does a transaction read state, will I be able to write into the grain state in another transaction without waiting for the first transaction to end?
The other option i noticed is that i could use TransactionOption.Create for the read operation, which would force orleans to create a smaller transaction context, which will release immediately after the read operation is completed. Will this option work?

**Comment by jinhong-** [comment]
IGrain1
 [Transaction(TransactionOption.Create)]
-ReadSnapshot()

IGrain2
[Transaction(TransactionOption.Join)]
-TakePartInTransaction()

IGrain3
 [Transaction(TransactionOption.Create)]
-PerformSomeOperationThatInvolveGrain1AndGrain2()

Assuming in grain 3, i make the following calls in the order defined:
1. await IGrain1.ReadSnapshot()
2. await IGrain2.TakePartInTransaction()

Will a call to IGrain1.ReadSnapshot from grain 4 be blocked until grain 3 finishes the transaction call? or will it unblock as soon as step 1 finishes?

**Comment by jsteinich** [comment]
Reading the transaction state requires a `PerformRead` call. This call will fail if no transaction exists. `TransactionOption.Suppress` will prevent the transaction context from being passed along and thus fail the call. `TransactionOption.Supported` may technically work, though I would almost consider it a bug if it does.

The grain method call which initiates a transaction won't "return" until the transaction it created is resolved. Individual grain calls within that transaction can return normally.

When a second transaction accesses state that an in-progress transaction is using, it won't be considered complete until the first transaction is completed.

**Comment by jinhong-** [comment]
In my example, a second transaction context is created on top of the first as i am using TransactionOption.Create. Doesn't this mean that the second transaction context should terminate without waiting for the "outer" transaction context? That should also mean that the resource locked in the "inner" transaction should be released. Is this correct?

1. First call creates transaction context 1, locking resource A
2. Within transaction context 1, transaction context 2 is created, locking resource B
3. Resource B gets unlocked as transaction context 2 is done
4. Resource B can now be accessed by yet another transaction context, without waiting for transaction context 1 to be released

Is those statements accurate on how orleans performs transactions? What i am trying to achieve is to be able to create a smaller "inner" transaction context, and releasing the resources of the "inner" transaction context before the "outer" transaction context is completed

**Comment by jsteinich** [comment]
As far as I'm aware that is correct. Sorry for the confusion.

**Comment by jinhong-** [comment]
Awesome thanks! No worries these problems are kinda hard to explain for me.. Cheers
