### ISSUE TITLE
Memory  increased by 10%  since Orleans upgraded from 2.2.4 to 2.3.2

### ISSUE THREAD

**Issue by HermesNew** [dotnet/orleans#5612]
Memory usage has doubled since Orleans upgraded from 2.2.4 to 2.3.2

**Comment by SebastianStehle** [comment]
I think it might be useful to make a memory dump and show some statistics.

**Comment by HermesNew** [comment]
btw Microsoft.Extensions.Options package version is 2.2.0.

**Comment by sergeybykov** [comment]
@HermesNew Can you share more details on how exactly you measure this and if you analyzed memory dumps? 10% seems to be within the margin of error to me.

**Comment by HermesNew** [comment]
I am seeing memory changes through the server monitoring chart.
![0509-0514](https://user-images.githubusercontent.com/22929457/58154378-10cf1b80-7ca4-11e9-8f1a-11e9b7d347ae.png)

![0516-0519](https://user-images.githubusercontent.com/22929457/58154405-1af11a00-7ca4-11e9-929c-ffbe42503f0f.png)

**Comment by HermesNew** [comment]
When the Orleans version is 2.2.4, the server memory usage is around 60%. After upgrading to 2.3.2, the memory usage is around 75%.

**Comment by HermesNew** [comment]
I guess there should be a memory leak.

**Comment by HermesNew** [comment]
All servers are the same, with memory growth of 10%-20%.

**Comment by sergeybykov** [comment]
The memory usage looks stable to me. Which wouldn't be the case with a memory leak.

Note also that the absolute amount of memory used by a .NET process is often misleading because it's up to the memory manager when to collect garbage. As a result, you can see free memory accounted as used at the process level. That's why it's interesting to take memory dumps and compare the real picture of the number/types of objects actually allocated and how much memory they use.

**Comment by HermesNew** [comment]
Thank you for your help.The overall usage is increasing and it seems to be slow.  When there is a large object, such as a memory leak in a concurrentdictionary.I have used dotmemory for a snapshot comparison of memory, there is a problem that large objects continue to grow, but there is no deep lookup. I made feedback after I found a specific question.

**Comment by sergeybykov** [comment]
Do you mean you will keep looking into the memory of the process, and update the issue later? Just want to make sure I understood you.
