### ISSUE TITLE
Add fluent support to TestClusterBuilder

### ISSUE THREAD

**Issue by fuocor** [dotnet/orleans#5617]
The TestClusterBuilder should support fluent method chaining so we can do the following

```
return new TestClusterBuilder()
    .AddClientBuilderConfigurator<TestClientBuilderConfigurator>
    .AddSiloBuilderConfigurator<TestSiloBuilderConfigurator>()
    .Build();
```

**Comment by xiazen** [comment]
yeah that would be cool. Now you mentioned it, I am not sure why we didn't do it in the first place.

**Comment by xiazen** [comment]
I put it in 3.0.0 since it is a breaking change @sergeybykov , let me know if this is the right milestone to put?

**Comment by sergeybykov** [comment]
Why is it breaking? Not a big deal anyway. 3.0.0 is the right milestone.

**Comment by xiazen** [comment]
it removes the non-fluent style methods. Unless we want to have 2 set of methods, which can be confusing IMO. But yeah that is what I meant

**Comment by sergeybykov** [comment]
Shouldn't break anybody I think.

**Comment by xiazen** [comment]
yeah I think you are right. 👍 it is public method change, but not breaking
