### ISSUE TITLE
How to implement Property Injection

### ISSUE THREAD

**Issue by Varorbc** [dotnet/orleans#5623]
according to the autofac documentation, the configuration of property injection has been done, but I find that property injection does not work. Is it something I missed? can you tell me how to implement it?

**Comment by xiazen** [comment]
HI

Orleans uses ASP.NET core's dependency injection abstraction. AFAIK, this abstraction is intentionally kept simple in both usage and features to offer a base for other DI containers to plug-in. This also means, it doesn't have support for property injection. If you want property injection, you will need to implement it. 

I found [this post is quite useful](https://stackoverflow.com/questions/38459625/property-injection-in-asp-net-core). It talks a bit about implement property injection using autofac. But it also warns that property injection is dangerous in most scenarios, maybe consider use construction injection. 

Maybe it is a good starting point.

**Comment by Varorbc** [comment]
@xiazen I use property injection under asp.net core is normal, but under orleans, it is unusable.

**Comment by xiazen** [comment]
OIC. yeah that will be an problem. Not sure why. Can you share your implementation of the property injection, so I can take a look?

**Comment by Varorbc** [comment]
```csharp
using System;
using Autofac;
using Autofac.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;

namespace Test
{
    public class ServiceContainerFactory : IServiceProviderFactory<ContainerBuilder>
    {
        public ContainerBuilder CreateBuilder(IServiceCollection services)
        {
            var containerBuilder = new ContainerBuilder();
            containerBuilder.Populate(services);
            containerBuilder.RegisterType<Class1>().As<Interface1>().PropertiesAutowired();

            return containerBuilder;
        }

        public IServiceProvider CreateServiceProvider(ContainerBuilder containerBuilder)
        {
            var container = containerBuilder.Build();
            return new AutofacServiceProvider(container);
        }
    }
}

```

```csharp
await new HostBuilder()
	.UseServiceProviderFactory(new ServiceContainerFactory())
	//ignore part of the code
	.RunConsoleAsync();
```

```csharp
    public class TestGrain : Grain, ITest
    {
        public Interface1 Interface1 { get; set; } //is null

        public Task Test()
        {
            return Task.CompletedTask;
        }
    }
```

**Comment by sergeybykov** [comment]
@Varorbc Were you able to solve this since?

**Comment by ReubenBond** [comment]
This should work in Orleans now the same way that it works in ASP.NET - you can use the same HostBuilder and IServiceProviderFactory with Orleans now.
