### ISSUE TITLE
[QUESTION] How to marshal a task into an ActivationTaskScheduler context

### ISSUE THREAD

**Issue by peter-perot** [dotnet/orleans#5628]
Version: Orleans 1.5.3

I have some code that runs inside a silo, but not in Orleans task scheduler (`ActivationTaskScheduler`). In order to access the grain factory and call a grain's method, code must be executed in context of the Orleans task scheduler, otherwise an exception is thrown.

I did the following to switch to Orleans task scheduler context:

In a bootstrap provider I write `TaskScheduler.Current` and the `providerRuntime.GrainFactory` into static variables (`MyBootstrapProvider.GrainFactory` and `MyBootstrapProvider.OrleansScheduler`).

From the code which is running on thread pool taskscheduler (default), I marshal into the Orleans task scheduler context with the following code:

```csharp
var result = await await Task.Factory.StartNew(() =>
  MyBootstrapProvider.GrainFactory.GetGrain<IMyGrain>(0).MyGrainMethod(),
  CancellationToken.None, TaskCreationOptions.None, MyBootstrapProvider.OrleansScheduler);
```

This works okay. But I figured that Orleans creates more than one `ActivationTaskScheduler` instance, not a singleton. So my questions are:

- Is my code okay in all circumstances? It uses one single task scheduler which has been saved from the bootstrap provider.

- Is `GrainFactory` a singleton? Is it okay to save it from the bootstrap provider and use it later?

What about Orleans 2.x? Will this work there, too? (I know the bootstrap provider stuff has been replaced with a different architecture.)

Or the other way round: What is the best way to get back into Orleans context from code which runs outside of it?

**Comment by Vhab** [comment]
While this doesn't really directly answer your question, there's a path that is a bit less fiddly.
If upgrading to 2.x is an option for you, there's a feature called 'direct client' [0].
This essentially allows you to inject and use an IGrainFactory from outside of Orleans' context, and invoke grains as if you would inside Orleans or using a cluster client.

[0]: https://dotnet.github.io/orleans/blog/announcing-orleans-2.1.html#direct-client

**Comment by peter-perot** [comment]
@Vhab wrote:
> If upgrading to 2.x is an option for you, there's a feature called 'direct client' [0](https://dotnet.github.io/orleans/blog/announcing-orleans-2.1.html#direct-client).

Thanks for the hint, but for some older projects we are not able to Migrate that fast to Orleans 2.x.

**Comment by ReubenBond** [comment]
The simplest way to do this is in older versions is to capture the `TaskScheduler` in `OnActivateAsync` & use it from there - as you've done.

> Is my code okay in all circumstances? It uses one single task scheduler which has been saved from the bootstrap provider.

Yes, that's fine. The boostrap provider uses a context which never expires.

> Is GrainFactory a singleton? Is it okay to save it from the bootstrap provider and use it later?

Yes it is, the same instance is used everywhere.

Apologies for the slow reply.

**Comment by ElanHasson** [comment]
@ReubenBond Is DirectClient still a thing? I injected IGrainFactory and still get the scheduler error..

**Comment by ReubenBond** [comment]
> @ReubenBond Is `DirectClient` still a thing? I injected `IGrainFactory` and still get the scheduler error...
> 
> Turns out, i had to also capture it from `OnActivateAsync`. Works great now.

What were you trying to do with it? It's supported, but if you try to do work in the constructor then you will probably hit issues
