### ISSUE TITLE
[Question] Deadlock in streams handling

### ISSUE THREAD

**Issue by damnlogin** [dotnet/orleans#5630]
Hello 

I am trying to implement some kind of RPC using Orleans 2.0 streams.

In grain method grain awaits publishing to CommandStream and then observes response from CommandResponseStream awaiting the result, 

remote service (another process) observes incoming command from CommandStream and then handles the command and awaits publishing result back to CommandResponseStream.

Looks like this setup gets deadlocked somehow in the internals of Orleans after remote service handles the command and publishes the response. I assume due to custom scheduler used. As if I mark the grain as `[Reentrant]` everything works as expected, looks like [Reentrancy within a call chain](https://dotnet.github.io/orleans/Documentation/grains/reentrancy.html#reentrancy-within-a-call-chain) does not work in this case. Maybe it would if instead of two streams I had used GrainObserver + CommandResponseStream.

So for now the only workaround I see is to use predicate to control reentrancy as in general I do not want my code to be reentrant, but is that the right way of implementing such calls? 

Thanks in advance.

**Comment by sergeybykov** [comment]
What stream provider are you using?

**Comment by damnlogin** [comment]
I am using SimpleMessageStreamProvider and for now I am just using reentrancy controlling predicate and filter by method arguments.

**Comment by sergeybykov** [comment]
The SMS provider behaves differently from all other stream providers because it uses direct grain calls, and hence lacks the decoupling that a real queue would provide. So, it's not surprising that you are seeing deadlocks with SMS. If you plan to use this for communication between two services, then using a persistent queue seems like a natural necessity anyway. Is there any consideration that makes look for a different solution?

**Comment by damnlogin** [comment]
Thanks, that was only the dev staging setup - but I doubt any other provider but SMS will behave differently as there is logical deadlock - grain call can not complete method call unless certain message gets delivered and message can not get delivered as grain method call is still not completed. So having a reentrancy predicate looks like a natural choice here.

**Comment by sergeybykov** [comment]
Yes, this makes sense - unless the grain is reentrant, it will not get to process a 'response' event to complete processing the previous request/event.
