### ISSUE TITLE
When does OrleansBrokenTransactionLockException occur?

### ISSUE THREAD

**Issue by jinhong-** [dotnet/orleans#5644]
Currently I am attempting to perform a transaction while in a timer. Occasionally i would get a broken lock exception with the following stack trace
```
[13:31:04 WRN] Break-lock timeout for transactions 5882be80-e0d3-47ef-a25e-e55363fb01b6. 3ms late
[13:31:04 WRN] Break-lock timeout for transactions 4b4acd05-0f33-40fa-8627-bf5ddf5ba34f. 2ms late
[13:31:04 WRN] Break-lock timeout for transactions 5882be80-e0d3-47ef-a25e-e55363fb01b6. 3ms late
[13:31:04 ERR] Caught and ignored exception: Orleans.Transactions.OrleansBrokenTransactionLockException with message: Transaction 4b4acd05-0f33-40fa-8627-bf5ddf5ba34f aborted because a broken lock was detected, when trying to re-enter lock thrown from timer callback GrainTimer. TimerCallbackHandler:MyGrainWithTimer->System.Threading.Tasks.Task <ReceiveReminder>b__10_0(System.Object)
Orleans.Transactions.OrleansBrokenTransactionLockException: Transaction 4b4acd05-0f33-40fa-8627-bf5ddf5ba34f aborted because a broken lock was detected, when trying to re-enter lock
   at Orleans.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
```
I have a setup using some sort of reduce pattern, where I have subtotal grains that have timers to transfer amount into the total grain using a transaction to perform the transfer. Seems like on a random chance, a broken lock exception will occur, which will cause the transaction to fail

**Comment by jsteinich** [comment]
How long do you expect a single transfer to take?
Does the total grain have transactional state? If so, how many and how close together do you expect them to update the total?

I believe the intent of the broken lock exception is to detect when a previous transaction has failed to go through all of the steps of a transaction.
However, in practice, we have seen it occur when a transaction simply takes too long (really easy to trigger with a debugger). I ask about the frequency of updates since internally multiple transactions involving the same resource can group together.

**Comment by jinhong-** [comment]
Not very long.. a transfer is a sub second process. Probably as fast as the database can write. I did more tests and i had a very interesting observation. Seems like Orleans transactions does not like it if you did multiple writes into the same grain state over multiple transaction calls.

Given Grain1, Grain2, Grain3, Grain4 where all grains participate in a transaction:
Grain1 calls Grain2 and Grain3, Grain2 and Grain3 calls Grain4 once each, all participating in the same transaction
What i noticed is that because ITransactionalState<>.PerformUpdate() is called twice (Grain4) over multiple function calls in the same transaction, Orleans does not take this very well when I increased the number of hits to Grain1 50 calls/sec was all it took to cause a broken lock exception

**Comment by jinhong-** [comment]
I refactored my code to create a new instance of Grain4 per transaction and the broken lock went away
This seems to point to the fact that if you do PerformUpdate() on the same grain instance multiple times inside the same transaction, there is a significantly increased risk of broken lock exceptions

**Comment by jinhong-** [comment]
Turns out it was much easier to replicate the problem than i thought. As long as you make multiple calls into the same grain instance in the same transaction, the problem will occur under load. I have committed some a sample in the link below that will replicate the issue:
https://github.com/jinhong-/orleans-broken-lock-sample

**Comment by jsteinich** [comment]
Just made a PR (https://github.com/dotnet/orleans/pull/5656) for something that I tried adjusting when diagnosing this type of issue. I ended up leaving the default, but I also didn't get to such a simple repro either. Could help here, but I'm wondering if there isn't just a bug.

**Comment by jinhong-** [comment]
Anyone has any idea if this is a bug?

**Comment by sebastianburckhardt** [comment]
Broken locks typically occur if a transaction takes too long to complete. The time from when a grain is accessed in a transaction until the transaction completes cannot exceed `TransactionalStateOptions.LockTimeout`, which is 8 seconds by default.

Maybe `broken lock` should have been called `lock timeout`.

Why would a transaction take so long? 

Perhaps your system has very high latencies, runs very long transactions, or is overloaded. In that case transactions simply don't work. You will need workflows, or sagas, or something like that.

Another (and more easily fixable) reason of why locks time out is that there may be deadlocks going on: If you have multiple transactions that are accessing the same grains they can get into a deadlock situation (each transaction holds some locks that another transaction needs). For example, if you have grains A and B, and transaction T1 accesses A first, then B, while transaction T2 accesses B first, then A, you can get into the situation where T1 is waiting for T2 to release the lock on B, while T2 is waiting for T1 to release the lock on A. This deadlock then causes the locks to time out.

Deadlocks can be avoided by designing transactions so they follow a consistent ordering when accessing grain. For example, say you have three grains A, B, C. By enforcing that the order of grain access inside a transaction follows alphabetic order, you can avoid deadlocks and the corresponding broken locks.

**Comment by jinhong-** [comment]
hi @sebastianburckhardt thanks for explaining broken lock exception.

Are you able to download the sample project i created to replicate the issue? I am consistently getting broken lock exception in my example and I believe it takes less than 8 seconds to execute.

Somehow broken lock consistently occurs during the situation where you attempt to perform 2 or more grain calls to the same grain instance within the same transaction, and multiple transactions are being performed on that same grain.

i don't feel like this is a timeout issue but there might be a bug in the implementation on such scenario

**Comment by jinhong-** [comment]
You can see here that I have Grain1, which has a method that does a Transaction.Create and it calls the same Grain2 instance twice:
https://github.com/jinhong-/orleans-broken-lock-sample/blob/d3e0e46b7cc19cb3a9c35346c817786a22b59220/Grains/Class1.cs#L10-L23

On my client, i simply call Grain1.Execute 100 times:
https://github.com/jinhong-/orleans-broken-lock-sample/blob/d3e0e46b7cc19cb3a9c35346c817786a22b59220/Client/Program.cs#L58-L72

@sebastianburckhardt  what you are saying does make sense, if i lock A and then B in one tx but B and then A in another, it will cause a deadlock. In my case, i only have A, and i am "locking" A twice. But since I already acquired lock for A, it should not cause any deadlocks if i attempt to lock A again

From what i can observe so far, it does seem like a deadlock issue when requests are being interleaved. 
Tx 1 Locks A
Tx 2 Locks A
Tx 1 Locks A <-- Fails

**Comment by jsteinich** [comment]
I was able to confirm the deadlock using @jinhong- 's sample. The actual deadlock is occurring between the `ReaderWriterLock` and the Orleans grain single threaded nature.
The flow goes as follows:
- Tx 1 starts `Grain2.Execute`
- Tx 1 acquires the transaction lock
- Tx 1 completes `Grain2.Execute`
- Tx 2 starts `Grain2.Execute`
- Tx 2 waits for transaction lock
- Tx 1 waits for `Grain2.Execute`

I was able to get the sample to run "successfully" by either marking `Grain2` as `Reentrant` or marking `Grain2.Execute` as `AlwaysInterleave`

For our use case, marking grains as `Reentrant` shouldn't be too bad (*need to further vent out), but it doesn't seem great to be forced to choose between single threaded guarantee, transactions, or never calling a transactional grain twice in a transaction.

**Comment by sebastianburckhardt** [comment]
Right, the transactional state is not compatible with non-reentrant grains. This is a known limitation but perhaps it is missing from the documentation. All grains that use transactional state should be marked as reentrant.

Allowing reentrancy on grains with transactional state is harmless because the transaction lock and transaction commit mechanism already prevent any "reentrancy effects" from being visible to the application: transactions are serializable, i.e. they will not interleave on the same grain.

**Comment by jinhong-** [comment]
Wow thanks! Will be good to improve the documentation and sample project to contain the reentrant attribute as well. It would have saved me quite a little bit of pain
https://github.com/dotnet/orleans/blob/4da0c5dc44511300ddd25155a8b1144d9c88d2e7/Samples/2.0/AccountTransfer.NetCore/src/AccountTransfer.Grains/AccountGrain.cs#L17-L18

**Comment by jinhong-** [comment]
@sebastianburckhardt  Another suggestion is that would it make sense to have it implicitly use always interleave for every method that supports transactions?

**Comment by sebastianburckhardt** [comment]
Yes, I htink that is a good idea @jinhong. We could make this automatic and it would eliminate this problem altogether.
