### ISSUE TITLE
Expected result of type System.Nullable`1[System.Int64] but encountered a null value.

### ISSUE THREAD

**Issue by mkjeff** [dotnet/orleans#5660]
after upgrade to v2.3.3, the grain method return `Nullable<T>` was broken.

https://github.com/mkjeff/orleans/blob/9d67a5c4a27cd9392f5d198b495ac90fa8df6ffb/src/Orleans.Core/Async/TaskExtensions.cs#L118

**Comment by ReubenBond** [comment]
Thank you for reporting, @mkjeff. This regression was introduced by #5582

I will PR a fix soon

**Comment by ReubenBond** [comment]
Opened PR #5663

**Comment by ReubenBond** [comment]
@mkjeff 2.3.4 has been released with a fix. Thank you for your patience.
