### ISSUE TITLE
Interface does not support output parameters?

### ISSUE THREAD

**Issue by YunTengGroup** [dotnet/orleans#5670]
I want to page through some entities and return the total number that meets the criteria, so I defined this interface:
`
Task<List<TestEntity>> GetEntitysByAge(int age ,int pageindex ,int pagesize ,out int total);
`
But compile time error: OrleansCodeGenTestServiceReference Do not implement interface ITestService.Search(int, int,int, out int)

This is the code generated at compile time(X.XX.IService.orleans.g.cs).
global::System.Threading.Tasks.Task<global::System.Collections.Generic.Listglobal::X.XX.XXX.TestEntity> global::X.XX.XXX.ITestService.Search(int age ,int pageindex ,int pagesize,int total)
{
return base.InvokeMethodAsync<global::System.Collections.Generic.Listglobal::X.XX.XXX.TestEntity>(unchecked((int)0xBC81583A), new object[]{age , pageindex , pagesize , total});
}
No ‘out’ keyword

What should I do?

**Comment by YunTengGroup** [comment]
This is the code generated at compile time.
global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<global::X.XX.XXX.TestEntity>> global::X.XX.XXX.ITestService.Search(int age ,int pageindex ,int pagesize,int total)
        {
            return base.InvokeMethodAsync<global::System.Collections.Generic.List<global::X.XX.XXX.TestEntity>>(unchecked((int)0xBC81583A), new object[]{age , pageindex , pagesize , total});
        }

**Comment by sergeybykov** [comment]
'out' parameters are not supported. The way around it is to return a data structure that includes all such return values, for example, `Task<Tuple<List<TestEntity>, int>>` instead of `Task<List<TestEntity>>`.

**Comment by YunTengGroup** [comment]
Thank you.  my own solution is handled like this.
`
    public class PageResult<T> where T : class
    {
        public bool IsError { get; set; }

        public  List<T> Data { get; set; }

        public int Total { get; set; }

        public string Message { get; set; }
    }
`

**Comment by sergeybykov** [comment]
This should work.

**Comment by ReubenBond** [comment]
@YunTengGroup it seems like your question has been answered. I'll close this & we can open another issue if needed.

**Comment by bddckr** [comment]
Is this documented somewhere? I'm wondering whether I'm missing other language constructs that aren't supported by the messaging in Orleans.

**Comment by bddckr** [comment]
I just saw #5530. Perhaps this could give errors during codegen, too? Currently the compilation does end in an error, though in one that doesn't hint at the actual issue (as it seems the codegen itself ran, and removed the `out`, thus just generating an interface implementation that's invalid).

```
1>obj\Debug\netstandard2.0\GrainInterfaces.orleans.g.cs(106,84,106,93): error CS0539: 'OrleansCodeGenHelloReference.SayHello2(string)' in explicit interface declaration is not found among members of the interface that can be implemented
1>obj\Debug\netstandard2.0\GrainInterfaces.orleans.g.cs(56,91,56,121): error CS0535: 'OrleansCodeGenHelloReference' does not implement interface member 'IHello.SayHello2(out string)'
```

**Comment by ReubenBond** [comment]
@bddckr having a codegen error or an analyzer error would be great. I opened a new issue for it: https://github.com/dotnet/orleans/issues/5704
