### ISSUE TITLE
not support ISiloBuilder.AddIncomingGrainCallFilter 

### ISSUE THREAD

**Issue by lfzm** [dotnet/orleans#5671]
Cannot use the `AddIncomingGrainCallFilter` function when using `Microsoft.Extensions.Hosting`

idea：
1. support `ISiloBuilder.AddIncomingGrainCallFilter `
2. `IServiceCollection.AddIncomingGrainCallFilter`  open public

**Comment by lfzm** [comment]
Temporary solution：
```
ISiloBuilder.ConfigureServices(services => services.AddSingleton<IIncomingGrainCallFilter, OrleansExceptionsFiltered>());
```

**Comment by ReubenBond** [comment]
@sergeybykov we merged a fix in #5466, but haven't picked it up for a patch release yet (my mistake)

**Comment by sergeybykov** [comment]
Oh, then this is already resolved.

**Comment by stephenlautier** [comment]
Was this released on version 2.3.4?

**Comment by ReubenBond** [comment]
@stephenlautier unfortunately this was not included in 2.3.4. We plan to make another release shortly and will include it. 

The extension method seems to resolve for me: 
![image](https://user-images.githubusercontent.com/203839/59391545-6e95d700-8d29-11e9-8921-4e880de730d5.png)

**Comment by stephenlautier** [comment]
@ReubenBond ahh oki that explains it, I was testing on 2.3.4, not on master.

I got confused because i was seeing the source and it was added 22 March (quite back), and somehow on VS i was getting 2 classes but couldnt access the `Orleans.Runtime` one, just the other

**Comment by stephenlautier** [comment]
Just checked on an orleans sample project, and im just not seeing the `ISiloBuilder` extensions, so if they are resolving correctly on master then it should work after release. Sorry about this

**Comment by ReubenBond** [comment]
It's my mistake, @stephenlautier

**Comment by lfzm** [comment]
V2.3.5 completed  [#5466](https://github.com/dotnet/orleans/pull/5466)
