### ISSUE TITLE
Microsoft.Extensions.Hosting.IHostBuilder and Orleans.Hosting.ISiloHostBuilder merge

### ISSUE THREAD

**Issue by lfzm** [dotnet/orleans#5685]
Microsoft.Extensions.Hosting.IHostBuilder and Orleans.Hosting.ISiloHostBuilder now have many of the same places.
example:
Microsoft.Extensions.Hosting.HostBuilderContext and Orleans.Hosting.HostBuilderContext
Microsoft.Extensions.Hosting.IHostingEnvironment and Orleans.Hosting.IHostingEnvironment

Can these be merged or all use Microsoft.Extensions.Hosting?

**Comment by ReubenBond** [comment]
> Can these be merged or all use Microsoft.Extensions.Hosting?

I think we can deprecate and delete `ISiloHostBuilder` eventually and move everything to `ISiloBuilder` + `HostBuilder` instead. Does that sound good to you?

**Comment by lfzm** [comment]
I am looking forward to it, is there a plan?

**Comment by ReubenBond** [comment]
The original plan for HostBuilder support is here: https://github.com/dotnet/orleans/issues/4702#issuecomment-446684609

Does that help?

**Comment by lfzm** [comment]
Great, I am looking forward to it.
