### ISSUE TITLE
Add Analyzer/CodeGen error for invalid grain interface signatures

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#5704]
Grain interfaces do not support parameter modifiers such as `out`/`ref`/`in`.

We should add clear error messages via the Orleans.Analyzers package and codegen to notify users when they attempt to use an unsupported modifier.

See #5670 & #5530

An analyzer was added in https://github.com/dotnet/orleans/pull/5589 - it could be extended

(note: support for `in` could be added to the code generator, too)

**Comment by miker1423** [comment]
If no one has take it, I'll like to take it :)

**Comment by ReubenBond** [comment]
That would be fantastic, @miker1423 !

**Comment by erictuvesson** [comment]
What is the status here @ReubenBond + @miker1423 ?

**Comment by ReubenBond** [comment]
I haven't had cycles for it, and it would be a welcome contribution

**Comment by miker1423** [comment]
Hello @erictuvesson, I had one half finished, it just needs testing, I pushed it to my fork, if you want to take over this issue, go ahead, but I could finish it by the weekend.

**Comment by erictuvesson** [comment]
Hi @miker1423, if you feel like you have time that would be great; otherwise I could take a look.

**Comment by sergeybykov** [comment]
Resolved via #6567. Thank you, @miker1423!
