### ISSUE TITLE
TestCluster.Deploy - OrleansMessageRejectionException : Target silo S127.0.0.1:41081:0 is unavailable

### ISSUE THREAD

**Issue by jonas-johansson** [dotnet/orleans#5726]
We have an issue where a test sometimes (~30% of the time) fails when deploying the TestCluster.

It only seems to happen on Linux (not on Windows).

```
16:27:59  ----------------------------- STARTING NEW UNIT TEST SILO HOST: Orleans.TestingHost.TestCluster -------------------------------------
16:27:59  Done initializing cluster
16:27:59  Initializing Cluster Client
16:27:59  Exception Uninitializing grain client: System.NullReferenceException: Object reference not set to an instance of an object.
16:27:59     at Orleans.TestingHost.TestCluster.StopClusterClientAsync()
16:27:59  
16:27:59  [xUnit.net 00:00:14.15]     SomeTestThatWeHave [FAIL]
16:27:59  Failed   SomeTestThatWeHave
16:27:59  Error Message:
16:27:59   Orleans.Runtime.OrleansMessageRejectionException : Target silo S127.0.0.1:41081:0 is unavailable
16:27:59  Stack Trace:
16:27:59     at Orleans.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
16:27:59     at Orleans.OutsideRuntimeClient.<>c__DisplayClass56_0.<<StartInternal>b__2>d.MoveNext()
16:27:59  --- End of stack trace from previous location where exception was thrown ---
16:27:59     at Orleans.OutsideRuntimeClient.<StartInternal>g__ExecuteWithRetries|56_3(Func`1 task, Func`2 shouldRetry)
16:27:59     at Orleans.OutsideRuntimeClient.StartInternal(Func`2 retryFilter)
16:27:59     at Orleans.OutsideRuntimeClient.Start(Func`2 retryFilter)
16:27:59     at Orleans.ClusterClient.Connect(Func`2 retryFilter)
16:27:59     at Orleans.TestingHost.TestCluster.InitializeClient()
16:27:59     at Orleans.TestingHost.TestCluster.InitializeAsync()
16:27:59     at Orleans.TestingHost.TestCluster.DeployAsync()
16:27:59     at Orleans.TestingHost.TestCluster.DeployAsync()
16:27:59     at Orleans.TestingHost.TestCluster.Deploy()
             --- ommitted for gitter ---
16:27:59  --- End of stack trace from previous location where exception was thrown ---
16:28:55  
16:28:55  Total tests: 4. Passed: 3. Failed: 1. Skipped: 0.
16:28:55  Test Run Failed.
```

Any idea what could cause this?

**Comment by ReubenBond** [comment]
NB I mentioned on Gitter that #5592 (v2.3.3) fixes the `NullReferenceException` seen here

As for the failure itself, how are you configuring the test cluster? We use the same TestCluster in our CI tests & I don't recall seeing any failures like this

**Comment by jonas-johansson** [comment]
We configure the test cluster like this:

```
public static TestCluster CreateAndDeployTestCluster()
{
	var testClusterBuilder = new TestClusterBuilder();
	testClusterBuilder.AddSiloBuilderConfigurator<TestSiloBuilderConfigurator>();

	var testCluster = testClusterBuilder.Build();
	testCluster.Deploy();

	return testCluster;
}

class TestSiloBuilderConfigurator : ISiloBuilderConfigurator
{
	public static Action<IServiceCollection> ConfigureServices { get; set; } = services => { };

	public void Configure(ISiloHostBuilder hostBuilder)
	{
		hostBuilder
			.ConfigureApplicationParts(parts =>
			{
				// ommitted
			})
			.AddMemoryGrainStorage("PubSubStore")
			.AddSimpleMessageStreamProvider(Constants.ClientStreamProvider, SimpleMessageStreamOptions)
			.AddMemoryGrainStorage("ommitted")
			.UseInMemoryReminderService()
			.AddStartupTask<GrainInitTask>()
			.ConfigureServices(ConfigureServices)
			.EnableDirectClient();
	}

	static void SimpleMessageStreamOptions(SimpleMessageStreamProviderOptions options)
	{
		options.FireAndForgetDelivery = true;
	}
}
```

**Comment by ReubenBond** [comment]
Can you capture logs? Does the issue still occur if you upgrade to 2.3.5?

**Comment by jonas-johansson** [comment]
I can't show the logs right now as they might contain sensitive data.

I'm trying to get everything running with 2.3.5 now to see how it behaves.

**Comment by jonas-johansson** [comment]
The test still fails (~30%) when using 2.3.5 (but the exception is obviously gone, as you suggested).

`Orleans.Runtime.OrleansMessageRejectionException : Target silo S127.0.0.1:40016:0 is unavailable`

**Comment by ReubenBond** [comment]
Is the test running inside of a container? Can you provide redacted logs? Alternatively, do the logs give you any clues?

**Comment by jonas-johansson** [comment]
Thank you for your patience @ReubenBond. Our team will leave for the day, so we'll have to get back with more information later. Thanks!

**Comment by seniorquico** [comment]
I'm standing up a new test project, using Orleans 2.3.5 and the TestCluster. I immediately started to encounter this same issue (same behavior & message at least). Tests are randomly failing, but around 50% of the time. I run in a Docker container (Hyper-V/Moby and base image `mcr.microsoft.com/dotnet/core/sdk:2.2`) on Windows 10.

I'm just started to get this setup, and I don't have anything logs-wise yet. Just the generic exception about failing to connect to the silo. I'll see if I can start to dig up something useful.

**Comment by ReubenBond** [comment]
@seniorquico if you can get some logs from the silos/clients that will help us to identify the issue

**Comment by seniorquico** [comment]
@ReubenBond Yeah, ran into issues with that. When `ConfigureFileLogging = true`, the test cluster is failing to start due to an IOException (looks permissions related). Still investigating (as time permits).

**Comment by ReubenBond** [comment]
@seniorquico I'll close this due to inactivity - I hope the issue is resolved. We can re-open if there's still something to investigate

**Comment by turowicz** [comment]
@jonas-johansson Did you manage to solve it? I'm getting this error when running tests.

cc @ReubenBond

**Comment by jonas-johansson** [comment]
@turowicz I have not looked further at this.
