### ISSUE TITLE
Orleans statistics floats have decimal separators written in culture specific format to storage

### ISSUE THREAD

**Issue by veikkoeeva** [dotnet/orleans#573]
Orleans statistics floats have decimal separators written in culture specific format. I think the intention is to store data in culture invariant way. I have verified this is  an issue with SQL Server where statistics are written to the table as

| StatValue | Statistic |  
|---|---|
| 6,572005  | Runtime.CpuUsage  |  
| 1,588444  | Runtime.GC.PercentOfTimeInGC  | 

in systems where decimal separator is not dot (e.g. Finnish). In relational database the code is [here](https://github.com/dotnet/orleans/blob/master/src/Orleans/Storage/OrleansRelationalExtensions.cs#L287). For Table Storage the code is [here](https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Storage/StatsTableDataManager.cs#L146). I would imagine it has a similar issue.

I recall .NET Design Guidelines tell that ``.ToString`` is to print culture aware strings, so in that sense the ``.ToString`` code is right, the callers are wrong. One way to provide a fix is to add an overload to ``ToString`` that accepts a ``CultureInfo`` parameter. An example: [Single.ToString Method (IFormatProvider)](https://msdn.microsoft.com/en-us/library/7tdhaxxa(v=vs.110).aspx).

Tangential notes:

* Maybe adding a ``DebuggerDisplay`` to ``ICounter``.
* It would look like sensible to refactor the relational code so that statistic values are always numeric.

**Comment by gabikliot** [comment]
Agree on adding Invariant culture to those calls to ToString(). Good idea.

**Comment by jthelin** [comment]
The core part of this problem should be fixed by PR #578 now merged.

@veikkoeeva - Please retest to confirm.

**Comment by veikkoeeva** [comment]
@jthelin I'm at computer later today, looking at the code I think the floating points are still written in a culture specific format. The change is to use custom numeric formats, but they are still culture specific. Look at [Custom Numeric Format Strings](https://msdn.microsoft.com/en-us/library/0c899ak8(v=vs.110).aspx) in MSDN. Feels like a place to write a test. :)

Say, if this is so, and thinking that according to .NET Design Guidelines (if I remember correctly) ``.ToString()`` is mean to print a culture specific string, so it feels like both ``ToString()`` and ``GetDisplayString()`` should return the stings without ``CultureInfo.InvariantCulture`` and if they need to return a string with culture specific or invariant coding, it is provided with an overload. These are internal and not data bound anywhere, but a thought that occurred.

**Comment by veikkoeeva** [comment]
Confirmed from a database: still comma. I'm at home a few days, I think I have time to make the fix if somebody else doesn't get it first.
