### ISSUE TITLE
Enable membership table cleanup by default

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#5733]

**Comment by stgolem** [comment]
Any details here? 🤔

**Comment by ReubenBond** [comment]
Sure thing, @stgolem 

We recently added functionality to periodically cleanup the membership table (removing long-dead silos) but this was opt-in behavior. The feature has demonstrated its value & we're planning on enabling it by default for the next release

**Comment by HermesNew** [comment]
@ReubenBond Does consul also support it?

**Comment by ReubenBond** [comment]
@HermesNew not yet: https://github.com/dotnet/orleans/blob/e479ef54513339a09b9accdaa88e6083dd8ce465/src/Orleans.Clustering.Consul/ConsulBasedMembershipTable.cs#L176

If you're able to implement this, that would be fantastic
