### ISSUE TITLE
Switching to NUnit Test Framework

### ISSUE THREAD

**Issue by jthelin** [dotnet/orleans#574]
# Switching to NUnit

This post is to raise a proposal to switch the test framework used for Orleans runtime code in GitHub to use **NUnit** instead of *MsTest*, and to solicit community feedback and discussion on that topic.

## Why Not MsTest?

The biggest problem that we have hit several times with MsTest is that **calls to the test class teardown function is non-deterministic**, so there are absolutely no guarantees that the ClassCleanup method for one test file will have been called before the ClassInitialize method for another test class gets called. 
 
This causes huge problems for some of the most advanced functional test cases for Orleans around cluster membership and other handling of silo failure cases, most recently demonstrated on PR #557.

We have also been hit several times by the unexpected MsTest behavior that it creates a separate instance of the test class **per test case**, which makes TestInitialize vs Constructor code almost completely pointless distinction. 

Most of the Orleans systems tests are grouped into similar functional units that can share test execution environment to amortize test silo start-up time & cost across several test cases, but MsTest does not observe or use that optimization.

Take a look at this (slightly old) blog post for more background info on these issues, and several others:  
[http://madcoderspeak.blogspot.com/2011/11/nunit-vs-mstest-2011-edition.html](http://madcoderspeak.blogspot.com/2011/11/nunit-vs-mstest-2011-edition.html)

The requirements we have for test framework functionality are fairly basic, but we have now run out of tricks to make MsTest work within this model:
  
* Class-Setup/Teardown - to be executed ONCE before/after ALL tests in that class / source file. 
* Test-Setup/Teardown - to be executed before/after EVERY test 

## Why NUnit?

[NUnit](http://nunit.net/ "NUnit") is one of several test frameworks commonly used for .NET projects, but offers a number of additional advantages compared to MsTest:

1. Generally works exactly the way people expect it to, with fewer example of quirky and unexpected behavior around test class / test case initialization and cleanup.
2. Already runs **cross-platform**, so provides a much easier transition route as we work towards building and running Orleans natively on other platforms, including Mac OSX, Linux, CoreCLR, etc. 
3. There is mostly a [simple direct mapping](http://xunit.codeplex.com/wikipage?title=Comparisons) of terminology, concepts and API attributes / methods between MsTest and NUnit, which is almost all cases make the conversion very easy to automate and check.
4. There is good support for NUnit in .NET editors and IDEs, including test harnesses built in to ReSharper and Visual Studio [through a simple [VS extension](http://nunit.net/index.php?p=vsTestAdapter&r=2.6.4)]. 
There are also standalone test runners for both GUI and command line use if preferred.
5. Many other .NET Foundation projects on GitHub have already moved away from MsTest for their test suite(s) in order to allow diverse cross-platform testing.

## Why not other test frameworks, such as xUNit?

The main priority of this switch is to minimize the conceptual and API changes we would need to make in order to get the new test suite up and running.

We don't have a dedicated test team assigned to Orleans, so any changes will be made by core developers or community members. 

Therefore **minimizing switching cost is a primary concern**.

For example, xUnit seems to be a very well regarded test framework, but requires some significant changes to the way testing is approached and reasoned about.
 
Some immediate examples of large conceptual changes when thinking about a move to xUnit:

* Fact vs general TestMethod.
* Constructor+IDisposable instead of Test Setup/Teardown.
* Fixtures instead of Test Class Setup/Teardown.

In short, switching to NUnit seems to have the lowest switching costs, and provide the smoothest transition path for test approach.

Bear in mind that we (the Orleans Core Team) have day jobs too :) 

We also have many other internal test suites and test cases that we want to get into GitHub but we already have problems with finding time to migrate them all to GitHub even as a direct MsTest -> MsTest conversion case. 

So realistically we feel we have even less cycles to make radical changes to the old test cases if there is large test framework porting gap :(

## Next Steps

I have created a prototype of the changes to switch over to use `NUnit` test framework on a branch in my repo.
[https://github.com/jthelin/orleans/tree/NUnit](https://github.com/jthelin/orleans/tree/NUnit)

I will shortly submit that branch as a Pull Request on GH for further community discussion.
That branch should be considered a work-in-progress which will require some ongoing updates to track any test-related changes in `master` but currently build and runs all test cases ok.

Please use that PR #575 for any specific feedback about the code-level changes themselves.

If you have any general comments or suggestions about changing test framework, then please reply to this thread.

We are targeting this switch over to the release after next (1.0.10) after current work in progress are stabilized and released in 1.0.9, but wanted to give early community visibility and feedback opportunity on the change proposal :)

**Comment by jthelin** [comment]
PR #575 contains the code changes related to this proposal.

**Comment by veikkoeeva** [comment]
Well explained plan. I don't have much to add (*) other than that when porting is done, should we try [NUnit Version 3 3.0.0-beta-2](https://www.nuget.org/packages/NUnit/3.0.0-beta-2) or later?  The [NUnit Wiki](http://www.nunit.org/) (see on the left) tells the latest beta and CTP should be of production quality already. I don't have an analysis of the benefits other than that NUnit 3.0 seem to support running in multiple AppDomains and processes (detailed [here](https://github.com/nunit/dev/wiki/NUnit-Vision)) and that if things work smoothly, why not for the sake of pointing out that NUnit 3.0 works with Orleans, which may be a note of confidence for the NUnit maintainers. If there are issues, we can just stay in 2.n or open/fix and issue.

(*) Integrate the other projects to Orleans so you have a full time job doing this. :-P

**Comment by jkonecki** [comment]
I would like to propose XUnit.

**Comment by galvesribeiro** [comment]
Guys / @jthelin, no pressure, but do we have any progress on this issue?

I'm blocked with the coreCLR move on #368 since we can't migrate the tests. :frowning: There is no MSTest for CoreCLR. 

I've spoke with @richlander on Gitter and looks like the efforts at coreCLR currently regarding UT (at least for a while) are on top of (x|n)Unit. 

They will probably come up some time with MSTest for coreCLR since there is a huge number of people using it but we can't be blocked until it gets ported/open-sourced.

Is there anything we can do to help?

Thanks

**Comment by sergeybykov** [comment]
We ended up using xUnit instead of NUnit. https://github.com/dotnet/orleans/issues/1540 concluded migration of tests to xUnit.

**Comment by AnaitBI** [comment]
In my Orleans project testing, can I use NUnit instead of XUnit?

**Comment by galvesribeiro** [comment]
@AnaitBI yes, you are free to use whatever test framework you want. I happens that we moved the Orleans code to xUnit but it is not mandatory to use it for user-level code.
