### ISSUE TITLE
Transaction over several states

### ISSUE THREAD

**Issue by Ilchert** [dotnet/orleans#5749]
Hello, I am investigating transactions and got strange behavior: can not update 2 different transaction state in a one grain method. The second update fails with exception: 'Transaction 2b5c1dc2-d6ee-4347-ad15-509d48c57518 aborted because a broken lock was detected, when trying to re-enter lock'
Is it expected behavior?
My code is very simple:
```C#
public async Task Method()
{
    await state1.PerformUpdate(p=>p.Id=1);
    await state2.PerformUpdate(p=>p.Id=1);
}
```

**Comment by jsteinich** [comment]
Any grain used in transactions needs to be `Reentrant` or at least have methods marked with `AlwaysInterleave`

See https://github.com/dotnet/orleans/issues/5644#issuecomment-502803583

**Comment by Ilchert** [comment]
> Any grain used in transactions needs to be `Reentrant` or at least have methods marked with `AlwaysInterleave`
> 
> See [#5644 (comment)](https://github.com/dotnet/orleans/issues/5644#issuecomment-502803583)

But several updates of one state are allowed. 
Thanks for the clarification!

**Comment by sergeybykov** [comment]
@Ilchert Can we close this now?

**Comment by Ilchert** [comment]
Yes, thanks.

**Comment by scampos-s3d** [comment]
I still have this issue with this code. Using `Reentrant` didn't make any difference
`[Reentrant]
	public class UserInventoryGrain : Grain, IUserInventory
	{
		private readonly ITransactionalState<Inventory> inventorySQL;
		private readonly ITransactionalState<Inventory> inventoryMongo;

		public UserInventoryGrain(
			[TransactionalState("inventory", "SQL")] ITransactionalState<Inventory> inventorySQL,
			[TransactionalState("inventory", "Mongo")] ITransactionalState<Inventory> inventoryMongo)
		{
			this.inventorySQL = inventorySQL;
			this.inventoryMongo = inventoryMongo;
		}

		[AlwaysInterleave]
		public async Task IncreaseMoneyAsync(int amount)
		{
			await inventorySQL.PerformUpdate(x => x.Money += amount);
			await inventoryMongo.PerformUpdate(x => x.Money += amount);
		}
	}`
