### ISSUE TITLE
Stream nullref exception on shutdown

### ISSUE THREAD

**Issue by jason-bragg** [dotnet/orleans#5755]
Orleans.Streams.*stg/4614814381842400150/de148396.EventHubStreamProvider, arg2 (eventId): 103312, arg3 (eventName): , exception: System.NullReferenceException: Object reference not set to an instance of an object. at Orleans.ServiceBus.Providers.EventHubAdapterReceiver.<GetQueueMessagesAsync>d__22.MoveNext()

**Comment by ReubenBond** [comment]
I'm not sure this is actionable, so I'll close it until we have a repro. I also believe this issue was fixed (but I am unable to find the PR/commit right now)
