### ISSUE TITLE
OrleansPSUtils 2.x support

### ISSUE THREAD

**Issue by yigitgursoy** [dotnet/orleans#5757]
Are there any plans to write a 2.x compatible OrleansPSUtils package?

https://www.powershellgallery.com/packages/OrleansPSUtils/1.5.0

**Comment by ReubenBond** [comment]
@yigitgursoy not at the moment, but since Orleans is a .NET application, you can load & call it from PowerShell.

My thought was that with all the various plugins we support today it's difficult for us to maintain a good PowerShell experience.

**Comment by yigitgursoy** [comment]
Thanks @ReubenBond
