### ISSUE TITLE
[Request] Grain implementation inheriting Grain requirement to be clearer

### ISSUE THREAD

**Issue by SirJosh3917** [dotnet/orleans#5762]
i just wasted about 6-8 hours just to realize i needed
```cs
public class HelloGrain : IHelloGrain
```
to be
```cs
public class HelloGrain : Grain, IHelloGrain
```

(silly me :upside_down_face:)

the exceptions I got from doing so weren't user friendly at all - I had included the code generator but the exception wasn't about the code generator. (exception: <https://github.com/dotnet/orleans/blob/master/src/Orleans.Core/Configuration/Validators/ApplicationPartValidator.cs#L65-L67>)

Is it possible that the code generator can create a warning if installed on a project with no classes inheriting Grain? funnily enough I thought the code generator was working as well because I had inspected the interfaces and grains dlls and they had orleans generated code in them.

I can probably try to find my way around the documentation and submit a PR to make it explicit that you *need* to inherit Grain, but i'm not familiar with roslyn enough to create a warning on build if there's nothing that inherits Grain

(perhaps the warning should even be an error by default?)

**Comment by sergeybykov** [comment]
Yes, this is an issue that people run into periodically.
>Is it possible that the code generator can create a warning if installed on a project with no classes inheriting Grain?

This would be confusing for projects that define only grain interfaces and not grain classes.

We could issue a warning for classes that implement grain interfaces without inheriting from `Grain`. That would be mostly correct, except for various such helper classes that people sometime create.

I think we can safely extend the error message by also suggesting to ensure that all grain classes inherit from `Grain`.

**Comment by ReubenBond** [comment]
There is a Roslyn analyzer for this now, added in #6941. Thanks for reporting
