### ISSUE TITLE
Passing an IEnumerable<Claim> to a grain method gives TypeAccessException

### ISSUE THREAD

**Issue by InzenDN** [dotnet/orleans#5767]
I'm trying to store Identity user claims in a grain state. I'm passing it in as `List<Claim>`, but when I do so it gives a `Message: System.TypeAccessException : Named type "Claim" is invalid: Type string "Claim" cannot be resolved.` I'm not sure if this is intended, if I'm doing something wrong, or if this is a bug.

The following is the method for the grain `UserClaimsGrain : Grain<List<Claim>>, IUserClaimGrain`
```csharp
public async Task AddClaimsAsync(List<Claim> claims, User user)
{
    foreach (Claim claim in claims)
    {
        if (State.Contains(claim)) continue;
        State.Add(claim);
        await GrainFactory.GetGrain<IUsersOfClaimGrain>(claim.Value).AddUser(user);
    }
    await WriteStateAsync();
    return;
}
```

This is the xUnit test I have for it. I'm currently using Orleans.TestingHost to setup a TestCluster with xUnit's IClassFixture.
```csharp
[Fact]
public async Task AddClaims_AddingClaims_ReturnSuccess()
{
    // Arrange
    var user = new User()
    {
        Id = Guid.NewGuid()
    };

    var claims = new List<Claim>()
    {
        new Claim(ClaimTypes.NameIdentifier, user.Id.ToString())
    };

    var userClaimsGrain = _Client.GetGrain<IUserClaimsGrain>(user.Id);

    // Act
    await userClaimsGrain.AddClaimsAsync(claims, user);
    List<Claim> retrievedClaims = await userClaimsGrain.GetClaimsAsync();

    // Assert
    for(var i=0; i<claims.Count; i++)
    {
        Assert.Equal(claims[i].Type, retrievedClaims[i].Type);
        Assert.Equal(claims[i].Value, retrievedClaims[i].Value);
    }            
}
```
I've tried changing `List<Claim>` to some other object such as `List<User>` and that works fine. I also notice that simply passing in `Claim` works, but it is when I pass in `List<Claim>` that it throws an error. I'd rather not pass each `Claim` one at a time, however, as that would cause the application to invoke WriteStateAsync() multiple times. Even if that were a work around, it wouldn't matter as returning the `List<Claim>` state also throws the same error.

![image](https://user-images.githubusercontent.com/10301859/61506072-cdd4b000-a995-11e9-992c-a1be4787ba78.png)

**Comment by ReubenBond** [comment]
It looks as though this "Claim" type is not serializable and does not have a serializer generated for it.

Where is the type defined? Is it available on both client & silo?

**Comment by InzenDN** [comment]
Thank you for responding so quickly! The type is defined in `System.Security.Claims` namespace, unless I'm misreading what you are saying. It should be available for any .NET project, including the client and silo.

**Comment by veikkoeeva** [comment]
@InzenDN Indeed the type is unserializable. You need to do something like https://stackoverflow.com/questions/28155169/how-to-programmatically-choose-a-constructor-during-deserialization .

**Comment by InzenDN** [comment]
@veikkoeeva Thank you for the link. That gave me just enough hint to get where I needed. I managed to design a custom serializer class, and now all my UserClaims unit tests are passing with green flags. 
```csharp
[Serializer(typeof(Claim))]
internal class ClaimsSerializer
{
    [CopierMethod]
    public static object DeepCopier(object original, ICopyContext context)
    {
        return (Claim)original;
    }
}
```
I'm not sure I wrote it with best practices in mind, but so far no issues. If there is an issue with what I did, please let me know. It seems all of Claim properties were read only, which made creating a copy impossible, so I just sent in the original instead. 

On that note, would it have been more appropriate to instantiate a new instance of `Claim` with `input.Type` and `input.Value` passed into its constructor parameter in the manner of 
```csharp
var input = (Claim)original;
var result = new Claim(input.Type, input.Value);
return result;
```
or is returning the original a non-issue? Thanks.

**Comment by veikkoeeva** [comment]
@InzenDN That is a tough question I would need to try to comment with more certainty. Unless @ReubenBond or someone else with better knowledge of these bits comments, I would say it's a non-issue as long as you do not change the type, i.e. it's immutale and deep copy, real serialization is not needed. I know:
1. That type is not serializable by JSON.NET and most (de)serializers), I'm not entirely sure about Orleans but it appears so.
2. That you could just pass through the original suggests to me this is an in-silo operation.

Due to `2.` it appears you could use [Immutable](https://orleanscn.github.io/orleans/Documentation/Advanced-Concepts/Using-Immutable-to-Optimize-Copying.html). But I think you have the same problem whenever you need to serialize that class either in Orleans or elsewhere unless you have a method with "external knowledge" on how to deserialize the type.

**Comment by ReubenBond** [comment]
@InzenDN returning the original is a non-issue as long as it is immutable

I'll close this for now because I believe this issue has been resolved by means of a custom serializer
