### ISSUE TITLE
[Question]: Silo connection via bus.

### ISSUE THREAD

**Issue by KSemenenko** [dotnet/orleans#5768]
Hello, tell me please, is there a way to connect Silo nodes to a bus like Redis or Azure Queue?
I tried to use Azure AppService as hosting my .net core webapi application, which also contains Silo, but the AppService does not allow opening a private endpoint for Silo connections. 
And I wondered if it was possible to connect the nodes without a direct connection.

**Comment by sergeybykov** [comment]
Currently, direct TCP connectivity between silo nodes is a requirement.

**Comment by KSemenenko** [comment]
Thanks @sergeybykov
