### ISSUE TITLE
[Question] There is a way to call another Grain without waiting for the Task?

### ISSUE THREAD

**Issue by KSemenenko** [dotnet/orleans#5774]
For example, I have to send SMS messages, and I want to just call the sending method, and without waiting for it to finish (and the result), continue to execute my code in the Grain process.
Is it possible to do?

``` cs
....
var grain1 = GrainFactory.GetGrain<IGrain>(1);
_ = grain1.DoSome(); //skip await
var x = 1;
.....

**Comment by wanton7** [comment]
I would NEVER skip `await`! You should `await` all tasks before method ends. I'm pretty sure you will mess up Orleans task scheduler badly if you do that and cause all kinds of problems. Instead use undocumented `[OneWay]` attribute. Checking out these tests will show you how to use it https://github.com/dotnet/orleans/blob/dad62cc16d4d6de671563f6b1e54196f617926a5/test/DefaultCluster.Tests/OneWayCallTests.cs

**Comment by jonathansant** [comment]
I would go for  `GrainFactory.GetGrain<IGrain>(1).InvokeOneWay(grain => grain.DoSome())`

**Comment by bluexo** [comment]
grain.DoSome().Ignore();

**Comment by ifle** [comment]
You can also to mark the DoSome method with OneWay attribute

**Comment by KSemenenko** [comment]
@wanton7 @jonathansant @bluexo @ifle thank you for your answers!

**Comment by sergeybykov** [comment]
There's also `.Ignore()` option. It is more expensive than `InvokeOneWay()` though because responses do get sent to the caller, logger, and ignored.
