### ISSUE TITLE
Heterogeneous Silo and "Cannot find an implementation class" error

### ISSUE THREAD

**Issue by ushenkodmitry** [dotnet/orleans#5778]
Hello,
can't figure out what is wrong with my Orleans based solution. Please advise.
I have four projects:
1. ClientApi - webapi application, references Orleans nugets and grain interfaces project;
2. GrainInterface - grains interfaces
3. Coordinator - silo, references Orleans MSBuild nuget and grain interfaces project. Contains grains implementation.
4. DataAccessor - silo, references Orleans MSBuild nuget and grain interfaces project. Contains grains implementation.
Now, from the controller i'm getting grain reference for the grain which is hosted in Coordinator silo. It gets called. From withing that grain i'm trying to get grain reference (using GrainsFactory property) which is hosted in DataAccessor silo. And here i'm getting exception "cannot find an implementation class...". 

I've read all documentation and it seems that i don't need to do some additional configuration for this to work. All my silos configured with the code, similar to this:
```
                .UseOrleans((context, builder) =>
                {
                    builder
                        .UseLocalhostClustering()
                        .Configure<ClusterOptions>(options =>
                        {
                            options.ClusterId = "ClusterId";
                            options.ServiceId = "UniqueServiceId";
                        })
                        .ConfigureApplicationParts(parts =>
                        {
                            parts.AddApplicationPart(executingAssembly).WithReferences();
                        });
                })
```
Here, executingAssembly is the assembly of my console project with the grain implementations.

**Comment by benjaminpetit** [comment]
Do you have this issue when you just started the silos, is it working when you wait 30 or 60 seconds?

The grain type map takes few seconds to propagate when you start silos, so you might want to tweak the defualt config values if needed.

**Comment by ushenkodmitry** [comment]
Hello @benjaminpetit 
Thank you for your answer. I've found TypeManagementOptions options and set TypeMapRefreshInterval to 30 seconds. But still i see the same error. Is there are any additional configurations i need to make to support my scenario?

**Comment by ushenkodmitry** [comment]
Some more info.
If i run both silos and try to get 2nd grain (hosted in the DataAccessor) directly from the ClientApi i see the same error. But when i run ClientApi and DataAccessor silo (without Coordinator silo) and try to get 2nd grain - it gets called.

**Comment by tomerpeled** [comment]
I'm encountering the same issue on our env. We wanted to start using Heterogeneous silos deployments, each silo holds references to the interfaces, while the implementation classes are found only on the silos which will actually use it.
But we're getting the mentioned exception...

Should we define the Silos "types" somehow?

**Comment by ushenkodmitry** [comment]
Orleans version 2.3.6, dotnet core version 2.2, OS Windows 10.

**Comment by benjaminpetit** [comment]
Sorry I missed the previous response, but I think the issue is in your configuration: `.UseLocalhostClustering()`. You have to use a "real" clustering provider if you have more than 1 silo. Here effectively, silos are isolated and does not make a unique cluster

**Comment by ushenkodmitry** [comment]
Thank you!
I'll check on weekend and close the issue.

**Comment by sheng-jie** [comment]
I got the same error.
I updated the 'HelloWorld' demo to test heterogeneous silo. The solution structure as blow figure shows.
![](https://user-images.githubusercontent.com/12607748/62833125-f9cd1380-bc6b-11e9-9bb4-5ff1d829ab56.png)

1. The SiloHost project is as the primary silo, it defines the implement of the `IHello`.
2. The SiloHost2 project defines the implement of the `IHelloArchive`.
3. The WebApi Client just call the `IHello`  api by orleans client.

Start all the silos and webapi project. It works fine. 

Then add a new `ITest` grain and implement it at the SiloHost2 project. And invoke the new grain in the webapi. The new updated structure as blow figure show.

![image](https://user-images.githubusercontent.com/12607748/62833197-6268c000-bc6d-11e9-8441-7ab91e8f6cbd.png)


Stop the SiloHost2 and webapi project and rerun it, keep the SiloHost running. 
The new Updated SiloHost2 can join the cluster successfully.

When I hit the invocation to the `ITest` grain, I got the exception.

The client and silo configuration as blow.
```
Client = new ClientBuilder()
    .UseLocalhostClustering()
    .Configure<TypeManagementOptions>(option=>option.TypeMapRefreshInterval=TimeSpan.FromSeconds(30))
    .ConfigureLogging(builder => builder.AddProvider(loggerProvider))
    .Build();

//SiloHost configuration
builder
    .UseLocalhostClustering()
    .Configure<TypeManagementOptions>(option=>option.TypeMapRefreshInterval=TimeSpan.FromSeconds(30))
    .Configure<ClusterOptions>(options =>
    {
        options.ClusterId = "dev";
        options.ServiceId = "HelloWorldApp";
    })
    .Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Loopback)
    .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(HelloGrain).Assembly).WithReferences());

//the SiloHost2 configuration
builder
    .UseLocalhostClustering(11112, 30001, new IPEndPoint(IPAddress.Loopback, 11111))
    .Configure<TypeManagementOptions>(option=>option.TypeMapRefreshInterval=TimeSpan.FromSeconds(30))
    .Configure<ClusterOptions>(options =>
    {
        options.ClusterId = "dev";
        options.ServiceId = "HelloWorldApp";
    })
    .Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Loopback)
    .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(HelloArchiveGrain).Assembly).WithReferences());
```

I don't have any idea on this. Is there anything wrong in my demo?

*PS: English is not my native language; please excuse typing errors.*

**Comment by benjaminpetit** [comment]
Can you repro that without using `LocalhostClustering` (using Azure for example)

> PS: English is not my native language; please excuse typing errors.

No worries, it's not my native language either :)

**Comment by sheng-jie** [comment]
@benjaminpetit  It works fine with azure cluster provider. 
I found the reason that the `UseLocalhostClustering()` only works for single silo unless specified multiple silos gateways when start the orleans client like below.
```
Client = new ClientBuilder()
    .UseLocalhostClustering(new []{30000,300001})
    .ConfigureLogging(builder => builder.AddProvider(loggerProvider))
    .Build();

```

**Comment by ushenkodmitry** [comment]
Hey folks!
I did some changes and now i have next configuration:
* 3 silos, each with its own grains (heterogeneous silos)
* 1st silo is configured with the code:
```
     builder
         .UseDevelopmentClustering(new IPEndPoint(IPAddress.Parse("10.0.75.1"), 11111))
         .Configure<ClusterOptions>(options =>
         {
               options.ClusterId = "Cluster";
               options.ServiceId = "Service1";
          })
          .ConfigureApplicationParts(parts =>
          {
               parts.AddApplicationPart(executingAssembly).WithReferences();
          })
          .ConfigureEndpoints(siloPort: 33333, gatewayPort: 30000)
          .AddSimpleMessageStreamProvider("SimpleStreamProvider")
          .AddMemoryGrainStorageAsDefault();
```

* 2nd silo:
```
    builder
       .UseDevelopmentClustering(new IPEndPoint(IPAddress.Parse("10.0.75.1"), 11111))
       .Configure<ClusterOptions>(options =>
       {
            options.ClusterId = "Cluster";
            options.ServiceId = "Service2";
       })
       .ConfigureApplicationParts(parts =>
       {
             parts.AddApplicationPart(executingAssembly).WithReferences();
       })
       .ConfigureEndpoints(siloPort: 22222, gatewayPort: 30000)
       .AddSimpleMessageStreamProvider("SimpleStreamProvider")
       .AddMemoryGrainStorageAsDefault();
```
* 3rd silo:
```
     builder
         .UseDevelopmentClustering(new IPEndPoint(IPAddress.Parse("10.0.75.1"), 11111))
         .Configure<ClusterOptions>(options =>
         {
               options.ClusterId = "Cluster";
               options.ServiceId = "Service3";
         })
         .ConfigureApplicationParts(parts =>
         {
              parts.AddApplicationPart(executingAssembly).WithReferences();
          })
          .ConfigureEndpoints(siloPort: 11111, gatewayPort: 30000)
          .AddSimpleMessageStreamProvider("SimpleStreamProvider")
          .AddMemoryGrainStorageAsDefault();
```

3rd silo is the primary silo. In the output of the 3rd silo i see:
```  
2019-08-29 19:04:27.3807| INFO|Orleans.Runtime.MembershipService.MembershipTableManager|ProcessTableUpdate (called from TryUpdateMyStatusGlobalOnce) membership table: 3 silos, 3 are Active, 0 are Dead, Version=<6, 10>. All silos: [SiloAddress=S10.0.75.1:11111:304790657 SiloName=Silo_47011 Status=Active, SiloAddress=S10.0.75.1:22222:304790657 SiloName=Silo_67a6b Status=Active, SiloAddress=S10.0.75.1:33333:304790657 SiloName=Silo_cd80b Status=Active]
```
Does this mean that all silos form a cluster?

**Comment by benjaminpetit** [comment]
Yes they do! But if your 3 silos are running on the same machine, you should also use different ports for the gateway

**Comment by ushenkodmitry** [comment]
Ok. I've changed silos configuration so they now use different gateway ports.
Then i have a cluster client, configured as:
```
    var gateways = new[]
    {
          new IPEndPoint(IPAddress.Parse("10.0.75.1"), 30001),
          new IPEndPoint(IPAddress.Parse("10.0.75.1"), 30002),
          new IPEndPoint(IPAddress.Parse("10.0.75.1"), 30003)
     };

     return new ClientBuilder()
           .UseStaticClustering(gateways)
            .Configure<ClusterOptions>(options =>
            {
                  options.ClusterId = "Cluster";
                  options.ServiceId = "Service4";
             })
             .AddSimpleMessageStreamProvider("SimpleStreamProvider")
             .Build();
```
It can connect to the cluster, but when i'm trying to get grain via the client i'm getting the same exception:
```
System.ArgumentException: Cannot find an implementation class for grain interface: TestService.Grains.ITestGrain. Make sure the grain assembly was correctly deployed and loaded in the silo.
```

**Comment by ReubenBond** [comment]
@ushenkodmitry when you add application parts, is your silo referencing the grain interface + class assemblies?

**Comment by ushenkodmitry** [comment]
@ReubenBond Yes, all silos reference grain interfaces. Double checked! Grains implementations are in each silo project, so i don't have any references to implementation assemblies.

**Comment by ushenkodmitry** [comment]
Wow! Just created a minimal solution to reproduce the behavior and it works. I hate it when it happens!

**Comment by ushenkodmitry** [comment]
Does Orleans play nicely with DI containers? This is the difference between my failed reproduction and my project. I'm using Autofac.

**Comment by ushenkodmitry** [comment]
Now it works! Thanks and sorry for bother. It was my fault.

**Comment by ushenkodmitry** [comment]
@ReubenBond @benjaminpetit I don't know if you have a sample for heterogeneous silos in your samples, but if you don't i may contribute one.
