### ISSUE TITLE
Mechanism to fetch all states from a grain (Like Select * from table)

### ISSUE THREAD

**Issue by AnikethNagansurya** [dotnet/orleans#5789]

**Comment by sergeybykov** [comment]
Do you mean to fetch state from multiple grains of a grain type?

**Comment by AnikethNagansurya** [comment]
No, meant to say like if we create grains with Guid n populate the states of that created grain and now want to fetch all the grains states at once from that silo.

**Comment by sergeybykov** [comment]
Doesn't "we create grains with Guid n populate the states" refer to multiple grains?

**Comment by AnikethNagansurya** [comment]
Yes. Sorry for the confusion, can we fetch the states for multiple grains at once.

**Comment by sergeybykov** [comment]
In the application code you can fan-out calls to multiple grains in parallel, and then merge the responses after they arrive. There's no built-in support for that though.

**Comment by AnikethNagansurya** [comment]
Ok. Thank you 😊
