### ISSUE TITLE
MSBuild codegen failing when only .NET Core 3 preview SDK is available

### ISSUE THREAD

**Issue by Vhab** [dotnet/orleans#5793]
It would appear something is causing `Microsoft.Orleans.CodeGenerator.MSBuild` to fall back to trying to use .NET Core 2.0.0 SDK when only .NET Core 3 Preview7 is available.

When using only 3.0 I'm getting the following message when attempting to build a .net standard 2.0 library containing a grain:

```
  It was not possible to find any compatible framework version
  The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
    - The following frameworks were found:
        3.0.0-preview7-27912-14 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

  You can resolve the problem by installing the specified framework and/or SDK.

  The .NET Core frameworks can be found at:
    - https://aka.ms/dotnet-download
```

I've setup a reproduction case at https://github.com/Vhab/OrleansCodegenNetCore3

It's using docker as it's the easiest way to get a clean environment to test in.

It contains 3 images, one with .NET Core 2,2, one with 3.0p7 and one with both.
The first and last one build fine, but the one with only 3.0 fails.

The repo includes a readme with how to run the reproduction cases.

**Comment by ReubenBond** [comment]
Thanks for reporting, @Vhab. Ideally we will be able to ship a self-contained codegen package which will not be framework-dependent while still being cross-platform.

**Comment by Vhab** [comment]
This might be much to ask, could you give a rough outline on which bits of the codegen are causing it to behave this way? Do you have an idea/angle on what it would take to fix it?

This sounds like an interesting problem, and I wouldn't mind taking a stab at it. But I could use some pointers on how deep this rabbit hole goes :)

**Comment by ReubenBond** [comment]
It's an Orleans problem, but it shouldn't be complicated to fix. The issue might be as simple as passing `--rollForwardOnNoCandidateFx=2` to the `dotnet` command here https://github.com/dotnet/orleans/blob/443d81c25e958d7c4c06d60bd568c3975ba504f0/src/Orleans.CodeGenerator.MSBuild/build/Microsoft.Orleans.CodeGenerator.MSBuild.targets#L122

Alternatively, you can try to set the environment variable: `DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX` to `2`. If you try that, please let me know if it works

**Comment by Vhab** [comment]
Wasn't much of a shot. It was exactly as you said :)
Thank you.
The environment variable is a great workaround meanwhile as well.
