### ISSUE TITLE
Calling Grain from StreamProvider throws Serialization Exception

### ISSUE THREAD

**Issue by jonathansant** [dotnet/orleans#5795]
I am invoking a grain from within my stream provider to track incoming messages. This is working fine locally but _sometimes_ fails then running on multiple silos with the following errors:

```
System.Runtime.Serialization.SerializationException: Type 'System.Net.Http.HttpConnectionPoolManager' in Assembly 'System.Net.Http, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable.    at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(Type type)    at System.Runtime.Serialization.FormatterServices.<>c.<GetSerializableMembers>b__5_0(MemberHolder mh)    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)    at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)    at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()    at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
--

```

This is is where I'm using it: https://github.com/jonathansant/Orleans.Streams.Kafka/blob/d67a72f722055daa834d435138cb9c44ed731a3b/Orleans.Streams.Kafka/Core/KafkaAdapterReceiver.cs#L163

Please note that the call to the `MessageTrackingGrain` is `OneWay`

The Message tracking grain:
https://github.com/jonathansant/Orleans.Streams.Utils/blob/master/Orleans.Streams.Utils/MessageTracking/MessageTrackingGrain.cs

I not doing any grain calls with HttpConnectionPoolManager so I'm not sure why it's trying to serialize an HttpConnectionPoolManager

**Comment by ReubenBond** [comment]
@jonathansant my guess would be that some call is throwing an exception and that is transitively including the `HttpConnectionPoolManager` within it (eg, maybe it's an HTTP exception).

Do the logs contain more details?

**Comment by jpeters5392** [comment]
I ran into this same error and in my case it was the AWS client throwing an exception that included extra unserializable data.  Once I added a try/catch and returned a custom exception type without the extra data then this error went away.

**Comment by ReubenBond** [comment]
Closing since we have an answer
