### ISSUE TITLE
How to structure Grains for fast loading of historical data?

### ISSUE THREAD

**Issue by jeddawson** [dotnet/orleans#5797]
Hello and thanks for building such an incredible framework. I’m beginning the process of sorting out how to leverage Orleans in a major revision of a project that I work on and have several high level questions that I’m hoping to receive some guidance on so I can avoid starting down the wrong path. If there is a better place or way to ask these questions, I’d be happy to change venues. Also, since I feel that an example application to tie together some of these concepts would help me personally as well as other newcomers in the IoT space I am very interested in contributing an example/quick start once I have a solid path to head down.

The platform that I’m working on handles the dispatching of work to drivers with the complexity that it is a multi-tenant application so we need to ensure each organization’s data is exclusive to their users and tablets. We currently provide this by putting each tenant’s data in their own SQL DB that only their users have access to (every tenant has a connection string to the correct DB). The dispatchers are using a windows desktop back office application with a companion ReactJS web app for viewing realtime/historical locations and the drivers are using an Android tablet app. We currently tie this all together with a blend of RESTish (there’s some RPC endpoints in it too) WebAPI that makes heavy use of Azure Event Hubs for incoming data from the tablets (processing happens in windows services that are subscribed to the hubs something that we want to move to Orleans), uses SignalR for pushing realtime data to the browser, and loads most things out of each tenant’s SQL DB (which are not all in the same datacenter as the API).

So now that the “what” of what I’m trying to improve is out of the way, where I need help is how we’re going to best utilize Orleans to improve our API. Using Orleans for the basic activity of the application feels really straight forward (although perhaps I’m over simplifying it) in that we can easily assign a Job to a Driver and trigger a push notification to the Device that the driver is using. When data comes in from a Device we can use an Event Hub based stream to queue the processing of its data and push the new location to the web app in realtime with SignalR. The challenging part for me is how to structure all this so that historical data can be easily and quickly retrieved as well as avoid packing too much data into a single Grain.

An example of this is that dispatchers may want to see the path a driver traveled to get to a job. Currently we load that data from the tenant’s DB and I would assume that is still the best way to handle it since loading data for a single driver is relatively quick. Where performance becomes challenging is loading the location of all devices from a particular point in time. Would it be reasonable to have a `ITenantGrain.LoadDeviceLocationAsOf(DateTime time)` that returns a list of all devices with their last known location at that point in time? If so, what is the recommendation for implementing something like that? Would it work to asyncly iterate through all the devices asking each of them to figure out where they where (there can be 100 - 1000ish devices per tenant)? We currently make this perform reasonably well by constantly building per-minute time windowed data for each tenant that is persisted separately so we can grab the time window that holds the locations we’re looking for. This is expensive from a storage standpoint so we trash the time windows after 7 days and queries for older data become slow. This feels like an area of our application that we should be able to improve with the power of Orleans, but I’m struggling to come up with an architecture that feels like a winner (likely because my optics are based in the way we’ve already solved it). If the pre-calculated time windows are still the best bet, is there an example out there of how to do this in Orleans (essentially a per-minute list of all the location changes for all devices belonging to a tenant). 

This question is getting too long, so I’ll leave it rooted in the historical data persistence and retrieval for now and as I gain a better understanding of the Orleans way of accomplishing some of this I’ll drill into other challenging aspects of the application.

If there’s some documentation that I should be reading to help come up with a solution or an example that I should be referencing instead of asking for help, please share and I’ll gladly keep trying to sort this out on my own. Thank you very much for your time!

**Comment by Cloud33** [comment]
Can i persist the statistics first? (I understand that the data should not change) dynamically calculate the thermal data

**Comment by sergeybykov** [comment]
Sorry about delay. I was under the false impression this was replied to.

My impression is that you are asking a more general question of organizing data, and Orleans is only a factor in the picture because of how it helps load and keep pieces of state in memory on demand. The potential solutions seem to boil down to how to denormalize the data for efficient access in both OLTP style and querying of time series data. Did I get it right?

>Would it work to asyncly iterate through all the devices asking each of them to figure out where they where (there can be 100 - 1000ish devices per tenant)?

This could work at a low scale, but I'm afraid it's not sustainable or efficient.

The approach with per-tenant location history grains seems more scalable to me. That would help retrieve (and potentially store) historical data in a way that is more suitable for querying state of drivers at a point in time. Per-tenant data could be further partitioned by larger time windows (e.g. a grain per day/hour) or geo-location (a grain per geographic tile), to help the system scale.

I hope this helps. But I'm not 100% sure I answered your question.

**Comment by jeddawson** [comment]
@sergeybykov you definitely got it right and your advice on how to structure the grains does indeed help. I've taken a couple pretty naive stabs at this in our testing environment and feel like your advice has me on the right track. Thank you for taking the time to read my extra-long question and provide some valuable insight.

**Comment by sergeybykov** [comment]
Great! Can we close this issue now?

**Comment by jeddawson** [comment]
Yep, thanks @sergeybykov
