### ISSUE TITLE
Cannot build Orleans projects in Docker using Core 3 Preview

### ISSUE THREAD

**Issue by futzy314** [dotnet/orleans#5809]
So I am working on a project where we want to use Docker for builds and deployments.  We are using Orleans 2.3.6 and .Net Core 3 Preview 7.  Runs fine on my desktop, but when I try to build it in Docker (using the mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview7-buster image), I get this error:

`  It was not possible to find any compatible framework version
  The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
    - The following frameworks were found:
        3.0.0-preview7-27912-14 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

  You can resolve the problem by installing the specified framework and/or SDK.

  The .NET Core frameworks can be found at:
    - https://aka.ms/dotnet-download
/root/.nuget/packages/microsoft.orleans.codegenerator.msbuild/2.3.6/build/Microsoft.Orleans.CodeGenerator.MSBuild.targets(122,5): error MSB3073: The command ""/usr/share/dotnet/dotnet" "/root/.nuget/packages/microsoft.orleans.codegenerator.msbuild/2.3.6/build/../tasks/netcoreapp2.0/Orleans.CodeGenerator.MSBuild.dll" SourceToSource "/src/***.OrleansInterfaces/obj/Release/netstandard2.0/***.OrleansInterfaces.orleans.g.args.txt"" exited with code 150. [/src/***.OrleansInterfaces/***.OrleansInterfaces.csproj]`

If I manually install the .Net Core 2.2 SDK in the Docker container that comes with Core 3 Preview 7 SDK installed, then everything works fine.  But it seems like this should not be a necessary step.

**Comment by ReubenBond** [comment]
Hi @futzy314, we recently merged a fix for this: https://github.com/dotnet/orleans/pull/5799

The fix is available in nightly builds, which you can access using the instructions [here](https://github.com/dotnet/orleans#official-builds). We are also planning to include the fix in 2.3.7 which we intend to release within a week. I hope that helps

**Comment by futzy314** [comment]
Awesome information, thanks!

**Comment by ReubenBond** [comment]
No worries - I'll close this issue for now and we can reassess as needed.
