### ISSUE TITLE
Is there an API-level document？

### ISSUE THREAD

**Issue by Cloud33** [dotnet/orleans#5826]
Hope to provide API-level documentation

**Comment by sergeybykov** [comment]
We auto-generate API docs, and those XML files are included in the NuGet packages. We do not generate documentation pages for them yet.

**Comment by lfzm** [comment]
@Cloud33 You can look at this  [Swashbuckle.Orleans.SwaggerGen](https://github.com/lfzm/Swashbuckle.Orleans.SwaggerGen)

**Comment by sergeybykov** [comment]
@lfzm What is this?

**Comment by lfzm** [comment]
@sergeybykov Generate Swagger document components
