### ISSUE TITLE
NATS streaming provider

### ISSUE THREAD

**Issue by shersh** [dotnet/orleans#5840]
Are there any implemantations of streaming provider for Orleans and NATS ?

**Comment by sergeybykov** [comment]
Sorry, what's NATS?

**Comment by shersh** [comment]
Sorry for not explaining right away

NATS - The Cloud Native Messaging System
https://github.com/nats-io
https://nats.io/

**Comment by sergeybykov** [comment]
Thanks. we are not aware of a streaming provider for NATS. That would be a great project to add to https://github.com/orleanscontrib I think.

**Comment by shersh** [comment]
Okay, thanks!
