### ISSUE TITLE
not support on dotnet core 2.2?

### ISSUE THREAD

**Issue by wuzhenda** [dotnet/orleans#5843]
I make a demo  target platform dotnet core 2.2 but not build successfully. so I try the hello word  sample on 2.0,it runs OK.but if I change the  target framework to 2.2 it  also build failed.
![image](https://user-images.githubusercontent.com/1329895/62770211-1bdc5f80-bacd-11e9-81fd-b699f99db7c1.png)

and I read sample there are  1.x,2.0,2.1,2.3 but not get 2.2. so is that reason?

**Comment by wuzhenda** [comment]
![image](https://user-images.githubusercontent.com/1329895/62770598-edab4f80-bacd-11e9-97f8-dde6af55665f.png)

`严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB3073	命令“"dotnet" "C:\Users\Administrator\.nuget\packages\microsoft.orleans.orleanscodegenerator.build\2.4.0\build\..\tasks\netcoreapp2.0\Orleans.CodeGeneration.Build.dll" "@obj\Debug\netcoreapp2.2\codegen\HelloWorld.Interfaces.orleans.g.args.txt"”已退出，代码为 3。	HelloWorld.Interfaces	C:\Users\Administrator\.nuget\packages\microsoft.orleans.orleanscodegenerator.build\2.4.0\build\Microsoft.Orleans.OrleansCodeGenerator.Build.targets	83	
`

**Comment by sgyy** [comment]
输出类型是 “类库”，那么目标框架就应该选 .NET Standard 2.0

**Comment by ReubenBond** [comment]
> and I read sample there are 1.x,2.0,2.1,2.3 but not get 2.2. so is that reason?

The sample is Orleans version 1.x, 2.0, 2.1, 2.3 - not .NET Core version 1.x, 2.0, etc. 

.NET Core 2.2 does work. You may need to use package `Microsoft.Orleans.CodeGenerator.MSBuild`

**Comment by wuzhenda** [comment]
tks.that's the reason.
Microsoft.Orleans.CodeGenerator.MSBuild                -new             after  .NET Core 2.2
Microsoft.Orleans.OrleansCodeGenerator.Build         - old              before  .NET Core 2.2
