### ISSUE TITLE
Orleans doesn't build on Mac

### ISSUE THREAD

**Issue by kestess** [dotnet/orleans#5846]
at commit c9fe1b4a5b9542b31922aa46709d4055e0c8a556 (latest) I cloned, cd'ed to the dir, and then brought in:
Microsoft.Orleans.Core.Abstractions
Microsoft.Orleans.CodeGenerator.MSBuild
Microsoft.Orleans.Server
Microsoft.Orleans.Client
...using nuget.
I then used "nuget restore OrleansCrossPlatform.sln" and then "dotnet build OrleansCrossPlatform.sln" - I get this error:

/usr/local/share/dotnet/sdk/2.2.300/NuGet.targets(265,5): error MSB3202: The project file "/Users/john/orleans/orleans/src/Azure/OrleansAzureUtils/OrleansAzureUtils.csproj" was not found. [/Users/john/orleans/orleans/OrleansCrossPlatform.sln]

The error message speaks the truth - that file does not exist. How can I encourage it to show up? Did I not import something or is it a bad reference? How does one compile Orleans on a Mac?

**Comment by kestess** [comment]
After reviewing the docs I'm wondering if I need to revert dotnet from 2.2.300 to 2.0.something.

**Comment by kestess** [comment]
I also have the same error with the Linux build.

**Comment by sergeybykov** [comment]
We recently removed AzureUtils project via #5792. I forgot to update OrleansCrossPlatform.sln accordingly. Sorry about that.
