### ISSUE TITLE
IMembershipOracle not added to services in 2.4.0?

### ISSUE THREAD

**Issue by pinkfloydx33** [dotnet/orleans#5847]
Doing a test-run upgrade to 2.4.0 and my health-check hosted service, which is modeled partially off of the one in Samples\2.3, fails to resolve its dependency on `IMembershipOracle` when using `UseOrleans`, crashing the startup process. I don't see anything in the change log or reviewing the recent commits that indicates registration of this type was removed. I _do_ see that there is now another type implementing the `IHealthCheckParticipant` interface, `MembershipTableManager` (registration of which was added in DefaultSiloServices). I've update my hosted service to expect an `IEnumerable<IHealthCheckParticipant>` instead of just the `IMembershipOracle` and things are working smoothly now. Would this be the suggested work around?

**Comment by ReubenBond** [comment]
Thanks for reporting this, @pinkfloydx33 - we split `IMembershipOracle` into smaller parts in 3.0 and I broke how `IHealthCheckParticipant` in doing so. Appologies for this. I've opened #5985 to remove it entirely.

Pulling `IEnumerable<IHealthCheckParticipant>` from the container is the right approach for now.

**Comment by RehanSaeed** [comment]
Is there some documentation or sample code for how to implement a health check?

**Comment by ReubenBond** [comment]
@RehanSaeed there are no recommendations yet. A typical health check would perform a ping to a random, [PreferLocalPlacement] grain. Health checks are a good candidate for a contrib package, imho. This issue is closed, so it's best to open a new issue to track discussion

**Comment by RehanSaeed** [comment]
Could we hook into the ASP.NET Core health checks? If Orleans could implement the `IHealthCheckPublisher` interface somehow, then a HTTP endpoint for health checks could be added. The plus side is that the ASP.NET Core health checks already have a lot of extra checks implemented in the community for CPU, memory, disk, Azure Table Storage and whatever else.

```c#
public class ReadinessPublisher : IHealthCheckPublisher
{
    private readonly ILogger _logger;

    public ReadinessPublisher(ILogger<ReadinessPublisher> logger)
    {
        _logger = logger;
    }

    // The following example is for demonstration purposes only. Health Checks 
    // Middleware already logs health checks results. A real-world readiness 
    // check in a production app might perform a set of more expensive or 
    // time-consuming checks to determine if other resources are responding 
    // properly.
    public Task PublishAsync(HealthReport report, 
        CancellationToken cancellationToken)
    {
        if (report.Status == HealthStatus.Healthy)
        {
            _logger.LogInformation("{Timestamp} Readiness Probe Status: {Result}", 
                DateTime.UtcNow, report.Status);
        }
        else
        {
            _logger.LogError("{Timestamp} Readiness Probe Status: {Result}", 
                DateTime.UtcNow, report.Status);
        }

        cancellationToken.ThrowIfCancellationRequested();

        return Task.CompletedTask;
    }
}
```

**Comment by SebastianStehle** [comment]
You can just implement IHealthCheck: https://github.com/Squidex/squidex/blob/835274396f58f9b9f8f11bab8956639337a97a5b/backend/src/Squidex.Infrastructure/Diagnostics/OrleansHealthCheck.cs

or 

https://github.com/Squidex/squidex/blob/835274396f58f9b9f8f11bab8956639337a97a5b/backend/src/Squidex.Domain.Apps.Entities/Apps/Diagnostics/OrleansAppsHealthCheck.cs

**Comment by RehanSaeed** [comment]
Wonderful, thanks for the links.
