### ISSUE TITLE
[Question] How do I access the GrainService in the specified Silo?

### ISSUE THREAD

**Issue by cateatcatx** [dotnet/orleans#5849]
I have many silos with their own GrainService in my scenario. How do I access the GrainService in the specified Silo? So i can polling every GrainService in my clusters.

Any recommendations, suggestions etc would be much appreciated.

**Comment by sergeybykov** [comment]
In 3.0.0 we are adding a low-level public API for that - `IGrainServiceFactory.MakeGrainServiceReference(int typeData, string systemGrainId, SiloAddress siloAddress)`. It was needed to make [Orleans.Indexing(https://github.com/OrleansContrib/Orleans.Indexing) work as an add-on.
