### ISSUE TITLE
Massive GC when log debug is enabled

### ISSUE THREAD

**Issue by EranOfer** [dotnet/orleans#5851]
We performing a load testing on Orleans 2.3.4 with 500,000 unique grains.
We enabled log **level debug**, after we stopped the load the silo suffer from high rate of GC that never stop.

Profiling the issue we saw 

![image](https://user-images.githubusercontent.com/13414515/62870447-5559d880-bd22-11e9-8055-b50df1f86bae.png)

I think it came from ```tostrings```
![image](https://user-images.githubusercontent.com/13414515/62870872-0bbdbd80-bd23-11e9-9de7-6db1d0478a25.png)

![image](https://user-images.githubusercontent.com/13414515/62870891-15dfbc00-bd23-11e9-812b-10452ad97002.png)

**Comment by sergeybykov** [comment]
That's expected with the high expense of debug level logging. The recommendation for production is to set the log level to `Info`.

**Comment by EranOfer** [comment]
Sounds good, thanks, you might want to consider adding a warning in the startup similar to the GC warning shown if configuration is incorrect.

**Comment by daniellm** [comment]
To clarify, the code's performance here is O(N^2), which is less than ideal, regardless of the fact that debug logs create overhead. Any reason not to use a StringBuilder here?

**Comment by sergeybykov** [comment]
>Any reason not to use a StringBuilder here?

No reason really. I guess we just didn't consider it important enough. Totally open to improvements.

>you might want to consider adding a warning in the startup similar to the GC warning shown if configuration is incorrect.

I like this idea. Opened #5873 for it.
