### ISSUE TITLE
Is there an example for AzureQueue streams in Orleans?

### ISSUE THREAD

**Issue by ahamdev** [dotnet/orleans#5866]

**Comment by hamsa-devarajegowda** [comment]
I am looking for an example for azure queue  streaming with explicit subscription. I looked over orleans/dotnet repo but couldn't come up with a sample implementation like ChatRoom application.

**Comment by sergeybykov** [comment]
I suggest you take a look at the test code - https://github.com/dotnet/orleans/blob/master/test/Extensions/TesterAzureUtils/Streaming/AQStreamingTests.cs.
