### ISSUE TITLE
how to call outside method  in grains?

### ISSUE THREAD

**Issue by wuzhenda** [dotnet/orleans#5869]
I have netty as frontend. the msg from device can pass throuth netty then we have a cluster to handler the msg. but how to send response  through netty to device?

I do got some method to do the job without orleans. but I 'd like to know the  orleans' way.

**Comment by sergeybykov** [comment]
If you need grains to send messages to devices, there's usually one of two ways.

1. If you already have a system for sending messages to devices, you can have grains make calls to that system.

2. If devices are connected to frontend web servers (via web sockets or HTTP long polling), you need grains to notify respective frontend servers. This can be done either via client observers or streams.

**Comment by wuzhenda** [comment]
way 1: can grains directly call the system's method,even we don't know where the grain exactly run in the cluster?

way 2:seems like the sample gps tracker do.
