### ISSUE TITLE
ConfigureFileLogging hangs/crashes TestCluster

### ISSUE THREAD

**Issue by fuocor** [dotnet/orleans#5870]
With the master branch of Orleans and netcore sdk 3.0.100-preview9-013803 
Having ```TestClusterBuilder.Options.ConfigureFileLogging == true```  the ```TestCluster``` will  hang or crash  ```TestClusterBuilder.Deploy()``` or ```TestClusterBuilder.DeployAsync()``` with 

```
Could not load type 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```

rich

**Comment by ReubenBond** [comment]
Fixed by #5943
