### ISSUE TITLE
Cannot find generated GrainReference class for interface

### ISSUE THREAD

**Issue by shersh** [dotnet/orleans#5878]
Strange behaviour.
When I registering IClusterClient in Dependncy Injection and use it in other parts of application exception "Cannot find generated GrainReference class for interface" will be raised. 

But, if I call GetGrain<> during registration - everything will be ok and no errors. 

What's wrong?

**Comment by ReubenBond** [comment]
Do you have the `Microsoft.Orleans.CodeGenerator.MSBuild` package installed on the project with the Grain interfaces and Grain classes?

**Comment by shersh** [comment]
@ReubenBond yes. I will provide repo for reproduce

**Comment by shersh** [comment]
You can check https://github.com/shersh/OrleansDIBug for reproducing this behaviour.

Currently it will raise error. 

But if you uncomment             https://github.com/shersh/OrleansDIBug/blob/bea91c7a211a0fb29c803553b6eef9b324b3f589/OrleanAzureClient/Startup.cs#L29

everything will be ok

**Comment by ReubenBond** [comment]
How do I run the client? I'm not familar

**Comment by shersh** [comment]
It's Azure Function.
You can find information here how to run locally: https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs

**Comment by ReubenBond** [comment]
This looks like an issue with how Azure Functions builds/packages your application.

If I add `typeof(IUserGrain).Name.ToString();` to the top of the `Configure(...)` method then everything works.

**Comment by shersh** [comment]
Yeah, I see. Thanks I will send issue to Azure Functions contributions team for this case. 
Thanks!

**Comment by ReubenBond** [comment]
Happy to help, @shersh!
