### ISSUE TITLE
InterfaceMethod null in call filter

### ISSUE THREAD

**Issue by wiezykrwi** [dotnet/orleans#5886]
We have a call filter to log errors. After migrating from 2.2 (core) and 2.0 (server) to more recent versions (2.4.1) we noticed that some of these methods are empty. The correct method is still being called, though.

We noticed the problem with a method called "Create", but the same name on another grain works just fine. Because it works fine on another grain I don't think we can work on reproduction code easily, is there something I can send you (like the generated code) that could help you look into this?

I don't think our call filter itself is very out-of-the-ordinary:

```
public class ErrorHandlingCallFilter : IIncomingGrainCallFilter
{
    public ErrorHandlingCallFilter(ILogger<ErrorHandlingCallFilter> logger) ...

    public async Task Invoke(IIncomingGrainCallContext context)
    {
    	try
    	{
    		await context.Invoke();
    	}
    	catch (Exception exception)
    	{
    		// context.InterfaceMethod is null
    		await logger.Error(context.Grain.GetPrimaryKeyString(), context.InterfaceMethod?.Name, exception);
    	}
    }
}
```

**Comment by ReubenBond** [comment]
This ought to be improved now, since https://github.com/dotnet/orleans/pull/6004
