### ISSUE TITLE
Optimize GrainLifecycle

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#5904]
Hi,

I think it would be good to optimize GrainLifecycle regarding memory consumption.

In my example I have a lot of grains and a lot of the consumed memory comes from GrainLifecycle.

Just from an example: 

![image](https://user-images.githubusercontent.com/1236435/63641567-d0bb7280-c6b0-11e9-84ee-5df00ef129b1.png)

**Comment by sergeybykov** [comment]
Linking #5907.

**Comment by sergeybykov** [comment]
Absolutely!
