### ISSUE TITLE
[Question] Is is possible to run Orleans on top of Kestrel?

### ISSUE THREAD

**Issue by cosmintiru** [dotnet/orleans#5906]
Is it possible to run Orleans on top of Kestrel given the networking rewrite from 3.0? Is there an example of this or a hint over how I might achieve this (if possible)?

Will this enable scale-out scenarios using Azure App Services?

**Comment by SebastianStehle** [comment]
Orleans uses a binary protocol, kestrel is a HTTP server.

But you can co-host it with ASP.NET Core and talk with grains from controllers.

**Comment by cosmintiru** [comment]
I know, but there are a couple of appealing notes from the beta release and the main PR from networking rewrite

1. Replaced networking stack with the Bedrock layer of ASP.NET Core (https://github.com/dotnet/orleans/releases/tag/v3.0.0-beta1)
2. The core purpose of this is to modernize the networking stack and eventually support implementing TLS (#828). In addition, Orleans gains improved support for non-TCP/non-Socket networking, including the ability to host on Kestrel. (https://github.com/dotnet/orleans/pull/5436)

**Comment by SebastianStehle** [comment]
Interesting

**Comment by cosmintiru** [comment]
Thank you @ReubenBond !

The network rewrite seems to open a whole new slew of opportunities. Also, interesting option using Azure SignalR service for transport.

**Comment by cosmintiru** [comment]
I was just wondering, given the flexibility of the new stack, would Hybrid Connections be an option for enabling Orleans on App Services?

If you find it feasible I can try to play around with it.

https://docs.microsoft.com/en-us/azure/app-service/app-service-hybrid-connections#add-and-create-hybrid-connections-in-your-app

**Comment by veikkoeeva** [comment]
WebApp with SignalR would be interesting since the infrastructure setup and deployment model is so slick, also it's cheap. Superficially it also feels it would become possible to run Orleans on Cloudflare Workers (have something like https://github.com/anywhichway/thunderclap as the backend) @cosmintiru does what you look into require ASE (and hence be more expensive)?

**Comment by cosmintiru** [comment]
@veikkoeeva , my gut feeling is that using the new primitives from Bedrock to trick Orleans into using relay connections (Hybrid connections) rather than P2P or SignalR, and that's not ASE dependent.

**Comment by veikkoeeva** [comment]
@cosmintiru Interesting idea! :)

**Comment by cosmintiru** [comment]
Hm, I just bumped into this: https://github.com/Azure/azure-relay/blob/master/samples/hybrid-connections/dotnet/portbridge/README.md

What if we can implement a side car that sits in the same app service sandbox but leverages the communication between multiple app services nodes via hybrid connections? 

If this works as I understood, then it will require few to no changes in the main networking stack (and if there are required changes, probably those will resume to some configuration knobs) and probably it will be usable with pre-3.0 Orleans.

**Comment by cosmintiru** [comment]
Ok, I've managed to deploy a simple web app that starts an Orleans silo inside a hosted service and against known machines.
![image](https://user-images.githubusercontent.com/6203490/63853144-9ef12700-c9a2-11e9-9b1e-97bd1f3da302.png)

The idea is that each silo will use a loopback address as advertised IP, while the side car that runs on that particular machine will do the following:
1. Register as a service the translated IP address of the machine (from 10.x.x.x to 127.x.x.x) against HC in order for it to listen for connections
2. Register as clients the rest of the known silos as proxy addresses (127.x.x.x) 

The idea is simple, once the row from the clustering provider is pulled down, it will actually point to a loopback address that will pump the message to the correct listener.

Problems:

1. Kind of hard to make sure the side car is properly running (needs proper instrumentation) and it doesn't automatically load. I have to manually forge requests and make sure that all the nodes are up and running. This might be fixable by switching to an aspnet core process with OutOfProcess hosting. 

2. The hybrid connections need to be created via ARM. A potential fix for this would be to enable Managed Identity for app services and issue a JSON template against management.azure.com, given that the app has the appropriate rights.

3. The ability to dynamically register new silos. I'm not very familiar with the inner workings of Orleans, but I'd expect to be able to hook into the membership table and issue requests against side car whenever a new fella comes into town (or old one leaves).

**Comment by ReubenBond** [comment]
I think we should revisit this in the 3.1.0 timeframe. There is still a bunch of work on the Bedrock side of things which is underway and that work will enable user-friendly, custom, customizable transports.

**Comment by ReubenBond** [comment]
We may revisit the idea of custom transports in the future (it's possible today, but not developer-friendly) but right now there does not seem to be a strong need for running Orleans' networking layer on Kestrel itself. So, I'll close this and we can open a new issue if a need arises.

Additionally, Orleans supports Azure App Service now: https://learn.microsoft.com/en-us/dotnet/orleans/deployment/deploy-to-azure-app-service
