### ISSUE TITLE
Add compression for messages

### ISSUE THREAD

**Issue by eisendle** [dotnet/orleans#5924]
Hi,

In my use case calls to grains return a table like structure which contains lots of duplicate strings. So this would be a good candidate for gzip compression. I´m aware of custom serialization, but maybe compression would be better suited at the transport layer of orleans.
Thanks to the bedrock integration in Orleans 3.0 this should be much easier to implement. Additionally as bedrock is foundation of Kestrel, possibly there already some code in Kestrel which could be reused.

If there is consent about adding this feature and there is a design how this will be configured, I would be happy to contribute this feature (if you guys point me to the right location where this could and should be added.)

**Comment by sergeybykov** [comment]
Migration to Bedrock should enable such scenarios. Although we might need to expose additional hooks. Of course, you can always change the argument type to `byte[]`, and perform serialization and compression outside of the whole pipeline. But that's, obviously, cumbersome.
