### ISSUE TITLE
Unable to use TestSilo on 3.0

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#5925]
According to this https://github.com/dotnet/orleans/blob/dad62cc16d4d6de671563f6b1e54196f617926a5/src/Orleans.Core/Logging/FileLogger.cs#L141 it looks like we're depending on the _old_ pubternal types there were all removed on .Net Core 3.0. 

With that we're unable to run unit test using the TestCluster as it fail to start with this:

```
warn: Microsoft.Orleans.Networking[0]
      Connection to endpoint S127.0.0.1:25980:0 terminated with exception System.AggregateException: An error occurred while writing to logger(s). (Could not load type 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.)
       ---> System.TypeLoadException: Could not load type 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
         at Orleans.Logging.FileLogger.BeginScope[TState](TState state)
         at Microsoft.Extensions.Logging.ScopeLogger.CreateScope[TState](TState state)
         at Microsoft.Extensions.Logging.Logger.BeginScope[TState](TState state)
         --- End of inner exception stack trace ---
         at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
         at Microsoft.Extensions.Logging.Logger.BeginScope[TState](TState state)
         at Orleans.Runtime.Messaging.NetworkingTrace.BeginScope[TState](TState state)
         at Orleans.Runtime.Messaging.ConnectionManager.BeginConnectionScope(Connection connection)
         at Orleans.Runtime.Messaging.ConnectionManager.<>c__DisplayClass19_1.<<ConnectAsync>b__0>d.MoveNext()
```

And the test silo is killed.

I've tried to avoid to load Orleans provider but it looks like it doesn't not respect my `ClearProviders` call and add its own anyway:

```
hostBuilder.ConfigureLogging(log =>
            {
                log.ClearProviders();
                log.AddConsole();
            });
```

According to https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.abstractions.internal.nullscope?view=aspnetcore-2.2&viewFallbackFrom=aspnetcore-3.0 the type indeed was removed...

Any workarounds for now?

Thanks!

**Comment by galvesribeiro** [comment]
It looks like the issue is caused by https://github.com/dotnet/orleans/blob/7846ffe80134aaae2bba4d2b6aa573ec0fee83c0/src/Orleans.Core/Logging/FileLoggerProvider.cs#L21

This is creating a `FileLogger` that is using the `NullScope` type. That provider is being added regardless if I call this:

```
 hostBuilder.Configure<TestClusterOptions>(opt =>
            {
                opt.ConfigureFileLogging = false;
            });
```

**Comment by galvesribeiro** [comment]
Ping @sergeybykov @ReubenBond

**Comment by sergeybykov** [comment]
The plan is to upgrade all our core dependency packages to their latest pre-release versions for 3.0.0-beta2. We think that should resolve issues like this.

**Comment by galvesribeiro** [comment]
Ah ok. That is cool. I thought 3.x would have that upgraded since it wont be released before .Net Core 3 if I understood correctly.

**Comment by sergeybykov** [comment]
3.0.0 final indeed won't be released before .NET Core 3. But we'd like to have another beta out before then.

**Comment by galvesribeiro** [comment]
Looking forward to it :)
