### ISSUE TITLE
silo to silo conncetion

### ISSUE THREAD

**Issue by SaeedBolhasani** [dotnet/orleans#5927]
Hi every body.
I have two different silos let say silo1 and silo2. there is a grain is silo2 named IEmailSender.
I want to connect to IEmailSender from silo1. i tried to build a clusterClient in silo1 to connect to silo2. it does not working. what is best practice to establish this connection?

**Comment by ushenkodmitry** [comment]
May be related #5778.

**Comment by ReubenBond** [comment]
@SaeedBolhasani did your question get answered?

Silos do not need to have a separate client to connect to each other: they connect automatically. We can talk about this more if you want.

**Comment by SaeedBolhasani** [comment]
> @SaeedBolhasani did your question get answered?
> 
> Silos do not need to have a separate client to connect to each other: they connect automatically. We can talk about this more if you want.

Hello my good friend. thank you very much. i mean two different silo. no silos in one cluster. are you sure?

**Comment by ReubenBond** [comment]
Two different clusters? Ok, yes, that is not as simple. In that case you can possibly use separate `ClusterClient` but be careful: do not store grain reference which belong to a different cluster in a grain's state and do not send them remotely from a grain.

Could you tell me more about your use case?

**Comment by SaeedBolhasani** [comment]
> Two different clusters? Ok, yes, that is not as simple. In that case you can possibly use separate `ClusterClient` but be careful: do not store grain reference which belong to a different cluster in a grain's state and do not send them remotely from a grain.
> 
> Could you tell me more about your use case?

I am very glad to conversation with you. i decide to use every micro services as a silo and its dependencies.so i have identity silo and accounting silo. i want to use identity silo from accounting silo by the way i am beginner in orleans. yes i used separate clusterclient to connect to other clusters. i don't understand "remotely" can you tell me more please?
