### ISSUE TITLE
GrainClient is failing to initialize in ASP.NET

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#593]
This was reported by @Maarten88 on Gitter.

GrainClient is failing to initialize in ASP.NET unable to load OrleansAzureUtils.dll. This is a regression and a showstopper for 1.0.9.

I tracked it down to AssemblyLoader.LoadAndCreateInstance<T> which assumes that the target assembly (OrleansAzureUtils.dll) is in the same directory as executing assembly (Orleans.dll). This is not the case in ASP.NET which puts these assemblies into separate directories.

I'm pretty sure the same should happen to OrleansZooKeeperUtils.dll but I didn't test that.

I'll submit a PR with a fix shortly.

**Comment by gabikliot** [comment]
Closed via #594 .
