### ISSUE TITLE
How to setup connectivity between silo and client, if first one lives in docker container and second does not?

### ISSUE THREAD

**Issue by YMichurin** [dotnet/orleans#5938]
Is it possible to setup Orleans cluster the way silos deployed under docker container, while Orleans client (service that calls grains) to be a regular Windows service? The problem I experince in the configuration is that silos register themselves under docker subnet ips in a membership table (MongoDb in my case), and then client tries to call gateway (port 11111) with their own docker ips, but dockers are not accessible under their own ip from host system, at least I do not know how to configure it. Instead the gateway accessible under host machine ip with 11111 port if you map it to a host port when running docker container. However client reads docker container IPs from mongo, not their host ips.  Anyone have an idea on how to get around it or set it up properly? Thanks

**Comment by JanEggers** [comment]
had the same issue.

I solved it by adding the host IP as adverticed host name.

**Comment by YMichurin** [comment]
> 
> 
> had the same issue.
> 
> I solved it by adding the host IP as adverticed host name.
> 
> ```
>             .ConfigureEndpoints(Environment.GetEnvironmentVariable("ORLEANS_HOST_IP"), SiloPort,
>                 GatewayPort, listenOnAnyHostAddress: true)
> ```

Got it, thanks. But then can you suggest me how to dynamically pass host ip into container on docker composer? I see you set env. variable ORLEANS_HOST_IP to host machine ip, but then where you get it from? As host ip might change I think it must be taken dynamically

**Comment by JanEggers** [comment]
https://github.com/dotnet/orleans/issues/4478#issuecomment-381757993
