### ISSUE TITLE
Retain producer-side stream filtering

### ISSUE THREAD

**Issue by cata** [dotnet/orleans#5939]
**Background**

Producer-side stream filtering is to be removed in an upcoming revision of Orleans (per ~#5408~ #6711).
See relevant Gitter excerpts below:
* [August 13, 2019 3:04 PM](https://gitter.im/dotnet/orleans?at=5d535e35d03a7c63e62256d5)
* [August 14, 2019 7:23 AM](https://gitter.im/dotnet/orleans?at=5d5443ad9507182477d9d6be)
* [August 14, 2019 8:04 AM](https://gitter.im/dotnet/orleans?at=5d544d494e17537f522fbd4e)

In short, the intent is to remove the feature due to maintainability and design-related concerns in the face of the pub-sub system becoming a public surface.
My understanding is that the primary design concern stems from the way the filter predicate is specified.  In the current implementation, the identity of the filter predicate (represented by a class name and method name tuple) is supplied by the subscribing party. In addition to constraining  eligible predicates to  static methods, the mechanism used to extract this identity employs delegates and leads to an undesirable dependency whereby the predicate function must be available to both producer and consumer. While this may appear fairly benign in the case in which both the producer and the consumer are grains, this requirement becomes harder to justify when consuming streams from an Orleans client. 

**Advocating for retaining producer-side filtering** 

> Please note that the scenarios described below have been significantly simplified for the sake of brevity

We use per-grain streams to publish incremental grain state changes, in a variation on event sourcing. Clients subscribe to these streams to render changes to grain state in real time. Upon subscribing, a new client receives an optimized version of the change log, allowing it to "catch-up" with the current grain state - we are currently using the feature in production to selectively deliver this class of messages to only the newly subscribed client. 

In addition to simple state(s), grains can hold collections - changes to these collections are similarly propagated to clients in real time. Clients can construct queries over these collections, the results of which are also updated in real time - we are currently using the feature in production to selectively deliver initial query results to only the client that has made the query. 

Continuing to be able to filter such messages on the producer side is very important to us.

**Possible approaches to retaining producer-side filtering**
 
It appears that allowing arbitrary client-supplied predicates while addressing the coupling concern would require serializing the predicate closure provided by the consumer at subscription time and then deserializing and executing it on the producer side.
While serializers that could be used to implement such behavior exists (e.g. [FsPickler](https://github.com/mbraceproject/FsPickler), [Hyperion](https://github.com/akkadotnet/Hyperion)), It is unclear to me at this point whether the added complexity is warranted and how such complexity would impact the goal of having an easily-maintainable public pub-sub surface.

A more conservative approach would avoid passing predicate identity during subscription altogether and instead rely on the predicate being supplied on the producer side, at the time of event emission. A subscriber would continue to be able to attach custom data to the subscription, data that could be used on the producer side to affect predicate logic. 
It is of note that this approach, while not requiring the subscriber to supply the predicate identity, would continue to allow the subscriber to choose a specific predicate logic out of a well-known set of choices available producer-side, by means of adequately constructed custom subscription data.

I am proposing adopting the latter approach, based on its relative simplicity and on the fact that it allows for a straightforward migration path - please let me know if this would be acceptable in principle. If so, I will try to modify the current implementation and tests accordingly and submit a PR

Please also let me know if you would like to discuss any of the above offline, I am more than happy to do so.

**Comment by jason-bragg** [comment]
What stream provider are you using?
Do different consumers use different predicates? That is, are there consumer specific predicates, or is a single predicate used for all consumers?

**Comment by cata** [comment]
@jason-bragg 

Hi Jason, thank you for responding!

We are currently using SMS for the streams in question.
There is a single predicate for all consumers of a given stream.
The predicate filters messages based on consumer identity, which is supplied by each consumer via `SubscribeAsync`'s `filterData` parameter.

**Comment by cata** [comment]
A replacement stream filtering mechanism that meets our needs has been implemented in #6739
Thank you @benjaminpetit!
