### ISSUE TITLE
Double serialization/deserialization for exceptions thrown in Grains marked as transactional

### ISSUE THREAD

**Issue by erikljung** [dotnet/orleans#5941]
When throwing custom exceptions in a transactional grain method the exception gets serialized and deserialized twice and then set as inner exception on a OrleansTransactionAbortedException. Is the double serialization/deserialization of the custom exception by design? Just trying to understand if this is a correct behaviour, since this doesn't seem to be the case in a non transactional method.

**Comment by jason-bragg** [comment]
Transactions are not normal grain calls, they are distributed operations.  In general they are about 3x (or more) more expensive than normal grain calls

As distributed operations, when there is a failure, errors may go through a couple hops to get back to the caller, so this is not surprising.  I'd not call this 'as designed' as much an expected error handling path which may be further optimized.
