### ISSUE TITLE
Demonstration package My-First-Orleans-Application.md does not compile

### ISSUE THREAD

**Issue by JustinMinnaar** [dotnet/orleans#5957]
I spent an hour trying to get this simple demo application to compile. It seems there is something wrong with the references, or packages. Surely having a simple step-by-step demo is a good idea for this project?

**Comment by benjaminpetit** [comment]
If I am not mistaken, this tutorial is based in an old version of Orleans (1.5.x). I suggest you to look the Samples from this repository: https://github.com/dotnet/orleans/tree/master/Samples

**Comment by ReubenBond** [comment]
This doc has since been deleted and there are many new and updated samples now, with brief documentation: https://github.com/dotnet/orleans/tree/main/samples#readme
