### ISSUE TITLE
Custom Log Event Store

### ISSUE THREAD

**Issue by rossbuggins** [dotnet/orleans#5962]
Hi,

I'm looking at implementing a custom storage provider - I would like to be storing the events for a Journaled Grains.  Could you please clarify if i need to implement a custom storage provider as well as the grains implement ICustomStorageInterface.

Also on storage providers, whats the difference between IStorageProvider and IGrainStorage - i.e. when is the IProvider implementation of IStorageProvider  used?

I've been going through the documenation, just a little confused at the moment. Thanks,
Ross

**Comment by rafikiassumani-msft** [comment]
@rossbuggins Are you still looking for guidance on implementing a custom storage provider?
