### ISSUE TITLE
Multiple message from  same stream cause  repetitive activation in consumer  

### ISSUE THREAD

**Issue by SalimiHabib** [dotnet/orleans#5964]
Hi

### Playground:

grain **A**  have a method to send message in `OnNextAsync` of stream **ST** to implicitly subscribed grain **B**  .  

In grain **B** there is initialization that need to perform in `OnActivateAsync()` of  grain **B** also subscription to stream **ST** and a lambda function to perform action on receiving message   .

project setup as 
`<TargetFramework>netcoreapp2.2</TargetFramework>`

` <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.2.0" />
    <PackageReference Include="Microsoft.Orleans.Clustering.AdoNet" Version="2.4.2" />
    <PackageReference Include="Microsoft.Orleans.OrleansGoogleUtils" Version="2.4.2" />
    <PackageReference Include="Microsoft.Orleans.Persistence.AdoNet" Version="2.4.2" />
    <PackageReference Include="Microsoft.Orleans.Reminders.AdoNet" Version="2.4.2" />
    <PackageReference Include="Microsoft.Orleans.Server" Version="2.4.2" />
    <PackageReference Include="Microsoft.Orleans.Transactions" Version="2.4.2" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.9.5" />
    <PackageReference Include="Orleans.Providers.MongoDB" Version="2.7.0" />`

host builder setting 

` UseLocalhostClustering(siloPort, gatewayPort)
                    .Configure<ClusterOptions>(options =>
                    {
                        options.ClusterId = Guid.NewGuid().ToString();
                        options.ServiceId = Guid.NewGuid().ToString();
                    })
                    .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(PersonGrain).Assembly).WithReferences())
                    .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(ConnectionRegistrarGrain).Assembly).WithReferences())
                    .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(OpmGrain).Assembly).WithReferences())
                    .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(DcGrain).Assembly).WithReferences())
                    .AddMemoryGrainStorageAsDefault()
                    .AddMemoryGrainStorage("MainGrainStorage")
                    .AddMemoryGrainStorage("PubSubStore")
                    .AddSimpleMessageStreamProvider(AcoConstant.GlobalSmsStreamProvider,
                    op=> {
                        op.PubSubType = Orleans.Streams.StreamPubSubType.ExplicitGrainBasedAndImplicit;
                        })
                    .AddMemoryStreams<DefaultMemoryMessageBodySerializer>(AcoConstant.RegisterDcStreamNameSpace)
                    .AddMemoryStreams<DefaultMemoryMessageBodySerializer>(AcoConstant.RequestForDcRegistrationStreamNameSpace)
                    .AddMemoryStreams<DefaultMemoryMessageBodySerializer>(AcoConstant.DiscardTheRequestForDcRegistrationStreamNameSpace)
                    .ConfigureLogging(logging => {
                        logging.AddConsole();
                        logging.SetMinimumLevel(LogLevel.Trace);
                        })
                    .UseInMemoryReminderService();`

### Problem:
When multiple activation of grain **A**  send message  to grain **B** it case repetitive activation in grain **B** without previous saved status of grain **B**  and eventually only  first saved state exist in gran **B** . 
grains primary key and stream namespace already checked in sender and receiver , `AddSimpleMessageStreamProvider ` and  `AddMemoryStreams` used in silo host builder .
after some test found out that changing `OnActivateAsync()`  to non async task case  **e-Tag mismatch in Memory Storage. Stored**   exception  .   
is there any missed config or some other issue that must be considered ?

(next day 22 sep) 
some new discover ;
after trace into source server `Orleans.Storage.InconsistentStateException` appear  on ` WriteStateAsync()` method of `StateStorageBridge<TState>` .

debug output on exception as below 

`Exception thrown: 'Orleans.Storage.Internal.MemoryStorageEtagMismatchException' in OrleansProviders.dll
Exception thrown: 'Orleans.Storage.Internal.MemoryStorageEtagMismatchException' in System.Private.CoreLib.dll
Exception thrown: 'Orleans.Storage.Internal.MemoryStorageEtagMismatchException' in System.Private.CoreLib.dll
Exception thrown: 'Orleans.Storage.Internal.MemoryStorageEtagMismatchException' in System.Private.CoreLib.dll
Exception thrown: 'Orleans.Storage.Internal.MemoryStorageEtagMismatchException' in System.Private.CoreLib.dll
Exception thrown: 'Orleans.Storage.InconsistentStateException' in OrleansProviders.dll
Exception thrown: 'Orleans.Storage.InconsistentStateException' in System.Private.CoreLib.dll
` 

after this error grain deactivated and reactivate for handling next message from stream.
other save process  with call to grain work normally (also first message from stream) .

grain **A** method  is 

 
                
                if (!State.DcCreationRequest.inProcess)
                {
                    State.DcCreationRequest = (dc, DateTimeOffset.Now, memo, true);

                    var a = this.GetPrimaryKey();

                   await _dcRegistrationRequestStream.OnNextAsync(a) ;
                   
                    await WriteStateAsync();

                    return await Task.FromResult(true);
                }

                return await Task.FromResult(false);
            }`

and action in grain **B** subscribe  method is  

```
                     {
                      State.DcCreationRequests.Remove(value);
                 
                        return Task.CompletedTask;
                       } 
```

if it is not miss config then may be there is regression like  #5086 

thank you

**Comment by sergeybykov** [comment]
I'm not sure I understand the following part:
>When multiple activation of grain A send message to grain B it case repetitive activation in grain B without previous saved status of grain B and eventually only first saved state exist in gran B 

Even if there are multiple parallel attempts to activate grain B, only one of them will successfully register the grain in directory, and then its `OnActivateAsync()` method is called. What is the "first saved state" that you are referring to?

**Comment by SalimiHabib** [comment]
As you can see in below test method there is 2 consecutive call for `AddNewDcCreationRequest` method in `personGrain0` and `personGrain1` this grain have 2 separate id  . 

These calls make a
 stream call `(await dcRegistrationRequestStream.OnNextAsync(a) ;) to` dcGrain before saving person grains state( showed as grain A method  in previous section)  .

Dcgrain have state initialization in `OnActivateAsync()` as below 

```
`if (!State.Initialized)
                {
                    // do initialization
                    if (State.RelatedPersons == null) State.RelatedPersons = new Dictionary<string, List<Guid>>();
                    if (State.Messages == null) State.Messages = new Queue<(DateTimeOffset, string)>();
                    State.Initialized = true;
                    await WriteStateAsync();
                }`
```

dcgrain is consumer of stream that was created by person grain and it is expected that dcgrain after runnig test have 2 record of  `AddNewDcCreationRequest` in its state but there is randomly 1 and 2 record was saved.
as mentioned earlier after tracing  into source server It was found that second save in dcgrain (case of second stream call from second person grain) will not success because of `Exception thrown: 'Orleans.Storage.Internal.MemoryStorageEtagMismatchException' in OrleansProviders.dll Exception thrown:`
and grain reactivate with no saved state and this case to new initialization and finally only one record saved It is noteworthy sometimes it save 2 record but rarely and just in time of debug .

if there is better way to trace the run time may be it  to be clearer

**Test method** 
```

 [Fact]
        public async Task RequestToCreateNewDc()
        {
            var p0 = Guid.NewGuid();//person reference
            var p1 = Guid.NewGuid();//person reference

            // get a brand new grain to test
            var personGrain0 = _fixture.GrainFactory.GetGrain<IPersonGrain>(p0);
            var personGrain1 = _fixture.GrainFactory.GetGrain<IPersonGrain>(p1);
 
            //DC info for request to create 
            DcInfo dci0 = new DcInfo()
            {
                Address = "DcInfoAddress",
                CellUnionId = "DcInfoCellUnionId",
                CommonName = "DcInfoCommonName",
                Coordinate = "DcInfoCoordinate",
                Phone = "DcInfoPhone",
                Pic = "DcInfoPic",
                PublicAddress = "DcInfoPublicAddress"
            };

            DcInfo dci1 = new DcInfo() 
            {
                Address = "DcInfoAddress1",
                CellUnionId = "DcInfoCellUnionId1",
                CommonName = "DcInfoCommonName1",
                Coordinate = "DcInfoCoordinate1",
                Phone = "DcInfoPhone1",
                Pic = "DcInfoPic1",
                PublicAddress = "DcInfoPublicAddress1"
            };

            //send request (by scanning bar code of request in web site)  
            var r0 = await personGrain0.AddNewDcCreationRequest(dci0, "memo from  p0");
            var r1 = await personGrain1.AddNewDcCreationRequest(dci1, "memo from p1");
            Assert.True(r0);
            Assert.True(r1);
```

**Comment by jason-bragg** [comment]
I suspect a race condition on dcGrain which is leading to duplicate activations, but I can't be confident of that without more info.

Are any of these grains stateless workers?
What storage does dcGrain use.
What stream provider are you using?
Are you using implicit or explicit subscriptions?

**Comment by SalimiHabib** [comment]
Fallowing repository contain project that similar to real project ,it contain only object that related to issue   
 ( To speed up and reduce ambiguity in the subject ).

 As noted in comment of  ` Test1Async()` method `UnitTest1` class ,It is expected that equal to 2 but  it return 1 .

### Repository  link
`https://github.com/SalimiHabib/MustRemove.git`

**Comment by jason-bragg** [comment]
@SalimiHabib, thanks for repo link.  The pattern looks good.  That *should* work.

That pattern should not be susceptible to the duplicate activation problem I speculated upon.

When it fails do you see any errors in the logs?

I noticed that the OnNextAsync lambda which processes the incoming guid no longer saves?  Why is that?  Without a safe, data could be lost if the grain is deactivated between stream messages.  I don't know why that would happen, but not willing to assume it's not given that something is causing the data loss.

I suggest adding the 'write' back into the OnNextAsync call.

I suggest adding trace logging to each step in the process to narrow down where things are going wrong.  

The component I'm least familiar with (hence more suspicious of) is the ADO storage provider.  I'm entirely unfamiliar with it's behaviors.  To remove it from speculation, would you mind verifying that the behavior persists when using memory storage?  If so, then we can rule out ADO storage as a potential source of the problem.

**Comment by jason-bragg** [comment]
I'd also suggest configuring the stream pubsub to be ImplicitOnly, so you don't need to configure PubSubStore, and we can rule out any stream subscription management issues.

As best practices, I suggest querying the stream for subscriptions (IAsyncStream<T>.GetAllSubscriptionHandles()), and calling ResumeAsync on the existing subscription rather than calling SubscribeAsync.  What you have works, but can mask issues.

**Comment by SalimiHabib** [comment]
### Changes
Repository has been updated base on suggestions as below :

- ` WriteStateAsync()` 'write' back into the `OnNextAsync()` call.
- ADO storage provider replaced by  memory storage
- Message stream provider configured as `StreamPubSubType.ImplicitOnly`
- Use  ` .ResumeAsync<Guid>()`  to attaches the processing logic to existing  subscription in `DcGrain`

 ### Results an observations

- exeption of  `Orleans.Storage.Internal.MemoryStorageEtagMismatchException` type **not thrown** 
- Break point in  `OnDeactivateAsync()` on `opmGrain  `always hit twice (expectation is one hit)
- It seams Process flow is unpredictable , Below  pic show result of test without any change in code( just running test again after receiving a pass in debug mode).
     
                               **Test passed in debug mode** 
![image](https://user-images.githubusercontent.com/23046553/66205726-fc237b00-e6ba-11e9-9880-fb958f8b66b8.png)


                                 **Test not passed without  debug ** 
![image](https://user-images.githubusercontent.com/23046553/66207090-b49eee00-e6be-11e9-825d-911961646bea.png)

-**No error or exception** was thrown and grain was activated twice .
-Some times in debug mode state of grain  filled with 2 record but next activation **clear** the state    .

**Comment by jason-bragg** [comment]
@SalimiHabib, thanks for the findings.  Good information.

Yes, the opmGrain should only be activated/deactivated once.  What ever is causing the duplicates is likely the source of our problem.

Looking at the test setup I noticed that the cluster information is being set to random values in the silo builder.  This will place each silo in it's own cluster, so a call to one silo (in it's own cluster) will place a grain on it, and a call to the other silo for the same grain will place a different grain on it because the silo is in a different cluster.  I suspect this is what's happening.  To resolve this one needs only remove the cluster options from the test silo configuration, as the test framework already sets that up, or set those values to some shared value.

If the issue persists, please provide logs of failed run.

**Comment by SalimiHabib** [comment]
@jason-bragg  Your solution was very precise and practical ,Thank you for your time

Based on your suggestion after changing  `var builder = new TestClusterBuilder(2)` to  `var builder = new TestClusterBuilder(1)`  The problem was solved   .
