### ISSUE TITLE
[SMSProvider] When multiple subscription handlers throw an exception, only the first exception can be caught

### ISSUE THREAD

**Issue by NilKu** [dotnet/orleans#5965]
Hi, I'm using Orleans 2.4.0 and currently playing around with Orleans streams, especially with the SMSProvider (FireAndForget - false).
Everything works fine, but I'm losing detailed failure results when multiple subscription handlers throw an exception.
```cs
Task result = null;
try
{
    result = stream.OnNextAsync(data);
    await result;
}
catch (Exception ex)
{
    // 'ex' and result.Exception contain only the first exception
}
```
This behavior is propagated from `Task.WhenAll` in [SimpleMessageStreamProducerExtension.cs](https://github.com/dotnet/orleans/blob/cc4749c9be837f3f6dd82ece9cb4ed7a9c5dc798/src/Orleans.Core/Streams/SimpleMessageStream/SimpleMessageStreamProducerExtension.cs#L195-L216)
```cs
internal class StreamConsumerExtensionCollection 
{
...
    internal Task DeliverItem(StreamId streamId, object item, bool fireAndForgetDelivery, bool optimizeForImmutableData)
    {
        ...
        return fireAndForgetDelivery ? Task.CompletedTask : Task.WhenAll(tasks);
    }
}
```
but then ```DeliverItem``` is used with async/await in [SimpleMessageStreamProducer.cs](https://github.com/dotnet/orleans/blob/cc4749c9be837f3f6dd82ece9cb4ed7a9c5dc798/src/Orleans.Core/Streams/SimpleMessageStream/SimpleMessageStreamProducer.cs#L92-L113)
```cs
internal class SimpleMessageStreamProducer<T> : IInternalAsyncBatchObserver<T>
{
    ...
    public async Task OnNextAsync(T item, StreamSequenceToken token)
    {
         ...
         await myExtension.DeliverItem(stream.StreamId, item);
     }
}
```
And as a result, AggregateException is unwrapped to the first exception and an external code cant affect it in any way.

How to solve this? Looks like an option in the class `SimpleMessageStreamProviderOptions` _UnwrapAggregateExceptions = true|false (default = true, current behavior)_

**Comment by sergeybykov** [comment]
I believe this behavior is specific to SMS provider, which is not a true stream provider because with it publisher isn't decoupled from subscribers. In SMS case, events are delivered as direct grain calls. I don't think we want to change how grain calls are handled. Maybe we can be clever just within `DeliverItem` to differentiate between `AggregateException` with a single inner exception and multiple?

**Comment by sergeybykov** [comment]
I wonder what @ReubenBond thinks about this.
