### ISSUE TITLE
Add overloads to IBinaryTokenStreamWriter and IBinaryTokenStreamReader

### ISSUE THREAD

**Issue by rmja** [dotnet/orleans#5967]
I am trying to incorporate messagepack for my serialization/deserialization, but some overloads are missing on the serialization interfaces which would make this nicer:

```
interface IBinaryTokenStreamWriter
{
     void Write(Span<byte> bytes);
}
```

```
interface IBinaryTokenStreamReader
{
    ReadOnlySequence<byte> Sequence { get; }
    Advance(int amount);
    void ReadBytes(in Span<byte> destination)
}
```

The sequence and advance methods are for deserializing directly from the underlying Orleans memory, instead of reading the bytes to a local buffer and deserialize from there. It may also be that some of these belong directly on the `ISerializationContext`/`IDeserializationContext`.

**Comment by rmja** [comment]
I think that what I want are exposed PipeReader/PipeWriter's...

**Comment by ReubenBond** [comment]
I think the abstractions are a little mismatched for this at the moment.

There's a divide between new networking stack (which extends up to messaging/serialization) and the old stack.

The new stack uses PipeReader/PipeWriter & has an implementation of IBinaryTokenStreamWriter/etc built on top of that so that we can adapt Pipes to Orleans' SerializationManager. The component which does that adaption is `IMessageSerializer`:

``` C#
internal interface IMessageSerializer
{
    void Write<TBufferWriter>(ref TBufferWriter writer, Message message) where TBufferWriter : IBufferWriter<byte>;
        
    /// <returns>
    /// The minimum number of bytes in <paramref name="input"/> before trying again, or 0 if a message was successfully read.
    /// </returns>
    int TryRead(ref ReadOnlySequence<byte> input, out Message message);
}
```

The interface is intentionally internal because `Message` is internal, however, so you cannot implement it easily.

One benefit of this interface is that it doesn't expose any Orleans SerializationManager types and hopefully that could help to open an avenue to use entirely different serializers in future.

Serialization is a very tricky topic. What would a MessagePack based serializer be used for, wire communication or state storage or something else?

Maybe we could expose `BinaryTokenStreamWriter2` (or an interface like you have above), etc so that you can test for them in your serializer and switch to more efficient serialization if they're being used.

The old `BinaryTokenStreamWriter` is still used for some areas (streaming, state storage), but we could potentially replace all uses with the new implementation and update the interfaces, too.

I'm open to suggestions.

**Comment by rmja** [comment]
I am currently accessing the two read and write methods on BinaryTokenStreamReader2 and the writer using reflection with a compiled expression and it works fine.

The reason I am using messagepack is for performance. I saw a significant performance increase when used instead of the in built serializer. But maybe I should re-measure this after the upgrade to v3.

And I will try and look into the iMessage serializer as you suggest, to see if that is a better extension point for swapping out the serializer.

**Comment by ReubenBond** [comment]
Could you share some code samples of what you're doing with me so I can better understand?

**Comment by rmja** [comment]
@ReubenBond yes of cause. Sorry for not getting back sooner.
The following is an example of a "grain action result model":

```
public class GetAggregateResult : IDisposable
    {
        private Action _onDispose;

        public Dictionary<int, AggregateHash> Entries { get; private set; }

        public GetAggregateResult(Dictionary<int, AggregateHash> entries, Action onDispose = null)
        {
            Entries = entries;
            _onDispose = onDispose;
        }

        ~GetAggregateResult()
        {
            Dispose();
        }

        public void Dispose()
        {
            _onDispose?.Invoke();
            _onDispose = null;
            Entries = null;
        }

        [CopierMethod]
        protected static object Copy(object input, ICopyContext context)
        {
            ...
        }

        [SerializerMethod]
        protected static void Serialize(object input, ISerializationContext context, Type expected)
        {
            var result = (GetAggregateResult)input;

            var pool = SequencePool<byte>.Default;
            var sequence = pool.Get();

            var writer = new MessagePackWriter(sequence);
            MessagePackSerializer.Serialize(ref writer, result.Entries);
            writer.Flush();

            context.StreamWriter.Write((int)sequence.Length);

            foreach (var segment in sequence.AsReadOnlySequence)
            {
                context.StreamWriter.Write(segment.Span);
            }

            pool.Return(sequence);

            result.Dispose();
        }

        [DeserializerMethod]
        protected static object Deserialize(Type expected, IDeserializationContext context)
        {
            var totalSize = context.StreamReader.ReadInt();

            var pool = SequencePool<byte>.Default;
            var sequence = pool.Get();

            var segment = sequence.GetSpan(totalSize).Slice(0, totalSize);
            context.StreamReader.ReadBytes(segment);
            sequence.Advance(segment.Length);

            var reader = new MessagePackReader(sequence);

            var entries = MessagePackSerializer.Deserialize<Dictionary<int, AggregateHash>>(ref reader);

            pool.Return(sequence);

            return new GetAggregateResult(entries);
        }
    }
```

(The `onDispose` stuff is to return the Entries dictionary to an object pool).
I am writing the serialized size because the `Length` property was left out in `3.0.0-beta1`. [I can see that it is back now](https://github.com/dotnet/orleans/pull/5997), so that part is probably irrelevant now.

<details>
<summary>The Write and ReadBytes extension methods</summary>

```
public static class BinaryTokenStreamExtensions
    {
        private delegate void WriteDeletate(IBinaryTokenStreamWriter writer, ReadOnlySpan<byte> bytes);
        private delegate void ReadBytesDelegate(IBinaryTokenStreamReader reader, in Span<byte> destination);

        private static WriteDeletate _write;
        private static ReadBytesDelegate _readBytes;
        private static Type _writerType;
        private static Type _readerType;
        private static object _writerLock = new object();
        private static object _readerLock = new object();

        public static void Write(this IBinaryTokenStreamWriter writer, ReadOnlySpan<byte> bytes)
        {
            EnsureWriterInitialized(writer.GetType());

            if (_write is object)
            {
                _write(writer, bytes);
            }
            else
            {
                writer.Write(bytes.ToArray());
            }
        }

        public static void ReadBytes(this IBinaryTokenStreamReader reader, in Span<byte> destination)
        {
            EnsureReaderInitialized(reader.GetType());

            if (_readBytes is object)
            {
                _readBytes(reader, destination);
            }
            else
            {
                reader.ReadBytes(destination.Length).CopyTo(destination);
            }
        }

        private static void EnsureWriterInitialized(Type writerType)
        {
            if (writerType == _writerType)
            {
                return;
            }

            lock (_writerLock)
            {
                if (writerType == _writerType)
                {
                    return;
                }
                else if (_writerType is null)
                {
                    _writerType = writerType;
                }
                else
                {
                    ThrowInvalidOperation();
                }

                var writer = Expression.Parameter(typeof(IBinaryTokenStreamWriter), "writer");
                var bytes = Expression.Parameter(typeof(ReadOnlySpan<byte>), "bytes");
                var writeMethod = writerType
                    .GetMethods(BindingFlags.Public | BindingFlags.Instance)
                    .Where(x => x.Name == "Write" && x.GetParameters().FirstOrDefault()?.ParameterType == typeof(ReadOnlySpan<byte>))
                    .SingleOrDefault();

                if (writeMethod is null)
                {
                    return;
                }

                _write = Expression.Lambda<WriteDeletate>(
                    Expression.Call(Expression.Convert(writer, writerType), writeMethod, bytes),
                    writer, bytes).Compile();
            }
        }

        private static void EnsureReaderInitialized(Type readerType)
        {
            if (readerType == _writerType)
            {
                return;
            }

            lock (_readerLock)
            {
                if (readerType == _readerType)
                {
                    return;
                }
                else if (_readerType is null)
                {
                    _readerType = readerType;
                }
                else
                {
                    ThrowInvalidOperation();
                }

                var reader = Expression.Parameter(typeof(IBinaryTokenStreamReader), "reader");
                var destination = Expression.Parameter(typeof(Span<byte>).MakeByRefType(), "destination");
                var readBytesMethod = readerType.GetMethods(BindingFlags.Public | BindingFlags.Instance)
                    .Where(x => x.Name == "ReadBytes" && x.GetParameters().FirstOrDefault()?.ParameterType == typeof(Span<byte>).MakeByRefType())
                    .SingleOrDefault();

                if (readBytesMethod is null)
                {
                    return;
                }

                _readBytes = Expression.Lambda<ReadBytesDelegate>(
                    Expression.Call(Expression.Convert(reader, readerType), readBytesMethod, destination),
                    reader, destination).Compile();
            }
        }

        private static void ThrowInvalidOperation() => throw new InvalidOperationException();
    }
```

</details>

During serialization, the `MessagePackWriter` supports a `IBufferWriter<byte>`, and so it would be nice if that could be the `PipeWriter` directly from the Orleans serialization system, instead of serializing to a pooled sequence, and then copy from that sequence back to the `StreamWriter` on the serialization context.

During deserialization, the `MessagePackReader` receives a `ReadOnlySequence<byte>`. I have not been able to find that on the `StreamReader`, so again I need to copy into a rented sequence and deserialize from there. If `ReadOnlySequence<byte>` was exposed directly, this copy step could be omitted.

**Comment by bill-poole** [comment]
Being able to write via an `IBufferWriter<byte>` would make the Protobuf serializer more efficient too because it would eliminate the unnecessary memory copy described [here](https://github.com/dotnet/orleans/blob/e154fab39423dd270083959201b8d846000cc4a5/src/Serializers/Orleans.Serialization.Protobuf/ProtobufSerializer.cs#L74). Protobuf provides a `WriteTo` extension method on `IMessage` that accepts an `IBufferWriter<byte>`. Seems a shame not to be able to use it.

**Comment by ReubenBond** [comment]
To be clear, we removed the ProtoBuf serializer in 4.x since we completely replaced the serializer with a much higher performance (and version tolerant) alternative. The new serializer does give access to an `IBufferWriter<byte>`, but delegated serializers still need to play within the protocol's framing rules (eg, writing a length prefix, like Protocol Buffers 3 does).

I'm not sure it's worth exposing an `IBufferWriter<byte>` in 3.x, which this issue pertains to. Under the covers, there is a buffer writer in the case of serialization for networking, but not in all cases (eg, when serialization is used in streaming, it uses a different buffer implementation).

**Comment by bill-poole** [comment]
If the Protobuf serializer is removed in 4.x, then what is the recommended way to forward a gRPC request message received from the Internet to an Orleans grain via an Orleans client? Can the auto-generated Protobuf message object be serialized using Orleans serialization in 4.x? Wouldn't it need to be decorated with Orleans attributes like `IdAttribute`, etc?

Or would we now need to create another set of message classes that Orleans can serialize and then map the auto-generated Protobuf classes to those classes?

**Comment by ReubenBond** [comment]
We could add a support package for protocol buffers. We have one for System.Text.Json and Newtonsoft.Json. It's not much difficulty to add one, but we need to have a customer need first. Ideally, you could create one following the existing pattern and submit it as a PR once you've gotten some production mileage on it.
If you're using a code-first approach, then adding Orleans attributes to the message types would suffice to allow it to be serialized by either serializer. Alternatively, you *can* create surrogates to serialize the protocol buffers types. I don't recommend that unless you're happy to accept the code + maintenance overhead and the alternatives are unattractive.

**Comment by bill-poole** [comment]
I'm willing to attempt creating one and submitting a PR when I move to 4.x; I'm still on 3.x. Is there documentation for how to create a serializer in 4.x as opposed to 3.x? Or should I look at the STJ/Newtonsoft code and work it out from there? If it is the latter, where do I find those serializers in the repo?

**Comment by ReubenBond** [comment]
I'd suggest taking a look at how the existing delegated serializers work. They follow a particular pattern. I can help you with it ([Discord](https://aka.ms/orleans-discord) would be the fastest way to collaborate on that)

**Comment by ReubenBond** [comment]
Obviated by 7.0+, which has good support for `Span<byte>`
