### ISSUE TITLE
Possible false-positive error log message

### ISSUE THREAD

**Issue by vyshkant** [dotnet/orleans#5968]
Hi!

I have received the next log messages with `Error` level:

> Work item WorkItem=WorkItemGroup:Name=[Activation: S10.0.41.9:11111:306587370*grn/97DB295E/ffedf592@93111980 #GrainType=Some.Namespace.FooGrain Placement=RandomPlacement],WorkGroupStatus=Running Executing for 00:00:00.0000024 WorkItemGroup Details: WorkItemGroup:Name=[Activation: S10.0.41.9:11111:306587370*grn/97DB295E/ffedf592@93111980 #GrainType=Some.Namespace.FooGrain Placement=RandomPlacement],WorkGroupStatus=Running. Currently QueuedWorkItems=0; Total EnQueued=1; Total processed=0; Quantum expirations=0; Executing Task Id=687 Status=Running for 00:00:00.0000417.TaskRunner=ActivationTaskScheduler-10172:Queued=0; Detailed SchedulingContext=<[Activation: S10.0.41.9:11111:306587370*grn/97DB295E/4aa62bf153091ff6f2a3b2ebffedf59203ffffff97db295e-0x730F3BE6@93111980 #GrainType=Some.Namespace.FooGrain Placement=RandomPlacement State=Activating NonReentrancyQueueSize=1 EnqueuedOnDispatcher=0 InFlightCount=0 NumRunning=0 IdlenessTimeSpan=737321.08:49:52.8640362 CollectionAgeLimit=00:05:00]> has been executing for long time

It says, that the work item of my `FooGrain` is `Executing for 00:00:00.0000024`, i.e. `24 / 10 000 000` of a second.

It doesn't sound like an error, especially considering that the default value of `TurnWarningLengthThreshold` hadn't been changed by me and should be equal to 200 ms.

This all sounds to me like a weird bug:
1) the message appears only if the work item is considered frozen:
https://github.com/dotnet/orleans/blob/cc4749c9be837f3f6dd82ece9cb4ed7a9c5dc798/src/Orleans.Core/Threading/ThreadPoolExecutor.cs#L244-L250
2) IsFrozen method says the item is frozen when the time passed after execution start is greater than threshold:
https://github.com/dotnet/orleans/blob/cc4749c9be837f3f6dd82ece9cb4ed7a9c5dc798/src/Orleans.Core/Threading/ThreadPoolExecutor.cs#L349-L352
3) the default value of threshold is 200 ms:
https://github.com/dotnet/orleans/blob/cc4749c9be837f3f6dd82ece9cb4ed7a9c5dc798/src/Orleans.Runtime/Configuration/Options/SchedulingOptions.cs#L46-L50
4) displayed execution time is `00:00:00.0000024` which is less than 200 ms.

I would be very happy if you explain me what is happening here and whether I should worry about this.

Thanks.

**Comment by sergeybykov** [comment]
Is it possible that this is a local-specific formatting issue? I mean that it's actually 240ms but presented this way.

**Comment by Itoktsnhc** [comment]
I also encountered this problem.

> 2019-11-17 14:12:18.177 +08:00 [ERR] Work item WorkItem=WorkItemGroup:Name=[Activation: S127.0.0.1:11111:311610923*grn/ECD4041A/13bef63f@189eb7bc #GrainType=JobTrackerX.Grains.JobGrain Placement=RandomPlacement],WorkGroupStatus=Waiting Executing for 00:00:00.0004087 WorkItemGroup Details: WorkItemGroup:Name=[Activation: S127.0.0.1:11111:311610923*grn/ECD4041A/13bef63f@189eb7bc #GrainType=JobTrackerX.Grains.JobGrain Placement=RandomPlacement],WorkGroupStatus=Waiting. Currently QueuedWorkItems=0; Total EnQueued=19; Total processed=19; Quantum expirations=0; TaskRunner=ActivationTaskScheduler-502807:Queued=0; Detailed SchedulingContext=<[Activation: S127.0.0.1:11111:311610923*grn/ECD4041A/00000000000000000000000013bef63f03ffffffecd4041a-0x3160CC62@189eb7bc #GrainType=JobTrackerX.Grains.JobGrain Placement=RandomPlacement State=Valid NonReentrancyQueueSize=0 EnqueuedOnDispatcher=0 InFlightCount=0 NumRunning=0 IdlenessTimeSpan=00:00:00.0024880 CollectionAgeLimit=00:10:00]> has been executing for long time.

**Comment by sergeybykov** [comment]
Can you share a repro for this?

**Comment by Itoktsnhc** [comment]
Still observing, this problem is rare, only happened once

**Comment by sergeybykov** [comment]
Closing for now because I don't see what we can do. Feel free to reopen with more information or suggestions.
