### ISSUE TITLE
Is it safe to inject ITimerRegistry using DI?

### ISSUE THREAD

**Issue by vyshkant** [dotnet/orleans#5969]
Hi everyone!

I found out that there is `Orleans.Timers.ITimerRegistry` interface, which is injectable as a service using DI.

Suppose we have `FooGrain`, `BarService` and `ITimerRegistry`:

```
public class FooGrain : Grain
{
    private readonly BarService _barService;

    public FooGrain(BarService barService)
    {
        _barService = barService;
    }

    public Task DoFoo()
    {
        _barService.DoBar();

        return Task.CompletedTask;
    }
}

public class BarService
{
    private readonly ITimerRegistry _timerRegistry;

    public BarService(ITimerRegistry timerRegistry)
    {
        _timerRegistry = timerRegistry;
    }

    public void DoBar()
    {
        _timerRegistry.RegisterTimer(
            grain: null,
            asyncCallback: _ =>
            {
                Console.WriteLine(nameof(DoBar));
                return Task.CompletedTask;
            },
            state: null,
            dueTime: TimeSpan.FromSeconds(1),
            period: TimeSpan.FromSeconds(10)
        );
    }
}
```

As you can see, I've passed `null` as a `grain` parameter to `ITimerRegistry.RegisterTimer`, and it still works, the timer does tick.

My question is: is it safe? I AFAIR timers are participants of grain messaging system and are alvays scheduled with Orleans scheduler.

But if I passed `null` as a grain, what schedule does they participate? Can I be sure that timers, that were created in the way I've shown above, are scheduling in the correct way and never run concurrently with other tasks?

**Comment by ReubenBond** [comment]
Users are not supposed to interact directly with `ITimerRegistry` but it's possible to inject it and use it. I would recommend that you do not pass `null` for the grain since that will *not* produce valid behavior. You must have an instance of the grain to register the timer for, otherwise the timer will not be associated with any grain and will be scheduled on a null context

**Comment by vyshkant** [comment]
Thanks!
