### ISSUE TITLE
Connecting to DynamoDB from Silo

### ISSUE THREAD

**Issue by pawanrao** [dotnet/orleans#5970]
I'm trying to configure AWS DynamoDB for my Silo clustering and I'm always hitting the following exception: 
```
Could not initialize connection to storage table OrleansSilos
Amazon.DynamoDBv2.AmazonDynamoDBException: The security token included in the request is invalid. ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
```

I'm  initializing my silo as follows: 
```
var siloHostBuilder = new SiloHostBuilder();
siloHostBuilder.UseDynamoDBClustering(options =>
                {
                    options.AccessKey = <value_of_AWS_ACCESS_KEY_ID>
                    options.SecretKey = <value_of_AWS_SECRET_ACCESS_KEY>;
                    options.Service = RegionEndpoint.USEast1.SystemName;
                    options.TableName = siloConfiguration.MembershipTableName;
                })
```

I'm able to successfully access the DynamoDB tables using the AWS CLI. 
Am I missing anything here? 
Orleans version: `2.4.2`

**Comment by jsteinich** [comment]
That looks correct. I would double check that access key and secret key have the correct values.
I believe that error happens when trying to use temporary credentials, which is what the membership code would try to use if either access key or secret key was missing.

**Comment by Frank-Krick** [comment]
@pawanrao Do you specify AccessKey and SecretKey for the aws tool on the command line or do you have the access key in ~/.aws/credentials? If so try to remove the Access and SecretKey from the Silo configuration. The AWS clients then would use the key stored in that file.

**Comment by pawanrao** [comment]
yep, that actually did it for me. I removed the AccessKey and SecretKey from the Silo Configuration and have the credentials in ~/.aws/credentials. Thanks @Frank-Krick !
