### ISSUE TITLE
Documentation for Stream balancers

### ISSUE THREAD

**Issue by aloysiustany** [dotnet/orleans#5981]
I am looking for documentation on eventhub stream's options `UseConsistentRingQueueBalancer`, `UseDynamicClusterConfigDeploymentBalancer`. Please can you point me to that. 

Thanks.

**Comment by oising** [comment]
Great call - when I had UseDynamicClusterConfigDeploymentBalancer in the builder, it stalls the streams and no pulling agents are created. I didn't mean to put it there, but had gotten the code from a sample (or maybe one of Orleans unit tests.)

**Comment by oising** [comment]
*bump* -- this shouldn't be closed.
