### ISSUE TITLE
Checkpointing is not happening when using eventhub Orleans stream.

### ISSUE THREAD

**Issue by MittalNitish** [dotnet/orleans#5982]
Hi Team,

We are using Orleans 2.2.4. We were trying out Azure Eventhub based Orleans stream. 

1. Although we are able to send and receive the messages to and from stream, we noticed that checkpointing is not happening at configured timespan. If we stop the silo in between and re-run it we still see the old messages are pulled from eventhub. There are checkpoints created in Azure table when Silo starts but doesn't update in configured time span.
Attaching the sample code which produces this issue. Stream configuration is done in `OrleansSiloBuilder.ConfigureStreamProviders` method. `EventSenderGrain` sends events to stream and `StreamDataRecieverGrain` subscribe to stream using implicit subscription.

2. If we use `UseDynamicClusterConfigDeploymentBalancer()` we are not receiving any messages from stream at all, hence using `UseConsistentRingQueueBalancer()`.

Can you please help with the configuration if we are missing something? We mostly did the configurations based on the tests written in Orleans code.
[Code to reproduce the issue](https://github.com/dotnet/orleans/files/3663200/OrleansStreamSample.zip)

**Comment by jason-bragg** [comment]
Checkpoints are only written when data is purged from the message cache, as that's the only point in which we need move the checkpoint forward.  The checkpoint interval is to prevent spamming storage under load.  Messages are purged from the cache is determined by StreamCacheEvictionOptions, and the default data age is 30 minutes with the default minimum time in cache of 5 minutes.  With the default configuration no checkpoints will be written for at least the first 5 minutes, and after that only if there is 30 minutes of data read from the partition.

**Comment by MittalNitish** [comment]
Thanks @jason-bragg,

Using `StreamSequenceToken` in `ResumeAsync` on grain activation works well. To increase the checkpoint frequency we used `StreamCacheEvictionOptions` through `ConfigureCacheEviction()`  Now we are facing a different issue. Memory usage of application is very high and it is causing `OutOfMemoryException`. The exception is raised from the constructor of `FixedSizeBuffer` class. I believe it happening because of the data pulled from the eventhub is stored in cache queues. I tried to workaround it by using different configuration options such as `ConfigureCachePressuring()` but not able to achieve low memory usage. Can you please help with that. We want to achieve the following:

1. Checkpoint more often but do not want to checkpoint before message is processed.
2. Wants to keep the memory usage low.

Our stream consumer grain could be really slow and it might not be able to process the messages at the same rate as pulling agent is pulling them from eventhub. Hence, we need to slow down pulling messages. Also, we are creating one stream per device, there could be 1000+ device and hence there would be 1000+ stream.

**Comment by jason-bragg** [comment]
The pressure settings you have should achieve your goal (in theory) but the memory usage could be high (which you've stated).  To reduce memory you'll need to configure your StreamCacheEvictionOptions.DataMinTimeInCache and DataMaxAgeInCache to lower values.  The memory used by the cache will usually depend on how much memory is used in DataMaxAgeInCache worth of messages per partition.

So if you've two silos with a hub of 20 partitions with 20 TU (That's 1MB/Second per partition) and your DataMaxAgeInCache is 5 minutes then the cache should max out around 3gig.  That's 60MB per minute per partition, assuming 10 partition per silo, for 5 minutes, so (60+10+5)MB.

This is only some rough math and you'll need to plug in your own numbers to figure out what's best for your service.

**Comment by MittalNitish** [comment]
Thanks @jason-bragg
