### ISSUE TITLE
Missing Global Namespace Alias in codegen

### ISSUE THREAD

**Issue by shayhatsor** [dotnet/orleans#599]
code generation fails for the following :
```csharp
namespace Something.Orleans
{
    public interface ISomeGrain : IGrain
    {
       Task Do();
    }
}
```
the cause is missing **global::** in the **using** statements in generated code.
Adding **global::** to the **using** statements seems to fix the problem.
It seems that the usage of **global::** is inconsistent.

**Comment by ReubenBond** [comment]
We should create a test case. I wonder if the new code generator (#528) fails on this. If so, we can add global:: to every type reference

**Comment by ReubenBond** [comment]
I've amended #528 to always globally-qualify type/namespace references.

**Comment by gabikliot** [comment]
I did not fix it, as @ReubenBond  has the fix already in the new code gen code.
