### ISSUE TITLE
Proper way to build SDK 1.0?

### ISSUE THREAD

**Issue by maiorfi** [dotnet/orleans#60]
Hi.

What is the right way to build SDK so that setting OrleansSDK evnironment variable everything works as with 0.9 SDK installer?

Will you provide precompiled SDK too (either on Codeplex site or on GitHub)?

Thanks!

**Comment by maiorfi** [comment]
Sorry: silly question.

Just spotted that Build.cmd batch also creates SDK installer (both in "orleans\Binaries\Release" and in "orleans\Binaries\Debug").

**Comment by jthelin-microsoft** [comment]
We also have Jenkins hooked up for CI builds, but that basically just runs Build.cmd and Test.cmd scripts from the repo so local build is just as good :)
http://dotnet-ci.cloudapp.net/job/dotnet_orleans/
