### ISSUE TITLE
Reduce timeout limit for calls to grain directory

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#6012]
Today, grain directory calls are subject to the application call timeout setting, by default 30 seconds. There's not reason to be that forgiving for directory calls. It would be better to getter timeouts much sooner, so that the system can recover faster.

The same probably applies to other system calls, but I think grain directory is the most obvious target here because it performs very little compute on those calls, and is critical in failure recovery scenarios.

**Comment by martinothamar** [comment]
Maybe a more general solution would be possible here - ability to set response timeout per grain / grain method? As in not just internal grains.

**Comment by ReubenBond** [comment]
Fixed in #6046. I agree that we need a more general per-call mechanism
