### ISSUE TITLE
TestCluster exposes the wrong ServiceProvider

### ISSUE THREAD

**Issue by turowicz** [dotnet/orleans#6026]
`TestCluster` returns the Client `ServiceProvider` instead of Host in the `ServiceProvider` property. It's problematic because we have no way of testing Mocks without getting them through said ServiceProvider and using the Client one returns objects that don't get created in Grains.

**Comment by turowicz** [comment]
cc @ReubenBond @sergeybykov

**Comment by ReubenBond** [comment]
Is the Host here the Silo? The following assumes it is.

Silos created by the TestCluster have separate containers to keep them isolated from one another as well as from the client. They can be in different AppDomains or potentially even different processes.

That is the primary reason why these things are available to tests.

If you know that the silo is hosted in the same AppDomain & process as the test itself then you can work around this with some casting:

``` C#
var siloHandle = testCluster.Primary as Orleans.TestingHost.InProcessSiloHandle;
var serviceProvider = siloHandle.SiloHost.Services;
```

**Comment by turowicz** [comment]
thanks mate @ReubenBond I will try that!
