### ISSUE TITLE
Timeout exception using SMS as streaming provider

### ISSUE THREAD

**Issue by games** [dotnet/orleans#6033]
Hi there,

I am writing a turn-based game, I have a GameGrain, PlayerGrain and LiveUpdateGrain, the GameGrain I use `RegisterTimer` to check game status for every seconds, and the method will call all PlayerGrain to get latest player's state. LiveUpdateGrain is an `ImplicitStreamSubscription` to consume and also produce new events from same stream.

pseudo code:

```c#
public class GameGrain : Grain<GameState>, IGameGrain {

    public override async Task OnActivateAsync() {
        var streamProvider = GetStreamProvider(Constants.GameEventStreamProvider);
        stream = streamProvider.GetStream<IEvent>(State.StreamId, Constants.GameEventStreamNameSpace);
        players = GetUsers().Select(x => GrainFactory.GetGrain<IPlayerGrain>(x));
        await Task.WhenAll(players.Select(x => x.BindToStream(stream.Guid)));
        await CheckGameStatus();
        RegisterTimer(CheckGameStateTimer, null, TimeSpan.FromSeconds(1), TimeSpan.FromSeconds(1));
    }

    private async Task CheckGameStateTimer(object _)
    {
        await Task.Run(() => this.AsReference<IGameGrain>().CheckGameState());
    }

    public async Task CheckGameState()
    {
        var results = await Task.WhenAll(players.Select(x => x.IsCompleted()));
        State.Completed = results.All(x => x);
        await WriteStateAsync();
        if (State.Completed)
        {
            var playerStates = await Task.WhenAll(players.Select(x => x.GetState()));
            stream.OnNextAsync(new Completed { PlayerStates = playerStates }).Ignore();
        }
    }
}

public class PlayerGrain : Grain<PlayerState>, IPlayerGrain {

    public async Task BindToStream(Guid streamId)
    {
        State.StreamId = streamId;
        await WriteStateAsync();
        var streamProvider = GetStreamProvider(Constants.GameEventStreamProvider);
        stream = streamProvider.GetStream<IEvent>(streamId, Constants.GameEventStreamNameSpace);
    }

    public Task<bool> IsCompleted() {
        return Task.FromResult(State.IsCompleted);
    }

    public Task<PlayerState> GetState() {
        return Task.FromResult(PlayerState);
    }

    // Call from client directly
    public Task SomeAction() {
        stream.OnNextAsync(new SomeAction{ PlayerId = PlayerState.Id });
    }
}

[ImplicitStreamSubscription(Constants.GameEventStreamNameSpace)]
public class LiveUpdateGrain : Grain, ILiveUpdateGrain
{
    public override async Task OnActivateAsync()
    {
        var streamId = this.GetPrimaryKey();
        var streamProvider = GetStreamProvider(Constants.GameEventStreamProvider);
        stream = streamProvider.GetStream<IEvent>(streamId, Constants.GameEventStreamNameSpace);
        subscription = await stream.SubscribeAsync(OnNext, OnError, OnCompleted);
        RegisterTimer(UpdateGameState, null, TimeSpan.FromSeconds(1), TimeSpan.FromSeconds(1));
    }

    private Task UpdateGameState(object arg)
    {
        if (!state.IsCompleted)
        {
            // just some live update data
            stream.OnNextAsync(new LiveUpdate {  }).Ignore();
        }
        return Task.CompletedTask;
    }

    public override async Task OnDeactivateAsync()
    {
        await subscription.UnsubscribeAsync();
    }

    private Task OnCompleted()
    { return Task.CompletedTask; }

    private Task OnError(Exception ex)
    { return Task.CompletedTask; }

    private async Task OnNext(IEvent evt, StreamSequenceToken token = null)
    {
        // some logic to handle game events
    }
}

```

WebApi + Signalr Hub
```c#
public override async Task OnConnectedAsync()
{
    var stream = streamProvider.GetStream<IEvent>(streamId, NameSpace);
    var subscriptionHandles = await stream.GetAllSubscriptionHandles();
    if (subscriptionHandles != null && subscriptionHandles.Any())
    {
        foreach (var x in subscriptionHandles)
        {
            await x.ResumeAsync(CreateEventObserver());
        }
    } else {
        var subscription = await stream.SubscribeAsync(CreateEventObserver());
        Context.Items.Add("subscription", subscription);   
    }
    await base.OnConnectedAsync();
}

public override async Task OnDisconnectedAsync(Exception exception)
{
    if (Context.Items.TryGetValue("subscription", out var subscription))
    {
        await (subscription as StreamSubscriptionHandle<IEvent>).UnsubscribeAsync();
    }
    await base.OnDisconnectedAsync(exception);
}
```

somehow I encounter timeout exception
message
```
Response did not arrive on time in 00:00:30 for message: Request S172.21.0.3:10000:308151601*grn/424C7040/00000000+4@@@2@df6c3e8a->S172.21.0.3:10000:308151601*grn/716E8E94/853792b5+GameEventStreamProvider@0fb6f3ab #7035583: . Target History is: <S172.21.0.3:10000:308151601:*grn/716E8E94/853792b5+GameEventStreamProvider:@0fb6f3ab>.
```

failed method
```
Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1+<Cleanup>d__29.MoveNext
```

formatted message
```
Ignoring unhandled exception during PubSub.UnregisterProducer
```

category
```
Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer
```

Call stack
```
System.TimeoutException:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamPr
```

Do I have something wrong in the code?

**Comment by games** [comment]
Actually right now I am not sure if its because of this exception, the client just somehow (not always but maybe when the server is busy) can't receive  events, and I found this exception happen at that time.

**Comment by sergeybykov** [comment]
The `ILiveUpdateGrain` grain class (did you mean `LiveUpdateGrain` rather?) subscribes and produces to the same stream. Wouldn't that be an issue? In case of the SMS provider, it effectively invokes its own method.

**Comment by games** [comment]
hi @sergeybykov, yeah you are right, its typo, I just modified it. 

>  subscribes and produces to the same stream. Wouldn't that be an issue?

I am not really sure if it's an issue, never found before when I just test on my local. Actually I just encounter this issue after I run the application on staging with multiply silo hosts. And I think maybe after the exception I encountered streaming re-subscription issue(still no idea how to handle this).

> In case of the SMS provider, it effectively invokes its own method.

Sorry I don't get it, you mean I should write to another stream? instead of same stream?

**Comment by sergeybykov** [comment]
In its `OnActivateAsync`, `LiveUpdateGrain` subscribes to the stream:
```csharp
subscription = await stream.SubscribeAsync(OnNext, OnError, OnCompleted);
```
That means that when inside `UpdateGameState` it calls
```csharp
stream.OnNextAsync(new LiveUpdate {  }).Ignore();
```
it effectively calls its own `OnNext()` method. If that call was awaited and `LiveUpdateGrain` is non-reentrant, it would cause a deadlock and a timeout because of the call cycle.

I guess that fact that you are not awaiting `OnNext()` there helps avoid the deadlock. But not awaiting async calls is generally a bad practice that can mask issues. I'd suggest first change the code to await all async calls. That would surface all exceptions that are being hidden in this version. Then I would look at the call chains and if some of them require reentrancy.

**Comment by games** [comment]
I didn't handle `LiveUpdate` event in `OnNext` method, but I just write `LiveUpdate` event to the same stream on `UpdateGameState` method, so I can consume it on another subscriber. In my case, I have another subscriber on `webApi`,  after the subscriber receive `LiveUpdate` event, I will use signalr to push it to front end web page.

the `OnNext` method on `LiveUpdateGrain` Grain just for aggregate data. something like this:

```c#
 private async Task OnNext(IEvent evt, StreamSequenceToken token = null)
        {
            if (evt is GameStarted started)
            {
                state.TotalGameStarted++;
            }
            else if (evt is GameCompleted game)
            {
                state.TotalGameCompleted++;
            }
        }
```

**Comment by games** [comment]
I am still trying to find a way to  resume subscription for the WebApi, and push these GameEvent to webpage front end via SignalR.

Any help is appreciated

**Comment by games** [comment]
I have managed to use a subscription manager to cache all subscriptions, and trying to resume all in `builder.AddClusterConnectionLostHandler` and `builder.AddGatewayCountChangedHandler`, but unfortunately, these event seems never be trigger.

**Comment by games** [comment]
Finally I make it works, I list down the mistakes I  have made before here for someone who encounter same issue:

1,  `builder.AddClusterConnectionLostHandler` I was use `serviceProvider scope`, but the `scope` after configure service it's disposed.

2, For the `Resume` method, I should check if the active handlers is exists, and resuming it if it does, but if none resubscribing to the stream.

More infos:
https://github.com/dotnet/orleans/issues/5310#issuecomment-462869849
https://github.com/dotnet/orleans/issues/2226#issuecomment-308682936

BTW, regarding @gabikliot suggestions: 
https://github.com/dotnet/orleans/issues/2226#issuecomment-308857774

> Regarding usage of ClusterConnectionLost. Can you also, in addition to using this event to detect potential stream loss, do the following:
periodically, very infrequently, publish some dummy test event to those system streams and check that it arrives. If not, re-subsricribe. This will make this combined logic more robust.

Anyone have some example code?

Thanks in advance.

**Comment by mindlink** [comment]
So we've been looking at resuming a stream that "might" be broken when cluster connectivity changes. While you can reasonably be told when connection is lost, how do you know when the connection comes back?

`AddGatewayCountChangedHandler` doesn't work because the implementation of `OutsideRuntimeClient` doesn't forward on the event like he does for connection lost - https://github.com/dotnet/orleans/blob/c683fa8f2fddf310c2dfc3c9cf43db4fb80be1ad/src/Orleans.Core/Runtime/OutsideRuntimeClient.cs#L121

Is there an alternative event/callback for being notified when a connection resumes?

**Comment by mindlink** [comment]
#6098

> So we've been looking at resuming a stream that "might" be broken when cluster connectivity changes. While you can reasonably be told when connection is lost, how do you know when the connection comes back?
> 
> `AddGatewayCountChangedHandler` doesn't work because the implementation of `OutsideRuntimeClient` doesn't forward on the event like he does for connection lost -
> 
> https://github.com/dotnet/orleans/blob/c683fa8f2fddf310c2dfc3c9cf43db4fb80be1ad/src/Orleans.Core/Runtime/OutsideRuntimeClient.cs#L121
> 
> Is there an alternative event/callback for being notified when a connection resumes?

Made a new issue for the broken handler - #6098

**Comment by sergeybykov** [comment]
@games @mindlink I'm not sure if this is still relevant to you. Sorry, I neglected this issue for so long.

I think the questions ultimately boil down to the fact that client subscriptions, unlike those of grains, are inherently unreliable because when a client loses connection to the cluster, it's unclear if it'll ever reconnect. The runtime could hold more state about clients for a longer period of time, but that would eventually hurt scalability and increase complexity.

The suggested pattern is for the client code to take the responsibility for detecting disconnects and losses of subscriptions and for recovering/resubscribing. At least, that's how we've seen such cases handled so far. New ideas are very welcome.
