### ISSUE TITLE
NullReferenceException when calling GetReminder or GetReminders

### ISSUE THREAD

**Issue by mindlink** [dotnet/orleans#6036]
### Environment
**Affects:** 3.0.0-rc1
**Worked in:** 2.x
**Additional:** Uses the AdoNet reminder provider

### Reproduction:
1. Create a `Grain` who has the following:
```csharp
public override async Task OnActivateAsync()
        {   
            var reminder = await this.GetReminder(this.GetPrimaryKeyString());

            if (reminder == default)
            {
                await this.RegisterOrUpdateReminder(
                        this.GetPrimaryKeyString(),
                        TimeSpan.FromMinutes(1),
                        TimeSpan.FromMinutes(5);
            }

            await base.OnActivateAsync();
        }
```
2. Create a `StartUpTask` that kicks the grain

### Expected:
Silo starts up with no problems, reminder is created in the table.

### Actual:
Silo fails to start up with the following stack trace:
```
fail: Orleans.Runtime.Silo[100439]
      Exception during Silo.Start
System.NullReferenceException: Object reference not set to an instance of an object.

Server stack trace:
   at Orleans.Runtime.ReminderService.AdoNetReminderTable.ReadRow(GrainReference grainRef, String reminderName)
   at Orleans.Runtime.ReminderService.LocalReminderService.<GetReminder>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
<snip/>
```

Even with a reminder in the database, there's still a `NullReferenceException` thrown:

ServiceId|GrainId|ReminderName|StartTime|Period|GrainHash|Version
----------|--------|-----------------|-----------|-------|-----------|--------
ClusterSample|GrainReference=00000000000000000000000000000000060000005ef5182d+Supervisor|Supervisor|2019-10-10 18:29:54.790|60000|1504553235|0

### Workaround
Changing the code so that it doesn't check for an existing reminder with `GetReminder` or `GetReminders` and instead calls `RegisterOrUpdateReminder` every time works without issue.

**Comment by mindlink** [comment]
> @mindlink Do you have knowledge if other platform or version works for you?

It worked in 2.x. For the 3.x releases we haven’t tried on the latest RC yet and we haven’t tried on other platforms.

**Comment by veikkoeeva** [comment]
@mindlink Which database you have? Is it MySQL?

**Comment by mindlink** [comment]
> @mindlink Which database you have? Is it MySQL or MariaDb?

@veikkoeeva It's MS SQL Server 2014 enterprise edition, we followed this process to setup the SQL server:
1. Created a fresh database,
2. Ran the provided Orleans SQL scripts in the following order:
    a. SQLServer-Main
    b. SQLServer-Clustering
    c. SQLServer-Persistence
    d. SQLServer-Reminders
3. Ran the Orleans cluster

**Comment by mindlink** [comment]
@veikkoeeva just tried this again with a fresh database and the 3.0.0 final release and it worked.
