### ISSUE TITLE
Recommendation on Grain ID creation

### ISSUE THREAD

**Issue by adminnz** [dotnet/orleans#6051]
We are using Orleans and have a need to map Grains backing storage to a relational table structure that will be ad-hoc queried using SQL. The tables will have auto incremented ID's controlled defined by the table.

My question is how would you recommend creating these grains, because GrainFactory.GetGrain<T>(..) requires an ID, but we don't know the ID until we have saved the record into the database.

**Comment by csyszf** [comment]
You can create the entity out of its own grain.
1. insert the entity to the database in another grain, like a stateless grain or an operator grain, or just a normal application service.
2. get the grain reference by the ID returned by database and do the initiation stuff in the grain

**Comment by sergeybykov** [comment]
@adminnz, did this approach work for you? Can we close this issue now?

**Comment by adminnz** [comment]
@sergeybykov Yes, this was what I was expecting needed to be done, but wanted to make sure I wasn't overlooking something.
