### ISSUE TITLE
Docs:  orleans/src/Documentation/grains/grain_persistence/index.md 

### ISSUE THREAD

**Issue by ry8806** [dotnet/orleans#6054]
Is the 64kb Limit for Azure Table storage still valid?

I've been searching the Azure Table Storage docs, but can't find any reference to 64kb being a limit
https://docs.microsoft.com/en-gb/azure/storage/common/storage-scalability-targets#azure-table-storage-scale-targets

Does this mean that the limit in Table Storage has been increased?
If so, let me know and I'll do a PR to change it 😄

**Comment by ReubenBond** [comment]
@ry8806 it is still valid on Azure Table Storage but the providers in Orleans automatically split longer values over multiple columns if they exceed that limit.

For each Table Storage column, it's 32K string chars or 64K bytes. The maximum length for any row in Table Storage is (IIRC) 1 MB

A PR to clarify is appreciated

**Comment by ReubenBond** [comment]
Fixed via #6061
