### ISSUE TITLE
Nullable warning in generated code.

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#6067]
Hi,

I get the following warning in the *.g.cs files:

```
warning CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
```

Could you disable it? It is enabled for the whole project.

**Comment by SebastianStehle** [comment]
Sorry, I thought it was my fault, because my project had a merge conflict. But it still happens.

**Comment by ReubenBond** [comment]
We can add `#nullable disable` to the top of *.g.cs files. I wonder if we need an opt-in/opt-out for this line - maybe it will fail/warn on older C# versions and I believe any language version detection we add would be unreliable/inaccurate

**Comment by SebastianStehle** [comment]
The best option would be to scan the csproj file I think.

**Comment by ReubenBond** [comment]
That's not reliable, though. For example, the property can be set by tooling automatically depending on your SDK or by a `<LangVersion>` property in a parent `Directory.Build.props`

We can set the opt-in/out based on `LangVersion` by default but with an explicit override

**Comment by SebastianStehle** [comment]
I was wrong. The problem is that in my case nullable is enabled in the csproj but it does not get applied to the generated code.

**Comment by SebastianStehle** [comment]
The docs mention that you can just use #nullable restore

https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-reference-types.md

**Comment by ReubenBond** [comment]
Based on that documentation we shouldn't need to do anything because `.g.cs` files are automatically opted-out of nullability checks - which is the correct behavior imho

**Comment by SebastianStehle** [comment]
Yes, but when you have a nullable type in one of the grain interfaces the warning is thrown.

**Comment by ReubenBond** [comment]
I wonder if that's an error in the tool chain? I'm not sure what action we ought to take here - if any.
We could potentially add a `#pragma` to the file to suppress any warnings related to nullable reference types.

**Comment by ReubenBond** [comment]
I believe this is fixed now, but if not please open a new issue and reference this one.
