### ISSUE TITLE
error NETSDK1085 when creating package using dotnet cli 3.0.100

### ISSUE THREAD

**Issue by pechkarus** [dotnet/orleans#6073]
After updating `dotnet` tools to 3.0.100, creation of NuGet packages started to fail.

Looks like behavior might have changed in dotnet 3.* as compared to 2.* ([see changes](https://github.com/dotnet/sdk/commit/af4fc22af555a2cc647dc533436e764759ad827f)) and now 
`Microsoft.Orleans.CodeGenerator.MSBuild` violates `NoBuild` constraint. I believe this behavior is the same for 2.4.* and 3.0.* of `Microsoft.Orleans.CodeGenerator.MSBuild`.

#### Command: 
```powershell
dotnet pack --no-build .\Grains.Interfaces\Grains.Interfaces.csproj
```
#### Expected 
New NuGet package is created:
```powershell
Successfully created package '*********REDACTED*********\Grains.Interfaces\bin\Debug\Grains.Interfaces.1.0.0.nupkg'.
```
#### Actual
Error is thrown:
```powershell
C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(133,5): error NETSDK1085: The 'NoBuild' property was set to true but the 'Build' target was invoked. [*********REDACTED*********\Grains.Models\Grains.Models.csproj]
```

### Setup
I was able to reproduce issue by crating a simple project:
- `Grains.Interfaces.csproj` - contains one interface `ITestGrain : IGrainWithStringKey` with a single method `Task<int> CreateAsync(TestModel testModel);`
- `TestModel` is a POCO defined in `Grains.Models.csproj`
- `Grains.Interfaces.csproj` has reference to  `Grains.Models.csproj` and following NuGet configuration:
```xml
<PackageReference Include="Microsoft.Orleans.CodeGenerator.MSBuild" Version="2.4.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
<PackageReference Include="Microsoft.Orleans.Core" Version="2.4.3" />
<PackageReference Include="Microsoft.Orleans.Core.Abstractions" Version="2.4.3" />
```

**Comment by turowicz** [comment]
Same issue here:

https://stackoverflow.com/questions/59289200/error-netsdk1085-the-nobuild-property-was-set-to-true-but-the-build-target?noredirect=1#comment104790166_59289200

**Comment by ReubenBond** [comment]
Thanks for reporting, I have a local repro and I'm looking into it.

**Comment by pechkarus** [comment]
Thanks for fixing this. When do you expect to release it as a NuGet?

**Comment by sergeybykov** [comment]
We are trying to decide if 3.0.3 or 3.1.0 is how we should release it - see https://github.com/dotnet/orleans/pull/6290#issuecomment-583788732.

**Comment by Bab95** [comment]
Why i am still getting this issue.

**Comment by ReubenBond** [comment]
I don't know, but perhaps try using the .MSBuild code generator instead.

If that doesn't work, create a new issue and upload the .binlog file created after passing the -bl flag to the pack command.

Closed issues present a challenge to track and reopening them involves notifying everyone in the thread, people who likely do not have this issue anymore. Therefore, we prefer new issues, perhaps referencing one or more already-closed issues.
