### ISSUE TITLE
[doc] Multiple language support

### ISSUE THREAD

**Issue by sheng-jie** [dotnet/orleans#6075]
I want to translate the docs to Chinese, How can I start?
I prefer add some language identifier folders (en-us, zh-cn and so on) to place the translated docs.

**Comment by sergeybykov** [comment]
Thank would be great! We seem to have quite a number of users in China, and translated docs would help a lot.

I think we can start by adding a top-level `zh-cn` folder to the docs branch. We can take care of `en-us` later, so that we don't break existing links to current pages.

**Comment by sheng-jie** [comment]
Ok , I will start working on that .

**Comment by sergeybykov** [comment]
Thanks! Please raise any issues you run into.

**Comment by ElderJames** [comment]
@sheng-jie Hi,how is it going?

**Comment by t1logy** [comment]
Hello, I am new to GitHub, but I’m really willing to contribute? How can I help you?

**Comment by sergeybykov** [comment]
@t1logy Any help would be much appreciated. You can start by looking at [issues marked as Help Wanted](https://github.com/dotnet/orleans/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)

**Comment by sheng-jie** [comment]
I'm sorry for taking so long to respond.   
I've translated the docs to Chinese in my forked repository(https://github.com/sheng-jie/orleans/blob/docs/zh-cn). Currently, I have deployed it to the Azure App Service. The website is https://orleans.azurewebsites.net. Because only a part of the docs have been reviewed. It's needs continuous improvement with Chinese community help. So I think it's still not the time to create a PR to merge with that. And I will create a PR to merge that when the docs is more fluent. 

So I want to ask if it is possible to add a link in the official doc top menu because I want more Chinese developers to know about that website and give some feedback,  and join the translation group to refine the docs.

**Comment by sheng-jie** [comment]
> ![Chinese Orleans Docs](https://user-images.githubusercontent.com/12607748/91639284-06bfcf00-ea48-11ea-817c-ed525dc8b305.png)
> @sergeybykov I'm sorry for taking so long to respond.
> I've translated the docs to Chinese in my forked repository(https://github.com/sheng-jie/orleans/blob/docs/zh-cn). Currently, I have deployed it to the Azure App Service. The website is https://orleans.azurewebsites.net. Because only a part of the docs have been reviewed. It's needs continuous improvement with Chinese community help. So I think it's still not the time to create a PR to merge with that. And I will create a PR to merge that when the docs is more fluent.
> 
> So I want to ask if it is possible to add a link in the official doc top menu because I want more Chinese developers to know about that website and give some feedback, and join the translation group to refine the docs.

@ReubenBond

**Comment by sergeybykov** [comment]
Thank you, @sheng-jie! I submitted #6748 to add a link to the docs landing page. There must another place to add it to be more prominent. I just can't think of where at the moment.

**Comment by sheng-jie** [comment]
@sergeybykov Thank you.

**Comment by ElderJames** [comment]
I think the Orleans documentation should be more modern.  At less integrate into MS Docs.
