### ISSUE TITLE
Upgrade to Orleans 3.0 from 2.* seems to incur performance issues

### ISSUE THREAD

**Issue by COCPORN** [dotnet/orleans#6076]
An upgrade from 2 to 3.0 seems to make performance worse in two ways:

- The average request time is higher than before
- There are "odd spikes" that go from what would normally be 5ms-20ms to 500ms-1000ms. These seem to not be related to external dependencies

This is running on alpine nightly with dotnet core 3.0 running on AKS.

Screenshot of normal operations:

![normal](https://user-images.githubusercontent.com/5766347/67874630-7a960000-fb35-11e9-9d90-ddeaefeab405.png)

This is the kind of peaks we are experiencing now:

![peaks](https://user-images.githubusercontent.com/5766347/67874663-85509500-fb35-11e9-8601-93eb9c29e659.png)

Information about the system: 

- Load is not high (sub 1 transaction a second)
- Load is very even re-using the same grains
- Backend database has been scaled up but we still have issues

**Comment by COCPORN** [comment]
I just did an upgrade to 3.0.1, and this seems to be fixed for us. Requests are now hovering nicely between 5ms and 20ms. 

I did also upgrade a bunch of other packages in the same go. Not sure if those could have had an impact on it.

**Comment by ReubenBond** [comment]
I'm glad to hear it, @COCPORN :) should we close this now?

**Comment by COCPORN** [comment]
@ReubenBond I am fine with that. I'll come back to it if there is a regression, and I have everything I changed in a single commit.
