### ISSUE TITLE
Saving references to Other grains

### ISSUE THREAD

**Issue by iniside** [dotnet/orleans#6085]
Hey

I've trying out Orleans for some simple projects to get my head around.
I'd like to ask if this is an Orleans way to approach things.

I have Player and player can have multiple inventories (which in turn store multiple items).
Right now I have Player Grain and Inventory Grain. Player Grain can reference multiple Inventory grains.

1. Should I store Inventory Grains IDs inside PlayerState ?
2. Can I just store Inventory References inside PlayerState and will they be automatically serialized ?
3. Should I simply put everything into single grain (Player) ?

**Comment by sergeybykov** [comment]
I think storing grain IDs is the most flexible approach. 2 will also work, but it wouldn't provide a material benefit over 1.

It's hard to tell if 3 is a good option. It depends on access patterns. If inventories can only be managed via their player's grain, then it might make sense to just keep them as part of player's state. If, on the other hand, inventories might be accessed independently, for example, for management, aggregation, etc., then it might be better to keep them as separate addressable entities (grains).
