### ISSUE TITLE
Rationale for StorageProvider attribute on grain implementation?

### ISSUE THREAD

**Issue by MV10** [dotnet/orleans#6087]
I'm wondering about the rationale behind grain implementations needing to specify `[StorageProvider(name)]` instead of making that a responsibility of the silo.

This coupling looks like a classic case of "leaky abstraction," although I'm still pretty new to Orleans. To me it would seem more natural to specify the provider at the same point in silo setup where `ConfigureApplicationParts` is called (which I realize is used by Orleans but not part of it). The silo controls every other aspect of storage, so to me, "where to store each grain" seems like a natural fit as well.

I'm curious if I'm overlooking some benefit to this design, and whether there might be interest in changing it (perhaps while still supporting the attribute for backwards compatibility).

**Comment by sergeybykov** [comment]
This feature was there long before support for DI and application parts was introduced. It is meant to decouple grain implementation from the specifics of the storage provider to be used. The new persistence API of [`IPersistentState<T>`](http://dotnet.github.io/orleans/Documentation/grains/grain_persistence/index.html) uses a similar name-based mapping mechanism for late binding.

**Comment by mv10-work** [comment]
The new `IPersistentState<T>` approach is pretty cool. I still don't really see why grains aren't persistence-implementation agnostic (other than the obvious historical reasons), it would make more sense to me for the silo to have full control over this, but you answered my question, please feel free to close this.
