### ISSUE TITLE
DynamoDB clustering: support extended membership protocol

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#6099]
The current implementation of the DynamoDB clustering provider only supports the initial membership protocol, not the later [extension to the protocol](https://dotnet.github.io/orleans/Documentation/implementation/cluster_management.html#extension-to-totally-order-membership-views) to support totally ordered views of cluster membership.

It's important to support this so that the provider will function correctly.

See this PR which adds such support to Consul: https://github.com/dotnet/orleans/pull/6095

**Comment by jsteinich** [comment]
We were thinking of updating to 2.4.x next week. Sounds like this may be a blocker, so I can see about getting some time to work on it.
