### ISSUE TITLE
What happens if ConfirmEvents fails?

### ISSUE THREAD

**Issue by MV10** [dotnet/orleans#6103]
The documentation area [Raising Events](http://dotnet.github.io/orleans/Documentation/grains/event_sourcing/journaledgrain_basics.html#raising-events) about ES and journaled grains says this:

> Note that RaiseEvent kicks off a write to storage access, but does not wait for the write to complete. For many applications, it is important to wait until we have confirmation that the event has been persisted. In that case, we always follow up by waiting for ConfirmEvents:

followed by a short code sample that calls `RaiseEvent` then simply does `await ConfirmEvents` and nothing more.

Is `ConfirmEvents` truly meant as _confirmation,_ the name implies something would be communicated back if the event was not successfully persisted. How is that failure communicated? If it fails, what should the caller do? (I realize that last question is more of a generic ES/actor-model question than Orleans-specific, but I still think the docs should offer guidance.)

Or does "confirmation" have some special meaning in ES logging that I'm not aware of? I dug through the logging code that is behind the call and it looks more like a "wait" activity than a confirmation mechanism (although the underlying code is pretty complicated and I don't completely understand what it's doing at this point).

**Comment by sergeybykov** [comment]
Tagging @sebastianburckhardt.

**Comment by sebastianburckhardt** [comment]
As the documentation says, `ConfirmEvents` waits until the events are successfully saved. There is an implicit retry loop which keeps trying to save the events (for example, if there are storage exceptions). If this never succeeds, then `ConfirmEvents` never finishes.
