### ISSUE TITLE
CQRS + Orleans = ?

### ISSUE THREAD

**Issue by jt4000** [dotnet/orleans#6110]
Is Microsoft Orleans fit to use for CQRS?

If yes, why?

**Comment by SebastianStehle** [comment]
Why not and about which variation of CQRS are you talking about?

**Comment by jt4000** [comment]
> Why not and about which variation of CQRS are you talking about?

I didn't know that there are variation of CQRS. Well, we can take all of them.

**Comment by SebastianStehle** [comment]
CQRS means to separate writes from reads, nothing more. You do not need event sourcing, no eventual consistency, no command bus, no event queue and so on:

https://lostechies.com/jimmybogard/2012/08/22/busting-some-cqrs-myths/
