### ISSUE TITLE
Codegen ignores negative integer type codes for TypeCodeOverride attribute

### ISSUE THREAD

**Issue by yevhen** [dotnet/orleans#6114]
The grain interface and class codes could be a negative integer as returned by [Utils.CalculateIdHash](https://github.com/dotnet/orleans/blob/master/src/Orleans.Core/Utils/Utils.cs#L200) But codegen skips such codes and instead is falling back to re-calculation.
https://github.com/dotnet/orleans/blob/bc41bf386095a335b7ccaeda431b5ebf2fd9ac60/src/Orleans.Core/CodeGeneration/GrainInterfaceUtils.cs#L424

Having `TypeCodeOverride` is a nice workaround for system evolution scenarios where names/assemblies of the grain interfaces and classes may change, and the ability to leave the old type code is crucial. It would be great if this could be patch fixed for 2.4.

**Comment by yevhen** [comment]
Guys, would you accept a PR for that?

**Comment by ReubenBond** [comment]
@yevhen certainly, that would be great- apologies for the slow reply
