### ISSUE TITLE
Can two grains of the same interface handle one reminder?

### ISSUE THREAD

**Issue by vyshkant** [dotnet/orleans#6116]
Hi!

Suppose we have two grains implementing one grain interface. `Grain-1` defines a reminder that was persisted, so on the next silo start it will be rised. Can `Grain-2` consume this reminder if `Grain-1` wasn't registered after reboot (but `Grain-2` was)?

Specifically, my case is this: I need to implement a way to disable some functionality (`Grain-1`), while retaining the ability to dummy-access it (`Grain-2` - dummy). At the same time, `Grain-1` creates a reminder that must be processed in a dummy way.

I hope for your help.

**Comment by sergeybykov** [comment]
Reminders are registered per grain. So, only the grain that registered a reminder will receive ticks from it.

I'm not sure what you mean by "registered" in the following sentence:
> if Grain-1 wasn't registered after reboot (but Grain-2 was)?

If Grain-1 registered a reminder, it will be invoked when the time comes. It can call Grain-2 as that point if needed. Unless I misunderstood your question.

**Comment by vyshkant** [comment]
Thanks for the answer!
