### ISSUE TITLE
Docs: CREATE TABLE OrleansQuery script missing from ADO.NET script links

### ISSUE THREAD

**Issue by mv10-work** [dotnet/orleans#6117]
Release 3.0 removed the scripts from the NuGet packages, but the documentation is missing a link to the "main" script which applies some database settings, and critically, creates the `OrleansQuery` table needed by all the other scripts. Consequently none of the other scripts can be executed for a new database. I only use SQL Server (the script used to be named `SQLServer-Main.sql`) but I assume the same problem applies for the other database types. (Luckily I have this file from some 2.x projects and I'm guessing it didn't change for 3.0.)

The scripts are listed [here](http://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/adonet_configuration.html) which are accessed from a link in the docs [here](http://dotnet.github.io/orleans/Documentation/grains/grain_persistence/relational_storage.html#realization-of-the-goals).

I noticed a couple of other minor issues on this page:

The intro paragraph says "The Orleans data storage layout has been explained already in Runtime Tables," but the docs don't contain a topic by that name, that I can find.

The section titled [Realization of the Goals](http://dotnet.github.io/orleans/Documentation/grains/grain_persistence/relational_storage.html#realization-of-the-goals) ends with a invalid link ("included in the database scripts").

**Comment by sergeybykov** [comment]
I submitted #6118 to add information about Shared/Main SQL scripts.

**Comment by veikkoeeva** [comment]
I'll cross-reference https://github.com/dotnet/orleans/pull/6097 directly too.

**Comment by sergeybykov** [comment]
Resolved via #6118.
