### ISSUE TITLE
Testing GrainServices in Orleans 2.4.2

### ISSUE THREAD

**Issue by virnemi** [dotnet/orleans#6123]
Hi there! 

I'm a new bee in Orleans, I just joined a team which uses this fantastic tech and now We're in charge of developing some tests **(version 2.4.2)**.

I got to this GrainService and using TestCluster in xUnit I just can't get to the service in the tests. This always returns NULL.

Here are some code from the classes:

Fixture configuring the service in the cluster silos:

```C#
private class SiloBuilderConfigurator : ISiloBuilderConfigurator
 {
    public void Configure(ISiloHostBuilder hostBuilder)
    {
        hostBuilder.ConfigureServices(services =>
        {
          // This two lines below was a try to fix a runtime exception explained in details further on...
            services.AddSingleton<FakeGrainIdentity>();
            services.AddSingleton<IGrainIdentity>(_ => _.GetService<FakeGrainIdentity>());
              ...
            services.AddSingleton<RmdsSubscriptionService>();
            services.AddSingleton<IRmdsSubscriptionService>(_ => _.GetService<RmdsSubscriptionService>());

        });
    }
}

public ClusterFixture()
{
    var builder = new TestClusterBuilder();

    builder.ConfigureHostConfiguration(config =>
    {
        config.AddInMemoryCollection(new Dictionary<string, string>()
        {
            { nameof(TestClusterId), TestClusterId }
        });
    });

    builder.AddSiloBuilderConfigurator<SiloBuilderConfigurator>();

    Cluster = builder.Build();
    Cluster.Deploy();

}
```

Then the GrainService constructor (where the problem raises):

```C#
    [Reentrant]
    [OneInstancePerCluster]
    public class RmdsSubscriptionService : GrainService, IRmdsSubscriptionService
    {
        ....
        public RmdsSubscriptionService(IGrainIdentity grainId, Silo silo, ILoggerFactory loggerFactory, IGrainFactory grainFactory)
            : base(grainId, silo, loggerFactory) // <== The Exception used to occour here in the GrainId casting.
        {
            this.logger = loggerFactory.CreateLogger(nameof(RmdsSubscriptionService));

            subscriptions = ImmutableArray<ISubscription>.Empty;

            this.grainFactory = grainFactory;
        }
       
    }
```
I implemented a FakeGrainIdentity inheriting IGrainIdentity to try to accomplish a DI in the service constructor but even with this the exception raises as follows:
System.InvalidCastException : Unable to cast object of type 'Grains.Tests.FakeGrainIdentity' to type 'Orleans.Runtime.GrainId'.

After some researching I found an example that uses the GetServiceByName in the ServiceProvider, but it keeps returning NULL.

I tried some code as follows:

```C#
// 1st try:
var rmdsService = _fixture.Cluster.ServiceProvider.GetServiceByName<RmdsSubscriptionService>(nameof(RmdsSubscriptionService));

// 2nd try:
var rmdsService = _fixture.Cluster.ServiceProvider.GetServiceByName<RmdsSubscriptionService>(_fixture.TestClusterId);
```

I'm stock in this code with no success. What am I doing wrong? What am I missing here? 

Please help!

Thanks beforehands!

**Comment by sergeybykov** [comment]
I'm not sure I understand why you are trying to inject `grainId`. It is generated by the runtime and is passed to the constructor just for the code to store it in a variable if it needs to. I don't see what you'd get by substituting it with `FakeGrainIdentity`.

**Comment by virnemi** [comment]
Hi @sergeybykov !

The creation of the FakeGrainEntity came within a try to resolve the exception below (as I commented in the service's constructor above):
```C#
System.InvalidOperationException
  HResult=0x80131509
  Message=Unable to resolve service for type 'Orleans.Core.IGrainIdentity' while attempting to activate 'MyProject.Grains.RmdsSubscriptionService'.
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at MyProject.Grains.Tests.ClusterFixture.SiloBuilderConfigurator.<>c.<Configure>b__0_2(IServiceCollection services) in C:\workspace\MyProject.Grains.Tests\Cluster\ClusterFixture.cs:line 171
```

So, after some searching we tried to mock the IGrainIdentity with NSubstitute and after this, I tried to supply the runtime with an implementation of IGrainIdentity, but with no success.

Now what we have is:

1) The scenario with no FakeGrainIdentity registred in the IServiceCollection and reaching the above exception; 

2) Registering this implementation and getting the cast exception below:
```C#
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'MyProject.Grains.Tests.FakeGrainIdentity' to type 'Orleans.Runtime.GrainId'.
  Source=Orleans.Runtime
  StackTrace:
   at Orleans.Runtime.GrainService..ctor(IGrainIdentity grainId, Silo silo, ILoggerFactory loggerFactory)
   at MyProject.Grains.RmdsSubscriptionService..ctor(IGrainIdentity grainId, Silo silo, ILoggerFactory loggerFactory, IGrainFactory grainFactory) in C:\workspace\MyProject.Grains\RmdsSubscriptionService.cs:line 47
```

3) We finally got the GraindId injected by adding the service using the **AddGrainService** method of the ISiloHostBuilder extension. The problem is that it becomes as a IGrainService and not our service's interface and another limitation is that, this method extension can only support one GrainService registration per Silo (according to the docs).

Any suggestions?

**Comment by virnemi** [comment]
**UPDATE**

We removed the `FakeGrainIdentity` and its interface from the project.

After referencing the DI in the class `ClusterFixture` and registering our service as the code below, we could accomplish the inclusion of the service in the silos' ServiceCollection dictionary (we could check this by breakpointing the constructor of the service):

```C#
public void Configure(ISiloHostBuilder hostBuilder)
{
    hostBuilder.ConfigureServices(services =>
    {
        // add the service in a way that lets us extract it afterwards
        services.AddSingleton<IRmdsSubscriptionService, RmdsSubscriptionService>();

        // this is the new line of code we put to get it "constructed correctly"
        services.AddGrainService<RmdsSubscriptionService>();
    });
                
    hostBuilder.UseServiceProviderFactory(services =>
    {
        var provider = services.BuildServiceProvider();
        var config = provider.GetService<Microsoft.Extensions.Configuration.IConfiguration>();

        // grab the cluster id that owns this silo
        var clusterId = config[nameof(TestClusterId)];

        // extract the service from the silo so unit tests can access it
        RmdsSubscriptionServices[clusterId].Add(provider.GetService<RmdsSubscriptionService>());
        return provider;
    });
```

Even with this service in the ServiceProvider, the Unit Test keeps returning NULL whenever it is called, as the below code:

```C#
[Fact]
public void RmdsSubscriptionService_Test()
{
    var rmdsService = _fixture.Cluster.ServiceProvider.GetService<RmdsSubscriptionService>();
    var st = rmdsService.Subscribe(new Subscription());
    Assert.Equal(st, Task.CompletedTask);
}
```

Please help!

**Comment by sergeybykov** [comment]
I think I understand now. You need to invoke your grain service via an implementation of `GrainServiceClient<IRmdsSubscriptionService>`.

Take a look at https://github.com/dotnet/orleans/blob/master/test/Tester/GrainServiceTests/TestGrainService.cs#L18 and https://github.com/dotnet/orleans/blob/master/test/Tester/GrainServiceTests/GrainServiceTests.cs#L11 for an example.

**Comment by virnemi** [comment]
Thanks @sergeybykov !

That's exactly what we wanted! 

I had browsed the examples but didn't see this as the solution. After reading more about the architecture and reading those classes more carefully I could understand how to test the Services' behavior.
