### ISSUE TITLE
Orleans.TestCluster cannot be used at the same time as the unit test. AspNetCore.TestServer is used at the same time.

### ISSUE THREAD

**Issue by lfzm** [dotnet/orleans#6125]
Orleans.TestCluster cannot be used at the same time as the unit test. AspNetCore.TestServer is used at the same time.
Is there any other solution?
```
            var webHostBuilder = new WebHostBuilder().UseStartup<HttpStartup>();
            this.Server = new TestServer(webHostBuilder);

            var builder = new TestClusterBuilder(1);
            builder.Options.BaseSiloPort = 1000; // this works, while ISiloBuilderConfigurator does not
            builder.Options.BaseGatewayPort = 1001;
            builder.AddClientBuilderConfigurator<ClientBuilderConfigurator>();
            builder.AddSiloBuilderConfigurator<SiloBuilderConfigurator>();
            var cluster = builder.Build();
            cluster.DeployAsync().Wait();
            this.Client = cluster.Client;
```

**Comment by ReubenBond** [comment]
What error do you see? Apologies for the slow reply. Is this still an issue?

**Comment by ReubenBond** [comment]
Closing for now. We can reopen if this is still an issue

**Comment by aelij** [comment]
@ReubenBond I think what they meant was how to integrate the two. `TestServer` and `TestClusterBuilder` both initialize separate DI engines. In a real project that use `UseOrleans` this separation doesn't work well... We register all of our dependencies in the Startup class, used both by grains and controllers.

We've hit this issue right now. It would be great if you could add such sample to `AspNetCoreCohosting`.

**Comment by ReubenBond** [comment]
Could you demonstrate how you would like this to look, @aelij or @lfzm?

**Comment by aelij** [comment]
This is how we worked around it:

```cs
        class OrleansInTestsHostBuilder : IHostBuilder
        {
            private readonly IServiceCollection _services;
            private readonly List<Action<HostBuilderContext, IServiceCollection>> _configureDelegates;

            public OrleansInTestsHostBuilder(IServiceCollection services)
            {
                _services = services;

                _configureDelegates = new List<Action<HostBuilderContext, IServiceCollection>>();

                Properties = new Dictionary<object, object>();
            }

            public void Build()
            {
                var context = new HostBuilderContext(Properties);
                foreach (var configureDelegate in _configureDelegates)
                {
                    configureDelegate(context, _services);
                }

                _services.AddSingleton<ITestClusterPortAllocator, TestClusterPortAllocator>();

                _services.AddOptions<EndpointOptions>().Configure<ITestClusterPortAllocator>((options, allocator) =>
                {
                    var ports = allocator.AllocateConsecutivePortPairs(5);
                    options.AdvertisedIPAddress = IPAddress.Loopback;
                    options.SiloPort = ports.Item1;
                    options.GatewayPort = ports.Item2;
                    options.SiloListeningEndpoint = new IPEndPoint(IPAddress.Loopback, options.SiloPort);
                    options.GatewayListeningEndpoint = new IPEndPoint(IPAddress.Loopback, options.GatewayPort);
                });
            }

            public IDictionary<object, object> Properties { get; }

            public IHostBuilder ConfigureServices(Action<HostBuilderContext, IServiceCollection> configureDelegate)
            {
                _configureDelegates.Add(configureDelegate);
                return this;
            }

            IHost IHostBuilder.Build() => throw new NotSupportedException();

            IHostBuilder IHostBuilder.ConfigureAppConfiguration(Action<HostBuilderContext, IConfigurationBuilder> configureDelegate) => throw new NotSupportedException();

            IHostBuilder IHostBuilder.ConfigureContainer<TContainerBuilder>(Action<HostBuilderContext, TContainerBuilder> configureDelegate) => throw new NotSupportedException();

            IHostBuilder IHostBuilder.ConfigureHostConfiguration(Action<IConfigurationBuilder> configureDelegate) => throw new NotSupportedException();

            IHostBuilder IHostBuilder.UseServiceProviderFactory<TContainerBuilder>(IServiceProviderFactory<TContainerBuilder> factory) => throw new NotSupportedException();

            IHostBuilder IHostBuilder.UseServiceProviderFactory<TContainerBuilder>(Func<HostBuilderContext, IServiceProviderFactory<TContainerBuilder>> factory) => throw new NotSupportedException();
        }
    }
```

And then just use `UseOrleans`:

```cs
        TestServer CreateTestServer()
        {
            var hostBuilder = new WebHostBuilder();
            hostBuilder.ConfigureTestServices(services =>
            {
               var builder = new OrleansInTestsHostBuilder(services);
               builder.UseOrleans(...);
               builder.Build();
            });
            return new TestServer(hostBuilder);
        }
```

Are there problems with this workaround? There's lots of stuff going on in the `Orleans.TestingHost` assembly which we skipped. Do you think you could build an API that would not require it? For example, an `AddOrleans` method that works with `IServiceCollection`.

**Comment by ReubenBond** [comment]
Is the issue here actually that TestServer doesn't support the newer `IHostBuilder` interface?

**Comment by aelij** [comment]
Yeah. And also:

> There's lots of stuff going on in the Orleans.TestingHost assembly which we skipped.

**Comment by aelij** [comment]
What's the difference between `UseOrleans` with in-memory providers and `TestCluster`?

**Comment by ReubenBond** [comment]
`TestCluster` calls `UseOrleans` eventually, but contains a bunch of methods to orchestrate more than just one silo. By default, you get 2 silos and a client, communicating with each other via localhost TCP.

The reason that the `TestCluster` is structured the way that it is largely for flexibility. Some of our tests use `AppDomains` for each silo, and theoretically, you could use separate processes or even separate hosts for each silo. The default options do not use `AppDomains` and all silos and clients are created in the default `AppDomain`.

Admittedly, this does result in some confusion for some users, particularly when it comes to configuring the silos.

`TestCluster` uses `IHostBuilder` internally, and you can configure those host builder instances before they're built, using the `AddSiloBuilderConfigurator<T>()` methods on the `TestClusterBuilder`

**Comment by aelij** [comment]
So basically all we lost is the multi-silo ability?

**Comment by ReubenBond** [comment]
Hard to say precisely what the implication would be, but as an example: perhaps your code accidentally communicates via some shared singleton and doesn't work in a multi-node environment correctly because of that, but single-host tests wouldn't find such a thing.

In most cases, it's not an issue.

**Comment by aelij** [comment]
Ok, thanks! And please consider adding an API that's compatible with `TestServer`.

**Comment by ReubenBond** [comment]
I'm not sure what such an API would look like, this seems to mostly be an issue with TestServer, not Orleans

**Comment by aelij** [comment]
Why does Orleans even need to use `IHostBuilder`? Seems like a method like `AddOrleans(this IServiceCollection)` could work just as well and would be less limiting.

**Comment by ReubenBond** [comment]
It's used for `IConfiguration` and the properties dictionary, or to allow switching on the environment value.

Can TestServer use IServiceCollection?

**Comment by aelij** [comment]
Yes, it can.
`IConfiguration` can be passed into the Add method, and I think the properties dictionary could be avoided.

**Comment by ReubenBond** [comment]
I think we'd gladly accept a PR to implement support for adding an ISiloBuilder directly to an IServiceCollection, if you're keen and can afford the time investment. Hopefully for the time being, you have a workable solution
