### ISSUE TITLE
ADO.NET persistence logs connection string credentials

### ISSUE THREAD

**Issue by mv10-work** [dotnet/orleans#6134]
I have noticed that the ADO.NET persistence package logs the complete connection string, including credentials. This would seem to be a security risk. We'll only deploy using `Warning` level logging so in practice this won't compromise production credentials, and we use Serilog so I could probably filter that out specifically, but it would probably be much more efficient to redact the content at the log output point. If it matters, I use SQL Server, I don't know if this is a problem with other database packages.

> [08:32:34 INF] Initialized storage provider: ServiceId=XXX ProviderName=Default Invariant=System.Data.SqlClient ConnectionString=Data Source=XXX;Database=XXX;User Id=XXX;Password=XXX;.

**Comment by veikkoeeva** [comment]
Should this be closed already, @benjaminpetit ?

**Comment by sergeybykov** [comment]
Resolved via #6139.
