### ISSUE TITLE
Custom Placement Director - resolve grain type from PlacementTarget

### ISSUE THREAD

**Issue by shlomiw** [dotnet/orleans#6135]
Hi,

I'm implementing a custom placement director with logic depended on the grain type. I actually want to be able to set the grain type activation random **weight** per silo, by using external dynamic configuration.
Use case examples: 
- Only 80% chance per GameGrain for Silo-A to reduce load.
- 0% chance for Silo-A to allow shutting down the silo after all grains are deactivated, then I could update the silo.

In my placement director `OnAddActivation()` method I get the `PlacementTarget`, which has `GrainIdentity` with `TypeCode`.
I couldn't find a way to resolve the Grain actual type (interface or implementation class, I don't mind) from the `TypeCode`, I've tried to use the `IPlacementContext` but with no success. 
Looking on Orleans source code the resolvers are internal.

Please advise, thanks in advance!

**Comment by sergeybykov** [comment]
Unfortunately, calculation of type codes is a one-way hash operation - https://github.com/dotnet/orleans/blob/master/src/Orleans.Core/CodeGeneration/GrainInterfaceUtils.cs#L421. We are looking at addressing this at a fundamental level in 4.0.

For now, it might be easier to use `[TypeCodeOverride]` attributes to set explicit value for type codes.

**Comment by shlomiw** [comment]
Any other way to resolve the grain's interface? 
Maybe I can cache it somehow at the silo startup? through bootstrap provider?
I saw that `GrainTypeManager` is also internal.

**Comment by yevhen** [comment]
[TypeCodeOverride] is the only solution at the moment.
