### ISSUE TITLE
StatelessWorker grain: effect of registering a reference for injection

### ISSUE THREAD

**Issue by mv10-work** [dotnet/orleans#6136]
Is the proxy grain reference to a stateless grain associated with a specific silo and/or running instance, or can each method call go to any available instance (either on a specific silo or anywhere on the cluster)?

I'm using a stateless grain to cache some information that is relatively expensive to load and analyze but is used throughout the app. I'd rather add the reference to the DI service collection instead of calling the grain factory all over the place. However, I'm wondering if that would effectively make the entire app execute methods on a single grain instance.

If a proxy really is permanently tied to a specific instance, I suppose I could make it a transient-scoped factory service in `Startup.cs`. Or is this unnecessary and I'm just over-thinking it?

```csharp
services.AddTransient(typeof(IFooCache), 
    (provider) => provider.GetRequiredService<IClusterClient>()
    .GetGrain<IFooCache>(0));
```

**Comment by sergeybykov** [comment]
Can you clarify what you mean "stateless grain"? If you mean a grain class marked as `[StatelessWorker]`, then call made to such grain would always go to local to the caller's silo, by default multiple, instances of the grain.

**Comment by mv10-work** [comment]
Yes, a `[StatelessWorker]` grain. The caller is on a separate server which is only connected through `IClusterClient` so I'm not sure what "the caller's silo" means. A cluster client isn't bound to one silo right?

To re-state how I'm interpreting your answer, if I have `class A` and `class B` and they both inject the same single registered instance of `IFooCache` which is a `[StatelessWorker]` grain registered for scoped injection, they'll both use the same silo but potentially different instances (CPUs)?

Would injecting a transient scoped factory (as shown earlier) potentially use other silo servers when the proxy grain reference is created for injection?

**Comment by sergeybykov** [comment]
@mv10-work Have you solved this since?

**Comment by MV10** [comment]
@sergeybykov We're no longer planning to use Orleans, so I haven't done anything new or differently relating to this question.
