### ISSUE TITLE
Breaking change in KnownAssemblyAttribute

### ISSUE THREAD

**Issue by yevhen** [dotnet/orleans#6140]
After migrating to 2.4.4 from 2.1.x I've stumbled across a breaking change that was done in this [commit](https://github.com/dotnet/orleans/commit/ffabe550a7891e7378f9f076e88a8e3c184d967f#diff-b3bf91c2bcb0bd950e3e704db47be338) to a `KnownAssemblyAttribute`. One of the constructors was [removed](https://github.com/dotnet/orleans/commit/ffabe550a7891e7378f9f076e88a8e3c184d967f#diff-b3bf91c2bcb0bd950e3e704db47be338L20-L26).

It's a complete showstopper for all Orleankka 1.x users, since this ctor was used by Orleankka codegen. I did 21 transitional releases to make migration to 2.x possible just to realize that none of them will work with Orleans 2.4.4 which contains a critical patch 😞  

I see 2 solutions here:
1. Apply patch to `TypeCodeOverride` to 2.1.x branch (and have an official 2.1.x patch release from Orleans)
2. Bring back overload for upcoming 2.4.4 (perhaps, mark it as obsolete)

Which one will be more acceptable?

**Comment by yevhen** [comment]
Sorry, I didn’t investigate that deeply. If the type code override bug was introduced only in new codegen, it might be that there is no need to produce patch release and we can proceed with any 2.x release prior to that change. I’ll check this later

**Comment by yevhen** [comment]
Unfortunately, the bug #6114 was in Orleans from the very beginning. 

To resolve this situation the patch release for version (2.4.2) prior to the one where new codegen was introduced (2.4.3) is required. This [commit](https://github.com/yevhen/orleans/commit/8f2ca73078bfdb482c44a24b381c8c83ffe24225) need to be cherry picked on top of 2.4.2 tag. We can name this release as 2.4.2-6114 and I'll warn all Orleankka 1.x users (via migration guide) that this patch release is mandatory to use for all transitional versions.

**Comment by yevhen** [comment]
Oops, wrong version. Looks like we need patched 2.0.5-6114. The new codegen was introduced in 2.1.x

**Comment by ReubenBond** [comment]
I'm not sure I understand the issue. That constructor was problematic because .NET Core doesn't allow loading assemblies by name when they aren't referenced.

Is there some way around this problem which you can see? For example, could the Orleankka codegen emit attributes using the other ctor?

**Comment by yevhen** [comment]
well, I already published 11 releases that were relying on KnownAssembly api prior 2.1.0 :(

Either I need to rollback and re-publish them targeting Orleans > 2.1.0 or wait for patch release for 2.0.5. Looks like re-publishing them right after 2.4.4 is released is the only way to not give a hassle to you.

Ok. I'll wait for 2.4.4 and then republish all

**Comment by ReubenBond** [comment]
I'm very happy to make a change, and everything is up for discussion. I'm just not sure what the right change is. I feel that that particular constructor was 'wrong' either in its implementation or its specification. Having a property of type `Assembly` instead of `string` may be the root issue.

It's possible that we could move this information to a csproj instead, as long as the full assembly path could be specified. An `AssemblyName` string works as long as the assembly is referenced by the project (`ProjectReference`/`PackageReference`/`Reference`) so that it's available when code generation runs.

What do you think? Of course, making this change will take some time (it moves us into next week), but it might be the best way forward.

**Comment by yevhen** [comment]
No worries. I'll fix this on my side and redo releases against 2.4.4. At least now they will specify 2.4.4 as min version which is a good thing (better than warn about this in docs). Closing this issue.
