### ISSUE TITLE
Can i use"OnActivateAsync&OnDeactivateAsync" instead "storageprovider"?

### ISSUE THREAD

**Issue by orangeagain** [dotnet/orleans#6150]
I am confusion on "storageprovider",so i don't  want to use orlean's "storageprovider".
Can i use database persistence function in "OnActivateAsync()&OnDeactivateAsync()" instead "storageprovider"?

**Comment by SebastianStehle** [comment]
Sure, I use it myself.

**Comment by jason-bragg** [comment]
Yes, many users provide their own grain persistence rather than using storage providers.  I'd note that it's probably not safe to rely on OnDeactivateAsync, because it may not always be called, especially during silo crashes or hard shutdown.
