### ISSUE TITLE
What is the relationship between Dapr and Orleans?

### ISSUE THREAD

**Issue by aioloswong** [dotnet/orleans#6152]
What is the relationship between Dapr and Orleans? Will Dapr eventually replace Orleans?

**Comment by KSLcom** [comment]
From my point of view, Dapr looks like a competitor for Service Fabric not for Orleans.

**Comment by sergeybykov** [comment]
Dapr operates at a higher level of abstraction, primarily concerned with composition of application components and their binding to various data sources. Orleans-based components can be integrated with Dapr to benefit from the standardized composition and binding mechanisms.

**Comment by RehanSaeed** [comment]
I'm also trying to compare the two. Here is what Dapr have to say:

> The actors in Dapr are based on the same virtual actor concept that Orleans started, meaning that they are activated when called and garbage collected after a period of time. If you are familiar with Orleans, Dapr C# actors will be familiar. Dapr C# actors are based on Service Fabric Reliable Actors (which also came from Orleans) and enable you to take Reliable Actors in Service Fabric and migrate them to other hosting platforms such as Service Fabric Mesh, Kubernetes or other on-premise environments. Also Dapr is about more than just actors. It provides you with a set of best practice building blocks to build into any microservices application. 

[Dapr FAQ](https://github.com/dapr/dapr/wiki/FAQ)

When you look at a [sample Dapr actor](https://github.com/dapr/dotnet-sdk/blob/master/docs/get-started-dapr-actor.md), it does indeed look fairly similar with state, reminders and timers. Even the client looks similar but is using gRPC under the hood. I guess the main difference is it's trying to be language agnostic.

Another interesting read in https://github.com/dapr/dotnet-sdk/issues/201.
