### ISSUE TITLE
How Orleans (should) recover when one silo is not responsive?

### ISSUE THREAD

**Issue by shlomiw** [dotnet/orleans#6153]
Hi,

We had a bug which blocked all orleans pool threads (we fixed it).
It happened in our Production environment, and only in one silo, so this silo became unresponsive to other silos which received many timeouts to their requests to this silo.
It went for a long time, about 10-15 minutes, until we restarted the system.

My question - doesn't orleans have a built-in mechanism to monitor and detect such an unresponsive silo and shut it down and/or restart it or remove it from the silo's pool to allow continue of normal operation? am I missing something?

Thanks

**Comment by sergeybykov** [comment]
So long as the silo responds to ping messages, it is considered healthy from the other silos' perspective. Blocking an application thread or a specific grain would not prevent pings from getting processed. In other words, silo-level pings are too low level to detect a situation like that.

Application code can do more than that, and implement its own health checks, such as synthetic transactions. People do that today to tell their hosting environment, such as k8s or SF, about an unhealthy node.

There's no way today to feed this information to Orleans other than by shutting down of restarting a silo. Maybe we should consider an integration point for application health probes.

**Comment by shlomiw** [comment]
@sergeybykov - thanks for your reply, I didn't know the pings are that low level. Now I understand.
For now I will implement a kind of monitor myself.

I believe that since Orleans already have blocking task detection (which is great, this is how I was able to resolve the issue we had!), it could be enhanced that if *all* threads in the thread-pool are blocked for X minutes, then consider the silo node as faulted, try to shut-it-down, and remove from the silos pool, or raise an event so we could let the hosting infrastructure handle it.

Should I close this issue, or let it open maybe for future revision?

**Comment by sergeybykov** [comment]
>it could be enhanced that if all threads in the thread-pool are blocked for X minutes, then consider the silo node as faulted, try to shut-it-down, and remove from the silos pool, or raise an event so we could let the hosting infrastructure handle it.

What we see some people doing is they send health-probe-like grain calls to each of the silos to detect that a silo is not responsive. My intuition is that an outside probe like that is more reliable than trying to infer a failure from within a silo itself. Maybe we could define a standard way to register an application-specific health probe method, so that other silos and/or the hosting infrastructure would periodically call it in addition to the low-level cluster membership pings?
