### ISSUE TITLE
Increased exception rate with 3.0.1 

### ISSUE THREAD

**Issue by Ulriksen** [dotnet/orleans#6156]
We updated to 3.0.0 on Friday but had to rewert on Monday as we experienced a noticable increase in exceptions. Downgrading to 3.0.0 we no longer see these exceptions. 

![image](https://user-images.githubusercontent.com/594884/70117556-0e437a80-1666-11ea-8465-533026945aa2.png)

See the attached xlsx file for a log sample. 

A single write operation looks like this 
![image](https://user-images.githubusercontent.com/594884/70118679-e275c400-1668-11ea-93ef-977160df7dd6.png). 

The exceptions occur in the storage provider, however the root cause may be outside of this. 

[sample exceptionlog.xlsx](https://github.com/dotnet/orleans/files/3920368/sample.exceptionlog.xlsx)

**Comment by benjaminpetit** [comment]
At first, the only change related to Azure Storage from 3.0.0 to 3.0.1 is #6071 , but it doesn't seems to be what is happening here.

Here you get `Conflict` because Orleasn try to write a state to storage without ETag (that should happen only at the first write), but Azure returns an error and says that there is already something in storage for this Grain.

It seems that you are only hitting this error with `KatalogDataGrain` grains. Do you have other grain with storage in your code?

**Comment by Ulriksen** [comment]
We looked at #6071 and concluded that it must be something else. We have several other grains with storage, however we do not see the same problems there. KatalogData is the only state in that specific storage account, but I do not believe the problem it is tied to Azure as the changes in exceptions rate correlate with both deployment and rollback. Read operations on KatalogData goes through the CachedKatalogData which is a stateless worker. If KatalogData is not initialized it fetches data from an external api and store it. As you can see it is not the most called grain, but it is in close to all instances activated from a stateless worker grain. 

![image](https://user-images.githubusercontent.com/594884/70174363-07078580-16d5-11ea-966e-8e262fdb6976.png)

I can make the grain code privately available if needed.

We've had the downgraded version in production for 24 hours, and are back to the normal of just above 100 exceptions.

**Comment by benjaminpetit** [comment]
Are you able to reproduce this in a test environment? Does other grain with state go though a StatelessWorker too?

**Comment by Ulriksen** [comment]
We've not seen it in our preproduction environment, however we do not have the same traffic load nor pattern there. We can try to increase our loadtests. 

CachedKatalogKobler (kobler == connector, maps external to internal id's) follows the same pattern, but KatalogData has 50 times the traffic

**Comment by benjaminpetit** [comment]
I looked everywhere and don't have an idea on what happened in your case. If you could send me a small repro, that would be very useful.


This Orleans 3.0.0 -> 3.0.1 was the only change in your deployment?

**Comment by Ulriksen** [comment]
Yes, it was during a high write period. We've decided to try 3.0.2 today to see if we could repliacte it. After running 3.0.2. in production for 2 hours we have not yet experienced this problem.
