### ISSUE TITLE
JournaledGrain should support injection of custom log consistency providers

### ISSUE THREAD

**Issue by srberard** [dotnet/orleans#6162]
According to the documentation [link](http://dotnet.github.io/orleans/Documentation/grains/event_sourcing/log_consistency_providers.html#orleanseventsourcingcustomstoragelogconsistencyprovider) a JournaledGrain with a custom log consistency provider needs to implement the ICustomStorageInterface interface.  This means that grain logic and storage implementations are intermixed which is undesirable.   

Instead, it would be better to support injecting the custom provider such that the two implementations can be separated. I.e. one should be able to change LogConsistencyProviders without changing the Grain implementation.

**Comment by MV10** [comment]
I don't see how this could work. An injected reference is something that the grain _uses_... something that it must actively call. Implementing `ICustomStorageInterface` provides methods that the rest of the log consistency infrastructure (like `LogViewAdaptor`) use to orchestrate event storage and state transitions. Those concerns are managed externally to `JournaledGrain`.

That being said, in a recent implementation I wanted to pursue a DDD + CQRS approach alongside event sourcing (with event logging and snapshots), so I carefully separated my state (domain model) and events (domain events), and my grain is really just a state-manager and event/snapshot storage system based on the CustomStorage log consistency provider. For CQRS to work I had to expose methods like `RaiseEvent` but that was trivial. I suppose it violates the "pure" actor model, but it works well. In effect, the `JournaledGrain` becomes the replaceable implementation akin to what you want to achieve with injection, I think.

Coincidentally, I posted an article about this earlier today. It runs a bit long but maybe you'll find it useful. The repo is [here](https://github.com/MV10/OrleansEventStreamLog).

**Comment by srberard** [comment]
Thanks Jon for the input and links,
You're right, making it *injected*, as is done with IPersistentState<TState>, into the grain likely won't work.  As you pointed out, unlike normal grain persistence in which the grain calls the provider, the JournaledGrain relies on the journaling infrastructure to call the provider.  Regardless, one should be able to plug in a new log provider independently from the grain implementation.  I changed the title to reflect this.

**Comment by MV10** [comment]
In my real implementation (still heavily based on the code in my public repo), nearly all of the CustomStorage code ended up in the `EventSourcedGrain` base class (part of my implementation, not part of Orleans), which itself subclasses `JournaledGrain` and implements `ICustomStorageInterface`. I made the base class abstract and added a few abstract methods which the grain class has to provide so that the non-grain-specific base class could provide CustomStorage support to any grain.

A similar approach might work for you -- derive your grain from an abstract base class which has abstract methods as extension points, have your grain constructor-inject the storage implementation it wants, and use those abstract methods to hand off the injected references when the base class needs them.

**Comment by srberard** [comment]
Thanks Jon,
I did a similar thing in my implementation as well (i.e. using a base class to handle the custom storage code).  It works and is about as clean as it can be given the way this works with Orleans today.  Still, changing providers requires changing the grain code.  With normal persistence in Orleans, one can change the configuration in the silo without having to modify the grains.  This is useful as it allows you to have the same grain work in a local dev silo, in the cloud, in a Kubernetes cluster, etc. as the persistence choice is configurable.  I think we should be able to do the same with JournaledGrains.
