### ISSUE TITLE
The best way to expose Grains through WebSockets?

### ISSUE THREAD

**Issue by Toktik** [dotnet/orleans#6164]
What is the best way to expose the grains through web sockets? I mean in terms of architecture.

Ideally I want to call the grain methods from frontend (smart mapping with SignalR maybe).

Anyone has experience with this?

**Comment by MV10** [comment]
Are you familiar with [Orleans.Http](https://github.com/OrleansContrib/Orleans.Http)?

It isn't using web sockets but it's probably much easier to just use that, than to try to come up with your own protocol over web sockets. If you have to use web sockets for some reason, that project is still probably a good approach to emulate.

**Comment by sergeybykov** [comment]
+1
