### ISSUE TITLE
Orleans for digital signal processing system

### ISSUE THREAD

**Issue by rsulab** [dotnet/orleans#6176]
Hi, is it possible use Orleans to create a distributed real time digital signal processing system?

For example, I need to use web sockets to get the time series data stream - to process it with a pipeline of heavy algorithms (FFT) and give the result back to the web socket.

Is Orleans good choice for same task?

**Comment by sergeybykov** [comment]
I think the answer depends on the latency budget and acceptable percentile of responses within that budget. If it's milliseconds, and occasional delayed responses (due to GC) are okay, then I think it might work.
