### ISSUE TITLE
Doc states that StaticGatewayListProvider is not updatable though it is not true.

### ISSUE THREAD

**Issue by victor-yarema** [dotnet/orleans#6177]
The documentation for "IGatewayListProvider.IsUpdatable" states that "StaticGatewayListProvider is not updatable":
https://github.com/dotnet/orleans/blob/425be00b30f4d3f80f53594134dbe4df5d7b053b/src/Orleans.Core/Messaging/IGatewayListProvider.cs#L27-L31
But the "StaticGatewayListProvider.IsUpdatable" always returns "true":
https://github.com/dotnet/orleans/blob/425be00b30f4d3f80f53594134dbe4df5d7b053b/src/Orleans.Core/Messaging/StaticGatewayListProvider.cs#L29-L32
Issues:
- The statement is not correct.
- If all providers return "true" then this property may not be even needed at all.

**Comment by ReubenBond** [comment]
We should probably remove the property and assume it is always true.

For the static provider, we return true because some gateways may be marked as 'dead' due to transient errors and these gateways should be retried periodically.
