### ISSUE TITLE
If a grain implementation class doesn't derive from Grain, the error message is unhelpful

### ISSUE THREAD

**Issue by OracPrime** [dotnet/orleans#6194]
I had a project with IMyGrain which inherited from IGrainWithIntegerKey, but I forget to derive the implementation class from Grain.

This all compiles with no warning (as IGrainWithIntegerKey has no methods to implement), but at runtime fails with "cannot find an implementation class" when I call GetGrain<IMyGrain>().

I feel this could be more helpfully spotted.

**Comment by sergeybykov** [comment]
We are looking into making inheriting from `Grain` unnecessary in 4.0. In the meantime, is there a way to give a useful warning? By flagging any non-abstract class that implements `IGrainWithXKey` and doesn't inherit from `Grain`?

**Comment by gulbanana** [comment]
An analyzer could be used for this, the way Xunit does it.

**Comment by QueenCitySmitty** [comment]
Can this be closed?
