### ISSUE TITLE
3.0.2 Linux build.sh errors

### ISSUE THREAD

**Issue by kestess** [dotnet/orleans#6195]
build.sh doesn't work for 3.0.2 Orleans on Ubuntu 18.04. The file /opt/code/OrleansCrossPlatform.sln.metaproj isn't present on my computer, so I'm pretty sure it's in the docker container. 

ivy@zerofluid:~/orleans-3.0.2$ sudo ./build.sh 
Launching build in Docker Container
Running command: /opt/code/run-build.sh
Using code from: /home/ivy/orleans-3.0.2
Unable to find image 'mcr.microsoft.com/dotnet/core/sdk:3.0' locally
3.0: Pulling from dotnet/core/sdk
16ea0e8c8879: Pull complete 
50024b0106d5: Pull complete 
ff95660c6937: Pull complete 
9c7d0e5c0bc2: Pull complete 
063a4686bd41: Pull complete 
cec5fae69b11: Pull complete 
adbf0f5973d9: Pull complete 
403487be26e6: Pull complete 
Digest: sha256:9491613d05e3684fec39f8e8ca91f7de2ee35cc6503b77739c505c4506ccb9c5
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/sdk:3.0
Microsoft (R) Build Engine version 16.3.2+e481bbf88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/opt/code/OrleansCrossPlatform.sln.metaproj : error MSB4126: The specified solution configuration "|Any CPU" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [/opt/code/OrleansCrossPlatform.sln]

Build FAILED.

/opt/code/OrleansCrossPlatform.sln.metaproj : error MSB4126: The specified solution configuration "|Any CPU" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [/opt/code/OrleansCrossPlatform.sln]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.19

**Comment by kestess** [comment]
The file is in the top-level directory of the orleans-3.0.2 directory. After running these three lines...
sed -i '/|Any CPU/d' OrleansCrossPlatform.sln
sed -i '/|x64/d' OrleansCrossPlatform.sln
sed -i '/|x86/d' OrleansCrossPlatform.sln

...I get a warning:

ivy@zerofluid:~/orleans-3.0.2$ sudo ./build.sh
Launching build in Docker Container
Running command: /opt/code/run-build.sh
Using code from: /home/ivy/orleans-3.0.2
Microsoft (R) Build Engine version 16.3.2+e481bbf88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/3.0.101/NuGet.targets(123,5): warning : Unable to find a project to restore! [/opt/code/OrleansCrossPlatform.sln]

Build succeeded.

/usr/share/dotnet/sdk/3.0.101/NuGet.targets(123,5): warning : Unable to find a project to restore! [/opt/code/OrleansCrossPlatform.sln]
    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.20
Microsoft (R) Build Engine version 16.3.2+e481bbf88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/3.0.101/NuGet.targets(123,5): warning : Unable to find a project to restore! [/opt/code/OrleansCrossPlatform.sln]

Is there a version of OrleansCrossPlatform.sln that works for Linux? Why does the error report the wrong path?

**Comment by kestess** [comment]
"dotnet build OrleansCrossPlatform.sln" results in a little more success, but results in this:

  Restore completed in 2.16 sec for /home/ivy/orleans-3.0.2/src/Orleans.Streaming.GCP/Orleans.Streaming.GCP.csproj.
  fatal: not a git repository (or any of the parent directories): .git
/home/ivy/.nuget/packages/sourcelink.create.commandline/2.8.3/build/SourceLink.Create.CommandLine.targets(21,5): error MSB3073: The command "git rev-parse --show-toplevel" exited with code 128. [/home/ivy/orleans-3.0.2/src/Orleans.Core.Abstractions/Orleans.Core.Abstractions.csproj]
  fatal: not a git repository (or any of the parent directories): .git
/home/ivy/.nuget/packages/sourcelink.create.commandline/2.8.3/build/SourceLink.Create.CommandLine.targets(21,5): error MSB3073: The command "git rev-parse --show-toplevel" exited with code 128. [/home/ivy/orleans-3.0.2/src/Orleans.CodeGenerator/Orleans.CodeGenerator.csproj]
  Orleans.CodeGenerator.MSBuild.Tasks -> /home/ivy/orleans-3.0.2/src/Orleans.CodeGenerator.MSBuild.Tasks/bin/Debug/netstandard2.0/Orleans.CodeGenerator.MSBuild.Tasks.dll

Build FAILED.

/home/ivy/.nuget/packages/sourcelink.create.commandline/2.8.3/build/SourceLink.Create.CommandLine.targets(21,5): error MSB3073: The command "git rev-parse --show-toplevel" exited with code 128. [/home/ivy/orleans-3.0.2/src/Orleans.Core.Abstractions/Orleans.Core.Abstractions.csproj]
/home/ivy/.nuget/packages/sourcelink.create.commandline/2.8.3/build/SourceLink.Create.CommandLine.targets(21,5): error MSB3073: The command "git rev-parse --show-toplevel" exited with code 128. [/home/ivy/orleans-3.0.2/src/Orleans.CodeGenerator/Orleans.CodeGenerator.csproj]
    0 Warning(s)
    2 Error(s)

I had downloaded the 3.0.2 tar.gz - apparently I should have git'ted it.

**Comment by kestess** [comment]
Cloned at d1a91965daa20045f96dad3f0c84371a7498af68 and ran:

dotnet build Orleans.sln

It builds without errors.

**Comment by kestess** [comment]
However, if I cd to ~/orleans/Samples/3.0/HelloWorld and run ./BuildAndRun.sh:

ivy@zerofluid:~/orleans/Samples/3.0/HelloWorld$ ./BuildAndRun.sh 
  Restore completed in 755.92 ms for /home/ivy/orleans/Samples/3.0/HelloWorld/src/HelloWorld.Interfaces/HelloWorld.Interfaces.csproj.
  Restore completed in 823.78 ms for /home/ivy/orleans/Samples/3.0/HelloWorld/src/HelloWorld.Grains/HelloWorld.Grains.csproj.
  Restore completed in 943.9 ms for /home/ivy/orleans/Samples/3.0/HelloWorld/src/OrleansClient/OrleansClient.csproj.
  Restore completed in 950.1 ms for /home/ivy/orleans/Samples/3.0/HelloWorld/src/SiloHost/SiloHost.csproj.
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/home/ivy/.nuget/packages/microsoft.orleans.codegenerator.msbuild/3.0.0/build/Microsoft.Orleans.CodeGenerator.MSBuild.targets(118,5): error MSB4062: The "Orleans.CodeGenerator.MSBuild.Tasks.GetDotNetHost" task could not be loaded from the assembly /home/ivy/.nuget/packages/microsoft.orleans.codegenerator.msbuild/3.0.0/build/../tasks/netcoreapp3.0/Orleans.CodeGenerator.MSBuild.Tasks.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [/home/ivy/orleans/Samples/3.0/HelloWorld/src/HelloWorld.Interfaces/HelloWorld.Interfaces.csproj]

Build FAILED.

/home/ivy/.nuget/packages/microsoft.orleans.codegenerator.msbuild/3.0.0/build/Microsoft.Orleans.CodeGenerator.MSBuild.targets(118,5): error MSB4062: The "Orleans.CodeGenerator.MSBuild.Tasks.GetDotNetHost" task could not be loaded from the assembly /home/ivy/.nuget/packages/microsoft.orleans.codegenerator.msbuild/3.0.0/build/../tasks/netcoreapp3.0/Orleans.CodeGenerator.MSBuild.Tasks.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [/home/ivy/orleans/Samples/3.0/HelloWorld/src/HelloWorld.Interfaces/HelloWorld.Interfaces.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.49
The application to execute does not exist: '/home/ivy/orleans/Samples/3.0/HelloWorld/src/SiloHost/bin/Debug/netcoreapp2.1/SiloHost.dll'

The problem is that I don't see how it's a duplicate because I deleted my .nuget directory before one of the runs and had exactly the same results.

**Comment by kestess** [comment]
It appears there are two - the MSBuild one stands out on a Linux box

ivy@zerofluid:~/orleans/src$ find . -name GetDotNetHost.cs

./Orleans.CodeGenerator.MSBuild.Tasks/GetDotNetHost.cs
./Orleans.CodeGeneration.Build/GetDotNetHost.cs

**Comment by kestess** [comment]
I cleaned up my installation a little and it appears the Orleans.CodeGenerator.MSBuild/ never built

ivy@zerofluid:~/orleans$ dotnet --list-sdks
3.1.100 [/usr/share/dotnet/sdk]
ivy@zerofluid:~/orleans$ dotnet --list-runtimes
Microsoft.AspNetCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

this is received 4 times during the build of Orleans (dotnet build Orleans.sln):

/home/ivy/orleans/src/Orleans.CodeGenerator.MSBuild/build/Microsoft.Orleans.CodeGenerator.MSBuild.targets(117,5): error MSB4062: The "Orleans.CodeGenerator.MSBuild.Tasks.GetDotNetHost" task could not be loaded from the assembly /home/ivy/orleans/test/../src/BootstrapBuild/Orleans.CodeGenerator.MSBuild.Bootstrap/bin/Debug/publish/netcoreapp3.0/Orleans.CodeGenerator.MSBuild.Tasks.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [/home/ivy/orleans/test/Grains/BenchmarkGrains/BenchmarkGrains.csproj]

**Comment by kestess** [comment]
The above errors seem to be entirely my fault. I removed all my docker image and containers and remove all dotnet related packages and reinstalled one sdk:

```
ivy@zerofluid:~/orleans/Samples/3.0/HelloWorld$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  157910edee

.NET Core SDKs installed:
  3.1.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

The current error is:

```
ivy@zerofluid:~/orleans/Samples/3.0/HelloWorld$ ./BuildAndRun.sh 
  Restore completed in 339.82 ms for /home/ivy/orleans/Samples/3.0/HelloWorld/src/HelloWorld.Interfaces/HelloWorld.Interfaces.csproj.
  Restore completed in 386.63 ms for /home/ivy/orleans/Samples/3.0/HelloWorld/src/HelloWorld.Grains/HelloWorld.Grains.csproj.
  Restore completed in 467.7 ms for /home/ivy/orleans/Samples/3.0/HelloWorld/src/OrleansClient/OrleansClient.csproj.
  Restore completed in 468.55 ms for /home/ivy/orleans/Samples/3.0/HelloWorld/src/SiloHost/SiloHost.csproj.
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Orleans.CodeGenerator - command-line = SourceToSource /home/ivy/orleans/Samples/3.0/HelloWorld/src/HelloWorld.Interfaces/obj/Debug/netstandard2.0/HelloWorld.Interfaces.orleans.g.args.txt
  HelloWorld.Interfaces -> /home/ivy/orleans/Samples/3.0/HelloWorld/src/HelloWorld.Interfaces/bin/Debug/netstandard2.0/HelloWorld.Interfaces.dll
  Orleans.CodeGenerator - command-line = SourceToSource /home/ivy/orleans/Samples/3.0/HelloWorld/src/HelloWorld.Grains/obj/Debug/netstandard2.0/HelloWorld.Grains.orleans.g.args.txt
  OrleansClient -> /home/ivy/orleans/Samples/3.0/HelloWorld/src/OrleansClient/bin/Debug/netcoreapp2.1/OrleansClient.dll
  HelloWorld.Grains -> /home/ivy/orleans/Samples/3.0/HelloWorld/src/HelloWorld.Grains/bin/Debug/netstandard2.0/HelloWorld.Grains.dll
Program.cs(30,26): error CS1061: 'ISiloBuilder' does not contain a definition for 'AddAzureBlobGrainStorage' and no accessible extension method 'AddAzureBlobGrainStorage' accepting a first argument of type 'ISiloBuilder' could be found (are you missing a using directive or an assembly reference?) [/home/ivy/orleans/Samples/3.0/HelloWorld/src/SiloHost/SiloHost.csproj]

Build FAILED.

Program.cs(30,26): error CS1061: 'ISiloBuilder' does not contain a definition for 'AddAzureBlobGrainStorage' and no accessible extension method 'AddAzureBlobGrainStorage' accepting a first argument of type 'ISiloBuilder' could be found (are you missing a using directive or an assembly reference?) [/home/ivy/orleans/Samples/3.0/HelloWorld/src/SiloHost/SiloHost.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:07.00
The application to execute does not exist: '/home/ivy/orleans/Samples/3.0/HelloWorld/src/SiloHost/bin/Debug/netcoreapp2.1/SiloHost.dll'
```
I'm a little curious as to why AddAzureBlobGrainStorage is part of this.

**Comment by kestess** [comment]
That seems like a reasonable error since src/SIloHost/Program.cs has this part that seems to need configuring:

```
                        .AddMemoryGrainStorage(name: "ArchiveStorage")
                        .AddAzureBlobGrainStorage(
                            name: "profileStore",
                            configureOptions: options =>
                            {
                                // Use JSON for serializing the state in storage
                                options.UseJson = true;

                                // Configure the storage connection key
                   
             options.ConnectionString = "DefaultEndpointsProtocol=https;AccountName=data1;AccountKey=SOMETHING1";
                            });
```

**Comment by kestess** [comment]
I had to manually change all the files that weren't in git that had a netcore 2.1.0 to a 3.1.0 in about 7 places to get it to work - in the targets and json files. There is mention of a "build.cmd netstandard" command, but that didn't seem to help. There is no "netstandard" in BuildAndRun.sh.

After all this I think the Readme just needs a little more attention:
1) to address the Azure storage or have it commented out
2) give advice for changing the netstandard version automatically - none of the affected files were found by a "git diff", so I'm assuming that they were autogenerated. How can those be autogenerated correctly?

Thank you for your patience.

**Comment by ReubenBond** [comment]
Thank you for your patience, @kestess, and I'm glad you got it working in the end.

We don't use the build.sh file when building on Linux in our CI - we use `dotnet build .\Orleans.sln` instead. Still, the build.sh file should either be made to work or should be deleted - what do you prefer?

**Comment by kestess** [comment]
I think `dotnet build .\Orleans.sln` is easiest and would meet my needs, but the idea behind build.sh - using a standard image of dotnet core, is probably valuable for people trying to build Orleans in a pristine environment; however, the build.sh file needs to be renamed to something like buildDockerNetcore3.0.sh or something as informative but perhaps less hideous. Also, its generated packages and libraries shouldn't conflict with those generated by dotnet build .\Orleans.sln`. I'm not the customer that would push for this, but I could understand this being necessary in a build environment (VSO and Jenkins are referenced in the file).

**Comment by ReubenBond** [comment]
I'm not sure there's much value in building Orleans in a fresh container, other than for CI, but for CI we can do that without the script.

**Comment by kestess** [comment]
Then it appears there is no need for the files added with https://github.com/dotnet/orleans/commit/271cd8eb7a2d0a0d615ae1ca5b6c17d77b391023#diff-0b83f9dedf40d7356e5ca147a077acb4 since https://github.com/dotnet/orleans/pull/3602 was created to allow builds on non-Windows machines without .Net installed. Netcore is crossplatform now, so it appears the explicit docker builds aren't necessary - not as part of this repo anyway. It appears all the tools for a straightforward build have been provided so the associated files in the first commit should be deleted. Containerized builds of a project should not be part of a project since there are too many variables (netcore versions and associated nuget packages) - your team should only be responsible for the most straightforward build of your project - creating a build image and using it should be part of a different repo if that functionality is necessary. Removing "build" hat now - I almost forgot where that was. I'm somewhat embarrassed I tried build.sh without reading the script more closely.

**Comment by ReubenBond** [comment]
I also tried it without reading it, and that was quite recently. I will go ahead and delete it

**Comment by kestess** [comment]
If you go down that path, you'll need to delete run-build.sh too - build.sh is the only one referring to tit - https://github.com/dotnet/orleans/commits/master/run-build.sh. You should probably also check the other files added in the commit I mentioned above.
