### ISSUE TITLE
UseLocalhostClustering for SiloHostBuilder doesn't complement ClientBuilder

### ISSUE THREAD

**Issue by kestess** [dotnet/orleans#6197]
I created a host that uses UseLocalhostClustering. Essentially I'm trying to reimplement Radim Motycka's Udemy class StockStreaming example with current Orleans (d1a91965daa20045f96dad3f0c84371a7498af68), VS 2019 Mac, and latest dotnet.

The server starts:
```
        private static async Task<ISiloHost> StartSilo()
        {
            var silo = new SiloHostBuilder()
                .UseLocalhostClustering()
                .Configure<ClusterOptions>(options =>
                {
                    options.ClusterId = "dev";
                    options.ServiceId = "StockTickerApp";
                })
                // Endpoints
                .ConfigureEndpoints(siloPort: 11111, gatewayPort: 30000)
                .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(StockStreamingGrain).Assembly).WithReferences())
                // Now create the silo!
                .Build();

            await silo.StartAsync();

            return silo;
        }
```
The problem is that it starts on my internet address of 10.0.0.47:
```
ivy:orleans john$ netstat -an | grep 30000
tcp4       0      0  10.0.0.47.30000        *.*                    LISTEN 
```
This is a problem when I run my client since it actually looks for localhost on the expected localhost:
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Unable to connect to endpoint S127.0.0.1:30000:0. See InnerException)
 ---> Orleans.Runtime.Messaging.ConnectionFailedException: Unable to connect to endpoint S127.0.0.1:30000:0. See InnerException
 ---> Orleans.Networking.Shared.SocketConnectionException: Unable to connect to 127.0.0.1:30000. Error: ConnectionRefused
   at Orleans.Networking.Shared.SocketConnectionFactory.ConnectAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Orleans.Runtime.Messaging.ConnectionFactory.ConnectAsync(SiloAddress address, CancellationToken cancellationToken)
   at Orleans.Internal.OrleansTaskExtentions.MakeCancellable[T](Task`1 task, CancellationToken cancellationToken)
   at Orleans.Runtime.Messaging.ConnectionManager.ConnectAsync(SiloAddress address)
```

/etc/hosts tells me that localhost is 127.0.0.1, but something else apparently gave my nic address to the silohost:

```
ivy:SiloHost john$ ifconfig -a
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 98:01:a7:8f:6f:9f 
	inet6 fe80::149d:bcf1:802e:2f19%en0 prefixlen 64 secured scopeid 0x4 
	inet 10.0.0.47 netmask 0xffffff00 broadcast 10.0.0.255
	inet6 2601:600:837f:daa0:4c:1803:1b11:1b25 prefixlen 64 autoconf secured 
	inet6 2601:600:837f:daa0:35b6:5c1f:73da:4dff prefixlen 64 autoconf temporary 
	inet6 2601:600:837f:daa0::8070 prefixlen 64 dynamic 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
```
Two questions:
1) Shouldn't SiloHostBuilder.UseLocalhostClustering() use the lo0 device on unixy OS's so it uses 127.0.0.1? If so please fix?
2) I'm assuming I can use UseStaticClustering on the client side to get around this problem for the example local client. Is that the expected workaround?

**Comment by kestess** [comment]
I couldn't get UseDevelopmentClustering() to work on the host side - it still starts on 10.0.0.47 regardless of the IPEndPoint I give it, so I'm using the combination of SiloHostBuilder.UseLocalhostClustering() and:

IPEndPoint result = null;
var success = IPEndPoint.TryParse("10.0.0.47:30000", out result);
var ipEndPoints = new IPEndPoint[] { result };

with ClientBuilder.UseStaticClustering(ipEndPoints) just to connect. I'm sure there is a better way, but I wondered if both the UseLocalhostClustering() functions were supposed to complement each other, or, if failing that, there should be a pair of UseDevelopmentClustering() functions that work together?

**Comment by ReubenBond** [comment]
> Shouldn't SiloHostBuilder.UseLocalhostClustering() use the lo0 device on unixy OS's so it uses 127.0.0.1? If so please fix?

That sounds reasonable to me. Are you able to submit a PR?

You can explicitly specify the addresses to bind to if you like, by configuring `EndpointOptions` on the silo:

``` C#
siloBuilder.Configure<EndpointOptions>(options =>
{
    options.SiloListeningEndpoint = new IPEndPoint(IPAddress.Loopback, siloPort);
    options.GatewayListeningEndpoint = new IPEndPoint(IPAddress.Loopback, gatewayPort);
    options.AdvertisedIPAddress = IPAddress.Loopback;
    options.SiloPort = siloPort;
    options.GatewayPort = gatewayPort;
});
```

> I'm assuming I can use UseStaticClustering on the client side to get around this problem for the example local client. Is that the expected workaround?

Yes, that will work.

**Comment by kestess** [comment]
I switch for MSBuild to just Build and then couldn't replicate the error even when switching back. I'm not sure if I cached something or not. This may or may not be an actual problem.

**Comment by ReubenBond** [comment]
It sounds as though this issue is resolved, so I'll close it. We can open a new one if this is still an issue
