### ISSUE TITLE
Start background process from grain

### ISSUE THREAD

**Issue by rsulab** [dotnet/orleans#6198]
Is it possible start background process from grain code using Start.Process?

I tried it but after Start.Process other grain calls dont work.

**Comment by ReubenBond** [comment]
@rsulab could you provide more details on what you're trying to accomplish and what you mean by the following?:

> I tried it but after Start.Process other grain calls dont work.

**Comment by MV10** [comment]
I think he meant `Process.Start` -- launching an external application.

**Comment by sergeybykov** [comment]
That should be totally fine.

**Comment by ReubenBond** [comment]
I understand that part, and starting a process ought to be fine. What I don't understand is the second part of your statement, the "other grain calls dont work" part. Are you able to provide some code for what you're doing? Perhaps your code is blocking until the started process terminates?

**Comment by rsulab** [comment]
> I understand that part, and starting a process ought to be fine. What I don't understand is the second part of your statement, the "other grain calls dont work" part. Are you able to provide some code for what you're doing? Perhaps your code is blocking until the started process terminates?

Sure sample code:

` public interface IMyGrain : IGrainWithGuidKey
    {
        Task Start();
        Task Send(string payload);
    }

implementation:
 public Task Start()
        {             
            m_Process = new Process
            {
                StartInfo =
                {
                    FileName = "MyConsoleApp.exe",
                    CreateNoWindow = true,
                    UseShellExecute = false,
                    Arguments = string.Join(" ", handles.input, handles.output),
                }
            };
            m_Process.Start();
            return Task.CompletedTask;
        }

        public async Task Send(string payload)
        {
            Console.WriteLine(payload);
            return Task.CompletedTask;
        }
`

1. calling Strart()
2. calling Send()

Without Start method - all works

**Comment by ReubenBond** [comment]
Glad you got it sorted. Do you think we can close this?

The grains task scheduler ought to work for reading the stream, too, though. I wonder if it was being blocked.

**Comment by rsulab** [comment]
> Glad you got it sorted. Do you think we can close this?


Yes. Can close. Thanks.
