### ISSUE TITLE
VSTools move to separeted git repository

### ISSUE THREAD

**Issue by pherbel** [dotnet/orleans#620]
I can see some benefits if the VSTools source code will be in a git new repository.
What do you think?

**Comment by pherbel** [comment]
Maybe we can do it with the samples too.

**Comment by grahamehorner** [comment]
personally I think that the orleans github repository should be broken up into small pieces (like the asp.net) this would allow a greater cadence for parts of the orleans framework; and a restructuring of parts like removing dependencies of non-supported coreclr libraries etc.  so in short yes I agree the vstools should be under the orleans project but in a different solution/repository and while it does have dependencies on some orleans assemblies these should be nugget not project references.

**Comment by attilah** [comment]
I think that since we're embedding nupkg files into the VSIX it is not a good idea anymore.

**Comment by sergeybykov** [comment]
I agree.
