### ISSUE TITLE
Streaming document may contain misleading information

### ISSUE THREAD

**Issue by brightness007** [dotnet/orleans#6202]
The comment in sample code may contain misleading information in Orleans document <https://dotnet.github.io/orleans/Documentation/streaming/streams_quick_start.html>, section "Subscribing and receiving streaming data".

> ```
> //Set our OnNext method to the lambda which simply prints the data, this doesn't make new subscriptions
> await stream.SubscribeAsync<int>(async (data, token) => Console.WriteLine(data));
> ```

To my understanding, `this doesn't make new subscriptions` is incorrect, the above code will make a new subscription and setup `OnNext` method to process incoming data.

```
public static Task<StreamSubscriptionHandle<T>> SubscribeAsync<T>(this IAsyncObservable<T> obs,
                                                                  Func<T, StreamSequenceToken, Task> onNextAsync)
{
    return obs.SubscribeAsync(onNextAsync, DefaultOnError, DefaultOnCompleted);
}

public static Task<StreamSubscriptionHandle<T>> SubscribeAsync<T>(this IAsyncObservable<T> obs,
                                                                  Func<T, StreamSequenceToken, Task> onNextAsync,
                                                                  Func<Exception, Task> onErrorAsync,
                                                                  Func<Task> onCompletedAsync)
{
    var genericObserver = new GenericAsyncObserver<T>(onNextAsync, onErrorAsync, onCompletedAsync);
    return obs.SubscribeAsync(genericObserver);
}
```

**Comment by sergeybykov** [comment]
The comment is correct because this sample uses [*implicit* stream subscriptions](http://dotnet.github.io/orleans/Documentation/streaming/streams_programming_APIs.html?q=implicit#explicit-and-implicit-subscriptionsa-nameexplicit-and-implicit-subscriptionsa). Maybe it would help to expand the comment to "this doesn't make new subscriptions because we are using implicit subscriptions"?

**Comment by brightness007** [comment]
Sure, it would be very helpful :-)

**Comment by sergeybykov** [comment]
Done.
