### ISSUE TITLE
Access DI service in Unit Test

### ISSUE THREAD

**Issue by pawanrao** [dotnet/orleans#6206]
I'm using the ClusterFixture way of testing Orleans grains and trying to verify if a call to one of the methods inside a dependency injected service actually happened inside of a grain call. 

I'm correctly configuring the service using `ConfigureServices` of the test ClusterFixture. 
But I still cannot access the injected service inside my unit test. 

Couple of ways I've tried are: 
`this._cluster.Cluster.ServiceProvider.GetServiceByName<MyServiceName>(nameof(MyServiceName))`
`this._cluster.Cluster.Service.GetService<IMyServiceName>()` but none of them have worked. 

Is there any good way to do this? 
I'm basically looking to ensure that a call to `IMyServiceName.Test()` happened.

**Comment by ReubenBond** [comment]
You're injecting a service into a grain and you want to check that the grain is calling it?
You will need to get a handle on the `IServiceProvider` on the silo. You can either do that with a test grain which accesses that service, or you can get access to the silo from the cluster directly.

Something like this:

``` C#
((InProcessSiloHandle)_cluster.Primary).SiloHost.Services.GetService<IMyService>()
```

**Comment by lfzm** [comment]
@ReubenBond  How can I solve the problem of duplicate ports in batch unit tests?

**Comment by ReubenBond** [comment]
@lfzm I am not sure. Limiting concurrency is one way. I think ultimately we should either move to an in-memory transport for TestCluster or add some kind of coordination between instances. If that's something you're interested in, please open a new issue on it.

I'm closing this one for now, since I think the original issue is resolved.
