### ISSUE TITLE
Surpport SkyWalking APM

### ISSUE THREAD

**Issue by ElderJames** [dotnet/orleans#6213]
I want to let orleans surpport skywalking APM,where can I start expanding?

**Comment by ReubenBond** [comment]
I recommend following how the AppInsights support is implemented: https://github.com/dotnet/orleans/tree/master/src/TelemetryConsumers/Orleans.TelemetryConsumers.AI

Eventually, we intend to start using EventCounter for metrics, rather than the internal counter implementation.

**Comment by Cloud33** [comment]
Is there any action? @ElderJames

**Comment by rafikiassumani-msft** [comment]
We will close this issue as we do have #4992 for tracking the proposal.
