### ISSUE TITLE
Enable non-connection string based authentication for Azure Storage

### ISSUE THREAD

**Issue by ronbrogan** [dotnet/orleans#6223]
My team is moving to use Managed Identities for all of our services. Using Azure Storage clustering with Orleans is forcing us to compromise on that goal due to the requirement of providing a connection string for the library to use to create a CloudTableClient. 

My proposal is to allow the user to provide a pre-configured CloudTableClient for the library to use when connecting to Azure Storage. This would enable the end user to setup authentication in any desired way. 

So, instead of setting up a builder like:

```csharp
var builder = new SiloHostBuilder()
    .UseAzureStorageClustering(options => options.ConnectionString = connectionString)
```

You could have something like:

```csharp
var cred = new StorageCredentials("token");
var acct = new CloudStorageAccount(cred, new Uri("https://{endpoint}.table.core.windows.net/"));
CloudTableClient client = acct.CreateCloudTableClient();

var builder = new SiloHostBuilder()
    .UseAzureStorageClustering(options => options.UseTableClient(client))
```

I'm willing to make a PR for this functionality, but I wanted to open an issue here first to ensure the idea is sound and the appropriate solution.

**Comment by veikkoeeva** [comment]
A note here that making use of this (a good thing) in ADO.NET may require making sure `System.Data.SqlClient` is used and technique like https://azure.microsoft.com/en-gb/blog/securing-azure-sql-databases-with-managed-identities-just-got-easier/ (also https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-connect-msi) is used. It should be checked also if all that is needed to use the correct, new libraries and modify the connectionstring accordingly or if some scenarios require to supply an access token (`SqlConnection.AccessToken` property) to the created connection directly.

**Comment by ronbrogan** [comment]
I hadn't considered stores other than Azure Table. One concern I have about just providing a one-off access token is that the default tokens are only valid for 1 hour. If the consumer of the token has the ability to renew the token, that seems appropriate - although I'm not well versed on how that would work.

**Comment by ReubenBond** [comment]
@ronbrogan we would welcome such a change. I think the `UseTableClient(client)` approach is suitable

**Comment by veikkoeeva** [comment]
@ronbrogan Nah, I was a bad person that wrote a note to myself in a haste while in transit. Should've created an issue an linked (will later, now to sleep).

**Comment by ronbrogan** [comment]
I went to implement some of this functionality today, only to realize that I conflated `Microsoft.Azure.Storage` functionality with `Microsoft.Azure.Cosmos.Table` functionality. As it stands, there's no way to create a CloudTableClient using token authentication to leverage Managed Identities. As such, there's not much motivation to make the proposed changes, and I'm closing the issue.
