### ISSUE TITLE
Cannot find generated GrainReference class for interface 'Orleans.Runtime.IClusterTypeManager'

### ISSUE THREAD

**Issue by 731315163** [dotnet/orleans#6231]
unity client throw execption "Cannot find generated GrainReference class for interface 'Orleans.Runtime.IClusterTypeManager"

**Comment by 731315163** [comment]
![image](https://user-images.githubusercontent.com/15324820/72305251-23241c80-36ae-11ea-90ae-00bb43a6d384.png)
Where is ISystemTarget implemented? Is it to generate code automatically

**Comment by ReubenBond** [comment]
I don't think this will work in Unity yet

**Comment by 731315163** [comment]
![image](https://user-images.githubusercontent.com/15324820/72416143-fad11680-37b0-11ea-86f2-102bae5b382c.png)
Orleans.core has generated some code. I think that if I can directly generate these code files, it may play a role in copying them to unity. I have copied the code generated by igraininterface to unity, which is feasible. But the code generated by orleans.core does not seem to have a single text file.

**Comment by 731315163** [comment]
![image](https://user-images.githubusercontent.com/15324820/72420791-4f2cc400-37ba-11ea-9351-25aaa38006da.png)
I need to get the text file of the code generated by orleans.client. What should I do?
