### ISSUE TITLE
Question : Correct Placement attribute to use to have singelton instance of Grain per node (locally)

### ISSUE THREAD

**Issue by manums** [dotnet/orleans#6235]
#### Requirement 

- Single instance of grain available locally on every node. 
- Single instance of grain for given *key* locally. Let's say if there are 4 tenants then there should be 4 different instances of this grain and each of them addressable using the GUID\string key of te tenant.
- This grain has a Timer to do some work.
- Also, registers itself as a Subscriber (IGrainObserver) for changes from other grain.

**Can you suggest if there is already a placement strategy that I can use as-is for above requirement?**

#### What I have tried so far?

After searching through documentation and code for the correct placement strategy for above grain, I thought StatelessWorker(1) or PreferLocalPlacement would work for my case. Later  I realized PreferLocalPlacement  might not *always* have a local instance of grain on every node.  

#### Issue with StatelessWorker
I can see that StatelessWorker(1) creates one local instance of the grain. When I used made grain as StatelessWroker, it ran into LongRunning task issue. 

````cs

fail: Orleans.Threading.ThreadPoolExecutor[101212]
Work item WorkItem=WorkItemGroup:Name=[Activation: S127.0.0.1:11111:316653458*grn/BDB9242C/0edd30a9@f162738e 

#GrainType=Common.Telemetry.Tracing.Tracer Placement=StatelessWorkerPlacement],WorkGroupStatus=Running Executing for 00:00:24.0630592 WorkItemGroup Details: WorkItemGroup:Name=[Activation: S127.0.0.1:11111:316653458*grn/BDB9242C/0edd30a9@f162738e 

#GrainType=Common.Telemetry.Tracing.Tracer Placement=StatelessWorkerPlacement],WorkGroupStatus=Running. Currently QueuedWorkItems=2; Total EnQueued=12; Total processed=9; Quantum expirations=0;  Executing Task Id=20876 Status=Running for 00:00:24.0641348.TaskRunner=ActivationTaskScheduler-22:Queued=2; Detailed SchedulingContext=<[Activation: S127.0.0.1:11111:316653458*grn/BDB9242C/4fca1ce75f7666f8b45cbded0edd30a903ffffffbdb9242c-0xC296A8A1@f162738e 

_#GrainType=Common.Telemetry.Tracing.Tracer Placement=StatelessWorkerPlacement State=Valid NonReentrancyQueueSize=0 EnqueuedOnDispatcher=0 InFlightCount=0 NumRunning=0 IdlenessTimeSpan=00:00:24.0651795 CollectionAgeLimit=02:00:00]> has been executing for long time._
````

**Comment by ReubenBond** [comment]
I think this question is more about long-running tasks than about placement.

What are you doing inside that grain, blocking a thread, taking an indefinite time to process a message?

**Comment by manums** [comment]
There is an open question on placement too - What would be the *correct* placement for this grain? Should I write a custom placement strategy for the requirement explained in my question?

About this grain: it is a tracer grain. There are two timer jobs. One that periodically publishes traces out to different providers and other that periodically polls for new provider registrations.

After reading example for statelessworker, it does not look like StatelessWorker is right in this case. **Please correct me if I'm wrong.**

**Comment by ReubenBond** [comment]
StatelessWorker may be the right kind for this grain, but I'm not convinced that a grain is the right fit here - you want one copy per silo, which doesn't fit the programming model of a grain well.

Instead, you could consider just using a background task which you launch from either an `IHostedService` (from `Microsoft.Extensions.Hosting.Abstractions`) or an `IStartupTask` (from Orleans). They can subscribe to a grain for updates on a timer.

Regardless, never block threads

**Comment by manums** [comment]
Thanks for you suggestion. I agree tracer grain kind of aligns to the idea of a background worker. There needs to be many such backgroundworkers - one per each tenant that is running inside that silo. Each silo can have more than one trace grain/one per each tenant. Probably I can have a named singleton instance per tenant and use factory around.

I was considering these pros of making it as grain - It will provide ability to address through tenant id as primary key, support for observing other grain & notifying other grains. Also, with StatelessWorker I can scale if required to more than 1 instance per node. 

I don't think threads are getting blocked in current scenario. Each timer task finishes quickly by just pushing down messages to different providers.

Timer tasks are still on the same single thread of grain right?
