### ISSUE TITLE
Build not sufficient after changing from release to debug (or vice versa)

### ISSUE THREAD

**Issue by OracPrime** [dotnet/orleans#6244]
In Release build.
Rebuild, Run,
Make a chain in (say) my interfaces assembly, 
Run.  OK.
Switch to debug.
Run.  Build errors as other assemblies aren't seeing the change in the interfaces assembly
Rebuild.
Run. OK.

**Comment by OracPrime** [comment]
OK, it's not that simple.  I've just had the problem when I haven't switched configurations.  I added an argument to a method on a grain interface, and got this
![image](https://user-images.githubusercontent.com/9028003/72544845-fe7f9e80-387f-11ea-954b-18c500d30df4.png)
So the .g.cs file is seeing the new interface but the old implementation (and indeed the .g.cs has not been regenerated).

**Comment by OracPrime** [comment]
Don't know if it's relevant, but the ISliceReference (which is the grain interface) is derived from a base interface, and the method change was on the base interface
```

  public interface ISliceReferenceBase : Orleans.IGrainWithGuidKey
  {
    ValueTask<string> AsString();
    Task ClearValues(string msg);
  }

  public interface ISliceReference : ISliceReferenceBase
  {
    Task<Immutable<double[]>> GetValues();
    Task SetValues(Immutable<double[]> values) ;
  }
```

**Comment by ReubenBond** [comment]
Is there something different about your project files or maybe your filesystem?

**Comment by OracPrime** [comment]
They're projects created in VS 2019 on the local hard disc of a Win10 machine

**Comment by ReubenBond** [comment]
Is there anything else possibly modifying the build process at all? Eg, PostSharp, ILMerge, something else

**Comment by OracPrime** [comment]
Not that I can think of. I'll see if procmon can tell me what's going on. I have Resharper installed, but it's not set to do anything without my say so.

**Comment by OracPrime** [comment]
I have solution set with both silo and client set as startup projects, and the error occurs when I F5 to run/debug. Pretty sure my project interdependencies are right. I'll get a colleague to do a reality check tomorrow
