### ISSUE TITLE
The Hash in the Build.Targets file is hashing names not contents

### ISSUE THREAD

**Issue by OracPrime** [dotnet/orleans#6247]
When doing an incremental build, the build targets file generates a hash of the CodeGenInputs files and checks whether it has changed, only rebuilding the .orleans.g.cs file if it hash.  Unfortunately, these lines:
```

    <Hash ItemsToHash="@(Orleans_CodeGenInputs)">
      <Output TaskParameter="HashResult" PropertyName="Orleans_UpdatedInputCacheContents" />
    </Hash>
```

generate a hash of the filenames, not the contents.  So changing a content doesn't cause a regeneration of the .orleans.g.cs file and a subsequent likely failed build.

**Comment by ReubenBond** [comment]
We need to set OrleansGenerateCode's to `Inputs="$(Orleans_CodeGenInputCache);@(Orleans_CodeGenInputs)"`

**Comment by ReubenBond** [comment]
This is intentional, by the way. The Hash task is there to catch the entire set of inputs to the code generator in terms of names & properties. What's missing (mistakenly removed) is what I mentioned above. Closing in favor of #6244
