### ISSUE TITLE
Grain interface instance equality

### ISSUE THREAD

**Issue by tg73** [dotnet/orleans#6248]
I'd like to have a `HashSet` of some grain interface, eg, `HashSet<IHelloGrain>`. I suspect that relying upon reference equality of interface instances is bad idea. I also note that `Orleans.Grain` does not override `object.Equals(...)`. The (only?) implementation of `IGrainIdentity`, `Oreans.Runtime.GrainId`, does override `object.Equals(...)`, so would seem to be a good candidate for testing the semantic equivalence of grain interface instances. But I'm also surprised that I can't find any utility implementation of `IEqualityComparer<IGrain>` in Orleans.

More generally, I've searched the documentation and issues here, but I can't find any best practice guidance regarding the equality of grain interface instances. What is the actual intended behaviour of grain interface instances when tested for equality? What patterns should be preferred or avoided?

**Comment by JorgeCandeias** [comment]
A `IHelloGrain` interface does not hide a `HelloGrain` grain instance directly. It hides a generated implementation of [`GrainReference`](https://github.com/dotnet/orleans/blob/c9f528a9e2ba590ac938d711e395d5a58e991816/src/Orleans.Core.Abstractions/Runtime/GrainReference.cs), which is a proxy that is able to send messages to `HelloGrain` grain instances in the cluster. You can find this generated code in a `<project-name>.orleans.g.cs` file in your `obj` folder after building the project.

The `GrainReference` class does implement `IEquatable<GrainReference>` and overrides `GetHashCode()`:

``` csharp
public override bool Equals(object obj)
{
    return Equals(obj as GrainReference);
}

public bool Equals(GrainReference other)
{
    if (other == null)
        return false;

    if (genericArguments != other.genericArguments)
        return false;
    if (!GrainId.Equals(other.GrainId))
    {
        return false;
    }
    if (IsSystemTarget)
    {
        return Equals(SystemTargetSilo, other.SystemTargetSilo);
    }
    if (IsObserverReference)
    {
        return observerId.Equals(other.observerId);
    }
    return true;
}

public override int GetHashCode()
{
    int hash = GrainId.GetHashCode();
    if (IsSystemTarget)
    {
        hash = hash ^ SystemTargetSilo.GetHashCode();
    }
    if (IsObserverReference)
    {
        hash = hash ^ observerId.GetHashCode();
    }
    return hash;
}
```

The implementation makes it okay for use in a `HashSet`, but whether that's a good idea or not depends on what you're looking to accomplish. E.g. if you're looking to hold references for future callbacks, the virtual streaming feature could be a better option, or if you're looking to persist references for future use, saving the grain keys only could be more space-efficient, if that's a concern.

What are you looking to address in particular?

**Comment by tg73** [comment]
@JorgeCandeias Thanks for the info. My use case is the [registry pattern](https://social.technet.microsoft.com/wiki/contents/articles/51018.registry-pattern-using-microsoft-orleans.aspx) - so it's grain code holding a collection (`HashSet`) of refs to other grains. I actually persist a collection of plain guids, but maintain a runtime cache of the corresponding interface instances.

In the code snippet you provided, what does `IsSystemTarget` mean? Does that affect the equality test for regular grains? From poking around, I get the impression that `IsSystemTarget` should only be true for special-purpose grains that are part of Orleans internal workings.

**Comment by ReubenBond** [comment]
If the objects in your set are all grain references (i.e, created by some call to GetGrain) then you can rely on the default Equals/GetHashCode overrides. If you have actual grain objects in there (eg, `this`) then you cannot - but you could always get a reference to the current grain by calling `this.AsReference<TInterface>()`

**Comment by JorgeCandeias** [comment]
> @JorgeCandeias Thanks for the info. My use case is the [registry pattern](https://social.technet.microsoft.com/wiki/contents/articles/51018.registry-pattern-using-microsoft-orleans.aspx) - so it's grain code holding a collection (`HashSet`) of refs to other grains. I actually persist a collection of plain guids, but maintain a runtime cache of the corresponding interface instances.

Yeah, that works fine, so long as - as @ReubenBond stated - you're using grain references and not the actual grain class instances.

> In the code snippet you provided, what does `IsSystemTarget` mean? Does that affect the equality test for regular grains? From poking around, I get the impression that `IsSystemTarget` should only be true for special-purpose grains that are part of Orleans internal workings.

[`SystemTarget`](https://github.com/dotnet/orleans/blob/ab6811376bbd8f504cec14c178b5bda85da0f537/src/Orleans.Runtime/Core/SystemTarget.cs) is a base class for internal actors that share some behaviour with regular grains but is otherwise not meant for direct use by application developers. This does not affect the equality for regular grain references.

If you want to make sure, you can dig through and see where the `IsSystemTarget` property is resolved, in [`UniqueKey`](https://github.com/dotnet/orleans/blob/c9f528a9e2ba590ac938d711e395d5a58e991816/src/Orleans.Core.Abstractions/IDs/UniqueKey.cs), via [`GrainId`](https://github.com/dotnet/orleans/blob/c9f528a9e2ba590ac938d711e395d5a58e991816/src/Orleans.Core.Abstractions/IDs/GrainId.cs):

```csharp
public enum Category : byte
{
    None = 0,
    SystemTarget = 1,
    SystemGrain = 2,
    Grain = 3,
    Client = 4,
    KeyExtGrain = 6,
    GeoClient = 7,
    KeyExtSystemTarget = 8,
}

private static bool IsSystemTarget(Category category)
    => category == Category.SystemTarget || category == Category.KeyExtSystemTarget;
```

Regular grains don't fall into the system target category so that check does not affect them.

**Comment by tg73** [comment]
Many thanks @JorgeCandeias and @ReubenBond, it would appear that my question has been thoroughly answered. Given that nobody has directed me to existing documentation, I assume that there is none covering this topic.

**Comment by ReubenBond** [comment]
I do not believe it's covered by documentation explicitly, so we would be open to a PR for that - perhaps something along the lines of 'grain references are equatable'
