### ISSUE TITLE
Add back removed overload for accepting deployment id

### ISSUE THREAD

**Issue by onionhammer** [dotnet/orleans#627]
We managed our own partition key (deployment id) prior to 1.0.9 so that things not running in a webrole on the same virtual network would be able to access orleans

```
            _silo = new AzureSilo();

            var ok = _silo.Start(config);
                //SiloLocator.GetDeploymentId(),
                //RoleEnvironment.CurrentRoleInstance,
                //config);
```

Since the 1.0.9 update we no longer have a place to put our pre-configured 'deploymentid' key, since you removed the AzureSilo Start overload that accepts a deployment Id and are doing reflection bastardy instead. :-1:

**Comment by skalpin** [comment]
:+1:

**Comment by ReubenBond** [comment]
I use this overload, too - or something like it - since we host on Service Fabric and use the application uri as the deployment id.

-----Original Message-----

**Comment by sergeybykov** [comment]
Can't you pass deployment ID via `config.Globals.DeploymentId`?

**Comment by onionhammer** [comment]
@sergeybykov I will try this and report back!

**Comment by onionhammer** [comment]
Just tested it. It does *not* work to set the config.Globals.DeploymentId was overridden after .Start(), and the value passed is ignored.

**Comment by sergeybykov** [comment]
@onionhammer Looks like we need indeed to add an overload to override Deployment Id. Do you feel like submitting a PR?

As a workaround, you should be able to use the Silo class instead of AzureSilo for now.

**Comment by onionhammer** [comment]
Sure i can submit a PR in a bit.

**Comment by sergeybykov** [comment]
Thanks!

**Comment by ReubenBond** [comment]
I checked how I do this (sorry, it was 1am before), I do not use the constructor, I ripped the code out of that constructor and created my own, which contains the following in which I set the DeploymentId:
```c#
// Configure this Orleans silo instance
if (config == null)
{
    this.host = new SiloHost(this.siloName);
    this.host.LoadOrleansConfig();
}
else
{
    this.host = new SiloHost(this.siloName, config);
}

// Configure the silo for the current environment.
var generation = SiloAddress.AllocateNewGeneration();
this.host.SetSiloType(Silo.SiloType.Secondary);
this.host.SetSiloLivenessType(GlobalConfiguration.LivenessProviderType.AzureTable);
this.host.SetReminderServiceType(GlobalConfiguration.ReminderServiceProviderType.AzureTable);
this.host.SetDeploymentId(this.deploymentId, this.connectionString);
this.host.SetSiloEndpoint(this.SiloEndpoint, generation);
this.host.SetProxyEndpoint(this.ProxyEndpoint);

this.host.InitializeOrleansSilo();
var ok = this.host.StartOrleansSilo();
```

**Comment by onionhammer** [comment]
@ReubenBond hmm, and this is in a worker role? What are you setting the siloName to?

**Comment by ReubenBond** [comment]
I think I'm using the windows fabric instance id, but it's no big deal

**Comment by onionhammer** [comment]
I ended up just building a nupkg of the azure utils and storing it in source control for now. Hopefully this goes into the next release! :)

**Comment by gabikliot** [comment]
It definitely will.

**Comment by gabikliot** [comment]
Closing via https://github.com/dotnet/orleans/pull/629.
