### ISSUE TITLE
Remove ProcessExitHandlingOptions

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#6270]
No longer necessary - this is the responsibility of hosting

**Comment by erdtsieck** [comment]
ProcessExitHandlingOptions is still mentioned in the documentation: https://dotnet.github.io/orleans/docs/host/configuration_guide/shutting_down_orleans.html

**Comment by ReubenBond** [comment]
Thank you for pointing that out, @erdtsieck. I've [added a commit](https://github.com/dotnet/orleans-docs/commit/d73c35b1fce0479dbf99d3b58fa8b7758c4f2f9a) to remove it from the [dotnet/orleans-docs](https://github.com/dotnet/orleans-docs) repo. If you spot other issues and are able and willing, PRs would be greatly appreciated.
