### ISSUE TITLE
Custom stream provider memory usage growing faster than working set

### ISSUE THREAD

**Issue by ryanjshaw** [dotnet/orleans#6279]
I'm using Orleans 3.0.2 on .NET Core 3.1, server GC enabled, along with @jonathansant's `Orleans.Streams.Kafka` library to consume mesages from a set of existing Kafka topics.  My topics have messages that range from 1KB to 500KB and I have millions of these messages per day.  There's anywhere from 1-100 messages per stream ID, i.e. millions of subscribers, and I'm using implicit subscriptions to manage this.

I noticed my silo's managed memory consumption keeps growing despite GC.  On a server with 128GB RAM and 32 cores I can hit 50GB+ after an hour.  I threw a memory profiler at it on my 8 core laptop and I see this breakdown after 15min:

Gen 1:  150KB
Gen 2:  750MB
LOH:  20MB
Unused .NET:  1.2GB
Unmanaged:  1.1GB, of which 800MB is `librdkafka`, but this is expected behaviour (it will cache max 1GB per topic by default)

In Gen 2 the biggest the biggest user of memory is `PersistentStreamPullingAgent` (1) 
-> ... -> `StreamConsumerCollection` (50k instances) 
-> {`Guid`: `StreamConsumerData`} (50k instances) 
-> `SimpleQueueCacheCursor` (50k instances) 
-> `<batch container>` (50k instances)
-> ... -> `<stream message type>` (50k instances)
-> 62MB of `byte[]` representing the Kafka message value itself

Then 46MB of 24 byte objects (boxing?), 35MB of strings, and 28MB of Orleans ActivationData, etc.

So this brings me to 2 big questions:

1.  Does this pattern of memory usage look right?  It looks like a lot of memory is simply being held onto by the server GC because I guess we have free RAM and we needed at least as much during the last GC run so .NET is keeping it allocated?  

What doesn't make sense to me is that the amount of data I'm processing in that time frame is maybe 1/10th of this.  Is this a code smell on my part, or is it just server GC maximising RAM use, or maybe a combination of the two?  I haven't seen any OOM issues after running until free memory is exhausted, but my (unmeasured) impression is that throughput drops.

My working set isn't very large at any given point in time, despite the large number of subscribers, and I would have expected to see inactive grains deactivated - is this assumption wrong?  I tried `DeactivateOnIdle` but I didn't really observe different memory usage characteristics.

2.  I have modified `Orleans.Streams.Kafka` to have a per-topic cache.  This is set to about 9k max items across all topics in the test above.  Yet there's 50k messages being referenced by `SimpleQueueCacheCursor`.

Is this because I have a backlog of tasks (I do get warnings that my tasks are taking too long e.g. 0.3-1sec to complete), or is it because every active subscribing activation will hold onto the last message it consumed due to the implementation of `SimpleQueueCacheCursor`?  And does the latter in turn imply `SimpleQueueAdapterCache` is not a good choice for a Kafka stream provider with message data this large - and are there any recommendations for an alternative?

I started looking at the other stream provider implementations but it's not clear to me what the right answer is.  Any pointers in the right direction would be appreciated.

**Comment by sergeybykov** [comment]
>1. Does this pattern of memory usage look right? It looks like a lot of memory is simply being held onto by the server GC because I guess we have free RAM and we needed at least as much during the last GC run so .NET is keeping it allocated?

That would be my guess, judging by the memory breakdown you mentioned. Have you tried to run that app on, for example, a VM with the same CPU but only 4GB of memory available or constrain the amount of memory available to it in some other way? Another crude experiment I can think of is to make it call `GC.Collect()` once a minute. I suspect it would grow anywhere near 50GB in either case.

>My working set isn't very large at any given point in time, despite the large number of subscribers, and I would have expected to see inactive grains deactivated - is this assumption wrong? I tried DeactivateOnIdle but I didn't really observe different memory usage characteristics.

The default idle time for deactivation is 2 hours. You can configure it much lower if there's no need to keep idle grain in memory for that long.

>I have modified Orleans.Streams.Kafka to have a per-topic cache. This is set to about 9k max items across all topics in the test above. Yet there's 50k messages being referenced by SimpleQueueCacheCursor.

Pulling agents keep caches of stream events for recovery and rewinding scenarios. The cache size is configurable.

>Is this because I have a backlog of tasks (I do get warnings that my tasks are taking too long e.g. 0.3-1sec to complete)

Can you share the exact warning text? This usually points to thread blocking synchronous operations. Sometime we also see these warnings when somebody perf tests on an overloaded laptop.

**Comment by ryanjshaw** [comment]
> That would be my guess, judging by the memory breakdown you mentioned. Have you tried to run that app on, for example, a VM with the same CPU but only 4GB of memory available or constrain the amount of memory available to it in some other way? Another crude experiment I can think of is to make it call GC.Collect() once a minute. I suspect it would grow anywhere near 50GB in either case.

It turns out there were a number of confounding issues:

- I was publishing my output back to Kafka through a singleton grain (!);  I didn't need a grain at all! (In fact my core process has gone down from 10 grains to 2 and my code is simpler and more compact as I've come to understand Orleans features better.)
- Kafka producer lingers for at most 0.5ms before publishing, which wasn't the most efficient approach
- My grain state was accidentally including large objects
- I have a grain that does implicit subscriptions (GUID key) and also receives messages from other grains (String key);  this was flawed and resulted in messages pilling up on the wrong grains and has forced me to figure out how to do automated testing on the grains themselves not just the business logic.  I've moved exclusively to GUID keys to avoid surprises.
- I had all my topics on the same stream provider (different namespaces), but the processing time for topics is highly variable.  Using separate stream provider instances with different cache sizes smoothed out latency quite a bit and seems to make things more predictable (maybe something to do with how backpressure or scheduling works?)
- I'm doing a lot of state updates and this is sometimes resulting in 500mbps of network traffic to SQL Server, which was becoming a bottleneck... I'm trying a couple of strategies to improve
- more things I can't remember, I should write some blog posts...

> The default idle time for deactivation is 2 hours. You can configure it much lower if there's no need to keep idle grain in memory for that long.
> Pulling agents keep caches of stream events for recovery and rewinding scenarios. The cache size is configurable.

Thanks, this is really valuable info, I'll look into fine tuning these parameters as I know that when a grain is activated during the day it's very unlikely for it to be activated again except for end of day due to the nature of the business.

>> Is this because I have a backlog of tasks (I do get warnings that my tasks are taking too long e.g. 0.3-1sec to complete) 
> Can you share the exact warning text? This usually points to thread blocking synchronous operations. Sometime we also see these warnings when somebody perf tests on an overloaded laptop.

I definitely see far fewer of these warnings on server hardware, but I still see them -- this is from a grain that is just processing a 1KB JSON message:
`
warn: Orleans.Runtime.Scheduler.WorkItemGroup[101215]
      Task [Id=9152835, Status=RanToCompletion] in WorkGroup [Activation: S127.0.0.1:11111:318508979*grn/1EF713FB/015295be@721568a3 #GrainType=XXXGrain Placement=RandomPlacement State=Valid] took elapsed time 0:00:00,6009557 for execution, which is longer than 00:00:00.2000000. Running on thread System.Threading.Thread
`

What's clear to me from now is that I need to build in a lot of instrumentation because the framework is very powerful but by itself quite opaque.

**Comment by sergeybykov** [comment]
Oh, clearly a lot is going on there! Much more than I could infer from your original post.

The warning is still alarming. It says that a task _synchronously_ executed for 600 ms without hitting an `await`. Is it possible that the code acquires a lock or wait synchronously on something else here? Sometimes we see that happening 2 or 3 dependency libraries down.

**Comment by ryanjshaw** [comment]
> Oh, clearly a lot is going on there! Much more than I could infer from your original post.
> The warning is still alarming. It says that a task synchronously executed for 600 ms without hitting an await. Is it possible that the code acquires a lock or wait synchronously on something else here? Sometimes we see that happening 2 or 3 dependency libraries down.

I see, I didn't realise that clock reflected the synchronous execution time - that's definitely not right, I use awaits extensively, don't return Tasks or do a .Result anyway.  I will add some instrumentation (looks like I'm going to need it!) and feed back.

Also:  I disabled publishing to Kafka and writing state back out to SQL Server, but left all my logic intact (which does hit the database to cache input messages and persist output messages).  Ididn't fine tune any Orleans deactivation parameters.  I let a single silo process about 17m messages across 2 grain types, representing around 20GB of data.

After processing the messages the service had 50GB of RAM allocated.  There were 1.5M `PubSubRendezvousGrain`s active (about 2GB in SQL server orleans Storage table, albeit with GZIP compression on the JSON payload column) and another 2.25M of my own grains active.  It then idled at 0.30% CPU (128 cores) with a trickle of messages (2-3/s) for 8 hours.  At that point:  3 grains active, working set 11GB, committed/private bytes 56GB.

**Comment by ryanjshaw** [comment]
I have performed further testing and added instrumentation to my code and confirmed that my code is completing with 10s of ms.  Some outcomes:

0. The `Orleans.Streams.Kafka` library I based my stream provider off was using a polling timeout with Kafka. This does not appear to be necessary because `librdkafka` uses a background thread to aggressive cache data from a topic, and `consumer.Consume(timeout)` just moves it from the internal cache into the application space.  Using a timeout on top of this was confusing the pulling agent, presumably preventing it from deriving the correct `maxCount` figure.  Replacing the timeout with zero results in ~600 `Get

0.  My code is fast enough (10s of ms).  But between the time
