### ISSUE TITLE
Serious NullReferenceException in Orleans 1.0.9

### ISSUE THREAD

**Issue by joeecz** [dotnet/orleans#628]
In  orleans/src/Orleans/Messaging/SqlMembershipTable.cs
In  public Task InitializeGatewayListProvider(ClientConfiguration config, TraceLogger traceLogger) method
On line 72 there is a call to  logger.IsVerbose3
But logger is not initialized yet since there is a missing assignment from passed traceLogger parameter:
logger = traceLogger;

This causes NullReferenceException and prevents GrainClient initialization.

**Comment by gabikliot** [comment]
Fixed via #631.
