### ISSUE TITLE
SimpleQueueCache mixes delivery receipts

### ISSUE THREAD

**Issue by Gaben007** [dotnet/orleans#6281]
I need for a custom implementation of IQueueAdapterFactory. In my solution I would like to use SimpleQueueAdapterCache for IQueueAdapterCache GetQueueAdapterCache() method's response. But if I use this implementation I experiences the calls of IQueueAdapterReceiver.MessagesDeliveredAsync(IList<IBatchContainer> messages) are confused.

Expected behavior:
MessagesDeliveredAsync should be called after the subscribed grain processed the IBatchContainer successfully. If the grain throws exception the method shouldn't be called until the retry period (which is 1 min as default) timing out. After the time out the method call shouldn't contain the failed messages. It's important because we can send ACK to the queue after a success message processing.

Current behavior:

1. If there is only one message in the cache it won’t wait to finish processing of it.
2. If there are more than one message in the cache it won’t wait to finish processing of last batch.
3. If processing of any message from the cache is failed the next one batch will be marked as failure (except if the message was the last one in that case nothing will be marked). The marked messages won’t be passed to the MessagesDeliveredAsync method as parameter. So the failed messages will be passed but some of the success won’t be.

Implementation issues:

1. When tries to get the next batch from the cursor here: https://github.com/dotnet/orleans/blob/9699b6df713e461765a825c2d40af0079f6f18de/src/OrleansProviders/Streams/Common/SimpleCache/SimpleQueueCache.cs#L244
it will remove the cursor from the cached message if it was the last one. This will cause the purge thinks there is no consumer on the message here: https://github.com/dotnet/orleans/blob/9699b6df713e461765a825c2d40af0079f6f18de/src/OrleansProviders/Streams/Common/SimpleCache/SimpleQueueCache.cs#L92
2. Reason is same as above.
3. Here the cache should filter the failed messages:
https://github.com/dotnet/orleans/blob/9699b6df713e461765a825c2d40af0079f6f18de/src/OrleansProviders/Streams/Common/SimpleCache/SimpleQueueCache.cs#L121 
But when sets its state here:
https://github.com/dotnet/orleans/blob/9699b6df713e461765a825c2d40af0079f6f18de/src/OrleansProviders/Streams/Common/SimpleCache/SimpleQueueCacheCursor.cs#L118
the Element.Value will point to the next one and not to the “current” variable however the method is called for the “current”.

I created a short code sample for repro:
https://github.com/Gaben007/OrleansCustomStreamProviderTest

**Comment by jsteinich** [comment]
This sounds very similar to https://github.com/dotnet/orleans/issues/903
