### ISSUE TITLE
Logging category names are inconsistent

### ISSUE THREAD

**Issue by KevinCathcart** [dotnet/orleans#6289]
Under Microsoft.Extensions.Logging, it is normal to use a type name complete with namespace, for the logging category.

Most of Orleans does indeed do this, sometimes with fictitious subtype names where it makes sense. That is all good. But there are a surprising number of locations where this is not followed, or has other anomalies.

This includes:
* `RuntimeCodeGen` (No namespace),
* `MembershipOracle` (No Namespace),
* `LeaseBasedQueueBalancer-{name}` (No namespace, use of `-` as separator)
* `AsyncTimer-{name}` (No namespace, use of `-` as separator)
* `SiloHealthMonitor/<SiloAddress>` (no namespace, use of `/` as separator)
* `Orleans.Runtime.ReminderService.GrainBasedReminderTable_<Data.Address>` (use of `_` as seperator)
* `Orleans.Streams.PersistentStreamPullingManager-<streamProviderName>` (use of `-` as separator)
* `Microsoft.Orleans.Networking` (weirdly begins Microsoft.Orleans),
* `Microsoft.Orleans.Messaging.<Subcategories>` (Weirdly begins Microsoft.Orleans).
* `Orleans.RuntimeSiloLogStatistics`/`Orleans.RuntimeClientLogStatistics` (It seems really odd that there is no '.' after Runtime).
* `Orleans.Runtime.Scheduler <SchedulingContext.Name>.WorkItemGroup`, (use of space of seperator. [1])
* Last, but certainly not least, `AsynchAgent` and `TaskSchedulerAgent`, both strip leading "Orleans." off of the type name which ends up getting used by the logger, resulting in categories that begin with `Runtime.`

------

The ones that lack namespaces (or lack the leading `Orleans.`) are obnoxious, as it makes it more difficult to configure the logging level for Orleans internals Separately from the logging level for other parts of the application. I was expected to just be able to configure for `Orleans`, but instead would need `Orleans`, `Runtime`, `Microsoft.Orleans`, and all the class names missing a namespace.

I don't have a problem with separating dynamic data with something other than a simple dot, but currently there is a mixture of `_`, `/`, `-`, space, and sometimes even `.` for that. (Dot is being used to seperate dynamic data more often than any of the others are.)

That said, dynamic values should in logging category names should be used with caution, since using them with an unbounded set of values can effectively be a slow memory leak. See #6096 for details. So dynamic values that have a small fixed set of values, like stream providers, is not a big deal, but including things like grain identity information can be somewhat suspect. Especially concerning is `TransactionalState`, and `TransactionComitter`. 

-----

So what I would like to see happen:
1. Add the namespace to the 5 or so cases that are missing it.
2. Change `AsynchAgent`, and `TaskSchedulerAgent` to use the full namespace as a basis for the logging category.
3. Add the missing dot in `SiloLogStatistics`, and `ClientLogStatistics`, unless that was deliberate.
4. Evaluate usages of dynamic values in category names, and remove them in cases where they are likely to effectively be memory leaks.
5. Consider standardizing the separators used for dynamically determined data in logging category names. (This is not particularly important.)
6. Consider changing the few `Microsoft.Orleans.` categories to just `Orleans.`. (This is definitely not important, and leaving them as-is may make sense, since some people may have these configured specially.)

Footnotes:
[1] Also this actually uses the namespace and type names of the subclass, which is rather odd when the class in question is internal with no subclasses, especially since for non system priority contexts, the hypothetical subclass's name is not used.

**Comment by ReubenBond** [comment]
Hi @KevinCathcart, thanks for the analysis & write-up!

Would you be open to creating a PR to fix those discrepancies?

For the dynamic cases, perhaps we need another convention, such as including the scope in the log message or scope rather than category.

**Comment by KevinCathcart** [comment]
Yeah, I'd be happy to create a PR. It would help if some of the details were more nailed down.

And I think _some_ of the dynamic ones can be left as is, for example, many providers append their name, which is unlikely to be very problematic. 

In some cases like SiloHealthMonitor, including the silo address is redundant anyway, as every message written with that logger also includes it, so any structured logging system can already filter on it.

But there are a fair dynamic data cases that don't fir either category, so some decision will need to be made.

**Comment by ReubenBond** [comment]
Much appreciated, I added responses to the specific points.

> 1. Add the namespace to the 5 or so cases that are missing it.

✔

> 2. Change `AsynchAgent`, and `TaskSchedulerAgent` to use the full namespace as a basis for the logging category.

✔ Note that there is an open PR to remove most async agents and convert some (one?) to task scheduler agents.

> 3. Add the missing dot in `SiloLogStatistics`, and `ClientLogStatistics`, unless that was deliberate.

✔

> 4. Evaluate usages of dynamic values in category names, and remove them in cases where they are likely to effectively be memory leaks.

✔ Let's try to remove the dynamic category names and try to ensure that the messages themselves have sufficient context cc @jason-bragg 

> 5. Consider standardizing the separators used for dynamically determined data in logging category names. (This is not particularly important.)

✔ Let's remove them. If we do keep them then let's use `.` as the separator.

> 6. Consider changing the few `Microsoft.Orleans.` categories to just `Orleans.`. (This is definitely not important, and leaving them as-is may make sense, since some people may have these configured specially.)

✔ Good idea

**Comment by KevinCathcart** [comment]
So the current status of the WIP PR is:
1. Done
2. Partially done. Now has full namespace, but still has dynamic data. I'm not sure how much the PR you mentioned would impact this, but since the relevant changes to both agent base classes are literally identical, I'm not very concerned.
3. Done

Now for 4-5. That seems reasonable. Adding the data to a message is obviously simple, but also obviously not always the correct approach. Some cases almost certainly just want this as extra properties in the structured logging message, like scopes provide. 

The question is the correct approach when using scopes. Obviously the simplest possible thing is to just wrap each logger call in a tiny scope, but that is both cumbersome, and likely not making the best use of the feature. 

Certainly using logging scopes more as intended is a better option for some cases. I know for Serilog, logging scopes function across different logger instances, scoped via `AsyncLocal`. So some care would need to be taken in picking where the scopes are used to avoid accidentally applying a scope to places where it does not belong, and also to avoid having log messages accidentally outside of the scope, and thus losing valuable information. I'm not familiar enough with most parts of Orleans' internal architecture to determine the appropriate spots to set logger scopes for most of these. 

I've flagged all the dynamic data in logging categories in my WIP PR. So if anybody wants to comment on specific cases, please be my guest. 

6. This is easy to change, but just not part of my WIP PR yet.
