### ISSUE TITLE
GrainFactory non-static field

### ISSUE THREAD

**Issue by ukluk** [dotnet/orleans#630]
Trying to call the factory from a Rest API.

The following works but shows deprecated in 1.0.9
`var fieldGateway = FieldGatewayFactory.GetGrain(long.Parse(fieldGatewayId));`

The following suggested line doesn't work:
`var fieldGateway = GrainFactory.GetGrain<IFieldGateway>(fieldGatewayId);`

The error doesn't make sense:
An object reference is required for the non-static field, method, or property `Orleans.GrainFactory.GetGrain<TGrainInterface>`

**Comment by gabikliot** [comment]
You should use `GrainClient.GrainFactory.GetGrain<IFoo>(grainKey)`.

`GrainFactory` is not a static class anymore, so that the default implementation can be substituted for testing and other reasons:
http://dotnet.github.io/orleans/What's-new-in-Orleans:

**Comment by ukluk** [comment]
Thx Gabi, I found that the hard way :). my comment/suggestion was about the error. It will help developers if the deprecated message will differentiate between client and grain invoke.

**Comment by weitaolee** [comment]
in IBootstrapProvider
when use GrainClient.GrainFactory.GetGrain<IFoo>(grainKey) ,must be initialize a grain client first.
but silo host not necessary initialize.
how to do this?

**Comment by nehmebilal** [comment]
@ukluk I would recommend that you use `GrainClient.GrainFactory` (or `providerRuntime.GrainFactory`) only once (after initializing the `GrainClient`) to get a reference to the `IGrainFactory` and then use that everywhere else.

Add a `IGrainFactory` parameter to the constructor of each class that needs the `GrainFactory` and pass it through. If you use `GrainClient.GrainFactory` directly in your code, you won't be able to swap the `IGrainFactory` with a test double during unit-testing.

**Comment by gabikliot** [comment]
Hopefully alleviated some of the pain in https://github.com/dotnet/orleans/pull/663.
