### ISSUE TITLE
Consul KV for silos are not getting cleaned up on new run

### ISSUE THREAD

**Issue by adison88** [dotnet/orleans#6304]
Hello

I'm facing a problem similar to https://github.com/dotnet/orleans/issues/6090

On first run, I'm able to spin up silo fine and see consul KV generated for per silo on Consul.

however when I spin up silo container next time on new port, client is trying to reach out the silo from previous run on previous port.

I'm seeing this error on silo container.

`Exception when trying to get GrainInterfaceMap for silos S10.84.36.86:20038:319257509`

I also have settings set in my code.

`
                            options.DefunctSiloCleanupPeriod = TimeSpan.FromMinutes(2);
                            options.DefunctSiloExpiration = TimeSpan.FromMinutes(2);
`

which I believe would clean up old KV but it's not happening it seems.

**Comment by ReubenBond** [comment]
In these kinds of development scenarios - where you are killing entire clusters between each successive run, you should randomize your ServiceId/ClusterId

**Comment by adison88** [comment]
@ReubenBond thanks, will try that let you know if issue persists.

**Comment by adison88** [comment]
@ReubenBond that means every new run will have its own folder under root KV path? Will the previous KV be cleaned up automatically on next run?

**Comment by ReubenBond** [comment]
It will not get cleaned up. Is this a development scenario or a production scenario?

During development, why not use an ephemeral clustering provider like the in-built provider?

You can use consul instead, but because it is intended for production uses, it will complain when you try to connect to a cluster which has been abruptly destroyed (not gracefully shut down). After some time (5 or 10 minutes - it's configurable), it will no longer try to connect to silos which have not renewed their membership and will then proceed to mark those as dead.

**Comment by adison88** [comment]
this is a CI/CD scenario and would like have similar set up there to avoid surprises in prod. I'm testing it out to see if randomizing serviceid and cluster id will work? I see that folder with clusterId gets created in consul however where's serviceId being used?

**Comment by adison88** [comment]
also, randomizing isnt working because client and silo are in different appdomain so not able to use same unique id across

**Comment by adison88** [comment]
>  After some time (5 or 10 minutes - it's configurable)

is that `TableRefreshTimeout` I need to set for this? If, yes , can I set it to up to 10 sec in dev scenario and wait until cleanup happens @ReubenBond

**Comment by sergeybykov** [comment]
>is that TableRefreshTimeout I need to set for this?

It's `ClusterMembershipOptions.IAmAliveTablePublishTimeout`.

**Comment by adison88** [comment]
@sergeybykov @ReubenBond thanks, will try to see if issue mitigates. For now, I'm able to generate KVs in new folder by randomizing ServiceID. However, KV clean up is still an issue. One way I'm thinking if we can write a script using Consul APIs to clean up stale KVs periodically. Would you recommend any other way? Also will this be a problem in prod scenario where we'd be doing rolling upgrades, scaling up/down silos?

**Comment by rainman-63** [comment]
We found a hacky workaround, figured I'd share in case anyone else was running into this as well.  Create a hosted service, something like this:

```
 public class ConsulCleanup : IHostedService
 {
    private readonly ILocalSiloDetails localSiloDetails;
    private readonly IMembershipTable membershipTable;

    public ConsulCleanup(ILocalSiloDetails localSiloDetails, IMembershipTable membershipTable)
    {
        this.localSiloDetails = localSiloDetails;
        this.membershipTable = membershipTable;
    }

    public Task StartAsync(CancellationToken cancellationToken) => Task.CompletedTask;

    public async Task StopAsync(CancellationToken cancellationToken)
    {
        await this.membershipTable.UpdateIAmAlive(new MembershipEntry
        {
            SiloAddress = this.localSiloDetails.SiloAddress,
            IAmAliveTime = DateTime.UtcNow.AddMinutes(-10),
            Status = SiloStatus.Dead, // This isn't used to determine if a silo is defunct but I'm going to set it anyway.
        });

        await this.membershipTable.CleanupDefunctSiloEntries(DateTimeOffset.UtcNow.AddMinutes(-5));
    }
}
```

Then register the hosted service with the HostBuilder:

```
IHostBuilder hoster = new HostBuilder()
    .ConfigureServices(serviceCollection =>
    {
        serviceCollection.AddHostedService<ConsulCleanup>();
    });
```

Now when process receives a SIGTERM, the ConsulCleanup host will remove it's entry.  It's a hack, but hopefully it helps.

**Comment by ReubenBond** [comment]
To be clear, Orleans doesn't have a concept of a "run". The idea is that clusters live forever, even if individual hosts within the cluster may come and go and generally change over time. So there is no way to know what silos were for a previous "run" and what are for the current one.

The test host from Orleans.TestingHost propagates a unique cluster id among all silos/clients which it is responsible for. It also supports using AppDomains for isolation. We don't publish the AppDomain host code, so for that, you can copy the bits from the Orleans.TestingHost.AppDomain project. You can also use that with Consul if you'd like (just be sure to set the `UseTestClusterMembership` option to false before you try).

Hopefully that helps. Aside from that, @rainman-63's code should help. You can do similarly with a much more aggressive time (eg, a few seconds) at the start of your run, if you'd like.

**Comment by rhyek** [comment]
In case anyone is running dotnet core + orleans with `dotnet run` or `dotnet watch run` in a containerized environment and hitting this issue (think local kubernetes dev clusters or even docker-compose), your silos are probably not gracefully shutting down. This is what @ReubenBond was talking about.

In such cases you might find this useful: dotnet/core#4458

**Comment by rhyek** [comment]
Btw, what is the recommended way to go about handling cases where in fact there was a complete and abrupt silo cluster loss and new silos can't join due to this issue? Manually clearing the membership table?

**Comment by ReubenBond** [comment]
You can manually clean up the cluster membership table, or you can wait 5-10 minutes for the problem to resolve itself, since silos will ignore entries which have not updated their "IAmAlive" entry in 5 minutes

**Comment by rhyek** [comment]
Thanks. @ReubenBond what is the best way to reduce that time in a general way? I know that for Ado.Net the `CleanupDefunctSiloEntries` method is not implemented.

**Comment by ReubenBond** [comment]
There are two settings which are relevant, `ClusterMembershipOptions.IAmAliveTablePublishTimeout` (default 5 minutes) and `ClusterMembershipOptions.NumMissedTableIAmAliveLimit` (default 2).

Those values are multiplied together and if a silo has not updated its IAmAlive entry in the resulting period of time, then it is not considered when performing the initial connectivity check.
