### ISSUE TITLE
Deadlocks when using MySql with Persistence.AdoNet

### ISSUE THREAD

**Issue by srollinet** [dotnet/orleans#6316]
I had to migrate one project from Postgres to MySql (MariaDB more precisely) and I had a lot of deadlock problems when massively persisting grain states

The issue is caused by Gap Locks (https://dev.mysql.com/doc/refman/8.0/en/innodb-locking.html#innodb-gap-locks)

Changing the transaction's isolation level from `REPEATABLE READ` (default in MySql) to `READ COMMITTED` in `WriteToStorage` procedure fixes the problem.

I don't see any advantage to use `REPEATABLE READ` in this context @veikkoeeva any thoughts?

If this solution is ok for you, I'd be happy to make a PR

**Comment by veikkoeeva** [comment]
@srollinet Please do make a PR.

You see in SQL Server this is already being done, plus some othere checks and I think that is the closest to "read committed snapshot":

https://github.com/dotnet/orleans/blob/master/src/AdoNet/Shared/SQLServer-Main.sql#L34

https://github.com/dotnet/orleans/blob/master/src/AdoNet/Orleans.Persistence.AdoNet/SQLServer-Persistence.sql#L88

As a side note, the next release supports also https://github.com/mysql-net/MySqlConnector which can help with performance too.

**Comment by srollinet** [comment]
Done.
 
> As a side note, the next release supports also https://github.com/mysql-net/MySqlConnector which can help with performance too.

Thanks for the hint! In fact I already use 3.1.0-RC3 with MySqlConnector :)
