### ISSUE TITLE
Need to remove beta package in Orleans.Streaming.GCP

### ISSUE THREAD

**Issue by OracPrime** [dotnet/orleans#6318]
Orleans.Streaming.GCP references Google.Cloud.PubSub.V1.  At the moment the selected version is v1.0.0-beta13.

Quite aside from the issue of having a beta version in production code, the beta version pulls in system.net.http v4.3.1 which has some known security vulnerabilities.

Upgrading to v1.1.0 unfortunately involves getting round some breaking changes (and I can't find any docs to ease the passage through unbreaking them :( ), but it does update the http reference to a not-known-to-be-insecure version

**Comment by sergeybykov** [comment]
I don't believe we ever published `Orleans.Streaming.GCP` package for exactly these reasons. We did publish Betas and RCs of [Microsoft.Orleans.OrleansGCPUtils](https://www.nuget.org/packages/Microsoft.Orleans.OrleansGCPUtils/). I just unlisted them.

**Comment by OracPrime** [comment]
Ah, OK.  Prior to looking to take Orleans to production use, I've thrown the Whitesource security analyser at it - but I pointed it at my clone which had all the solutions in it.

The other bizarre report from it, which I don't quite understand, is that the system.runtime reference in the Orleans.CodeGeneration.Build causes an insecure version of system.private.uri to be pulled in.  I can't see what it is about that one project that causes that.

**Comment by sergeybykov** [comment]
I don't know what that system.private.uri is about. Consider also that `Microsoft.Orleans.OrleansCodeGenerator.Build` is effectively deprecated and was replaced by `Microsoft.Orleans.CodeGenerator.MSBuild`.

**Comment by OracPrime** [comment]
Presumably .Build won't be removed from the nuget package for a while though.
No worries, I'm sure I can get it past our security guys by saying "we don't use that one" :)

**Comment by sergeybykov** [comment]
I think we should deprecate .Build after we publish 3.1.0 and point to .MSBuild as a replacement. Nuget.org now supports that.

**Comment by sergeybykov** [comment]
We deprecated `Microsoft.Orleans.OrleansCodeGenerator.Build` starting with 3.1.0 and pointed to `Microsoft.Orleans.CodeGenerator.MSBuild` as a replacement. Will stop publishing `Microsoft.Orleans.OrleansCodeGenerator.Build` in 3.2.0+.
