### ISSUE TITLE
Should ActivationData Scope be dispose explicitly in all scenario?

### ISSUE THREAD

**Issue by EranOfer** [dotnet/orleans#6349]
I notice that when an exception is thrown during grain OnActivateAsync /constructor the catalog doesn't dispose of the ActivationData scope.

```c#
    internal class ActivationData : IGrainActivationContext, IActivationData, IInvokable, IDisposable
{
......


.....
      internal void SetupContext(GrainTypeData typeData, IServiceProvider grainServices)
        {
            this.GrainTypeData = typeData;
            this.Items = new Dictionary<object, object>();
            this.serviceScope = grainServices.CreateScope();
```

```c#
public interface IServiceScope : IDisposable
```
The [Dispose()](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable.dispose?view=dotnet-plat-ext-3.1#System_IDisposable_Dispose) method ends the scope lifetime. Once Dispose is called, any scoped services that have been resolved from [ServiceProvider](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.iservicescope.serviceprovider?view=dotnet-plat-ext-3.1#Microsoft_Extensions_DependencyInjection_IServiceScope_ServiceProvider) will be disposed.

In the default implantation, there is no problem due to the fact the ServiceScope is the only one who references the scope object. 

![image](https://user-images.githubusercontent.com/13414515/75321588-ba69bb80-5879-11ea-87e9-33fce909fc84.png)

But it depends on the implementation of the IServiceScope
I encounter other implantation that must dispose of the scope or it causes a memory leak.

I think we should always dispose of the scope.

**Comment by ReubenBond** [comment]
Yes, it should. If a scope is created then we must dispose it. Thank you for investigating!

Are you able to open a PR to fix this?

**Comment by EranOfer** [comment]
I investigated a memory leak, I decided that the best approach for me is to create other implementation of the service scope eliminating this kind of leaks in the first place.

I don't sure, I have time to create a PR.

The problematic flow:

```mermaid
sequenceDiagram
    catalog-->>ActivationData:GetOrCreateActivation
    ActivationData-->>ActivationData:constractor
    catalog-->>catalog:RegisterMessageTarget(ActivationData )
    catalog->>catalog:activations.Add
    catalog-->>catalog:SetupActivationInstance
    catalog-->>ActivationData:SetupContext() !!
    catalog-->>catalog:CreateGrain<throw>
    catalog-->>catalog:UnregisterMessageTarget
    catalog-->>catalog:activations.Remove
    ActivationData-->ActivationData:Missing Dispose like heppand in the FinishDestroyActivations
```
I missing a lot of context but ,my assumption is that on UnregisterMessageTarget that grain should be dead and can safly dispose of the context  .

**Comment by EranOfer** [comment]
I think the scope is not disposed also a case of duplicate activation.

**Comment by EranOfer** [comment]
@ReubenBond,
I read the code, I am trying to understand what can affect failing to create the state due to duplicate activation.
As I understand from the code fail to create due to duplicate activation race is affected by a few conditions. 

- Time to publish grain directory.
- Placement strategy (local)
- Time to create the Grain.
  - OnActivateAsync 
  - Constructor 

What should be the approach to avoid failers to create the grain due to duplicate activation when your grain needs to do long init operation (what is the right stage)?

**Comment by ReubenBond** [comment]
ActivationData was rewritten in 7.0 and if there was an issue here, it was likely fixed along with that. I'll close this now but please reopen if you still experience this issue
