### ISSUE TITLE
Is a ClusterClient expected to recover from intermittent connection issues?

### ISSUE THREAD

**Issue by alexrp** [dotnet/orleans#6359]
I've seen cohosting and dependency injection examples where people are injecting a singleton `IClusterClient` at startup (which is also what I'm currently doing), but looking through the documentation, I couldn't actually find out whether the client is expected to eventually recover from intermittent connection issues.

This is of course an important guarantee to have since, if the client is *not* guaranteed to recover and one is using a singleton instance, the application would need to be restarted to obtain a working client instance again.

This seems like an obvious enough issue that I would imagine this guarantee is actually there, but I would rest easier knowing for sure whether that's the case.

**Comment by ReubenBond** [comment]
Yes, it is - if you could please add some text to the documentation which makes this more clear, that would be most appreciated

**Comment by alexrp** [comment]
Sure. A few questions regarding that:

* What exception type(s) should one expect if there's an inability to obtain a grain instance, stream provider, or whatever the case may be due to connection issues?
* How many times will the client retry on failure / how long would it take for the client to retry a silo that's been flagged as "broken"? (Are these configurable?)

**Comment by ReubenBond** [comment]
> What exception type(s) should one expect if there's an inability to obtain a grain instance, stream provider, or whatever the case may be due to connection issues?

You can get connection issues during startup (in the Connect method), but after that you ought to be able to create a reference to any grain which the cluster has an implementation for. Creating a grain reference doesn't involve communicating with anything, so connection issues do not affect it.

> How many times will the client retry on failure / how long would it take for the client to retry a silo that's been flagged as "broken"? (Are these configurable?)

The client will retry connections indefinitely, but the logic isn't as simple as that. It works like this:
* If a connection fails, the connection is marked as 'dead' for some period of time and will not be used again until:
  * All connections are marked as dead; or
  * The `IGatewayListProvider.MaxStateleness` duration passes. This is the value of `GatewayOptions.GatewayListRefreshPeriod`, which defaults to 1 minute.

**Comment by alexrp** [comment]
So for instance, if I obtain a grain reference and the whole cluster goes down, and I then try to call `grain.SomeMethod()`, would I just get a `TimeoutException`?

**Comment by ReubenBond** [comment]
You will see a `SiloUnavailableException`

**Comment by alexrp** [comment]
Resolved by #6360.
