### ISSUE TITLE
I want to donate Orleans.MultiClient, how do I do it?

### ISSUE THREAD

**Issue by lfzm** [dotnet/orleans#6367]
I want to donate  [Orleans.MultiClient](https://github.com/lfzm/Orleans.MultiClient) to OrleansContrib, how do I do it?

**Comment by ReubenBond** [comment]
Do you mean you want to move the project to into the [OrleansContrib](https://github.com/OrleansContrib/) organization? Otherwise I don't quite understand.

**Comment by sergeybykov** [comment]
I think OrleansContrib is the right place for this. That would be great if you put it there. @galvesribeiro or @richorama can create a repository for you and make it admin of it.

**Comment by galvesribeiro** [comment]
@lfzm hey!

It is ok to add it to OrleansContrib. But first I would suggest you to convert everything to English before the move. That way more people can easily contribute and use your package.

**Comment by lfzm** [comment]
@galvesribeiro @ReubenBond @sergeybykov  Sorry, it should be added to OrleansContrib.
I ’ll sort it out this time and add the content in English

**Comment by lfzm** [comment]
@galvesribeiro  English README has been added, my English is not good, there may be problems, please help review

**Comment by galvesribeiro** [comment]
Wow! Now I understand what the package means :)

Really clever idea @lfzm!!! Specially when people are using clusters as microservices. 

The repo was created on OrleansContrib: https://github.com/OrleansContrib/Orleans.MultiClient

The code was imported and you are admin there now.

Thanks, and :shipit:!!!

**Comment by lfzm** [comment]
@galvesribeiro  Thank you

**Comment by lfzm** [comment]
@galvesribeiro Excuse me; I just want to submit a PR, I ca n’t manage OrleansContrib / Orleans.MultiClient

**Comment by galvesribeiro** [comment]
Ah! Ok @lfzm 

I've imported your code already and it is there. I'll setup the CI/CD for it and keep it from here.

Can you also transfer the NuGet package https://www.nuget.org/packages/Orleans.MultiClient to me so we can setup publishing from here?

Thanks!

**Comment by lfzm** [comment]
@galvesribeiro Does moving to OrleansContrib need to hand over nuget.org? Can I maintain it myself? I want to join OrleansContrib as a member and maintain Orleans.MultiClient together. I don't know if I meet the standard.

**Comment by galvesribeiro** [comment]
Absolutely! Sorry for the confusion. I've spoken with @ReubenBond offline.

I've added you on that repository as admin. The code is there for you to maintain. Fell free to keep maintaining it, accepting PRs and publishing packets from it. Its all yours 😄 

So, unless we have anything else to discuss, I think we can close this issue.

If you have any issues there, feel free to open an issue on your repo and tag me there.

Again, sorry for the confusion and thanks for the contribution!

**Comment by lfzm** [comment]
@galvesribeiro Thank you, English is not my native language, which leads to misunderstanding, sorry

**Comment by jason-bragg** [comment]
@lfzm, Great work!  Very practical solution for a front-end service which talks to multiple back-end services (each in it's own Orleans cluster).

I like how the clients partitioning is broken out by grain organization, as it allows sets of logic to be moved between the services in somewhat of a distributed component manner.  Very flexible.  One could start with a single monolithic cluster with multiple sets of grain logic, then later move each set of grain logic into is own cluster (to be maintained and scaled separately) with minimal changes to the front end.

**Comment by galvesribeiro** [comment]
Yeah, that is really cool. I think it should be something built-in at the `IClusterClient` 

💃
