### ISSUE TITLE
Explanation regarding IAsyncStream<T>.GetAllSubscriptionHandles()

### ISSUE THREAD

**Issue by DiAifU** [dotnet/orleans#6368]
Hi,

I am working on the subscription logic in our app to ensure that I resubscribe to a stream instead of creating a new handle each time (whenever possible).
What I expected from the `IAsyncStream<T>.GetAllSubscriptionHandles()` function is to return the handles for a given grain type + primary key. Since we're only subscribing once to each stream in our grains, I assumed that I should only have one handle in the list (if a previous subscription already existed obviously) and that I could reuse it to resubscribe.

But after a few tests, I realized that different activations of a grain were retrieving the handles from other activations too.

So I decided to test this pattern in a sample project, and I couldn't reproduce it. In the end, when I created two activations of a grain, `IAsyncStream<T>.GetAllSubscriptionHandles()` only retrieved the handles for each specific activation (which is the pattern I expected). So I gave a look at the JSON payload and I noticed a few differences between my main and my test projects.

Here is the JSON of my test project :
```json
{
  "$id": "1",
  "$type": "Orleans.Streams.PubSubGrainState, Orleans.Runtime",
  "Producers": {
    "$type": "System.Collections.Generic.HashSet`1[[Orleans.Streams.PubSubPublisherState, Orleans.Core]], System.Collections",
    "$values": []
  },
  "Consumers": {
    "$type": "System.Collections.Generic.HashSet`1[[Orleans.Streams.PubSubSubscriptionState, Orleans.Core]], System.Collections",
    "$values": [
      {
        "$id": "2",
        "$type": "Orleans.Streams.PubSubSubscriptionState, Orleans.Core",
        "Stream": {
          "$id": "3",
          "$type": "Orleans.Streams.StreamId, Orleans.Core",
          "Guid": "79dd573a-efc3-4e3a-9957-3f0b7452d51a",
          "ProviderName": "SMS",
          "Namespace": "test"
        },
        "SubscriptionId": {
          "$id": "4",
          "$type": "Orleans.Runtime.GuidId, Orleans.Core.Abstractions",
          "Guid": "f0b37117-16db-4cf1-9cf6-3373740aaf22"
        },
        "consumerReference": {
          "$type": "Orleans.Streams.OrleansCodeGenStreamConsumerExtensionReference, Orleans.Core",
          "GrainId": "0000000000000000000000000000000103ffffffc024bd45",
          "GenericArguments": ""
        }
      },
      {
        "$id": "5",
        "$type": "Orleans.Streams.PubSubSubscriptionState, Orleans.Core",
        "Stream": {
          "$ref": "3"
        },
        "SubscriptionId": {
          "$id": "6",
          "$type": "Orleans.Runtime.GuidId, Orleans.Core.Abstractions",
          "Guid": "99a2600d-c107-4485-a05f-1fcd51e15c7c"
        },
        "consumerReference": {
          "$type": "Orleans.Streams.OrleansCodeGenStreamConsumerExtensionReference, Orleans.Core",
          "GrainId": "0000000000000000000000000000000203ffffffc024bd45",
          "GenericArguments": ""
        }
      }
    ]
  }
}
```

Each subscription has a different `GrainId`, one for the activation with `1` as the primary key, and `2` for the other.

Here is the one from my main project :
```json
{
  "$id": "1",
  "$type": "Orleans.Streams.PubSubGrainState, Orleans.Runtime",
  "Producers": {
    "$type": "System.Collections.Generic.HashSet`1[[Orleans.Streams.PubSubPublisherState, Orleans.Core]], System.Collections",
    "$values": [
      {
        "$id": "2",
        "$type": "Orleans.Streams.PubSubPublisherState, Orleans.Core",
        "Stream": {
          "$id": "3",
          "$type": "Orleans.Streams.StreamId, Orleans.Core",
          "Guid": "6395d740-6e55-11e8-b566-0800200c9a66",
          "ProviderName": "SMS",
          "Namespace": "M7.Heartbeat"
        },
        "producerReference": {
          "$type": "Orleans.Streams.OrleansCodeGenStreamProducerExtensionReference, Orleans.Core",
          "GrainId": "450a8ec3eeba4965f566fb006ede70950400000000000000",
          "ObserverId": "23706d43-baaf-4a48-8301-4d6a767e0a82",
          "GenericArguments": ""
        }
      }
    ]
  },
  "Consumers": {
    "$type": "System.Collections.Generic.HashSet`1[[Orleans.Streams.PubSubSubscriptionState, Orleans.Core]], System.Collections",
    "$values": [
      {
        "$id": "4",
        "$type": "Orleans.Streams.PubSubSubscriptionState, Orleans.Core",
        "Stream": {
          "$ref": "3"
        },
        "SubscriptionId": {
          "$id": "5",
          "$type": "Orleans.Runtime.GuidId, Orleans.Core.Abstractions",
          "Guid": "75abe7f9-390f-4ce1-a26a-67d1cc028c2b"
        },
        "consumerReference": {
          "$type": "Orleans.Streams.OrleansCodeGenStreamConsumerExtensionReference, Orleans.Core",
          "GrainId": "450a8ec3eeba4965f566fb006ede70950400000000000000",
          "ObserverId": "583016d5-3639-43e5-885b-5aa6b32c9df7",
          "GenericArguments": ""
        }
      },
      {
        "$id": "6",
        "$type": "Orleans.Streams.PubSubSubscriptionState, Orleans.Core",
        "Stream": {
          "$ref": "3"
        },
        "SubscriptionId": {
          "$id": "7",
          "$type": "Orleans.Runtime.GuidId, Orleans.Core.Abstractions",
          "Guid": "a2338aff-2ef7-4acd-bef9-ee37c6488718"
        },
        "consumerReference": {
          "$type": "Orleans.Streams.OrleansCodeGenStreamConsumerExtensionReference, Orleans.Core",
          "GrainId": "450a8ec3eeba4965f566fb006ede70950400000000000000",
          "ObserverId": "583016d5-3639-43e5-885b-5aa6b32c9df7",
          "GenericArguments": ""
        }
      },
      {
        "$id": "8",
        "$type": "Orleans.Streams.PubSubSubscriptionState, Orleans.Core",
        "Stream": {
          "$ref": "3"
        },
        "SubscriptionId": {
          "$id": "9",
          "$type": "Orleans.Runtime.GuidId, Orleans.Core.Abstractions",
          "Guid": "a25178cd-61ec-4fa1-bd31-2803033b3142"
        },
        "consumerReference": {
          "$type": "Orleans.Streams.OrleansCodeGenStreamConsumerExtensionReference, Orleans.Core",
          "GrainId": "450a8ec3eeba4965f566fb006ede70950400000000000000",
          "ObserverId": "583016d5-3639-43e5-885b-5aa6b32c9df7",
          "GenericArguments": ""
        }
      },
      {
        "$id": "10",
        "$type": "Orleans.Streams.PubSubSubscriptionState, Orleans.Core",
        "Stream": {
          "$ref": "3"
        },
        "SubscriptionId": {
          "$id": "11",
          "$type": "Orleans.Runtime.GuidId, Orleans.Core.Abstractions",
          "Guid": "3aad6d49-6792-4bd2-b6a2-3c7320afa268"
        },
        "consumerReference": {
          "$type": "Orleans.Streams.OrleansCodeGenStreamConsumerExtensionReference, Orleans.Core",
          "GrainId": "450a8ec3eeba4965f566fb006ede70950400000000000000",
          "ObserverId": "583016d5-3639-43e5-885b-5aa6b32c9df7",
          "GenericArguments": ""
        }
      },
      {
        "$id": "12",
        "$type": "Orleans.Streams.PubSubSubscriptionState, Orleans.Core",
        "Stream": {
          "$ref": "3"
        },
        "SubscriptionId": {
          "$id": "13",
          "$type": "Orleans.Runtime.GuidId, Orleans.Core.Abstractions",
          "Guid": "35820dd5-adb6-4ce2-bf01-c7af0ff90a43"
        },
        "consumerReference": {
          "$type": "Orleans.Streams.OrleansCodeGenStreamConsumerExtensionReference, Orleans.Core",
          "GrainId": "450a8ec3eeba4965f566fb006ede70950400000000000000",
          "ObserverId": "583016d5-3639-43e5-885b-5aa6b32c9df7",
          "GenericArguments": ""
        }
      },
    ]
  }
}
```

I have a few more activations subscribing to the same topic, but here is the thing : Every subscription has the same `GrainId` + an `ObserverId` which is also the same every time. I guess then this is why the `IAsyncStream<T>.GetAllSubscriptionHandles()` function returns all the handles everytime, but the thing is that these subscriptions are made in different activations and even in different grains.
This main project has a bit of a different pattern than my test one, especially regarding which class actually do the subscription, etc. But even when trying to reapply this pattern, I am not able to have that `ObserverId` in the JSON.

EDIT : There is one thing that I forgot to mention and which seems to make a difference : The streams for which GrainId is always the same + there is an observer id, are streams that were created (and for which producers) are within a nugget package that is referenced in our main project. I don't see why this would make things behave differently, but I have been able to reproduce the pattern by subscribing with a simple client to streams in that nugget, whereas all the other streams in my app do have a different GrainId + no observerId.

So my questions are :
- First of all, do I misinterpret how  `IAsyncStream<T>.GetAllSubscriptionHandles()`  should be working ?
- What is the signification of that `ObserverId` inside the JSON payload ?
- What could make different grains, and different activations have the same ids inside that JSON ?

Thank you in advance for your help.

Regards,
Nicolas

**Comment by DiAifU** [comment]
Hi,
Sorry about the confusion, I am indeed talking about a grain with a unique key when I was using « grain activation ».
So in this case, let’s say I have a grain A (class name), with a primary key 1, producing on a stream with guid a-a-a-a, and grains B with different primary keys (1 to 10 for example), consuming that  a-a-a-a stream, should each B grain get 1 handle if they subscribe once, or get all the handles ?
 
Because depending on whether I run my test project or my main project, I seem to have different results.

Regarding `ObserverId`, these specific streams have only grains producing and consuming them within the silo. No client is subscribed to these streams

**Comment by sergeybykov** [comment]
>should each B grain get 1 handle if they subscribe once, or get all the handles ?

Each grain would get only its own handle. Unless it subscribes more than once to the same stream, which is also supported.

**Comment by DiAifU** [comment]
And my problem is here. As you can see in the second json within my first post, each consumer seems to be from the same grain, but it is not. It's actually from different grains, and whenever I call `GetAllSubscriptionHandles()` from one of these grains, I also get the handles from the others.

**Comment by sergeybykov** [comment]
I'm not sure I understand. All consumers seem to have the same GrainId - `450a8ec3eeba4965f566fb006ede70950400000000000000`.

**Comment by DiAifU** [comment]
This is what I see too, but to build this JSON, I actually subscribed from different grains

**Comment by sergeybykov** [comment]
Could this JSON be from a different case? Unless I'm missing something, it shows 5 subscriptions from the same grain - `450a8ec3eeba4965f566fb006ede70950400000000000000`. `ObserverId` confuses me. This looks as if these are for client subscriptions.

/cc @jason-bragg in case he has a different insight.

**Comment by jason-bragg** [comment]
Is it possible that the test code is running the subscription logic outside of the grain's context?  I ask because that used to cause an error, but we added support for grain calls to be called from outside grains, which may also allow subscription creation from outside the context.  If this was done then all of the subscriptions from outside the grain context would all look like they are from the same grain.

Subscribing to a stream from outside a grain context (unless through the client) is not supported, but I may be doing the wrong thing instead of failing, due to the change.  Please check storage and see what the pubsub state is for that stream.  If the grain ID in the pubsub is not the same as it should be it may be the ID of the system target that handles the grain calls made when outside the grain context instead of the grain the subscribe logic lives in.

**Comment by DiAifU** [comment]
That was exactly it, I made sure to stay in the orleans context for the grains calls, but not the subscriptions. It definitly fixed my problem, thank you for your help !
