### ISSUE TITLE
Documentation: Orleans Transactions suggestion

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/orleans#6373]
Hi,

The documentation for Orleans Transactions is somewhat small, but it's an interesting field so I'd be happy to see more documentation later on. However, for now I'll try to make some suggestions and let's see if they make sense.

First of when working with transactions, I'm used to some node starting the transaction scope and then somewhen either commit or rollback the transaction, e.g. using .NET [TransactionScope](https://docs.microsoft.com/en-us/dotnet/api/system.transactions.transactionscope?view=netcore-3.1) class managing the scope.

Reading the documentation gives me an idea that the transaction is owned by the invoked method (with the attribute `[Transaction(TransactionOption.Create)]`) and then committed by the same method when done, e.g. with the `IATMGrain::Transfer` method and [example](https://dotnet.github.io/orleans/Documentation/grains/transactions.html).

But it's not clear from the documentation if that's the case, and if so it would be nice to understand the design decision to not use the `TransactionScope` (for pedagogical reasons).

The other suggestion is a kind of description how the transaction works under the hood. Reading from the [repository](https://github.com/dotnet/orleans/blob/85ba26aa6554639fddb630d6a3f4ab71ad8649b9/src/Azure/Orleans.Transactions.AzureStorage/TransactionalState/AzureTableTransactionalStateStorage.cs) gives me an idea about the store, but I might be wrong, so I need to experiment to see if I got it right.

The point is that if the mechanics are laid out it's easier to understand how it works and how to write a transactional store provider. And to see how it fits in with the Orleans EventSource implementation that more or less requires a [CustomProvider](https://dotnet.github.io/orleans/Documentation/grains/event_sourcing/log_consistency_providers.html).

Other than that, very good work and nice documentation!

Thanks,
Jan

**Comment by sergeybykov** [comment]
I think these are very valid suggestions! We'll gladly accept contributions to make things more clear.

**Comment by jan-johansson-mr** [comment]
Transactions are documented nicely in Orleans, closing this issue
