### ISSUE TITLE
Slow access to Azure Table Reminders for ReadTableEntriesAndEtags

### ISSUE THREAD

**Issue by turowicz** [dotnet/orleans#6377]
I've recently started getting the following error:

```
warn: Orleans.Reminders.AzureStorage.AzureTableDataManager[100815]
      Slow access to Azure Table Reminders for ReadTableEntriesAndEtags, which took 00:00:03.1855454
```

My Orleans Cluster is running 3 silo instances that are idle - there are no activations as nobody uses the system. It has its own dedicated Azure Storage Account for discovery, reminders et al.

Is there something going terribly bad and will the system crash when actual traffic builds up?

Should I provision more storage accounts?

Orleans 2.4.x

cc @ReubenBond

**Comment by turowicz** [comment]
While we don't register any reminders, we do make use of the (now legacy) Grain Observer pattern. Not many observations though, as nobody is using the service. Somewhere between 1 and 10.

**Comment by turowicz** [comment]
Yes it is all in the same region - West Europe.

**Comment by turowicz** [comment]
The cluster is Azure Kubernetes Service based on the Virtual Machine Scale Set.

**Comment by sergeybykov** [comment]
If you aren't using reminders, then this is 100% benign. I wonder if it's caused by such a low usage of the reminders table that a first call to it in a long while is slow (warm up of the table store frontends or something like that). I'm purely speculating here.

Observers are completely unrelated.

**Comment by turowicz** [comment]
OK thanks
