### ISSUE TITLE
Orleans scheduler code examples

### ISSUE THREAD

**Issue by mchudinov** [dotnet/orleans#6387]
Are there any code examples for Orleans scheduler available?

**Comment by sergeybykov** [comment]
Are you looking for how the scheduler is (was) implemented or for how to leverage the concurrency guarantees of it (for example, http://dotnet.github.io/orleans/Documentation/grains/external_tasks_and_grains.html)?

**Comment by mchudinov** [comment]
I probably misunderstood the concept of Orleans scheduler. I was looking for something similar to Service Fabric scheduled tasks. Thank you for the code examples. Ill go through them.

**Comment by mchudinov** [comment]
Oh now I have found something very similar to reminder in Service Fabric https://dotnet.github.io/orleans/Documentation/grains/timers_and_reminders.html
