### ISSUE TITLE
System.TypeLoadException: Method 'Create' on type 'Orleans.Runtime.PersistentStateFactory' tried to implicitly implement an interface method with weaker type parameter constraints

### ISSUE THREAD

**Issue by ifle** [dotnet/orleans#6388]
in some cases we have following error. Failing code does not related to orleans ( v 3.1.2)

System.TypeLoadException: Method 'Create' on type 'Orleans.Runtime.PersistentStateFactory' from assembly 'Orleans.Runtime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' tried to implicitly implement an interface method with weaker type parameter constraints.
  at at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
  at at System.Reflection.RuntimeAssembly.GetExportedTypes()
  at System.Linq.Dynamic.Core.CustomTypeProviders.AbstractDynamicLinqCustomTypeProvider.<GetAssemblyTypesWithDynamicLinqTypeAttribute>d__3.MoveNext() in C:\Users\azurestef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\CustomTypeProviders\AbstractDynamicLinqCustomTypeProvider.cs:131
_

**Comment by ReubenBond** [comment]
What is this code trying to do?

**Comment by ifle** [comment]
This code does not use orleans, it use the extension method ToDataSourceResult of Telerik Kendo.DynamicLinqCore library that run the entity framework query. 
We have this error when migrated from orleans 3.0.2 to 3.1.2
```c#

var result = efContext.Orders.ToDataSourceResult(dataSourceRequest.Take, dataSourceRequest.Skip, dataSourceRequest.Sort, dataSourceRequest.Filter);

```

**Comment by sergeybykov** [comment]
@ifle Have you figured this out? If this code doesn't use Orleans, I'm confused how it gets onto the call stack.

**Comment by ifle** [comment]
Sorry for delay.
I don't understand, failing only one mvc action that does not use directly orleans. 
But the asp.net mvc application use orleans as client (.net 472)
