### ISSUE TITLE
Grain calls retry policy

### ISSUE THREAD

**Issue by srollinet** [dotnet/orleans#6391]
Is there a standard and centralized way to implement retry strategies when calling grain methods from a client or from another grain?

I want to use Polly to retry calls that throw specific exceptions, like `ConnectionFailedException`. But I don't know where to put this code, without doing it manually everywhere I call a grain method.

I tried with an `OutgoingGrainCallFilter`, but it seems `context.Invoke()` cannot be called multiple times.

Thanks in advance for your help!

**Comment by sergeybykov** [comment]
There's no built-in mechanism in Orleans for retrying calls. I guess a base grain class or a helper class could potentially help with that?

**Comment by srollinet** [comment]
Okay, so as it stands today, I suppose there is no chance to retry a call in or after the outgoing filters?

**Comment by sergeybykov** [comment]
I'm not sure off the top of my head why `context.Invoke()` cannot be called multiple times. @ReubenBond might know.

As a general rule, we advise against automatic retries at the 'infrastructure' level because they more often than not lead to retry storms in case of failures and outages.

**Comment by veikkoeeva** [comment]
I cross-link https://github.com/dotnet/orleans/issues/6383 and https://github.com/dotnet/orleans/issues/6384 as it would be nice if there were a system that would similar across the system to do these sort of things: e.g. retries in various point and also exposing native functionality where available (also going to databases). This likely needs to be thought in a fashion that takes account other functionality in the pipeline now and in the future.

**Comment by srollinet** [comment]
> As a general rule, we advise against automatic retries at the 'infrastructure' level because they more often than not lead to retry storms in case of failures and outages.

The idea is not to do simple automatic retries, but to be able to plug more advanced fault handling mechanisms.

> I'm not sure off the top of my head why context.Invoke() cannot be called multiple times. @ReubenBond might know.

When I tried it, I got an `InvalidOperationException` saying that the request was not valid

**Comment by ReubenBond** [comment]
The implementation was intentionally conservative in an attempt to reduce the scope for incorrect usage. For instance, not awaiting the Invoke() call, calling it multiple times successively when no exception has been thrown. Generic retries could have side effects when other filters are not designed to be used that way.

That being said, it's been asked for multiple times, it's a simple change, and the current restriction violates the principal of least surprise.

I've opened PR #6414 with a fix
