### ISSUE TITLE
Multi-targeting in Orleans 3.1.0 caused a rolling-upgrade compatibility break

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#6392]
We have a compatibility break introduced when multi-targeting the Orleans build for 3.1.x.

Some generated code changed in an incompatible way, impacting rolling upgrades. The generated code includes identities of methods and these identities are a hash of the method signature. Differences in type identity between .NET Core and .NET Standard at build time caused these methods to vary between the versions.

One example of the impact of this issue is #6381, but it could manifest in other, similar ways.

Affected versions:
* 3.1.0
* 3.1.2

This issue can affect you if:
* You target .NET Core 3.1 and you upgrade to an affected version
* You build against an an affected version and upgrade to .NET Core 3.1 from a previous version of .NET Core

Impact:
When a cluster has a mix of code built against different Orleans or .NET versions, some method invocations will not work. If you are performing a rolling upgrade, then this will be resolved once the upgrade is complete.

**Comment by sergeybykov** [comment]
Resolved via #6394 and #6396.
