### ISSUE TITLE
After upgrading from 2.4.5 to 3.1.2,A warning appears:Error initializing CPU & Memory perf counters

### ISSUE THREAD

**Issue by HermesNew** [dotnet/orleans#6393]
This is the log：

warn: Orleans.Statistics.PerfCounterEnvironmentStatistics[100719]
      Error initializing CPU & Memory perf counters - you need to repair Windows perf counter config on this machine with 'lodctr /r' command
System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter #3': Cannot marshal a string by-value with the [Out] attribute.
   at System.StubHelpers.StubHelpers.ThrowInteropParamException(Int32 resID, Int32 paramIdx)
   at System.Management.ManagementPath.GetWbemPath(IWbemPath wbemPath)
   at System.Management.ManagementPath.GetWbemPath()
   at System.Management.ManagementPath.get_Path()
   at System.Management.ManagementScope.set_prvpath(ManagementPath value)
   at System.Management.ManagementScope._Clone(ManagementScope scope, IdentifierChangedEventHandler handler)
   at System.Management.ManagementScope._Clone(ManagementScope scope)
   at System.Management.ManagementObjectSearcher..ctor(ManagementScope scope, ObjectQuery query, EnumerationOptions options)
   at Orleans.Statistics.PerfCounterEnvironmentStatistics.InitCpuMemoryCounters()

**Comment by ReubenBond** [comment]
Have you tried running the `lodctr /r` command?

**Comment by HermesNew** [comment]
Already run but did not solve the problem.

**Comment by HermesNew** [comment]
![perferr](https://user-images.githubusercontent.com/22929457/76498829-9b257d80-6478-11ea-8597-1a87ba74fc19.png)
OrleansDashboard cannot view memory usage.

**Comment by HermesNew** [comment]
I think this issue is more urgent.

**Comment by JorgeCandeias** [comment]
Is this on your workstation or laptop? Last time I've seen this one, I've fixed it by updating the [`System.Diagnostics.PerformanceCounter`](https://www.nuget.org/packages/System.Diagnostics.PerformanceCounter/) package to the latest version, 4.7 in my case. The [`Microsoft.Orleans.TelemetryConsumers.Counters`](https://www.nuget.org/packages/Microsoft.Orleans.OrleansTelemetryConsumers.Counters/) package declares a dependency on 4.5 but it looks like that has become outdated against the ever-changing Windows 10. I've seen no such issues on stable server boxes yet though.

**Comment by HermesNew** [comment]
Windows server2012R2 , Windows servier 2016 has this problem.

**Comment by HermesNew** [comment]
Windows Server 2012R2 , Windows Server 2016 has this problem.

**Comment by HermesNew** [comment]
BTW .NetCore version is 3.1,Orleans version is 3.1.2.
Windows Server 2012R2 , Windows Server 2016,Windows10 all has this warn.

**Comment by windperson** [comment]
My case is to upgrade [System.Management](https://www.nuget.org/packages/System.Management) to **4.7.0**, on a Windows 10 1909 box so as to fix this issue.

**Comment by HermesNew** [comment]
@windperson Thank you very much.
After Upgrading  System.Management to 4.7.0, the problem was resolved.

**Comment by HermesNew** [comment]
@ReubenBond I suggest that the Orleans team can upgrade the Microsoft.Orleans.OrleansTelemetryConsumers.Counters version to System.Management (> = 4.5.0) to System.Management (> = 4.7.0)

**Comment by HermesNew** [comment]
@JorgeCandeias Thanks.
System.Diagnostics.PerformanceCounter also need >=4.7.0

**Comment by ReubenBond** [comment]
@HermesNew are you able to open a PR? We can include it in 3.1.3

**Comment by ReubenBond** [comment]
Actually, I will update it. I'll link the PR here, so please let me know if it looks right to you.

**Comment by ReubenBond** [comment]
Here's the PR: https://github.com/dotnet/orleans/pull/6397

**Comment by HermesNew** [comment]
OK,good job.Thanks.
