### ISSUE TITLE
Slow performance - unusable with Debugger attached

### ISSUE THREAD

**Issue by cosmintiru** [dotnet/orleans#6402]
Hello,

One of my colleagues is having a hard experience debugging the application. Whenever he has the debugger attached, he seems to experience massive waits. 

![image_2020_03_16T16_06_58_447Z](https://user-images.githubusercontent.com/6203490/76777994-c0d0c080-67b1-11ea-8465-fabd35db2db7.png)

Is there something we can do to avoid this?

**Comment by sergeybykov** [comment]
Is he debugging only manage code or in mixed mode? It can also be slow if it is loading tons of symbols for system assemblies.
