### ISSUE TITLE
Same grain activated multiple times

### ISSUE THREAD

**Issue by srollinet** [dotnet/orleans#6403]
I have an issue where the same grain is activated multiple times. For 3 distinct Ids, I have 4 activations. Even when they are all in the same silo.

In my case, it causes multiple problems
- A timer is registered during the activation -> task is run twice instead of 1
- Inconsistent states issues when writing the state from within the timer
- Some properties of the grain are not part of the persisted state -> grains have inconsistent "in-memory" states

note: the grain has 2 interfaces `MyGrain : IMyGrain, IInternalMyGrain` and in the timer, I use `this.AsReference<IInternalMyGrain>()` to call the grain in order to avoid re-entrency issues.
Is this a problem?

**Comment by srollinet** [comment]
maybe related to https://github.com/dotnet/orleans/issues/5536 because the duplicate grain is used in the StartupTask

**Comment by sergeybykov** [comment]
If the cluster is stable (no silos leaving/joining it at the moment) there should be no duplicate activations of a grain.
>note: the grain has 2 interfaces MyGrain : IMyGrain, IInternalMyGrain and in the timer, I use this.AsReference<IInternalMyGrain>() to call the grain in order to avoid re-entrency issues.
Is this a problem?

That shouldn't be a problem, so long as the grain interfaces aren't generic with different type arguments.

Do you have a minimal repro demonstrating what you see?

**Comment by srollinet** [comment]
I see this problem frequently in production these days even with grains that should be "singleton" in our system.

Orleans Dashboard frequently reports that such grains are present twice on a cluster containing 2 silos.

I tried to restart both silos, waiting several minutes between the restarts but some grains are still activated multiple times with no apparent reasons.

Is there a way I can debug it and try to figure out why it happens?

**Comment by sergeybykov** [comment]
This is a regular grain, not a `[StatelessWorker]`? Do you configure activation collection time for it or call `DeactivateOnIdle()`?

How exactly do you determine that there's more than one activation of a grain in the cluster *at the same time* other than the Dashboard? Can you have them generate unique IDs upon activation and log with that ID for every request or periodically? Dashboard relies on polling. So it might display stale data.

For regular grains and stable cluster, you should *never* see more than one activation of a grain successfully created and registered in the grain directory. I wonder what's the disconnect here.

**Comment by srollinet** [comment]
> This is a regular grain, not a [StatelessWorker]? Do you configure activation collection time for it or call DeactivateOnIdle()?

It is a regular grain with integer key and its id is always 0. That's why I say it is a "singleton"

> How exactly do you determine that there's more than one activation of a grain in the cluster at the same time other than the Dashboard? Can you have them generate unique IDs upon activation and log with that ID for every request or periodically? Dashboard relies on polling. So it might display stale data.

Other than the Dashboard, I know there are multiple activations because some duplicated grains periodically broadcast their state on a message bus and I have inconsistant states

Let say original state has a value 'x' I receive messages with value 'x'. I change the grain state with value 'y', then I receive messages with value 'x' and messages with value 'y'

> For regular grains and stable cluster, you should never see more than one activation of a grain successfully created and registered in the grain directory. I wonder what's the disconnect here.

What can make a cluster not stable? In my case I start a silo, wait approx 30 seconds and start the other silo. Even after several minutes I can see duplicated grains in the Dasboard and I receive inconsistent events if I modify the state of the grain

**Comment by sergeybykov** [comment]
The cluster should be stable within a split-second after you start the second silo. Unless you see silos crashing and restarting.

Can you capture and share `Info` level logs from both silos? That would help confirm that nothing bad happens with the cluster.

I'm still rather skeptical you are actually seeing multiple activation of the same grain, and suspect that it might be some message ordering issue. But it's a pure speculation at this point. Adding unique IDs should help shed light on that.

**Comment by srollinet** [comment]
> The cluster should be stable within a split-second after you start the second silo. Unless you see silos crashing and restarting.

Silos are not crashing

> Can you capture and share `Info` level logs from both silos? That would help confirm that nothing bad happens with the cluster.

No problem, I'll do that on Monday

**Comment by srollinet** [comment]
I check the Orleans log and it appears there is a warning I haven't seen, reporting an exception

```
ProcessSiloAddEvent(S127.0.0.1:11112:330519505) failed, will NOT be retried: 
Exc level 0: Orleans.Runtime.OrleansMessageRejectionException: Exception while sending message: Orleans.Runtime.Messaging.ConnectionFailedException: Unable to connect to S127.0.0.1:11112:330519505, will retry after 661.4312ms
   at Orleans.Runtime.Messaging.ConnectionManager.ConnectionEntry.ThrowIfRecentConnectionFailure()
   at Orleans.Runtime.Messaging.ConnectionManager.GetConnectionAsync(SiloAddress endpoint)
   at Orleans.Runtime.Messaging.OutboundMessageQueue.<SendMessage>g__SendAsync|10_0(ValueTask`1 c, Message m)
   at Orleans.Runtime.OutgoingCallInvoker.Invoke()
   at Orleans.Runtime.OutgoingCallInvoker.Invoke()
   at Orleans.Runtime.GrainReferenceRuntime.InvokeWithFilters(GrainReference reference, InvokeMethodRequest request, String debugContext, InvokeMethodOptions options)
   at Orleans.Runtime.GrainDirectory.GrainDirectoryHandoffManager.ProcessAddedSiloAsync(SiloAddress addedSilo, List`1 splitPartListSingle, List`1 splitPartListMulti)
   at Orleans.Runtime.GrainDirectory.GrainDirectoryHandoffManager.ExecutePendingOperations()
```

Everything was working normally except for the duplicated grains

I updated Orleans from 3.1.0 to 3.2.0 and it seem it solves the issue

I will do more test and try to deploy in pre-prod to see if everything works as expected.

**Comment by krasin-ga** [comment]
We also observe duplicate activation of grains. At the moment, we use only one active silo, as we are in the stage of data migration. The number of activation of grains is approximately 1500 per second. The grain has a life time of two minutes. Orlean version is 3.2.0.

```
Trying to forward NewPlacement Request
         S10.10.0.162:11111:330880145*grn/PublicationImagesGrain/2b561489@fe3ca7b1 ->
         S10.10.0.162:11111:330880145*grn/PublicationImageGrain/c756aea9@567a258d #415413917 
from 
         S10.10.0.162:11111:330880145*grn/PublicationImageGrain/c756aea9@567a258d 
to
         S10.10.0.162:11111:330880145*grn/PublicationImageGrain/c756aea9@f6954b94
after Duplicate activation. Attempt 0
```
```
Trying to forward NewPlacement Request 
        S10.10.0.162:11111:330880145*grn/PublicationGrain/6b5606ba@d29d1196->
        S10.10.0.162:11111:330880145*grn/PublicationUriVariantGrain/00000000+mc://999/12/11/01@ca4dbd9f #436393599
from 
        S10.10.0.162:11111:330880145*grn/PublicationUriVariantGrain/00000000+mc://999/12/11/01@ca4dbd9f 
to 
        S10.10.0.162:11111:330880145*grn/PublicationUriVariantGrain/00000000+mc://999/12/11/01@5373dc9f
 after Duplicate activation. Attempt 0
```
(We format our logs to include actual type name, instead of type hash code)

![image](https://user-images.githubusercontent.com/11534678/86012008-1f9b0c80-ba26-11ea-961d-5bae6bc9e36e.png)

This happens quite rarely, but it is not clear why this should happen at all with only one active silo. 😅

**Comment by sergeybykov** [comment]
@krasin-ga The wording in this `Info` message is unfortunately confusing. It is meant to indicate that there was a race of trying to create two activations of the same grain. One activation won the race, and messages that were sent to the other one that lost the race are getting forwarded to the winner activation. No duplicate activation actually got created. The winner activation (@f6954b94 in the first case and @5373dc9f in the second) is the only one that got successfully created and registered.

So, no duplicate activations here.

**Comment by krasin-ga** [comment]
Thanks for clarification! Does this mean that the losing grain will not perform any methods other than activation?

We occasionally experience exceptions that could be perfectly explained by concurrent duplicate activations.

**Some pseudocode**

SampleGrain: Grain, ISampleGrain (IGrainWithStringKey)
OnActivateAsync(): read ids from database into _uniqueIds (HashSet)
TryAdd(id): if(_ids.Add(id)) await InsertUniqueId(id) else LogDuplicateId(id);
InsertUniqueId(id): inserts into db, rethrows exceptions as InvalidStateException


**Timeline**

1) _grainClient.GetGrain<SampleGrain>("sample").TryAdd(1); 

2) InvalidStateException is thrown with inner exception of type Microsoft.Data.SqlClient.SqlException
"Cannot insert duplicate key row in object 'dbo.SampleTable' with unique index 'IX_SampleGrainId_Id'.

3) Instance of SampleGrain with id "sample" gets deactivated due to InvalidStateException exception

4) Our RetryOutgoingGrainCallFilter attemps to retry execution of method TryAdd(1) on SampleGrain with id "sample"

5) Method LogDuplicateId is invoked, indicating that the identifier is already in the _uniqueIds collection of SampleGrain with id "sample"

**Comment by sergeybykov** [comment]
>Does this mean that the losing grain will not perform any methods other than activation?

The activation that lost the race fails to activate, and no requests gets invoked on it. 

In the pseudocode above, do all insert calls to the database always go through the grain, and is the list of IDs partitioned by the grain key (e.g. "sample")? Is the grain non-reentrant (default)?

If `OnActivateAsync()` loads all existing keys, and `TryAdd(id)` is the only way to add a new key to the list, I don't understand how `InsertUniqueId(id)` would ever throw a ""Cannot insert duplicate key row" error.

>3. Instance of SampleGrain with id "sample" gets deactivated due to InvalidStateException exception

Is that because you catch the exception in your code and call `DeactivateOnIdle()`?

>5. Method LogDuplicateId is invoked, indicating that the identifier is already in the _uniqueIds collection of SampleGrain with id "sample"

If the "sample" grain got deactivated, this doesn't make sense. However, if it does stay activated, then that's what I would expect because the id gets added to `_ids` and doesn't get removed from it (?) upon `InsertUniqueId(id)` throwing an exception?

**Comment by krasin-ga** [comment]
@sergeybykov, thanks! I checked the code for the tenth time and found the reason. 

The neighboring entries in the error logs from database and duplicate activations were indeed coincidence. The error was in our class, which calculates hash from the string (grain idenitity) to use it as index key. Singleton instance of that class was used during activation and produced incorrect results when used concurrently, so no identities was actually loaded into HashSet.

>Is that because you catch the exception in your code and call DeactivateOnIdle()?

Deactivation occurs within the Orleans runtime:
https://github.com/dotnet/orleans/blob/8b7eaf2f481272dd9b4080ceff103a34db637713/src/Orleans.Runtime/Core/InsideRuntimeClient.cs#L391

```
Jul 4, 2020 @ 22:33:03.157 [Info] Deactivating [Activation: S10.10.0.162:11111:331364446*grn/PublicationUriVariantGrain/00000000+mc://2020/10/01@7d22c89b #GrainType=M13.Archive.Grains.Publications.PublicationUriVariantGrain Placement=PreferLocalPlacement State=Valid] due to inconsistent state.
Jul 4, 2020 @ 22:33:03.157 [Info] DeactivateActivationOnIdle: [Activation: S10.10.0.162:11111:331364446*grn/PublicationUriVariantGrain/00000000+mc://2020/10/01@7d22c89b #GrainType=M13.Archive.Grains.Publications.PublicationUriVariantGrain Placement=PreferLocalPlacement State=Deactivating] later when become idle.
```

**Comment by sergeybykov** [comment]
@krasin-ga Great! So you are good now?

**Comment by krasin-ga** [comment]
Yep, thanks again!

**Comment by apatenotre** [comment]
> > Does this mean that the losing grain will not perform any methods other than activation?
> 
> The activation that lost the race fails to activate, and no requests gets invoked on it.

@sergeybykov does that mean that `OnActivateAsync()` is called **only** on the grain that wins the race ?

**Comment by apatenotre** [comment]
@ReubenBond, mentioning you here as you may be able to have a quick answer about the above question. Thanks!

**Comment by hichemaichour** [comment]
@sergeybykov We are facing similar issue of same grain activate multiple times:

1. We are using Orleans 3.3.0 (latest)
2. We are using the grain exactly as mentioned here "[Combining Timers and Reminders](https://dotnet.github.io/orleans/docs/grains/timers_and_reminders.html#combining-timers-and-reminders)"
   - We are overloading `OnActivateAsync` and `OnDeactivateAsync` to log activation/deactivation
   - We are setting reminder for every 2 minutes with initial 50 seconds delay.
   - We are setting timer for every 35 seconds with initial 5 seconds delay.
   - Grain interface implements `IGrainWithStringKey`
   - The two grains were both running simultaneously the timer `asyncCallback` every 35 seconds for a period of 3 minutes, with an offset of 5 seconds at the beginning, that kept shortening until a `WriteStateAsync` collided causing an exception
   - We can see the following logs:

|      Time        |    Silo    | Log | 
|---------------|---------|-----------------------------------------------------------------------|
| T01:31:53.18 | Silo-02 | Grain activated. Key:'106a102b-49e8-4eb3-8e5e-62a0af76e318' |
| T01:34:45.81 | Silo-01 | Grain activated. Key:'106a102b-49e8-4eb3-8e5e-62a0af76e318' |
| T03:37:11.47 | Silo-02 | Grain deactivated. Key:'106a102b-49e8-4eb3-8e5e-62a0af76e318' |
| T03:39:07.50 | Silo-01 | Grain deactivated. Key:'106a102b-49e8-4eb3-8e5e-62a0af76e318' |
