### ISSUE TITLE
OrleansJsonSerializer does not set SerializationManager in JsonSettings context anymore

### ISSUE THREAD

**Issue by rikbosch** [dotnet/orleans#6424]
Hi,

We're using a 'trick' to serialize the orleans request-context to Json in 1.5.x.

We serialize the context to a base64 encoded string using the orleans `SerializationManager`, which was being set by the `OrleansJsonSerializer`.

```csharp
internal class OrleansBase64Converter<T> : JsonConverter
    {
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            // secret handshake
            // is provided by serialization settings
            var orleansSerializationManager = serializer.Context.Context as SerializationContext;
            var bytes = orleansSerializationManager.SerializationManager.SerializeToByteArray(value);
            var base64 = Convert.ToBase64String(bytes);

            writer.WriteValue(base64);
        }

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            var orleansSerializationManager = serializer.Context.Context as SerializationContext;

            var source = (string) reader.Value;
            var bytes = Convert.FromBase64String(source);
            return orleansSerializationManager.SerializationManager.DeserializeFromByteArray<T>(bytes);
        }

        public override bool CanConvert(Type objectType)
        {
            return true;
        }
    }
```

The reason is, we do not know what types are being put into the request-context. And if Orleans can serialize them, we should use the Orleans serializer for this.

But after migrating to Orleans 3.1. The SerializationContext is not set in the JsonSerializerSettings:

![image](https://user-images.githubusercontent.com/549975/77318346-376b4200-6d0d-11ea-8298-6da3acdb8c87.png)

It was changed in this commit: https://github.com/dotnet/orleans/commit/14044fcceb5fb9a7a3237c5964edb08c40a093a0#diff-4d91f8bd442b5b667b72284482b39fb7

Is it possible to reuse the orleans `SerializationManager` within the json-context? Note: we're using the converter as an attribute to certain properties.

**Comment by ReubenBond** [comment]
Could you construct your OrleansBase64Converter using DI and inject the SerializationManager instead?

The main problem with the context was that it wasn't reliable - some types would override the context when serializing/deserializing inner members
