### ISSUE TITLE
Generic Grain Activation throws error

### ISSUE THREAD

**Issue by AmrutaMoghe** [dotnet/orleans#6426]
public class GenericGrainWithContraints<A, B> : Grain, IGenericGrainWithConstraints<A, B, string>
        where A : struct
        where B : struct
{
     public string Add(A a, B b){}
}

IGrain grain = GrainFactory.GetGrain(typeof(IGenericGrainWithConstraints<A, B, string>),0);
var grainInterface = (IGenericGrainWithConstraints<A, B, string>)grain;

The following line throws error, error creating activation, with innerexception as The number of generic arguments provided doesn't equal the arity of the genric type definition. 

grainInterface.Add(1,1);

I looked at Orleans code,  In GrainTypeManager class
className = implementation.GetClassName(genericArguments);
Type[] typeArgs = TypeUtils.GenericTypeArgsFromClassName(className)
 var concreteTypeData = genericGrainTypeData.MakeGenericType(typeArgs);

It seems, an instance is being created with A,B and fails.

**Comment by ReubenBond** [comment]
This is a known limitation. You can still activate that grain and communicate with it using that interface, but you need to do it in a different way. It's something we plan to sort out in 4.0.

The interface you use to create the original grain reference must have matching generic parameters to the grain class.

However, once you have that grain reference, you can .Cast it to a different type (eg, your 3-parameter interface) and make calls on it.

So, the workaround for now is:

``` C#
public class GenericGrainWithContraints<A, B> :
    Grain,
    IConstraintsGrain<A, B>,
    IGenericGrainWithConstraints<A, B, string>
{ ... }

var grain = GrainFactory
    .GetGrain<IGenericGrain<int, int>>(0)
    .Cast<IGenericGrainWithConstraints<int, int, string>>();

grain.CallSomethingOnIGenericGrainWithConstraints();

```

**Comment by AmrutaMoghe** [comment]
IConstraintsGrain<A, B> : IGrainWithIntegerKey
{
}

IGenericGrainWithConstraints<A, B, C>
{
}
 Is this how the interfaces will be?

**Comment by ReubenBond** [comment]
Ah, the Cast results in a different issue to the one I was thinking of. Yes, this wont work yet. Still, some of the work for 4.0 will hopefully rectify this.

You can work around some aspects of the current limitation by creating a partially-specialized interface and using that, instead. It's not a full workaround, however.

``` C#
public interface ISpecializedGenericGrainWithConstraints<A, B> : IGenericGrainWithConstraints<A, B, string>
    where A : ICollection<B>, new() where B : struct
{
}
```

**Comment by ThiagoT1** [comment]
@AmrutaMoghe , @ReubenBond , 
It seems a workaround would be to have the actual grain export its Casted GrainReference originated from it's main interface.
Does it make sense?
