### ISSUE TITLE
Silo Keys are being deleted from Consul KV

### ISSUE THREAD

**Issue by AmrutaMoghe** [dotnet/orleans#6429]
When Silo Starts the silodetails key is created in consul followed by IamAlive key creation.
But it is observed that the SiloDetailskey is getting deleted after sometime from Consul.

When going through sourcecode I observed that consulBaseMembershiptable.cs file has two function cleanupDefunctSiloEntries & Deletemembershiptable entries.

DeleteMembershiptable entry method is getting invoked from some grain internally which we are not able to figure out and cleanupDefunctSiloEntries being called from
Membership table cleanup agent.

But still, we are not able to figure out why the SiloDetailKey is getting deleted and this happening when we are doing load testing.

**Comment by sergeybykov** [comment]
I only see `DeleteMembershipTableEntries` being invoked from tests. Do you see it getting called? I suspect it must be something else that deletes the data from Consul.
