### ISSUE TITLE
OrleansRelationalConstants Exception

### ISSUE THREAD

**Issue by weitaolee** [dotnet/orleans#643]
When use sql server membership
 &lt;SystemStore SystemStoreType="SqlServer"
               DeploymentId=".."
               DataConnectionString=".."/&gt;

https://github.com/dotnet/orleans/blob/master/src/Orleans/RelationalStorage/OrleansRelationalConstants.cs#L179

QueryConstants does not has "ActiveGatewaysQueryKey" and throw "System.Collections.Generic.KeyNotFoundException"	

I use TwitterWebApplication for this test

**Comment by veikkoeeva** [comment]
@weitaolee Hi!

As you noticed, the keys are defined there in that classa and they are fetched . The code should fetch the keys from the storage, which is defined at [CreateOrleansTables_SqlServer.sql line 1191](https://github.com/dotnet/orleans/blob/master/src/OrleansProviders/SQLServer/CreateOrleansTables_SqlServer.sql#L1191). I think I see the reason, you are initializing a client and it does not retrieve the keys. The relevant piece of code is [here](https://github.com/dotnet/orleans/blob/bf1ca659ca16e09f0e327a9f52618926bf76392e/src/Orleans/Messaging/SqlMembershipTable.cs#L70). It should call [InitializeOrleansQueriesAsync()](https://github.com/dotnet/orleans/blob/bf1ca659ca16e09f0e327a9f52618926bf76392e/src/Orleans/Messaging/SqlMembershipTable.cs#L54) just as membership table initialization.

**Comment by veikkoeeva** [comment]
@weitaolee I can provide the fix, but it takes about 12-14 hours before I'm back at home. It should be just adding that one line to ``InitializeGatewayListProvider`` so that when the call to [SqlMembershipTable.GetGateways()](https://github.com/dotnet/orleans/blob/bf1ca659ca16e09f0e327a9f52618926bf76392e/src/Orleans/Messaging/SqlMembershipTable.cs#L97) comes, the queries would be ready. It would be great if you have time to try it, but it's OK if you want to wait for a bit.

**Comment by veikkoeeva** [comment]
I'm not sure if this is the correct way to configure, but I whipped up the following:
**DevTestServerConfiguration**
```
<?xml version="1.0" encoding="utf-8"?>
<OrleansConfiguration xmlns="urn:orleans">
  <Globals>    
      <SystemStore SystemStoreType ="SqlServer"
      DeploymentId="Test1"
      DataConnectionString="Data Source=(localdb)\MSSQLLocalDB;Database=TwitterTest;Integrated Security=True;Asynchronous Processing=True;Max Pool Size=200; MultipleActiveResultSets=True" />
    <StorageProviders>
      <!-- To use Azure storage, uncomment one of the following lines: -->
      <Provider Type="Orleans.Storage.MemoryStorage" Name="store1" NumStorageGrains="1"/>
      <!--<Provider Type="Orleans.Storage.AzureTableStorage" Name="AzureStore" DataConnectionString="UseDevelopmentStorage=true" />-->
      <!--<Provider Type="Orleans.Storage.AzureTableStorage" Name="AzureStore" DataConnectionString="DefaultEndpointsProtocol=https;AccountName=MYACCOUNTNAME;AccountKey=MYACCOUNTKEY" />-->
      </StorageProviders>
    <SeedNode Address="localhost" Port="11111" />
  </Globals>
  <Defaults>
    <Networking Address="localhost" Port="11111" />
    <ProxyingGateway Address="localhost" Port="30000" />
    <Tracing DefaultTraceLevel="Info" TraceToConsole="true" TraceToFile="{0}-{1}.log">
      <TraceLevelOverride LogPrefix="Application" TraceLevel="Info" />
    </Tracing>
    <Statistics MetricsTableWriteInterval="30s" PerfCounterWriteInterval="30s" LogWriteInterval="300s" WriteLogStatisticsToTable="true"/>
  </Defaults>
  <Override Node="Primary">
    <Networking Address="localhost" Port="11111" />
    <ProxyingGateway Address="localhost" Port="30000" />
  </Override>
</OrleansConfiguration>
```

**ClientConfiguration (also DevTestClientConfiguration)**
```
<?xml version="1.0" encoding="utf-8" ?>
<!-- 
	This is a sample client configuration file. 
	For a detailed reference, see "Orleans Configuration Reference.html".
-->
<ClientConfiguration xmlns="urn:orleans">
  <ConfigurationSettings>
    <Setting name="DataConnectionString" value="Data Source=(localdb)\MSSQLLocalDB;Database=TwitterTest;Integrated Security=True;Asynchronous Processing=True;Max Pool Size=200; MultipleActiveResultSets=True"/>
  </ConfigurationSettings>
  <GatewayProvider ProviderType="Config"/>
  <Gateway Address="localhost" Port="30000"/>
  <Statistics MetricsTableWriteInterval="30s" PerfCounterWriteInterval="30s" LogWriteInterval="300s" WriteLogStatisticsToTable="true"/>
</ClientConfiguration>
```

**Comment by SergVorontsov** [comment]
Why using record with very strange syntax (without coma between [ProxyPort] and [Generation] ) in ( [CreateOrleansTables_SqlServer.sql Line 1191] (https://github.com/dotnet/orleans/blob/master/src/OrleansProviders/SQLServer/CreateOrleansTables_SqlServer.sql#L1191)) ? :
```
SELECT
		[Address],
        [ProxyPort]
		[Generation]
      FROM
```

**Comment by veikkoeeva** [comment]
@SergVorontsov No reason at all. There is another one I know [here](https://github.com/dotnet/orleans/blob/master/src/OrleansProviders/SQLServer/CreateOrleansTables_SqlServer.sql#L110). Would you want to submit fix for this?

**Comment by SergVorontsov** [comment]
Understand. Fix you, please, if you can.

But now I am concerned by another trouble...
```
Exc level 0: System.AggregateException: 
   в System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   в System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   в System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   в Orleans.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout)
   в Orleans.Runtime.Silo.DoStart()
   в Orleans.Runtime.Silo.Start()
   в Orleans.Runtime.Host.SiloHost.StartOrleansSilo()
Exc level 1: System.Data.SqlClient.SqlException: Invalid column name 'Key'.
Invalid column name 'Query'.
   в System.Data.SqlClient.SqlCommand.<>c__DisplayClass16.<ExecuteDbDataReaderAsync>b__17(Task`1 result)
   в System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()
```
WTF and why ?

**Comment by veikkoeeva** [comment]
@SergVorontsov It appears to be that you have old binaries (e.g. 1.0.9 Nuget ones) but a database created with a newer script (possibly picked up straight from GitHub).

**Comment by SergVorontsov** [comment]
@veikkoeeva thanks a lot. After clone and rebuild latest master - all is "ok".
And special thanks at invitation to Gitter channel. Very interesting. :)
