### ISSUE TITLE
[Question] Grain independent GrainService

### ISSUE THREAD

**Issue by EshG** [dotnet/orleans#6436]
I have some code that sometimes query the database and sometimes fetch the data from other grains. I can best describe it as a multi-grain service. the closest thing I can find that is suitable for such application is a GrainService. the problem is that (as far as I can tell), I need to get a normal grain to access that service from the ClusterClient.

I think I can get this service to serve multiple requests simultaneously by getting a new grain for each request. but I'm not sure if this is a good practice or perhaps there's a better approach to this?

Thanks.

**Comment by JorgeCandeias** [comment]
Have you looked at [stateless workers](https://dotnet.github.io/orleans/Documentation/grains/stateless_worker_grains.html)?

A stateless worker is a local pool of grains of a given type, with as many instances in the pool as the number of processors on the given host (by default). Orleans will grow and shrink the pool for you as needed. Among other things, they work well for "repository"-like grains, whose only purpose is to simplify or organize access to other sources.

Calls to stateless workers always resolve locally, so they feel like calling `ISomeService`, except you enjoy Orleans' execution semantics within them. As a bonus, marking a stateless worker as `[Reentrant]` will allow full use of the CPU by a given pool, assuming you can handle reentrancy correctly in your use case.

I would recommend against approaches that activate a new grain for every single request, as this puts a heavy load on the grain directory.

**Comment by EshG** [comment]
Perfect, seems like this what I was missing. thanks a lot.
