### ISSUE TITLE
GC OnDeactivate timeout when calling > 1 other grains being GC'd at the same time

### ISSUE THREAD

**Issue by EdeMeijer** [dotnet/orleans#6437]
We've been running into an issue where a grain's `OnDeactivateAsync` failed because a call to another grain timed out. I have been able to reduce the issue to a simple repro:

- 1 instance of grain A gets called and thus activated, and calls 2 instances of grain B, also getting activated at roughly the same time.
- After some time of inactivity, Orleans GC deactivates all three acivations in the same tick.
- During the deactivation of grain A, it calls a function on the 2 instances of grain B being deactivated at the same time.
- One of those calls will succeed, while the other one will fail with a timed out `NewPlacementRequest` (which one succeeds is random, but it seems that when using more than 2 B instances, only one of the calls will in fact succeed).

It's important to note that if grain A only calls to 1 instance of grain B, no problems occur.

**Here's some code to reliably reproduce the issue**

`Foo.cs` (grain A from the description)
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Orleans;

namespace Bug
{
    public interface IFoo : IGrainWithGuidKey
    {
        Task TriggerAsync();
    }

    public class FooGrain : Grain, IFoo
    {
        private List<IBar> Bars;

        public override async Task OnActivateAsync()
        {
            var BarIds = new List<string> {"A", "B"}; // Remove "B" to make the bug disappear
            Bars = BarIds.Select(Id => GrainFactory.GetGrain<IBar>(Id)).ToList();
        }

        public async Task TriggerAsync()
        {
            // Activate the Bar grains at the same time, so that they get GC'd at the same time
            await Task.WhenAll(Bars.Select(Topic => Topic.SnozAsync()));
        }

        public override async Task OnDeactivateAsync()
        {
            Console.WriteLine("Deactivating foo grain");
            foreach (var Bar in Bars)
            {
                var BarId = Bar.GetPrimaryKeyString();
                try
                {
                    Console.WriteLine($"Snozzing bar {BarId}");
                    await Bar.SnozAsync();
                    Console.WriteLine($"Successfully snozzed bar {BarId}");
                }
                catch (Exception)
                {
                    Console.WriteLine($"Failed to snoz bar {BarId}");
                    throw;
                }
            }

            Console.WriteLine("Foo grain deactivated successfully");
        }
    }
}
```

`Bar.cs` (grain B from the description)
```c#
using System;
using System.Threading.Tasks;
using Orleans;

namespace Bug
{
    public interface IBar : IGrainWithStringKey
    {
        Task SnozAsync();
    }

    public class BarGrain : Grain, IBar
    {
        public override async Task OnActivateAsync()
        {
            Console.WriteLine($"Activating bar {this.GetPrimaryKeyString()}");
        }

        public override async Task OnDeactivateAsync()
        {
            Console.WriteLine($"Deactivating bar {this.GetPrimaryKeyString()}");
        }

        public async Task SnozAsync()
        {
            Console.WriteLine($"Snozzing bar {this.GetPrimaryKeyString()}");
        }
    }
}
```

Unless you want to wait for 2 hours to reproduce, configure the GC to collect inactive grains after a short while and check often. Also decrease the default response timeout of 30 seconds to make the issue appear a bit quicker (not required though).
```c#
SiloBuilder.Configure<SiloMessagingOptions>(Options =>
{
    Options.ResponseTimeout = TimeSpan.FromSeconds(5);
});
SiloBuilder.Configure<GrainCollectionOptions>(Options =>
{
    Options.CollectionQuantum = TimeSpan.FromSeconds(1);
    Options.CollectionAge = TimeSpan.FromSeconds(5);
});
```

In the orleans application, for example in a startup task, create an instance of Foo and trigger it
```c#
var Foo = GrainFactory.GetGrain<IFoo>(Guid.NewGuid());
await Foo.TriggerAsync();
```

When running this, I see the following console output (with Serilog logger configured)

```
Activating bar A
Activating bar B
Snozzing bar B
Snozzing bar A
Deactivating bar B
Deactivating bar A
Deactivating foo grain
Snozzing bar A
13:03:36.359 | WARN | T10 | Orleans.Runtime.CallbackData | Response did not arrive on time in 00:00:05 for message: Request S192.168.16.1:11111:323006602*grn/EA282091/b454baba@5ef5c3a7->S192.168.16.1:11111:323006602*grn/43AA04A2/00000000+A@8a7a31a2 #18: . Target History is: <S192.168.16.1:11111:323006602:*grn/43AA04A2/00000000+A:@8a7a31a2>. About to break its promise. 
Failed to snoz bar A
13:03:36.402 | EROR | T18 | Orleans.LifecycleSubject | Stopping lifecycle encountered an error at stage 2000. Continuing to stop. Exception: System.TimeoutException: Response did not arrive on time in 00:00:05 for message: Request S192.168.16.1:11111:323006602*grn/EA282091/b454baba@5ef5c3a7->S192.168.16.1:11111:323006602*grn/43AA04A2/00000000+A@8a7a31a2 #18: . Target History is: <S192.168.16.1:11111:323006602:*grn/43AA04A2/00000000+A:@8a7a31a2>.
   at Bug.FooGrain.OnDeactivateAsync() in /home/ede/repos/netwerkplek/Cloud/Cloud/Orleans/Repro/Foo.cs:line 39
   at Orleans.LifecycleSubject.<OnStop>g__CallOnStop|10_0(Int32 stage, OrderedObserver observer, CancellationToken cancellationToken)
   at Orleans.LifecycleSubject.OnStop(CancellationToken ct) 
13:03:36.414 | WARN | T15 | Microsoft.Orleans.Messaging | Dropping expired message NewPlacement Request S192.168.16.1:11111:323006602*grn/EA282091/b454baba@5ef5c3a7->S192.168.16.1:11111:323006602*grn/43AA04A2/00000000+A@76daf0b0 #18[ForwardCount=1]:  at phase Send 
```

![Screenshot from 2020-03-27 13-04-25](https://user-images.githubusercontent.com/5758565/77754390-91c91300-702b-11ea-9318-3a0bd297f1a7.png)

This is run on a test setup with a single silo and development clustering configured.

I hope someone can take a look at this and figure out what is going on here.

Thanks!

Edit: before submitting I saw some 'similar issues' suggested by Github, and this seems very much related to https://github.com/dotnet/orleans/issues/378. Maybe the fix introduced for that issue does not cover all possible cases?

**Comment by benjaminpetit** [comment]
> This is run on a test setup with a single silo and development clustering configured.

When a silo is shutting down, it will not accept new activation placement on itself. So if you run a cluster with only one silo and you shut it down, you will experience something like this is you do grain calls in the `OnDeactivateAsync`.

I would not be surprise if you could reproduce this in a multi silo cluster though. We have some issues with request forwarding that we are fixing. Could you test that with a recent version of Orleans with 2 silos?

**Comment by EdeMeijer** [comment]
It has nothing to do with silo shutdown, just activation garbage collection.

**Comment by EdeMeijer** [comment]
So it's been a while, any updates on this issue? We have a dirty workaround in production that randomizes deactivation time using `delayDeactivation` but that really is not a proper solution. If you need more information please let me know.

**Comment by benjaminpetit** [comment]
Sorry I let that slip. I think the issue is that all your grains were deactivated in the same batch, on the same silo. In previous versions, we were waiting for all batch to finish their `OnDeactivateAsync` calls before unregistering them from the directory and then forward the pending requests.

In your repro, I assume that foo was trying to enqueue a request on a grain that was pending unregistration/forwarding. Unregistration of this grain was pending completion of `OnDeactivateAsync` of foo...

I think we fixed this issue with the refactor of the grain directory. Could you try again using 3.3.0?

**Comment by EdeMeijer** [comment]
Thanks, I will try!

**Comment by EdeMeijer** [comment]
Okay, this seems to be fixed now, the just-deactivated grains get properly reactivated again and everything works fine.
