### ISSUE TITLE
Azure Devops fails build using windows 2019 Hosted, works with vs2017-win2016 hosted. Missing master.dacpac

### ISSUE THREAD

**Issue by noxidjkram** [dotnet/orleans#6438]
I'm using VS2017 for my database projects. All build fine locally when referencing the master database (master.dacpac). 

Azure Devops fails build using windows-2019 Hosted agent, but works with vs2017-win2016 hosted agent. 

The error message indicates that the master.dacpac is missing.

Build error SQL72027: File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\master.dacpac" does not exist.

I believe the WIndows-2019 agent requires update to include this file.

Anyone have any idea how to get this actioned?

Thanks in advance.

M

**Comment by ReubenBond** [comment]
Is this about Orleans?

**Comment by noxidjkram** [comment]
Likely not. I'm new here, and seem to have posted in the wrong place.
