### ISSUE TITLE
Documentation: "What's new in Orleans" - v1.0.9 SDK links to v1.0.8

### ISSUE THREAD

**Issue by rsir** [dotnet/orleans#644]
Hi,

I tried to download the v1.0.9 Orleans SDK from link provided at http://dotnet.github.io/orleans/What's-new-in-Orleans (see the attached picture). However, the installer turned out to be for version 1.0.8, which is in fact what the link points to. 

![image](https://cloud.githubusercontent.com/assets/13479723/8869266/0651e5fe-31e2-11e5-8529-5e62cc784c9b.png)

**Comment by sergeybykov** [comment]
Thank you! Fixed.
