### ISSUE TITLE
Some questions about orleans

### ISSUE THREAD

**Issue by huiali** [dotnet/orleans#6443]
# Question 1

I want to try to use the advantages of Orleans as a distributed ID solution. Is it applicable to the production environment with large amount of data? How to design better?

    `public class SerialNumber : Grain, ISerialNumber
    {
        private const int MaxSeed = 99999;
        private int _seed = 0;
        private int _currentSecondCounter = 0;
        Task<Immutable<string>> ISerialNumber.Next()
        {
            var oldCounter = this._currentSecondCounter;

            while (true)
            {
                this.UpdateCurrentTimestamp();

                if (oldCounter != this._currentSecondCounter)
                    this._seed = 1;
                else
                {
                    ++this._seed;
                }

                if (this._seed > MaxSeed) Task.Delay(100);
                else break;
            }

            var seq = DateTime.Now.ToString("yyyyMMdd") + this._currentSecondCounter.ToString() + this._seed.ToString();
            return Task.FromResult($"{this.RuntimeIdentity}->SEND：{seq}".AsImmutable());
        }

         private void UpdateCurrentTimestamp()
        {
            var currentTime = DateTime.Now;
            var currentDayStart = Convert.ToDateTime(currentTime.ToShortDateString());
            this._currentSecondCounter = (int)(new TimeSpan(currentTime.Ticks - currentDayStart.Ticks).TotalSeconds);
        }`

# Question 2

I tried to use docker to deploy on CentOS 7+. The registration center used is: consul, but I found that no matter how I set it, the retrieved address is always the IP address inside the container. How can I solve this problem? using netcore 3.1

## Silo
                 silo = new SiloHostBuilder()
                .Configure<ClusterOptions>(options =>
                {
                    options.ClusterId = "docker-cluster";
                    options.ServiceId = "SerialNumber";
                })
                .UseConsulClustering(gatewayOptions =>
                        {
                            gatewayOptions.Address = new Uri("http://xxxxx:8550");
                            gatewayOptions.KvRootFolder = "cluster";
                        })
                .ConfigureEndpoints(Dns.GetHostName(), 11112, 30000)
                .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(SerialNumber).Assembly).WithReferences())
                .ConfigureLogging(builder => builder.SetMinimumLevel(LogLevel.Warning).AddConsole())
                .UseDashboard(options => { options.Port = 8090; })
                .Build();
            Task.Run(StartSilo);

            Console.CancelKeyPress += (sender, e) =>
            {
                Task.Run(StopSilo);
                siloStopped.WaitOne();
            };

            AppDomain.CurrentDomain.ProcessExit += (s, e) =>
            {
                Task.Run(StopSilo);
                siloStopped.WaitOne();
            };

            siloStopped.WaitOne();`
## dockerfile
           `FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
            WORKDIR /src

            EXPOSE 8090
            EXPOSE 11112
            EXPOSE 30000

           COPY ["Silo/Silo.csproj", "Silo/"]
           COPY ["Interface/Interface.csproj", "Interface/"]
           COPY ["Grains/Grains.csproj", "Grains/"]
           RUN dotnet restore "Silo/Silo.csproj"

           COPY . .
           RUN dotnet publish "Silo/Silo.csproj" -c release -o /app --no-restore

           FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim
           WORKDIR /app
           COPY --from=build /app .
           ENTRYPOINT ["dotnet", "Silo.dll"]`

**Comment by benjaminpetit** [comment]
> Question 1

I am not sure to understand correctly your application here. I see that you are doing a `Task.Delay` but you don't `await` it, and I am not sure why you need that.

> Question 2

Does your client(s) and silo(s) live on the same docker network? Do you plan to use just docker on one host, or something like K8s or swarm?

It's better if your clients and silos are on the same network. Using the host IP with port forwarding can work, but will add a lot of complexity, I don't recommend it, especially for silos.
