### ISSUE TITLE
Reoccuring "Connection reset by peer" warnings

### ISSUE THREAD

**Issue by oleggolovkovuss** [dotnet/orleans#6445]
1. I keep getting dozens of this messages in logs however the system seems to be doing fine.
There is not much additional info on it: the stack trace begins with 
`Orleans.Runtime.Messaging.Connection.ProcessIncoming()` and dives into `Pipelines` implementations where it eventually gets

> Exception while processing messages from remote endpoint "10.0.31.99:33694": "Microsoft.AspNetCore.Connections.ConnectionResetException: Connection reset by peer

I get about 1-2 of these messages per minute on each silo. Looks like it's retrying something (not important? bcause the log level is `Warning`, not `Error`?) and can't figure out that it should stop? It lasts for days/weeks and sometime persists through reboot.

2. I also started to get this `Error` periodically which I think I haven't seen before

> CleanupDefunctSiloEntries operation is not supported by the current implementation of IMembershipTable. Disabling the timer now.

which I don't quite understand: if it's not supported but the system can live without it this should be a `Warning`? And if not this should be `Fatal`?

My config:
ASP.NET Core 3.1
Orleans 3.1.4
ADO.NET clustering (MySQL)
3 silos

**Comment by sergeybykov** [comment]
>Exception while processing messages from remote endpoint "10.0.31.99:33694": "Microsoft.AspNetCore.Connections.ConnectionResetException: Connection reset by peer

Is 10.0.31.99 IP address of one of the silos?

>which I don't quite understand: if it's not supported but the system can live without it this should be a Warning? And if not this should be Fatal?

This is a warning that the ADO.NET clustering provider doesn't currently support cleanup of the membership table. If you use a different provider that support that functionality, the runtime will stop generating this warning. The cleanup functionality was added as optional, so that existing providers wouldn't get suddenly broken.

**Comment by oleggolovkovuss** [comment]
> Is 10.0.31.99 IP address of one of the silos?

Yes it is, I get this warning  from other silos as well

> This is a warning that the ADO.NET clustering

Yes, the question is why is this `warning` logged with level `Error` ? Should I do something about it? Like implement my own cleanup or move to other "recommended" (are there any?) provider?

**Comment by sergeybykov** [comment]
>Yes, the question is why is this warning logged with level Error ? Should I do something about it? Like implement my own cleanup or move to other "recommended" (are there any?) provider?

You are right. I didn't realize we were logging it as an error. I submitted #6447 for that.

>Yes it is, I get this warning from other silos as well

This is strange. What deployment/networking environment do you run these silos in?

**Comment by oleggolovkovuss** [comment]
I'm using a rather standard `docker swarm` setup with 6 Ubuntu VMs (3 of those are running an ASP.NET Core container with Orleans silo in it) on my private Linux server.

I'm no longer getting this warning after one of the redeployments. I think I'll post additional info or open another issue if I get it happening again and more info

**Comment by sergeybykov** [comment]
Good. Can we close this one?
