### ISSUE TITLE
AzureSilo Start method breaking change in 1.0.9

### ISSUE THREAD

**Issue by ellern** [dotnet/orleans#645]
I used to have the following code in a WorkerRole:

    _azureSilo = new AzureSilo();
    _azureSilo.Start(RoleEnvironment.DeploymentId, RoleEnvironment.CurrentRoleInstance, clusterConfiguration);
    _azureSilo.Run();

After upgrading to 1.0.9 the `Start` method only accepts 1 parameter, a `ClusterConfiguration` parameter, I used to supply a `DeploymentId` and `CurrentRoleInstance`.

If I change to `Start(clusterConfiguration)` would I then need to somehow supply the `DeploymentId` or `CurrentRoleInstance` some other way?

**Comment by veikkoeeva** [comment]
@ellern It has been readded, see https://github.com/dotnet/orleans/pull/629.
