### ISSUE TITLE
Broken doc link to grain_placement.html 

### ISSUE THREAD

**Issue by lovettchris** [dotnet/orleans#6451]
http://dotnet.github.io/orleans/Documentation/index.html

Expand "Grains" and try and click on "Grain Placement", the TOC link doesn't work, but the page does exist here: https://dotnet.github.io/orleans/Documentation/grains/grain_placement.html

**Comment by sergeybykov** [comment]
Fixed. Thank you, @lovettchris!

**Comment by lovettchris** [comment]
wow that was quick :-)
