### ISSUE TITLE
IClusterClient missing when using Shared Host resulting in no GetStreamProvider implementation

### ISSUE THREAD

**Issue by fuocor** [dotnet/orleans#6466]
The ```IClusterClient``` interface is not in the service provider when using the Orleans shared host.
Without it there is no implementation of ```GetStreamProvider``` for anything on the Web side.

**Comment by ReubenBond** [comment]
Please provide more information

**Comment by fuocor** [comment]
Sorry, My bad. I was looking at the wrong service provider
