### ISSUE TITLE
Orleans generating non-deterministic class names

### ISSUE THREAD

**Issue by stan-sz** [dotnet/orleans#6495]
When building code with /p:[Deterministic](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/deterministic-compiler-option)=true, we expect that code generated by Orleans would also produce the same outputs for the same inputs. While Orleans does support incremental builds (avoid running code gen when inputs have not changed), still invoking generator for the same inputs (e.g. in two clean builds) will produce slightly different assemblies. This is mostly due to the use of `Guid.NewGuid()` in:

* https://github.com/dotnet/orleans/blob/ffabe550a7891e7378f9f076e88a8e3c184d967f/src/Orleans.CodeGeneration/FeaturePopulatorGenerator.cs#L23
* https://github.com/dotnet/orleans/blob/ffabe550a7891e7378f9f076e88a8e3c184d967f/src/Orleans.CodeGenerator/Generators/FeaturePopulatorGenerator.cs#L23

Can the generated code adhere to the [Deterministic](https://blog.paranoidcoding.com/2016/04/05/deterministic-builds-in-roslyn.html) mode?

**Comment by ReubenBond** [comment]
Hi @stan-sz, would you be willing to submit a PR? I'm in favor of making these deterministic, too.

**Comment by stan-sz** [comment]
Let me first kindly include and ask @KirillOsenkov and @gafter for any inputs what's the best strategy for codegen-tools to inherently obey the deterministic rules. Thanks in advance.

The top-of-my head idea would be to hash the inputs to the method(s) and pass it as hash to a `new Guid(...)`. Another approach, if the deterministic build property can be retrieved, use a constant Guid. I'm open for other ideas.

**Comment by ReubenBond** [comment]
It could also use the assembly name, instead, maybe sanitizing it if needed. Alternatively, hash it.

**Comment by KirillOsenkov** [comment]
Yup, you guys got it right. Hashing inputs is fine. As long as there is no randomness and no other inputs like current time or local machine state.

**Comment by rikbosch** [comment]
@ReubenBond I took the liberty to create the PR to support deterministic builds because we have a need for it internally.
