### ISSUE TITLE
Return type of IAsyncEnumerable

### ISSUE THREAD

**Issue by arinn1204** [dotnet/orleans#6504]
Are there any plans to allow grains to return IAsyncEnumerable<T>? Or is it going to be needed to have a Task<IAsyncEnumerable<T>> for the future?

**Comment by ReubenBond** [comment]
There are no firm plans to support it yet, but I would love to see it, as long as the semantics are well-defined.

There was previously a WIP PR for doing something similar, but with IAsyncObservable instead of IAsyncEnumerable: #1916

**Comment by ElanHasson** [comment]
Looking forward to this one :)

**Comment by jbockle** [comment]
same!

**Comment by danielleiszen** [comment]
Thank you guys. This would be awesome!  What is the best practice for this scenario for the time being though?

**Comment by ReubenBond** [comment]
This is supported now, since Orleans v7.2.0
