### ISSUE TITLE
Place grain into the same silo as the grain it was referenced from

### ISSUE THREAD

**Issue by andreasinpb** [dotnet/orleans#6511]
Hi,
i am trying to implement a same silo placement strategy to minimize inter-silo communication. It should work as follows: I have a GrainA which is resolved from a client. GrainA has a method called GetGrainB(long key).
Now the client calls this method to obtain a GrainB reference. The strategy should place the new GrainB instance on the silo of the "calling" GrainA instance. I implemented the strategy and the corresponding director, whose OnAddActivation is called:

        {
            var compatibleSilos = context.GetCompatibleSilos(target);

            // If the current silo is not shutting down, place locally if we are compatible
            if (!context.LocalSiloStatus.IsTerminating())
            {
                foreach (var silo in compatibleSilos)
                {
                    if (silo.Equals(context.LocalSilo))
                    {
                        this._logger.Info("Placing local: {0}", target.GrainIdentity);
                        return Task.FromResult(context.LocalSilo);
                    }
                }
            }

            // otherwise, place somewhere else
            this._logger.Warn(101, "Placing random: {0}", target.GrainIdentity);
            return Task.FromResult(compatibleSilos[SameSiloPlacementDirector.Random.Next(compatibleSilos.Count)]);
        }

Now my problem is that the context does not always reflect the silo of the GrainA instance. Sometimes the context´s local silo is a completely different silo and hence GrainB gets placed on a different silo than GrainA.
Am I doing something wrong here? Is the context not supposed to be the "calling" instance´s silo?

Thanks in advance for any help :),
Andreas

**Comment by JorgeCandeias** [comment]
Is there anything stopping you from using the built-in `[PreferLocalPlacement]` strategy on `GrainB`?

**Comment by andreasinpb** [comment]
No, actually I overlooked the built-ins. But using `[PreferLocalPlacement]` results in the same behaviour. Though my setup is really simple so far (LocalHostClustering or TestCluster with 5 silos and only a few active grains), GrainB is still placed into a different silo.

**Comment by JorgeCandeias** [comment]
What do you mean by a significant number of tries? What is the exact setup of the grains, could you show them? Is GrainA a regular grain or a stateless worker? Is the client calling using the same key while calling GrainA or different keys? What about GrainB, same questions.

`[PreferLocalPlacement]` will attempt to place it in the silo of the first call that makes it activate. However further calls to the same instance, even coming from different silos, will be directed at the existing activate instance, until it eventually deactivates. Could this be causing confusion in your testing?

**Comment by andreasinpb** [comment]
GrainA looks like this:

    public class GrainA: Grain, IGrainA
    {
        /// <inheritdoc />
        public Task<IGrainB> GetGrainB(int key)
        {
            return Task.FromResult(this.GrainFactory.GetGrain<IGrainB>(key));
        }

    }

GrainB:

    [SameSiloPlacementStrategy] // or [PreferLocalPlacement]
    public class GrainB: Grain, IGrainB
    {

        /// <inheritdoc />
        public Task<bool> DoSomething()
        {
            return Task.FromResult(true);
            // ...implement
        }
    }

Test setup:

        [OneTimeSetUp]
        public async Task Setup()
        {
            var builder = new TestClusterBuilder();
            builder.Options.ServiceId = "test-dev";
            builder.Options.ClusterId = "Backend";
            builder.Options.BaseGatewayPort = 30000;
            builder.AddSiloBuilderConfigurator<TestSiloConfigurations>();
            var cluster = builder.Build();
            this._cluster = cluster;
            this._cluster.Deploy();
            await this._cluster.StartAdditionalSilosAsync(3);
        }

Calling GrainA.DoSomething from testcode:

            // Act
            var grainA = this._cluster.GrainFactory.GetGrain<IGrainA>(123);
            IGrainB grainB = await grainA.GetGrainB(123);
            // force activation
            bool validated = await grainB.DoSomething();

Significant means around 50 % or so.

**Comment by JorgeCandeias** [comment]
In this code
```csharp
    public Task<IGrainB> GetGrainB(int key)
    {
        return Task.FromResult(this.GrainFactory.GetGrain<IGrainB>(key));
    }
```
will not activate `GrainB` at all. "Getting" a grain simply returns a smart proxy to it (a typed grain reference), nothing more. It's only an abstraction describing the identity of grain and a few other odd bits, and creating one has no side-effects in the cluster. Returning a grain reference in a method will serialize that reference and deliver it to the caller. When the caller caller calls `DoSomething()`, only then will Orleans attempt to locate `GrainB` and activate it if necessary. If the grain has `[PreferLocalPlacement]` then this activation happens in the silo of that caller, or if calling via a client, in the gateway silo that it hits, which is random.

If you need `GrainB` to activate in the same silo of `GrainA` then you need to make a call from `GrainA` itself, e.g.:

```csharp
public class GrainA: Grain, IGrainA
{
    /// <inheritdoc />
    public Task DoSomethingOnGrainB(int key)
    {
        return GrainFactory

        // this has no side-effects, it's a cheap local call to create a reference
        .GetGrain<IGrainB>(key)

        // this sends a message to the grain, inducing activation if needed
        .DoSomething();
    }
}
```

**Comment by andreasinpb** [comment]
Thank you very much, this resolves my problem. Much appreciated!
