### ISSUE TITLE
How do you get started with .Net Core 3.1 and Orleans?

### ISSUE THREAD

**Issue by keithn** [dotnet/orleans#6514]
All the documentation seems out of date and the examples don't seem to work

There's some samples on github, but they go off and do different things than a "getting started" would.  

eg, for some weird reason the hello world sample initializes azure stuff..... why? I don't want to use azure and seems odd for a hello world sample to have a dependency on a cloud service when it doesn't need to?

**Comment by ThiagoT1** [comment]
This is a great place to start:
https://github.com/dotnet/orleans/tree/master/Samples/OneBoxDeployment

**Comment by orangeagain** [comment]
my temp solution is //azure code, it works
