### ISSUE TITLE
converting legacy code from Task.Run, to execute on Orleans Scheduler 

### ISSUE THREAD

**Issue by peter-maude** [dotnet/orleans#6515]
Hi,

We have some legacy code, that we have wrapped into grains. In that code there are a fair few tasks started with Task.Run

Question is, should we aim to convert them to run on the orleans scheduler, and if so , why ?

That code, is not blocking, or long running, all IO is async etc.

- It does not mutate grain state.
- It does not need to communicate to other grains
- It will not affect turn based concurrency issues.

I know those are the main issues, you would not want to Task.Run, are there other reasons for avoiding task.run, and moving to the orleans scheduler ?

Thanks

**Comment by ReubenBond** [comment]
It should be fine to leave it as-is, given the points you mentioned.

**Comment by ThiagoT1** [comment]
What if code like that mutated grain state?

**Comment by ReubenBond** [comment]
Then no, not unless you can mutate it in a thread-safe manner.
Additionally, if you want to persist the state, that must be performed in the context of the grain (not in Task.Run).
