### ISSUE TITLE
PublicKeyToken for Orleans seems to be missing...

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/orleans#6519]
Hi,

I was surprised to learn that Orleans assemblies appear to be unsigned, e.g. there was no `PublicKeyToken` for `Orleans.Core`. Are the assemblies supposed to be signed by Orleans team?

Thanks,
//Jan

**Comment by ReubenBond** [comment]
The assemblies are signed, but not strong-named:
![image](https://user-images.githubusercontent.com/203839/81004103-bb324700-8e00-11ea-8ff1-08b6e6fb3527.png)

Note from the [Strong-naming docs](https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named):

> Do not rely on strong names for security. They provide a unique identity only.

**Comment by jan-johansson-mr** [comment]
Thanks Reuben 👍
