### ISSUE TITLE
Behaviour of yield return of enumerables in Grain methods

### ISSUE THREAD

**Issue by srivathsah** [dotnet/orleans#6526]
I have a method in my domain logic library like so
`protected virtual IEnumerable<TEvent> YieldBusinessEvents(TState state)`
        `{`
            `yield return GetEvent(state);`
        `}`

This method is invoked in a grain method and the stream is materialised using a foreach
`foreach (var @event in agg.YieldBusinessEvents(state))`
                `{`
                    `doSomething`
                `}`

What is strange is when the grain client is invoking a grain method and when the result of the invocation is returned to the client side, the deserialization is expecting the domain library to be referenced in the client side which is not required, and also if I reference the domain library, it is throwing **Referred object without a reference**  exception. When I change the yield return to a List, everything is fine. Is this the expected behaviour ? I was not able to get much help from the docs or other posts on Enumerable streams in grains.

**Comment by ReubenBond** [comment]
What does your grain methods signature look like?

**Comment by srivathsah** [comment]
`public virtual async Task<Immutable<DomainCommandResult>> Execute(Immutable<TCommand> command)`

DomainCommandResult contains the IEnumerable property

**Comment by ReubenBond** [comment]
The implementation of your IEnumerable is not serializable - it's the C# generated state machine for your yielding method. That's why the client needs your library to be able to deserialize it.

What is the expected behavior in this case? Would it be for Orleans to try to identify unknown IEnumerables and enumerate them into lists?

**Comment by srivathsah** [comment]
@ReubenBond  Thanks for the response, I am really not sure what the best solution would be, the minimum we can do (not really a solution) is the docs showing this scenario as something that needs to be taken care of, like how the Task related caveats are explicitly mentioned in many places. Having said that, I am actually curious to see how asp net core handles this, as we all know the controller end points can return (serialize) models with IEnumerable properties without any issues. I think it serializes all IEnumerable<T> to Array<T>
