### ISSUE TITLE
UnboundedChannelWriter seems to max out available connections

### ISSUE THREAD

**Issue by kristofferlindvall** [dotnet/orleans#6533]
We're running our silo on Linux, with a pretty low ulimit (due to our hosting provider).

The behavior we seem to experience after many hours of debugging and analyzing is that we are running out of connections. I've done some digging and I noticed that Orleans uses UnboundedChannelWriter (as set up in Orleans.Core.Networking.Connection.cs line 24).

The problem we experience when we run out of connections is that the whole silo basically grinds to a halt.

What is the rationale behind using UnboundedChannelWriter as opposed to BoundedChannelWriter?

If I was able to pass in a BoundedChannelOptions.Capacity and FullMode = BoundedChannelFullMode.Wait as Orleans config I think I would be able to work around the problem, with a small performance hit. But I'd rather have delayed silo-to-silo messaging than the whole silo stop dead in it's tracks.

**Comment by kristofferlindvall** [comment]
This is likely the root cause for these issues as well: #6527 and #6529

**Comment by ReubenBond** [comment]
I think I'm not quite understanding the relationship between the channel (i.e, queue of messages to send) and the number of connections. Connections aren't created on a per-message basis, there should be a relatively small, fixed number of connections.

**Comment by kristofferlindvall** [comment]
I'm not too familiar with how the ChannelWriter works under the hood apart from what I've been able to decipher from the code itself, but it seems that it does allow parallel writes. Not sure if it has some internal limit. But the setup where we experience the problem the ulimit is ~1000 while we're having about 100k grains that are quite chatty in the cluster.

Running on a different machine where ulimit is higher, or running a single-node cluster on the same machine does not yield the same problem.

**Comment by ReubenBond** [comment]
Parallel writes into an in-memory queue, not parallel in terms of network IO. Messages are interleaved over a small number of sockets.

Which ulimit value is set to 1000 / which resource is restricted?

Apologies for the questions, I'm still trying to understand how to improve the experience for you.

How did you determine that socket I/O is the issue, what diagnostics did you use?

**Comment by kristofferlindvall** [comment]
I see.

We haven't been able to produce any hard proof unfortunately. We can only infer that the only plausable explanation we have at the moment is that when there's too much concurrent messaging between silos suddenly everything stops. And it seems to correlate with ulimit and number of silos in the cluster.

It doesn't look like a resource issue as the memory and cpu is not showing any significant load, and our timing measurements are showing a steady pace all up until it hit a brick-wall and most messages starts timing out. Once everything cools down and the communication starts it works again (without any silo restart) only to soon hit the wall again.

We have also seen that our external web api has had problem connecting during these instances, which lead us to believe it's definitely network related.

Do you have any suggestion on how we can further pinpoint where the actual problem is?

**Comment by yevhen** [comment]
@kristofferlindvall What kind of work you do inside silo? I've seen a similar situation when a lot of IO operations were run in a parallel. It has nothing to do with Orleans.

**Comment by kristofferlindvall** [comment]
Mostly updating grain state and pushing events to streams. Could it be the AzureBlobGrainStorage or AzureEventHubs streams that overflows the network, having the side-effect that Orleans can't communicate properly anymore?

**Comment by ReubenBond** [comment]
Have you seen this, @kristofferlindvall? https://github.com/jnoller/kubernaughty/blob/master/docs/part1-introduction-and-problem-description.md

The series of posts is about Azure Kubernetes Service, but it may well apply to any Linux environment where resource limits are set. I don't know if/how ulimit/setrlimit and cgroup limits would differ in terms of behavior, though.

What's the output of `ulimit -a`? I assume this is running on a VM/metal and not in a container.

**Comment by kristofferlindvall** [comment]
It seems this problem was indeed caused by a deadlock due to our misunderstanding of the task scheduler and call chain. Since we sorted that out Orleans is performing brilliantly.

**Comment by ReubenBond** [comment]
Glad to hear it, @kristofferlindvall
