### ISSUE TITLE
Deployment/Multi-Cluster documentation is not available from the main documentation

### ISSUE THREAD

**Issue by logiclabs** [dotnet/orleans#6548]
The hosted documentation does not link to the deployment or multi-cluster documentation here: 
https://dotnet.github.io/orleans/Documentation/deployment/

Submitted a PR #6547 to fix invalid toc.yml

**Comment by ReubenBond** [comment]
Multi-clustering has been removed. We may consider re-introducing it in the future if we arrive at a design/implementation which we are comfortable with, comfortable maintaining, and if the need is apparent
