### ISSUE TITLE
await on System.Threading.Tasks.Task is throwing System.TimeoutException

### ISSUE THREAD

**Issue by jyothivedurada** [dotnet/orleans#6551]
Hi Orleans team,

I have added the following highlighted two lines to the Deposit() method of the existing TestGrains.AccountGrain class and trying to run Tester.EventSourcingTests.AccountGrainTests.AccountWithoutLog test.

        public Task Deposit(uint amount, Guid guid, string description)
        {
            **Task t = addDelay();
            t.Wait();**
            RaiseEvent(new DepositTransaction() {
                Guid = guid,
                IssueTime = DateTime.UtcNow,
                DepositAmount = amount,
                Description = description
            });

            // we wait for storage ack
            return ConfirmEvents();
        }
        private async Task addDelay()
        {
            await Task.Run(() => {
                int cnt = 0;
                for (int m = 0; m < 1000; m++)
                {
                    cnt += m;
                }
                Console.WriteLine("The cnt value is: " + cnt);
            });
            Console.WriteLine("After the delay in addDelay() ");
        }

I am getting the following error message.
    System.TimeoutException : Response did not arrive on time in 00:00:30 for message: Request sys.client/5acd9557ebd546f787791fff4cb876a4@fb5c7cb1->S127.0.0.1:44561:0sys.grain.v1.06FFFFFFDD9BA720/00000000000000000000000000000000+Account-d7f1eefc-315f-475c-8958-138f8f3a81a9 #47. Target History is: <S127.0.0.1:44561:0:sys.grain.v1.06FFFFFFDD9BA720/00000000000000000000000000000000+Account-d7f1eefc-315f-475c-8958-138f8f3a81a9:>.
  Stack Trace: 
    AccountGrainTests.TestSequence(IAccountGrain account, Boolean hasLogStored) line 28
    AccountGrainTests.AccountWithoutLog() line 74
        
Could you please throw some light on this.

**Comment by ReubenBond** [comment]
You should never use Task.Wait or any other blocking operation unless you are absolutely certain that it's safe. In this case, it will cause a deadlock because grains are single threaded, but your task requires another thread to complete (since the main one is blocked). You should also generally avoid Task.Run and Console.WriteLine from within grain code.

Task.Run executes code outside of the grain's context and Console.WriteLine will cause performance issues under load

**Comment by jyothivedurada** [comment]
Thanks for your quick reply, Reuben. Its helpful.

**Comment by sergeybykov** [comment]
@jyothivedurada, can we close this?

**Comment by jyothivedurada** [comment]
> @jyothivedurada, can we close this?

Please do.
