### ISSUE TITLE
Use of streams

### ISSUE THREAD

**Issue by GaLeGayGay** [dotnet/orleans#6554]
I am new to the server, and I am watching Orleans Streams. I have a question, should I create a ClusterClient when the front-end server receives a Socket connection. Use this ClusterClient to listen to the stream and send the received stream to Front-end server. Then sent from the front-end server to the client?

**Comment by sergeybykov** [comment]
Yes, `ClusterClient` is what is used by frontend servers for communicating with a cluster of silos. One of the options for receiving notification on the frontends is to use streams (more reliable). Another option is observers (best effort). Frontend servers then forward the notification to the clients connected to them.

**Comment by GaLeGayGay** [comment]
Hello, @sergeybykov which means that every time a player connects to my front-end server, I need to establish an independent ClusterClient for him. I am now testing. I created 10,000 ClusterClient in the loop in one go and the error occurred at the 700-1500.
![QQ图片20200602102022](https://user-images.githubusercontent.com/8246779/83472913-f173ec80-a4ba-11ea-8532-a5da7139ed70.png)
![QQ图片20200602102010](https://user-images.githubusercontent.com/8246779/83472918-f5077380-a4ba-11ea-8ecd-64f0b007a5d5.png)
![QQ图片20200602101938](https://user-images.githubusercontent.com/8246779/83472923-f769cd80-a4ba-11ea-8aad-cd435cdf9d7c.png)

**Comment by sergeybykov** [comment]
>Hello, @sergeybykov which means that every time a player connects to my front-end server, I need to establish an independent ClusterClient for him.

No, a single `ClusterClient` instance is enough (and better) for communicating with the cluster of behalf of all clients connected to the frontend.
