### ISSUE TITLE
Reminder Can it be used in large quantities?

### ISSUE THREAD

**Issue by Cloud33** [dotnet/orleans#6555]
Hi, Great project，I have two questions about reminders:

1.Whether Reminder is ready to be used in large numbers, this number may exceed a million Is this being used correctly? Will it have a negative effect? what are the suggestions of Orleans. I do this to monitor whether the running state of each `grains` is normal, and if it is abnormal, use `Reminder` to recover.

2.In the case of a **split brain**,Remind it of what it will behave？
Don't go outside I find out,The description of the brain split has been removed,What happened in https://github.com/dotnet/orleans/pull/6065

**Comment by Cloud33** [comment]
thank.
1.If there are a large number of single type of `grain` reminders, are they the same? Will the loading of the reminder be affected during `silo` initialization because there will be a large amount of data to be loaded.

For example, I have an A  `grain` ，`A`  grain may have millions of reminders about whether this situation will affect `Orleans`

**Comment by sergeybykov** [comment]
>If there are a large number of single type of grain reminders, are they the same?

Each reminder is stored as a separate record.

>Will the loading of the reminder be affected during silo initialization because there will be a large amount of data to be loaded.

It will take time to load reminder data, but that it done asynchronously, without blocking the rest of the silo initialization.

>For example, I have an A grain ，A grain may have millions of reminders

By "grain" do you mean a grain type (class)? And millions of reminders - are they for different grains (instances of the grain class with different keys)?

What do you need millions of reminders for?

**Comment by Cloud33** [comment]
instances of the grain class with different keys ，An instance has only one reminder, but it belongs to the same type of grain. What is the impact of this?

**Comment by sergeybykov** [comment]
Then you should be fine. Reminders should scale to millions easily.

**Comment by Cloud33** [comment]
Thank you for your answer.
