### ISSUE TITLE
[Question] Regarding cancel operation in StatelessWorker grain

### ISSUE THREAD

**Issue by steven22tom** [dotnet/orleans#6558]
I am looking for a solution to cancel an executing operation in **StatelessWorker** grain.
I tried **GrainCancellationToken**, but it didn't work, and i got an exception when i executed **Cancel** method.
Exception:
Extension not installed on grain CustomGrain.CancelGrain attempting to invoke type Orleans.Runtime.OrleansCodeGenCancellationSourcesExtensionMethodInvoker from invokable Orleans.Runtime.ActivationData

**Comment by sergeybykov** [comment]
Are you invoking the Cancel operation from within the same silo? I assume you are.

Is the grain class marked as `[StatelessWorker(1)]`? Otherwise, the cancellation request may be routed to a different activation of the grain.

Can you share your repro code?

**Comment by steven22tom** [comment]
@sergeybykov Yes of course, When I marked the grain class as `[StatelessWorker(1)]`, it could be canceled. But in fact, I have not only one grain in the same silo

**Comment by sergeybykov** [comment]
Without `[StatelessWorker(1)]` calls are routed to different activations of the grain. So that behavior is by design. You can still have multiple grains in the silo, they would just need to have different IDs.

**Comment by steven22tom** [comment]
@sergeybykov I use `[StateleseWorker]` grain because of the function of automatically scaling up and down. Otherwise, I need to create a management tool by myself as a grain pool to manage those grains with different IDs.

**Comment by sergeybykov** [comment]
Note that for each stream an event or a batch of events will be delivered one at a time. So, you won't get any parallelism within the scope of a stream.

**Comment by sergeybykov** [comment]
Please disregard my last comment. Your question has nothing to do with streams.

Individual activations of a `[StateleseWorker]` aren't directly addressable. So you can't deliver to a specific one. A grain pool is indeed the next option to consider. Unless those grains keep a lot of state in memory, it's relatively cheap to keep a number of grains (instead of one) in memory the whole time.

**Comment by steven22tom** [comment]
Well, It's seem that creating a grain pool mey be the solution to my problem at present

**Comment by sergeybykov** [comment]
Can we close this issue then?

**Comment by steven22tom** [comment]
@sergeybykov OK......
