### ISSUE TITLE
orleans configurable via IConfiguration

### ISSUE THREAD

**Issue by jason-bragg** [dotnet/orleans#6565]
Orleans uses Options and I Configuration but doesn't link the two.  Out of the box a silo cannot be directly configured a IConfigurable source (say json) without developers writing custom conversion code (read from IConfig, then set options) to do so, which should not be necessary as options can be initialized from IConfig.  The reason for this is that the various configuration hooks and extension functions do not take configuration sources as the underlying options calls do.

For instance, instead of just having:

        public static ISiloBuilder Configure<TOptions>(this ISiloBuilder builder, Action<TOptions> configureOptions) where TOptions : class
        {
            return builder.ConfigureServices(services => services.Configure(configureOptions));
        }

Which requires and action be written by the developer, wherein they must set the option values, if there were also overrides for reading from I config.. something like:

        public static ISiloBuilder Configure<TOptions>(this ISiloBuilder builder, IConfigurationSection section) where TOptions : class
        {
            return builder.ConfigureServices(services => services.Configure<TOptions>(section));
        }

and/or

        public static ISiloBuilder Configure<TOptions>(this ISiloBuilder builder, IConfigurationRoot configurationRoot) where TOptions : class
        {
            return builder.ConfigureServices(services => services.Configure<TOptions>(configurationRoot.GetSection(typeof(TOptions).Name)));
        }

Then using Orleans with IConfiguration (the expected pattern) would be much simpler and cleaner.

Note: The above examples are half baked at best.  Please consider before settling on a general pattern.

**Comment by SebastianStehle** [comment]
Is this really needed? No other Microsoft library supports this afaik.

And you can very easily implement it yourself like this...

```
builder.AddAzureMonitorTraceExporter(options =>
{
    config.GetSection("logging:applicationInsights").Bind(options);
});
```

It is from Open Telemetry but it is the idea that matters ;)
