### ISSUE TITLE
Is there a missing document for reminder persistence?

### ISSUE THREAD

**Issue by Cloud33** [dotnet/orleans#6588]
I can't find the document about reminder persistence in the document. At present, only grains persistence is available. Can I add this part of the description?

**Comment by sergeybykov** [comment]
There's no special configuration of reminder persistence. When a particular reminder provider is configured, it is given enough information to persist state. http://dotnet.github.io/orleans/Documentation/grains/timers_and_reminders.html?q=reminder#configuration shows a couple of examples, for Azure Table and SQL. Both use `options.ConnectionString` to tell where to store reminders.

**Comment by Cloud33** [comment]
Does it mean that reminders cannot be customized like grains persistence?

**Comment by sergeybykov** [comment]
Reminders are customized the same way as persistence - via using different providers. What exactly would you like to customize?

**Comment by Cloud33** [comment]
for example, like `grain persistences`, implement the `reminder persistence` interface and we can customize the implementation, store it in Mysql, sql server, MongoDB

**Comment by sergeybykov** [comment]
No worries. I bet for most people here English is a second language. 🙂

>Implement IGrainStorage to customize your own storage

Similarly, for a reminder provider you'd need to implement `IReminderTable`. See https://github.com/dotnet/orleans/blob/master/src/Azure/Orleans.Reminders.AzureStorage/Storage/AzureBasedReminderTable.cs#L12 for an example. 
And configuration extension methods. For example, like in https://github.com/dotnet/orleans/blob/master/src/Azure/Orleans.Reminders.AzureStorage/SiloHostBuilderReminderExtensions.cs#L135.

**Comment by Cloud33** [comment]
OK, thank you very much，In theory, I can also implement `clustering` by myself, which is a very good design.

**Comment by sergeybykov** [comment]
Yes, you can implement a clustering table provider. For example, look at https://github.com/dotnet/orleans/tree/master/src/AWS/Orleans.Clustering.DynamoDB/Membership.
