### ISSUE TITLE
[Question]There is a small window during a silo failure

### ISSUE THREAD

**Issue by Cloud33** [dotnet/orleans#6591]
I've seen before The Issues, there's mentioned
https://github.com/dotnet/orleans/issues/920
>There is a small window during a silo failure when if you are unlucky you may get two activations of the same grain activated at the same time. One of them will get removed after the cluster state settles.

Can I lock grain for a period of time when `silo` is unstable until it stabilizes?

Doing so may increase the complexity of the system and reduce performance, but we can provide policy options for use.

**Because I want to make sure grain is a single-threaded operation in any case, because that's the greatest value for `Actor` in itself, what do you think?**

**Comment by sergeybykov** [comment]
You could use an external lease/coordination mechanism to ensure a strong single activation guarantee.

Another option is to use a storage-based grain directory implementation that are now enabled in 3.2.0. It includes Azure Table and Redis providers (in beta).

>Because I want to make sure grain is a single-threaded operation in any case

I suspect you meant single activation guarantee here. Each grain activation is still single-threaded.

**Comment by Cloud33** [comment]
> You could use an external lease/coordination mechanism to ensure a strong single activation guarantee.
>Another option is to use a storage-based grain directory implementation that are now enabled in 3.2.0. It includes Azure Table and Redis providers (in beta).

Great, is there any documentation available?I want to know the mechanism right now.

>I suspect you meant single activation guarantee here. Each grain activation is still single-threaded.

Don't doubt that you're right.

**Comment by sergeybykov** [comment]
The documentation is here at the moment - https://github.com/dotnet/orleans/pull/6572.
