### ISSUE TITLE
Has Empty Guid as Grain Id a special behavior?

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#6594]
Hi,

it is a very vague question and issue, but I am just trying to reproduce a bug.

I see in my logs, that some users make invalid requests, e.g. they make a request like

/PATCH /api/content/123 but 123 should be a guid instead. Then the ASP.NET Core binder cannot parse the string and just returns an empty guid and a grain with empty guid is invoked. The PATCH request is converted to an update command and send to my grain domain object. 

Such a domain objects has a check to see if it has been created before. It checks the storage if a state object exists and throws an exception otherwise. To create a domain object you have to invoke the /POST endpoint and the ID of the content item is generated with `Guid.NewGuid()`. There is no way to define the id over the API when creating the domain object.

But my problem is that the check does not seem to work. It tries to invoke the update command and fails with another exception. Unfortunately I cannot reproduce it and it does not happen very often. Perhaps only with a real cluster and network calls? Don't know for sure.

Therefore: is there any special behavior for Guid.Empty that I need to be aware of?

**Comment by sergeybykov** [comment]
I don't believe there's any special treatment of `Guid.Empty` in the Orleans codebase. Are you suspecting ASP.NET has a special case for it?

**Comment by SebastianStehle** [comment]
No, it is just that my case behaves so strange and it is inside my domain object (Grain)
