### ISSUE TITLE
[please help] how to achieve elegant shutdown and restart?

### ISSUE THREAD

**Issue by Cloud33** [dotnet/orleans#6596]
Hi, I have a problem.
I'm working on an app similar to `Saga`:
Structure: `Activity`->`Event`
Correspondence: 1:n 

It's a long-running service, and I'll use reminders to periodically scan all checkpoint steps, because to provide idempotence, event execution needs to be persisted after execution.

This creates a question, how do I stop it?
How do you ensure that completed events are persisted during normal shutdowns or failures at high speeds?

Or do you think about failures, how to achieve elegant shutdown and restart?

**Comment by HermesNew** [comment]
使用orleans的事务即可。

**Comment by Cloud33** [comment]
If the event contains an RPC request, the RPC request completes the required tag event has been completed.
This situation does not seem to be able to be handled as a matter?

**Comment by sergeybykov** [comment]
I'm not sure I fully understand the question. As a general rule, one should not rely on clean graceful shutdown of a node in the cluster. If an operation doesn't complete successfully, the caller should get an error and may decide to retry. Reminders are another mechanism for retrying or rolling back operations that haven't completed successfully.

**Comment by Cloud33** [comment]
I understand what you mean

However,I want to have a place to execute 'action' after the closing of Orleans slio. The value of this is that if all my storage is batch storage, the data is a fact that has happened. If there is such an opportunity, the last batch of data can be safely stored in the database.

**Comment by sergeybykov** [comment]
You can try to leverage silo lifecycle for that I think.

**Comment by Cloud33** [comment]
The silo lifecycle is executed immediately when the shutdown is performed, not after the shutdown. I mean after closing all grains, there will be no new storage requirements

**Comment by sergeybykov** [comment]
A lifecycle participant you register choses stage of the lifecycle it will execute at. So, you should be able to get register one that will store the data after all grains are deactivated.

**Comment by Cloud33** [comment]
I checked the document on silo lifecycle and wrote an example. It seems that the silo lifecycle is only the period of silos startup, not the lifecycle of shutdown? Strange, here is my code and print information:
```
builder.AddStartupTask(
              async (IServiceProvider services, CancellationToken cancellation) =>
              {
                  Console.WriteLine("=======================AddStartupTask Active=======================");
              }, ServiceLifecycleStage.Active);
            builder.AddStartupTask(
             async (IServiceProvider services, CancellationToken cancellation) =>
             {
                 Console.WriteLine("=======================AddStartupTask First=======================");
             }, ServiceLifecycleStage.First);
             builder.AddStartupTask(
             async (IServiceProvider services, CancellationToken cancellation) =>
             {
                 Console.WriteLine("=======================Star  Last=======================");
                 await Task.Delay(2000);
                 Console.WriteLine("=======================End  Last=======================");
             }, ServiceLifecycleStage.Last);
            var host = builder.Build();
            await host.StartAsync();
```
The focus is on the message printing of  `last`
```
info=======================Star  Last=======================
: Orleans.Runtime.SiloLifecycleSubject[100452]
      Orleans.Hosting.SiloBuilderStartupExtensions+StartupTask started in stage Active (20000) in 1.1587 Milliseconds
info: Orleans.Runtime.SiloLifecycleSubject[100452]
      ClusterHealthMonitor started in stage Active (20000) in 0.2107 Milliseconds
info: Orleans.Runtime.SiloLifecycleSubject[100452]
      MembershipTableCleanupAgent started in stage Active (20000) in 0.165 Milliseconds
info: Orleans.Runtime.SiloLifecycleSubject[100452]
      GatewayConnectionListener started in stage Active (20000) in 2.488 Milliseconds
info: Orleans.Runtime.SiloLifecycleSubject[100452]
      Orleans.Runtime.Silo started in stage Active (20000) in 2.8443 Milliseconds
info: Orleans.Runtime.SiloLifecycleSubject[100452]
      Starting lifecycle stage Active (20000) took 6.0084 Milliseconds
info: Orleans.Runtime.Messaging.Gateway[101301]
      Recorded opened connection from endpoint 127.0.0.1:60113, client ID *cli/193690ba.
info: Orleans.Networking[0]
      Starting to process messages from remote endpoint 127.0.0.1:60113 to local endpoint 127.0.0.1:30000
info: Orleans.Networking[0]
      Starting to process messages from local endpoint 127.0.0.1:30000 to remote endpoint 127.0.0.1:60113
info: Grains.HelloGrain[0]

 -----------OnActivateAsync 0 TraceId:
info: Grains.HelloGrain[0]
      SomeDelegateAsync 1 Star
=======================End  Last=======================


 Press Enter to terminate...


info: Orleans.Runtime.SiloLifecycleSubject[100452]
      Orleans.Hosting.SiloBuilderStartupExtensions+StartupTask started in stage Last (2147483647) in 2010.169 Milliseconds
info: Orleans.Runtime.SiloLifecycleSubject[100452]
      Starting lifecycle stage Last (2147483647) took 2010.3077 Milliseconds
info: Grains.HelloGrain[0]
      SomeDelegateAsync 2
info: Grains.HelloGrain[0]
      SomeDelegateAsync 3 End
```
I didn't turn it off at this time
If I use the problem, or understand the problem, please advise

thank

**Comment by sergeybykov** [comment]
`ILifecycleObserver` includes both `OnStart` and `OnStop' methods.

Instead of calling `builder.AddStartupTask()`, you need to register an implementation of `ILifecycleParticipant` in the DI, and then in its `Participate()` method subscribe to any combination of `OnStart` and `OnStop' events for stages you want to run as part of.

See https://github.com/dotnet/orleans/blob/master/test/Tester/Lifecycle/LifecycleTests.cs for an example.

**Comment by Cloud33** [comment]
Great. It solved my problem,

Thank you very much
