### ISSUE TITLE
[Question] How to prevent InconsistentStateExceptions caused by interleaving grain calls

### ISSUE THREAD

**Issue by rikbosch** [dotnet/orleans#6597]
Hi

We're experiencing issues, where interleaving graincalls (like timers) are causing inconsistentstate exceptions. 

If i'm correct, this means that during an await `WriteStateAsync()` call, another grain call is interleaving and also calling `WriteStateAsync()`. 
One of these `WriteStateAsync()` calls will throw an `InconsistentStateException` because one call changed the `ETag` of the `GrainState` object before the other completed.

So to fix this, I think I could use a `SemaphoreSlim` in the `WriteStateAsync` calls. Effectively this will serialize `WriteStateAsync` calls to the underlying storage provider. Could this be a solution? or will this introduce other problems like deadlocking grain calls?

example of using `SemaphoreSlim` to serialize `WriteStateAsync` calls
```csharp
/// <summary>
/// Semaphore used to serialize WriteStateAsync calls
/// </summary>
private readonly SemaphoreSlim _commitGate = new SemaphoreSlim(1);

protected override Task WriteStateAsync()
{
            // protect this with a semaphore,
            // only one Task is allowed to write
            // so all WriteStateAsynctasks are executed in serial order
            await _commitGate.WaitAsync();
            try
            {              
                     base.WriteStateAsync();
            }
            finally
            {
                _commitGate.Release();
            }
}

```

**Comment by martinothamar** [comment]
There is some sample code showing how to deal with this without locks: https://github.com/dotnet/orleans/blob/master/Samples/2.3/Chirper/Chirper.Grains/ChirperAccount.cs#L244

We've been using this ourselves without issues

**Comment by rikbosch** [comment]
Closing, as the proposed solution from @martinothamar from the Chirper sample suits our needs. Thx!
