### ISSUE TITLE
Exceptions stacktrace incomplete if client and silo not same process

### ISSUE THREAD

**Issue by buzzers** [dotnet/orleans#6599]
I'm using Orleans to write a real-time game app, and writing the game's WebApi interface with AspNetCore, calling Silo's Grain in Controller. 

When I host AspNetCore and Silo in a process, the exception stacktrace is complete, 
but when I host AspNetCore and Silo as two processes, 
then stacktrace of exceptions I caught by AspNetCore starts with ToTypedTask method instead of my code.

The code on the AspNetCore side is very simple, and he looks like this:

```csharp
[HttpPost]
public async Task<MyResponse> MyRequestAsync()
    => await this.GrainFactory.GetGrain<IGrain>(this.Id).MyRequestAsync();
```

In Grain's implementation code, I call the List.Add method using the null parameter to throw an exception. 
It looks like this:

```csharp
var values = new List<string>();
values.Add(null);
```

Then I caught an exception in AspNetCore, but I got the call stack:

```
at async Task<T> Orleans.Internal.OrleansTaskExtentions.ToTypedTask<T>(Task<object> task)+ConvertAsync(?)
at async Task<MyResponse> Carbon.Hosting.Controllers.MyController.MyRequestAsync() in /builds/carbon/src/Carbon.Hosting.Ingress.RESTful/Controllers/MyController.cs:line 126
```

**Comment by pughua** [comment]
I also met the same problem. Is there any solution?

**Comment by buzzers** [comment]
@pughua No, I didn't find any way to work. Our current ad hoc scenario is to use trace IDs to correse logs of different Silos to view the complete call stack.

**Comment by pughua** [comment]
Here's how I do it, implementing the interface IOutgoingGrainCallFilter to catch all exceptions, serializing the stack message into a custom exception object, and throwing it later.
``` C#
    public class OutCallFilter:IOutgoingGrainCallFilter
	{
		public async Task Invoke(IOutgoingGrainCallContext context)`
        {
           try
            {
                await context.Invoke();
            }
           catch(Exception ex)
           {
               throw new CustomException(ex.Message,ex.StackTrace);
           }
        }
	}
	
	[Serializable]
    public class CustomException:Exception
    {
        public string ErrorInfo
        {
            get;
            private set;
        }

        public CustomException():base()
        {

        }

        [SecuritySafeCritical]
        protected DomainBaseException(SerializationInfo info, StreamingContext context) : base(info, context)
        {
            ErrorInfo = info.GetString(nameof(ErrorInfo));
        }

        public override void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            base.GetObjectData(info, context);
            info.AddValue(nameof(ErrorInfo), ErrorInfo);
        }

        public DomainBaseException(string msg,string stackTrace):base(msg)
        {
            ErrorInfo =  stackTrace;
        }

    }
