### ISSUE TITLE
RedactAttribute required to redact secrets in options

### ISSUE THREAD

**Issue by jason-bragg** [dotnet/orleans#6603]
Orleans options logging will not log any property marked with the RedactAttribute.  This is great for Orleans options, but will not work for any third party options, or developer options not depending on Orleans.Core.

Suggest adding some means to opt out of option logging that does not depend on the option itself being written with redaction in mind.  Maybe a configurable redact list?

**Comment by ReubenBond** [comment]
Orleans will not log non-Orleans options, so this should not be an issue.
