### ISSUE TITLE
Microsoft.Orleans.OrleansConsulUtils does not have option to clear consul existing instances

### ISSUE THREAD

**Issue by sandeepso** [dotnet/orleans#6606]
I am using Microsoft.Orleans.OrleansConsulUtils v3.2.0 to run my silo in consul. 
In UseConsulClustering, I do not see any option to clean or clear consul folder previous instances.

  .UseConsulClustering(gatewayOptions =>
   {
            gatewayOptions.Address =
                            new Uri(ConfigurationManager.AppSettings["ServiceDiscoverEndPoint"]);
                        gatewayOptions.AclClientToken = ConfigurationManager.AppSettings["ServiceDiscoveryToken"];
                        gatewayOptions.KvRootFolder = ConfigurationManager.AppSettings["KvFolderName"];
        })

**Comment by iwillspeak** [comment]
You can control this from the `ClusterMembershipOptions` via `DefunctSiloCleanupPeriod` and `DefunctSiloExpiration` I think.

**Comment by satishviswanathan** [comment]
The property DefunctSiloCleanupPeriod is not available via ClusterOptions or ConsulClusteringSiloOptions. Do you know how we can set it?

**Comment by iwillspeak** [comment]
They’re in ClusterMembershipOptions I think.

**Comment by sergeybykov** [comment]
Yes, you can set expiration of old silo membership records via `ClusterMembershipOptions.DefunctSiloExpiration`, and it will work for all clustering providers that implement the feature. The Consul provider does implement it.

**Comment by sandeepso** [comment]
I tried using ClusterMembershipOptions DefunctSiloExpiration and DefunctSiloCleanupPeriod  properties but its not clearing old silo instance from consul, here is my code for your reference.

var builder = new SiloHostBuilder()
                    .Configure<ClusterOptions>(options =>
                    {
                        options.ClusterId = ConfigurationManager.AppSettings["ClustId"];
                        options.ServiceId = ConfigurationManager.AppSettings["ServiceId"];
                    })
                    .Configure<ClusterMembershipOptions>(clusterOptions =>
                    {
                        clusterOptions.DefunctSiloCleanupPeriod = TimeSpan.FromSeconds(30);
                        clusterOptions.DefunctSiloExpiration = TimeSpan.FromSeconds(30);
                    })

**Comment by sandeepso** [comment]
I tried again after upgrading all dependent nuget libraries in my project and it seems to be working now. 
Thank you!

**Comment by yilezhu** [comment]
Hi, friend. I have also encountered this problem at present. After silos is offline, the consul has not been updated and removed the offline silos. How can I solve it?

**Comment by iwillspeak** [comment]
How many working silos remain? You still need a working Orleans cluster for defunct silo cleanup to work. The cluster will periodically remove the older defunct entries. Entries aren’t removed immediately, there is a job that searches for expired entries periodically and removes them.

**Comment by yilezhu** [comment]
Thank you for your reply. I have two silos, and I stopped one. How can I set the recycling time for the job that searches for expired entries periodically and removes them.?

**Comment by iwillspeak** [comment]
I think you might need at least 3 silos to form a quorum. Without that the membership oracle can’t mark silos as dead. What happens if you have four silos and remove one of them. Does the entry get cleared then?
