### ISSUE TITLE
Event messaging sample application using orleans

### ISSUE THREAD

**Issue by skynetit** [dotnet/orleans#6608]
We are looking to build a virtual actor application which gets events (UserAdded, UserUpdated, ProfileAdded, etc) from service bus topic and process it by calling external apis. Also store those events in a no-sql database. 

I tried to find some samples but couldn't find any. If we built such application in Orleans, how to deploy the app?

Can you please suggest any ideas?

**Comment by sergeybykov** [comment]
Orleans is nearly deployment agnostic and can be deployed in many different ways. How do you usually deploy your cloud services/applications?

**Comment by skynetit** [comment]
Currently we are using scale sets to deploy our web/api applications. 
Can you please suggest few options for developing  the above scenario using orleans & deploy?

**Comment by sergeybykov** [comment]
If your question is about deployment, I'd suggest as a first step to take https://github.com/dotnet/orleans/tree/master/Samples/3.0/HelloWorld or https://github.com/dotnet/orleans/tree/master/Samples/3.0/AspNetCoreCohosting, replace `UseLocalhostClustering()` with `UseAzureStorageClustering()` in their configuration code, and try to deploy them the same way you deploy to scale sets today.

**Comment by skynetit** [comment]
Thanks @sergeybykov. The above links are very useful.

Which approach will be better for processing the events received from service bus topic listener, EventSourcedGrain or general grains? We will be processing around 500k messages per day.

**Comment by sergeybykov** [comment]
To me, this is a tradeoff between the additional complexity and cost of keeping the log of state changes (to protect from state corruption, for audit, etc.) vs. the efficiency of destructive updates. I don't believe there's a universal answer here.

**Comment by skynetit** [comment]
For us, the log will be only for reference perspective ( analyze when a particular event occured/ what type of event for unique id). So I am thinking of using general grains
