### ISSUE TITLE
Method not found: 'Orleans.Runtime.IAddressable Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(System.Type, Int32, Int64, System.String)

### ISSUE THREAD

**Issue by combrinckd** [dotnet/orleans#661]
Every time I try to connect to the local silo I get the error: Method not found: 'Orleans.Runtime.IAddressable Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(System.Type, Int32, Int64, System.String)

I have updated to the new version 1.0.9, ensured that the old SDK was uninstalled and the new installed, updated the nuget packages and relevant references across the interfaces, grains and local silo host as well as the client. 
However the exception occurs with every connection from the client:

![orleans error](https://cloud.githubusercontent.com/assets/13551104/8951879/fe2aeaee-35d1-11e5-9d23-287b955c8244.png)

Any help with this will be greatly appreciated!

**Comment by gabikliot** [comment]
Concrete generated grain factories were deprecated in 1.0.9.
Instead you should use the generic factory:
`IMetaUnit device = GrainFactory.GetGrain<IMetaUnit>(0);

**Comment by combrinckd** [comment]
Hi gabikliot, thanks for the quick responce. I have tried what you suggested, but now I can't even build.
Error	10	An object reference is required for the non-static field, method, or property 'Orleans.GrainFactory.GetGrain<TGrainInterface>(long, string)'
Any ideas?

**Comment by veikkoeeva** [comment]
@combrinckd How about when you replace ``Orleans`` with ``this``. As in ``this.GrainFactory.GetGrain(long, string)``?

**Comment by combrinckd** [comment]
Found similar issue on #630. Trying solution suggested there. thanks guys :)

**Comment by gabikliot** [comment]
Yes, sorry, on the client it should be You should use  `GrainClient.GrainFactory.GetGrain<IMetaUnit>(grainKey)`
