### ISSUE TITLE
Question: IHostedService (Or long running services) and Orleans 

### ISSUE THREAD

**Issue by derekssmith** [dotnet/orleans#6610]
I am having trouble understanding how to use long running services with Orleans.  It is possible this is stemming from my understanding (or mis-understanding) of the Orleans Streaming.  I run stream processing logic on top of Kafka for a very large amount of data.  The processing pipelines for these use cases don't need to be dynamic, and the documentation for Orleans Streams indicates that  was the motivation for its design.  

My main question is if it is okay to create a grain like this:

```c#
// Grain Interface
public interface IStreamProcessorGrain : IGrainWithStringKey {

    Task<bool> GetIsRunningAsync();

    Task StartAsync();

    Task StopAsync();
}

// Grain Class
public class StreamProcessorGrain : Grain, IStreamProcessorGrain {
    private Task _processingTask;
    private bool _isRunning;

    public Task<bool> GetIsRunningAsync() {
        return Task.FromResult(_isRunning);
    }

    public Task StartAsync() {
       _processingTask = Task.Run(DoWork);
       _isRunning = true;
      return Task.CompletedTask;
    } 

    public Task StopAsync() {
        // clean up
    }
}
```

My concern is the grain instance would get deactivated after a period of time, causing this not to be an always on service.  

I saw the `GrainService` code, however that doesn't quite fit because it says it will run in each Silo.  

> A GrainService is a special grain; one that has no identity, and runs in every silo from startup to shutdown.

**Comment by derekssmith** [comment]
I found information in #1721 that helped clarify some things.  It seems like reminders and timers might be a better approach for my situation.

**Comment by ReubenBond** [comment]
If you are pulling from some place and pushing into a grain, then you could use an IHostedService if you want, too.

**Comment by eramosr16** [comment]
I wanna have a grain listen to a websocket, to me it fits more like IHostedService but I would have multiple instances if I scale. Can we have a grain that behave like IHostedService:
- Have same lifetime as the Silo
- Only one implementation across the cluster allowed(or number set by settings).
- Start and Stop methods.
- Always Active

**Comment by derekssmith** [comment]
@eramosr16 We ended up deciding that always-on grains were an anti-pattern with Orleans.  You might want to look at [GrainService](https://dotnet.github.io/orleans/docs/grains/grainservices.html).  The definition sounds like close to what you are describing. 

> A GrainService is a special grain; one that has no identity, and runs in every silo from startup to shutdown.
