### ISSUE TITLE
MemoryStreamsProvider does not appear to manage StreamSequenceTokens properly

### ISSUE THREAD

**Issue by rrector** [dotnet/orleans#6619]
We recently upgraded from v2.4.5 to v3.0.2 and started seeing this issue. We've since upgraded to v3.1.7 and are still experiencing the same issue. 

Our expectation is that the in-memory stream provider would manage both the `SequenceNumber` and the `EventIndex` of the `SequenceToken` for us. What we're observing is that the `EventIndex` appears to be tracked properly, but the `SequenceNumber` is always 0 when received by our subscribed grain.

I've created a simple program to reproduce what we're seeing at https://github.com/rrector/OrleansMemoryStreamTest

The producer will in this example will create a number of events (based on input). It will create that number of events - the data for the event is a sequence number generated by the producer and will randomly batch the events in batch sized from 1 to 4 events.

As you can see in the output below, the `EventIndex` matches the index of the items as we batched them up, but `SequenceNumber` in the `SequenceToken` is always 0.

>Enter the number of events to generate, 0 to quit
>25
>Received item, Our sequence is 31 and batch is 0. Sequence Token is (SN:0, EI:0)
>Received item, Our sequence is 32 and batch is 1. Sequence Token is (SN:0, EI:1)
>Received item, Our sequence is 33 and batch is 2. Sequence Token is (SN:0, EI:2)
>Received item, Our sequence is 34 and batch is 0. Sequence Token is (SN:0, EI:0)
>Received item, Our sequence is 35 and batch is 1. Sequence Token is (SN:0, EI:1)
>Received item, Our sequence is 36 and batch is 2. Sequence Token is (SN:0, EI:2)
>Received item, Our sequence is 37 and batch is 3. Sequence Token is (SN:0, EI:3)
>Received item, Our sequence is 38 and batch is 0. Sequence Token is (SN:0, EI:0)
>Received item, Our sequence is 39 and batch is 1. Sequence Token is (SN:0, EI:1)
>Received item, Our sequence is 40 and batch is 0. Sequence Token is (SN:0, EI:0)
>Received item, Our sequence is 41 and batch is 1. Sequence Token is (SN:0, EI:1)
>Received item, Our sequence is 42 and batch is 2. Sequence Token is (SN:0, EI:2)
>Received item, Our sequence is 43 and batch is 0. Sequence Token is (SN:0, EI:0)
>Received item, Our sequence is 44 and batch is 1. Sequence Token is (SN:0, EI:1)
>Received item, Our sequence is 45 and batch is 0. Sequence Token is (SN:0, EI:0)
>Received item, Our sequence is 46 and batch is 0. Sequence Token is (SN:0, EI:0)
>Received item, Our sequence is 47 and batch is 1. Sequence Token is (SN:0, EI:1)
>Received item, Our sequence is 48 and batch is 2. Sequence Token is (SN:0, EI:2)
>Received item, Our sequence is 49 and batch is 0. Sequence Token is (SN:0, EI:0)
>Received item, Our sequence is 50 and batch is 1. Sequence Token is (SN:0, EI:1)
>Received item, Our sequence is 51 and batch is 2. Sequence Token is (SN:0, EI:2)
>Received item, Our sequence is 52 and batch is 0. Sequence Token is (SN:0, EI:0)
>Received item, Our sequence is 53 and batch is 1. Sequence Token is (SN:0, EI:1)
>Received item, Our sequence is 54 and batch is 2. Sequence Token is (SN:0, EI:2)
>Received item, Our sequence is 55 and batch is 3. Sequence Token is (SN:0, EI:3)

Is there something else we should be doing to get SequenceNumbers properly created with In-Memory streams? We rely on them for some of our local testing scenarios so we don't have to create an EventHub for each developer, and this new behavior is breaking our tests.

**Comment by sergeybykov** [comment]
Resolved via #6622.
