### ISSUE TITLE
grain call from grain: "You must initialize the Grain Client before accessing the GrainFactory"

### ISSUE THREAD

**Issue by sgratwohl** [dotnet/orleans#662]
Hi,

Since I updated to 1.09 I have a problem with a grainfunction that calls another grain. The call throws an exception "You must initialize the Grain Client before accessing the GrainFactory".

The problem only occurs if I get the grain with "GrainClient.GrainFactory.GetGrain<IMyGrain>(grainid)". If I use the autogenerated (deprecated) grainfactory everything works as before. 

In GrainClient.cs from the orleanscode I see the comment "//TODO: prevent client code from using this from inside a Grain". Does that mean, that you should not (or cannot) use a grain from another grain?

Thanks for any hints.

**Comment by sergeybykov** [comment]
From within a grain it's `this.GrainFactory.GetGrain(grainid)`. `GrainClient` is to be used only from outside of a silo.

**Comment by sgratwohl** [comment]
oh, i see.  thanks!

**Comment by gabikliot** [comment]
I added a more explicit and more helpful exception here: #663.
