### ISSUE TITLE
Does orleans transport use multicast and broadcast over tcp/ip?

### ISSUE THREAD

**Issue by KirillJK** [dotnet/orleans#6627]
Hello. I would like to clarify if Orleans uses multicast or broadcast on the IP level. I'm asking because I want to use this greatful framework in our project but we aren't allowed to use broadcasting on the network level due to security reasons.
Thank you.

**Comment by ReubenBond** [comment]
Hi Kirill, I can confirm that Orleans does not use multicast or broadcast on the IP level, all communication is point to point

**Comment by KirillJK** [comment]
Thank you
