### ISSUE TITLE
Warning: Refresh the GrainTypeResolver failed. Will be retried after

### ISSUE THREAD

**Issue by SeppPenner** [dotnet/orleans#6629]
It's not that I believe this is some serious issue, but from time to time (Around every minute), I get the following warning in my Orleans Silo:

```chsarp
[WRN] Refresh the GrainTypeResolver failed. Will be retried after
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Orleans.Runtime.Messaging.ConnectionManager.GetConnectionAsync(SiloAddress endpoint)
   at Orleans.Messaging.ClientMessageCenter.<GetGatewayConnection>g__ConnectAsync|35_1(SiloAddress gateway, ValueTask`1 connectionTask, Message message, Boolean directGatewayMessage)
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
```

I'm not able to find where exactly this comes from. Does anyone have an idea why this occurs? I have already looked through all my grains and grain interfaces but can't see an issue (Every interface has an implementation).

**Comment by sergeybykov** [comment]
This warning is on the client side (in `OutsideRuntimeClient`). Are you sure you are seeing it in the silo logs?

**Comment by SeppPenner** [comment]
Hi @sergeybykov. Yes, this was shown in the Silo log for sure.

I'm honestly not sure where it came from (It's resolved now after I rebuilt the solution). Maybe it was caused by some inconsistent grain interfaces or so? I have no idea 😅

**Comment by sergeybykov** [comment]
Could it be package version mismatch after a partial rebuild? Anyway, you are good now, right?

**Comment by SeppPenner** [comment]
> Could it be package version mismatch after a partial rebuild?

I guess that was the issue. I wasn't able to reproduce this...

> Anyway, you are good now, right?

Yes, I will close this issue now.
