### ISSUE TITLE
[bug]   Reminder failure

### ISSUE THREAD

**Issue by Cloud33** [dotnet/orleans#6632]
Under the latest 'Orleans' 3.2.1, no reminders will be executed after the reminders are injected. It is very sure that the reminders are stored normally and loaded into' Orleans'. The same code is normal under 3.2.0

**Comment by ReubenBond** [comment]
Can you provide more information, including what the reminder name is, and the storage provider that you're using? Could you show how you're registering them and how you are verifying that they are not being executed?

**Comment by Cloud33** [comment]
The storage I use is a custom ADO vendor because I only use it on a specific environment, and I reduce some logical processing, approximate lying code
`UpsertReminderRowAsync`
![image](https://user-images.githubusercontent.com/8787198/86503094-41f1a900-bddd-11ea-9b9a-d172947a9607.png)
`ReadReminderRowsAsync`
![image](https://user-images.githubusercontent.com/8787198/86503113-6cdbfd00-bddd-11ea-931f-c127eb8f719c.png)

Presumably, I could see 'ReadRecallRowsAsync' read out, but the reminder was not executed.

This is the conversion:
![image](https://user-images.githubusercontent.com/8787198/86503136-a3197c80-bddd-11ea-83ed-c0b7cfb4504a.png)

**Comment by Cloud33** [comment]
Add:
Environment: only one silo, local development configuration，'Orleans' 3.2.1
If there are no reminders before, use API to register 2 reminders
If there are no reminders before, register 2 reminders with API. The number of reminders loaded is correct, but only one is running:
![image](https://user-images.githubusercontent.com/8787198/86507560-ba6f5e80-be0b-11ea-91cc-2115ee2df84f.png)

If four reminders already exist, restart silo and I test it twice:
1. The number of reminders loaded is normal, but only 3 reminders are running
2. The number of reminders loaded is normal, but only 4 reminders are running
Screenshot of the second time:
![image](https://user-images.githubusercontent.com/8787198/86507412-93fcf380-be0a-11ea-8549-c694357795c6.png)

The situation is like this. I didn't have this problem at all in 3.2.0

**Comment by Cloud33** [comment]
Add,
I did this test:

1. I generated four reminders in `Orleans 3.2.1`, but only three of them were running. I ran these reminders in `Orleans 3.2.0`, and the results were the same, and the keys of the three instances were the same.


2. I generated four reminders in `Orleans 3.2.0`, and all of them were running. I ran these reminders in `Orleans 3.2.1`, and the results were the same. All four data were running.


I wonder if there is a change in `GrainId`?

**Comment by Cloud33** [comment]
@ReubenBond 
Is the information I provide useful?
What else can I provide.

thank you

**Comment by Cloud33** [comment]
I may have found the reason, I think

https://github.com/dotnet/orleans/blob/master/src/AdoNet/Orleans.Reminders.AdoNet/ReminderService/AdoNetReminderTable.cs

Using
```
private readonly GrainReferenceKeyStringConverter grainReferenceConverter
```


I use it myself
```
private readonly IGrainReferenceConverter grainReferenceConverter;
```
Is this place influential?
I quoted` Microsoft.Orleans.Core `DLL, but can't use 'grainreferencekeystringconverter'. What's the reason?
@ReubenBond

**Comment by Cloud33** [comment]
Modify the scheme, close
