### ISSUE TITLE
No logging in Application Insight when using AddApplicationInsightsTelemetryConsumer

### ISSUE THREAD

**Issue by drano** [dotnet/orleans#6644]
With Orleans 3.1, I am using AddApplicationInsightsTelemetryConsumer with applicationinsights key, but I cannot see logging in Application Insights.

**Comment by sergeybykov** [comment]
Have you tried debugging what's going on there? We don't currently have any tests for AI telemetry consumer. So, It's hard to tell right away if something is broken here.

**Comment by maurert** [comment]
I have the same problem. And I noticed there are a couple of questions about this on Gitter that have not been answered anywhere.

The only documentation I can fin is this page:
https://dotnet.github.io/orleans/docs/host/monitoring/index.html

My silo configuration looks like this:
` public static Task Main(string[] args)
        {
            return Host.CreateDefaultBuilder(args)
                .UseDefaultServiceProvider(provider => provider.ValidateOnBuild = false)
                .UseOrleans(
                    (context, builder) =>
                    {
                        builder
                            .AddApplicationInsightsTelemetryConsumer(context.Configuration["APPINSIGHTS_INSTRUMENTATIONKEY"])
                            .ConfigureApplicationParts(
                                parts => parts.AddApplicationPart(typeof(XGrain).Assembly)
                                    .WithReferences())
                            .UseDashboard()
                            .UseAzureStorageClustering(options =>
                            {
                                var config = context.Configuration.GetSection("Orleans");

                                options.ConnectionString = config["ClusterTableConnectionString"];
                            })
                            .Configure<ClusterOptions>(
                                options =>
                                {
                                    var orleansConfig = context.Configuration.GetSection("Orleans");

                                    options.ClusterId = orleansConfig["ClusterId"];
                                    options.ServiceId = orleansConfig["ServiceId"];
                                })
                            .Configure<EndpointOptions>(
                                options =>
                                {
                                    var orleansConfig = context.Configuration.GetSection("Orleans");
                                    var gatewayPort = orleansConfig.GetValue<int>("GatewayPort");
                                    var siloPort = orleansConfig.GetValue<int>("SiloPort");
                                    var advertisedIp = orleansConfig["AdvertisedIp"];

                                    options.GatewayPort = gatewayPort;
                                    options.SiloPort = siloPort;
                                    options.GatewayListeningEndpoint = new IPEndPoint(IPAddress.Any, gatewayPort);
                                    options.SiloListeningEndpoint = new IPEndPoint(IPAddress.Any, siloPort);
                                    options.AdvertisedIPAddress = IPAddress.Parse((ReadOnlySpan<char>)advertisedIp);
                                })
                            .ConfigureServices(
                                services =>
                                {                                    
                                    services.AddSingleton<IEventHubService>(
                                        container =>
                                        {
                                            var logger = container.GetRequiredService<ILogger<EventHubService>>();
                                            return new EventHubService(
                                                XConnectionString,
                                                YConnectionString,
                                                logger);
                                        });
                                })
                            .AddEventHubStreams(
                                Constants.StreamProviderId,
                                ehc =>
                                {
                                    var queueConfig = context.Configuration.GetSection("MessageQueue");
                                    var stateStorageConfig = context.Configuration.GetSection("GrainStateStorage");

                                    ehc.ConfigureEventHub(
                                        eh => eh.Configure(
                                            options =>
                                            {
                                                options.ConnectionString = queueConfig["EventHubConnectionString"];
                                                options.ConsumerGroup = queueConfig["EventHubConsumerGroup"];
                                                options.Path = queueConfig["EventHubPath"];
                                            }));
                                    ehc.UseAzureTableCheckpointer(
                                        atc => atc.Configure(
                                            options =>
                                            {
                                                options.ConnectionString =
                                                    stateStorageConfig["TableStorageConnectionString"];
                                                options.PersistInterval = TimeSpan.FromSeconds(10);
                                            }));
                                })
                            .AddAzureTableGrainStorage(
                                "TelemetryGrainStorage",
                                options =>
                                {
                                    var config = context.Configuration.GetSection("GrainStateStorage");

                                    options.ConnectionString = config["TableStorageConnectionString"];
                                    options.DeleteStateOnClear = true;
                                })
                            .AddAzureTableGrainStorage(
                                "PubSubStore",
                                options =>
                                {
                                    var config = context.Configuration.GetSection("GrainStateStorage");

                                    options.ConnectionString = config["TableStorageConnectionString"];
                                    options.DeleteStateOnClear = true;
                                })
                            .ConfigureLogging(logging => logging.AddConsole());                                                   
                    })
                .RunConsoleAsync();
        }`

**Comment by ReubenBond** [comment]
The Application Insights telemetry consumer does not add logging. For logging, you should use the [Microsoft.Extensions.Logging.ApplicationInsights](https://www.nuget.org/packages/Microsoft.Extensions.Logging.ApplicationInsights) package.

**Comment by maurert** [comment]
I also tried to track metrics by injecting Orleans.Runtime.ITelemetryProducer in my grain. But that telemetry did not end up anywhere it seems. Any documentation how to use the telemetry interfaces and hook them up to Application Insights?

**Comment by galvesribeiro** [comment]
Yes, the logging is provided by AI's own Microsoft.Extensions.Logging implementation. The only thing you need to inject on the grain is `ITelemetryProducer` which is an abstraction that in its internal implementation, publish metrics/counters/stats to all the registered telemetry consumers.

That being said, all you need is to call `AddApplicationInsightsTelemetryConsumer(instrumentationKey)` on your silo builder which looks like is what you are already doing, and all built-int metrics will be reported automatically. Are you sure the `instrumentationKey` is correct?

If you go to the AI resource and look at the Monitoring > Metrics, you may see under the Metric > Custom Metrics dropdown, all the built-in Orleans stats/counts/metrics and also anything custom you have created and published by using `ITelemetryProducer` like this:

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/4714040/119862719-2ad51180-beef-11eb-9bc5-ba327cffd223.png">

**Comment by maurert** [comment]
Thanks! 

I got telemetry to work using:
```
AddApplicationInsightsTelemetryConsumer("#######-####-####-####-############")
```
instead of 
```
AddApplicationInsightsTelemetryConsumer() 
```
With appsettings
```
"ApplicationInsights": {
    "InstrumentationKey": "#######-####-####-####-############"
  }
```

Am I doing something wrong with the appsettings entry or does the extension not support it? There are more settings for application insights I would like to set.

**Comment by galvesribeiro** [comment]
You can configure the Telemetry Consumer in different ways:

1. Passing the Instrumentation Key to `AddApplicationInsightsTelemetryConsumer(key)`
2. Configure the `ApplicationInsightsTelemetryConsumerOptions` and bind it to whatever config source (like the json file) you want and call `AddApplicationInsightsTelemetryConsumer()` without any parameter
3. Configure your `Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.Active` with the key and call  `AddApplicationInsightsTelemetryConsumer()` without any parameter

Those are the current ways you can configure it.

**Comment by Expecho** [comment]
> icationInsightsTelemetryConsumer()



> Thanks!
> 
> I got telemetry to work using:
> 
> ```
> AddApplicationInsightsTelemetryConsumer("#######-####-####-####-############")
> ```
> 
> instead of
> 
> ```
> AddApplicationInsightsTelemetryConsumer() 
> ```
> 
> With appsettings
> 
> ```
> "ApplicationInsights": {
>     "InstrumentationKey": "#######-####-####-####-############",
>     "EnableAdaptiveSampling": false
>   }
> ```
> 
> Am I doing something wrong with the appsettings entry or does the extension not support it? There are more settings for application insights I would like to set.

Instead of passing the key as a literal value you can use the configuration of the context like this:

```csharp
.UseOrleans((context, siloBuilder) =>
{
   ...
   siloBuilder.AddApplicationInsightsTelemetryConsumer(context.Configuration["ApplicationInsights:InstrumentationKey"]);
   ...
}
```

Anyway, can't this issue be closed since multiple people report they have it working for the metrics?

**Comment by iamsamcoder** [comment]
I'm running my silos in Azure Kubernetes Service. I've added the App insights configuration as others have. 

`.AddApplicationInsightsTelemetryConsumer("instrument-key")`

However, I'm not able to see application logs in App insights. I also enabled Container Insights, and after much experimentation I finally found my app logs in the Kubernetes Service > Monitoring > Logs > "ContainerLogs" table. 

Should I also expect to find my app logs in the Application Insights resource > Logs > trace table? 

One follow-up question, now that my app logs are being saved to ContainerLogs, I see that all orleans logs are going there and I'm running up my daily ingestion quite quickly. Is there a way to stop all orleans logs from going to Container Insights?

**Comment by ReubenBond** [comment]
@iamsamcoder that line adds telemetry, but if you want logs then you would configure App Insights as a logging provider by installing https://www.nuget.org/packages/Microsoft.Extensions.Logging.ApplicationInsights and configuring it during startup on your servers/clients like so:

``` C#
builder.ConfigureLogging((context, loggingBuilder) =>
{
     // Providing an instrumentation key is required if you're using the
    // standalone Microsoft.Extensions.Logging.ApplicationInsights package,
    // or when you need to capture logs during application startup, such as
    // in Program.cs or Startup.cs itself.
    loggingBuilder.AddApplicationInsights(context.Configuration["APPINSIGHTS_CONNECTIONSTRING"])
})
```

For more information, please see the App Insights docs on the matter: https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger

**Comment by Expecho** [comment]
> However, I'm not able to see application logs in App insights. I also enabled Container Insights, and after much experimentation I finally found my app logs in the Kubernetes Service > Monitoring > Logs > "ContainerLogs" table.

@iamsamcoder feel free to check out [my repo](https://github.com/Expecho/Orleans.Telemetry.ApplicationInsights) that adds  support for application insights telemetry, other than metrics.
