### ISSUE TITLE
TestingHost and live unit testing

### ISSUE THREAD

**Issue by jbockle** [dotnet/orleans#6652]
I'm using the TestingHost and with live unit testing, code generation doesn't run (using Microsoft.Orleans.CodeGenerator.MSBuild on the dependent project).  Is there a way to get it to run with a property in my tests csproj? I  was been able to get live unit testing working with TestingHost if I add OrleansCodeGenerator and add the application parts explicitly, which I'm not sure is the best route to go.

**Comment by jbockle** [comment]
bump..I realize this is a nice to have feature but life without live unit testing sucks 😭

**Comment by sergeybykov** [comment]
I'm not sure I understand the problem. Can't you reference `Microsoft.Orleans.CodeGenerator.MSBuild` in the dependent project at build time?

**Comment by jbockle** [comment]
I do have that referenced in both my grain interface/implementation projects, but code generation is not occurring for LUT, it only occurs when I run tests outside LUT.

**Comment by ReubenBond** [comment]
@jbockle perhaps Live Unit Testing is running a "design time build", which could explain why code generation is not being executed (since that would degrade the IDE user experience)?

I wonder if the new C# Source Generators have a way around this issue?

**Comment by cqgis** [comment]
This problem always exist, please try to resove it, with out live unit test sucks
