### ISSUE TITLE
Host with Service Id containing ':', reminders do not get resurrected

### ISSUE THREAD

**Issue by ry8806** [dotnet/orleans#6663]
Hi All,

I've come across what I think is a bug with the Azure Table Reminders functionality.

Essentially; If you run your cluster and your service Id has a ':' in, reminders that are saved to Azure Table Storage (defaultTable: "OrleansReminders"), that have already ticked, are never resurrected on Silo restart. All other parts of the system seem to function as expected.

This may not be too common, however in the ServiceFabric sample, the service Id is set to `fabricServiceContext.ServiceName.ToString();`, which is a string in the format: `fabric:/xxxx`. So for copy/pasta people (like me) this might catch a lot of people out. 

I've created a small repro application here: https://github.com/ry8806/orleans-bug
You can ignore most of the grain code in there - as it's just there to get a couple of reminders started.

*The Working path*
So with the sample app, go to Program.cs, choose service id without the colon (**const**s at the top).
then start the Silo, wait until all 3 reminders have been started (you'll see "Warn" in the console output).
Then shutdown the silo. Wait a minute or two, comment out `await CreateClientAndStartReminders();` so we don't create any more reminders and confuse ourselves, then restart the Silo. With console output set to Debug, you'll see messages like "read X reminders from table" - where some x's will be > 0. And you'll see other warn/error logs about the reminders ticking/unregistering etc

*The buggy path*
now, chose the other const (the one with the ':' in). Run the steps the same as above, and the reminders wont get resurrected on silo restart. Instead, they'll just sit in the reminders table and never get picked back up.

After a quick look at the source for Orleans I can see that the AzureStorageUtils.cs has a method -> SanitizeTableProperty - this could be changed. This is called by `RemindersTableManager.ConstructPartitionKey`, in which comments mention that it is likely going to be a "breaking change"

The partition key (containing the ':') is passed off to the Azure Table Storage SDK, so not sure if the problem lies in that package, maybe they're not excaping it correctly (as i believe a query gets turned into a URL for the Azure Table Storage Service)

I would like to help by submitting a PR (this bug has cost me over 20hrs this week, so I have a personal vendetta against it 😆) - however I'm unsure of the preferred approach at this time and possible side-effects to currently running applications

**Comment by ReubenBond** [comment]
Is this the same bug that was fixed in https://github.com/dotnet/orleans/pull/6460?
I see you're running 2.4.5, which doesn't include the fix.

**Comment by ry8806** [comment]
@ReubenBond just tested against Nuget Package version 3.2.2 and you're correct, this has been fixed by the PR referenced

**Comment by ReubenBond** [comment]
Good to hear! Should we close this one then?
