### ISSUE TITLE
Newbie trying hello world on .NET 5 and C# 9

### ISSUE THREAD

**Issue by dodyg** [dotnet/orleans#6666]
```
            .AddAzureBlobGrainStorage(
                            name: "profileStore",
                            configureOptions: options =>
                            {
                                // Use JSON for serializing the state in storage
                                options.UseJson = true;

                                // Configure the storage connection key
                                options.ConnectionString = "DefaultEndpointsProtocol=https;AccountName=data1;AccountKey=SOMETHING1";
                            });
```

https://github.com/dotnet/orleans/blob/master/Samples/3.0/HelloWorld/src/SiloHost/Program.cs

I am trying try a sample without the azure dependency. 

![exploded](https://user-images.githubusercontent.com/1761249/88774616-f46e1f00-d183-11ea-826c-5fcfebae690f.png)

The code for this is here https://github.com/dodyg/practical-aspnetcore/blob/3.1-LTS/projects/5-0/orleans/hello-world/silo/Program.cs

**Comment by ReubenBond** [comment]
I *think* the problem might be that the task returned from RunConsoleAsync() isn't being awaited

**Comment by dodyg** [comment]
Lol yup. Using top level statements scrambled my brain. Fixed now. Thanks!
