### ISSUE TITLE
Create Microsoft.Orleans.Sdk package to ease development

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#6668]
I believe we should consider a metapackage with the name `Microsoft.Orleans.Sdk` as the main package for clients and silos.

It can include codegen, abstractions, core, and runtime.

Thoughts/concerns?

**Comment by galvesribeiro** [comment]
I would even make it an sdk rather than just a meta-package. Like aspnet does...

**Comment by galvesribeiro** [comment]
PIng.

**Comment by ReubenBond** [comment]
I don't think this should be a 'FrameworkReference' or SDK, since those are not composable, or at least not as easily. It's much easier to install a regular package. I don't see any upside to making it an SDK (i.e, something which can live on the `<Project>` element.

**Comment by galvesribeiro** [comment]
Yeah, with the recent enhancements on the (almost) empty Program.cs, I would rethink this. The goal was to basically remove all the boilerplate that used to exist on it (or in the startup.cs) but I think if we proper support the Minimal APIs APIs, we should be good with packages.

**Comment by ReubenBond** [comment]
Closing, since this is in main now.
