### ISSUE TITLE
OperationCancelledException during graceful shutdown while ASP.NET Cohosting

### ISSUE THREAD

**Issue by highlyunavailable** [dotnet/orleans#6688]
I'm writing a simple app that uses ASP.NET Cohosting and when I use ctrl-C to shut down the program, I get:

```
info: Orleans.Hosting.SiloHostedService[0]
      Orleans Silo stopped.
Unhandled exception. System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Thingie.Program.<Main>(String[] args)
```

The Main method is very simple and cloned from the ASP.NET Cohosting sample with a few mods to use the default Startup class.

```c#
        public static Task Main(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
                .UseOrleans(siloBuilder =>
                {
                    siloBuilder
                    .UseLocalhostClustering()
                    .Configure<ClusterOptions>(options =>
                    {
                        options.ClusterId = "Thingie";
                        options.ServiceId = "Backend";
                    })
                    .Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Loopback);
                })
            .RunConsoleAsync();
```

There are no other hosted services, it's entirely a blank ASP.NET Core 3.1 webapp template otherwise.

**Comment by ReubenBond** [comment]
You can call `.Configure<HostOptions>(options => options.ShutdownTimeout = TimeSpan.FromMinutes(1))` to give the silo more time to shutdown gracefully. The default for that value (which is from `Microsoft.Extensions.Hosting`) is only 5 seconds, but the silo now has some delays during shutdown to give clients extra time to drain requests and that makes graceful shutdown take longer than 5 seconds.

**Comment by highlyunavailable** [comment]
That was it. It might be good to update the example, but that did indeed fix the problem. Thanks so much! Do you want me to close this or should it be used to track example changes?

**Comment by ReubenBond** [comment]
Would you be able to submit a PR to update the sample? I would greatly appreciate it

**Comment by highlyunavailable** [comment]
Okay, I submitted a PR. It doesn't update the base version (it's still 3.0) but I'm not sure that matters since it's the copy/paste that was my problem.
