### ISSUE TITLE
DisposeAsync not handled properly in Orleans 3.2.2

### ISSUE THREAD

**Issue by DiAifU** [dotnet/orleans#6699]
Hi,

I just tried updating to Orleans 3.2.2 from 3.1.6, and I am getting errors during silo shutdown with this exception :

```log
Application: eZ.Orleans.Silo.exe
CoreCLR Version: 4.700.20.11803
.NET Core Version: 3.1.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: '****Class Name****' type only implements IAsyncDisposable. Use DisposeAsync to dispose the container.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at Orleans.Runtime.Catalog.DestroyActivation(ActivationData activationData, CancellationToken ct)
   at Orleans.Runtime.Catalog.<>c__DisplayClass75_0.<<DeactivateActivation>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

It was working fine before. Has anything changed in 3.2.2 or any recent versions regarding DisposeAsync ?

Thanks for your help !

Edit : To clarify, this error happens on differents classes which are all injected though Orleans DI and implements IAsyncDisposable

**Comment by ReubenBond** [comment]
In 3.x, activation are disposed using `IDisposable` only, not `IAsyncDisposable`.
For 4.x, `IAsyncDisposable` is used if the container supports it.

If you are willing to submit a PR against the 3.3.0 branch, we could possibly squeeze support for `IAsyncDisposable` in to the next release. The relevant areas in code are Catalog.DestroyActivation, and ActivationData.Dispose/DisposeAsync

**Comment by DiAifU** [comment]
Got it, thanks for the answer.
I see it's already implemented for 4.x, so for now, I'll follow the pattern with both IDisposable and IAsyncDisposable.
I'm wondering though how can I never have seen this exception with previous versions. Has anything changed regarding this ? Or does it simply mean DisposeAsync was never called ?

**Comment by DiAifU** [comment]
Implementing IDisposable in the concerned classes solved the problem. Thanks for the answer.
