### ISSUE TITLE
Orleans Transactions Test

### ISSUE THREAD

**Issue by neilxkchen123** [dotnet/orleans#6708]
I did a simple ball experiment: both the grid and the ball are defined as grain. The grid uses a list to store the ID of the ball grain entity in its own area. Start a client to periodically call the move method of the grid to move the ball in its own area. If the ball moves outside its own area, it will delete the ball ID from the list and inform another grid to add the ball ID to its ID list.
  The grid area is 200 * 200, and the velocity of the ball in X and Y directions is 2, positive and negative random. Each grid is initially allocated one ball. If the client calls the move method of the grid every 50 ms, it only can support up to 9 grids.
  Has anyone done the relevant transaction performance test？How about its performance？ Are there any official transaction performance reports？

**Comment by neilxkchen123** [comment]
client code：
private static async Task DoClientWork(IClusterClient client)
        {
           
            List<IGridGrain> grid_list = new List<IGridGrain>();
            var tasks = new List<Task>();
            for (uint x_grid_index = 0; x_grid_index < Common.x_grid_num; x_grid_index++)
                for (uint y_grid_index = 0; y_grid_index < Common.y_grid_num; y_grid_index++)
                {
                    long grid_id = Common.GetGridId(x_grid_index, y_grid_index);
                    IGridGrain grid = client.GetGrain<IGridGrain>(grid_id);
                    grid_list.Add(grid);
                    tasks.Add(grid.Init());
                }
           
            await Task.WhenAll(tasks);

            tasks.Clear();
            while (true) {
                try
                {
                    foreach (var grid in grid_list)
                    {
                        tasks.Add(grid.Move());
                    }
                    await Task.Delay(TimeSpan.FromSeconds(0.05));
                }
                catch (Orleans.Transactions.OrleansTransactionAbortedException e)
                {
                    Console.WriteLine($"\n  worker: transaction exception: {e}");
                }
                catch (System.TimeoutException e)
                {
                    Console.WriteLine($"\n  worker: timeout exception: {e}");
                }
            }
        }

grid grain move func code:
async Task IGridGrain.Move()
        {
            long grid_id = attr.PerformRead(x => x.Id).Result;

            var tasks = new List<Task>();
            List<long> ball_list = InnerGetBallList();
			int ball_count = ball_list.Count;
            if (ball_count > 2)
            {
                // Console.WriteLine($"\n\ngrid_id = {grid_id} ball_count = {ball_count}\n\n");
            }
            foreach (var ball_id in ball_list)
            {
                tasks.Add(GrainFactory.GetGrain<IBallGrain>(ball_id).Move());
               // Console.WriteLine($"\n\ngrid_id = {grid_id} move ball_id = {ball_id}\n\n");
            }
            await Task.WhenAll(tasks);

            tasks.Clear();
            foreach (var ball_id in ball_list)
            {
                long in_grid_id = await GrainFactory.GetGrain<IBallGrain>(ball_id).GetInGridId();
                if (grid_id != in_grid_id)
                {
                    tasks.Add(ball_arr.PerformUpdate(x => x.remove(ball_id)));
                    tasks.Add(GrainFactory.GetGrain<IGridGrain>(in_grid_id).AddBall(ball_id));
                }
            }
            await Task.WhenAll(tasks);

            return;
        }

**Comment by ReubenBond** [comment]
That `Task.Result` call at the top of `Move()` will not be helping your test. The whole method execution should likely be inside one PerformUpdate call and the grains should be marked `[Reentrant]` since all state is protected by the transaction lock.
Where are you storing the state in this test? Is the code available somewhere?

**Comment by neilxkchen123** [comment]
I store the state in memory. The test code github address：https://github.com/neilxkchen123/orleans_ball_test
