### ISSUE TITLE
Failing reminders

### ISSUE THREAD

**Issue by dodyg** [dotnet/orleans#6712]
I got this error multiple times. Is this type of failing reminder (every 3 minutes) to be expected as a normal course of operation? 

```
fail: Orleans.Runtime.ReminderService.LocalReminderService[102915]
      Could not deliver reminder tick for [http://feeds.twincities.com/mngi/rss/CustomRssServlet/569/201033.xml, GrainReference:*grn/9FC29EAA/0000000000000000000000000000000003ffffff9fc29eaa-0x5ECFF8A5, 00:03:00, 2020-08-25 09:00:26.339 GMT, cbc7a65a-0c80-4c1a-b68f-9541c07522b3, 76, Ticking], next 8/25/2020 9:03:56 AM.
      System.TimeoutException: Response did not arrive on time in 00:00:30 for message: Request S127.0.0.1:11111:336041936*stg/0/00000000@S00000000->S127.0.0.1:11111:336041936*grn/9FC29EAA/00000000@5d6415b6 #440. Target History is: <S127.0.0.1:11111:336041936:*grn/9FC29EAA/00000000:@5d6415b6>.
         at Orleans.Runtime.ReminderService.LocalReminderService.LocalReminderData.OnTimerTick()
```

The relevant code is [here](https://github.com/dodyg/practical-aspnetcore/blob/3.1-LTS/projects/5-0/orleans/rss-reader-3/Program.cs#L190)

**Comment by zeus82** [comment]
Is it possible that your call to `feedFetcherGrain.FetchAsync(feedSource);` (line 225) is taking a really long time to complete?

We'd had error similar to that, and they were either related to a call that was taking a really long time to complete, or a deadlock.  You don't see that error while debugging because when you are debugging, the timeout is set to infinity.

You can change that behaviour by doing this:

```
siloBuilder.Configure<SiloMessagingOptions>(o => o.ResponseTimeoutWithDebugger = TimeSpan.FromMinutes(1));
```

**Comment by dodyg** [comment]
> Is it possible that your call to feedFetcherGrain.FetchAsync(feedSource); (line 225) is taking a really long time to complete?

In this case the feed is broken http://feeds.twincities.com/mngi/rss/CustomRssServlet/569/201033.xml. So it really shouldn't take  *that* long. What's the definition of "really long time"?

**Comment by zeus82** [comment]
really long time would be more than 30 seconds in this case.  It could also be that some other method is your grain is taking more than 30 seconds to return, and because grains are single threaded that would also cause you to get a timeout exception.

**Comment by dodyg** [comment]
The grain just has a single http call per url to fetch an RSS feed. Let me adjust the HttpClient timeout to 10 seconds (the default is 100 seconds) and see if I still get this time out.

**Comment by dodyg** [comment]
![reminder](https://user-images.githubusercontent.com/1761249/91298325-1b7a3980-e7a0-11ea-9d03-38273323afc4.png)

Still the same error. This time the feed https://www.seattletimes.com/mariners/feed/ is actually working.

**Comment by dodyg** [comment]
![reminder-2](https://user-images.githubusercontent.com/1761249/91298502-7318a500-e7a0-11ea-92ce-78c9a76985da.png)

**Comment by zeus82** [comment]
Try marking your grain as `[Reentrant]` ([documented here](https://dotnet.github.io/orleans/Documentation/grains/reentrancy.html)).  If that fixes your problem, then there is a method in your grain that is taking a long time to complete.

**Comment by ReubenBond** [comment]
Apologies, @dodyg, I meant to reply yesterday. The sample uses a single grain to fetch all feeds, so if one feed is slow (eg, I see one timing out after 100s here) it will hold up all of the others. I opened a PR with a resolution that works for me: https://github.com/dodyg/practical-aspnetcore/pull/239

**Comment by dodyg** [comment]
>The sample uses a single grain to fetch all feeds

This is not the case though. I use a single grain to obtain the source feed info but  `var feedFetcherGrain = _grainFactory.GetGrain<IFeedFetcher>(feedSource.Url);` is a string grain.

```
  public async Task ReceiveReminder(string reminderName, TickStatus status)
    {
        _logger.Info($"Receive {reminderName} reminder");

        if (_runningReminders.TryGetValue(reminderName, out var reminder))
        {
            if (!reminder.FetchTask.IsCompleted)
            {
                _logger.LogInformation(
                    "Received reminder {ReminderName}, but previous refresh task is still running and has been running for {TaskRunTime}",
                    reminderName,
                    reminder.FetchDuration.Elapsed);
                return;
            }
        }

        var feedSourceGrain = _grainFactory.GetGrain<IFeedSource>(0)!;

        var feedSource = await feedSourceGrain.FindFeedSourceByUrlAsync(reminderName);

        if (feedSource is object)
        {
            _logger.Info($"Fetching {feedSource.Url}");
            var feedFetcherGrain = _grainFactory.GetGrain<IFeedFetcher>(feedSource.Url);
            var task = feedFetcherGrain.FetchAsync(feedSource);
            task.Ignore();
            var stopwatch = reminder.FetchDuration ?? new Stopwatch();
            stopwatch.Restart();
            _runningReminders[reminderName] = (task, stopwatch);
        }
    }
```

**Comment by dodyg** [comment]
> The sample uses a single grain to fetch all feeds,

What I did is use a single grain to handle all the reminders and then *await* the fetcher grain that use string key grain. ` var feedFetcherGrain = _grainFactory.GetGrain<IFeedFetcher>(feedSource.Url);` 

So that's where I made the mistake I think because the reminder grain got tied up. Would putting [Reentrant] on reminder grain solve this issue as well?

```
  public async Task ReceiveReminder(string reminderName, TickStatus status)
    {
        _logger.Info($"Receive {reminderName} reminder");

        var feedSourceGrain = _grainFactory.GetGrain<IFeedSource>(0)!;

        var feedSource = await feedSourceGrain.FindFeedSourceByUrlAsync(reminderName);

        if (feedSource is object)
        {
            _logger.Info($"Fetching {feedSource.Url}");
            var feedFetcherGrain = _grainFactory.GetGrain<IFeedFetcher>(feedSource.Url);
            await feedFetcherGrain.FetchAsync(feedSource);
        }
    }
```

**Comment by ReubenBond** [comment]
> So that's where I made the mistake I think because the reminder grain got tied up. 

Yes, exactly

> Would putting [Reentrant] on reminder grain solve this issue as well?

It would in this case, but you would still see timeout exceptions when a grain takes longer than the configured ResponseTimeout (default 30s). I don't recommend having long-running reminders in the foreground, preventing other methods from running. Ideally, we should provide helpers to make this kind of thing easier to get right.

**Comment by dodyg** [comment]
I am planning to add 3000 RSS feed sources. They will need to run in the background in various intervals but let's just say it's every 15 minutes. What's a good design for this? Shall I create 3000 reminder grains or shall I do something more complicated?

**Comment by ReubenBond** [comment]
3000 reminder grains ought to work fine for that

**Comment by dodyg** [comment]
In a single sever or probably dual servers setup, what's the approximate number of reminders before we have to worry about it? A million? millions? higher? lower?

**Comment by sergeybykov** [comment]
Years ago, we tested and found that we could easily hold on the order of 300K -500K reminders per silo. I imagine it should be much higher now with all the performance and memory management improvements both in Orleans and .NET Core.

**Comment by dodyg** [comment]
OK thanks - I'll file this under "don't worry about it".
