### ISSUE TITLE
Convert code generator to C# Source Generator

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#6717]
We can delete a bunch of MS Build code and simplify the Orleans.sln build process

For reference, here is a PR for a similar conversion: https://github.com/ReubenBond/Hagar/pull/68

**Comment by jsteinich** [comment]
Would this introduce a dependency on .net 5? At least for compiling?

**Comment by ReubenBond** [comment]
Yes, for compilation. It will introduce a dependency on the newer SDK once it's released, but not at runtime. Hopefully that's not a significant problem, but this issue is up for discussion either way.

**Comment by ifle** [comment]
Is Orleans will continue support the .NET framewrork?

**Comment by ReubenBond** [comment]
Yes, we target .NET Standard 2.0 - that wouldn't change even if we do implement this feature. This just means that you need a newer .NET SDK to build your apps, but not to run them. You already need .NET Core SDK to build an Orleans app today, because the existing code generator is a .NET Core app

**Comment by ifle** [comment]
Yes we running .NET Framework 4.7.2 and have plans migrate to .NET 5. 
But for now is very important for us is supporitng of .NET Framework.

**Comment by ReubenBond** [comment]
Implemented in #6925
