### ISSUE TITLE
Nuget Package upgrade

### ISSUE THREAD

**Issue by eramosr16** [dotnet/orleans#6720]
Any plans of do a Nuget dependencies upgrade, some of them started getting older.

**Comment by sergeybykov** [comment]
Do you have some specific packages in mind? As a general rule, we prefer to lag behind quite a bit, so that we don't force people to use latest and greatest versions of dependencies, while at the same time allowing them to upgrade when they are comfortable.

**Comment by eramosr16** [comment]
Yeah, I was thinking in upgrade the AWS dependencies, I forked the repo and I did it for the AWS but then, Orleans Providers gave me an error with the version. Not sure if I have to upgrade that one too.

**Comment by sergeybykov** [comment]
I had no problem upgrading them for 3.3.0 - https://github.com/dotnet/orleans/pull/6723. Can you double-check that this will be sufficient?

**Comment by sergeybykov** [comment]
Also submitted #6726 to upgrade AWS packages in `master`.

**Comment by eramosr16** [comment]
Thanks man.
I appreciate your help.
Keep up the good work.

Best.

**Comment by sergeybykov** [comment]
[3.3.0](https://github.com/dotnet/orleans/releases/tag/v3.3.0) was released with updated AWS packages.
