### ISSUE TITLE
Is a project with ~100 billion grains feasible with Orleans?

### ISSUE THREAD

**Issue by ChadJessup** [dotnet/orleans#6733]
Hi there,
I'm looking at choosing a tech for some distributed simulation work, and I couldn't find any details on upper limits that might exist in the Orleans framework?

Based on my limited knowledge of Orleans, I think I'd roughly be looking at:
1. 100 billion grains
1. On average each grain would only talk to ~10,000 other grains in a one-way fashion.
1. Mainly grains would be talking to the same set of grains - so silo/host affinity would be nice
1. Each grain would be very simple, doing very basic math.
1. Data would most likely be streaming in, 24/7.
1. Messages would be extremely small, probably a byte or two.
1. This this would be a lot of compute, but if specific silos can be offlined, and grains not rebalanced, or affinity honored, that would be fantastic to the budget.

It's certainly a big project in scale, so I'm hoping Orleans doesn't have any inherent caps in the amount of grains/silos?

I also realize that I would most likely need to condense the amount of grains (have 1 grain act like a 1,000 units for example) - knowing the bounds will help with design.

Thanks!

**Comment by sergeybykov** [comment]
There are two numbers of grains to keep in mind - 1) active at the same time and 2) existing in the system. 2) doesn't really matter, 1) does. 100 billion of active grains sounds way too many. Considering that .NET memory manager starts showing signs or trouble, last I looked, at object counts per process on the order of 10 million. And each grain takes more than one object.

For each grain to be actively talking to 10,000 other grains also sound too chatty.

I think the right approach is the one you mentioned at the end - to use grains as partitions to hold much larger number of items. That would be much more feasible and performant.

Similarly with messaging. Sending 1-2 byte messages is way too expensive. If you can batch a large number of such messages in few bigger messages between the partition grains, that should be orders of magnitude more efficient.

**Comment by ChadJessup** [comment]
Sounds good! Thank you!
