### ISSUE TITLE
Possible approaches to multitenancy

### ISSUE THREAD

**Issue by dazinator** [dotnet/orleans#6736]
Hi,

We have some asp.net core web api's, serving traffic to multiple tenants. Currently they also perform long running jobs on background threads, and I am thinking of offloading that processing into to an orleans cluster.

We currently have asp.net core middleware that establishes the "tenant" based on the host / domain name from the request.

Ideally we want this context (the tenant) to flow through to our cluster, so that when the grain is activated, we can inject tenant specific services. This is because different tenants might have different `IConfiguration` and other things that effects how the grain should process a given task - so being able to configure / inject the tenant specific services removes all that logic / concerns from grain code.

I'm wondering if orleans has some extensivitiy points where I could:

1. With the orleans client - ensure some additional context / "header" value is sent with all requests to the cluster - this will indicate the current tenant id. (p.s see below - perhaps it would be better to use the existing "clusterId" for this?)
2. Within the orleans cluster, before any grain is activated:
    - I'd like to lazy cache a "child container" for the tenant with that tenant id.
    - I'd like to activate the grain using the tenants "child container" rather than the application wide container.

Also - my assumption is that if I did all of that, I'd be able to:

1. Add new tenants at runtime. (My extension running in the cluster would lazily build the new container for that tenant on a cache miss, and add it to the cache, then use that to activate the grain)
2. Use DI with grains, but as they are activated from the tenant's child container, they could now have the tenant specific services injected.

A few things I am uncertain with this approach:

1. If I wanted to delete a tenant from my database, how would I `dispose` of that tenants lazy cached child container (on whichever nodes that was built)
2. Do I need to create a DI scope (`IServiceProvider.CreateScope`) to activate the grain within, and then Dispose() of that DI scope once the grain has finished? (Analagous to `HttpContext.RequestServices` in asp.net core which serves a single http request and gets disposed afterwards) - or are grains always activated in the root scope?
2. Should / Could "ClusterId" be used as a mechanism to isolate different tenants? (We don't use blue / green deployments)
    - If on the asp.net core side, I created a ClusterClient per tenant, and set the ClusterId to that tenant's tenant ID - can I take advantage of this on the cluster side when activating the grain to lazily cache an IServiceProvider for that cluster ID representing that tenants services?

I like the idea of using a different `ClusterId` per tenant in that conceptually it would act as a sandbox between tenants grains leading to better tenant isolation? However I am not sure if that's really an abuse of this feature.. I am aware if would only isolate communication between grains, and would not isolate for example, storage.

**Comment by benjaminpetit** [comment]
The `ClusterId` is here to identify an Orleans cluster, it's configured on each silo and each client. If you deploy several silos/clients with different `ClusterId`, they will not be able to talk to each other.

To send "headers" along Grain messages, you can use the `RequestContext`, see [doc here](http://dotnet.github.io/orleans/Documentation/grains/request_context.html).

In 4.0, you might be able to use a custom `IGrainActivator` to create Grain instances like you want, but it's not available in 3.x.

You might consider something more simple maybe, and use the tenant id as (or at least as part of) the Grain identity?

There is also some consideration using Orleans for long running jobs, I thinkthe is some code snipped around.

**Comment by dazinator** [comment]
@benjaminpetit thanks for the info!

> If you deploy several silos/clients with different ClusterId, they will not be able to talk to each other.

I think that's ok, as we don't want cross tenant communication - tenants should be isolated from one another.

> To send "headers" along Grain messages, you can use the RequestContext, see doc here.

Thats great - thanks I will look at that :-)

> In 4.0, you might be able to use a custom IGrainActivator to create Grain instances like you want, but it's not available in 3.x

Ok that looks promising, I'll try upgrading to 4.0 and giving that a go.

> You might consider something more simple maybe, and use the tenant id as (or at least as part of) the Grain identity?

Ok thanks - I'll look further into that!
