### ISSUE TITLE
Azure Storage Emulator executable has changed name.

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#674]
The Azure Storage Emulator changed its name somewhere around SDK v2.5 or v2.6.
The new executable name is `AzureStorageEmulator.exe`, in the same location as the previous executable, `WAStorageEmulator.exe`.

This can cause tests to fail on hosts with newer SDKs installed.

**Comment by veikkoeeva** [comment]
@ReubenBond Are the failures due to the automatic initializer no finding the exe and consequently not starting the emulator correctly?
