### ISSUE TITLE
[Question] - Is there a way to access a grain without referencing the grain interface in a client?

### ISSUE THREAD

**Issue by Ryujose** [dotnet/orleans#6741]
**Problem**

We want to use Orleans client without referencing a reference/assembly by an interface... Because we want to consume Orleans server from different apps that they aren't with the same solution, and we don't want to be dependant on one particular assembly.

For now we're using this, like the documentation shows it.

`.ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(IGrain).Assembly).WithReferences())`

**Possible solutions?** 

Three possible solutions to being communicated with the orleans client so it goes the information to one point in case that orleans client doesn't have something builded in for this.

**Possible solution 1** - Web API

**Possible solution 2** - gRPC 

**Possible solution 3** - Sockets

Any architecture recommendations for performance and scalability?

**Comment by ericgla** [comment]
https://github.com/OrleansContrib/Orleans.Http

**Comment by Ryujose** [comment]
> https://github.com/OrleansContrib/Orleans.Http

Thanks, we'll take a look on this!

**Comment by Ryujose** [comment]
That's what we were searching. Issue closed. Thanks.
