### ISSUE TITLE
Grain Identity

### ISSUE THREAD

**Issue by Mickael-Lamare** [dotnet/orleans#6744]
Hello, I tried to invoke a grain with a formatted guid containing only digits. Like so:

`var guid = Guid.Parse(Guid.NewGuid().ToString("N"));` // contains no dashes
`var grain = GrainFactory.GetGrain<IGrain>(guid);`
`var key = grain.GetPrimaryKey();` // contains dashes

As the parsed guid should be valid, I expect the grain primary key to have the exact same value.
Or maybe I missed an option in the silo configuration, it would be nice to be able to format the guid key generated if needed.

**Comment by benjaminpetit** [comment]
`key` here is of type `Guid`. "00000000000000000000000000000000" or "00000000-0000-0000-0000-000000000000" are two string representation of the same guid value.

**Comment by Mickael-Lamare** [comment]
Yes not a big deal, just a bit surprised, thanks 👍
