### ISSUE TITLE
ObjectDisposedException in Connection.cs on Silo Shutdown

### ISSUE THREAD

**Issue by JohnMorman** [dotnet/orleans#6747]
It looks like this commit may have introduced the issue
https://github.com/dotnet/orleans/commit/22f76266c8ddc62272a5792350b6f4729c7915bf#diff-48a0ebda7cb14bf627a70d0d8c07f983

Specifically the flow looks like one of the Tasks ProcessIncoming or ProcessOutgoing will see that they are canceled and will break out of their loop and call input?.Complete() or output?.Complete(). This disposes the stream's underlying CancellationTokenSource. After calling output.Complete() we call this.CloseInternal() then. 

The issue looks like in CloseInternal we check to see if the incoming and outgoing tasks are actually tasks and if they are complete. Howerver since the call to CloseInternal came from one of those tasks, it's holding the task open still and won't be marked complete. So we then call either input.CancelPendingRead() or output.CancelPendingFlush() which will then throw on the CancellationTokenSource as the .Complete() from above already disposed of the object.

We almost exclusively see this on the output stream and not the input, but I believe it should be possible to happen on both.

Example Exception with stack
ExceptionType: System.ObjectDisposedException: Exception: System.ObjectDisposedException: The CancellationTokenSource has been disposed. 
| at System.Threading.CancellationTokenSource.ThrowObjectDisposedException() 
| at System.IO.Pipelines.StreamPipeWriter.CancelPendingFlush()
| at Orleans.Runtime.Messaging.Connection.CloseInternal(Exception exception) in /source/external/src/Orleans.Core/Networking/Connection.cs:line 229

**Comment by ReubenBond** [comment]
Hi @JohnMorman, thanks for reporting that. Would you be able to PR a fix?

**Comment by JohnMorman** [comment]
Ya I should be able to, may be a week or so before I can get to it.

**Comment by JohnMorman** [comment]
My suggestion for fixing would be to change 
```
if (_processIncomingTask is Task task && !task.IsCompleted)
{
   this.Context.Transport.Input.CancelPendingRead();
}
```

to something like

```
private int inputClosed = 0;
....
if (Interlocked.Exchange(ref this.inputClosed, 1) == 0)
{
    this.Context.Transport.Input.CancelPendingRead();
}
```

for both the input and output pipes and before calling input?.Complete() doing same same interlocked exchange to ensure we can never perform both a .Complete() and .CancelPendingFlush(). An alternative that's a bit simpler is just using a single lock around the .Complete() and .CancelPendingFlush() calls and using a separate bool for input and output to determine whether one has occurred already.

**Comment by ReubenBond** [comment]
A lock sounds fine to me
