### ISSUE TITLE
[Question] Add/Remove Application-Parts during runtime

### ISSUE THREAD

**Issue by hokusp** [dotnet/orleans#6756]
Hi,

I'm working with a system where the business-logic can be updated during runtime by updating the DLL. It is also possible to add additional parts to the system as DLLs. Is it possible to add and remove/update application parts in Orleans during runtime?

After reading [this](https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability) I almost come to the conclusion that it is not really possible what I wanted to do because grains could hold instances to that business-logic that should be unloaded. Am I understanding this correctly here?

A solution would be to serialize grain-calls that involve that updateable business-logic manually but I wanted to hear if there is a better/automatic solution first. 

_Edit:_ And with more thoughts this second approach also might not be possible at all as if the grains itself store references to the business logic that should be unloaded and therefore the business-logic would never be unloaded at all. Or am I misunderstanding something here?

Thanks!

**Comment by benjaminpetit** [comment]
You are correct, it's not possible in Orleans to do that. What you will have to do is shutdown the silo, update the DLLs, then restart the silo.

All silos in the cluster don't need to have the same Grains code deployed: http://dotnet.github.io/orleans/Documentation/clusters_and_clients/heterogeneous_silos.html

**Comment by hokusp** [comment]
I see, makes sense, thanks for the clarification.
So updating with Kubernetes rolling updates it will be then.
