### ISSUE TITLE
Tests Die When IAsyncDisposable Service is Used

### ISSUE THREAD

**Issue by ThiagoT1** [dotnet/orleans#6758]
When using a Service that implements `IAsyndDisposable`, tests are crashing:

> The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.InvalidOperationException: 'Marv.Apex.Broadcast.ApexBroadcasterService<Marv.Apex.Messages.ApexEnvelope>' type only implements IAsyncDisposable. Use DisposeAsync to dispose the container.
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
>    at Orleans.Runtime.Catalog.DestroyActivation(ActivationData activationData, CancellationToken ct)
>    at Orleans.Runtime.Catalog.<>c__DisplayClass75_0.<<DeactivateActivation>b__0>d.MoveNext()
> 

Making the service `IDisposable` and calling (without awaiting) the `DisposeAsync` method works around the issue, though.

**Comment by ReubenBond** [comment]
Hi Thiago, I believe you should implement IDisposable if you implement IAsyncDisposable. That being said, Catalog should call DisposeAsync if it's supported. Are you able to make a PR against the 3.3.0 branch to implement that and help prevent people from hitting this in future?

**Comment by ThiagoT1** [comment]
Sure! Will do!

**Comment by ThiagoT1** [comment]
PR was merged.
