### ISSUE TITLE
Support serialization of DateTimeOffset for optimal performance

### ISSUE THREAD

**Issue by onionhammer** [dotnet/orleans#676]
System type DateTimeOffset may require a custom serializer for optimal performance. If you use arguments of this type a lot, consider asking the Orleans team to build a custom serializer for it.

**Comment by yevhen** [comment]
+1

**Comment by sergeybykov** [comment]
Can somebody prepare a PR for https://github.com/dotnet/orleans/blob/master/src/Orleans/Serialization/BuiltInTypes.cs?

**Comment by onionhammer** [comment]
I can work on this tomorrow probably, if no one beats me to it

**Comment by yevhen** [comment]
go for it! :)

2015-08-06 21:21 GMT+03:00 onionhammer <notifications@github.com>:

**Comment by veikkoeeva** [comment]
+1 from me too.

**Comment by jthelin** [comment]
No test cases for this new functionality?

**Comment by jthelin** [comment]
PR #684 contains a unit test case for DateTimeOffset serialization.
