### ISSUE TITLE
Unobvious generic grain and interface matching

### ISSUE THREAD

**Issue by Ilchert** [dotnet/orleans#6766]
It is not clear, that type parameter names of grain interface and its implementation must have the same name otherwise, you can get an error `Cannot find an implementation class for grain interface`.
Example:
```C#
public interface IG<T> :IGrain
{
}
public class G<TOtherName>: Grain, IG<TOtherName>
{
}
```
Because orleans uses names for grain interface identity and register grain implementation [twice ](https://github.com/dotnet/orleans/blob/82560d170a9d4815af9d4df35dfe58aae1e4dcaa/src/Orleans.Core/Runtime/GrainInterfaceMap.cs#L169) (for interface and its generic version) different names break `GrainInterfaceMap`.
It happens because different interfaces have the same `interfaceTypeKey` and different `interfaceId `

In provided example for `G<TOtherName>`:

grain interface (`typeof(G<TOtherName>).GetInterfaces()[0]`) `interfaceId` will be calculated as a hash of `IG<TOtherName>`
 generic version (`typeof(G<TOtherName>).GetInterfaces()[0].GetGenericTypeDefinition`) `interfaceId` will be calculated as hash of `IG<T>`
and `interfaceTypeKey` will be `IG'1`

**Comment by ReubenBond** [comment]
Interesting bug, thanks for reporting, @Ilchert. Are you able to take a shot at fixing this?

**Comment by Ilchert** [comment]
Hello, here is a pull request. #6777
