### ISSUE TITLE
PubSub with Grains

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#6772]
Hi,

I have a few grains that are used so often for queries that I have a performance issue in some cases, therefore I would like to cache them.

My idea was to use a local cache and to send out invalidation messages. But these messages need to be reliable, otherwise a sequence of API calls within a short duration can lead to unexpected results, e.g. when the state is updated on server 1 but not invalidated on server 2, before the next update is received at server 2.

My first idea was to use Grain Observers and it works. But they are not reliable. How can I implement a pubsub mechanism in Orleans? I would need a local grain per silo and a pubsub grain, but Grain services do not have an identity. So what is their purpose anyway?

**Comment by cecilphillip** [comment]
Have you considered using orleans streams?

**Comment by SebastianStehle** [comment]
No, it would have the same problem, that producers are decoupled from the consumer.

I need something like databases, where the master sends the message to all replicas before confirming the write.

e.g. in Pseudo code:

```
public async Task DoAsync(Command command)
{
   var domainObject = grainFactory.GetGrain<IDomainObject>(command.Id);

   await domainObject.ExecuteAsync(command);
   await cache.InvalidateAsync(command.Id);

  // All caches are purged now.
}
```

**Comment by JorgeCandeias** [comment]
Do you need transactional consistency, or is "as fast as network allows" eventual consistency good enough for you?

If so, have you considered the reactive caching pattern? With that pattern, the replica grain instances will internally long-poll the main grain for new data and pro-actively bring it over, for as long as incoming requests keep them alive, using a version scheme. So you can use the master grain instance for writes and the replica grain instances for cached reads, where the latter ones self-update as fast as the cluster allows. There is the risk of stale data if the cluster goes into an unhealthy state but the system will recover as fast as it can without intervention. The replica grains can be regular grains (with any placement or pool configuration, it doesn't matter) or stateless workers (so each node will eventually get a replica and keep it updated for you before the client even asks).

If not, then you can simulate transactional-ish behaviour here in a couple of ways:
* A saga pattern from the master grain invalidating everything (or refusing to accept the new value if it can't). This would require the replicas registering with the master grain so it has control of invalidation, just like a master-replica database setup would. The drawback is that a transient failure in a replica would case a transient failure in the master grain too (but maybe that's what you want?). The saga pattern would ensure that the master grain plus all replica grains remain "locked" until the invalidation message goes through them all and then unwinds. The grains cannot be re-entrant for this to work.

* A version scheme, where you have a light-weight grain control what the latest version of some data is, with RequestNext/Accept methods or similar. A bit like a database sequence. Upon attempt to update the master grain, your stateless code can request a new version number, spin new master and replicas grain instances using that number as part of the key and then ask the version grain to accept that version number. The version grain will ignore it if it already has a newer one. Requests to read from the replicas need to ask the version grain instance first for the latest number. The drawback is that this puts a lot of pressure on the version grain. However that pressure will be on a method that returns a single integer with no further operations, so you may get away with it. The version grain will be at the same sharding level as the grains it represents, probably using the same key, minus the version itself.

* There's always Orleans Transactions if your setup supports it but it sounds like overkill.

The general idea here, is to not treat grains like *data* that need to be updated from the outside, but instead treat them like *actors* that can update themselves.

**Comment by SebastianStehle** [comment]
I know that I cannot achieve 100% consistency, but it should be good enough. The cache times are short anyway as it is only needed to keep the spikes low.

So I am only looking for a pubsub implementation. I need one grain per silo and a way to send them messages.

**Comment by JorgeCandeias** [comment]
> So I am only looking for a pubsub implementation.

Isn't a pub-sub model inherently opposite to the consistency you want, due to being decoupled by design?

> I need one grain per silo and a way to send them messages.

Okay, the hard "one-grain-per-silo" requirement is important as this will stop you from using a vanilla saga model.
Commuting this to "around-one-grain-per-silo-more-or-less" would make life easier.

However, you can still have a one-to-many propagation model without overlap (and that specific requirement), if you combine the reactive caching pattern (which is as aggressive on the network as you'll get bar streaming) with a replica-master version checklist.

E.g.
1) Have a regular grain as a master and stateless worker (1) as a replica.
2) The stateless workers reactive-poll the master grain as usual, however each individual worker also sends a unique stable guid along with the poll that identifies itself, e.g. it's unique "key" in the cluster. It doesn't matter what the guid is as long as it's unique for each instance.
3) Have the master manage registrations for Id/Version tuples. The master keeps a checklist of what ids have what version, which it can know via the reactive polling calls. The replicas keep polling the master for the new data as normal, supplying both their current version and their unique guid, so the master can distinguish between them (they're stateless workers after all, they don't have identity otherwise). The checklist is maintained, and added to, dynamically as polls come through. This is, in principle, very similar to what the grain observer manager used to do, but adapted to allow for stateless workers.
3) When the master receives a call to change its data, it will do so internally so the reactive polls can pick it up on a round-trip, but not yet resolve the call. On each reactive poll round-trip the master also keeps track of what replicas have what version. Once all the replicas have the expected version, the call on the master resolves. This makes sure that no other update call on the master can start before the prior one completes, and, with it, all the reactive polls complete propagating and acknowledging.
4) Replica grains, upon graceful deactivation, should be nice and notify the master grain that they will no longer be polling, so the master grain can take them off the "expectation" checklist.

On a healthy cluster and assuming no additional work within the polling calls, this model will resolve very quickly, due to the active polling resolving immediately from master to replica and the following polls doubling as an acknowledgement message, used to update the checklist.

If a healthy node collapses however, an expected reactive poll from a previously healthy stateless worker grain will not come through and will hinder the resolving of the master call and possibly fault it. Therefore the master is responsible for keeping track, along with the version checklist, of the time a previously healthy poll is no longer active, and to take them out the checklist after a configured amount of time, preferably less than the orleans timeout, say 10s or so. A healthy reactive poll loop shouldn't be taking any longer than a second to re-establish itself, usually in the low millis if no other work is hindering it.

I've done something similar in the past, the structural code is simpler than it sounds, maybe less words than this long reply. This is probably as good as you're going to get for one-to-many stable propagation without committing to transactions, and still holding to the "one-replica-per-silo" requirement. Unless there's some other magic I'm not yet aware of.

You can make this model even more aggressive by separating the flow between a prepare step and a commit step, but you'll be reinventing the two-phase commit protocol at that point.

**Comment by SebastianStehle** [comment]
You are right, the pubsub model is not the right pattern name for that. It is more an acknowledged write like in some databases, where a majority of the members need to acknowledge the write to be successful.

The polling idea would definitely work, that is true, but the performance depends on the poll interval, which is not that great. On the other side if you would have a lot of node you can batch invalidation messages.

I guess you mean something like this:

Not sure, what you need the version for. This might contains errors, I have written it with Notepad++ ;)

```
public class InvalidationGrain
{
	private static readonly TimeSpan Timeout = TimeSpan.FromMilliseconds(500);
	private static readonly TimeSpan SiloIsDeadTimeout = TimeSpan.FromSeconds(10);
	private readonly ConcurrentDictionary<(Guid SiloId, string Key), TaskCompletionSource<bool>> pendingAcks = new ConcurrentDictionary<...>();
	private readonly ConcurrentDictionary<Guid, DateTime> targets = new ConcurrentDictionary<...>();
	
	public Task ConfirmAsync(Guid siloId, string key)
	{
		Confirm(siloId, key);
		 
		IamAlive(siloId);
		
		return Task.CompletedTask;
	}
	
	public Task<List<string>> GetPendingKeys(Guid siloId)
	{
		var keys = pendingAcks.Where(x => x.SiloId == siloId).ToList();
		
		IamAlive(siloId);
		
		foreach (var key in keys)
		{
			Confirm(siloId, key);
		}
		
		return Task.FromResult(keys);
	}
	
	public Task RegisterAsync(Guid siloId)
	{
		IamAlive(siloId);
		
		return Task.CompletedTask;
	}
	
	public Task UnregisterAsync(Guid siloId)
	{
		targets.Remove(siloId);
		
		foreach (var key in pendingAcks.Where(x => x.SiloId == siloId).ToList())
		{
			Cancel(siloId, key);
		}
		
		return Task.CompletedTask;
	}
	
	public async Task InvalidateAsync(string key)
	{	
		if (!targets.Any())
		{
			return;
		}
		
		using (var cts = new CancellationTokenSource(Timeout)
		{
			var aliveTargets = GetTargets();
			
			await Task.WhenAll(aliveTargets.Select(x => InvalidateAsync(x, key, cts.Token)));
		}
	}
	
	private Task InvalidateAsync(Guid siloId, string key, CancellationToken ct)
	{
		if (targets.TryGetValue(siloId, out var target))
		{
			var completion = TaskCompletionSource<bool>();
			
			pendingAcks.Add((siloId, key), completion);
			
			using (ct.Register(() => 
			{
				Cancel(siloId, key);
				
				return await completion.Task;
			});
		}
		
		return Task.CompletedTask;
	}
	
	private IEnumerable<ITarget> GetTargets()
	{
		var now = DateTime.UtcNow;
		
		foreach (var (siloId, lastSeen) in targets)
		{
			var timeToLastSeen = now - lastSeen;
			
			if (timeToLastSeen > SiloIsDeadTimeout)
			{
				IamDead(siloId);
			}
			else
			{
				yield return GrainFactory.GetGrain<ITarget>(siloId);
			}
		}
	}
	
	private void IamAlive(Guid siloId)
	{
		targets[siloId] = DateTime.UtcNow;
	}
	
	private void IamDead(Guid siloId)
	{
		targets.Remove(siloId);
	}
	
	private void Confirm(Guid siloId, string key)
	{
		if (pendingAcks.TryRemove((siloId, key), out var ack))
		{
			ack.TrySetResult(true);
		}
	}
	
	private void Cancel(Guid siloId, string key)
	{
		if (pendingAcks.TryRemove((siloId, key), out var ack))
		{
			ack.TrySetCancelled();
		}
	}
}
```

**Comment by SebastianStehle** [comment]
I was just thinking that I only need a `IPlacementDirector` that only creates grains locally. Then I activate a grain with random id on each node and use it to register it at the mangement grain.

**Comment by JorgeCandeias** [comment]
> The polling idea would definitely work, that is true, but the performance depends on the poll interval, which is not that great.

I was suggesting *reactive polling / caching*, not regular polling. Do you known this pattern?

> I was just thinking that I only need a `IPlacementDirector` that only creates grains locally. Then I activate a grain with random id on each node and use it to register it at the mangement grain.

You could do that, but then you lose the ability to automatically shard the grain graph based on the key alone, unless, maybe, you use composite keys.

Your code is more or less what I had in mind, and it will probably work. Except:

1) It focuses on having the master grain *invalidating* the replicas, rather than having the replicas preemptively *refreshing themselves* and acknowledging the completion of that fact over time.
2) It cares about "silos" in grain code, so it breaks the illusion of location transparency that Orleans provides. The replica keys would fulfill that role.
3) The versions aren't required in your code but they help a lot with troubleshooting what replica has what. They are required for reactive caching.

The above are opinions, so take them with some salt.

An aside, you don't need to use concurrent collections inside regular grain code, as the activation scheduler already guarantees turn-based concurrency, so there's no need to waste cycles on top of that.

I'm completing some code to demonstrate what I had in mind.

**Comment by JorgeCandeias** [comment]
I was writing this as a formal sample so forgive me the long form, a lot of this is comments and logging.

Abstractions:
```csharp
    public interface IMainGrain : IGrainWithGuidKey
    {
        public Task<Guid> SetAsync(MyItem item);

        public Task<(Guid, MyItem)> GetAsync();

        [AlwaysInterleave]
        public Task<(Guid, MyItem)> PollAsync(Guid replicaId, Guid version);

        [AlwaysInterleave]
        public Task UnregisterAsync(Guid replicaId);
    }

    public interface IReplicaGrain : IGrainWithGuidKey
    {
        public Task<(Guid, MyItem)> GetAsync();
    }

    [Immutable]
    public class MyItem
    {
        public MyItem(Guid value)
        {
            Value = value;
        }

        public Guid Value { get; }

        public override string ToString()
        {
            return Value.ToString("D", CultureInfo.InvariantCulture);
        }
    }
```

`MainGrain` implementation:
```csharp
    public class MainGrain : Grain, IMainGrain
    {
        private readonly ReactiveOptions _options;
        private readonly ILogger _logger;
        private readonly Dictionary<Guid, ChecklistItem> _checklist = new Dictionary<Guid, ChecklistItem>();

        public MainGrain(IOptions<ReactiveOptions> options, ILogger<MainGrain> logger)
        {
            _options = options?.Value ?? throw new ArgumentNullException(nameof(options));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        private string _name;
        private Guid _key;
        private MyItem _item;
        private Guid _version = Guid.NewGuid();

        private TaskCompletionSource<bool> _propagated;
        private TaskCompletionSource<(Guid, MyItem)> _future = new TaskCompletionSource<(Guid, MyItem)>();

        public override Task OnActivateAsync()
        {
            base.OnActivateAsync();

            _name = GetType().Name;
            _key = this.GetPrimaryKey();

            // keep the checklist healthy
            RegisterTimer(_ => CleanupAsync(), null, TimeSpan.FromSeconds(1), TimeSpan.FromSeconds(1));

            return Task.CompletedTask;
        }

        private Task CleanupAsync()
        {
            // elect expired items
            var now = DateTime.UtcNow;
            var elected = ArrayPool<Guid>.Shared.Rent(_checklist.Count);
            var count = 0;
            foreach (var item in _checklist)
            {
                if (!item.Value.IsActive && item.Value.Expiry <= now)
                {
                    elected[count++] = item.Key;
                }
            }

            // remove expired items
            if (count > 0)
            {
                for (var i = 0; i < count; ++i)
                {
                    _checklist.Remove(elected[i]);
                    _logger.LogWarning("{GrainType} {GrainKey} removed expired replica {ReplicaId}", _name, _key, elected[i]);
                }

                // complete any stuck set operation now
                TryCompleteSet();
            }

            ArrayPool<Guid>.Shared.Return(elected);
            return Task.CompletedTask;
        }

        /// <summary>
        /// This method is never re-entrant.
        /// </summary>
        public Task<(Guid, MyItem)> GetAsync()
        {
            return Task.FromResult((_version, _item));
        }

        /// <summary>
        /// This method is never re-entrant.
        /// </summary>
        public async Task<Guid> SetAsync(MyItem item)
        {
            // update the internal value
            _item = item;
            _version = Guid.NewGuid();
            _propagated = new TaskCompletionSource<bool>();

            _logger.LogInformation(
                "{GrainType} {GrainKey} setting state to ({Version}, {Item})",
                _name, _key, _version, item);

            // propagate the new value
            Pulse();

            // attempt an early complete in case there are no replicas
            TryCompleteSet();

            // wait for propagation to complete
            try
            {
                await _propagated.Task.ConfigureAwait(true);
                return _version;
            }
            finally
            {
                _propagated = null;
                _logger.LogInformation(
                    "{GrainType} {GrainKey} completed setting state to version {Version}",
                    _name, _key, _version);
            }
        }

        /// <summary>
        /// This method is always re-rentrant.
        /// </summary>
        public async Task<(Guid, MyItem)> PollAsync(Guid replicaId, Guid version)
        {
            _logger.LogInformation(
                "{GrainType} {GrainKey} handling reactive poll from replica {ReplicaId} with replica version {Version}",
                _name, _key, replicaId, version);

            // register the replica as-needed
            if (!_checklist.TryGetValue(replicaId, out var registration))
            {
                _checklist[replicaId] = registration = new ChecklistItem();
            }

            // keep track of what this is known to have right now
            registration.Version = version;
            registration.IsActive = true;

            try
            {
                // quick path for outdated replica
                if (version != _version)
                {
                    return (_version, _item);
                }

                // this replica is up-to-date so attempt to complete a waiting set operation
                TryCompleteSet();

                // reactive polling path for up-to-date replica
                // this method is reentrant so this await will unblock the grain for other calls including the cleanup timer
                return await _future.Task.WithResultOnTimeoutAsync((version, null), _options.PollingTimeout).ConfigureAwait(true);
            }
            finally
            {
                // keep track of this replica now entering a renewal period
                registration.IsActive = false;
                registration.Expiry = DateTime.UtcNow.Add(_options.RenewalTimeout);
            }
        }

        /// <summary>
        /// This method is always re-entrant.
        /// </summary>
        public Task UnregisterAsync(Guid replicaId)
        {
            // attempt to remove the replica from the checklis
            if (_checklist.Remove(replicaId))
            {
                // attempt to complete any stuck set operation
                TryCompleteSet();
            }

            return Task.CompletedTask;
        }

        private void Pulse()
        {
            // propagate the current data to any waiting reactive polls
            _future.TrySetResult((_version, _item));
            _future = new TaskCompletionSource<(Guid, MyItem)>();
        }

        private void TryCompleteSet()
        {
            // check if there is a set operation waiting for confirmation
            if (_propagated is null) return;

            // check if all known replicas are known to be updated
            var okay = true;
            foreach (var item in _checklist)
            {
                if (item.Value.Version != _version)
                {
                    okay = false;
                    break;
                }
            }

            // release the set operation now
            if (okay)
            {
                _propagated.TrySetResult(true);
                _logger.LogInformation(
                    "{GrainType} {GrainKey} completed propagation of version {Version} to {ReplicaCount} replicas",
                    _name, _key, _version, _checklist.Count);
            }
        }

        private class ChecklistItem
        {
            public Guid Version { get; set; }
            public bool IsActive { get; set; }
            public DateTime Expiry { get; set; }
        }
    }
```

`ReplicaGrain` implementation:

```csharp
    [StatelessWorker(1)]
    public class ReplicaGrain : Grain, IReplicaGrain
    {
        private readonly ReactiveOptions _options;
        private readonly ILogger _logger;

        public ReplicaGrain(IOptions<ReactiveOptions> options, ILogger<ReplicaGrain> logger)
        {
            _options = options?.Value ?? throw new ArgumentNullException(nameof(options));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        private string _name;
        private Guid _key;
        private Guid _replicaKey = Guid.NewGuid();
        private Guid _version;
        private MyItem _item;

        private IMainGrain _main;

        public override async Task OnActivateAsync()
        {
            await base.OnActivateAsync().ConfigureAwait(true);

            _key = this.GetPrimaryKey();
            _name = GetType().Name;

            // keep the main grain proxy handy
            _main = GrainFactory.GetGrain<IMainGrain>(this.GetPrimaryKey());

            // get the current version of data
            (_version, _item) = await _main.GetAsync().ConfigureAwait(true);

            // setup a reactive poll against the main grain - note that timers are always re-entrant
            RegisterTimer(async _ =>
            {
                _logger.LogInformation(
                    "{GrainType} {ReplicaKey} starting reactive poll with version {Version}",
                    _name, _key, _version);

                bool okay = false;
                try
                {
                    var (version, item) = await _main.PollAsync(_replicaKey, _version).ConfigureAwait(true);
                    if (version != _version)
                    {
                        _item = item;
                        _version = version;

                        _logger.LogInformation(
                            "{GrainType} {GrainKey} {ReplicaKey} received new data version {Version}",
                            _name, _key, _replicaKey, _version);
                    }
                    else
                    {
                        _logger.LogInformation(
                            "{GrainType} {GrainKey} {ReplicaKey} resolved poll without a new data version",
                            _name, _key, _replicaKey);
                    }
                    okay = true;
                }
                finally
                {
                    // backoff from the next poll as not to hammer a recovering target
                    if (!okay)
                    {
                        _logger.LogWarning(
                            "{GrainType} {GrainKey} {ReplicaKey} backing off for {Timeout} after the reactive poll faulted",
                            _name, _key, _replicaKey, _options.BackoffTimeout);

                        await Task.Delay(_options.BackoffTimeout).ConfigureAwait(true);
                    }
                }
            }, null, TimeSpan.FromTicks(1), TimeSpan.FromTicks(1));
        }

        public override async Task OnDeactivateAsync()
        {
            await _main.UnregisterAsync(_replicaKey).ConfigureAwait(true);

            await base.OnDeactivateAsync().ConfigureAwait(true);
        }

        public Task<(Guid, MyItem)> GetAsync()
        {
            return Task.FromResult((_version, _item));
        }
    }
```

Assorted:
```csharp
    public class ReactiveOptions
    {
        public TimeSpan PollingTimeout { get; set; } = TimeSpan.FromSeconds(20);
        public TimeSpan RenewalTimeout { get; set; } = TimeSpan.FromSeconds(10);
        public TimeSpan BackoffTimeout { get; set; } = TimeSpan.FromSeconds(1);
    }

    public static class TaskExtensions
    {
        public static Task<T> WithResultOnTimeoutAsync<T>(this Task<T> task, T result, TimeSpan timeout)
        {
            // validate arguments
            if (task is null) throw new ArgumentNullException(nameof(task));
            if (timeout <= TimeSpan.Zero) throw new ArgumentOutOfRangeException(nameof(timeout));

            // quick path for completed task
            if (task.IsCompleted) return task;

            // defer to the async state machine
            return InnerWithResultOnTimeoutAsync(task, result, timeout);
        }

        private static async Task<T> InnerWithResultOnTimeoutAsync<T>(Task<T> task, T result, TimeSpan timeout)
        {
            // this token ensures the timer is removed from the timer queue if the user task completes first
            using var cancellation = new CancellationTokenSource();

            // this task will complete when the user delay is reached
            var delay = Task.Delay(timeout, cancellation.Token);

            // wait for either task to complete
            var first = await Task.WhenAny(task, delay).ConfigureAwait(false);

            // check if the user task completed first
            if (first == task)
            {
                // propagate any exceptions now
                return await task.ConfigureAwait(false);
            }
            else
            {
                // otherwise return the default result
                return result;
            }
        }
    }
```

**Comment by SebastianStehle** [comment]
> I was suggesting reactive polling / caching, not regular polling. Do you known this pattern?

Yes, this is what my code does. It uses polling for the invalidation keys and would then use the normal domain object grain to retrieve the value. But the point is: I need to wait for the acknowledgment and this depends on the polling interval. Or I solve it like in your case with long polling.

> You could do that, but then you lose the ability to automatically shard the grain graph based on the key alone, unless, maybe, you use composite keys.

In my example I only share invalidation keys for the caches, not state. Therefore I do not need sharding.

**Comment by JorgeCandeias** [comment]
I looked at your code, and although I haven't tested it, I think it can work just fine.

My question is, won't this do exactly what the Orleans SMS provider does out-of-the-box, given SMS is a coupled provider? 

Meaning, a call from a publisher to an SMS stream will fail if even one subscriber fails. If you don't care about automatic sharding at all (or you do but are happy with composite keys), you can have your api code call a regular replica grain (non-stateless-worker) with some stable id that's unique to the silo, and where that replica is decorated with the built-in `[PreferLocalPlacement]`. That replica then subs to SMS as normal. It then becomes indirectly coupled to the publisher by means of SMS itself just calling grains methods directly and propagating exceptions to the publisher. That way the publisher knows when the invalidation message has gone through to all subscribers (the publish task just completes) or it has failed to reach at least on one (the publish task throws), and if so, retry until it does.

For adapting to cluster changes, the replica itself can have some basic detection code upon activation that checks whether that replica instance belongs to that silo (maybe compare its own id to the current silo id) and if not, then just unsubscribe from the stream and deactivate itself.

I think this could save you a lot of code if a "coupled" but still brokered pub sub model is what you're looking for.

**Comment by SebastianStehle** [comment]
> Meaning, a call from a publisher to an SMS stream will fail if even one subscriber fails. If you don't care about automatic sharding at all (or you do but are happy with composite keys), you can have your api code call a regular replica grain (non-stateless-worker) with some stable id that's unique to the silo, and where that replica is decorated with the built-in [PreferLocalPlacement]. That replica then subs to SMS as normal. It then becomes indirectly coupled to the publisher by means of SMS itself just calling grains methods directly and propagating exceptions to the publisher. That way the publisher knows when the invalidation message has gone through to all subscribers (the publish task just completes) or it has failed to reach at least on one (the publish task throws), and if so, retry until it does - without allowing the next update operation to start.

Yepp, was not aware that the stream provider works like that. I thought it is decoupled.

**Comment by JorgeCandeias** [comment]
The SMS provider in particular is a coupled provider. It's the only one I'm aware of at this time. It just forwards messages from the publisher to all subscribers via the Orleans messaging system. The subscriptions themselves are still persisted via the `PubSubRendevousGrain`s onto whatever persistence provider you have, so that bit is reliable. However the messages are not, so it falls upon the publisher to catch exceptions and retry. It also falls upon the publisher to serialise the calls if that happens to be important, like in your case. Overall the code for a setup like this will be minimal, less than either of our samples.

**Comment by SebastianStehle** [comment]
I tested it in the same repository.

What is strange with streams is that when one silo leaves the cluster there is a chance that no silo actually retrieves an update, I guess this happens when this silo fails first.

There is also no exception in this case.

**Comment by JorgeCandeias** [comment]
That is odd. Let me play around with your code. Also, I'm not sure why you are using an explicit broker grain with streams, is this something that is important to your application architecture?

**Comment by SebastianStehle** [comment]
No, that's not needed, I was copy and pasting the other implementation to the new folder and then made the adjustments.

**Comment by JorgeCandeias** [comment]
I've PR'd an alternate scenario onto your repository. I didn't want to change existing code but I had to rename a couple of classes due to conflicts.

**Comment by sergeybykov** [comment]
For "one grain per silo" cases you can also consider leveraging grain services. They are quirky, and @ReubenBond wanted to replace then with regular grains for a long time now. But as they are today they have the lifecycle of a silo, and that can be useful for building per-silo caches with consolidated refresh and invalidation logic.

**Comment by SebastianStehle** [comment]
@JorgeCandeias Thank you very much, perhaps we should add them to: https://github.com/OrleansContrib/DesignPatterns

@sergeybykov : If I understand grain services correctly, I cannot talk with them. So the only option is polling, so that the grain service is asking my broker grain for updates. Right?

**Comment by JorgeCandeias** [comment]
You can directly address a grain service instance via `IGrainServiceFactory.MakeGrainServiceReference(int typeData, string systemGrainId, SiloAddress siloAddress)` and providing the appropriate parameters. This goes against the principle of location transparency that Orleans attempts to provide, which is why I hadn't suggested it before, but it's there if you really want it.

**Comment by sergeybykov** [comment]
>@sergeybykov : If I understand grain services correctly, I cannot talk with them. So the only option is polling, so that the grain service is asking my broker grain for updates. Right?

Not exactly. A grain service can be invoked, but that requires its silo address (as I see @JorgeCandeias already mentioned). However, once you have a grain reference to a particular grain service instance (on a particular silo), you should be able to call it directly. If each instance were to register with your broker upon its silo startup and provided a grain reference to call it, then the broker should be able to call them.

If a silo goes down, the grain reference won't work anymore. But the pattern with expiring registrations where each  subscriber (in this case each grain service instance) regularly reconfirms that it's still there, can help with that.
