### ISSUE TITLE
Add System.Text.Json support for Orleans.Persistence.AdoNet

### ISSUE THREAD

**Issue by wanton7** [dotnet/orleans#6775]
Don't replace Json.NET but add System.Text.Json as alternative JSON (de)serializer for Orleans.Persistence.AdoNet. With System.Text.Json it should also be possible to stream serialization to avoid LOH allocations when serializing large state to JSON.

**Comment by ReubenBond** [comment]
Hi @wanton7, is this something that you may be able to contribute?

I think it would be worth having a generic interface for storage serializers. @benjaminpetit is working on one.

**Comment by wanton7** [comment]
Having generic interface for storage serializers would have also fixed problem I was having using Json.NET serializer that would have been easy to solve with System.Text.Json.

It seems that SqlChars doesn't support stream but SqlBytes seems to. So I'm not sure if we can actually get streaming to work with System.Text.Json serializer. Also it will output UTF-8 bytes so that is another problem. I'm not sure if there are any other options to remove LOH allocations when serializing and storing to nvarchar column in SQL Server.

**Comment by wanton7** [comment]
After a bit of research SQL Server 2019 supports UTF-8 for varchar columns and those should support SqlBytes and SqlBytes supports a Stream. So it might be possible to get write streaming to work when using SQL Server 2019 and UTF-8 varchar columns. I don't see how to get write streaming to work with nvarchar column.

**Comment by veikkoeeva** [comment]
@wanton7 The simplest way to add this would be to switch the JSON provider at https://github.com/dotnet/orleans/tree/master/src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider. This might deployments using JSON.NET, so yet more option would be add a similar one for `System.Text.Json` and add it to external configuration.

I would like to link this to https://github.com/dotnet/orleans/pull/6752.
