### ISSUE TITLE
Delete old grains' state

### ISSUE THREAD

**Issue by turowicz** [dotnet/orleans#6778]
Are there any patterns for clearing out the state of old grains, that haven't been used since a custom TimeSpan?

**Comment by sergeybykov** [comment]
I can think of a reminder registered for this purpose that would wake up a grain to check if it's time to delete its state. Obviously, requires some timestamp of last access saved to storage.

If you have such timestamps in storage and the storage is queryable, it's likely more efficient to perform a cleanup operation directly in storage.

**Comment by turowicz** [comment]
Good idea @Sergey-Grudskiy !
