### ISSUE TITLE
Documentation issue for IHostEnvironmentStatistics?

### ISSUE THREAD

**Issue by Kritner** [dotnet/orleans#6779]
Looking at the below line in the xml documentation

https://github.com/dotnet/orleans/blob/f372b6771ede39a0050b22a63277ce74443b0b96/src/Orleans.Core.Abstractions/Statistics/IHostEnvironmentStatistics.cs#L14

in comparison to the value being returned when observing as in this screenshot:

![image](https://user-images.githubusercontent.com/8814983/95799067-84bafb00-0cc1-11eb-8567-4aef943b3ea5.png)

Makes me think either the xml comment is incorrect, and it should be 0-100, rather than 0.0f-1.0f, or the current implementation of `UsePerfCounterEnvironmentStatistics` is incorrect.  I'm leaning toward it just being a documentation issue considering the fact that the OrleansDashboard lists the CPU utilization correctly and not offset by a factor of 100.

**Comment by ReubenBond** [comment]
Is this on Linux or Windows, @Kritner?

**Comment by Kritner** [comment]
FWIW here's a repro showing at least the `UsePerfCounterEnvironmentStatistics` I'm using from "out of the box" for windows is using 0-100 rather than 0-1:

https://github.com/Kritner-Blogs/OrleansGettingStarted/releases/tag/v0.60

I'm currently multiplying the value from `CpuUsage` by 100 to get a percentage, and my CPU is running hotter than iron man after getting hit by thor's mjolnir ;)

![](https://user-images.githubusercontent.com/8814983/96037334-b358e300-0e33-11eb-95c2-de6ae3bee104.png)

**Comment by ReubenBond** [comment]
Thanks for the repro, could you submit a PR to update the doc comment?
