### ISSUE TITLE
System.NullReferenceException at Orleans.Runtime.OutgoingCallInvoker.Invoke

### ISSUE THREAD

**Issue by irwang** [dotnet/orleans#6782]
Service always show null reference exception in OutgoingCallInvoker.Invoke randomly, while from this exception I really can not tell which object is null:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.Runtime.OutgoingCallInvoker.Invoke()
   at Orleans.Runtime.OutgoingCallInvoker.Invoke()
   at Orleans.Runtime.OutgoingCallInvoker.Invoke()
   at Orleans.Runtime.GrainReferenceRuntime.InvokeWithFilters(GrainReference reference, InvokeMethodRequest request, InvokeMethodOptions options)`

is there any suggestion to help diagnosic this kind of issues?

**Comment by ReubenBond** [comment]
@irwang could you share the code for your outgoing call filters?

**Comment by irwang** [comment]
I delare a Grain and calling its function then it throws this exception, the code works like this:

public async Task<T> StartGrain<T>(string key, Func<T, Task> initialMethod)
 where T : IGrainWithStringKey
{
var grain = clusterClient.GetGrain<T>(key);
await initialMethod(grain).ConfigureAwait(false);
return grain(); //from stack trace, this is the line throw above exception.
}

so I am confuse how to identity which obj is null?

**Comment by irwang** [comment]
close this as i found mitigate solution

**Comment by irwang** [comment]
close this for mitigation
