### ISSUE TITLE
Question: Will Orleans be "ported" to .Net 5.0?

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/orleans#6784]
Thanks for an amazing project!

.Net 5.0 is about to be released in November, and then according to the .Net roadmap .Net 6.0 (LTS) is to be released 2021 in November. The current Orleans release is not kind of "compatible" with .Net 5.0+ profile (getting errors with the build system trying to use .Net 5.0 with Orleans).

Is there a roadmap to "port" Orleans to .Net 5.0?

Thanks

**Comment by ReubenBond** [comment]
Orleans should work on .NET 5 already - what errors are you seeing? There are some features that we will need to wait for to support or use, such as C# 9 records and Source Generators. We can't support those in a stable package before .NET 5 is released, since they require pre-release packages

**Comment by jan-johansson-mr** [comment]
Sorry, __my mistake__.
Your comment made me go through my solution dependencies, and I had an "Event" (private) NuGet package, making use of Orleans events, and that one had netstandard2.1 profile, making my solution blow up! Rebuilding the "Event" NuGet for a .Net 5.0 profile with Orleans (and using that NuGet with my solution) made the problem go away. In short, Orleans already works fine on .Net 5.0 profile.
Thanks :-)
