### ISSUE TITLE
Microsoft.Orleans.Streaming.EventHubs not pushed to Ci nuget

### ISSUE THREAD

**Issue by fuocor** [dotnet/orleans#6787]
the Microsoft.Orleans.Streaming.EventHubs package is not pushed to the `https://orleans.pkgs.visualstudio.com/orleans-public/_packaging/orleans-builds/nuget/v3/index.json` nuget feed

**Comment by fuocor** [comment]
Any movement on this?

**Comment by ReubenBond** [comment]
Hi @fuocor - apologies for the slow response. Looking at the build artifacts in the CI feed, I also don't see the package. I'm taking a look.

**Comment by ReubenBond** [comment]
The package name is very unintuitive: it's Microsoft.Orleans.OrleansServiceBus. We ought to change that for the next major release.
