### ISSUE TITLE
Question: Is telemetry with Orleans aligned with open telemetry

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/orleans#6790]
Hi,

I want to start using telemetry throughout, and with that I'm curious if the telemetry support in Orleans is aligned with open telemetry. Also, is there a sample for an implementation with Orleans show casing telemetry?

Thanks

**Comment by ReubenBond** [comment]
Is OpenTelemetry in a production-ready state? I think after .NET 5.0 releases and the changes to Activity are stable, we can adopt it more actively within Orleans. There is an issue on distributed tracing in Orleans: https://github.com/dotnet/orleans/issues/4992

**Comment by jan-johansson-mr** [comment]
Thanks Reuben,
Will monitor the thread, and see when it'll be ready for production!
