### ISSUE TITLE
GrainReferenceKeyStringConverter could not be resolved

### ISSUE THREAD

**Issue by ZeBobo5** [dotnet/orleans#6794]
On latest version, on master branch, in Orleans.Clustering.AdoNet project, GrainReferenceKeyStringConverter could not be resolved for AdoNetClusteringTable.

Application lock. Nothing respond.

**Comment by ReubenBond** [comment]
@ZeBobo5 can you show me how you reproduce this? I am looking at the source where all dependencies are registered (DefaultClientServices & DefaultSiloServices), and I see that it is being registered in both.

**Comment by ZeBobo5** [comment]
Sample : https://github.com/ZeBobo5/orleans-issues-6794
Tested nd error on netcoreapp3.1 and net5.0

**Comment by ReubenBond** [comment]
I couldn't reproduce this on 3.4.1. It's possible that the CI build had some outdated packages. Apologies for the very slow response.
