### ISSUE TITLE
Save grains to files

### ISSUE THREAD

**Issue by turowicz** [dotnet/orleans#6797]
Is it possible to persist actors as files on disk? Currently I'm using the ADO.NET providers for on-premise deployments of my product but I have found SQL to be quite slow for binary handling and I would prefer the grains to simply live as json files on C drive. Is there a provider for this?

cc @ReubenBond

**Comment by turowicz** [comment]
These are smart cache grains used for reporting. It is not a problem if the state is lost.

**Comment by SebastianStehle** [comment]
I think there is no provider yet, but It is very likely less than 50 Lines of code to write something like this ;)

But the problem is: How to transfer the state from one node to another? The only advantage is when a gain is recreated on the same node, but how likely is that?

**Comment by turowicz** [comment]
Good question. My on-premise deployments are running in a single node mode.
