### ISSUE TITLE
Best way to implement resource governor pattern?

### ISSUE THREAD

**Issue by EricGriffith** [dotnet/orleans#6798]
In question #2662 there was discussion on how to limit access to a particular API on a cluster-wide, per-user level.

I would like to implement a way to limit concurrent access to an API on a purely cluster-wide level.  We've previously used a work around based on StatelessWorkers, but this doesn't work cluster-wide and the limit cannot be adjusted dynamically.

In 2662, a resource governor pattern was mentioned as an option for this problem:

> There is a "resource governance" pattern for this kind of throttling scenarios which employs a fixed set of non-reentrant grains per target resource, and all requests to the resource are forwarded via the 'resource governor' grains. For example, it is used to restrict the number of open connections to a SQL database.

I'd like to implement this pattern.  Is there a recommended best way to implement it?  Are there any examples of it?

**Comment by SebastianStehle** [comment]
Is this not relatively easy? You need a grain per user and it needs two methods:

```
Task<bool> RequestStarted(Guid id);
Task RequestFinished(Guid id);
```
In RequestStarted it adds a new request to a dictionary with a timestamp, if the list has not reached its capacity limits. Otherwise it just returns false.

in RequestFinished you remove a request from the dictionary.

Futhermore I would add a timer to delete very old requests, so that it cannot block in case of any strange errors.

**Comment by EricGriffith** [comment]
@SebastianStehle Thanks for the quick reply, but I think that may be too simplistic or perhaps I am not properly understanding what you are suggesting.

At a high level, I want to be able to recreate the effect of the [&lt;connectionManagement&gt;](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/connectionmanagement-element-network-settings?redirectedfrom=MSDN) configuration element that lets you limit the number of parallel connections to a given endpoint.  And, similar to this element, I don't want the limit to be a compile time constant.  Ideally it should also be changeable after initialization as well.

As described in #2662, the idea is that there would be a resource governor grain that would broker access to the resources and there would be N resource grains, each representing one parallel connection to the resource.

Similar to the &lt;connectionManagement&gt; element, I would expect (except in the case of severe delays) the fact that there is a resource broker to be transparent to users of the resource.  That is, resource users should just await a call to the resource by awaiting a method on the resource governor, which eventually succeeds or times out.  Behind the scenes, the resource governor would queue the request until there is a resource grain available, use that resource grain to make the actual request, and then return the response.  Importantly, the resource user would not need to worry about trying to secure a resource grain, handling the case when one was not available, and so on.

I ask the question because it's a bit unclear to me how the resource manager should create and maintain the state of the individual resource grains and handle the immediate or delayed execution of the requests to the resource.

**Comment by SebastianStehle** [comment]
Yes, my idea is just like a semaphore. It does not protect the limited resource, but is a way to track the number of parallel requests. In the end I would rather fail instead of queuing up everything and have a little bit of timeout or so like this:

```


[AlwaysInterleave]
class ResourceProtector 
{
    private readonly Dictionary<Guid, DateTime> runningRequests = new ...;
    private readonly List<(Guid Id, TaskCompletionSource<bool> Waiting)> waitingRequests;
    private readonly int maxRequests;
    
    public async Task OnActivateAsync()
    {
       // Read max requests from DB or so
    }
    
    public async Task<bool> TryGetResource(Guid requestId, int timeout)
    {
        if (runningRequests.Count < maxRequests) 
        {
            runningRequests[requestId] = DateTime.UtcNow;
            return true;
        } 
        else
        {
            var tcs = new TaskCompletionSource<bool>();
            
            waitingRequests.Insert(0, (requestId, tcs));
            try
            {
        
                using (var cts = new CancellationTokenSource(timeout))
                {
                    using (tcs.Register(() => tcs.TrySetCompleted(false)))
                    {
                        var acquired = await tcs.Task;
                        
                        if (acquired && runningRequests.Count < maxRequests)
                        {
                            runningRequests[requestId] = DateTime.UtcNow;
                            return true;
                        }
                        
                        return false;
                    }
                }
            } 
            finally 
            {
                waitingRequests.RemoveAt(x => x.Id == requestId);
            }
        }
    }

    public Task ReleaseResource(Guid requestId)
    {
        runningRequests.Remove(requestId);
        
        if (waitingRequests.Count > 0)
        {
            waitingRequests.Waiting.TrySetCompleted(true);
        }
        
        return Task.Completed;
    }
}
```

I have written it with notepad++, so it contains errors very likely. But something like this can help to reduce the maximum number of requests on a resource.

**Comment by alyaros** [comment]
Option A: You can create stateless worker with max count. (If you can work without state)

Option B (example on DB access Repository) : Have Single RepositoryGrain that implements IRepository and in each of his methods it just forward the request to a different InnerRepositoryGrain with id 0..MaxNumberYouWishToLimit. 
You can forward requests by doing round robin between the innerRepositoryGrains.
