### ISSUE TITLE
Update dependencies to Azure SDK 2.5

### ISSUE THREAD

**Issue by maiorfi** [dotnet/orleans#68]
In order to get AzureWebSample working (although it is likely that same should be done to deploy any Orleans applications on Azure environment), it seems that several Orleans components have to be updated to correct dependencies from Azure SDK 2.5.

Please refer to #67 for details.

**Comment by veikkoeeva** [comment]
As a note, update to Azure SDK 2.5 seem to bring its own set of another problems as enumerated at [Azure SDK 2.5 and Cloud Service Diagnostics](http://gauravmantri.com/2014/11/18/azure-sdk-2-5-and-cloud-service-diagnostics/) and specifically [moving diagnostics configuration from cloud config](https://social.msdn.microsoft.com/Forums/en-US/9ad5938f-abc5-4aa6-b842-85f54a6fc717/azure-sdk-25-diagnostics?forum=windowsazuredevelopment) files  seem to cause trouble.

**Comment by sergeybykov** [comment]
I submitted a PR to move from 2.4 to 2.5 - https://github.com/dotnet/orleans/pull/72. Do we want to move or release 1.0.0 still referencing 2.4 and then move?

**Comment by gabikliot** [comment]
We removed Azure diagnostics in the Azure samples we posted here, which we ported to 2.5: (https://github.com/dotnet/orleans/tree/master/Samples/AzureWebSample)

**Comment by veikkoeeva** [comment]
Taking a peek to the tagged release, the references are to Azure SDK 2.5. Should this be closed? I need to adjust the development flow a bit, nothing big though...

**Comment by gabikliot** [comment]
Yes, closing.
