### ISSUE TITLE
Client hangs when grain call causes Silo process termination

### ISSUE THREAD

**Issue by zahirtezcan-bugs** [dotnet/orleans#6802]
We are planning to use Orleans and currently running some edge case tests with C++ interoperability. Main thing I am testing is low level failures which may cause `abort()` or `std::terminate()` to be called. In that case, as one may assume the process goes down with silo abruptly.

For example:

1. I open up my silo.
2. I connect with my client and call `IMyGrain.GoDown` function
3. One Silo process crashes, but **the Task returned from `GoDown` on client side never finishes**. No exceptions thrown.

If I reopen the silo and wait for some time, I see that client reconnects to the silo on the console logs, but Task still does not return.

Is this the expected behavior? Should I always call grains with a timeout-task, such as putting grain-call-task and timeout-task into `Task.WhenAny`?

I have prepared a sample application to demonstrate the issue and simplified things, such as localhost clustering no persistence etc. Also, instead of C++ code and failures, I simply kill the process. We may also use `Environment.Exit`, result does not change.

[OrleansSiloKill-201026.zip](https://github.com/dotnet/orleans/files/5440024/OrleansSiloKill-201026.zip)

**Comment by ReubenBond** [comment]
Hi @zahirtezcan-bugs, I ran your repro locally and the call times out after 30s, which is by design.

I believe you were likely running under a debugger: when a debugger is attached, the default timeout is increased to 30mins. You can change that by setting `ClientMessagingOptions.ResponseTimeoutWithDebugger` and `SiloMessagingOptions.ResponseTimeoutWithDebugger` on the client and silo respectively.

**Comment by zahirtezcan-bugs** [comment]
Thank you for the response. Is it possible to define messaging options for a grain type? Because some grains may require more time while others are supposed to do their work quickly.

**Comment by zahirtezcan-bugs** [comment]
@ReubenBond Is it possible to define messaging options for a grain type?
