### ISSUE TITLE
Grain activation status

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#6809]
# Use case

As discussed offline with @ReubenBond earlier Today, we have a need to know whether or not a grain is active on a given Orleans Cluster. 

# Proposal

We propose add a (extension) method to `IAddressable` with the following signature:

```cs
ValueTask<(bool activated, SiloAddress SiloAddress)> GetActivationSiloAddress(this IAddressable addressable);
```

And to `IManagementGrain` a new method would be added with similar signature to allow remote `IClusterClient` to have access to it:

```cs
ValueTask<(bool activated, SiloAddress SiloAddress)> GetActivationSiloAddress(IAddressable addressable);
```

# Developer UX

```cs
// From inside grain code
var grain = GrainFactory.GetGrain<IMyFancyGrain>(id);
var (activated, address) = await grain.GetActivationSiloAddress();

...

// From a remote IClusterClient
var mgmtGrain = GrainFactory.GetGrain<IManagementGrain>(0);
var grain = GrainFactory.GetGrain<IMyFancyGrain>(id);
var (activated, address) = await mgmtGrain.GetActivationSiloAddress(grain);
```

# Caveats

We agreed that for that to work, the developer must be aware that due to the nature of distributed systems, the state (activated or not) may change by the time that method call is made and the caller receive the return. That means the return of this method should not be considered a strong consistent view of the grain activation but instead, as an approximated state of it.

**Comment by galvesribeiro** [comment]
cc: @benjaminpetit

**Comment by benjaminpetit** [comment]
I am fine having such method on the `IManagementGrain` (we already have `IManagementGrain.GetGrainActivationCount` that could be used to see if the grain is activated?). 

How the `StatelessWorker` case will be handled though? 

I am a bit against adding the extension method to `IAddressable`, so it is not _too much_ discoverable. I understand that some scenario might need this information, but it should really be a corner case, and we don't want developer to rely on this information too much, as there is caveats as you noted.

**Comment by galvesribeiro** [comment]
Yeah, I'm ok with only having it exposed on `IManagementGrain` so it covers both internal and external scenarios anyway.

@ReubenBond ?

**Comment by galvesribeiro** [comment]
> How the StatelessWorker case will be handled though?

That would always return true in that case.

**Comment by ReubenBond** [comment]
I am fine with `IManagementGrain` being used for both cases. It might lead to more bottlenecking than required, though - having a thin wrapper around the directory APIs (which can use the local cache) is more scalable.

I suggest we could also expose an interface for performing the lookups. An extension method is not the way to to.
