### ISSUE TITLE
Serialization exception

### ISSUE THREAD

**Issue by shallowtek** [dotnet/orleans#6811]
Hello there. I am looking for more information on the Serialization exceptions I am seeing in our Prod ENV that seem to be causing Timeouts.

**Serialization Exception Example**
`Unexpected token '54' introducing type specifier`

**Timeout Exception Example**
`Response did not arrive on time in 00:00:30 for message: Request Silo1_IP:20028:341518350*grn/652E3695/71ccddb6@6e7b228f->Silo2_IP:20028:341518345*grn/32CBE9A1/00000000+147.226.159.102@6a218290 #6427964: . Target History is: <Silo2_IP:20028:341518345:*grn/32CBE9A1/00000000+147.226.159.102:@6a218290>. `

The issue does seem to be related to high load and I have seen mention of this issue elsewhere on this Github.

Our message sizes for some of are largest documents can be as large as 1MB but most average around 50KB.

We currently run 9 Silo's on VM Scalesets hosted on Azure Service Fabric. We have a fairly standard configuration and it is only these intermittent exceptions causing issues.

The Scaleset metrics are all stable so it does not seem like a scaling issues. The 9 Silo's should be fine for the throughput.

Any help would be great and I am happy to share additional logs of necessary.

I also have a Microsoft Support ticket open but they recommended to message here.

Regards,
Matt

**Comment by ReubenBond** [comment]
Hi @shallowtek, issues like this are usually caused by a mismatch in types on the various clients/silos in the cluster.
Which version of Orleans are you running?

**Comment by shallowtek** [comment]
Hi Reuben. We have version 2.4.1 across our projects. Could you explain what you mean by a mismatch in types?
Thanks!

**Comment by ReubenBond** [comment]
If you add or remove a property on a type, then it will change how it's serialized and this can break serialization (which is not version-tolerant).

Please upgrade at least to the latest 2.4.x patch release. Eg, 2.4.2 contains several bug fixes which can address the problem you are seeing. I recommend upgrading before digging too deep.

**Comment by shallowtek** [comment]
Ah I see. We will upgraded as you suggest and see if this resolves the issues we are seeing. Thank you for your time!

**Comment by shallowtek** [comment]
I have actually seen a few more timeouts with no serialization exceptions thrown. The CPU and Memory of VM appear to be stable at this time also. The cluster reported no health events either.

I am trawling through one of the VM's event viewers to see what was going on. I can see the azure diagnostic heartbeat messages with a service fabric bootstrap and some security messaged before event.
![image](https://user-images.githubusercontent.com/31650721/98437540-de54f080-20da-11eb-83d8-1b3593bc6143.png)

Here is a view of Administrative events. Does anything stand out to you as suspect?
![image](https://user-images.githubusercontent.com/31650721/98437581-3c81d380-20db-11eb-9714-2ef24f2b4e7b.png)
