### ISSUE TITLE
Is the task scheduler reentrant?

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#6817]
Hello,

I have a question. I am using Dataflow library together with a grain. 

The last step in the pipeline has the task scheduler set to the scheduler of the grain, something like that.

```
public class MyGrain : Grain
{
    public override Task OnActivateAsync()
    {
		var step1 = new TransformBlock<int, int>();
		var step2 = new TransformBlock<int, int>();
		
		var scheduler = TaskScheduler.Current;
		
		var step3 = new ActionBlock<int>(..., new ExecutionDataflowBlockOptions
		{
			Scheduler = scheduler
		});
		
		step1.LinkTo(step2);
		step2.LinkTo(step3);
    }
}
```

But it behaves sometimes as if the grain is reentrant, which is definitely not the case.

**Comment by ReubenBond** [comment]
The Task scheduler executes each task one-by-one, to completion, and there is no parallelism there. *However* people often misunderstand what that means. A `Task` from the perspective of the .NET `TaskScheduler` is a synchronous block of code. An asynchronous method which has await points in it is comprised of several `Task` instances which are each scheduled on the `TaskScheduler`.

So in your case, those blocks will execute in an interleaved fashion. I'm not sure how else it could work.

**Comment by SebastianStehle** [comment]
Makes sense, but what is the correct way to implement that? Even if we do not use the Dataflow library.

I remember an issue which mentions that timers have the same problem.

**Comment by srollinet** [comment]
What I do usually in timers, is to create an "internal interface" for my grain, and I use it to make a regular method call to my grain

    public interface IInternalExampleGrain: IExampleGrain
    {
        Task DoSomething();
    }

    public class ExampleGrain: Grain, IInternalExampleGrain 
    {
        Task IInternalExampleGrain.DoSomething()
        {
            //Do something
            return Task.CompletedTask;
        }
        
        .....
    }

Now, you can call `await this.AsReference<IInternalExampleGrain>().DoSomething` to schedule the call on the grain.

I'm interested to know if there is an other way to do it.
