### ISSUE TITLE
Create grains that wrap tcp and udp connections

### ISSUE THREAD

**Issue by mika76** [dotnet/orleans#6819]
I think it would be a great idea to have build in grains which wrap comms with actual tcp and udp sockets (managing closures, errors, etc..) - kind of like akka.net's system.tcp and system.udp. I understand this can be created by each person but it can get quite complex to handle and would probably be best created by the knowledgable people developing Orleans.

In my case I have custom IOT hardware which communicates over tcp and udp.

**Comment by sergeybykov** [comment]
Do you mean this for outgoing TCP/UDP connections?

**Comment by mika76** [comment]
@sergeybykov well I would say for both/either incoming or outgoing. Basically just a wrapper around comms through tcp/udp but neatly wrapper into a grain and message communications for sending/receiving messages, connections, error/fault handling and especially opening and closing sockets.

**Comment by sergeybykov** [comment]
I'm personally of the opinion that incoming TCP/UDP connection are better to terminate at the dedicated frontend layer. That has a number of benefits, security is just one of them, over opening inbound sockets ad-hoc on backend servers. I realize there are scenarios where frontends might be excessive, but I've not seen them really in my experience.
