### ISSUE TITLE
Codegen with `record` in interface results in error if in sibling folders (dotnet 5)

### ISSUE THREAD

**Issue by withinboredom** [dotnet/orleans#6822]
While trying to create a simple project to reproduce the issue, I somehow fixed the issue by moving the `record` to a different namespace. I thought I'd report it in case anyone else runs into the same issue and has a way to reproduce and/or can fix it the same way.

Error (sorry I lost the logs):

`CodeGen<interface> does not implement the interface <interface>`

In output window:

`Type <record> does not exist in namespace <namespace>`

I tried:
- Clean and rebuild

**Comment by withinboredom** [comment]
So, that fixed compilation, but now seeing the same error in the client.

Reproduction:

1. Create a GrainInterfaces project from https://dotnet.github.io/orleans/docs/tutorials_and_samples/tutorial_1.html
2. Add a new folder: `folder1`
3. Add another folder: `folder2`
4. Add a file in folder1: `IContactGrainInterface.cs`
5. Add a file in folder2: `ContactRecord.cs`

Contents of `IContactGrainInterface.cs`:

```csharp
using System;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Test.folder2;

namespace Test.folder1
{
    public interface IContactGrainInterface
    {
        Task<ImmutableList<ContactRecord>> GetContact();
    }
}
```

Contents of `ContactRecord.cs`:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Test.folder2
{
    public record ContactRecord(string Name, string Email);
}
```

It appears that the two files being in sibling folders causes the issue.

**Comment by withinboredom** [comment]
This is the message I'm seeing in the project when setting codegen to trace:

```
ProcessSerializableType skipping abstract type GrainInterfaces.Contacts.Contact
```

The record isn't an abstract type, and I'm not sure why it's saying that, yet

**Comment by withinboredom** [comment]
After adding a bit more logging to the `ValidForKnownTypes()` function, I see it skipped for two reasons:

```
ValidForKnownTypes not adding type GrainInterfaces.Contacts.<invalid-global-code> because implicitly declared
ValidForKnownTypes not adding type GrainInterfaces.Contacts.Contact because TypeKind.Error
```

**Comment by ReubenBond** [comment]
Orleans uses the C# compiler for code generation, and since there is no stable version of the C# compiler which supports records, Orleans does not yet support records. We will have to make a release to support them after .NET 5 RTMs and a stable package is released.

**Comment by withinboredom** [comment]
Yep, was just about to say that updating `Microsoft.CodeAnalysis.CSharp.Workspaces` to `3.8.0-5.final` fixes the issue :)

**Comment by AlseinX** [comment]
Now that .NET 5.0 is formally released, is there a new version that fully supports .NET 5?
BTW, will it be another conditional build target for `net5.0` to take full advantage from .NET 5's new APIs?
