### ISSUE TITLE
Kubernets autoscaler terminate my pods even I still have some task running

### ISSUE THREAD

**Issue by clement128** [dotnet/orleans#6832]
Hi there, I am running orleans on google kubernetes cluster, I noticed that kubernets some time terminate my pods even I still have some tasking running. I had configure `terminationGracePeriodSeconds` to `180` to let the container finish current task. but seems doesn't help. My running task still got interrupted. Do I missing anything? Thanks

**Env:**
- Microsoft.Orleans.Clustering.AzureStorage: 3.3.0
- Microsoft.Orleans.Persistence.AzureStorage: 3.3.0
- Microsoft.Orleans.Server: 3.3.0
- Microsoft.Orleans.Hosting.Kubernetes: 3.3.0-rc2
- dotnet core 3.1
- GKE: 1.17.13-gke.1400
- node image: Container-Optimized OS (cos)

**Comment by ReubenBond** [comment]
Could you provide more details? What task?
If you're using the .NET Generic Host, then be sure to configure `HostOptions` `ShutdownTimeout` to a value which gives your app time to shutdown

**Comment by clement128** [comment]
hi @ReubenBond, for example, I am some image recognition task send to my grain to process. it usually take 1~3 minutes. I am running on Kubernetes cluster, sometimes my pods get terminates due autoscaler. what I want is before the pod got terminate, let it finish the task (image recognition) first. 

Yes I am using .net generic host, let me try the `ShutdownTimeout` settings. thanks

**Comment by ReubenBond** [comment]
Great, let me know if that works for you

**Comment by clement128** [comment]
I had set shutdown timeout to 3minutes, but seems silo will be stop after 35s, if I don't set it, will stop after 5s.

Do i missing anything? I ma using AspNetCoreCohosting and use same way like this (https://github.com/dotnet/orleans/blob/master/Samples/3.0/AspNetCoreCohosting/API/Program.cs#L22) to config shutdown timeout

**Comment by clement128** [comment]
It seems because of this? https://github.com/dotnet/orleans/blob/3.3.1/src/Orleans.Runtime/Configuration/Options/GrainCollectionOptions.cs#L34

**Comment by ReubenBond** [comment]
Yes, that's probably it - so you could bump that, too, if you want.

**Comment by games** [comment]
Hi @ReubenBond, just submit a fix on the sample #6841, is that a correct way?
