### ISSUE TITLE
Samples for running on Kubernetes cluster and best practices 

### ISSUE THREAD

**Issue by clement128** [dotnet/orleans#6833]
Hi there, is it possible to add a sample for how to run on Kubernetes with some documents for best practices on production.

**Comment by pollumi** [comment]
Hey,
I'm also looking for that. This would really be a huge improvement for Orleans if there were some always up to date best practice samples for Kubernetes.

This project looks very interesting, hope it will be further developed!  https://github.com/johnazariah/orleans-contrib-universalsilo
