### ISSUE TITLE
Detecting Subscribe/Unsubscribe to stream from Producer grains

### ISSUE THREAD

**Issue by highlyunavailable** [dotnet/orleans#6846]
Is it possible to add hooks on Producer grains of a stream to find out if another grain or client has subscribed or unsubscribed?

My use case is that I'm trying to build a system where I can send messages to a Client (via a stream) but I want to find out when a client subscribes so I can send it an initial state message.

As it stands I've got a race condition where the client starts up, calls the "Hi, I'm here and want initial state!" method on the grain, and then subscribes to the stream. I've had cases where messages are "lost" between the return of the initial state method and the subscription call going through, because the grain method returns and thus new methods can start, some of which send messages.

I also want to return from the "Hi, I'm here and want initial state!" method before sending the "update" messages to the client via the stream, since it depends on the initial state, so I was hoping they could somehow be combined so that the stream Subscribe call caused an initial state message from the producer/all producers that cared about subscribe calls (there would only be one in my scenario, but I can see where multiple would be fine), followed by the rest of the messages as they were produced.

Ideally, I could also detect unsubscribe calls so that the producers could update internal state, but detecting subscribe only would at least let me proceed without race conditions.

I know streams have a very loose concept of "producer" since you just start sending data to them without registering as a producer, but it's painful to use them in a way that doesn't drop messages if you want a summary initial state + an update stream.

I thought I'd found a solution via Programmatic Subscribe or `IStreamSubscriptionObserver` but I can't figure this one out. Both of these are undocumented so it's kind of trial and error to see can be done, so I'm opening this in hopes that someone else knows how to "intercept" the subscription to populate initial state on a consumer client.

**Comment by highlyunavailable** [comment]
Leaving this for others that have the same problem:

This is "documented" in https://github.com/dotnet/orleans/issues/2741 and is possible via `IStreamSubscriptionManagerAdmin`.

**Comment by highlyunavailable** [comment]
For others that have the same problem: On your producer grain, implement `IStreamSubscriptionObserver` and then your grain's `OnSubscribed` method should be called when a subscriber subscribes.

**Comment by sergeybykov** [comment]
Have you found the [tests](https://github.com/dotnet/orleans/blob/08b6e4bfc4daa75a6bba120ee464d469ae79e113/test/Grains/TestGrains/ProgrammaticSubscribe/Passive_ConsumerGrain.cs#L69) for `IStreamSubscriptionObserver`?

**Comment by highlyunavailable** [comment]
I did see those, but I think I got confused about how exactly they worked. What I'm trying to do is make sure that between some sort of method call to the grain from the client to fetch initial state (all items in a collection) and when the subscribe call completes, the collection can't be edited, as I want new items that are added to the collection to be forwarded onto the stream. It's a fairly simple thing in theory, with the only twist being that the call that would be mutating the collection is marked AlwaysInterleave. What I was trying to figure out how to do is take the Client connection and pass it to an OnConnect method in the grain (which I have right now, it sets up an Observer/callback based path), which would then use programmatic subscribe to wire the connection up and after it was wired up, return the full collection to the caller. The problem I ran into is that I can't pass the client (it's not a grain) via the method to be wired up via programmatic subscribe.

**Comment by randrewy** [comment]
Id like to bring this up once again
@sergeybykov as far as i understand `IStreamSubscriptionObserver` allows **Consumers** to be notified when a subscription is created for them.
Original question (and also mine) is the opposite: is there a way to know when someone subscribes to **Producer's** stream?

I have exactly the same issue as @highlyunavailable
My ProducerGrain holds some state and streams diffs, and my SubscriberGrain needs to get initial state to apply those diffs on top of it.

If it is done via separate method, like `ProducerGrain.GetCurrentState()` followed by a subscription to stream then some diffs may be lost. The idea is to know when a subscription happens so that `ProducerGrain` can push whole state to stream, for example.

**Comment by highlyunavailable** [comment]
I just ended up re-implementing streams but with the tradeoffs I could tolerate unfortunately. My SubscriberGrains end up in a HashSet on the ProducerGrain and Subscribe returns the state + adds them to the HashSet as well. I also use the Subscribe function to poll state on a fairly long period (60 seconds) and use it as a keepalive as well - it resets a datetime in a Subscriber Manager class that can do a Task.WhenAll over the subscribers given a Func to notify them of updates. I don't use message types either, there are just different functions on the subscribers that get called from the producer.

**Comment by randrewy** [comment]
Oh, I see. Looks realy great if you can afford long polling with high delay. 
Unfortunately I need more reactive way to accomplish the goal, very similar to `IStreamSubscriptionObserver` but for ProducerGrain to get notofied.

**Comment by highlyunavailable** [comment]
I'm not long polling though? As I said, the Producer notifies all subscribers _immediately_ upon a state change. It just has a poll for keepalive/sync state.

**Comment by randrewy** [comment]
Ah, sorry, missed that point. So you manually iterate HashSet of subscribers. 
How do you avoid deadlocks with this approach? Do you use Interleave functions?

**Comment by highlyunavailable** [comment]
> I would do the opposite: first subscribe, then manually get the state. If you keep a timestamp that is updated when the state is changed, you can then easily filter some possibly "outdated" events coming from the stream.

That's certainly a way to do it. I've ended up having to effectively re-implement streams in my app because there is super poor control over the subscribers and there's also very poor detection/handing of error conditions (e.g. 1 subscriber timing out makes message delivery fail for other subscribers) so it made more sense to just ignore streams entirely and keep my own lists of "subscribers" and call a method on them just like the SMS grain does.

**Comment by benjaminpetit** [comment]
That's why I think we should remove SMS as a stream implementation. We could still provide it via another interface, but the implementation does not really comply with the persistent implementations (EventHub, etc.).

**Comment by highlyunavailable** [comment]
An alternative (at least, a recommended pattern) should be provided then, because it feels like "observable values" is too useful a thing to ignore and for stuff like cache invalidation it is supremely valuable. I absolutely _am_ using SMS for that - I've got a "cache" grain that named based on the machine ID that starts silo (since apparently stateless workers can't be subscribers! I'd love to move away from this pattern too - stateless workers would be much nicer than honor-system grain names) and uses the streaming system to be notified of cache changes.
