### ISSUE TITLE
Is Microsoft.Orleans.CodeGenerator.MSBuild 3.3.0 support F#?

### ISSUE THREAD

**Issue by curiousBuroman** [dotnet/orleans#6849]
Is F# still supported?

Can't build GrainLib with Microsoft.Orleans.CodeGenerator.MSBuild 3.3.0 package

Compilation error:
Exc level 0: System.NotSupportedException: Projects of type .fsproj are not supported.

**Comment by ReubenBond** [comment]
It ought to work with a dummy C# project: create a .csproj which references your fsproj and add the `[KnownAssembly(typeof(SomeFSharpProjType))]`

**Comment by ReubenBond** [comment]
Closing for now, since the question is answered and the issue is inactive. Hopefully this works for you. If not, please open a new issue.
