### ISSUE TITLE
Add support for heterogeneous silo deployments

### ISSUE THREAD

**Issue by jason-bragg** [dotnet/orleans#685]
- [ ] Do not assume that all silos in the cluster have an identical set of grain classes deployed. 
- [ ] Add a list of available grain classes and their respective versions for each silo to the cluster state, so that each silo has a full map of all grain classes (and their versions) available in the system. 
- [ ] Change placement to only consider silos that have the target grain class deployed.

**Comment by NielsHoogeveen** [comment]
Has there been any follow up to this issue. since last year?

**Comment by sergeybykov** [comment]
Not yet. But we are going to bring this up soon as part of the smooth upgrade story.

**Comment by benjaminpetit** [comment]
Implemented in #2443
