### ISSUE TITLE
Is there a safe client to directly work with orleans cluster api from a non-trusted environment

### ISSUE THREAD

**Issue by chismar** [dotnet/orleans#6856]
A few years ago the company I worked at decided against orleans, in favour of a homemade platform, because there was no way to have an orleans client in a non-trusted environment (say, game client directly connected to the cluster). 

I'm curious if anything changed. Ideally, I see it akin to our way - allowing client to communicate with specific entities/grains, while sharing a root grain with the list of all other accessible ones. I would very much like to not write an additinal layer of services/fronted/replication to hide the cluster away, and just directly use everything that is available, while rejecting any illegal calls to non-shared entities from server.

**Comment by sergeybykov** [comment]
While it is technically possible nowadays to connect to silos over an untrusted network by configuring TLS, that's still not a recommended way of exposing Orleans-based services into the wild. The big issue here is that the client would have to read (and refresh) the cluster membership table and keep TCP connections open to all silos. This is neither scalable nor safe approach.

The recommended way is to co-host a HTTP or gRPC endpoint within each silo process (so no extra nodes are required), and expose their endpoints via a load balancer as a single externally accessible endpoint. [Orleans.Http](https://github.com/OrleansContrib/Orleans.Http) might help with putting the HTTP layer together.

**Comment by freever** [comment]
SignalR also works nicely as a public interface to a cluster.

**Comment by Ilchert** [comment]
@chismar because Orleans uses project badrock for connections encription, you can specify [client certificate requirements](https://github.com/dotnet/orleans/blob/8462235d77d98f284ee8870d1eb4e576a03a61f2/src/Orleans.Connections.Security/Security/TlsOptions.cs#L51) and use it to authenticate clients, but, as Sergey said, it can't be recommended way to expose orleans culster to the internet.
