### ISSUE TITLE
problem when shutdown silo

### ISSUE THREAD

**Issue by lpyvvvvvv** [dotnet/orleans#6857]
there are two silos, siloA and siloB. 
grainA on siloA.
then shutdown siloA, sometimes grainA  OnActivate on siloB before OnDeactivate on siloA.
I save data when OnDeactivateAsync, 
I read data when OnActivateAsync,
so i lost data what happend on siloA, 
Is there any way to solve this issue?

**Comment by Cloud33** [comment]
When you close silos, `OnDeactivateasync` cannot be guaranteed to trigger. This is a best effort behavior.


You may have to change the method, such as calling `WriteStateAsync` synchronously when the data changes

**Comment by sergeybykov** [comment]
+1
The general rule is to persist any state that you don't want to lose as part of the operation that updates it.

**Comment by freever** [comment]
Is there a recommended way to persist state asynchronously, so that the grain can release its caller while persisting? Or is that just generally a bad idea?

**Comment by lpyvvvvvv** [comment]
> Is there a recommended way to persist state asynchronously, so that the grain can release its caller while persisting? Or is that just generally a bad idea?

+1

**Comment by rallets** [comment]
@freever @lpyvvvvvv it depends on how "important" the grain state is. 
1) If it's not ok for your business to lose "some" state in case of a crash, then you need to persist the grain state as soon it's changed (basically before leaving the grain method), awaiting the WriteStateAsync call to the storage to be able to handle exceptions, as then they are not swallowed. 
2) Instead, if you can get the risk of loosing the grain state in case of errors (silo crash, network failures, storage provider errors, etc), you can use a timer and persist the state only every x seconds.

**Comment by sergeybykov** [comment]
Nicely stated, @rallets.
