### ISSUE TITLE
Exceptions when starting the silo

### ISSUE THREAD

**Issue by AlessandroRodaro** [dotnet/orleans#6863]
Hi, 
i am developing an IOT application with orleans, but I can't solve an exception problem when starting the silo.

![ExceptionOrleanSilo](https://user-images.githubusercontent.com/64959332/102987839-4472c700-4513-11eb-8d4e-5fa2c2ecf8fe.png)

After exceptions I can start everything, but it doesn't normal to me.
This is my Silo code:

`
using Microsoft.Extensions.Logging;
using Orleans;
using Orleans.Configuration;
using Orleans.Hosting;
using OrleansCommon;
using System;
using System.Net;
using System.Threading.Tasks;

namespace Silo
{
    public static class Program
    {
        public static async Task Main(string[] args)
        {
            try
            {
                var host = await StartSilo();
                Console.WriteLine("Press Enter to terminate...");
                Console.ReadLine();

                await host.StopAsync();
                host.Dispose();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }

        private static async Task<ISiloHost> StartSilo()
        {
            var persistenceConfiguration = new PersistenceConfiguration(); //My configuration from library 
            var networkConfiguration = new NetworkConfiguration(); //My configuration from library

            var currentPersistenceConfiguration = persistenceConfiguration.GetPersistenceConfiguration();
            var currentNetworkConfiguration = networkConfiguration.GetNetworkConfiguration();

            var siloHostBuilder = new SiloHostBuilder()
           .Configure<ClusterOptions>(options =>
           {
               options.ClusterId = "dev";
               options.ServiceId = "silo1";
           })
            .UseAdoNetClustering(options =>
            {
                options.Invariant = currentPersistenceConfiguration.Invariant; //My configuration from library
                options.ConnectionString = currentPersistenceConfiguration.ConnectionString; //My configuration from library
            })
            .ConfigureApplicationParts(parts => parts.AddFromApplicationBaseDirectory())
            .UseDashboard(options =>
            {
                options.Host = "localhost";
                options.Port = 8080;
                options.HostSelf = true;
                options.CounterUpdateIntervalMs = 1000;
            });
            siloHostBuilder.Configure<EndpointOptions>(options =>
             {
                 options.SiloPort = currentNetworkConfiguration.SiloHostPort;
                 options.GatewayPort = currentNetworkConfiguration.SiloGateway;
                 options.AdvertisedIPAddress = IPAddress.Parse("Home wi-fi address"); 
             })
           .ConfigureLogging(logging => logging.AddConsole());

            var host = siloHostBuilder.Build();
            await host.StartAsync();
            return host;
        }
    }
}
`

Thanks!

**Comment by ReubenBond** [comment]
That's a first-chance exception which is caught and handled. It's not an issue, despite being annoying. We ought to remove the responsible code. I believe if you specify your Application Parts more precisely (not `AddFromApplicationBaseDirectory()`), then it will not occur.
