### ISSUE TITLE
Transaction rollback issues

### ISSUE THREAD

**Issue by sinanbabacan** [dotnet/orleans#6864]
I have two grain method marked as TransactionOption.CreateOrJoin, which is invoked by another grain method marked as TransactionOption.Create. I want to abort all process if any of two grain method marked as TransactionOption.CreateOrJoin failed. Should I throw an exception? Or is there any solution to abort all process?

```
await _balance.PerformUpdate(q =>{
   if (q.Amount + amount > _balanceLimit)
   {
     throw new ApplicationException("limit exceeded");
   }  
   
   q.Amount += amount;
});
```

**Comment by jsteinich** [comment]
Throwing an exception will indeed trigger a rollback. I'm not aware of any other methods.
