### ISSUE TITLE
TestCluster Dispose is very slow.

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#6865]
Hi,

I don't exactly know what the problem is, but TestCluster.DisposeAsync() is very slow.

My whole test takes 5 second and with the DisposeAsync() around 30 seconds. Is there something I can do about it?

**Comment by freever** [comment]
I have this problem too

**Comment by ReubenBond** [comment]
Apologies for the long delay. I wonder what it's doing in that time. We generally recommend creating test fixtures that can be reused for many tests, though I think that generally we could abruptly terminate the silos without being graceful during tests. Test termination is something we should look at.

**Comment by Romanx** [comment]
Sorry for bumping a very old issue but i've noticed this too. The most minimal case I can create seems to have an overhead when tearing down the cluster at the end of tests.

Also worth noting that the test time doesn't include this overhead but the test explorer will look like it's hanging during it.
