### ISSUE TITLE
Issue with kubernetes yaml from docs

### ISSUE THREAD

**Issue by digisimon** [dotnet/orleans#6867]
Hi,

I'm trying to get the kubernetes hosting running as [described in the docs](https://dotnet.github.io/orleans/docs/deployment/kubernetes.html).

If I take exactly the same code as in the example and try to deploy to my cluster I get the following error:

> The Deployment "dictionary-app" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"orleans/clusterId":"dictionary-app", "orleans/serviceId":"dictionary-app"}: `selector` does not match template `labels`

What am I missing here?
Thanks!

**Comment by ReubenBond** [comment]
Hi @digisimon, apologies for the very slow response. The docs are updated now and there is an end-to-end sample which you can follow here: https://github.com/ReubenBond/hanbaobao-web

**Comment by digisimon** [comment]
Hey @ReubenBond 
Thank you, the example project is very helpful!

Turns out that I had to delete my deployment first before adding the selectors instead of just modify it. But now it seems to work so far.
