### ISSUE TITLE
Microsoft.Orleans.OrleansConsulUtils does not auto remove offline silo?

### ISSUE THREAD

**Issue by yilezhu** [dotnet/orleans#6874]
I am using Microsoft.Orleans.OrleansConsulUtils v3.3.0 to run my silo in consul. 
![image](https://user-images.githubusercontent.com/18655233/103969763-a2eda580-51a1-11eb-961a-d716dbabf939.png)
But it not work!
After one silos is offline, it has not been updated and removed from the consumer. How can it be solved

**Comment by yilezhu** [comment]
https://github.com/dotnet/orleans/issues/6606#issuecomment-756644944
My friend, we can move to a new issue for discussion. Do you mean Orleans need three or more silos to form a cluster for high availability? I'll do the test now!

**Comment by ReubenBond** [comment]
It should work. Do you have logs? What behavior are you seeing, exactly?

**Comment by yilezhu** [comment]
Yeah!Here I started three Silos,197,200,14 !And I set the `DefunctSiloCleanupPeriod` time to 30 seconds
```csharp
 "ClusterMembershipOptions": {
      "TableRefreshTimeout": "00:10:00",
      "DefunctSiloCleanupPeriod": "00:00:30",
      "DefunctSiloExpiration": "00:00:30"
    },
```
Then I stopped the 14 silo，But  after a long time, 14 on the consumer was not removed。
![image](https://user-images.githubusercontent.com/18655233/104117474-85b10680-535c-11eb-8885-db7be43e43f7.png)

197silo log
![image](https://user-images.githubusercontent.com/18655233/104117503-bee97680-535c-11eb-95e3-de68df96ff89.png)
200silo log
![image](https://user-images.githubusercontent.com/18655233/104117513-d45ea080-535c-11eb-9e0c-29bc0864d756.png)

**Comment by ReubenBond** [comment]
If you stop them all, then there are no silos around to clean up Consul.

Regarding the other error: you're stopping the entire service while clients are sending messages?

**Comment by yilezhu** [comment]
Thanks for your reply, friend！
First there were three silos, and I only stopped one！
Second, when one of the silos is stopped, the client is continuously sending data！
The client code is shown below

```csharp
            int n = 0;
            int loop = 50_000           
            var sw = new Stopwatch();
            sw.Start();
            Parallel.For(0, loop, new ParallelOptions { MaxDegreeOfParallelism = 16 }, async s =>
                {
                    var g = this._client.GetGrain<ICatalogRouting>(rm.Next(100));
                    var response = await g.Storage("Img", new Immutable<byte[]>(buf));
                    //G3_1 @H1\Vib\2020\12\1_28102715178@87968:11749346
                    //var response = await g.GetStream(@"G3_1@H1\Vib\2020\12\1_28102715178@0:87968");
                    Interlocked.Increment(ref n);
                    if (n == loop)
                    {
                        Console.WriteLine(response);
                    }
                });

            while (n < loop)
            {
                await Task.Delay(1);
            }
            Console.WriteLine("总耗时{0},返回个数:{1}", sw.ElapsedMilliseconds, n);
            await Task.CompletedTask;
```

**Comment by ReubenBond** [comment]
And you never see any entries being deleted? That's odd... Do you have logs?

**Comment by yilezhu** [comment]
It will be removed after a period of time, but it is not the time interval I set, and the client will have the following error。
![image](https://user-images.githubusercontent.com/18655233/104145226-28bb5c00-5401-11eb-8db7-9cd0735ba56c.png)

**Comment by ReubenBond** [comment]
The errors you're posting make sense assuming that the silos are not available. Are they being shut down cleanly? It looks as though the process is being killed abruptly. Is that correct?

**Comment by yilezhu** [comment]
Yes, but I just stopped one of the three. The other two silos are still running. That's the strange thing

**Comment by ReubenBond** [comment]
If you kill a process abruptly then it will take some time for the other two silos to decide that the silo is dead, and you will see errors like that `ConnectionFailedException` until the client synchronizes (each minute by default). Shutting it down cleanly is much better. You shouldn't see something saying there are no gateways available unless your client is using static routing.

**Comment by yilezhu** [comment]
Yes, it should be. The bad thing is that I'm in this situation now, and I haven't found the reason yet! I will post my code
the client:
```csharp

```
