### ISSUE TITLE
Remove ActivationId

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#6880]
I propose that we remove the concept of an ActivationId as means to identify individual activations of a grain in a cluster.

### What is an `ActivationId`

`ActivationId` is a unique identifier given to a particular instance of a grain. It is a virtual physical identifier. `ActivationAddress` fills the role of physical identifier where `ActivationId` is the unique component. A `GrainId` is a logical identifier, used for all instances of a particular grain.

### Why we should remove `ActivationId`

In short, in my opinion, they are difficult to reason about & handle internally, do not serve a useful purpose, and are an unnecessary form of indirection and complexity.

`ActivationId`s are generated at placement time. This means that multiple silos can generate different `ActivationId`s for the same grain simultaneously, and send messages destined for that grain to different silos. These silos then try to instantiate the grain locally and register it in the grain directory. Only one silo will win the registration race, and all other silos will re-route requests to the winning `ActivationId` / `SiloAddress`. The silos which selected that incorrect `ActivationId` will have to invalidate caches pointing at the losing silo and update them to the winning silo. This works by setting a `Message.CacheInvalidationHeader` on the message forwarded from a losing silo to the winning silo, and propagating those headers back to the original calling silo (see [`MessageFactory.CreateResponseMessage`](https://github.com/dotnet/orleans/blob/bbc79cd092a5600c8b0f676da67798adb704f8ed/src/Orleans.Core/Messaging/MessageFactory.cs#L126) for where this is propagated from request to response). This leaves a gap where additional messages are sent to the wrong silos from around the cluster during a new activation race, which is wasteful and increased the chance of messaging errors.

### What should we do instead

When a grain's location in the cluster is unknown to a silo because it doesn't exist, existed on a removed silo, or is currently being activated:

* The silo will perform a lookup as usual
* If the grain is not present in the directory, the silo will execute placement locally and set a `TargetSilo` hint on the outgoing message. Otherwise it will set `TargetSilo` to the value found in cache/directory.
* If a message arrives at a silo with `TargetSilo` set, it will try to find the grain locally via the `TargetGrain` `GrainId` property on the message.
  * If the grain is activated locally, pass the message to that grain.
  * If not, attempt to activate the grain locally, which involves registering it in the directory.
    * If the directory registration race is won, complete activation and send the message to that grain.
    * If the race is lost, the winning silo's address is set as TargetSilo on the message and the message is forwarded to that silo. To prevent infinite cycles, the `ForwardCount` property can be used to limit the number of times this can occur.
* If `TargetSilo` is not set, the silo will restart this process from the first point (lookup grain)
* Note: we could keep a `Task<T>` representing the activation process via a lookup so that concurrent incoming messages can be treated identically - that helps to retain the activation exception, too, if activation fails and all enqueued messages are to be rejected with the activation exception.

When a grain is deactivated due to idleness (i.e, activation garbage collection), the activation is unregistered from the directory. Any messages from other silos which have already been addressed to that deactivated activation can arrive and re-activate the activation locally. Since directory registration is performed on activation, then there are no races and the activation will be re-registered in the directory before processing messages. The invariant that all activations must be registered in the directory is maintained.

### Other considerations

Currently, we allow for multiple activations of `[StatelessWorker]` grains for improved throughput, and each has a unique `ActivationId`. These grains break the programming model whereby there is logically one grain for each `GrainId`. Instead, we could rework `[StatelessWorker]` grains so that each one has multiple scheduling contexts and multiple instances of the implementation class. That allows us to retain throughput without breaking the model at that level. We could eventually allow for "multi threaded grains", which do not preserve the single-threaded nature of grains, and also allow improved single-grain throughput.

This involves removing the *multiple activations* feature from the grain directory. This feature is currently only used by Clients, as a means to store which gateways each client is connected to. That information is used for routing responses and messages sent to observer objects. For this, the in-cluster grain directory is relied upon. We can keep using this special implementation, or migrate to a more fit-for-purpose scheme for finding out which gateways each client is connected to for routing.

We can keep some unique incarnation identifier for local logging purposes, if we want.

If a token is needed to use for optimistic concurrency control in a grain directory, that is also acceptable but could be replaced with an "incarnation" or "version" integer, which doubles as giving us a rough idea of how many times a grain has been activated in the case of a persistent directory.

### Proposed strategy

Removing the concept of an ActivationId in one shot may be difficult to accomplish and especially difficult to review, as well as being risky. Therefore, we can move incrementally towards this goal. Here are some example intermediate steps:

* [x] Migrate clients away from the directory
  * Eg, assume each client is connected to all gateway nodes (generally true) and route randomly (biasing to local node). If a gateway receives a message for a client which is not connected to it, it can select the next node in the ring (i.e, round robin) and forward messages to that gateway node. Alternatively, if the client isn't locally connected, query other gateways to ask if they have the client connected. If none do, keep messages local (in `ClientState` until the client connects or timeout (existing behavior))
* [x] Remove multiple activation support from grain directory
* [ ] Remove ActivationId from IGrainContext
* [x] Key ActivationDirectory on GrainId instead of ActivationId (Catalog)
* [ ] Remove ActivationId from Message
* [ ] Remove all references to ActivationId, and ActivationId itself

**Comment by sergeybykov** [comment]
>When a silo is deactivated due to idleness

Looks like a typo - you meant *a grain* is deactivated, right?

> Instead, we could rework [StatelessWorker] grains so that each one has multiple scheduling contexts and multiple instances of the implementation class. That allows us to retain throughput without breaking the model at that level.

I don't know. instead of this behind-the-scene complexity, wouldn't it be better to use multiple grain IDs? For example, by adding an explicit suffix to the original ID.

>We could eventually allow for "multi threaded grains", which do not preserve the single-threaded nature of grains, and also allow improved single-grain throughput.

I'm afraid this will encourage wrong patterns and in the end create more harm than benefit. Single-threadiness of grains is overwhelmingly referred to as a major benefit of the programming model. If somebody needs to scale a single grain beyond it's normal throughput limits, I can think of several possibilities:
* a) They are making a modeling mistake by introducing a bottleneck in the system
* b) They legitimately need to scale up that grain, and can leverage one of the scale out patterns like stateless workers or a pool of locally placed grains to parallelize execution
* c) They really need multithreading

In my mind, the probability of these cases goes down from a) to c). If somebody does have the c) case (which is difficult for me to imagine), wouldn't they easily implement multithreading themselves and integrate it with the single-threaded grain?

>This involves removing the multiple activations feature from the grain directory. 
👍👍

>We can keep some unique incarnation identifier for local logging purposes, if we want.

In my opinion, this is important. Yes, activation ID are hard to read GUIDs today, but they have helped many times to disambiguate between different incarnations of a grain when debugging races. Ideally, it would be an auto-incremented integer "version", but that's impossible to do without using storage or consensus. But even a silo-like epoch number would be a great help I think.

In general, I'm very much supportive of this proposal, with the caveats I mentioned.

**Comment by ReubenBond** [comment]
> I don't know. instead of this behind-the-scene complexity, wouldn't it be better to use multiple grain IDs? For example, by adding an explicit suffix to the original ID.

I agree. Pushing the concern up as a library/application level pattern is preferable.

> I'm afraid this will encourage wrong patterns and in the end create more harm than benefit. Single-threadiness of grains is overwhelmingly referred to as a major benefit of the programming model. If somebody needs to scale a single grain beyond it's normal throughput limits, I can think of several possibilities:
>
> a) They are making a modeling mistake by introducing a bottleneck in the system
> b) They legitimately need to scale up that grain, and can leverage one of the scale out patterns like stateless workers or a pool of locally placed grains to parallelize execution
> c) They really need multithreading
>
> In my mind, the probability of these cases goes down from a) to c). If somebody does have the c) case (which is difficult for me to imagine), wouldn't they easily implement multithreading themselves and integrate it with the single-threaded grain?

I agree that single-threadedness is a massive boon to application developers. I think that if we want this particular aspect, it should only be for very specialized "safety off" cases and therefore it's not suitable for `[StatelessWorker]`. It's the kind of thing which should be possible in-theory (eg, by implementing `IGrainContext` yourself), but not offered out of the box at all. Either way, multi-threaded grains are out-of-scope for this issue. The pattern-based approach is much cleaner and doesn't warp the model.
