### ISSUE TITLE
Kubernetes hosting package

### ISSUE THREAD

**Issue by xontab** [dotnet/orleans#6886]
Is the Kubernetes hosting package (https://www.nuget.org/packages/Microsoft.Orleans.Hosting.Kubernetes) currently stable and ready for production use?  Looks like there was a PR to remove the `beta1` keyword from the version suffix https://github.com/dotnet/orleans/pull/6804 but this wasn't pushed to 3.4.0.  

![image](https://user-images.githubusercontent.com/4987684/104291783-44376d00-54bc-11eb-991c-5966c5d30a0f.png)

Thus is this package intended to be stable in the next major version?

**Comment by ReubenBond** [comment]
We may mark it as stable for the next release. I want to test it more. If you can try the package and let us know, that will be greatly appreciated. If there are holes/inconsistencies in the [documentation](https://dotnet.github.io/orleans/docs/deployment/kubernetes.html), please let us know. If you'd like, you can use this issue for that.

**Comment by xontab** [comment]
Thanks a lot @ReubenBond.  We will definitely test it out.  At the moment we are using https://github.com/OrleansContrib/Orleans.Clustering.Kubernetes but this will eliminate the need for CRDs and reduce maintenance.

**Comment by ReubenBond** [comment]
That clustering package is different from the Orleans.Hosting.Kubernetes package. The hosting package does not replace the need for clustering - you can use Redis or Azure Table Storage or Orleans.Clustering.Kubernetes for that.

By the way, there is a new sample to demonstrate the hosting package with Redis for clustering here: https://github.com/ReubenBond/hanbaobao-web

**Comment by turowicz** [comment]
@ReubenBond I understand we can use `Orleans.Clustering.Kubernetes` for membership in tandem with `Microsoft.Orleans.Hosting.Kubernetes`. The documentation mentions `ISiloBuilder.UseKubernetesHosting`. Do we also have an `IClientBuilder` equivalent?

**Comment by ReubenBond** [comment]
There is no client equivalent for hosting, and I am unsure what it would do. I suppose you could plumb ServiceId/ClusterId values from the pod manifest using a small helper. That can be accomplished without a new package, however.

**Comment by turowicz** [comment]
OK so if I keep the labels in line it should work. So what are the benefits of using this hosting packages other than red-blue?

**Comment by turowicz** [comment]
More detailed explanation here: https://github.com/OrleansContrib/Orleans.Clustering.Kubernetes/issues/48#issuecomment-767528831

**Comment by ReubenBond** [comment]
The hosting package has been released as stable now, thanks everyone for the testing & feedback

**Comment by turowicz** [comment]
It's working great.
