### ISSUE TITLE
Recently changed to using PreferLocalPlacement and noticed the following exception

### ISSUE THREAD

**Issue by govenkat-ms** [dotnet/orleans#6894]
System.ArgumentNullException: Value cannot be null. (Parameter 'existingActivationAddress')
   at Orleans.Runtime.Catalog.RegisterActivationInGrainDirectoryAndValidate(ActivationData activation)
   at Orleans.Runtime.Catalog.InitActivation(ActivationData activation, Dictionary`2 requestContextData)

Forwarding 1 requests destined for address S10.241.32.192:11114:348371692*grn/2E596F41/1ca50c90@0fb89099 to address (null) after Failed RegisterActivationInGrainDirectory
--------------------------------------------------------------------
Trying to forward NewPlacement Request S10.241.32.192:11114:348371692*cli/5e3126ae@18ce4a9f->S10.241.32.192:11114:348371692*grn/2E596F41/1ca50c90@0fb89099 #1355 from S10.241.32.192:11114:348371692*grn/2E596F41/1ca50c90@0fb89099 to (null) after Failed RegisterActivationInGrainDirectory. Attempt 0
-------------------------------------------------------------------------------------------
Failed to forward message NewPlacement Request S10.241.32.192:11114:348371692*cli/5e3126ae@18ce4a9f->S10.241.32.192:11114:348371692*grn/2E596F41/1ca50c90@0c897498 #1365[ForwardCount=2] from S10.241.32.192:11114:348371692*grn/2E596F41/1ca50c90@0c897498 to (null) after Failed RegisterActivationInGrainDirectory. Attempt 2

**Comment by benjaminpetit** [comment]
Are you using the default directory or another one (Redis, ect.)?

**Comment by govenkat-ms** [comment]
Just using the default directory

**Comment by govenkat-ms** [comment]
Any updates?

**Comment by benjaminpetit** [comment]
Chatted offline with @govenkat-ms , it seems like the silo is trying to register an entry in the directory that points to a dead silo.

I will make a code change that will throw an exception, with a clear message instead of returning `null` causing this cryptic message later.

**Comment by benjaminpetit** [comment]
Fixed in 3.4.1
