### ISSUE TITLE
Is there any official way to compatible with OWIN? 

### ISSUE THREAD

**Issue by Alikhll** [dotnet/orleans#6899]
Is there any potential way to have an old ASP.NET MVC application configured with OWIN to be using Orleans side by side, as well as something we do have with ASP.NET Core now?

**Comment by ReubenBond** [comment]
Yes, I released this package a long time ago, so it's very outdated, but you could take the code and update it:
https://www.nuget.org/packages/Dapr.Orleans.Owin/
Code: https://github.com/daprlabs/Orleans.Owin

**Comment by Alikhll** [comment]
Ah nice, Great
