### ISSUE TITLE
Allow for custom IMembershipTable implementations

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#69]
Currently there are 3 IMembershipTable implementations, a "development only" grain-based implementation, an Azure Table Storage implementation, and a SQL Server implementation.

I want to be able to reliably bootstrap silos without relying on SQL Server or Azure Table Storage.

It would be great if we could have a model for injecting custom IMembershipTable implementations.

**Comment by sergeybykov** [comment]
@ReubenBond - Are you suggesting adding "Custom" to LivenessProviderType and a way to specify a class that implements IMembershipTable and IGatewayListProvider?

**Comment by ReubenBond** [comment]
I think so, but I want to hear your thoughts 

-----Original Message-----

**Comment by sergeybykov** [comment]
Makes sense to me. I wonder what @gabikliot thinks.

**Comment by gabikliot** [comment]
I am all for allowing more membership providers. The question is how exactly, right?

Adding another membership provider is as easy as:
1) adding a new value into enum GlobalConfiguration.LivenessProviderType
2) adding another case into MembershipFactory (https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/MembershipService/MembershipFactory.cs)
3) and of course implementing ISiloStatusOracle.
The interface ISiloStatusOracle, as you see, is actually very well encapsulated. There is not much semantical specifics that are not directly encapsulated in the interface.

I see no big value in allowing generic, dynamic types of membership provider, like we do for storage providers. I can practically think only about 2 or 3 different membership providers people may want. Zookerper being one. I can think about another one or 2. But not beyond that. It's not like there are 20 different well encapsulated implementation of consensus and memberships out there (as opposite to storage systems).
So I see no value, at this point, to make it dynamically loadable.
Statically adding a new implementation to the code, and hooking it all the way in the MembershipFactory - sure, great idea! 
I am in fact planning to post as an issue an open "student idea" for hookup Zookeeper as a membership provider.

**Comment by ReubenBond** [comment]
Aside from ZooKeeper, there's also the new kid on the block, etcd... but there are many possible membership providers. If we have Azure, why not AWS, for example.

I'm not particularly opinionated, I just want to achieve my specific goal in a way which is beneficial for everyone.

What about IGatewayListProvider? It looks like I would want to customize that, too.
I am still familiarizing myself with the code - so apologies while I play catch-up.

**Comment by gabikliot** [comment]
Sure, all the new options can be supported this way, ZK was just an example.

Yes, you are right: IGatewayListProvider should also be extended. It is quiet easy, it basically returns the same list of alive silos that is returned by the ISiloStatusOracle. So it is a read only view on the membership. The 2 differences are:
1) different port - proxy gateway port instead of internal silo to silo port.
2) there is an opportunity for IGatewayListProvider to return only a partial list. For example restrict certain clients to only subset of gateways. We don't use it now, but it is possible.

In your case it will be simply returning the list of all alive silos with a different port.

**Comment by ReubenBond** [comment]
Is this closed because the feature is now present?

**Comment by gabikliot** [comment]
No, I thought you found an alternative and this is not needed any more. I will re-open. It will be up to you to leave it open or close. Sorry about the misunderstanding.

**Comment by ReubenBond** [comment]
Oh, that's fine - I just haven't gotten around to implementing a solution yet. Azure Storage is sufficient for now, and I will worry about an alternative solution when we can find time.

**Comment by grahamehorner** [comment]
We should also consider this also a coreclr compatibility issue; as the current providers use features not supported by the coreclr, and therefore we should break out the current providers into satellite assemblies; which can be dependency injected or loaded from configuration.

**Comment by gabikliot** [comment]
@ReubenBond , 6 months and 600 PR/issues later on, your request for allowing to load new system store dynamically from configuration ("a model for injecting custom IMembershipTable implementations") has finally been implemented, by @kucheruk in #648 !
