### ISSUE TITLE
Why I get low throughput with OrleansTransaction

### ISSUE THREAD

**Issue by YijianLiu1210** [dotnet/orleans#6912]
@philbe Hi, I am running experiments with OrleansTransaction to investigate its performance. But my current result shows it has relatively low throughput comparing to an in-memory system that I implemented on Orleans:

OrleansTransaction:
| num_grain per txn  | deadlock | throughput (txn / second) | median latency (ms) | 99% latency (ms) | abort rate |
| ------------------- | --------- | -------------------------- | -------------------- | ------------------ | ---------- |
|                2                |        no     |                    7113                   |             4.37               |              112.64        |     0.00%   |
|                2                |        yes    |                   6914                   |             4.5                |              115.98         |     0.00%   |
|                4                |        yes    |                  3453                   |             7.49               |              244.25        |     0.00%   |

My in-memory system (S2PL + wait-die + 2PC):
| num_grain per txn  | deadlock | throughput (txn / second) | median latency (ms) | 99% latency (ms) | abort rate |
| ------------------- | --------- | -------------------------- | -------------------- | ------------------ | ---------- |
|                2                |        no     |                    12482                  |             2.08               |              6.31          |   0.27%   |
|                2                |        yes    |                   12050                |             2.13                |              6.44           |     0.26%   |
|                4                |        yes    |                  7130                   |             3.40               |              12.82           |     0.92%   |

*note: "no deadlock" means I eliminate deadlock by sorting the accessed grains per txn while generating workload, so that there will not be any deadlock between grains.

**[My deployment]**
(1) **Client**: 4 threads, each builds a client connection to silo, and each sends an async pipeline of transaction requests. 
(2) **Server**: A 4-core virtual machine, 1 silo, 10K transactional grains
- I implement ITransactionalStateStorage as no-op (Because right now I only want to see the overhead of scheduling and concurrency control, not durability, so that I can compare OrleanTransaction with an in-memory system which has no durability guarantees yet. )
- My transactional grain:
```
public interface IAccountGrain : IGrainWithGuidKey
{
    [Transaction(TransactionOption.Join)]
    Task Deposit(uint amount);

    [Transaction(TransactionOption.Create)]
    Task MultiTransfer(uint amount, List<Guid> accounts);
}

[Reentrant]
public class AccountGrain : Grain, IAccountGrain
{
    private readonly ITransactionalState<Balance> balance;

    public AccountGrain(
        [TransactionalState("balance", "TransactionStore")]
        ITransactionalState<Balance> balance)
    {
        this.balance = balance ?? throw new ArgumentNullException(nameof(balance));
    }

    Task IAccountGrain.Deposit(uint amount)
    {
        return this.balance.PerformUpdate(x => x.Value += amount);
    }

    Task IAccountGrain.MultiTransfer(uint amount, List<Guid> accounts)
    {
        await this.balance.PerformUpdate(x => x.Value -= amount * accounts.Count);
        var tasks = new List<Task>();
        foreach (var account in accounts)
        {
             var grain = GrainFactory.GetGrain<IAccountGrain>(account);
             tasks.Add(grain.Deposit(amount));
        }
        await Task.WhenAll(tasks);
    }
}
```
(3) **Workload**
- Each transaction will access 2 or 4 different grains to complete "MultiTransfer".
- The client request is sent to one grain, which will invoke calls to other grains.
- All accessed grains are uniformly randomly chosen from all grains.

**[My Question]**
1. How does OrleansTransaction handle deadlock? Is it time-out based or wait-die? I'm thinking maybe the low throughput is due to the time-out mechanism. 
2. How many RPCs per transaction will happen in OrleansTransaction? Maybe it's the reason for longer latency compared to my system. 
- In my in-memory system, for each MultiTransfer transaction (4 grain), I have 1 RPC from client to the grain to start a  transaction + 3 RPCs between grains to execute transaction + 6 RPCs to do 2PC. 
- As for OrleansTransaction, as far as I know, there will be: 1 RPC from client to the grain to start a  transaction + 3 RPCs between grains to execute transaction + 3 RPCs between grains to do Prepare Phase of 2PC + 1 RPC to Transaction Manager + 3 RPCs to commit/abort the transaction.
3. Will the Transaction Manager becomes the bottleneck in my experiment?
4. Is there any design in OrleansTransaction, like group commit, that will work fine with durability enabled, but does not perform so good when I manually disable durability?

**Comment by jsteinich** [comment]
1. It uses timeouts to handle deadlocks.
2. I think that's about the right amount (there are some steps that can be bypassed under the right conditions)
3. The transaction manager is actually just a grain that participates in the transaction that is chosen to be the manager for that particular transaction. It may prefer the first grain with a write, but it sounds like that is distributed amongst the grains in your test
4. I do wonder if having `ITransactionalStateStorage` be a no-op is impacting things. I believe some of the tracking of which versions of the state are kept is handled by it.
5. I could see the p99 latency being a result of dependent transactions. (When you access a grain that was already in use in an existing transaction, the transactions become dependent and need to be processed serially).

**Comment by philbe** [comment]
@YijianLiu1210  RE: (4). I agree with @jsteinich that making ITransactionalStateStorage a no-op is likely to cause problems. Instead, I suggest you try connecting it up to a storage provider that reads and writes main memory.

**Comment by YijianLiu1210** [comment]
Hi, thanks for your reply. Instead of pure no-op, I've tried to improve my code by maintaining all "persisted" (stored) states in memory, just like the data structure _List<KeyValuePair<long, StateEntity>> states_ in AzureTableTransactionalStateStorage. With this version, I get almost the same throughput as no-op version.

**Comment by sebastianburckhardt** [comment]
It is not all that surprising that simply turning off the persistence does not give the same results as using an in-memory-only algorithm.

In-memory transaction algorithms ("transactional memory") are designed differently than transaction algorithms that require atomic persistence. The former only care about concurrency control; the latter care about concurrency control (e.g. two-phase locking) and atomic persistence (e.g. two-phase commit). 

Two-phase commit was the dominant performance challenge for us,  and our algorithm's design focuses on mitigating the effects of dealing with slow storage. But if you don't actually need to store anything, we are likely to do some extra work compared to an in-memory-only algorithm.

For example, our algorithm has a garbage-collection phase to remove no-longer-needed prepare and commit records from storage, which is completely superfluous for the in-memory-only case.
