### ISSUE TITLE
Timers asyncCallback invocations and reentrant behaviour

### ISSUE THREAD

**Issue by jenyayel** [dotnet/orleans#693]
In the documentation of [Timers and Reminders](http://dotnet.github.io/orleans/Advanced-Concepts/Timers-and-Reminders), there is a sentence regarding Timers:
>Note however, asyncCallback invocations are not delivered as messages and are thus not subject to message interleaving semantics. This means that invocations of asyncCallback should be considered to behave as if running on a reentrant grain with respect to other messages to that grain.

I'm on another hand, don't want the behavior of reentrant grain. In my case the timer updates the state, so if the message coming from outside to update the state as well, then the raise condition can occur. I'm totally OK that the messages will wait until timer finishes its operation.

One idea I had is that in asyncCallback to send a message to grain itself, but is seems a little bit weird.

**Comment by gabikliot** [comment]
>One idea I had is that in asyncCallback to send a message to grain itself.

That is exactly the workaround that we are suggesting to customers.
We have a work item in the backlog to change the above behavior and make sure Timers respect the grain message reentrancy, but we just never got time to do that.

**Comment by jenyayel** [comment]
Great, works perfect! Thanks for quick response.
