### ISSUE TITLE
ReminderStorage (Postgres): Creating too many connections

### ISSUE THREAD

**Issue by seanamosw** [dotnet/orleans#6944]
Version: Microsoft.Orleans.Reminders.AdoNet 3.4.1 (all packages are 3.4.1)

I haven't tested across different databases.

At least with Postgres, enabling ReminderStorage creates 29 additional connections to the database per silo.
An out of the box Postgres install allows a maximum of 100 connections without raising it or using a load balancer.

This is obviously far too many connections for a single application, this probably means a connection leak.

### How to reproduce

Run appropriate scripts from https://dotnet.github.io/orleans/docs/host/configuration_guide/adonet_configuration.html

```csharp
            var siloConn = configuration.GetConnectionString("...");
            var invariant = "Npgsql";

            var builder = new SiloHostBuilder()
                .UseLocalhostClustering()
                .Configure<ClusterOptions>(x =>
                {
                    x.ClusterId = "dev";
                    x.ServiceId = "dev";
                })
                .UseAdoNetReminderService(x => {
                    x.Invariant = invariant;
                    x.ConnectionString = serviceConn;
                })
                .ConfigureApplicationParts(x => ...);
                .ConfigureLogging(logging => logging.AddConsole());

            var host = builder.Build();
            await host.StartAsync();
```

Check the connections:

```sql
select * from pg_stat_activity
```

No grain activations are required, simply starting the Silo with`UseAdoNetReminderService` creates a large amount of connections.

**Comment by veikkoeeva** [comment]
@seanamosw Can you share the connection string? Interesting bit is if https://www.npgsql.org/doc/connection-string-parameters.html#pooling is used.

The case likely is that Orleans creates this many connections and PostgreSQL connector does not have pooling on. See at https://github.com/dotnet/orleans/blob/master/src/AdoNet/Shared/Storage/RelationalStorage.cs#L263 how the connections are created and disposed.

**Comment by seanamosw** [comment]
The connection string is simple:
`Server=db;Database=...;User Id=...;Password=...;`

There are no explicit pooling options set, however the defaults according to the docs is to use connection pooling.

I did however try explicitly setting connection pooling on:
`Server=db;Database=...;User Id=...;Password=...;Pooling=true`

This did not resolve the issue.

I also tested the `AdoNetGrainStorage` with postgres and after hammering it a bit, it does not seem to exhibit the same behaviour.

**Comment by veikkoeeva** [comment]
@seanamosw I think what happens with pooling is that many connections will be opened as Orleans is issuing many reminder calls and there are not pooled connections to serve the calls as the previously issued calls have not returned yet. Once that has happened, the pooler keeps the connections open for next calls as specified by the default paramteres or the ones explicitly set. If you need to have less connections open, you could set a maximum number for connections. 

It does not look to me connections are leaked as they're used within a `using` clause and being returned to the pool once used. The database sees them as open connections as they're open, the upside is that the connections are open and calls are multiplexed over them and specifically no time is needed to re-open the connections on server side. 

I do not know if something needs to happen here, while of course the right thing to record a record a concern. :) I think I saw recently a PR for an optimization for reminders to issue less calls, @ReubenBond might remember if that's the case and if so, what was the issue.

Waving hands a bit: I think Orleans could issue less calls. I think it would be a good idea to consider some server side pooling too. Also the PostgreSQL calls and DB could be more efficient (I may work on that in the future if nobody else will).

**Comment by veikkoeeva** [comment]
@seanamosw To give more sense to what I wrote, I'll add that there are three layers at work here:

- The low layer that manages the connection, does the queries, collects the results and such things. The link about connections is from there.
- A provider layer that uses the previous. These are what you configure in your example.
- Orleans that use these providers according to its internal logic. Orleans runs some logic, for some reason (e.g. depending on what kind of grains you run) that calls the reminders plugin that then opens the connections you see.

**Comment by veikkoeeva** [comment]
@seanamosw Here is the issue I was thinking: https://github.com/dotnet/orleans/pull/6818.

**Comment by pentp** [comment]
#6818 should reduce the number of storage calls to 1 for a one silo cluster. As the number of silos increases the range handled by each silo's reminder service is further split up, so at around 16 silos the situation is pretty much the same as before (many storage calls).

The general solution for this would probably require either a different distribution (splitting) of the range handled by each silo and/or adding a new `IReminderTable.ReadRows` overload that loads multiple ranges at once (and can decide how/if to do parallel queries).

**Comment by veikkoeeva** [comment]
@pentp This is an important optimization, I think, since some people are running systems with very large numbers of reminders. I don't remember anymore the details if they start to also consume quite a lot of memory (and processor resources), but definitely I have thought about refactoring the ADO.NET storage (maybe like in persistence; one can, and should, add indexes there too, maybe should be added by default).

**Comment by veikkoeeva** [comment]
@seanamosw & others By the way, if you want to have different pools per reminders, membership and persistene, you could use `application_name` (https://stackoverflow.com/questions/24046578/how-to-specify-applicationname-in-npgsql-connection-string) in the connection string. I think all ADO.NET connectors create one pool per connection string. Naming connections is a good practice also in general.

**Comment by suraciii** [comment]
One possible workaround is to enable multiplexing for ngpsql by adding `Multiplexing=true;` in the connection string, npgsql can use much less connections with multiplexing.
Notice, however, multiplexing is considered experimental in npgsql
