### ISSUE TITLE
microsoft.orleans.codegenerator.msbuild fails on net5.0

### ISSUE THREAD

**Issue by fuocor** [dotnet/orleans#6948]
The generator fails with a net5 project using CI packages `3.9.9-ci.20210208.4`
The generated command line from the build task is:

`dotnet "C:\Users\...\.nuget\packages\microsoft.orleans.codegenerator.msbuild\3.9.9-ci.20210208.4\build\..\tasks\netcoreapp3.1\Orleans.CodeGenerator.MSBuild.dll" SourceToSource "C:\Ossiaco\chorus\artifacts\obj\Chorus.Services\Debug\net50\win7-x64\Chorus.Services.orleans.g.args.txt"`

but the binaries are in:
`C:\Users\...\.nuget\packages\microsoft.orleans.codegenerator.msbuild\3.9.9-ci.20210208.4\tasks\net5.0`

**Comment by ReubenBond** [comment]
Thanks, @fuocor, there is a fix PR here: https://github.com/dotnet/orleans/pull/6949

**Comment by KSemenenko** [comment]
I still have this issue in 3.4.2 on Rider in MacOs
