### ISSUE TITLE
Orleans with Service Fabric and Dependency Injection strange behaviour

### ISSUE THREAD

**Issue by StephaneMartignier** [dotnet/orleans#6957]
Hi everyone,

So we encounter a strange bug using Orleans.

First a little about the project structure :

- We are using Orleans with Service Fabric (currently on a VM on our server)
- We have heterogeneous silos
- We use DI

So we have a ServiceType (a Stateless Service Fabric type) that we will call AbstractServiceType, that on initialisation take a string containing the path to a folder on an Azure Blob Storage. It then download the file and based on the content instantiate some grains. Each instance of AbstractServiceType create it's own silo.
The folder is represented by an instance of an IRepository class that is put in the DI.

```
private ServiceInstanceListener CreateApiServiceListener(IProjectRepository projectRepository)
        {
            return new ServiceInstanceListener(serviceContext =>
                    new KestrelCommunicationListener(serviceContext, "ServiceEndpoint", (url, listener) =>
                    {
                        ServiceEventSource.Current.ServiceMessage(serviceContext, $"Starting Kestrel on {url}");

                        return new WebHostBuilder()
                                    .UseKestrel()
                                    .ConfigureServices(
                                        services => services
                                            .AddSingleton<StatelessServiceContext>(serviceContext)
                                            .AddSingleton<IProjectRepository>(projectRepository))
                                    .UseContentRoot(Directory.GetCurrentDirectory())
                                    .UseStartup<SFStartup>()
                                    .UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.None)
                                    .UseUrls(url)
                                    .Build();
                    }));
        }
```

```
            // Add repositories
            siloBuilder.ConfigureServices(services =>
            {
                services.AddSingleton(processRepository);
            });
```

Then we call a grain which has this constructor:

``` 
   public class BusinessProcess : Grain, IBusinessProcessInternal
    {
        // Used to save and retrieve bpmn to and from different sources
        private readonly IProjectRepository _projectRepository;
    
        private string _processId;
    
        public BusinessProcess(IProjectRepository projectRepository)
        {
            _projectRepository = projectRepository;
        }
```

On this grain the Id is a string and the string contain the name of a file the grain will need. The file is stored in the instance of 
IProjectRepository.

So when testing we first create an instance of AbstractServiceType (let call it Service1 and the silo Silo1) and give the path to folder. It's work like a charm. It create an instance of IProjectRepository  (let call it Service1ProjectRepo) and put it in the DI. Then the grain is called and it's also work fine, it's receive the instance Service1ProjectRepo and can get the file.
Then we want to create another instance of AbstractServiceType (let call Service2 and Silo2) with a different path. The instance creation work well, we have another instance of IProjectRepository  (let call it Service2ProjectRepo).

But now come a strange behaviour. When calling the grain BusinessProcess for a file that is in the Service2ProjectRepo, the grain actually receive the Service1ProjectRepo in the constructor and then when getting the file it can't found it. Sometimes it's receive the "correct" Service2ProjectRepoin constructor.

Have you any idea of what can be happening? Are we doing somehting wrong?

Our guess is that having heterogeneous silos, when Service2 call a grain and the grain is activated on Silo1, in the DI it's receive the instance of IProjectRepository configured by Service1.

Have you any lead on how to make it work without changing too much of the structure?

Thanks a lot

**Comment by benjaminpetit** [comment]
Hi,

Sorry the issue isn't clear to me, so I'll ask a few questions:

> We have heterogeneous silos

You have "Heterogenous silos" in a cluster when silos support different grain types. For example you have Silo1 that supports GrainA and GrainB, and Silo2 that supports GrainB and GrainC. I am not sure that's what you have here, the `BusinessProcess` grain is available on all silos, correct?

If I understand correctly in your case, Silo1 and Silo2 will be configured with two different `IProjectRepository`. These two silos are part of the same cluster (configured with the same `ClusterId`), is that true?

When calling a grain from the client, how do you know which "Service" should it target?

**Comment by StephaneMartignier** [comment]
Hi,

thanks for the attention ported to my issue.

> You have "Heterogenous silos" in a cluster when silos support different grain types. For example you have Silo1 that supports GrainA and GrainB, and Silo2 that supports GrainB and GrainC. I am not sure that's what you have here, the BusinessProcess grain is available on all silos, correct?

Yes it's exactly that

> If I understand correctly in your case, Silo1 and Silo2 will be configured with two different IProjectRepository. These two silos are part of the same cluster (configured with the same ClusterId), is that true?

Also correct

> When calling a grain from the client, how do you know which "Service" should it target?

I'm not sur to understand this question, but from what I understand, each Service is a "client" and he is the one calling the grain.

**Comment by benjaminpetit** [comment]
> I'm not sur to understand this question, but from what I understand, each Service is a "client" and he is the one calling the grain.

The clients will connect to several silos in the cluster. If the target grain is placed on SiloA, then the grain will have the `IProjectRepository` configured for SiloA, if placed on SiloB it will have the one from SiloB.

Do you need the silo to be part of the same cluster? It seems that these silos should be completely isolated from each other.

**Comment by StephaneMartignier** [comment]
Thanks for the answer.

We need the silos in the same cluster because they have to be able to contact each other.

We change the way we were getting the needed informations in the grains in a way that it's not dependant to the DI.

Thanks for clarifying what was happened, it's always good to know some things like this one.

I close this as I consider it answered

**Comment by benjaminpetit** [comment]
You could plug a custom `IPlacementDirector` and do some placement logic based on the grain key or the request context. 

Not sure if I would advise going this route (it might be a bit complex to setup), but it should be doable.
