### ISSUE TITLE
MemoryStorageProvider does not respect grain state default constructor upon initialization

### ISSUE THREAD

**Issue by skalpin** [dotnet/orleans#696]
When grain state is initialized from the MemoryStorageProvider, the default constructor is called, and if no previous state is found it initializes all of the properties on the state to null. In `ReadStateAsync`, if the call to 
```
IDictionary<string, object> state = await storageGrain.ReadStateAsync(STATE_STORE_NAME, id);
```
returns null. `SetAll(null)` then resets the properties to null after the grain state constructor has been called.

**Comment by gabikliot** [comment]
Closed via #700.
