### ISSUE TITLE
Orleans.Hosting.Kubernetes monitoring IOException

### ISSUE THREAD

**Issue by Martijnvos** [dotnet/orleans#6963]
This problem is similar to #6759 as I've configured the service- and clusterId + ENV variables in the same way. I'm working with a RBAC-enabled cluster.

When using `UseKubernetesHosting` I get `Error monitoring Kubernetes pods` in my log with the following exception information:

```
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)
   at k8s.WatcherDelegatingHandler.CancelableStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadLineAsyncInternal()
   at k8s.WatcherDelegatingHandler.PeekableStreamReader.PeekLineAsync()
   at k8s.WatcherDelegatingHandler.LineSeparatedHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at k8s.Kubernetes.ListNamespacedPodWithHttpMessagesAsync(String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, Nullable`1 timeoutSeconds, Nullable`1 watch, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Orleans.Hosting.Kubernetes.KubernetesClusterAgent.MonitorKubernetesPods()
```

This is my current `deployment.yaml`, in which I added the core API group in `apiGroups` and the `pods` under `resources`:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterversions.orleans.dot.net
spec:
  group: orleans.dot.net
  version: v1
  scope: Namespaced
  names:
    plural: clusterversions
    singular: clusterversion
    kind: OrleansClusterVersion
    shortNames:
    - ocv
---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: silos.orleans.dot.net
spec:
  group: orleans.dot.net
  version: v1
  scope: Namespaced
  names:
    plural: silos
    singular: silo
    kind: OrleansSilo
    shortNames:
    - oso

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: conversational-orleans-service-account
  
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: conversational-orleans-service-role
subjects:
  - kind: ServiceAccount
    name: conversational-orleans-service-account
    namespace: apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orleans-service-role

---

apiVersion: v1
kind: Service
metadata:
  name: conversational-orleans-silo
spec:
  selector:
    app: conversational-orleans-silo
  ports:
    - port: 80
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orleans-service-role
rules:
- apiGroups: ["orleans.dot.net", ""] # "" indicates the core API group
  resources: ["silos", "clusterversions", "pods"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
```

I also tried running it with the exact example RBAC config of [the docs](https://dotnet.github.io/orleans/docs/deployment/kubernetes.html), to no avail.

```yaml
# The same CRD's + ServiceAccount as above is used here

apiVersion: v1
kind: Service
metadata:
  name: conversational-orleans-silo
spec:
  selector:
    app: conversational-orleans-silo
  ports:
    - port: 80
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
- apiGroups: [ "" ]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ''
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: ''
```

Maybe this has to do with the fact that my silo's run in the namespace `apps` rather than `default`?

**Comment by ReubenBond** [comment]
Hi @Martijnvos, thanks for reporting.

Can you try a couple of things?
1. Add a new `namespace` property to the metadata on that `Role` & `RoleBinding` to match your pod's namespace. Example in the docs here: https://kubernetes.io/docs/reference/access-authn-authz/rbac/
2. Configure your Kubernetes client to use your namespace:

``` C#
siloBuilder.Configure<KubernetesHostingOptions>(options =>
{
    options.GetClientConfiguration = () =>
    {
        var config = KubernetesClientConfiguration.InClusterConfig();
        config.Namespace = options.Namespace; // Or replace this with your namespace
        return config;
    };
});
```

**Comment by Martijnvos** [comment]
Thanks for your quick reply Reuben!

Unfortunately adding the namespaces doesn't fix the issue:

```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: conversational-orleans-service-role
  namespace: apps
subjects:
 ....

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orleans-service-role
  namespace: apps
rules:
...
```

I also added the KubernetesHostingOptions as you suggested:

```c#
return builder
    .UseKubeMembership()
    .UseKubernetesHosting()
    .ConfigureEndpoints(10001, 10002)
    .Configure<ClusterMembershipOptions>(o =>
    {
        o.DefunctSiloCleanupPeriod = TimeSpan.FromMinutes(1);
        o.DefunctSiloExpiration = TimeSpan.FromMinutes(2);
    })
    .Configure<KubernetesHostingOptions>(options =>
    {
        options.GetClientConfiguration = () =>
        {
            var config = KubernetesClientConfiguration.InClusterConfig();
            config.Namespace = "apps";
            return config;
        };
    });
```
I hardcoded "apps" because `options.Namespace` isn't available in `KubernetesHostingOptions`.

**Comment by ReubenBond** [comment]
Interesting. Does it work with a `ClusterRole`/`ClusterRoleBinding`? I'm leaning towards this being a configuration issue with Kubernetes or the Kubernetes client. It might not be an AuthZ issue, maybe it's an AuthN issue on the kube API endpoint.

**Comment by Martijnvos** [comment]
Replacing `Role` with `ClusterRole`, `RoleBinding` with `ClusterRoleBinding` and removing the namespaces didn't help. I'm also seeing `Exception during Silo.Start` errors with the following stacktrace:

```
Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Conflict'
   at k8s.Kubernetes.ReplaceNamespacedCustomObjectWithHttpMessagesAsync(Object body, String group, String version, String namespaceParameter, String plural, String name, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.ReplaceNamespacedCustomObjectAsync(IKubernetes operations, Object body, String group, String version, String namespaceParameter, String plural, String name, CancellationToken cancellationToken)
   at Orleans.Clustering.Kubernetes.KubeMembershipTable.UpdateRow(MembershipEntry entry, String etag, TableVersion tableVersion)
   at Orleans.Runtime.MembershipService.MembershipTableManager.DeclareDead(MembershipEntry entry, String etag, TableVersion tableVersion)
   at Orleans.Runtime.MembershipService.MembershipTableManager.TryKill(SiloAddress silo)
   at Orleans.Runtime.ClusterMembershipService.TryKill(SiloAddress siloAddress)
   at Orleans.Hosting.Kubernetes.KubernetesClusterAgent.OnRuntimeInitializeStart(CancellationToken cancellation)
   at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct)
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute()
   at Orleans.Runtime.Silo.StartAsync(CancellationToken cancellationToken)
```
Another one that might be noteworthy is `Exception when trying to get GrainInterfaceMap for silos S10.42.80.57:10001:351428334`:

```
Orleans.Runtime.SiloUnavailableException: The target silo became unavailable for message: Request S10.42.0.33:10001:351438552*stg/17/00000011@S00000011->S10.42.80.57:10001:351428334*stg/17/00000011@S00000011 InvokeMethodRequest -895522402:-1669561441 #3. Target History is: <S10.42.80.57:10001:351428334:*stg/17/00000011:@S00000011>. See https://aka.ms/orleans-troubleshooting for troubleshooting help.
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem`1.Execute()
   at Orleans.Runtime.TypeManager.GetTargetSiloGrainInterfaceMap(SiloAddress siloAddress)
```

This last one might be due to the 'old' silo winding down, not sure. Does this provide useful information?

**Comment by ReubenBond** [comment]
I think I misunderstood the initial problem. It seems like your silos are starting, but that you're running into some issues afterwards, is that correct? Could you provide more information on the symptoms?

Based on that first error in your latest comment, you're using the Kubernetes Clustering provider. I cannot help much with that, except to say that @galvesribeiro would probably appreciate a PR to handle that exception and not bubble it up.

**Comment by Martijnvos** [comment]
Apologies if I'm unclear. 

I'm indeed using the Kubernetes Clustering provider together with the Kubernetes hosting package.
Functionally speaking it all works correctly. The new silo's are starting and the dead silo's get removed correctly after a deployment. Every 30 seconds I'm getting these `Error monitoring Kubernetes pods` exceptions in the logs though. My train of thought is that it could be some kind of access permission problem due to the Hosting package not having access to the `apps` namespace since the exception mentions the response ending prematurely and other exceptions suggest the silo is not reachable.

I might be off on that though. I'm still quite inexperienced with Orleans and Kubernetes.

**Comment by ReubenBond** [comment]
Is your ServiceAccount also in the 'apps' namespace?

You could try testing listing the pods without having Orleans involved, just using the Kubernetes client from C#

**Comment by Martijnvos** [comment]
Running `kubectl -n apps get serviceaccount` returns the ServiceAccount `conversational-orleans-service-account`, which you can see specified in the `deployment.yaml` of my initial post.
All pods and deployments are healthy.

**Comment by ReubenBond** [comment]
Did the TaskCancelledException in your original post occur during shutdown?

**Comment by Martijnvos** [comment]
This error also appears after the dead silos are removed. In fact, it get's thrown every 1 minute and 45 seconds.

**Comment by ReubenBond** [comment]
Are you seeing any other warnings or errors in the logs, or are the errors all related to Kubernetes?

**Comment by Martijnvos** [comment]
No other errors or noteworthy logs unfortunately.

The silo `.csproj` contains PackageReferences to `Microsoft.Orleans.OrleansCodeGenerator`, `Microsoft.Orleans.OrleansRuntime` and `Microsoft.Orleans.OrleansProviders` all of which are on version 3.4.1.

The `Grains` and `Interfaces` projects have a `.csproj` containing `Microsoft.Orleans.Core.Abstractions`, `Microsoft.Orleans.OrleansCodeGenerator` and `Microsoft.Orleans.OrleansRuntime`.

Am I missing something?

**Comment by ReubenBond** [comment]
I was thinking perhaps you're seeing some kind of slowdown (eg, because of blocking IO), causing the request to timeout. Is the system under any load? Perhaps the system is operating normally

**Comment by Martijnvos** [comment]
This is run on a test environment where after deployment it runs without load (no-one uses the system).

**Comment by Martijnvos** [comment]
Found something curious: I'm running 3 silo's which all have the same problem. During the weekend it looks like 2 stopped spewing the error while one still does. Redeploying made all three start outputting the error again. Maybe it is something that's fixed with time or our test environment acts strange. I'll try running everything locally to see if that gives other results.

**Comment by ReubenBond** [comment]
Are you able to test running this in the default namespace?

**Comment by Martijnvos** [comment]
I tried running this locally with both `apps` and `default` namespaces to no avail. Still getting `System.IO.IOException: Unable to read data from the transport connection: Operation canceled.`

**Comment by Martijnvos** [comment]
Do you have other ideas about ways this can occur? I currently can't think of any other logical explanation.

**Comment by Martijnvos** [comment]
@ReubenBond I'm blocked by this. Do you have other theories?

**Comment by ReubenBond** [comment]
If you're blocked, I recommend not using the integration for the time being - it's not required.

If you can create a repro, I can work with you to solve it.

**Comment by worldspawn** [comment]
I'm also experiencing the same behaviour. Like the op i'm also using the clustering package.  I don't think there is a security issue at work here as without the configured roles I just get Forbidden errors.

My cluster is brand new and has nothing on it but this single silo instance. My log output is pretty much identical to the ops.

I also had the Conflict exception at one point and resolved it by deleting all the silos/clusterversions resources.

In case there is something relevant elsewhere in the logs i've dumped the last 2000 lines here: https://pastebin.com/kR0WJ9Tt

Please ignore the other exceptions (like sql), i'm still getting this env up and running.

**Comment by Martijnvos** [comment]
To be more specific, the error originates from https://github.com/dotnet/orleans/blob/c3a0f70ab2ada30106ae9cdcbd6ad3f4ec8d4e49/src/Orleans.Hosting.Kubernetes/KubernetesClusterAgent.cs#L218 which calls the C# Kubernetes client method `ListNamespacedPodWithHttpMessagesAsync()` found in [this file](https://raw.githubusercontent.com/kubernetes-client/csharp/c4d1f852a22320eddb9553c0f5c85f2f7ee563b0/src/KubernetesClient/generated/Kubernetes.cs).

Why its an IO Exception in the Orleans library isn't clear to me, as that k8s client method only defines these exceptions:

- HttpOperationException
- SerializationException
- ValidationException
- System.ArgumentNullException

**Comment by worldspawn** [comment]
I've read anecdotally that TaskCancelled from a http call is _probably_ a timeout. I'm going to try it with a vanilla silo (no user code) on the same cluster and will report back.

**Comment by ReubenBond** [comment]
Can you both show me your host builder code? @worldspawn I suspect you have an ordering issue in your hosted services

Is the service failing to start in time and being told to exit? We can add a check to see if the shutdown cancellation token is being canceled and avoid logging certain exceptions in that case.

**Comment by worldspawn** [comment]
@ReubenBond thanks for your reply. I'm swamped with a prod issue atm will swing back here next week.

**Comment by worldspawn** [comment]
Heres the UseOrleans part.

``` csharp
.UseOrleans((ctx, siloBuilder) => 
                {
                    var config = new ConfigHelper();
                    var configData = new SiloConfigData
                    {
                        StatisticsLevel = StatisticsLevel.Info,
                        DataConnection = config.Get(config.Keys.DataConnectionString),
                        EventHubConnection = config.Get(config.Keys.EventHubConnection),
                        EventHubName = config.Get(config.Keys.EventHubName),
                        RedisHost = config.Get(config.Keys.RedisHost),
                        RedisAccesskey = config.Get(config.Keys.RedisAccesskey),
                        RedisPrefix = config.Get(config.Keys.RedisPrefix),
                        NodeIpAddresses = config.Get(config.Keys.OrleansSiloIpAddresses)?.Split(',')
                    };

                    var clusterId = config.Get(config.Keys.OrleansClusterId);
                    var serviceId = config.Get(config.Keys.OrleansServiceId);
                    if (kubernetesMode)
                    {
	                    siloBuilder.UseKubernetesHosting().UseKubeMembership();
                    }
                    else
                    {
                        siloBuilder.ApplyAzureClusterConfiguration(configData.DataConnection)
		                    .Configure<EndpointOptions>(options =>
		                    {
			                    options.AdvertisedIPAddress = configData.NodeIpAddresses != null && configData.NodeIpAddresses.Any()
				                    ? IPAddress.Parse(configData.NodeIpAddresses.FirstOrDefault() ?? IPAddress.Loopback.ToString())
				                    : Dns.GetHostAddressesAsync(Dns.GetHostName()).Result.FirstOrDefault();
		                    });
                    }

                    //, clusterId
                    siloBuilder.ApplyHostingConfiguration(configData, clusterId, serviceId)
	                    .ConfigureLogging(logging => logging.AddConsole())
                        .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(HelloGrain).Assembly).WithReferences())
                        .AddMemoryGrainStorageAsDefault()
	                    .AddStartupTask<AutoStartProvider>();  // register provider to start background timers
                })
```
