### ISSUE TITLE
StatelessWorker with maxLocalWorkers = 1 creates two activations and then kills one

### ISSUE THREAD

**Issue by MhinRa** [dotnet/orleans#6985]
This issue is observed in 3.4.1.   If you send two messages to a stateless worker grain with maxLocalWorkers = 1 at almost the exact same time, two activations of the stateless worker are created, each processing one of the messages.   Then one of the instances appears to be killed (it never gets the timer callback you can see below and the data relay that timer would have triggered never happens for the message received by the dead activation).

The fact that there are two activations was verified by doing a Guid.NewGuid() in the grain constructor and then logging it.   Two different guids were observed for the first two messages, after which only one of those guids was ever seen again.

An abbreviated version of the grain is below.   I have not verified that this exact code will reproduce the issue, although (other than some initialization stuff), this contains all the code which was being executed on the stateless worker grains.   As part of debugging the issue, I believe I observed that the grain message (which is 'ReportTicket' in the below example) being very, very fast increases the chances of the multiple activations happening.   Notably, you can see below that the method executes synchronously and essentially just adds an item to a list and creates a timer.   I saw the issue happen between 30 and 50% of the time when the grain was being initially activated.

An abbreviated version of the grain in question is this:

    [StatelessWorker(maxLocalWorkers: 1)]
    public class MetricsRelayGrain : CoolBaseClasses
    {
        public MetricsRelayGrain()
        { }

        private void AddPendingRequest(BasketMetricsRequest request)
        {
            this.PendingRequests.Add(request);
            if (this.PendingRequestTimer == null)
            {
                this.PendingRequestTimer = this.TimerManager.Enqueue(TimeSpan.FromSeconds(2));
            }
        }

        public Task ReportTicket(TicketMetric ticketMetric)
        {
            this.AddPendingRequest(new ReportTicketMetricRequest(ticketMetric));
            return Task.CompletedTask;
        }
    }

**Comment by benjaminpetit** [comment]
Fixed with #6988, the fix will be included in 3.4.2
