### ISSUE TITLE
The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')

### ISSUE THREAD

**Issue by Difficulty-in-naming** [dotnet/orleans#6987]
.net 5
Turn on one silo
Error pops up every 5 minutes on membership
```The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')```
I tried to trace the code
I found it in the UpdateIAmAlive of the MembershipTableManager. A MembershipEntry is created, which contains a StartTime variable. Its value is 0001/1/1, which causes the above error
I checked the Orleans documentation. I used Google to look for keywords, but didn't find the answer

**Comment by ReubenBond** [comment]
@Difficulty-in-naming are you able to provide some more detail such as the clustering provider you are using and how it's configured?

**Comment by Difficulty-in-naming** [comment]
@ReubenBond Thanks for your Answer
that my Silo Code
![image](https://user-images.githubusercontent.com/8246779/109087430-68879a00-7748-11eb-925a-29d6324f0fb6.png)

that my client
![image](https://user-images.githubusercontent.com/8246779/109087739-02e7dd80-7749-11eb-88e5-5388cbb694a2.png)

**Comment by ReubenBond** [comment]
Perhaps this is an issue with the Cosmos DB clustering provider. Are you able to find the issue in code?

**Comment by ReubenBond** [comment]
I believe this was fixed in OrleansContrib/Orleans.CosmosDB#49
