### ISSUE TITLE
Orleans ClusterClient disconnected unexpectedly

### ISSUE THREAD

**Issue by doctorcode-org** [dotnet/orleans#6997]
Hi
I create an IHostedService and initial a client. then inject services as a singleton to get IClusterClient service. but this client disconnected immediately after first use.
I create a repo and upload my sample project to [sample repo](https://github.com/doctorcode-org/OrleansSample)

**Comment by ReubenBond** [comment]
My initial guess would be that the client program is exiting normally after the request. I will close this, since I was too slow at responding and the repro repo is gone + it sounds like you've made progress based on other comments.
