### ISSUE TITLE
Client is not responsive until timeout(30minutes) occurs, if number of silo has more than 2 nodes(machine), Is there any configuration to configure number of silo in a cluster?

### ISSUE THREAD

**Issue by selvakumarmca** [dotnet/orleans#7001]
If number of silo is **2**(running a **single silo in  each machine**) in a UseAdoNetClustering, then the client is **getting result**. If we **add one more silo** from another machine, then the Client is not responsive until timeout(30minutes) occurs. Is there any configuration to configure number of silo in a cluster?

**Comment by ReubenBond** [comment]
Did the client on the other machine manage to connect to the cluster?
