### ISSUE TITLE
Propagate host name as cluster address

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#7013]
Hello,

I am developing a headless CMS (https://github.com/squidex/squidex) that is using Orleans and is also used by thousand of users and clients. Therefore I also have to deal with issues when people have problems with Orleans. I think it would make my live much easier when the clustering mode would use host names instead of IP addresses. Just yesterday a customer had issues because has has forgotten to clear the membership table after restoring a backup. The host names are often "static" but not the IP addresses. For example you could use stateful sets in kubernetes.

**Comment by veikkoeeva** [comment]
Or in general there could be a provider model, e.g. a `Func` that would give this information. By default it could be IP but switchable to a one that gives a host name or something else.

**Comment by ReubenBond** [comment]
@SebastianStehle the Microsoft.Orleans.Kubernetes.Hosting package does that, along with a sample here: https://github.com/ReubenBond/hanbaobao-web and in the docs here. 

That package prevents such issues by asking Kubernetes what pods exist, so if the user deletes their deployment and redeploys, then those old silos will be cleaned up automatically.

Would that work for you?

**Comment by SebastianStehle** [comment]
Partially. I think it does make my live that much easier because you have to configure a lot of things.
