### ISSUE TITLE
[Question] Same Grain (with the same ID) stored in memory at multiple silos in the same time

### ISSUE THREAD

**Issue by fernandozago** [dotnet/orleans#7020]
Hey guys.
How everyone is doing ?

So. I'm trying to sync the same grain within multiple silo instances.

Lets say, 
I have a Grain with a integer unique id (100) persisted in memory.

The reason behind this is, I want to be able to retrieve the latest piece of data, even if my silos scale down and without persist the data on cold repository.

There is a easy way to do that ? or i'll have to manage this setup myself ?

**Comment by wanton7** [comment]
Grain ids are unique so I don't that is possible. Here is one solution using replica grain and reactive caching pattern https://github.com/dotnet/orleans/issues/6772#issuecomment-705845659

**Comment by creyke** [comment]
Sounds like a job for [stateless workers](https://dotnet.github.io/orleans/docs/grains/stateless_worker_grains.html).

**Comment by ReubenBond** [comment]
There is no automated cache, but the solutions which @wanton7 and @creyke provided can form a good basis. I'll close this, but if there is more to discuss or a feature request, please feel free to open a new issue which references this one.
