### ISSUE TITLE
Support byte[] grain key to avoid GC pressure of wrapping it in a string

### ISSUE THREAD

**Issue by craigajohnson** [dotnet/orleans#7024]
The scenario is - some of our entity IDs contain other elements that fall outside the string/guid/int/string+guid/string+int options. For our own purposes we create IEquatable ref structs (with fixed buffers for string content) for locality of reference, avoiding the GC heap when used as dictionary keys, etc.

I am happy to be responsible for deserializing the byte[] as needed. Seems that it would also need to do a value comparison and a hash that respects that (appears to be plenty of high perf implementations out there for both)

It appears the only solution at this time is to represent the byte[] as a string. My main concern here is the extra GC incurred.

For the record, I do NOT think that Orleans should contain any type of key serialization/deserialization logic. But having the escape hatch of a byte[] key (with value comparison) would be immensely helpful

**Comment by ReubenBond** [comment]
Hi @craigajohnson, the GrainIds in `main` are backed by byte arrays now. Ideally, I would prefer to use UTF8 strings for the purpose of logging

**Comment by craigajohnson** [comment]
@ReubenBond thank you. I agree the byte[] are not inherently easy to reason over from a debugging perspective until they are deserialized. But that is excellent to hear the trunk uses byte[] internally and I hope the use case above (and others) would justify it on the public interface
