### ISSUE TITLE
Improve structured logging

### ISSUE THREAD

**Issue by waitxd** [dotnet/orleans#7025]
I'd like to improve logging of Orleans by using named arguments in logs as initial stage of "better logging initiative".
This will open doors to search and aggregate by log parameters and better integration with structured log provides, such as Serilog, NLog, etc.

## Examples
Simple case where named arguments are not used at all.
https://github.com/dotnet/orleans/blob/a2e48255fe797d7109deb46287081d165573e7ae/src/Orleans.Runtime/MembershipService/MembershipTableManager.cs#L615-L618

Can be rewritten as:

```c#
if (log.IsEnabled(LogLevel.Debug))
    {
        log.LogDebug("TryKill: Read Membership table {Table}", table);
    }
```

Log template is constructed by string.Format, not being unique string and arguments are not passed to the logger.
https://github.com/dotnet/orleans/blob/a1eebad4c4ecca9de24d25d697d7413686842b32/src/Orleans.Streaming/SimpleMessageStream/SimpleMessageStreamProducerExtension.cs#L205-L206
Can be simplified as:

```c#
    this.logger.LogWarning("Ignoring exception while trying to evaluate subscription filter '{StreamFilter}' with data '{FilterData}' on stream {StreamId}", streamFilter.GetType().Name, filterData, streamId);
```

Argument is not used, because template argument gets inlined by `string.Format`.
https://github.com/dotnet/orleans/blob/d9a22985c6b066837c7e1383bf5b1c672f560f4a/src/Orleans.Core/Configuration/OptionLogger/IOptionsLogger.cs#L82
Correct version:

```c#
    this.logger.LogError(ex, "An error occurred while logging options {FormatterName}", formatter.Name);
```

## More issues with logging
However, while looking through code I found some more issues of different types, but related to logging, there are few examples of them:

- ### Unnecessary allocations

  This code will translate to string.Concat(string.Format(...), string.Format(...)) causing extra allocations.
  https://github.com/dotnet/orleans/blob/921fcb40158c9e264208383370dd26e52b1af239/src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs#L464-L465

- ### Unobserved exceptions

  Exception passed as one of template parameters (even unused in first example), rather than dedicated `exception` parameter.
  https://github.com/dotnet/orleans/blob/c3a0f70ab2ada30106ae9cdcbd6ad3f4ec8d4e49/src/Orleans.Core/Hosting/ApplicationLifetime.cs#L72-L75
  https://github.com/dotnet/orleans/blob/10d58d6747520b52223a3db7d6a803b78214644e/src/Orleans.Runtime/Lifecycle/SiloLifecycleSubject.cs#L125-L134

- ### Wrong template syntax

  First parameter is unobserved due typo in template (wrong closing bracket).
  https://github.com/dotnet/orleans/blob/769729dbcb714c5542626b37aca3a13a6d1d2382/src/Orleans.GrainDirectory.Redis/RedisGrainDirectory.cs#L162
  https://github.com/dotnet/orleans/blob/769729dbcb714c5542626b37aca3a13a6d1d2382/src/Orleans.GrainDirectory.Redis/RedisGrainDirectory.cs#L165

- ### Not consistent logging style

  Mix of using LoggerExtensions and [legacy wrapper](https://github.com/dotnet/orleans/pull/3333).
  https://github.com/dotnet/orleans/blob/87f217870a6b73003bbf251192363c8f41ff2b67/src/Orleans.Runtime/Silo/Silo.cs#L125-L135

- ### Thin wrappers to `Microsoft.Extensions.Logging`

  There are multiple thin wrappers in code, basically doing nothing. Static analyzers (e.g. Roslyn/Resharper/Rider ones) are not able to detect these method's arguments as structured log templates and therefore are unable to analyze. And extra method call will hurt performance if JIT somehow decide to not inline it. I propose to eliminate them all and use `Microsoft.Extensions.Logging` directly.
  https://github.com/dotnet/orleans/blob/48dedcff87a3245efe2d704ccd91d6e55d501d62/src/Orleans.Core/Logging/ILoggerExtensions.cs#L20-L23
  https://github.com/dotnet/orleans/blob/d59798ad95cad2a1870ce62c2b7f8c2a477732cc/src/Orleans.Streaming/Common/SimpleCache/SimpleQueueCache.cs#L317-L321
  https://github.com/dotnet/orleans/blob/a0b03bd879771e2c197935e16f277000fb534272/src/Orleans.Streaming.GCP/GoogleErrorCodes.cs#L19-L22

- ### Following naming rules
  Best practice is to name arguments uppercase.
  https://github.com/dotnet/orleans/blob/87f217870a6b73003bbf251192363c8f41ff2b67/src/Orleans.Runtime/Messaging/Gateway.cs#L141-L145

- ### Log event messages should not be sentences
  Best practice is to avoid trailing period in messages, because log messages are fragments, not sentences.
  https://github.com/dotnet/orleans/blob/6a626eb65a1011ca1eb2a62e1b010566c0aa8798/src/Orleans.Runtime/Silo/Watchdog.cs#L105-L112

- ### Not all logging calls are guarded with `.IsEnabled()`
  All default logging providers do `.IsEnabled()` check in `Log` function, so there is no need to guard `.Log()` calls with `.IsEnabled()`.
  However, arguments in `Log()` functions are passed as `params` array, therefore there will be an extra array allocation even if logging is disabled.
  https://github.com/dotnet/orleans/blob/1d7e3270e81ad47179a44b4f76520e552b734ee1/src/Orleans.Core/Networking/ConnectionManager.cs#L157-L169

## Downsides

My bigger concern is performance. 
This code is not causing extra allocations for reference types due one argument overload in `string.Format(string format, object? arg0)`.

```c#
logger.LogError(ex, $"An error occurred while logging options {formatter.Name}");
```

But because of `params` argument, this code does (allocate new array for params). Parsing template with named arguments for the first time adds too.

```c#
logger.LogError(ex, "An error occurred while logging options {FormatterName}", formatter.Name);
```

There are few ongoing issues in dotnet/runtime repo:
- [Allocation-free logging for disabled log levels](https://github.com/dotnet/runtime/issues/36012)
- [Strongly-typed logging source generator](https://github.com/dotnet/runtime/issues/36022) with [PR draft](https://github.com/dotnet/runtime/pull/49472)

It might be not a problem for rare log events and events disabled by log level (if they are guarded by `.IsEnabled()` call). For frequent events we can utilize `LoggerMessage` with pre-parsed templates captured in lambda
functions, like we already do:
https://github.com/dotnet/orleans/blob/3874c5350421571273478b936651a546ee09b993/src/Orleans.Core/Networking/Shared/SocketsTrace.cs#L10-L11
Personally, I find using this pattern everywhere a bit cumbersome. But if we decide to follow this path (in mind to sometime use logging source generator), in followed PR we can create such lambdas and invoking functions for each `Orleans.ErrorCode` and split them into different extension classes (to prevent lambda initialization if some parts of Orleans are not used, e.g. Streams or ServiceFabric).

Or we can create helper with allocation-free overloads for 1-5 arguments. It will require some code duplication from `Microsoft.Extentions.Logging` (named arguments parsing logic, because of `internal` keyword on `Microsoft.Extensions.Logging.LogValuesFormatter` class).

I will prepare a PR if you are OK with all/some of these changes, so what do you think?

**Comment by ReubenBond** [comment]
Hi @waitxd, any help here is greatly appreciated, thank you for the great writeup, and apologies for the slow response.

I agree that LoggerMessage should not be used everywhere, because it can indeed be cumbersome.

Those thin wrapper methods were used as a quick way to port over from Orleans' internal logging system to Microsoft.Extensions.Logging in the 2.0 timeframe, but ultimately they should be removed.
