### ISSUE TITLE
Having to set SchedulingOptions.AllowCallChainReentrancy to false to prevent turn interlacing from external tasks

### ISSUE THREAD

**Issue by creyke** [dotnet/orleans#7026]
I have a grain which spawns a number of local worker POCOs (not grains) which in turn hop off the Orleans scheduler and onto the thread pool before periodically making a call back to the grain via it's reference using the method described [here](https://dotnet.github.io/orleans/docs/grains/external_tasks_and_grains.html#advanced-example---making-a-grain-call-from-code-that-runs-on-a-thread-pool).

Unexpectedly these calls back into the grain interlace with each other, and do not follow the turn-based concurrency guarantees, despite:
- Using `Task.StartNew()` back onto the Orleans scheduler as proposed in the method above.
- Passing the reference `AsReference()`.
- **Not** using `[Reentrant]` attributes on the grain or methods of the grain

To resolve this, I have had to set `SchedulingOptions.AllowCallChainReentrancy` to `false` globally, which feels like using a sledgehammer to crush a nut.

**Comment by ReubenBond** [comment]
Are you able to share a code sample or repro?

**Comment by creyke** [comment]
Here's a [minimum code repro](https://github.com/creyke/OrleansTurnbasedExternal) which logs the number of concurrently active turns.

All business logic, error handling, disposal etc. is removed as well as lifecycle management of grain and worker.

**Comment by ReubenBond** [comment]
Thanks for the repro. I understand better now. The call is being made in the context of the grain (on the grain's scheduler). I changed the code to not make the grain call on the grain's scheduler (it is not needed anymore) and the results show that there is no overlapping execution. See the changes here: https://github.com/creyke/OrleansTurnbasedExternal/pull/1

I've updated the docs: https://github.com/dotnet/orleans-docs/commit/9d09428daf43da2fe23fb6cb951239ec22f75afb

**Comment by yevhen** [comment]
I just disable this from the beginning in every project. I was bitten too many times by this feature.

**Comment by ReubenBond** [comment]
@yevhen yep, I was also unhappy with the implementation. It's been removed from the `main` branch, but we didn't want to make a behavior change for 3.x

**Comment by creyke** [comment]
> I changed the code to not make the grain call on the grain's scheduler (it is not needed anymore) and the results show that there is no overlapping execution. See the changes here: [creyke/OrleansTurnbasedExternal#1](https://github.com/creyke/OrleansTurnbasedExternal/pull/1)

Great - thanks for the quick response.
