### ISSUE TITLE
Release for BinaryFormatter Removal?

### ISSUE THREAD

**Issue by bcuff** [dotnet/orleans#7028]
I'm currently using the latest release, **3.4.1**. I'm running on **dotnet 5** so I'm still running into errors related to **BinaryFormatter** not being supported in dotnet 5 when exceptions are thrown. I noticed that https://github.com/dotnet/orleans/pull/6922 removes BinaryFormatter but this change isn't in the 3.4.1 release.

Will there be a release that includes this change in the near future?

Thanks.

**Comment by ReubenBond** [comment]
Hi Brandon, it would be a breaking change to release that in 3.x, but there are workarounds:
https://github.com/dotnet/orleans/issues/6805#issuecomment-717778302

Ultimately, maybe we will need to make that breaking change, since the workaround is a hassle. cc @bradygaster

**Comment by bcuff** [comment]
Yeah, I saw the workaround but I was reluctant to do that.

**Comment by ReubenBond** [comment]
Fixed by #7198
