### ISSUE TITLE
[Question]: Ability to disable statistics for client & server?

### ISSUE THREAD

**Issue by branimirg** [dotnet/orleans#7030]
Is there a configuration-based way or otherwise which will allow to disable statistics completely? 
I want to be able to use configuration or an extension method or otherwise code-based approach for interaction with this API.
It should also stay in effect and override otherwise-configured monitoring, like Orleans Dashboard which I think ignores global cluster-level settings.

Is this currently available in Orleans?

**Comment by ReubenBond** [comment]
Apologies for the slow response, @branimirg.

I'd like to understand why you want to disable statistics?

Some of the statistics collected by the dashboard are collected via custom grain call filters, so they wouldn't respond to any in-box settings unless they were explicitly respected by OrleansDashboard (in that case, though, maybe just disabling the dashboard is the right thing to do).

There are some options: you can set `StatisticsOptions.CollectionLevel` to lower the amount of collected statistics.

**Comment by highlyunavailable** [comment]
I personally also want to disable this. It's because the statistics are log spam and I do not want them in my logs. I'd love to be able to collect the statistics and export them as OpenMetrics style stats, but as it stands they're just junk and entirely unparseable from a log standpoint, especially since even with JSON logging, they just come out as a massive text blob rather than a JSON object.

**Comment by highlyunavailable** [comment]
Oh, and the worst part? Setting the log level does _nothing_. I have this in my appsettings:

```
"Orleans.Runtime.SiloLogStatistics": "Error",
"Orleans.Runtime.ClientLogStatistics": "Error"
```

And while it's respected for all other logs, the stats logs don't respect it. I'm not sure why.

**Comment by ReubenBond** [comment]
Strange that setting the log level doesn't work. You can disable logging statistics by setting the write interval to `Timeout.Infinite`, which is equal to -1 ms. Eg, I tested this locally:

``` C#
builder.Configure<StatisticsOptions>(options => options.LogWriteInterval = TimeSpan.FromMilliseconds(-1));
```

**Comment by highlyunavailable** [comment]
Thanks! Great to know that.

**Comment by highlyunavailable** [comment]
Oh, speaking of "Things that don't respect the logging level": another one is the `Orleans.Messaging.GatewayManager` logging. For example:

https://github.com/dotnet/orleans/blob/main/src/Orleans.Core/Messaging/GatewayManager.cs#L236

This debug message is always logged, no matter the level set in the logging. Not to hijack this issue too much but I think it's a larger problem.

**Comment by ReubenBond** [comment]
> Oh, speaking of "Things that don't respect the logging level": another one is the `Orleans.Messaging.GatewayManager` logging. For example:
> 
> https://github.com/dotnet/orleans/blob/main/src/Orleans.Core/Messaging/GatewayManager.cs#L318
> 
> This message is always logged, no matter the level set in the logging. Not to hijack this issue too much but I think it's a larger problem.

That's very strange - the logging isn't controlled by Orleans, it's directly controlled by Microsoft.Extensions.Logging
