### ISSUE TITLE
Singleton GrainService

### ISSUE THREAD

**Issue by turowicz** [dotnet/orleans#7032]
Is it possible to create a GrainService in such a way, that we only get a single instance in one of the silos?

**Comment by turowicz** [comment]
(Currently Orleans will spin up one GrainService for each Silo)

**Comment by turowicz** [comment]
cc @ReubenBond

**Comment by ReubenBond** [comment]
@turowicz why not use a regular grain with a constant id? In other words, what benefit does a GrainService provide in this case?

**Comment by turowicz** [comment]
The scenario I'm trying to fill is that I need a background process that will go through many different grains and make sure the data in the state is correct, if not tell grain to regenerate data.

**Comment by turowicz** [comment]
And I would like that background process to be a part of the silo, without having to start it from external service.

**Comment by turowicz** [comment]
Something like IHostedService in ASP.NET

**Comment by turowicz** [comment]
But I see your point, I could use the GrainService to start that particular grain you mentioned. Race condition is not a problem and also I could have a cooldown for being called too often.

**Comment by ReubenBond** [comment]
@turowicz You could implement a regular .NET Generic Host [`BackgroundService`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.backgroundservice?view=dotnet-plat-ext-5.0) and have them listen for cluster membership changes via an async foreach over `IClusterMembershipService.MembershipUpdates`. When they find that their silo is the first (eg sorting via 'sSiloAddress.GetConsistentHashCode()`), then they can activate and start processing.

That's assuming that you want to try to avoid having all silos perform that work.

Alternatively, you can use a regular grain service and use the `IRingRange` passed to `OnRangeChange` to find out who is responsible for position `0` (or any constant number).

If you want to divide the work, then each GrainService can determine which grains they are responsible for using the above method, given a consistent hash code of the grain's id.

**Comment by turowicz** [comment]
Just to keep it simple I will first try the GrainService -> Singleton Grain approach.
