### ISSUE TITLE
Record type used as collection generic parameter of grain method return type causes System.TypeAccessException

### ISSUE THREAD

**Issue by syberside** [dotnet/orleans#7033]
# Description
[Minrepo: https://github.com/syberside/ms_orleans_record_array_support_bug](https://github.com/syberside/ms_orleans_record_array_support_bug)
Using record type as a collection generic parameter of grain causes `TypeAccessException` on client activation.
If record is used as generic parameter of `Task` everything works correctly. Replacing record with regular class fixes the issue. Replacing `Record[]` with `List<Record>` doesn't solve problem.
So it looks like error is related to client code generation for collections and records.
# Steps to reproduce:
1. Create project using tutorial https://dotnet.github.io/orleans/docs/tutorials_and_samples/tutorial_1.html
2. Create record type in interface library, for example `public record RecordDto(string Value);`
3. Change result type of SayHello to array of record types, for example `Task<RecordDto[]> SayHello(string value)`
4. Apply fixes in HelloGrain due to result type change.
5. Try to run client and silo
# Actual result
Exception `System.TypeAccessException: Named type "MinRepo.Grains.Interfaces.RecordDto" is invalid: Type string "MinRepo.Grains.Interfaces.RecordDto" cannot be resolved.` while creating client.
# Expected result 
No exception

**Comment by oising** [comment]
The Orleans serializer (which is custom for reasons of perf) cannot serialize/deserialize records (yet.)

**Comment by syberside** [comment]
@oising are there any plans to support it?

However, it looks like only small changes to serializer/deserializer are required. Exception is thrown only for record type used as array or collection generic parameter. If method returns single record or DTO with a record field than everything works fine.
