### ISSUE TITLE
Heterogeneous cluster does not listen to all partitions for EventHubStreams

### ISSUE THREAD

**Issue by sunniejai** [dotnet/orleans#7037]
We have 32 partitions on EventHub and we have a total of 6 silos 

- 3x Silo A that listens to the Event Hub streams 
- 3x Silo B that don't listen to the event hub streams 
   - It doesn't listen because it doesn't call AddEventHubStreams in ConfigureSilo
   - It also doesn't host the grains that would listen to the EventHub Streams provider
- We are just using the default queue balancer. (haven't tried UseConsistentRingQueueBalancer, or UseLeaseBasedQueueBalancer yet

We're seeing that when it's configured this way, the 3 Silo As doesn't listen to all 32 partitions. It's balanced out with the other silos that are not listening to the event hub streams. As a result, some messages in the Event hub are not being processed. Is there a way to change this behavior?

Note: We saw that when we shut down all Silo B, the 3 Silo A would pick back up all the partitions for the queue.

**Comment by benjaminpetit** [comment]
The default queue balancer is `ConsistentRingQueueBalancer`. This balancer assumes that all silos have the same configuration. 

I think the `LeaseBasedQueueBalancer` would be the most appropriate for your usage and the easiest to configure.

The `DeploymentBasedQueueBalancer` could also work if your cluster is totally static when using it with `StaticClusterDeploymentOptions`. Otherwise you could implement your own `IDeploymentConfiguration` to use with the `DeploymentBasedQueueBalancer`.

**Comment by sunniejai** [comment]
I just gave this a test with the `LeaseBasedQueueBalancer` and also read through the code, but was still seeing the same behavior as I described.

I am only running 1x Silo A and 1x Silo B in this case.

Initially when Silo A starts, the log mentions
```
Executing QueueChangeNotification number 1. Queue balancer says I should now own 32 queues
```

But as soon as Silo B starts, the Silo A log mentions
```
Executing QueueChangeNotification number 2. Queue balancer says I should now own 16 queues: [...]
About to remove 16 agents from my responsibility
```

Looking at the code, I don't see how it filters the activeSilos based on if it pulls from the StreamProvider or not. Is there something else that I need to config with `LeaseBasedQueueBalancer `? I am just using the defaults by adding a `UseAzureBlobLeaseProvider` and `UseLeaseBasedQueueBalancer`

**Comment by benjaminpetit** [comment]
You are right, the `LeaseBasedQueueBalancer` still assume that all silos are configured the same, my mistake.

I think the only solution in your case (if you want to keep this configuration) is to implement your own `IStreamQueueBalancer` and inject it. You can derive from `LeaseBasedQueueBalancer`, and then filter with your own logic.

**Comment by sunniejai** [comment]
I don't know the Orleans code that well. Is there someway I can figure out if a Silo is setup with a specific StreamProvider just with the `SiloAddress`?

**Comment by benjaminpetit** [comment]
Nothing built-in unfortunately. You would have to implement something that would read/write from a table storage for example.

In the future we might be able to pass the silo name, and you could do some logic on that.

**Comment by archonandrewhunt** [comment]
Appreciate the guidance Benjamin! We ended up following your advice and derived a new balancer based on LeaseBasedQueueBalancer which uses a grain to allow the eventhub processing silos to advertise this fact to each other. 

Here's our implementation at the moment, for anyone else who may land here https://gist.github.com/archonandrewhunt/02d7881f9f2e08d9cadb46e18eeb1660

**Comment by benjaminpetit** [comment]
Closing this issue, since you managed to find a solution :)
