### ISSUE TITLE
Can client code decide to commit or abort prepared transaction?

### ISSUE THREAD

**Issue by DunetsNM** [dotnet/orleans#7040]
Do I understand correctly that `[Transaction]` attribute is the only way to define scope of transaction and commit/abort are always implicitly executed by the Orleans runtime? 

Is it possible in principle to just prepare transaction and defer the commit / leave it up to the client code to commit or abort  it?
Under the "client code" I mean a caller outside of Orleans runtime e.g. some legacy system.

**Comment by jsteinich** [comment]
The scope of the transaction is defined by the grain call. That grain call could in theory be calling out to a legacy system or awaiting some other grain call being made; however, transactions by default have a lower timeout than regular grain calls.

**Comment by ReubenBond** [comment]
Thanks, @jsteinich!

@DunetsNM I believe that @jsteinich's response answers your question, so I will close this. Please feel free to open a new issue if there are other questions
