### ISSUE TITLE
Custom serializer not picked up during deployment

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#7041]
Hi,

I have a custom type that is used to represent types that need to be serialized using json serializer:
https://github.com/Squidex/squidex/blob/master/backend/src/Squidex.Infrastructure/Orleans/J%7BT%7D.cs

 It works as expected but during deployments i have a few cases where the serializer is not picked up.
 
 I see exceptions like 
 
 ```
System.TypeAccessException: Named type "Squidex.Infrastructure.Orleans.J`1<Squidex.Infrastructure.Commands.CommandRequest>" is invalid: Type string "Squidex.Infrastructure.Commands.CommandRequest" cannot be resolved.
at Orleans.Serialization.BinaryTokenStreamReaderExtensinons.ReadSpecifiedTypeHeader[TReader]
at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader]
at Orleans.Serialization.BuiltInTypes.DeserializeInvokeMethodRequest
at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader]
at Orleans.Runtime.Messaging.MessageSerializer.OrleansSerializer`1.Deserialize
at Orleans.Runtime.Messaging.MessageSerializer.TryRead
at Orleans.Runtime.Messaging.Connection.ProcessIncoming
```

Unfortunately I do not have more details, but it could be a race condition or so.

It also happens when sending requests.

```
System.TypeAccessException: Named type "Squidex.Infrastructure.Orleans.J`1<Squidex.Infrastructure.Commands.CommandRequest>" is invalid: Type string "Squidex.Infrastructure.Commands.CommandRequest" cannot be resolved. at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
at Squidex.Infrastructure.Commands.GrainCommandMiddleware`2.ExecuteCommandAsync (GrainCommandMiddleware.cs:52)
[...]
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute
```

My environment:

* Net5
* Docker / Kubernetes
* Linux 
* Orleans: 3.4.1

**Comment by ReubenBond** [comment]
I believe the issue here is not that the serializer isn't being picked up, but rather that the type being sent (eg, `Squidex.Infrastructure.Commands.CommandRequest`) is unknown.

Orleans uses its own type name formatting and in in this case, it isn't aware of the type name.
To fix it, you can use `[KnownType(typeof(T))]` attribute in an assembly which has codegen enabled to add a specific type or `[KnownAssembly(typeof(T))]` to add an entire assembly to identify the types.

**Comment by SebastianStehle** [comment]
The type is part of an assembly and directly part of an grain interface. It also happens for a few requests only and then it works like normal.

**Comment by ReubenBond** [comment]
If the type is changed from a `record` to a `class`, does it work reliably?

**Comment by SebastianStehle** [comment]
I have to test it, it happens very sporadically only.

**Comment by SebastianStehle** [comment]
I can confirm that when I change it to a normal class the type is indeed added to code generation and also the serializer.

But this does not explain why the error happens sporadically only.

**Comment by ReubenBond** [comment]
The sporadicness of it is that Orleans will also add types to the "known types" list on first use, and once it's there it will remain there and it will know how to read that type during deserialization. If a type isn't known, though, then it will fail to read it.

**Comment by SebastianStehle** [comment]
I see, can be closed then.
