### ISSUE TITLE
[Question]: Orleans Observables vs Streams

### ISSUE THREAD

**Issue by doctorcode-org** [dotnet/orleans#7042]
Hi:
Which observers and streams work best for the following scenario:
We have several consumers that receive messages from external services. Each consumer then processes the received message and then updates a grain state. The grain then notifies the clients of these changes. Grains notification fires and forget. my question is to notify clients with make grain as an observable or to use streams?

**Comment by ReubenBond** [comment]
I would default to observers for push-notification style updates like you're describing. I would also have those observers resubscribe to the grain periodically to give the grain a chance to resend any missed messages.

It also depends on how many clients are being notified and how many grains each one is observing. If the answer is "many" to those questions, then I would consider streams instead, likely backed by Azure Event Hubs. If in doubt, I would go with observers for their simplicity.

**Comment by doctorcode-org** [comment]
Hi @ReubenBond 
Thank you for your answer. 
I tried both methods and using streams worked much better. Periodic subscribing of grains in the expected scenario did not work well because some grains had no message to process at all and the use of observers allowed these grains to remain active in memory without the need for them.
I'm currently using Orleans to develop a trading system, and thank you to Orleans, and its developer community for this magical framework.

**Comment by ReubenBond** [comment]
Very glad to hear it, @doctorcode-org. I'll close this issue
