### ISSUE TITLE
Background service and Task Scheduler

### ISSUE THREAD

**Issue by MaximeCharles** [dotnet/orleans#7044]
Hello ! I'm new with Orleans so maybe I do this in wrong way.
I'm trying to use ILifecycleParticipant interface to create background service.

In my case, I need to process message receive by RabbitMq listener and do some action on my grain.

So I create a class with `ILifecycleParticipant<ISiloLifecycle>`  and register it in dependency injection. The class work perfecly. My messages are receive and I can call my grain from this class.
But I see that Orleans use a TaskScheduler and I ask myself if I'm not breaking the flow doing this way.

RabbitMq class
```csharp
public RabbitMqListener : ILifecycleParticipant<ISiloLifecycle> 
{
     private readonly IGrainFactory  _grainFactory;

     public RabbitMqListener(IGrainFactory grainFactory)
     {
         _grainFactory = grainFactory;
     }

     public void Participate(ISiloLifecycle lifecycle) 
     {
            lifecycle.Subscribe(OptionFormattingUtilities.Name<RabbitMqListener>("rabbitMqListener"), ServiceLifecycleStage.ApplicationServices,
                                Init, Close);
      }

     private async Task MessageReceive(string message) 
     {
         // From RabbitMq library callback
        var messageGrain =  _grainFactory.GetGrain<MyMessageGrain>(Guid.NewGuid());
        await messageGrain.DoSomething(message);
     }

     private Task Init(CancellationToken arg) 
     {
           // Init rabbitmq stuff
     }

     private Task Close(CancellationToken arg) 
     {
           // Close rabbitmq stuff
     }
}
```

I hope I made myself clear enough. Don't hesitate to ask for more information.

**Comment by ReubenBond** [comment]
@MaximeCharles you can use the .NET Generic Host's `BackgroundService` instead of ILifecycleParticipant. Register it after your `hostBuilder.UseOrleans(...)` call to ensure that the startup order is correct.

See the docs: https://docs.microsoft.com/en-us/dotnet/core/extensions/generic-host
and https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.backgroundservice?view=dotnet-plat-ext-5.0

**Comment by MaximeCharles** [comment]
Ok I will make a try and give you a feedback as soon as possible

**Comment by MaximeCharles** [comment]
I have a quick question, but the hosted service with RabbitMQ need to create a OrleansClient from configuration, right ?
Can I get it from the OrleansHostedService ?

**Comment by ReubenBond** [comment]
You can get an Orleans client by injecting `IClusterClient` or `IGrainFactory` into your `IHostedService` implementation

**Comment by ReubenBond** [comment]
Closing. I believe this has been resolved. If there are further questions, please open a new issue referencing this one.
