### ISSUE TITLE
Calling back into a grain which published event on stream causes deadlock

### ISSUE THREAD

**Issue by erikljung** [dotnet/orleans#7045]
This issue is based on a discussion from Gitter with @benjaminpetit 
I found a case where a specific call/event chain causes deadlocks in my application. Consider the following code (SMS stream provider):
```
GrainA
  SomeMethod()
    await this.GetStream<SomeEvent>(this.GetPrimaryKey())
      .OnNextAsync(new SomeEvent(this.GetPrimaryKey())

[ImplicitStreamSubscription..]
GrainB
   OnSomeEvent(SomeEvent ev)
     var grainC = GrainFactory.GetGrain<GrainC>()
     await grainC.DoSomething(ev.GrainAId)

GrainC
  DoSomething(GrainAId)
    var grainA = GrainFactory.GetGrain<GrainA>(GrainAId)
    await grainA.DoSomethingElse()
```

When `grainA.DoSomethingElse()` is executed the whole application hangs and I get the repeating log `Orleans.Runtime.InsideRuntimeClient: Received status update for pending request, Request: "NewPlacement Request....`

This code creates "kind of" a cycle: `A -> B -> C -> A`, but just to clarify: _Grain A_ publishes an event. _Grain B_ is a grain with `[ImplicitStreamSubscription]` which then will get activated to retrieve that event.

Verified solutions  that solves this problem:
- Set ` [AlwaysInterleave]` on `grainA.DoSomethingElse()`
- Use `InvokeOneWay(..)` or `[OneWay]`, this does however not give any response
- Setting `SimpleMessageStreamProviderOptions.FireAndForgetDelivery = true`
- Calling _Grain A_ directly from _Grain B_ (without entering _Grain C_)
- Publishing the event outside _Grain A_ after `SomeMethod()` is executed

**Comment by benjaminpetit** [comment]
Orleans support for reentrancy within a call chain is limited: we support only `A -> B -> C`.

Since here you are using SMS as the stream provider, you are effectively doing `A -> B -> C -> A`, as you mentioned. If you switch to another stream provider (even the in memory one), you will break this circular dependency.

**Comment by randrewy** [comment]
Omg, documentation is terribly misleading about this! https://dotnet.github.io/orleans/docs/grains/reentrancy.html
There is no way to get that info, instead it seems like a `Call chain` could be of any length. I see this as a huge problem coz it may lead to a poor design decisions based on wrong prior information.

Will Orleans support arbitrary call chan lenght reentrancy in fututre?
Why this restriction exists?

**Comment by benjaminpetit** [comment]
> Omg, documentation is terribly misleading about this!

I agree, document should be better. We are open to contribution, even on the doc :)

> Will Orleans support arbitrary call chan lenght reentrancy in fututre?

If we find a good way to implement it, for sure. It might be easier to implement in 4.x since we don't care about on the wire backward compatibility.

> Why this restriction exists?

Previous implementation attempt failed. I remember we merged a PR for this a while ago, but we had to revert it because it was breaking backward compatibility.

**Comment by randrewy** [comment]
Thanks for your reply!
Can you please link previous PR I'd like to dig into it a little

> We are open to contribution, even on the doc :)
Is there any CoC regarding docs?

**Comment by randrewy** [comment]
Btw, a lot of cool features seems to be in development at the moment, can I find Orleans roadmap or smth similar anywhere?

**Comment by benjaminpetit** [comment]
> Can you please link previous PR I'd like to dig into it a little

https://github.com/dotnet/orleans/pull/5145

> Is there any CoC regarding docs?

Yes there is: https://github.com/dotnet/orleans-docs/blob/main/CODE-OF-CONDUCT.md

> Btw, a lot of cool features seems to be in development at the moment, can I find Orleans roadmap or smth similar anywhere?

Not yet, but that's something we should do in the future.

**Comment by erikljung** [comment]
Am I understanding this correct, the **length** of the call chain is the issue, and this is why `A -> B -> A`  works?

**Comment by benjaminpetit** [comment]
Yes
