### ISSUE TITLE
Orleans Streams throws: Operation is not valid due to the current state of the object. in .NET5 host

### ISSUE THREAD

**Issue by rjygraham** [dotnet/orleans#7057]
The current Microsoft.Orleans.OrleansServiceBus package has a dependency on an older version of Microsoft.Azure.EventHubs which is incompatible with .NET5.

When running the SiloHost, you will encounter an exception similar to:
````
System.InvalidOperationException
  HResult=0x80131509
  Message=Operation is not valid due to the current state of the object.
  Source=Microsoft.Azure.Amqp
  StackTrace:
   at Microsoft.Azure.Amqp.Transport.TransportStream.Flush()
````

This has been detailed in another GH issue:
https://github.com/Azure/azure-amqp/issues/165

Explicitly adding the latest version (currently 4.3.1) of Microsoft.Azure.EventHubs package resolves this exception.

**Comment by ReubenBond** [comment]
Fixed by #7255. Thanks for reporting & investigating, @rjygraham! I expect 3.5.0 to be released within the next day.
