### ISSUE TITLE
Method to cleanly cordon/drain/evict grains from a silo?

### ISSUE THREAD

**Issue by highlyunavailable** [dotnet/orleans#7058]
Is there a way to cleanly migrate off of a silo? The reason I ask is because I am doing deployments with Helm to a set of Orleans silos on Kubernetes, but simply asking the silos to shutdown normally causes all sorts of havoc like clients asking for Non-Existent Activations. I'm waiting for a clean shutdown and all that, but is there a way to tell Orelans explicitly "Get all running grains off of this silo and make sure no grains can activate there in the future, because I'm going to be stopping it soon"? Especially reminders and the like - it seems like there's no good way to drain a silo before stopping it.

**Comment by benjaminpetit** [comment]
While there is room for improvement, and it's not perfect yet, the existing shutdown sequence should handle your case properly.

When a silo will start its shutdown sequence, it will notify the other silo of that: other silos will not try to place new activations on the silo that is stopping, and the silo stopping will try to deactivate cleanly all its running activations, before forwarding any pending requests.

Are you 100% sure that in your case you have a clean shutdown?

Multiple silos shutting down at the same time can make things challenging for the distributed directory. If you see a lot of errors related to the directory during shutdown, you could look at using an external directory, like the [redis based one](https://www.nuget.org/packages/Microsoft.Orleans.GrainDirectory.Redis).

**Comment by highlyunavailable** [comment]
It is indeed because all the old silos are stopping within a very short time of each other so the distributed directory loses a lot of data. It really is a clean shutdown. That’s why I was asking if I could cordon silos.

**Comment by benjaminpetit** [comment]
Clean shutdown already drain running activations, if you leave enough time for them to finish this operation. Could you post some logs to see the errors you are encountering?

**Comment by highlyunavailable** [comment]
It's mostly a massive spam of these kinds of messages:

```
info: Orleans.Runtime.Dispatcher[100147]
      => PlayerGrain title_player_account!f0ada6d35228f197 OnConnect
      Intermediate NonExistentActivation for message Request S172.31.19.244:11111:356246833*grn/Showdown.Backend.Grains.PlayerGrain/0+title_player_account!f0ada6d35228f197@75ea90a8->S172.31.19.244:11111:356246833*grn/Showdown.Backend.Grains.DataCacheGrain/0+S172.31.19.244:11111:356246833@e44502a4 InvokeMethodRequest Showdown.Backend.Interfaces.IDataCache:GetQueueOptions #78372, with Exception Orleans.Runtime.Catalog+NonExistentActivationException: Non-existent activation: [ActivationAddress: S172.31.19.244:11111:356246833*grn/Showdown.Backend.Grains.DataCacheGrain/0+S172.31.19.244:11111:356246833@e44502a4, Full GrainId: [GrainId: *grn/Showdown.Backend.Grains.DataCacheGrain/0+S172.31.19.244:11111:356246833-0x1DC3FA9E, IdCategory: KeyExtGrain, BaseTypeCode: 2145202125 (x7FDD2FCD), PrimaryKey: 0 (x0), UniformHashCode: 499382942 (0x1DC3FA9E), KeyExtension: S172.31.19.244:11111:356246833], Full ActivationId: @46027c16f041121b8fc2337ee44502a40000000000000000], grain type: Showdown.Backend.Grains.DataCacheGrain.
         at Orleans.Runtime.Catalog.GetOrCreateActivation(ActivationAddress address, Boolean newPlacement, String grainType, String genericArguments, Dictionary`2 requestContextData, Task& activatedPromise)
         at Orleans.Runtime.Dispatcher.ReceiveMessage(Message message)
```

**Comment by benjaminpetit** [comment]
> It's mostly a massive spam of these kinds of messages

This log line is fine (that's why it is only in the `info` category) and expected. The message should be forwarded to the correct activation shortly after, without any intervention from the user.

> The catalog issues can also cause requests to time out/be dropped and stream messages to not get to their targets, which is also problematic

It is possible to lose some messages (in our testing we only get 100% availability during rolling upgrade when using the Redis directory), but I am not sure to understand the issue with streaming. You should not lose stream messages.

> I guess what I'm trying to do is mostly cleanly remove the "old" servers from the distributed grain catalog so they can go away safely.

They do! But you will always have a race condition when a silo start to shutdown and other silos are trying to send messages to it.

**Comment by highlyunavailable** [comment]
I'm using SMS streaming, so it's effectively just calls directly to grains via that method, hence stream loss.

Anyway, it sounds like I just need to move some stuff to an external grain directory or maybe implement some "post-stop" hook that wait for a minute or so after each silo pod shuts down for the grain directory to stabilize before moving onto the next. It's not like I have a lot of silos (usually 2) so losing 1 means losing 1/3rd (2 + the new 1 being deployed) of the grain directory.

I really wish there was a better way to manually notify servers so they stopped being part of the distributed directory prior to _immediately_ stopping but it doesn't sound like that's the case.

**Comment by highlyunavailable** [comment]
Just to follow up on this for future web-searchers:

The best thing I found short of moving off of the distributed grain directory was to set up my rolling update config to be less aggressive:

My deployment is now:
```
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
```

It takes a bit longer to roll out, but I'm dropping way fewer things on the floor now.
