### ISSUE TITLE
Stream Length

### ISSUE THREAD

**Issue by turowicz** [dotnet/orleans#7063]
Is it possible to get the current stream length into prometheus? I am using SMS and I need to make sure all streams are cleared before I can restart / deploy new version of my service.

**Comment by turowicz** [comment]
cc @ReubenBond

**Comment by ReubenBond** [comment]
I don't think so, @turowicz. SMS streams do not have buffering, they involve direct grain calls.

cc @benjaminpetit

**Comment by nkosi23** [comment]
What is the right way to gracefully shutdown/restart Orleans? (without losing messages and interrupting current operations)

**Comment by benjaminpetit** [comment]
You should:

- wait for `silo.StopAsync()` to finish
- do not use memory based provider (Memory Streams or Memory Grain Storage provider)

SMS should be fine since it's basically regular grain calls

**Comment by ReubenBond** [comment]
Will close for now, since there is a resolution.

**Comment by turowicz** [comment]
@ReubenBond @benjaminpetit What happens in Orleans when I am running SMS in a fire and forget mode, and the producer Grain is 100x faster than the consumer Grain? Is there an in-memory queue being filled up? Is the data lost when the some of the silos crashe? 

If that's the case then I would like to somehow count the amount of messages that are currently in those in-memory queues.

**Comment by turowicz** [comment]
Also, will the messages get rejected if the consumer Grain is busy?

**Comment by benjaminpetit** [comment]
SMS is basically regular grain calls. So calls will be enqueued on the consumer request queue.

There is some warning/error limits that you can configure for request queue length in `SiloMessagingOptions`. Check `MaxEnqueuedRequestsSoftLimit` and `MaxEnqueuedRequestsHardLimit`

**Comment by turowicz** [comment]
@benjaminpetit thanks for the answer. What are the defaults? Infinity?

Another one:

What about the following logs (fire and forget SMS):

```
"Response did not arrive on time in 00:00:30 for message: Request S10.1.103.229:11111:369235956*grn/xxx/3bc442d7-49c8-43d5-8782-303a5c470ad8@fa7a679f->S10.1.103.229:11111:369235956*grn/xxx/b0322b4b-a4e2-4ef2-ac23-ea3cfbdb3fa5@88f7c39e InvokeMethodRequest Orleans.Streams.IStreamConsumerExtension:DeliverImmutable #38246. Target History is: <S10.1.103.229:11111:369235956:*grn/xxx/b0322b4b-a4e2-4ef2-ac23-ea3cfbdb3fa5:@88f7c39e>." About to break its promise.
```

Is that message eventually dequeued if the consumer gets around to it or is it dropped on timeout?

**Comment by turowicz** [comment]
@benjaminpetit I don't have any "Dropping expired message" in the logs for the last 7 days so I assume none are dropped.

**Comment by turowicz** [comment]
@benjaminpetit thanks a lot for the answers!
