### ISSUE TITLE
Adding new properties in already persisted grain model gives error

### ISSUE THREAD

**Issue by saurabhtyagi00** [dotnet/orleans#7064]
I am persisting a grain with the help of ADO persistent. It is working fine.
Now i add some new properties in the Grain Model and try to run it again, but it is giving me some casting error -

Error reading grain state: ServiceId=serviceid ProviderName=modelStore GrainType=Flow.Implementations.Trigger.ScheduledTriggerGrain,Flow.Implementations.scheduleState GrainId=0#a70bd631-b101-4413-907f-3fae19a47e3d ETag= Exception=Unable to cast object of type 'System.Boolean' to type 'System.Int32'..
System.InvalidCastException: Unable to cast object of type 'System.Boolean' to type 'System.Int32'.

I debug it further and found **Flow.Abstraction.orleans.g.cs** file with method **public global::System.Object Deserializer(global::System.Type expected, global::Orleans.Serialization.IDeserializationContext context)** causing this error. 

Actually all the properties are stored in ascending order in persistence db and they retrieved in the same order. if we add new property it will be get/set according to the order. it is causing me error in previously persisted data.

How can i check and clear this type of previous persisted data or any other way

**Comment by JorgeCandeias** [comment]
Are you relying on the default serializer for this? The default serializer is not version tolerant, so serialization will break when the model definition changes between writing and reading. This means the default serializer, although it works with persistence, is not reliable for that purpose. With the ado.net persistence provider you can address this in one of two ways.

* Configure the ado.net persistence provider to use the json serializer (the json format is version tolerant).
* Leave the ado.net persistence provider as-is and configure a version-tolerant binary serializer onto the solution, e.g. protobuf-net, then decorate your models as needed.

The first option will make the models easy for a human to read on the database table, but the payloads can become very large.

The second option will keep performance up, and so long as you follow protobuf tagging and type conventions, you won't see anything break as you change the models between releases.

**Comment by saurabhtyagi00** [comment]
Thanks for the reply, I will look into it.

**Comment by saurabhtyagi00** [comment]
I found out this property did the trick

                        .AddAdoNetGrainStorage("storename", options =>
                           {
                               //other properties
                               options.UseJsonFormat = true;
                           });

**Comment by JorgeCandeias** [comment]
Yes, that's the first option. Keep in mind that if you use that:

* It applies wholesale to all persistence models that use that store.
* You'll have to follow json version tolerance conventions now, e.g. don't rename model properties ever.
* Json can create large payloads and slow down saving/loading a little bit as compared to binary formats - but at least it's easier to troubleshoot when things go wrong.

Note that Orleans does not stop you from saving and loading data directly from some data store. That's the third option that I didn't mention. The built-in persistence feature works great for simple things and quick development, but on a complex project, it tends to be better overall to liaise directly with the data store.

**Comment by saurabhtyagi00** [comment]
@JorgeCandeias  Thanks for your help and advise. I will test and try other options later. 
Closing this as it solves my problem
