### ISSUE TITLE
[Help Need]: Orleans Multi Cluster Deployments

### ISSUE THREAD

**Issue by doctorcode-org** [dotnet/orleans#7067]
I am looking at using Orleans as a mechanism to help fix concurrency concerns. I noticed in the later version of Orleans has removed the MultiCluster functionality; however, it's still on their docs.

https://github.com/dotnet/orleans/releases/tag/v3.2.0

What is the recommended approach to hosting two clusters and allowing the Orleans clusters to communicate?

My application will need to ensure that a guid Grain on cluster A is not getting acted upon at the same time as a Grain in cluster B with the same guid.

**Comment by benjaminpetit** [comment]
For most cases, it's better to keep both clusters isolated, and communicate via another front door.
