### ISSUE TITLE
ManagementGrain returns cached membership table silo status

### ISSUE THREAD

**Issue by awshrubsall** [dotnet/orleans#7071]
I am looking at the Health Check Sample found here: https://github.com/dotnet/orleans/blob/main/Samples/2.3/HealthCheckSample/src/Silo/ClusterHealthCheck.cs trying to implement a health service on Orleans v3.4.1.

I have noticed that [GetHosts](https://github.com/dotnet/orleans/blob/10af0f4af588cd4aa45cb3e250dfbffa389d59c7/src/Orleans.Runtime/Core/ManagementGrain.cs#L52) on the ManagementGrain never changes result after startup, and I believe it is due to the cache in the SiloStatusOracle.
https://github.com/dotnet/orleans/blob/10af0f4af588cd4aa45cb3e250dfbffa389d59c7/src/Orleans.Runtime/MembershipService/SiloStatusOracle.cs#L49-L54
If I create a situation where a silo in the membership table is gracefully terminated, it marks its Status "Dead", and I start a new silo process, the ClusterHealthCheck here reports a degraded service with "1 silo(s) unavailable". I can see a debug log after membershipTableManager.Refresh() is called:
```
[15:50:08 DBG] ProcessTableUpdate (called from Refresh) membership table 2 silos, 1 are Active, 1 are Dead, Version=<16, W/"datetime'2021-05-07T03%3A49%3A29.2200842Z'">. All silos: [SiloAddress=S10.8.226.129:11111:358055395 SiloName=Silo_7863a Status=Active, SiloAddress=S10.8.226.129:11111:358055107 SiloName=Silo_1882c Status=Dead]
```
Later when this dead silo is cleared out of the membership table, I can see another debug log from the MembershipTableManager
```
[15:50:42 DBG] ProcessTableUpdate (called from Refresh) membership table 1 silos, 1 are Active, 0 are Dead, Version=<17, W/"datetime'2021-05-07T03%3A49%3A59.7370000Z'">. All silos: [SiloAddress=S10.8.226.129:11111:358055395 SiloName=Silo_7863a Status=Active]
```
Yet ManagementGrain.GetHosts() still has the dead silo in its list and so the ClusterHealthCheck never progresses from Degraded to Healthy.

I am using Azure Table Storage for my cluster management, if that makes a difference, I haven't tried this on any other implementation.

**Comment by ReubenBond** [comment]
Looks like an issue with the logic in that sample: it's normal to have "Dead" silos being reported from those calls.

I also recommend that health checks are as simple as possible if you are using them for performing any automated action, such as for Kubernetes probes. In the Kubernetes case, I'd likely go with a simple ping: that helps with the case where a process becomes a total zombie (eg, execution engine deadlock, massive thread pool starvation, or some other catastrophe), and leaves the Orleans cluster responsible for terminating unhealthy silos.

**Comment by awshrubsall** [comment]
I am indeed intending to use this for a Kubernetes readiness probe in our rolling update deployment strategy. I only particularly care that the silo has joined the cluster so I know it is safe to stop previous versions. It looks like I can do without the ClusterHealthCheck sample in my scenario.

**Comment by ReubenBond** [comment]
> It looks like I can do without the ClusterHealthCheck sample in my scenario.

Most certainly. We have also removed that sample: I don't consider it especially applicable to users. There is a new Kubernetes sample [here (https://github.com/dotnet/orleans/tree/main/samples/Voting)](https://github.com/dotnet/orleans/tree/main/samples/Voting) which does not use health checks.

Will close this since it seems that you have a resolution.
