### ISSUE TITLE
[Question]: Difference between MemoryStreams and SimpleMessageStreamProvider

### ISSUE THREAD

**Issue by doctorcode-org** [dotnet/orleans#7073]
Hi;
What is the difference between SimpleMessageStreamProvider and MemoryStreams? 
The guide document only mentions SMS and there is no explanation for MemoryStreams.
Where can I study the difference between them?

**Comment by ReubenBond** [comment]
Hi @doctorcode-org, the difference is roughly this:

SMS (Simple Message Stream Provider) uses direct grain messaging from the producers of a message to all consumers.
MemoryStream uses an in-memory buffer to decouple producers and consumers.

Both should be considered *best efforts* as neither uses persistent storage to store messages.
I hope that helps

**Comment by doctorcode-org** [comment]
Hi @ReubenBond 
Thank you so much. Your explanation was excellent and helped me a lot.
