### ISSUE TITLE
Support C# records in grain method parameters and return value

### ISSUE THREAD

**Issue by VincentH-Net** [dotnet/orleans#7076]
As discussed with @ReubenBond [here](https://gitter.im/dotnet/orleans?at=609a800e72823a6a046632f6)
Adding support for C# records in Orleans method parameters would allow this code
```csharp
[Immutable]
public class CallParty
{
    public string Name { get; init; }
    public string Address { get; init; }
    public string UserId  { get; init; }
}
```
To become this
```csharp
[Immutable]
public record CallParty(string Name, string Address, string UserId);
```
In addition, records eliminate writing code for value equality, hash code - many loc saved.

The support should enable to use the `record` `CallParty` and immutable collections of that, like `ImmutableArray<CallParty>`, in grain method signatures.

Eliminating the need to add the `[Immutable]` attribute to records would be a nice to have. Roslyn code generators should allow access to the actual source text, so even if the Roslyn model does not distinguish records, it should be possible to determine that from the source code text.

The combination of `[Immutable]` and `record` would be an reasonably safe performance optimization, provided any contained collections are immutable, e.g. `ImmutableArray<T>`. For calls within the same silo no deep copy will be made, while the state of the calling actor will also be reasonably well protected from unintentional external modification by the (adequate) immutability of `record` and `ImmutableArray<T>` (or equivalent).

Possible related issues: #6822, #7033

**Comment by andrejpk** [comment]
Agreed.. also 'with' C# syntax with immutable types is a huge help... no way that I can tell to use that with classes, even Immutable ones.

**Comment by oising** [comment]
https://github.com/dotnet/orleans/pull/7108
