### ISSUE TITLE
AddDynamoDBGrainStorage - not working as expected

### ISSUE THREAD

**Issue by PiotrJustyna** [dotnet/orleans#7077]
I'm having a difficult time getting `AddDynamoDBGrainStorage` working the way it is documented:

https://dotnet.github.io/orleans/docs/grains/grain_persistence/dynamodb_storage.html

Here is the code which specifically does not work for me in some scenarios:

```csharp
siloBuilder.AddDynamoDBGrainStorage(
    name: "helloWorldStore",
    configureOptions: options =>
    {
        options.UseJson = true;
        options.AccessKey = accessKey;
        options.SecretKey = secretKey;
        options.Service = "us-west-2";
    });
```

What is not working? There are two scenarios which result in exceptions:

| - | `AWS_SECRET_ACCESS_KEY` and `AWS_ACCESS_KEY_ID` environment variables present | `AWS_SECRET_ACCESS_KEY` and `AWS_ACCESS_KEY_ID` environment variables missing |
| --- | --- | ---|
| correct values of `options.AccessKey` and `options.SecretKey` provided | This scenario is not relevant to me and I didn't check what's happening in this case. | `The security token included in the request is invalid.` More on this error below. |
| `options.AccessKey` and `options.SecretKey` not provided | dynamodb connection works | `Unable to get IAM security credentials from EC2 Instance Metadata Service.` I would expect `DynamoDBStorage` to refer to my `~/.aws/credentials` for the expected values (which are present there by the way). |

Maybe I'm missing something, but I'm not sure this is the way the `DynamoDBStorage` should work. For reference, at the time of writing this, the `DynamoDBStorage` looks as follows:

```csharp
private void CreateClient()
{
    if (this.service.StartsWith("http://", StringComparison.OrdinalIgnoreCase) ||
        this.service.StartsWith("https://", StringComparison.OrdinalIgnoreCase))
    {
        // Local DynamoDB instance (for testing)
        var credentials = new BasicAWSCredentials("dummy", "dummyKey");
        this.ddbClient = new AmazonDynamoDBClient(credentials, new AmazonDynamoDBConfig { ServiceURL = this.service });
    }
    else if (!string.IsNullOrEmpty(this.accessKey) && !string.IsNullOrEmpty(this.secretKey))
    {
        // AWS DynamoDB instance (auth via explicit credentials)
        var credentials = new BasicAWSCredentials(this.accessKey, this.secretKey);
        this.ddbClient = new AmazonDynamoDBClient(credentials, new AmazonDynamoDBConfig {RegionEndpoint = AWSUtils.GetRegionEndpoint(this.service)});
    }
    else
    {
        // AWS DynamoDB instance (implicit auth - EC2 IAM Roles etc)
        this.ddbClient = new AmazonDynamoDBClient(new AmazonDynamoDBConfig {RegionEndpoint = AWSUtils.GetRegionEndpoint(this.service)});
    }
}
```

1. Condition 1 is fine for local use.

2. Condition 2 (`!string.IsNullOrEmpty(this.accessKey) && !string.IsNullOrEmpty(this.secretKey)`) results in the code creating an instance of `BasicAWSCredentials` which behind the scenes results in:

  ```csharp
  public BasicAWSCredentials(string accessKey, string secretKey)
  {
    if (string.IsNullOrEmpty(accessKey))
      return;
    this._credentials = new ImmutableCredentials(accessKey, secretKey, (string) null);
  }
  ```

  Where `(string) null` is the token, which to me explains why we're getting the `The security token included in the request is invalid.` exception (correct me if I'm wrong!). Shouldn't we be passing in the token as well?

3. Condition 3 is fine for production use.

4. What seems to be missing is `~/.aws/credentials` file fallback option. Once AWS-authenticated, user credentials are stored there by default.

Are these conditions there by design? Do we want to ignore the token and the default credentials file?

**Comment by PiotrJustyna** [comment]
Update:

My profile name in `~/.aws/credentials` is `sts`, so the file looks something like this:

```
[sts]
aws_access_key_id = ***
aws_secret_access_key = ***
aws_security_token = ***
aws_session_expiration = ***
aws_session_token = ***
```

Changing `sts` to `default` does the trick and `DynamoDBStorage` falls back to the credentials stored there, but still one question remains:

* do we want to pass in the token to `DynamoDBStorage` when `options.AccessKey` and `options.SecretKey are provided?

One new question also emerges:

* in case of many profile names, should we not give the callers an option to specify the profile name to chose in the `~/.aws/credentials` file?

**Comment by jsteinich** [comment]
> * do we want to pass in the token to `DynamoDBStorage` when `options.AccessKey` and `options.SecretKey are provided?

Tokens aren't required for non-session based credentials.


> * in case of many profile names, should we not give the callers an option to specify the profile name to chose in the `~/.aws/credentials` file?

The authentication has definitely been kept simple. I believe this was intentional to make it easy to use for most cases.

There was some discussion about switching to using more of a c[onfiguration injection approach / injecting the clients](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-config-netcore.html), but I'm having trouble finding that issue. That would allow for more advanced authentication options without reinventing things. There was some concern about backwards compatibility, but otherwise, it's just a matter of someone from the community submit a PR.

**Comment by PiotrJustyna** [comment]
@jsteinich Please check the proposed adjustments which extend the current configuration/credentials model. Long term, I think I would second the idea to streamline the approach to configuration, but for now I could really use those fixes.

**Comment by PiotrJustyna** [comment]
All my changes are now accepted, so I'm happy to close the issue. Thank you all.
