### ISSUE TITLE
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.DateTime'

### ISSUE THREAD

**Issue by bruno-goncalves-cko** [dotnet/orleans#7087]
Hi,

While doing a rolling deployment of my cluster, I experienced a series of exceptions such as the one below, while invoking a grain's method.

```
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.DateTime'.
   at Orleans.Runtime.OutgoingCallInvoker.Invoke()
   at Orleans.Runtime.OutgoingCallInvoker.Invoke()
   at Orleans.Runtime.GrainReferenceRuntime.InvokeWithFilters(GrainReference reference, InvokeMethodRequest request, InvokeMethodOptions options)
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
   at 
```

It seems to have been a transient error which only happened during deployment of the new instance. We're using MS Orleans 3.4.1.

Is this a case for concern? Not sure exactly why nor where this exception is coming from.

**Comment by benjaminpetit** [comment]
Did you changed some grain interface signatures?

**Comment by bruno-goncalves-cko** [comment]
We did add a new property to a class which is passed to the grain's method, but we did not change the signature per se.

The method signature was something like this and did not change. We just added a new string property on the Request class.

`Task<Response> DoSomethingAsync(Request request);`

Does that count as changing the interface siganture?

**Comment by bruno-goncalves-cko** [comment]
Also worth noticing that we added a new property of type `string` to the request class and it was declared just after an existing property of type `DateTime`. How are requests being routed/serialized between silos? 

Would a v1.0 Silo routing a v1.0 request to a v1.1 Silo could explain this? Are silos (de)serializing requests using a binary serializer? I wouldn't expect this to happen with a json serialization though.

**Comment by benjaminpetit** [comment]
> Does that count as changing the interface siganture?

Yes!

By default, for wire transport, Orleans will use its own serializer that doesn't support versioning.

What you are describing seems possible to me.

**Comment by bruno-goncalves-cko** [comment]
Thanks for the confirmation. I think that explains the exception.
