### ISSUE TITLE
Orleans website on github pages is working incorrect

### ISSUE THREAD

**Issue by LeftTwixWand** [dotnet/orleans#7089]
It's impossisble to navigato from the main menu page in the orleans website: [https://dotnet.github.io/orleans/](https://dotnet.github.io/orleans/)

![image](https://user-images.githubusercontent.com/50652041/119149703-6b97db00-ba56-11eb-93d4-78d7cb26b71e.png)

**Comment by LeftTwixWand** [comment]
Now it's working

**Comment by ReubenBond** [comment]
Thanks for reporting, @LeftTwixWand - we since rectified the issue
