### ISSUE TITLE
OrleansBrokenTransactionLockException when read and write in the same grain method

### ISSUE THREAD

**Issue by luyangdev** [dotnet/orleans#7093]
Hello, I got OrleansBrokenTransactionLockException when:
- Silo: PerformRead and PerformUpdate in the same grain method.
- Client: make multiple calls of the grain method above at the same time

I've marked the grain class [Reentrant] as discussed in  #5644  

Reproduce the issue: [github repo](https://github.com/luyangdev/orleans-broken-transaction-lock-exception-sample) 

Exception:
```
Unhandled exception. Orleans.Transactions.OrleansBrokenTransactionLockException: 
Transaction 238e27ee-1cf1-4e3f-9a12-c7da6045541f aborted because a broken lock was detected, when trying to re-enter lock
at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
```

Silo grain method:
```CSharp
async Task<GrainState> ITaskGrain.Execute()
{
           var state = await _state.PerformRead(_ => _);
           state.Count++;
           await _state.PerformUpdate(e => e.Count = state.Count);
           return state;
}
```

Client:
```CSharp
var tasks = Enumerable.Range(1, 100).Select(async _ => await _client.GetGrain<ITaskGrain>("key").Execute()).ToList();
var results = await Task.WhenAll(tasks)
```

**Comment by jsteinich** [comment]
Does lowering the number of tasks help?

I'm wondering if the memory storage is causing a bunch of contention since it just uses a simple non-reentrant grain.

**Comment by luyangdev** [comment]
When reducing task number to 2, the problem seems gone, but when more than 2, the problem remains. 
I still get the same exception when using SqlServer storage instead.

The updated code for using sqlserver has been pushed to [github repo](https://github.com/luyangdev/orleans-broken-transaction-lock-exception-sample).

**Comment by jsteinich** [comment]
That particular error message is coming from https://github.com/dotnet/orleans/blob/efa8adb9530ae9233662a793c7675a9d2552b289/src/Orleans.Transactions/State/ReaderWriterLock.cs#L110.

I believe there is an error with this check. While the reads/writes could have been incremented by the current transaction, they can also have been incremented by a different transaction (what I believe is happening in this case). I believe concurrent read transactions are generally supported.

That said, any fix there would likely just result in a different exception being thrown a bit later in the process as the 2nd transaction to attempt a write would fail since the 1st transaction is still pending.

**Comment by luyangdev** [comment]
Thank you for reply, Jon. It sounds like an error to be fixed in Orleans. 
To bypass this issue in my application, I am thinking about doing either PerformRead or PerformUpdate but not both in a single grain method. Or is there any other way I can do?

**Comment by jsteinich** [comment]
> It sounds like an error to be fixed in Orleans.

Yes and no. I do believe there to be an error; however, what you are doing is still likely to hit a different exception which I believe to be simply a limitation of the transaction system. I don't imagine they would change that limitation, but it could be attempted.

> To bypass this issue in my application, I am thinking about doing either PerformRead or PerformUpdate but not both in a single grain method. Or is there any other way I can do?

Just doing one of those operations in a transaction should get around this issue. If you move to a different method but call both, then this will likely still occur (though you would be reducing the chance of it happening).

**Comment by luyangdev** [comment]
Thanks. I will try to do one of. It would be very helpful to add the limitation to the document.
