### ISSUE TITLE
How to use postgres with SSL enabled to become AdoNetClustering

### ISSUE THREAD

**Issue by coocms** [dotnet/orleans#7095]
Hi guys,
Our company recently required all interactions with the database to use two-way authentication.
Does Orleans provide relevant interfaces to configure database certificates?
Or is there any way to get the DBConnection inside Orleans? I have cleared how to implement mutual authentication after obtaining the DBconnection object.

This is the error message：Exception while performing SSL handshake

**Comment by veikkoeeva** [comment]
Orleans does not currently provide access to connection objections.

To consigure TLS you can use connection string, I believe: https://www.npgsql.org/doc/connection-string-parameters.html.

**Comment by ReubenBond** [comment]
I believe @veikkoeeva answered your question, @coocms, so I will close this issue. Please feel free to reopen it if there are remaining questions.
