### ISSUE TITLE
Orleans CodeGenerator (MSBuilld) fails when previous code has a static local function

### ISSUE THREAD

**Issue by icanhasjonas** [dotnet/orleans#7096]
Given this code

```cs

namespace SomeNamespace.Grains {
	public class A {
		private IEventFactory _eventFactory;

		public Task Hello() => _eventFactory
			.BeginUpdate("hello")
			.Scope(() => {
				ValidateReferenceIntegrity(null, Guid.Empty, null);

				static void ValidateReferenceIntegrity(string existingGrain, Guid givenValue, string parameterName)
				{
					if (existingGrain is not null && existingGrain == null) {
						throw new Exception(parameterName);
					}
				}

				return Task.CompletedTask;
			})
			.ProcessAsync();
	}

	public class AState { }
}
```

Expected:
  The generated code should register the `AState` object as a known type on the namespace `SomeNamespace.Grains` but it registers it as `<global namespace>.AState`

If you remove the `static void ValidateReferenceIntegrity` (just comment it out) it will generate the correct code again. It is almost like the code syntax parser (Roslyn?) is using an older syntax version and failing to parse `AState` as part of `SomeNamespace.Grains` namespace.

This obviously breaks code that tries to deserialize `AState` from persisted storage etc.

PS. Moving `AState` to the top of the file also fixes the issue, again reinforcing the idea that this is a roslyn syntax issue (possibly an older roslyn reference)

**Comment by ReubenBond** [comment]
I believe this will have been fixed in #7108/#7119, which updated the compiler version which the codegen references.
