### ISSUE TITLE
Question: Any news about running Orleans on Azure App Service

### ISSUE THREAD

**Issue by christiansparre** [dotnet/orleans#7098]
Hi, in the gitter chat and in the [On .NET Deep dive video](https://youtu.be/R0ODfwU6MzQ?t=723) (timestamped to the mention) back in march @ReubenBond mentioned that it should now be possible to run Orleans on Azure App Service (something that was not possible before) and that it was being used by teams internal at Microsoft.

I have not been able to find more information about this (I might have missed more gitter conversations about it), but it is a very interesting notion to our team because jumping into the whole Kubernetes/Service fabric world might be too big of a shift in technology etc.

We have use cases where Orleans might be an absolutely fantastic fit, but putting Kubernetes or Service Fabric on top might not make it feasible currently.

I'm wondering if I might have misunderstood or that information about it is just not ready to be shared yet?

**Comment by ReubenBond** [comment]
Hi @christiansparre, I misspoke: the teams running Orleans on App Service today are using an internal, unofficial facility for that. I'll try to update this issue when something is broadly available.

**Comment by christiansparre** [comment]
Thanks for the clarification @ReubenBond we'll look into other options for the time being :)
