### ISSUE TITLE
Documentation: error in code example

### ISSUE THREAD

**Issue by cjenp** [dotnet/orleans#7102]
Hi,

there is a small bug in the Clients documentation:
[https://dotnet.github.io/orleans/docs/host/client.html](https://dotnet.github.io/orleans/docs/host/client.html)

If you look at the code example for changing GatewayListRefreshPeriod, currently it is 
`.Configure<GatewayOptions>(opts => GatewayListRefreshPeriod = TimeSpan.FromMinutes(10))`
should be
`.Configure<GatewayOptions>(opts => opts.GatewayListRefreshPeriod = TimeSpan.FromMinutes(10))`

**Comment by 107295472** [comment]
It is ok

**Comment by ReubenBond** [comment]
Fixed in dotnet/orleans-docs#48
