### ISSUE TITLE
Consul Clustering + Kubernetes StatefulSet = bloating membership table?

### ISSUE THREAD

**Issue by wangjia184** [dotnet/orleans#7105]
```xml
    <PackageReference Include="Microsoft.Orleans.Hosting.Kubernetes" Version="3.4.3" />
    <PackageReference Include="Microsoft.Orleans.OrleansConsulUtils" Version="3.4.3" />
    <PackageReference Include="Microsoft.Orleans.Server" Version="3.4.3" />
```

```csharp
siloBuilder
     .UseConsulClustering(opt =>
     {
         opt.Address = new Uri(AppConfig.Orleans.ConsulUrl);
         opt.AclClientToken = AppConfig.Orleans.AclClientToken;
     })
     .UseKubernetesHosting();
```

```yml
          - name: ORLEANS_SERVICE_ID #Required by Orleans 
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['orleans/serviceId']
          - name: ORLEANS_CLUSTER_ID #Required by Orleans 
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['orleans/clusterId']
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['statefulset.kubernetes.io/pod-name']
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
```

A StatefulSet with 3 replicas, empty consul.  After create the StatefulSet, PODs crashes with following exception.
```
System.AggregateException: One or more errors occurred. (Failed to get ping responses from 1 of 1 active silos. Newly joining silos validate connectivity with all active silos that have recently updated their 'I Am Alive' value before joining the cluster. Successfully contacted: []. Failed to get response from: [S10.18.123.218:11111:361110184])
 ---> Orleans.Runtime.MembershipService.OrleansClusterConnectivityCheckFailedException: Failed to get ping responses from 1 of 1 active silos. Newly joining silos validate connectivity with all active silos that have recently updated their 'I Am Alive' value before joining the cluster. Successfully contacted: []. Failed to get response from: [S10.18.123.218:11111:361110184]
   at Orleans.Runtime.MembershipService.MembershipAgent.ValidateInitialConnectivity()
   at Orleans.Runtime.MembershipService.MembershipAgent.BecomeActive()
   at Orleans.Runtime.MembershipService.MembershipAgent.<>c__DisplayClass26_0.<<Orleans-ILifecycleParticipant<Orleans-Runtime-ISiloLifecycle>-Participate>g__OnBecomeActiveStart|6>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct)
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute()
   at Orleans.Runtime.Silo.StartAsync(CancellationToken cancellationToken)
   at Orleans.Hosting.SiloHost.StartAsync(CancellationToken cancellationToken)
   at Orleans.Hosting.SiloHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at UBS.OrleansServer.EntryPoint.Start() in /app/UBS/OrleansServer/EntryPoint.cs:line 102
   --- End of inner exception stack trace ---
```

When Pods crash, StatefulSet restarts them. After some time, they stablize down.  Note the `RESTARTS` column

```
NAME                                 READY   STATUS             RESTARTS   AGE
ubs-job-dev-0                        1/1     Running            4          17m
ubs-job-dev-1                        1/1     Running            4          16m
ubs-job-dev-2                        1/1     Running            3          16m
```

Logs says there are 7 silos

> ProcessTableUpdate (called from TryUpdateMyStatusGlobalOnce) membership table: 7 silos, 3 are Active, 4 are Dead, Version=<33, 31015>. All silos: [SiloAddress=S10.18.123.246:11111:361178481 SiloName=ubs-job-dev-0 Status=Active, SiloAddress=S10.18.123.199:11111:361178519 SiloName=ubs-job-dev-1 Status=Active, SiloAddress=S10.18.117.114:11111:361178416 SiloName=ubs-job-dev-2 Status=Active, SiloAddress=S10.18.117.114:11111:361178292 SiloName=ubs-job-dev-2 Status=Dead, SiloAddress=S10.18.123.199:11111:361178366 SiloName=ubs-job-dev-1 Status=Dead, SiloAddress=S10.18.123.235:11111:361177868 SiloName=ubs-job-dev-0 Status=Dead, SiloAddress=S10.18.123.246:11111:361178329 SiloName=ubs-job-dev-0 Status=Dead]

Unlike ReplicaSet,  the pod name in StatefulSet does not change after restart. But it seems Orleans see each newly-started pod as a new silo, even its pod name does not change after restart.

And Consul gets more and more keys when PODs restart.

![image](https://user-images.githubusercontent.com/2765840/121769503-7d245c80-cb96-11eb-877a-04d1eada1add.png)

Although the POD will eventually stablize down and works well. But every time when our CI tool performs RollUpgrade on StatefulSet,  the PODs keep crashing and need restart over and over again to startup.

With only 3 replicas, it bloats to more than 20 silos in membership table. Will the Dead record removed from Consul sometime later? or it will bloat forever?

> Received cluster membership snapshot via gossip: [Version: 56, 21 silos, SiloAddress=S10.18.123.199:11111:361178366 SiloName=ubs-job-dev-1 Status=Dead, SiloAddress=S10.18.123.199:11111:361178235 SiloName=ubs-job-dev-1 Status=Dead, SiloAddress=S10.18.123.199:11111:361178120 SiloName=ubs-job-dev-1 Status=Dead, SiloAddress=S10.18.123.199:11111:361178519 SiloName=ubs-job-dev-1 Status=Dead, SiloAddress=S10.18.123.199:11111:361178018 SiloName=ubs-job-dev-1 Status=Dead, SiloAddress=S10.18.123.227:11111:361186453 SiloName=ubs-job-dev-1 Status=Active, SiloAddress=S10.18.123.246:11111:361178201 SiloName=ubs-job-dev-0 Status=Dead, SiloAddress=S10.18.123.246:11111:361178329 SiloName=ubs-job-dev-0 Status=Dead, SiloAddress=S10.18.123.246:11111:361178481 SiloName=ubs-job-dev-0 Status=Dead, SiloAddress=S10.18.123.246:11111:361177984 SiloName=ubs-job-dev-0 Status=Dead, SiloAddress=S10.18.123.246:11111:361178087 SiloName=ubs-job-dev-0 Status=Dead, SiloAddress=S10.18.117.114:11111:361178075 SiloName=ubs-job-dev-2 Status=Dead, SiloAddress=S10.18.117.114:11111:361178416 SiloName=ubs-job-dev-2 Status=Dead, SiloAddress=S10.18.117.114:11111:361178174 SiloName=ubs-job-dev-2 Status=Dead, SiloAddress=S10.18.117.114:11111:361178292 SiloName=ubs-job-dev-2 Status=Dead, SiloAddress=S10.18.123.197:11111:361186514 SiloName=ubs-job-dev-0 Status=Active, SiloAddress=S10.18.117.116:11111:361182925 SiloName=ubs-job-dev-2 Status=Dead, SiloAddress=S10.18.123.235:11111:361177868 SiloName=ubs-job-dev-0 Status=Dead, SiloAddress=S10.18.123.218:11111:361182980 SiloName=ubs-job-dev-1 Status=Dead, SiloAddress=S10.18.123.255:11111:361183031 SiloName=ubs-job-dev-0 Status=Dead, SiloAddress=S10.18.117.117:11111:361186385 SiloName=ubs-job-dev-2 Status=Active]
info: Orleans.Runtime.MembershipService.ClusterHealthMonitor[100612]

**Comment by ReubenBond** [comment]
Hi @wangjia184, apologies for the slow response. The Consul membership provider should be cleaning up records after a week or so of them being declared `Dead`.

This behavior can be configured via these `ClusterMembershipOptions` properties:

``` C#
/// <summary>
/// The period of time after which membership entries for defunct silos are eligible for removal.
/// Valid only if <see cref="DefunctSiloCleanupPeriod"/> is not <see langword="null" />.
/// </summary>
public TimeSpan DefunctSiloExpiration { get; set; } = DEFAULT_DEFUNCT_SILO_EXPIRATION;
public static readonly TimeSpan DEFAULT_DEFUNCT_SILO_EXPIRATION = TimeSpan.FromDays(7);

/// <summary>
/// The duration between membership table cleanup operations. When this period elapses, all defunct silo
/// entries older than <see cref="DefunctSiloExpiration" /> are removed. This value is per-silo.
/// </summary>
public TimeSpan? DefunctSiloCleanupPeriod { get; set; } = DEFAULT_DEFUNCT_SILO_CLEANUP_PERIOD;
public static readonly TimeSpan? DEFAULT_DEFUNCT_SILO_CLEANUP_PERIOD = TimeSpan.FromHours(1);
```
