### ISSUE TITLE
Journaled grains get stucked on a single silo

### ISSUE THREAD

**Issue by VladislavRybnikov** [dotnet/orleans#7109]
At some time, all incoming requests to a single JournaledGrain are waiting for another for a long time (> 1 hour), similar requests to other actors being processed in a few ms. After the reboot of a single silo (with a problematic actor) - all problems are gone. Nothing special for these requests wasn't found.
Logs:
```
Current request has been active for 00:23:17.1282598 for activation [Activation: S10.47.128.135:11200:361300094*grn/Wallet.Grains.PlayerGrain/0+905497364-0x9828C6B2@7b6b0ba8 #GrainType=Wallet.Grains.PlayerGrain Placement=RandomPlacement State=Valid NonReentrancyQueueSize=78 EnqueuedOnDispatcher=1 InFlightCount=1 NumRunning=1 IdlenessTimeSpan=00:23:21.5362341 CollectionAgeLimit=00:30:00]. Currently executing Request S10.207.151.194:11200:361230394*cli/06e1d09f@1aa14087->S10.47.128.135:11200:361300094*grn/Wallet.Grains.PlayerGrain/0+905497364@7b6b0ba8 InvokeMethodRequest Wallet.GrainInterfaces.IPlayerGrain:ProcessTransactionAsync #27401026. Trying  to enqueue Request S10.207.151.4:11200:361230439*cli/d2d3bc93@a5baccae->S10.47.128.135:11200:361300094*grn/Wallet.Grains.PlayerGrain/0+905497364@7b6b0ba8 InvokeMethodRequest Wallet.GrainInterfaces.IPlayerGrain:GetAllBalances #40652271.
```
```
Dropping expired message Status Response S10.207.150.39:11200:361230195*grn/Wallet.Grains.PlayerGrain/0+443427711@18c5cd87->S10.207.151.194:11200:361230394*cli/b9b506bc@cbd7119d #19082289 at phase Send
```

We hosting Orleans inside the Kubernetes cluster and using consul clustering and Redis grain directory.

**Comment by VladislavRybnikov** [comment]
Maybe this can help to resolve this issue. 
We see that the actor is stucked and all other requests to this actor are causing such errors:
```
{
  "message": 
  "Response did not arrive on time in 00:00:30 for message: 
	Request *cli/020eeebf@fc27ffa6->S10.42.159.2:30003:0*grn/Wallet.Grains.PlayerGrain/0+load-test-90862 
	InvokeMethodRequest Wallet.GrainInterfaces.IPlayerGrain:GetAllBalances #14. 
	Last known status is IsExecuting: False, IsWaiting: True, 
	Diagnostics: [
		[
			Activation: S10.42.159.2:11200:363365558*grn/Wallet.Grains.PlayerGrain/0+load-test-90862-0xD4F6E62E@bbddc2b0 
			#GrainType=Wallet.Grains.PlayerGrain 
				Placement=RandomPlacement 
				State=Valid 
				NonReentrancyQueueSize=27 
				EnqueuedOnDispatcher=0 
				InFlightCount=1 
				NumRunning=1 
				IdlenessTimeSpan=737977.15:27:10.3233030 
				CollectionAgeLimit=00:01:30
		], 
		TaskScheduler status: 
		WorkItemGroup:Name=
		[
			Activation: S10.42.159.2:11200:363365558*grn/Wallet.Grains.PlayerGrain/0+load-test-90862@bbddc2b0 
			#GrainType=Wallet.Grains.PlayerGrain 
				Placement=RandomPlacement 
				State=Valid
		],
		WorkGroupStatus=Waiting. 
		Currently QueuedWorkItems=0; 
		Total Enqueued=33; 
		Total processed=33; 
		Quantum expirations=0; 
		TaskRunner=ActivationTaskScheduler-167820:Queued=0; 
		Detailed context=
			<[
				Activation: S10.42.159.2:11200:363365558*grn/Wallet.Grains.PlayerGrain/0+load-test-90862-0xD4F6E62E@bbddc2b0 
				#GrainType=Wallet.Grains.PlayerGrain Placement=RandomPlacement 
					State=Valid 
					NonReentrancyQueueSize=27 
					EnqueuedOnDispatcher=0 
					InFlightCount=1 
					NumRunning=1 
					IdlenessTimeSpan=737977.15:27:10.3234443 
					CollectionAgeLimit=00:01:30 
					CurrentlyExecuting=NewPlacement 
					Request S10.42.159.2:11200:363365558*cli/448778a4@1af3ff87->S10.42.159.2:11200:363365558*grn/Wallet.Grains.PlayerGrain/0+load-test-90862@bbddc2b0 
					InvokeMethodRequest Wallet.GrainInterfaces.IPlayerGrain:ProcessTransactionAsync #160970]
			>, 
		Message NewPlacement Request S10.42.159.2:11200:363365558*cli/448778a4@1af3ff87->S10.42.159.2:11200:363365558*grn/Wallet.Grains.PlayerGrain/0+load-test-90862@bbddc2b0 
		InvokeMethodRequest Wallet.GrainInterfaces.IPlayerGrain:ProcessTransactionAsync #160970 was enqueued 00:13:39.8899371 ago and has now been executing for 00:13:39.7216966., 
		Message Request S10.42.159.2:11200:363365558*cli/020eeebf@fc27ffa6->S10.42.159.2:11200:363365558*grn/Wallet.Grains.PlayerGrain/0+load-test-90862@bbddc2b0 
		InvokeMethodRequest Wallet.GrainInterfaces.IPlayerGrain:GetAllBalances #14 has been enqueued on the target grain for 00:00:25.0570648 and is currently position 27 in queue for processing.
	]. 
	Target History is: <S10.42.159.2:30003:0:*grn/Wallet.Grains.PlayerGrain/0+load-test-90862:>."
}
```

**Comment by VladislavRybnikov** [comment]
@benjaminpetit pls help

**Comment by benjaminpetit** [comment]
It seems that a request to `IPlayerGrain.ProcessTransactionAsync` is blocking the grain.

Can you share the code of this method?

**Comment by VladislavRybnikov** [comment]
We are using JournaledGrain and the method ProcessTransaction pseudo is following (excluding metrics and logs):

```csharp
public async Task<TransactionResultDto> ProcessTransaction(Transaction transaction)
{
	RaiseEvent(new TransactionEvent(template.Value, transaction));
        await ConfirmEvents();
	await _kafkaProducer.Publish(transaction);
}

```
And ApplyUpdatesToStorage 

```csharp
public async Task<bool> ApplyUpdatesToStorage(IReadOnlyList<TransactionEvent> updates, int expectedVersion)
{
    if (expectedVersion != State.Version)
        return false;

    if (State.ShouldBeStored)
    {
        var generation = await _stateRepository.PutAsync(State.ToStateData());
        State.SetGeneration(generation);
        _commitTransactionsTask = _transactionRepository.TouchTransactions(_appliedTransaction);
        _appliedTransaction.Clear();
    }

    foreach (var transactionEvent in updates)
    {
        if (transactionEvent.Transaction.BalanceVersion != State.Version)
        {
            continue;
        }

        await _transactionRepository.InsertAsync(transaction);
    }

    return true;
}

```

BUT, what is most important is that there are problems under high load for methods that do not use the JournaledGrain event sourcing algorithm. For example simple methods with changing state and storing data to DB. Also, the same requests after restarting of Orleans node with the problematic grain will be retried successfully. Now it is stably reproducing on our test environment under load testing when we set up ~1000 req/sec and around 100k activations. Our client code gets a request from the message broker and retries each failure with circuit breaker policy (5 times and delay 10 sec). When we restart the client service (but not the Orleans service), and the load is gone (25 total activations on the dashboard), the problematic grain still returning timeouts. For test purposes, we surround all our methods with timeout logic (fail with exception after 5 sec and log it as an error), but we did not notice the logs with timeout errors from our client code. So, it looks like the request was deadlocked before entering the grain...

**Comment by VladislavRybnikov** [comment]
Also, the WorkGroupStatus=Waiting, maybe there are some problems inside OrleansTaskScheduler?

**Comment by VladislavRybnikov** [comment]
@benjaminpetit, Could we use SiloMessagingOptions.MaxRequestProcessingTime for deactivation of stuck grains? And could you please take a look at the previous message about WorkGroupStatus ?

**Comment by VladislavRybnikov** [comment]
What is interesting is that for [ActivationData.EnqueueMessageResult](https://github.com/dotnet/orleans/blob/2eb6b863f548d2790c4346e0857bd7f56d6063e8/src/Orleans.Runtime/Catalog/ActivationData.cs#L375) if there will a deadlock (and SiloMessagingOptions.MaxRequestProcessingTime set 1 minute) in `JournaledGrain.ReadStateFromStorage` method the [State](https://github.com/dotnet/orleans/blob/2eb6b863f548d2790c4346e0857bd7f56d6063e8/src/Orleans.Runtime/Catalog/ActivationData.cs#L206) property will be Activating but [Blocking](https://github.com/dotnet/orleans/blob/2eb6b863f548d2790c4346e0857bd7f56d6063e8/src/Orleans.Runtime/Catalog/ActivationData.cs#L282) property will be null so handling of [ActivationData.EnqueueMessageResult.ErrorStuckActivation](https://github.com/dotnet/orleans/blob/97062ace8a89811ee3ac3ca6805d54e7b6b56334/src/Orleans.Runtime/Core/Dispatcher.cs#L471) will never be reached. Is this expected behavior or not?
