### ISSUE TITLE
https://aka.ms/orleans-troubleshooting points to non-existent page

### ISSUE THREAD

**Issue by pechkarus** [dotnet/orleans#7111]
While looking at error messages, some of them contained this link https://aka.ms/orleans-troubleshooting. It appears to point to non-existent page (HTTP 404):
![image](https://user-images.githubusercontent.com/124804/122141529-6124f300-ce02-11eb-8893-e408cc20d3fd.png)

**Comment by ReubenBond** [comment]
We fixed the redirect some time ago but neglected to update this thread - thank you for reporting, @pechkarus!
