### ISSUE TITLE
Catalog.GCTimer timer should have fired at

### ISSUE THREAD

**Issue by DiAifU** [dotnet/orleans#7113]
Hi,

I have an issue since a few days that I didn't have before. Orleans starts to complain the Catalog.GCTimer has not fired in time after a few minutes/hours after the process start.
I haven't had any of these problem before, and I don't know exactly what is causing them, but due to that, the grain starts to respond really slowly. It is working perfectly fine until this message appears for the first time, and then the grain responds slowly. The rest of the process is running fine, because I have some timers that continue to work perfectly fine in the process.

The messages are the following :
> Self-monitoring determined that local health is degraded. Degradation score is 1/8 (lower is better). Complaints: "Health check participant Orleans.Runtime.Catalog is reporting that it is unhealthy with complaint: Catalog.GCTimer timer should have fired at 16/06/2021 18:43:19, which is 14:02:52.2339738 ago"

> Health check participant "Orleans.Runtime.Catalog" is reporting that it is unhealthy with complaint: "Catalog.GCTimer timer should have fired at 16/06/2021 18:43:19, which is 14:02:52.2339738 ago"

I have both of them at the same time every 10 secs exactly.

I also did a trace in dotTrace but I just see that the process seems to be waiting for something :
![image](https://user-images.githubusercontent.com/675679/122365765-3e5a2200-cf5b-11eb-8b3e-8992a0125f91.png)

Let me know if I can give you more information.

Nicolas

**Comment by ReubenBond** [comment]
@DiAifU are you able to capture a memory dump of a process which is in that state and show us what the Parallel Stacks (Threads & Tasks) views in Visual Studio look like?

**Comment by DiAifU** [comment]
Hi,

Sorry for the French language. Here is the list of threads :
![image](https://user-images.githubusercontent.com/675679/122529360-b557ef00-d01d-11eb-80b9-1dca324827ee.png)

The list of tasks which is basically only waiting and planned tasks and  :
![image](https://user-images.githubusercontent.com/675679/122529789-213a5780-d01e-11eb-88c5-bd2ac48bacc8.png)

Also VS Analysis tell me that there is a deadlock in a IClusterClient.Dispose() call :
![image](https://user-images.githubusercontent.com/675679/122530021-59419a80-d01e-11eb-992b-542b32734f9a.png)

**Comment by DiAifU** [comment]
From what I see in the ClusterClient code, Dispose calls GetAwaiter().GetResult(). I guess this is the cause of my deadlock ?
Implementing the IAsyncDisposable interface would probably fix my issue I guess

**Comment by ReubenBond** [comment]
You should not need to use a ClusterClient in the same process as the silo - you can just start the silo and get `IClusterClient`/`IGrainFactory` from the silo/host service provider.


Apologies for the slow response

**Comment by DiAifU** [comment]
I needed to use a ClientBuilder because the grain I want to talk to is in a different cluster. I implemented the IAsyncDisposable interface and my problem was solved.

Thanks for the answer, I'm closing the issue
