### ISSUE TITLE
Queue Mapper only works for static queues?

### ISSUE THREAD

**Issue by wangjia184** [dotnet/orleans#7128]
I am trying to implement a custom stream provider.   I guess `IConsistentRingStreamQueueMapper.GetQueuesForRange()` is called by each silo to determine the queues to be pulled by SystemTargets of current silo. In other words, all queues are distributed on all silos by consistent ring.  Is that right?

As I see from the source code, 
https://github.com/dotnet/orleans/blob/3.5.0/src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubQueueMapper.cs,  the queues are static.  Does that mean I cannot add more queues when system is running?

In my use case, I want to have 1-to-1 mapping between stream and queue. The queue supports priority. So when producing a message via `OnNextAsync`,  I suppose I can supply the priority within `StreamSequenceToken`

**Comment by benjaminpetit** [comment]
Correct, the system for now doesn't support adding/removing queues.
