### ISSUE TITLE
What is new in Orleans v3.4.3

### ISSUE THREAD

**Issue by pcdccam** [dotnet/orleans#7135]
Can anyone please help me with my query ? What is new in version v3.4.3 comparing to v3.4.2 ?
I couldn't find this information in https://github.com/dotnet/orleans/releases..

**Comment by nycdotnet** [comment]
Based on the release dates, it's probably [this diff](https://github.com/dotnet/orleans/compare/4e2af02...efa8adb9530ae9233662a793c7675a9d2552b289), but hard to know without the tag being applied or a release marked.

**Comment by ReubenBond** [comment]
Apologies for the slow delay. v3.4.3 only includes one PR not included in v3.4.2: #7049. There were other changes which were supposed to be included, but they weren't due to human error. Ultimately, we decided to roll them up into v3.5.0 instead.

**Comment by nycdotnet** [comment]
Thanks Reuben!

**Comment by ReubenBond** [comment]
Release published https://github.com/dotnet/orleans/releases/tag/v3.4.3
3.5.0 will be released soon - there were a couple more fixes which internal partners were waiting on.
