### ISSUE TITLE
Question: Migrating reminders from DynamoDB to Azure Table Storage

### ISSUE THREAD

**Issue by benthepoet** [dotnet/orleans#7139]
I'm currently working on migrating our Orleans backend from AWS over to Azure with minimal downtime. 

For grain storage we took the approach of implementing a custom provider that checks if the grain state is present in Azure Blob Storage and if not then it pulls it from DynamoDB and writes the state into Azure. This allows us to live migrate grain states over as they're activated.

Now we're looking at how to migrate our reminders from DynamoDB to Azure Table Storage. Is there a similar strategy to how we're migrating grain storage available? Can we do this live or does it require taking all the silos down? We have less than 100 reminders in production, so it's a rather small set of data.

**Comment by ReubenBond** [comment]
Hi @benthepoet, you could potentially write a custom reminders provider which adapted both providers and assisted with the migration.

Are these reminders updated frequently? If not, then a custom one-shot tool to read from DynamoDB and write to Azure Table Storage might also work.

**Comment by benthepoet** [comment]
That's helpful. So theoretically in a custom `IReminderTable` implementation it sounds like doing the following in `ReadRows(uint beginHash, uint endHash)` would work:
* Read rows from DynamoDB for range
* If rows are found then move them to Azure Table
* Return rows from Azure Table for range
