### ISSUE TITLE
How to Store Transaction State In Regular Storage If Transaction Is Successful

### ISSUE THREAD

**Issue by nkosi23** [dotnet/orleans#7141]
What would be the correct pattern to save a transaction state in regular storage (grain storage, custom storage...) **immediately** after a successful transaction. I have a complex grain having custom storage logic. I already have a place to store the properties/state involved in the transaction and I do not want to spread the domain model across several data stores. 

I do not mind using ITransactionState<T> as some sort of transient data store enabling Orleans to manage the distributed transaction, however looking at the documentation, it looks like Orleans is forcing us to store the domain data involved in a transaction as TransactionalState, which looks weird seems this feature is advertised as a way to allow us to run distributed ACID transactions across heterogeneous data stores (even across systems). 

As a result, I have a hard time believing that having to fit all reads and writes in synchronous PerformRead/PerformUpdate methods is the whole story, I have to be missing something. Unfortunately [the documentation does not address](https://dotnet.github.io/orleans/docs/grains/transactions.html) this major use case. If PerformRead/PerformUpdate accepted two async delegates allowing us to define async remote calls to save and rollback state, this would have made more sense to me. This is the kind of API I am after.

I am looking for the API/hook that would allow me to save data wherever I want at the end of a transaction. Saving data in custom stores at the end of the method marked as TransactionOption.Create seems risky since if I need to commit the data to 3 different data stores (say A, B and C), and the last commit to the data store C fails, having to write this kind of rollback code looks a lot like defeating the whole purpose for which this feature was created in the first place.

**Comment by ReubenBond** [comment]
Orleans transactions requires storing the metadata associated with the transaction alongside the domain data because it (only) depends on atomic writes - i.e, it is not a mechanism for integrating multiple transactional stores, but rather a general purpose mechanism for storing transactional state which may or may not involve state stored in multiple stores.

Am I understanding correctly that what you're asking for is a mechanism to save *raw* state to multiple different stores when a transaction commits in an atomic fashion? If so, that is not possible unless those stores themselves support distributed transactions (i.e, it wouldn't be enough for them to each be independently transactional).

**Comment by nkosi23** [comment]
Many thanks for your assistance! Indeed a mechanism to save raw state to different stores when a transaction commits in an atomic fashion is what I was asking. Your explanations make sense and clarify things quite a lot in my mind. 

However this leads me to this question: how can we access the transaction state independently from the TransactionState<T> facet being injected in the grain? For example, is it possible to use a grain as a transaction state, so that the grain can be instantiated independently of the transaction.

To clarify what I am trying to explain: in SQL databases, while a row may be updated in the context of a transaction, any row can be read and updated outside of a transaction. My concern is that the Orleans Transaction framework seems to take full ownership of the TransactionState to the extent that it is not clear to me how one may access the data (the transaction state) outside of the context of a transaction.

Beside my search for a pattern/API allowing me to achieve what I am after, my concern is that I'm afraid that using transactions means forfeiting control of our schema and data model. I am hoping there is a way to use transactions where needed, but keep Orleans transparent in terms of its impact on our data model.

Now I can also sense that it may actually make sense to consider that as soon as some data is updated atomically in a distributed transaction, one should stick to reading it using the transaction framework to ensure the value being read is consistent. However, i wonder if in practice this architecture will pass the test of time, and we will not face a need to access some transaction state independently. Maybe this concern is not justified though.

Having more insights in the way transaction state is stored and retrieved by Orleans (how is the right TransactionState located by Orleans? Which entity id is being used) would probably go a long way to ease these concerns.

**Comment by ReubenBond** [comment]
> How can we access the transaction state independently from the TransactionState facet being injected in the grain?

You can't, Orleans transactions are all-or-nothing - but it's often a reasonable ask for cases where transactional guarantees are not necessary. I'd like if we could support a *stale read* type of functionality for reading previously-committed state outside the scope of a transaction. I also am not a fan of the current PerformRead/PerformUpdate APIs: I would prefer something which is not callback-driven.

Your concerns around schema/data model are entirely reasonable and I would avoid Orleans' transactions if you need that level of control. Orleans' transactions do not fit all use cases for the reasons you identified, but thankfully you can always use a regular transactional database, so nothing is being taken away.

**Comment by nkosi23** [comment]
This fully answers my question, thank you very much for your time.

> one way to allow developers to implement stale reads would be to have a simple on-commit hook so that you could update a private field on the grain when a commit occurs.

This would be great indeed

**Comment by nkosi23** [comment]
Any chance to see this on-commit hook land in 3.5? This would open up a world of very interesting possibilities.
