### ISSUE TITLE
TlsClientConnectionMiddleware does not have a certificate selector

### ISSUE THREAD

**Issue by andyatwork** [dotnet/orleans#7143]
There is no way to reload a certificate through a selector on a new client connection. Ideally, the client would  TlsOptions.LocalServerCertificateSelector over TlsOptions.LocalCertificate when specified, just like in TlsServerConnectionMiddleware.

Doing so would allow certificate rotations, say through Azure KeyVault (and  VM extension) to occur seamlessly and without a process restart.

**Comment by ReubenBond** [comment]
Fixed in #7144
