### ISSUE TITLE
Azure membership on Azurite throws etag exception

### ISSUE THREAD

**Issue by MarcDHall** [dotnet/orleans#7146]
`[silo_63ebdfaa-8]: Azure table access write error InsertTableEntryConditionally to table OrleansSiloInstances entry OrleansSilo [ Deployment=signallingcluster LocalEndpoint=172.20.128.1 LocalPort=11111 Generation=363341917 Host=MATH Status=Joining ProxyPort=30000 RoleName=Platform.Signalling.Orleans.Silo SiloName=Silo_7ddc8 UpgradeZone=0 FaultZone=0 StartTime=2021-07-07 08:18:37.846 GMT IAmAliveTime=2021-07-07 08:22:21.306 GMT]
[silo_63ebdfaa-8]: System.ArgumentException: Replace requires an ETag (which may be the '*' wildcard).`

Orleans successfully writes a single row then fails with the above error. Not sure if this is an issue with Orleans or Azurite. Might be that the Azurite API deviates from Azure?

**Comment by ElanHasson** [comment]
I am encountering the same thing.

**Comment by ReubenBond** [comment]
Is this an issue with Orleans or Azurite? It seems that if Azurite's behavior diverges from Azure Storage's behavior, then it may be classified as an Azurite issue.

**Comment by koenbeuk** [comment]
This seems to be related to Azurite indeed, see: https://github.com/Azure/Azurite/issues/946

**Comment by ReubenBond** [comment]
This has since been fixed.
