### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by kwaazaar** [dotnet/orleans#7148]
I'm trying to get started with Orleans, but I find myself searching the source code and checking the [HanBaoBao-sample](https://github.com/ReubenBond/hanbaobao-web), because there is no decent documentation.

There are so many packages for example and I have no idea when to use what. I'm trying to use grains inside my ASP.NET service (host+client in one app), which to me seams like the most used scenario, but I cannot find any documentation on this.

**Comment by ElanHasson** [comment]
Hi @kwaazaar,

Have you seen https://dotnet.github.io/orleans/docs/host/client.html ?

To get a grain client, see https://dotnet.github.io/orleans/docs/host/client.html#initialization-of-grain-client

If you're inside of the silo host already (like in ASP.Net) and you'd like to call a gain from a controller or similar, and you're using DI, you can just inject a `IClusterClient` to get the same behavior.

Let me know if you're still having trouble and I can help out further.

**Comment by kwaazaar** [comment]
Thank you for the answer.

I am now using _grainFactory.GetGrain<IUserGrain>(... Is that not correct?
Found that [here](https://github.com/ReubenBond/hanbaobao-web/blob/d0c8b1a1685aac75df11becbe66499f136ed689b/HanBaoBaoWeb/Search.cs).

**Comment by ReubenBond** [comment]
Either `IGrainFactory` or `IClusterClient` (which implements `IGrainFactory`) is fine.
We are working on documentation improvements (and your feedback is welcome). In the meantime, hopefully the samples which @ElanHasson linked (https://github.com/dotnet/orleans/tree/main/samples) are useful to you.

**Comment by detaybey** [comment]
Problem with existing tutorials and examples are they are either Hello Orleans or some simple counter. Most people including me find these examples hard to understand the benefits of Orleans. We need an updated real life scenario example.

**Comment by ReubenBond** [comment]
@detaybey after looking at [the samples](https://github.com/dotnet/orleans/tree/main/samples), are there other kinds of samples you'd like to see? Or is the issue that the samples do not have step-by-step style tutorials?

On that subject, would something like [this Consoso.Monitoring sample](https://github.com/bradygaster/Contoso.Monitoring) be suitable?

**Comment by kwaazaar** [comment]
I'm currently having two very basic questions and I tried to find an example which will demonstrate these. I looked at all their descriptions, but I cannot find the answers.

- How can a grain communicate with another?
- How can a grain publish an event which another grain can subscribe to without (the Receive<T>() method in Akka.net)

**Comment by ReubenBond** [comment]
@kwaazaar the basics are that grains communicate with each other by making method calls. There is no Receive method.
The Hello World sample explains the steps https://github.com/dotnet/orleans/tree/main/samples/HelloWorld#readme

* Get a reference to the grain you want to call using `grainFactory.GetGrain<TGrainInterface>(key)`
* Make a method call on that grain by calling a method

There is no difference between calling a grain from within a grain or from outside a grain (eg, from an ASP.NET MVC controller)

**Comment by PiotrJustyna** [comment]
This does not solve the documentation problem you're experiencing, but you can also find many good examples here: https://github.com/PiotrJustyna/road-to-orleans

**Comment by ReubenBond** [comment]
Closing as not directly actionable (please open specific issues for areas/questions)
