### ISSUE TITLE
Misleading stack trace - https://aka.ms/orleans-troubleshooting

### ISSUE THREAD

**Issue by PiotrJustyna** [dotnet/orleans#7155]
I noticed this exception in my logs:

```
OnClientRefreshTimer has thrown an exceptions.
Orleans.Runtime.SiloUnavailableException: The target silo became unavailable for message: Request S10.50.10.15:32779:363843678*stg/DirectoryService/0000000a@S0000000a->S10.50.10.251:32775:363839619*stg/DirectoryService/0000000a@S0000000a InvokeMethodRequest Orleans.Runtime.IRemoteGrainDirectory:RegisterAsync #1964. Target History is: <S10.50.10.251:32775:363839619:*stg/DirectoryService/0000000a:@S0000000a>. See https://aka.ms/orleans-troubleshooting for troubleshooting help.
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
   at Orleans.Runtime.GrainDirectory.LocalGrainDirectory.RegisterAsync(ActivationAddress address, Boolean singleActivation, Int32 hopCount)
   at Orleans.Internal.OrleansTaskExtentions.LogException(Task task, ILogger logger, ErrorCode errorCode, String message)
   at Orleans.Runtime.ClientObserverRegistrar.OnRefreshClients()
```

which is fine, but it looks like this url is no longer valid: `https://aka.ms/orleans-troubleshooting`. It resolves to `https://dotnet.github.io/orleans/Documentation/deployment/troubleshooting_deployments.html` which results in a 404.

I'm happy to take a look into fixing it, but what should be the correct URL?

![Screen Shot 2021-07-13 at 9 48 44 AM](https://user-images.githubusercontent.com/6170837/125421682-2b996a09-adab-41af-a6c5-9e37f57a98d8.png)

**Comment by ReubenBond** [comment]
Thanks for letting us know, @PiotrJustyna! I'll update the aka.ms link. In the meantime, the correct link is https://dotnet.github.io/orleans/docs/deployment/troubleshooting_deployments.html (docs instead of Documentation)

**Comment by benjaminpetit** [comment]
I just updated the link, thanks for catching this!
