### ISSUE TITLE
Question: Long running grains

### ISSUE THREAD

**Issue by shersh** [dotnet/orleans#7156]
Is there any solutions for long running grains?

**Comment by ReubenBond** [comment]
@shersh what are you trying to accomplish, is is individual method calls which take a long time (>20s, for example) to complete, or is it grains which are active for a very long time (many hours)?

**Comment by ericgla** [comment]
You might want to take a look at this post...  [Long-running tasks in Orleans dotnet](https://pcholko.com/posts/2020-06-07/orleans-long-running-tasks/)

**Comment by shersh** [comment]
@ReubenBond I mean tasks with looong time. 
For example some workers that must be unique in cluster and with some methods for starting, stopping, progress getting

**Comment by ReubenBond** [comment]
@shersh the post which @ericgla linked above is a good start. I would suggest much the same: if the work is not to be completed synchronously, then model it as a series of methods with either eager notification (faster response time on completion), polling (more resilient), or both (fast & resilient, but more complex).

**Comment by nkosi23** [comment]
The following documentation link mentioned in the blog post no longer works:

https://dotnet.github.io/orleans/Documentation/grains/external_tasks_and_grains.html

I also wasn't able to find the page by browsing the documentation.

**Comment by nkosi23** [comment]
My mistake, while the link is indeed broken, as far as the Orleans website is concerned the page is correctly referenced in the advanced documentation for grains:

https://dotnet.github.io/orleans/docs/grains/external_tasks_and_grains.html
