### ISSUE TITLE
Client connection tracking during rolling deploys

### ISSUE THREAD

**Issue by jsteinich** [dotnet/orleans#7162]
I've been troubleshooting some issues during rolling silo deploys. Specifically, clients will often fire the `ConnectionToClusterLost` event despite the new silo(s) being available. I'm trying to determine a point at which the client(s) know about the new silo(s) at which we can safely shutdown the old silo(s).

I was thinking that waiting ~1 minute after the new silo is up would be enough (since gateway configuration is updated every minute on the client); however, I observed that even though the client knew about the new gateway (confirmed by refresh gateway logging), it still triggered the connection lost when the old server shutdown ~20 seconds later.
Is there some other later point or some proactive work that could be done to ensure that shutdown is safe?

This mostly matters because we are shutting down the client on connection loss to make sure any client side streams are recreated cleanly.

Setup:
- Separate clients and silos running in AWS ECS Fargate tasks
- DynamoDB membership

**Comment by benjaminpetit** [comment]
Clients only create connection "lazily". Moreover, they will try to always use the same silo connection for a given grain.

So if your clients are not making grain calls, or at least not frequently, it's possible that they end up with no opened connection.

If you enabled info log on clients, you should see this message every minutes "Refreshed the live gateway list [...]". Can you check that you see your new silo in this list?

**Comment by jsteinich** [comment]
> So if your clients are not making grain calls, or at least not frequently, it's possible that they end up with no opened connection.

Good to know. I have seen this most often in test environments, so that makes sense.



> If you enabled info log on clients, you should see this message every minutes "Refreshed the live gateway list [...]". Can you check that you see your new silo in this list?

Yep, that's how I was able to confirm that the client "knew" about the new silo.



> Clients only create connection "lazily". Moreover, they will try to always use the same silo connection for a given grain.

Is there any way to force a connection to the new silo?

**Comment by benjaminpetit** [comment]
> Is there any way to force a connection to the new silo?

Nothing out of the box at least... I think it's something to consider for the next major release maybe?

You would not have this issue if you were not using separate clients. Do you have any strong reason to keep them?

**Comment by jsteinich** [comment]
> > Is there any way to force a connection to the new silo?
> 
> Nothing out of the box at least... I think it's something to consider for the next major release maybe?

Automatic client stream resubscription would be even nicer. I'm testing out an application level version of this based on advice in other issues, but I don't have some concerns about reliably detecting the need.



> You would not have this issue if you were not using separate clients. Do you have any strong reason to keep them?

Our stack was initially built before co-hosting was an option. Conceptually I look the divisions in terms of responsibility, scaling, and security; however, I'm not sure that it's necessarily been helpful from a practical perspective.

**Comment by benjaminpetit** [comment]
> Automatic client stream resubscription would be even nicer.

Check `AddClusterConnectionLostHandler` on the client builder. You can inject your own logic to run when the client detects that it lost all connection to the cluster.

> Our stack was initially built before co-hosting was an option. Conceptually I look the divisions in terms of responsibility, scaling, and security; however, I'm not sure that it's necessarily been helpful from a practical perspective.

I agree on the benefits of dividing clients and silos. However, co-hosting bring a lot of benefits: more robust failover detection, less network hops during calls (min 1, in most case 2 less hops), potentially less serializations, easier to deploy.... I think these benefits outweigh the advantage of segregating client/silos.

I am not saying you should do the architecture change now, your scenario is still and will be supported.

**Comment by benjaminpetit** [comment]
I will close this issue now, feel free to reopen this issue if you still need help or have any suggestion for future version.

I think `AddClusterConnectionLostHandler` should be enough in your case.
