### ISSUE TITLE
RequestContext does not get a value

### ISSUE THREAD

**Issue by 107295472** [dotnet/orleans#7165]
Start by ClusterClientHostedService, inherit IOutgoingGrainCallFilter, and call it in Invoke. There is no value in get in AddIncomingGrainCallFilter of silo

**Comment by suraciii** [comment]
Could you provide some code snippets to better explain this issue?

**Comment by 107295472** [comment]
`  public class ClusterClientHostedService : IHostedService
    {
        private readonly ILogger<ClusterClientHostedService> _logger;

        public ClusterClientHostedService(ILogger<ClusterClientHostedService> logger, ILoggerProvider loggerProvider)
        {
            _logger = logger;
             Client = new ClientBuilder()
                    .Configure<SerializationProviderOptions>(options =>
                    {
                        options.SerializationProviders.Add(typeof(BondSerializer));
                        options.FallbackSerializationProvider = typeof(BondSerializer);
                    })
                    .Configure<GatewayOptions>(opts => opts.GatewayListRefreshPeriod = TimeSpan.FromMinutes(2))
                    .Configure<ConnectionOptions>(options => { options.ProtocolVersion = NetworkProtocolVersion.Version2; })
                    .Configure<ClusterOptions>(options =>
                    {
                        options.ClusterId = OrleansConfig.ClusterId;
                        options.ServiceId = OrleansConfig.ServiceId;
                    })
#if dev
                    .UseLocalhostClustering()
#else
   .UseAdoNetClustering(options =>
                    {
                        options.ConnectionString = AppSettings.Configuration["ConnectionString"];// connectionString;
#if PgSQL
                        options.Invariant = "Npgsql";
#endif
#if MsSQL
                        options.Invariant = "System.Data.SqlClient";
#endif
#if MySQL
                        options.Invariant = "MySql.Data.MySqlClient";
#endif
                    })
#endif
                    .AddSimpleMessageStreamProvider(StreamProviderProxy.StreamProviderName)
                    .AddOutgoingGrainCallFilter(async context =>
                    {
                        if (context.Grain is ISecurityContext)
                        {
                            RequestContext.Set(ContextConfig.traceKey, "GrainCall:3333");
                        }
                        Freight.Core.Reflection.Utilities.JsonSerialize(context.Arguments), traceKey, traceOrder));

                        await context.Invoke();
                    })
                    .Build();
        }





            return builder
                .Configure<SerializationProviderOptions>(options =>
                {
                    options.SerializationProviders.Add(typeof(BondSerializer));
                    options.FallbackSerializationProvider = typeof(BondSerializer);
                })
                .Configure<ConnectionOptions>(options => { options.ProtocolVersion = NetworkProtocolVersion.Version2; })
                .Configure<ClusterOptions>(options =>
                {
                    options.ClusterId = clusterId;
                    options.ServiceId = serviceId;
                })
                .Configure<GrainCollectionOptions>(options => { options.CollectionAge = TimeSpan.FromMinutes(grainCollectionAgeMinutes); })
#if dev
                .UseLocalhostClustering()
#else
   .UseAdoNetClustering(options =>
                                {
                                    options.ConnectionString = connectionString;
#if PgSQL
                                    options.Invariant = "Npgsql";
#endif
#if MsSQL
                                    options.Invariant = "System.Data.SqlClient";
#endif
#if MySQL
                                    options.Invariant = "MySql.Data.MySqlClient";
#endif
                                })
                                .AddAdoNetGrainStorageAsDefault(options =>
                                {
                                    options.ConnectionString = connectionString;
#if PgSQL
                                    options.Invariant = "Npgsql";
#endif
#if MsSQL
                                    options.Invariant = "System.Data.SqlClient";
#endif
#if MySQL
                                    options.Invariant = "MySql.Data.MySqlClient";
#endif
                                })
                                .UseAdoNetReminderService(options =>
                                {
                                    options.ConnectionString = connectionString;
#if PgSQL
                                    options.Invariant = "Npgsql";
#endif
#if MsSQL
                                    options.Invariant = "System.Data.SqlClient";
#endif
#if MySQL
                                    options.Invariant = "MySql.Data.MySqlClient";
#endif
                                })
                                .ConfigureEndpoints(siloPort, gatewayPort)
#endif

                .ConfigureApplicationParts(parts =>
                {
                    foreach (string fileName in Directory.GetFiles(App.AppBaseDirectory, "*.Business.dll"))
                    {
                        parts.AddApplicationPart(Assembly.LoadFrom(fileName)).WithReferences().WithCodeGeneration();
                    }
                       
                    foreach (string fileName in Directory.GetFiles(App.AppBaseDirectory, "*.Contract.dll"))
                    {
                        parts.AddApplicationPart(Assembly.LoadFrom(fileName)).WithReferences().WithCodeGeneration();
                    }
                       
                    foreach (string fileName in Directory.GetFiles(App.AppBaseDirectory, "*.Api.dll"))
                    {
                        parts.AddApplicationPart(Assembly.LoadFrom(fileName)).WithReferences().WithCodeGeneration();
                    }
                       
                })
                .AddSimpleMessageStreamProvider(StreamProviderProxy.StreamProviderName)
                .AddMemoryGrainStorage("PubSubStore")
                .AddIncomingGrainCallFilter(async context =>
                {
                    if (context.Grain is ISecurityContext)
                    {
                        var t = RequestContext.Get(ContextConfig.traceKey);
                        Console.WriteLine(t);
                    }
                    await context.Invoke();
                }).ConfigureServices(ConfigureServices);
             }
        private static void ConfigureServices(IServiceCollection services)
        {
            services.AddSingletonNamedService<PlacementStrategy, SamplePlacementStrategy>(nameof(SamplePlacementStrategy));
            services.AddSingletonKeyedService<Type, IPlacementDirector, SamplePlacementStrategyFixedSiloDirector>(typeof(SamplePlacementStrategy));
        }
`

**Comment by 107295472** [comment]
Requestcontext. Set cannot be fetched without ISecurityContext
