### ISSUE TITLE
ADO.NET Clustering: implement `CleanupDefunctSiloEntries`

### ISSUE THREAD

**Issue by wangjia184** [dotnet/orleans#7171]
With Microsoft.Orleans.Clustering.AdoNet v3.4.3, and MySql.Data,  Microsoft Orleans handled SIGTERM signal and exited gracefully.
But the corresponding record in OrleansMembershipTable is not removed. Its status changes to `6`.

```
info: Orleans.Hosting.SiloHostedService[0]
      Stopping Orleans Silo
info: Orleans.Runtime.SiloLifecycleSubject[100452]
      OrleansDashboard.Metrics.GrainProfiler stopped in stage Last (2147483647) in 0.4551 Milliseconds.
info: Orleans.Runtime.SiloLifecycleSubject[100452]
      Stopping lifecycle stage Last (2147483647) took 2.9755 Milliseconds
info: Orleans.Runtime.SiloLifecycleSubject[100452]
      Orleans.Hosting.SiloBuilderStartupExtensions+StartupTask stopped in stage Active (20000) in 0.1449 Milliseconds.
info: Orleans.Runtime.SiloLifecycleSubject[100452]
      MembershipTableCleanupAgent stopped in stage Active (20000) in 1.6222 Milliseconds.
info: Orleans.Runtime.SiloLifecycleSubject[100452]
      ClusterHealthMonitor stopped in stage Active (20000) in 20.5276 Milliseconds.
info: Orleans.Runtime.SiloLifecycleSubject[100452]
      Orleans.Runtime.MembershipService.LocalSiloHealthMonitor stopped in stage Active (20000) in 10.6568 Milliseconds.
info: Orleans.Runtime.SiloLifecycleSubject[100452]
      Orleans.Runtime.Silo stopped in stage Active (20000) in 6.772 Milliseconds.
```

![image](https://user-images.githubusercontent.com/2765840/127440081-94d2d7ba-07c7-4e91-a1a0-8003a2a80d4e.png)

And I see the following warning message.
```
warn: Orleans.Runtime.MembershipService.MembershipTableCleanupAgent[100662]
      CleanupDefunctSiloEntries operation is not supported by the current implementation of IMembershipTable. Disabling the timer now.
```

The OrleansMembershipTable is bloating.  Is there a way to remove unneeded records from the table?

**Comment by benjaminpetit** [comment]
Silo status "6" means that the silo is no longer online. It is an information that can be necessary for some part of Orleans and its provider.

What membership provider are you using? The table is getting bigger because the provider you are currently using does not support cleaning of old entries.

**Comment by wangjia184** [comment]
The provider is Microsoft.Orleans.Clustering.AdoNet v3.4.3

**Comment by veikkoeeva** [comment]
One option always is to prune unused entries explicitly.

The SQL clause to prune exist, f.ex. https://github.com/dotnet/orleans/blob/main/src/AdoNet/Orleans.Clustering.AdoNet/SQLServer-Clustering.sql#L229 and the delete action is implemented at https://github.com/dotnet/orleans/blob/main/src/AdoNet/Orleans.Clustering.AdoNet/Messaging/AdoNetClusteringTable.cs#L166. It seems to be it ought to be wired to https://github.com/dotnet/orleans/blob/10af0f4af588cd4aa45cb3e250dfbffa389d59c7/src/AdoNet/Orleans.Clustering.AdoNet/Messaging/AdoNetClusteringTable.cs#L194.

**Comment by benjaminpetit** [comment]
It would be more efficient do to this cleaning with a date condition in SQL, no?

**Comment by veikkoeeva** [comment]
@benjaminpetit Maybe. Let I be clearer, I think (thought) the beforeDate is not fixed, so it needs to be passed as a parameter to the database. It can use whatever part that is in `beforeDate`. If it's always fixed, it can be embedded also in SQL.

I think, since this was from the Codeplex era code that this delete has been used in tests and such, not in production. So it may warrant a new SQL clause to be added (I'd prefer SQL, since it's easier to change, even dynamically, if needed).

**Comment by veikkoeeva** [comment]
If it becomes clear how to handle this variable, we can create a clean workitem and implement this. :)

**Comment by benjaminpetit** [comment]
The value isn't fixed, it's computed like this: `DateTime.UtcNow - ClusterMembershipOptions.DefunctSiloExpiration`

**Comment by wangjia184** [comment]
A dirty hack to avoid bloating OrleansMembershipTable table:

Prepend the following SQL to `OrleansQuery` table, Key is `InsertMembershipKey`

```
DELETE FROM OrleansMembershipTable WHERE `Status` = 6 AND `IAmAliveTime` < DATE_SUB(UTC_TIMESTAMP(), INTERVAL 10 MINUTE);  
```

**Comment by veikkoeeva** [comment]
@wangjia184 This does not need to be 'a dirty hack', one can have a scheduled reminder to do this too. :) It may be better to implement the right functionality in code now that it's available in Orleans.

I'm not sure I can get to this this month, but I think there is now sufficient information available on how to implement this to Orleans.

**Comment by ReubenBond** [comment]
Is the work item here to implement `CleanupDefunctSiloEntries` for the ADO.NET clustering provider (plus deployment scripts for each DB)?

**Comment by veikkoeeva** [comment]
@ReubenBond I think so. Should we create a clearer one with all information in one place?

@wangjia184 has a clever workeraround too, just modify the query to delete entries before the membership insertion. This way the table is periodically pruned. It's of course not the same thing as implementing the functionality.

**Comment by fabiociconi** [comment]
Hi 
I am having the same issue. Did someone try to implement the functionality?

**Comment by ReubenBond** [comment]
Help is wanted to implement `CleanupDefunctSiloEntries` for the ADO.NET Clustering provider

**Comment by fabiociconi** [comment]
For now @ReubenBond I included a delete into the `OrleansQuery `table, Key is `InsertMembershipKey`, after the commit transaction. Does it look right? Any suggestion?

`Update OrleansQuery
SET QueryText = '
	SET XACT_ABORT, NOCOUNT ON;
	DECLARE @ROWCOUNT AS INT;
	BEGIN TRANSACTION;
	INSERT INTO OrleansMembershipTable
	(
		DeploymentId,
		Address,
		Port,
		Generation,
		SiloName,
		HostName,
		Status,
		ProxyPort,
		StartTime,
		IAmAliveTime
	)
	SELECT
		@DeploymentId,
		@Address,
		@Port,
		@Generation,
		@SiloName,
		@HostName,
		@Status,
		@ProxyPort,
		@StartTime,
		@IAmAliveTime
	WHERE NOT EXISTS
	(
		SELECT 1
		FROM
			OrleansMembershipTable WITH(HOLDLOCK, XLOCK, ROWLOCK)
		WHERE
			DeploymentId = @DeploymentId AND @DeploymentId IS NOT NULL
			AND Address = @Address AND @Address IS NOT NULL
			AND Port = @Port AND @Port IS NOT NULL
			AND Generation = @Generation AND @Generation IS NOT NULL
	);

	UPDATE OrleansMembershipVersionTable
	SET
		Timestamp = GETUTCDATE(),
		Version = Version + 1
	WHERE
		DeploymentId = @DeploymentId AND @DeploymentId IS NOT NULL
		AND Version = @Version AND @Version IS NOT NULL
		AND @@ROWCOUNT > 0;

	SET @ROWCOUNT = @@ROWCOUNT;

	IF @ROWCOUNT = 0
		ROLLBACK TRANSACTION
	ELSE
		COMMIT TRANSACTION
		BEGIN
			COMMIT TRANSACTION
			-- Manually included to delete status 6 (dead status)
			DELETE FROM OrleansMembershipTable
			WHERE 
			Status = 6 
			AND IAmAliveTime < GETUTCDATE();
		END
	SELECT @ROWCOUNT;
'
WHERE QueryKey = 'InsertMembershipKey'`

**Comment by ElanHasson** [comment]
I'll take this one.
