### ISSUE TITLE
Co-hosting Orleans with the web host and background worker doesn't run the Silo in .NET 5.0

### ISSUE THREAD

**Issue by ld100** [dotnet/orleans#7175]
I'm on .NET 5.0 (Linux) and Orleans 3.4.2.
Trying to co-host Orleans silo with the web host and a background worker (which calls Orleans grainFactory). The app starts with no problem, but both Silo and the Background worker show no signs of life: no logs, Gateway/Silo ports are not open.
I'm using ADO storage/clustering and see that all appropriate database tables are empty.

Tried switching the order of boot (e.g. starting worker and web before or after Orleans), but result was the same.

Here is my *Program.cs* for the Silo: https://gist.github.com/ld100/b79d71448c994aeaf1d3e8c0bc16d2b6

Am I doing something wrong?

**Comment by ReubenBond** [comment]
What happens when you attach a debugger and break some time after it has become stuck?

**Comment by ld100** [comment]
Could try the debugging tomorrow, but I'm not sure what even to look for, since technically the app is not stuck, e.g. the web host (which is initialized after the Silo and worker) runs just fine.

**Comment by ReubenBond** [comment]
That's very strange. Do you get logs from the Web host?

**Comment by ld100** [comment]
Yeah, getting logs from the web host:

```
{"@t":"2021-07-29T15:54:26.5717354Z","@m":"Now listening on: \"http://[::]:5000\"","@i":"d826f4b8","address":"http://[::]:5000","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-07-29T15:54:26.5788996Z","@m":"Application started. Press Ctrl+C to shut down.","@i":"dcaefe54","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-07-29T15:54:26.5791884Z","@m":"Hosting environment: \"Production\"","@i":"c3307c92","envName":"Production","SourceContext":"Microsoft.Hosting.Lifetime"}
{"@t":"2021-07-29T15:54:26.5795546Z","@m":"Content root path: \"/app\"","@i":"b5d60022","contentRoot":"/app","SourceContext":"Microsoft.Hosting.Lifetime"}
```

**Comment by zahirtezcan-bugs** [comment]
We had an issue with using `IGrainFactory` in background worker. Grain factory gives the requested grain without a problem (``var grain = grainFactory.GetGrain<IMyGrain>(0);` ), but **stalls indefinitely** when you make a call eg. `await grain.Foo()`. 

This was due to silo startup is asynchronous and worker was getting the grain reference **too soon**.

My solution to the problem was two fold; 

1. either subscribe to silo lifecyle wait until silo is activated,
2. or make a busy wait on `IClusterClient.IsInitialized`

Your mileage may vary

**Comment by ld100** [comment]
I've just tried removing an async worker altogether for the test and result was the same: the application starts and I'm getting logs from the web host part, but the silo part looks dead (ports not open, no logs).

Any other ideas what should I do?

**Comment by veikkoeeva** [comment]
https://github.com/dotnet/orleans/tree/main/samples/OneBoxDeployment should start both console and run tests in reliable configuration.

**Comment by ld100** [comment]
Don't think OneBoxDeployment is relevant here, since it does not use Ado clustering, grain storage, etc. and it is "one box".

**Comment by ReubenBond** [comment]
So you get zero logs from the silo? If that's true, please attach a debugger to find out why. I can walk you through it if you DM me on gitter: https://gitter.im/ReubenBond
