### ISSUE TITLE
Can linux and win cluster together?

### ISSUE THREAD

**Issue by 107295472** [dotnet/orleans#7180]
fail: Orleans.Runtime.Scheduler.OrleansTaskScheduler[101231]
      QueueWorkItem was called on a non-null context [SystemTarget: S192.168.110.21:11117:365663783*stg/13/0000000d@S0000000d] but there is no valid WorkItemGroup for it.

**Comment by benjaminpetit** [comment]
I am not sure about the link between the title and the content of the issue?

We don't test mixed environment yet. So maybe it works, maybe it doesn't. I wouldn't do that in production without extensive validation.
