### ISSUE TITLE
VirtualBucketsRingProvider may cause issues on removal if silo was added with hash collision

### ISSUE THREAD

**Issue by Horusiath** [dotnet/orleans#7193]
If you checkout implementation of `VirtualBucketsRingProvider.AddServer` method you may stumble on the case where Orleans handles potential collisions using silo seniority: https://github.com/dotnet/orleans/blob/10af0f4af588cd4aa45cb3e250dfbffa389d59c7/src/Orleans.Runtime/ConsistentRing/VirtualBucketsRingProvider.cs#L118-L129

However when removing a silo, this rule is no longer applied: https://github.com/dotnet/orleans/blob/10af0f4af588cd4aa45cb3e250dfbffa389d59c7/src/Orleans.Runtime/ConsistentRing/VirtualBucketsRingProvider.cs#L145-L149

Instead removal just blindly removes the buckets without checking if silo they were assigned to matches the method parameter. This may cause removing bucket for active silo.

**Comment by ReubenBond** [comment]
Thanks for finding that, @Horusiath! Of course, you're right that it's an issue. Are you able to submit a PR to fix it?
