### ISSUE TITLE
Does CollectionAgeLimit have some kind of hard limit or I am configuring it wrong?

### ISSUE THREAD

**Issue by kuskmen** [dotnet/orleans#7201]
A little background:

We have a CPU leak inside our silo, which we believe we already found and made a fix for it, but in order to verify it, I had to configure grain deactivation to a reasonable amount of time before concluding our fix as final.

The problem:

I configured `collectionAgeLimit` and `collectionAgeQuantum` following this [guidelines](https://dotnet.github.io/orleans/docs/host/configuration_guide/activation_garbage_collection.html). This is how host builder configurations looks like.

```csharp
Host
    .CreateDefaultBuilder(args)
    .UseOrleans((context, siloBuilder) =>
    {
         var configuration = context.Configuration;

         var settings = configuration
              .GetSection(nameof(SiloHostSettings))
              .Get<SiloHostSettings>();

         siloBuilder
             .UseKubernetesHosting()
             .UseZooKeeperClustering(options => options.ConnectionString = settings.ZooKeeperConnectionString)
             .Configure<GrainCollectionOptions>(options => 
             {
                 options.CollectionAge = TimeSpan.FromSeconds(settings.GrainGarbageCollectionAgeInSec);
                 options.CollectionQuantum = TimeSpan.FromSeconds(settings.GrainGarbageCollectionQuantumInSec);
             })
             .ConfigureApplicationParts(options => options
             .AddApplicationPart(typeof(MarketGrain).Assembly)
             .AddApplicationPart(typeof(IMarketGrain).Assembly));

        var dashboardSettings = configuration
            .GetSection("OrleansDashboardSettings")
            .Get<OrleansDashboardSettings>();
})
```

Starting the silo prompts the following configurations

```
[13:13:47 INF] Configuration Orleans.Configuration.GrainCollectionOptions:
CollectionQuantum: 00:00:02
CollectionAge: 01:00:00
DeactivationTimeout: 00:00:30
```

Also, we notice that `DeactivateAsync()` is not called within the configured (from us) time, just in case the log is wrong.

Thank you very much for your time for any further questions I will strive to answer as quickly as possible!

**Comment by ReubenBond** [comment]
Could you try using constants instead pulling the value from `IConfiguration` and update your comment to match? I cannot validate the settings here are correct.

**Comment by kuskmen** [comment]
Do you refer to the log? If yes, this log comes from Orleans logger we are not logging anything specific to Orleans by ourselves. I will log the constants nevertheless and update you.

**Comment by ReubenBond** [comment]
No, I mean that your code sample should be as simple as possible, so you should use constants to configure the values and not IConfiguration. Once that's working, then introduce IConfiguration again.

**Comment by kuskmen** [comment]
Which constants? Because the constants I find are readonly or am I missing something?

**Comment by ReubenBond** [comment]
``` C#
options.CollectionAge = TimeSpan.FromSeconds(120);
options.CollectionQuantum = TimeSpan.FromSeconds(2);
```

**Comment by kuskmen** [comment]
Yes, as expected I am stupid and I overlooked one of the many overrides that we have in our configuration providers (appsettings, helm and etc.)
