### ISSUE TITLE
Unify the Orleans HostingEnvironment and the Microsoft.Extensions.Hosting implementations

### ISSUE THREAD

**Issue by icanhasjonas** [dotnet/orleans#7202]
As a suggested papercut item for Milestone 4

**Comment by ReubenBond** [comment]
@icanhasjonas apologies for the slow response. I agree with you. We should remove our version of `HostingEnvironment` and use `Microsoft.Extensions.Hosting.Abstractions` instead.

**Comment by ReubenBond** [comment]
Fixed in #7276
