### ISSUE TITLE
Sending Message From One Grain to Multiple Grains

### ISSUE THREAD

**Issue by BYiZ** [dotnet/orleans#7203]
Hi, I am trying to broadcast a message from a source grain to multiple other grains that subscribe the source. Inside the source grain, I keep a list of Guids of the subscribing grains that should receive an update message. I tried to iterate the list of Guids and using `await GrainFactory.GetGrain<ISubscribeGrain>().RecieveMessage(msg).ConfigureAwait(false);` to send the message inside the loop. However, when doing that I get `Activation access violation. A non-activation thread attempted to access activation services`.

I know https://github.com/dotnet/orleans/issues/7086 in this issue the creator of the issue suggested to use a static IGrainFactory, but this is not necessarily what i was looking for. Also, it shouldn't be necessary to use a static one as each Grain contains a IGrainFactory for us to use. 

Any thoughts on what is the cause of this issue and how to resolve it?

Thanks in advance.

**Comment by ReubenBond** [comment]
Never use `ConfigureAwait(false)` in your grain code.
In your case, it sounds like you should have a `List<Task>` (eg called `tasks`) which you populate by `foreach`ing over your subscribers, adding each `subscriber.ReceiveMessage(msg)` call to the list, and then calling `await Task.WhenAll(tasks)` after the loop.

**Comment by BYiZ** [comment]
I see! That indeed fix my issue! And I will try the await WhenAll approach! Thank you so much!
