### ISSUE TITLE
Is it possible to pass func or predicate as a parameter to a method in a grain

### ISSUE THREAD

**Issue by ajvwray** [dotnet/orleans#7207]
I've tried to add it is a parameter similar to this:

`public async Task<List<UserHistory>> GetUserHistory(Func<UserHistory, bool> filter = null)
`

And with nothing supplied it runs but any attempt to pass values i.e.

`var userHistory = await GetUserHistory(x=>x.LastLogin > DateTime.Now.AddDays(-1));`

It errors but can't even see where as nothing appears in the logs

**Comment by SebastianStehle** [comment]
I don't think so. Technically it would be possible to serialize it but if you capture a variable inside the function it is impossible.

**Comment by ajvwray** [comment]
> I don't think so. Technically it would be possible to serialize it but if you capture a variable inside the function it is impossible.

I've ended up using https://github.com/esskar/Serialize.Linq and its worked ok for now being passed as an param "ExpressionNode"
