### ISSUE TITLE
Transactions error

### ISSUE THREAD

**Issue by 107295472** [dotnet/orleans#7210]
No ITransactionalStateStorageFactory nor IGrainStorage with the name TransactionStore was found while attempting to create transactional state storage.

ATMGrain.cs
AccountGrain.cs

**Comment by 107295472** [comment]
System.InvalidOperationException: No ITransactionalStateStorageFactory nor IGrainStorage with the name TransactionStore was found while attempting to create transactional state storage.

**Comment by benjaminpetit** [comment]
You probably need to configure a storage provider with the name "TransactionStore"

**Comment by 107295472** [comment]
> You probably need to configure a storage provider with the name "TransactionStore"

AddRedisGrainStorage

**Comment by 107295472** [comment]
TransactionStore  Write it yourself
