### ISSUE TITLE
Distributed tracing support should use DistributedContextPropagator

### ISSUE THREAD

**Issue by shirhatti** [dotnet/orleans#7251]
Follow-up issue based on my feedback from #6853 

`ActivityPropagationIncomingGrainCallFilter` and `ActivityPropagationOutgoingGrainCallFilter` have apriori knowledge of the W3C TraceContext specification. It's better to delegate that to the configured `DistributedContextPropagator`. I'm not familiar with Orleans, but in ASP.NET Core we use the propagator registered in DI and if not present, we fall back to the globally configured `DistributedContextPropagator.Current`.

Relying of the default propagator also allows you to support the hierarchical ActivityId format (in addition to W3C) which was another ask on the PR.

:eyes: @cijothomas @tarekgh

**Comment by oising** [comment]
Tell me more--- would that help it actually integrate properly into Application Insights? Right now if you go with a purely OTEL approach and use the Azure Monitor exporter, it (this PR) doesn't pick up/correlate any causal RequestActivity which may have triggered the grain call, i.e. a co-hosted HTTP request.

**Comment by Ilchert** [comment]
we had the same discussion about v5 [packages](https://github.com/dotnet/orleans/pull/6853#issuecomment-742698992). I think we should refactor this code after orleans upgrades all nuget references to 6.0.

**Comment by shirhatti** [comment]
>  it seems DistributedContextPropagator is a .NET 6.0+ feature. Will it be available for 5.0 ?

It's part of `System.Diagnostics.DiagnosticSource` which also ships as NuGet package making it usable on net5.0 (and other TFMs)

> @shirhatti - could you point out a good/illuminating place, contextually, in asp.net core source that propagator is used, or documented? Please :)

Unfortunately, I don't have a good link to point you to. This is still hot of the press.
The next best thing is to take a look at the OpenTelemetry propagator specification. Specifically the the TextMapPropagator- https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#textmap-propagator.

> would that help it actually integrate properly into Application Insights? Right now if you go with a purely OTEL approach and use the Azure Monitor exporter, it (this PR) doesn't pick up/correlate any causal RequestActivity which may have triggered the grain call, i.e. a co-hosted HTTP request.

 My unfamiliarity with Orleans doesn't help answer that question 😅. Let me kept back to you on that

**Comment by oising** [comment]
@shirhatti Thank you -- for what it's worth from my extended reading, it seems that using "pure" OpenTelemetry .NET (with the Azure Monitor exporter) in conjunction with trace telemetry from Application Insights just doesn't integrate properly at all. They won't correlate on the server side - or at least I could not get it to work. It seems that the App Insights DiagnosticSource does things that make it incompatible with OTEL's DiagnosticSource, though they will both successfully publish to Azure Monitor.

**Comment by ReubenBond** [comment]
If someone is looking into implementing this, please feel free to reference .NET 6.0 preview packages, since `main` is a non-shipping branch at the moment - we will update the reference to a stable release when .NET 6.0 ships

**Comment by ReubenBond** [comment]
Fixed by @suraciii in #7443
