### ISSUE TITLE
[Question] Streams with very large number of subscribers

### ISSUE THREAD

**Issue by nkosi23** [dotnet/orleans#7254]
We have a design where occasionally something needs to be streamed to a large number of grains so that they can process the event and update their state.

My question is: how is stream delivery scheduled? What I am specifically interested in is: if there are so many consumers of a particular stream (say millions) that all these grains cannot be activated at once for example because of memory constraints. Is it right to assume that the consuming grains will be activated progressively in batches?

If so, let's say 10 batches are needed and that while Orleans is just starting to send the event to grains in the batch 4, the cluster is shutdown. When the cluster restarts will the delivery of the stream events already produced but not fully delivered resume where it stopped? Is this reliable?

I have this question for the SMS Stream Provider, and for durable stream providers (we intend to use RabbitMQ through a custom provider). 

I understand that streams are multiplexed through a smaller number of queues so it is not clear to me what would happen in this scenario.

Any insights would be appreciated,

Thanks

**Comment by nkosi23** [comment]
So after reading [this page](https://dotnet.github.io/orleans/docs/implementation/streams_implementation/index.html#pulling-protocola-namepulling-protocola), in particular the section regarding the pulling protocol, and after reading a bit of the source code, my understanding is that what will happen in the scenario I have described is that the items in the IQueueCache will not be marked as processed and therefore the event will be sent again to consumers the next time the cluster is started (including to consumers who already received it). Receiving the same event twice is not an issue, my only concern was data loss.

However this investigation led me to this seeing the class [PersistentStreamPullingAgent](https://github.com/dotnet/orleans/blob/c36462286928f23ff74772adae3e14b5c898fa28/src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs#L24) and triggered another question. From what I see, the list of all consumers is stored as an in-memory dictionary. This would mean that assuming that a StreamConsumerData record takes 100kb in memory, subscribing 30 million grains to a single stream would require having 2.8 terabytes of RAM on every single silo (since the cache is loaded in a single pulling agent, and a pulling agent can be placed on any silo by the runtime). 

Is this understanding correct? If so this looks like a major issue preventing users from relaying on streams for a wide-range of scenarios at web scale. If just requiring a single silo to have that much RAM would be an issue since 30 million grains is not that much (many small to medium applications have more records than that). And if my understanding is correct, this memory would be required even if the application only handles a relatively small number of concurrent users in practice (say 500k users per day).

For example, we are building a kind of social platform where every user has its own timeline modeled as a grain. Some events are specific to a user, so the user would subscribe directly to that stream, but some other events (for example general announcements) need to be sent to all users and then their timeline is in charge of either ignoring or accepting the event if it is relevant to the user (and in this case, putting it in the right position in the timeline). Many streams would therefore have a huge number of subscribers.

Even if an application is not expected to reach that many users, I feel there are many scenarios in which a developer would run into this issue, there just need to be a scenario where he needs a large number of grains to process the same updates in near real-time. I really hope my understanding is wrong.

**Comment by SebastianStehle** [comment]
Just a general note. In twitter users with large number of subscribers are handled differently, because of this problem. You just cannot duplicate a tweet 10 Mio Times.

**Comment by nkosi23** [comment]
@SebastianStehle Thanks Sebastian, this optimization is good to know (updating users' timeline on reads rather than on the production of an event) however it is not ideal as it takes us away from the streaming pattern and the conveniences it offers in terms of code simplicity and design patterns. So I'm really curious about how the Orleans runtime behaves in the situation I have described. 

As far as we are concerned what we are doing is not duplicating the content, every timeline inspects the content and if it is relevant stores a reference to it. Moreover timelines are FIFO queues of fixed size so we can always play with their length to keep storage under control. 

Anyway, these social platform situations are just one use case among many others, so introducing this kind of optimizations everywhere a large number of subscription is expected would make the code quite messy and inconsistent.

**Comment by benjaminpetit** [comment]
First, note that SMS isn't like other streaming provider, it's not a persistent one. There is no queue or caching involved. Everytime you publish an event, it will basically iterate over all subscribers and sent the event immediately.

> My question is: how is stream delivery scheduled? What I am specifically interested in is: if there are so many consumers of a particular stream (say millions) that all these grains cannot be activated at once for example because of memory constraints. Is it right to assume that the consuming grains will be activated progressively in batches?

Pulling agent will dequeue the event, put it into cache, and will notify all subscribers. There is nothing that will throttle these calls.

> So after reading this page, in particular the section regarding the pulling protocol, and after reading a bit of the source code, my understanding is that what will happen in the scenario I have described is that the items in the IQueueCache will not be marked as processed and therefore the event will be sent again to consumers the next time the cluster is started (including to consumers who already received it). Receiving the same event twice is not an issue, my only concern was data loss.

Mostly correct, items that are still in cache will be reloaded the next time the pulling agent start, but will not redeliver items to consumers that already processed them if they keep the last `StreamSequenceToken` they processed.

> However this investigation led me to this seeing the class PersistentStreamPullingAgent and triggered another question. From what I see, the list of all consumers is stored as an in-memory dictionary. This would mean that assuming that a StreamConsumerData record takes 100kb in memory, subscribing 30 million grains to a single stream would require having 2.8 terabytes of RAM on every single silo (since the cache is loaded in a single pulling agent, and a pulling agent can be placed on any silo by the runtime).
>
> Is this understanding correct? If so this looks like a major issue preventing users from relying on streams for a wide-range of scenarios at web scale. Just requiring a single silo to have that much RAM would be an issue since 30 million grains is not that much (many small to medium applications have more records than that). And if my understanding is correct, this memory would be required even if the application only handles a relatively small number of concurrent users in practice (say 500k users per day).

This is correct (I don't know how much space a `StreamConsumerData` takes however) assuming ALL your grains are ALWAYS subscribed to this stream.

If you have a small number of concurrent users, you could make their grain unsubscribe from the stream: no messages would be delivered. Once the user is active, he will trigger a grain activation that will subscribe to the stream, with a token pointing to the last processed event by this activation. It will then receive all events that happen between now and the last time this token was seen.

You might have issues with cache however: your cache will have to be big enough to support this scenario to avoid cache miss. Or handle them in another way.

Another possibility would be to configure different stream providers, partition users across these providers, have a queue balancer that is aware of that to place pulling agents in a clever manner, etc.

**Comment by nkosi23** [comment]
Thank you for these insights! Hum..... This makes Orleans feel slightly less magic. Why haven't you partitioned stream subscriptions across the whole silo similarly to what you have done with reminders? Well, you may actually have done it to a certain extent with pulling agents being placed randomly across the cluster, but there should probably be an additional layer of indirection to distribute subscriptions across the cluster.

A relatively easier workaround coming to my mind would be that for streams expected to have a large number of subscribers, we could create a component creating multiple streams behind the scenes. The API would look like this:
- StreamBalancer.GetStream(streamId): returns either a handle to the stream (if the stream has a small number of subscribers), or a handle to a replica of that stream (if the stream has a large number of subscribers)
- StreamBalancer.OnNext(streamId): publishes the event to the stream and all its replicas

Internally, this class would manage the replicas of the main stream. As a result, instead of having 1 stream with 30 million subscribers, this class would therefore automatically and transparently ensure that there is only (for example) 1,000 streams with 30,000 subscribers in a transparent manner for consumers, and without needing to change anything to the core classes of Orleans. Here what we are winning is that the StreamConsumerData dictionaries of the 1,000 streams would be balanced across the cluster.

However I feel this logic would benefit from being into the core library because in addition to making this concern transparent for users, right now users have to remember to never produce events using the handle returned by StreamBalancer.GetStream since the stream returned could be a replica (events should therefore only be produced using StreamBalancer.OnNext). However, by handling this logic in the core library of Orleans, every stream could be extended with the properties IsReplica and OriginalBalancedStream so that users can safely produce event using any handle while the runtime knows how to route events.

Is this something you would consider adding to Orleans 3.X or is there no chance that this would make it into any release (this is to allow me to make architectural decisions based on whether support for this will eventually land into Orleans).

**Comment by ReubenBond** [comment]
> This makes Orleans feel slightly less magic.

Orleans is most definitely *not* magic.

> Why haven't you partitioned stream subscriptions across the whole cluster similarly to what you have done with reminders? 

Orleans Streaming was designed with an intended use in mind. There are design tradeoffs which need to be made in terms of complexity, scalability, and supported semantics. In the case of streams, the target involved a relatively large number of streams with relatively few subscribers each, with each consumer checkpointing their position in the stream for reliability/deduplication. It simply was not designed for a single stream with 30 million subscribers and I do not see this architecture changing significantly in 3.x, but input on a theoretical "Streaming 2.0" is welcome, and designs/PRs even more so.

If you think that a library solution could work here, I'd be interested to see what you come up with. If it's something which can be transparently introduced into the core, even better.

**Comment by nkosi23** [comment]
Thank you all for your time and input, I am definitely interested in proposing a design and PR for this so I will leave this issue open in the meantime!

**Comment by nkosi23** [comment]
As a side remark, [the documentation website says](https://dotnet.github.io/orleans/docs/streaming/streams_why.html#motivation):

> A typical scenario for Orleans Streams is when you have per user streams and you want to perform different processing for each user, within the context of an individual user. We may have millions of users but some of them are interested in weather and can subscribe to weather alerts for a particular location, while some are interested in sports events; somebody else is tracking status of a particular flight. Processing those events requires different logic, but you don't want to run two independent instances of stream processing. Some users are interested in only a particular stock and only if a certain external condition applies, a condition that may not necessarily be part of the stream data (and thus needs to be checked dynamically at runtime as part of processing).

In light of @ReubenBond's remarks the wording and examples used here do not reflect the intended usage of streams (at least the current one). Weather - even limited to a region - is followed by millions of people. The same is true for sport events and stocks.  Maybe a warning should be added somewhere and/or clarifications on what is meant by "per user stream" because generally speaking the page really conveys a sense that Orleans was built to handle the use case I described. 

While the bar to shoot ourselves in the foot is actually quite low when one steps outside the Gaming and IoT scenarios. For example, one just needs to build a free news website using one large Orleans Stream + Websocket to deliver live updates to millions of people to hit this limitation quite easily and have to get his hands dirty. Flight tickets and IoT scenarios should probably be emphasized, and a warning should probably be added regarding streams with large number of consumers.

**Comment by ReubenBond** [comment]
@nkosi23 PRs welcome

**Comment by oising** [comment]
@nkosi23 You could also offload the subscription management to Redis, or Azure Web PubSub, for example.

**Comment by nkosi23** [comment]
I wanted to keep this issue open until I have enough bandwidth to submit a design and then PR.
