### ISSUE TITLE
Custom Stream Provider: IQueueAdapterFactory, IQueueAdapter and IQueueAdapterReceiver 

### ISSUE THREAD

**Issue by shykln** [dotnet/orleans#7262]
Hi Team,

I'm not sure if there is a doc for how to implement a custom stream provider.

```
  public interface IQueueAdapterFactory
  {
    /// <summary>Create queue adapter.</summary>
    /// <returns></returns>
    Task<IQueueAdapter> CreateAdapter();

    /// <summary>Create queue message cache adapter</summary>
    /// <returns></returns>
    IQueueAdapterCache GetQueueAdapterCache();

    /// <summary>Create queue mapper</summary>
    /// <returns></returns>
    IStreamQueueMapper GetStreamQueueMapper();
```

Could you explain some key concepts here:

1. What is a StreamQueueMapper?  I think an `IQueueAdapterFactory` would create multiple `IQueueAdapter` based on the QueueMapper
2. I saw `HashRingStreamQueueMapperOptions`, `IConsistentRingStreamQueueMapper`  can you describe how are they designed to be used?
3. When a grain subscribe to one stream, how many `IQueueAdapterReceiver` and `IQueueAdapter` instances would be used to serve this stream? And what if there are multiple grains subscribe to the same stream?

Thank you.

**Comment by benjaminpetit** [comment]
Before implementing a streaming provider, I strongly suggest to check how the streaming infrastructure in Orleans work :) There is some doc here: https://dotnet.github.io/orleans/docs/implementation/streams_implementation/index.html

Let me know what more info you need that's not cover by this doc.
