### ISSUE TITLE
how to get all grain state

### ISSUE THREAD

**Issue by wuzhenda** [dotnet/orleans#7266]
I use grain persistence to save device status which from iot-devices.
I can get one device status by grain which primary key is the device Id.
How can I get all the devices status without know the device Ids?
Yes.I may use raw sql query.but if there are already exist method in orleans.

**Comment by SebastianStehle** [comment]
There is no good method for that, but you have 2 options:

1. Write your own store. It is not that complicated, perhaps this helps: https://github.com/Squidex/squidex/blob/master/backend/src/Squidex.Infrastructure/Orleans/GrainState.cs

2. Write an index grain, which maintains a list of all device grains, but you have to register your device grain when activated the first time.

**Comment by wuzhenda** [comment]
tks.

**Comment by wuzhenda** [comment]
https://github.com/dotnet/orleans/pull/1772

**Comment by SebastianStehle** [comment]
Good to know, but most of the time you want all grains, not only the active records.
