### ISSUE TITLE
How to create grains working with SQL Server?

### ISSUE THREAD

**Issue by Oleg26Dev** [dotnet/orleans#7268]
How to create this or where can I find any sample like this style:

The server creates silo with grains to work with SQL Server database, for example:
GetProduct(id)
GetProducts()
AddProduct(id)
DelProduct(id)
DelProducts()

When clients (multiple, in any language) connect to the server and send commands like:
/GetProduct?id=idx etc (REST, GRPC, GraphQL)
the server created the grains and each grain executes and returns status and data .

I build a ASP.NET Core web server which works via (REST, GRPC, GraphQL). thats thy the question.
Thank you!

**Comment by ReubenBond** [comment]
Hi @Oleg26Dev, I'm not sure if there are any samples for this (grain calling into SQL directly), but it is relatively straightforward: you create grains and grain interfaces which have those methods and then call into SQL directly from the implementation.

What benefit are you looking for Orleans to give you in this case, other than perhaps caching `GetProduct(id)` calls. Could you elaborate on what you'd like Orleans to handle here?

**Comment by Oleg26Dev** [comment]
Hi @ReubenBond , 
I have now WCF web service. It SOAP+REST. But it is legacy (as MS declared) and I am rewriting it using gRPC.NET, adding GraphQL endpoint and REST still exist.
I see what yet new technologies can be used. 
I am going to add Orleans  to the server to use caching (as you correctly wrote), performance and scalability, i.e. to use clustering provided by Orleans. 
The schema of my web service is: 
Client -> Web Service->Database Server->database
Every client passes to server Database (SQL Server or PostgreSQL) name, database name and query.
I.e. 
N11 clients (SQL Server1+db11)->Web Service->SQL Server1->db1
N12 clients (SQL Server1+db12)->Web Service->SQL Server1->db12
...
N101 clients (SQL Server2+db21)->Web Service->SQL Server2->db21
...
P1 clients (PGSQL1+dbp21)->Web Service->PGSQL1+dbp21
and so on.

The loading can be different in different day/night time, including very high in some 1-2 hrs.

**Comment by NTTAKR** [comment]
Hi @Oleg26Dev, @ReubenBond 

My setup is not very different from your description, but I am using MongoDB as a database. 
What you should definitely have in mind is number of connections to the database. 
Orleans is easily scaling to multiple thousands of grains on a single machine, whereas your database would be very upset if every grain would make its own database connection. 
You would quickly run out of instances. 

I was thinking about having a number of grains that work as database "workers" and they ask for work on some sort of coordinator.
So you have the client issueing work items to grains, the grains themselves putting their work-order into a coordinator grain and the database "worker" grains asking the coordinator for work items. 
You can control how much worker grains are alive and even modify that during runtime if desired. 

@ReubenBond I am not sure if the coordinator thing could be solved more elegantly using PubSub or streams. That's where you have a much better overview on Orleans. 

Best of luck with your implementation!
