### ISSUE TITLE
[Question] Is it possible to get details about grain activation reason inside grain?

### ISSUE THREAD

**Issue by f-i-x-7** [dotnet/orleans#7274]
Hello,

I am developing a system where some caching grain is implemented:

```c#
    public interface ISomeDataGrain : IGrainWithStringKey
    {
        [ReadOnly]
        Task<SomeData> GetData();

        Task Refresh(bool force = false);
    }

    [StorageProvider(ProviderName = "StorageProvider")] // actually it is backed by MS SQL + EF Core
    public sealed class SomeDataGrain: Grain<SomeDataGrainState>, ISomeDataGrain
    {
        private async Task Reload()
        {
            DataFromOtherSystem dataFromOtherSystem = await DoSomeExpensiveNetworkCalls();
            ConvertAndSetToGrainState(dataFromOtherSystem);
            await WriteStateAsync();
        }

        public override async Task OnActivateAsync()
        {
            if (State is null)
            {
                State = new();
                await Reload();
            }
            else
            {
                if (IsDataStale())
                {
                    await Reload();
                }
            }
            await base.OnActivateAsync();
        }

        public Task<SomeData> GetData()
        {
            return Task.FromResult(ConvertGrainStateToSomeData());
        }

        public async Task Refresh(bool force = false)
        {
            if (force || IsDataStale())
            {
                await Reload();
            }
        }

        // other private methods are ommitted for simplicity of this sample
    }
```

So, as you see, cache is updated automatically only during grain activation. If grain is already active then cache should be updated only in case of manual call of `Refresh()` method. This allows to use interleaving for `GetData()` method calls which improves throughtput.

I am trying to extend it with some internal contract (it will not be visible to regular Orleans cluster clients):

```c#
    public interface ISomeDataGrainInternal : IGrainWithStringKey
    {
        Task SetDataManually(DataFromOtherSystem dataFromOtherSystem);
    }
    
    public sealed class ExchangeSymbolGrain : Grain<SomeDataGrainState>, ISomeDataGrain, ISomeDataGrainInternal 
    {
        public async Task SetDataManually(DataFromOtherSystem dataFromOtherSystem)
        {
            ConvertAndSetToGrainState(dataFromOtherSystem );
            await WriteStateAsync();
        }
    }
```

In this case, if required data was already loaded from external source in advance, I want to prevent excessive network calls to external source in `OnActivateAsync()` (e.g. - do not call `Reload()` in `OnActivateAsync()` if `SetDataManually()` is called). Is it possible?

I tried to implement `IIncomingGrainCallFilter` by this grain and detect whether `SetDataManually()` is called, but grain activation occurs before interceptor is called. So actually this is of no help.

I see 2 options that are "dirty":
1) Do not introduce `ISomeDataGrainInternal.SetDataManually()`, just write preloaded data directly to database and then call `ISomeDataGrain.GetData()`.
2) Still implement `IIncomingGrainCallFilter` by this grain. Move `Reload()` call from `OnActivateAsync()` to interceptor (`OnActivateAsync()` should just detect the necessity of such reload). The downside is: because of reentrancy of `ISomeDataGrain.GetData()` method, I need to introduce a critical section in interceptor (e.g. using `SemaphoreSlim.WaitAsync()`) to ensure that `Reload()` will not be called more than once. As for me, manual reentrancy management inside Orleans grains is "dirty" approach.

What actually would be preferrable is to have an access to some grain activation context inside `OnActivateAsync()` where reason of grain activation could be detected (e.g. call of some grain method, or silo shutdown & grain relocation to another silo, etc.).

**Comment by benjaminpetit** [comment]
I see two solutions here:

- use `RequestContext` to say to the grain to skip data loading in the `OnActivateAsync` ([see doc](https://dotnet.github.io/orleans/docs/grains/request_context.html))
- never load data in `OnActivateAsync`, but check is `State` is `null` before returning the result. Otherwise, do a **grain call** to `Refresh(false)` that will load the data only if it was not loaded, so only the first call coming from `GetData` will actually do a network call.

**Comment by f-i-x-7** [comment]
Thank you for response.

> * never load data in `OnActivateAsync`, but check is `State` is `null` before returning the result. Otherwise, do a **grain call** to `Refresh(false)` that will load the data only if it was not loaded, so only the first call coming from `GetData` will actually do a network call.

This seems interesting. But, if 2 clients call `GetData()` then the calls will interleave because of [ReadOnly] attribute. And if then both calls do a grain call to `Refresh(false)`, then such calls will be interleaved too, won't they?

**Comment by benjaminpetit** [comment]
Not if you do something like this:

```csharp
        public Task<SomeData> GetData()
        {
            if (State is null)
            {
                // Since GetData is interleaving and we don't want to
                // call Reload concurrently, do not call Reload() directly,
                // do a grain call on itself
                await this.AsReference<ISomeDataGrain>().Reload(false);
            }
            return ConvertGrainStateToSomeData();
        }
````

**Comment by f-i-x-7** [comment]
> Not if you do something like this:
> 
> ```cs
>         public Task<SomeData> GetData()
>         {
>             if (State is null)
>             {
>                 // Since GetData is interleaving and we don't want to
>                 // call Reload concurrently, do not call Reload() directly,
>                 // do a grain call on itself
>                 await this.AsReference<ISomeDataGrain>().Reload(false);
>             }
>             return ConvertGrainStateToSomeData();
>         }
> ```

Unfortunately, interleaving occurs. Repro that I used for test before actually implementing it:

```c#
public interface ITestGrain : IGrainWithGuidKey
{
    Task Reload(bool force = false);

    [ReadOnly]
    Task<int> GetData();
}

public sealed class TestGrainState
{
    public DateTimeOffset LoadedAt { get; set; }
}

[StorageProvider(ProviderName = StorageProviders.Redis)] // for test purpose Redis is used instead of MS SQL
public sealed class TestGrain : Grain<TestGrainState>, ITestGrain
{
    private static readonly TimeSpan RefreshTimeout = TimeSpan.FromHours(12);

    private readonly ILogger<TestGrain> logger;

    public TestGrain(ILogger<TestGrain> logger)
    {
        this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    public override Task OnActivateAsync()
    {
        State = null!; // Redis storage provider ensures not null state; for test purpose, set it to null explicitly as it would be in SQL Server case
        return base.OnActivateAsync();
    }

    public async Task Reload(bool force = false)
    {
        if (force || State is null || State.LoadedAt + RefreshTimeout < DateTimeOffset.Now)
        {
            logger.LogCritical("RELOAD"); // Critical level just for easy discoverability of log record

            await Task.Delay(1000); // emulate long network call
            State = new TestGrainState { LoadedAt = DateTimeOffset.Now };
            await WriteStateAsync();
        }
    }

    public async Task<int> GetData()
    {
        if (State is null)
        {
            await this.AsReference<ITestGrain>().Reload(false);
        }
        return 42;
    }
```

And client code:

```c#
var grain = client.GetGrain<ITestGrain>(Guid.NewGuid());
var nums = Enumerable.Range(0, 100).ToArray();
await Task.WhenAll(nums.Select(n => grain.GetData()));
```

I see 100 critical log records in silo logs.

Is this a bug with interleaving mechanism? I use Orleans 3.5.0.

**Comment by benjaminpetit** [comment]
Ah yes sorry, my mistake, the `AsReference` trick only works with Reminders.

I think the `RequestContext` solution is better.

**Comment by f-i-x-7** [comment]
> Ah yes sorry, my mistake, the `AsReference` trick only works with Reminders.
> 
> I think the `RequestContext` solution is better.

Ok, thank you for suggestions.

The questions are resolved, so I think the issue could be closed.
