### ISSUE TITLE
[Feature Request] Control the start of the grain reminders manually

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#7275]
Hi,

when cohosting my application I need to control the startup sequence. The preferred order would be:

1. Initialize my stuff like repositories and other services.
2. Start Orleans.
3. Run migrations to the database using some Orleans Grains.
4. Start the reminders.

Step 3 is the problem here because the Reminders start together with step 2, when Orleans is initialized. I have worked around this by stopping all grains that make use of reminders in my migration step and to start them again when I am done, but it is easy to forget one grain.

Would be great to have a way for this to run the reminders. Perhaps just a separate "UseReminders" method that can be invoked in the correct order.

**Comment by ReubenBond** [comment]
Hi Sebastian, apologies for the slow response. What you are asking for sounds reasonable to me, but I want to try to understand it better before jumping to a solution.

Does step 3 need to use grains? If it were some other service (with no dependencies on the runtime), it would be relatively straight-forward to insert it before reminders start. What benefit does making it a grain have here?

For step 4, does starting reminders mean starting the delivery of reminders? What about registration? If grains are allowed to run after step 2, then what would stop one from registering a reminder before the reminder service has started?

**Comment by SebastianStehle** [comment]
Yes, step 3 requires grains, but none of them uses reminders.

I am talking about delivery of reminders only, not registration.

**Comment by nkosi23** [comment]
> Yes, step 3 requires grains, but none of them uses reminders.
> 
> I am talking about delivery of reminders only, not registration.

I think @ReubenBond is pointing to potential implementation challenges and asking your views on the expected behavior (ie. if we allow people to use grains before reminders are activated, what should happen if someone tries to register a reminder in grain code) and your use case (what benefits do you gain by putting your point 2 logic into a grain over a regular class at this stage of your program.

**Comment by SebastianStehle** [comment]
Hi,

Step 3:
I have indexing grains. Sometimes, very infrequently it happens that the index gets corrupt. So part of migration and repair process is to trigger a method on the indexing grains to repair itself. Of course I could add this to a normal class, but it would either make my code more complicated or I would have to introduce code duplication. But when repairing indexes, the background processes cannot run. E.g. I have a grain executing jobs and asking the index grain for an entity that belongs to that job. During repair the index grain might not be able to provide this entity and job might think that the entity has been deleted in the meantime. 
There are obviously other solutions, like throwing an exception in the index grain while the repair is running and then retry the job a few times, but doing the things in the right order is the easiest approach for me.

Step 4:
I would say, if a reminder is registered, it just gets registered and should run as normal when the reminders start running. Of course this breaks the duetime guarantee, but I think it is the best solution.
