### ISSUE TITLE
Actor Action Execution Time

### ISSUE THREAD

**Issue by turowicz** [dotnet/orleans#7280]
Is it possible to tell how long my actors and their methods take?

Looking at the performance counters in this repo I am unable to tell how to get that information:

https://github.com/zh6335901/Orleans.TelemetryConsumers.Prometheus
https://github.com/zh6335901/Orleans.TelemetryConsumers.Prometheus/blob/master/src/Orleans.TelemetryConsumers.Prometheus/PrometheusTelemetryConsumer.cs

But I see they are not using the `properties` dictionary in their implementation. Is it possible that grain names and actions are there and its as easy as pulling those out?

cc @ReubenBond @sergeybykov

**Comment by turowicz** [comment]
cc @ursanon

**Comment by JorgeCandeias** [comment]
You can use an `IIncomingGrainCallFilter` to perform this kind of custom telemetry for all grains and methods. This is [how the Orleans Dashboard](https://github.com/OrleansContrib/OrleansDashboard/blob/master/OrleansDashboard/Implementation/GrainProfilerFilter.cs) measures grain method execution time, for example.

**Comment by pipermatt** [comment]
You can also use [IOutgoingGrainCallFilter](https://dotnet.github.io/orleans/docs/grains/interceptors.html#ordering-of-grain-call-filters) on the client-side to measure from the caller.

**Comment by turowicz** [comment]
Thank you guys I will look into this!
