### ISSUE TITLE
Orleans silos crashing 'Process is terminating due to StackOverflowException.'

### ISSUE THREAD

**Issue by Tusharknath1** [dotnet/orleans#7289]
Orleans Silo is getting crashed
Console App - netcoreapp2.2
Orleans Silo - Packages
Microsoft.Orleans.Clustering.AdoNet ="3.4.2" 
Microsoft.Orleans.OrleansTelemetryConsumers.Counters ="3.4.2"
Microsoft.Orleans.Persistence.AdoNet ="3.4.2" 
Microsoft.Orleans.Server ="3.4.2" 
Microsoft.Orleans.CodeGenerator.MSBuild = 2.3.5
Microsoft.Orleans.Core.Abstractions = 2.3.5
Server - C5xLarge AWS 

CPU and memory is exceeding not more then 60 %. Around 300+ clients for the silo.
Could you please help me on it ?

**Comment by Tusharknath1** [comment]
Any idea what i am doing wrong here ?


public static ISiloHost silo;

        public static async Task<ISiloHost> Start()
        {
            var builder = new SiloHostBuilder()
                .Configure<ClusterOptions>(options =>
                 {
                     options.ClusterId = "Silo";
                     options.ServiceId = "ProcessorSilo";
                 })
                 .UseDashboard(options =>
                 {
                     options.Username = "ttttt";
                     options.Password = "ttttt";
                     options.Host = "*";
                     options.Port = 8080;
                     options.HostSelf = true;
                 })
                 .UseAdoNetClustering(option =>
                 {
                     option.ConnectionString = DBConnectionString; 
                     option.Invariant = "System.Data.SqlClient";
                 })
                 .ConfigureEndpoints(IPAddress.Parse(127.0.0.1), siloPort: 11111, gatewayPort: 50000, listenOnAnyHostAddress: true)
                 .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(CLASSNAME).Assembly).WithReferences())
                 .UsePerfCounterEnvironmentStatistics()
                 .UseDashboard(options => { })
                 .AddAdoNetGrainStorage("MessageStore", options =>
                 {
                     options.Invariant = "System.Data.SqlClient";
                     options.ConnectionString = AppSettings.OrleansConnectionString;
                 });

            silo = builder.Build();

            await silo.StartAsync();
            return silo;
        }

**Comment by ReubenBond** [comment]
A stack trace is the most expedient way to discover the source of the problem, so please try to follow the instructions outlined above (set the env var, collect the crash dump, analyze it using a debugger)
