### ISSUE TITLE
Question: How to extract data for reporting

### ISSUE THREAD

**Issue by gprossliner** [dotnet/orleans#7292]
Hi Folks!

Orleans seems to be great for any kind of Transaction-Processing: For hot data you never have to hit slow storage, you structure the data within the Grains as it is best for processing. No need to build complex DB style queries. Keeping all data for reporting within the Grain state seems to be a pretty awful idea, including historical data not needed for the processing itself. You also want to control the DB Schema, and don't use the generic DB Schema from Orleans to directly run any queries.

Are there any best practices how to implement this? Should this just be a part of eachs Grain implementation? Would it be a good idea to use a Stream for individual events of data change? Should I look into features like Interceptors or Journaling for this?

Thanks

**Comment by ReubenBond** [comment]
Hi @gprossliner, some internal services write events to an external stream for auditing/reporting purposes.
I would probably make this a part of each grain's implementation. Another alternative is to use event sourcing (the pattern, not necessarily the Orleans.EventSourcing library) and emit events that can be analyzed by a report generation service.

Members of the community might have other ideas or experiences to share
