### ISSUE TITLE
Contribution idea: Orleans backplane for SignalR

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#73]
Take OrleansR by @richorama - https://github.com/OrleansContrib/OrleansR and develop it into a robust feature. Or redo it from scratch differently if there is a better idea.

**Comment by veikkoeeva** [comment]
Contemplating a bit here:
* Create a distributed cache in Orleans, akin to Redis, and use that as a backplane like Redis is used now. This would create a sort of general purpose distributed cache component on Orleans.
* Do some work to facilitate purpose-built solutions such example code, example patterns or something like that.

I'm not sure if it's possible to do a general SignalR backplane that plays well with Orleans. I may be off here as I don't have much experience with SignalR, but I have a feeling it's too easy to broadcast all data to all nodes when it's not desired and some kind of a *routing table* approach would be nice and a away of managing sessions.

As for more context, I was initially thinking this as it would be nice to avoind taking a dependency on Redis if there's Orleans already, also it isn't always that smart to run everthing through either a database or a Azure Queue.

**Comment by richorama** [comment]
I suggest a good place to start is benchmarking this implementation against the other backplane options. Redis is fast, and it's hard to advocate other technologies unless there are compelling reasons.

Perhaps we need to engage the SignalR team and see where their thoughts are regarding backplanes?

@davidfowl @DamianEdwards ?

**Comment by veikkoeeva** [comment]
@richorama Sorry for the delay, this year's winter flu really drained my energy...

Maybe we should asses on how to play on the strenghts of the Orleans framework. One is that Orleans is already a cluster that can span multiple servers. The the grains that participate in the communication chain that eventually goes to SignalR connected clients can selectively support persistence and message distribution.

The general idea could be that the ``Hubs`` in another servers would accept clients and pass their connection parameters to special grains, ``SignalRGrains`` in the Orleans cluster. These grains in turn would keep count on in which external hub which client is and upon receiving a message from some grain, would also know to which hub to send the message. Doing like this, looks like, would be like the [high-frequence SignalR example](http://www.asp.net/signalr/overview/getting-started/tutorial-high-frequency-realtime-with-signalr)  example.

Connecting to these hubs could be via

* SignalR proxy, like in the [GPSTracker example](https://github.com/dotnet/orleans/blob/master/Samples/GPSTracker/GPSTracker.GrainImplementation/PushNotifierGrain.cs), albeit some more book keeping and most likely authentication is needed.
* The hub registers a listener and receives events
* The hub polls for events from some grain
* Would the new [Streaming Grain](https://github.com/dotnet/orleans/blob/master/src/TestGrains/SampleStreamingGrain.cs) work here? I don't know if the streams can reach outside of Orleans cluster.

Some ideas and food for thoughts...

**Comment by gabikliot** [comment]
Streams can work outside silos, yes. Exactly the same observer/observable model works both inside grains and on the client. This is fully implemented and working for both SMS streams (streams over TCP) and for Azure Queue based streams.

**Comment by ReubenBond** [comment]
Closing this, since we aren't planning on having anything in-box to do this at this point in time. Note also that there is https://github.com/OrleansContrib/SignalR.Orleans, which is active, and https://github.com/OrleansContrib/Orleans.AspNetCore.SignalR (unsure about the last one). Teams within Microsoft also use Orleans as a kind of backplane for SignalR, but not through any purpose-built SignalR or Orleans feature.
