### ISSUE TITLE
Leveraging smart cache use case. Grain calls are slow

### ISSUE THREAD

**Issue by forik** [dotnet/orleans#7301]
I have a cluster of 3 silos where 2 of them intend to work with the same data, so I decided to put some common data into orleans grains to avoid database calls. I have two types of grains (**ResourceGrain** and **AddressGrain** for reference) which holds these common data, they are pretty simple: they load data during activation and the methods are basically getters and setters except one method on **AddressGrain** which reloads some piece of state from db (this one is not being invoked for now so won't be taken into account).
**ResourceGrain** was marked as **Reentrant**, but I suppose it doesn't matter as the methods don't await anything.
My intention was that getting data from **ResourceGrain** should be fast (milliseconds at most considering serialization costs), but on practice a latency could be as much as few seconds. Even if process CPU not getting higher than 10%

ResourceGrain and AddressGrain are being identified by Guid.

Setup: 3 aspnet core apps with orleans co-hosting. Running locally in Release mode.
Laptop: Core I7 12 logical processors, 32GB RAM.

Silo 1 fetches data from kafka and pushes to SMSStream. ProcessorGrain (has the same key as ResourceGrain) implicitly subscribes to stream and executes a message. This ProcessorGrain calls for data from different sources including ResourceGrain, database. Pushes to RabbitMq event for further processing. For each ProcessorGrain with unique key a message rate is around 1 message in 5 seconds.

Silo 2 is being subscribed to RabbitMq and proceeds messages from it also using grains (SchedulerGrain). SchedulerGrain also calls for ResourceGrain for data. Message rate here is even lower.

I keep getting warnings like this (I set message timeout to 10 seconds):

`2021-09-24 17:12:47.101 +03:00 [WRN] Response did not arrive on time in 00:00:10 for message: IsAlwaysInterleave Request S172.22.64.1:1112:370185850*grn/Emw.JuiceConnect.Api.Handlers.Orleans.ResourceTelemetryProcessingGrain/01ebf918-03cf-46d7-bff5-45d03ac4c8cc@b8566790->S172.22.64.1:1111:370185846*grn/Emw.ResourceIntegration.Grains.Resources.ResourceStateGrain/01ebf918-03cf-46d7-bff5-45d03ac4c8cc@94bef8a5 InvokeMethodRequest Emw.ResourceIntegration.GrainInterfaces.Resources.IResourceStateGrain:AddSnapshotsAsync #203581. Target History is: <S172.22.64.1:1111:370185846:*grn/Emw.ResourceIntegration.Grains.Resources.ResourceStateGrain/01ebf918-03cf-46d7-bff5-45d03ac4c8cc:@94bef8a5>. About to break its promise.`

`2021-09-24 17:12:46.980 +03:00 [WRN] Response did not arrive on time in 00:00:10 for message: IsAlwaysInterleave Request S172.22.64.1:1112:370185850*grn/Emw.JuiceConnect.Api.Handlers.Orleans.ResourceTelemetryProcessingGrain/06d2f1f6-b8ec-4c61-9541-d6008a8ec6ec@9a5f59b3->S172.22.64.1:1111:370185846*grn/Emw.ResourceIntegration.Grains.Resources.ResourceStateGrain/06d2f1f6-b8ec-4c61-9541-d6008a8ec6ec@290cc097 InvokeMethodRequest Emw.ResourceIntegration.GrainInterfaces.Resources.IResourceStateGrain:GetPreviousPowerSnapshotTimestampAsync #203613. Target History is: <S172.22.64.1:1111:370185846:*grn/Emw.ResourceIntegration.Grains.Resources.ResourceStateGrain/06d2f1f6-b8ec-4c61-9541-d6008a8ec6ec:@290cc097>. About to break its promise.`

`2021-09-24 17:12:47.037 +03:00 [WRN] Dropping expired message IsAlwaysInterleave Response S172.22.64.1:1111:370185846*grn/Emw.ResourceIntegration.Grains.Groups.AddressGrain/eb38849c-6c01-4401-9618-c6795206074b@6537ca9f->S172.22.64.1:1112:370185850*grn/Emw.JuiceConnect.Api.Handlers.Orleans.ResourceTelemetryProcessingGrain/0a9036b5-8347-48fe-bfc7-95da187ef370@48b82391 #203578 at phase "Receive"`

I don't understand why it takes so long. Maybe orleans is not a good fit for this?

**Comment by ReubenBond** [comment]
Hi @forik, based on those log messages, I would guess that you have a severe performance issue in your process. It looks like thread pool starvation, which would usually be caused by synchronous blocking (such as `task.Wait()`, `task.Result`, `Task.WaitAny(tasks)`, `Task.WaitAll(tasks)`). There is some guidance on async usage here: https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md

Are there any other log warnings? Could you upload the code somewhere, or relevant parts of the code?

**Comment by forik** [comment]
Hi @ReubenBond, thanks for quick reply. 
Blocking calls which you have mentioned would have been an easy thing to fix, but I look carefully to avoid sync over async usage. 
Probably in my workload it is better not to co host orleans with aspnet core app. I'll create another silo and offload cache grains there first and then try to create a repro.

**Comment by ReubenBond** [comment]
I think something is going away here. Unless all calls are going through one grain and there's a high load, this should not be an issue. Can you profile the code to see? Profiling should make the cause of performance issues more apparent. You could capture traces using `dotnet trace` and share them if you'd like some help analyzing them.

Could you put the code somewhere? You can share a repo with me individually or DM me on Gitter if you don't want to put it out in the open.

**Comment by forik** [comment]
@ReubenBond for now attaching orleans logs here
[silo1.txt](https://github.com/dotnet/orleans/files/7227470/silo1.txt)

[silo2.txt](https://github.com/dotnet/orleans/files/7227472/silo2.txt)
.

**Comment by forik** [comment]
Thanks for pointing to a right direction towards threadpool starvation! I implemented bulkhead mechanism using TPL Dataflow for incoming messages through kafka and used direct rpc calls to processing grains instead of fire-and-forget stream calls. I also moved silo with cache grains into a separate process. Works much better now.
