### ISSUE TITLE
Cannot find an implementation class after cluster type map refresh

### ISSUE THREAD

**Issue by TaiwanSpring** [dotnet/orleans#7313]
Hello, I have a problem is "Cannot find an implementation class" exception in heterogeneous silo
I have demo code here
[https://github.com/TaiwanSpring/OrleansIssuesDemo.git](url)

I want to start a clustering include main silo (platform x86) and two other silo (x86 & x64), then use console app create client connect to clustering.

I get "Cannot find an implementation class" exception when GetGrain() after connected 3 sec, but 
It can work after client connected long time.

I think it is type map not refresh, but I can see log "Expediting cluster type map refresh due to new silo, S127.0.0.1:10064:370606175"

By the way, it migth  throw can't find interface, grainClassNamePrefix : "X86.Grain.ServiceGrain" or grainClassNamePrefix : "X64.Grain.ServiceGrain"

Sorry about my English.

**Comment by benjaminpetit** [comment]
If your client connects to a silo before all the silos had enough time to start (or at least 1 silo of each type), it is expected.

By default the **client** will only refresh its type map once every minutes. You can configure it using `TypeManagementOptions.TypeMapRefreshInterval`, and use a smaller value
