### ISSUE TITLE
Check Actor is Idle

### ISSUE THREAD

**Issue by turowicz** [dotnet/orleans#7321]
Is it possible to tell if an Actor is idle and can process a request? Let's say I have a low priority operation in the pipeline that I only want to execute if that operation is not already running. Currently based of an Orleans Stream.

@ReubenBond @sergeybykov

**Comment by ReubenBond** [comment]
You can't do that from the outside: only grains know their own current state (i.e, it's encapsulated). You could ask the grain how busy it is, eg using an `[AlwaysInterveave]` message so that it can be invoked while another message is still being processed.

**Comment by turowicz** [comment]
So basically something like IsBusy()?
