### ISSUE TITLE
Question: Getting the reason of a deactivation

### ISSUE THREAD

**Issue by Expecho** [dotnet/orleans#7324]
When `OnDeactivateAsync` is called on a grain, is it possible to know why it got called? I would like to make a distinction whether it is caused by exceeding the idle time or if it is caused by a graceful shutdown of a silo. 

My goal is to reactivate a grain as soon as possible on a new silo after it got deactived due to a graceful shutdown of a silo. If, however, the actor got deactivated due to idle time it should *not* be activated automatically.

**Comment by ReubenBond** [comment]
@Expecho what kind of API would you like to see for this? I imagine an interface or method which a grain can implement/override which exposes the deactivation reason. As for what the deactivation reason should look like, that could either be an enum or a struct or a string or something else. A struct with an enum/string is more easily extensible in case we feel the need to expose more information, but I'm happy either way.

What we have right now is not exposed, but perhaps it's good inspiration: https://github.com/dotnet/orleans/blob/3895e070ea4b9870440a5c44eed93262923b73a5/src/Orleans.Runtime/Catalog/ActivationData.cs#L1525

Note that that's the `main` branch and looks very different to what's in the 3.x releases. I think we can find a way to offer similar functionality in 3.x, too.

**Comment by Expecho** [comment]
@ReubenBond I love what you did there in that PR, exactly what I think is needed!
