### ISSUE TITLE
Orleans.TimeoutException Service Fabric

### ISSUE THREAD

**Issue by shallowtek** [dotnet/orleans#7338]
Hello,

We had an event recently where an increase in Orleans.TimeoutExceptions across all Silo's took down all the Service Fabric nodes at the same time.

We can see these Orleans.TimeoutExceptions happening all the time. Sometimes a few here and there. Every so often we will get a spike across all Silo's and the Service Fabric Nodes go down.

Any help in where we should start looking first would be great.

A few more specifics:

1. We have a Microsoft Support ticket opened and there does not appear to be any Network or Hardware issues with Service Fabric Cluster or the Client Side Cloud Service that communicates with the Silos.
2. We still use Azure Classic Storage for registering the Silos. It appears when we do a fresh deployment we do not remove the old Silo records and not sure if this is an issue.
3. We are running Orleans Version 2.4.5 on all Orleans related packages except for Orleans.Client package which we are using 2.4.2 for some reason.
4. We have been running Orleans in Production with Service Fabric for over a year and have seen this increase spike in timeouts 5 or 6 times where Service Fabric Nodes restarted. On 2 occasions the Cluster does not seem to self heal and we are forced to swap to another region which has same deployed code and runs stable.
5. We have 9 Nodes In Service Fabric running our Silos using the Azure Virtual Machine Scaleset's.
6. We are reviewing the Silo's Metrics and Statistics to see if that can she light on problem.

Any initial thoughts would be great.

Thank You

**Comment by ReubenBond** [comment]
> Is it correct to say that if an unhandled exception is thrown on a grain that grain would time out because it needs to reactivate?

Grains act like regular C# object in that an exception does not cause the object to become unusable. I believe what's happening here is more likely that the exception was not [de]serializable and it was manifesting as timeouts.

I'll close this, but feel free to open a new one if needed.
