### ISSUE TITLE
Unable to connect to endpoint S10.240.19.35:30002:0. See InnerException

### ISSUE THREAD

**Issue by sycao5** [dotnet/orleans#7344]
`"customDimensions": {
	"KubernetesAppBuildDate": "2021-10-20T00:00:00.0000000Z",
	"KubernetesPodNamespace": "vienna-master",
	"AspNetCoreEnvironment": "master",
	"KubernetesAppBuildId": "49841821",
	"KubernetesAppBuild": "2021102042612",
	"KubernetesCluster": "vienna-test-westus2-01",
	"KubernetesAppName": "globaljobdispatcher",
	"KubernetesNodeIP": "10.240.15.103",
	"{OriginalFormat}": "Failed to GetGrain T with key ItpClusterMeta.",
	"KubernetesPodIP": "10.240.15.173",
	"KubernetesImage": "viennadroptest.azurecr.io/globaljobdispatcher:2f21c20212dc55427571d51cd744c077",
	"CalledByService": "False",
	"KubernetesNode": "aks-pool2-12720191-vmss00000h",
	"ContainerName": "globaljobdispatcher",
	"KubernetesPod": "globaljobdispatcher-7b5cbf7f76-zxl8l",
	"KubernetesApp": "globaljobdispatcher",
	"CategoryName": "Microsoft.MachineLearning.GlobalJobDispatcher.Services.GlobalDispatcher.AmlK8s.AmlK8sWorkerClient",
	"ScenarioName": "Other",
	"AzureRegion": "westus2",
	"Hostname": "globaljobdispatcher-7b5cbf7f76-zxl8l",
	"Envtype": "dev",
	"SpecApp": "globaljobdispatcher",
	"ExceptionMessage": "Unable to connect to endpoint S10.240.19.35:30002:0. See InnerException"
},`

**Comment by ReubenBond** [comment]
Hi @sycao5, I will work with you offline to resolve this. Additional logs will be necessary.
