### ISSUE TITLE
Implementing parallelism in Orleans

### ISSUE THREAD

**Issue by ffMathy** [dotnet/orleans#7368]
I have a server, and a client.

If I start up multiple servers, and then create multiple grains on the client of the same type, the load doesn't seem to redistributed across the servers.

Is this because the grains are of the same type? And if so, is it possible to distribute two instances of the same grain type across multiple servers?

**Comment by nycdotnet** [comment]
You may find this docs page useful:  https://dotnet.github.io/orleans/docs/grains/grain_placement.html
