### ISSUE TITLE
Question about READ_COMMITTED_SNAPSHOT

### ISSUE THREAD

**Issue by IlBaffo** [dotnet/orleans#7369]
> This is just a question, not a bug

Hello,
I'd like to integrate Orleans in an already existing .NET application, this application already runs on MSSQL on-premises.

Since creating an additional dedicated database would increase operational costs and `SET READ_COMMITTED_SNAPSHOT ON` (as specified in in [this file](https://github.com/dotnet/orleans/blob/main/src/AdoNet/Shared/SQLServer-Main.sql)) would probably break everything else, I'm asking: **could I deploy to production with this option disabled** (as MSSQL default value) at a performance cost or is it needed to be turned on for correctness? Is this been tested?

What kind of decrease in performance can I expect? 2/3x or 100x? I won't run a lot of grains, probably in the order of 10-50 with 2 base silos and 4-12 additional siloes for heavy cpu and untrusted code with process isolation.

Thank you in advance.

> Edit: fixed link to sql file

**Comment by ReubenBond** [comment]
Apologies for the slow response, @IlBaffo. I am not familiar enough with MSSQL itself, but some base isolation level is needed in order for everything to work correctly.

Can you set an isolation level on a per-table basis in MSSQL? If so, that may be the easiest approach.

**Comment by IlBaffo** [comment]
Sadly this is not possible because `READ_COMMITTED_SNAPSHOT [ON|OFF]` is not a separate isolation level but it is a global flag to change how the real `READ_COMMITTED` isolation level behaves for the entire database: to use row versioning instead of shared locks.
This is why it will affect every query that uses the `READ_COMMITTED` level which is the default isolation level.
https://www.mssqltips.com/sqlservertip/6368/sql-server-readcommittedsnapshot-database-option-and-read-commited-transaction-isolation-level/

While I know that this is very useful to improve performance in "queue like" tables, this will also impact other queries causing previously sequential statements to run in parallel. What I fear the most is to have hard to reproduce bugs or silent data corruption if I enable this option.

This will also increase disk I/O and memory usage for the entire application because Sql Server will begin to create row versions when concurrent transactions will access the same rows instead of making them wait with locks.

**Comment by ReubenBond** [comment]
Thanks for the information, @IlBaffo. I believe that it should be save to remove that line, given what you described. cc @veikkoeeva, what are your thoughts?

**Comment by veikkoeeva** [comment]
@ReubenBond Noted. I come to this a bit later...

**Comment by veikkoeeva** [comment]
@IlBaffo, @ReubenBond I wonder if you could test database by just setting

```
ALTER DATABASE <OrleansDatabase>
SET ALLOW_SNAPSHOT_ISOLATION ON
```

and then modify the queries Orleans uses by adding `SET TRANSACTION ISOLATION LEVEL SNAPSHOT` to them?

As far as I understand, setting `SET TRANSACTION ISOLATION LEVEL SNAPSHOT;` just enables one to use the option. The queries would still run as without snapshot isolation, but the database tables take some bytes more space and `tempdb` is used more (in SQL Server 2019 and newer [Persistent Version Store (PVS)](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/snapshot-isolation-in-sql-server)). I don't think this is well explained in official documents, but it looks to me [Implementing Snapshot or Read Committed Snapshot Isolation in SQL Server: A Guide](https://www.brentozar.com/archive/2013/01/implementing-snapshot-or-read-committed-snapshot-isolation-in-sql-server-a-guide/) by @BrentOzar explains well.

@IlBaffo You can modify the queries the way you like, Orleans minds only the parameter names and types and reads them from the table when it starts. If you now have something, maybe you can argue later for a specific database. I think if you run something valuable, you need to modify the queries for your schema, filegroups and that kind of things to get the security, disaster recovery and other things you likely need.
