### ISSUE TITLE
Microsoft.Orleans.CodeGenerator.MSBuild package is not in the CI NuGet feed

### ISSUE THREAD

**Issue by fuocor** [dotnet/orleans#7370]
The last version in the CI  feed is `3.9.9-ci.20210809.1` and everyone else is at or past `3.9.9-ci.20211030.1`.

Is there a reason for this?

**Comment by ReubenBond** [comment]
The .MSBuild package is no longer being published: it was replaced by the C# source generator in v7.0+ - use Microsoft.Orleans.Sdk
