### ISSUE TITLE
Is Microsoft Orleans supported in Azure Container Apps?

### ISSUE THREAD

**Issue by jhedt** [dotnet/orleans#7373]
Link to issue raised on Azure Container App repo
https://github.com/microsoft/azure-container-apps/issues/5#issue-1043687953

**Comment by christiansparre** [comment]
I have made a small sample showing that it works here https://github.com/christiansparre/HelloContainerApps

It is currently deployed to: https://spio-hello-aca4-client.orangegrass-26d615b9.northeurope.azurecontainerapps.io/

I'll probably delete it shortly as to not burn through all my Azure credits :)

**Comment by bradygaster** [comment]
Also worked up a sample of this that you can clone and setup using `setup.ps1` as long as you have the Azure Container Apps CLI extension installed. 

https://github.com/bradygaster/OrleansOnAzureContainerApps

Closing this issue for now, but we'll be working with the ACA team on improving this experience so please leave comments as you try it out.

**Comment by ReubenBond** [comment]
We have docs for this now: https://learn.microsoft.com/en-us/dotnet/orleans/deployment/deploy-to-azure-container-apps
