### ISSUE TITLE
Key of grain when it is activated by reminder

### ISSUE THREAD

**Issue by wangjia184** [dotnet/orleans#7377]
As the [doc ](https://dotnet.github.io/orleans/docs/grains/timers_and_reminders.html)explains

> - If a grain has no activation associated with it when a reminder ticks, the grain will be created. If an activation becomes idle and is deactivated, a reminder associated with the same grain will reactivate the grain when it ticks next.
> - Reminders are associated with a grain, not any specific activation.

So there could be two different grain activations.
First when `RegisterOrUpdateReminder` is called within an activation of grain, and later `ReceiveReminder` is fired within an activation of grain.

The grain key of both activations are the same?
Or in another words,  is `ReceiveReminder` always fired in the grain with same key which called `RegisterOrUpdateReminder`?

Currently I am using the following code, unsure if that is nessesary.

```
        public async Task ReceiveReminder(string reminderName, TickStatus status)
        {
            if( reminderName != null && reminderName.StartsWith(REMINDER_PREFIX, StringComparison.CurrentCultureIgnoreCase) )
            {
                if( long.TryParse( reminderName.Substring(REMINDER_PREFIX.Length), out long id))
                {
                    if( _id == id) // same activation
                    {
                        await this.Award();
                    }
                    else  // ReceiveReminder is fired in a different activation
                    {
                        var grain = _grainFactory.GetGrain<IMyGrain>(id);
                        await grain.Award();
                    }
                    return;
                }
            }
            else
            {
                _logger.LogWarning("Unrecognizable reminder name {0} in {1}", reminderName, this.GetType().Name);
            }
        }
```

**Comment by nkosi23** [comment]
Yes your reminder will only be called for the grain having the same key so your `_id == id` check is not necessary. If you have a grain type `IMyGrainType` and two instances of that type having respectively the ids `myGrainKey1` and `myGrainKey2` if you set up a reminder for `myGrainKey1` this reminder will only be called for `myGrainKey1`. You would need to setup an additional reminder for `myGrainKey2`. So there is no risk that `myGrainKey2` receives a reminder tick intended for `myGrainKey1`.
