### ISSUE TITLE
Is it intended that the latest version of Orleans (3.5.1) throws a SerializationException when an object doesn't have the [Serializable] attribute?

### ISSUE THREAD

**Issue by SeppPenner** [dotnet/orleans#7381]
Is it intended that the latest version of Orleans (3.5.1) throws a SerializationException when an object doesn't have the [Serializable] attribute or am I doing something wrong?

I would have looked into the changelog, but there is not yet an entry: https://github.com/dotnet/orleans/blob/main/changelog.md 😅 

EDIT: `EnableUnsafeBinaryFormatterSerialization` is set to `true` in our case.

**Comment by ReubenBond** [comment]
Basically, yes. Orleans will detect classes which appear in grain interface calls (methods params or return types) and a few other places and generate serializers for them. It will not search the type hierarchy, though (eg, if you have `object` as a method param, Orleans wont start generating a serializer for every possible type).

`[Serializable]` tells the code generator that you intend to serialize a given type, so Orleans will generate a serializer for it.

**Comment by SeppPenner** [comment]
Setting `EnableUnsafeBinaryFormatterSerialization` to `false` fixes this. I have no idea why it was set either (There might have been some issues without it in a prior version that is now fixed).
