### ISSUE TITLE
[Question] Is there a way to disable client connections to silo hosts with orleans server endpoint configuration?

### ISSUE THREAD

**Issue by modabas** [dotnet/orleans#7389]
For some cases, like when silo hosts only process messages from message broker or like when grpc/web api service is hosted in same generic host with orleans silo, i don't need a gateway port to listen to client connections, and would like to disable it completely to reduce attack surface.

Is there a way to configure silo host so that it will not accept client connections?

**Comment by benjaminpetit** [comment]
If you set `EndpointOptions.GatewayPort` to `0` then the gateway will be disabled
