### ISSUE TITLE
This latest lock free implementation can be applied to Orleans

### ISSUE THREAD

**Issue by u-less** [dotnet/orleans#7392]
https://github.com/dotnet/aspnetcore/blob/main/src/Servers/Kestrel/Transport.Sockets/src/Internal/IOQueue.cs

https://github.com/dotnet/orleans/blob/main/src/Orleans.Core/Networking/Shared/IOQueue.cs

**Comment by ReubenBond** [comment]
@u-less this issue makes sense to me - we should port the changes over. Would you be willing to open a PR?
