### ISSUE TITLE
Starting transactions from non-statelessworker grains throws lock timeout exception a lot

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [dotnet/orleans#7393]
I have a grain which manages purchases and even when it is not busy if i start a transaction from it I get this exception 

`aborted because a broken lock was detected, before prepare`

I have PurchaseManager which calls OrderList and OrderUserList 
If I make PurchaseManager a stateless workder (like your accounting sample) then everything works but if it is not the case then I get the exception above 4 times out of 5 despite the fact that I'm running locally and there is no load on the system.

I'm using Memory storage for the locally running system if that matters and am not pausing under any breakpoints or anything else either.

**Comment by ashkan-saeedi-mazdeh** [comment]
@jsteinich  Neither the docs nor the sample don't do that. I saw another issue you and others were discussing this however. Are you sure about this, did Reuben or any other person in the Orleans team confirm this?

I can update the docs if this is the case.

**Comment by jsteinich** [comment]
The most confirmation I've seen is https://github.com/dotnet/orleans/issues/5644#issuecomment-502803583

**Comment by ashkan-saeedi-mazdeh** [comment]
@sebastianburckhardt  or @ReubenBond  Can you guys confirm that this is the case?
Should I update samples and docs or you guys are going to make this automatic so every transactional grain is reentrant? 

but not knowing how transactions exactly work now this doesn't make much sense that stateless workers work because this is the first call to the said grain which I modified to be stateless worker which failed before.
the other grains participating in the transaction were being called before this from the client but this specific `PurchaseManager` grain was failing even in its first call IIRC.

**Comment by jsteinich** [comment]
@ashkan-saeedi-mazdeh can you please elaborate some on the flow?
I gather that you have a method in `PurchaseManager` with the create transaction attribute and that it calls 2 other grain's methods that have a join transaction attribute. Is that correct?
Is the order of the other grain calls fixed?
Are you starting more than one purchase?

**Comment by ashkan-saeedi-mazdeh** [comment]
@jsteinich  All correct. the order is fixed and I only have the single purchase that I call when running locally in debug mode and that fails more often than not if `PurchaseManager` is not a stateless worker.

**Comment by jsteinich** [comment]
@ashkan-saeedi-mazdeh is the `PurchasManager` itself using `ITransactionalState`? Are there multiple `PerformRead` or `PerformUpdate` blocks within a single grain method?

**Comment by ashkan-saeedi-mazdeh** [comment]
@jsteinich  No is the answer to both.

**Comment by HermesNew** [comment]
Any grain used with transactions needs to be reentrant.
This is the correct way.



> Any grain used with transactions needs to be reentrant (or at least interleaving methods). That would be the first thing I'd double check as it is easily missed.

**Comment by HermesNew** [comment]
@jsteinich You are right.I did the same.

**Comment by ashkan-saeedi-mazdeh** [comment]
@HermesNew  What is your source of this information?

**Comment by ashkan-saeedi-mazdeh** [comment]
Guys Reuben told me the same thing. Thanks for your help and will try to update Orleans docs as soon as I can too.
