### ISSUE TITLE
[Documentation] Description of call chain reentrancy is missing

### ISSUE THREAD

**Issue by f-i-x-7** [dotnet/orleans#7397]
[Official docs](https://dotnet.github.io/orleans/docs/grains/reentrancy.html) are not saying anything regarding grains call chain reentrancy. I've found this information only in [obsolete docs for one of the previous versions of Orleans](http://sergeybykov.github.io/orleans/Documentation/grains/reentrancy.html#reentrancy-within-a-call-chain).

Could you please update the official docs to include this information? Of course, something may have been changed since the previous version of Orleans; so it is possible that description of call chain reentrancy should be updated before inlcusion to modern docs.

If you could confirm that old description is still relevant, then I could possibly update docs by myself (if it is possible for contributors).

P.S. Also IMHO it is worth to mention explicitly that call chain reentrancy is not allowed from grain OnActivateAsync() method (as well as any other reentrancy).

**Comment by benjaminpetit** [comment]
`SchedulingOptions.AllowCallChainReentrancy` is still there on 3.x, but was removed in main... Maybe we will need to have two separate docs, one for 3.x, one for main

**Comment by f-i-x-7** [comment]
Does this mean that call chain reentrancy will be prohibited in new versions of Orleans (e.g. in 4.x)?

**Comment by ReubenBond** [comment]
This is documented now: https://learn.microsoft.com/en-us/dotnet/orleans/grains/request-scheduling#call-chain-reentrancy
