### ISSUE TITLE
Doubt in Co-Hosting ASP.NET and Orleans

### ISSUE THREAD

**Issue by shyamsundarb-arch** [dotnet/orleans#7401]
In a co-hosting Orleans and ASP.NET, assuming I have hosted the application in multiple nodes. Should I place all my nodes behind a Load Balancer to distribute traffic to each silo/node? Or is there no need to put up an Load Balancer for distributing HTTP load among all the silos/nodes?

I am fairly new to Orleans, kindly guide me if my fundamental understanding is wrong.

**Comment by SebastianStehle** [comment]
Yes, you should put your nodes behind a load balancer. 
 There are 2 main reasons for that:
 
1. Availability: If you have only one HTTP server your users will loose access to your backend if this server goes down. Even if it gets restarted after a few minutes, you don't want this.

2. Your requests have many steps: JSON deserialization -> Orleans stuff -> JSON serialization (and many more). If you have only one server act as HTTP gateway you cannot scale the JSON / API stuff.

**Comment by shyamsundarb-arch** [comment]
> Yes, you should put your nodes behind a load balancer. 
> 
>  There are 2 main reasons for that:
> 
>  
> 
> 1. Availability: If you have only one HTTP server your users will loose access to your backend if this server goes down. Even if it gets restarted after a few minutes, you don't want this.
> 
> 
> 
> 2. Your requests have many steps: JSON deserialization -> Orleans stuff -> JSON serialization (and many more). If you have only one server act as HTTP gateway you cannot scale the JSON / API stuff.

Thank you for the prompt reply. A small top up question is, does this mean when the ASP.NET controller invokes a GetGrain request, the grain gets created only in the node in which the controller received the request in? Or can it get created in any silo/node in the cluster?

**Comment by SebastianStehle** [comment]
> Thank you for the prompt reply. A small top up question is, does this mean when the ASP.NET controller invokes a GetGrain request, the grain gets created only in the node in which the controller received the request in? Or can it get created in any silo/node in the cluster?

Usually it is the same node, but if the grain already exists on another node or if you have a custom placement logic (it decides where grains will be created) it can also be another node.
