### ISSUE TITLE
[Question] About sample application showcased on dotnetconf

### ISSUE THREAD

**Issue by modabas** [dotnet/orleans#7403]
Hello,

Is the [application that was showcased on Dotnetconf](https://www.youtube.com/watch?v=wYXSZ9VAQCM) by @ReubenBond available online? I think it was a variation of Voting application in orleans samples, but had a blazor frontend co-hosted with orleans in same generic host and had realtime poll result watchers (observers?)

**Comment by ReubenBond** [comment]
The sample is in this branch here: https://github.com/ReubenBond/orleans/commit/90762e243770ebe0b61b307d40a606f3cf489644
