### ISSUE TITLE
LogStorage.LogConsistencyProvider  (ADO NET) does not work

### ISSUE THREAD

**Issue by sanzor** [dotnet/orleans#7404]
I am trying to understand how to use the Orleans.EventSourcing.LogStorage.LogConsistencyProvider with JournaledGrains having an ADO Net storage  and i find no refrence besides [this](https://dotnet.github.io/orleans/docs/grains/event_sourcing/log_consistency_providers.html).

I keep getting this error , the debugger not even entering inside the grain method:

**Exception**
```
fail: Orleans.LifecycleSubject[100450]
      Lifecycle start canceled due to errors at stage 1000: Orleans.Storage.BadGrainStorageConfigException: No default storage provider found loading grain type Notification.WebApi.PaymentGrain.
         at Orleans.Storage.GrainStorageExtensions.ThrowMissingProviderException(Type grainType, String name)
         at Orleans.Storage.GrainStorageExtensions.GetGrainStorage(Type grainType, IServiceProvider services)
         at Orleans.Storage.GrainStorageExtensions.GetGrainStorage(Grain grain, IServiceProvider services)
         at Orleans.LogConsistency.LogConsistentGrain`1.OnSetupState(CancellationToken ct)
         at Orleans.LifecycleExtensions.Observer.OnStart(CancellationToken ct)
         at Orleans.LifecycleSubject.<OnStart>g__CallOnStart|7_0(OrderedObserver observer, CancellationToken cancellationToken)
      --- End of stack trace from previous location where exception was thrown ---
         at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
fail: Orleans.Runtime.Catalog[100513]
      Error calling grain's OnActivateAsync() method - Grain type = Notification.WebApi.PaymentGrain Activation = [Activation: S127.0.0.1:11111:375351297*grn/BD1F8C1D/1@2ee6739a #GrainType=Notification.WebApi.PaymentGrain Placement=RandomPlacement State=Activating]
```

**Scenario:**
All my events have a value that must be appeneded to a list in the state.There is no complex state business logic.I do not need to use snapshots , i can retrieve the confirmed events from the log storage and just recreate the state.

I have tried configuring the silo like this:

**Silo configuration**
```
IHostBuilder host = CreateHostBuilder(args);
            host.UseOrleans(builder =>
            {
                builder
                .UseLocalhostClustering()
                .Configure<EndpointOptions>(opt =>
                {
                    opt.AdvertisedIPAddress = System.Net.IPAddress.Loopback;
                })
                .AddLogStorageBasedLogConsistencyProvider()
                .Configure<ClusterOptions>(options =>
                    {
                        options.ClusterId = "mycluster";
                        options.ServiceId = "myservice";
                    })
                .ConfigureApplicationParts(parts =>
                {
                    parts.AddFromApplicationBaseDirectory();
                })
                .AddAdoNetGrainStorage("LogStorage", (opt) =>
                {
                    opt.ConnectionString = @"Server=AdrianB-LAPTOP;Integrated Security=true;Database=LogStorage";
                    opt.Invariant = "System.Data.SqlClient";
                });
            });
```
I do not understand ,do  i have to run a script and have a database prepared for this , and  how and where do i tell Orleans to use that target database.

**Interface**
```
public interface IPayment
{
      public async Task AddValue(SomeEvent ev);
}
```

**Event**
```
public class SomeEvent
{
      public int Value{get;set;}
}
```

**State**
```
public class SomeState
{
   public long Id{get;set;}
    public List<int> Values=new List<int>();
   public void Apply(SomeEvent ev)
  {
       this.Values.Add(ev.Value);
  }
}

**Snapshot**
```
public class Snapshot
{
    public string Value {get;set;}
    public long Id{get;set;} 
}
```

**JournaledGrain**

```
 [LogConsistencyProvider(ProviderName = "LogStorage")]
 public class PaymentGrain : JournaledGrain<SomeState, SomeEvent>,IPayment
{
     public async Task AddValue(SomeEvent ev)
     {
            this.RaiseEvent(ev);
            this.ConfirmEvents();
     } 
     protected override void OnStateChanged()
        {
            using SqlConnection con = new SqlConnection(CONNECTION);
            var snapshot= new Snapshot
            {
                Value = JsonSerializer.Serialize(this.State),
                PaymentId = this.State.Id
            };
            con.Execute("INSERT into State", state);
            //write state to db
            base.OnStateChanged();
        }
}
```

**Comment by benjaminpetit** [comment]
You also need to configure a storage provider as "default"
