### ISSUE TITLE
How to ensure write state and publish message to stream consistent? 

### ISSUE THREAD

**Issue by zh6335901** [dotnet/orleans#7407]
I wonder if there has some way to ensure write state and publish message to stream consistent? Maybe like the outbox pattern.
For example, I have a `OrderGrain` that has a `PlaceOrder` method. In the `PlaceOrder` method, If place order is successful, It would write order state to storage and publish the `PlaceSucceed` message to stream. How to ensure these two operations both successful or failed?

**Comment by HermesNew** [comment]
Use orleans transaction to ensure these two operations both successful or failed.

**Comment by zh6335901** [comment]
> Use orleans transaction to ensure these two operations both successful or failed.
Thank for you reply, I am not very familiar with Orleans Transaction, But i think it has some drawbacks:
1. Orleans Transaction only support few of storage now.
2. Orleans Transaction does not support publish message to stream directly. To use it, I must create a grain for publish message to stream, I think it is a bit heavy.

**Comment by HermesNew** [comment]
You can implement custom transaction storage.Use orleans transactions to solve the success or failure of multiple operations.

**Comment by HermesNew** [comment]
[https://github.com/dotnet/orleans/tree/main/samples/BankAccount](BankAccount - ACID transactions between grains sample)

**Comment by HermesNew** [comment]
BankAccount - ACID transactions between grains sample
https://github.com/dotnet/orleans/tree/main/samples/BankAccount

**Comment by zh6335901** [comment]
> You can implement custom transaction storage.Use orleans transactions to solve the success or failure of multiple operations.

I know it can implement custom transaction storage. But i think it is heavy, So i'm finding a way that can ensure these ops both successful or failed in  same grain.

**Comment by zh6335901** [comment]
Finally, I implemented it:
1. Write state and events or messages to store together
2. Use timer to publish the events or messages to stream
3. Use reminder to ensure event will published eventually

Code is [here](https://github.com/zh6335901/Orleans.EventuousGrains/blob/main/src/Orleans.EventuousGrains/EventuousGrain.cs)

But i think it also have some drawbacks:
1. The times of write storage increased, At most double
2. The reminder would affect grain's deactivation

@ReubenBond @benjaminpetit Can you give me some suggestions or ideas improve please? thx
