### ISSUE TITLE
Accessing GrainFactory from IBootstrapProvider in 1.0.9.

### ISSUE THREAD

**Issue by philreindl** [dotnet/orleans#741]
I have been working through the process of upgrading to orleans 1.0.9 from 1.0.8.  We have some code that implements IBootstrapProvider, which is used to load some starting data into the system at startup.  
Before: 
`var cropGrain = GrainFactory.GetGrain<ICrop>(crop.CropId); `

After:
`var cropGrain = GrainClient.GrainFactory.GetGrain<ICrop>(crop.CropId);`

This was working fine in 1.0.8.  Now, the calls to get grain references from the GrainFactory are failing due to the GrainClient not being initialized.  Since this code is running on the Silo, I wouldn't expect to need to configure a client.  Attempts to do so have failed.

Are there any examples of how to properly interact with grains in the bootstrap providers, which are set up to be deployed on Azure?  

Thanks
Phil

**Comment by gabikliot** [comment]
The `GrainFactory` is available via a member field in `IProviderRuntime` that is passed to `IBootstrapProvider.Init()`.

**Comment by philreindl** [comment]
So it is.  Thanks for getting me straightened out!
