### ISSUE TITLE
Discord Button in README.md doesnt link to Discord

### ISSUE THREAD

**Issue by mikecann** [dotnet/orleans#7412]
As the title of this issue suggests, clicking the discord button just opens the image not the Discord server. I have Googled it but cant find where the URL to the discord server is supposed to be...

**Comment by ReubenBond** [comment]
Thanks for pointing that out, @mikecann. I thought I tested it, but here we are. I'll fix that ASAP and in the meantime, the discord server is accessible via https://aka.ms/orleans-discord

**Comment by mikecann** [comment]
Oh lol :P I just found the URL and submitted a PR: https://github.com/dotnet/orleans/pull/7414 I guess you beat me to it, ill ddelete that PR :P
