### ISSUE TITLE
[Test] Doubts in this PR (#6416)

### ISSUE THREAD

**Issue by DarknessChen** [dotnet/orleans#7420]
As for this issue: https://github.com/dotnet/orleans/issues/6416, when clearing the queue, why did we get a 404 in response?

The `ClearAsync()` SDK API call is to clear the messages in the queue, so I think that even if the clearing succeeds, the queue should still be there instead of being gone, right? I have tried to reproduce this scenario but failed. Since I have no access to the example run, could someone kindly provide more information about it (like which test case causes this bug)?  

Also, after checking the `Clear Messages` in the [REST API doc](https://docs.microsoft.com/en-us/rest/api/storageservices/clear-messages#remarks), it says when dealing with large files and timeout happens, "the Queue service will return status code 500 with the additional error code OperationTimedOut". So are we supposed to deal with the 500 (e.g., doing more retries)? and 409 [(QueueBeingDeleted)](https://docs.microsoft.com/en-us/rest/api/storageservices/queue-service-error-codes).

**Comment by benjaminpetit** [comment]
> The ClearAsync() SDK API call is to clear the messages in the queue, so I think that even if the clearing succeeds, the queue should still be there instead of being gone, right?

You are right, the queue should still be there. But we do manually delete the queues in some tests. I wonder if it was just a race condition in the `Dispose` methods in test classes.

> I have tried to reproduce this scenario but failed. Since I have no access to the example run, could someone kindly provide more information about it (like which test case causes this bug)?

Unfortunately, the build is gone now, so I can't find any logs.

I wouldn't worry about it anyway, since this code is only used in tests.
