### ISSUE TITLE
Some loggers don't respect logging configuration.

### ISSUE THREAD

**Issue by chillitom** [dotnet/orleans#7421]
A few of Orleans' loggers don't obey regular _aspnet_ log configuration e.g. `app.settings`.

Examples: `Orleans.Messaging.GatewayManager`,  `Orleans.Runtime.ClientLogStatistics` and  `Orleans.Runtime.SiloLogStatistics` 

Setting them to LogLevel.Warning and disabling colours has no effect.  

Others have experienced this in the past: https://github.com/dotnet/orleans/issues/7030#issuecomment-827915480

Is there something particular about the stage at which these components are configured?  Could more than one logger factory be being created somehow?

**Comment by ReubenBond** [comment]
@chillitom Can you create a repro for this or show how you're configuring Orleans?
I'm especially interested in how appsettings.json is being propagated to the DI container which Orleans exists in

**Comment by chillitom** [comment]
https://github.com/chillitom/LoggingRepro -- here's a minimal repro, you can see the issue in the client process where _Orleans.Messaging.GatewayManager_ and _Orleans.Runtime.ClientLogStatistics_ are logged at info level despite being set to log at _Warning_

**Comment by ReubenBond** [comment]
@chillitom I believe what's going on here is that you're trying to configure logging using appsettings.json, but the ClientBuilder simply doesn't read from there by default: it doesn't read config from anywhere by default.
Your two options are:
1. Explicitly add JSON config from appsettings.json to the client builder
2. Programmatically configure log levels on the client builder, rather than in appsettings.json

**Comment by chillitom** [comment]
@ReubenBond thanks for responding, based on your comment I found and fixed the issue.  It appears there was an extra call to `clientBuilder.ConfigureLogging(logging => logging.AddConsole());` which was overriding the default logging configuration. 

I wonder if this appears in an example somewhere, that might explain a few people experiencing this.

**Comment by ReubenBond** [comment]
@chillitom the client has its own dependency injection container, so you need to configure logging twice
