### ISSUE TITLE
Multi region k8s hosting

### ISSUE THREAD

**Issue by aczarkowski** [dotnet/orleans#7430]
We are evaluating Orleans to use it to run a number of orchestrations in the system we are building.

All our services are deployed to 2 Azure regions (UK South and UK West) and hosted on AKS (2 AKS clusters). What is the appropriate way of deploying Orleans cluster that needs to span across 2 Azure regions? 

We were thinking that for all the silos to see each other across regions we could do a vnet peering.

I looked at Orleans.Hosting.Kubernetes but that does not look like a proper solution for that kind of scenario or perhaps I am missing something.

I would much appreciate for any help on that.

**Comment by drub0y** [comment]
I believe you're looking for multi-clustering and you can [check out the docs on that here](https://dotnet.github.io/orleans/docs/deployment/multi-cluster_support/Overview.html).

**Comment by aczarkowski** [comment]
Thanks. I looked at this already but according to https://github.com/dotnet/orleans/issues/6548 multi clustering has been removed.

**Comment by ReubenBond** [comment]
We cut multiclustering from Orleans and are considering bringing it back in a different form.
I generally recommend keeping clusters in each region separate, maybe all talking to a database which spans regions, and having a front-door type of service to select the correct region for a connection/request. [This paper](https://arxiv.org/ftp/arxiv/papers/2105/2105.00560.pdf) depicts something similar:
![image](https://user-images.githubusercontent.com/203839/146208958-3fe6f112-034f-45b7-a213-03ffefdac840.png)

That being said, you can create Orleans clusters which span geographies, we just don't recommend it.

**Comment by drub0y** [comment]
Would a PR to remove it from the docs be welcomed then?

**Comment by ReubenBond** [comment]
Yes, thank you

**Comment by aczarkowski** [comment]
Thank you for all the answers. Much appreciated. Btw. I hope Orleans becomes a more prominent product as it's such a little gem that it's not really well known.
