### ISSUE TITLE
DynamoDB Reminders GSI not used

### ISSUE THREAD

**Issue by michaeltdaniels** [dotnet/orleans#7434]
I believe the intent is for the GSI here: https://github.com/dotnet/orleans/blob/5cd5595c84a5781306b2d1a4ada709a9daf911f8/src/AWS/Orleans.Reminders.DynamoDB/Reminders/DynamoDBReminderTable.cs#L62 to be used here: https://github.com/dotnet/orleans/blob/5cd5595c84a5781306b2d1a4ada709a9daf911f8/src/AWS/Orleans.Reminders.DynamoDB/Reminders/DynamoDBReminderTable.cs#L153

I believe that isn't happening for two reasons: first, the index name isn't being passed in, and second ConsistentRead = true is specified here https://github.com/dotnet/orleans/blob/5cd5595c84a5781306b2d1a4ada709a9daf911f8/src/AWS/Shared/Storage/DynamoDBStorage.cs#L595

GSI's do not support consistent reads (I believe the DynamoDB client would throw a ValidationException if attempted).  The result of this is that every silo ends up doing a full table scan on start (which is costly and inefficient).

**Comment by ReubenBond** [comment]
cc @galvesribeiro do you have thoughts on this issue and the accompanying PR?

**Comment by galvesribeiro** [comment]
Awesome catch! I guess I've removed it and never added it back since indeed the validation would fail.

Thanks @michaeltdaniels!
