### ISSUE TITLE
Stream behavior in crash or deployment

### ISSUE THREAD

**Issue by idanbenyehoshua** [dotnet/orleans#7445]
I am using Orleans in production for almost one year and all works for us very well.
Now we have plans to use Orleans stream capability for aggregation some data and more.
Our plan is to setup background process that pull data from some DB (once a second) and post the data to stream.
We are expecting data rate of approximate 50 (stream messages) events per second to publish.
Two things are bothers me:
1. lets say we have an stream consumer that pull the stream and from 12:00 PM to 12:01 PM the consumer can ingest/process 20 messages per second. Until consumer will be back to process in normal rate, all the event messages will be internally queued in the Silo agent ( According Orleans document). What happened to all unprocessed messages if in 12:00:50 PM the Silo that holding the cache (Silo stream), fall down due to unexpected crash or deploy? The consumer will not get these pending stream messages.
What I am missing here?
2. According Orleans document, the messages delivery to consumer is one by one. So if I have 3 consumers to one stream and rate of 50 messages per second, that means 150 IO hits per second (lets say the consumers are spreading in different machines in the cluster)?

*Stream provider: AWS SQS
Thank you!

**Comment by benjaminpetit** [comment]
I am not 100% sure on how SQS works, but I assume they are the equivalent of Azure Queues.

> 1. lets say we have an stream consumer that pull the stream and from 12:00 PM to 12:01 PM the consumer can ingest/process 20 messages per second. Until consumer will be back to process in normal rate, all the event messages will be internally queued in the Silo agent ( According Orleans document). What happened to all unprocessed messages if in 12:00:50 PM the Silo that holding the cache (Silo stream), fall down due to unexpected crash or deploy? The consumer will not get these pending stream messages.
What I am missing here?

The Pulling Agent will delete messages from SQS when they are purged from its cache. If the silo crashes, messages will not be deleted. Once a silo takes responsibility of this SQS partition, the new Pulling Agent should see this new message and try to send them again.

The only way here to lose messages is if your cache isn't configured big enough (cache is purged before a cusnsumer had time to process the events)

> 2. According Orleans document, the messages delivery to consumer is one by one. So if I have 3 consumers to one stream and rate of 50 messages per second, that means 150 IO hits per second (lets say the consumers are spreading in different machines in the cluster)?

The Pulling Agent will read once from SQS, then from memory will send them to the consumer. You will have only 50 IO/s on SQS.

I would suggest using something like Event Hub if you are concerned about reliability. This provider is far more battle tested for recovery case like this.

**Comment by idanbenyehoshua** [comment]
Thank you so much for your answer.
I'm running on AWS and as I see there is no Kinesis provider. Unfortunately Azure is not option for me. 
I'm consider to use Kafka provider( I think there is an managed service in AWS). 
Again, thank you.

**Comment by yevhen** [comment]
@benjaminpetit does azure queue provider work like this?
> The only way here to lose messages is if your cache isn't configured big enough (cache is purged before a cusnsumer had time to process the events)

my understanding was that it deletes messages from the queue only if they were successfully delivered. No?
