### ISSUE TITLE
Azure Queue Streams Improvements

### ISSUE THREAD

**Issue by Jubast** [dotnet/orleans#7448]
Would it be possible to change the `AzureStreamQueueMapper` to use the `streamNamespace` in the queue chusing algorithm?
Or support changing the azure queue stream mapper with a custom one while building the silo?

The reason for this is that we use Orleankka for CQRS / ES. Streams in Orleankka always have the `streamGuid` set to `Guid.Empty` and the `streamNamespace` is the StreamId ([Orleakka StreamRef](https://github.com/OrleansContrib/Orleankka/blob/4deb126f76439100253a0e07d3c93e5cc9002b53/Source/Orleankka/StreamRef.cs#L53)). Whatever StreamId we chose, we can never shard the load to multiple queues.

example of 200_000 streams being put on one queue:
```cs
var queueNames = new List<string>
{
	"queue-1",
	"queue-2",
	"queue-3",
};

var mapper = new AzureStreamQueueMapper(queueNames, "sms");

var hashMap = new Dictionary<string, int>();

var ids = Enumerable.Range(0, 200_000).Select(x => Guid.NewGuid().ToString());
foreach (var id in ids)
{
	var streamId = $"GameGrain-{id}-Events";
	var queue = mapper.GetQueueForStream(Guid.Empty, streamId);
	var azureQueue = mapper.PartitionToAzureQueue(queue);

	if (!hashMap.ContainsKey(azureQueue))
		hashMap[azureQueue] = 1;
	else
		hashMap[azureQueue]++;
}

foreach (var value in hashMap)
{
	System.Console.WriteLine(value);
}
```

**Comment by yevhen** [comment]
I'm eagerly awaiting Orleans 4.0 so we can finally have actor and stream ids to be just a string))

@Jubast my apologies, using stream namespace was the only option to have string id for a stream. I still don't know what was the original idea behind this concept. Neither why stream ids should be guid only 😃

**Comment by Jubast** [comment]
@yevhen no worries, no blaming is going on here 😀 sorry if it came over that way. I am just trying to find a solution for us. Is there a ETA for Orleans 4.0?

**Comment by benjaminpetit** [comment]
> Would it be possible to change the AzureStreamQueueMapper to use the streamNamespace in the queue chusing algorithm?
Or support changing the azure queue stream mapper with a custom one while building the silo?

We can't change the current algorithm for backward compatibility reason, but we could definitely make it pluggable during silo configuration.

 > Is there a ETA for Orleans 4.0?

Not yet

**Comment by yevhen** [comment]
@Jubast I think the only way to have this soon is to make a PR for current major version and then get it in a next minor release.

**Comment by Jubast** [comment]
@benjaminpetit and @yevhen thank you for the help 👍
I've presented these options to my colleagues and we've decided that the single queue works good enough for now. We will wait for Orleans 4.0.
