### ISSUE TITLE
First-class on-premise Stream Provider

### ISSUE THREAD

**Issue by turowicz** [dotnet/orleans#7450]
Dear .NET Team,

We are using Orleans in the on-premise Kubernetes clusters. The reason for this is that our clients insist on running our software (manufacturing AI) within the walls of their factories so none of their intellectual property gets lost. 

So far Orleans has been working very well in on-premise for us but we have been missing out on Persistent Streams, as it is only really available in a cloud deployment with Azure Storage Queues.

While there are some 3rd party implementations (Kafka, Redis, RabbitMq), they lack good quality of code and often miss the mark.

Would it be possible to put an on-premise Stream Provider for Orleans in the set of first-class libraries developed by the .NET team? Ideally something that is **not** a resource hog such as Kafka, more like Etcd.

PS. This has been previously highlighted in https://github.com/dotnet/orleans/issues/7271 but it was not pulled into the backlog.

**Comment by benjaminpetit** [comment]
I guess right now you could use `MemoryStreams`, but they are not really persistent...

**Comment by turowicz** [comment]
Your guess is right @benjaminpetit 

Please triage as feature request.

**Comment by rafikiassumani-msft** [comment]
@turowicz We are not planning to implement this feature in Orleans at the moment.

**Comment by turowicz** [comment]
That's very unkubernetesy

**Comment by ReubenBond** [comment]
If you have a target backend system in mind, you could build a provider for it and release it, or improve the other providers which you mentioned as lacking.

I wouldn't recommend etcd for this, since it was designed as an unpartitioned metadata store (low volumes of data, generally low update rate). NATS may be more appropriate.

**Comment by turowicz** [comment]
@ReubenBond thanks for suggesting NATS, it looks like a good candidate.

RE etcd, have you seen this? https://www.cncf.io/blog/2019/05/09/performance-optimization-of-etcd-in-web-scale-data-scenario/

**Comment by ReubenBond** [comment]
A NATS provider would be a great addition, I think

**Comment by turowicz** [comment]
It looks like I have no choice but to implement it. How should I go about making sure it goes in the Contrib?

**Comment by turowicz** [comment]
@ReubenBond do you know how NATS compares to Etcd in terms of key-value storage? I need something that can run on small arm devices and basically be a layer over the filesystem. Etcd has delivered on this promise except for some reason its caches grow exponentionally high at times.

**Comment by ReubenBond** [comment]
> How should I go about making sure it goes in the Contrib?

Coordinate with the community in the #development channel in [Discord](https://aka.ms/orleans-discord).

> do you know how NATS compares to Etcd in terms of key-value storage? 

It's not built for it - I was suggesting NATS for a stream provider, not KV storage.
If the goal is to run on small devices, maybe these kinds of systems aren't ideal. They're mostly built for clusters of servers. Do you need something replicated/resilient? If not, maybe use SQLite for everything and store data locally.

**Comment by turowicz** [comment]
Actually Etcd works pretty well for me in single instance with low resources. I was thinking if I could swap it with NATS as it also has queues (similar to azure storage). I'm fine with spinning up NATS aside of Etcd, but it would save me CPUs if I didn't need two systems.

That said, we also have massive clusters (100s of CPUs & tons of RAM), but our solution runs on a wide variety of hardware.

**Comment by ReubenBond** [comment]
To clarify what that blog post says, etcd is used for storing metadata/specs/status, but not application state. Small, low velocity data. If it meets your needs, then by all means go for it.

**Comment by turowicz** [comment]
@ReubenBond 
![image](https://user-images.githubusercontent.com/1055391/151536856-c0b1a878-fd66-440c-87e0-01d0836fe938.png)

**Comment by turowicz** [comment]
I have contacted you guys on the Discord development channel

**Comment by oising** [comment]
I've been reading about nats today and I might highlight something I found in the docs about NATS Streams (also known as "STAN"). It seems that NATS Streams is effectively a legacy product, and that future *new* streaming work with NATS should be done with NATS JetStream instead. This is fully integrated into the primary NATS product and adds incrementally more robust behaviour onto the base messaging caps, i.e. pub/sub, queues and request/reply.

**Comment by turowicz** [comment]
@oising I am well aware. This will be a JetStream integration with `Retention Policy = WorkQueuePolicy`

**Comment by turowicz** [comment]
I have halted the work on this as the .NET lib for NATS is not async-await capable, therefore it's not very feasible to use within Orleans model.

**Comment by turowicz** [comment]
https://github.com/Surveily/Orleans.Streaming.NATS

**Comment by oising** [comment]
> 

There are other unofficial - and active - libraries that are async enabled.

**Comment by turowicz** [comment]
@oising we will be circling back to this issue very soon. Good find, thanks!

**Comment by oising** [comment]
@turowicz -- having played with https://github.com/Cysharp/AlterNats for a bit, I can say it's absolutely great. They seem to have full support for rpc, pubsub and messaging (commands) -- highly optimized, supports sharded nats servers and uses modern dotnet idiomatic API design.

**Comment by oising** [comment]
Oops, they don't have Jetstream support (yet) - this would be essential for a stream provider, of course.

https://github.com/Cysharp/AlterNats/issues/5

**Comment by turowicz** [comment]
He're is an on-prem provider written by me, that is using stateful grains as queues:

https://github.com/Surveily/Orleans.Streaming.Grains
