### ISSUE TITLE
Generate code for all types in another Assembly

### ISSUE THREAD

**Issue by suixin567** [dotnet/orleans#7454]
I want to Generate code for all types in another assembly
I follow the steps of the official documentation:
    1、Create a C# project.
    2、Install the Microsoft.Orleans.CodeGenerator.MSBuild or the Microsoft.Orleans.OrleansCodeGenerator.Build package.
    3、Add a reference to the target assembly.
    4、Add [assembly: KnownAssembly("OtherAssembly")] at the top level of a C# file.
When I get to step 4, I find that KnownAssembly attribute cannot take a string as an argument.
Who can help me?

**Comment by ReubenBond** [comment]
You can use any type in the other assembly instead of the assembly name
