### ISSUE TITLE
`EndpointOptions.AdvertisedIPAddress` should be set to something by default.

### ISSUE THREAD

**Issue by brunolins16** [dotnet/orleans#7456]
See the `ConfigureEndpoints` helper method for how this could be done (the overload which doesn't take a hostname).

https://github.com/dotnet/orleans/blob/d3e58ce277ccdd5c2d95abeb787c02a78ab41893/src/Orleans.Runtime/Hosting/EndpointOptionsExtensions.cs#L72

**Comment by brunolins16** [comment]
@ReubenBond / @benjaminpetit 

I can work on this item as suggested (calling the `ConfigUtilities.ResolveIPAddress(null, null, AddressFamily.InterNetwork)`), however looking in the source code I found this:

https://github.com/dotnet/orleans/blob/10af0f4af588cd4aa45cb3e250dfbffa389d59c7/src/Orleans.Hosting.Kubernetes/ConfigureKubernetesHostingOptions.cs#L44

Is that, ok? or should we change how this verification is done?

**Comment by ReubenBond** [comment]
@brunolins16 that would be great. We can throw in the setter if the value is being set to null and therefore remove the validator

**Comment by brunolins16** [comment]
> @brunolins16 that would be great. We can throw in the setter if the value is being set to null and therefore remove the validator

@ReubenBond, we can do that, however, it will not fix the change in the `ConfigureKubernetesHostingOptions`, right?
The `AdvertisedIPAddress` will not be set to `PodIP` (from `POD_IP` env var) anymore, since the condition (`if (options.AdvertisedIPAddress is null)`) will never be true. Do you think it will be a breaking change?

https://github.com/dotnet/orleans/blob/eaf9ae1ad6de8b72ac9de3737bd7653bda98a4bc/src/Orleans.Hosting.Kubernetes/ConfigureKubernetesHostingOptions.cs#L44
