### ISSUE TITLE
Unable to connect to Orleans Cluster in a VMScaleSet in Azure

### ISSUE THREAD

**Issue by paul-cunningham-access** [dotnet/orleans#7458]
We are currently having connectivity issues to our Orleans Cluster.

Our setup is that we have got an Azure app service which acts as our API and a VMScaleSet in Azure hosting our Orleans Cluster.
Each of these is in their own Virtual Network and these have a peer relationship between them to allow traffic to flow freely.
We are using Azure Storage Clustering to manage the cluster so don't directly influence the addresses at all.

![image](https://user-images.githubusercontent.com/23554325/148048980-5f961a98-a26b-4999-8b0b-48a54e07b462.png)

When the API side tries to connect to the cluster it fails to connect with the error "Unable to connect to endpoint S10.0.0.4:30021:0"

When I look at the Peered Virtual Network address space from the app service to the scaleset, it is registered as the address range of  "10.0.0.0 - 10.0.255.255" so should be going to the other vnet.

If we go into the Kudu console of the app service and try tcpping 10.0.0.4:30021 we get "Connection attempt failed: Connect timed out." 30021 being the port our Silo is listening on.

If I try to tccpping 10.0.0.4:3389 to prove that the connection to the machine at least works than this is successful.

If I then remote onto the VM and run the silo in a command window rather than as a windows service, I can see no data being logged to the console when I TCPPING it or attempt to use the application. This kind of implies that it is failing completely to receive anything. 

I have also confirmed that the silo is definitely using that port.
![image](https://user-images.githubusercontent.com/23554325/148420033-b3f8cd16-e3f3-432a-9c00-d3a6e48b2ab1.png)

**Comment by ReubenBond** [comment]
Could this be a firewall issue?

**Comment by paul-cunningham-access** [comment]
We are currently looking into that with an azure support ticket but we are able to tcpping on port 3389 and have actually very quickly added a temporary inbound rule allowing any port from any source to any destination and we still couldn't get it to connect on 30021. We then of course removed the dangerous firewall rule after that. 

We will carry on with the Azure Support ticket to see if we can prove if it is getting blocked anywhere just in case but currently there is no reason it shouldn't reach the silo cluster from what we have found.

**Comment by ReubenBond** [comment]
@paul-cunningham-access feel free to message me on Discord, perhaps in the `#support` channel. It will allow us to help yo more quickly. You can join via this link: https://aka.ms/orleans-discord

**Comment by paul-cunningham-access** [comment]
We think we have solved the connectivity with Azure support. (firewall inside the virtual machine wasn't being set properly)
