### ISSUE TITLE
[Bug] Intermittent timeout leads to unhandled 404 MessageNotFound when deleting an Azure Queue message

### ISSUE THREAD

**Issue by rmt2021** [dotnet/orleans#7461]
### Describe the bug
We encounter an unhandled exception thrown by `DeleteQueueMessage` that crashes the caller application. The exception is caused by an error code 404 (MessageNotFound) when calling `DeleteQueueMessage` to delete an **existing** message. The exception is unexpected because the existing message should be successfully deleted and no 404 exceptions should be thrown. The exception is thrown from the Azure SDK API `DeleteMessageAsync` inside `DeleteQueueMessage`:
```
public async Task DeleteQueueMessage(QueueMessage message) {
  ...
  try {
      await queueClient.DeleteMessageAsync(message.MessageId, message.PopReceipt); <--This line throws the exception
  }
  catch (Exception exc) {
      ReportErrorAndRethrow(exc, "DeleteMessage", AzureQueueErrorCode.AzureQueue_11);
  }
  ...
}
```
`DeleteMessageAsync` retries message deletion multiple times until the message is successfully deleted without any transient error (timeout or server busy). We found that the retry mechanism can actually lead to a 404 error even if the message exists when issuing the deletion. More concretely:
1. Inside `DeleteQueueMessage`, `DeleteMessageAsync` (the SDK API) sends a HTTP request to delete the message
2. The message is deleted by the first try but a timeout happens (the timeout could either be an Azure cloud service timeout returning an HTTP 500 response with an error code, OperationTimedOut, described in the [Azure doc](https://docs.microsoft.com/en-us/rest/api/storageservices/common-rest-api-error-codes), or an SDK timeout which means there is no response from the remote in a limited timespan) 
3. The timeout triggers the SDK API to retry the deletion
4. The second try fails and encounters a 404 error because the message has already been deleted by the first try
5. The Azure SDK throws this 404 exception to Orleans, and `DeleteQueueMessage` in Orleans would catch it and trigger `ReportErrorAndRethrow`  

### To Reproduce
As shown above, when the first deletion request sent by `DeleteMessageAsync` in `DeleteQueueMessage` succeeds after a timeout, MessageNotFound will appear in the response of the second deletion request, which results in an unhandled exception.

<details>
<summary>Logs of DeleteQueueMessage</summary>
Error Message: System.AggregateException : Error doing DeleteMessage for Azure storage queue test-1-bb2ded91-0594-4b7c-bb9a-7c30fd5917bc-aqdatamanagertests Exception = Azure.RequestFailedException: The specified message does not exist. RequestId:b978eba4-508c-4739-a931-0707db750001 Time:2021-12-27T07:10:45.4351282Z Status: 404 (The specified message does not exist.) ErrorCode: MessageNotFound
Content:
MessageNotFoundThe specified message does not exist.
RequestId:b978eba4-508c-4739-a931-0707db750001
Time:2021-12-27T07:10:45.4351282Z

Headers:
Server: Windows-Azure-Queue/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: b978eba4-508c-4739-a931-0707db750001
x-ms-version: 2018-11-09
x-ms-error-code: MessageNotFound
Date: Mon, 27 Dec 2021 07:10:45 GMT
Content-Length: 221
Content-Type: application/xml

at Azure.Storage.Queues.MessageIdRestClient.DeleteAsync(String messageid, String popReceipt, Nullable`1 timeout, CancellationToken cancellationToken)
at Azure.Storage.Queues.QueueClient.DeleteMessageInternal(String messageId, String popReceipt, Boolean async, CancellationToken cancellationToken)
at Azure.Storage.Queues.QueueClient.DeleteMessageAsync(String messageId, String popReceipt, CancellationToken cancellationToken)
at Orleans.AzureUtils.AzureQueueDataManager.DeleteQueueMessage(QueueMessage message) in C:\Users\yinfang\orleans\src\Azure\Orleans.Streaming.AzureStorage\Storage\AzureQueueDataManager.cs:line 308 (The specified message does not exist.
RequestId:b978eba4-508c-4739-a931-0707db750001
Time:2021-12-27T07:10:45.4351282Z
Status: 404 (The specified message does not exist.)
ErrorCode: MessageNotFound
</details>

### Expected behavior & Possible Solution
The catch block should catch the RequestFailedException and check whether it is a 404 response. Instead of letting the harmless 404 error crash the application, `DeleteQueueMessage` should swallow the exception (and print some logs). We actually find a better practice than throwing the exception is adopted in [`ClearQueue`](https://github.com/dotnet/orleans/blob/5ec98fb485ea89be192947878216a546f02e35d4/src/Azure/Orleans.Streaming.AzureStorage/Storage/AzureQueueDataManager.cs#L150-L156) from https://github.com/dotnet/orleans/pull/6419.

### Additional context
We are willing to send a PR to help on this issue if swallowing 404 and printing logs is considered better practice than throwing the exception.

**Comment by ReubenBond** [comment]
Hi @rmt2021, why is this crashing the caller application? Could you show me the call site which leads to a crash?

I agree with your assessment that it would be better for 'sAzureQueueDataManager.DeleteQueueMessage` to swallow 404 messages rather than throw.

Thank you for the offer to open a PR, it would me much appreciated!

**Comment by rmt2021** [comment]
> why is this crashing the caller application? 

When we use `AzureQueueDataManager.DeleteQueueMessage` to delete an existing queue message we created before, an `AggregateException` will be thrown from Orleans. This exception here is unexpected because the existing message should be successfully deleted and no exceptions led by 404 should be thrown.

> Could you show me the call site which leads to a crash?

The stack trace is here:
```
Error Message: System.AggregateException : Error doing DeleteMessage for Azure storage queue test-1-bb2ded91-0594-4b7c-bb9a-7c30fd5917bc-aqdatamanagertests Exception = Azure.RequestFailedException: The specified message does not exist. RequestId:b978eba4-508c-4739-a931-0707db750001 Time:2021-12-27T07:10:45.4351282Z Status: 404 (The specified message does not exist.) ErrorCode: MessageNotFound
Content:
MessageNotFoundThe specified message does not exist.
RequestId:b978eba4-508c-4739-a931-0707db750001
Time:2021-12-27T07:10:45.4351282Z

Headers:
Server: Windows-Azure-Queue/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: b978eba4-508c-4739-a931-0707db750001
x-ms-version: 2018-11-09
x-ms-error-code: MessageNotFound
Date: Mon, 27 Dec 2021 07:10:45 GMT
Content-Length: 221
Content-Type: application/xml

at Azure.Storage.Queues.MessageIdRestClient.DeleteAsync(String messageid, String popReceipt, Nullable 1 timeout, CancellationToken cancellationToken)
at Azure.Storage.Queues.QueueClient.DeleteMessageInternal(String messageId, String popReceipt, Boolean async, CancellationToken cancellationToken)
at Azure.Storage.Queues.QueueClient.DeleteMessageAsync(String messageId, String popReceipt, CancellationToken cancellationToken)
at Orleans.AzureUtils.AzureQueueDataManager.DeleteQueueMessage(QueueMessage message) in C:\Users\usr\orleans\src\Azure\Orleans.Streaming.AzureStorage\Storage\AzureQueueDataManager.cs:line 308 (The specified message does not exist.
RequestId:b978eba4-508c-4739-a931-0707db750001
Time:2021-12-27T07:10:45.4351282Z
Status: 404 (The specified message does not exist.)
ErrorCode: MessageNotFound
```

**Comment by ReubenBond** [comment]
Are you calling `AzureQueueDataManager.DeleteQueueMessage` directly from your own code? By call site, I mean the source code itself.

Is this actually crashing your application, i.e, causing the process to terminate abruptly?

**Comment by rmt2021** [comment]
Yes, we directly call the `AzureQueueDataManager.DeleteQueueMessage` in our own application which utilizes the Orleans.AzureUtils part, and the raised exception terminates the process.
