### ISSUE TITLE
[Epic]: Orleans Enhancements for .NET7

### ISSUE THREAD

**Issue by rafikiassumani-msft** [dotnet/orleans#7467]
#### Grains

- [x] #7468 - Replaced by #https://github.com/dotnet/orleans/issues/7351
- [ ] #7469
- [x] #7470

#### Persistence

- [x] #7471
- [ ] #7472

#### Streaming

- [ ] #7473
- [x] #7474
- [ ] #7475
                                          
#### Hosting/Deployment

- [ ] #7485
- [ ] #7486
    - Creating deployment docs

#### Reminders & Timers

- [x] #7476
- [ ] #7477
      - Needs system design
- [ ] #7478

#### Workflows

 - [ ] #7487
     - Work with Azure Durable functions
     - Needs design and user studies
 
#### Tooling

- [ ] #7479

#### Modernization/Continuous improvements 
- [x] #7480
  - Turn-key support for the major Azure hosting platforms (App Service, Azure Container Apps, Azure Kubernetes Service)
  - Support for open telemetry
- [ ] #7482
- [x] #7483
- [ ] #7481

#### Docs
- [x] #7484

**Comment by jirisykora83** [comment]
@SebastianStehle https://support.squidex.io/t/feedback-needed-the-future-or-orleans/4338/3
