### ISSUE TITLE
Remove SMS Provider

### ISSUE THREAD

**Issue by rafikiassumani-msft** [dotnet/orleans#7475]
Value: SMS provider lacks decoupling capabilities needed from streams. Our goal is to make sure customers are using in-memory stream provider.

**Comment by andyhoyle** [comment]
It has been [mentioned](https://discord.com/channels/333727978460676096/922945034427432980/950318480119447573) that this will be implemented with the 4.0 release.

We make extensive use of the SMS provider (and fully understand the consequences of doing so) to allow direct grain communication without the need for explicitly calling the destination grain. It allows us to raise an event in the source grain and subscribe to it using implicit subscriptions in the destination grain without the source grain ever needing to know about the destination grain.

Event handlers in our grains only ever mutate state in memory and once all grains in the chain have successfully processed events, the state it is committed to storage for all grains in the chain. It is an important part of our infrastructure.

I understand the reason for removing it, but could we not keep the feature, but rename it away from the streams namespace?

**Comment by benjaminpetit** [comment]
I understand that it might not be a very popular decision.

Renaming SMS from the stream namespace wouldn't be sufficient, since SMS share some code with persistent streams. This common code is limiting us in enhancing the streaming infrastructure.

Ideally, I think SMS users should move to MemoryStreams. Did you considered moving to that?

**Comment by andyhoyle** [comment]
For reference - discussed on Discord channel: https://discord.com/channels/333727978460676096/950376855297474611

**Comment by benjaminpetit** [comment]
I forgot to update this thread so there is the current plan for 4.0:

- Remove SMS from the stream provider dll, and encourage people to migrate to InMemoryStream provider
- Create in a separate dll extension a partial replacement for SMS. It will only support "implicit" subscription, and the interface will be incompatible with the "traditional" stream interfaces.

The goal is to discourage people completely to use SMS just as another stream implementation, but allow people that want SMS-like behavior to still use it.
