### ISSUE TITLE
Implement the ability to schedule non re-entrance timers

### ISSUE THREAD

**Issue by rafikiassumani-msft** [dotnet/orleans#7478]

**Comment by ReubenBond** [comment]
Tracked by #2574

**Comment by tomachristian** [comment]
@ReubenBond I see this was closed as completed, although #2574 is still open. Could you please clarify if this has been fixed (or alternative implemented)? I can't find any PR reference.

**Comment by ReubenBond** [comment]
The GitHub close statuses should be ignored. The comment is more relevant: this is tracked by https://github.com/dotnet/orleans/issues/2574
