### ISSUE TITLE
When useless PubSubRendezvousGrain will be deactivated and cleared state when silo running

### ISSUE THREAD

**Issue by zh6335901** [dotnet/orleans#7489]
I've used in my project (Kafka stream provider and MongoDB PubSub store), These streams only have implicit subscribtion. When   
a grain produce a message to stream, The `PubSubRendezvousGrain` will save state to the store. From the PubSub store I can see the saved state contains producer set and empty consumer info set. 

But i found these `PubSubRendezvousGrain` still activate and would not clear state when relevant stream not produce message any more for a long time. These `PubSubRendezvousGrain` only clear state when i shutdown silo gracefully

**Comment by benjaminpetit** [comment]
Did you configured your stream provider with `StreamPubSubOptions.PubSubType = StreamPubSubType.ImplicitOnly`? This should avoid activating any `PubSubRendezvousGrain`.

It is expected that the `PubSubRendezvousGrain` will have an activation, and that it will only clear its state when all silos are shut down.

**Comment by zh6335901** [comment]
@benjaminpetit Thanks for your reply

> Did you configured your stream provider with `StreamPubSubOptions.PubSubType = StreamPubSubType.ImplicitOnly`? This should avoid activating any `PubSubRendezvousGrain`.

Does persistent stream provider support with `StreamPubSubOptions.PubSubType = StreamPubSubType.ImplicitOnly` If they want?  I can't find it in Kafka stream provider options.

> 
> It is expected that the `PubSubRendezvousGrain` will have an activation, and that it will only clear its state when all silos are shut down.

As more and more message produced to new stream, Will this cause `PubSubRendezvousGrain` activation and state leak?

And if i confirm a stream no longer in use,  Can i call `PersistentStreamProvider.ExecuteCommand(PersistentStreamProviderCommand.StopAgents)` directly in the grain?

**Comment by benjaminpetit** [comment]
> Does persistent stream provider support with `StreamPubSubOptions.PubSubType = StreamPubSubType.ImplicitOnly` If they want? I can't find it in Kafka stream provider options.

It's supported by Orleans stream infrastructure, all providers will support that.

> As more and more message produced to new stream, Will this cause `PubSubRendezvousGrain` activation and state leak?

It is a possibility. But when a silo shut down, it will unregister itself from the stream producer list. If the consumer and producer lists are empty, the state will be cleared.

For explicit subscriptions we need to have this rendez-vous grain, so when adding a new consumer we can notify stream producer. If the stream is configured for implicit only, we don't need this grain.

> And if i confirm a stream no longer in use, Can i call PersistentStreamProvider.ExecuteCommand(PersistentStreamProviderCommand.StopAgents) directly in the grain?

No, because with this command you will stop pulling agents. Pulling agents are responsible for multiple streams.

**Comment by zh6335901** [comment]
@benjaminpetit  Thanks, I got it, I will try `StreamPubSubOptions.PubSubType = StreamPubSubType.ImplicitOnly` in my case
