### ISSUE TITLE
Redis as Grain Directory Storage not working on 3.5.1

### ISSUE THREAD

**Issue by mario-pina-cko** [dotnet/orleans#7491]
Hello! We are trying to migrate our solution to start using Orleans version 3.5.1. However, we are using Redis as the grain storage, and with this update, this is no longer working.

I've created a very simple web application trying to replicate the error and I was successful. Using the grains examples from [your tutorial](https://dotnet.github.io/orleans/docs/tutorials_and_samples/tutorial_1.html) (IHello and HelloGrain) I've created a simple controller with the following code:

```cs
[ApiController]
[Route("[controller]")]
public class OrleansController : ControllerBase
{
    private readonly ILogger<OrleansController> _logger;
    private readonly IClusterClient _clusterClient;

    public OrleansController(ILogger<OrleansController> logger, IClusterClient clusterClient)
    {
        _logger = logger;
        _clusterClient = clusterClient;
    }

    [HttpGet("{id}")]
    public IHelloGrain Get([FromRoute] int id)
    {
        var grain = _clusterClient.GetGrain<IHelloGrain>(id);

        grain.SayHello("humans");
        
        return grain;
    }
}
```

For adding Orleans with Redis I simply added the following code:

```cs
public static IHostBuilder CreateHostBuilder(string[] args) =>
Host.CreateDefaultBuilder(args)
    .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); })
    .UseOrleans((context, builder) =>
    {
        builder.UseLocalhostClustering();
    
        builder.UseRedisGrainDirectoryAsDefault(options =>
        {
            var host = "localhost";
            var port = 6379;

            options.ConfigurationOptions = new ConfigurationOptions
            {
                EndPoints = { new DnsEndPoint(host, port) }
            };
        });
    });
```

### Version 3.5.0

Using version 3.5.0 of the several required dependencies:

```cs
<PackageReference Include="Microsoft.Orleans.Client" Version="3.5.0" />
<PackageReference Include="Microsoft.Orleans.CodeGenerator.MSBuild" Version="3.5.0">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
<PackageReference Include="Microsoft.Orleans.GrainDirectory.Redis" Version="3.5.0-beta1" />
<PackageReference Include="Microsoft.Orleans.Server" Version="3.5.0" />
```

I was able to call the endpoint (<url>/orleans/1) and I could see that Redis contained a new entry for grain with id = 1. Example after 3 calls with ids 1, 2, and 3: 

![image](https://user-images.githubusercontent.com/83644079/149095143-d41c746d-241b-42c4-897d-0e2f1210bcd6.png)

### Version 3.5.1

Using version 3.5.1 of the several required dependencies and restarting everything:

```cs
<PackageReference Include="Microsoft.Orleans.Client" Version="3.5.1" />
<PackageReference Include="Microsoft.Orleans.CodeGenerator.MSBuild" Version="3.5.1">
    <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
<PackageReference Include="Microsoft.Orleans.GrainDirectory.Redis" Version="3.5.1-beta1" />
<PackageReference Include="Microsoft.Orleans.Server" Version="3.5.1" />
```

I was able to call the endpoint (<url>/orleans/5), but this time when I looked at Redis the grain directory entry for grain id = 5 hadn't been created.

### Investigation

I was looking into this using the debugger, and I found the issue on [this line](https://github.com/dotnet/orleans/blob/v3.5.1/src/Orleans.Runtime/Catalog/Catalog.cs#L1182). On version 3.5.0 the _grainLocator_ its a _GrainLocatorSelector_ with Redis, while in version 3.5.1 the _grainLocator_ its a _DhtGrainLocator_.

I took a further look into the code and found that the issue most likely occurs due to [this PR](https://github.com/dotnet/orleans/pull/7316/files), more specifically the change on the _SiloBuilder.cs_ from moving the _this.ConfigureDefaults();_ from the _Build()_ method into the constructor.

That [_ConfigureDefaults()_](https://github.com/dotnet/orleans/blob/v3.5.1/src/Orleans.Runtime/Hosting/DefaultSiloServices.cs#L122) method will check if there is any implementation of the _IGrainDirectory_ registered and if there is will change the implementation of the _grainLocator_. Since this method is now called on the constructor, the code inside the UseOrleans on the HostBuilder, will no longer be called before the _this.ConfigureDefaults()_, which causes the default _DhtGrainLocator_ to be instantiated instead of the requested implementation.

Is there supposed to be a different way to configure Redis as a grain directory in version 3.5.1? If so, isn't this a breaking change? 

Thanks in advance.

**Comment by benjaminpetit** [comment]
It seems you clearly identified the issue...

Could you try maybe registering manually the redis directory in the service provider before calling `UseOrleans` until we fix this issue?

**Comment by Romanx** [comment]
Hey,

We ran into a variation of this while writing some TestCluster code using an in memory shared implementation of a grain directory.

Unfortunately in the test cluster the host builder is created in internal code then immediately configured using the SiloConfigurator pattern however it calls the [ConfigureDefaults()](https://github.com/dotnet/orleans/blob/v3.6.0/src/Orleans.Runtime/Hosting/DefaultSiloServices.cs#L122) method as it's first thing and then all of the client silo configuration code meaning there is no way for you to register a grain directory implementation for tests.

As an **awful hack** you can do the following in a configurator to add to the settings. *Note: this is going to be very brittle.*
```csharp
public static IServiceCollection AddGrainDirectory(this IServiceCollection services, string name)
{
    Type cachedGrainLocator = Type.GetType("Orleans.Runtime.GrainDirectory.CachedGrainLocator, Orleans.Runtime", throwOnError: true)!;

    services
        .AddSingletonNamedService<IGrainDirectory>(name, (sp, name) => ActivatorUtilities.CreateInstance<MyCustomGrainDirectory>(sp))
        .AddSingleton(Type.GetType("Orleans.GrainDirectory.IGrainLocator, Orleans.Core", throwOnError: true)!, Type.GetType("Orleans.Runtime.GrainDirectory.GrainLocatorSelector, Orleans.Runtime", throwOnError: true)!)
        .AddSingleton(cachedGrainLocator)
        .AddFromExisting(typeof(ILifecycleParticipant<ISiloLifecycle>), cachedGrainLocator);

    return services;
}
```

If there isn't capacity to pick this up soon i'd be happy to take a look, in the TestCluster it looks like it should be as simple as calling it after all of the client configuration as the defaults look like they're supposed to, as for the standard cluster i'm not sure about but happy to take some guidance
