### ISSUE TITLE
[Epic]: Orleans + DAPR Integration

### ISSUE THREAD

**Issue by rafikiassumani-msft** [dotnet/orleans#7493]
We would like to investigate the possibilities of integrating Orleans and DAPR.

**Comment by geffzhang** [comment]
There is a strong demand for this, is there any progress ？

**Comment by ReubenBond** [comment]
We are interested to hear what kind of integration people would like to see. We are also open to contributions

**Comment by geffzhang** [comment]
I want to replace the Dapr Actor with Orleans, which makes better use of other building blocks of Dapr, such as service invocation.

**Comment by m3nax** [comment]
> Dapr has actor support based on Orleans. But since this is a .net project we can cast most famous actors for our project by utilizing Microsoft Orleans for our dapr enabled service. Since Orleans is around for much longer, it has many more features not yet implemented by Dapr actors.
> 
> I want to replace the Dapr Actor with Orleans, which makes better use of other building blocks of Dapr, such as service invocation， State management。

Yes, service invocation is a great DAPR function, which can be used for integration with other ecosystems and languages.

**Comment by ReubenBond** [comment]
Closing for now, since we don't have any actionable plans here. For specific integrations, please open issues & PRs
