### ISSUE TITLE
Orleans OpenTelemetry question

### ISSUE THREAD

**Issue by Vlad-Stryapko** [dotnet/orleans#7504]
I've been recently toying with Orleans OT locally. It seems some work has already been done in Orleans master branch but it wasn't released yet, so, I've decided to try out the Grain filters from https://github.com/dotnet/orleans/blob/dc7fd582e7f00e0f89a7790f99950f31fdb6109b/src/Orleans.Core/Diagnostics/ActivityPropagationGrainCallFilter.cs locally to see how they would work.

Unfortunately, they don't seem to work correctly or perhaps I misunderstand something. 

I've got a web app which is an Orleans client and two Orleans grains - Parent and Child. The call graph is the usual App -> Parent -> Child.

However, the traces I see in Jaeger are not correctly correlated - their trace ids are different. In particular, Web app has its own trace which contains web call + silo call, while the silo itself has the rest of the operation - incoming Parent call and the Child calls. 

I've taken a look at a similar example for messaging, found here: https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/examples/MicroserviceExample/Utils/Messaging/MessageReceiver.cs#L68

The difference is that the messaging code sets the activity's parent context, whilst the Orleans one sets Parent but creates the activity itself w/o the parent context. 

I've updated the Incoming filter as follows:

```
       public Task Invoke(IIncomingGrainCallContext context)
        {
            Activity activity = default;

            // Start an activity if this is an application call
            var target = context.Grain.GetPrimaryKey(out var grainIdStr);
            string activityName = $"{context.Grain}/{grainIdStr ?? target.ToString()}/{context.InterfaceMethod?.Name}";

            propagator.ExtractTraceIdAndState(
                null,
                (object carrier, string fieldName, out string fieldValue, out IEnumerable<string> fieldValues) =>
                {
                    fieldValues = default;
                    fieldValue = RequestContext.Get(fieldName) as string;
                },
                out var traceParent,
                out var traceState);

            if (!string.IsNullOrEmpty(traceParent))
            {
                activity = ActivitySource.CreateActivity(activityName, ActivityKind.Server, traceParent);
            }
            else
            {
                activity = ActivitySource.CreateActivity(activityName, ActivityKind.Server);
            }            
           [rest is similar]
```

Now, the spans are correctly correlated as can be seen below in Jaeger:

![image](https://user-images.githubusercontent.com/22256471/150376744-301fc348-19fe-47c8-b401-cafdfb593230.png)

My question is, am I missing something or is it indeed a small omission in the current Grain filter (no bashing intended, thanks everyone for the wonderful work you do)? 

Edit: 

I've also checked the span ids themselves and the Silo span references the span from the Web app as its parent, so it seems `SetParent` works to some extent, but it doesn't seem to change the root trace id.

**Comment by suraciii** [comment]
Hi @Vlad-Stryapko , thanks for the feedback!

I reproduced this issue and found that the OpenTelemetry SDK touches the created but not started activity (at sampling stage I assume), it makes the created activity generate a new trace id before `SetParentId` called, after this, the trace id of this activity cannot be updated any more

The changes you posted should be the right solution, `SetParentId` should not be used commonly as the document said:
> This is intended to be used only at 'boundary' scenarios where an activity from another process logically started this activity.
And there's an issue in dotnet/runtime about it: https://github.com/dotnet/runtime/issues/60078

And what makes me curious is why `SetParentId` works in [aspnetcore](https://github.com/dotnet/aspnetcore/blob/v6.0.0/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L298)😂

**Comment by Vlad-Stryapko** [comment]
Thanks, sounds good. I'm not well versed in the Orleans PRs, shall I try to create one or will someone implement my suggestion later on?

**Comment by suraciii** [comment]
> Thanks, sounds good. I'm not well versed in the Orleans PRs, shall I try to create one or will someone implement my suggestion later on? 

It would be great if you can submit a PR for this, since you've provided the fix already :)

**Comment by Vlad-Stryapko** [comment]
Sure, here is it: 

https://github.com/dotnet/orleans/pull/7506
