### ISSUE TITLE
`IReminderRegistry` should accept `IGrainContext` on every method instead of using `RuntimeContext.Current`

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#7507]
In the ongoing de-magicifying effort, I propose we refactor `IReminderRegistry` to remove internal usage of `RuntimeContext.Current` and instead pass the `IGrainContext` in directly from the calling grain.

`RuntimeContext` is `internal`, whereas `IReminderRegistry` is public and somewhat expected to be mocked/substituted in tests (it's a member on `IGrainRuntime`, which IIRC was created to improve testability)

``` C#
public interface IReminderRegistry : IGrainServiceClient<IReminderService>
{
    Task<IGrainReminder> RegisterOrUpdateReminder(string reminderName, TimeSpan dueTime, TimeSpan period);
    Task UnregisterReminder(IGrainReminder reminder);
    Task<IGrainReminder> GetReminder(string reminderName);
    Task<List<IGrainReminder>> GetReminders();
}
```
Proposed
``` C#
public interface IReminderRegistry : IGrainServiceClient<IReminderService>
{
    Task<IGrainReminder> RegisterOrUpdateReminder(IGrainContext grainContext, string reminderName, TimeSpan dueTime, TimeSpan period);
    Task UnregisterReminder(IGrainContext grainContext, IGrainReminder reminder);
    Task<IGrainReminder> GetReminder(IGrainContext grainContext, string reminderName);
    Task<List<IGrainReminder>> GetReminders(IGrainContext grainContext);
}
```

**Comment by Romanx** [comment]
I took a quick look at this. It seems that `GrainServiceClient<TGrainService>` uses the `RuntimeContext.Current`  to get the current grain reference. 

It uses the `GrainReference` to work out which GrainService should be called which is currently a propert getter, to replace this with a passed context this will have to become a method instead.

I couldn't find an easy way to get from a grain to an `IGrainContext` for an external consumer. Internally the `IActivationData` implements `IGrainContext` so you can use that but if you're a different assembly I couldn't work out how you would solve this.

If no other members of the grain context are used (I may be missing some places) then it might be easier for anyone consuming for `IReminderRegistry` to take the calling `GrainReference` instead.

**Comment by JorgeCandeias** [comment]
The `ITimerRegistry` just takes a `Grain`. This makes it easy to use from DI, easy to mock for no-ops and easy to fake for callback testing.

The `ReminderRegistry` [only appears to need to a GrainReference](https://github.com/dotnet/orleans/blob/d3e58ce277ccdd5c2d95abeb787c02a78ab41893/src/Orleans.Runtime/ReminderService/ReminderRegistry.cs#L72) from what I can tell. Assuming I'm not missing anything, why not just let it take a `Grain` instance and derive the reference from there, so we lazy devs can just type `this` like we do with the `ITimerRegistry`?

**Comment by zeinali0** [comment]
Why just don't inject `IGrainContextAccessor` instead?

**Comment by brunolins16** [comment]
@ReubenBond If I am not missing something, I agree with @Romanx and we could use the `GrainReference` instead. Here is the API change proposal:

``` diff
public interface IReminderRegistry : IGrainServiceClient<IReminderService>
{
-    Task<IGrainReminder> RegisterOrUpdateReminder(string reminderName, TimeSpan dueTime, TimeSpan period);
+    Task<IGrainReminder> RegisterOrUpdateReminder(GrainReference callingGrainReference, string reminderName, TimeSpan dueTime, TimeSpan period);

-    Task UnregisterReminder(IGrainReminder reminder);
+    Task UnregisterReminder(GrainReference callingGrainReference, IGrainReminder reminder);

-    Task<IGrainReminder> GetReminder(string reminderName);
+    Task<IGrainReminder> GetReminder(GrainReference callingGrainReference, string reminderName);

-    Task<List<IGrainReminder>> GetReminders();
+   Task<List<IGrainReminder>> GetReminders(GrainReference callingGrainReference);
}

public abstract class GrainServiceClient<TGrainService> : IGrainServiceClient<TGrainService> where TGrainService : IGrainService
{
-        protected TGrainService GrainService { get; }
-        protected GrainReference CallingGrainReference => RuntimeContext.Current?.GrainReference;

+        protected TGrainService GetGrainService(GrainReference callingGrainReference) {}
}
```

**Comment by ReubenBond** [comment]
If not `IGrainContext`, I think `GrainId` would be preferable. The `GrainReference` carries around extra baggage: some interface type, which is not necessary (it *was* necessary in 3.x).

Using `GrainId`/`GrainReference` instead of `IGrainContext` has the benefit that it can be called remotely for any random grain. Maybe that's useful. I recall that the Azure ML team requested the ability to manage reminders for foreign grains.
