### ISSUE TITLE
Orleans.Statistics.LinuxEnvironmentStatistics  fails when running in a container on gVisor

### ISSUE THREAD

**Issue by ElanHasson** [dotnet/orleans#7520]
See: https://github.com/OrleansContrib/OrleansDashboard/issues/334#issuecomment-1025753455

I think https://github.com/dotnet/orleans/blob/main/src/TelemetryConsumers/Orleans.TelemetryConsumers.Linux/LinuxEnvironmentStatistics.cs#L163-L166 is having a hard time dividing by zero 🤷🏼 

It's difficult for me to get logs out of that environment, but will work on it.

Happy to send a PR for this that would prevent the division from happening and just return `0`s.

thoughts on above approach?

Discord chat link for context: https://discord.com/channels/333727978460676096/922945034427432980/937707474570608710

**Comment by ReubenBond** [comment]
Answered in Discord:
* We should leave `CpuUsage` unset if we cannot read a valid value (set to `null`)
* Change `OverloadDetector.Overloaded` to check `.HasValue`
* Coalesce `CpuUsage` to `0f` in `LinuxEnvironmentStatistics.WriteToStatistics`
