### ISSUE TITLE
Looking for some examples about deploying and using Microsoft.Orleans.ServiceFabric

### ISSUE THREAD

**Issue by ajvwray** [dotnet/orleans#7524]
As the old repo's no longer work is there another source of information for using Azure SF? 

It may be this isnt the preferred way to host now, however I'm still evaluating any potential options so any alternatives are welcome.

**Comment by ReubenBond** [comment]
Hosting on Service Fabric is still supported, but we no longer recommend a specific integration package for it. Instead, we recommend using the .NET Generic Host. For more information, see this issue: https://github.com/dotnet/orleans/issues/6961
