### ISSUE TITLE
Add DataConnectionStringForReminders & AdoInvariantForReminders to xml configs

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#753]
https://github.com/dotnet/orleans/pull/750 added DataConnectionStringForReminders & AdoInvariantForReminders to the config objects but not to the xml parsing code and the xsd. Need to add that for consistency.

Also need to add DataConnectionStringForReminders & AdoInvariantForReminders to the docs.

**Comment by shayhatsor** [comment]
we also need to add the new "AdoInvariant" key, which was added to the client and global config

**Comment by sergeybykov** [comment]
Resolved by https://github.com/dotnet/orleans/pull/925.
