### ISSUE TITLE
Remove `PerformanceTuningOptions`

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#7538]
We should not be managing process-wide options which are not Orleans-specific.

Therefore, lets remove `PerformanceTuningOptions.

**Comment by ElanHasson** [comment]
Can this performance tuning code be migrated to an optional nuget or at least documented?

I fear removing this will result in the perf tuning "for Orleans" being lost forever, and others having to discover what knobs to turn to achieve the same.

I do agree it should t be "part" of Orleans.
