### ISSUE TITLE
Code generation does not support C# 6

### ISSUE THREAD

**Issue by Liversage** [dotnet/orleans#755]
The code generator uses the BCL CodeDom to generate C#. This code generator does not support C# 6 and using some of the newer constructs in grain interface projects or grain projects (like `nameof`) will generate errors during gode generation.

The solution is probably to use the [Roslyn CodeDom](https://www.nuget.org/packages/Microsoft.CodeDom.Providers.DotNetCompilerPlatform/).

**Comment by sergeybykov** [comment]
https://github.com/dotnet/orleans/pull/528 is Roslyn based and I believe should address this.

**Comment by jthelin** [comment]
@Liversage - I could not find any documentation about how to use the Roslyn CodeDom package you linked to, so it is hard to evaluate the amount of changes involved. :(

If the Roslyn CodeDom package is intended as a drop-in replacement for old BCL CodeDom functions then i am guessing the changes in our code would all be contained in `CodeGeneratorBase.GetCodeProvider` method.

https://github.com/dotnet/orleans/blob/master/src/ClientGenerator/CodeGeneratorBase.cs#L137

As an experiment, if you add reference to the `Microsoft.CodeDom.Providers.DotNetCompilerPlatform` package, and change CompilerVersion to ` "v4.6" ` on line 140 does that make your C# 6 grain code work?

**Comment by Liversage** [comment]
@jthelin Currently, I am quite busy writing business code and I can live without C# 6 features in my grains. However, as soon as my schedule is less packed it will be interesting to test your proposal.

**Comment by Liversage** [comment]
I have created a pull request https://github.com/dotnet/orleans/pull/924 but it failed to build on the build server: I have been unable to understand why this happens - the way code generation interacts with the Orleans project is more complex than I expected.

My changes to the source code are simple and from my own testing they works. But integrating the changes with how Orleans is built probably requires someone with a deeper understanding of the Orleans build process than me.

**Comment by sergeybykov** [comment]
Resolved by https://github.com/dotnet/orleans/pull/528.
