### ISSUE TITLE
Sample content specific to running Orleans on Azure App Service

### ISSUE THREAD

**Issue by bradygaster** [dotnet/orleans#7553]
Create conceptual articles demonstrating two different scenarios with Microsoft Orleans and Azure App Service:

- Running an application with 2 or more Silos containing various grain implementations. 

> Example: `Monster` grains are hosted in a `MonsterSilo` ASP.NET Core project, and `Player` grain are hosted in a second ASP.NET Core project named `PlayerSilo`. Both projects reference an `Abstractions` or `GrainInterfaces` project containing the grain abstractions, but the individual projects contain the grain implementations. This way, we'd be able to show multi-silo clusters hosting independent sets of grains. 

- Running an application with 2 or more Silos containing various grain implementations, and a client project

> Example: Same as above, but the `Client` project is an ASP.NET Core Blazor app that functions as an Orleans client so humans can interface with the game system on the back. Each `Client` connected to the game would create a new `Player` grain in the `PlayerSilo`, but no new `Monster` grains would be created. 

The conceptual article would need to cover the basics of getting a multi-silo app running on App Service. At a minimum, it'd need to explain:

- How an S1 or greater is required. 
- That each Web App representing a silo would need to be in an Azure regional virtual network. 
- That each Web App representing a silo would need to have its `vnetPrivatePortsCount` property set to 2 or greater.
- An Azure Storage account would be used for the clustering and grain persistence. 
- Ideally the article could link off to a pre-set Azure calculator showing the price of this setup (as it's not as expensive as it sounds). 

Ideally the topology could be demonstrated with an Azure Bicep file that sets it all up for the customer. 

## Sample

I've created an initial example of such a scenario in this repo: [Orleans silo + client on App Service](https://github.com/bradygaster/OrleansOnAzureAppService)

**Comment by finsharp** [comment]
Would this work with Containers?

**Comment by Timovzl** [comment]
@bradygaster Extremely useful!

Perhaps something could be added with regards to health checks: if a silo dies, ideally Azure should restart that replica.

Granted, the [health checks documentation](https://docs.microsoft.com/en-us/azure/app-service/monitor-instances-health-check#what-app-service-does-with-health-checks) for Azure App Services indicates that the possibilities are somewhat limited: Health checks are made only every 1 minute. A dead instance is replaced only after 1 hour. This can occur only 3 times per day. Still, it's something.

I think it makes sense to include an "is my own silo still alive" health check component in an Orleans Azure App Service, to be able to make use of the above behavior. It helps to have this in the example, especially when it comes to _how_ best to check this. Personally I'm leaning towards consulting the membership table. I'm curious to hear your thoughts.

**Comment by bradygaster** [comment]
> Would this work with Containers and Linux App Services?

This will work with Containers and Linux App Services. On Container Apps, there've been some changes that I learned about just yesterday that might make it somewhat more complex to set up, but I'm working with the team to convey the importance of this scenario so that they can prioritize some adjustments on that side. 

I'm *extremely* excited about what-can-be with Orleans, App Service, and Container Apps.

**Comment by bradygaster** [comment]
> @bradygaster Extremely useful!

So glad to hear it!

> Perhaps something could be added with regards to health checks: if a silo dies, ideally Azure should restart that replica.
> 
> Granted, the [health checks documentation](https://docs.microsoft.com/en-us/azure/app-service/monitor-instances-health-check#what-app-service-does-with-health-checks) for Azure App Services indicates that the possibilities are somewhat limited: Health checks are made only every 1 minute. A dead instance is replaced only after 1 hour. This can occur only 3 times per day. Still, it's something.

Ah - this is a very good point. Let me reach out to the team and see if there's a future opportunity here for us (or try to create one if one doesn't exist yet).

**Comment by bradygaster** [comment]
This sample content is about 90% complete, and an official doc is already in the review area for docs.ms.com demonstrating how to publish this sample to App Service. 

https://github.com/Azure-Samples/Orleans-Cluster-on-Azure-App-Service
