### ISSUE TITLE
GenerateGenerateSerializerAttributeAnalyzer  should have a codefix to Add `GenerateSerializer` attribute without `Serializable` already being present

### ISSUE THREAD

**Issue by ElanHasson** [dotnet/orleans#7564]
In the spirit of less onboarding paper cuts and to ease migration from 3.x to 4, we should implement a codefix to the analyzers to allow for automatically adding the `GenerateSerializer` attribute for `ORLEANS0005`. I noticed a codefix only activates when you have `Serializable`.

~~For the `Id` attributes, they can be generated by the ordinal position of the property in the body. This behavior already has precedence in the scenario when you have an `enum` without explicitly defined values assigned to each member.~~

I see it autogenerates the `Id(n)` attributes for `ORLEANS0004`, but not the `GenerateSerializer` for `ORLEANS0005`.

It would be great if the analyzer looked at grains and noticed exceptions, and model state, and types published to streams and raised warnings for them.

**Comment by ReubenBond** [comment]
I have a few concerns with this:
1. Determining what will need to be serialized by inspecting method signatures is error prone. eg, a signature might have a param of type `object` or an interface. Does that imply that any object might be sent?
2. Custom serializers can be configured at startup, such as JSON.NET. Static analysis will not be able to determine that a type will indeed have a capable serializer at runtime.
3. The check would likely be expensive, potentially requiring multiple passes.

**Comment by ReubenBond** [comment]
Closing for now, given the concerns listed above. If we find a way to address those, then we can reopen this.
