### ISSUE TITLE
SMS Stream provider: Ability to await for the queue to balance out 

### ISSUE THREAD

**Issue by koenbeuk** [dotnet/orleans#7570]
This is strictly a request to make testing simpler, consider the following contrived example that uses an SMS Provider with `FireAndForgetDelivery` set to true:

```csharp
await fooGrain.DoSomething();
await Task.Delay(1000);
var barStatus = await barGrain.GetStatus();
Assert.True(barStatus.FooHasDoneSomething);
```

BarGrain in this case has an explicit stream subscription to FooGrain, though this may be an indirect subscription through additional grains. The `Task.Delay` call is purely meant to ensure that all stream messages have been processed. 1s may or may not be sufficient depending on the environment where this test is running.

I'm looking for an option to replace the `Task.Delay` call with something that can ensure that all the SMS Stream provider is clear and no longer has any messages to process. This also requires the SMS Stream provider to be aware when an Event has been processed and also needs to assumes that no OneWay grain calls have been queued up.

Hypothetically I could write a helper method in the form of:

```csharp
async Task AwaitEmptyStreamQueue()
{
  var smsStatusProvider = Cluster.ServiceProvider.GetRequiredService<SMSStatusProvider>();
  while (true){
     if (smsStatusProvider.GetPendingMessagesCount() > 0){
        await Task.Delay(10); // Short delay, not really affecting our test durations or reliability
     }
  }
}
```

With something like the above, we could cleanly ensure that all pending messages have been processed. 

I'm happy to champion this if this issue makes sense.

(Outside of the scope of this issue, it would also be useful to look into the state of the cluster to see if any calls are still ongoing).

**Comment by benjaminpetit** [comment]
SMS isn't a "real" stream provider and we are considering removing it for 4.0 final. I don't think we want to invest more in it.

Your proposition could make sense for MemoryStreams though.
