### ISSUE TITLE
Unable to schedule reminders with a dueTime > 4294967294ms 

### ISSUE THREAD

**Issue by ElanHasson** [dotnet/orleans#7571]
See: https://github.com/dotnet/orleans/blob/a30f0ab6a3c4c46e01d4e09d8960fe95cf9387d4/src/Orleans.Runtime/ReminderService/ReminderRegistry.cs#L36-L53

Why is this limitation imposed?

**Comment by ElanHasson** [comment]
Dupe of https://github.com/dotnet/orleans/issues/1298#issue-127361552

**Comment by ElanHasson** [comment]
What would it take to change this?

**Comment by rafikiassumani-msft** [comment]
Closing as dupe of #1298

**Comment by ElanHasson** [comment]
@rafikiassumani-msft  I'm talking with @ReubenBond  about how to do this. I have a working prototype.

Details to follow.
