### ISSUE TITLE
Merge *.Abstractions projects into their non-Abstractions counterparts

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#7579]
The abstractions packages have gone too far, and we should consider merging most of them into their counterparts for 4.0.

* [ ] Merge Orleans.Streaming.Abstractions into Orleans.Streaming
* [ ] Merge Orleans.Runtime.Abstractions into Orleans.Runtime
* [ ] Merge Orleans.Core.Abstractions into Orleans.Core

Perhaps we should leave Orleans.Streaming.Abstractions alone, as it only contains attributes and it's common for people to keep their data model in separate projects. Counterpoints to that are:
* The most important attributes can be user-supplied (specified in .csproj/.props) and the code generator supports generating code for one project and putting that code in another project (we do this primarily to support F# & VB)
* Generated code relies on the Orleans.Serialization project anyway and there's no way that will change

**Comment by jsteinich** [comment]
For our use case having `Orleans.Core.Abstractions` is very important. We have grain interfaces (extending `IGrain` etc) with some Orleans attributes (mostly transaction related) that are shared with a client side project (Unity). Other than not needing anything in `Orleans.Core`, the biggest issue is all the additional dependencies that would come with the merge.

Another potential issue is what target frameworks are in use. It would be great if the abstractions project still supported netstandard2.0 (netstandard2.1 might be ok). I think that has gone back and forth, but we're unlikely to be able to update to 4.x without it.

**Comment by jsteinich** [comment]
> Could you help me understand why there are grain interfaces in your client projects

The main goal is sharing logic between client and server. We actually created an `IGrainFactory` implementation for the client that effectively just stores grains in a dictionary. It's nice to not have to pass as many parameters and instead lookup things as needed.

Splitting interfaces is likely still an option with that system, but mostly just seems like an inconvenience.



> The transactions attributes were moved into the `Orleans.Transactions` project

I must have missed that change. I'll have to look at that some more.



> Unity are working on supporting .NET 6

I've been following that thread. I hope they can do so on a reasonable timeline, but I think it's going to be quite awhile there.
