### ISSUE TITLE
Serialization , Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by Arazesh** [dotnet/orleans#7591]
Hi ,

We have 2 classes Teacher and student

Each teacher can have many students

`
public class Teacher
    {
        public int Id { get; set; }
        public string Name { get; set; }

        private ICollection<Student> _students;       
        public ICollection<Student> Students
        {
            get => _students ?? (_students = new HashSet<Student>());
            protected set => _students = value;
        }
    }

public class Student  
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Teacher Teacher { get; set; }
    }
`
When we fetch data from database the result is something like this

`
student  {
id = 1 ,

teacher = {
 1,
 students =[{ teacher = {...} },{teacher = {...}}]
}
}

`
As you can see it is infinite reference between them

Since we upgraded to version 3.6.1, we encounter the following error 

>  "Message": "Arithmetic operation resulted in an overflow.",
  "Detail": "   at Orleans.Serialization.BinaryTokenStreamReader2.ReadBytes(UInt32 count) in /_/src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs:line 225\r\n   at Orleans.Serialization.BinaryTokenStreamReader2.ReadBytes(Int32 count) in /_/src/Orleans.Core/Serialization/BinaryTokenStreamReader2.cs:line 470\r\n   at Orleans.Serialization.BinaryFormatterSerializer.Deserialize(Type expectedType, IDeserializationContext context) in /_/src/Orleans.Core/Serialization/BinaryFormatterSerializer.cs:line 82\r\n   at Orleans.Serialization.SerializationManager.FallbackDeserializer(IDeserializationContext context, Type expectedType) in /_/src/Orleans.Core/Serialization/SerializationManager.cs:line 1686\r\n   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader) in /_/src/Orleans.Core/Serialization/SerializationManager.cs:line 1362\r\n   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in /_/src/Orleans.Core/Serialization/SerializationManager.cs:line 1247\r\n   at Orleans.Serialization.BuiltInTypes.DeserializeHashSet[T](Type expected, IDeserializationContext context) in /_/src/Orleans.Core/Serialization/BuiltInTypes.cs:line 274\r\n   at Orleans.Serialization.BuiltInTypes.DeserializeGenericHashSet(Type expected, IDeserializationContext context) in /_/src/Orleans.Core/Serialization/BuiltInTypes.cs:line 246\r\n   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader) in /_/src/Orleans.Core/Serialization/SerializationManager.cs:line 1362\r\n   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context) in /_/src/Orleans.Core/Serialization/SerializationManager.cs:line 1247\r\n   at TeacherDeserializer(Type , IDeserializationContext )\r\n   at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context)\r\n   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)\r\n   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)\r\n   at StudentDeserializer(Type , IDeserializationContext )\r\n   at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context)\r\n   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)\r\n   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)\r\n   at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, IDeserializationContext context)\r\n   at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)\r\n   at Orleans.Runtime.Messaging.MessageSerializer.OrleansSerializer`1.Deserialize(ReadOnlySequence`1 input, T& value)\r\n   at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message)\r\n   at Orleans.Runtime.Messaging.Connection.ProcessIncoming()\r\n   at Orleans.Runtime.OutgoingCallInvoker.Invoke()\r\n   at Orleans.Runtime.OutgoingCallInvoker.Invoke()\r\n   at Orleans.Runtime.GrainReferenceRuntime.InvokeWithFilters(GrainReference reference, InvokeMethodRequest request, InvokeMethodOptions options)\r\n   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)\r\n   at Test.API.V1.Controllers.StudentController.GetById(Int32 id) in C:\\project\\hasti\\hasti.core\\SourceCode\\Distributed\\Test\\GrainTest.API\\V1\\Controllers\\StudentController.cs

**Comment by ReubenBond** [comment]
Orleans is not generating serializers for these types - you can see that by the presence of `BinaryFormatterSerializer` in the stack trace. I recommend you add the `[Serializable]` attribute to the type definitions and ensure that the `Microsoft.Orleans.CodeGenerator.MSBuild` package is installed in the project defining those types.

**Comment by Arazesh** [comment]
> 

Thanks for the reply and tips

Change ICollection<Student> and HashSet<Student> to List<Student> Fixed an issue
