### ISSUE TITLE
GenerateSerializer for record types, Id attribute usage on record parameter

### ISSUE THREAD

**Issue by jbockle** [dotnet/orleans#7594]
Should `IdAttribute` be updated to allow usage on parameters to support record property parameters, or maybe a distinct attribute like `RecordIdAttribute`?

e.g. this isn't possible
```cs
[GenerateSerializer]
public record MyRecord([Id(0)] string Id);
```

I could do this, however by doing that I feel I've lost the benefit of record types being succinct:
```cs
[GenerateSerializer]
public record MyRecord(string Id)
{
    [Id(0)]
    public string Id { get; init; } = Id;
}
```

**Comment by ReubenBond** [comment]
@jbockle in the former case, the attribute needs the `property:` specifier, eg:
``` C#
[GenerateSerializer]
public record Person([property: Id(0)] int Age, [property: Id(1)] string Name)
{
    [Id(2)]
    public string FavouriteColor { get; init; }

    [Id(3)]
    public string StarSign { get; init; }
}
```

**Comment by jbockle** [comment]
ah didn't know that existed, thanks!
