### ISSUE TITLE
NullReferenceException when you forget to call context.Invoke() in IIncomingGrainCallFilter

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#7610]
When you forget to call context.Invoke() in an IIncomingGrainCallFilter you get a NullReferenceException.

Of course it is a bug in the filter, but a better exception would be great.

Sample: https://github.com/SebastianStehle/OrleansIssue/blob/main/ConsoleApp21/Program.cs

**Comment by ReubenBond** [comment]
Thanks for reporting, @SebastianStehle. Will fix.
