### ISSUE TITLE
POCO grain IIncomingGrainCallFilter

### ISSUE THREAD

**Issue by jbockle** [dotnet/orleans#7618]
note - testing this with 4.0 preview

I have `IIncomingGrainCallFilter` added to my POCO grain, but the `IIncomingGrainCallFilter.Invoke` method is never invoked

```csharp
public interface IMyGrain : IGrainWithIntegerKey
{
    Task<string> Greet();
}

public class MyGrain : IMyGrain, IGrainBase, IIncomingGrainCallFilter
{
    public MyGrain(IGrainContext context) { GrainContext = context; }

    public IGrainContext GrainContext { get; }

    public Task Invoke(IIncomingGrainCallContext context)
    { // --> never reached when calling Greet
        return context.Invoke();
    }

    public Task<string> Greet()
    {
        return Task.FromResult("Hello world!");
    }
}
```

**Comment by jbockle** [comment]
actually having this issue with regular grains as well, maybe I'm doing something wrong but I'm not sure what it may be

**Comment by SebastianStehle** [comment]
I am not sure if the `IIncomingGrainCallFilter` interface can be used like that.

The normal approach is to write a custom class for that and then register it in service locator, e.g. like this:

https://github.com/SebastianStehle/OrleansIssue/blob/main/ConsoleApp21/Program.cs

The sample is there to reproduce a bug, when you forget the call `context.Invoke()` in the filter, but in general it works like this. Especially this line: https://github.com/SebastianStehle/OrleansIssue/blob/main/ConsoleApp21/Program.cs#L58

**Comment by jbockle** [comment]
the docs show its possible, was this changed with 4.0 maybe? https://docs.microsoft.com/en-us/dotnet/orleans/grains/interceptors#per-grain-grain-call-filters

**Comment by jbockle** [comment]
was looking into this a bit more, I have a hunch if I have at least one global incoming grain filter it'll solve it.. https://github.com/dotnet/orleans/blob/14bc87740e830342a9eafb2e8e057794d7b7156c/src/Orleans.Runtime/Core/InsideRuntimeClient.cs#L274-L284

**Comment by jbockle** [comment]
I think this is the issue, should it be `target.GrainInstance is IIncomingGrainCallFilter` instead of `target is IIncomingGrainCallFilter`?
https://github.com/dotnet/orleans/blob/14bc87740e830342a9eafb2e8e057794d7b7156c/src/Orleans.Runtime/Core/InsideRuntimeClient.cs#L274

**Comment by ReubenBond** [comment]
Thanks for reporting and determining the cause. Are you able to submit a PR including a test with a POCO grain? The test could live in [`GrainCallFilterTests.cs`](https://github.com/dotnet/orleans/blob/main/test/Tester/GrainCallFilterTests.cs)
