### ISSUE TITLE
Query about deploying new codebase

### ISSUE THREAD

**Issue by ADringer** [dotnet/orleans#7625]
Hi all,

I have a query regarding what happens to active grains when I deploy a new codebase. Take for example the following grain:

```
public interface IUserGrain : IGrainWithGuidKey
{
    Task SendEmail();
}

public class UserGrain: Grain, IUserGrain
{
    public Task SendEmail()
    {
    ....
    }
}
```

These have methods on them but the content of them doesn't matter for this query.

So this version of the grain is deployed and I have activations for it. I then deploy a newer version which has a property on the grain implementation which is set on activation:

```
public class UserGrain: Grain, IUserGrain
{
    private object _preferences;

    public override Task OnActivateAsync()
    {
        _preferences = .....;
    }

    public Task SendEmail()
    {
        if(preferences....)
    }
}
```

So for new activations the new property will be initialised and can be used by other methods on the grain. 

What I'm not sure about is what happens to existing activations after deployment? Will they cause a null reference exception as the grains are already activated and so won't initialise the property?

If so, is there a way of forcing reactivating active grains? Something to do with versioning? Or do I just need to be a bit more defensive in my coding and check for null references and initialise accordingly?

**Comment by benjaminpetit** [comment]
I am not sure to understand your question.

Activations that are created on a silo with the old `UserGrain` will have the old implementation. Activations created on a silo with the new `UserGrain` will have the new implemention?

When a silo shut down, all its activation will be deactivated. Then new activations will be created on another silo when needed (when there is a request made to them). When a new activation is created, `OnActivateAsync` will be called.

`OnActivateAsync` is called everytime an activation is created.
