### ISSUE TITLE
Let Orleans.Clustering.Consul use an existing ConsulClient

### ISSUE THREAD

**Issue by DerHulk** [dotnet/orleans#7626]
Hi Folks,

the Orleans.Clustering.Consul creates a instance of the ConsulClient by themself. See:
- [ConsulBasedMembershipTable](https://github.com/dotnet/orleans/blob/main/src/Orleans.Clustering.Consul/ConsulBasedMembershipTable.cs) line 37
- [ConsulGatewayListProvider](https://github.com/dotnet/orleans/blob/main/src/Orleans.Clustering.Consul/ConsulGatewayListProvider.cs) line 47

I got a situation where i have already a ConsulClient registered in my host/client environments, which has all informations (address, token), plus some additional settings 
- we use [polly](https://github.com/App-vNext/Polly) for the underlining http-client
- handle the certificate validation by ourself
- ...

It would be nice if we can change the code so that an existing ConsulClient can also be used (injected).
I think there are several possibilities to do that:

1) Create a second ctor with a ConsulClient-Object (therefore the Extensions methodes should be extended).
2) Refactor out abstract classes from the ConsulBasedMembershipTable and ConsulGatewayListProvider. User can then create their own implementations based of the existing.
3) Extend the [options](https://github.com/dotnet/orleans/tree/main/src/Orleans.Clustering.Consul/Options) with a factory property which can then be changed at setup time.

I can offer to create a pull request , but i want to ask first.

**Comment by benjaminpetit** [comment]
I think we should do option 3., to align what we have for the azure providers.

If you could do open a PR with this solution, that would be fantastic :)

**Comment by DerHulk** [comment]
Check you mean like [here](https://github.com/dotnet/orleans/blob/d2ae41ca9ba9e207486a9051c1614553c19ed5c6/src/Azure/Shared/Storage/AzureStorageOperationOptions.cs#L28)? Ok i will start to work an hopefully be back with a usefull pr in the next time.

**Comment by ReubenBond** [comment]
Fixed
