### ISSUE TITLE
Error monitoring Kubernetes pods after AKS cluster upgrade

### ISSUE THREAD

**Issue by pollumi** [dotnet/orleans#7627]
Hi,

After upgrading my AKS cluster to kubernetes version 1.21.9 (from 1.20.x) I notice regular `Error monitoring Kubernetes pods` logs. Before the update there were no issues with this, I can see this with a log query:
![grafik](https://user-images.githubusercontent.com/72297387/157733577-7364ee27-092e-4e04-bca6-543a9db6e0e0.png)

Other than that the cluster works fine, there is no pod restarting or any other suspicious logs.
I'm using Microsoft.Orleans.Hosting.Kubernetes in version 3.5.1.

Is there anything I could check to see where this error comes from? 
Thanks for any help!

This is the full error log:

> System.IO.IOException: The request was aborted.
>  ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
>  ---> System.Net.Sockets.SocketException (104): Connection reset by peer
>    --- End of inner exception stack trace ---
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
>    at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
>    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
>    at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
>    --- End of inner exception stack trace ---
>    at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
>    at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
>    at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer, Boolean partOfSyncRead)
>    at System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(Memory`1 buffer, HttpResponseMessage responseMessage, CancellationToken cancellationToken)
>    at k8s.LineSeparatedHttpContent.CancelableStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
>    at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
>    at System.IO.StreamReader.ReadLineAsyncInternal()
>    at k8s.Watcher`1.<>c.<CreateWatchEventEnumerator>b__21_1[TR](Task`1 t)
>    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> --- End of stack trace from previous location ---
>    at k8s.Watcher`1.CreateWatchEventEnumerator(Func`1 streamReaderCreator, Action`1 onError, CancellationToken cancellationToken)+MoveNext()
>    at k8s.Watcher`1.CreateWatchEventEnumerator(Func`1 streamReaderCreator, Action`1 onError, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
>    at k8s.Watcher`1.WatcherLoop(CancellationToken cancellationToken)
>    at k8s.Watcher`1.WatcherLoop(CancellationToken cancellationToken)
>    at Orleans.Hosting.Kubernetes.KubernetesClientExtensions.<>c__DisplayClass0_0`2.<<WatchAsync>b__4>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
>    at Orleans.Hosting.Kubernetes.KubernetesClientExtensions.WatchAsync[TList,TValue](HttpOperationResponse`1 watchList, CancellationToken cancellation)+MoveNext()
>    at Orleans.Hosting.Kubernetes.KubernetesClientExtensions.WatchAsync[TList,TValue](HttpOperationResponse`1 watchList, CancellationToken cancellation)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
>    at Orleans.Hosting.Kubernetes.KubernetesClusterAgent.MonitorKubernetesPods()
>    at Orleans.Hosting.Kubernetes.KubernetesClusterAgent.MonitorKubernetesPods()

**Comment by benjaminpetit** [comment]
Is it possible that for some reason the minimum version of SSL/TLS was bumped, but your app is trying to use a now unsupported version?

**Comment by pollumi** [comment]
Sorry to ask a probably trivial question, but how would I check and configure what `Microsoft.Orleans.Hosting.Kubernetes` is using for those API calls?

**Comment by benjaminpetit** [comment]
I think it will be used whatever is configured in `ServicePointManager.SecurityProtocol`

**Comment by pollumi** [comment]
So, I redeployed my deployment and.. the error is gone. 
Thanks @benjaminpetit for looking into it.

I'll close it then.
