### ISSUE TITLE
Clustering.AdoNet hangs and application does not start

### ISSUE THREAD

**Issue by pmorelli92** [dotnet/orleans#7644]
Given this `demo.csproj`:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <AssemblyName>Silo</AssemblyName>
        <RootNamespace>Silo</RootNamespace>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Npgsql" Version="6.0.3" />
        <PackageReference Include="Microsoft.Orleans.Sdk" Version="4.0.0-preview1" />
        <PackageReference Include="Microsoft.Orleans.Server" Version="4.0.0-preview1" />
        <PackageReference Include="Microsoft.Orleans.Clustering.AdoNet" Version="4.0.0-preview1" />
    </ItemGroup>
</Project>
```

And this `Program.cs`

```
using System.Net.Sockets;
using Orleans;
using Orleans.Configuration;
using Orleans.Hosting;

var builder = WebApplication.CreateBuilder(args);

builder
    .Services
    .AddLogging(e => e.AddConsole().AddFilter(level => level >= LogLevel.Trace));

builder
    .Host
    .UseOrleans(builder => builder
        .Configure<ClusterOptions>(options =>
        {
            options.ClusterId = "MyClusterId";
            options.ServiceId = "MyServiceId";
        })
        .ConfigureEndpoints(11111, 30000, AddressFamily.InterNetwork, true)
        .UseAdoNetClustering(opt =>
        {
            opt.Invariant = "Npgsql";
            opt.ConnectionString = "foo";
        })
        // .UseLocalhostClustering()
        .ConfigureLogging(opt => opt.AddConsole().AddFilter(level => level >= LogLevel.Trace))
    );

var app = builder.Build();

var grainFactory = app.Services.GetRequiredService<IGrainFactory>();
var helloGrain = grainFactory.GetGrain<IHelloGrain>("friend");

app.MapGet("/hello", () => helloGrain.SayHello("hi from minimal API"));

await app.RunAsync();

public interface IHelloGrain : IGrainWithStringKey
{
    Task<string> SayHello(string greeting);
}

public class HelloGrain : IHelloGrain
{
    public Task<string> SayHello(string greeting) => Task.FromResult($"Hello, {greeting}!");
}
```

When doing `dotnet run` on NET6, the terminal will just hang. There is not any log message or exception saying the connection string is not valid. Of course I tried with a valid connection string and it is still the same. 

Then if I instead comment the `UseAdoNetClustering` and uncomment the `UseLocalhostClustering`, when executing `dotnet run` everything seems to work as expected.

Is AdoNet clustering not supported in v4.0.0-preview1 yet? Or is it another thing?

**Comment by JorgeCandeias** [comment]
> When doing dotnet run on NET6, the terminal will just hang.

Does it run from Visual Studio in the first place?

To note that on v3, you also need to set the endpoint and cluster information when using adonet or other providers, such as with:

```csharp
.ConfigureEndpoints(11111, 30000, AddressFamily.InterNetwork, true)
.Configure<ClusterOptions>(options =>
{
    options.ClusterId = "MyClusterId";
    options.ServiceId = "MyServiceId";
})
```

Not saying it's the problem here, and not sure if it still applies to v4, just noticed it from memory.

**Comment by pmorelli92** [comment]
Hi @JorgeCandeias thanks for the quick reply!

I've added the `ConfigureEndpoints` (my bad here) but it still does not work. I will modify the example on the issue to have this one added.

> Does it run from Visual Studio in the first place?

I am using Visual Studio Code and running everything on the terminal :)

**Comment by leedonhyun** [comment]
This is where hang happens

https://github.com/dotnet/orleans/blob/150dd5dbde80269db19a49fcaa66f050a6767589/src/Orleans.Runtime/Silo/Silo.cs#L137

**Comment by ReubenBond** [comment]
Apologies for the slow delay, this is a known bug which we still need to fix. Hopefully we can fix it for `4.0.0-preview2`

See #7588

**Comment by pmorelli92** [comment]
Great! Thanks for the information 👍

**Comment by ReubenBond** [comment]
Thanks for providing the details. I'll close this, so please refer to the aforementioned issue for updates.
