### ISSUE TITLE
Orleans.Reminders.DynamoDB uses the Scan operation

### ISSUE THREAD

**Issue by smiron** [dotnet/orleans#7657]
Hi,

In version `3.6.0` of `Orleans.Reminders.DynamoDB`, we use the DynamoDB `scan` operation in `ReadRows(GrainReference grainRef)`.
This is inefficient and it leads to a high level of RCUs being consumed as we scan the entire table when this method is being called.

A more efficient way of doing this would be to leverage a GSI with a PartitionKey of `ServiceId` and a SortKey of `GrainReference`.

**Comment by ReubenBond** [comment]
There was a recent discussion about this: https://github.com/dotnet/orleans/pull/7437#discussion_r779716388

Are you willing to open a PR?

**Comment by smiron** [comment]
Yes. I'll raise a PR with this fix.

**Comment by smiron** [comment]
@ReubenBond please have a look at the PR.

**Comment by ReubenBond** [comment]
Fixed by #7658
