### ISSUE TITLE
Unable to invoke grains to read from state store

### ISSUE THREAD

**Issue by moonytheloony** [dotnet/orleans#766]
Please review my client code at: https://github.com/moonytheloony/orleans

This code does not work and hangs indefinitely.
            var decodeGrain = GrainClient.GrainFactory.GetGrain<IDecodeGrain>("10.0.0.0");
            decodeGrain.DecodeDeviceMessage("10.0.0.0,VIOLET").Wait();
            var aggregatorGrain = GrainClient.GrainFactory.GetGrain<IAggregatorGrain>("aggregator");
            var data = aggregatorGrain.GetGrainInformation(0).Result;
            return this.Content(string.Format("Device: {0} Value: {1} Time: {2}", data.DeviceId, data.Value, data.Time));

This code works perfectly in dev test host.
Deployed code at: http://myorleansdemo.cloudapp.net/

**Comment by sergeybykov** [comment]
Your config in https://github.com/moonytheloony/orleans/blob/master/OrleansWebApplicaton/AzureClientConfiguration.xml appears hardcoded to `localhost`, which is fine for local testing but won't work for a real deployment.

**Comment by moonytheloony** [comment]
This deployment has a worker role hosting Orleans and  a web role front end which also acts as client. Since worker role exposes only internal endpoint, shouldn't it connect through localhost only?

Sent from my Windows Phone
________________________________

**Comment by sergeybykov** [comment]
The worker role instances run on different VMs, so you cannot talk to them via local host from the web role VMs.

**Comment by moonytheloony** [comment]
Isn't it correct that as long as role is able to connect to primary (table storage in this case). It doesn't need to connect to secondary nodes.

I have another sample which has localhost mentioned in its gateway setting and yet it is able to perform read operations on grains. However, in the same sample when I try to call a function to call a grain from another grain, it fails.

Sent from my Windows Phone
________________________________

**Comment by gabikliot** [comment]
>Isn't it correct that as long as role is able to connect to primary (table storage in this case). It doesn't need to connect to secondary nodes..

No, that is definitely incorrect.
First, table storage is **not** the primary
Second, all silos talk to each other, not just to the primary silo.
Third, the whole notion pf primary silo only exists in the local dev setup. In any full, regular, production setup Orleans does not even have the notion of primary. All sillos are equal and all are secondaries.
Please follow those instructions: http://dotnet.github.io/orleans/Step-by-step-Tutorials/Cloud-Deployment

**Comment by moonytheloony** [comment]
Thanks. Great help. Can I ask what should go inside gateway field of Orleans client, internal endpoint of one of the roles?

Sent from my Windows Phone
________________________________

**Comment by moonytheloony** [comment]
Thanks. Great help. Can I ask what should go inside gateway field of Orleans client, internal endpoint of one of the roles?

**Comment by moonytheloony** [comment]
This time I cleared everything from client configuration file. Yet the  application is stuck. http://myorleansdemo.cloudapp.net/

Code here: https://github.com/moonytheloony/orleans/blob/master/OrleansWebApplicaton/AzureClientConfiguration.xml

I hope to get this running soon for a demo.

**Comment by sergeybykov** [comment]
You seem to have commented out the call to `AzureClient.Initialize()` in https://github.com/moonytheloony/orleans/blob/master/OrleansWebApplicaton/Global.asax.cs. I don't see where you initialize the client.

**Comment by moonytheloony** [comment]
I thought it was causing error so I placed it inside every action in controller.

Sent from my Windows Phone
________________________________

**Comment by sergeybykov** [comment]
I see now. That should work. What's in the client log then? Does it find silos in the table? Is it able to connect to them?

**Comment by jthelin** [comment]
Take a look at the **AzureWebSample**, in particular the `Orleanaconfigruation.xml` silo settings that sample app uses.
https://github.com/dotnet/orleans/tree/master/Samples/AzureWebSample

Your OrleansWorker role is using silo config for local dev deployment, which won't work for Azure cloud deployment.

I also notice you are using Azure SDK v2.7 but you haven't added the necessary binding redirects for that to work.
http://dotnet.github.io/orleans/Deployment-and-Versioning-of-Dependencies

You might find it easier to start with the AzureWebSample as a start point and add your grains to that.

**Comment by moonytheloony** [comment]
Thanks guys. I got it working: http://myorleansdemo.cloudapp.net/
Updated the code.
@jthelin: I fixed the configuration file.
Another issue I fixed was to let the grain activations remain asynchronus. I removed calls with Wait() and Result() functions from grain invocations and everything started working.
