### ISSUE TITLE
How to Implement IMembershipTable?

### ISSUE THREAD

**Issue by fabiociconi** [dotnet/orleans#7666]
HI,

I would like to know how I implement the IMembershipTable to delete entries from  OrleansMembershipTable.

I am using MS Orleans 3.5.1

please let me know if you need more details.

**Comment by ReubenBond** [comment]
Hi @fabiociconi, are you looking to enhance an existing membership table provider or to write a new one? If you are wanting to modify an existing provider, which one?

**Comment by fabiociconi** [comment]
Hi @ReubenBond. Actually is more a question of how to use CleanupDefunctSiloEntries using the IMembershipTable implementation.
Now, I am getting the message "CleanupDefunctSiloEntries operation is not supported by the current implementation of IMembershipTable. Disabling the timer now.".  As I need to remove all status 6 in the MembershipTable, I think it could be done through SQL or implement the IMembershipTable interface. Is that, right? Is it clear?


Please let me know if you need more information

**Comment by ReubenBond** [comment]
I think we should use the existing issue for this: https://github.com/dotnet/orleans/issues/7171
I've renamed that issue to reflect the desire, so I'll close this and we can use that instead. Apologies for not responding on that issue already.

**Comment by fabiociconi** [comment]
Thank you
