### ISSUE TITLE
Sample content for running Orleans on AKS

### ISSUE THREAD

**Issue by bradygaster** [dotnet/orleans#7675]
Create conceptual articles demonstrating two different scenarios with Microsoft Orleans and Azure Kubernetes Service. This article should highlight the following areas: 

- Running an application with 2 or more Silos containing various grain implementations. 
- Using Kubernetes clustering and linking to (or improving) the existing [Orleans + Kubernetes doc page](https://docs.microsoft.com/en-us/dotnet/orleans/deployment/kubernetes) and [related video](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiwx97Ckvz2AhXADjQIHTOPCg0QwqsBegQIBRAB&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dda9u5tqw-eo&usg=AOvVaw0uZkVJUvau7ctS6Py7WIV2) Reuben and Cecil completed. 
- Using Redis for clustering.
- Implementing a KEDA Scaler for sizing a cluster. (stretch)

## Sample

I've created an initial example of such a scenario in this repo

https://github.com/bradygaster/WoodgroveBank

**Comment by ReubenBond** [comment]
Fixed: https://learn.microsoft.com/en-us/samples/dotnet/samples/orleans-voting-sample-app-on-kubernetes/
