### ISSUE TITLE
DynamoDB Reminders fails to initialize if tables are pre-created with OnDemand capacity

### ISSUE THREAD

**Issue by smiron** [dotnet/orleans#7682]
Steps to reproduce:
1. Create the grain storage and reminders DynamoDB tables and indexes with OnDemand capacity
2. Configure the library to use the tables created at step 1 (`DynamoDBReminderStorageOptions.TableName`)

Expected results:
The tables created at step 1 are used.

Actual results:
The reminders storage fails to initialize with the below issue

Unhandled exception. Amazon.DynamoDBv2.AmazonDynamoDBException: One or more parameter values were invalid: ProvisionedThroughput must be specified for index: ServiceIdIndex,ServiceIdGrainReferenceIndex

**Comment by ReubenBond** [comment]
Fixed by @smiron in #7681
