### ISSUE TITLE
Calling IGrainFactory.GetGrain<T>(pk) from constructor is a bad practice ?

### ISSUE THREAD

**Issue by fernandozago** [dotnet/orleans#7688]
I'm doing some experiments with the Orleans.

I tried to find the answer but i could not...

Is it a bad idea reusing another grain gathered from the constructor like this ?

```csharp
public class MainGrain : Grain, IMainGrain
{
    private readonly IOtherGrain _otherGrain;

    public MainGrain(IGrainActivationContext context, IGrainFactory grainFactory) 
    {
        _otherGrain = grainFactory.GetGrain<IOtherGrain>(context.GrainIdentity.PrimaryKeyString);
    }

    public ValueTask<Item> GetCurrentValue() =>
        _otherGrain.GetItem();

   //others methods here
}
````

MainGrain stay in memory longer then IOtherGrain... (Calling GetCurrentValue() may call a already collected grain)

**Comment by ReubenBond** [comment]
It's fine to call GetGrain in the grain's constructor.

GetGrain doesn't return the grain itself, just a reference to it. It's similar to a URL or a typed HttpClient wrapper. It's a fast, synchronous operation and doesn't perform any IO.

**Comment by fernandozago** [comment]
> It's fine to call GetGrain in the grain's constructor.
> 
> GetGrain doesn't return the grain itself, just a reference to it. It's similar to a URL or a typed HttpClient wrapper. It's a fast, synchronous operation and doesn't perform any IO.

Thanks for the quick reply!

Even if the `OtherGrain` eventually gets `Deactivated`, it should reactivate again when i call `GetItem()` ?

Thank you @ReubenBond

**Comment by ReubenBond** [comment]
That's exactly right, Orleans will make sure to activate it on-demand for you
