### ISSUE TITLE
Not all (streams)queues are pulled in heterogeneous cluster

### ISSUE THREAD

**Issue by wangjia184** [dotnet/orleans#7689]
A  heterogeneous cluster with 7 silos.
4 of them do not call `AddAzureQueueStreams` on startup.
Only 3 of them call `AddAzureQueueStreams` with 5 Azure queues.

It seems queue balancer still tries to distribute these 5 Azure queues over 7 silos.  
While only 3 silos are able to pull but not all 5 queues are assigned to them.
Hence it results in occational message leaking (actually the message is produced into Azure queue but that queue is not pulled by any silo).

![image](https://user-images.githubusercontent.com/2765840/163355621-e140ea31-73f2-4744-b108-35dfc94569b1.png)

How to instruct queue balancer to skip current silo on startup?  or is there a way to disable pulling agent in certain silo?

**Comment by benjaminpetit** [comment]
Yep, it's not a supported configuration. All silos need to have the same configuration, but they can support different grain types.

**Comment by wangjia184** [comment]
I didn't notice there was a duplicated [issue](https://github.com/dotnet/orleans/issues/7037#issuecomment-810549265).
