### ISSUE TITLE
1 Minute wait for testing

### ISSUE THREAD

**Issue by chasit** [dotnet/orleans#7690]
Hi there.

I've been trying to test different Grains in Orleans for the past week. I used this (https://dotnet.github.io/orleans/docs/tutorials_and_samples/testing.html) tutorial for creating my own testing silo. 
The grain I am trying to test is a persistent grain which only writes and reads making use of `state.WriteStateAsync()` and with returning making use of `Task.FromResult(state)`.

My test looks like this. However the 'news' variable in the test will always be null if there is not a delay of 60 seconds or more after calling 'AddNewsItem' and before the calling the 'Get' method. 
If the delay is added the 'news' variable will have the correct values added in the 'AddNewsItem' method.

The time of 60 seconds seems oddly specific, anyone got any ideas? 

I've provided as much information as I can. Thanks in advance.
The test

```
var guid = Guid.NewGuid();

            var newsitem = ()

            var newsitemgrain = this._cluster.GrainFactory.GetGrain<INewsItemGrain>(guid);

            await newsitemgrain.AddNewsItem(newsitem);
            var news = await newsitemgrain.Get();


            Asserts here

```
Adding news item in grain
```
  public async Task AddNewsItem(NewsItemModel newsitem)
    {
        this.newsItem.State = newsitem;
        await this.newsItem.WriteStateAsync();
    }
```

Getting a news item in grain
```
public async Task<NewsItemModel> Get()
    {
        return await Task.FromResult(this.newsItem.State);
    }
```

My Cluster Fixture looks like this:

```
public class ClusterFixture 
{
    public ClusterFixture()
    {
        var builder = new TestClusterBuilder();
        builder.AddSiloBuilderConfigurator<SiloConfigurator>();
        this.Cluster = builder.Build();
        this.Cluster.Deploy();
    }

    public void Dispose()
    {
        this.Cluster.StopAllSilos();
    }

    public TestCluster Cluster { get; private set; }

    public static FakeGrainStorage GrainStorage { get; } = new();
    public class SiloConfigurator : ISiloConfigurator
    {
        public void Configure(ISiloBuilder hostBuilder)
        {
            hostBuilder
                .ConfigureServices(services => {
                    services.AddSingleton<IGrainStorage>(GrainStorage);
                })
                .UseLocalhostClustering()
                .AddMemoryGrainStorage("OrleansStorage");
        }
    }
}

```
My FakeGrainStorage looks like this:

```
public class FakeGrainStorage : IGrainStorage
    {
        public ConcurrentDictionary<GrainReference, IGrainState> Storage { get; } = new();

        public Task ClearStateAsync(string grainType, GrainReference grainReference, IGrainState grainState)
            => Task.FromResult(Storage.TryRemove(grainReference, out _));

        public Task ReadStateAsync(string grainType, GrainReference grainReference, IGrainState grainState)
            => Task.FromResult(Storage.TryGetValue(grainReference, out grainState));

        public Task WriteStateAsync(string grainType, GrainReference grainReference, IGrainState grainState)
            => Task.FromResult(Storage.TryAdd(grainReference, grainState));
    }

```

**Comment by ReubenBond** [comment]
The 60s is odd. What happens if you call `UseMemoryGrainStorageAsDefault()` instead of using your custom storage provider?
Are there multiple test cases running or just the one?

**Comment by JorgeCandeias** [comment]
Just a note that this code is incorrect:

```csharp
public Task ReadStateAsync(string grainType, GrainReference grainReference, IGrainState grainState)
    => Task.FromResult(Storage.TryGetValue(grainReference, out grainState));
```

This code attempts to replace the `grainState` argument but that argument in `ReadStateAsync()` is not market with `out`, so this won't have any effect.

The implementation needs to hydrate the passed in `grainState` argument like [in this example](https://github.com/dotnet/orleans/blob/d4cead8950f73e3de15afddf32e69926422f0a31/src/Azure/Orleans.Persistence.AzureStorage/Providers/Storage/AzureTableStorage.cs#L78).

Also note that, if your tests do not require inspecting the underlying storage, then there's no need to create fakes to begin with, and using the built-in in-memory provider as the default, as @ReubenBond suggested, is the way to go.

**Comment by chasit** [comment]
I've found a temporary fix for this issue. However, this is not the final solution I am looking for. 
In `FakeGrainStorage` I added 
```
public TState GetGrainState<TState>(IGrain grain)
    => Storage.TryGetValue((GrainReference)grain, out var state) ? (TState)state.State : default;
```

I am calling this method from my unit test with the NewsItemModel the Grain needs `ClusterFixture.GrainStorage.GetGrainState<NewsItemModel>(newsitemgrain);`

This returns the correct state of the model with all the changes being made. Unfortunately I have to remove the 'OrleansStorage' in the PersistentState in the Grain `[PersistentState("newsitem", "OrleansStorage")]` and make use of the `AddMemoryGrainStorageAsDefault()` as @ReubenBond suggested. Although the unit tests will run and give back the correct state, removing the storageName from the PersistentState has the downside of not working anymore with the ADO.net provider we're using for our database. Meaning we have to remove and add 'OrleansStorage from all our grains so that unit tests can be ran.

**Comment by JorgeCandeias** [comment]
> Unfortunately I have to remove the 'OrleansStorage' in the PersistentState in the Grain `[PersistentState("newsitem", "OrleansStorage")]` and make use of the `AddMemoryGrainStorageAsDefault()` as @ReubenBond suggested.

You can add the same storage provider multiple times, under different names:

```csharp
hostBuilder
    .AddMemoryGrainStorageAsDefault()
    .AddMemoryGrainStorage("OrleansStorage")
    .AddMemoryGrainStorage("SomeOtherName")
```

The above works for all providers, including the ado.net one.

**Comment by chasit** [comment]
I've added the `.AddMemoryGrainStorage("OrleansStorage")` in the SiloConfigurator:
```
public class SiloConfigurator : ISiloConfigurator
    {
        public void Configure(ISiloBuilder hostBuilder)
        {
            hostBuilder.ConfigureServices(services => {
                services.AddSingleton<IGrainStorage>(GrainStorage);
            })
            .UseLocalhostClustering()
            .AddMemoryGrainStorageAsDefault()
            .AddMemoryGrainStorage("OrleansStorage");
        }
    }
```

Upon doing that no change is seen in the GetGrainState method, the `state` will be null. Looking at further testing and debugging it seems that when there is a storageName provided in the PersistentState it will always create a MemoryStore with the name of the storageName property seen here (even with .AddMemoryGrainStorageAsDefault() removed).
![image](https://user-images.githubusercontent.com/71491544/164085939-f0759cb5-cbce-442d-98be-af047a342060.png)
![image](https://user-images.githubusercontent.com/71491544/164085976-1c76d38a-76b6-4183-ac41-4ba3daf44cd1.png)

When the storageName property is removed the correct storage is used (FakeGrainStorage), even without any MemoryGrainStorage.
![image](https://user-images.githubusercontent.com/71491544/164086141-527acae0-1a45-4370-ae10-6280a87c4b4d.png)
![image](https://user-images.githubusercontent.com/71491544/164086289-e1c02f71-2710-4aa3-92e1-bfac6cca5502.png)

**Comment by ReubenBond** [comment]
Apologies for the delay in getting back to you, @chasit. When you're using `TestClusterBuilder`, you must not configure clustering manually, since the point of the `TestClusterBuilder` is that it builds a test cluster for you (which involves configuring clustering).

Please remove the `UseLocalhostClustering()` line from your code.

We should throw when the TestClusterBuilder's clustering configuration is overridden by the user, but we don't throw today (there are cases in our tests where we do it on purpose, eg for testing clustering itself).

As for the issue regarding defaults for storage, I believe that's an issue in how named storage providers are registered: they register a default, non-named instance of the provider. Could you please open a separate issue for this?

**Comment by chasit** [comment]
Thank you for your response @ReubenBond, removing the `UseLocalhostClustering()` has indeed solved the issue.
Now only the `AddMemoryGrainStorage()` remains with the name of the storage provider used in the PersistentState and using multiple MemoryGrainStorages works as well. 
Regarding the 2 lines of your comment, the (ADO.net) storage provider does have a default implementation of `AddAdoNetGrainStorageAsDefault()` however I'm using the `AddAdoNetGrainStorage(name)` with a storage name (same as in PersitentState). Switching this to Default and removing the storageName will work the the `AddMemoryGrainStorage()`.

**Comment by ReubenBond** [comment]
It's a bug in the implementation of "keyed services", which the storage providers use. We should fix it. If you can open a new issue with your code sample and link back to this one, I'd greatly appreciate it. That helps us to track it.
