### ISSUE TITLE
IHostBuilder.UseOrleans() should be IServiceCollection.AddOrleans()

### ISSUE THREAD

**Issue by Timovzl** [dotnet/orleans#7695]
I was a bit surprised to find that Orleans had taken the liberty of replacing the entire host and host builder for its default registration method. (Edit: I just read that Orleans' host predates .NET's generic host.) Exploring how to co-host ASP.NET Core and Orleans, I was happy to discover a less brazen alternative: the `UseOrleans()` extension on `IHostBuilder`.

It works, but there are a few issues with it:

- The `Use` prefix suggests that it adds middleware, which (looking at the code) it does not. The `Add` prefix is what is normally used to add dependencies. _(A notable exception is when we are configuring the details of an outer `Add*`, e.g. `services.AddDbContext<MyContext>(options => options.UseSqlServer...`.)_
- By extending `IHostBuilder` instead of `IServiceCollection` (the standard), we are reducing discoverability.
- By extending `IHostBuilder` instead of `IServiceCollection`, we become less resilient to changes. For example, it took me a while to figure out how to port this design to the [new `WebApplication.CreateBuilder` approach](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-6.0). Things took a number of changes and become significantly less pretty.

The current `UseOrleans` implementation (decompiled) is as follows:

```cs
public static IHostBuilder UseOrleans(this IHostBuilder hostBuilder, Action<HostBuilderContext, ISiloBuilder> configureDelegate)
{
	if (configureDelegate == null) throw new ArgumentNullException("configureDelegate");

	SiloBuilder siloBuilder;
	if (!hostBuilder.Properties.ContainsKey("SiloBuilder"))
	{
		siloBuilder = new SiloBuilder(hostBuilder);
		hostBuilder.Properties.Add("SiloBuilder", siloBuilder);
	}
	else
	{
		siloBuilder = (SiloBuilder)hostBuilder.Properties["SiloBuilder"];
	}

	siloBuilder.ConfigureServices(delegate (HostBuilderContext context, IServiceCollection services)
	{
		configureDelegate(context, siloBuilder);
	});
	return hostBuilder;
}
```

Looking at the implementation, I would guess that `IHostBuilder` was chosen as the target to extend simply to be able to rely on its properties dictionary. This pattern is easily replicated by extension methods _without_ access to such a dictionary: the extension method can access a private static `ConditionalWeakTable` in its own class, which simply associates a `SiloBuilder` with an `IServiceCollection`. And thanks to `ConditionalWeakTable`, if the latter is discarded, then so is the reference to the former.

With the obvious obstacle out of the way, I propose that the following registration extension method be added:

```cs
public static IServiceCollection AddOrleans(this IServiceCollection services, Action<ISiloBuilder> configurationDelegate)
```

In my opinion, it does not matter too much whether `UseOrleans()` is removed - the new method is more discoverable and standard-conformant, and thus likely to be discovered sooner.

**Comment by ReubenBond** [comment]
The `IServiceCollection.AddOrleans()` method exists in `main`, but if you can make a PR to backport it to the `3.x` branch without introducing semantic differences with what exists today, then we'd happily take it.

`UseOrleans` is akin to `ConfigureWebDefaults`. It could be `ConfigureOrleans` instead. I'm fine with unifying around `AddOrleans` on both `IHostBuilder` and `IServiceCollection`, too.

As far as the new WebApplicationBuilder is concerned, use the `.Host` property, eg. `builder.Host.UseOrleans(...)`.

> I was a bit surprised to find that Orleans had taken the liberty of replacing the entire host and host builder for its default registration method. Exploring how to co-host ASP.NET Core and Orleans, I was happy to discover a less brazen alternative: the UseOrleans() extension on IHostBuilder.

FYI, the .NET Generic Host was the result of collaboration between the Orleans team and the ASP.NET team from the days before we merged to form one team. See https://github.com/dotnet/orleans/issues/2936 and https://github.com/aspnet/Hosting/issues/1163

**Comment by Timovzl** [comment]
@ReubenBond I see that you guys are way ahead of me. 😄

For my understanding, what is the difference between [`AddOrleans`](https://github.com/dotnet/orleans/blob/main/src/Orleans.Runtime/Hosting/GenericHostExtensions.cs#L52) (in Orleans.Runtime) and [`AddOrleansClient`](https://github.com/dotnet/orleans/blob/main/src/Orleans.Core/Hosting/GenericHostExtensions.cs#L50) (in Orleans.Core), and which is preferred?

> The IServiceCollection.AddOrleans() method exists in main, but if you can make a PR to backport it to the 3.x branch without introducing semantic differences with what exists today, then we'd happily take it.

Great, I'll see if I can find the time to do so.

> FYI, the .NET Generic Host was the result of collaboration between the Orleans team and the ASP.NET team from the days before we merged to form one team.

Interesting. Nice work!

**Comment by ReubenBond** [comment]
AddOrleans is for server (silo) processes and AddOrleansClient is for client processes (which don't host grains)
