### ISSUE TITLE
4.0 Preview StreamId with compound key, when sent from external eventhub producer

### ISSUE THREAD

**Issue by RbsTechOnline** [dotnet/orleans#7700]
Given

```cs
[ImplicitStreamSubscription(Constants.StreamNamespace)]
public class ConsumerGrain : Grain, IConsumerGrain, IStreamSubscriptionObserver, IAsyncObserver<SomeClass>
{
   ...
```
and

```cs
public interface IConsumerGrain : IGrainWithGuidCompoundKey
{
   ...
```
I would have assumed to send a compound key externally to an event hub stream would be to internally just pack the GUID and compound key into the partition key of the event hub

```cs
var options = new SendEventOptions { PartitionKey = grainId.ToString("N") + "+" + extKey};
```

and pass it in to the `StreamId`  via `StreamId.Create`  as a complete string variable in the `EventHubDataAdapter` , assuming the StreamId was packed like a GrainReference

```cs
public override StreamId GetStreamIdentity(EventData queueMessage)
{
     var ns = (string)queueMessage.Properties[StreamNamespace];
     return StreamId.Create(ns, queueMessage.PartitionKey);
}
```
Obviously what i have isn't working, 

```
System.ArgumentException: streamId
   at Orleans.Streams.DefaultStreamIdMapper.GetGuidKey(StreamId streamId, Boolean includeNamespaceInGrainId) in /_/src/Orleans.Streaming/Core/DefaultStreamIdMapper.cs:line 47
   at Orleans.Streams.DefaultStreamIdMapper.GetGrainKeyId(GrainBindings grainBindings, StreamId streamId) in /_/src/Orleans.Streaming/Core/DefaultStreamIdMapper.cs:line 36
   at Orleans.Streams.ImplicitStreamSubscriberTable.MakeConsumerReference(IInternalGrainFactory grainFactory, InternalStreamId streamId, StreamSubscriber streamSubscriber) in /_/src/Orleans.Streaming/PubSub/ImplicitStreamSubscriberTable.cs:line 254
   at Orleans.Streams.ImplicitStreamSubscriberTable.GetImplicitSubscribers(InternalStreamId streamId, IInternalGrainFactory grainFactory) in /_/src/Orleans.Streaming/PubSub/ImplicitStreamSubscriberTable.cs:line 118
   at Orleans.Streams.ImplicitStreamPubSub.RegisterProducer(InternalStreamId streamId, IStreamProducerExtension streamProducer) in /_/src/Orleans.Streaming/PubSub/ImplicitStreamPubSub.cs:line 31
   at Orleans.Streams.PersistentStreamPullingAgent.PubsubRegisterProducer(IStreamPubSub pubSub, InternalStreamId streamId, IStreamProducerExtension meAsStreamProducer, ILogger logger) in /_/src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs:line 778
   at Orleans.Streams.PersistentStreamPullingAgent.<>c__DisplayClass48_1.<<RegisterAsStreamProducer>b__0>d.MoveNext() in /_/src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs:line 790
--- End of stack trace from previous location ---
   at Orleans.Internal.AsyncExecutorWithRetries.<>c__DisplayClass1_0.<<ExecuteWithRetries>b__0>d.MoveNext() in /_/src/Orleans.Core/Async/AsyncExecutorWithRetries.cs:line 26
--- End of stack trace from previous location ---
   at Orleans.Internal.AsyncExecutorWithRetries.ExecuteWithRetriesHelper[T](Func`2 function, Int32 callCounter, Int32 maxNumSuccessTries, Int32 maxNumErrorTries, TimeSpan maxExecutionTime, DateTime startExecutionTime, Func`3 retryValueFilter, Func`3 retryExceptionFilter, IBackoffProvider onSuccessBackOff, IBackoffProvider onErrorBackOff) in /_/src/Orleans.Core/Async/AsyncExecutorWithRetries.cs:line 143
```

We end up here in the `DefaultStreamIdMapper`, which is not going to work.

```cs

private static IdSpan GetGuidKey(StreamId streamId, bool includeNamespaceInGrainId)
{
    var key = streamId.Key.Span;
    if (!Utf8Parser.TryParse(key, out Guid guidKey, out var len, 'N') || len < key.Length) throw new ArgumentException(nameof(streamId));

    return includeNamespaceInGrainId
        ? GrainIdKeyExtensions.CreateGuidKey(guidKey, streamId.GetNamespace())
        : GrainIdKeyExtensions.CreateGuidKey(guidKey);
}

```

Trying to ignore the compound part of the key when sending the event hub message, results in the compound component of the GrainRefrence being the namespace of the stream. 

I am only starting to depick how the stream plumbing is working in orleans. Is there a solve for compound keys working with `IGrainWithGuidCompoundKey` when sent from an external event hub producer? Its entirely likely i have missed something simple

...

`EventDataAdapter `gleaned from various docs added for completeness

```cs
public class CustomDataAdapter : EventHubDataAdapter
{
    private const string StreamNamespace = "StreamNamespace";

    public CustomDataAdapter(Serializer serializationManager) : base(serializationManager) {}

    public override StreamId GetStreamIdentity(EventData queueMessage)
    {
        var guid = Guid.Parse(queueMessage.PartitionKey);
        var ns = (string)queueMessage.Properties[StreamNamespace];
        return StreamId.Create(ns, guid);
    }

    protected override IBatchContainer GetBatchContainer(EventHubMessage eventHubMessage)
    {
        return new CustomBatchContainer(eventHubMessage);
    }
}

public class CustomBatchContainer : IBatchContainer
{
    private readonly byte[] _payload;

    public CustomBatchContainer(EventHubMessage eventHubMessage)
    {
        StreamId = eventHubMessage.StreamId;
        StreamGuid = Guid.Parse(StreamId.GetKeyAsString());
        StreamNamespace = eventHubMessage.StreamId.GetNamespace();
        SequenceToken = new EventHubSequenceTokenV2(eventHubMessage.Offset, eventHubMessage.SequenceNumber, 0);
        _payload = eventHubMessage.Payload;
    }

    public Guid StreamGuid { get; }

    public string StreamNamespace { get; }

    public StreamSequenceToken SequenceToken { get; }

    public bool ImportRequestContext() => false;

    public StreamId StreamId { get; }

    public IEnumerable<Tuple<T, StreamSequenceToken>> GetEvents<T>()
    {
        var evt = JsonSerializer.Deserialize<T>(_payload);
        return new[] { Tuple.Create(evt, SequenceToken) };
    }
}
```

**Comment by RbsTechOnline** [comment]
Ok after looking at code a lot more, i see this is currently not possible with the `DefaultStreamIdMapper` as it seemingly is trying to pin guids/ints to namespaces based on the legacy grain key type. I am wondering if this could be easily achieved by implementing a custom implementation of `IStreamIdMapper` ? Or maybe i am missing something well known with implicit streams and compound keys?

**Comment by nkosi23** [comment]
If I am not mistaken currently the identifier of implicit stream subscriptions may only be of Guid type, support for other key types will be implemented in 4.0 as per the conclusion reached [in this ticket](https://github.com/dotnet/orleans/issues/1121).

**Comment by RbsTechOnline** [comment]
@nkosi23 thanks for the link, it allowed me to find a few more issues related to streaming and GUID and understand a little more about the problem. however i have still yet to find a work around, though seemingly what i am trying to achieve seems possible, though i am not entirely sure how.

**Comment by benjaminpetit** [comment]
The `DefaultStreamIdMapper` is capable of handling grain with a compound guid key, assuming your `StreamId` is compatible.

In your `GetStreamIdentity` implementation you need to construct the `StreamId` using a `Guid`, not a `string`

**Comment by RbsTechOnline** [comment]
@benjaminpetit yeah, though `DefaultStreamIdMapper` is only capable of `guid`, `int` or `string`, however the need was to have a grain implementing `IGrainWithGuidCompoundKey` which would work with and Implicit stream namespace, however i think the limitation stems from the fact when a `Guid` compound key is used, the `Guid` gets stored in the lower order bytes and the namespace getting stored in higher order bytes (the extension) of the `IdSpan`.

You will need to forgive my understanding here, as i was completely new to Orleans a couple of months ago, and learnt most things from trawling through the docs to 3x and the source code to 4.0 and the conversion process of a hand full of providers. 

I haven't debugged the current work around as yet, however, using a grain with a string key, and StreamId with a string key and namespace, implicit streams with a namespace still works as intended (at least from basic tests)., which has enabled me to write a storage provider that takes a string key and break it apart to get all the partition keys i have needed for cosmos DB.

---

I am wondering whether both GrainIds and and StreamIds should just allow an arbitrary amount of primitive composite keys by just holding an index array of key offsets in the array, and letting the user deal with type safety.  

Obviously equality and hashes would work the same.
 
As an example, It seems fairly doable to implement something like 

`GetGrain<T>(SomePrimitive).With(SomePrimitive).With(SomePrimitive)`

and alternatively

`IAddressable.GetKey(out somePrimitiveType).WithKey(out someOtherType)`

Anyway just a thought.

**Comment by benjaminpetit** [comment]
Technically in 4.0 there is no restriction for the grain key, you could use a byte array as the identifier, so you could already do what you are suggesting.

Although I think it would be better to transform everything to string so logging is more readable.

**Comment by RbsTechOnline** [comment]
@benjaminpetit thanks for the help, yeah i been on a steep learning curve, though i am starting to be in a better place now. 

Quick question, is there any way to set the prefetch value on event hub stream provider. That's to say, my cosmos check pointer is holding the correct offset, however i notice when i start the silo its seemingly prefetching a certain number of events which Maybe a few hundred) and causing grains to activate unnecessarily, note the grains are starting with the right sequence token, and not firing OnNext.  Is this expected behavior? After searching through the code, i can see there is Prefetch Count, though i cant see exactly how its implemented or how to actually configure the value. Or whether its doing what i think its doing

**Comment by RbsTechOnline** [comment]
@benjaminpetit thanks for your time, very much appreciated.
