### ISSUE TITLE
Exception in IsPrimaryKeyBasedOnLong disallow to use Guid Grains in AdoNet persistence

### ISSUE THREAD

**Issue by Dred95** [dotnet/orleans#7702]
Method **IsPrimaryKeyBasedOnLong** used in AdoNet throws exception instead of **false**

https://github.com/dotnet/orleans/blob/f9299762e433ed2b426f7a6e676776d224f13f52/src/Orleans.Core.Abstractions/Core/GrainExtensions.cs#L147-L161

https://github.com/dotnet/orleans/blob/f9299762e433ed2b426f7a6e676776d224f13f52/src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/AdoNetGrainStorage.cs#L488-L500

Because of exception it is impossible to use any Grains with guid.

**Comment by benjaminpetit** [comment]
Fixed by #7704
