### ISSUE TITLE
Is there an option to debug why the Orleans serializer generation fails and Orleans falls back to the BinaryFormatter?

### ISSUE THREAD

**Issue by SeppPenner** [dotnet/orleans#7705]
I've switched a project from some not Orleans-ready code to Orleans grains. Since there a lot of models have been used, I just more or less used them as they were (Removing some obvious types that can't be serialized). I looked over all used models in the grain calls several times, but still something can't be serialized properly and the following error is thrown:

```csharp
System.NotSupportedException: "BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information."
```

Since I didn't activate the binary formatter (and I don't want to) as it's unsafe, I tried to figure out why Orleans would fall back to the binary serializer with no success yet.

Is there a way to get debug information on which type (class or then field or property) can't be serialized? Or is there a simple way to call the Orleans serializer from external to check this?

With just the above message, it's really a pain to find the issue...

**Comment by SeppPenner** [comment]
In my case, a `protected` logger was serialized which caused the issue, so it's solved in my project for now. Still, it would be good to get information on which property / field / class is not serialized properly if somehow possible as debugging is really a pain else...

**Comment by ReubenBond** [comment]
This is much easier now with 7.x, since failure to generate a serializer results in a build failure

**Comment by SeppPenner** [comment]
> This is much easier now with 7.x, since failure to generate a serializer results in a build failure

Thanks for the reply. We definitely need to upgrade to v7 than sometime... :D
