### ISSUE TITLE
[Question] Why need to create GrainServiceClient for GrainService?

### ISSUE THREAD

**Issue by zeinali0** [dotnet/orleans#7706]
Hi

why do we need to create a `GrainServiceClient` for each `GrainService` to access them?

I think Orleans can hide the need of `GrainServiceClient` and let developer access them just like other grains.

`grainfactory.GetGrain<IMyServiceGrain>()`;

**Comment by JorgeCandeias** [comment]
> why do we need to create a `GrainServiceClient` for each `GrainService` to access them?

The client is itself an optional extensibility point. We can use it for things like validation rules, or fetching additional data, or any other work, which run *before* the message is sent across the network to the appropriate grain service instance. We can even manipulate the message before it flies away, like with an outbound call filter. We can omit the client altogether too.

> I think Orleans can hide the need of `GrainServiceClient` and let developer access them just like other grains.

With the newer code generation capabilities in dotnet, perhaps this could become a generated partial class. I think it could cause confusion to mix it with the `GetGrain<T>(key)` method.

"GrainServices" share some properties of grains but they are not grains themselves, nor do they work like them. Their unique utility is that they allow us to distribute ownership of some work or load across the cluster in a ring-based way, just like a DHT does. That's what the [RingRange](https://github.com/dotnet/orleans/blob/f9299762e433ed2b426f7a6e676776d224f13f52/src/Orleans.Runtime/Services/GrainService.cs#L27) property is for. When the cluster grows or shrinks, so does the ownership range of each grain service instance changes, in an inverse fashion. For example, the reminder subsystem uses a grain service to allow it to load reminder entities in a balanced way across the cluster, before it fires them. If we don't need ring functionality for a feature, we can probably do it with regular grains instead.
