### ISSUE TITLE
Move all hosting extension methods to Orleans.Hosting namespace

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#7707]
For the sake of keep things clear together, we should move all the hosting extensions to `Orleans.Hosting`. To give an example, `UseLinuxEnvironmentStatistics()` is at `Orleans.Statistics`.

Moving it and all other `UseXXX`/`AddXXX` extension methods that are tied to `IServiceCollection` or `ISiloBuilder` to `Orleans.Hosting` will improve discoverability.

**Comment by ReubenBond** [comment]
We should move all extensions into the common hosting namespace.
Ideally, we should consider adding the hosting ns to global usings, too

**Comment by galvesribeiro** [comment]
Yeah, I agree. I'm not sure if/how we can add `global using Orleans.Hosting;` from within an MSBuild props file injected when the user adds Orleans packages but that would definitively be a big enhancement in dev experience.

**Comment by ReubenBond** [comment]
TODO list for this:

* [ ] All `IServiceCollection` extensions into the `Microsoft.Extensions.DependencyInjection` namespace
* [ ] All `IHostBuilder` extensions should be in `Microsoft.Extensions.Hosting` namespace
* [ ] All `ISiloBuilder` and `IClientBuilder` extensions should be in the `Orleans.Hosting` namespace
* [ ] `Orleans.Hosting` should be added to global usings by the `Microsoft.Orleans.Sdk` package
