### ISSUE TITLE
AzureTable ReminderService needs to sanitize RowKey

### ISSUE THREAD

**Issue by mhertis** [dotnet/orleans#772]
AzureTable ReminderService tries to register grain reminder with disallowed characters (https://msdn.microsoft.com/library/azure/dd179338.aspx). It should escape disallowed characters.

@sergeybykov pointed out where RowKey is constructed: https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Storage/RemindersTableManager.cs#L49. 

While @gabikliot mentioned that this is already implemented in Azure Table Storage provider: https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs#L345.

Can not promise that I would manage to prepare a PR anytime soon.

**Comment by mhertis** [comment]
Now there is another problem. Now that my grain id does not have disallowed characters it seems that is too long. On Table Entity update I get StorageException `HTTP Error 400. The request URL is invalid`. If I shorten grain id its all ok.

More explicit exception message will help other users facing this issue.

**Comment by sergeybykov** [comment]
@mhertis Do you see the 400 error with https://github.com/dotnet/orleans/pull/774?

**Comment by mhertis** [comment]
No, I have manually removed disallowed characters from Grain Id. Only after I have also shorten Grain Id, reminder was successfully upserted.

**Comment by gabikliot** [comment]
The fix in #774 will now also check the length limit and [throw an explicit exception telling that](https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Storage/AzureStorageUtils.cs#L301).

**Comment by sergeybykov** [comment]
Are you getting 400 from emulator or the service? There are important differences between them as mentioned in https://azure.microsoft.com/en-us/documentation/articles/storage-use-emulator/
>
•The storage emulator supports partition key and row key property values of less than 512 bytes each. Additionally, the total size of the account name, table name, and key property names together cannot exceed 900 bytes.
•The total size of a row in a table in the storage emulator is limited to less than 1 MB.

**Comment by mhertis** [comment]
Yes, it was on emulator. I was not aware of such differences between emulator and the service. Can't wait for next release =D

**Comment by gabikliot** [comment]
OK, so seems like we can close this issue, right?
