### ISSUE TITLE
Some Orleans exceptions don't have proper serialization constructor, so can't pass client-silo trust boundary

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#775]
Writing this to capture these findings for future searches or references (as per discussion on gitter):

There is at least 2 exceptions in Orleans - `DuplicateActivationException` and `NonExistentActivationException` which aren't inherited from `OrleansException` class, but directly from `Exception` class. Generally, it's a good practice to make your custom exception serializable - so it can be serialized in one domain (Orleans Silo) and deserialized in another (Orleans Client). One's can find some nice guidelines on how to implement such constructor [here](http://stackoverflow.com/questions/94488/what-is-the-correct-way-to-make-a-custom-net-exception-serializable)

Also if custom exception doesn't have Deserialization constructor like this: 
`protected DuplicateActivationException(SerializationInfo info, StreamingContext context): base(info, context)`

when such exception will be thrown .NET indicate the problem with an error like this:
```
Exc level 0: System.Runtime.Serialization.SerializationException: **The constructor to deserialize an object of type 'Orleans.Runtime.Catalog+DuplicateActivationException' was not found.**
 ```

@veikkoeeva wrote: I have an application depdendent concern: The boundary between a silo and a client looks like a natural trust boundary, so by that token I personally would be wary of serializing exceptions from a silo to a client. It may the case the silo and client are controlled by the same entity, like a web server and behind a WebAPI connecting to a silo, but that might also not be the case (it might be suboptimal design, though). If one controls both ends, one likely has access to logs and can correlate or perhaps do some other custom processing.
I can see myself ensuring exceptions won't leak any data, in a way or another, in some projects. 

centur wrote: yes, it's a valid point. For that we have catch-all-exceptions filter registered globally for webapi. Which prevents leaking and wraps known exceptions into meaningful responses and unknown exceptions into generic "500 Oops "
I think I saw this exception on unit tests because of the way xUnit\Resharper runs tests - isolated appdomain with UnhandledExceptionHandler which re-throws all caught exceptions.

@sergeybykov wrote: Yes, that's correct - DuplicateActivationException and NonExistentActivationException are internal exceptions. In theory, they shouldn't be exposed to the client. I'm not 100% positive if they may leak via inner exceptions. Would have to check the code.

**Comment by gabikliot** [comment]
Fixed via #783.
