### ISSUE TITLE
CancellationToken.Register does not fire for non-reentrant methods

### ISSUE THREAD

**Issue by zahirtezcan-bugs** [dotnet/orleans#7752]
This can be considered as a question instead of an issue.

For asynchronous communication with an external component, I implemented a messaging interface which is utilizing `IValueTaskSource<TMessage>` for messages. The thing is while awaiting on an incoming message or a response for a previous request, I needed to trigger a timeout event.

As contents of my source class and grain interface was like (could not share from company internal network) this:
```csharp
class MessageTaskSource<TMessage> : IValueTaskSource<TMessage>
{
    ManualResetValueTaskSourceCore<TMessage> source = default;
    CancellationTokenSource cts = InitializeTimeoutCts();
    
    private CancellationTokenSource InitializeTimeoutCts()
    {
        var cts = new CancellationTokenSource();
        //calls static TimeoutCallback method when canceled via timeout
        cts.Token.Register(TimeoutCallback, this /*, false*/);
    }

    public void Initialize(TimeSpan timeout)
    {
        cts.CancelAfter(timeout);
    }
    
    public bool Reset()
    {
        if (!cts.Reset())
        {
            cts = InitializeTimeoutCts();
        }

        source.Reset();
        return true; // returns boolean for pooling
    }

    static void TimeoutCallback(object? state)
    {     
        (state as MessageTaskSource<TMessage>)?.OnTimeout();
    }

    //rest trivially calls member "source" with appropriate methods
}

interface ICommunicator
{
    [AlwaysInterleave]
    Task<int> GetInterleavedValue();

    Task<int> GetValue();
}
```

Both `GetInterleavedValue` and `GetValue` methods calls internal messaging interface with usual awaits, for example `await messenger.GetValue()` and messenger instantiates a `MessageTaskSource<int>` (or get from pool), sends a message to external component and awaits on the task generated from `MessageTaskSource<int>`.

The thing is, when external component does not respond (or disconnected), `GetInterleaved` value always gets the timeout and `GetValue` method always stalls. When I put a breakpoint in `TimeoutCallback` function while calling synchronous `GetValue` method, `TimeoutCallback` is *never* called. But, `TimeoutCallback` function is called while calling `GetInterleavedValue` method.

Setting `soruce.RunContinuationsAsynchronously` as `true` or `false` did not change resulting behavior. Also, setting `useSynchronizationContext` parameter on `CancellationToken.Register` function did not change resulting behavior either.

I wanted to make a repro of the case as simple as this but could not reproduce the stalling behavior. On my simple test application, timeout was always triggered. Main difference in our company's implementation is two fold; for one we use a lot of threads from thread-pool on the silo and for two we use grain call filters.

As last note, if I replace `CancellationTokenSource` with a `System.Threading.Timer`, then synchronous methods do not stall and timeout is triggered via timers. I tried to check online code for both classes and it seems both uses internal dotnet timer-queue.

So, can someone inform me about what I am doing wrong or can direct me into the right direction if I am misusing the dotnet asynchronous operations from within Orleans?

**Comment by ReubenBond** [comment]
This is a complex case to try to diagnose without having all the code - including the callsite where your hand-rolled `IValueTaskSource` is being used. It's a very advanced topic. Are you absolutely certain that you need it?

**Comment by zahirtezcan-bugs** [comment]
Like I said, I had implemented a workaround with `Timer`. It is a workaround and I wonder why `CancellationToken.Register` does not fire. I assume that it fires but get scheduled into the grain's synchronized call queue.

What bothers me is, it seems I don't understand the scheduling mechanism well. And I am afraid of whether it will bite me in wrong time/wrong place.

I'd be happy if you can give me some pointers to read and understand (code or documentation).

**Comment by ReubenBond** [comment]
Could you show me how your code is being used?

**Comment by zahirtezcan-bugs** [comment]
I was trying to repro this in a [test branch here](https://github.com/zahirtezcan-bugs/Boreleans/tree/taskSourceCancelAfter)
There
* `Services.Messenger` is representative of a communicator with external component
* `Tasks.CancelingTaskSource<T>` is the class I am trying to trigger timeout
* `Grains.TestGrain` has two methods `Run` and `RunInterleaved` as described above.

After running the program if I type `run` on the console and press enter then grain's `Run` method is called. If I type `rin` and press enter then `RunInterleaved` is called. This can be mechanically improved to call multiple times in `Services.ConsoleActivatorService` via loops.

Currently I could not reproduce the behavior I observe on our internal code. But, this represents how I use the task sources and cancellation sources.

**Comment by ReubenBond** [comment]
The repo you linked to is private/404-ing for me

**Comment by zahirtezcan-bugs** [comment]
My bad, sorry. It should be public now

**Comment by ReubenBond** [comment]
I took a look, but there was nothing obvious (maybe because the issue doesn't repro in that repo)
