### ISSUE TITLE
Transaction aborted because a broken lock was detected, before prepare

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/orleans#7757]
Hi,

I've seen this issue in the repo before (closed), with no resolution, so I opened a new issue with the same subject, including [a simple sample](https://github.com/jan-johansson-mr/OrleansTransactionTest) to reproduce and pinpoint the problem.

The sample is built using the latest (at current date) versions of .NET (version 7, preview) and Orleans (version 4, preview).

The sample show how a transaction can fail, even though it really should not according to documentation.

Thanks

**Comment by rammicz** [comment]
We are also facing similar issue, when saving match results for the player, there is a bit bigger workflow on several grains under a transaction and we are occasionally getting this error without any more details.
