### ISSUE TITLE
Orleans.Runtime.OrleansException was unhandled

### ISSUE THREAD

**Issue by ukluk** [dotnet/orleans#776]
Help please. 
I Needed to update grain code and the actors got corrupted (this is a different issue about state not extensible).
Deleted the State table and started to see errors. Sorry I did not document.
Next I deleted all the Orleans tables and now silo fails to start. I get the following error running on the emulator:

Orleans.Runtime.OrleansException was unhandled
  HResult=-2146232832
  Message=Failed to create OrleansSiloInstanceManager. This means CreateTableIfNotExist for silo instance table has failed with 
Exc level 0

This is my code:
                // It is IMPORTANT to start the silo not in OnStart but in Run.
                // Azure may not have the firewalls open yet (on the remote silos) at the OnStart phase.
                _silo = new AzureSilo();
                var config = new ClusterConfiguration();
                config.StandardLoad();

                var ok = _silo.Start(config);

And this is the configuration:
<?xml version="1.0" encoding="utf-8"?>
<OrleansConfiguration xmlns="urn:orleans">
  <Globals>
    <Liveness LivenessType="AzureTable" />

    <SystemStore SystemStoreType="AzureTable"
             DeploymentId="2b3d0ed02df74109bf581fa8345e40f5"
             DataConnectionString="DefaultEndpointsProtocol=https;AccountName=[name];AccountKey=[key]"/>

    <StorageProviders>
      <Provider Type="Orleans.Storage.AzureTableStorage"
                Name="AzureStore"
                DataConnectionString="DefaultEndpointsProtocol=https;AccountName=[name];AccountKey=[key]" />

    </StorageProviders>

  </Globals>

  <Defaults>
    <Networking Address="" Port="11111" />
    <ProxyingGateway Address="" Port="30000" />
    <Tracing DefaultTraceLevel="Warning" TraceToConsole="false" TraceToFile="{0}-{1}.log">
      <TraceLevelOverride LogPrefix="Application" TraceLevel="Info" />
    </Tracing>

  </Defaults>
</OrleansConfiguration>

**Comment by sergeybykov** [comment]
Is this with Storage Emulator?

**Comment by ukluk** [comment]
Hi Sergey, thanks for following up.The problem occurs running in compute emulator.
I tried to hit the storage emulator, the real storage account and even a memory provider and no matter what I get the same error starting the silo.
The load config is getting the settings from the config file, that is clear by stepping the code. But somehow after deleting ALL the Orleans tables I cannot recover.
As a compund question, if I need to delete the state table, do I need to remove any other table?
Best regards


Happy Connecting. Sent from my Sprint Samsung Galaxy S® 5

-------- Original message --------

**Comment by sergeybykov** [comment]
You don't need to delete any other table. Could you share the full silo log. Are any details in the exception as to why `CreateTableIfNotExist` failed?

**Comment by gabikliot** [comment]
" But somehow after deleting ALL the Orleans tables I cannot recover."

After table is deleted from Azure table, it cannot be recreated for some time. It is a known limitation ("feature") of Azure table and one simply needs to wait/backoff and keep retrying. Even better, avoid deleting tables.

**Comment by gabikliot** [comment]
" But somehow after deleting ALL the Orleans tables I cannot recover."

After table is deleted from Azure table, it cannot be recreated for some time. It is a known limitation ("feature") of Azure table and one simply needs to wait/backoff and keep retrying. Even better, avoid deleting tables.

**Comment by mauriciomagni** [comment]
Hello 
I found a similar problem with WindowsAzure.Storage 8.0.0. It was similar, because I got the same message ("This means CreateTableIfNotExist for silo instance table has failed with"). The difference was that I have not created nor deleted a previous table.
It started working after going back to WindowsAzure.Storage 7.2.1
I am using development storage.
Please, let me know if I can provide more information about this issue.
Kind regards

**Comment by sergeybykov** [comment]
@mauriciomagni Please open a separate issue. Which version of Orleans are you running?

**Comment by mauriciomagni** [comment]
Hello @sergeybykov the issue has been created: #2543
