### ISSUE TITLE
Update HelloWorld sample to dotnet 6

### ISSUE THREAD

**Issue by behroozbc** [dotnet/orleans#7760]
I see the hello world sample still on .Net 5 but .Net 5 support has ended on [May 8, 2022](https://www.bing.com/ck/a?!&&p=9f506b1215b71e0fbc757573ccc77cfc8a1996f385f5934be3289647f81570d1JmltdHM9MTY1MzY3MDM3MyZpZ3VpZD0yNzgyMjU5MS1jMWUwLTQ2ZTQtODBlOS01ZTlmODA1YWNhYjUmaW5zaWQ9NTM5Ng&ptn=3&fclid=73256c56-dddd-11ec-8456-27bd58d31e16&u=a1aHR0cHM6Ly9kZXZibG9ncy5taWNyb3NvZnQuY29tL2RvdG5ldC9mZWJydWFyeS0yMDIyLXVwZGF0ZXMvIzp-OnRleHQ9Lk5FVCUyMDUuMCUyMHdpbGwlMjByZWFjaCUyMGVuZCUyMG9mJTIwbGlmZSUyMG9uLG1vdmUlMjBhbnkuTkVUJTIwNS4wJTIwYXBwbGljYXRpb25zJTIwYW5kJTIwZW52aXJvbm1lbnRzJTIwdG8uTkVUJTIwNi4wLg&ntb=1).  I thought the hello word sample had forgotten to update.

**Comment by ReubenBond** [comment]
Fixed by #7761
