### ISSUE TITLE
TestCluster may be broken with version 4.0.0-preview1

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/orleans#7762]
Hi,

My unit tests do not work after upgrading to 4.0.0-preview1, and to illustrate what is happening, I've included [a sample](https://github.com/jan-johansson-mr/OrleansTestCluster). The tests are working with version 3.6.2.

Thanks

**Comment by jan-johansson-mr** [comment]
Found out that using `Microsoft.Orleans.Sdk` and removing `Microsoft.Orleans.CodeGenerator.MSBuild` from the package references in the `csproj` file makes the sample work with 4.0.0-preview1.

**Comment by ReubenBond** [comment]
Hi @jan-johansson-mr, do you think we need to do something here? Maybe we can need to try to disable the MSBuild code generator if the `Microsoft.Orleans.CodeGenerator` package is also installed (which is a C# Source Generator).

**Comment by jan-johansson-mr** [comment]
I think there is nothing really to do, except maybe as you say, to disable the MSBuild code generator, or putting in documentation as version 4.0.0 gets released. I like the SDK way of things.
