### ISSUE TITLE
Suggestion for transactional - enriching developer toolkit and experience

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/orleans#7764]
Hi,

The transactional design in Orleans helps to define a *Unit of Work* with writing and reading from a smattering set of grains, and in my humble opinion is kind a required tenet with distributed design. The transactional design in Orleans is steered toward the coupling of the transactional scope to a grain method, managing of the *Unit of Work* in a kind of an *aggregator* grain.

E.g., let's assume there are two grains, each with a method **Set...** with some parameters and each grain can Create or Join a transaction scope. In this story, the two grains should **Set...** in one transaction scope (a defined *Unit of Work*).

The available design for this is to create another grain, with a method implementing the *Unit of Work* as illustrated

    public async Task SetPhraseAndNumber(string phrase, int number)
    {
        ...

        var first = _cluster.GetGrain<IFirstGrain>(id);
        var second = _cluster.GetGrain<ISecondGrain>(id);

        await first.SetPhrase(phrase);
        await second.SetNumber(number);

        ...
    }

And with the method declared as

    [Transaction(TransactionOption.Create)]
    Task SetPhraseAndNumber(string phrase, int number);

Where first and second grain has methods defined as

    [Transaction(TransactionOption.CreateOrJoin)]
    Task SetPhrase(string phrase);

And

    [Transaction(TransactionOption.CreateOrJoin)]
    Task SetNumber(int number);

The illustrated example works good for simple use cases. The drawback is that it requires the said *aggregator* grain to be developed in order to define a **Unit of Work**, second that the design becomes increasingly cluttered as the **Unit of Work** increases with either involved grains or with parameters in the scope, the third is that return value from each grain has to be packed in a return value from the aggregator grain, and the fourth is that the *aggregator* grain is hard coupled to the grains making up the **Unit of Work**.

Another approach to define transactional scope as a **Unit of Work** is already present in the .NET echo system today with the [TransactionScope](https://docs.microsoft.com/en-us/dotnet/api/system.transactions.transactionscope?view=net-6.0) class. The design is to create the scope in the code where it is needed, and then let actors hook onto the ambient transaction and defining the **Unit of Work** from there.

My suggestion would be to enrich the support of transactional capability to Orleans by a similar design approach as the **TransactionScope** offers today in .NET echo system (not saying that the same type has to be used, but rather enable the same design option).

Some tools of this approach are already present in Orleans today. There is the [TransactionContext](https://github.com/dotnet/orleans/blob/73212fd3083ca09a9cf1f394067880edf18ec439/src/Orleans.Transactions/TransactionContext.cs#L18) type available, helping to keep track of transaction for the grain, and there is the [ITransactionAgent](https://docs.microsoft.com/en-us/dotnet/api/orleans.transactions.itransactionagent?view=orleans-3.0) managing transaction creation, resolution and abort (begin, commit, abort).

Maybe this support isn't that hard to add to Orleans by introducing a type that manages a transaction scope, since the ambient transaction is [picked up](https://github.com/dotnet/orleans/blob/73212fd3083ca09a9cf1f394067880edf18ec439/src/Orleans.Transactions/TransactionAttribute.cs#L107) already today by the grain call filter.

Thanks

**Comment by jan-johansson-mr** [comment]
Hi @ReubenBond, @benjaminpetit,

I've been working on the described proposal in this issue, and want to do a pull request. How do I go about it to potentially contribute to Orleans?

**Comment by ReubenBond** [comment]
This sounds like an interesting idea. How do you think the end result would look? Something like this, perhaps:

``` C#
public async Task MyMethod()
{
  // do something

  await using (transactionAgent.StartTransaction(TransactionOption.Create))
  {
    await grainA.SetPhrase("hi");
    await grainB.SetNumber(4);
  }

  // do something else
}
```

Who would be able to create a transaction scope: any grain/client? It would likely need access to the transaction agent or some similar (but user-facing) type.
Should the other transactional methods (in SetPhrase & SetNumber) still require attributes? I think the answer should be "yes".

**Comment by jan-johansson-mr** [comment]
Actually, I already have coded the proposal, and want to create a pull request :-)
However, I'm struggling to make the request :-) The code however is working great when running it!
I'll get back when it's done (I hope soon)

**Comment by jan-johansson-mr** [comment]
Alright, I just made the pull request.

Thanks for all good feedback :-)

**Comment by jan-johansson-mr** [comment]
Hi @ReubenBond,

I'd be happy to share my thoughts on the PR.

I've worked with the nice pattern

    public async Task MyMethod()
    {
        // do something

        await using (transactionAgent.CreateScope())
        {
            await grainA.SetPhrase("hi");
            await grainB.SetNumber(4);
            transactionAgent.Commit();
        }

        // do something else
    }

As we leave the scope, the `Commit` signals to the scope that we want to commit the scoped transaction. When we reach the closure by `IAsyncDisposable`, we really don't know if we hit the dispose because of leaving the scope or if we are there because of an exception. And to have a transaction scope without `Commit` really doesn't make sense.

The behavior that the PR have is that we throw an exception if `Commit` is missing. That seems to be a pragmatic approach, however, the grub here is that if we hit end of scope because of an exception, then we mask the original exception by throwing that we are missing a `Commit`. That is not so good, but there seems to be no way to pick up an ambient exception in flight, and do something with it.

Another option is to use the following pattern

    await transactionalAgent.CreateScope(async () =>
    {
            await grainA.SetPhrase("hi");
            await grainB.SetNumber(4);
            transactionAgent.Commit();
    });

That is, we encapsulate the whole scope in a delegate. The pattern is not as intuitive as the first pattern, but we have better control of the execution flow and can handle exceptions better. I'm sitting on the fence on this one.

But then again, the user can very well safe guard the execution flow with try-catch and do whatever action needed, and then it might not matter that the exception gets masked by the first pattern.

**Comment by jan-johansson-mr** [comment]
The transactional client is merged in the code base, closing this issue
