### ISSUE TITLE
How to make Orleans run @ 100K+ requests/second?

### ISSUE THREAD

**Issue by JsAndDotNet** [dotnet/orleans#7785]
I've been learning orleans via the docs, [Pluralsight](https://app.pluralsight.com/library/courses/microsoft-orleans-introduction/table-of-contents) and a very good book from [Packt](https://www.packtpub.com/product/distributed-net-with-microsoft-orleans/9781801818971). It's great tech!

I need to create a system that can take 100K+ requests a second.

I've created a simple [performance test project](https://github.com/JsAndDotNet/OrleansLoadTest#orleans-load--performance-test).

The problem is, I can't get great performance out of it.

Testing on an Azure VM - Standard DS3 v2 (4 vcpus, 14 GiB memory, good IOPS), running 10 silos with 10 Azure Table Storage Accounts, I can only get [300-700 requests per second](https://github.com/JsAndDotNet/OrleansLoadTest#results-so-far). My cluster config is[ here](https://github.com/JsAndDotNet/OrleansLoadTest/blob/e06ac287ea8cc0f6f7bfc79af090a28f65d6e540/LoadTest.Silo.Console/Program.cs#L102).

Is the answer just to keep adding more and more Silos/ Table Storage? I think we'd need 200+ (I'm guessing across multiple machines) to get anything close to the performance I need.

Is this correct, or am I missing something?

Sorry if this isn't the right place, the homepage states to start a technical discussion here...

**Comment by SebastianStehle** [comment]
What is your scenario?

You should have a relative high number of grains that are not activated that often and then call each grain multiple times. Grain activation is expensive.

But I am sure you cannot simulate 100k http calls from a single machine anyway.

**Comment by JsAndDotNet** [comment]
Hi @SebastianStehle 

To provide a known analogy - My scenario is something similar to the (failed) HQ Trivia, whereby someone is asking a question, then many tens of thousands of people then fire in their answers in a short time.

My expectation of how this would work would be that each person submitting would be represented by a grain (lit up before the question is asked) then their data sent to that grain.

The [test application](https://github.com/JsAndDotNet/OrleansLoadTest#orleans-load--performance-test) is just passing in a number to represent any form of input sent by a user.

On the current test, it would take over 3 minutes to get the data in, which is not viable.

Hence, I need to understand how I can ramp up the performance. 

I can absolutely use more machines/AKS - I wouldn't use one machine in prod. 

The issue is understanding what I need to do to get the performance I need. Is is just a case of more machines and more Silos, or is there a smarter way to achieve the desired result. 200+ Silos/Storage accounts just seems really messy.

**Comment by JsAndDotNet** [comment]
@ReubenBond  -  I've updated the repo - it's much more performant. 

The suggestions made a massive difference - Thank you 😊!

Actions Taken:
- Remove all Console.WriteLines
- Remove Stopwatch(es)
- Warm up grains before calling
- Call using a List of Tasks, then WaitAll
- Remove logging - except for exceptions
- Removed the Dashboard (suggested by @ElanHasson in Discord)

Thank again!
