### ISSUE TITLE
Orleans CodeGenerator ignoring [NonSerialized] attribute on private fields in base classes from a packaged project

### ISSUE THREAD

**Issue by BorgChrist** [dotnet/orleans#7796]
We've encountered the same issue discovered in #6962 and would like to raise it.

We have a base class with a private field decorated with `[NonSerialized]` in a library which is packaged. The required work to properly make it discoverable was also done following the guide [here](https://dotnet.github.io/orleans/docs/grains/code_generation.html#generate-code-for-all-types-in-another-assembly)
This base class is then extended by another class which is a parameter of a grain method call.

However, on build, the code generator still generates code for the field decorated with `[NonSerialized]` and therefore get serialized which shoudn't.

**Comment by ReubenBond** [comment]
Could you please show some example code + the relevant generated output, or (even better) provide a repro project?

**Comment by BorgChrist** [comment]
The issue was also replicated using direct dll referencing bypassing the package reference.

The following is an example of the base class structure in a different library.

```
[Serializable]
public class BaseClass
{
    [NonSerialized]
    private string Test;
    
    private IDictionary<string, string>? _additionalProperties;
}
```

The following is a the class extending the BaseClass through the installation of the package.
```
[assembly: KnownAssembly(typeof(BaseClass))]

[Serializable]
public class MyClass  : BaseClass
{
    public int Num { get; set; }
}
```

The generated code for the serializers of both classes is attached below:

[BaseClassSerializer.txt](https://github.com/dotnet/orleans/files/8929408/BaseClassSerializer.txt)
[MyClassSerializer.txt](https://github.com/dotnet/orleans/files/8929409/MyClassSerializer.txt)

**Comment by ReubenBond** [comment]
What are the target framework types of the different libraries? I wonder if the issue is type equality - maybe we need to move away from type equality and rely on fully-qualified names instead

**Comment by BorgChrist** [comment]
Making the property `public` property i.e `public string Test {get; set;}` will help the generator to identify and skip it. However later on during runtime, a `System.MethodNotFoundException` is being thrown for method `get_Test`

**Comment by ReubenBond** [comment]
Is the `Test` property/field is in an external library which you control?

Interesting that it would throw that exception. It seems that the project was not fully re-built.

**Comment by BorgChrist** [comment]
> Is the `Test` property/field is in an external library which you control?
> 
> Interesting that it would throw that exception. It seems that the project was not fully re-built.
Yes the base class is in a project we control.

**Comment by ReubenBond** [comment]
After rebuilding everything, do you still hit this issue?

**Comment by BorgChrist** [comment]
> After rebuilding everything, do you still hit this issue?

Yes after rebuilding and even manually cleaning and building, code is still generated for this field.

**Comment by ReubenBond** [comment]
@BorgChrist which code generation package are you using? If it's the `.Build` package, could you try migrating to the `.MSBuild` package?

**Comment by BorgChrist** [comment]
@ReubenBond we are making use of `Microsoft.Orleans.CodeGenerator.MSBuild` v3.6.1 already.

**Comment by ReubenBond** [comment]
I think this is too stale for us to look at - apologies for not getting back to you sooner. If you still see this, please feel free to open a new issue and we will try to assist.
