### ISSUE TITLE
InvalidateCache does not have an implemenation

### ISSUE THREAD

**Issue by aeonopolis** [dotnet/orleans#7797]
Hello,

I am currently trying to run a unit test on some grain code.  When setting up the TestCluster as below:

private readonly TestCluster cluster;

var builder = new TestClusterBuilder();
cluster = builder.Build();
cluster.Deploy();

Calling Deploy on the cluster returns the error :

"Method 'InvalidateCache' in type 'Orleans.Runtime.GrainDirectory.DhtGrainLocator' from assembly 'Orleans.Runtime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation"

I opened the Orleans.Runtime dll in dotPeek and located the DhtGrainLocator class that implements the IGrainLocator interface, and sure enough, the interface has a method called InvalidateCache(ActivationAddress address) but the DhtGrainLocator class does not implement this method.  What is the solution?  Thanks!

For reference, here is the decompiled DhtGrainLocator class:

// Decompiled with JetBrains decompiler
// Type: Orleans.Runtime.GrainDirectory.DhtGrainLocator
// Assembly: Orleans.Runtime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 06A6EAC9-C86F-48C3-8905-0F950B04146C

using Orleans.GrainDirectory;
using Orleans.Runtime.Scheduler;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Orleans.Runtime.GrainDirectory
{
  /// <summary>
  /// Implementation of <see cref="T:Orleans.GrainDirectory.IGrainLocator" /> that uses the in memory distributed directory of Orleans
  /// </summary>
  internal class DhtGrainLocator : IGrainLocator
  {
    private readonly ILocalGrainDirectory localGrainDirectory;
    private readonly OrleansTaskScheduler taskScheduler;
    private readonly IGrainContext grainContext;
    private readonly ConcurrentQueue<(TaskCompletionSource<object> tcs, ActivationAddress address, UnregistrationCause cause)> unregistrationQueue = new ConcurrentQueue<(TaskCompletionSource<object>, ActivationAddress, UnregistrationCause)>();
    private int isWorking;

    public DhtGrainLocator(
      ILocalGrainDirectory localGrainDirectory,
      OrleansTaskScheduler taskScheduler,
      IGrainContext grainContext)
    {
      this.localGrainDirectory = localGrainDirectory;
      this.taskScheduler = taskScheduler;
      this.grainContext = grainContext;
    }

    public async Task<List<ActivationAddress>> Lookup(GrainId grainId) => (await this.localGrainDirectory.LookupAsync(grainId)).Addresses;

    public bool TryLocalLookup(GrainId grainId, out List<ActivationAddress> addresses)
    {
      AddressesAndTag addresses1;
      if (this.localGrainDirectory.LocalLookup(grainId, out addresses1))
      {
        addresses = addresses1.Addresses;
        return true;
      }
      addresses = (List<ActivationAddress>) null;
      return false;
    }

    public async Task<ActivationAddress> Register(ActivationAddress address) => (await this.localGrainDirectory.RegisterAsync(address, true)).Address;

    public Task Unregister(ActivationAddress address, UnregistrationCause cause)
    {
      TaskCompletionSource<object> completionSource = new TaskCompletionSource<object>(TaskCreationOptions.RunContinuationsAsynchronously);
      this.unregistrationQueue.Enqueue((completionSource, address, cause));
      this.taskScheduler.RunOrQueueTask((Func<Task>) (() => this.UnregisterExecute()), this.grainContext).Ignore();
      return (Task) completionSource.Task;
    }

    public static DhtGrainLocator FromLocalGrainDirectory(
      LocalGrainDirectory localGrainDirectory)
    {
      return new DhtGrainLocator((ILocalGrainDirectory) localGrainDirectory, localGrainDirectory.Scheduler, (IGrainContext) localGrainDirectory.RemoteGrainDirectory);
    }

    private async Task UnregisterExecute()
    {
      while (!this.unregistrationQueue.IsEmpty && Interlocked.CompareExchange(ref this.isWorking, 1, 0) != 1)
      {
        List<(TaskCompletionSource<object>, ActivationAddress, UnregistrationCause)> operations = new List<(TaskCompletionSource<object>, ActivationAddress, UnregistrationCause)>();
        UnregistrationCause? nullable1 = new UnregistrationCause?();
        try
        {
          (TaskCompletionSource<object>, ActivationAddress, UnregistrationCause) result;
          while (this.unregistrationQueue.TryPeek(out result))
          {
            if (!nullable1.HasValue)
            {
              nullable1 = new UnregistrationCause?(result.Item3);
            }
            else
            {
              UnregistrationCause? nullable2 = nullable1;
              UnregistrationCause unregistrationCause = result.Item3;
              if (!(nullable2.GetValueOrDefault() == unregistrationCause & nullable2.HasValue))
                break;
            }
            this.unregistrationQueue.TryDequeue(out result);
            operations.Add(result);
          }
          if (operations.Any<(TaskCompletionSource<object>, ActivationAddress, UnregistrationCause)>())
          {
            await this.localGrainDirectory.UnregisterManyAsync(operations.Select<(TaskCompletionSource<object>, ActivationAddress, UnregistrationCause), ActivationAddress>((Func<(TaskCompletionSource<object>, ActivationAddress, UnregistrationCause), ActivationAddress>) (op => op.address)).ToList<ActivationAddress>(), nullable1.Value);
            foreach ((TaskCompletionSource<object>, ActivationAddress, UnregistrationCause) valueTuple in operations)
              valueTuple.Item1.SetResult((object) null);
          }
        }
        catch (Exception ex)
        {
          foreach ((TaskCompletionSource<object>, ActivationAddress, UnregistrationCause) valueTuple in operations)
            valueTuple.Item1.SetException(ex);
        }
        finally
        {
          Interlocked.Exchange(ref this.isWorking, 0);
        }
        operations = (List<(TaskCompletionSource<object>, ActivationAddress, UnregistrationCause)>) null;
      }
    }
  }
}

**Comment by ReubenBond** [comment]
This indicates that you have an assembly version mismatch. Rebuild your project and make sure you are using a consistent version of Orleans

**Comment by aeonopolis** [comment]
Hi,

I rebuilt the solution but am still encountering the error.  My packages.config suggest that the Orleans versions are the same.  A snippet:

  <package id="Microsoft.Orleans.Core" version="3.6.0" targetFramework="net461" />
  <package id="Microsoft.Orleans.Core.Abstractions" version="3.6.0" targetFramework="net461" />
  <package id="Microsoft.Orleans.OrleansProviders" version="3.6.0" targetFramework="net461" />
  <package id="Microsoft.Orleans.OrleansRuntime" version="3.6.0" targetFramework="net461" />
  <package id="Microsoft.Orleans.Runtime.Abstractions" version="3.6.0" targetFramework="net461" />
  <package id="Microsoft.Orleans.TestingHost" version="3.6.0" targetFramework="net461" />

**Comment by ReubenBond** [comment]
What other packages do you have @aeonopolis?

**Comment by aeonopolis** [comment]
> What other packages do you have @aeonopolis?

Here is the entirety of the config:

`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Dapper" version="2.0.123" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Connections.Abstractions" version="6.0.5" targetFramework="net461" />
  <package id="Microsoft.Bcl.AsyncInterfaces" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration" version="6.0.1" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.Abstractions" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.Binder" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.CommandLine" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.EnvironmentVariables" version="6.0.1" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.FileExtensions" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.Json" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.UserSecrets" version="6.0.1" targetFramework="net461" />
  <package id="Microsoft.Extensions.DependencyInjection" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.DependencyModel" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Features" version="6.0.5" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileProviders.Abstractions" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileProviders.Physical" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileSystemGlobbing" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Hosting" version="6.0.1" targetFramework="net461" />
  <package id="Microsoft.Extensions.Hosting.Abstractions" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging.Abstractions" version="6.0.1" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging.Configuration" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging.Console" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging.Debug" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging.EventLog" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging.EventSource" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.ObjectPool" version="6.0.5" targetFramework="net461" />
  <package id="Microsoft.Extensions.Options" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Options.ConfigurationExtensions" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Primitives" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.Orleans.Core" version="3.6.0" targetFramework="net461" />
  <package id="Microsoft.Orleans.Core.Abstractions" version="3.6.0" targetFramework="net461" />
  <package id="Microsoft.Orleans.OrleansProviders" version="3.6.0" targetFramework="net461" />
  <package id="Microsoft.Orleans.OrleansRuntime" version="3.6.0" targetFramework="net461" />
  <package id="Microsoft.Orleans.Runtime.Abstractions" version="3.6.0" targetFramework="net461" />
  <package id="Microsoft.Orleans.TestingHost" version="3.6.0" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="13.0.1" targetFramework="net461" />
  <package id="System.Buffers" version="4.5.1" targetFramework="net461" />
  <package id="System.Collections.Immutable" version="6.0.0" targetFramework="net461" />
  <package id="System.Diagnostics.DiagnosticSource" version="6.0.0" targetFramework="net461" />
  <package id="System.IO.Pipelines" version="6.0.3" targetFramework="net461" />
  <package id="System.Memory" version="4.5.5" targetFramework="net461" />
  <package id="System.Numerics.Vectors" version="4.5.0" targetFramework="net461" />
  <package id="System.Reflection.Emit" version="4.7.0" targetFramework="net461" />
  <package id="System.Reflection.Emit.Lightweight" version="4.7.0" targetFramework="net461" />
  <package id="System.Reflection.Metadata" version="6.0.1" targetFramework="net461" />
  <package id="System.Runtime" version="4.3.1" targetFramework="net461" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="6.0.0" targetFramework="net461" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.1" targetFramework="net461" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="System.Text.Encodings.Web" version="6.0.0" targetFramework="net461" />
  <package id="System.Text.Json" version="6.0.4" targetFramework="net461" />
  <package id="System.Threading.Channels" version="6.0.0" targetFramework="net461" />
  <package id="System.Threading.Tasks.Extensions" version="4.5.4" targetFramework="net461" />
  <package id="System.ValueTuple" version="4.5.0" targetFramework="net461" />
  <package id="xunit" version="2.4.1" targetFramework="net461" />
  <package id="xunit.abstractions" version="2.0.3" targetFramework="net461" />
  <package id="xunit.analyzers" version="0.10.0" targetFramework="net461" />
  <package id="xunit.assert" version="2.4.1" targetFramework="net461" />
  <package id="xunit.core" version="2.4.1" targetFramework="net461" />
  <package id="xunit.extensibility.core" version="2.4.1" targetFramework="net461" />
  <package id="xunit.extensibility.execution" version="2.4.1" targetFramework="net461" />
</packages>`

**Comment by ReubenBond** [comment]
Also, please post the entire stack trace from the exception

**Comment by aeonopolis** [comment]
Here you go:

`		StackTrace	"   at Orleans.Hosting.DefaultSiloServices.AddDefaultServices(IApplicationPartManager applicationPartManager, IServiceCollection services)\r\n   at Orleans.Hosting.CoreHostingExtensions.<>c.<ConfigureDefaults>b__6_0(HostBuilderContext context, IServiceCollection services)\r\n   at Orleans.Hosting.SiloBuilder.InvokeConfigureServicesDelegates(HostBuilderContext ctx, IServiceCollection services)\r\n   at Orleans.Hosting.SiloBuilder.<.ctor>b__4_0(HostBuilderContext ctx, IServiceCollection services)\r\n   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()\r\n   at Microsoft.Extensions.Hosting.HostBuilder.Build()\r\n   at Orleans.TestingHost.TestClusterHostFactory.CreateSiloHost(String hostName, IEnumerable`1 configurationSources)\r\n   at Orleans.TestingHost.InProcessSiloHandle.<>c__DisplayClass7_0.<<CreateAsync>b__0>d.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Orleans.TestingHost.InProcessSiloHandle.<CreateAsync>d__7.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Orleans.TestingHost.TestCluster.<StartSiloAsync>d__65.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Orleans.TestingHost.TestCluster.<InitializeAsync>d__63.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Orleans.TestingHost.TestCluster.<DeployAsync>d__40.MoveNext()\r\n   at Orleans.TestingHost.TestCluster.<DeployAsync>d__40.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Orleans.TestingHost.TestCluster.Deploy()\r\n   at Onboarding.Grains.ClientCreationServiceTest..ctor() in C:\\src\\code\\Services\\Onboarding\\Grains\\ClientCreationService.test.cs:line 21"	string
`

**Comment by aeonopolis** [comment]
Sorry if I'm messing up the formatting on these, this is my first time posting here.

**Comment by ReubenBond** [comment]
No worries about the formatting, I was just fixing it so I can read it more easily.
That stack trace is odd to me, are you certain that's everything?

Do you have any other projects added which could be referencing a newer version of Orleans? At some point, your project is pulling in a newer version, probably via a dependency (eg, another project).

The `IGrainLocator.InvalidateCache` method was added in 3.6.1 here https://github.com/dotnet/orleans/pull/7636

Upgrading to that version would also likely fix your issue.

**Comment by aeonopolis** [comment]
There was indeed a project that this had a dependency on with a newer version of Orleans installed that it didn't need.  I never would have thought to look there.  Thank you!

**Comment by ReubenBond** [comment]
No problem at all, @aeonopolis, I'm glad I could help.
