### ISSUE TITLE
The same grain, some one thread call to client's IGrainObserver method that did not respond

### ISSUE THREAD

**Issue by islovingness** [dotnet/orleans#7798]
Hi there.

I add breakpoints inside the calling method of Grain and the IGrainObserver execution body of the client.

However, a problem thread can only trigger a method call, not within the execution body.The other threads are fine.

I want to know under what circumstances, the program does not report an error, but the client's IGrainObserver execution body breakpoint cannot be triggered.

Thank you!!!

**Comment by ReubenBond** [comment]
Hi @islovingness, I don't quite understand the issue you're having. Could you please provide some more detail?

**Comment by islovingness** [comment]
@ReubenBond 
Thank you for your reply!
I mean, the normal situation is the following 2 images:
img1:
![1](https://user-images.githubusercontent.com/17868490/174424740-8a9f5880-a16e-442f-a58a-b36e0bedaffe.jpg)
img2:
![2](https://user-images.githubusercontent.com/17868490/174424746-24bc07c3-a7d7-4f10-97b4-fd628ed58e45.jpg)

`
    public interface IPacketObserver : IGrainObserver
    {
        void SendPacket(LkfMsg msg);
        void Close(LkfMsg msg = null);
    }
`
But when I do something else, the first one `CreateObjectReference<IPacketObserver>`, that is `_observer`, method calls can proceed normally, but the client did not receive it. The following images:

img3:
![3](https://user-images.githubusercontent.com/17868490/174425172-f1c678c9-141e-48db-8fdb-1bf3987089ad.jpg)
img4:
![4](https://user-images.githubusercontent.com/17868490/174425190-42733cf5-20c4-4c6e-8597-f991ff30053b.jpg)

I don't see any obvious mistakes. I wonder why the client did not receive the function call of Grain.

Thank you!!!

**Comment by ReubenBond** [comment]
When you call `CreateObjectReference(obj)`, you need to make sure that you keep a reference to `obj` yourself. If you don't, the object will be collected by the .NET Garbage Collector and will not receive the call.

Could that be the issue?

**Comment by islovingness** [comment]
I'm sure I keep a reference.

img5：
![5](https://user-images.githubusercontent.com/17868490/174426997-1307b4e5-46a0-48f9-a00e-f562ab95feda.jpg)
img6:
![6](https://user-images.githubusercontent.com/17868490/174427007-553ea053-bc06-4af9-8a8a-6c24b231e205.jpg)

it means, in a special case, I can receive user messages. The session corresponding to each user can call its corresponding grain, and its grain can respond to the operation. However, the session cannot receive the message from grain.

**Comment by ReubenBond** [comment]
My apologies, let me clarify: you need to keep a reference to the argument passed *to* `CreateObjectReference`. In your case, it's the `OutgoingPacketObserver` object you created.

**Comment by islovingness** [comment]
oh, my god...
I can't describe how I feel right now.
It seems that I need to write exactly according to the official example. A bit of arbitrary code leads to a problem that has bothered me for a long time, and I can't locate it.

Thank you!!!

**Comment by ReubenBond** [comment]
No problem, @islovingness. I think the documentation tries to inform you of this, but it's an easy mistake to make. If we did not do this, then `CreateObjectReference` would be a source of memory leaks.

We are always happy to help, so please do not hesitate to ask us when you run into issues.
