### ISSUE TITLE
Issue deserialising message

### ISSUE THREAD

**Issue by ADringer** [dotnet/orleans#7799]
Hi,

I'm currently getting the following error when trying to processing a message:

`ILSerializerTypeToken of 36 is not supported. at Orleans.Serialization.ILBasedSerializer.ReadType(ILSerializerTypeToken token, IDeserializationContext context, Type expectedType) in /_/src/Orleans.Core/Serialization/ILBasedSerializer.cs:line 177\n at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context) in /_/src/Orleans.Core/Serialization/ILBasedSerializer.cs:line 142\n at Orleans.Serialization.SerializationManager.FallbackDeserializer(IDeserializationContext context, Type expectedType) in /_/src/Orleans.Core/Serialization/SerializationManager.cs:line 1686\n at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader) in /_/src/Orleans.Core/Serialization/SerializationManager.cs:line 1362\n at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, IDeserializationContext context) in /_/src/Orleans.Core/Serialization/BuiltInTypes.cs:line 2136\n at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader) in /_/src/Orleans.Core/Serialization/SerializationManager.cs:line 1362\n at Orleans.Runtime.Messaging.MessageSerializer.OrleansSerializer\u00601.Deserialize(ReadOnlySequence\u00601 input, T\u0026 value) in /_/src/Orleans.Core/Messaging/MessageSerializer.cs:line 157\n at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence\u00601\u0026 input, Message\u0026 message) in /_/src/Orleans.Core/Messaging/MessageSerializer.cs:line 85\n at Orleans.Runtime.Messaging.Connection.ProcessIncoming() in /_/src/Orleans.Core/Networking/Connection.cs:line 358\n at Orleans.Runtime.OutgoingCallInvoker.Invoke() in /_/src/Orleans.Core/Runtime/OutgoingCallInvoker.cs:line 113\n at Orleans.Runtime.OutgoingCallInvoker.Invoke() in /_/src/Orleans.Core/Runtime/OutgoingCallInvoker.cs:line 113\n at Orleans.Runtime.GrainReferenceRuntime.InvokeWithFilters(GrainReference reference, InvokeMethodRequest request, InvokeMethodOptions options) in /_/src/Orleans.Core/Runtime/GrainReferenceRuntime.cs:line 116\n at Orleans.Internal.OrleansTaskExtentions.\u003CToTypedTask\u003Eg__ConvertAsync|4_0[T](Task\u00601 asyncTask) in /_/src/Orleans.Core/Async/TaskExtensions.cs:line 114\n at InitialiseInstallationWhenInstallationProvisionedIntegrationEventHandler.Handle(InstallationProvisionedIntegrationEvent notification, CancellationToken cancellationToken) in /src/MonitorAndControlService/src/MonitorAndControl.Worker/IntegrationEventHandlers/InstallationProvisioned/InitialiseInstallationWhenInstallationProvisionedIntegrationEventHandler.cs:line 110`

I've had this error a couple of times now, what does `ILSerializerTypeToken of x is not supported` actually mean? I'm not too sure what I should be looking at and can't find much reference to this error.

Could possibly be the cause, but should objects sent on a stream be marked as `Serializable`? The method this is failing on sends out messages on a stream but the object doesn't have the attribute. Although it has been working up until now.

Thanks

Alex

**Comment by ReubenBond** [comment]
> I've had this error a couple of times now, what does ILSerializerTypeToken of x is not supported actually mean?

The serializer encountered some data that it didn't expect or know how to handle.

> Could possibly be the cause, but should objects sent on a stream be marked as Serializable? 

Yes, I recommend that you mark all objects you're intending to serialize as `[Serializable]`.

This typically happens when some settings or types have changed, or if settings are not the same on both sides of the wire (eg, the client is using one version and the server is using another). Could you

**Comment by ADringer** [comment]
Thanks for the feedback. I've gone through the code changes and the method declaration itself hasn't changed, so client and server are both the same type.

The parameter of the method is just a bool, should serialisation work out the box for built in types? 

I'll try adding the `serializable` to stream object and see if that works. Were you going to suggest something else? It looks like you got cut off at the end!

**Comment by ReubenBond** [comment]
> Were you going to suggest something else? It looks like you got cut off at the end!

Ah, thanks for pointing that out. I was going to ask if you could provide some more details in general, about the scenario and about the code (types being used, where they're being sent from and to, etc.)

**Comment by ADringer** [comment]
Found the issue! The server was throwing an exception which the client wasn't expecting. We've implented an instance of `IIncomingGrainCallFilter` but guess we need to have another look at it!
