### ISSUE TITLE
Orleans SDK and VS Tools on the Visual Studio Gallery

### ISSUE THREAD

**Issue by pherbel** [dotnet/orleans#78]
It would be very helpful if we are able to update the Tools and SDK with the VS Extension manager.

**Comment by sergeybykov** [comment]
What does it take to get us there, do you know? We are rather shallow on the whole VS integration topic, so any help is greatly appreciated.

**Comment by BenjaminGibbs** [comment]
All extensions are listed here: https://visualstudiogallery.msdn.microsoft.com/ which in turns gets pushed in to the VS Extension manager.

You can upload new extensions here: https://visualstudiogallery.msdn.microsoft.com/site/upload normally it is just the VSIX file you upload if you are submitting a tool which I think this would be classified as.

But I'm no expert on how much 'other stuff' you have going on outside of installing the VSIX to visual studio (and I have not had time to study the installer), but it maybe the case where the Tools/SDK won't all be able to deploy via the extensions. (for example azure SDK isn't installed via extensions). It could be worth looking at if you can use Web Platform Installer instead like the Azure SDK does.

**Comment by pherbel** [comment]
Unfortunately I don't have experience with the VS Extension publish method.
Just it's  came into my mind it would be very easy to update.
I think you need a separated CI build which is able to create the VSIX package and upload into the Gallery automatically if there is a stable version

**Comment by sergeybykov** [comment]
The VSIX is tightly coupled with the SDK bits. If update VSIX and SDK via different mechanisms, wouldn't that potentially break things in non-obvious ways?

**Comment by jesuspsalas** [comment]
Sergey, you are right, the best is to keep the VSIX together with the SDK as long as both SDK and VSIX are coupled (probably forever). 

Visual Studio gallery extensions are intended for standalone stuff with no external dependencies and you can only have a single version at once for any given VSIX (or you need to generate different package ids for each VSIX version and upload what looks for VSG a new product)

**Comment by smoothdeveloper** [comment]
Can we check how to get the extension installed on Visual Studio 2015 (CTP), I'm having issue installing it, even after changing the extension manifest to bump ```13)``` to ```14)```

Any help on getting it installed on VS 2015 would be much appreciated.

```log
28/02/2015 18:14:58 - Microsoft VSIX Installer
28/02/2015 18:14:58 - -------------------------------------------
28/02/2015 18:14:58 - Initializing Install...
28/02/2015 18:14:58 - Extension Details...
28/02/2015 18:14:58 - 	Identifier      : 462db41f-31a4-48f0-834c-1bdcc0578511
28/02/2015 18:14:58 - 	Name            : OrleansVSTools11
28/02/2015 18:14:58 - 	Author          : Microsoft
28/02/2015 18:14:58 - 	Version         : 1.0.0
28/02/2015 18:14:58 - 	Description     : Orleans Tools for Visual Studio 2012
28/02/2015 18:14:58 - 	Locale          : en-US
28/02/2015 18:14:58 - 	MoreInfoURL     : http://toolbox/orleans
28/02/2015 18:14:58 - 	InstalledByMSI  : False
28/02/2015 18:14:58 - 	SupportedFrameworkVersionRange : [4.5]
28/02/2015 18:14:58 - 
28/02/2015 18:14:58 - 	Supported Products : 
28/02/2015 18:14:58 - 		Microsoft.VisualStudio.Premium
28/02/2015 18:14:58 - 			Version : [11.0,14.0)
28/02/2015 18:14:58 - 		Microsoft.VisualStudio.Pro
28/02/2015 18:14:58 - 			Version : [11.0,14.0)
28/02/2015 18:14:58 - 		Microsoft.VisualStudio.Ultimate
28/02/2015 18:14:58 - 			Version : [11.0,14.0)
28/02/2015 18:14:58 - 
28/02/2015 18:14:58 - 	References      : 
28/02/2015 18:14:58 - 		-------------------------------------------------------
28/02/2015 18:14:58 - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
28/02/2015 18:14:58 - 		Name         : Visual Studio MPF 11.0
28/02/2015 18:14:58 - 		Version      : [11.0]
28/02/2015 18:14:58 - 		MoreInfoURL  : 
28/02/2015 18:14:58 - 		Nested       : No
28/02/2015 18:14:58 - 
28/02/2015 18:14:58 - 
28/02/2015 18:14:58 - Searching for applicable products...
28/02/2015 18:14:58 - Found installed product - Microsoft Visual Studio Ultimate 2015 CTP
28/02/2015 18:14:58 - Found installed product - Microsoft Visual Studio Premium 2015 CTP
28/02/2015 18:14:58 - Found installed product - Microsoft Visual Studio Professional 2015 CTP
28/02/2015 18:14:58 - Found installed product - Microsoft Visual Studio Community 2015 CTP
28/02/2015 18:14:58 - Found installed product - Microsoft Visual Studio 2015 CTP Shell (Integrated)
28/02/2015 18:14:58 - Found installed product - Global Location
28/02/2015 18:14:58 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

**Comment by ElanHasson** [comment]
@smoothdeveloper  did you ever submit a PR with the change?
