### ISSUE TITLE
Direct streaming between grains

### ISSUE THREAD

**Issue by bill-poole** [dotnet/orleans#7830]
We have a requirement to send streams of messages directly between grains - i.e., one grain sending a stream of messages directly to another grain. Furthermore, we need these streams to be particularly high performance, where the sender does not wait for acknowledgement of one message before sending another message - like with gRPC streaming requests.

We would be happy to use gRPC to stream messages between grains, but that would require being able to establish a gRPC connection from one grain to another, and that doesn't seem possible.

Sending individual messages is too slow given the latency between grains. I recognise that the messages can be batched, but that still requires each batch to be sent and processed one at a time, which means the next batch is not being sent while the previous batch is being processed.

This performance limitation also applies to Orleans streams because each stream event is delivered from the agent to consumers via the standard Orleans grain messaging - i.e., one at a time.

It would be great if a grain interface method could accept and/or return an `IAsyncEnumerable<TMessage>`, or something along those lines, which Orleans then understood/interpreted as inbound/outbound message streams.

**Comment by benjaminpetit** [comment]
I have a prototype of a working `IAsyncEnumerable<TMessage>`, but it is backed by persistent streams.

> Sending individual messages is too slow given the latency between grains

Is it the latency between grains the issue, or the time needed to process a request by the target grain? You could use `[OneWay]` messages to not wait for a response from the target, but it can make error handling difficult.

> This performance limitation also applies to Orleans streams because each stream event is delivered from the agent to consumers via the standard Orleans grain messaging - i.e., one at a time.

You can use batching with some streaming providers.

**Comment by arnoldp-workstreampeople-com** [comment]
> I have a prototype of a working `IAsyncEnumerable<TMessage>`, but it is backed by persistent streams.

Is there a chance that this prototype will become production ready code and released?

**Comment by ReubenBond** [comment]
xref #940 & #1916

**Comment by bill-poole** [comment]
>If you are using MemoryStreams, the stream publisher can push event one by one, but the consumer can get batches. If B was able to push 3 events while A was processing something, the next OnNextAsync from A can return these 3 events.

This seems similar to gRPC [client streaming](https://grpc.io/docs/what-is-grpc/core-concepts/#client-streaming-rpc), where the sender "pushes" messages to the receiver - except, with client streaming:
- flow control enforces a max window size, which limits the number of messages that have been sent but not yet received/processed; and
- the receiver replies with a single response message once the full stream has been received.

If a failure occurs, the initiating part re-sends the entire stream.

My use case is more akin to gRPC [server streaming](https://grpc.io/docs/what-is-grpc/core-concepts/#server-streaming-rpc) (as opposed to client streaming), where one party sends a message to request a stream from another party, and then the requested stream of messages is sent to the requesting party. Like with client streaming, flow control limits the number of messages that have been sent but not yet received/processed.

If a failure occurs, the initiating party re-requests the stream (or part thereof).

If senders/receivers are decoupled with a `MemoryStream`, then it seems that if a failure occurs, then neither the sender nor receiver can compensate for the failure - i.e., messages are lost. Is that correct? If each message sent by a sender via a stream is not acknowledged as received/processed by the receiver, then the sender cannot know to re-send messages that are not successfully received/processed by the receiver.

To my understanding, any time messages are sent via an intermediary such that the sender only knows about successful receipt by the intermediary (not the end receiving party), then the messages must be held in durable storage by the intermediary if at-least-once delivery is required to the end receiving party.

**Comment by benjaminpetit** [comment]
When a consumer receives an event with `OnNextAsync`, it also gets a `StreamSequenceToken`. This token allows to resume a subscription to a given stream position. Events stay in the cache for a given time, so the subscriber is free to "rewind" if needed, no need to notify the producer to send everything again.

If the subscriber gets a `CacheMissException`, then it means that some messages may have been lost. In this case, the consumer could send a request to the publisher to send again all the events to a new stream.

**Comment by bill-poole** [comment]
>When a consumer receives an event with OnNextAsync, it also gets a StreamSequenceToken. This token allows to resume a subscription to a given stream position. Events stay in the cache for a given time, so the subscriber is free to "rewind" if needed, no need to notify the producer to send everything again.

Thanks @benjaminpetit. If the stream is not durable (which I understand a `MemoryStream` is not), then upon a failure of the node hosting the stream, messages would be lost. I'm new at the Orleans/streams architecture so apologies if I've misunderstood.

i.e., the sender grain could send messages into the stream and then complete the operation, persisting a state that says that those messages were sent such that they will never be sent again. The consumer/receiver could keep track of the `StreamSequenceToken` as it consumes the stream such that if it fails, it can restart from the stream position where it failed. However, if the stream itself fails, then am I correct in assuming the messages would be lost?

**Comment by benjaminpetit** [comment]
That's correct, you may lose messages in case of failure.

I assumed that in your case, the publisher would enqueue a special message to denote the last event of a stream (`OnComplete` is there for historical reason, but was never implemented), and the consumer would send a `ack` when all messages were processed. 

If the consumer doesn't get the last message after a given time (or get a cache miss exception), or if the subscriber doesn't receive this `ack` in a timely manner, you could force a full delivery to another stream maybe?

**Comment by bill-poole** [comment]
Okay, so yes it is possible that the receiver/consumer grain could send a message back to the sender/producer grain when the stream has been fully consumed. Good point! I hadn't considered that. So you're correct that it could be made to work. But, it would be more complex than direct streaming between grains.

I guess it's somewhat similar to the added complexity of implementing a request-reply interaction through two correlated one-way calls - a request call and a reply callback - rather than as a synchronous request-reply interaction.

If the sender and receiver are decoupled over an unreliable streaming channel with a manual callback/ack method call, then the sender and receiver must both implement a workflow that manually compensates for any failures. However, if the sender and receiver are coupled over a direct connection, then the relevant party is immediately informed when a failure occurs as it occurs, which means the failed operation is naturally immediately retried.

It's also worth noting that streams deliver messages to consuming grains via standard grain message calls (as far as I understand them) - which means that the "last mile" of stream delivery is standard message-by-message method calls, meaning each message is received, processed and acknowledged one at a time. If the stream is hosted on a different silo than the consuming grain, then this "last mile" would be a bottleneck in message delivery performance.

So, I think there would be benefit in grains supporting a streaming interface (i.e., methods accepting/returning `IAysncEnumerable<TMessage>`), which could be used for more efficient Orleans stream production/consumption - but also for direct grain-to-grain streaming.

**Comment by ReubenBond** [comment]
Orleans supports returning `IAsyncEnumerable<T>` from a grain method as of v7.2.0: https://github.com/dotnet/orleans/pull/8416

**Comment by bill-poole** [comment]
Thanks @ReubenBond!
