### ISSUE TITLE
Move Contributions links to main readme.md

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [dotnet/orleans#785]
Hi awesome Orleaners
Currently links to contributions like Orleans templates is barried in the documentation, Shouldn't we include them at the bottom of readme.md to be easier to find? 
And maybe links to more important contribution projects like Orleans Templates and ES?

**Comment by sergeybykov** [comment]
Wouldn't that be a single link to https://github.com/OrleansContrib/? Maybe we should indeed elevate it to the readme.

**Comment by gabikliot** [comment]
Added a link to Readme.md
