### ISSUE TITLE
I just used Autofac.Core. And I got an error？

### ISSUE THREAD

**Issue by wz172** [dotnet/orleans#7866]
![image](https://user-images.githubusercontent.com/46833139/179756659-d3731acf-c0eb-4a19-a75e-77735acfda67.png)

![image](https://user-images.githubusercontent.com/46833139/179756761-44070285-4eb9-40dc-a0e8-13bb12edcf39.png)

**Comment by ReubenBond** [comment]
Is the issue that no grain storage providers are configured?
