### ISSUE TITLE
Why use old Asp.net way on GPSTracker

### ISSUE THREAD

**Issue by behroozbc** [dotnet/orleans#7868]
### Discussed in https://github.com/dotnet/orleans/discussions/7867

<div type='discussions-op-text'>

<sup>Originally posted by **behroozbc** July 19, 2022</sup>
I see this [line of code](https://github.com/dotnet/orleans/blob/d700bb3eed98e16d4ea515f297c29417238ae27c/samples/GPSTracker/GPSTracker.Service/Program.cs#L5) that uses the old aspnet way.
https://github.com/dotnet/orleans/blob/d700bb3eed98e16d4ea515f297c29417238ae27c/samples/GPSTracker/GPSTracker.Service/Program.cs#L5
Why should we use this way instate of using the below approach? And what benefits the old method?
```

var builder = WebApplication.CreateBuilder(args);

builder.Host.UseOrleans((ctx, siloBuilder) => {

    siloBuilder.UseLocalhostClustering(
        siloPort: 11111 + instanceId,
        gatewayPort: 30000 + instanceId,
        primarySiloEndpoint: new IPEndPoint(IPAddress.Loopback, 11111));

});
.
.
.
var app = builder.Build();
...
...
...
app.Run();

```
</div>

**Comment by ReubenBond** [comment]
Fixed by #7869
