### ISSUE TITLE
Consider renaming GenerateSerializerAttribute

### ISSUE THREAD

**Issue by bill-poole** [dotnet/orleans#7872]
The .NET runtime has recently [renamed `RegexGeneratorAttribute` to `RegexAttribute`](https://github.com/dotnet/runtime/issues/62123) (dropping the "Generator"). Likewise, the `[DllImportGenerator]` attribute was renamed to `[LibraryImport]`. Furthermore, the `[JsonSerializable]` and `[LoggerMessage]` attribute names do not contain "Generate", "Generator" or "Generated".

I was therefore wondering whether `[OrleansSerializable]` or maybe `[HagarSerializable]` would be more consistent with this direction taken by the .NET runtime?

**Comment by ReubenBond** [comment]
This is a good idea. I wanted the attribute name to be very clear about its purpose (it causes a serializer to be generated), but `[OrleansSerializable]` is likely a better name and is still clear.

**Comment by jeremylcarter** [comment]
> This is a good idea. I wanted the attribute name to be very clear about its purpose (it causes a serializer to be generated), but `[OrleansSerializable]` is likely a better name and is still clear.

Its a tough one, because the act of using the attribute does not force the user to also have the serialization package(s). Perhaps in the description/help of this attribute it should mention that codegen is required for this attribute to be of any use.

**Comment by bill-poole** [comment]
Should the attribute be shipped with the serialization package(s)?

**Comment by ReubenBond** [comment]
Maybe we should bundle codegen in by including it as a dependency of the package which holds the attribute itself.
It's one of the things which trips up more people than it should. I'm not aware of compelling reasons not to bundle it.

**Comment by ReubenBond** [comment]
We shipped without doing this, so I'll close this for now, but we could consider renames/obsoletion in the future.
