### ISSUE TITLE
System.Text.Json instead of Newtonsoft Json.NET?

### ISSUE THREAD

**Issue by bill-poole** [dotnet/orleans#7874]
It looks like a prior proposal to switch to System.Text.Json (STJ) from Newtonsoft Json.NET (#6070) was not accepted due to lack of support for polymorphism in STJ. However, it appears [support has now been added for .NET 7](https://github.com/dotnet/runtime/pull/71346). Should replacing Newtonsoft with STJ therefore be re-evaluated?

**Comment by bill-poole** [comment]
Thanks @ReubenBond. Apologies I wasn't sufficiently specific - I was actually talking about persistence - specifically the DynamoDB provider. So if I understand you correctly, the position going forward for the DynamoDB persistence provider is to continue to use Newtonsoft as the default serializer, but allow a custom serializer to be configured, which would allow STJ to be used?

**Comment by ReubenBond** [comment]
The position is that storage providers shouldn't be responsible for serialization. Instead, they should delegate that to `IGrainStorageSerializer`, which can have various implementations (one per storage provider). If there's a default, Newtonsoft.Json certainly provides a better experience than System.Text.Json out of the box. Is there any particular reason you'd prefer System.Text.Json be the default?

**Comment by bill-poole** [comment]
I'm not particularly fussed about what the default storage serializer is as long as it is configurable. That being said, it would be nice to avoid unnecessarily packaging Newtonsoft Json.NET with my application. My primary concerns/interests wrt using STJ instead of Json.NET are:
- Performance: STJ is a much higher performance serializer than Json.NET and I have a very data-intensive application (that writes a lot of data to storage in very fast bursts) where every CPU cycle is precious.
- Consistency: I would like to avoid having some JSON serialized with STJ and the rest with Json.NET in my application because the two libraries can have different behaviours.
