### ISSUE TITLE
[3.x] Regression in GenericMethodInvoker with generic constraints

### ISSUE THREAD

**Issue by niblak** [dotnet/orleans#7875]
#7185 (and subsequent changes) introduced a regression in GenericMethodInvoker when the method specifies a type constraint that is also itself generic. This used to work in Orleans 3.4.3, but will now throw `Could not find exact match for generic method` on 3.6.2.

I will submit a PR to address this in the 3.x branch. Looks like this code path has been removed in the main branch as part of the serializer improvements in 4.0. My project has not yet upgraded to 4.0 so I am not sure what if any changes need to be made there, but it would be good if someone could investigate whether this regression also exists in 4.0.

**Comment by ReubenBond** [comment]
Fixed by #7876
