### ISSUE TITLE
Unable to find UseAzureTableReminderService on Microsoft.Orleans.Reminders.AzureStorage v3.6.x onward

### ISSUE THREAD

**Issue by Desz01ate** [dotnet/orleans#7880]
Refer to https://dotnet.github.io/orleans/docs/grains/timers_and_reminders.html#configuration

I was able to find `UseAzureTableReminderService` on Microsoft.Orleans.Reminders.AzureStorage v3.5.1 just fine, however when upgrading to v3.6.x the extension method is nowhere to be found, is it renamed or am I missing something?

**Comment by taurusni** [comment]
The extension method is applied to both ISiloHostBuilder and ISiloBuilder in v3.5.1. But the method is only applied to ISiloBuilder in v3.6.2.

Is there any reason for that change?

Thanks

**Comment by benjaminpetit** [comment]
Sorry I thought I already responded to that issue.

@Desz01ate We changed how to configure the azure storage providers. Now it can be configured like this: ``builder.UseAzureTableReminderService(connectionString)``

@taurusni `ISiloHostBuilder` is deprecated, you should use `ISiloBuilder` instead.

**Comment by Desz01ate** [comment]
@benjaminpetit thanks for the solution!

**Comment by taurusni** [comment]
@benjaminpetit Thanks for the clarification. 

However, the https://docs.microsoft.com/en-us/dotnet/api/orleans.hosting.isilohostbuilder?view=orleans-3.0 doesn't mention that and the migration from `ISiloHostBuilder` to `ISiloBuilder` is not seamlessly. For example, OrleansServiceListener still depends on the `ISiloHostBuilder`

Will `ISiloHostBuilder` be obsolete in Orleans 4.0?

Thanks in advance.

**Comment by benjaminpetit** [comment]
@taurusni sorry missed the last message.

Yes `ISiloHostBuilder` is removed from 4.0

**Comment by thakursagar** [comment]
> @benjaminpetit Thanks for the clarification.
> 
> However, the https://docs.microsoft.com/en-us/dotnet/api/orleans.hosting.isilohostbuilder?view=orleans-3.0 doesn't mention that and the migration from `ISiloHostBuilder` to `ISiloBuilder` is not seamlessly. For example, OrleansServiceListener still depends on the `ISiloHostBuilder`
> 
> Will `ISiloHostBuilder` be obsolete in Orleans 4.0?
> 
> Thanks in advance.

@taurusni were you able to figure out how to migrate from ISiloHostBuilder to ISiloBuilder when upgrading to 3.6.x? I am not seeing a method exposed on the OrleansServiceListener which would accept ISiloBuilder so not sure how to fix that? @benjaminpetit any thoughts?

**Comment by ReubenBond** [comment]
For the Service Fabric case, we recommend a different approach. We recommend integrating `IHost` with the SF communication listener lifetime and adding Orleans to that `IHost` (via the `IHostBuilder.UseOrleans(...)` extension method). For an example, see: [HostedServiceStatelessService](https://gist.github.com/ReubenBond/83a08cfdc77d6232f97ec531e377fdc4)

**Comment by taurusni** [comment]
@thakursagar I didn't do the migration. Will do that when I can not avoid. The missing function is maintained locally for the time being.

@ReubenBond Thanks for the suggestion.
