### ISSUE TITLE
Information about multiple persistence?

### ISSUE THREAD

**Issue by wz172** [dotnet/orleans#7882]
I am using Grain as a parent class. The persistence information is used in subclasses and added to the constructor of the parent class. Is there any other way to add the persistence field?For example, use Iserviceprovider

![image](https://user-images.githubusercontent.com/46833139/181149583-5397e0d7-f9e9-4c5f-bf10-908e9607640a.png)

**Comment by bradygaster** [comment]
You could just inject another one. Here's an example of a use-case where I'm doing that in a sample code. 

```csharp
public WorldGrain([PersistentState(Constants.PersistenceKeys.WorldStateName,
        Constants.PersistenceKeys.WorldStorageName)]
        IPersistentState<World> world,
       [PersistentState(Constants.PersistenceKeys.PlayerStateName,
        Constants.PersistenceKeys.PlayerStorageName)]
        IPersistentState<Player> player,
        IHubContext<WanderlandHub, IWanderlandHubClient> wanderlandHub,
        ILogger<WorldGrain> logger)
    {
        _world = world;
        _player = player;
        _wanderlandHub = wanderlandHub;
        _logger = logger;
    }
```
