### ISSUE TITLE
Getting Started link references an Orleans 2.2 guide.

### ISSUE THREAD

**Issue by rwkarg** [dotnet/orleans#7884]
https://github.com/dotnet/orleans/blob/55053831da91ebb986cda639a9027a4a67f88e0a/README.md?plain=1#L163

The above link references being tested with Orleans 2.2.0:

> This tutorial provides step-by-step instructions for creating a basic functioning Orleans application. It is designed to be self-contained and minimalistic, with the following traits:
> 
> It relies only on NuGet packages
It has been tested in Visual Studio 2017 using Orleans 2.2.0
It has no reliance on external storage

It's unclear if the steps still work for 3.X (or 4.0) but my assumption would be that it wouldn't given the major version jump(s).

**Comment by bradygaster** [comment]
cc @IEvangelist

**Comment by ReubenBond** [comment]
Fixed
