### ISSUE TITLE
Is it safe to call HttpContext inside the grain?

### ISSUE THREAD

**Issue by MaximTkachenko** [dotnet/orleans#7897]
I have an http endpoint which puts id into the current httpcontext and then call the grain:
```
HttpContext.Items["id"] = Guid.NewGuid().ToString();
var d = await _cluster.GetGrain<IHttpGrain>(1).GetId();
```
The grain returns this id from the current httpcontext (**this grain activation and httprequest are on the same server**):
```
public class HttpGrain : Grain, IHttpGrain
{
    private readonly IHttpContextAccessor _http;    
    public HttpGrain(IHttpContextAccessor http)
    {
        _http = http;
    }
    
    public async Task<string> GetId()
    {
        return Task.FromResult((string)_http.HttpContext.Items["id"]);
    }
}
```
I call the endpoint like this:
```
var http = new HttpClient();
var tasks = new List<Task<string>>
{
    http.GetStringAsync("http://localhost:8080/test"),
    http.GetStringAsync("http://localhost:8080/test"),
    http.GetStringAsync("http://localhost:8080/test"),
    http.GetStringAsync("http://localhost:8080/test"),
    http.GetStringAsync("http://localhost:8080/test"),
    http.GetStringAsync("http://localhost:8080/test"),
    http.GetStringAsync("http://localhost:8080/test"),
    http.GetStringAsync("http://localhost:8080/test"),
};
await Task.WhenAll(tasks);
foreach (var result in tasks.Select(x => x.Result))
{
    Console.WriteLine(result);
}
```
The output:
```
055fb4a5-3151-4028-ae1d-a486cc93171f
055fb4a5-3151-4028-ae1d-a486cc93171f
055fb4a5-3151-4028-ae1d-a486cc93171f
055fb4a5-3151-4028-ae1d-a486cc93171f
055fb4a5-3151-4028-ae1d-a486cc93171f
abb34f03-bd83-487c-8892-5577d3139878
abb34f03-bd83-487c-8892-5577d3139878
abb34f03-bd83-487c-8892-5577d3139878
```
I suppose it's because Orleans has its own `TaskScheduler` and puts tasks into the queue and that's why in some cases it's mixing, i.e. `AsyncLocal` used in `IHttpContextAccessor` works incorrectly in that case. Could you explain this behavior with more details? Is a calling `IHttpContextAccessor` inside the grain a bad idea or it's possible to make it work?

**Comment by rwkarg** [comment]
The Grain could be on a completely different process/machine (from a conceptual standpoint, even if you have a specific scenario where it's on the same process) so that wouldn't work.

Pull the data from the code processing the incoming HTTP request before calling in to the grain. Then pass that in to the grain call as an argument.

**Comment by ElanHasson** [comment]
An alternative is to copy the HttpContext values into the Orleans RequestContext https://dotnet.github.io/orleans/docs/grains/request_context.html

**Comment by SebastianStehle** [comment]
There are a lot of values that cannot be copied, like body-stream, pipe-reader and so on. You could put basically everything you want inside a http context, so you could (by accident) put a 100MB buffer into the request context.

**Comment by MaximTkachenko** [comment]
I know that in general a grain could be on another server, but in my case I have a check to prevent it. I need `HttpContext` to accept a websocket connection and start listening so I need a real `HttpContext` not just values from it. My current workaround:
- I registered a singleton class which internally has `ConcurrentDictionary` of `<string key, HttpContext ctx>`
- when I receive a request I put the httpcontext into the singleton instance and pass the key into the grain
- then I read the HttpContext from the singleton within the grain.
I know that HttpContext could be invalidated but in my case it's ok to fail in that case.

**Comment by SebastianStehle** [comment]
This sounds good, I guess this is the same approach that is used by SignalR.
