### ISSUE TITLE
[question]a little confusion about ProcessSiloAddEvent(SiloAddress addedSilo) ' in GrainDirectoryHandoffManager.cs

### ISSUE THREAD

**Issue by yulei1990** [dotnet/orleans#7898]
in this function 'internal void ProcessSiloAddEvent(SiloAddress addedSilo) ' of GrainDirectoryHandoffManager.cs
`
                // Reset our follower list to take the changes into account
                ResetFollowers();

                // check if this is one of our successors (i.e., if I should hold this silo's copy)
                // (if yes, adjust local and/or copied directory partitions by splitting them between old successors and the new one)
                // NOTE: We need to move part of our local directory to the new silo if it is an immediate successor.
                List<SiloAddress> successors = localDirectory.FindSuccessors(localDirectory.MyAddress, 1);
                if (!successors.Contains(addedSilo))
                {
                    if (logger.IsEnabled(LogLevel.Debug)) logger.Debug($"{addedSilo} is not one of my successors.");
                    return;
                }
`
List<SiloAddress> successors = localDirectory.FindSuccessors(localDirectory.MyAddress, 1);  

when the above code executes,  only the immediate successor of myAddress is returned.
so, if the immediate silo is not "addedSilo", then the following if statement will always be true and the function return immediately. why only one successor is needed here.
i get stuck in there why only pass "1" to the FindSuccessors function.

looking forward to your reply

**Comment by yulei1990** [comment]
can anyone help me about this question?

**Comment by ReubenBond** [comment]
It's only supposed to find a single successor. This is a process for splitting the grain directory when a new silo is added, so it does not need to know about any silos which come after the immediate successor: that successor is the one which it sends a portion of its directory entries to.

**Comment by yulei1990** [comment]
thank your for your reply. but if only immediate successor is supposed here.
then the following code's "else" part will never get a chance to execute.

```
// check if this is one of our successors (i.e., if I should hold this silo's copy)
                // (if yes, adjust local and/or copied directory partitions by splitting them between old successors and the new one)
                // NOTE: We need to move part of our local directory to the new silo if it is an immediate successor.
                List<SiloAddress> successors = localDirectory.FindSuccessors(localDirectory.MyAddress, 1);
                if (!successors.Contains(addedSilo))
                {
                    if (logger.IsEnabled(LogLevel.Debug)) logger.Debug($"{addedSilo} is not one of my successors.");
                    return;
                }

                // check if this is an immediate successor
                if (successors[0].Equals(addedSilo))
                {
                    // split my local directory and send to my new immediate successor his share
                    if (logger.IsEnabled(LogLevel.Debug)) logger.Debug("Splitting my partition between me and " + addedSilo);
                    GrainDirectoryPartition splitPart = localDirectory.DirectoryPartition.Split(
                        grain =>
                        {
                            var s = localDirectory.CalculateGrainDirectoryPartition(grain);
                            return (s != null) && !localDirectory.MyAddress.Equals(s);
                        }, false);
                    List<ActivationAddress> splitPartListSingle = splitPart.ToListOfActivations(true);
                    List<ActivationAddress> splitPartListMulti = splitPart.ToListOfActivations(false);

                    EnqueueOperation(
                        $"{nameof(ProcessSiloAddEvent)}({addedSilo})",
                        () => ProcessAddedSiloAsync(addedSilo, splitPartListSingle, splitPartListMulti));
                }
                else
                {
                    // adjust partitions by splitting them accordingly between new and old silos
                    SiloAddress predecessorOfNewSilo = localDirectory.FindPredecessors(addedSilo, 1)[0];
                    if (!directoryPartitionsMap.TryGetValue(predecessorOfNewSilo, out var predecessorPartition))
                    {
                        // we should have the partition of the predcessor of our new successor
                        logger.Warn(ErrorCode.DirectoryPartitionPredecessorExpected, "This silo is expected to hold directory partition of " + predecessorOfNewSilo);
                    }
                    else
                    {
                        if (logger.IsEnabled(LogLevel.Debug)) logger.Debug("Splitting partition of " + predecessorOfNewSilo + " and creating a copy for " + addedSilo);
                        GrainDirectoryPartition splitPart = predecessorPartition.Split(
                            grain =>
                            {
                                // Need to review the 2nd line condition.
                                var s = localDirectory.CalculateGrainDirectoryPartition(grain);
                                return (s != null) && !predecessorOfNewSilo.Equals(s);
                            }, true);
                        directoryPartitionsMap[addedSilo] = splitPart;
                    }
                }
```
i think the following "else part" handles the situation that the spliting silo is not the immediate silo.
if  List<SiloAddress> successors = localDirectory.FindSuccessors(localDirectory.MyAddress, 1);  is only supposed to find
the immediate successor. then the else part will never be executed.
that is the thing that has beening confusing me.

**Comment by ReubenBond** [comment]
That class is quite confusing. It did contain some dead code. Take a look at the current version, since it was updated recently

**Comment by yulei1990** [comment]
i got the latest code. that class did change a lot. i will read the code soon. thank your for your patience.
