### ISSUE TITLE
Need help with system design 1-M implementation for Client and Order classes

### ISSUE THREAD

**Issue by P9avel** [dotnet/orleans#7899]
Hi, i am need to have acess to Client with orders and each Order separate. I am think need 2 classes for grains. 

public record Order(int Number, IList<Product> Products);

public interface IClient
{
   IList<Order> GetOrders();
}

public interface IOrder
{
   IOrder GetOrder();
}
 And now syncronization states in 2 grains for each Order changes. Can you to show beatifull design? How correct implement so tasks?

**Comment by ReubenBond** [comment]
Hi @P9avel, this is the kind of question which might be better for a discussion on Discord: https://aka.ms/orleans-discord
The community might be able to help.

**Comment by P9avel** [comment]
Many thanks for your link
