### ISSUE TITLE
[Question] Grain activation is jumping between silos during the cluster update

### ISSUE THREAD

**Issue by MaximTkachenko** [dotnet/orleans#7904]
I host Orleans cluster in AWS ECS Fargate. I faced the strange behavior:
- I update the cluster;
- when silo A with grain B is deactivated this grain is activated on one of the new silos;
- after a few minutes the new silo deactivates grain B (I don't know why) and then the grain is activated on another silo; sometimes I have 2 or 3 such hops between new silos.

What is the possible reason for such behavior? As I understand when the grain is activated it should work on the home silo.

**Comment by MaximTkachenko** [comment]
I found such logs 
![image](https://user-images.githubusercontent.com/1560515/183862103-926a58f0-6dff-4478-9615-dbac444f1b16.png)
I suppose it's from [Catalog.StartDeactivatingActivations](https://github.com/dotnet/orleans/blob/639be7f3e83262e70327b58892d6cf54c801b32d/src/Orleans.Runtime/Catalog/Catalog.cs#L347) which is called in [on silo status change](https://github.com/dotnet/orleans/blob/639be7f3e83262e70327b58892d6cf54c801b32d/src/Orleans.Runtime/Catalog/Catalog.cs#L463).

**Comment by benjaminpetit** [comment]
The default directory is distributed in the cluster.

Let's say you have a 3-silo cluster. `SiloA` is hosting the activation of `Grain1`, and  `Grain1` directory entry is stored by `SiloB`.

If `SiloB` shuts down (gracefully or not), then the entry for `Grain1` might be now the responsibility of `SiloC`. To avoid duplicate activations, it's safe for `SiloA` to just deactivate its activation of `Grain1`, and a new one will be created on next call.

**Comment by MaximTkachenko** [comment]
@benjaminpetit Is there a way to somehow minimize this behavior?

**Comment by benjaminpetit** [comment]
> Ok, is there a way to somehow minimize this behavior with the default in-memory directory?

Not really. Today it should be easier to implement a more robust in memory directory thanks to the public interface `IGrainDirectory`

> How is a directory entry placement defined?

Do you mean how to configure a custom directory?

**Comment by MaximTkachenko** [comment]
@benjaminpetit Currently I don't want to switch to redis based or azure table based grain directory.
Could you elaborate a bit this idea:

> Today it should be easier to implement a more robust in memory directory thanks to the public interface IGrainDirectory

Do you mean a custom grain directory which might replace default one based on DHT?

**Comment by benjaminpetit** [comment]
> Do you mean a custom grain directory which might replace default one based on DHT?

Yes, exactly. Before the DHT directory was plumbed too deep into Orleans core. We have to keep it for backward compatibility reason, and because it's still the most robust and battle tested. But it would be nice to see another take at an in-memory implementation.
