### ISSUE TITLE
Generator 'OrleansSerializationSourceGenerator' failed to generate source, 4.0.0-preview2 

### ISSUE THREAD

**Issue by COCPORN** [dotnet/orleans#7907]
I think I've managed to upgrade relatively well to preview2, but I am getting this error message still: `CS8785    Generator 'OrleansSerializationSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.TypeParameterSymbol' to type 'Microsoft.CodeAnalysis.INamedTypeSymbol'.' `.

This manifests for me as Orleans picking up the grain interfaces, but not their implementation, it seems. I think they are related.

It logs like this at runtime, which is similar to what I assume the error message would be if the implementation was just missing:

```
System.ArgumentException: Could not find an implementation for interface HelloWorld.IHelloWorldService
   at Orleans.GrainInterfaceTypeToGrainTypeResolver.GetGrainType(GrainInterfaceType interfaceType) in /_/src/Orleans.Core/Core/GrainInterfaceTypeToGrainTypeResolver.cs:line 149
   at Orleans.GrainFactory.GetGrain(Type interfaceType, IdSpan grainKey, String grainClassNamePrefix) in /_/src/Orleans.Core/Core/GrainFactory.cs:line 214
   at Orleans.GrainFactory.GetGrain(Type grainInterfaceType, Int64 key) in /_/src/Orleans.Core/Core/GrainFactory.cs:line 162
   at Orleans.Runtime.InternalClusterClient.GetGrain(Type grainInterfaceType, Int64 grainPrimaryKey) in /_/src/Orleans.Runtime/Core/InternalClusterClient.cs:line 129
```

It seems to me to start occurring with preview2 as the same (or at least similar code) worked fine with preview1, but I am not 100% sure exactly when it started happening.

Also, this could obviously be related to me not correctly doing the upgrade from preview1 to preview2.

**Comment by jeremylcarter** [comment]
Could you confirm that the codegen has worked?

For instance you should be able to decompile your dll/exe and see that the codegen has created a namespace etc for all of the activators, serialization codecs etc.

![image](https://user-images.githubusercontent.com/2087337/184518759-77cb42b6-5722-4cb4-bd04-b44b9e805d1c.png)

**Comment by jeremylcarter** [comment]
I can replicate the issue with the following simple application:

````
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Orleans;
using Orleans.Hosting;

var hostBuilder = new HostBuilder();
hostBuilder.UseOrleans((ctx, siloBuilder) =>
{
    siloBuilder.UseLocalhostClustering();
});

var host = hostBuilder.Build();

await host.StartAsync();

var client = host.Services.GetService<IClusterClient>();
await client.GetGrain<IHelloGrain>(0).SayHello();

await host.StopAsync();

[Serializable]
[GenerateSerializer]
public class HelloResponse
{
    [Id(0)]
    public string Response { get; set; }
}

public class HelloGrain : Grain, IHelloGrain
{
    public Task<HelloResponse> SayHello()
    {
        return Task.FromResult(new HelloResponse() { Response = "Hello" });
    }
}

public interface IHelloGrain : IGrain, IGrainWithIntegerKey
{
    Task<HelloResponse> SayHello();
}
````
![image](https://user-images.githubusercontent.com/2087337/184519607-929f22d4-980f-4b11-93c0-316b4cddb0f4.png)

**Comment by ReubenBond** [comment]
I cannot repro your issue @jeremylcarter - I tried with your project, targeting it to `4.0.0-preview2` or locally built packages. I didn't try with referencing the packages using `ProjectReference`, since that's not a supported case anyway.

I can repro your case, @COCPORN, using the OCore repo. I believe the issue is that your `IDataEntityGrain` has a non-`Task`-returning method:

``` C#
public interface IDataEntity : IGrainWithStringKey
{
    /// <summary>
    /// Get a decomposed part with the same identity
    /// </summary>
    /// <typeparam name="T">The type</typeparam>
    /// <returns></returns>
    T Get<T>() where T: IDataEntity, new();
}
```

This should be returning `Task<T>` or `ValueTask<T>`, not merely `T`.

**Comment by COCPORN** [comment]
@ReubenBond Yes, that does indeed seem to fix it, totally my bad for adding new features at the same time I was trying to upgrade Orleans. Sorry for the red herring and thank you so much for your help!

I didn't test @jeremylcarter 's reproduction in this case, but what I originally reported has gone away with your guidance.

I did get another set of errors trying to change it to a Task<T> in the interface, however I don't really need this to be part of the interface at all, so that's OK and probably something for another day.

**Comment by jeremylcarter** [comment]
> I cannot repro your issue @jeremylcarter - I tried with your project, targeting it to `4.0.0-preview2` or locally built packages. I didn't try with referencing the packages using `ProjectReference`, since that's not a supported case anyway.
> 
> I can repro your case, @COCPORN, using the OCore repo. I believe the issue is that your `IDataEntityGrain` has a non-`Task`-returning method:
> 
> ```cs
> public interface IDataEntity : IGrainWithStringKey
> {
>     /// <summary>
>     /// Get a decomposed part with the same identity
>     /// </summary>
>     /// <typeparam name="T">The type</typeparam>
>     /// <returns></returns>
>     T Get<T>() where T: IDataEntity, new();
> }
> ```
> 
> This should be returning `Task<T>` or `ValueTask<T>`, not merely `T`.

Sorry for the run around then. Glad you got a result.

**Comment by ReubenBond** [comment]
@COCPORN I'm diagnosing the issue and looking to add a better error, something which will appear in VS.

@jeremylcarter no worries - if you can repro it with the packages from NuGet, please let us know. If you want to build against what's in main, check out the Directory.Build.* files in src to see how to configure it

**Comment by ReubenBond** [comment]
I'm reopening this, since the error message you hit is clearly a bad developer experience.
Here's the output from the new analyzer when building OCore:
`Error	ORLEANS0102	The type T for the grain interface method OCore.Entities.Data.IDataEntity.Get<T>() cannot be used as a grain method return type. Grain methods must return one of the following types: System.Threading.Tasks.ValueTask<>, System.Threading.Tasks.ValueTask, System.Threading.Tasks.Task<>, System.Threading.Tasks.Task, void.	OCore.Entities.Data	C:\tmp\OCore\src\OCore\OCore.Entities.Data\IDataEntity.cs	15`
![image](https://user-images.githubusercontent.com/203839/185014250-6efdb0bd-66f0-49df-a8c0-ed6ceb7785ee.png)

**Comment by jeremylcarter** [comment]
Great result @ReubenBond !
