### ISSUE TITLE
[4.0] Inheritance hierarchy deserialization fails after update to 4.0-preview2

### ISSUE THREAD

**Issue by christiansparre** [dotnet/orleans#7921]
We have a few records that are part of an inheritance hierarchy. Ex. Foo > Bar > Baz. After updating from 4.0-preview1 to 4.0-preview2 this fails with "Insufficient data present in buffer." exceptions - seems to be the `IsSpanInput` check in https://github.com/dotnet/orleans/blob/main/src/Orleans.Serialization/Buffers/Reader.cs#L550

I have made a simple repro here that shows the problem: https://github.com/christiansparre/OrleansSerializationIssueRepro20220816

The records are as follows

```csharp
[GenerateSerializer]
public record Foo([property: Id(1)] string Message) : Bar
{
    public override string Type => "Foo";
}

[GenerateSerializer]
public abstract record Bar : Baz;

[GenerateSerializer]
public abstract record Baz
{
    public abstract string Type { get; }
}
```

Are we missing something in the [GenerateSerializer],[Id] annotations?

It seems that if `Bar` or `Baz` have properties in the primary constructor it works, but I have not explored all combinations.

The "empty" base types are a bit of an edge case maybe, in our solution the inheritance hierarchy is a part of some "generic" settings code. We have not finalized the design yet so might work around this problem if there is not another workaround.

**Comment by ReubenBond** [comment]
xref #7923
