### ISSUE TITLE
System.InvalidOperationException: OutgoingCallInvoker.Invoke() received an invalid call.

### ISSUE THREAD

**Issue by canitez** [dotnet/orleans#7922]
Hi, although not constantly, we sometimes get this error. Is the problem caused by startup settings, what could be the reason?

` public void ConfigureCustomServices(IServiceCollection services)
        {
            var retryAsyncPolicy = Policy
                .Handle<Exception>(e => !(e is BusinessException))
                .RetryAsync();

            services.AddSingleton(typeof(IHttpContextAccessor), new HttpContextAccessor());
            services.AddTransient(typeof(IUserPrincipalContextFactory), typeof(ClientUserPrincipalContextFactory));

            services.AddTransient(typeof(IClientBuilder), aspnetProvider =>
            {
                IClientBuilder clientBuilder = new ClientBuilder()
                    .Configure<ClusterOptions>(options =>
                    {
                        options.ClusterId = orleansSettings.ClusterId;
                        options.ServiceId = orleansSettings.ServiceId;
                    })
                    .ConfigureServices(sc =>
                    {
                        sc.AddSingleton(typeof(ILoggerFactory), orleansProvider => aspnetProvider.GetRequiredService<ILoggerFactory>());
                        sc.AddSingleton(typeof(IMetrics), orleansProvider => aspnetProvider.GetRequiredService<IMetrics>());
                    })
                    .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(CommonTypesPointer).Assembly).WithReferences())
                    .AddClusterConnectionLostHandler((object sender, EventArgs e) =>
                    {
                        var metrics = aspnetProvider.GetRequiredService<IMetrics>();
                        metrics.Measure.Counter.Increment(MetricsRegistry.ClusterConnectionLostCounter);

                        Log.Fatal("Cluster connection lost");
                    })
                    .AddOutgoingGrainCallFilter<MetricCallFilter>()
                    .AddOutgoingGrainCallFilter(async context =>
                    {
                        HttpContextAccessor accessor = new HttpContextAccessor();

                        if (accessor.HttpContext != null)
                        {
                            RequestContext.Set("Language", new ClientLanguageProvider(accessor).Language);
                            RequestContext.Set("UserPrincipal", new UserPrincipal(accessor.HttpContext.User));
                            RequestContext.Set("CorrelationId", new LogCorrelationIdGeneratorForHttp(accessor).GetCorrelationId());
                            RequestContext.Set("RequestPath", accessor.HttpContext.Request.Path.ToString());
                            RequestContext.Set("ClientMachineName", Environment.MachineName);
                        }

                        await retryAsyncPolicy.ExecuteAsync(() => context.Invoke());
                    });

                if (environment.IsEnvironment("LocalDevelopment"))
                {
                    clientBuilder.UseLocalhostClustering();
                }
                else if (orleansSettings.UseStaticGatewayList)
                {
                    // Uri format should be like: gwy.tcp://127.0.0.1:1/0
                    string[] uris = orleansSettings.ClusterIPList;

                    clientBuilder.UseStaticClustering((StaticGatewayListProviderOptions o) =>
                    {
                        foreach (var uriStr in uris)
                        {
                            Uri uri = new Uri(uriStr);
                            if (uri.HostNameType == UriHostNameType.Dns)
                            {
                                System.Net.IPHostEntry host = System.Net.Dns.GetHostEntry(uri.Host);
                                var uriBuilder = new UriBuilder(uri);
                                uriBuilder.Host = host.AddressList.First().ToString();
                                uri = uriBuilder.Uri;
                            }

                            o.Gateways.Add(uri);
                        }
                    });
                }
                else
                {
                    clientBuilder
                        .UseAdoNetClustering(options =>
                        {
                            var connectionStringBuilder = new NpgsqlConnectionStringBuilder(configuration.GetConnectionString("SiloConnection"));
                            connectionStringBuilder.Password = orleansSettings.SiloDatabasePassword;
                            options.ConnectionString = connectionStringBuilder.ConnectionString;
                            options.Invariant = orleansSettings.AdoProvider;
                        });
                }

                return clientBuilder;
            });
        }`

System.InvalidOperationException: OutgoingCallInvoker.Invoke() received an invalid call.

at Orleans.Runtime.OutgoingCallInvoker.ThrowInvalidCall()

at Orleans.Runtime.OutgoingCallInvoker.Invoke()

at Polly.RetrySyntaxAsync.<>c__DisplayClass9_1.<<RetryAsync>b__1>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

at Polly.Retry.RetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory, Boolean continueOnCapturedContext)

at Polly.Retry.RetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory, Boolean continueOnCapturedContext)

at Polly.Policy.ExecuteAsyncInternal(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)

at Polly.Policy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)

**Comment by ReubenBond** [comment]
Hi @canitez, which version of Orleans are you using?

**Comment by canitez** [comment]
> Hi @canitez, which version of Orleans are you using?

I'm using version 2.2

**Comment by ReubenBond** [comment]
Ok, that likely explains what you experienced. This was fixed in a later release: #6414
