### ISSUE TITLE
Applying [Id(x)] to a property init method results in NRE when resolving Serializer<T>. Could source generators possibly flag this as an error?

### ISSUE THREAD

**Issue by MarkNickeson** [dotnet/orleans#7924]
Repro with workaround:  [https://gist.github.com/MarkNickeson/c21d86a77b891b28b2ba44c77a6eb324](https://gist.github.com/MarkNickeson/c21d86a77b891b28b2ba44c77a6eb324)

Given the record definition below, the [Id(0)] attribute on Bar is basically invalid because init can only be invoked during construction. However, a developer does not receive feedback until they attempt to resolve the serializer at which point a NRE is thrown.

One workaround is to move the [Id(0)] to the backing field and use SerializationCallbacks to perform necessary logic after fields/properties have been deserialized.

Ideally it would be nice if the source generators could flag the error while they are processing the source tree.

```csharp
 [GenerateSerializer]
    public record RecordWithSetterMethod
    {
        string _bar;

        [Id(0)]
        public string Bar
        {
            get => _bar;
            init
            {
                _bar = value; DoMore(_bar);
            }
        }

        public RecordWithSetterMethod(string bar)
        {
            _bar = bar;
            DoMore(_bar);
        }

        void DoMore(string bar)
        {
            // do more!
        }
    }
```

**Comment by ReubenBond** [comment]
We should have an analyzer for this and error out from the code generator
