### ISSUE TITLE
How implement IRepository for getting list of grains for show in Grid?

### ISSUE THREAD

**Issue by P9avel** [dotnet/orleans#7931]
I am want to list of grains in GUI, I am need to implement IRepository and GetList method with skip and take parameters. How to get grains state without loading grain in silo?

**Comment by ElanHasson** [comment]
Hi @P9avel,

Orleans does not _yet_ support enumerating grain ids by grain type.

There are a few options all with some trade-offs.

1)  Query the data store directly, get a list of grain IDs and then get the state for the grid directly through the grain as it may be different in  memory: https://github.com/web-scheduler/web-scheduler-api/blob/main/Source/WebScheduler.Client.Core/Repositories/ScheduledTaskRepository.cs#L101-L162
2) Maintain an index, an example is here: https://github.com/OrleansContrib/Orleans.IdentityStore/tree/master/src/Orleans.IdentityStore
3) Maintain your own data structure for collecting grain instances: https://github.com/ElanHasson/Orleans.DataStructures/blob/master/samples/Examples.Client/DoublyLinkedListExamples.cs#L41
4) If your lists won't be super large, you can just have a `ListGrain` which stores a regular `List<TState>` with grain references and can use that for enumerating.

Hope this helps.

**Comment by P9avel** [comment]
Many many thx for your links. will learning
