### ISSUE TITLE
Stream is not getting re-activated after Silo restarts

### ISSUE THREAD

**Issue by kishor-raskar** [dotnet/orleans#7932]
Hi Team,
We have two services:
1. Orleans Silo host.
2. Microsoft SignalR web Application (which will be client server for Silohost).

Orleans Silo is acting as backplane for our SignalR application, when we connects some of the clients to SingalR Hub, this connections is getting registered with Silo as steam (I may not aware of underlying behavior of it).

So messages are getting delivered from one SingalR client to another and everything works fine unless silo gets restarted, after that we see server clients are getting reconnected, but actual signalr clients no longer receives any messages. We are getting following warning:
**[WRN] Consumer ObserverId:*cli/5df83a99/ad57ac09-fd68-4867-8a81-ca151af2e6fd on stream SERVERS_STREAM-cbd1b061-1708-4fde-ac99-8bbc14b3e713-ORLEANS_SIGNALR_STREAM_PROVIDER is no longer active - permanently removing Consumer.**

Can you please help me with this?
Note: I am trying this on my local machine, hence I could have only single Silo instance running in local clustering, if you could help me to set multi-silo cluster either locally or on environment it would be great help (if multi-silo avoids this kind of issues)

**Comment by benjaminpetit** [comment]
What you are experiencing is "expected". When an event is supposed to be delivered to a client no longer connected to the cluster (that's possible when your restart silos for example), Orleans will drop the subscriptions.

Two possible solutions:
- don't use external clients and use hosted client directly on silos
- have the client resubscribe to streams when it detects connection loss
