### ISSUE TITLE
Consistent 'No target activation` errors when silo is dead

### ISSUE THREAD

**Issue by benthepoet** [dotnet/orleans#7933]
We've recently encountered an issue where after deploying a new set of silos (5 total), we are consistently getting errors like these for a number of grain instances that keep failing to activate.

```
No target activation S10.1.0.19:11111:398459896*grn/Salad.Services.Users.ProfileGrain/4077d9c3-0184-4c61-a594-5ec47606d7b6@67c74992 for response message: Transient Rejection (info: Target silo is known to be dead) Response S10.1.0.243:11111:398460762*grn/Salad.Services.Referrals.RefereeGrain/4077d9c3-0184-4c61-a594-5ec47606d7b6@cb7b748a->S10.1.0.19:11111:398459896*grn/Salad.Services.Users.ProfileGrain/4077d9c3-0184-4c61-a594-5ec47606d7b6@67c74992 #22935009
```

We're using the AWS clustering provider currently. 
I've checked the membership table and the target silo that appears to be in question `10.1.0.243` is marked dead (`SiloStatus = 6`).

Any idea why this would be happening even though the target silo is dead?

**Comment by ReubenBond** [comment]
@benthepoet there was a bug in versions of Orleans prior to 3.6.5 which could land you in that situation. Which version of Orleans are you using?

**Comment by ReubenBond** [comment]
Do you have logs showing why the grains are failing to activate?

**Comment by benthepoet** [comment]
> @benthepoet there was a bug in versions of Orleans prior to 3.6.5 which could land you in that situation. Which version of Orleans are you using?

We're currently on version `3.6.2`. We'll go ahead and update our dependencies and see if that resolves the issue.

**Comment by benthepoet** [comment]
Updating to `3.6.5` took care of the issue. Thanks!
