### ISSUE TITLE
None of the assemblies added to ApplicationPartManager contain generated code

### ISSUE THREAD

**Issue by bouyeijiang** [dotnet/orleans#7939]
client = new ClientBuilder()
            .UseStaticClustering(ipandports.Select(x=>IPEndPoint.Parse(x)).ToArray())
            .Configure<ClusterOptions>(options =>
            {
                options.ClusterId = "dev";
                options.ServiceId = "dev_s";
            })
            .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(IGrainGdbQuery).Assembly))
            .Build();

catch exception:
Orleans.Runtime.OrleansConfigurationException:“None of the assemblies added to ApplicationPartManager contain generated code. Ensure that code generation has been executed for grain interface and class assemblies.”

**Comment by benjaminpetit** [comment]
Did you add the nuget package for codegen to the project containing `IGrainGdbQuery`?

**Comment by bouyeijiang** [comment]
that's it ,it's been solved
