### ISSUE TITLE
In the implementation class, connect to other servers and wait

### ISSUE THREAD

**Issue by bouyeijiang** [dotnet/orleans#7940]
example code:   

 public class GrainGdbQuery : Grain, IGrainGdbQuery
    {
        public GrainGdbQuery()
        { }
 
        public Task GdbQueryFromCluster(string version,string dataName,
            string dataType,string commandText)
        {
           var client = new ClientBuilder()
            .UseStaticClustering(ipandports.Select(x=>IPEndPoint.Parse(x)).ToArray())
            .Configure<ClusterOptions>(options =>
            {
                options.ClusterId = "dev";
                options.ServiceId = "dev_s";
            })
            .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(IGrainGdbQuery).Assembly))
            .Build();

            client.Connect(ReplayFilter).Result;// **always waiting**
        }
}

**Comment by captainsafia** [comment]
@bouyeijiang Can you share a clearer reproduction for your problem?

```chsarp
public Task GdbQueryFromCluster(string version,string dataName,
        string dataType,string commandText)
...
        client.Connect(ReplayFilter).Result;// **always waiting**
```

You're code won't compile given the above method is not returning a task as expected.

**Comment by bouyeijiang** [comment]
the picture is my idea, the client connect to silo is blocking
![aa3](https://user-images.githubusercontent.com/4083760/186800700-476f0826-a75d-49ef-a0af-818fdd5bb4a5.jpg)

**Comment by ReubenBond** [comment]
@bouyeijiang you need to use `await` within grain code, you should never use `.Result` or `.Wait()` or `Task.WaitAll`/`Task.WaitAny`

**Comment by bouyeijiang** [comment]
yeah!silo1 and silo2 is separate clusters,mybe have silo3 and so on.and every silo to do own work. Similar to multiple clusters, but the clusters work together

**Comment by ReubenBond** [comment]
Have you seen this, @bouyeijiang? https://github.com/OrleansContrib/Orleans.MultiClient

**Comment by bouyeijiang** [comment]
I tried to use this，but I couldn't satisfy it，It needs different interface names to distinguish the instantiated objects, but my interface type is the same, but I need to call different silos

**Comment by ReubenBond** [comment]
Ok, no problem. Anyway, the solution to your problems is in my first response. I hope it helps
