### ISSUE TITLE
Cannot transform data from IEnumerable between two assemblies

### ISSUE THREAD

**Issue by NikitaPozharskyi** [dotnet/orleans#7957]
Hi! I have two services and one of them take a Grain which was specified in another service. So after i take it we execute method which shold return class object with fields smth like that
```
class Person{
public string Name{get;set;}
public IEnumerable<Children> ChildrenList {get;set;}
. . .
}
```
After method execution we handle the break point in another service where we calculating that data in IEnumerable (we have local function that makes some calculations). Like this

```
public class PeopleHandler{
public async Task ExecuteAsync(personName){
var name = _context.People.First(_ => _.Name == personName);
var children = GetChildren(name);

return new Person(name, childrens)

IEnumerable GetChildren (string personName){
var children =  _context.GetChildren.Select(. . .) . . .

 return children;
 }
}
}
```

Attention. We don't use ToList() at the end. We handle it like that to another service. So we execute method 

```
public async Task GetPersonInformation (personName){
  var peopleHandler = _client.GetGrain<PeopleHandler>(grainId);
  var person = await peopleHandler.ExecuteAsync(personName);

 var childrens = person.ChildrenList.ToList() // or any other method that makes programm to calculate data 'First() etc.'
}
```

After that we got an exception about NullReferenceException in Children. We can't calculate data between services. I decided to make it ToList() before we return data from the ExecuteAsync method and i got a result but what was the reason of that? If it wasn't a local function i understand that private functions can be not visible in first assembly but this is local function and we need to know everything about public method including it's private methods inside of it. So i changed return Type of GetChildren and got my result. What do you think?

**Comment by mnmr** [comment]
When you call a method on a grain, the data (objects) get serialized into a stream of bytes. These bytes are then sent over the network to the receiving grain, where the objects are re-created. However, if you do not call ToList() before sending the data, there is no data to send (because LINQ lazy-evaluates the query).

As a general recommendation, use concrete types (i.e. List<T> instead of IList<T> or IEnumerable<T>) when passing data between grains. This avoids surprises and is more explicit than relying on the serialization logic to automagically do the right thing.

**Comment by NikitaPozharskyi** [comment]
> When you call a method on a grain, the data (objects) get serialized into a stream of bytes. These bytes are then sent over the network to the receiving grain, where the objects are re-created. However, if you do not call ToList() before sending the data, there is no data to send (because LINQ lazy-evaluates the query).
> 
> As a general recommendation, use concrete types (i.e. List instead of IList or IEnumerable) when passing data between grains. This avoids surprises and is more explicit than relying on the serialization logic to automagically do the right thing.

Thanks for your message! I thought in that way too so i resolved that pretty fast but. So I just want to be pretty sure that is working like that
