### ISSUE TITLE
codegen\ref\xxx.dll could not be found

### ISSUE THREAD

**Issue by zxyao145** [dotnet/orleans#7967]
Hi, I'm learning orleans according to https://docs.microsoft.com/zh-cn/dotnet/orleans/tutorials-and-samples/tutorial-1, but the Grains project cannot be rebuild, and an error ouput:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'OrlensDemo.GrainInterfacesLib\obj\Debug\net6.0\codegen\ref\OrlensDemo.GrainInterfacesLib.dll' could not be found	OrlensDemo.GrainsLib	D:\codeDemo2\OrlensDemo.SiloServer\OrlensDemo.GrainsLib\CSC	1	Active
```

I don't understand why it looks for DLL under `codegen\ref`, and my demo is here: https://github.com/zxyao145/OrleansDemo. Can anyone tell me where I was wrong?

**Comment by ReubenBond** [comment]
In your OrlensDemo.GrainsLib.csproj file, change this package:
``` diff
   <ItemGroup>
     <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.1" />
     <PackageReference Include="Microsoft.Orleans.Core.Abstractions" Version="3.6.5" />
-    <PackageReference Include="Microsoft.Orleans.OrleansCodeGenerator.Build" Version="3.6.5">
+    <PackageReference Include="Microsoft.Orleans.CodeGenerator.MSBuild" Version="3.6.5">
       <PrivateAssets>all</PrivateAssets>
       <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
     </PackageReference>
```

**Comment by zxyao145** [comment]
@ReubenBond 

Hi, I import the package Microsoft.Orleans.CodeGenerator.MSBuild in the `OrlensDemo.GrainInterfacesLib` project:
```xml
    <PackageReference Include="Microsoft.Orleans.CodeGenerator.MSBuild" Version="3.6.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```

 and the project `OrlensDemo.GrainsLib` refers to `OrlensDemo.GrainInterfacesLib`:

```zml
  <ItemGroup>
	  <ProjectReference Include="..\OrlensDemo.GrainInterfacesLib\OrlensDemo.GrainInterfacesLib.csproj" />
  </ItemGroup>
```

 So why does `OrlensDemo.GrainsLib` need to add this package?

**Comment by ReubenBond** [comment]
It's a development dependency (since it's a code generator) so it needs to be applied directly to projects which need to have code generated

**Comment by zxyao145** [comment]
> It's a development dependency (since it's a code generator) so it needs to be applied directly to projects which need to have code generated

OK, thanks a lot!
