### ISSUE TITLE
runtime error: Orleans.ClientBuilder.Build() is failing on 3.6.0+

### ISSUE THREAD

**Issue by johnds1974** [dotnet/orleans#7968]
Getting this exception now all of a sudden on a previously working test console app:

{"Generic implementation type 'Orleans.DefaultOptionsFormatter`1' has a DefaultConstructorConstraint ('new()' constraint), but the generic service type 'Orleans.IOptionFormatter`1' doesn't."}

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.ValidateTrimmingAnnotations(Type serviceType, Type[] serviceTypeGenericArguments, Type implementationType, Type[] implementationTypeGenericArguments)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Orleans.Hosting.ServiceProviderFactoryAdapter`1.BuildServiceProvider(HostBuilderContext context, IServiceCollection services)
   at Orleans.Hosting.ServiceProviderBuilder.BuildServiceProvider(HostBuilderContext context)
   at Orleans.ClientBuilder.Build()
   at AgentApp.Program.CreateClusterClient() in C:\DEV\MSOrleansTest\AgentApp\Program.cs:line 102
   at AgentApp.Program.<RunMainAsync>d__3.MoveNext() in C:\DEV\MSOrleansTest\AgentApp\Program.cs:line 48

.Net Core 6.0 console app:

My **CreateClusterClient** method (called from main):

        private static Task<IClusterClient> CreateClusterClient()
        {
            //logger.LogInformation($"ConnectClient()...");

            var client = new ClientBuilder()
                .UseLocalhostClustering()
               .Configure<ClusterOptions>(options =>
                {
                    options.ClusterId = "dev";
                    options.ServiceId = "OrleansBasics";
                })
                //.AddSimpleMessageStreamProvider("teststream")
                .ConfigureLogging(logging => logging.AddNLog())
                .Build();

            return Task.FromResult(client);
        }

**Comment by ReubenBond** [comment]
I have never seen this before. Are you able to create a repro project and upload it?

**Comment by Osypchuk** [comment]
Same issue...

**Comment by ReubenBond** [comment]
Same response

**Comment by Osypchuk** [comment]
Please find repro attached. 
It looks like behavior is different in different platforms. Unfortuantely, you will  need VS 2022 with MUI and Android Emulator.

Console app (`cd Repro.Console && dotnet run`) works as expected: `(Unable to connect to endpoint S127.0.0.1:30000:0) ` (server code is not included in this repro project).

Within MUI project fails although in different ways: 
- Windows application stuck in endless loop in Connect().
- Android project fails with error from initial post (Generic implementation type 'Orleans.DefaultOptionsFormatter`1' has a DefaultConstructorConstraint('new()' constraint), but the generic service type 'Orleans.IOptionFormatter`1' doesn't.)

You can find corresponding lines in source code using search for '//REPRO'
[Repro.zip](https://github.com/dotnet/orleans/files/9562337/Repro.zip)

**Comment by ReubenBond** [comment]
Thank you for the repro! I'm taking a look now.

> Unfortuantely, you will need VS 2022 with MUI and Android Emulator.

This is concerning. Is this some kind of an issue with Mono, perhaps? I'm installing MAUI to try this... it sounds like an unsupported scenario (running Orleans in a MAUI app)

**Comment by johnds1974** [comment]
@ReubenBond sorry for late response. I have not yet been able to build a proper 'case' as my dev system and codebase is always in flux. I managed to get rid of the problem by starting a new test project from scratch, and the problem has gone away.

I am trying to, step by step, add all the other bits n bobs to my new project (like other Nuget packages that my system needs) to see if there is any connection, to try reproduce this. In the meantime I hope you find something via @Osypchuk sample repo! 
:-)

**Comment by johnds1974** [comment]
Thanks @ReubenBond. I'm not using MAUI at all here. Vanilla .NET 6, Console apps, Windows 11 (dev box), test boxes are Windows 10 & Windows 8.1. Win11 and 8.1 is where this problem surfaced when my original project was on .NET 5 and I updated it to use .NET 6. No code was changed. Just that bizarre appeared out of nowhere ;-)

**Comment by Osypchuk** [comment]
@ReubenBond thanks for looking into this.
Initially, I was planning to use API/SignalR on the client side. However, one of the samples lead me to an idea to try to use Orleans on the client side directly: https://github.com/dotnet/orleans/blob/main/samples/Adventure/AdventureClient/Program.cs 

Please let me know if that's ultimately bad idea and I should not try it

**Comment by ReubenBond** [comment]
@Osypchuk yes, you should use an API/SignalR. Perhaps we need to make a note on that Adventure sample that it's not intended to be used for external clients which are outside your trust boundary.

**Comment by ReubenBond** [comment]
I'm going to close this for now as running Orleans within a MAUI app isn't supported and you have a better alternative (HTTP API or SignalR API)

**Comment by joelving** [comment]
I'll just add this for context for however might stumble on this issue.

I ran into the same issue when running Orleans in a Maui app on Android (Mono). It was easily fixed in the Orleans source (see [my fork](https://github.com/joelving/orleans/commit/3acc844471677a4a62eff4dea7e9e91ee329bc1f)), but since we're in an entirely different runtime, the troubles doesn't end there.

The next issue is being unable to activate grains. `Unable to find an IGrainReferenceActivatorProvider for grain type xxx` where `xxx` is both internal grains like "sys.svc.clustering.dev" and user-defined grains.
Usually, this happens when I haven't added the right dependencies (so code generation doesn't happen correctly?). I suspect that this is an issue of code generation (at runtime?) which fails on Mono, but at this point I'm out of my depth.

Running Orleans in a Maui app on Windows does seem to work with relatively few hacks, though.
