### ISSUE TITLE
4.0-preview2 missing IStartupTask and maybe other types as well

### ISSUE THREAD

**Issue by rjygraham** [dotnet/orleans#7974]
I'm trying to use IStartupTask in 4.0-preview2 but the type appears to be missed in the consolidation work that occurred between preview1 and preview2.

The type is available in Microsoft.Orleans.Runtime.Abstractions 4.0-preview1 but adding that package ends up adding duplicate types across Microsoft.Orleans.Runtime.Abstractions 4.0-preview1 and Microsoft.Orleans.Runtime 4.0-preview2 which makes compiler all kinds of mad. 😊

Not sure how close 4.0-preview3 is to release, but 4.0-preview2 is unusable for some scenarios due to this issue.

**Comment by ReubenBond** [comment]
It's in `Orleans.Runtime` package in the `Orleans.Runtime` namespace (which is not a great namespace for it).
The abstractions package was removed
