### ISSUE TITLE
GrainServices aren't working because DI doesn't inject IGrainIdentity

### ISSUE THREAD

**Issue by t4s-ryan** [dotnet/orleans#7978]
Hello!

We are trying to use a GrainService to hold a shared messaging service within our application, but are having difficulties getting the service to activate.  We've been following the documentation here:

https://dotnet.github.io/orleans/docs/grains/grainservices.html

What we're seeing is that when the grain is activated and its constructor called:

> public MessagingServiceGrain(IMessagingManager messagingManager, IGrainIdentity grainId, Silo silo, ILoggerFactory loggerFactory)
>  : base(grainId, silo, loggerFactory)
> {
>     _messagingManager = messagingManager;
>     _logger = loggerFactory.CreateLogger<MessagingServiceGrain>();
> }

The runtime produces the following error:

> InvalidOperationException: Unable to resolve service for type 'Orleans.Core.IGrainIdentity' while attempting to activate 'Fintercept.Grains.Services.MessagingServiceGrain'.

The IGrainIdentity is definitely required by the GrainService base class constructor:

> //     Constructor to use for grain services
>         protected GrainService(IGrainIdentity grainId, Silo silo, ILoggerFactory loggerFactory);

So, you'd think that the DI will drop this in for you as required.  As discussed in issue #3148 (https://github.com/dotnet/orleans/issues/3148), the DI doesn't do this and it is suggested that it isn't possible to set it up yourself.

How does one overcome this issue?

**Comment by t4s-ryan** [comment]
I think we've figured it out.  The issue seems to have been that we were attempting to inject _both_ the GrainServiceClient and the GrainService as singletons.  The GrainServiceClient does not have the issue where the DI lacks all proper services.  Here was the offending code:

> //services.AddSingleton<IMessagingService, MessagingServiceGrain>();  <--- This was causing the issue
> services.AddSingleton<IMessagingServiceClient, MessagingServiceClient>();

**Comment by ReubenBond** [comment]
Apologies for failing to answer your question sooner, @t4s-ryan. You're right that grain classes should not be added to DI. They are constructed using DI, but you must always access them via reference (eg created via `IGrainFactory`)
