### ISSUE TITLE
Make it possible to tune the deactivation of grains in relation to memory usage

### ISSUE THREAD

**Issue by COCPORN** [dotnet/orleans#7985]
Make it possible to tune the deactivation of grains in relation to memory usage, both for the GC-reported usage and host environment. Orleans implements `IHostEnvironmentStatistics` and `IAppEnvironmentStatistics` and these can be queried against configuration to see if deactivation of grains should be suppressed.

The implementation should have functional parity with the current implementation to make any configurable new behavior not come off as surprising.

**Comment by ReubenBond** [comment]
Closing in favor of the existing issue, #370
