### ISSUE TITLE
Multi silos on same host

### ISSUE THREAD

**Issue by pinopino** [dotnet/orleans#7993]
i`m pretty new to orleans and i use a sample called 'Advanture' to lean orleans. below are my steps:
1. first silo create using: `.siloBuilder.UseLocalhostClustering();`
2. second one create using: `.siloBuilder.UseLocalhostClustering(siloPort: 11112, gatewayPort: 30001);`
3. create client using: `.UseLocalhostClustering(new int[] { 30000, 30001 })`
4. start two silos and start client (yes, they all are on the same machine)
5. when i type a name i got response: `I don't understand`, i do believe this comes from: 
![image](https://user-images.githubusercontent.com/2641760/192480322-d34e8f89-c3af-4c07-bafb-f194187083bb.png)

when start only one silo everything gose fine. i want know whether orleans support scenario like this(multiple silos deploy on same machine)

**Comment by benjaminpetit** [comment]
We do support it, but you need to configure your second silo to use the first one as "primary" (set the parameter `primarySiloEndpoint` to point to the first silo in your call to `UseLocalhostClustering`). 

Right now, you deployed two silos that do not form a single cluster, but rather two single-silo clusters.

**Comment by pinopino** [comment]
thanks for your response. i`ll give it a try.
