### ISSUE TITLE
Allow configuration of the JsonSerializerSettings in OrleansJsonSerializer

### ISSUE THREAD

**Issue by niblak** [dotnet/orleans#8010]
As discussed on Discord with @ReubenBond, it would be beneficial to be able to configure the serializer settings for the built-in JSON serializer. Currently the only way to modify these is via reflection.

In our application, we have several types with property-level defaults that differ from the default for the data type, so `DefaultValueHandling` must be set to `Include` to correctly round-trip these objects.

**Comment by ReubenBond** [comment]
Fixed by https://github.com/dotnet/orleans/pull/8018
