### ISSUE TITLE
Grain Error - "Response did not arrive on time in 00:00:30" occurring repeatedly

### ISSUE THREAD

**Issue by ashokmandial** [dotnet/orleans#8025]
Hi,
we are facing `"An unhandled exception occurred. request System.TimeoutException: Response did not arrive on time in 00:00:30 for message: Request *cli/45517fb3@037b17aa->S10.244.1.208:30000:0*grn/Wallet.Core.Services.Grains.WalletGrain/17 InvokeMethodRequest Wallet.Core.Domain.Abstractions.Wallet.IWalletGrain:DebitPlayerAsync #3495500. Target History is: <S10.244.1.208:30000:0:*grn/Wallet.Core.Services.Grains.WalletGrain/17:>. at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task1 asyncTask) in /_/src/Orleans.Core/Async/TaskExtensions.cs:line 114"` error for specific gain (Grain Key 17) repeatedly. At the same time, other grains work just fine. To resolve this problem, we have to restart the cluster. Deleting the pod that had the issue resulted in futile efforts. However, restarting the whole cluster resolved the problem. The cluster is running inside Kubernetes.

We also have Orlean grain call filter interceptor logic that traces out all outgoing calls to customize the response. we were suspecting this might be stuck on some unhandled exception thrown from grain service but that was not the case. This interceptor also logs the errors however we are not seeing any errors on our monitoring platform.

This problem is occurring on daily basis and for the same grain. Can you please give us some ideas and suggestions on how we can troubleshoot this problem? we have also checked the dashboard but there is no information regarding this problem.

More info about the error:
``
An unhandled exception occured. request System.TimeoutException: Response did not arrive on time in 00:00:30 for message: Request *cli/90014b9b@34bbfc84->S10.244.0.183:30000:0*grn/Wallet.Core.Services.Grains.WalletGrain/17 InvokeMethodRequest Wallet.Core.Domain.Abstractions.Wallet.IWalletGrain:DebitPlayerAsync #3495368. Last known status is IsExecuting: True, IsWaiting: False, Diagnostics: [[Activation: S10.244.2.220:11111:403250839*grn/Wallet.Core.Services.Grains.WalletGrain/17-0x1AC98BC6@7f833c9a #GrainType=Wallet.Core.Services.Grains.WalletGrain Placement=RandomPlacement State=Valid NonReentrancyQueueSize=0 EnqueuedOnDispatcher=0 InFlightCount=1 NumRunning=1 IdlenessTimeSpan=00:00:30.5536408 CollectionAgeLimit=02:00:00], TaskScheduler status: WorkItemGroup:Name=[Activation: S10.244.2.220:11111:403250839*grn/Wallet.Core.Services.Grains.WalletGrain/17@7f833c9a #GrainType=Wallet.Core.Services.Grains.WalletGrain Placement=RandomPlacement State=Valid],WorkGroupStatus=Running. Currently QueuedWorkItems=1; Total Enqueued=290; Total processed=288; Quantum expirations=0;  Executing Task Id=6 Status=Running for 00:00:27.7573004.TaskRunner=ActivationTaskScheduler-1977:Queued=1; Detailed context=<[Activation: S10.244.2.220:11111:403250839*grn/Wallet.Core.Services.Grains.WalletGrain/17-0x1AC98BC6@7f833c9a #GrainType=Wallet.Core.Services.Grains.WalletGrain Placement=RandomPlacement State=Valid NonReentrancyQueueSize=0 EnqueuedOnDispatcher=0 InFlightCount=1 NumRunning=1 IdlenessTimeSpan=00:00:30.5536765 CollectionAgeLimit=02:00:00 CurrentlyExecuting=Request S10.244.0.183:11111:403250904*cli/90014b9b@34bbfc84->S10.244.2.220:11111:403250839*grn/Wallet.Core.Services.Grains.WalletGrain/17@7f833c9a InvokeMethodRequest Wallet.Core.Domain.Abstractions.Wallet.IWalletGrain:DebitPlayerAsync #3495368]>, Message Request S10.244.0.183:11111:403250904*cli/90014b9b@34bbfc84->S10.244.2.220:11111:403250839*grn/Wallet.Core.Services.Grains.WalletGrain/17@7f833c9a InvokeMethodRequest Wallet.Core.Domain.Abstractions.Wallet.IWalletGrain:DebitPlayerAsync #3495368 was has been executing for 00:00:27.7614482.]. Target History is: <S10.244.0.183:30000:0:*grn/Wallet.Core.Services.Grains.WalletGrain/17:>.
   at Orleans.Internal.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask) in /_/src/Orleans.Core/Async/TaskExtensions.cs:line 114
``

**Comment by ReubenBond** [comment]
Judging by this section of the error: `WorkGroupStatus=Running. Currently QueuedWorkItems=1; Total Enqueued=290; Total processed=288; Quantum expirations=0; Executing Task Id=6 Status=Running for 00:00:27.7573004.TaskRunner=ActivationTaskScheduler-1977:Queued=1`, I suspect that you have a blocking Task somewhere in your `DebitPlayerAsync` method which is causing a deadlock. Eg, a `task.Wait()`/`task.Result`/`Task.WaitAll`/etc. If you're not able to find the culprit on your own, please find a way to share the code and I'll help you find it (you can DM via Discord to share it directly).

**Comment by ashokmandial** [comment]
> Judging by this section of the error: `WorkGroupStatus=Running. Currently QueuedWorkItems=1; Total Enqueued=290; Total processed=288; Quantum expirations=0; Executing Task Id=6 Status=Running for 00:00:27.7573004.TaskRunner=ActivationTaskScheduler-1977:Queued=1`, I suspect that you have a blocking Task somewhere in your `DebitPlayerAsync` method which is causing a deadlock. Eg, a `task.Wait()`/`task.Result`/`Task.WaitAll`/etc. If you're not able to find the culprit on your own, please find a way to share the code and I'll help you find it (you can DM via Discord to share it directly).

Thanks for the prompt response, Reuben. We are further analyzing it based on your feedback. If we do not get a blocking routine I will try to share the code with you using Discord.

Wondering, shouldn't it recover automatically from deadlock after some time?

**Comment by ReubenBond** [comment]
It will, but the default time for it to forcibly evict a "stuck" grain is 2 hours. You can configure that via `SiloMessagingOptions.MaxRequestProcessingTime`, but I don't recommend using that as a means to try to workaround scheduling deadlocks caused by invalid code patterns (you should never block a thread waiting for a task, but especially in grain code)

**Comment by ashokmandial** [comment]
We are using async and await throughout the code not `task.Wait, Task.WaitAll etc`

**Comment by ReubenBond** [comment]
@ashokmandial are you able to reproduce this locally? It might be that some library you're calling is blocking the scheduler.
If you can reproduce this under a debugger, then you can pause the process while in VS and look at the *Debug > Parallel Stacks > Tasks* view to see what's blocking the scheduler. The *Debug > Parallel Stacks > Threads* view ought to show it, too.
![image](https://user-images.githubusercontent.com/203839/195921634-981ae537-6911-4d41-a6e2-38ebf3f58fe6.png)
![image](https://user-images.githubusercontent.com/203839/195921670-cf3f5184-bd98-4b38-b8ae-94654477498d.png)

**Comment by ashokmandial** [comment]
Hi @ReubenBond, can we start the discussion on Discord? I wanted to share some code with you so please send me an invite to discord username Ashok#9953. Also, let me know a suitable time when we can connect. Thanks a lot for your quick response on this matter. Really appreciated!

**Comment by ReubenBond** [comment]
I don't recall if we addressed this already, but I will close for now. Please open a new issue if you are still seeing this.
