### ISSUE TITLE
CodeGenerator should warn/err when trying to generate for inaccessible types

### ISSUE THREAD

**Issue by koenbeuk** [dotnet/orleans#8037]
Currently, when applying `[GenerateSerializer]` on a private class (nested within), no code gets generated as this class is then silently ignored by the code generator https://github.com/dotnet/orleans/blob/4a6ddcdb059f4f113998b4ee4fcb1879a9697900/src/Orleans.CodeGenerator/CodeGenerator.cs#L340

Instead, I propose we generate an error as the source generator is unable to fulfill the request.

This is currently happening within the orleans framework, e.g. here:
https://github.com/dotnet/orleans/blob/4a6ddcdb059f4f113998b4ee4fcb1879a9697900/src/Orleans.EventSourcing/CustomStorage/LogViewAdaptor.cs#L76

**Comment by ReubenBond** [comment]
This would be a welcome change, thanks for suggesting it, @koenbeuk

**Comment by ReubenBond** [comment]
Fixed in #8087
