### ISSUE TITLE
Question: Is Orleans 7.0.0-rc2 a real Release Candidate?

### ISSUE THREAD

**Issue by AlseinX** [dotnet/orleans#8038]
RC releases of .NET is guaranteed to make API almost stable and there is unlikely to be further breaking changes, and it could be safely based on in production.

But Orleans 4.0.0 used to stay in early previews, with even APIs moving among packages. I wonder if the so-called rc2 should be taken as a real go-to-live Release Candidate.

**Comment by ReubenBond** [comment]
We have no plans to change APIs between now and the final 7.0 release.

**Comment by ReubenBond** [comment]
Are you looking to go live before November?

**Comment by AlseinX** [comment]
No, but it looks very weird to me because there the former milestones shows that there seems to be a long way to go before reaching RC. But now it turns to be 7.0.0-rc2 just because .NET 7 is rc2, so I wonder if it is really ready to be an RC, or just for alignment of versions (maybe as a prerequisite before merging into .NET sdk?).

**Comment by ReubenBond** [comment]
Ah, I see the concern. The release was originally going to have been -rc1, but I mistyped it. Since -rc2 coincides with the current .NET RC which this RC builds against, we decided to keep it that way. Is there anything you're looking for which isn't in the release?

**Comment by koenbeuk** [comment]
@ReubenBond Documentation! as the current docs are still referring to v3 and there seems to be no migration guide yet.

**Comment by bradygaster** [comment]
> @ReubenBond Documentation! as the current docs are still referring to v3 and there seems to be no migration guide yet.

This is something we're working on currently. The first article will inform customers on how to migrate from 3.x to 7. After that we'll start updating all the samples with help from @IEvangelist and the docs team.
