### ISSUE TITLE
Hello World Sample incorrectly instructs to NOT add reference to GrainCollection from SiloHost

### ISSUE THREAD

**Issue by blackram** [dotnet/orleans#805]
HI,

I've just started with the Hello World sample after downloading the SDK 1.0.9. The tutorial for [Hello World] (http://dotnet.github.io/orleans/Step-by-step-Tutorials/My-First-Orleans-Application)  instructs

> Add a project dependency (not a project reference) on the grain collection to the host project, so that it is automatically (re-)built when starting the debugger.

but if I don't do this the silo doesn't seem to have a way to discover the grains.

I get (in Visual Studio 2013):

> An unhandled exception of type 'System.ArgumentException' occurred in Orleans.dll
>
> Additional Information: Cannot find an implementation class for grain interface: IGrain11.IGrain1. Make sure the grain assembly was correctly deployed and loaded in the silo. ...

**Comment by sergeybykov** [comment]
I fixed the doc - it now says "Add a reference for the grain collection project to the host project, so that it is automatically (re-)built and copied when starting the debugger."

**Comment by blackram** [comment]
Thankyou.

Sent from my M1 Abrams somewhere in sunny Golmud
________________________________

**Comment by dbmercer** [comment]
The phrasing of that instruction can be read opposite of intended. Perhaps should phrase as:

> Add to the host project a reference to the grain collection project…
