### ISSUE TITLE
Will Orleans 4/7 be compatible with .NET 6?

### ISSUE THREAD

**Issue by brijgogogo** [dotnet/orleans#8060]
We have been using Orleans 3.x with our .NET apps. Does the recent change in version number mean Orleans 7 will be compatible with .NET 7 and not .NET 6?

**Comment by ReubenBond** [comment]
Hi @brijgogogo, Orleans 7.0 relies on some features only available in .NET 7 and we intend to follow the versioning and dependencies of .NET and ASP.NET as Orleans continues to align with .NET & ASP.NET. It will not be compatible with .NET 6.0

We will continue releasing Orleans 3.x versions which support .NET 6.0 for the time being
