### ISSUE TITLE
OrleansCounterControl.exe

### ISSUE THREAD

**Issue by GadgetGeekUK** [dotnet/orleans#8066]
The documentation (https://learn.microsoft.com/en-us/dotnet/orleans/host/monitoring/) mentions Performance Counter monitoring, by adding the applicable packages to the Silo and Client.

However there is no details on using the Performance counter package 'Microsoft.Orleans.CounterControl'.

After adding it (assuming it is added to Silo and Client?) it still needs configuring by running 'OrleansCounterControl.exe'. I can see this  in the 'lib/net461/' folder of the Package, but it is not added to any project in the solution, so how and where is it run from?

I've tried from several places, with admin privileges, but it just says it is missing one of its dependencies.

Could you clear this up in the  'monitoring' documentation?

**Comment by benjaminpetit** [comment]
What version of Orleans are you using? We removed windows performance counter a while ago. We definitely need to update this doc page...

If you need it (meaning you are running Orleans 2.4.x or before?) You need to run manually the tool as an admin one time, to install the counter.

**Comment by GadgetGeekUK** [comment]
I'm using the latest version of Orleans, so it looks like you therefore just need to update the documentation that still refers to the performance counters!
Is there any good documentation out there for performance monitoring of Silo/Client - what are the recommended methods for monitoring?

**Comment by ReubenBond** [comment]
Fixed - docs updated
