### ISSUE TITLE
ADO.NET - BinarySerializer still uses the old serializer

### ISSUE THREAD

**Issue by mayrmax** [dotnet/orleans#8077]
As far as I see Orleans 7-rc.2 is still using the old serializer in ADO.NET. Is there a reason for that? 
We would really like to take advantage of the version tolerant serializer if possible. 

Do you see the possibility to still add this to 7.0 either as replacement for the old binary serializer or as opt in?

Another possibility would be to possibly remove all of the current variants to only support one serializer as done in the other providers (Azure/DynamoDB).

**Comment by benjaminpetit** [comment]
Implemented with #8081
