### ISSUE TITLE
Microsoft Faster  implementation in orleans

### ISSUE THREAD

**Issue by SalimiHabib** [dotnet/orleans#8078]
For trying  to replace concurrent dictionary in grain state with Microsoft Faster , we need to use  IDevice to access logs in file system .
1- does it correct way to implement Microsoft faster in orleans cluster ?
2- how cluster instances access to data in this way ?
thank you

**Comment by ReubenBond** [comment]
Hi @SalimiHabib, I'm not sure how to answer this. FASTER is an embedded data store, so you would need to be some work done to make that work well in a distributed setting.

What benefit do you hope to gain from it?

**Comment by SalimiHabib** [comment]
There is large database that need to be accessed by Orleans  , it managed by other active service and cannot be integrate in Orleans store , we don't know how Orleans performance affected by large database out of its own store ( may be by creating API to access it  from Orleans ) , also we have chance to create partitioned dataset and update data in schedule before using in Orleans.
Base on these uncertainty and opportunity we found that Orleans store more reliable than outside of it (for this case)  
and using FASTER is just about to prevent creating bottleneck( because of data size).
but as you pointed precisely to embedded data store , it is more complicated than it seems    
May be we go by API .

Thank you
