### ISSUE TITLE
[Analyzers] Show error when adding a property to a grain interface

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#8080]
This has bit a few people, for example https://github.com/dotnet/orleans/issues/8065
We should add an analyzer error for the case where a developer attempts to add a property to a grain interface.

``` C#
public interface IUserGrain : IGrain
{
  Task<int> Age { get; } // Error
  string Name { get; set; } // Error
}
```

**Comment by buzzers** [comment]
@ReubenBond 
I think the code generator should also report an error instead of a warning when it encounters a failure to generate code or an unhandled exception, so that the developer doesn't waste time by ignoring the problem.

**Comment by ReubenBond** [comment]
> @ReubenBond 
> I think the code generator should also report an error instead of a warning when it encounters a failure to generate code or an unhandled exception, so that the developer doesn't waste time by ignoring the problem.

Agreed. We have an exception which can report a diagnostic now. Perhaps we should add a general purpose Diagnostic to handle all unaccounted-for failure cases, and convert all existing explicit exceptions thrown from the codegen into diagnostics.

**Comment by buzzers** [comment]
> > @ReubenBond
> > I think the code generator should also report an error instead of a warning when it encounters a failure to generate code or an unhandled exception, so that the developer doesn't waste time by ignoring the problem.
> 
> Agreed. We have an exception which can report a diagnostic now. Perhaps we should add a general purpose Diagnostic to handle all unaccounted-for failure cases, and convert all existing explicit exceptions thrown from the codegen into diagnostics.

I think this is a good solution, and I do it in my own project's code generator.

**Comment by ReubenBond** [comment]
@buzzers I opened https://github.com/dotnet/orleans/pull/8087 to address this
