### ISSUE TITLE
Add support for Azure SDK 2.7

### ISSUE THREAD

**Issue by mbernard** [dotnet/orleans#809]
Just installed VS2015 and if you try to deploy a Cloud Service project (ccproj) and you have Azure SDK 2.5 VS simply hang during the deployment and you have to kill the whole thing. It seems to be a know issue and the current workaround seems to simply install the Azure SDK 2.7, but according to the Orleans documentation only Azure SDK 2.4 or 2.5 are supported. Any ideas when 2.7 will be supported?

**Comment by sergeybykov** [comment]
This is strange. Orleans should work just fine with Azure SDK 2.4 - 2.7 provided dependencies of OrleansAzureUtils.dll are properly redirected via app.config. Can you provide more details of what you are seeing, logs, etc.?

**Comment by mbernard** [comment]
Actually I didn't try it yet, as your documentation was saying that Orleans was only supporting SDK 2.5. I'll install the 2.7 SDK and give it a try them. I'll let you know if it works

**Comment by sergeybykov** [comment]
2.5 should also work.

**Comment by gabikliot** [comment]
@mbernard , did that work?

**Comment by mbernard** [comment]
Nop. seems like orleans is unable to load settings from the Azure config anymore
i.e
In my Azure config local I have 
```
<Setting name="DataConnectionString" value="UseDevelopmentStorage=true" />
```

Before the ClientConfiguration.DataConnectionString was automatically filled up with my Azure Config. Now it's always empty.
The comment on the ClientConfiguration.DataConnectionString still says

```
/// <summary>
    /// Specifies the connection string for the gateway provider.
    ///             If the silos are deployed on Azure (run as workers roles), DataConnectionString may be specified via RoleEnvironment.GetConfigurationSettingValue("DataConnectionString");
    ///             In such a case it is taken from there and passed to the silo automatically by the role via config.
    ///             So if the silos are run as Azure roles and this config is specified via RoleEnvironment,
    ///             this variable should not be specified in the OrleansConfiguration.xml (it will be overwritten if specified).
    ///             If the silos are deployed on the cluster and not as Azure roles,  this variable should be set in the OrleansConfiguration.xml file.
    ///             If not set at all, DevelopmentStorageAccount will be used.
    /// 
    /// </summary>
```

**Comment by sergeybykov** [comment]
@mbernard Can you try https://github.com/dotnet/orleans/tree/master/Samples/AzureWebSample to see if it works in your environment?

**Comment by sanjinharacic** [comment]
nope :(, dies on silo.start for both web sample and tictactoe(elevated), with autmatically migrated 
2.5->2.7  with the following null ref:
   at Orleans.Runtime.Host.AzureSilo.Start(ClusterConfiguration config, String deploymentId, String connectionString)
   at OrleansXO.WorkerRole.WorkerRole.OnStart() in C:\Users\orleansTestUser\Downloads\orleans-master\orleans-master\Samples\TicTacToe\OrleansXO.WorkerRole\WorkerRole.cs:line 44
   at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.InitializeRoleInternal(RoleType roleTypeEnum)
   at Microsoft.WindowsAzure.ServiceRuntime.Implementation.Loader.RoleRuntimeBridge.<InitializeRole>b__0()

hope this helps

**Comment by veikkoeeva** [comment]
I chime in with just a note if someone has more time to dedicate to this that it looks like it'd be possible to add a deployment test for this scenario. The Orleans tests already know how to start compute emulator if it exists, so that part of the work would be done.

**Comment by johnkattenhorn** [comment]
Disclaimer - we are using Orleannka on top of Orleans and there's some differences in bootstrap and config.

This works for us in both emulator and cloud service, need to ensure your running SDK 2.7.1 with up to date emulator and we also use Net 4.6 and there use a solution based on this article

https://azure.microsoft.com/en-us/documentation/articles/cloud-services-dotnet-install-dotnet/
