### ISSUE TITLE
Immutable - how to find which instances are cloned

### ISSUE THREAD

**Issue by cerkoid** [dotnet/orleans#8099]
How to find which method parameters or return values are cloned when invoking grain method? It's hard to find which types should have Immutable attribute or when to wrap return values intu Immutable instance...

Regards.

**Comment by cerkoid** [comment]
I am still on 3.xx branch :) @ReubenBond thanks for response. I really admire the work you are doing with Orleans. It's a wonderful project.

My question should be more concrete

Imagine a system that can receive commands and queries. Command definition is immutable record type for instance CreatePersonCommand, that gets routed to a Grain responsible for handling this type of command. So for instance PeopleManagerGrain would have a method like
public Task<CommandResult>CreatePerson(CreatePersonCommand command).
Because record types are by design immutable I should ensure, that orleans does not make a copy of command, as it by design is not necessary. I mark such type as [Immutable] and also CommandResult is by design immutable so I mark such class as [Immutable]. As I understand, Orleans does not make a copy of such instance of type marked as immutable?

Simularly for queries. Like QueryAllPeople with signature like
public Task<Person[]>QueryAllPeople()
Since Person type is marked as [Immutable] is Person[] copied? If so, what signature could one use to ensure orleans does not copy result since it makes no sense? IEnumerable<Person> or ImmutableArray<Person>? It is a bit redundant to wrap result in Immutable<Person[]> type... Or should we create PersonArray type and mark it as [Immutable]

So it would be nice to see what orleans does and does not copy to reduce memory pressure on GC...

**Comment by ReubenBond** [comment]
> Because record types are by design immutable

This is a common misconception; record types are not immutable by-design. If a record type contains an array, the values in the array can be mutated, for example. In .NET, a type is only immutable if all of its properties are themselves immutable, which is frequently not true for record types. So, for Orleans, types are immutable if you tell Orleans to treat them as immutable. See the docs here: https://learn.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/serialization-immutability
