### ISSUE TITLE
HelloWorld sample throwing 'Cannot find generated factory type ..'  during runtime at GetGrain call

### ISSUE THREAD

**Issue by pankajksingh** [dotnet/orleans#810]
I am getting error running HelloWorld sample. 

machine : windows 10
orleans version : 1.0.9

This is what I did:
1. I downloaded the samples using git clone.
2.  I tried to get HelloWorld sample working. Here are the steps:
a. I opened the HelloWorld solution in Visual Studio. All the Orleans references were broken and nuget did not fix that. I manually fixed references using command. 
For e.g. Install-Package Microsoft.Orleans.Server
b. I built the solution and that failed for not finding the codegen file under Property directory.
c. I deleted codegen.cs files and rebuilt the solution. Build succeeded but codegen.cs is not present any more.
d. Running the test fails 

Any idea on how to investigate or fix this? Sharing the trace:

*********************************************************************************************************
Test Name:	SayHelloTest
Test FullName:	Tests.HelloWorldSiloTests.SayHelloTest
Test Source:	c:\tree\src\orleans\Samples\HelloWorld\Tests\HelloWorldSiloTests.cs : line 71
Test Outcome:	Failed
Test Duration:	0:00:04.0993686

Result Message:	
Test method Tests.HelloWorldSiloTests.SayHelloTest threw exception: 
System.InvalidOperationException: Cannot find generated factory type for interface 'HelloWorldInterfaces.IHello'
Result StackTrace:	
at Orleans.GrainFactory.MakeFactoryDelegate(Type interfaceType, String methodName, Type delegateType)
   at Orleans.GrainFactory.MakeCaster(Type interfaceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Orleans.GrainFactory.Cast[TGrainInterface](IAddressable grain)
   at Orleans.GrainFactory.GetGrain[TGrainInterface](Int64 primaryKey, String grainClassNamePrefix)
   at Tests.HelloWorldSiloTests.<SayHelloTest>d__0.MoveNext() in c:\tree\src\orleans\Samples\HelloWorld\Tests\HelloWorldSiloTests.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
***************************************************************************************************

**Comment by gabikliot** [comment]
@pankajksingh , I just tested HelloWorld  sample on my windows 10 machine and it builds just fine, out of the box. I wonder if in your visual studio you have nuget restore somehow messed up (based on you saying "All the Orleans references were broken and nuget did not fix that").
Can you please double check in your nuget manager settings that "allow nuget to download missing packages" and "automaticity check for missing packages during build" are both set.

**Comment by pankajksingh** [comment]
I was able to download and run the HelloWorld on a different box but it seems that Nuget is messed up on the box where I am still facing issues. I checked that the settings are right for Nuget Package Manager but  somehow these are not getting honored while running the code(see the error message). 

Given that even Orleans is getting downloaded as part of Nuget, it seems to me that the msi installation is not needed. Is that right?

Sharing error snippet :
***********************************************************************************************************
Error	1	This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Orleans.Templates.Interfaces.1.0.9\build\Microsoft.Orleans.Templates.Interfaces.props.	C:\tree\src\orleans\Samples\HelloWorld\HelloWorldInterfaces\HelloWorldInterfaces.csproj	60	5	HelloWorldInterfaces

**Comment by gabikliot** [comment]
Yes, msi is not needed anymore at all. In fact, we have just released 1.0.10 and removed msi from it completely. https://github.com/dotnet/orleans/releases/tag/v1.0.10

**Comment by gabikliot** [comment]
So it worked ok for you on the different box? Good!

**Comment by pankajksingh** [comment]
I fixed the issue. It was due to a config file that Nuget was reading to locate the server. It was unable to do that but the error message led me astray.

**Comment by gabikliot** [comment]
:+1:
