### ISSUE TITLE
Warning CS8785 Generator 'OrleansSerializationSourceGenerator' failed to generate source.

### ISSUE THREAD

**Issue by RbsTechOnline** [dotnet/orleans#8112]
I have a huge project in Orleans, the upgrade from preview 2 to 7 has been fairly smooth. Great work

However, I am getting

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	CS8785	Generator 'OrleansSerializationSourceGenerator' failed to generate source. 
It will not contribute to the output and compilation errors may occur as a result. 
Exception was of type 'InvalidOperationException' with message 'Cannot find type with metadata name System.Buffers.IBufferWriter`1'

threw the following exception:
'{0}'.


```

I am not sure what is causing this, or even how to investigate it. Any tips on how I can investigate this issue?

**Comment by RbsTechOnline** [comment]
A bit more information 

**Project structure** 

```
Aspnetcore
    ┕ Grains  (Grain implementations)
          ┕ Grain Abstractions (Grain interfaces)
          ┕ Grain States 
```     
**Project references**
   
Aspnetcore  - no Orleans references 

**Grains**  

```
<PackageReference Include="Microsoft.Orleans.Hosting.Kubernetes" Version="7.0.0" />
<PackageReference Include="Microsoft.Orleans.Sdk" Version="7.0.0" />
<PackageReference Include="Microsoft.Orleans.Streaming.EventHubs" Version="7.0.0" />
```

**Grain Abstractions**

```
<PackageReference Include="Microsoft.Orleans.Core.Abstractions" Version="7.0.0" />
<PackageReference Include="Microsoft.Orleans.Sdk" Version="7.0.0" />
```

**Grain States**

```
<PackageReference Include="Microsoft.Orleans.Core.Abstractions" Version="7.0.0" />
<PackageReference Include="Microsoft.Orleans.Sdk" Version="7.0.0" />
```

trying to reduce the degrees of freedom more, I remove everything except the health check, and placed the interface and implementation in the same project (Grains)

```
Aspnetcore
    ┕ Grains  (Grain implementations)
```

```
[StatelessWorker(1)]
public class HealthCheckGrain : Grain, IHealthCheckGrain
{
    public Task PingAsync()
    {
        return Task.CompletedTask;
    }
}
public interface IHealthCheckGrain : IGrainWithGuidKey
{
    public Task PingAsync();
}
```

I use the following boiler plating

```
[assembly: GenerateCodeForDeclaringAssembly(typeof(HealthCheckGrain))]

...

        builder.Host.UseOrleans((_, siloBuilder) =>
        {
            if (builder.Environment.IsDevelopment())
                siloBuilder.UseLocalhostClustering();
            else
                siloBuilder.UseKubernetesHosting();

            siloBuilder.AddTraceFilter(exclude: new[] { "Orleans" });

            siloBuilder.Configure<GrainCollectionOptions>(options =>
            {
                options.CollectionAge = TimeSpan.FromHours(1);
                options.SetGrainCollectionAgeFromAttributes();
            });

            siloBuilder.Configure<KubernetesHostingOptions>(options =>
            {
                options.GetClientConfiguration = () =>
                {
                    var config = KubernetesClientConfiguration.InClusterConfig();
                    config.Namespace = builder.Environment.EnvironmentName.ToLower();
                    return config;
                };
            });

            siloBuilder.Configure<ClusterMembershipOptions>(opt => opt.DefunctSiloExpiration = TimeSpan.FromMinutes(5));
            siloBuilder.Configure<CosmosCheckPointOptions>(opt => opt.StorageSettings.Database = builder.Environment.EnvironmentName.FirstCharToUpper());

            siloBuilder.UseCosmosDbMembership(builder.Environment);

            siloBuilder.AddContainers(builder);


            //siloBuilder.ConfigureEventHub("Default", builder.Environment, builder.Configuration, tokenCredential);
        });
        return builder;
```

Note i have been trying not to make an isolated repro :(, but unless you can see something obvious, i might try and reduce degrees of freedom more, i am sure i have done something stupid somewhere

**Comment by ReubenBond** [comment]
What happens if you add Microsoft.Orleans.Sdk to the AspNetCore project? All projects are supposed to have it. Still, it's odd that you don't have access to IBufferWriter<T>. Are you defining things in the System namespace in your projects?

**Comment by RbsTechOnline** [comment]
@ReubenBond 

> Are you defining things in the System namespace in your projects?

Now that would be story to tell the interns. But no, :)

Also added `Microsoft.Orleans.Sdk` to the main project, no cigar. 

Note, this is a super large solution there are 200 projects (dont ask) :P its obvious something else is causing the issue. ill just  start from first principles dial back everything slowly until it breaks. 

Ill let you know if i find an obvious cause, or a trap for young players

**Comment by ReubenBond** [comment]
Thanks for investigating. If you remain stuck after some time, let's set up a call to investigate, if you're available.

**Comment by RbsTechOnline** [comment]
@ReubenBond thanks cheers

**Comment by RbsTechOnline** [comment]
@ReubenBond

OK, results are in. this was an absolute nightmare to isolate and debug, I have sooo much code, so many grains, so many Orleans plugins, and generally have made some really bad life choices in regards to becoming a programmer :((( 

However, as it turns out, yeah it was me and a dependency i had taken. BUT WAIT there's more. The following behavior turned up between Preview 2, and 7.0.0 (maybe something there)

Consider the following convoluted example

Aspnetcore

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

    <ItemGroup>
	    <PackageReference Include="Microsoft.Orleans.Runtime" Version="7.0.0" />
	    <PackageReference Include="Microsoft.Orleans.SDK" Version="7.0.0" />
	    <PackageReference Include="IronPdf" Version="2022.11.10347" />
    </ItemGroup>

</Project>

```

Code

```

using Microsoft.Extensions.Diagnostics.HealthChecks;
using Orleans.Concurrency;

var builder = WebApplication.CreateBuilder(args);

builder.Services
    .AddHealthChecks()
    .AddCheck<GrainHealthCheck>("GrainHealthCheck");

builder.Host.UseOrleans((_, siloBuilder) => siloBuilder.UseLocalhostClustering());

var app = builder.Build();

app.MapHealthChecks("/health");

app.UseRouting();

app.Run();


public class GrainHealthCheck : IHealthCheck
{
    private readonly IClusterClient _client;

    public GrainHealthCheck(IClusterClient client) => _client = client;

    public async Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken = default)
    {
        try
        {
            var grain = _client.GetGrain<IHealthTestGrain>(Guid.Empty);
            var task = grain.PingAsync();
            return await Task.WhenAny(task, Task.Delay(1000, cancellationToken)) == task 
                ? HealthCheckResult.Healthy() 
                : HealthCheckResult.Degraded();
        }
        catch (Exception error)
        {
            return HealthCheckResult.Unhealthy("Failed to ping the local health check grain.", error);
        }
    }
}

[StatelessWorker(1)]
public class HealthTestGrain : Grain, IHealthTestGrain
{
    public Task PingAsync() => Task.CompletedTask;
    public Task<SomeClass> Test(SomeClass someclass) => Task.FromResult(new SomeClass());
}

public interface IHealthTestGrain : IGrainWithGuidKey
{
    public Task PingAsync();
    public Task<SomeClass> Test(SomeClass someclass);
}

[GenerateSerializer]
public class SomeClass
{
    [Id(0)] public string? Bob { get; set; }
}
```

if you add and remove the Package reference `<PackageReference Include="IronPdf" Version="2022.11.10347" />` and force a rebuild so the codegen reruns. you will get this little gem

```
Warning	CS8785	Generator 'OrleansSerializationSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Cannot find type with metadata name System.Buffers.IBufferWriter`1'	
Generator threw the following exception:
'{0}'.
```
Which, "**_warns_**" you (maybe it should be an error), you just broke the build, and aint nothing gunna work as it should. 
 
Additionally, if you hit the health check endpoint (in this case `/health`)

```
System.ArgumentException: Could not find an implementation for interface IHealthTestGrain
   at Orleans.GrainInterfaceTypeToGrainTypeResolver.GetGrainType(GrainInterfaceType interfaceType) in /_/src/Orleans.Core/Core/GrainInterfaceTypeToGrainTypeResolver.cs:line 149
   at Orleans.GrainFactory.GetGrain(Type interfaceType, IdSpan grainKey, String grainClassNamePrefix) in /_/src/Orleans.Core/Core/GrainFactory.cs:line 214
   at Orleans.GrainFactory.GetGrain[TGrainInterface](Guid primaryKey, String grainClassNamePrefix) in /_/src/Orleans.Core/Core/GrainFactory.cs:line 45
   at Orleans.Runtime.InternalClusterClient.GetGrain[TGrainInterface](Guid primaryKey, String grainClassNamePrefix) in /_/src/Orleans.Runtime/Core/InternalClusterClient.cs:line 33
   at GrainHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken) in D:\Development\repos\MyStrac\MyStrac.Portals\WebApi\Program.cs:line 32
```

However, the main story is, adding IronPdf breaks the code gen for whatever reason, even in release. Also, this seemingly has only popped up post Preview 2. 

Though I am not going to go as far as class this as a bug with Orleans, mainly because. 

1. There are 3rd party library involved
2. PDF libraries (in general) are 7 levels of stupidity written by the willywonker factory, wrapped in leaky security vulnerable nugets. looking at you **wkhtmltopdf**. 
3. And who knows this might be my environment, or any number of other issues. 

It would be nice if someone could verify these results for me. 

Until then, pdf generation is getting pushed to a service bus in its own pod where it can crash and tear down what ever it likes.

**Comment by ReubenBond** [comment]
Thanks for creating a repro. It seems that IronPdf is causing there to be multiple instances of `IBufferWriter`1` in the compilation context. One is defined in *IronPdf.dll* itself?! It's an 18MB assembly. I wonder if they ILMerged all of the dependencies (Newtonsoft.Json, BouncyCastle, mscorlib/System.Private.dll, etc), into one assembly.
![image](https://user-images.githubusercontent.com/203839/201243819-53de80ce-8aa7-4726-8b93-363ccaa283f7.png)

**Comment by RbsTechOnline** [comment]
@ReubenBond yeah, it wouldnt surprise me, if it was any other library, I would be more included to worry, however this is likely an edge case for the average user, the libraries are always problematic, and to be honest html to pdf generation and thumbnailing has no place being in a grain and just service bussed and Keda scaled on its own node, I can always just stream back any metadata I need. 

The only thing I wonder is if `failed to generate source` warnings should be promoted to errors... if that is even possible.
