### ISSUE TITLE
Orleans 3 -> 7: codec exception on System.Collection.ObjectModel.Collection<T>

### ISSUE THREAD

**Issue by seniorquico** [dotnet/orleans#8123]
Working through a project upgrade, and hit a small issue with a model using `System.Collection.ObjectModel.Collection<string>`. I swapped it out for `System.Collections.Generic.List<string>`, and the exception went away. I assume this means `Collection<T>` isn't yet supported by the new serializer? If that's the case, it would be awesome to support it or document it as an explicitly unsupported scenario.

I know very little about the new serializer... As a follow-up, it would be awesome if there were a documentation page identifying which built-in types are supported or which aren't. If there's an easy way to define this, I'd be happy to try to contribute such a page to the docs project.

**Comment by ReubenBond** [comment]
Fixed by #8238. Thank you for reporting and apologies for the delayed response here.
