### ISSUE TITLE
Orleans 4.0-p2 to 7.0 upgrade with records and Serializer with .NET 7.0 has wire difference

### ISSUE THREAD

**Issue by shacal** [dotnet/orleans#8124]
Hi!

If you are using Orleans Serializer with records, you will have deserialization issue.
We investigated with @ReubenBond and found that .NET 7.0 records make different output.

As an workaround, inherit your records from empty class.

```
[GenerateSerializer, Immutable]
public record StateBase { }

[GenerateSerializer, Immutable]
public sealed record MyState : StateBase { ... }
```

**Comment by ReubenBond** [comment]
The relevant change was introduced by this PR: https://github.com/dotnet/orleans/pull/7958
It does make version tolerance for records more fragile. Eg, adding a primary constructor to this type would break without alos changing the `[GenerateSerializer]` to `[GenerateSerializer()]`

Original:
```csharp
[GenerateSerializer]
public record Person
{
    [Id(0)]
    public string FavouriteColor { get; init; }

    [Id(1)]
    public string StarSign { get; init; }
}
```

Breaks version tolerance (1):
```csharp
[GenerateSerializer]
public record Person(int Age)
{
    [Id(0)]
    public string FavouriteColor { get; init; }

    [Id(1)]
    public string StarSign { get; init; }
}
```

Breaks version tolerance (2):
```csharp
[GenerateSerializer]
public record Person([property: Id(2)] int Age)
{
    [Id(0)]
    public string FavouriteColor { get; init; }

    [Id(1)]
    public string StarSign { get; init; }
}
```

Does not break version tolerance:
```csharp
[GenerateSerializer(IncludePrimaryConstructorParameters = false)]
public record Person([property: Id(2)] int Age)
{
    [Id(0)]
    public string FavouriteColor { get; init; }

    [Id(1)]
    public string StarSign { get; init; }
}
```
