### ISSUE TITLE
#Question: How to add multiple IClusterClient in Orleans 7

### ISSUE THREAD

**Issue by doctorcode-org** [dotnet/orleans#8145]
In previous versions, we can configure multiple IClusterClient to connect different silos. 
Is there any way to do this in Orleans 7?

**Comment by ReubenBond** [comment]
@doctorcode-org that was not a supported scenario beforehand and it is not a supported scenario now. *However*, it should be easier to implement now than it was before.

The easiest way to do it is to create `HostBuilder` for each (it takes the place of `ClientBuilder` from previous versions) and configure it with a client using `UseOrleansClient(...)`.

You can create a client without an `IHostBuilder`, too, but it is much more manual, so I don't recommend it:

``` C#
var serviceCollection = new ServiceCollection();
serviceCollection.AddOrleansClient(clientBuilder => { });
var services = serviceCollection.BuildServiceProvider();
var hostedServices = services.GetRequiredService<IEnumerable<IHostedService>>();
foreach (var hostedService in hostedServices)
{
    await hostedService.StartAsync(cancellationToken);
}

// Get the client
var client = services.GetRequiredService<IClusterClient>();

// ...use the client...

// Eventually, when your application is shutting down, you'll want to stop the client.
foreach (var hostedService in hostedServices.Reverse())
{
    await hostedService.StopAsync(cancellationToken);
}

await services.DisposeAsync();
```

There is the *Orleans.MultiClient* project which could be updated to support Orleans 7.0: https://github.com/OrleansContrib/Orleans.MultiClient

**Comment by doctorcode-org** [comment]
@ReubenBond Thank you very much, I was using an approach similar to Orleans.MultiClient and migrates it to Orleans 7 like you suggested approach, but I thought there was a better way.
I can put my project in the Orleans samples repository.
