### ISSUE TITLE
Cannot register grain activations using the Azure table-based directory

### ISSUE THREAD

**Issue by NSTA2** [dotnet/orleans#8148]
Porting a project to Orleans 7 caused an issue for me: 

A grain which has both transactional state and uses a persisted grain directory to ensure only one instance of the grain will ever exist causes this error (which was not the case using 3.6.5)

```
        Orleans.Runtime.OrleansMessageRejectionException: 
        'Forwarding failed: tried to forward message Request [S127.0.0.1:11111:27517279 sys.client/hosted-127.0.0.1:11111@27517279]->[S127.0.0.1:11111:27517279 transactiongrainwithdirectory/B]
        GrainDirectoryWithTransactionIssueReproduction.ITransactionGrainWithDirectoryGrainDirectoryWithTransactionIssueReproduction.ITransactionGrainWithDirectory.SayHi() 
        #28[ForwardCount=2] for 2 times after "Failed to register activation in grain directory." to invalid activation. Rejecting now. '
```

Removing the `GrainDirectory` attribute on the affected grain resolved the issue for me.

[Here](https://github.com/NSTA2/GrainDirectoryWithTransactionIssueReproduction) is a reproduction of the issue

**Comment by benjaminpetit** [comment]
It seems that the Azure table-based directory is broken in 7.0

**Comment by NSTA2** [comment]
Ah, so nothing to do with transactions? (should I correct the title?)

**Comment by benjaminpetit** [comment]
Done :) Thanks for catching the issue!
