### ISSUE TITLE
UnsupportedWireTypeException with memory grain storage

### ISSUE THREAD

**Issue by tanordheim** [dotnet/orleans#8152]
I've encountered an issue in Orleans 7 where if working locally on a heterogeneous silo setup in what is agreeably a less than optimal way of doing things, I encounter the following exception when activating grains that use `IPersistentState<T>` where `<T>` is a type defined within the silo that has a base type defined in another assembly:

```
Unhandled exception. Orleans.Runtime.OrleansException: Error from storage provider MemoryGrainStorage.state during ReadState for grain Type=state Id=test Error=

Exc level 0: Orleans.Serialization.UnsupportedWireTypeException: A WireType value of Reference is expected by this codec. [TagDelimited, IdDelta:0, SchemaType:Encoded, RuntimeType:]
   at Orleans.Serialization.WireProtocol.Field.UnsupportedWireType(WireType expectedType) in /_/src/Orleans.Serialization/WireProtocol/Field.cs:line 245
   at Orleans.Serialization.Codecs.VoidCodec.ReadValue[TInput](Reader`1& reader, Field field) in /_/src/Orleans.Serialization/Codecs/VoidCodec.cs:line 26
```

The setup here is:

- Each silo is its own solution.
- One solution contains a class library of some shared components that is used as `<ProjectReference />` between each silo project - and also crossing the solution boundary for one of the silos.

I've added a showcase of this in https://github.com/tanordheim/OrleansSerializationErrorDemo with a README that outlines how to reproduce the issue. My assumption is that this causes a recompilation and thus codegen is rerun for the shared class library when the second silo starts - causing some issues.

It might be that this is not intended to be supported, in that case feel free to close this issue.

**Comment by ReubenBond** [comment]
In your samples, you have your packaging wrong: your silos should be pulling in `Microsoft.Orleans.Server`

**Comment by tanordheim** [comment]
Right, I was pulling in the entire SDK for convenience but that's maybe bad; I'll retry with some cleaned up dependencies later tonight :)

**Comment by ReubenBond** [comment]
Pulling in the `Microsoft.Orleans.Sdk` package in your `Abstractions` project is the right approach. In your silos, you should be pulling in `Microsoft.Orleans.Server`.

**Comment by tanordheim** [comment]
I've updated the demo project now; abstraction packages depend on `.Sdk`, silo services depend on abstraction packages + `.Server`. The same still occurs, which I guess was expected however.

If you suspect this is a bug, and want to point me in the right direction, I can try and take a look at this tomorrow morning.

**Comment by ReubenBond** [comment]
I took a look (apologies for the long delay). So, you have a model type on Silo2 which the other silo does not have, and then you're sending that across the wire to Silo1. That is indeed not supported. In this case, though, there are at least two things which we could improve:

1. The error message which you get when this blows up
2. In-memory persistence should not need the concrete type - we should make those interfaces take opaque, serialized data and have the remote end deserialize the information into the desired type, like a typical database would
