### ISSUE TITLE
Microsoft.Orleans.CodeGenerator.MSBuild Microsoft.Orleans.OrleansTelemetryConsumers.Counters

### ISSUE THREAD

**Issue by a645010545** [dotnet/orleans#8174]
Microsoft.Orleans.CodeGenerator.MSBuild and Microsoft.Orleans.OrleansTelemetryConsumers.Counters vesion is 3.6.5
then orleans is 7.0.0
An error occurred while compiling

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB3073	命令“"dotnet" "C:\Users\Administrator\.nuget\packages\microsoft.orleans.codegenerator.msbuild\3.6.5\build\..\tasks\Orleans.CodeGenerator.MSBuild.dll" SourceToSource "\obj\Debug\net7.0\IMS.HostService.orleans.g.args.txt"”已退出，代码为 3。	Application.HostService	C:\Users\Administrator\.nuget\packages\microsoft.orleans.codegenerator.msbuild\3.6.5\build\Microsoft.Orleans.CodeGenerator.MSBuild.targets	123

**Comment by ReubenBond** [comment]
I don't understand the versions, what do you mean "3.6.5 then Orleans is 7.0.0"?
Orleans 7.0.0 must be used with other 7.0.0 packages, not 3.x packages. Please read https://learn.microsoft.com/en-us/dotnet/orleans/whats-new-in-orleans

**Comment by a645010545** [comment]
> I don't understand the versions, what do you mean "3.6.5 then Orleans is 7.0.0"? Orleans 7.0.0 must be used with other 7.0.0 packages, not 3.x packages. Please read https://learn.microsoft.com/en-us/dotnet/orleans/whats-new-in-orleans

yep.but Microsoft.Orleans.CodeGenerator.MSBuild and Microsoft.Orleans.OrleansTelemetryConsumers.Counters is not update.so just need remove Microsoft.Orleans.CodeGenerator.MSBuild and Microsoft.Orleans.OrleansTelemetryConsumers.Counters?

**Comment by ReubenBond** [comment]
Yes, remove them

**Comment by a645010545** [comment]
> I don't understand the versions, what do you mean "3.6.5 then Orleans is 7.0.0"? Orleans 7.0.0 must be used with other 7.0.0 packages, not 3.x packages. Please read https://learn.microsoft.com/en-us/dotnet/orleans/whats-new-in-orleans

when orleans is 7.0.0
the IClusterClient.IsInitialized is remove.
how to judge IClusterClient IsInitialized

**Comment by a645010545** [comment]
> Yes, remove them

ok.i try
