### ISSUE TITLE
GetStreamProvider not found

### ISSUE THREAD

**Issue by SalimiHabib** [dotnet/orleans#8175]
`GetStreamProvider  `not found after upgrading to 7.0 
also `ImplicitStreamSubscription  ` , `IAsyncStream ` and .. not found 
namespace exist but method and attribute not exist 

my package is 

```
<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="7.0.0" />
<PackageReference Include="Microsoft.Orleans.CodeGenerator.MSBuild" Version="3.6.5">
	<PrivateAssets>all</PrivateAssets>
	<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
<PackageReference Include="Microsoft.Orleans.Core.Abstractions" Version="7.0.0" />
<PackageReference Include="Microsoft.Orleans.Runtime.Abstractions" Version="3.6.5" />
```
 

thank you

**Comment by benjaminpetit** [comment]
You need to install the package `Microsoft.Orleans.Streaming`.

`Microsoft.Orleans.CodeGenerator.MSBuild` is no longer published, you should add `Microsoft.Orleans.CodeGenerator.MSBuild`. `Microsoft.Orleans.Runtime.Abstractions` was also removed.

Relevant documentation to migrate to 7.0: https://learn.microsoft.com/en-us/dotnet/orleans/whats-new-in-orleans

**Comment by SalimiHabib** [comment]
thank you
