### ISSUE TITLE
Orleans7 generates serialization for pure getter?

### ISSUE THREAD

**Issue by d-lebedev** [dotnet/orleans#8179]
After moving to Orleans 7 serialization/deserialization duplicate items in List<> members with 'alias' getter.

Example: 
```
[GenerateSerializer]
public class SomeGrainState {
    [Id(0)] public List<string> Items { get; set; } = new ();
    public List<string> ItemsAlias => Items;
}

public class SomeGrain : Grain, ISomeGrain {
    private readonly IPersistentState<SomeGrainState> _state;

    public SomeGrain([PersistentState("some", "some_storage")]IPersistentState<SomeGrainState> state)
    {
         _state = state;
    }

    public Task<List<string>> GetItems()
    {
        return Task.FromResult(_state.State.Items);
    }
    public Task AddItem(string item) 
    {
        _state.State.Items.Add(item);
        return _state.WriteStateAsync();
    }

    public Task Deactivate()
    {
        this.DeactivateOnIdle();
        return Task.CompletedTask;
    }
    ...
}
```

1. Call AddItem("item1")
2. GetItems() returns { "item1" }
3. Call Deactivate()
4. GetItems() returns { "item1", "item1" }
5. Call AddItem("item2")
6. GetItems() returns  { "item1", "item1" , "item2" }
7. Call Deactivate()
8. GetItems() returns  { "item1", "item1" , "item2", "item1", "item1" , "item2" }

Reproduced with DymanoDb storage.

**Comment by MarkusGeigerDev** [comment]
Sounds like this happens when deserializing from storage. Are you using Json as your storage format? 
Is maybe the list serialized twice and then on deserialization, the two lists are appended to the same backing field?
If yes, add a JsonIgnore attribute to either one of the properties.

**Comment by ReubenBond** [comment]
I think you're right, @MarkusGeigerDev, and thank you for responding. If Orleans.Serialization does this, I would be very surprised.

**Comment by ReubenBond** [comment]
We decided that JSON is the safest default, especially since people are very familiar with it, so we chose that for persistence.

**Comment by d-lebedev** [comment]
@ReubenBond  Thank you!
I figured out how to configure OrleansGrainStorageSerializer via DI.
Now I'm looking for how to use GrainStorageSerializer to migrate already serialized data from json to a binary representation on a production server.
