### ISSUE TITLE
Could not find an implementation for  grain interface 

### ISSUE THREAD

**Issue by 99565475** [dotnet/orleans#8180]
// Configure the host
using var host = Host.CreateDefaultBuilder()
    .UseOrleans(siloBuilder=>
    {
        siloBuilder.UseLocalhostClustering();
    })
    .Build();
// Start the host
await host.StartAsync();
Console.WriteLine("Map file name is '{0}'.", mapFileName);
Console.WriteLine("Setting up Adventure, please wait ...");
// Initialize the game world
var client = host.Services.GetRequiredService<IGrainFactory>();
var adventure = new AdventureGame(client);
await adventure.Configure(mapFileName);

An example of upgrading from 3.x to 7.0 in 3.x,Could not find an implementation for interface  in Orleans7.0，Cancel ConfigureApplicationParts in 7.0 

How  can i do it to solve the problem.

Thanks!

**Comment by xiangzLL** [comment]
How did you solve this problem?

**Comment by ReubenBond** [comment]
Make sure *every* project has Microsoft.Orleans.Sdk installed. Including silo and client.

**Comment by xiangzLL** [comment]
I try to run the Adventure demo that downloaded from Github, but it also report **Could not find the implemenation for interface XXX** exception?

**Comment by xiangzLL** [comment]
this problem is fixed by upgrade Visual Studio 2022 to the latest version.
