### ISSUE TITLE
Orleans.Runtime.GrainDirectory.ClientDirectory[0]

### ISSUE THREAD

**Issue by 99565475** [dotnet/orleans#8181]
I found a problem .

the status value  is 3  in orleansmembershiptable table when  _host.StartAsync(); 
 
Orleans.Runtime.GrainDirectory.ClientDirectory[0]
      Exception publishing client routing table to silo S192.168.2.28:3015:28186857
      Orleans.Runtime.SiloUnavailableException: The target silo became unavailable for message: Request [S192.168.2.28:3015:28186993 sys.svc.dir.client/192.168.2.28:3015@28186993]->[S192.168.2.28:3015:28186857 sys.svc.dir.client/192.168.2.28:3015@28186857] Orleans.Runtime.GrainDirectory.IRemoteClientDirectoryOrleans.Runtime.GrainDirectory.IRemoteClientD
![Bug](https://user-images.githubusercontent.com/51226466/203480660-b125ca8f-6438-4de1-a3aa-d15f9fe14e5e.png)
irectory.OnUpdateClientRoutes(System.Collections.Immutable.ImmutableDictionary`2[Orleans.Runtime.SiloAddress,System.ValueTuple`2[System.Collections.Immutable.ImmutableHashSet`1[Orleans.Runtime.GrainId],System.Int64]]) #3. See https://aka.ms/orleans-troubleshooting for troubleshooting help.

**Comment by bxjg1987** [comment]
I have the same problem

**Comment by bxjg1987** [comment]
I have the same problem，you can try 
Change to 6 manually
Please stop silo normally in the future, such as ctrl+c
