### ISSUE TITLE
Orleans serializer source generator doesn't support "required" keyword of C# 11

### ISSUE THREAD

**Issue by christallire** [dotnet/orleans#8182]
Hey guys, as issue title says source generator doesn't support 'required' keyword which I like :)

repro:
```
[GenerateSerializer]
public class Test
{
    [Id(0)] public required long TestNumber { get; set; }
}

```

It doesn't matter class or record, auto property or `get; init;`, just not works.

Compiler error:
`
1> D:\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\Grains.orleans.g.cs(34751,73,34751,113): error CS9035: Required member 'Test.TestNumber' must be set in the object initializer or attribute constructor.
`

**Comment by zh6335901** [comment]
I had the same problem with it

**Comment by orionstudt** [comment]
We are also running into this and looking for an update.

**Comment by ReubenBond** [comment]
This ought to be have been fixed in https://github.com/dotnet/orleans/pull/8595. Which version of Orleans are you using, @orionstudt? Thank you for bumping the issue.

**Comment by ReubenBond** [comment]
This ought to be fixed (see above). Closing for now. Please open a new issue if you still hit this on the latest version of Orleans.

**Comment by orionstudt** [comment]
Hey @ReubenBond, apologies for missing the message. Just confirming that it was fixed with a version bump 👍🏼

**Comment by ReubenBond** [comment]
Great, thank you!
