### ISSUE TITLE
[Question] Can Orleans serialize .proto generated codes? 

### ISSUE THREAD

**Issue by zeinali0** [dotnet/orleans#8211]
Hi
Can classes generated by `Grpc.Tools` base on `.proto` files be used as messages in grains, by using `ProtobufSerializer`?
Orleans 7.0

**Comment by abe545** [comment]
Hey @zeinali0 - not sure if you got this working, but I also need protobuf serialization support. I found this other issue where another dev did most of the work: https://github.com/dotnet/orleans/issues/8276

**Comment by ReubenBond** [comment]
Yes, you can use the Microsoft.Orleans.Serialization.ProtocolBuffers package to accomplish this:

```csharp
siloBuilder.Services.AddSerializer(serializerBuilder => serializerBuilder.AddProtobufSerializer(...))
```
