### ISSUE TITLE
SMS is not fully replaced in Orleans 7

### ISSUE THREAD

**Issue by wakemaster39** [dotnet/orleans#8215]
I am currently in the processes of trying to port a code base from Orleans 3.x to Orleans 7. The code is inspired heavily from the Orleans.SignalR implementation https://github.com/OrleansContrib/SignalR.Orleans/tree/master/src/SignalR.Orleans

Specifically this section of code: https://github.com/OrleansContrib/SignalR.Orleans/blob/5ae8310c7bad156638bab3a9441f3782140d953a/src/SignalR.Orleans/OrleansHubLifetimeManager.cs#L78-L79

For context and explanation, OrleansHubLifetimeManager is a singleton that contains all the connections to the server. By adding a Subscriber to a stream, we are able to execute code in the context of that singleton on every message and send messages to the individual connections, or all the connections.  

The issue I am running into is that `MemoryStreams` seem to be the recommended replacement, as I need explicit subscriptions here. But when you attempt to call `GetStream`, it errors saying: `Cannot resolve scoped service 'Orleans.Streams.StreamDirectory' from root provider.`

Digging through the call stack, I can see that `AddSiloStreaming` does implemented this as a scoped service, and it also appears to be the same in 3.x but this wasn't an issue with the SMS Provider.

I am wondering if there is a recommended practice or some means without SMS to get a stream into this singleton or if this is a complete deal breaker in Orleans 7 that needs a re architecture on my end.

**Comment by benjaminpetit** [comment]
Not sure to understand everything.

Are you sure you added the memory stream support to the client you are using?

**Comment by wakemaster39** [comment]
I am trying to replace SMS with memory streams as I try and move to orleans 7 from 3.6.5. 

Memory streams do not seem to work in singletons because they require a scoped instance unlike SMS which I was able to use previously. So from the porting advice, it does not seem to be a direct replacement and trying to figure out if I am missing something.

**Comment by benjaminpetit** [comment]
Is it related to #8219?

**Comment by ReubenBond** [comment]
> I think a direct replacement for SMS is BroadcastChannel, not MemoryStream.

This is the answer
