### ISSUE TITLE
is it possible to recreate Grains for every call?

### ISSUE THREAD

**Issue by rogerex** [dotnet/orleans#8221]
I would like to have a new grain for every call, is that possible?

if yes, please what files can I customize for it?

**Comment by ReubenBond** [comment]
What benefit would a grain give you in that case?

**Comment by rogerex** [comment]
I would like to call a grain method as a request/response, I don't want to deal with db context DI issues, the threads issue due to have a single grain, I just want to have a way to move my current code to orleans to test it in load testing to see results

**Comment by SebastianStehle** [comment]
Grains are single threaded, you will not have threading issues
