### ISSUE TITLE
Configure types and member to be serialized at runtime 

### ISSUE THREAD

**Issue by brijgogogo** [dotnet/orleans#8231]
Hi guys. We are using Orleans 7 and the docs suggest that we mark the serializable types and members with GenerateSerializer and Id attributes. We are able to get it work in that way, but is there a way to do same at runtime while configuring Orleans, something like:

```
orleansOptions.RegisterType(typeof(A))
                           .RegisterMemberId(nameof(A.PropOne), 0)
                           .RegisterMemberId(nameof(A.PropTwo), 1);
```

**Comment by ReubenBond** [comment]
Orleans generates high performance serializers for your types at build time, so there is no way to provide the necessary information for types on the fly during startup.

In your case, I would recommend either using JSON or configuring surrogate types: https://learn.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/serialization?pivots=orleans-7-0
