### ISSUE TITLE
[Orleans 3.x] Failed to un-register NonExistentActivation error when calling DeactivateOnIdle & using Redis grain directory

### ISSUE THREAD

**Issue by rpatel372** [dotnet/orleans#8232]
We're using a Redis grain directory that has multiple shards and multiple clusters in the shard. We're seeing the following exception when calling DeactivateOnIdle:

```
Failed to un-register NonExistentActivation
ERR Script attempted to access a non local key in a cluster node script
```

We are using version 3.6.5-beta1. This is the code to reproduce the error:

```
try
{
    await _state.WriteStateAsync();
    await _state.ReadStateAsync();
    await _state.ClearStateAsync();
}
finally
{
   DeactivateOnIdle();
}
```

**Comment by ReubenBond** [comment]
I think the issue here is Redis clustering, based on this error: "ERR Script attempted to access a non local key in a cluster node script". This should have been fixed by #8261
