### ISSUE TITLE
'OrleansSerializationSourceGenerator' failed to generate source.

### ISSUE THREAD

**Issue by fwaris** [dotnet/orleans#8233]
I am starting to get this code gen error for an F# Orleans library referenced by a C# 'code gen' library.

I am using Window 11 with Visual Studio Version 17.4.3.

A simple repo solution is attached. I have tried this on two different machines with the same result.

Not sure how to go about troubleshooting a problem like this.
[FsGrains.zip](https://github.com/dotnet/orleans/files/10263072/FsGrains.zip)

The full error is:
CSC : warning CS8785: Generator 'OrleansSerializationSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Operation is not valid due to the current state of the object.'

(seems like code generation will likely be a source of fragility for a long time to come)

**Comment by ReubenBond** [comment]
The error message us unfortunate. I can see from your F# code that you have a method on your `IGetData` grain which returns a double synchronously. That is not allowed: grains must return a specific set of async types (`Task`, `Task<T>`, `ValueTask`, `ValueTask<T>`, or (not recommended) `void`)

**Comment by ReubenBond** [comment]
I opened a PR to catch these cases. There is an error in your code (invalid return type for a grain method, see previous comment) which is triggering a bug in the code generator. xref #8234

**Comment by fwaris** [comment]
@ReubenBond thanks!
