### ISSUE TITLE
Microsoft.Orleans.Hosting.Kubernetes RBAC needs delete permission?

### ISSUE THREAD

**Issue by cdemi** [dotnet/orleans#8248]
According to this:
https://github.com/dotnet/orleans/blob/041fd50105abe2002dedfc7f2577c159f7344323/src/Orleans.Hosting.Kubernetes/KubernetesClusterAgent.cs#L176

The RBAC sample here: https://learn.microsoft.com/en-us/dotnet/orleans/deployment/kubernetes also needs a `delete` verb on the role.

Am I correct?

**Comment by ReubenBond** [comment]
Yes, that sounds correct to me. Is the required docs change as simple as adding a "delete" element to the verbs list?

``` yaml
verbs: ["get", "watch", "list", "delete"]
```

**Comment by cdemi** [comment]
Looks like it. If you want I can open a PR

**Comment by ReubenBond** [comment]
That would be great, thank you

**Comment by ReubenBond** [comment]
Fixed by https://github.com/dotnet/docs/pull/33299 (thank you, @cdemi)
