### ISSUE TITLE
Question: Distributed Tracing in a SignalR + Orleans app using AWS X-Ray

### ISSUE THREAD

**Issue by rajumakade** [dotnet/orleans#8251]
Hi Team,
We have two services:

**1. Orleans Silo host (Activate grains)**
**2. Microsoft SignalR .net web Application (which will be client server for Silohost).**

We are using **UseDynamoDBClustering** to store state of grain in dynamodb.

**When user connects to  SignalR .net web Application we have to trace call in AWS xray using open telemetry.**

As mentioned here in this vedio

**https://www.youtube.com/watch?v=GKXiGhFBd90**

We tried by configuring **ActivityPropagationOutgoingGrainCallFilter** in our SignalR .net web Application. Able to see traces in AWS xray but not getting any call trace for grain call (Only seeing the  SignalR .net web Application side trace.)

This is trace information currently getting
<img width="866" alt="image" src="https://user-images.githubusercontent.com/88999028/210768979-20012d85-dc90-49f4-b63f-6ff99ddc26fb.png">

Request you to please help with this as its blocking us.

Thanks.

**Comment by ReubenBond** [comment]
Which version of Orleans are you using and how are you configuring tracing?

**Comment by rajumakade** [comment]
Hi @ReubenBond ,

Please find below details
We are using below packages in **SignalR .net web Application**
<img width="635" alt="image" src="https://user-images.githubusercontent.com/88999028/210926468-716a228e-9d85-4e1f-9f90-afa3f6c2d3ff.png">

In **Silo host project**

<img width="611" alt="image" src="https://user-images.githubusercontent.com/88999028/210926563-f905c3c5-fd18-44ed-9be8-b1841a4071b1.png">

Tracing configuration is done in **SignalR .net web Application** as shown below
1. Added attached **ActivityPropagationGrainCallFilter** class
2. While configuring silo host using **ClientBuilder** added this class as Outgoing filter
    <img width="434" alt="image" src="https://user-images.githubusercontent.com/88999028/210927814-5191f977-fabf-4b1f-8a28-598e39c49911.png">
3. Configured tracing in program.cs as below
<img width="629" alt="image" src="https://user-images.githubusercontent.com/88999028/210927439-29c8fa73-5f38-4dfc-a0e1-2d4120c180ff.png">

[ActivityPropagationGrainCallFilter.zip](https://github.com/dotnet/orleans/files/10357269/ActivityPropagationGrainCallFilter.zip)

Please let me know if anything required.

Thanks

**Comment by ReubenBond** [comment]
> While configuring silo host using ClientBuilder

What do you mean by this?

**Comment by ReubenBond** [comment]
If you want tracing, you'll need both an incoming and outgoing call filter.

**Comment by rajumakade** [comment]
> > While configuring silo host using ClientBuilder
> 
> What do you mean by this?

Please refer below code in SignalR .net web Application to connect to silo

<img width="508" alt="image" src="https://user-images.githubusercontent.com/88999028/210931310-d813e78f-e883-42d2-92b1-5bfed77af919.png">

**Comment by rajumakade** [comment]
> If you want tracing, you'll need both an incoming and outgoing call filter.

Not showing any option to configure incoming filter for **ClientBuilder** in code shown in comment above

**Comment by ReubenBond** [comment]
Are the call filters also configured on your silo?

**Comment by rajumakade** [comment]
> Are the call filters also configured on your silo?

Yes tried with by adding filters on silo side as well. not getting any trace in aws xray
<img width="568" alt="image" src="https://user-images.githubusercontent.com/88999028/210934139-132bb51b-7e89-478f-bae4-23f78b353a06.png">

Also from silo side filters are getting called continuously

<img width="458" alt="image" src="https://user-images.githubusercontent.com/88999028/210934112-fb17adf2-226f-4edc-899c-424e599b630b.png">

**Comment by rajumakade** [comment]
Hi @ReubenBond ,

I have tried below set up and seems working fine with expected traces in AWS xray.(Testing more scenarios)
1. Configured **ActivityPropagationOutgoingGrainCallFilter** in  **SignalR .net web Application**
2. Configured **ActivityPropagationIncomingGrainCallFilter** in **Silo application**

I have below queries. Request you to please confirm
1. Is this only way to add Grain filters for tracing or any other way?
2. Used attached class for Outgoing and incoming filters configuration (modified as per need) any nuget package available for same or this is correct?
3. Filters on silo side, can we configure it to execute only when grain method is called.?

Thanks
[ActivityPropagationGrainCallFilter.zip](https://github.com/dotnet/orleans/files/10361398/ActivityPropagationGrainCallFilter.zip)

**Comment by rajumakade** [comment]
Hi @ReubenBond ,

By using below set up able to see the traces of Grains in AWS xray. But if any exception in Grain method (catch block) not showing in traces.
1. Configured **ActivityPropagationOutgoingGrainCallFilter** in **SignalR .net web Application**
2. Configured **ActivityPropagationIncomingGrainCallFilter** in **Silo application**

However, traces for exception from **SignalR .net web Application** side is showing by adding below code in catch block

<img width="403" alt="image" src="https://user-images.githubusercontent.com/88999028/211538306-cfe3056d-33d6-4d36-a065-1777d99aedc2.png">

Request you to please help with this.

Thanks.
