### ISSUE TITLE
Custom Json Converter does not work in Orleans

### ISSUE THREAD

**Issue by andtii** [dotnet/orleans#8252]
Using a custom json converter for System.Text.Json is throwing an exception. It works when serializing directly using JsonSerializer but not when passed to the grain method.

![image](https://user-images.githubusercontent.com/1434571/210855887-54a34b1a-f6fe-49d2-997d-185747b944f4.png)

The exception stacktrace is
![image](https://user-images.githubusercontent.com/1434571/210855964-099daff6-46a9-4eba-b83b-29b29143f0b7.png)

Here is a repro 
https://github.com/andtii/OrleansCustomJsonConverter

**Comment by TheFo2sh** [comment]
any updates ?

**Comment by ReubenBond** [comment]
Thank you for reporting and for providing a repro. I have a fix which I hope to have ready and merged soon. Apologies for the hassle.

<img width="394" alt="image" src="https://user-images.githubusercontent.com/203839/215876322-30f62b64-76ca-4924-9163-a5f7f7a73820.png">

**Comment by andtii** [comment]
Sweeet!

**Comment by ReubenBond** [comment]
Fix PR: #8300
