### ISSUE TITLE
what's 7.0package and sourcecode differents  when if build my project ref two mode

### ISSUE THREAD

**Issue by liuzhixin405** [dotnet/orleans#8253]
ref  sourcecode 7.0 problem : Could not find an implementation for interface Fake.Interfaces.IFakeMessage
but is i use  7.0package is normal.

code this 

```C#
public interface IFakeMessage: Orleans.IGrainWithIntegerKey
{
    Task<string> GetMessageAsync();
}
public class FakeMessage : Orleans.Grain, IFakeMessage
{
    public Task<string> GetMessageAsync() =>Task.FromResult("ok");
}
```

server :   

``` C#
internal class Program
{'
    static void Main(string[] args)
    {
        var hostBuilder = new HostBuilder().UseOrleans((ctx, siloBuilder) =>
        {
            siloBuilder.UseLocalhostClustering();
        });

        var host = hostBuilder.Build();

        host.StartAsync().GetAwaiter().GetResult();
        Console.Write("host server start...");
        Console.ReadLine();
    }
}
```
client:
``` C#
 static async Task Main(string[] args)
    {
        var hostBuilder = new HostBuilder()
             .UseOrleansClient((ctx, builder) => {
                 builder.UseLocalhostClustering();    
             });
        using var host = hostBuilder.Build();

        var client = host.Services.GetService<IGrainFactory>()??throw new ArgumentNullException(nameof(IGrainFactory));
        var ms =await client.GetGrain<IFakeMessage>(0).GetMessageAsync();
       
        Console.WriteLine($"result:{ms}");
        await host.StartAsync();
    }
```

**Comment by ReubenBond** [comment]
Your Server, Client, and Grain/Interfaces projects all need to reference `Microsoft.Orleans.Sdk`

**Comment by ReubenBond** [comment]
You cannot resolve a grain before `host.StartAsync()` completes. You should move `StartAsync()` above the `client.GetGrain<IFakeMessage>(0)...` line.
Below, you can `await host.StopAsync()` instead, or `host.WaitForShutdownAsync()` if you call `.UseConsoleLifetime()` on the host builder to ensure it listens for Ctrl+C

**Comment by liuzhixin405** [comment]
thank you! error corrected!but throw error still。
![image](https://user-images.githubusercontent.com/30038237/211720622-c13df295-a3b6-430b-8bbd-df65a5d4b0cf.png)
![image](https://user-images.githubusercontent.com/30038237/211720645-3ab24a85-a559-4145-92d7-d6f6a1380ff3.png)
![image](https://user-images.githubusercontent.com/30038237/211720690-32d20833-c250-432e-9fe1-e20b25c2caed.png)
![image](https://user-images.githubusercontent.com/30038237/211720725-e1bcb0cb-74b3-4b56-bd3d-451c32409837.png)
![image](https://user-images.githubusercontent.com/30038237/211720770-bdfac7cb-1b7e-4460-ae52-075340b8cadc.png)
![image](https://user-images.githubusercontent.com/30038237/211720800-70d024fc-a6e2-44ea-982e-be98d0cd3ac2.png)

**Comment by liuzhixin405** [comment]
the right result if i ref nugit，all  code is the same, before i test the project  other things.
![image](https://user-images.githubusercontent.com/30038237/211721908-ebe6a86f-8b4d-49db-9c17-f75c0226310b.png)
