### ISSUE TITLE
Provide alternative to using System.Reflect.Emit in Orleans Serialization

### ISSUE THREAD

**Issue by jsteinich** [dotnet/orleans#8254]
The `System.Reflection.Emit` namespace is unsupported on many AOT platforms. Those platforms probably aren't relevant for running Orleans directly, but are useful when using the serializer in a standalone context.
Likely the alternative path would use reflection.

**Comment by ReubenBond** [comment]
We should consider implementing alternatives for AOT platforms. I'm far from an expert in this area. What are the places it's being used today? Maybe some of the sites can be statically generated, but I'm sure we'll need reflection in places.

I believe that one of the bigger problems for AOT will be `MakeGenericType`, which is used extensively in the serializer (eg, to turn a `ListCodec<T>` into a `ListCodec<int>`)

**Comment by KSemenenko** [comment]
I don’t think there is a reason for it at least for now. AOT isn't necessarily faster or more efficient.

**Comment by gfoidl** [comment]
> I'm far from an expert in this area

Same here, but when possible source generators could do the job of creating specialized types so it becomes AOT-friendly/friendlier.
For Orleans I'm with @KSemenenko, as ASP.NET Core isn't really AOT friendly today too -- but here it shouldn't lag behind the efforts done in ASP.NET in this area.

**Comment by ReubenBond** [comment]
I'll close this now, but PRs to replace IL with more AOT-friendly alternatives are more than welcome and we may get to them ourselves eventually.
