### ISSUE TITLE
F# discriminated union types are not serialized correctly (v 7.x)

### ISSUE THREAD

**Issue by fwaris** [dotnet/orleans#8255]
Usng the Microsoft.Orleans.Serialization.FSharp package.

F# discriminated union types are not being serialized/deserialized correctly.

Workaround is to use Choice<'t1, 't2, ...> instead, which seems to work fine.

Please add support for F# discriminated unions

**Comment by ReubenBond** [comment]
They would work. I believe we have a test. If not, do you mind providing a repro?

**Comment by fwaris** [comment]
Ok I will try to create a minimal repo. Thanks.

**Comment by fwaris** [comment]
Please see attached a repo. Non-DU message works from Sender to Receiver but DU message is never received.
[FSharpSerDeTest.zip](https://github.com/dotnet/orleans/files/10422368/FSharpSerDeTest.zip)

**Comment by nitesh-hurchand-insbro** [comment]
Hi, any feedback about this issue. 
I am having same issue of DUs serialization after migrating to v7.

**Comment by ReubenBond** [comment]
I'm testing the repro now

**Comment by ReubenBond** [comment]
This works for me after adding the missing `[<GenerateSerializer>]` attribute missing to your code (highlighted):
<img width="221" alt="image" src="https://user-images.githubusercontent.com/203839/215906845-53089579-e6aa-4839-b786-84bb0d98565a.png">
The code outputs this for me:
<img width="241" alt="image" src="https://user-images.githubusercontent.com/203839/215907049-84c06c68-3aa2-4815-b533-e47a536fe056.png">


I did find a different bug in serialization for F# types, though, and I will open a PR for that.

**Comment by fwaris** [comment]
@ReubenBond thanks for the solution.

**Comment by fwaris** [comment]
[FSharpSerDeTest (2).zip](https://github.com/dotnet/orleans/files/11416159/FSharpSerDeTest.2.zip)

@ReubenBond I found another issue. 

Serialization fails when DU has a single case, e.g.:
```F#
[<GenerateSerializer>]
type D1 = 
    | T1 of E1 
    //| T2 of E2
```

I have attached the repo. I found that the generated serialization code is quite different when DU has a single case vs. two or more case.
