### ISSUE TITLE
Use same ILifetimeScope in some Grains to resolve same DbContext

### ISSUE THREAD

**Issue by Arazesh** [dotnet/orleans#8274]
Is there any way to use same scope between some grains ?

Imagine we have two grains

```
public class OrderGrain : Grain
{
   
        public async Task InsertOrder(order)
        {
            
            OrderRepository.Add(order);
        
            await _paymentGrain.InsertPayment(new payment());
        }
 
}

public class PaymentGrain : Grain
{
   
        public async Task InsertPayment(payment)
        {

            PaymentRepository.Add(payment);

            await dbContext.SaveChangesAsync();
        }
 
}
```

And on api somthing like this

```
[HttpPost]
public async Task<IActionResult> InsertOrder(order order)
{
            
     await _orderGrain .InsertOrder(order);

     return Ok();
}
```

By calling InsertPayment() , order should save and also for each request IRepository should use new dbContext instance
 
Solution that @ReubenBond suggested here :

https://github.com/dotnet/orleans/issues/5520#issuecomment-481123304

Is good when each grain SaveChanges separately

**Comment by ReubenBond** [comment]
The call may span multiple machines, but a DbContext cannot be serialized and rehydrated on another machine, so it could never be guaranteed to work.
You would need to use EF distributed transactions (requiring MSDTC, etc), which is probably not a path you want to go down.

**Comment by Arazesh** [comment]
thanks @ReubenBond  

we used to work with MSDTC for this problem ( with https://github.com/softwarehelden-com/Softwarehelden.Transactions.Oletx package) but actually it was not really reliable (maybe we used it wrong!) so we try to find a better solution.

"The call may span multiple machines" yes I understand the point.

I am curious to know if there is a solution if we use UseLocalhostClustering so there is just one machine?(I know this is not suitable for production)

**Comment by ReubenBond** [comment]
> I am curious to know if there is a solution if we use UseLocalhostClustering so there is just one machine?(I know this is not suitable for production)

If you can guarantee that you will never need to send this across the network, then you *could* add it to `RequestContext` as an `Immutable<DbContext>` so that it will flow along the request. If a `DbContext` is not available, you would create one in a scope as you see in the comment you linked and add it.

For the record: this is absolutely not a supported scenario :)

**Comment by Arazesh** [comment]
Immutable<T> is exactly what I needed and it works perfectly

Thank You
