### ISSUE TITLE
Grain with named PersistentState store still requires default storage to be added

### ISSUE THREAD

**Issue by michaelmcneilnet** [dotnet/orleans#8283]
If I have a grain with a constructor such as 

```cs
public MyGrain([PersistentState("myGrainState", "storageName")] IPersistentState<MyState> state)
```

and a silo builder with

```cs
builder
    .Host
    .UseOrleans(siloBuilder => siloBuilder
        .UseLocalhostClustering()
        .AddMemoryGrainStorage("storageName")
    );
```

I receive the following error unless I also register `.AddMemoryGrainStorageAsDefault()`.

```
Orleans.Storage.BadProviderConfigException: No default storage provider found loading grain type MyGrain
```

The grains are correctly using the named storage and not the default storage. I tested this by registering memory storage as the default, and azure blob storage as the named storage, and I can see the grains in azure blobs.

I expected `PersistentState` with a named store to use the named store and not also require a default store to be registered. If this is intended behaviour, it would be good to make this clearer in the Persistence documentation.

This is using Orleans v7, I haven't tried with v3.

**Comment by michaelmcneilnet** [comment]
I just tested this with Orleans v3, and I only need to register a named storage provider and do not also need to register default storage. Does it seem like this is a regression in v7?

**Comment by michaelmcneilnet** [comment]
Ignore this, my grain also inherited from `Grain<MyState>`  🤦

**Comment by ReubenBond** [comment]
Glad you got it sorted :)
