### ISSUE TITLE
Orleans.Serialization.CodecNotFoundException : Could not find a codec for type Orleans.Serialization.NewtonsoftJsonCodec.

### ISSUE THREAD

**Issue by EquineSolutions** [dotnet/orleans#8293]
iam getting Orleans.Serialization.CodecNotFoundException : Could not find a codec for type Orleans.Serialization.NewtonsoftJsonCodec

when using Newtonsoft Json Serializer with TestCluster

`
namespace Jcl.Tests
{
   

    public class TestSiloConfigurations : ISiloConfigurator
    {
        void AddSerializer(ISerializerBuilder serializerBuilder)
        {
            serializerBuilder.AddNewtonsoftJsonSerializer(isSupported: type =>
            {
                return typeof(HttpResponseException) == type;
            });
        }
        public void Configure(ISiloBuilder siloBuilder)
        {
            siloBuilder.AddMemoryGrainStorageAsDefault();
            siloBuilder.UseLocalhostClustering();
            siloBuilder.Services.AddSerializer(AddSerializer);
        }
    }

    public class ClusterFixture : IDisposable
    {
        public ClusterFixture()
        {
            var builder = new TestClusterBuilder();

            builder.AddSiloBuilderConfigurator<TestSiloConfigurations>();
            
            Cluster = builder.Build();
            
            Cluster.Deploy();
        }

        public void Dispose() => Cluster.StopAllSilos();

        public TestCluster Cluster { get; }
    }
}

`

**Comment by ReubenBond** [comment]
You need to configure it on the silo and the client if these types are being exchanged from one to the other. I'm not sure if that's what is happening here (there is insufficient detail to determine that).
