### ISSUE TITLE
30 - 80 ms delay for calling a grain that returns a simple string ?

### ISSUE THREAD

**Issue by EquineSolutions** [dotnet/orleans#8298]
is it normal to have 30 - 80 ms delay for calling a grain in localhost ?

I made a simple grain (STATELESS) that returns a string

`public ValueTask<string> TestTwo(string input)
        {
            return ValueTask.FromResult(input);
        }
`

and a simple controller to call it

`[HttpGet("test-two")]
        public async Task<IActionResult> TestTwo(string input)
        {
            var shim = _client.GetGrain<IShimGrain>(0);
            return Ok(await shim.TestTwo(input));
        }`
    it takes about 30 - 80 ms to complete, it's like querying data from a database

returning a string directly takes on average 10ms
`[HttpGet("test")]
        public async Task<IActionResult> TestOne(string input)
        {
            return Ok(await Task.FromResult(input));
        }`

**Comment by ReubenBond** [comment]
Did you work out what was happening here?
