### ISSUE TITLE
ArgumentOutOfRange: The added or subtracted value results in an un-representable DateTime

### ISSUE THREAD

**Issue by gparissis** [dotnet/orleans#8303]
Recently I have been viewing the below error in the Orleans console, and I don't know what I did in order to cause it.

`Orleans.Runtime.ActivationCollector[0]
Exception while collecting activations
System.ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime. (Parameter 't')
   at System.DateTime.ThrowDateArithmetic(Int32 param)
   at System.DateTime.op_Addition(DateTime d, TimeSpan t)
   at Orleans.Runtime.ActivationCollector.MakeTicketFromTimeSpan(TimeSpan timeout) in /_/src/Orleans.Runtime/Catalog/ActivationCollector.cs:line 362`

I understand that something is adding or removing units from a date-time value that is causing the value not to be representable anymore, but it is not my code. I can't even see the type of grain that caused the exception. I believe it is something internal in Orleans, but I wonder how my code triggered this behavior? What should I look for in my code?

I appreciate any help you can provide.

**Comment by ReubenBond** [comment]
Do you have a `[CollectionAgeLimit(x)]` attribute on the grain or some other configuration setting the activation collection age limit?

**Comment by gparissis** [comment]
> 

As a matter of fact, I do have a DelayDeactivation(TimeSpan.MaxValue) for one grain. I don't have the attribute you mentioned in my code. Any ideas?

**Comment by michaelmcneilnet** [comment]
> > 
> 
> As a matter of fact, I do have a DelayDeactivation(TimeSpan.MaxValue) for one grain. I don't have the attribute you mentioned in my code. Any ideas?

Orleans is taking the `TimeSpan.MaxValue` and adding to it, hence the crash. Are you doing this to try to keep the grain alive forever? If you are using Orleans v7, you can use the [KeepAlive](https://learn.microsoft.com/en-us/dotnet/api/orleans.keepaliveattribute?view=orleans-7.0) attribute on the grain implementation.

**Comment by gparissis** [comment]
You are correct. I need this grain to stay alive since it hosts a queue that is processed sequentially and I didn't need to be deactivated while the queue has still entries to be processed. I will use the [KeepAlive] attribute then. Thank you.
