### ISSUE TITLE
Distributed transaction over JournaledGrains

### ISSUE THREAD

**Issue by dvlprx** [dotnet/orleans#8305]
I'm trying to use a distributed transaction over N JournaledGrains and need a hint to get me on track.

The JournaledGrains do use a custom `LogConsistencyProvider` and implement `ICustomStorageInterface<TState, TEvent>`. So they are already forcing all read/write operations to go through it's own methods:

`ReadStateFromStorage()`
`ApplyUpdatesToStorage(..)`

To use distributed transactions I have to use an `ITransactionalState<TState>` facade, which also forces all read/write operations to go through it's own methods:

`PerformRead<TResult>(..)`
`PerformUpdate<TResult>(..)`

How to combine JournaledGrains (based on custom LogConsistencyProvider), with ITransactionalState, or if this is the wrong approach at all: how to combine eventSourcing with distributed transactions in orleans, when having a custom `LogConsistencyProvider`?

Are there any samples in the code, that I missed?
Thank you for every hint.

**Comment by ReubenBond** [comment]
Journaled grains don't support transactions, at least not yet.

**Comment by NatElkins** [comment]
Just want to drop a note that I am also interested in this use case.
