### ISSUE TITLE
Use of ContinueWith in IGrainMethodInvoker.Invoke() breaks async/await exception handling.

### ISSUE THREAD

**Issue by PaulNorth** [dotnet/orleans#831]
Due to the generated code `IGrainMethodInvoker.Invoke()` using a `ContinueWith` that wraps and rethrows any exception that occurs within an async Grain method, the consuming code must therefore always catch `AggregateException` and unwrap the `InnerException`; i.e. I can't just catch the specific exception as you would normally expect to with TPL.

One proposed solution would be to generate the code using `TaskContinuationOptions.OnlyOnRanToCompletion`.  

For example: 
`return ((IMyGrain)grain).DoSomethingAsync((String)arguments[0]).ContinueWith(t => {return (object)null; }, TaskContinuationOptions.OnlyOnRanToCompletion);`

as per http://stackoverflow.com/questions/29621079/how-to-avoid-nested-aggregateexception-when-using-task-continuewith

Paul

**Comment by yevhen** [comment]
I think that problem might be in some other place but I'm not sure.

Anyway, from past discussions I remember @sergeybykov or @gabikliot mentioned that unwrapping and re-throwing of original exception led to the loss of stacktrace. That could be fixed. I'm using [this](https://github.com/yevhen/Orleankka/blob/master/Source/Orleankka/Utility/TaskExtensions.cs) utility extension method in Orleankka.

Could be useful.

**Comment by ReubenBond** [comment]
In general, I think `ExceptionDispatchInfo.Capture` is the best way to preserve stack traces, but the suggestion of just using `TaskContinuationOptions.OnlyOnRanToCompletion` should give the desired result. The `ContinueWith` exists to convert each `Task`/`Task<T>` from the grain into a `Task<object>`.

**Comment by gabikliot** [comment]
We should try ` TaskContinuationOptions.OnlyOnRanToCompletion `.

Just a background information: why did we use  `ContinueWith`  and not `await` here? The reasoning was that `await` is in general mode costly that `CW`, since `await` results in additional object allocation that compiler generates to translate `await` into CW so it more expensive. Since this is a generate code (so write once) we thought that a one time more complicated code is worth the potential perf. benefit.
And as Reuben pointed, we need this `CW` or `await` there to cast from `T` to `object`. We did not find a way to get rid of this cast at all. If we could , then we would not need this generated code inside the invoker at all, and the whole problem would go away.

**Comment by ReubenBond** [comment]
In addition to `TaskContinuationOptions.OnlyOnRanToCompletion`, we should specify `TaskContinuationOptions.ExecuteSynchronously` to reduce the cost further.

**Comment by ReubenBond** [comment]
So in #528 I replaced this continuation with a `Box` extension method which executes synchronously and uses a task completion source to propagate the exception from the antecedent. I will simplify that to simply only execute on success and just cast the result.

**Comment by gabikliot** [comment]
+1 on trying ` TaskContinuationOptions.OnlyOnRanToCompletion ` and ` TaskContinuationOptions.ExecuteSynchronously`.

**Comment by veikkoeeva** [comment]
> And a 2nd marginally related comment: in general, if we are looking into optimization the performance of the runtime stack, optimizing the usage of TPL (reducing the number of times during a hot path of message call that we call await or CW) will probably give us a lot of benefits. So reducing this one place in the invoker where we call CW can be very beneficial.

[The zen of async: Best practices for best performance](https://channel9.msdn.com/Events/Build/BUILD2011/TOOL-829T), faint memories of the video, but just glanced through the PowerPoint slides and they still feel golden. Maybe there are improvements to be had here (e.g. what I personally overlook often is caching ``Task``s).

**Comment by sergeybykov** [comment]
Resolved by https://github.com/dotnet/orleans/pull/528.
