### ISSUE TITLE
BenchmarkDotNet not working for Orealns 7.x

### ISSUE THREAD

**Issue by YAJeff** [dotnet/orleans#8311]
Seems to be the same issue as #7751.

Setup power plan (GUID: 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c FriendlyName: High performance)
// Build Error: Standard output:

 Standard error:
 MSBuild version 17.4.1+9a89d02ff for .NET
F:\vwac\repos\Breakpoint\DeviceBroker\src\DeviceBroker.Benchmarks\bin\Release\net7.0\58f26a13-c3c4-4093-9d12-ded6c7a1bc98\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\58f26a13-c3c4-4093-9d12-ded6c7a1bc98.orleans.g.cs(17,93): error CS0118: 'OrleansCodeGen' is a namespace but is used like a type [F:\vwac\repos\Breakpoint\DeviceBroker\src\DeviceBroker.Benchmarks\bin\Release\net7.0\58f26a13-c3c4-4093-9d12-ded6c7a1bc98\BenchmarkDotNet.Autogenerated.csproj]
F:\vwac\repos\Breakpoint\DeviceBroker\src\DeviceBroker.Benchmarks\bin\Release\net7.0\58f26a13-c3c4-4093-9d12-ded6c7a1bc98\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\58f26a13-c3c4-4093-9d12-ded6c7a1bc98.orleans.g.cs(17,113): error CS0103: The name 'a13c3c440939d12ded6c7a1bc98' does not exist in the current context [F:\vwac\repos\Breakpoint\DeviceBroker\src\DeviceBroker.Benchmarks\bin\Release\net7.0\58f26a13-c3c4-4093-9d12-ded6c7a1bc98\BenchmarkDotNet.Autogenerated.csproj]
F:\vwac\repos\Breakpoint\DeviceBroker\src\DeviceBroker.Benchmarks\bin\Release\net7.0\58f26a13-c3c4-4093-9d12-ded6c7a1bc98\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\58f26a13-c3c4-4093-9d12-ded6c7a1bc98.orleans.g.cs(17,12): error CS1729: 'TypeManifestProviderAttribute' does not contain a constructor that takes 4 arguments [F:\vwac\repos\Breakpoint\DeviceBroker\src\DeviceBroker.Benchmarks\bin\Release\net7.0\58f26a13-c3c4-4093-9d12-ded6c7a1bc98\BenchmarkDotNet.Autogenerated.csproj]
Build FAILED.
F:\vwac\repos\Breakpoint\DeviceBroker\src\DeviceBroker.Benchmarks\bin\Release\net7.0\58f26a13-c3c4-4093-9d12-ded6c7a1bc98\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\58f26a13-c3c4-4093-9d12-ded6c7a1bc98.orleans.g.cs(17,93): error CS0118: 'OrleansCodeGen' is a namespace but is used like a type [F:\vwac\repos\Breakpoint\DeviceBroker\src\DeviceBroker.Benchmarks\bin\Release\net7.0\58f26a13-c3c4-4093-9d12-ded6c7a1bc98\BenchmarkDotNet.Autogenerated.csproj]
F:\vwac\repos\Breakpoint\DeviceBroker\src\DeviceBroker.Benchmarks\bin\Release\net7.0\58f26a13-c3c4-4093-9d12-ded6c7a1bc98\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\58f26a13-c3c4-4093-9d12-ded6c7a1bc98.orleans.g.cs(17,113): error CS0103: The name 'a13c3c440939d12ded6c7a1bc98' does not exist in the current context [F:\vwac\repos\Breakpoint\DeviceBroker\src\DeviceBroker.Benchmarks\bin\Release\net7.0\58f26a13-c3c4-4093-9d12-ded6c7a1bc98\BenchmarkDotNet.Autogenerated.csproj]
F:\vwac\repos\Breakpoint\DeviceBroker\src\DeviceBroker.Benchmarks\bin\Release\net7.0\58f26a13-c3c4-4093-9d12-ded6c7a1bc98\Orleans.CodeGenerator\Orleans.CodeGenerator.OrleansSerializationSourceGenerator\58f26a13-c3c4-4093-9d12-ded6c7a1bc98.orleans.g.cs(17,12): error CS1729: 'TypeManifestProviderAttribute' does not contain a constructor that takes 4 arguments [F:\vwac\repos\Breakpoint\DeviceBroker\src\DeviceBroker.Benchmarks\bin\Release\net7.0\58f26a13-c3c4-4093-9d12-ded6c7a1bc98\BenchmarkDotNet.Autogenerated.csproj]
    0 Warning(s)
    3 Error(s)
Time Elapsed 00:00:04.75

// BenchmarkDotNet has failed to build the auto-generated boilerplate code.
// It can be found in F:\vwac\repos\Breakpoint\DeviceBroker\src\DeviceBroker.Benchmarks\bin\Release\net7.0\58f26a13-c3c4-4093-9d12-ded6c7a1bc98
// Please follow the troubleshooting guide: https://benchmarkdotnet.org/articles/guides/troubleshooting.html

**Comment by YAJeff** [comment]
Going to spend a few more cycles trying to solve. And if nothing, will try to provide a repo. Also, thanks @ReubenBond for everything you've done for Orleans. Big fan of your stuff on YouTube as well. My org is doing a major shift over to using Orleans as a core part of our strategy. We are a large (maybe massive) partner of Microsoft. We could really use some insights. Reaching out to you on Twitter.

**Comment by YAJeff** [comment]
Ok. Figured this out. It was related to all of the code generation settings in the .csproj file. Removing them allows this to work fine.

**Comment by ReubenBond** [comment]
Which attributes were they, @YAJeff, do you recall?

**Comment by YAJeff** [comment]
Unfortunately the issue came back. Haven't been able to get it working consistently. The issue is very intermittent. Working on putting together a repo I can share.
