### ISSUE TITLE
Questionable test/cast pair in OrleansJsonSerializer.cs

### ISSUE THREAD

**Issue by Jens-G** [dotnet/orleans#8322]
There is a questionable test/cast pair in OrleansJsonSerializer.cs:

* First we [test against `AddressableType.IsAssignableFrom(objectType)` in line 289](https://github.com/dotnet/orleans/blob/095def6734a61c99101293721fae265341344740/src/Orleans.Core/Serialization/OrleansJsonSerializer.cs#L289);
* the we do a hard [cast in line 295: `var val = (GrainReference)value;`](https://github.com/dotnet/orleans/blob/095def6734a61c99101293721fae265341344740/src/Orleans.Core/Serialization/OrleansJsonSerializer.cs#L295)

If the instance is Addressable but not a GrainReference, you get an NPE next.

Would it maybe more correct to test sth along of `objectType is GrainReference`?

**Comment by ReubenBond** [comment]
Well spotted. It should be cast to `IAddressable` and then to `GrainReference` using the non-generic `AsReference` extension method: https://github.com/dotnet/orleans/blob/2195a32918ca325090cb01f0cb3eb9c983f49284/src/Orleans.Core.Abstractions/Core/GrainExtensions.cs#L20
