### ISSUE TITLE
[Orleans 3.x] Simple Message Stream provider hangs

### ISSUE THREAD

**Issue by benthepoet** [dotnet/orleans#8327]
I'm having an issue with the Simple Message Stream provider in Orleans 3.6.5. The setup is I have a grain in the silo where I'm publishing messages to the stream.

Externally in a console application, I've instantiated a client and subscribed to the stream. My client is able to get messages from the stream. However, I've noticed that if I hard shutdown my client application without unsubscribing then the producer gets hung up on the following `OnNextAsync` task. No more messages come through and the task never errors or times out.

**Comment by ReubenBond** [comment]
Hi @benthepoet, when I've seen this in the past, the cause has been a cycle (deadlock) in the grain calls made by the SMS provider under the covers (producer grain calls the consumer grains). I recommend switching to MemoryStreams instead. If you think that is not happening in this situation, please feel free to respond with some more info and we'll take a look with you
