### ISSUE TITLE
[Question] Handle timeout error in the target grain

### ISSUE THREAD

**Issue by ifle** [dotnet/orleans#8331]
Hi,

Suppose we have 2 grains, A and B. A call B. grain B has a long-running process and grain A has a timeout. Is there a built-in way to handle this timeout in grain B for the cancellation of the long-running process?

**Comment by ReubenBond** [comment]
@ifle good question. There is not, unless you use GrainCancellationToken https://learn.microsoft.com/en-us/dotnet/orleans/grains/cancellation-tokens
