### ISSUE TITLE
[Orleans 7] Rewindable streams are skipping first message in queue cache on subscribe

### ISSUE THREAD

**Issue by abe545** [dotnet/orleans#8335]
We have a custom stream implementation that is fully rewindable. While upgrading to Orleans 7, I noticed that all subscriptions were skipping the first message in the queue cache. I narrowed this down to [this block of code](https://github.com/dotnet/orleans/blob/main/src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs#L300-L307). For clarity, I'll copy it here:
```cs
if (requestedHandshakeToken != null)
{
    consumerData.SafeDisposeCursor(logger);
    // The handshake token points to an already processed event, we need to advance the cursor to
    // the next event.
    consumerData.Cursor = queueCache.GetCacheCursor(consumerData.StreamId, requestedHandshakeToken.Token);
    consumerData.Cursor.MoveNext(); //
}
```

From what I can tell, that comment isn't strictly true. The `requestedHandshakeToken` could be a `DeliveryToken` or a `StartToken`. In my testing, if I add a check to only do the `MoveNext()` if it is a `DeliveryToken`, then my test suite passes. 

I don't have an EventHub to test on sadly, so I was looking through the tests (as I think that is the only other rewindable stream implemented in this repo), and I noticed that the `ProgrammaticSubcribeTestsRunner` never does tests where subscriptions happen after data is already produced (and the tests in `EHImplicitSubscriptionStreamRecoveryTests` are both commented out). This is one of the scenarios that we'd like to support, so I have a number of tests that validate this behavior. This is especially important for silo restarts/rolling deployments - I need to verify that grains can then resume their subscriptions without missing events. 

I can't share my code unfortunately, but does this sound like I'm implementing the rewindable streams wrong, or do you think I found a bug in the `PersistentStreamPullingAgent`?

This code block changed in orleans 7 - [here is the code in the 3.x branch](https://github.com/dotnet/orleans/blob/3.x/src/Orleans.Runtime/Streams/PersistentStream/PersistentStreamPullingAgent.cs#L294-L298):
```cs
if (requestedHandshakeToken != null)
{
    consumerData.SafeDisposeCursor(logger);
    consumerData.Cursor = queueCache.GetCacheCursor(consumerData.StreamId, requestedHandshakeToken.Token);
}
```

**Comment by nycdotnet** [comment]
Hi @ReubenBond and @benjaminpetit ,

We've got around seven services using Orleans 3.7.1 in production today, all on .NET 6, and we're generally pretty happy with it.  Many of our other services are using .NET 7 now, but we've had to keep our Orleans stuff on .NET 6 since our library code uses Orleans Streaming and unfortunately the change to streaming referenced above in Orleans 7 breaks our ability to reprocess subscriptions because the first message always gets skipped.

Abe has done all the research here and opened a PR now.  It sounds like perhaps the change made in the .NET 7 version of Orleans was incorrect - at least it is for us, and with the change our test suites pass like they do with Orleans 3.7.1.  Do you think you could please review and approve Abe's PR if it looks right?  This would unblock us from getting on Orleans 7.  Thank you!

**Comment by abe545** [comment]
Hi @benjaminpetit - our stream provider is specifically a rewindable stream provider, which we support subscribing to events that have already been delivered. So we want to be able to subscribe to a specific offset, and receive all events starting with the specified offset. We don't necessarily know the *previous* offset to subscribe to, but maybe I can try to hack that together. I appear to have lost my working branch where I was attempting this upgrade, so I'll see if I can get back to the point where I left off last time.

**Comment by abe545** [comment]
@benjaminpetit ok, I'm back to where I left off, and I think I understand what the disconnect is. For grains that have already processed events, everything is working fine when we resume subscriptions (yes, we pass a token with the last consumed event's token).

However, we also support subscribing a grain to any point in the stream. The problem I have is when I want to subscribe to the beginning of the stream. With the current implementation, there is no way to do this. The best I can do is to subscribe starting with the second event. This is because there is no semantic way of getting the first item in the stream. If I try to subscribe to an item with a `SequenceNumber` before the oldest message, the `PooledQueueCache` throws a `QueueCacheMissException` when I try to get a cursor for it. But if I pass a token pointing at the first message, it gets skipped. And if I pass a `null` token, I only get new events. Our implementation uses a custom `StreamSequenceToken` that supports the semantics of subscribing to the beginning of the stream, but there doesn't seem to be a way to translate that into a form that orleans understands.

**Comment by benjaminpetit** [comment]
We didn't support subscribing from the first event in cache intentionally: it can cause `QueueCacheMissException` in repetition. Maybe it's a setting we could add in a future release?

Right now, I think your only option would be to implement your own cache, so it could understand your custom `StreamSequenceToken`.

**Comment by abe545** [comment]
I had already implemented our own queue cache, with semantics that allowed us to do this - specifically for cases where the first item in the stream wasn't actually in cache any longer 😄. It is just that this new `MoveNext` call unexpectedly skips the first event. My current approach is to skip the first call to `MoveNext` if the token is a "first event" token, but that just seems wrong to me.

**Comment by benjaminpetit** [comment]
I don't think it's _that_ wrong, consider the "first token event" ike it's "inclusive" and regular token are "exclusive".

**Comment by abe545** [comment]
Thanks for the feedback @benjaminpetit - I guess I'll go with this approach. And sorry for the delay, I was on vacation.
