### ISSUE TITLE
[Orleans 7] Activation access violation

### ISSUE THREAD

**Issue by fergusbown** [dotnet/orleans#8339]
Hi,

We're seeing an issue (Orleans 7.1.0), which we didn't see when using Orleans 3.x, where GrainRuntime.CheckRuntimeContext is throwing an InvalidOperationException accessing Grain.GrainFactory from a grain call.

The grain in question also uses Orleans timers, and we have tried both with and without the workaround described in #2574 to ensure that these methods follow standard grain call semantics (Task.Run with this.AsReference<>)

If I disable the timers, then the exception is not thrown, so presumably the interplay of the timer with the grain is somehow resetting the RuntimeContext..?

I can work around it by injecting the GrainFactory into the grain, but this feels like a sticking plaster rather than a genuine solution.

There are no external or long running tasks involved, nothing really unusual at all that I can see

**Comment by ReubenBond** [comment]
@fergusbown aside from the cases you identified, this could be caused by a `ConfigureAwait(false)` call (you should remove those from grain code). The exception is an intentional guard-rail to detect these kinds of cases, since they usually indicate a mistake.
