### ISSUE TITLE
Cross grain storage type transactions

### ISSUE THREAD

**Issue by tomhreb** [dotnet/orleans#8340]
Hi,
we are using Orleans to store some relational data. I was investigating how the transactional state works, but it appears to me that the transactions are supported only within grains with the same State type.

Is that correct understanding, or have I missed something?

Thank you

**Comment by ReubenBond** [comment]
Hi @tomhreb, that's not correct, transactions can mix various grains with different state types. What makes it appear that a single state type is supported per transaction?

**Comment by tomhreb** [comment]
Hi @ReubenBond , sorry for late anwer. If you're saying it's supported I trust you :) I need to take another look.

I want to add support for transactional strorage to the mongodb repo, that's where my question popped up.
