### ISSUE TITLE
Deploy TestCluster is deadlocking the whole specflow test

### ISSUE THREAD

**Issue by CasperCBroeren** [dotnet/orleans#8343]
I've some prewritten specflow intergration test of my grain which I would like to test with a Orleans testcluster. 
When using the ClusterFixture I can see it been set up but when my breakpoint hits the deploy, I'm forever waiting to it to be finished.
When I do a similar setup but a regular Xunit test, the deploy works and I can use the grain for testing.

Is there anything I miss here?

```
     var builder = new TestClusterBuilder();
     builder.AddSiloBuilderConfigurator<TestSiloConfigurations>();
     this.Cluster = builder.Build();
     this.Cluster.Deploy();
```
I'm using Orleans 7.1.0  and the Orleans Testing Host. Specflow  is version 3.9.74 so both newest versions out there. If you want I can make an isolated version of the problem

**Comment by ReubenBond** [comment]
What does your TestSiloConfigurations class look like?

**Comment by CasperCBroeren** [comment]
Nothing really fancy.  I've got one store called bookstore

```
public class TestSiloConfigurations : ISiloConfigurator
{
    public void Configure(ISiloBuilder siloBuilder)
    { 
        siloBuilder.AddMemoryGrainStorage("BookStore");
    }
}
```
In my silo host program I initialize it like this in my startup
``` 
builder.AddAdoNetGrainStorage(
                                "BookStore",
                                options =>
                                {
                                    options.Invariant = invariant;
                                    options.ConnectionString = orleansDb;
                                })

```

**Comment by CasperCBroeren** [comment]
Is there anything I could do in the mean time?

**Comment by ReubenBond** [comment]
Would you be able to upload repro project that we could debug?
