### ISSUE TITLE
SimpleMessageStreamProvider sliently removed on 7.0

### ISSUE THREAD

**Issue by AlseinX** [dotnet/orleans#8348]
Why?
And what is the replacement?
Since orleans 7.0 only provide with Azure related stream providers, and open source providers are all not maintained several years ago.
And there is no stream provider available for production at all.
Does it mean that streaming is now a paid feature in practical sense, unless app developers have to look into the implementation details and implement one by hand?

**Comment by mehmetakbulut** [comment]
Does `BroadcastChannel` or `MemoryStream` work for your use case?
https://learn.microsoft.com/en-us/dotnet/orleans/migration-guide#replacement-of-simplemessagestreams-with-broadcastchannel

Curious to hear if/how you have migrated.

**Comment by benjaminpetit** [comment]
As @mehmetakbulut mentioned, `BroadcastChannel` and `MemoryStream` are the replacement.

`SimpleMessageStreamProvider` didn't had the behavior of a "true" stream provider.

**Comment by AlseinX** [comment]
> As @mehmetakbulut mentioned, `BroadcastChannel` and `MemoryStream` are the replacement.
> 
> `SimpleMessageStreamProvider` didn't had the behavior of a "true" stream provider.

Is the new `MemoryStream` designed ready for production now (I have read some docs that says it is for development only)?
Since the docs linked above says they have the same behavior, what about `BroadcastChannel`?

**Comment by AlseinX** [comment]
@BTW, since the 3rd party stream providers for open source mqs are no longer maintained, and there are in fact only Azure and AWS stream providers available for Orleans 7.0. Would the Orleans team consider to take over some of them?

Although the docs about impl details might be clear enough for a custom impl, the interface along with its behavior detail is still too complexed for App developers to keep aligned to the latest Orleans.

**Comment by thejavascriptways** [comment]
We are using SimpleMessageServiceProvider to disptach events to messaging queue.  SimpleMessageServiceProvider is added to host using AddSimpleMessageStreamProvider.

When grain is initiated this below method gets called dispatches the message, similar to the code snippet nelow 

MethodAsync(params){
           var streamProvider = GetStreamProvider(OrleansStreamConfiguration.SimpleStreamProviderName);
           var stream = streamProvider.GetStream<SomeDto>(this.GetPrimaryKey(), 
                                 OrleansConfiguration.EventDispatchSomeNamespace);
              stream.SubscribeAsync(new SomeDispatcher(_eventStream, _domainMessageEnveloper, _logger));
            )

Can we achieve similar functionality with BroadCastChannel?

**Comment by benjaminpetit** [comment]
> > As @mehmetakbulut mentioned, `BroadcastChannel` and `MemoryStream` are the replacement.
> > `SimpleMessageStreamProvider` didn't had the behavior of a "true" stream provider.
> 
> Is the new `MemoryStream` designed ready for production now (I have read some docs that says it is for development only)? Since the docs linked above says they have the same behavior, what about `BroadcastChannel`?

Yes, it's perfectly fine for production use now. There is a risk that you might lose data if a silo crashes, but you always had this issue with SMS anyway.

> BTW, since the 3rd party stream providers for open source mqs are no longer maintained, and there are in fact only Azure and AWS stream providers available for Orleans 7.0. Would the Orleans team consider to take over some of them?
> 
> Although the docs about impl details might be clear enough for a custom impl, the interface along with its behavior detail is still too complexed for App developers to keep aligned to the latest Orleans.

Testing is the biggest issue. I think orleans-contrib is a better place for these providers.



> We are using SimpleMessageServiceProvider to disptach events to messaging queue. SimpleMessageServiceProvider is added to host using AddSimpleMessageStreamProvider.
> 
> When grain is initiated this below method gets called dispatches the message, similar to the code snippet nelow
> 
> MethodAsync(params){ var streamProvider = GetStreamProvider(OrleansStreamConfiguration.SimpleStreamProviderName); var stream = streamProvider.GetStream(this.GetPrimaryKey(), OrleansConfiguration.EventDispatchSomeNamespace); stream.SubscribeAsync(new SomeDispatcher(_eventStream, _domainMessageEnveloper, _logger)); )
> 
> Can we achieve similar functionality with BroadCastChannel?

You cannot (yet?) use explicit subscriptions for `BroadcastChannel`. For this, use `MemoryStream`.
