### ISSUE TITLE
Serialization and deserialization logic needs some form of NonSerialized attribute

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#835]
Currently there is no way to mark a computed property on Grain State and avoid it's serialization. It can be beneficial for Orleans users to add some equivalent of `NonSerialized` attribute to skip serialization of certain computed fields.
There is a set of cases when developer may need to omit serialization of the computed field e.g.  versioning some parts of the state - DocumentState keeps multiple versions of DocumentMeta and to switch between versions we need to set CurrentVersionId to desired one and computed property Metadata will return proper version details :

``` C#
public class DocumentState :GrainState
{
  public string Id {get;set;}
  public string Name {get;set;}
  public int CurrentVersionId {get;set;}
  public Dictionary<int,DocumentMeta> AllMetadataVersions {get;set;}

  [DontSerializeMe]
  public DocumentMeta CurrentVersionMetadata {get { return AllMetaDataVersions[CurrentVersionId];}}
}
```

NOTE: Can't really use `NonSerialized` attribute as it's defined like 

```C#
[AttributeUsageAttribute(AttributeTargets.Field, Inherited = false)]
[ComVisibleAttribute(true)]
public sealed class NonSerializedAttribute : Attribute
```

and **AttributeTargets.Field** doesn't allow it to be used on properties, only on backing fields.

**Comment by gabikliot** [comment]
@centur , in your example, the property is a non backing property (does not have field any field storing it) and as such (as far as I remember) the standard.NET serializer will not even try to serialize it, even without the ` NonSerialized ` attribute. We, as we are trying to be compatible with the standard.NET serializer should do the same, even not try to serialize. Is not this the case now? If not (and assuming I am correct about the the standard.NET serializer), could you please create a test demonstrating that deviation from the standard.NET serializer. If we indeed deviate, I would consider that a bug.

Are you also asking for backing properties? What is .NET's behavior there? We should again try to follow the same pattern I would say.

**Comment by sergeybykov** [comment]
@centur Can't you turn this property into a method. It seems like it really is a method disguised as a property.

**Comment by centur** [comment]
@gabikliot fair point about non-backing fields. I don't know the answer yet and I need to do the investigation on that. It might be that it's not really serializing it and the problem is just in my head, but before that I need to understand how to properly deserialize the data stored in blob storage (or implement my own serializer to JSON and plug it in). If there is an easy way to take a row from blob storage and restore an object from it, without using orleans runtime - can you give me some starting point for this?

@sergeybykov yes, I can, but it's really a computed property. AFAIK internal implementation of the property will be anyway converted to a pair of getXXX \ setXXX methods. So properties are methods in disguise, but this doesn't mean I want to give up simplicity of property (and computed-property) semantic.

**Comment by gabikliot** [comment]
@centur , regarding Blob and Json: you can take a look in [`OrleansBlobStorageProvider`](https://github.com/OrleansContrib/OrleansBlobStorageProvider/blob/master/Orleans.StorageProvider.Blob/BlobStorageProvider.cs ), created by @richorama . You may be bale to reuse the of how he configures Json serializer and accesses Blobs.

**Comment by gabikliot** [comment]
@centur , looks like we can close that issue, right?

**Comment by centur** [comment]
Ok, lets close it as it feels that I struggling to find time and check it. I''ll reopen it in case I manage to confirm the issue exists. Thanks for the directions on serializer example
