### ISSUE TITLE
Is there any way to manually create a transaction?

### ISSUE THREAD

**Issue by gufigueiredo** [dotnet/orleans#8351]
I've a grain that have several methods marked with a `[Transaction] `attribute. All the state is controlled via `ITransactionalState<T>`.

However, now I need to build a function that runs every X minutes via a Timer, which needs to manipulate the state. When the timer is triggered, I get an `OrleansTransactionException`, saying that there is no active transaction. 

How to solve this without having to create 2 distinct states?

**Comment by ReubenBond** [comment]
Hi @gufigueiredo, you can create a transaction using `ITransactionClient` (which can be injected), which is mentioned here: https://learn.microsoft.com/en-us/dotnet/orleans/migration-guide#transaction-client

An alternative is to have a `Create`/`CreateOrJoin` transaction method which you call from your timer.
