### ISSUE TITLE
Stream FilterData is not saved to the AzureTableStorage when using JsonFormat

### ISSUE THREAD

**Issue by mhertis** [dotnet/orleans#836]
I filter stream items by item type, therefore my FilterData is a `List<Type>` with item types. 

If I use AzureTableStorage with JsonFormat enabled FilterData is null.

```"FilterWrapper": {
          "$type": "Orleans.Streams.OrFilter, Orleans",
          "FilterData": null
        },
        "Filter": {
          "$type": "Orleans.Streams.OrFilter, Orleans",
          "FilterData": null
        }```

When an item should be delivered I get a nre in `OrFilter.ShouldReceive` https://github.com/dotnet/orleans/blob/master/src/Orleans/Streams/Predicates/OrFilter.cs#L74

It seems to work if I don`t use JsonFormat.

**Comment by gabikliot** [comment]
What lines exactly fails with nre?
Json serializer has some very strict rules and restriction on what fields/properties have to be public (it will not serialize private fields). So it is totally possible that some fields inside `OrFilter` have to be made public. 
Can you reproduce this error with a standalone test, without the streaming just instantiating the filter object and trying it with json serializer configured like now in Orleans ([here](https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Providers/Storage/AzureTableStorage.cs#L129)). That would help find out the offending field and make it public.

**Comment by jthelin** [comment]
FYI, PR #937 is trying to add into GitHub the stream filtering test cases we have internally, so that new test case(s) can be added to explore this issue, but that PR is currently hitting some problems with Jenkins build so isn't ready for merge yet. :(
