### ISSUE TITLE
RandomTimeSpan can use Random.NextInt64()

### ISSUE THREAD

**Issue by henricj** [dotnet/orleans#8381]
As of .NET 6, `RandomTimeSpan` can use `.NextInt64()` instead of `.NextDouble()`.  For example,
```C#
   return TimeSpan.FromTicks(Random.Shared.NextInt64(timeSpan.Ticks));
```
instead of,
https://github.com/dotnet/orleans/blob/5ea07d68e892c4cb9c81c64555092663a61cf0dc/src/Orleans.Core/Utils/RandomTimeSpan.cs#L13

**Comment by ReubenBond** [comment]
Sounds good to me. Please feel free to open a PR
