### ISSUE TITLE
Documentation AdoNet Sql Scripts

### ISSUE THREAD

**Issue by kylejuliandev** [dotnet/orleans#8403]
Embedded links in the XML comments refer to a page that no longer exists (http://aka.ms/orleans-sql-scripts)

https://github.com/dotnet/orleans/blob/01475f531c27c1c1fa7bc6f20827ffc8a50e5636/src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/AdoNetGrainStorageServiceCollectionExtensions.cs#L23

https://github.com/dotnet/orleans/blob/01475f531c27c1c1fa7bc6f20827ffc8a50e5636/src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/AdoNetGrainStorageServiceCollectionExtensions.cs#L34

https://github.com/dotnet/orleans/blob/01475f531c27c1c1fa7bc6f20827ffc8a50e5636/src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/AdoNetGrainStorageServiceCollectionExtensions.cs#L45

https://github.com/dotnet/orleans/blob/01475f531c27c1c1fa7bc6f20827ffc8a50e5636/src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/AdoNetGrainStorageServiceCollectionExtensions.cs#L56

I believe the new location is: https://learn.microsoft.com/en-gb/dotnet/orleans/host/configuration-guide/adonet-configuration

**Comment by bradygaster** [comment]
I've updated the AKA link - can you check this again to make sure the experience is repaired and if so, close the issue? Thanks so much!

**Comment by kylejuliandev** [comment]
Awesome! They appear to be working now, thank you!
