### ISSUE TITLE
OnDeactivateAsync is called without grain context resulting in access violation

### ISSUE THREAD

**Issue by mehmetakbulut** [dotnet/orleans#8404]
**Description:**
Interacting with persistent state causes an access violation if the grain deactivates following a DeactivateOnIdle() call inside a timer which has called a grain method via non-reentrancy workaround from #2574. 

**Environment:**
Issues seems to be introduced in Orleans 7.x as it wasn't present in 3.x.

**Steps to reproduce:** 
1. Write a grain with a persistent state.
2. Register a timer with this grain.
3. Call a grain method from timer callback using `await Task.Run(() => this.AsReference<IMyGrain>().MyMethod())` pattern.
4. Call `DeactiveOnIdle()` inside timer.
5. Have `OnDeactivateAsync()` interact with persistent state. (e.g. access `persistent_state.State`)
6. Activate grain / cause timer to execute.

See example repo https://github.com/mehmetakbulut/OrleansAccessViolationDemo

**Expected result:**
Grain deactivates normally.

**Actual result:**
```
fail: Orleans.Grain[100516]
      Error calling grain's OnDeactivateAsync(...) method - Grain type = Demo.MyGrain Activation = [Activation: S127.0.0.1:11111:41218990/my/dab8a3d360654eb791414946dddade41@a208e821061c40f4b81c5dde14dc3ef1#GrainType=Demo.MyGrain,Demo Placement=RandomPlacement State=Deactivating]
      System.InvalidOperationException: Activation access violation. A non-activation thread attempted to access activation services.
         at Orleans.Runtime.GrainRuntime.<CheckRuntimeContext>g__ThrowMissingContext|20_0() in /_/src/Orleans.Runtime/Core/GrainRuntime.cs:line 93
         at Orleans.Runtime.GrainRuntime.CheckRuntimeContext(IGrainContext context) in /_/src/Orleans.Runtime/Core/GrainRuntime.cs:line 92
         at Orleans.Core.StateStorageBridge`1.set_State(TState value) in /_/src/Orleans.Runtime/Storage/StateStorageBridge.cs:line 35
         at Orleans.Runtime.PersistentStateFactory.PersistentStateBridge`1.set_State(TState value) in /_/src/Orleans.Runtime/Facet/Persistent/PersistentStateStorageFactory.cs:line 74
         at Demo.MyGrain.OnDeactivateAsync(DeactivationReason reason, CancellationToken cancellationToken) in OrleansAccessViolationDemo\OrleansAccessViolationDemo\Demo\MyGrain.cs:line 23
         at Orleans.Runtime.ActivationData.<FinishDeactivating>g__CallGrainDeactivate|135_0(CancellationToken ct) in /_/src/Orleans.Runtime/Catalog/ActivationData.cs:line 1456
         
```

**Debugging:**
- If timer calls grain method with `await Task.Run(...).ConfigureAwait(false)`, then the access violation does not happen.
- Calling `DeactiveOnIdle()` via a proxy (e.g. another `Task.Run` pattern where a grain method does the actual call) does not change outcome.
- When `OnDeactiveAsync(...)` is called after the problematic pattern,  `RuntimeContext.Current` will have been set to null thus resulting access violation.

**Comment by mehmetakbulut** [comment]
Seems similar to #8339, could be same root cause.

**Comment by ReubenBond** [comment]
Is there a reason you're not awaiting the WriteStateAsync() call?

**Comment by mehmetakbulut** [comment]
Unintentional, I must have dropped it while putting the example together. 😄 
Updated the repo, you can see that the issue remains.

**Comment by mehmetakbulut** [comment]
Did a bit more digging. Here are the different scenarios I have tested so far.

|#|Scenario|Access Violation|
|-|-|-|
|1|No `await Task.Run(...Noop());` inside timer,<br> `DeactivateOnIdle()` inside timer|No|
|2|`await Task.Run(() => this.AsReference<IMyGrain>().Noop());` inside timer,<br> `DeactivateOnIdle()` inside timer|Yes|
|3|`await Task.Run(() => this.AsReference<IMyGrain>().Noop()).ConfigureAwait(false);` inside timer,<br> `DeactivateOnIdle()` inside timer|No|
|3|`await Task.Run(...Noop());` inside timer,<br> `await Task.Run(() => this.AsReference<IMyGrain>().DeactiveViaGrainCall());` inside timer|Yes|
|4|`await Task.Run(...Noop());` inside timer,<br> `clusterClient.GetGrain<IMyGrain>(...).DeactiveViaGrainCall();` from outside|No|
|5|`await Task.Run(...Noop());` inside timer,<br> `DeactivateOnIdle()` inside timer but on next iteration instead|No|
|6|`await Task.Run(...Noop());` inside timer,<br> `await Task.Run(() => DeactivateOnIdle());` inside timer|No|

I'm a bit surprised that 3 results in access violation but not 6.

During these tests, I have attached a debugger and checked to make sure `DeactivateOnIdle()` was eventually getting called at the intended call site.

I also checked what was happening with `RuntimeContext.Current`. For example, I expected that it would be null inside timer right after `await Task.Run(...Noop());` returns but that was not the case. I can't seem to find what state is altered that eventually yields in the context being set to null prior to executing `OnDeactivateAsync(...)`. Or at least I am not sure where to look into?

@ReubenBond I'm happy to spend some more time on this if you have some pointers. At the very least though, it seems `await Task.Run(() => DeactivateOnIdle());` can be a hacky workaround.

**Comment by ReubenBond** [comment]
I believe the specific fix for this was https://github.com/dotnet/orleans/pull/8864, but there were many other fixes in this area regarding grain timers in [v8.2.0](https://github.com/dotnet/orleans/releases/tag/v8.2.0)
