### ISSUE TITLE
[Could not find an implementation for interface] When I try to debug simple sample with source code

### ISSUE THREAD

**Issue by Arthur-Lee** [dotnet/orleans#8414]
1. First clone the source code.
2. Add HelloWorld project from https://github.com/dotnet/samples/tree/main/orleans/HelloWorld into samples folder
3. Change the NuGet dependency to project dependency

However I got the exception:
![image](https://user-images.githubusercontent.com/9337816/235300230-ac256724-dc55-4423-97bf-1fb929f533dc.png)

The project file will be:
![image](https://user-images.githubusercontent.com/9337816/235300261-54b29cc5-e128-4d3d-84ec-4f9a168501ca.png)

**Comment by ReubenBond** [comment]
When you're referencing Orleans from source (i.e, within the Orleans repo), you need to add a project property to your project to enable codegen, which is what is missing in this case. Add this property to your project and it should :

``` xml
<OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
```

**Comment by Arthur-Lee** [comment]
That work

> When you're referencing Orleans from source (i.e, within the Orleans repo), you need to add a project property to your project to enable codegen, which is what is missing in this case. Add this property to your project and it should work:
> 
> ```
> <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
> ```
> 
> If it doesn't, that may be because your project is not in a folder which the relevant Directory.Build.targets file applies to: https://github.com/dotnet/orleans/blob/main/Directory.Build.targets

That works like magic. I have tried another ChatRoom example, It will work fine if I add the same property. However the error is not like the first one:
![image](https://user-images.githubusercontent.com/9337816/235314061-6783aa47-a61a-42fd-84e8-90d303125788.png)

Can you elaborate a little what does the property function in High level?

**Comment by ReubenBond** [comment]
The property I mentioned ensures that your project has a reference to the code generator so that it can generate source code corresponding to your grain classes, interfaces, and data types. You can see what it does exactly by looking at the file I linked.

The exception you're seeing now seems to be different. I think one or more of the projects are missing that property

**Comment by Arthur-Lee** [comment]
> The property I mentioned ensures that your project has a reference to the code generator so that it can generate source code corresponding to your grain classes, interfaces, and data types. You can see what it does exactly by looking at the file I linked.
> 
> The exception you're seeing now seems to be different. I think one or more of the projects are missing that property

After adding the same property in ChatRoom.Client and ChatRoom.Service, the client and server project can be executed normally.

**Comment by ReubenBond** [comment]
Glad to hear it!
