### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by bill-poole** [dotnet/orleans#8433]
The XML comment for the `NumVotesForDeathDeclaration` setting in `ClusterMembershipOptions` says it "should be at most `NumMissedProbesLimit`". However, I would have thought that it should be at most `NumProbedSilos`, not `NumMissedProbesLimit`.

That is, it makes sense that the number of votes needed to declare a silo dead cannot exceed the number of silos probing each silo in the cluster, but I wouldn't have thought it would matter how many missed probes it would take for any one silo to suspect another silo is dead.

Have I misunderstood something?

**Comment by ReubenBond** [comment]
You have not misunderstood, thank you for pointing that out. Would you be willing to submit a PR to fix the doc comment?

**Comment by ReubenBond** [comment]
Much appreciated!
