### ISSUE TITLE
Bug in DeserializationContext about deserializing cyclic data structures

### ISSUE THREAD

**Issue by gabikliot** [dotnet/orleans#852]
Issue #843 exposed 2 bugs in the serializer related to cyclic data structures (data structure that has a cycle of references).
The first, minor bug, was related to capturing the right offset during serialization of cyclic data structures. It has been fixed in #851.
The 2nd bug is related to Deserialization.
Currently, when we deserialize an object, we first call its generated deserialization method, which will create an empty object and then recursively call deserialization on its member fields and assign them to the object fields. Only after the object was fully deserialized and created, do we put it in the [`DeserializationContext`](https://github.com/dotnet/orleans/blob/master/src/Orleans/Serialization/DeserializationContext.cs#L54). This works if the same object is referenced multiple times from the same parent object (not within a cycle), since when we encounter the same object reference again, it will be found in the [`DeserializationContext`](https://github.com/dotnet/orleans/blob/master/src/Orleans/Serialization/DeserializationContext.cs#L60).

However, it does not work for cyclic objects, since when we encounter a 2nd reference to the same object, the parent object (the first reference to that object in the cycle) was not fully deserialized yet (we are currently deserializing it). As a result, it was not put yet in the `DeserializationContext` and thus cannot be found by the 2nd reference.

The suggested fix is to change the order of deserialization and storing of the object in the `DeserializationContext`. We should first allocate a new empty object, then store a reference to it in the `DeserializationContext` and only then recursively call deserialization on its fields. When storing in the `DeserializationContext` we should store at the `var start = stream.CurrentPosition;` offset like done now [here](https://github.com/dotnet/orleans/blob/master/src/Orleans/Serialization/SerializationManager.cs#L1309). The call to `DeserializationContext.Current.RecordObject` will be removed from [`SerializationManager`](https://github.com/dotnet/orleans/blob/master/src/Orleans/Serialization/SerializationManager.cs#L1309) and instead moved into the generated serialization code, right after the un-initialized object is created.

**Comment by ReubenBond** [comment]
@gabikliot I can help to fix this, I just need to better understand the fix.
Currently `DeserializationContext` is internal, should we make it public?
We will then change the generated deserialization code to something like this:
```C#
public static global::System.Object Deserializer(global::System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
{
    MyObserverSubscriptionManager<T> result = new MyObserverSubscriptionManager<T>();
// This bit is new
    DeserializationContext.Current.RecordObject(stream.CurrentPosition, result);
    result.@Foo = (int)SerializationManager.@DeserializeInner(typeof (int), stream);
    field1.@SetValue(result, (HashSet<T>)SerializationManager.@DeserializeInner(typeof (HashSet<T>), stream));
    return result;
}
```
In `SerializationManager.DeserializeInner` we will remove the last call to `RecordObject`, the call from this part:
```C#
var deser = GetDeserializer(resultType);
if (deser != null)
{
    result = deser(resultType, stream);
    DeserializationContext.Current.RecordObject(start, result);
    return result;
}
```
Does that sound right?

**Comment by ReubenBond** [comment]
I implemented this change, but it fails for the built-in deserializers. It seems cumbersome to follow all non-generated calls to `DeserializeInner` with `RecordObject`. It is benign to leave the call to `RecordObject` in `DeserializeInner`, so I am rerunning tests with that in place.

**Comment by gabikliot** [comment]
Your first comment above looks correct. That is more or less what I meant. Of course, compiled with eyes, so can't be 100% sure.

Not sure about your later comment on built in deserializers. You don't want to store the same object twice in the deser context.
