### ISSUE TITLE
Orleans serializer code-fix questions

### ISSUE THREAD

**Issue by yoDon** [dotnet/orleans#8523]
**Context:**
The [Orleans 7 Serializer Docs](https://learn.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/serialization?pivots=orleans-7-0) mention "the included code-fix" as a way to add Orleans.IdAttributes but doesn't indicate what that code-fix is included with. 

I'm running on an M2 Mac with both Visual Studio Mac and JetBrains Rider.

**Questions/Issues:**

1) I have been able to get the code-fix to run, but it seems unreliable. Is there some way to force it to load or validate that it has loaded?

I've seen and used the code-fix hints in Visual Studio Mac but having closed VS and relaunched I'm now unable to get the code-fix to show on new or pre-existing classes in assemblies where I had previously used the code-fix (including classes with and without `[Id]` attributes inside the `[GenerateSerializer]` tagged class). 

I've never been able to get the code-fix hints to show in JetBrains Rider (my primary IDE on Macs, based on Roslyn, runs a wide range of code fixes).

2) Does the Orleans serializer system support record typed properties in serialized classes? I've never gotten the Id's code-fix to show in such cases, but I don't know if that's an issue with the code-fix, the class, or the serializer.

```csharp
[GenerateSerializer]
public class Example
{
    public record SampleGreeting(string Message, DateTimeOffset Timestamp);
}
```

The discussion of records in the [Orleans 7 Serializer Docs](https://learn.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/serialization?pivots=orleans-7-0) just talks about applying the `[GenerateSerializer]` attribute to record types themselves, not to classes containing them.

3) Is there a way to automatically apply the Apply Id's code-fix to all [GenerateSerializer] tagged classes in a project? Anyone porting a real project from Orleans 3.x to Orleans 7 or moving an existing non-Orleans project to Orleans is going to encounter a large number of data classes that need to be marked up, and at present there seems to be no way to get the compiler to help detect classes that are missing [Id] tags (see #8521 and #8522).

**Comment by luckyycode** [comment]
Agreed with 3), having a very large code base with over 1000 of classes and still can't migrate to Orleans 7 right now because of this

**Comment by ReubenBond** [comment]
1. I have not encountered reliability issues, but if you do, please report them. Perhaps it's a VS-for-Mac issue?
2. records are supported. The GenerateSerializer attr needs to go on the record class, not the class which contains it
3. This should work. The IPersistentState issue is complex because we cannot determine statically whether a type is going to be serializable at runtime, eg because you may have a custom serializer like JSON

**Comment by yoDon** [comment]
@ReubenBond could you say more on what you mean by "3 should work"?

Both @luckyycode and I were hoping to find a way to do this to big legacy projects with hundreds or thousands of classes, and couldn't.

**Comment by ReubenBond** [comment]
> Is there a way to automatically apply the Apply Id's code-fix to all [GenerateSerializer] tagged classes in a project? 

This should work already (you can apply the code fix to all instances in a solution:

![image](https://github.com/dotnet/orleans/assets/203839/89058d6d-810a-4306-bea8-254ba22ee25a)


>  at present there seems to be no way to get the compiler to help detect classes that are missing [Id] tags

This does not and is a good suggestion.

**Comment by ReubenBond** [comment]
@nkosi23 code fixes and analyzers are a Roslyn feature and they're language specific. I don't think thet can be made to work on F# and I'm not sure what the F# equivalent is.

**Comment by ReubenBond** [comment]
I'll close this now, since the original issue is fixed: you can increase the severity of the Id analyzer to error to catch missing Id attributes.
