### ISSUE TITLE
Question - What happen when a stream producer fails?

### ISSUE THREAD

**Issue by mbernard** [dotnet/orleans#854]
Question

I have a scenario where a need to return a lot of results ~10,000 and fetching them could be long. Long enough to exceed the request timeout. I was thinking on leveraging the Orleans Streams to achieve this and avoid time outs. Delegating the load to another grain which I will not wait on, and that will stream back the results.

If I'm in a at-least-one delivery scenario.
What happen if the producer of the stream results fails? Will the producer be reactivated? and will it re-execute the `LoadRawData` or will the message be lost forever and I will receive no more results in my `MyGrain`?

Also, if you have any better solution so handle this kind of scenario, I'm open to suggestions :D

this is a simple example of what it could look like

```
public class MyGrain : IGrain
{
	public Task LoadStuff()
	{
		var pg = GrainFactory.GetGrain<ProducerGrain>("foo");

		// Subscribe on stream X (streamHandleX)
		// ...

		// Don't wait on the return as this is a long running operation that will result in a time out
		pg.LoadRawData();
	}

	public Task OnNext(object item)
	{
		// Save result in state
	}

	public Task OnCompleted()
	{
		// Set load as completed
	}
}

public class ProducerGrain : IGrain
{
	public async Task LoadRawData()
	{
		// This is a potentially long operation
		// ...
		// Get stream handle and stream each result as they come in
		foreach(var result in results)
		{
			await streamHandleX.OnNext(result);
		}

		await streamHandleX.OnCompleted();
	}
}

```

**Comment by gabikliot** [comment]
If a `ProducerGrain` fails in the middle, it will not be recreated by itself. You need someone to send it a new message to reactivate it. The options are:

1) Make `MyGrain` watch the production process and keep periodically pocking the producer. So for example,  `MyGrain` will create a timer (not a reminder) that will periodically check when was the last OnNext called and it looks like  producer was idle for some time, just pick it, also telling him - hei, I got X chunks (this part of the data), where is the rest? The not failed producer will ignore, while the failed producer will be reactivated and can restart from the latest point.

2) Use reminder. `ProducerGrain` will subscribe to a reminder that will tick periodically. Once all data was produced, it can unregister the reminder. In that solution, producer will need to remember by itself how much it already produced, so it does not start from the beginning (unless you don't care to resend all). He will need to store this reliably in storage.

**Comment by mbernard** [comment]
Thank you, very usefull information.
I was thinking about writer a "watcher" anyway, good to know that I'm in the right direction
