### ISSUE TITLE
Multi Tenant DI Orleans7

### ISSUE THREAD

**Issue by stephenlautier** [dotnet/orleans#8549]
We are trying to migrate to Orleans7, however one of the issues we are having is to migrate the tenancy which was implemented based on this discussion https://github.com/dotnet/orleans/issues/4580

However now `DefaultGrainActivator` along with some of its dependencies (such as `ConstructorArgumentFactory.ArgumentFactory`) are all set to internal which we cannot extend. Is there any other way of doing this?

Basically we have something like this (shortened)

```cs
public class TenantGrainActivator : DefaultGrainActivator
{
	private readonly ITenantResolver _tenantResolver;

	public TenantGrainActivator(
		IServiceProvider serviceProvider,
		ITenantResolver tenantResolver,
	) : base(serviceProvider)
	{
		_tenantResolver = tenantResolver;
	}

	public override object Create(IGrainActivationContext context)
	{
		if (context.GrainIdentity.PrimaryKeyString == null)
			return base.Create(context);

		var scope = context.ActivationServices.GetRequiredService<IExportLocatorScope>();
		var tenant = _tenantResolver.ResolveByPrimaryKey(context.GrainIdentity.PrimaryKeyString);

		scope.SetTenantContext(tenant);

		return base.Create(context);
	}
}
```

Any help would be appreciated. Thanks

**Comment by ReubenBond** [comment]
Great feedback. I've opened #8550 to rectify this. It includes a slight refactor to clean things up for exposure.

**Comment by stephenlautier** [comment]
Thanks! @ReubenBond 

> Great feedback. I've opened #8550 to rectify this. It includes a slight refactor to clean things up for exposure.
