### ISSUE TITLE
Question: Stream message Exception

### ISSUE THREAD

**Issue by turowicz** [dotnet/orleans#8556]
What happens when an OnNext is triggering an exception. Will the message be retried? If yes then how many times? Is it configurable? 

I have observed during my custom stream provider implementations ([1](https://github.com/Surveily/Orleans.Streaming.Grains), [2](https://github.com/Surveily/Orleans.Streaming.NATS)) that when I throw an unhandled exception in OnNext it will be retried multiple times after which it won't. I would like to be able to manipulate this behaviour for my custom streaming provider so it puts it back on the queue on error or retries infinitely one-by-one.

Can you show me how?

cc @ReubenBond @benjaminpetit

**Comment by benjaminpetit** [comment]
Look at this method: https://github.com/dotnet/orleans/blob/964ed094a5f77b3181c330a0cf33c58e19b48b85/src/Orleans.Streaming/PersistentStreams/PersistentStreamPullingAgent.cs#L574

By default, the pulling agent will try to retry for 1 minute before giving up. If it failed after this period, the failure will be handled by the configured `IStreamFailureHandler`.

**Comment by turowicz** [comment]
Thanks!
