### ISSUE TITLE
Unexpected leakage in Orleans 3.x

### ISSUE THREAD

**Issue by qiu-lijie-fro** [dotnet/orleans#8569]
In our system using .Net 6 Orleans 3.6.5, we have found an unexpected memory leak seemingly coming from Orleans.

I have produced a minimal demo of this issue [here](https://github.com/qiu-lijie-fro/OrleansLeakDemo). It is a simply a root grain calling a bunch of worker grains that does no actual work repeatedly. Neither grain allocate any resources besides that. And running under memory profiling you can see a continuous memory growth. 
![image](https://github.com/dotnet/orleans/assets/141737170/b6dae3fd-025b-492e-b77e-3492320ad52b)

Please note that the ForemanGrain intentionally does not await the call to `StartWorker()`. In our system, we have some lifecycle sidecar grains waking on up on reminder/timer to trigger the root grain to do work, but it is likely irrelevant here so it is left out.

Any insight you can provide would be greatly appreciated!

**Comment by SebastianStehle** [comment]
if you have the snapshots, why do you not analyze them?

**Comment by qiu-lijie-fro** [comment]
We did, spent quite a bit of time on this actually before resorting to this. 

In our live system, the leak seems to stem from were a grain sends a HTTP request. However, after some investigation, even if we does not do the request and simply wait on `Task.Delay(0)`, the leak still persist.

**Comment by ReubenBond** [comment]
Did the analysis reveal which objects were leaking?

**Comment by ReubenBond** [comment]
This doesn't seem correct to me. Are you sure these are leaking and they're not pending calls which are never being completed? If you look at these objects in a memory dump, what state are they in? Are they completed or still pending? What is your response timeout set to?

**Comment by qiu-lijie-fro** [comment]
Since we have been upgrading to 7.x these past weeks, don't see the point of looking into 3.x issue if they don't persist. Will close this ticket for now and reopen if we find the issue in 7.x
