### ISSUE TITLE
can't obtain IConfiguration while implementing Orleans.TestingHost.ISiloConfigurator

### ISSUE THREAD

**Issue by DunetsNM** [dotnet/orleans#8575]
As per subject,  I'm implementing Orleans.TestingHost.ISiloConfigurator in Orleans 7 and can't see a way to obtain `IConfiguration` inside of it.  

```
public interface ISiloConfigurator
    {
        void Configure(ISiloBuilder siloBuilder);
    }
```

In `IHostConfigurator.Configure`  I can obtain `IConfiguration` from the passed `IHostBuilder` ,  but nothing like that in `ISiloConfigurator.Configure`,  are there any technical/design limitations that I don't see?

A bit more context which might be relevant:  I need to pass instance of `IConfiguration` further down  to  `ISiloBuilder.ConfigureLogging` . In Orleans 3.x it wasn't a problem because there was an overload of  `ConfigureLogging` with second `context` parameter that has the `IConfiguration` in it,   this overload is now gone too.

**Comment by DunetsNM** [comment]
I also tried to inject  `IConfiguration` into constructor of my class that implements `ISiloConfigurator` however   `TestClusterBuilder.AddSiloBuilderConfigurator` requires a class with default constructor

**Comment by ReubenBond** [comment]
Use IHostConfigurator instead. You can then call UseOrleans from within it
