### ISSUE TITLE
Orleans Framework Monitoring & Tracing using OpenTelemetry

### ISSUE THREAD

**Issue by panosxro** [dotnet/orleans#8600]
Hello team! I am relatively new to Orleans framework concepts when it comes to monitoring & tracing, using OpenTelemetry and I would like to learn some more technical details, for an internal project that we are undertaking in our organization. In particular:

1. If we want to use OpenTelemetry standard to collect metrics, traces, logs etc. from Orleans framework, used for several internal .NET applications, which are some important metrics of Orleans to focus our attention for capturing? 
2. Which are some key information/ concepts/ methods/ classes to be collected by applications developed in Orleans? 
3. What information/ data/ metrics etc. does the Orleans framework allow us to collect with tracing from OpenTelemetry?
4. For the tracing part, how much "deep-dive development" is need to collect all traces & transactions? 
5. The level of granularity in tracing capture in OpenTelemetry is it determined by the specific code implementation with OpenTelemetry?  Ideally we want to collect all traces, even with a 1-second granularity precision. 
6. Can we understand the underlying topology of our infrastructure & servers by collecting OpenTelemetry data?
7. How deep can we reach with OpenTelemtry when it comes to logs collection?
Many many thanks in advance for all your help & support! It's really appreciated!

**Comment by ReubenBond** [comment]
Hi, apologies for the slow response. We have some documentation on [Observability in Orleans here](https://learn.microsoft.com/en-us/dotnet/orleans/host/monitoring/), which includes a list of counters with descriptions for most. I hope that answers your questions. Some of your questions seem related to Open Telemetry more generally and aren't Orleans-specific. In short, Orleans uses the standard .NET mechanisms for [Logging](https://learn.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line), [Tracing](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing), and [Metrics](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics) and integration with [Open Telemetry](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/observability-with-otel)
