### ISSUE TITLE
Running a reminder once - disable periodic run

### ISSUE THREAD

**Issue by SoucianceEqdamRashti** [dotnet/orleans#8616]
Hello,

In SF actors reminders, you could give the value of -1 to the parameter "period" so that would disable periodic runs.

Is there something similar in Orleans?

My use case is that I just want a reminder to run once. I know I can unregister it after its run but it would be good to able to disable periodic runs as well. Thanks.

**Comment by ReubenBond** [comment]
This is something we're working on. Orleans doesn't have this behavior today because reminders can be missed if the cluster if offline or due to some transient errors (eg, network errors, crashes), etc, so the period is used to ensure that they are fired at least once, when the system is available.

**Comment by SoucianceEqdamRashti** [comment]
Thanks for your reply @ReubenBond. I'll close this then.
