### ISSUE TITLE
Silo shutdown callback for providers

### ISSUE THREAD

**Issue by randa1** [dotnet/orleans#862]
Currently there is no callback that can be implemented that will be executed at Silo shutdown, in order to cleanup external state and resources (for example - releasing a external event bus consumer).

This can be solved by re-adding the `Close` method to `IProvider`, and calling it when the silo shutdown is in progress. It will allow implementing it in a bootstrap provider (hence satisfying the above demand), or in any other provider that needs to gracefully shut down (stream providers come to mind).

What do you think?

**Comment by gabikliot** [comment]
Addressed via #863.

**Comment by randa1** [comment]
Thank you for the quick fix.
