### ISSUE TITLE
Testcluster does not return previously instantiated grain

### ISSUE THREAD

**Issue by SoucianceEqdamRashti** [dotnet/orleans#8621]
Hello,

I am writing a test where grain one calls grain two. Grain two's state is changed and written. The test checks to see if the state of grain two is what is expected.

The problem is that no matter how I try the grain state returned is always the default one and not not the state of the instantiated one.
This is my SiloConfiguration.
` public void Configure(ISiloBuilder siloBuilder)
    {
        siloBuilder.UseLocalhostClustering()
                .AddMemoryGrainStorage("automationcenter_grains");
        siloBuilder.UseInMemoryReminderService();
        siloBuilder.Configure<OrleansOptions>(options =>
        {
            options.ReminderAmountToWaitBeforeFirstRun = 1;
            options.ReminderRunDuration = 5000;
        });
    }`

In my test code this is the gist of it:
`var imeiGrain = GetTestCluster().GrainFactory.GetGrain<IImeiTriggerCondition>(triggerConditionContract.EntityId.ToString());
        await imeiGrain.AddOrUpdateTriggerConditionAsync(triggerConditionContract);
        await imeiGrain.TriggerImeiTriggerConditionAsync(triggerValues);
        var cooldownGrainId = string.Concat(triggerConditionContract.EntityId.ToString(), "_COOLDOWN");
        var cooldownGrain = GetTestCluster().GrainFactory.GetGrain<ICooldown>(cooldownGrainId);`

Inside the TriggerIemiTriggerConditionAsync it creates a new cooldown grain with the grain id being equal to the value of cooldownGrainId.

However when i try to get the grain with the same id it returns a grain with the default state. Have I configured something wrong?

**Comment by SoucianceEqdamRashti** [comment]
I have tried my best to investigate but it really is strange. Essentially Grain A creates Grain B. Grain B starts a reminder.
Then in my test I call the test cluster with the grain id for Grain B and try to get the state and the reminder name. The state is just the default and the reminder is null. It all seems like calling GetGrain creates the grain a new rather than retrieving the existing grain with the same id. This is for writing tests mind. If there is any way to get direct help via chat or something, it would be awesome.

**Comment by ReubenBond** [comment]
The problem is most likely the call to UseLocalhostClustering. TestCluster configures clustering for you already, so that multiple silos and a client can all communicate. UseLocalhostClustering overrides that and creates two independent silos (not talking to each other) with a client that is configured to talk to both of them

**Comment by SoucianceEqdamRashti** [comment]
@ReubenBond , that was exactly the issue. Man thanks a lot, if you ever drop by to southern Sweden remind me to buy a beer!
