### ISSUE TITLE
TestSilo: Add Configure overload with HostContext param into ISiloConfigurator

### ISSUE THREAD

**Issue by spingee** [dotnet/orleans#8627]
Hello
It would be nice to have IConfiguration available in TestingHost ISiloConfigurator. 
We have heavy class with lot of service configurations and we would like to reuse it in more then one Fixture, and we would like to change behavior based on standard IConfiguration values. 
But there is only this method: void Configure(ISiloBuilder siloBuilder);

By looking into source code TestClustHostFactory:176 i can see:
`hostBuilder.UseOrleans((ctx, siloBuilder) => (configurator as ISiloConfigurator)?.Configure(siloBuilder));`

Why not pass ctx too? Or just IConfiguration property.

**Comment by ReubenBond** [comment]
You can implement `IHostConfigurator` instead and call `UseOrleans` on it yourself, if you'd like.

Alternatively, what you are suggesting could be implemented, but we would need to maintain the existing signature for compatibility, so implementing it as an optional method (i.e, with a default implementation) on the interface would be preferable. A PR for this would be welcome

**Comment by spingee** [comment]
Tried IHostConfigurator and looks good for me, Thanks
