### ISSUE TITLE
Registering a non-DHT GrainDirectory as default does not actually cause that GrainDirectory to get used.

### ISSUE THREAD

**Issue by bangfalse** [dotnet/orleans#8632]
I was attempting to use the `UseRedisGrainDirectoryAsDefault` hosting extension provided in `RedisGrainDirectoryExtensions`, and discovered that while a `RedisGrainDirectory` class was being constructed, it was not being used, and no information was being persisted to Redis.

I've dug down, and I think the problem is in this method in `GrainLocatorResolver`:

```c#
        public IGrainLocator GetGrainLocatorInternal(GrainType grainType)
        {
            IGrainLocator result;
            if (grainType.IsClient())
            {
                result = this._clientGrainLocator ??= _servicesProvider.GetRequiredService<ClientGrainLocator>();
            }
            else if (this.grainDirectoryResolver.HasNonDefaultDirectory(grainType))
            {
                result = this.cachedGrainLocator;
            }
            else
            {
                result = this.dhtGrainLocator;
            }

            return result;
        }
```
 
```c#
public bool HasNonDefaultDirectory(GrainType grainType) => !ReferenceEquals(Resolve(grainType), this.DefaultGrainDirectory);
```

Specifically, the check `HasNonDefaultDirectory` appears to not actually check the _implementation_ of the default grain directory, just whether or not you're using the default, and if you're using the default, assumes you want to use the DHT instead of whatever grain directory you've actually configured? 

If this sounds like a correct diagnosis, I can try to prepare a Pull Request for this, I'm just not sure how many testing additions/changes it will need.

**Comment by NimaAra** [comment]
We are also experiencing this regression. @bangfalse Did you manage to raise a PR for this? 

@ReubenBond Using the Redis grain directory as default is now broken after migrating from v3 to v7. Decorating the grain individually works but this is a problem for us as we have many grains some of which we don't own.
