### ISSUE TITLE
Silo shutdown guarantees

### ISSUE THREAD

**Issue by verdie-g** [dotnet/orleans#8637]
I understand from https://learn.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/shutting-down-orleans that there is a concept of graceful shutdown but what does it exactly do? I'm wondering if it processes all enqueued RPCs and deactivate all the grains. Does its grain become unavailable during the shutdown?

**Comment by benjaminpetit** [comment]
The graceful shutdown basically try to ensure that all silos (and connected clients) are notified that the silo is shutting down, so they should not try to place new activations, and take some decision regarding the distributed grain directory for example.

The grain activations that are on the silo that is shutting down will stop processing requests, but the silo will still receive them and add it to a local queue. The silo will then forward the pending request to another silo. The silo that is shutting down should be forwarding all requests taht come during shutdown. So no, in the ideal case, the grain will not be unavailable during silo shutdown
