### ISSUE TITLE
Is there an offline mode supported?

### ISSUE THREAD

**Issue by mike7ang1rdz** [dotnet/orleans#8638]
Hello guys,

I could not find in the documentation. I have an application that when is in offline mode (a local exe), it saves work on disk and when gets connection it will send work to the server,  (I'm not currently using orleans) I use WCF but it's time to kill it.

I would like to get rid of this local storage mechanism (at least not manage it in my application), is orleans capable of managing the state automatically and  retry sending work when gets connection?  or am I totally lost?.

thanks

**Comment by ReubenBond** [comment]
It's not really intended to use Orleans offline (it's meant for cloud apps), but it can work. You can configure clustering using `UseLocalhostClustering` so that it has no external dependencies. You still need some database if you want to persist state, though. You could use SQLite for that.
