### ISSUE TITLE
Are System.Collections.Immutable types considered Immutable by Orleans

### ISSUE THREAD

**Issue by verdie-g** [dotnet/orleans#8640]
It's mentioned here https://learn.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/serialization-immutability that objects marked as immutable are not serialized when passed to a grain method in the same silo. Does the developer need to mark immutable types such as [FrozenDictionary](https://learn.microsoft.com/en-us/dotnet/api/system.collections.frozen.frozendictionary-2) or [ImmutableDictionary](https://learn.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutabledictionary-2) as Immutable?

**Comment by ReubenBond** [comment]
It depends: they are considered immutable if the element types are immutable.
If you have `ImmutableDictionary<string, int>`, that is immutable. If you have `ImmutableDictionary<string, List<int>>`, that is mutable.

**Comment by ReubenBond** [comment]
`FrozenDictionary<K,V>` is not yet supported, but it will follow the same behavior. It's also worth noting that because hash codes are process-dependent, the cost of computing the frozen dictionary kind/layout would be paid whenever you transfer them from one host to another. Those are better kept in-process, in my opinion.

**Comment by verdie-g** [comment]
> they are considered immutable if the element types are immutable

Makes sense.

> hash codes are process-dependent

Interesting I didn't realize the deserializer would have to recompute the hash for all keys for a Dictionary.

> the cost of computing the frozen dictionary kind/layout would be paid whenever you transfer them from one host to another

That sounds like an easy performance trap to fall into. Maybe that will deserve a dedicated analyzer.

I can try pushing a PR to update the doc or would you prefer doing it?

**Comment by ReubenBond** [comment]
> I can try pushing a PR to update the doc or would you prefer doing it?

Apologies for responding so late. If you are still interested, a PR would be welcome. It may be too much work. We should at least support serializing frozen collections.
