### ISSUE TITLE
Too many timeout errors due to persistence write

### ISSUE THREAD

**Issue by pkatsampiris** [dotnet/orleans#8647]
Hello!!

We have implemented a .NET 6 web application using Orleans 3.6.5 and we are using Dapper and Stored Procedures to read/write from MSSQL databases implementing `IGrainStorage`. The persistence state which we read and write is a List<> object.
We have a RabbitMQ consumer that consumes messages and inserts data to the list and we have web endpoints to retrieve the data and return it via web. So basically we have silos and client to Orleans on the same solution.
Our Grain is instantiated in web retrieve/RabbitMQ consume and the read process (the SP that retrieves the data from db) is run for the first time.
We have a timer in our grain that writes to the database 5 minutes after the grain's activation and then every 15 minutes. We also write the persistence state when the grain is on `OnDeactivateAsync()` as a last step of trying not to lose our data.
We have set on startup `ClassSpecificCollectionAge` = 15 minutes and `ResponseTimeout` for silo/client = 30 seconds.

We released this in OpenShift and we noticed that when a lot of simultaneous calls come at the RabbitMQ consumer/web retrieval, a lot of grains are created with the Kubernetes in OpenShift uses AutoScales correctly by increasing the pods when needed but when the persistences writes are trying to be run (it seems to be on `OnDeactivateAsync` and not in timer's write), we get A LOT of errors with this message:
```
System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
 ---> System.ComponentModel.Win32Exception (258): Unknown error 258
```
Also we get these errors (filtered due to sensitive data):
```
Orleans.Runtime.OrleansException: Current directory at SXXXXXXXXX:XXXXXX:XXXXXXX is not stable to perform the lookup for grainId *grn/XXXXXXXXXX/XXXXXXX (it maps to SXXXXXX:XXXXXX:XXXXXXX, which is not a valid silo). Retry later
```

So, the grains are correctly created on simultaneous calls, the AutoScaler is correctly handling and increasing the pods when needed and the timer seems to correctly write the persistence state to the database. When no longer used, the grains are set to `OnDeactivateAsync` state and the persistence state is written yet again one last time. In this moment the simultaneous persistence writes go to timeout because of the massive amount of them (it is not the database per se, more like the application waiting for database response that has the issue, I think). The grains are deactivated and removed on a massive amount and the AutoScaler kills the extra pods as well and we are given those massive amounts of errors with no guaranty on not losing any data.

So, regarding this issue the following questions come in mind:

- Is there a best practice on when/how to write the persistence state to database or doing it on `OnDeactivateAsync` is indeed the only way?
- Is there a similar issue for anyone else and if yes, how did you manage to get around it and what workaround do you propose?
- Is there any alternative suggested for this kind of handling? We need to be able to write one last time just before grains are removed to not lose data or maybe handling this better to lose less data instead
- The way we handle Orleans it seems that these errors are ok to be thrown. Is this correct or is it a mishandling from our part?

**Comment by ReubenBond** [comment]
It looks like this may be occurring during shutdown. If all grains are performing a write at the same time (during shutdown), then you will likely run into connection pool capacity issues or overload the database. I would recommend only writing the state if it has changed and trying to space out the writes.

I also recommend that if state is important, you must write it to storage immediately, otherwise you have no guarantees that the state will ever be made durable (hosts can crash at any time). If state is not critical, then writing dirty state on a timer is acceptable. It's preferrable to write that state only if the state has changed,

**Comment by pkatsampiris** [comment]
We added a stateChanged variable and we only save if that has value, meaning if the state was changed. But we still did not get a definite answer about writing state in `OnDeactivateAsync`. Is that expected and can we handle this better alongside the stateChanged variable we already added?

Also, how would you handle a similar case? The space between writes has to do with the timer intervals, right? So, a lot of grains would be created at the same time (due to spikes in traffic) but we would add a space in the time the write state is occurred, Right?

Apart from that, there is no additional ways to handle those writes in `OnDeactivateAsync` right? So, we have a good approach it seems.

Can we re-open it since the main questions seem unanswered?
