### ISSUE TITLE
SiloHost stop issue (hanging during the stop)

### ISSUE THREAD

**Issue by alexkr403** [dotnet/orleans#8655]
Hello everyone, 

I faced with the SiloHost stop issue. You can find Unit test here [OrleansTest](https://github.com/alexkr403/OrleansTest )
This situation occurs since version 3.5.1 and is relevant for using UseLocalhostClustering. _siloBuilder.UseAdoNetClustering works without problem.

Prerequisite: run two SiloHosts via unit test. There are two SiloHosts running in total: Primary and Secondary. This means that both SiloHosts are running in the same process. 

If the Primary SiloHost is stopped, the Secondary SiloHost hangs. 
If the Secondary SiloHost is stopped, the Primary SiloHost stops without any problem.

Look at the "Hanging" Unit test.

**Comment by ReubenBond** [comment]
This ought to have been fixed in #5747, but I see that we missed a case.
The secondary is blocked trying to tell the primary that it has stopped. It's an artifact of `UseLocalhostClustering` which is only intended for dev/test scenarios.

I've opened #8719 to fix this
