### ISSUE TITLE
MSI to connect to TableServiceClient and BlobServiceClient

### ISSUE THREAD

**Issue by ransinha1989** [dotnet/orleans#8657]
Our team is using MSI to connect to Azure Table Storage for all other use cases. We so far are using connection string to connect to BlobServiceClient and TableServiceClient.

Current Code:

```
// example of using azure table storage 
siloBuilder.UseAzureStorageClustering(options => options.ConfigureTableServiceClient(orleansAzureStorageConnectionString));
siloBuilder.UseAzureTableReminderService(options => options.ConfigureTableServiceClient(orleansAzureStorageConnectionString));

// example of using azure blob storage
siloBuilder.AddAzureBlobGrainStorageAsDefault(
    configureOptions: options =>
    {
        options.ConfigureBlobServiceClient(orleansAzureStorageConnectionString);
        options.ContainerName = "ExampleContainerName";
    });
```
We are hoping to pass in our own TableServiceClient so that we can set up its authentication any way we want.

https://learn.microsoft.com/en-us/javascript/api/@azure/data-tables/tableserviceclient?view=azure-node-latest#@azure-data-tables-tableserviceclient-constructor-2

**Comment by ReubenBond** [comment]
There is a ConfigureBlobServiceClient overload which allows you to pass your own BlobServiceClient, and similar for TableServiceClient
