### ISSUE TITLE
Proposal: Switch Orleans Serialization from protobuf-net to MemoryPack

### ISSUE THREAD

**Issue by SunSi12138** [dotnet/orleans#8668]
Hello Orleans community,

I'd like to propose a change in the underlying serialization mechanism of Orleans from protobuf-net to MemoryPack.

Rationale:

Performance: MemoryPack is a serialization library natively designed for C#. Preliminary tests and benchmarks have shown that it offers superior serialization and deserialization speeds compared to many other libraries.

Memory Efficiency: Alongside its performance benefits, MemoryPack has demonstrated lower memory overhead, which can be crucial for applications that require efficient memory utilization.

Native C# Design: Given that Orleans is a .NET framework, using a serialization library that's natively designed for C# can offer better integration, performance, and maintainability.

Switching to MemoryPack could potentially lead to better performance and reduced memory footprint for Orleans-based applications. I believe this change could be beneficial for the broader Orleans community and would love to hear thoughts, feedback, or any potential concerns regarding this proposal.

Thank you for considering this suggestion. Looking forward to the community's feedback.

Best regards

**Comment by buzzers** [comment]
However, the underlying serializer of Orleans is not pb.

**Comment by ReubenBond** [comment]
Orleans' serializer is optimized for .NET's type system. It is version tolerant like PB and fast like MemoryPack. You can run benchmarks comparing it to PB & MemoryPack by cloning the repository, navigating to `tests/Benchmarks`, and executing one of the following commands (one for each class of benchmark - maybe we should reorganize them so it's just one command):

* `dotnet run -c Release -- suite --filter *StructSerializeBenchmark*`
* `dotnet run -c Release -- suite --filter *StructDeserializeBenchmark*`
* `dotnet run -c Release -- suite --filter *ClassSerializeBenchmark*`
* `dotnet run -c Release -- suite --filter *ClassDeserializeBenchmark*`

**Comment by ReubenBond** [comment]
Closing this, but please feel free to open a new issue to discuss or ask questions in the [Orleans Discord Server](https://aka.ms/orleans/discord)
