### ISSUE TITLE
Question about .NET 8

### ISSUE THREAD

**Issue by AlseinX** [dotnet/orleans#8669]
Is there any plan about Orleans 8.0? (Since Orleans 4.0 becomes 7.0 to align with .NET versions)
Will there be a lot of breaking changes?

**Comment by nycdotnet** [comment]
https://github.com/dotnet/orleans/compare/main...v7.2.2

This shows no changes, so one hopes v8 will be just a rename and they're not working on a private branch...

**Comment by AlseinX** [comment]
Are you sure?
When it was 4.0 and the main branch had not been updated for long, a 7.0 preview was suddenly released with a bunch of updates.
It is so likely that they do have a private branch.

**Comment by AlseinX** [comment]
Additionally, Orleans' versioning does not respect semver, for a patch version increment could deliver functional updates. And there are always announcements without publicly visible discussions.
I do believe that the team must be working within a private context.

**Comment by BrianLawton** [comment]
Looks like there's already a PR working towards v8 support. https://github.com/dotnet/orleans/pull/8666

**Comment by ReubenBond** [comment]
I responded to a similar question in [Discord](https://discord.com/channels/333727978460676096/333727978460676096/1170088907313004596) ([server invite](https://aka.ms/orleans/discord)):

> The changes will only include the upgrade to .NET 8 itself and things which come with that (eg Keyed DI), whenever possible. We aim to backport fixes to 7.x releases whenever possible. Unlike ASP.NET, we make feature releases throughout the year, so we can hopefully avoid disruptive releases in Nov. We are deleting our custom Keyed DI to use the one which Ben contributed upstream
