### ISSUE TITLE
ORLEANS0010 should not get triggered in case type is a grain implementation

### ISSUE THREAD

**Issue by ledjon-behluli** [dotnet/orleans#8671]
ORLEANS0010 analyzes:

* POCOs (class, struct, record, record struct) that have GenerateSerializer applied to them to distinguish from non-orleans types.
* Interfaces (and their methods which are not static or properties) that extend base grain interfaces.

It should not react to `class`'s which inhertit from `Grain` or `Grain<TState>`

**Comment by ReubenBond** [comment]
Fixed in #8662
