### ISSUE TITLE
No way to enumerate the keys in RequestContext

### ISSUE THREAD

**Issue by worldspawn** [dotnet/orleans#8674]
I recently tried to implement something in our service. When http clients send any header that begins with `x-client-` i inject it into the log scope. So far so good, I then put all these values in the request context. I ran into trouble when I wanted to read them out again. I can only extract known keys, theres no way to get all keys (despite it being a dictionary under the hood).

Allowing access to the key collection would be useful.

I'm on 3.5.1.

**Comment by ReubenBond** [comment]
Good idea, I've opened #8720 to implement this.
