### ISSUE TITLE
Breaking change in release 7.2.2

### ISSUE THREAD

**Issue by jkonecki** [dotnet/orleans#8680]
I believe there is an unexpected breaking change introduced in release 7.2.2 through this PR:

https://github.com/dotnet/orleans/pull/8596

Code that uses `CollectionAgeLimitAttribute` and sets one of the fields will fail to compile.

```
    [CollectionAgeLimit(Days = 30)]
    public class ConnectionSearchGrain { }
```

The above code will compile in Orleans 7.2.1, but in 7.2.2. will cause the following compile-time error:

`Error	CS0617	'Days' is not a valid named attribute argument. Named attribute arguments must be fields which are not readonly, static, or const, or read-write properties which are public and not static.`

This is due to the change of property setters from `set` to `init`, which prohibits from using them in atribute declarations.

I suspect this in an unintented change, as it makes fields like `AlwaysActive`, `Days`, `Hours`, `Minutes` unusable.
I recommend changing properties from `init` back to `set`.

**Comment by jkonecki** [comment]
@ReubenBond would you like to me prepare a PR with the fix?

**Comment by ReubenBond** [comment]
You're right, this is unintended. I've got a PR ready

**Comment by jkonecki** [comment]
That's great! 

On an unrelated note, while looking at the source code I've noticed the below:

```
        private TimeSpan CalculateValue()
        {
            var span = AlwaysActive
            ? TimeSpan.FromDays(short.MaxValue)
            : TimeSpan.FromDays(Days) + TimeSpan.FromHours(Hours) + TimeSpan.FromMinutes(Minutes);
            return span <= TimeSpan.Zero
                ? MinAgeLimit
                : span;
        }
```

Shouldn't the last line be:

```
            return span < MinAgeLimit
                ? MinAgeLimit
                : span;
```

I know that at the moment `MinAgeLimit` is set to one minute, but if it was changed in the future (or a `Seconds` property was introduced) than it will be possile to set the span that is shorter than `MinAgeLimit`

**Comment by ReubenBond** [comment]
Great catch, I've updated the PR

**Comment by jkonecki** [comment]
Awesome! Have a lovely weekend!
