### ISSUE TITLE
Make the invocation of some methods only possible if the grain was already created

### ISSUE THREAD

**Issue by mhadhbi** [dotnet/orleans#8685]
Hello,

We have an API that the user call it to submit an asynchronous processing request.

The client submits his processing request using the following route:

HTTP POST /process
Returns ACCEPTED 
Location: /task/{GUID}

Then, he uses the URL in the location to do the polling of the result.

We want to use a grain to represent a processing request (task) but we are worried about a potential memory leak occurring when a client calls multiple times the polling URL with random Guids (do not belong to existants grains).

Is it possible to reject some RPC requests if the grain was not already created?
If not, how can we protect our platform from this kind of attack ?

Regards,
Ahmed

**Comment by ReubenBond** [comment]
You can check in the method itself if you want, by having a flag in the grain's state, for example. You can also check the `RecordExists` property of the grain's persistent state. If the grain does not exist, you can deactivate the grain after creation. You can also use require authentication and use a per-user grain to throttle requests, such as how this sample accomplishes that: https://github.com/ReubenBond/hanbaobao-web/blob/d0c8b1a1685aac75df11becbe66499f136ed689b/HanBaoBaoWeb/AccessControl.cs#L44 (video which covers the sample here: https://learn.microsoft.com/en-us/shows/on-net/building-real-applications-with-orleans)

**Comment by mhadhbi** [comment]
Thank you for your quick response. We will run some tests based on your suggestion.
