### ISSUE TITLE
Redis grain directory inconsistencies if registering grain fails

### ISSUE THREAD

**Issue by tanordheim** [dotnet/orleans#8686]
I have a scenario here where I have a lot of data flowing in from SQS causing a lot of grain activations, and during a rolling restart/deployment of the service there can be hundreds of thousands/millions of grain restarting in a relatively short time. What I have noticed moving from the DHT directory to Redis that some times during heavy grain activation, the `EVAL` statement issued to Redis during registration can time out. After this, the cluster seems confused about where the grain lives.

There are some logs for one particular grain earlier today for us:

```
Failed to register grain [Activation: S10.36.58.118:11111:57077053/historicstate/61a42209dcbb43bfa0270fe15ecdb894@3799bb88553a45608742d6e013120cf3#GrainType=MyService.HistoricStateGrain,MyService Placement=RandomPlacement State=Create] in grain directory

Orleans.Runtime.OrleansException: Register failed for historicstate/61a42209dcbb43bfa0270fe15ecdb894 ({"GrainId":"historicstate/61a42209dcbb43bfa0270fe15ecdb894","ActivationId":"@3799bb88553a45608742d6e013120cf3","SiloAddress":"10.36.58.118:11111@57077053","MembershipVersion":20096}) : StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=1630KiB, inbound=2588KiB, 5336ms elapsed, timeout is 5000ms), command=EVAL, next: EVAL, inst: 0, qu: 1761, qs: 0, aw: True, bw: Flushing, rs: DequeueResult, ws: Flushing, in: 987, last-in: 1, cur-in: 5, sync-ops: 0, async-ops: 79127, serverEndpoint: redis:6379, conn-sec: 62.02, aoc: 1, mc: 1/1/0, mgr: 9 of 10 available, clientName: MyService, PerfCounterHelperkeyHashSlot: 4859, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=8,Free=32759,Min=8,Max=32767), POOL: (Threads=14,QueuedItems=66,CompletedItems=1353614,Timers=21985), v: 2.6.122.38350 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.RedisDatabase.ScriptEvaluateAsync(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1559
   at Orleans.GrainDirectory.Redis.RedisGrainDirectory.Register(GrainAddress address, GrainAddress previousAddress) in /_/src/Redis/Orleans.GrainDirectory.Redis/RedisGrainDirectory.cs:line 132
   at Orleans.GrainDirectory.Redis.RedisGrainDirectory.Register(GrainAddress address, GrainAddress previousAddress) in /_/src/Redis/Orleans.GrainDirectory.Redis/RedisGrainDirectory.cs:line 132
   at Orleans.Runtime.GrainDirectory.CachedGrainLocator.Register(GrainAddress address, GrainAddress previousAddress) in /_/src/Orleans.Runtime/GrainDirectory/CachedGrainLocator.cs:line 109
   at Orleans.Runtime.ActivationData.RegisterActivationInGrainDirectoryAndValidate() in /_/src/Orleans.Runtime/Catalog/ActivationData.cs:line 1554
```

After this happened, any call towards this grain fails with this errer:

```
Failed to forward message Request [S10.36.37.125:11111:57076423 sys.svc.stream.agent/10.36.37.125:11111@57076423+internal-vstates-stream_2_internal-states-stream-1-0x15555556]->[S10.36.58.118:11111:57077053 historicstate/61a42209dcbb43bfa0270fe15ecdb894] Orleans.Streams.IStreamConsumerExtension.DeliverBatch(4e2a8f73-0d8d-0d85-1400-000018bd409d, internal-states-stream/device:state/61a42209dcbb43bfa0270fe15ecdb894, [SQSBatchContainer:Stream=device:state/61a42209dcbb43bfa0270fe15ecdb894,#Items=1], Orleans.Streams.DeliveryToken) #1607858[ForwardCount=5] from [GrainAddress GrainId historicstate/61a42209dcbb43bfa0270fe15ecdb894, ActivationId: @2109782677cd44f9ba7cbbdb83d88fe8, SiloAddress: S10.36.58.118:11111:57077053] to S10.36.58.118:11111:57077053 after This grain is active on another host (S10.36.58.118:11111:57077053).. Attempt 5
```

This grain is mostly only being called by the stream consumers, I cannot find any attempts at calling it via other code - successful or otherwise. The record for this grain in the directory looks like this:

```json
{
    "GrainId": "historicstate/61a42209dcbb43bfa0270fe15ecdb894",
    "ActivationId": "@3799bb88553a45608742d6e013120cf3",
    "SiloAddress": "10.36.58.118:11111@57077053",
    "MembershipVersion": 20096
}
``` 

The silo address corresponds with the same Kubernetes pod that attempted registration and timed out so it looks like this was successfully registered after all.

We store our grain directory in the same Redis instance that we use for grain states, which maybe amplifies our problem a little; lots of grain activations means lots of reading of grain state and lots of registrations in the grain directory. I'm going to try and move over to a dedicated Redis for this tonight or tomorrow to see if that resolves the problem. Optionally maybe wrap `RedisGrainDirectory` in a custom grain directory type and wrap the `.Register(GrainAddress, GrainAddress)` call in a retry of something.

Though it feels like this should be possible to handle on the infrastructure level as well. This is running on Orleans 7.2.2, using Redis as the default grain directory.

**Comment by tanordheim** [comment]
I at first glance thought this could be related to #8667, but it apparently could be something different according to the discussion in there - so moving it to a separate issue.

**Comment by ReubenBond** [comment]
I am hoping that https://github.com/dotnet/orleans/pull/8696 & https://github.com/dotnet/orleans/pull/8704 fix this issue, especially because of this:

> The silo address corresponds with the same Kubernetes pod that attempted registration and timed out so it looks like this was successfully registered after all.

The second PR there addresses this specifically. We will create a release shortly.

**Comment by ReubenBond** [comment]
The v7.2.3 release which aims to fix this is now available, so I will close this but please open a new issue and reference this if you still encounter this issue: https://github.com/dotnet/orleans/releases/tag/v7.2.3
