### ISSUE TITLE
GrainDirectory entities belonging to a dead silo are not removed from Azure Table Storage

### ISSUE THREAD

**Issue by mhadhbi** [dotnet/orleans#8687]
Hello,

I noticed that grain directory entities are not removed from Azure Table Storage after manually shutting down the hosting silo.

Is there any existant mechanism that can be used to remove ghost grains' activations from the directory stored in Azure Table Storage?

Regards,
Ahmed

**Comment by ReubenBond** [comment]
This is expected: the entries which point to defunct silos are ignored when they are read, so that they can be updated to point to valid silos.

**Comment by ReubenBond** [comment]
Closing this since it's intentional behavior (aligned with the characteristics of Azure Table Storage). An enhancement to perform background cleanup is possible, likely as an external contribution, but that can be a separate issue/PR.
