### ISSUE TITLE
Problems shutting down a silo

### ISSUE THREAD

**Issue by Liversage** [dotnet/orleans#869]
Recently a silo shutdown event was added in https://github.com/dotnet/orleans/commit/10fe0c6127a8b2464d8c7f2caa35629be8587939. This involves a thread that waits for the event to be set before shutting down the silo. This thread is not a background thread and as long as the thread waits the process will not terminate and this is giving me some issues.

A fix is to make sure the thread is created as a background thread but before I make a pull request for this change I want to get a better understanding of how the event is supposed to be used.

So far I have been calling `SiloHost.ShutdownOrleansSilo` to stop the silo hosted in a Windows service but now I have to use the event to make sure the thread terminates. However, I see no way of setting the event except by depending on the default name of the event (I know the name can be configured):

      var shutdownEvent = EventWaitHandle.OpenExisting(siloHost.Name + "-Shutdown");
      shutdownEvent.Set();

This will work across process boundaries so is that the purpose of the event?

**Comment by sergeybykov** [comment]
I think you are 100% correct. This thread should have been created as a background one. My mistake. A PR would be great.

The same commit also added a config parameter for specifying an arbitrary name for the shutdown event - https://github.com/dotnet/orleans/commit/10fe0c6127a8b2464d8c7f2caa35629be8587939#diff-b3d534c54af118ba07a4395585a560e4R244. It hasn't been added to the XML config though. So it currently can only be set programmatically.

**Comment by Liversage** [comment]
If the only purpose of the thread and the event is to enable shutdown of the silo from another process then you could argue that this feature is something that should not be included in Orleans but easily can be implemented using the exact same pattern combined with a call to `SiloHost.ShutdownOrleansSilo`. In my case the silo is hosted in a Windows service and the only way I want to be able to shutdown the silo is using the service manager.

Buy anyway, I have created a pull request to fix the thread issue.

**Comment by sergeybykov** [comment]
It's always a blurry line - what should be in the framework, and what should be left out. This seemed like one belonging in the `SiloHost` code as we have similar events for silo startup and termination.

Thanks for the PR. Already merged.

**Comment by gabikliot** [comment]
Fixed via #870.
