### ISSUE TITLE
Unable to log method arguments in Interceptor for v 7.2.1

### ISSUE THREAD

**Issue by SoucianceEqdamRashti** [dotnet/orleans#8743]
I cannot log the arguments to my interface methods in the incoming or outgoing interceptors for logging purposes.
There is GetArguments method available. How are we to log our method arguments? Only way right now seems to be not use the Interceptors and add some custom decorator. Is there a more built in way?

**Comment by ReubenBond** [comment]
What's wrong with using `GetArgument<object>(i)` for each argument?

**Comment by SoucianceEqdamRashti** [comment]
@ReubenBond , maybe I am not following, but where would the `GetArgument` method exist? It's not available here https://learn.microsoft.com/en-us/dotnet/api/orleans.iincominggraincallcontext?view=orleans-7.0

**Comment by ReubenBond** [comment]
It's on the `Request` property, which is of type `IInvokable`: https://learn.microsoft.com/en-us/dotnet/api/orleans.serialization.invocation.iinvokable?view=orleans-7.0

**Comment by SoucianceEqdamRashti** [comment]
Great, I will test that! Thanks!
