### ISSUE TITLE
F# Discriminated Unions with 4 cases or more fail when deserializing

### ISSUE THREAD

**Issue by gfix** [dotnet/orleans#8752]
F# Discriminated Unions with 4 cases or more fail when deserializing cases other than the first one.

Consider the following type
```fsharp
[<GenerateSerializer>]
type QuadrupleCaseDU =
    | Case1 of string
    | Case2 of int
    | Case3 of char
    | Case4 of byte
```
The cases `Case2`, `Case3` and `Case4` all fail during deserialization, but `Case1` succeeds.

The generated `ReadValue` methods for `IFieldCodec<QuadrupleCaseDU.Case[2-4]>` tries to obtain an instance of `QuadrupleCaseDU.Case[2-4]` calling:
```csharp
var result = (QuadrupleCaseDU.Case[2-4]) RuntimeHelpers.GetUninitializedObject(typeof(QuadrupleCaseDU.Case[2-4]))
````
This however fails for cases 2-4, but succeeds for Case 1.

[This skipped test case](https://github.com/dotnet/orleans/blob/eb5395e0d13b3757d0a0de9fcd53c55357375e26/test/DefaultCluster.Tests/SerializationTests/SerializationTests.cs#L145) exibits the behaviour described above.

**Comment by clement128** [comment]
Hello,  any plan to fix this?

**Comment by clement128** [comment]
UPDATE:

I am configure System.Text.Json for now instead of using default one  it seems solved my issue

https://learn.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/serialization-configuration?pivots=orleans-7-0#configure-orleans-to-use-systemtextjson
