### ISSUE TITLE
Use UpDownCounter instead of Counter for "orleans-grains" metric

### ISSUE THREAD

**Issue by Costo** [dotnet/orleans#8753]
Hi,

The "orleans-grains" instrument type is a `Counter` but it should be an `UpDownCounter`. Counters are exported with aggregation temporality "Delta", whereas UpDownCounters are exported with aggregation temporality "Cumulative" which make them more suitable to display the grain counts in Azure Monitor for instance.

See: https://github.com/open-telemetry/opentelemetry-dotnet/blob/9211cee8bf332bd0542795645f8e903443626e74/src/OpenTelemetry/Metrics/MetricReader.cs#L44

Here's what the metric currently looks like in Azure Monitor.
![Capture d’écran 2023-12-01 125609](https://github.com/dotnet/orleans/assets/46972/ff10a11b-8f53-4a15-879a-135355d91927)

As a workaround, I created an UpDownCounter that just listens to the "orleans-grains" counter:

```cs
/// <summary>
/// A listener for the "orleans-grains" Counter that republishes it as an UpDownCounter.
/// UpDownCounters are published to Azure Monitor with a "cumulative" aggregation type instead of a "sum" aggregation type for Counter.
/// </summary>
internal static class GrainsMetricListener
{
    const string CounterName = "orleans-grains-custom";

    private static readonly MeterListener meterListener = new();
    private static UpDownCounter<int> grainCounts = default!;

    static GrainsMetricListener()
    {
        meterListener.InstrumentPublished = (instrument, listener) =>
        {
            if (instrument.Name == "orleans-grains")
            {
                grainCounts ??= instrument.Meter.CreateUpDownCounter<int>(CounterName);
                listener.EnableMeasurementEvents(instrument);
            }
        };
        meterListener.SetMeasurementEventCallback<int>(OnMeasurementRecorded);
    }

    internal static void Start()
    {
        meterListener.Start();
    }

    private static void OnMeasurementRecorded(Instrument instrument, int measurement, ReadOnlySpan<KeyValuePair<string, object?>> tags, object? state)
    {
        grainCounts.Add(measurement, tags);
    }
}
```

I haven't checked other counters in the Orleans codebase.

**Comment by Costo** [comment]
Here's what it looks like in Azure Monitor when using `UpDownCounter` instead of `Counter`:

![Capture d’écran 2023-12-07 132953](https://github.com/dotnet/orleans/assets/46972/35fb5f41-f902-451f-b45d-021f46b7204f)

**Comment by ReubenBond** [comment]
I believe the reason we did this was to minimize the performance overhead. If the new approach does not add significant overhead, a PR would be more than welcome, if you are willing.

**Comment by Costo** [comment]
I don't know if it has a performance cost. I'll try to dig in the Open Telemetry SDK to see what's the difference betwwen the two counters.

**Comment by Costo** [comment]
Ok so as far as I understand, the main difference between "delta" and "cumulative" metrics is that  "delta" metric points can be reclaimed and reused once they have been collected.
The "cumulative" metric points can't be reclaimed because they need to keep the cumulative value since the start of the application. When there are many tags, with many disctinct values for a metric, this can lead to cardinality explosion.
See: https://opentelemetry.io/docs/specs/otel/metrics/supplementary-guidelines/#synchronous-example-cumulative-aggregation-temporality
The dotnet OTel SDK limits the number of metric points to 2000 by default by stream and will drop measurements if there's no more metric point available.

Cardinality explosion is not a concern for the "orleans-grains" counter because only the grain type is tracked with each measurement. But that means that the limit of grain types it can keep track of is 2000. Is that a reasonable limit?
