### ISSUE TITLE
optimisation of LRU full

### ISSUE THREAD

**Issue by slawomirpiotrowski** [dotnet/orleans#8762]
I have spotted an efficiency problem in used LRU implementation.

It looks like if it hits maximum size then a loop is starting that is deleting oldest entries, but unfortunatelly it is only deleting one entry per invocation and searching all of the entries when doing that. So deleting old entries is an O(n) operation and is making AddOrUpdate to be an O(n) operation too.

It is fairly easy to work around that. Just make sure it is deleting 5% (or some other fixed percentage) of entries at one invocation.

Something like this:

`private long GetNewGeneration() => Interlocked.Increment(ref nextGeneration) * 20 / MaximumSize;`

**Comment by ReubenBond** [comment]
Hi @slawomirpiotrowski, well spotted! You're right, and we are aware of the issue. We will likely replace the LRU with an entirely different implementation, likely from [BitFaster.Caching](https://github.com/bitfaster/BitFaster.Caching), which has 2Q and TinyLFU implementations. It seems that the TinyLFU implementation is the most suitable for Orleans.

**Comment by ReubenBond** [comment]
Closing in favor of #8736
