### ISSUE TITLE
Serialization: Stack<T> is deserialized in reversed order

### ISSUE THREAD

**Issue by DmitryZhelnin** [dotnet/orleans#8766]
Consider following example:
```cs
public class MyGrain : IMyGrain
{
    public Task<Stack<int>> GetStack()
    {
        var stack = new Stack<int>();
        stack.Push(1);
        stack.Push(2);
        stack.Push(3);
        stack.Push(4);
        return Task.FromResult(stack);
    }
}
```
And the calling code:
```cs
var stack = await myGrain.GetStack();
var value = stack.Pop(); // returns 1
```

Here in `StackCodec` during deserealization process values from original stack are just pushed to the new stack what makes the order to be reversed.
https://github.com/dotnet/orleans/blob/cd09126368aeb9e5ede05ba6618a5b538e987722/src/Orleans.Serialization/Codecs/StackCodec.cs#L97

**Comment by ReubenBond** [comment]
Thank you for reporting. I've opened #8768 with a fix + test.

**Comment by ReubenBond** [comment]
I've opened https://github.com/dotnet/orleans/pull/8769 to ensure that this does not happen again.
