### ISSUE TITLE
8.0-rc1 - AddServiceByName is gone.

### ISSUE THREAD

**Issue by turowicz** [dotnet/orleans#8775]
How to migrate? I understand there will be a guide coming soon but for now the DI is the only thing that doesn't compile after bumping package versions.

**Comment by turowicz** [comment]
cc @ReubenBond @benjaminpetit @sergeybykov

**Comment by AdrianoAE** [comment]
It was replaced with .Net 8 KeyedServices https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#keyed-di-services

**Comment by turowicz** [comment]
Does injecting custom grain storage work the same way?

```c#
var name = ProviderConstants.DEFAULT_STORAGE_PROVIDER_NAME;

services.AddSingleton<IGrainStorage>(f => f.GetServiceByName<IGrainStorage>(name));
services.AddSingletonNamedService<IGrainStorage>(name, (f, n) => f.GetService<OrleansFileStorage>());
services.AddSingletonNamedService<IGrainStorage>(ProviderConstants.DEFAULT_PUBSUB_PROVIDER_NAME, (f, n) => f.GetService<OrleansFileStorage>());
services.AddSingleton(f => new OrleansFileStorage(f.GetService<ILogger>(), hostContext.Configuration["ConnectionStrings:Storage.Grain"], new HashSet<string>
{
    typeof(UnitReportGrain).Name,
    typeof(AccountReportGrain).Name
}));
```

**Comment by turowicz** [comment]
cc @AdrianoAE @ReubenBond @benjaminpetit

**Comment by benjaminpetit** [comment]
> Does injecting custom grain storage work the same way?
> 
> ```cs
> services.AddSingleton<IGrainStorage>(f => f.GetServiceByName<IGrainStorage>(name));
> services.AddSingletonNamedService<IGrainStorage>(name, (f, n) => f.GetService<OrleansFileStorage>());
> services.AddSingletonNamedService<IGrainStorage>(pubSub, (f, n) => f.GetService<OrleansFileStorage>());
> services.AddSingleton(f => new OrleansFileStorage(f.GetService<ILogger>()));
> ```
> 
> would turn to:
> 
> ```cs
> services.AddSingleton<IGrainStorage>(f => f.GetKeyedService<IGrainStorage>(name));
> services.AddKeyedSingleton<IGrainStorage>(name, (f, n) => f.GetService<OrleansFileStorage>());
> services.AddKeyedSingleton<IGrainStorage>(pubSub, (f, n) => f.GetService<OrleansFileStorage>());
> services.AddSingleton(f => new OrleansFileStorage(f.GetService<ILogger>()));
> ```

Yes! You could also use the helper method `AddGrainStorage`.

**Comment by turowicz** [comment]
Thanks @benjaminpetit

**Comment by turowicz** [comment]
@benjaminpetit  would it then become this?
```c#
siloBuilder.Services.AddGrainStorage(name, (f, n) => f.GetService<OrleansFileStorage>());
siloBuilder.Services.AddGrainStorage(pubSub, (f, n) => f.GetService<OrleansFileStorage>());
siloBuilder.Services.AddSingleton(f => new OrleansFileStorage(f.GetService<ILogger>());
```

**Comment by turowicz** [comment]
Its not as required as one might think ;) thanks anyways!
