### ISSUE TITLE
Is there any recommended way how can we configure projection handlers to generate the read models for the event sourced grains?

### ISSUE THREAD

**Issue by AlexandrIalticenco** [dotnet/orleans#8789]
Orleans offers a possibility to customize storage and to have multiple persistent states per grain stored in different ways, but  what should we do if we need multiple projections of the same state to be maintained (for regular CQRS scenario)? I didn't find any projection mechanisms for the event handling built-in. Is there any recommended way to do such things?  I really don't believe that custom storage is a way to go, because the projections should be used from the outside by the external systems and custom GrainStorage implementation also forces to implement read mechanism which is really not required there. Could you please provide me with a documentation link or at least a hint if so?

Example of scenario: I would like to have Order grains stored and event sourced using built-in Orleans mechanisms, but I need to project them to have a read model for search / filtering / etc. Frameworks like Akka, Axon, etc have such functionality provided.

**Comment by AlexandrIalticenco** [comment]
Actually I found the answer on my question here https://github.com/pmorelli92/Orleans.Tournament?tab=readme-ov-file#cqrs-projections-event-sourcing-and-eventual-consistency.

There is a really nice diagram describing the whole flow I need (copying from there if it can be useful for anyone). 
![image](https://github.com/dotnet/orleans/assets/45029521/1a907201-abdc-441b-b937-e79abf5675bd)

**Comment by smfields** [comment]
Another option to consider is using a mechanism built-in to your storage provider. For instance, if you store your events in EventStoreDB then it can create the projections for you.

I didn't look closely at the sample you linked, but you have to be careful about persisting state and publishing events in separate actions. When you do that, there's a chance, however small, that something happens between when you save to the database and when you publish the event that causes the event to never get published.

Event sourcing can sidestep this issue by making the persistence of the state and the publishing of the event a single atomic action, but only when you use a supported event store.

**Comment by AlexandrIalticenco** [comment]
@smfields  thank you for your response. Yes, the sample I linked has exactly the problem you are talking about "You have to be careful about persisting state and publishing events in separate actions."

We are considering now to apply the solution you described by using custom log consistency storage provider.

**Comment by smfields** [comment]
@AlexandrIalticenco you're also welcome to look into [Orleans.EventSourcing.EventStorage](https://github.com/smfields/Orleans.EventSourcing.EventStorage). It's a library I'm working on to add support for using an external event store with Orleans event sourcing.

The package I linked is for the base library that you could build your own storage on top of, but I've already got other packages made for common event stores like:
- [EventStoreDB](https://github.com/smfields/Orleans.EventSourcing.EventStorage.EventStore) 
- [MartenDB](https://github.com/smfields/Orleans.EventSourcing.EventStorage.Marten)

It's still a bit of a work in progress, but it does have nuget packages published if you want to start using it, or you can use it as inspiration for your own solution.
