### ISSUE TITLE
Mark the AlwaysInterleaveAttribute attribute method can be interleaved with itself?

### ISSUE THREAD

**Issue by paxhujing** [dotnet/orleans#8803]
![a](https://github.com/dotnet/orleans/assets/13563757/ecfb3e54-99ea-46d8-92c8-de14646af795)

[AlwaysInterleave]
Task Test();

Does this mean that the 'Test' method cannot interleave with itself, but it can interleave with other methods?

**Comment by ReubenBond** [comment]
I opened #8804 to clarify
