### ISSUE TITLE
Orlerans 8 - Dependency on Microsoft.CodeAnalysis >= 4.8.0

### ISSUE THREAD

**Issue by jkonecki** [dotnet/orleans#8806]
Orleans 8 introduces dependency on Microsoft.CodeAnalysis >= 4.8.0:

_Microsoft.Orleans.Runtime 8.0.0 -> Microsoft.Orleans.Core 8.0.0 -> Microsoft.Orleans.Core.Abstractions 8.0.0 -> Microsoft.Orleans.Serialization 8.0.0 -> Microsoft.CodeAnalysis.Workspaces.Common (>= 4.8.0)_ 

This is clashing with **Entity Framework**, which has a strict dependency on 4.5.0.

_Microsoft.EntityFrameworkCore.Design 8.0.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.5.0 -> Microsoft.CodeAnalysis.Workspaces.Common (= 4.5.0)_

The above means that it's impossible to use Orleans 8 with Entity Framework. I understand this is more of the issue with Entity Framework and their strict dependency, but I wonder if Orleans really requires 4.8.0 - maybe 4.5.0 is sufficient?

**Comment by jkonecki** [comment]
I've managed to solve the problem with Entity Framwork by disregarding the compiler suggestion

`Error	NU1107	Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.8.0 directly to project to resolve this issue. 
`

and installing _Microsoft.CodeAnalysis.CSharp.Workspaces 4.8.0_ in the projects that use Entity Framework.

I've run into similar issue with web projects that use **Microsoft.VisualStudio.Web.CodeGeneration.Design 8.0.0** - they require `Microsoft.CodeAnalysis.CSharp.Features 4.8.0` to be referenced directly.

I'm closing the issue - hopefully the above will help other who run into the same upgrade issues.

**Comment by mile-abrettschneider** [comment]
Having the same problem with centralized package management and many projects. Installing directly into every project that is using efcore might work but in our case that's not really viable and hard to manage. It would be nice if orleans could check if 4.8.0 is really required or if 4.5.0 could be used instead to make it compatible with Microsoft.EntityFrameworkCore.Design and Microsoft.VisualStudio.Web.CodeGeneration.Design.

**Comment by JsAndDotNet** [comment]
I'm having the same problem too. Unfortunately, some of our processes use MSBuild, which is not as smart as visual studio, so adding the references as shown here does not resolve the problem (it's fine in VS, just not when built via MS Build).

As well as EF Tools, there's also a conflict with `Microsoft.VisualStudio.Web.CodeGeneration.Design` and a few other .NET libs that reference `Microsoft.CodeAnalysis.Common 4.8.0-3.final`

**Comment by ReubenBond** [comment]
Thanks for reporting this, folks. I will see if we can downgrade to v4.5.0
