### ISSUE TITLE
Mark `error=true` tag if an exception is thown in Grains in the context of ActivityPropagation

### ISSUE THREAD

**Issue by scalalang2** [dotnet/orleans#8831]
- Orleans Version: 7.2.4
- Dotnet core version: 7

---

## Motivation

Within the context of enabled ActivityPropagation, the current implementation appends a `status=Error` tag to activities when exceptions are thrown within Grains.

```csharp
activity.SetTag("exception.type", e.GetType().FullName);
activity.SetTag("exception.message", e.Message);
activity.SetTag("exception.stacktrace", e.StackTrace);
activity.SetTag("exception.escaped", true);
activity.SetTag("status", "Error");
```

However, It doesn't look as an error in jaeger as below.
![image](https://github.com/dotnet/orleans/assets/2603286/295ae243-226e-4c0e-9929-665172cca3b7)
![image](https://github.com/dotnet/orleans/assets/2603286/d9775517-d2c3-4435-a66b-9d013e0e29a2)

I expect that it should be marked error like this.
![image](https://github.com/dotnet/orleans/assets/2603286/175897fc-371d-4599-804a-20c718251fef)

We can simply make this work by adding one line of code.
```csharp
activity.SetTag("error", true);
```

**Comment by ReubenBond** [comment]
Thank you for the suggestion, @scalalang2. Would this be a more appropriate alternative? https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/reporting-exceptions/README.md#option-4---use-activityrecordexception

**Comment by scalalang2** [comment]
Thank you for your work @ReubenBond, LGTM, tk!
