### ISSUE TITLE
Custom Grain Storage - Issues After Upgrading to Orleans 8

### ISSUE THREAD

**Issue by JsAndDotNet** [dotnet/orleans#8833]
Hi,

Using the [Official Orleans Docs](https://learn.microsoft.com/en-gb/dotnet/orleans/tutorials-and-samples/custom-grain-storage?pivots=orleans-7-0) and [this book](https://www.packtpub.com/product/distributed-net-with-microsoft-orleans/9781801818971), I created a **custom storage provider** for sharding storage across multiple accounts.

The github repro can be found [here](https://github.com/JsAndDotNet/OrleansShardedStorage) and the key project [here](https://github.com/JsAndDotNet/OrleansShardedStorage/tree/main/OrleansShardedStorageProvider).

When trying to upgrade to Orleans 8, the instantiation has been broken.

Specifically,

````
internal static IServiceCollection AddAzureShardedGrainStorage(
	this IServiceCollection services,
	string name,
	Action<OptionsBuilder<AzureShardedStorageOptions>> configureOptions = null)
{
	configureOptions?.Invoke(services.AddOptions<AzureShardedStorageOptions>(name));
   
	services.ConfigureNamedOptionForLogging<AzureShardedStorageOptions>(name);
	if (string.Equals(name, ProviderConstants.DEFAULT_STORAGE_PROVIDER_NAME, StringComparison.Ordinal))
	{
		services.TryAddSingleton(sp => sp.GetServiceByName<IGrainStorage>(ProviderConstants.DEFAULT_STORAGE_PROVIDER_NAME));
	}
	return services.AddSingletonNamedService<IGrainStorage>(name, AzureShardedGrainStorageFactory.Create)
				   .AddSingletonNamedService<ILifecycleParticipant<ISiloLifecycle>>(name, (s, n) => (ILifecycleParticipant<ISiloLifecycle>)s.GetRequiredServiceByName<IGrainStorage>(n));
}
````

Looking at [this issue](https://github.com/dotnet/orleans/issues/8775), it appears `GetServiceByName` has been replaced by `GetKeyedService`. Simple fix.

I'm stuck on issues with the return statement.

Changing `AddSingletonNamedService` hits troubles as `AddKeyedSingleton` requires different parameters.

As with [official tutorial](https://learn.microsoft.com/en-gb/dotnet/orleans/tutorials-and-samples/custom-grain-storage?pivots=orleans-7-0), the storage Factory.Create requires an `IServiceProvider services`

AzureSharedGrainStorageFactory looks like this:

```
public static class AzureShardedGrainStorageFactory
{
    public static IGrainStorage Create(IServiceProvider services, string name)
    {
        var options = services.GetRequiredService<IOptionsMonitor<AzureShardedStorageOptions>>().Get(name);
        return ActivatorUtilities.CreateInstance<AzureShardedGrainStorage>(services, options, name);
    }
}
```

I can't find a way to fix it and don't want to further elongate this with my attempts. I've put a branch with the issue [here](https://github.com/JsAndDotNet/OrleansShardedStorage/tree/orleans-8-broken) so you can view the issue in VS.

What is the appropriate update for the return statement please?

```
return services.AddSingletonNamedService<IGrainStorage>(name, AzureShardedGrainStorageFactory.Create)
                   .AddSingletonNamedService<ILifecycleParticipant<ISiloLifecycle>>(name, (s, n) => (ILifecycleParticipant<ISiloLifecycle>)s.GetRequiredServiceByName<IGrainStorage>(n));
```

**Comment by sec** [comment]
Hi.
I hit the same issue, documentation and samples are not yet updated to 8.0, as you also saw :)

Based on your code, something like this should work:
```csharp
    internal static IServiceCollection AddAzureShardedGrainStorage(
        this IServiceCollection services,
        string name,
        Action<OptionsBuilder<AzureShardedStorageOptions>> configureOptions = null)
    {
        configureOptions?.Invoke(services.AddOptions<AzureShardedStorageOptions>(name));

        services.ConfigureNamedOptionForLogging<AzureShardedStorageOptions>(name);

        return services.AddGrainStorage(name, AzureShardedGrainStorageFactory.Create);
    }
```

But I'm 100% sure if this is all that's needed after migrate to v8, because right know my custom provider it not working, method `Participate` is not called during Silo startup :(

**Comment by JsAndDotNet** [comment]
Thanks @sec for the info. That would get past the build error, but wouldn't get it running (I did test to make sure). Hopefully the Orleans team might have some more info?

@ReubenBond - do you know how 'Custom Grain Storage' should be set up in Orleans 8 please? Are there any docs anywhere?

If there aren't any current docs and you can show me how to fix it, I could update/create the tutorial for Orleans 8. Here is an example of my standard of [writing](https://medium.com/@HKJ8/break-it-down-dealing-with-complex-code-9313a246ea6b).

**Comment by JsAndDotNet** [comment]
I've had a look at the above mentioned sample. I think it's missing a lot of new stuff. 

I checked out the [release notes](https://github.com/dotnet/orleans/releases/tag/v8.0.0), but couldn't see any pointers.

I checked out Orleans Contrib and found the [Mongo provider](https://github.com/OrleansContrib/Orleans.Providers.MongoDB), but I'm really struggling to work out the changes.

Does anyone from the Orleans team will know what to do with this please?

**Comment by sec** [comment]
What do you miss exactly or maybe what problem are you facing? After those code changes and change in Storage factory return type, your provider should work - what errors are you getting?

**Comment by JsAndDotNet** [comment]
The same thing as you whereby `Participate(ISiloLifecycle lifecycle)` isn't called on the silo startup. 

If you check out the [Mongo Provider](https://github.com/OrleansContrib/Orleans.Providers.MongoDB), it seems to be done in a very different manner in V8, but that provider is quite complex, so I'm having trouble working out exactly what's needed.

Did you get your repo working with the provider calling Participate?

**Comment by sec** [comment]
Yes, you need to change the return type in your storage factory to be like this
```
public static class AzureShardedGrainStorageFactory
{
    public static AzureShardedGrainStorage Create(IServiceProvider services, string name)
    {
        var options = services.GetRequiredService<IOptionsMonitor<AzureShardedStorageOptions>>().Get(name);
        return ActivatorUtilities.CreateInstance<AzureShardedGrainStorage>(services, options, name);
    }
}
```

**Comment by JsAndDotNet** [comment]
I couldn't get it going, so I went to the Orleans repo and re-modelled my stuff based on the [Redis](https://github.com/dotnet/orleans/tree/main/src/Redis) provider. 

Thanks for your help.

The tutorial is still out of date, so I'll leave this open as notification that the docs need updating. Appreciate the team have a lot on.

**Comment by JsAndDotNet** [comment]
For anyone else who gets stuck, I now have the persistence provider working. Code can be found [here](https://github.com/JsAndDotNet/OrleansShardedStorage).

It's based on the [Redis](https://github.com/dotnet/orleans/tree/main/src/Redis) provider, which is a nice example to follow.

I'm going to close this issue as my problem is resolved and hopefully others will be able to follow these examples.
