### ISSUE TITLE
Serialization issues - Orleans 8.0.0

### ISSUE THREAD

**Issue by claylaut** [dotnet/orleans#8859]
We're migrating from Orleans 3.7.1 to Orleans 8.0.0. 

Currently, we have these two issues:

**Issue 1**
When a class inherits from a generic list. Currently, the codegen is skipping this and on runtime, it's throwing an error: Could not find a base type serializer. 

![image](https://github.com/dotnet/orleans/assets/1999085/8204ed0d-f8ef-48a6-af12-d65f5d9f3bf0)

I've added a simple failing unit test (currently skipped) so you have an easy repro of this issue. https://github.com/dotnet/orleans/pull/8858

**Issue 2**
As per doc https://learn.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/serialization?pivots=orleans-7-0#serializing-record-types

When using GenerateCodeForDeclaringAssembly for an external lib and Sdk is not added to the library
Just added a failing test (which is skipped) with a repro https://github.com/dotnet/orleans/pull/8860

**Comment by ReubenBond** [comment]
Please open a separate issue for "Issue 2" and the `IUniverseIndices` issue so we can track a fix. They might be caused by the same issue.

**Comment by claylaut** [comment]
@ReubenBond I've just created a new issue for issue 2.
https://github.com/dotnet/orleans/issues/9006

**Comment by claylaut** [comment]
@ReubenBond I've just created a new issue for issue 3
https://github.com/dotnet/orleans/issues/9007
