### ISSUE TITLE
One Way time Duration. Is it too long?

### ISSUE THREAD

**Issue by keithazzopardi** [dotnet/orleans#8874]
Hello,

I had noticed that executing  a OneWay Grain takes approximately 700 milliseconds in production with a 3 node cluster. Based on your experience inproduction environments, doesn't this duration seem too much? I would expect it to have a lower duration for a fire and forget mechanism and build backpressure on MS Orleans.

**Comment by ReubenBond** [comment]
This is a lot, but we'd need to know more to understand what's going on here. Eg, how is that time being measured, what is the distribution of latencies (is 700ms the max or typical? is it always around 700ms or only at certain times), how much load is the system under, what are the grains doing, what kinds of machines are you running on, and how is everything configured (.NET version + settings, k8s pod settings, etc), GC stats, etc. If you are able to shed some more light, we'd be happy to help you investigate
