### ISSUE TITLE
New Microsoft.Extensions.Configuration stuff breaks existing Orleans project with "Could not find Clustering provider named 'Default'."

### ISSUE THREAD

**Issue by EdeMeijer** [dotnet/orleans#8878]
I upgraded from Orleans 8.0.0 to 8.0.1-preview2 to try the fix for https://github.com/dotnet/orleans/issues/8854, but now our app won't boot and crashes with an error `Could not find Clustering provider named 'Default'. This can indicate that either the 'Microsoft.Orleans.Sdk' or the provider's package are not referenced by your application.`. I did some digging and found that you changed some stuff to improve interop with `Microsoft.Extensions.Configuration`.

For an existing application where we already rolled our own configuration handling and use custom providers for storage, clustering and reminders, this is quite annoying. It would be nice if we wouldn't be forced to update our configuration scheme to do it "the new way", and instead have this new configuration approach be opt-in (or at least make it optional somehow).

**Comment by ReubenBond** [comment]
What is in your configuration? Are you also using `Orleans` as the root configuration node?

**Comment by EdeMeijer** [comment]
Yes, but it's a custom structure. Would renaming that also fix it?

**Comment by ReubenBond** [comment]
Yes, if there is no config node named "Orleans", you ought to be fine

**Comment by EdeMeijer** [comment]
Thanks, will try and get back to you

**Comment by EdeMeijer** [comment]
Alright, I renamed the section to `OrleansCustom` for now and we'll probably revisit this later to see if we want to adopt the new style config.
