### ISSUE TITLE
Code can not be generated when string interpolation is used

### ISSUE THREAD

**Issue by Dewaldf** [dotnet/orleans#888]
Hi, not a big issue, just wanted to let you guys know.

I am doing a tutorial on using Orleans, and then resharper suggested that I use string interpolation c# 6). After it is implemented I can not build the project because the code generation fails. 

    public class HelloWorldGrain :Grain,IHelloWorldGrain
    {
        public Task<string> SayHallo(string value)
        {
            return Task.FromResult(string.Format("Hallo {0}", value));
        }
    }

The above builds 100%, but when I change 

     return Task.FromResult(string.Format("Hallo {0}", value));
to 

     return Task.FromResult($"Hallo {value}");  

The build fails with the following errors. 

     Error : Orleans code generator found error : -- Code-gen FAILED --
     C:\Dev\FirstOrleansApplication\MyOrleans.Implementation\Exception = System.Exception : error :     ClientGenerator could not compile and generate CSharp -- encountered 1 compilation   warnings/errors.
      ErrorList = 
      c:\Dev\FirstOrleansApplication\MyOrleans.Implementation\HelloWorldGrain.cs Line 11,36 - ERROR CS1056 -- Unexpected character '$'

    at Orleans.CodeGeneration.GrainClientGenerator.BuildInputAssembly(CodeGenOptions options)
    at Orleans.CodeGeneration.GrainClientGenerator.RunMain(String[] args)
  
        C:\Dev\FirstOrleansApplication\packages\Microsoft.Orleans.Templates.Grains.1.0.10\build\Microsoft.Orleans.Templates.Grains.targets(150,5): error MSB3073: The command ""C:\Dev\FirstOrleansApplication\packages\Microsoft.Orleans.Templates.Grains.1.0.10\build\..\tools\ClientGenerator.exe" "@obj\Debug\MyOrleans.Implementation.codegen.args.txt"" exited with code 3.

**Comment by ReubenBond** [comment]
Thank you for letting us know :) This will be fixed when #528 & #886 are merged

**Comment by gabikliot** [comment]
so its the same issue as https://github.com/dotnet/orleans/issues/755 - Code generation does not support C# 6.

**Comment by sergeybykov** [comment]
Resolved by https://github.com/dotnet/orleans/pull/528.
