### ISSUE TITLE
ISiloBuilder.ConfigureApplicationParts not in version 8 ?

### ISSUE THREAD

**Issue by meisamhasani** [dotnet/orleans#8895]
hi
Do settings
ApplicationParts
Has it been removed in the latest version?
I get the following error
'Unable to find an IGrainReferenceActivatorProvider for grain type logcontext'
The structure of my solution and projects is as follows:
Interface
Grains
UIClient

**Comment by ledjon-behluli** [comment]
Yes, its not needed anymore! Orleans will scan the assemblies and generate code that is marked with Orleans specific attributes/marker interfaces

**Comment by meisamhasani** [comment]
thanks for your response
Why do you think I am getting the following error?
'Unable to find an IGrainReferenceActivatorProvider for grain type logcontext'
![image](https://github.com/dotnet/orleans/assets/2770416/0b307606-a67c-4fdf-9823-ce325a066ab6)

**Comment by ledjon-behluli** [comment]
Can you show me the package references in all these projects

**Comment by meisamhasani** [comment]
![image](https://github.com/dotnet/orleans/assets/2770416/239a9b76-b23b-47d0-9f2d-a344aa57dff2)

![image](https://github.com/dotnet/orleans/assets/2770416/cdde6c7a-a29f-4d31-a054-f411d7082f06)

**Comment by ledjon-behluli** [comment]
Package not Project references

**Comment by meisamhasani** [comment]
![image](https://github.com/dotnet/orleans/assets/2770416/25e44713-8877-4561-98b0-8d878ebbe379)
![image](https://github.com/dotnet/orleans/assets/2770416/0621fe23-3bdf-4904-bf28-a5be13343a69)
![image](https://github.com/dotnet/orleans/assets/2770416/279389ab-3803-4d97-a17c-d323cce16b1a)

**Comment by meisamhasani** [comment]
thanks, ledjon-behluli
it is fixed
i added package Microsoft.Orleans.Sdk to interface
