### ISSUE TITLE
The best suggestion for grain state storage?

### ISSUE THREAD

**Issue by meisamhasani** [dotnet/orleans#8900]
Hello good time
I have an application designed and implemented based on Orleans.
The information of each grain is stored in a file every few seconds, and at the time of activation, the last state of each grain is also loaded from the file.
How can I cover these few seconds? I don't want to save as soon as the state changes.

**Comment by rallets** [comment]
Hi, using a timer as explained here:
https://learn.microsoft.com/en-us/dotnet/orleans/resources/best-practices?source=recommendations#grain-state-persistence

In my opinion the old documentation had a better discoverability, I'm pretty sure it had a detailed example about this topic/pattern.

Btw if you mean to write to a local file, that is not the best approach in Orleans, as each machine in the cluster should be able to access a shared (cloud) storage. A file could be local to each machine, blocking another machine to reach it. A blob storage could be better.

**Comment by meisamhasani** [comment]
Yes, it's true, I use shared storage and there is no problem.
My problem is: How many seconds? Whatever this number is, we may still have data loss.

**Comment by rallets** [comment]
If the silo crashes, yes you could have data losses. 
I think there isn't a magic number, just meet your requirements, as a balance of throughput and risk.

**Comment by meisamhasani** [comment]
Yes, I understand.
What I mean is, what is the solution to keep the last state in a safe place so that latency does not occur.
I think more. thank you

**Comment by rallets** [comment]
For completeness I would like to add to the discussion that you can lose data only if the silo crashes (pretty unfortunate thing, but can happen with HW failures or ungraceful shutdown), and not in the normal flow, if you save the grain state following the deactivation lifecycle OnDeactivateAsync.
In this way when the grain is deactivated the state is saved, it doesn't need to wait for the timer to tick. 
Be also aware that timers doesn't keep grains active, so with a lot of pressure the silo could decide to deactivate the grain, starting to trash you performance as it's designed on the timer back pressure not being anymore "reliable".
I hope it helps.
