### ISSUE TITLE
Could not find a copier for type System.Func`

### ISSUE THREAD

**Issue by meisamhasani** [dotnet/orleans#8911]
hello
I have a grain that has a method with the following input parameters:

Task<List<T>> Where(Func<T, bool> exp);

Is there a solution to fix the following error?
Could not find a copier for type System.Func`

**Comment by ReubenBond** [comment]
This is simply not copyable/serializable: you cannot safely serialize a closure and deserialize it on another machine. I would guess what is happening is that you're passing or returning an IEnumerable<T> over the wire. You should enumerate it to a list/array first.

**Comment by meisamhasani** [comment]
I want to pass an action dir as a parameter

**Comment by ReubenBond** [comment]
You can't: closures cannot be reliably serialized. You should find another way, one which does not involve serialization of Action/Func.

**Comment by meisamhasani** [comment]
Ok.thank you
