### ISSUE TITLE
Move Relational Storage code into a separate assembly

### ISSUE THREAD

**Issue by gabikliot** [dotnet/orleans#892]
We should move [Relational Storage code](https://github.com/dotnet/orleans/tree/master/src/Orleans/RelationalStorage) into a separate assembly, `OrleansRelationalUtils` or `OrleanSQLUtils`. This is both in order to remove the extra dependencies from core Orleans and also help with #368. Apparently,  `System.Data`  and  `System.Transactions` are not .NET Core compliant (after we do that, we can ponder around how to make `OrleansRelationalUtils` .NET Core compliant).

**Comment by dVakulen** [comment]
I'd like to take this one.

**Comment by gabikliot** [comment]
:+1: Go for it!
@veikkoeeva will hopefully be able to help answer questions if there are any and assist with testing.

**Comment by gabikliot** [comment]
Also just an FYI, I updated #368 with new the compatibility report and more porting issues.

**Comment by veikkoeeva** [comment]
@dVakulen Yeah, don't wait for us! :) Don't be afraid to adjust namespaces or things like that if it makes sense.

**Comment by veikkoeeva** [comment]
@gabikliot Notes:

* `System.Transactions` code is not used actually anywhere at the moment by Orleans, so it could be safely removed. For a moment it looked like the code either stays in SQL Server only or that I would need to use `TransactionScope`, which in async code would work only from .NET 4.5.2 onwards. But I think having the current scripts are a more flexible alternative and consquently this code isn't needed.

* System.Data.Common was recently added to [CoreFx](https://github.com/dotnet/corefx/pull/2197) and there seem to be Nuget packages for CoreCLR if I interpret correctly [System.Data.Common](https://www.nuget.org/packages/System.Data.Common) and [System.Data.SqlClient](https://www.nuget.org/packages/System.Data.SqlClient/).
