### ISSUE TITLE
IPersistentState<MyClass>.RecordExists is false until .ReadStateAsync() is called

### ISSUE THREAD

**Issue by SGStino** [dotnet/orleans#8936]
I have a single grain class where `IPersistentState` doesn't seem to be read when the grain is activated.

But when i manually call `state.ReadStateAsync()` in `OnActivateAsync`, it invokes the Storage's Read method for the first time.

All other grains (that i've inspected closer), seem to have ´.RecordExists` set correctly

Comparison of the observed flows:

 **Normal grain:**
1. Grain Constructor
2. IGrainStorage.ReadStateAsync
3. Grain.OnActivateAsync

**Misbehaving grain:**
1. Grain Constructor
2. Grain.OnActivateAsync
2.1. _myGrainState.ReadStateAsync() _(this call isn't even present in the normal grain)_
3. IGrainStorage.ReadStateAsync()

Is there something that might explain this behavior, or where I can look to find out why the state isn't being read?

its a dotnet 8, Orleans 8 project self hosted in a blazor web app for testing purposes.

**Comment by SGStino** [comment]
It's now even more bizarre:

```csharp
public MyClass([PersistentState("statemachine")] IPersistentState<MyState> botState, [PersistentState("otherstate")] IPersistentState<MyState> testState) : Grain, IMyGrain
```

in `OnActivateAsync` `botState.RecordsExists` is false while `testState.RecordExists` is true.

after invoking `botState.ReadStateAsync()`, both are true.

the `IGrainStorage.ReadStateAsync` only got invoked once for the testState before `OnActivateAsync`

**Comment by SGStino** [comment]
Turns out, if you call .State in the constructor, it prevents it from being read on activation.
Moving the setup logic from the constructor to the OnActivate method fixes that issue.

**Comment by ledjon-behluli** [comment]
The state will not be loaded when injected into the constructor, so accessing it is invalid at that time.

**Comment by ReubenBond** [comment]
> Turns out, if you call .State in the constructor, it prevents it from being read on activation.
> Moving the setup logic from the constructor to the OnActivate method fixes that issue.

This is a bug. Thank you for finding this

**Comment by SGStino** [comment]
> The state will not be loaded when injected into the constructor, so accessing it is invalid at that time.

I figured as much, although I don't see a direct logical reason for it. (There might be a practical one though)

State _could_ be very well read before invoking the constructor, followed by OnActivate.
Because for every OnActivate, i'd expect a constructor call unless it hasn't been garbage collected yet after deactivation?
A grain still gets a class instance per activation, always, it's not that grain activation instances in a silo can share a class instance?

So the order of operations could be very well be:
- Collect dependencies 
- Read State
- Construct class
- Activate

But i believe the current implementation is, from what i can observe:
- Collect dependencies 
- Construct class
- Read State
- Activate

Which makes `... so accessing it is invalid at that time.` true, and possibly not what could be expected/assumed by someone new with the system.

> This is a bug. Thank you for finding this

Happy to be of help




**Just a bit more context,** (not that I'd expect this information to change the flow mentioned before):

When using stateless, it's clean to have a `private readonly StateMachine<MyState,Command> state` statemachine.

But since i'm not allowed to construct it in the constructor (because it reads the state at least once while being constructed), 
i need to put the statemachine in a (nullable)  `private StateMachine<MyState,Command>? state` and use `state!.FireAsync(Command) ` instead of just `state.FireAsync(Command)` to keep the compiler happy when checking for nullability.

If only `stateless` would not read the state while constructing, then I'd never ran into this bug...

**Comment by ReubenBond** [comment]
I opened a PR which ought to fix the bug: https://github.com/dotnet/orleans/pull/8944

**Comment by ledjon-behluli** [comment]
@SGStino Maybe it is doable, but highly impractical because the state loading component itself is a grain lifecycle participant. 
Participants have `OnStart` which is an `async` method and allows for execution of async tasks (i.e. reading state from external storage). Now the participant can not execute if the grain that it participates WITH, does not yet exist.

**So, while the logic for loading the state can (and is) constructed before the grain activation is constructed, its logic (loading the state) has to run AFTER the activation exists.**

I am sure there are ways to handle that, but overall this gives me the typical vibe of "async ctors" which even if doable, I am not sure it is worth it. But that is just my opinion ofc.

**Comment by ledjon-behluli** [comment]
Regarding `StateMachine<MyState,Command>? state`, there is a clean way out of it:

Before: `private StateMachine<MyState,Command>? state;`
After: `[AllowNull] private StateMachine<MyState,Command> state;`

**Comment by SGStino** [comment]
makes sense, i knew there was some reason i didn't know existed :) thanks for the enlightenment.
