### ISSUE TITLE
OrleansQuery not exists

### ISSUE THREAD

**Issue by Pragrammist** [dotnet/orleans#8962]
I attempted to integrate ADO.net into a project that included MSSQL and PostgreSQL. I got the same error as OrleansQuery does not exist; I saw sql scripts that are in here:
https://learn.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/adonet-configuration
and I notice SQL scripts have no OrleansQuery table for MS SQL and Postgres. I can't find on the internet how to solve it.
I also tried to run scripts manually and got the same error.

**Comment by Pragrammist** [comment]
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'OrleansQuery'.

"Npgsql.PostgresException (0x80004005): 42P01: "orleansquery" relation does not exist" (translated error message)

**Comment by Pragrammist** [comment]
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.3" />
    <PackageReference Include="Microsoft.Orleans.Persistence.AdoNet" Version="8.1.0" />
    <PackageReference Include="Microsoft.Orleans.Server" Version="8.0.0" />
    <PackageReference Include="Npgsql" Version="8.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>

</Project>
My packages


builder.Host.UseOrleans(static siloBuilder =>
{
    siloBuilder.UseLocalhostClustering();
    siloBuilder.AddAdoNetGrainStorage("users", options =>
        {
            options.Invariant = "System.Data.SqlClient";
            options.ConnectionString = @"
                Data Source=(localdb)\MSSQLLocalDB;
                Initial Catalog=Orleans;
                Integrated Security=True;
                Database=Orleans
            ";
        });
    siloBuilder.AddAdoNetGrainStorage("users2", options =>
        {
            options.Invariant = "Npgsql";
            options.ConnectionString = @"Server=localhost;Port=5432;User Id=postgres;Password=postgres;Database=postgres;";
        });
});

**Comment by Pragrammist** [comment]
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.3" />
    <PackageReference Include="Microsoft.Orleans.Persistence.AdoNet" Version="8.1.0" />
    <PackageReference Include="Microsoft.Orleans.Server" Version="8.0.0" />
    <PackageReference Include="Npgsql" Version="8.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>

</Project>

**Comment by Joshhua5** [comment]
You need to run the setup scripts on the database, to create the table and stored procedures used. 

https://learn.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/adonet-configuration

**Comment by Pragrammist** [comment]
I ran that scripts and they are not working

**Comment by Pragrammist** [comment]
Pleas, First read and then answer

**Comment by Joshhua5** [comment]
You might want to look at that again, because the main script creates the OrleansQuery table. 

https://github.com/dotnet/orleans/blob/main/src/AdoNet/Shared/PostgreSQL-Main.sql#L34

**Comment by Pragrammist** [comment]
Thanks!
