### ISSUE TITLE
Orleans membership table is not cleared properly from obsolete silos

### ISSUE THREAD

**Issue by UladzimirVyaziginTR** [dotnet/orleans#8968]
Context:
1. I am using Orleans 8.1.0 and PostgreSQL clustering in Kubernetes containers. These containers are recreated enough frequently.
2. Near the half of all requests fails due to incorrect IP address of a defunct silo. The error message may vary but the most frequent of them is on screenshot below.
3. Cluster membership options are configured according to the screenshot below. The value of 'MembershipTableCleanupInMinutes' is 5 minutes.

Questions:

1. Is it the bug of Orleans 8.1.0 or misconfiguration of cluster membership options?
2. What exactly should I do to overcome the issue with defunct silos?

![image](https://github.com/dotnet/orleans/assets/88712242/d2513428-b1c6-433e-a482-617d02d96beb)
![image](https://github.com/dotnet/orleans/assets/88712242/2bd173dd-a6f9-41b0-aa28-e9fa2e92860d)

**Comment by ArminShoeibi** [comment]
@UladzimirVyaziginTR Did you solve the problem?
