### ISSUE TITLE
Bug: Exclude inaccessible interface methods from codegen

### ISSUE THREAD

**Issue by alrz** [dotnet/orleans#8973]
Using the following type:
```cs
interface ISomeGrain : IGrain {
  protected Task Method();
  // other methods
}
```
The codegen generates invalid code. This member should be excluded from the proxy as it's not accessible from outside.

**Comment by ReubenBond** [comment]
What would you like to see happen here? Internal interfaces are acceptable. Protected members within them could possibly be supported with a codegen change to mark the corresponding member on the generated proxy as protected also

**Comment by alrz** [comment]
> What would you like to see happen here?

The  implementation must be public or explicit, but it's simply throwing an unreachable exception because the code from ISomeGrain client won't get there anyways. 

Note this member is only callable via DIM from inside an inherited interface but at that point we're already on the server, not client.

**Comment by alrz** [comment]
> simply throwing an unreachable exception

Corrention: that wouldn't be correct for `internal` methods though
