### ISSUE TITLE
Typo in silo start log

### ISSUE THREAD

**Issue by kmcclellan** [dotnet/orleans#8979]
Orleans surfaces `MachineNAme` (bad casing) as a log property in structured logs, which is annoying and doesn't correlate with other logs that send `MachineName`.

https://github.com/dotnet/orleans/blob/deda4baa2892174d0ca2c9fb470f0082ec33a679/src/Orleans.Runtime/Silo/Silo.cs#L128

**Comment by ReubenBond** [comment]
Thanks for notifying us, @kmcclellan - I've opened #8980
