### ISSUE TITLE
Cannot serialize type inheriting from Dictionary

### ISSUE THREAD

**Issue by defilerc** [dotnet/orleans#8989]
We have a type that inherits from a `Dictionary<IncidentType, int[]>` (simplified version follows):

```csharp
[GenerateSerializer]
public class MatchStatistics : Dictionary<IncidentType, int[]>
{
    public MatchStatistics()
    {
        this[IncidentType.Score] = new[] { 0, 0 };
    }
}

public enum IncidentType { Unknown = 0, Score = 1 }
```

When trying to serialize/deserialize it and assert the two objects are equal, the test fails, as one additional Dictionary entry (with a key value of 0) seems to be created by the serializer:

```
Unhandled exception. NUnit.Framework.AssertionException:   Assert.That(actual, Is.EquivalentTo(expected))
  Expected: equivalent to < [Score, < 0, 0 >] >
  But was:  < [Unknown, null], [Score, < 0, 0 >] >
  Extra (1): < [Unknown, null] >
```

We are currently trying to migrate to Orleans v7.2.6 (from v3.5.0), but the issue is also present in v8.1.0. I have also created a small repro project to assist you: [orleans-serialization.zip](https://github.com/dotnet/orleans/files/15260802/orleans-serialization.zip)

SDK versions used: `v7.0.408` (but it's also reproducible with `v8.0.204`)

### Additional Info:

- When the class doesn't inherit from `Dictionary<IncidentType, int[]>`, but it uses a property of this type, the serialization works as expected. Currently, this change is not trivial for us, though, as our codebase is huge and this is a core object.
- The problem also persists if the Dictionary has an `int` type for keys, instead of `enum` and we set `this[1] = new[] { 0, 0 }` in the ctor. An additional entry (`this[0]`) is created, as well.

cc: @ReubenBond does this seem like a bug to you or are we missing something?

**Comment by ReubenBond** [comment]
This does seem like a bug to me. Thanks for reporting. I'm investigating

**Comment by ReubenBond** [comment]
@defilerc I've opened #8993 with a fix. I assume you will need this backported to v7.x

**Comment by defilerc** [comment]
@ReubenBond thx a lot for your prompt reply and fix! If that's possible, that would be great, as we're migrating to Orleans v7.x at the moment and will migrate to .NET8/Orleans 8.X at a later stage.
