### ISSUE TITLE
Do not log error "Error monitoring Kubernetes pods" on shut down

### ISSUE THREAD

**Issue by gp-jorge** [dotnet/orleans#9044]
I have been using the k8s hosting without issues but there is an error log `Error monitoring Kubernetes pods` consistently recorded on every deployment. The 

The underlying exception is a task cancelled, I guess due to the shutdown of the system:

![image](https://github.com/dotnet/orleans/assets/129280461/f5ae1b7b-f465-4b87-a018-e69d40c5a690)

After checking the code base I have seen that the [log comes from the `KubernetesClusterAgent`](https://github.com/dotnet/orleans/blob/c76b4431a5013616a1e1105be7169937ee4a26eb/src/Orleans.Hosting.Kubernetes/KubernetesClusterAgent.cs#L352).

The log is not filtered when the shutdown was requested as it is [filtered in the `MonitorOrleansClustering` method when shutdown is requested](https://github.com/dotnet/orleans/blob/c76b4431a5013616a1e1105be7169937ee4a26eb/src/Orleans.Hosting.Kubernetes/KubernetesClusterAgent.cs#L269).

Would it be possible to follow the same approach and filter that exception catch on shutdown request? That would avoid logging the error in each shutdown of the pod.

I can do the changes if needed.

**Comment by ReubenBond** [comment]
Thank you for the suggestion, @gp-jorge! Would you be willing to submit a PR?
