### ISSUE TITLE
[Concurrency] ReadWrite ? ReadOnlyAttribute

### ISSUE THREAD

**Issue by MickaelThumerel** [dotnet/orleans#9046]
I drop this question to be sure, the documentation is not clear on this point.

public interface ISampleGrain : IGrain
{
    Task Write(int data);

   [ReadOnly]
   Task<int> Read();
}

In this sample, the concurrency behavior is like a **ReadWriteLocker** ?
Meaning it allow concurrent read but block everthing when write ?

**Comment by ReubenBond** [comment]
Yes, you are correct
