### ISSUE TITLE
Telemetry/activity not linked back through Observers

### ISSUE THREAD

**Issue by onionhammer** [dotnet/orleans#9053]
When using observers, activities are not linked back to their enclosing observer activity. Not sure if this is a bug or enhancement idea

Per @ReubenBond: The issue is that grain call filters don't run on incoming observer calls

Example:

```C#
class MyGrain() : Grain, IMyGrain, IMyGrainObserver
{
    public async Task StartProcessingAThing() // from: IMyGrain
    {
        var reference = this.AsReference<IMyGrainObserver>();

        var processor = GrainFactory.GetGrain<IMyProcessorGrain>(0);

        await processor.StartAndSubscribeAsync(reference);
    }

    public async Task OnProcessedAsync() // from: IMyGrainObserver
    {
        // No longer linked to any activity
    }
}
```

where the 'processor' would do some job then invoke the observer when complete

**Comment by onionhammer** [comment]
@ReubenBond here's a repro:

https://github.com/onionhammer/repro-orleans/blob/763ab292cef51854d70fe608a52acdcaba7ecb3a/repro-orleans.API/Grains/ParticipantGrain.cs#L32

![image](https://github.com/dotnet/orleans/assets/969938/4904c818-0b51-4ff0-8d75-4e44bb3e37d8)

**Comment by onionhammer** [comment]
Ah I switched to nightly - I was using a custom build before, let me keep experimenting

**Comment by ReubenBond** [comment]
![image](https://github.com/dotnet/orleans/assets/203839/9cba3aef-ead2-4f19-9c28-0d2693cb7496)
Your trace above is also correct, since you're calling an observer method on a grain, not an external object reference (which is what my PR adds support for). The last line in your trace is the ReceiveMessageAsync call

**Comment by onionhammer** [comment]
Crap, I think you're right - the discrepancy I'm seeing is actually related to Aspire's trace not handling links (where app insights does), so it's not an Orleans issue at all.

**Comment by ReubenBond** [comment]
I'll close this, then. We got a feature out of it anyway: observer calls on the client now emit traces and support incoming grain call filters :)
