### ISSUE TITLE
Can I use generated codes by protobuf for state of the grain storage?

### ISSUE THREAD

**Issue by scalalang2** [dotnet/orleans#9072]
## Motivation
Lets assume that we declare a protobuf message as blow.

```protobuf
message ChatRoom {
    bool isActive = 1;
    repeated string members = 2;
}
```

Then, we need to store the ChatRoom as state in the ChatGrain.

```csharp
class ChatGrain : IChatGrain {
    private IPersistentState<ChatRoom> state; // or use TransactionalState depends on your needs.
}
```

Even though the ChatRoom class is generated by protobuf.
I've not been met any issue.

Can I keep using this pattern without any issues?

**Comment by scalalang2** [comment]
@jsteinich thanks for a reply 👍 

We've used Orleans 7.x and without configuring `Serializer`, and the class generated by protobuf works fine.
I'm not sure whether it is intended or not.

Can I assume that we can use this without any concerns?

**Comment by jsteinich** [comment]
I recommend double checking the format that your data is actually saved in. Without additional configuration, I believe it defaults to JSON (possibly binary JSON depending on the storage provider used). As long as it matches what you want it to be, then there shouldn't be any issue.
