### ISSUE TITLE
RegisterGrainTimer not coalled callback

### ISSUE THREAD

**Issue by meisamhasani** [dotnet/orleans#9073]
Hello
I am using version 8.2.0
I use the following line when
 this.RegisterTimer(ReloadCache, null, TimeSpan.FromSeconds(1), TimeSpan.FromHours(1));

Everything is ok, but when I use the below line

 this.RegisterGrainTimer(ReloadCache, this.State, TimeSpan.FromSeconds(1), TimeSpan.FromHours(1));

The timer is not called!

**Comment by ReubenBond** [comment]
@meisamhasani is your grain busy waiting for a call to complete? Try using the overload which accepts options and pass `Interleave=true` to see if that does what you want

**Comment by meisamhasani** [comment]
thank you @ReubenBond
