### ISSUE TITLE
GrainFactory in IIncomingGrainCallContext 

### ISSUE THREAD

**Issue by meisamhasani** [dotnet/orleans#9077]
hello
how do i have GrainFactory forcall grains into a :
Task Invoke(IIncomingGrainCallContext context)

**Comment by ivanvyd** [comment]
Hello @meisamhasani,

if we are talking about grains interceptors, there are multiple ways to access the `GrainFactory` from `Invoke` method.

1. If **Call Filter** is being implemented on the `Grain` level, you can simply use `GrainFactory` from base grain class.
2. If **Call Filter** is silo-wide, then it is possible to:
2.1. inject `GrainFactory` using DI;
2.2. get `GrainFactory` from `IServiceProvider`, that can be accessed via `IGrainContext`:
```cs
IGrainFactory grainFactory = context.TargetContext.ActivationServices.GetService<IGrainFactory>();
```

> [!WARNING]
> Be careful with calling grains from interceptor, you might face with **deadlocks** or **recursion**. For instance,
> 1) calling Grain A
> 2) executing interceptor for Grain A
> 3) **_calling Grain B from interceptor_**
> 4) **_executing interceptor for Grain B_**

If you still have questions, please provide more details about your problem and share the snippet.

**Comment by ReubenBond** [comment]
@ivanvyd great answer!

**Comment by meisamhasani** [comment]
thank you @ivanvyd
