### ISSUE TITLE
II don't understand why a CodecNotFoundException is thrown

### ISSUE THREAD

**Issue by paxhujing** [dotnet/orleans#9105]
![image](https://github.com/user-attachments/assets/d7113ce3-9a51-4a4c-86ce-e7688e070916)

**Comment by ledjon-behluli** [comment]
Does the project reference the Sdk package?

**Comment by paxhujing** [comment]
> Does the project reference the Sdk package?

Yes. Clear and rebuild solution, the problem disappears
