### ISSUE TITLE
how do i balance resource usage?

### ISSUE THREAD

**Issue by meisamhasani** [dotnet/orleans#9162]
hi
I have 10 Grain, each of which uses 2 GB of RAM. 
I have 5 nodes in Kuber cluster, which has a silo on each node.
With what strategy can I activate exactly 2 grain on each silo? to balance the consumption of resources.
@ReubenBond

**Comment by scalalang2** [comment]
Please refer [Grain placement](https://learn.microsoft.com/en-us/dotnet/orleans/grains/grain-placement) feature.
Intuitively, You can use hash-based placement approach.

I'll drop my opinion here.
- Only lookcing at RAM is not a good indicator for balancing resource consumption.
- Designing a Grain holds huge amount of RAM is not recommended. 
    - In the most of cases, loosely-coupled large number of small grains are preferred.
    - see also. [Best practices in Orleans](https://learn.microsoft.com/en-us/dotnet/orleans/resources/best-practices)
