### ISSUE TITLE
[question] Isn't GC a problem on high-load servers?

### ISSUE THREAD

**Issue by xeynyty** [dotnet/orleans#9215]
It's a stupid question, but it might be interesting.

I am interested in comparing Orleans with Beam (Erlang VM), in which garbage collection is performed on each thread separately and the system never stops completely.

Isn't the garbage collector in dotnet a problem when working with actors? Won't it create significant pauses in silo's work? 
Thank you in advance.

**Comment by SebastianStehle** [comment]
It really depends on your workload. The GC is really fast, but it can block requests. What I cannot recommend is to have workloads with a lot of long living objects and a lot of per request allocations. This went horribly wrong last time (but it was about 10 years ago).
