### ISSUE TITLE
CodecNotFoundException: HybridCache and migrating from IDistributedCache to use Orleans

### ISSUE THREAD

**Issue by joshcornejo** [dotnet/orleans#9251]
I have a set of controllers that interact in tandem or independently with different front-end components. As they interact, the controllers populate a Redis cache (which was easily moved to use [HybridCache](https://learn.microsoft.com/en-us/aspnet/core/performance/caching/hybrid?view=aspnetcore-9.0)), none of them would particularly benefit from migrating to Orleans.

Orleans is relevant to one controller where changes happen and have to be done in sequence, the problem I have is that within the grain, I need to reference the HybridCache (or IDistributedCache?) to access those values populated by the other controllers.

I have tried all sorts of things (pass an object, the controller instance, an IDistributedCache, or a HybridCache), and I keep running into the serialisation exception, which is fair enough. Still, I've run out of ideas unless I move all of the other controllers to use Orleans.

```
An unhandled exception has occurred while executing the request.
      Orleans.Serialization.CodecNotFoundException: Could not find a copier for type Microsoft.Extensions.Caching.Hybrid.Internal.DefaultHybridCache.
```

Ideas welcome!

**Comment by ledjon-behluli** [comment]
It sounds to me like you are passing a `HybridCache` object to the grain's method, is that correct?

**Comment by joshcornejo** [comment]
That is correct.

But I've refactored the code, so I don't have to pass any non-serialisable object anymore.

For now, I've gone for a static variable inside the class implementing the Grain's interfaces - seems to work fine for now.

**Comment by ledjon-behluli** [comment]
@joshcornejo why don't you simply inject it into the grain's constructor?

**Comment by joshcornejo** [comment]
A good idea, but for now, it is all working and I can test with it being a static variable.
