### ISSUE TITLE
Turn IGatewayListProvider.GetGateways() into a Task-based method

### ISSUE THREAD

**Issue by veikkoeeva** [dotnet/orleans#927]
As per comment [related to another issue](https://github.com/dotnet/orleans/pull/923#issuecomment-149649160), there is no good reason for [IGatewayListProvider.GetGateways()](https://github.com/dotnet/orleans/blob/fc0af9079413505de6c5dad928a266fccda74d68/src/Orleans/Messaging/IGatewayListProvider.cs#L47) to be non-async.

**Comment by dVakulen** [comment]
I'm on it.

**Comment by veikkoeeva** [comment]
:+1:

**Comment by sergeybykov** [comment]
Resolved by https://github.com/dotnet/orleans/issues/928.
