### ISSUE TITLE
1.0 + Road Map

### ISSUE THREAD

**Issue by GavinOsborn** [dotnet/orleans#93]
We're evaluating Orleans for suitability in an upcoming project, it certainly ticks a lot of boxes for us.

One sticking point at the moment though is around current project status and where it might go from here. 
1) How close are we to a 1.0 release?
 - What is left to do before 1.0?
 - Given the above, were we to adopt 0.9 now, how much friction do you anticipate in moving to 1.0

2) What is the Road Map for the framework?
 - Once 1.0 is out, where does the project go from here?
 - Are there plans to continue pushing it forward or is it your intention to hand it over to the community?

Thank in advance.

**Comment by sergeybykov** [comment]
>1)How close are we to a 1.0 release?

We are there for all practical purposes. Minor technicalities and some last minute renaming slowed us down a bit.

>•What is left to do before 1.0?

Code-signing and publishing on the NuGet packages

•Given the above, were we to adopt 0.9 now, how much friction do you anticipate in moving to 1.0

I'd suggest to start right with 1.0. Lust build it from master and install the msi. No reason to go back to 0.9.

2) What is the Road Map for the framework?

We discussed it at the virtual meetup - https://www.youtube.com/watch?v=D4kJKSFfNjI.

•Once 1.0 is out, where does the project go from here?
•Are there plans to continue pushing it forward or is it your intention to hand it over to the community?

The intent is to move it forward. In fact we hope to accelerate the pace and widen the scope of improvements and features with the help of the community.

**Comment by gabikliot** [comment]
I would like to repeat and stress what Sergey said:
We, the Microsoft Orleans team, plan to continue actively develop the project, on GitHub, in a fully transparent way, in the best spirit of the Open Source Community.
Not only we plan to fix bugs and make incremental improvements, but we are also actively working on a number of new, big and important features. One of them being the streaming extensions for Orleans grains that allow building reactive applications. Another one is in place upgrade. And a number of other big capabilities. Some of those new capabilities are done in collaboration and with help of other people in Microsoft and Microsoft Research. And of course we are highly welcoming any help and contributions from the community.

**Comment by sergeybykov** [comment]
Just posted v1.0.0 - https://github.com/dotnet/orleans/releases/tag/v1.0.0.

**Comment by GavinOsborn** [comment]
:thumbsup:
