### ISSUE TITLE
LRU.Add O(n) algorithm complexity?

### ISSUE THREAD

**Issue by tupunco** [dotnet/orleans#94]
[LRU.cs#L113.Add](https://github.com/dotnet/orleans/blob/master/src/Orleans/Utils/LRU.cs#L113)

The problem for :[LRU.cs#L193](https://github.com/dotnet/orleans/blob/master/src/Orleans/Utils/LRU.cs#L193)

**Comment by gabikliot** [comment]
Hi

Yes, you are right that LRU Add has a linear worst case complexity.
The reason I am not worried about is:
The linear scan happens only if/when we need to evacuate an object from the full LRU cache. There are 2 usages of LRU currently in the runtime, in both the default configuration is bigger than what we expect this cache to grow, essentially making this LRU not really a cache but rather a full collection. The reason we still want the LRU  is for protection.

I do agree that in general improving the complexity in this case would be nice, but it is not high priority. Please also notice that probably a much more important perf. consideration is that the internal cache is ConcurrentDictionary, so it can be accessed without grabbing a global lock. At least one of the usages of this cache, for directory cache, is indeed in a highly concurrent usage pattern. Therefore, improving the Add complexity will need to take this into account. If we simply replace the ConcurrentDictionary with SortedDictionary or something similar, but will need to grab a lock on every Get and Add, I suspect the overall perf. will degrade.

All the above said, if you would like to take a shot at improving this, while still maintaining the fine grained locking like  ConcurrentDictionary is doing, we would gladly review and accept this pull request.

**Comment by tupunco** [comment]
OK, thx, not a common LRU_cache collection.
