### ISSUE TITLE
Bring internal Microsoft projects built on Orleans to GitHub

### ISSUE THREAD

**Issue by veikkoeeva** [dotnet/orleans#941]
From time to time somebody wonders if it were possible to bring currently internal Microsoft projects utilizing Orleans to GitHub. [Today was such a day](https://gitter.im/dotnet/orleans?at=562e130d5e0024c823b6f74c) again, [Horton](http://research.microsoft.com/en-us/projects/ldg/) was specifically mentioned. Are there other projects?

**Comment by ReubenBond** [comment]
CodeBook is another project. There are also numerous pieces of code which people have written over the years, such as the `GraphPartitioningPlacementStrategy` and I'm sure much more.

**Comment by gabikliot** [comment]
Codebook is not our code. It was an application that used Horton. Graph Partitioning was an intern project. It was a code inside the Orleans runtime. We could in theory potentially bring it as a branch. 

I am not sure we want to just throw out everything we had during the years. There have been a lot of prototyping, things that didn't quite work. We better pick the parts that are valuable and there is a chance that someone else might advance them.

PAD project comes to mind (performance anomaly detection paper).
