### ISSUE TITLE
Could grain calls be made fail earlier if silo fails or shuts down before the grain call timeout?

### ISSUE THREAD

**Issue by veikkoeeva** [dotnet/orleans#942]
Opened from discussion in [Orleans Gitter thread](https://gitter.im/dotnet/orleans?at=562e1bf5f67aa4d236ca5ca8).

Copied from what @gabikliot writes via phone:
> Basically, already now, if the msg was sent to a silo that lets say 10 sec later was voted dead, this msg will still timeout only after 20 sec later (30,sec from the original send). We can easily add a logic to break it earlier. Should be pretty trivial. If you open an issue, u can describe how to do that.
I can describe how to do that.

@ReubenBond believes this would help to support https://github.com/dotnet/orleans/issues/940 too.

**Comment by ReubenBond** [comment]
Thank you, @veikkoeeva :)

This will help us to support #940 by allowing us to reliably determine when a silo will no longer produce values to an Observable. It will also help us to remove the Message Timeout if it is so desired and have long-running grain calls - I'm not sure that's particularly useful/necessary, but it's good to have.

**Comment by gabikliot** [comment]
I can provide details about this is a week, when I am back at the computer.

**Comment by gabikliot** [comment]
OK, the way this can be done is the following:

**On the silo**:
`Catalog` is already a listener to membership events. It gets notified every time membership changes. So in this place: https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Catalog/Catalog.cs#L1281 (before we deactivate all activations for which the failed silo is a primary directory partition) we can check if the `updatedSilo` is dead. Only if it is dead (not shutting down or stopping, just Dead), call a new method on `InsideGrainClient`, something like `BreakAllOutstandingMessagesToDeadSilo`.
`InsideGrainClient.BreakAllOutstandingMessagesToDeadSilo` will scan the dictionary of all outstanding requests whose destination is the dead silo. The requests are stored in `ConcurrentDictionary<CorrelationId, CallbackData> callbacks`, so just compare `CallbackData.Message.TargetSilo` with the silo address of the dead silo. For all matching requests call the new method `CallbackData.Fail`, which should basically mimic the `CallbackData.OnTimeout`: check if not already disposed, dispose timer,  unregister, and call a callback with error response. The main difference will be the exception that is used to generate the error: not timeout exc, but some other Orleans Exc.

**Test**:
Need to create a test just for that. 2 silos, send request from a grain on one tom another, kill the silo, and check that the call is throwing with the right exception: not TimeoutExc, but the new one. Before the change it will be throwing TimeoutExc.

**Client**:
TBD.

**Comment by dVakulen** [comment]
I'd like to take this one.

**Comment by gabikliot** [comment]
:-)
Let me know if you have any questions! I kind of compiled it in my head, so there might be something I missed.

**Comment by dVakulen** [comment]
What a pity that there's no ability to make commit from the head.

**Comment by gabikliot** [comment]
This has now been fully implemented  @reubenbond. Thanks to @dVakulen for the implementation!

**Comment by sergeybykov** [comment]
+1 @dVakulen That was just great!
