### ISSUE TITLE
Geo-Distribution Project

### ISSUE THREAD

**Issue by sebastianburckhardt** [dotnet/orleans#948]
Let's use this issue to discuss the proposed geo-distribution features, and to track progress.

Also see:
- Virtual Meetup: https://www.youtube.com/watch?v=fOl8ophHtug
-  preliminary documentation (including slides, API documentation, and a research paper draft) is at https://github.com/sebastianburckhardt/orleans/tree/geo-docs/geo/docs

**Comment by johnkattenhorn** [comment]
I know I'm not supposed to say thanks, but thanks @sebastianburckhardt, we can't wait to get our hands on the code :-)

**Comment by sebastianburckhardt** [comment]
Ok, code is here! Sorry for the long delay - I had to separate out the parts that are ready to release, and  break them into branches. Here is a description of the branches and how they are related:
  - **geo-multiclusternetwork** contains code for configuration and operation of multi-cluster-network, and for explicit calling of grains in remote clusters. 
  - **geo-graindirstruct** contains a refactoring of the grain directory structure (reduces code duplication in local and remote grain directories) and introduces a mechanism for choosing the multi-cluster registration strategy.
  - **geo-globalsingleinstance** contains the implementation of the global single-instance grain. It depends on geo-graindirstruct.
  - **geo-queuedgrain** contains the QueuedGrain API, defines replication providers, and contains one such provider (which can wrap a regular storage provider). It depends on geo-multiclusternetwork.
  - **geo-docs** contains documentation
  - **geo-samples** contains all the other branches taken together, and also some Azure samples for the single-instance grain and for the queued grain.

**Comment by sebastianburckhardt** [comment]
FYI: I have added an experimental branch showing how one may provide an event-sourcing interface (journaledgrain) on top of the replication provider abstraction.

https://github.com/sebastianburckhardt/orleans/tree/geo-journaledgrain

It is not tested, and there are lots of things that can improved. But at least it shows how things can be hooked together.

**Comment by veikkoeeva** [comment]
A modest question, is there documentation on how this affects storage? I see there is `IGossipChannel` and `AzureTableBasedGossipChannel`, but is there yet further information available? I think we should record issues for relational backend and ZooKeeper for adding the necessary structures.

**Comment by sebastianburckhardt** [comment]
An update on where we stand. We currently have two independent PRs open.

- #1800 is adding global-single-instance support. It's not quite finished - there are some open issues. Once resolved, this will be the first significant use of multi-cluster.
- #1488 adds log view providers. These represent the common functionality used by queued grains and event sourcing. Its use is not restricted to multi-cluster scenarios - it has benefits for single cluster as well. Once in, #1488  will unlock the next PRs for queued grain (likely going to be renamed, e.g. VersionedGrain) and for event sourcing.

Once #1488 is in, we can add event sourcing support easily - just add a syntactic layer on top to create the JournaledGrain API, and add log view provider at the bottom to interface with event stores. We already have a draft of this working (thanks to contributions by @jkonecki early this year).

**Comment by veikkoeeva** [comment]
@sebastianburckhardt It looks like #1488 isn't the issue you would like to reference here.

**Comment by sebastianburckhardt** [comment]
@veikkoeeva You are of course correct. I have updated the comment.

**Comment by jason-bragg** [comment]
Feature has been merged.
