### ISSUE TITLE
Failure to clean up stale directory entries

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#954]
If unregistration from directory of garbage collected activations fails (we've seen it happening a couple of times in production because of network connectivity issues), the directory entry for an activation that we failed to removed is supposed to be cleaned up upon receiving a NonExistentActivation response for a next call to that grain.

The cleanup code has a protection from a message ordering race via the configurable 'maturity' time for directory entry (by default it is 1 minute). There appear to be a bug in the condition of 'maturity' check that prevent the stale activation entry from ever being removed after when it's older than the 'maturity' period.

The condition on https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/GrainDirectory/GrainDirectoryPartition.cs#L135 should be `<=` rather than `>=`.

**Comment by gabikliot** [comment]
Good catch!

I looked at the code now and at this comment in dispatcher and I wander if we need this maturity check at all. Appears redundant. Not very harmful (except when there was this bug of course) but redundant. I don't see how this race is possible , but even if it is, the unregister will just not unregister anything if it arrives before register.

**Comment by sergeybykov** [comment]
I see that `Failed MissingActivation_2` test is failing with this fix. I suspect it's unrelated because it tests invalidation of directory cache. Still peculiar why.

**Comment by gabikliot** [comment]
It might be related. There were also 2 direct tests for the behavior here. Not sure how they were passing with the bug.

**Comment by sergeybykov** [comment]
This was a bug in the test - it relied on the incorrect timing condition to remove 'immature' activations from directory.

**Comment by sergeybykov** [comment]
Resolved by https://github.com/dotnet/orleans/issues/955.
