### ISSUE TITLE
Timer Documentation [Documentation]

### ISSUE THREAD

**Issue by pnzrdrgoon** [dotnet/orleans#956]
There's a nice comment in regards to timer period in SafeTimerBase that would be nice to surface to the documentation, please?
> "Specify negative one (-1) milliseconds to disable periodic signaling",

**Comment by veikkoeeva** [comment]
@pnzrdrgoon Good catch! This is [Timeout.InfiniteTimeSpan](https://msdn.microsoft.com/en-us/library/system.threading.timeout.infinitetimespan(v=vs.110).aspx), by the way.

> For threading methods that accept a timeout parameter of type TimeSpan, such as Thread.Sleep(TimeSpan) and Thread.Join(TimeSpan), this value is used to suspend the thread indefinitely. However, in most cases, we recommend that you use other System.Threading classes such as Mutex, Monitor, EventWaitHandle, or Semaphore instead to sychronize threads or manage resources.
>
>The value of this field is -00:00:00.0010000, or -1 millisecond.

Maybe the comment should be rephrased and then surfaced? There is also another piece of documentation, albeit with regards to reminders and their implementation [here](https://github.com/dotnet/orleans/issues/637#issuecomment-124152405). I think I'll add it to the SQL script at some point, maybe to the documentation too if I find a place for implementation notes. :)

**Comment by pnzrdrgoon** [comment]
Timeout.InfiniteTimeSpan may just be what I needed.  Thanks for the help!
