### ISSUE TITLE
Contribution idea: Upgrade application binaries via Orleans Streams

### ISSUE THREAD

**Issue by creyke** [dotnet/orleans#958]
Provide the facility within Orleans to propagate and reload updated application binaries programmatically via Orleans Streams.

**Comment by sergeybykov** [comment]
Why streams? Why not, for example, put new binaries to a blob store, and point Orleans to them to perform an upgrade?

**Comment by creyke** [comment]
Blob storage is valid... there is potentially one less dependency by using streams? From an application developer perspective it's tempting to inject binaries directly into the cluster via an Orleans client. This could potentially scale well to geo distributed clusters without shared global connectivity to a shared file storage.

**Comment by sergeybykov** [comment]
The purpose of Orleans Streams is to deliver series of messages (events) for a particular logical context. In most cases the logical (virtual) streams are implemented over persistent queues that require their dependencies and configuration.

It is possible to use SMS streams that are not persistent. What would be a message in this case? An assembly binary? It probably doesn't make a lot of sense to cut them into chunks. But then we could as easily do the same via direct grain calls, e.g. via the ManagementGrain.

The blob option is a popular one. It is a well understood pattern. BigPark folks built their deployment solution for Orleans using blob as well.

**Comment by jason-bragg** [comment]
I tend to agree with Sergey here.  Orleans streams interfaces don't preclude things like this but the supporting infrastructure has been developed with event delivery in mind, and will not likely be a good fit for binary distribution.  Sending some sort of 'update binaries to version N' event, which when received loaded binaries from some backend store would be more suited to Orleans streams.

**Comment by creyke** [comment]
Makes complete sense. Closing issue but it would be great to see the blob process standardised.
