### ISSUE TITLE
TestingSiloHost with StartFreshOrleans

### ISSUE THREAD

**Issue by sxam** [dotnet/orleans#962]
Hi guys,
When trying to make my tests run with SiloConfigFile, StartPrimary = true, StartSecondary = false, StartFreshOrleans = false (in order to speed it up), the second tests (if I run more than one in a single test run) has GrainFactory member as null when trying to access it. 

I overcome this problem by using GrainClient.GrainFactory (which is ok) but its still something worth fixing (unless, of course, I did something wrong in my usage).

**Comment by sergeybykov** [comment]
What `GrainFactory` are you referring to? Client code (tests code in unit tests) is supposed to be accessing `GrainFactory` via `GrainClient.GrainFactory` by design.

**Comment by sxam** [comment]
But in my test class (which inherits from TestingSiloHost ) GrainFactory member is available. ( public IGrainFactory GrainFactory { get; } ). So if I am supposed to go through GrainClient.GrainFactory only, what is GrainFactory member for?

**Comment by sergeybykov** [comment]
I see. You should be able to use `TestingSiloHost.GrainFactory` then. It seems to me it should be static to match static `Primary` and `Secondary`. Can you change that and try?

**Comment by sxam** [comment]
"Can you change that" - change where exactly? In Orleans TestingSiloHost source code?

**Comment by sergeybykov** [comment]
Yes - https://github.com/dotnet/orleans/blob/master/src/OrleansTestingHost/TestingSiloHost.cs#L80.

**Comment by sxam** [comment]
Ok, I will do it next week.

**Comment by sxam** [comment]
Created a pull request with those the small changes.
