### ISSUE TITLE
Streaming feature documentation

### ISSUE THREAD

**Issue by pherbel** [dotnet/orleans#98]

**Comment by veikkoeeva** [comment]
:+1:

**Comment by MovGP0** [comment]
:ok_hand:

**Comment by veikkoeeva** [comment]
A late suggestion, but I'd like to have one where the streams are used to messaging to and from a silo with an "outsider".

**Comment by gabikliot** [comment]
@veikkoeeva This is already supported. The streams can be used in exactly the same way both inside grains and on the client. We will add sample unit tests to show how to do that. This will also allow to completely substitute Observers with streams.

**Comment by veikkoeeva** [comment]
[Link to streaming documentation Wiki page](https://github.com/dotnet/orleans/wiki/Orleans-Streams). Is there more to come or should we close this for now? :)

**Comment by sergeybykov** [comment]
Yes, there is more to come. This is an early draft. Will close this once we add a link to it to the Documentation page. :-)

**Comment by gabikliot** [comment]
And here it goes ... [Orleans Streams] (https://github.com/dotnet/orleans/wiki/Orleans-Streams)! It is linked in the wiki pages from [Documentation](https://github.com/dotnet/orleans/wiki/Documentation).

**Comment by jkamstra** [comment]
Very nice. Very nice indeed. Thanks team Orleans.

Need to take this out for a spin shortly.

**Comment by yevhen** [comment]
Would be nice to expand it on implementing custom stream provider. I'd like to implement one for event streams stored in Azure Table Storage.

**Comment by richorama** [comment]
great start - would be good to see some more code snippets...

Shame you can't PR wiki pages.

**Comment by gabikliot** [comment]
@yevhen This is out plan. At the first step we want to refactor the QueueAdapters, so its easier to build new ones. The 2nd phase would be to simplify the stream providers interfaces. One can write a new stream provider now, by following on the examples of SMS and AQ, but he will find it a bit cumbersome and complicated I think. Our highest priority was to release the stream themselves, so people can write application that use stream. Polishing the extensibility points is the 2nd priority, which we are at now.

@richorama  We fully agree. We think the right thing is to move the documentation from the wiki pages to somewhere better. It is also item 7 on [Ideas-for-Contributions](https://github.com/dotnet/orleans/wiki/Ideas-for-Contributions) "Migrate documentation from Wiki to HTML-based solution (GitHub pages) [Small/Medium]". We currently don't have time to do that, and any help would be appreciated!

**Comment by yevhen** [comment]
@gabikliot cool!

**Comment by pherbel** [comment]
It's very useful. Thanks guys.
