### ISSUE TITLE
Edge Grain Strategy 

### ISSUE THREAD

**Issue by bstead** [dotnet/orleans#984]
Im hoping someone can give me a hand with a general sanity check on how I pass data to my edge grains. We receive our messages from a 3rd party ESB(java) that can send messages over tcp or write to our mongo db directly.(or call a WS, etc.) The current plan is to create a persistentstreamprovider that feeds itself from the mongodb. The alternate option that I considered was to create a simple tcp listener that fed a stateful(mongo storage provider) edge grain. This application will receive 10 transactions/second initially and will need to perform parsing/rules processing in near real-time, but we expect that the throughput to scale linearly and the processing to scale somewhat exponentially as we add customers.(the average message size is ~30kb) I considered creating an orleans client layer(perhaps webapi), but I was hoping to avoid the need to manage another possible point of failure. There are times in which I will need to refeed old transactions and I do need this system to be durable, so I was really leaning toward the db-driven approach as it seems I could handle re-feeding old messages, re-feeding unprocessed messages(after a fatal system failure), and feeding new messages all from the same queue. Im a little concerned about the performance hits I may take by adding the overhead of a polling pull, but maybe Im trying to overengineer this...Any guidance/thoughts are much appreciated!

**Comment by jason-bragg** [comment]
Questions:
    In processing (or reprocessing) messages from mongodb, does order matter?
    How tolerant is your message processing to duplicated messages?

**Comment by bstead** [comment]
Order does not matter and I think we can handle dupes at every stage in the processing....To the point where if the system went down and some messages were mid-process, re-feeding them completely could produce the same result.

**Comment by sergeybykov** [comment]
So effectively you are considering using MongoDB as a persistent queue, right? That's a sensible design to me if you want to receive those messages from the 3rd party and persist on your side.

The alternative without a queue is for the 3rd party to send (and resend if necessary) those messages to your HTTP frontend with an Orleans Client. The benefit of this approach is that you would not only eliminate MongoDB from the picture (fewer moving parts), but you could reduce latency, and have a way return meaningful responses (e.g. results of processing) to the sender. The downside is that you'd lose the loose coupling property of the solution with a queue.

Of course, this completely depends on what kind of system you have on the other end and what the requirements are. I'm not suggesting this as a better solution, only using it for a comparison.

**Comment by bstead** [comment]
Thanks a lot for your help. I think we are on the same page.

Im going to go with the Mongo approach for now since Ill need something similar anyway to refeed old messages and I am up against an ambitious deadline. (At times we will change how we process messages and will need to parse new data from the old data.) I may need to reassess immediately upon testing :) but, hopefully this gets the job done.

**Comment by jason-bragg** [comment]
Processing data from mongoDB, two options come to mind.

**Work Dispatcher Role**
Develop an Orleans Client role that reads from mongoDB and dispatches work to the Orleans silo worker roles.  This is very strait forward, but you'd need to write your own message dispatching, replay, and error handling logic.  This may also include availability issues like dealing with rebalancing responsibilities when reader roles become unavailable for extended periods of time.

**Streams**
The streaming interfaces support your needs, but the out-of-the-box stream providers don't fully support your scenario.  This means you'd probably need to build your own stream provider (I would suggest a modified version of the PersistentStreamProvider).

*Considerations*
* The existing PersistentStreamProvider enforces ordered delivery, which may work for your environment but is not necessary and could introduce processing delays, especially when errors occur (poison message problem for instance).
* The existing PersistentStreamProvider supports only limited rewind/replay capabilities.  It can replay recent events from a message cache, but if events are no longer in the message cache, the replay attempt will not go back and reread them from the store (mongoDB).

The PersistentStreamProvider could be customized to address these capabilities allowing you to take advantage of much of the stream processing infrastructure (queue balancing, subscription management, event delivery, recovery/error handling).  It should be noted that while the stream processing infrastructure is being used in large scale production environments, it is one of the newest Orleans feature sets, so it has not as mature as much as the virtual actor model.

**Comment by bstead** [comment]
Thanks for the details on this. Given the feedback and some further research/testing, Ive decided to start with a simpler approach using actors. 

Ideally, Id like to begin dispatching work on silo startup.Since this is an on-premise system, roles did not appear to be an option for me. It sounds as if a windows service to pass messages to the grains would be the advisable alternative? I also considered kicking off a timer on init(or bootstrapping it). This seemed straight forward(but perhaps messier). Am I missing something that may be more applicable here for on-premise solutions?

**Comment by jason-bragg** [comment]
>"Am I missing something that may be more applicable here ...?"

Not that I can see.

>"It sounds as if a windows service to pass messages to the grains would be the advisable alternative?"

This seems comparable to the 'Work Dispatcher Role' approach raised previously.  A windows service as an Orleans client could read from MongoDB and dispatch the processing to grains distributed among Orleans Silos. I think this is a reasonable approach.  It's really a question of tradeoffs, but this is probably the more strait forward approach.

**Comment by sergeybykov** [comment]
@bstead Feel free to reopen if needed.
