### ISSUE TITLE
List who uses Orleans in production

### ISSUE THREAD

**Issue by pherbel** [dotnet/orleans#99]

**Comment by MovGP0** [comment]
I guess currently that's only 343 Industries.

**Comment by ReubenBond** [comment]
There are more. We use it in production for example, & I know of others.

**Comment by gabikliot** [comment]
There are multiple (at least 10) production usages within Microsoft, in various groups and divisions, a lot of them are unrelated to gaming.
And multiple usages outside Microsoft.

**Comment by pherbel** [comment]
I guess that it is good to know and help if somebody is thinking about the usage. like [node.js usage list](https://github.com/joyent/node/wiki/Projects,-Applications,-and-Companies-Using-Node)

@gabikliot Could you please create a list about the Microsoft usage if it is not confidential?
@ReubenBond and others would expand this list later.

**Comment by sergeybykov** [comment]
At least some internal Microsoft usages are confidential for various reasons. To err on the safe side, we need to treat them all as confidential, unless the product groups themselves decide to speak up.

**Comment by wmattlong** [comment]
We used Orleans on an interesting High Altitude Balloon experiment, http://pegasusmission.com, to perform real-time IOT from 85K ft in the upper atmosphere.  Orleans allowed to be not only transfer telemetry from our high altitude payload to a Web site in ~20ms, it also allowed us to control operations during the flight in the remote and hostile environment of Near Space (10km-200km) above the surface of the earth. Additionally, we used Orleans to help track the payload in real-time on an updateable Bing Map.   Blog posts, photos, and video are on the site mentioned above.

**Comment by pherbel** [comment]
I've created a md file for this list. You can find here: [List] (https://github.com/pherbel/orleans/blob/list_of_orleans_usage/Projects-Applications-and-Companies-Using-Orleans.md)
I don't know which is the right place for this maybe the wiki.
@gabikliot Could you put it into the wiki?
Thanks

**Comment by gabikliot** [comment]
Thank you.
Lets host it as an md file under https://github.com/dotnet/orleans/tree/master/misc.
That way others will be able to submit pull requests against it (I don't think one can submit pull request against Wikis right?).
Can you please submit a PR to include this file in Orleans/misc?

**Comment by gabikliot** [comment]
I guess we can close this issue now. Thank you @pherbel!
