### ISSUE TITLE
How to use ImplicitStreamSubscriptions ?

### ISSUE THREAD

**Issue by angshuman-agarwal** [dotnet/orleans#994]
Hi,
I was going through the _MultipleImplicitSubscriptionGrain_ UnitTest. What is the exact use case for _ImplicitStreamSubscription_ attribute if we have to do explicit subscription to each in the class ? Will be useful if I can mark the composite class by passing the Stream names / provider in the attribute and it automatically does the subscription (i.e. I do not write the boilerplate code).

Sorry, if my understanding is wrong.

regards
Angshuman

**Comment by gabikliot** [comment]
http://dotnet.github.io/orleans/Orleans-Streams/Streams-Programming-APIs

**Comment by jason-bragg** [comment]
@gabikliot +1

I definitely recommend the link Gabriel provided, but the short answer is that the application developer must provide an observer to the stream subscription, which means subscribing to the stream.

Simplifying this to some automatic pattern would be nice, but would likely only work for specific cases.  Someone may add that for the most common use cases, but as of yet, no one has contributed auto-wiring of subscriptions.  (hint, hint, nudge, nudge, :] )

**Comment by gabikliot** [comment]
:+1:  for  "someone" contributing code for automatic declarative stream subscriptions.

**Comment by jason-bragg** [comment]
@angshuman-agarwal I apologize, I missed your primary question
>"What is the exact use case for ImplicitStreamSubscription attribute"

With explicit subscriptions something must know that there is a stream that one wants to subscribe to, and a grain call must be made to trigger the subscription logic.  Implicit subscriptions main value is allowing the stream activity to trigger the grain activation (hence triggering the subscription).

For instance, using sms streams, if a grain wanted to write to a stream and have another grain process the stream, it might get an observer for the stream, then make a grain call to the consumer grain, telling it to subscribe to the stream, then it can start sending events.  This means the producer would need to know about the consumer, which kinda sucks.  Instead, using implicit subscriptions, the producer can just start producing events onto a stream, and the consumer grain will automatically be activated and subscribe to the stream.  In that case, the producer doesn't care at all about who is reading the events.

**Comment by gabikliot** [comment]
Jason, do you think we need to update the documentation that describes implicit subs. with what you write above, or is it ok now as it is?

I would encourage us to constantly improve the docs every time we find ourselves describing things in the issue that are better be in the docs.

**Comment by jason-bragg** [comment]
>"Jason, do you think we need to update the documentation that describes implicit subs"

Good question, but I think I'm to close to the subject to be objective.
@angshuman-agarwal, After reading the documentation, did implicit subscriptions make sense, or was my further clarification necessary?

**Comment by angshuman-agarwal** [comment]
yea makes sense when I read alongwith this link - http://dotnet.github.io/orleans/Orleans-Streams/Streams-Programming-APIs

**Comment by gabikliot** [comment]
I have updated the docs with some of @jason-bragg 's writeup from above.
Closing the issue as it was answered.

**Comment by angshuman-agarwal** [comment]
Thank you

**Comment by odises** [comment]
> http://dotnet.github.io/orleans/Orleans-Streams/Streams-Programming-APIs

The link is broken.

**Comment by sergeybykov** [comment]
THe doc page moved to http://dotnet.github.io/orleans/Documentation/streaming/index.html.
