### ISSUE TITLE
VS 2015 Quick Actions not working

### ISSUE THREAD

**Issue by peter-perot** [dotnet/orleans#996]
Hi folks,

I have a problem with VS Enterprise 2015 (14.0.23107.0 D14REL) and the context menu **"Action..."**.

Let's start from scratch. Hint: Microsoft Orleans Tools (1.0.10) for VS is already installed.

1) Start VS.

2) Create a new grain interface project *GrainInterfaces.csproj* with the template and save the solution.

3) Interface *IGrain1* looks like this:

````c#
public interface IGrain1 : IGrain
{
}
````
4) Compile.

5) Add a new grain class project *GrainClasses.csproj* with the template.

6) Class *Grain1* looks like this:

````c#
public class Grain1 : Grain, IGrain1
{
}
````

7) Trying to compile will result in an error. That's ok so far.

8) In project *GrainClasses.csproj* add a reference to *GrainInterfaces.csproj*.

9) In class *Grain1* set focus on *IGrain1* and press **CTRL+.** ("control" and "period"). This should throw up a menu like **"Implement interface"**, but it doesn't. Strange behavior: The class *Grain* where I derive from is displayed in black color instead of blue.

10) Restart VS. But this does not fix it.

11) Unload *GrainInterfaces.csproj* and edit the XML file like this:

Change

````xml
<Import Project="$(SolutionDir)packages\Microsoft.Orleans.Templates.Grains.1.0.10\build\Microsoft.Orleans.Templates.Grains.targets" Condition="Exists('$(SolutionDir)packages\Microsoft.Orleans.Templates.Grains.1.0.10\build\Microsoft.Orleans.Templates.Grains.targets')" />
````

to

````xml
<!-- <Import Project="$(SolutionDir)packages\Microsoft.Orleans.Templates.Grains.1.0.10\build\Microsoft.Orleans.Templates.Grains.targets" Condition="Exists('$(SolutionDir)packages\Microsoft.Orleans.Templates.Grains.1.0.10\build\Microsoft.Orleans.Templates.Grains.targets')" /> -->
````

12) Reload the project.

13) Close the solution.

14) Open the solution.

15) In class *Grain1* set focus on *IGrain1* and press **CTRL+.** ("control" and "period"). Now it works.

16) Unload *GrainInterfaces.csproj* and edit the XML file like this:

Change

````xml
<!-- <Import Project="$(SolutionDir)packages\Microsoft.Orleans.Templates.Grains.1.0.10\build\Microsoft.Orleans.Templates.Grains.targets" Condition="Exists('$(SolutionDir)packages\Microsoft.Orleans.Templates.Grains.1.0.10\build\Microsoft.Orleans.Templates.Grains.targets')" /> -->
````

to

````xml
<Import Project="$(SolutionDir)packages\Microsoft.Orleans.Templates.Grains.1.0.10\build\Microsoft.Orleans.Templates.Grains.targets" Condition="Exists('$(SolutionDir)packages\Microsoft.Orleans.Templates.Grains.1.0.10\build\Microsoft.Orleans.Templates.Grains.targets')" />
````

17) Reload the project.

18) Compile.

Now everything is ok.

To make things even stranger: I have the same problem with VS 2013 which is installed on a different machine. Here the menu **"Implement Interface"** is missing. The workaround is the same as with VS 2015.

All my colleagues in our company have the same problem.

Cheers
Peter

**Comment by sergeybykov** [comment]
Peter, this is strange. Are you essentially saying the issue goes away if you turn code generation build targets off and then back on? Or did I misunderstand?

**Comment by amamh** [comment]
I think the codegen completely screws up VS intellisense. ReSharper works just fine, but I don't use that either because it slows down everything.

**Comment by sergeybykov** [comment]
Is this with 1.0.10 or 1.1.0-beta1 or both?

**Comment by peter-perot** [comment]
Hi Sergey!

Ø  Peter, this is strange. Are you essentially saying the issue goes away if you turn code generation build targets off and then back on? Or did I misunderstand?

Yes, you are right. Most of the time I edit grains (interfaces and classes) I remove the build targets. When everything compiles okay I reinsert the targets into the csproj files.

Ø  Is this with 1.0.10 or 1.1.0-beta1 or both?

The problem exists since we are using Orleans, and we started with version 1.0.5. We are using VS 2013 and VS 2015 on different machines; the issue exists on all machines.

Regards

Peter

**Comment by sergeybykov** [comment]
But is it with 1.1.0-beta1 of Orleans where we completely redid codegen with Roslyn or with a previous version where we used CodeDOM?

**Comment by peter-perot** [comment]
The issue is present in VS 2013 and 2015 from Orleans version 1.0.5 to 1.0.10.

I've just tried version 1.1.0-beta1 with VS 2015, and hey: it works!

We have some production code I don't want to update to Orleans 1.1.0-beta1, but I think we can cope with the issue since it will disappear when we switch to the final 1.1.0.

**Comment by sergeybykov** [comment]
Great! Looks like @ReubenBond enable it for you with his Roslyn codegen.

**Comment by peter-perot** [comment]
+1 Mr. @ReubenBond! Thanks a lot.
