### ISSUE TITLE
Observer pattern documentation needs work

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [dotnet/orleans#999]
The observer pattern's [page](http://dotnet.github.io/orleans/Getting-Started-With-Orleans/Observers) in Orleans should be in step by step guides and be much more clear.
the current page is in getting started and is a little sparse. The page for the pattern in design patterns is much more clear but out of date,

I can fix both but wanted permission first for changing the place of the observers and changing the material in it much. I thought there might be reasoning behind it.

**Comment by sergeybykov** [comment]
@ashkan-saeedi-mazdeh Go for it! We wanted to deprecate observers for some time because SMS streams are more powerful. But since observers are still part of the programming model, a better documentation would only help

**Comment by gabikliot** [comment]
This was addressed by https://github.com/dotnet/orleans/pull/1054.
